[msg YOUSUKE_FOE_FOLLOW_START]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3300]Crap, it's an FOE![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3301]That FOE's following us![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3302]Aw crap! It found us![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3303]Watch it, an FOE![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3304]Careful... The FOE's right there![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3305]There's an FOE nearby![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3306]Phew... That could've been nasty.[n][f 1 6 65535][e]

[msg YOUSUKE_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3307]Nice! We lost the FOE![n][f 1 6 65535][e]

[msg YOUSUKE_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3308]Sweet! I think we lost it.[n][f 1 6 65535][e]

[msg YOUSUKE_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3369]Careful, guys.[n][f 1 6 65535][e]

[msg YOUSUKE_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3370]Let's take this slow.[n][f 1 6 65535][e]

[msg YOUSUKE_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3371]Quiet, guys... We don't wanna[n]get spotted.[n][f 1 6 65535][e]

[msg YOUSUKE_DENKISAKU_REACTI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3372]Yeah, probably not happening.[n]Let's stop the electricity first.[n][f 1 6 65535][e]

[msg YOUSUKE_DENKISAKU_REACTI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3373]If we don't turn that off,[n]we're toast.[n][f 1 6 65535][e]

[msg YOUSUKE_DENKISAKU_REACTI_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3374]Where's the switch for the[n]electric gate?[n][f 1 6 65535][e]

[msg YOUSUKE_KYOUHU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3375]No way![n][f 1 6 65535][e]

[msg YOUSUKE_KYOUHU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3376]Whoa![n][f 1 6 65535][e]

[msg YOUSUKE_KYOUHU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3377]Wha―!?[n][f 1 6 65535][e]

[msg YOUSUKE_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3324]Hey! Looks like we can[n]keep going![n][f 1 6 65535][e]

[msg YOUSUKE_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3325]On to the next area![n][f 1 6 65535][e]

[msg YOUSUKE_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3326]C'mon, let's get to the[n]next floor![n][f 1 6 65535][e]

[msg YOUSUKE_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3327]Sweet! A treasure box![n][f 1 6 65535][e]

[msg YOUSUKE_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3328]Hey, that's a treasure box, right?[n][f 1 6 65535][e]

[msg YOUSUKE_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3329]A treasure box! We're cracking[n]that open, right?[n][f 1 6 65535][e]

[msg YOUSUKE_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3330]Looks like something's there...[n][f 1 6 65535][e]

[msg YOUSUKE_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3331]Isn't this place kinda fishy?[n][f 1 6 65535][e]

[msg YOUSUKE_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3332]Keep your eyes open, okay?[n][f 1 6 65535][e]

[msg YOUSUKE_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3333]Huh? There's a switch.[n][f 1 6 65535][e]

[msg YOUSUKE_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3334]A switch... We gonna push it?[n][f 1 6 65535][e]

[msg YOUSUKE_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3335]All right, I found a switch![n][f 1 6 65535][e]

[msg YOUSUKE_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3336]Can't we go through that?[n][f 1 6 65535][e]

[msg YOUSUKE_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3337]Is that a shortcut?[n][f 1 6 65535][e]

[msg YOUSUKE_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3338]Hey, can we take a[n]shortcut here?[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]【パーティの半分以上が死んでいる】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_FOE_WARNING_NEAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3309]Crap, the FOE's still on us.[n][f 1 6 65535][e]

[msg YOUSUKE_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3310]An FOE. Better keep our[n]distance, huh...?[n][f 1 6 65535][e]

[msg YOUSUKE_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3311]Man, it's still after us.[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_HP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3312]Ugh... We can't catch a break...[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3313]...Can't we just go home?[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3314]Crap... Can't take any more...[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_TP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_TP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_PARTY_TP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3315]Don't know if I can go on...[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3316]C'mon, please! I need a[n]pick-me-up![n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3317]Hngh... That hurts...[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3318]Crap, I'm gonna run out of...[n]stamina...[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3319]I can't keep going! I'm outta[n]juice, man![n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3320]Dang it... I can't go on...[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3321]Hah! Piece of cake![n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3322]Let's keep up the pace, guys![n][f 1 6 65535][e]

[msg YOUSUKE_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3323]Man, too easy.[n][f 1 6 65535][e]

[msg YOUSUKE_BATTLE_CHANGE_DU]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_BATTLE_CHANGE_DU_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_BATTLE_CHANGE_DU_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_DUNGEON_]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_DUNGEON__2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_ITEM_90_DUNGEON__3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3360]Let's give it all we got![n][f 1 6 65535][e]

[msg YOUSUKE_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3361]You all ready? Let's go![n][f 1 6 65535][e]

[msg YOUSUKE_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3362]All right! Get pumped, guys![n][f 1 6 65535][e]

[msg YOUSUKE_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3363]We got a mission here![n][f 1 6 65535][e]

[msg YOUSUKE_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3364]I've got this, guys![n][f 1 6 65535][e]

[msg YOUSUKE_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3365]C'mon! Let's keep it up![n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3352]We're just getting started.[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3353]Let's stay focused, guys.[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3354]That's about halfway, huh?[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3355]Okay, we've got a pretty[n]good pace.[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3356]Man, we've come a long way.[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3357]Oh dang! That's pretty much[n]a full map.[n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3358]Sweet! That map looks finished![n][f 1 6 65535][e]

[msg YOUSUKE_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3359]We finished the map![n]Nice work, man.[n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_ALL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3342]Oh, nice![n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3343]That's a pretty good map![n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_KAI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3344]No more getting lost![n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_KAI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3345]Now we know where we[n]need to go![n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_CHANGE_C]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3346]That's got style, man.[n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_CHANGE_C_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3347]It's weird how your personality[n]comes through in this...[n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_DEL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3348]Yeah, good to keep our[n]notes clean.[n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3349]There you go. Just dump the[n]stuff we don't need![n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3350]Gotta keep track of the[n]important stuff.[n][f 1 6 65535][e]

[msg YOUSUKE_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3351]Nice. Looks great![n][f 1 6 65535][e]

[msg YOUSUKE_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3366]C'mon, this way![n][f 1 6 65535][e]

[msg YOUSUKE_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3367]Next room![n][f 1 6 65535][e]

[msg YOUSUKE_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3368]Open sesame! Or something.[n][f 1 6 65535][e]

[msg YOUSUKE_KARITORU_ENCOUNT]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg YOUSUKE_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg YOUSUKE_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ３[n][f 1 6 65535][e]

