[msg KUMA_FOE_FOLLOW_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9300]An FOE's comin' our way![n][f 1 6 65535][e]

[msg KUMA_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9301]Aaaah! FOE closing in![n][f 1 6 65535][e]

[msg KUMA_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9302]Noooo! Not an FOE![n][f 1 6 65535][e]

[msg KUMA_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9303]There's an FOE close by![n]Be beary careful![n][f 1 6 65535][e]

[msg KUMA_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9304]Be careful of that FOE![n][f 1 6 65535][e]

[msg KUMA_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9305]*sniff sniff* This smell...[n]It's an FOE![n][f 1 6 65535][e]

[msg KUMA_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9306]Too slow! We won't get[n]caught by some lousy FOE![n][f 1 6 65535][e]

[msg KUMA_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9307]Phew, we got away.[n][f 1 6 65535][e]

[msg KUMA_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9308]Hrm? Looks like it gave up![n][f 1 6 65535][e]

[msg KUMA_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9369]Tiptoe, tiptoe, stealth mode![n][f 1 6 65535][e]

[msg KUMA_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9370]I feel like we're playing[n]hide and seek.[n][f 1 6 65535][e]

[msg KUMA_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9371]I'm a little nervous...[n][f 1 6 65535][e]

[msg KUMA_DENKISAKU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9372]Touching that sure would[n]be shocking![n][f 1 6 65535][e]

[msg KUMA_DENKISAKU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9373]We won't fall for a trap[n]like this![n][f 1 6 65535][e]

[msg KUMA_DENKISAKU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9374]We'd better stop this before[n]it fries us to a crisp![n][f 1 6 65535][e]

[msg KUMA_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9375]Weeeeee![n][f 1 6 65535][e]

[msg KUMA_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9376]Oh noooo![n][f 1 6 65535][e]

[msg KUMA_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9377]Aaaaaah![n][f 1 6 65535][e]

[msg KUMA_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9324]I spy a way forward![n][f 1 6 65535][e]

[msg KUMA_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9325]Hrmm, I sense we're closing[n]in on the next area![n][f 1 6 65535][e]

[msg KUMA_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9326]I think those'll take us to[n]the next floor![n][f 1 6 65535][e]

[msg KUMA_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9327]Hehe! A treasure box! I bet[n]there's something good inside. [n][f 1 6 65535][e]

[msg KUMA_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9328]A treasure box! Is it from the[n]box office? I'm kidding... Hehe![n][f 1 6 65535][e]

[msg KUMA_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9329]It's a treasure box![n]Ooh! Ooh! What's inside!?[n][f 1 6 65535][e]

[msg KUMA_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9330]*sniff sniff*[n]Something's fishy here...[n][f 1 6 65535][e]

[msg KUMA_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9331]*sniff sniff* I'll bet there's[n]something over here...[n][f 1 6 65535][e]

[msg KUMA_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9332]I'm sensing something fishy[n]around here![n][f 1 6 65535][e]

[msg KUMA_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9333]I found a switch![n][f 1 6 65535][e]

[msg KUMA_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9334]The pressure's on to press[n]the switch! Just joking... Hehe![n][f 1 6 65535][e]

[msg KUMA_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9335]A switch! Can I press it?[n][f 1 6 65535][e]

[msg KUMA_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9336]Oh, there! I think we can get[n]through there![n][f 1 6 65535][e]

[msg KUMA_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9337]Let's take a shortcut![n][f 1 6 65535][e]

[msg KUMA_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9338]I found a shortcut![n]Nothing gets past this nose![n][f 1 6 65535][e]

[msg KUMA_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]【パーティの半分以上が死んでいる】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_FOE_WARNING_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9309]Out of the frying pan,[n]into the FOE![n][f 1 6 65535][e]

[msg KUMA_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9310]It's still chasing us![n][f 1 6 65535][e]

[msg KUMA_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9311]Grrr, that FOE's persistent...[n][f 1 6 65535][e]

[msg KUMA_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_PARTY_HP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_PARTY_HP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_PARTY_HP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9312]I'm pooped...[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9313]Nooo! I think I'm seeing[n]the pearly gates...[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9314]Ohhh... I feel like this is it[n]for this bear...[n][f 1 6 65535][e]

[msg KUMA_PARTY_TP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_PARTY_TP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_PARTY_TP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9315]I'm'a hurtin'! Someone, help![n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9316]At this rate, it won't be long[n]before I'm bear jerky...[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9317]This is way too tough...[n]Heeeeeelp![n][f 1 6 65535][e]

[msg KUMA_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9318]My stamina's low...[n][f 1 6 65535][e]

[msg KUMA_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9319]I can't go on... Pretty boys[n]like me don't live forever...[n][f 1 6 65535][e]

[msg KUMA_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9320]I'm so beary tired...[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9321]Woohoo! We're on a roll![n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9322]We can easily keep going![n][f 1 6 65535][e]

[msg KUMA_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9323]We got this floor![n]Let's keep going![n][f 1 6 65535][e]

[msg KUMA_BATTLE_CHANGE_DUNGE]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_BATTLE_CHANGE_DUNGE_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_BATTLE_CHANGE_DUNGE_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9360]Let's be on our way![n][f 1 6 65535][e]

[msg KUMA_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9361]Everyone, follow me![n][f 1 6 65535][e]

[msg KUMA_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9362]We're off and on our way![n][f 1 6 65535][e]

[msg KUMA_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9363]Let's take care of this[n]special showing![n][f 1 6 65535][e]

[msg KUMA_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9364]Don't worry, I'm sure we'll[n]succeed![n][f 1 6 65535][e]

[msg KUMA_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9365]We'll do it together![n][f 1 6 65535][e]

[msg KUMA_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9352]Whew... We're bear-ly there.[n][f 1 6 65535][e]

[msg KUMA_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9353]Our map's coming along[n]quite nicely.[n][f 1 6 65535][e]

[msg KUMA_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9354]Let's see... It looks like[n]we're halfway there![n][f 1 6 65535][e]

[msg KUMA_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9355]I'd say we're starting to get[n]our bear-ings.[n][f 1 6 65535][e]

[msg KUMA_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9356]I feel like we've made[n]good progress![n][f 1 6 65535][e]

[msg KUMA_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9357]Just a little more,and we're all done![n][f 1 6 65535][e]

[msg KUMA_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9358]Hooray, we finished it![n][f 1 6 65535][e]

[msg KUMA_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9359]Map complete! We made it![n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_ALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9342]Ooh, this is gonna be one[n]fancy map.[n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9343]Oooh, that looks better![n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_KAIDAN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9344]We won't get lost if we know[n]where the stairs are![n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_KAIDAN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9345]*whistle* I'm bear-y impressed![n][f 1 6 65535][e]

[msg KUMA_MAPPING_CHANGE_COLO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9346]Me, me, me! Lemme draw too![n][f 1 6 65535][e]

[msg KUMA_MAPPING_CHANGE_COLO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9347]Oho, you're quite the artist.[n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_DEL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9348]The way you casually throw[n]things away is remarkable![n][f 1 6 65535][e]

[msg KUMA_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9349]Yosuke always says it's good[n]to tidy up.[n][f 1 6 65535][e]

[msg KUMA_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9350]Hm, hm.[n]This'll help us remember.[n][f 1 6 65535][e]

[msg KUMA_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9351]This map's really well drawn![n][f 1 6 65535][e]

[msg KUMA_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9366]Through the door we go![n][f 1 6 65535][e]

[msg KUMA_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9367]Over here![n][f 1 6 65535][e]

[msg KUMA_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9368]Let's gooo![n][f 1 6 65535][e]

[msg KUMA_KARITORU_ENCOUNT_1]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg KUMA_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg KUMA_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ３[n][f 1 6 65535][e]

