[msg MARGARET_FOE_FOLLOW_STAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55300]That's... a Film Ob...[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_STAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55301]There is an FOE in pursuit.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_STAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55302]You are being followed.[n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55303]Stay calm, it's an FOE.[n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55304]It is quite large, but of course,[n]everything looks large to you.[n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55305]Be warned that there is an FOE[n]nearby.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55306]Well done. You've evaded the FOE.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55307]Your escape was a successful one.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55308]Thankfully, it gave up its pursuit of you.[n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55375]If those lights manage to touch you,[n]you'll most certainly be seen.[n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55376]Spotlights have been set up here.[n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55377]Exercise caution once you're past[n]here.[n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55378]To continue, it will be necessary to[n]deactivate the electric gate.[n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55379]That gate is an unfortunate obstacle.[n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55380]There is likely a switch to turn off the[n]power. Hopefully you can locate it.[n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55381]What a strong wind.[n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55382]Mind your footing, everyone.[n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55383]That's quite a breeze![n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55309]Well done. You've found the stairs.[n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55310]Remarkable progress. Now, are you[n]ready to go further?[n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55311]At last, you've located the stairs.[n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55336]That appears to be a treasure box. You[n]plan on opening it, I hope?[n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55337]Oh, a treasure box. What could be[n]inside, I wonder?[n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55338]I do hope that you will find something[n]worthwhile in that treasure box.[n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55339]You may very well wish to take a closer[n]look there.[n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55340]Hm, what could that be?[n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55341]I cannot discern what it is, but there is[n]something ahead.[n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55342]There is a switch up ahead.[n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55343]I wager there is a switch nearby.[n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55344]Do you think you should see what this[n]switch does?[n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55345]That wall is a traversable one.[n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55346]There is a hidden passage in the[n]vicinity.[n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55347]That wall... There is something[n]significant about it.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55387]You're undeniably very injured.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55388]I agree. Perhaps you should head back[n]for now?[n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55389]I can't recommend proceeding any[n]further.[n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55309]The FOE is back. You should remain[n]alert.[n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55310]That is correct, so best keep an eye on[n]your surroundings.[n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55311]An FOE is coming near. Be on guard.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55315]I suggest you withdraw for now.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55316]Unfortunately, the whole team is on[n]the verge of collapse...[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55317]Yes, it would be unwise to proceed any[n]further as is.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55318]Everyone's health is fast approaching[n]a dangerous level.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55319]Truly, you should take a look at the[n]health of your party.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55320]You should make healing everyone[n]your first priority.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55312]Your health and energy are woefully[n]depleted.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55313]Healing really ought to be your first[n]order of business.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55314]Alas, you've lost significant health and[n]energy.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55327]There's a dearth of energy in the party.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55328]I'm growing concerned about your[n]large losses of energy.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55329]It would seem the party is suffering a[n]lack of energy.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55318]You should prioritize healing yourself.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55319]May I suggest restoring your health?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55320]Would you consider restoring your[n]health first?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55324]Is there anything you can do to[n]recover?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55325]I agree. It wouldn't do to be reckless.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55326]Hm, you are wholly out of stamina.[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55390]Some clean-up on your part is[n]necessary.[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55391]You're holding a surplus of items.[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55392]Are you aware that you may leave[n]some items with Theodore?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55330]You seem to be doing well.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55331]There is still someone who appears to[n]be in fine condition.[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55332]You should move on while you still[n]can.[n][f 1 6 65535][e]

[msg MARGARET_BATTLE_CHANGE_D]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg MARGARET_BATTLE_CHANGE_D_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg MARGARET_BATTLE_CHANGE_D_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55390]Consider cleaning up your superfluous[n]collection of items.[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55391]You're holding a surplus of items.[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55392]Are you aware that you may leave[n]some items with Theodore?[n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55369]I shall support you from "behind[n]the camera," as they'd say here.[n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55370]Have you finished your preparations?[n]Then let's be off.[n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55371]Are you prepared?[n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55372]Both of us will provide you[n]support, come what may.[n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55373]If everyone is ready, let us begin.[n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55374]Let's begin the special screening.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55361]You're getting quite adept at this.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55362]In truth, you've only just begun.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55363]It looks like you're about halfway.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55364]You're exploring at a good pace.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55365]There's not much left of this floor.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55366]You've nearly completed this floor. I[n]wish you the best of luck in finishing.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55367]You probably know this floor like the[n]back of your hand by now.[n][f 1 6 65535][e]

[msg MARGARET_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55368]Well done. You've mastered this floor.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_AL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55351]It looks like your map is exceedingly[n]accurate.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_AL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55352]You're exercising sound judgment.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_KA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55353]With that level of skill, you ought to[n]have no fear of getting lost.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_KA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55354]Let us mark these stairs down.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_CHANGE_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55355]I approve of your artistic sensibility.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_CHANGE__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55356]I look forward to seeing the map when[n]it's done.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_DE]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55357]Doing some clean-up?[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_DE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55358]Of course, it's wise to correct mistakes[n]wherever possible.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55359]You mustn't forget important details.[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55360]Writing notes for later reference is an[n]excellent habit.[n][f 1 6 65535][e]

[msg MARGARET_DOOR_OPEN_1]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg MARGARET_DOOR_OPEN_2]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg MARGARET_DOOR_OPEN_3]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55384]The Reaper is here! Stay on guard![n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55385]Remain alert. A powerful enemy is[n]approaching.[n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55386]The Reaper is close. Stay vigilant.[n][f 1 6 65535][e]

