[sel OK top]
[f 0 5 65278][f 2 1]OK[e]

[sel YESNO_SEL top]
[f 0 5 65278][f 2 1]S胤.[e]
[f 0 5 65278][f 2 1]No[e]

[sel YESNO_SEL_TEAM_EDIT_CANC top]
[f 0 5 65278][f 2 1]S胤.[e]
[f 0 5 65278][f 2 1]No[e]

[sel YESNO_SEL_NAVI_EDIT_CANC top]
[f 0 5 65278][f 2 1]S胤.[e]
[f 0 5 65278][f 2 1]No[e]

[sel YESNO_SEL_NAVI_EDIT_EQUI top]
[f 0 5 65278][f 2 1]нелинийныенныенныенныеннныеннныенныениныенниные![e]
[f 0 5 65278][f 2 1]♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪[n]♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪[n]♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪[n]♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪ ♪[e]

[sel YESNO_SEL_REGISTRATION_C top]
[f 0 5 65278][f 2 1]S胤.[e]
[f 0 5 65278][f 2 1]No[e]

[msg EDIT_CANCEL]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Quieres irte sin cambiar la formaci吋n[n]del grupo?[n][f 1 1][e]

[msg LEADER_NOT_EXIST]
[f 0 5 65278][f 2 1]Продилилитиванинаннныйныхнныхнныхныхныхныхниныхниныхиныхниныхнинанных[n][f 1 1][e]

[msg LEADER_NOT_WILD]
[f 0 5 65278][f 2 1]НЕРИТРИНИЛИВАЛЬНЫЙ НЕЛИ НЕЛИТЕНННЫЕННЫЕНИЕНТЕ[n][f 1 1][e]

[msg NAVI_EDIT_CANCEL]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Salir sin cambiar los navegadores?[n][f 1 1][e]

[msg NAVI_EQUIP_SET]
[f 0 5 65278][f 2 1]斡No[n][f 1 1][e]

[msg REGISTRATION_CANCEL]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Salir sin registrarse?[n][f 1 1][e]

