[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23019][f 6 1 2 0 0 4]夷Mm? Espera un segundo, eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 23 1 0 1][f 4 6 19 10 0 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]斡夷Eh?! 斡Pens姻 que el FOE no se mov胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 0]Es posible que solo comience a moverse[n]cuando haya un problema con las luces.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Supongo que podr胤amos llamarlo sistema[n]de seguridad dual... Esto va a ser[n]una molestia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 24008][f 6 1 2 0 0 3]Est茨s diciendo que[f 0 1 2] su comportamiento[n]est茨 relacionado con los interruptores[f 0 1 0]...[n]Esto no es bueno.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]No importa c吋mo funcione, todo lo que[n]tenemos que hacer es enga隠arlo como[n]siempre, 夷no?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Quiero decir, vamos, toda esta seguridad[n]nos est茨 gritando que hay algo[n]importante adelante![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 0 0 1][f 3 1 1 0 0 23073]斡Skull tiene raz吋n! No deber胤amos tener[n]problemas si avanzamos con[n]precauci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Vamos, Joker![n][f 1 3 65535][f 1 1][e]

