[msg FUKA_FOE_FOLLOW_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14300]斡Un FOE se acerca![n][f 1 6 65535][e]

[msg FUKA_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14301]斡Oh no! 斡Un FOE te vio![n][f 1 6 65535][e]

[msg FUKA_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14302]斡Que FOE est茨 en tu cola![n][f 1 6 65535][e]

[msg FUKA_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14303]Hay un FOE cerca... 斡Mant姻n tu guardia[n]arriba![n][f 1 6 65535][e]

[msg FUKA_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14304]斡El FOE est茨 a tu lado![n][f 1 6 65535][e]

[msg FUKA_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14305]Estoy detectando un FOE. 斡Ten cuidado![n][f 1 6 65535][e]

[msg FUKA_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14306]Whew... Parece que sacudiste ese FOE.[n][f 1 6 65535][e]

[msg FUKA_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14307]斡El FOE abandonó la persecución![n][f 1 6 65535][e]

[msg FUKA_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14308]斡Bien! 斡Hemos perdido el FOE![n][f 1 6 65535][e]

[msg FUKA_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14375]斡Cuidado![n][f 1 6 65535][e]

[msg FUKA_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14376]斡No dejes que nada te vea![n][f 1 6 65535][e]

[msg FUKA_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14377]Cuidado por ah胤...[n][f 1 6 65535][e]

[msg FUKA_DENKISAKU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14378]Una puerta el姻ctrica... 夷Tal vez pueda[n]apagarse?[n][f 1 6 65535][e]

[msg FUKA_DENKISAKU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14379]No hay manera alrededor de la puerta. Tenemos[n]que apagarlo.[n][f 1 6 65535][e]

[msg FUKA_DENKISAKU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14380]斡No lo toques, esa puerta es el姻ctrica![n]Nuestra 雨nica esperanza es encontrar su[n]cambio.[n][f 1 6 65535][e]

[msg FUKA_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14381]斡Eeep! 斡Eso es un asqueroso calabozo![n][f 1 6 65535][e]

[msg FUKA_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14382]斡Cuidado![n][f 1 6 65535][e]

[msg FUKA_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14383]斡Tan fuerte viento![n][f 1 6 65535][e]

[msg FUKA_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14333]斡Las escaleras est茨n por delante![n][f 1 6 65535][e]

[msg FUKA_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14334]Las escaleras est茨n aqu胤. 夷Hora de ir a otro[n]piso?[n][f 1 6 65535][e]

[msg FUKA_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14335]夷Eh? 夷Qu姻 pasa? 斡Oh! 斡Es una escalera![n][f 1 6 65535][e]

[msg FUKA_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14336]斡Hay una caja de tesoros por ah胤![n][f 1 6 65535][e]

[msg FUKA_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14337]夷Una caja de tesoros? Veamos qu姻 hay dentro.[n][f 1 6 65535][e]

[msg FUKA_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14338]斡Qu姻 emocionante! 夷Qu姻 podr胤a estar dentro?[n][f 1 6 65535][e]

[msg FUKA_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14339]Hay algo curioso sobre esa pared...[n][f 1 6 65535][e]

[msg FUKA_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14340]Hm... 夷Te importar胤a revisar esa pared?[n][f 1 6 65535][e]

[msg FUKA_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14341]Esa pared... 夷Podr胤as echarle un vistazo m茨s[n]de cerca?[n][f 1 6 65535][e]

[msg FUKA_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14342]Detecto un interruptor cerca.[n][f 1 6 65535][e]

[msg FUKA_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14343]Hay un interruptor cerca de ti. 夷Quieres[n]probarlo?[n][f 1 6 65535][e]

[msg FUKA_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14344]Creo que hay un interruptor en sus alrededores.[n]斡Mira![n][f 1 6 65535][e]

[msg FUKA_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14345]Parece que podr胤as pasar por ah胤.[n][f 1 6 65535][e]

[msg FUKA_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14346]Mira, eso podr胤a ser un atajo.[n][f 1 6 65535][e]

[msg FUKA_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14347]Creo que hay un atajo en esa 茨rea. 夷Ves algo?[n][f 1 6 65535][e]

[msg FUKA_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14387]夷Ves lo bajo que es tu salud? 斡Esto es[n]peligroso![n][f 1 6 65535][e]

[msg FUKA_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14388]夷Y si te atacaron en este estado? 斡Haz algo[n]de curación![n][f 1 6 65535][e]

[msg FUKA_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14389]斡Es tan arriesgado seguir as胤! 夷Qu姻 tal si[n]regresamos?[n][f 1 6 65535][e]

[msg FUKA_FOE_WARNING_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14309]斡El FOE todav胤a te persigue![n][f 1 6 65535][e]

[msg FUKA_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14310]斡Que FOE sigue en la zona![n][f 1 6 65535][e]

[msg FUKA_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14311]斡Prep茨rense! 斡El FOE est茨 dirigiendo su[n]camino![n][f 1 6 65535][e]

[msg FUKA_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14315]斡Estoy preocupado por todos ustedes presionando[n]en tal estado![n][f 1 6 65535][e]

[msg FUKA_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14316]斡Todos est茨n sufriendo de baja salud y[n]energ胤a![n][f 1 6 65535][e]

[msg FUKA_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14317]Algunos de ustedes est茨n muy golpeados.[n]夷Alguien puede hacer algo de curación?[n][f 1 6 65535][e]

[msg FUKA_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14321]斡Por favor, vigila tu salud![n][f 1 6 65535][e]

[msg FUKA_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14322]斡Est茨s en peligro! 斡Necesitas curación![n][f 1 6 65535][e]

[msg FUKA_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14323]斡Todo el equipo necesita curación![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14312]夷Est茨s bien? 斡Deber胤as arreglarte![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14313]斡Cuidado! Health and energy are low![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14314]Est茨s en estado cr胤tico. 斡Tienes que sanar![n][f 1 6 65535][e]

[msg FUKA_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14327]斡Algunos de ustedes apenas cojean! 斡Por favor,[n]descansa![n][f 1 6 65535][e]

[msg FUKA_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14328]Todos se est茨n quedando sin energ胤a...[n][f 1 6 65535][e]

[msg FUKA_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14329]Ahora puede ser un buen momento para volver[n]y descansar.[n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14318]夷Puede reponer alguna salud?[n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14319]Mira tu salud. 斡No es prudente empujarte as胤![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14320]斡Cuidado! 斡Tu salud es baja![n][f 1 6 65535][e]

[msg FUKA_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14324]Me sentir胤a mucho menos ansioso si tomaras[n]un descanso para recuperarte.[n][f 1 6 65535][e]

[msg FUKA_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14325]Te ves tan agotada. 夷Crees que es seguro[n]seguir adelante?[n][f 1 6 65535][e]

[msg FUKA_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14326]Me preocupa que todos ustedes aprendan en[n]este estado.[n][f 1 6 65535][e]

[msg FUKA_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14390]夷Est茨 empezando a pesar tu inventario?[n][f 1 6 65535][e]

[msg FUKA_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14391]Parece que est茨s cerca de llevar tu carga[n]m茨xima.[n][f 1 6 65535][e]

[msg FUKA_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14392]夷Tal vez deber胤as regresar y poner algunos[n]art胤culos en almacenamiento?[n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14330]斡Eso fue incre胤ble![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14331]斡Mantengamos esto arriba![n][f 1 6 65535][e]

[msg FUKA_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14332]Wow, todos se ve胤an tan impresionantes durante[n]esa pelea![n][f 1 6 65535][e]

[msg RISE_FUKA_MAKASETA_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6396]斡Lo tomas de aqu胤, Fuuka-chan![n][f 1 6 65535][e]

[msg RISE_FUKA_MAKASETA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6397]斡Aqu胤 tienes, Fuuka-chan! 斡Ve por ellos![n][f 1 6 65535][e]

[msg RISE_FUKA_MAKASETA_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6398]斡Veamos lo que tienes, Fuuka-chan![n][f 1 6 65535][e]

[msg RISE_FUKA_ANSWER_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14399]斡Entendido! 斡Har姻 lo mejor que pueda![n][f 1 6 65535][e]

[msg RISE_FUKA_ANSWER_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14400]斡Lo tomar姻 de aqu胤, Rise-chan! 斡Vamos, todos![n][f 1 6 65535][e]

[msg RISE_FUKA_ANSWER_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14401]Eso fue una navegación impresionante. 斡Tengo[n]zapatos grandes para llenar![n][f 1 6 65535][e]

[msg FUTABA_FUKA_MAKASETA_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26399]斡Te lo llevo, Fuuka![n][f 1 6 65535][e]

[msg FUTABA_FUKA_MAKASETA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26400]斡Fuuka est茨 en la escena![n][f 1 6 65535][e]

[msg FUTABA_FUKA_MAKASETA_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26401]斡Cambia a Fuuka![n][f 1 6 65535][e]

[msg FUTABA_FUKA_ANSWER_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14402]Puedes ir a descansar bien. 斡Lo tengo![n][f 1 6 65535][e]

[msg FUTABA_FUKA_ANSWER_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14403]Har姻 apoyo desde aqu胤. 斡Hag茨moslo![n][f 1 6 65535][e]

[msg FUTABA_FUKA_ANSWER_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14404]斡Gran trabajo, Oracle! 斡Me har姻 cargo de[n]aqu胤![n][f 1 6 65535][e]

[msg FUKA_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14390]夷Est茨 empezando a pesar tu inventario?[n][f 1 6 65535][e]

[msg FUKA_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14391]Parece que est茨s cerca de llevar tu carga[n]m茨xima.[n][f 1 6 65535][e]

[msg FUKA_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14392]夷Tal vez deber胤as regresar y poner algunos[n]art胤culos en almacenamiento?[n][f 1 6 65535][e]

[msg FUKA_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14369]斡Buena suerte, todos![n][f 1 6 65535][e]

[msg FUKA_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14370]斡Recuerde, no hay necesidad de entrar en el[n]suelo![n][f 1 6 65535][e]

[msg FUKA_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14371]Estar姻 aqu胤, haciendo todo lo posible para[n]apoyarte![n][f 1 6 65535][e]

[msg FUKA_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14372]斡Hag茨moslo mejor![n][f 1 6 65535][e]

[msg FUKA_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14373]斡Har姻 todo lo posible para brindarte apoyo![n][f 1 6 65535][e]

[msg FUKA_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14374]斡Pueden hacerlo, chicos![n][f 1 6 65535][e]

[msg FUKA_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14361]Todav胤a hay una manera de ir. No te presiones[n]demasiado.[n][f 1 6 65535][e]

[msg FUKA_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14362]Vigila tu salud.[n][f 1 6 65535][e]

[msg FUKA_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14363]El mapa est茨 a mitad de camino. 斡No pares[n]ahora![n][f 1 6 65535][e]

[msg FUKA_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14364]El mapa se ve genial. 斡Eres un explorador[n]intr姻pido![n][f 1 6 65535][e]

[msg FUKA_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14365]Sólo un poco m茨s, y este piso est茨 mapeado![n][f 1 6 65535][e]

[msg FUKA_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14366]斡Est茨s a pocos pasos de terminar tu mapa![n][f 1 6 65535][e]

[msg FUKA_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14367]斡Considera este piso hecho![n][f 1 6 65535][e]

[msg FUKA_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14368]斡Ahora conoces este piso como la parte[n]posterior de tu mano![n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_ALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14351]斡Buena ubicación![n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14352]Tengo que decir... 斡Eres un gran cartógrafo![n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_KAIDAN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14353]Buena idea... Es importante saber dónde est茨n[n]las escaleras.[n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_KAIDAN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14354]斡Ahora nunca nos perderemos cuando busquemos[n]las escaleras![n][f 1 6 65535][e]

[msg FUKA_MAPPING_CHANGE_COLO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14355]斡Estamos llenando el mapa r茨pido! Y muy[n]colorida, tambi姻n![n][f 1 6 65535][e]

[msg FUKA_MAPPING_CHANGE_COLO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14356]斡Oh wow, incluso est茨s de color![n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_DEL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14357]斡Seguro que prestas atención a los detalles![n][f 1 6 65535][e]

[msg FUKA_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14358]Buen pensamiento... No queremos que nuestro[n]mapa se arruine.[n][f 1 6 65535][e]

[msg FUKA_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14359]斡Le胤ste mi mente![n][f 1 6 65535][e]

[msg FUKA_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14360]斡Siempre es prudente tomar notas![n][f 1 6 65535][e]

[msg FUKA_DOOR_OPEN_1]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg FUKA_DOOR_OPEN_2]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg FUKA_DOOR_OPEN_3]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg FUKA_KARITORU_ENCOUNT_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14384]Estoy captando una señal... 斡Cuidado, es el[n]Segador![n][f 1 6 65535][e]

[msg FUKA_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14385]斡Viene el Segador! 斡Ten cuidado![n][f 1 6 65535][e]

[msg FUKA_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14386]Esta lectura... 斡Eek, es el Segador![n]斡Cuidado![n][f 1 6 65535][e]

