[msg MITURU_FOE_FOLLOW_START_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13300]斡Hemos sido detectados por un FOE![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_START__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13301]Tsk... 斡Un FOE nos ha encerrado![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_START__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13302]斡Nos est茨 siguiendo un FOE![n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13303]Hay un FOE cerca...[n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13304]Un FOE. As胤 que est茨n aqu胤, tambi姻n.[n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13305]Es un FOE. 斡Atenci吋n![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13306]Parece que hemos eludido a ese FOE.[n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13307]Bien... Parece que se rindi吋.[n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13308]Nuestro escape est茨 asegurado...[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13369]Ten cuidado.[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13370]Qu姻 trampa tan inconveniente.[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13371]Aseg雨rate de dar prioridad al sigilo...[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13372]Aconsejo no tocar eso.[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13373]Podemos continuar despu姻s de apagar la energ胤a.[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13374]Apagar la electricidad ser胤a la medida prudente.[n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13375]斡Ngh...![n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13376]夷Qu姻?[n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13377]夷Eh, el viento?[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13324]Podemos seguir adelante. 夷Alguna objeci吋n?[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13325]Hay una escalera all胤.[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13326]Escaleras... El siguiente piso est茨[n]adelante.[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13327]Una cofre del tesoro... 夷Vamos?[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13328]Hm. Hay una cofre del tesoro.[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13329]Hay un tesoro adelante.[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13330]夷Hm...? 夷Qu姻 es eso?[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13331]Algo me est茨 molestando. 夷Te importa si[n]investigamos?[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13332]夷Qu姻 es eso? Echemos un vistazo m茨s de cerca.[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13333]夷Hm? 夷Esto es... un interruptor?[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13334]Mira. Hay un interruptor.[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13335]夷Un interruptor...? 夷Cu茨l es nuestro movimiento?[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13336]夷Hm? Parece que podemos pasar por all胤.[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13337]Bien. Esto deber胤a hacer un buen atajo.[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13338]Mira. Eso deber胤a servir como atajo.[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13309]斡No te relajes todav胤a! 斡El FOE est茨 casi[n]sobre nosotros![n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13310]Ese FOE todav胤a nos persigue...[n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13311]斡Mantente alerta! Ese FOE sigue aqu胤.[n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_1]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_2]
[f 0 5 65278][f 2 1]◆CONT威CTELO 10% DE LA VISTA[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_3]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13312]Ngh... Estoy bien... Puedo... seguir... adelante...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13313]夷C吋mo pudo pasar esto...? Fui demasiado descuidada...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13314]No quiero ser una carga, pero...[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13315]Ngh... Lo siento, 夷podr胤a molestarte con algo de curaci吋n...?[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13316]Ngh... Tengo bastante poca salud...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13317]Mis disculpas, pero estoy cerca de mi l胤mite...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13318]Tengo dificultades para mantenerme...[n]Disculpas...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13319]La tensi吋n me est茨 afectando...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13320]Lo siento... 夷Podemos descansar un momento?[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]◆Recibir 90% escrito[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13321]夷Mantendremos este impulso, espero?[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13322]Otro testimonio de nuestro crecimiento.[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13323]斡C'est magnifique! Biena pelea.[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13360]Dejaremos las decisiones en tus manos.[n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13361]斡Vamos![n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13362]斡Que comience nuestra exploraci吋n![n][f 1 6 65535][e]

[msg MITURU_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13363]Vamos.[n][f 1 6 65535][e]

[msg MITURU_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13364]斡Ahora, a la misi吋n![n][f 1 6 65535][e]

[msg MITURU_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13365]Empecemos.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13352]Apenas hemos comenzado.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13353]Avancemos lentamente, pero seguros.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13354]Espero que las responsabilidades no sean una carga. 夷Est茨s cansado?[n][f 1 6 65535][e]

[msg MITURU_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13355]Hemos cubierto una buena parte de este piso.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13356]Hemos caminado bastante. 夷C吋mo est茨 la[n]salud de todos?[n][f 1 6 65535][e]

[msg MITURU_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13357]Estoy empezando a ver el panorama completo...[n][f 1 6 65535][e]

[msg MITURU_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13358]Me atrevo a decir que no volveremos a perdernos[n]en este piso.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13359]Veo que ten胤amos raz吋n al ponerte a cargo.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_ALL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13342]S胤, todo parece familiar.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_ALL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13343]Ah, s胤... Lo recuerdo.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_KAID]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13344]Ahora siempre sabremos el camino a las[n]escaleras.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_KAID_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13345]As胤 que esto conduce al siguiente piso,[n]夷verdad?[n][f 1 6 65535][e]

[msg MITURU_MAPPING_CHANGE_CO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13346]夷Oh...? Tienes buen gusto para eso.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_CHANGE_CO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13347]Una idea novedosa.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_DEL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13348]Casi refrescante.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_DEL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13349]Una haza隠a ejemplar de cartograf胤a.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13350]Bien. Ahora no lo olvidar茨s.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13351]Eso deber胤a ser 雨til.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13366]Procedamos.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13367]Ahora, adelante.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13368]Ven.[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT_]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT__2]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT__3]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay 姻xito[n][f 1 6 65535][e]

