[msg MITURU_FOE_FOLLOW_START_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13300]斡Hemos sido detectados por un FOE![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_START__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13301]Tsk... 斡Un FOE nos ha encerrado![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_START__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13302]斡Estamos siendo rastreados por un FOE![n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13303]Hay un FOE cerca...[n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13304]Un FOE. As胤 que est茨n aqu胤, tambi姻n.[n][f 1 6 65535][e]

[msg MITURU_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13305]Es un FOE. 斡Atenci吋n![n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13306]Parece que hemos eludido a ese FOE.[n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13307]Bien... Parece que se rindi吋.[n][f 1 6 65535][e]

[msg MITURU_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13308]Nuestro escape est茨 asegurado...[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13369]Ten cuidado.[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13370]Qu姻 trampa inconveniente.[n][f 1 6 65535][e]

[msg MITURU_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13371]Aseg雨rate de priorizar el robo...[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13372]Aconsejo no tocar eso.[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13373]Podemos proceder despu姻s de apagar el poder.[n][f 1 6 65535][e]

[msg MITURU_DENKISAKU_REACTIO_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13374]Cerrar la electricidad ser胤a el curso prudente.[n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13375]Ngh...![n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13376]夷Qu姻?[n][f 1 6 65535][e]

[msg MITURU_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13377]夷El viento?[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13324]Podemos seguir adelante. 夷Alguna objeci吋n?[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13325]Hay una escalera all胤.[n][f 1 6 65535][e]

[msg MITURU_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13326]Escaleras... El siguiente piso est茨 por delante.[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13327]Una caja de tesoros... 夷Vamos?[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13328]Hm. Hay una caja de tesoros.[n][f 1 6 65535][e]

[msg MITURU_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13329]Hay un tesoro por delante.[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13330]夷Hm...? 夷Qu姻 es eso?[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13331]Algo me est茨 molestando. 夷Le importa si[n]investigamos?[n][f 1 6 65535][e]

[msg MITURU_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13332]夷Qu姻 es eso? Echemos un vistazo m茨s de cerca.[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13333]夷Hm? 夷Esto es... un interruptor?[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13334]Mira. Hay un interruptor.[n][f 1 6 65535][e]

[msg MITURU_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13335]夷Un cambio...? 夷Cu茨l es nuestro movimiento?[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13336]夷Hm? Parece que podemos pasar por all胤.[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13337]Bien. Esto deber胤a hacer un buen atajo.[n][f 1 6 65535][e]

[msg MITURU_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13338]Mira. Eso deber胤a servir como atajo.[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13309]斡No te relajes todav胤a! 斡El FOE est茨[n]casi sobre nosotros![n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13310]Que FOE sigue en persecuci吋n...[n][f 1 6 65535][e]

[msg MITURU_FOE_WARNING_NEAR__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13311]斡Mant姻nganse afilados! 斡Que FOE sigue aqu胤![n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_1]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_2]
[f 0 5 65278][f 2 1]◆CONT威CTELO 10% DE LA VISTA[n][f 1 6 65535][e]

[msg MITURU_PARTY_HP10_3]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13312]Estoy bien... Puedo seguir... yendo...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13313]夷C吋mo sucedi吋 esto? Estaba muy descuidado...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13314]No quiero ser una responsabilidad, pero...[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_PARTY_TP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13315]Lo siento, 夷pero podr胤a molestarte por[n]algo de curaci吋n?[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13316]Estoy bastante bajo en salud...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13317]Disculpa, pero estoy cerca de mi l胤mite...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13318]Tengo dificultades para mantenerme... Disculpas...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13319]La tensi吋n me est茨 afectando...[n][f 1 6 65535][e]

[msg MITURU_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13320]Lo siento... 夷Podemos descansar un momento?[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]◆Recibir 90% escrito[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13321]Mantendremos este impulso, espero?[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13322]Otro testamento para nuestro crecimiento.[n][f 1 6 65535][e]

[msg MITURU_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13323]斡C'est magnifique! Bien peleado.[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg MITURU_BATTLE_CHANGE_DUN_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13360]Te dejaremos la toma de decisiones.[n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13361]斡Vamos![n][f 1 6 65535][e]

[msg MITURU_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13362]斡Que comience nuestra exploraci吋n![n][f 1 6 65535][e]

[msg MITURU_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13363]Vamos.[n][f 1 6 65535][e]

[msg MITURU_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13364]斡Ahora, a la misi吋n![n][f 1 6 65535][e]

[msg MITURU_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13365]Empecemos, todos.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13352]Acabamos de empezar.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13353]Procedamos lentamente, pero seguramente.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13354]Espero que las responsabilidades no[n]sean una carga. 夷Est茨s cansada?[n][f 1 6 65535][e]

[msg MITURU_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13355]Hemos cubierto una buena parte de este piso.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13356]Hemos caminado bastante lejos. 夷C吋mo[n]est茨 la salud de todos?[n][f 1 6 65535][e]

[msg MITURU_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13357]Estoy empezando a ver el cuadro completo...[n][f 1 6 65535][e]

[msg MITURU_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13358]Me atrevo a decir que no volveremos a[n]perdernos en este piso.[n][f 1 6 65535][e]

[msg MITURU_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13359]Veo que ten胤amos raz吋n para ponerte a cargo.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_ALL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13342]S胤, todo parece familiar.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_ALL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13343]Ah, s胤... Lo recuerdo.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_KAID]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13344]Ahora siempre sabremos el camino a las escaleras.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_KAID_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13345]As胤 que esto conduce al siguiente piso, 夷verdad?[n][f 1 6 65535][e]

[msg MITURU_MAPPING_CHANGE_CO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13346]夷Oh...? Tienes buen sentido para esto.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_CHANGE_CO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13347]Una idea novedosa.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_DEL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13348]Casi refrescante.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_ICON_DEL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13349]Una haza隠a ejemplar de cartograf胤a.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13350]Bien. Ahora no lo olvidar茨s.[n][f 1 6 65535][e]

[msg MITURU_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13351]Eso deber胤a ser 雨til.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13366]Procedamos.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13367]Ahora, adelante.[n][f 1 6 65535][e]

[msg MITURU_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13368]Ven.[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT_]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT__2]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg MITURU_KARITORU_ENCOUNT__3]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay 姻xito[n][f 1 6 65535][e]

