[msg AKECHI_FOE_FOLLOW_START_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28300]Ya viene, no te asustes.[n][f 1 6 65535][e]

[msg AKECHI_FOE_FOLLOW_START__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28301]Un FOE... C茨lmate.[n][f 1 6 65535][e]

[msg AKECHI_FOE_FOLLOW_START__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28302]斡El FOE se acerca![n][f 1 6 65535][e]

[msg AKECHI_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28303]Estar茨 bien. No perdamos la calma.[n][f 1 6 65535][e]

[msg AKECHI_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28304]Est茨 justo delante.[n][f 1 6 65535][e]

[msg AKECHI_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28305]Curses, est茨 ah胤...![n][f 1 6 65535][e]

[msg AKECHI_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28306]Qu姻 alivio escapar.[n][f 1 6 65535][e]

[msg AKECHI_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28307]Parece que lo superamos.[n][f 1 6 65535][e]

[msg AKECHI_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28308]Parece que no nos sigue.[n][f 1 6 65535][e]

[msg AKECHI_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28369]Est茨 bien. Estoy seguro de que estar茨s bien.[n][f 1 6 65535][e]

[msg AKECHI_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28370]En realidad es un simple truco.[n][f 1 6 65535][e]

[msg AKECHI_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28371]Mantengamos la calma.[n][f 1 6 65535][e]

[msg AKECHI_DENKISAKU_REACTIO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28372]Debemos encontrar la manera de detenerlo.[n][f 1 6 65535][e]

[msg AKECHI_DENKISAKU_REACTIO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28373]Darn... una puerta el姻ctrica...[n][f 1 6 65535][e]

[msg AKECHI_DENKISAKU_REACTIO_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28374]Tal vez haya una forma de hacerlo.[n][f 1 6 65535][e]

[msg AKECHI_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28375]Ngh...![n][f 1 6 65535][e]

[msg AKECHI_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28376]Whoa...![n][f 1 6 65535][e]

[msg AKECHI_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28377]斡Una r茨faga![n][f 1 6 65535][e]

[msg AKECHI_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28324]Parece que podemos proceder.[n][f 1 6 65535][e]

[msg AKECHI_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28325]Encantador, hacia el siguiente 茨rea.[n][f 1 6 65535][e]

[msg AKECHI_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28326]夷Cu茨l es el plan? 夷Para seguir?[n][f 1 6 65535][e]

[msg AKECHI_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28327]Una caja de tesoros. Ser姻 generoso y te[n]lo permitir姻.[n][f 1 6 65535][e]

[msg AKECHI_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28328]Una caja de tesoros, 夷eh? 夷Por qu姻 no[n]intentas abrirla?[n][f 1 6 65535][e]

[msg AKECHI_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28329]斡He aqu胤! 斡Una caja de tesoros![n][f 1 6 65535][e]

[msg AKECHI_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28330]夷Hm? 夷Eso es...?[n][f 1 6 65535][e]

[msg AKECHI_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28331]Estas paredes no enga隠an mis ojos.[n][f 1 6 65535][e]

[msg AKECHI_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28332]夷Por qu姻 no lo revisamos?[n][f 1 6 65535][e]

[msg AKECHI_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28333]Un interruptor... Lo entiendo.[n][f 1 6 65535][e]

[msg AKECHI_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28334]Hay un interruptor aqu胤.[n][f 1 6 65535][e]

[msg AKECHI_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28335]Un interruptor... 夷Qu姻 propones que hagamos?[n][f 1 6 65535][e]

[msg AKECHI_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28336]Parece que podemos pasar.[n][f 1 6 65535][e]

[msg AKECHI_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28337]Es bueno saber que tenemos un atajo aqu胤.[n][f 1 6 65535][e]

[msg AKECHI_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28338]Quiz茨 podamos pasar. 夷Qu姻 sugieres?[n][f 1 6 65535][e]

[msg AKECHI_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg AKECHI_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg AKECHI_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg AKECHI_FOE_WARNING_NEAR_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28309]Es bastante persistente.[n][f 1 6 65535][e]

[msg AKECHI_FOE_WARNING_NEAR__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28310]No nos deja tomar un descanso.[n][f 1 6 65535][e]

[msg AKECHI_FOE_WARNING_NEAR__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28311]El FOE todav胤a nos persigue.[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HP10_1]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HP10_2]
[f 0 5 65278][f 2 1]◆CONT威CTELO 10% DE LA VISTA[n][f 1 6 65535][e]

[msg AKECHI_PARTY_HP10_3]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28312]He sufrido demasiado da隠o. Necesito refuerzos.[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28313]Estoy en mal estado. 夷Un poco de ayuda, por favor?[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28314]Seguir adelante podr胤a ser imprudente...[n][f 1 6 65535][e]

[msg AKECHI_PARTY_TP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_PARTY_TP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_PARTY_TP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28315]夷Crees que podemos curar algo de tiempo[n]en un futuro cercano?[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28316]Estoy m茨s da隠ada de lo que pens姻...[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28317]Esto no es nada, lo juro.[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28318]Estoy vencido... Creo... Podr胤a desmayarme.[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28319]Quiz茨 podamos descansar...[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28320]Parece que ser茨 una batalla de resistencia...[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28390]【justificadamente[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28391]◆Recibir 90% escrito[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28392]【justificadamente[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28321]Todo el mundo est茨 bien.[n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28322]斡Estamos sacando algunas verdaderas haza隠as![n][f 1 6 65535][e]

[msg AKECHI_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28323]Siempre puedes confiar en m胤.[n][f 1 6 65535][e]

[msg AKECHI_BATTLE_CHANGE_DUN]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg AKECHI_BATTLE_CHANGE_DUN_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg AKECHI_BATTLE_CHANGE_DUN_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg AKECHI_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg AKECHI_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28360]斡Empecemos![n][f 1 6 65535][e]

[msg AKECHI_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28361]Tengo fe completa que podemos hacerlo.[n][f 1 6 65535][e]

[msg AKECHI_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28362]Todos est姻n alertas.[n][f 1 6 65535][e]

[msg AKECHI_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28363]Empecemos la misi吋n.[n][f 1 6 65535][e]

[msg AKECHI_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28364]Veamos de qu姻 se trata este lugar.[n][f 1 6 65535][e]

[msg AKECHI_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28365]Ahora, que comience nuestra noble exploraci吋n.[n][f 1 6 65535][e]

[msg AKECHI_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28352]Despacio, pero seguro...[n][f 1 6 65535][e]

[msg AKECHI_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28353]El mapa de Roma no fue dibujado en un d胤a.[n][f 1 6 65535][e]

[msg AKECHI_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28354]斡A mitad![n][f 1 6 65535][e]

[msg AKECHI_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28355]Est茨 resultando bastante bueno.[n][f 1 6 65535][e]

[msg AKECHI_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28356]Debemos proceder lentamente y cuidadosamente.[n][f 1 6 65535][e]

[msg AKECHI_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28357]斡Ya terminamos![n][f 1 6 65535][e]

[msg AKECHI_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28358]斡Terminamos! 斡Parece fant茨stico![n][f 1 6 65535][e]

[msg AKECHI_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28359]斡Felicidades, terminamos con este piso![n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_ALL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28342]S胤, sin duda.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_ALL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28343]Parece excelente.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_KAID]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28344]Bien hecho.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_KAID_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28345]斡Eso es perfecto![n][f 1 6 65535][e]

[msg AKECHI_MAPPING_CHANGE_CO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28346]Ah, cambiar los colores, 夷eh?[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_CHANGE_CO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28347]Debes ser el tipo exigente.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_DEL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28348]Debo admitir que creo que eso tambi姻n[n]es innecesario.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_ICON_DEL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28349]Oh, eso es atrevido de ti.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28350]Aha, ahora es una gran idea.[n][f 1 6 65535][e]

[msg AKECHI_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28351]Te da paz mental, marcando el mapa, 夷no?[n][f 1 6 65535][e]

[msg AKECHI_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28366]斡Por aqu胤![n][f 1 6 65535][e]

[msg AKECHI_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28367]夷Vamos?[n][f 1 6 65535][e]

[msg AKECHI_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28368]Vamos.[n][f 1 6 65535][e]

[msg AKECHI_KARITORU_ENCOUNT_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28384]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg AKECHI_KARITORU_ENCOUNT__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28385]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg AKECHI_KARITORU_ENCOUNT__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28386]? ? Todav胤a no hay 姻xito[n][f 1 6 65535][e]

