[msg ANN_FOE_FOLLOW_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22300]斡Viene un FOE![n][f 1 6 65535][e]

[msg ANN_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22301]Eeep... esa cosa nos est茨 mirando![n][f 1 6 65535][e]

[msg ANN_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22302]夷Eh? 夷Nos vio?[n][f 1 6 65535][e]

[msg ANN_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22303]斡Es un FOE![n][f 1 6 65535][e]

[msg ANN_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22304]夷Un FOE? 斡Esto es malo![n][f 1 6 65535][e]

[msg ANN_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22305]Hey, es un FOE, ya sabes! 斡Tengo que[n]tener cuidado![n][f 1 6 65535][e]

[msg ANN_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22306]Estamos bien... Supongo que lo perdimos.[n][f 1 6 65535][e]

[msg ANN_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22307]Parece que finalmente se rindi吋.[n][f 1 6 65535][e]

[msg ANN_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22308]斡S胤! 斡Nos escapamos![n][f 1 6 65535][e]

[msg ANN_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22369]斡No queremos quedar atrapados![n][f 1 6 65535][e]

[msg ANN_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22370]Muy f茨cil ahora...[n][f 1 6 65535][e]

[msg ANN_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22371]Estoy sudando por todas partes. 斡Y no[n]porque est姻 caliente![n][f 1 6 65535][e]

[msg ANN_DENKISAKU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22372]Puedo sentir el pelo en la parte[n]posterior de mi cuello de pie...[n][f 1 6 65535][e]

[msg ANN_DENKISAKU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22373]斡No queremos tocar eso![n][f 1 6 65535][e]

[msg ANN_DENKISAKU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22374]Whoa... Toda esta electricidad es rid胤cula...[n][f 1 6 65535][e]

[msg ANN_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22375]斡Yipe! 斡Viento![n][f 1 6 65535][e]

[msg ANN_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22376]Ugh! 夷En serio? 斡Mi pelo![n][f 1 6 65535][e]

[msg ANN_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22377]夷D吋nde estamos, un tornado?[n][f 1 6 65535][e]

[msg ANN_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22324]斡Podemos pasar por aqu胤![n][f 1 6 65535][e]

[msg ANN_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22325]斡Oh! 斡Un camino![n][f 1 6 65535][e]

[msg ANN_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22326]Hey, vamos a comprobarlo![n][f 1 6 65535][e]

[msg ANN_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22327]斡Tesoro![n][f 1 6 65535][e]

[msg ANN_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22328]斡Un tesoro! 斡Claro que s胤![n][f 1 6 65535][e]

[msg ANN_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22329]斡Espio algo bueno![n][f 1 6 65535][e]

[msg ANN_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22330]Parece sospechoso, 夷no crees?[n][f 1 6 65535][e]

[msg ANN_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22331]夷Quieres revisarlo?[n][f 1 6 65535][e]

[msg ANN_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22332]斡Tiene que haber algo aqu胤![n][f 1 6 65535][e]

[msg ANN_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22333]Podemos cambiar este interruptor gratis, 夷verdad?[n][f 1 6 65535][e]

[msg ANN_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22334]斡Oh! 斡Hay un interruptor![n][f 1 6 65535][e]

[msg ANN_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22335]夷Deber胤amos cambiar este interruptor?[n][f 1 6 65535][e]

[msg ANN_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22336]斡Ah胤! 斡Parece un atajo![n][f 1 6 65535][e]

[msg ANN_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22337]Tal vez usemos esto como un atajo, 夷s胤?[n][f 1 6 65535][e]

[msg ANN_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22338]Oye, tal vez podamos pasar por ah胤.[n][f 1 6 65535][e]

[msg ANN_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg ANN_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg ANN_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg ANN_FOE_WARNING_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22309]斡Hombre! 夷Cu茨nto m茨s va a perseguirnos?[n][f 1 6 65535][e]

[msg ANN_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22310]斡Viene el FOE! 斡Vete![n][f 1 6 65535][e]

[msg ANN_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22311]夷En serio? 夷Cu茨l es su problema?[n][f 1 6 65535][e]

[msg ANN_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_PARTY_HP10_1]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg ANN_PARTY_HP10_2]
[f 0 5 65278][f 2 1]◆CONT威CTELO 10% DE LA VISTA[n][f 1 6 65535][e]

[msg ANN_PARTY_HP10_3]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg ANN_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22312]Lo siento... No puedo seguir...[n][f 1 6 65535][e]

[msg ANN_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22313]Hey, 夷crees que podemos conseguir un poco de R?[n][f 1 6 65535][e]

[msg ANN_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22314]Creo que esto es lo m茨s lejos que puedo ir...[n][f 1 6 65535][e]

[msg ANN_PARTY_TP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_PARTY_TP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_PARTY_TP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg ANN_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22315]Mierda... esto no es bueno.[n][f 1 6 65535][e]

[msg ANN_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22316]*groan* Qu姻 pena...[n][f 1 6 65535][e]

[msg ANN_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22317]Creo que he llegado a mi l胤mite...[n][f 1 6 65535][e]

[msg ANN_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22318]As胤 que... cansado...[n][f 1 6 65535][e]

[msg ANN_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22319]Por favor, d姻jame descansar un poco...[n][f 1 6 65535][e]

[msg ANN_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22320]Estoy totalmente empapado...[n][f 1 6 65535][e]

[msg ANN_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg ANN_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]◆Recibir 90% escrito[n][f 1 6 65535][e]

[msg ANN_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg ANN_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22321]斡S胤! 斡Muy bien![n][f 1 6 65535][e]

[msg ANN_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22322]夷Todos siguen bien?[n][f 1 6 65535][e]

[msg ANN_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22323]夷Por qu姻 parar ahora?[n][f 1 6 65535][e]

[msg ANN_BATTLE_CHANGE_DUNGEO]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg ANN_BATTLE_CHANGE_DUNGEO_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg ANN_BATTLE_CHANGE_DUNGEO_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg ANN_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg ANN_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg ANN_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg ANN_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22360]斡Empecemos![n][f 1 6 65535][e]

[msg ANN_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22361]斡Es hora de explorar![n][f 1 6 65535][e]

[msg ANN_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22362]斡Vamos![n][f 1 6 65535][e]

[msg ANN_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22363]斡Hag茨moslo, chicos![n][f 1 6 65535][e]

[msg ANN_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22364]夷Est茨s listo?[n][f 1 6 65535][e]

[msg ANN_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22365]斡Vamos, vamos, vamos![n][f 1 6 65535][e]

[msg ANN_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22352]斡Todav胤a estoy bien para ir![n][f 1 6 65535][e]

[msg ANN_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22353]斡Vamos a darles el infierno![n][f 1 6 65535][e]

[msg ANN_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22354]A mitad de ah胤.[n][f 1 6 65535][e]

[msg ANN_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22355]斡A mitad de camino![n][f 1 6 65535][e]

[msg ANN_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22356]夷Ya casi terminamos?[n][f 1 6 65535][e]

[msg ANN_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22357]斡Un poco m茨s![n][f 1 6 65535][e]

[msg ANN_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22358]斡Hurra! 斡Terminamos![n][f 1 6 65535][e]

[msg ANN_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22359]斡S胤! 斡Todo listo![n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_ALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22342]斡Qu姻 bien![n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22343]斡Mira bien![n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_KAIDAN_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22344]斡Ah胤 est茨 el lugar![n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_KAIDAN__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22345]斡Parece importante![n][f 1 6 65535][e]

[msg ANN_MAPPING_CHANGE_COLOR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22346]斡Me gusta eso![n][f 1 6 65535][e]

[msg ANN_MAPPING_CHANGE_COLOR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22347]斡Se ve bien! 夷M茨s color, incluso?[n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_DEL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22348]斡As胤 se organiza![n][f 1 6 65535][e]

[msg ANN_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22349]S胤, deber胤amos deshacernos de lo que no[n]necesitamos.[n][f 1 6 65535][e]

[msg ANN_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22350]斡Aseg雨rese de tomar notas![n][f 1 6 65535][e]

[msg ANN_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22351]Justo lo que esperar胤a de ti.[n][f 1 6 65535][e]

[msg ANN_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22366]斡Muy bien, vamos![n][f 1 6 65535][e]

[msg ANN_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22367]斡Por aqu胤![n][f 1 6 65535][e]

[msg ANN_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22368]斡Empecemos un poco de maldad![n][f 1 6 65535][e]

[msg ANN_KARITORU_ENCOUNT_1]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg ANN_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg ANN_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay 姻xito[n][f 1 6 65535][e]

