[msg P3_HERO2_FOE_FOLLOW_STAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19300]Parece que el FOE nos ha notado![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_FOLLOW_STAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19301]斡Un FOE viene tras nosotros![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_FOLLOW_STAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19302]斡Cuidado! 斡Un FOE nos persigue![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19303]斡Hay un FOE cerca![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19304]斡El FOE nos vio![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19305]Drat, hay un FOE...[n][f 1 6 65535][e]

[msg P3_HERO2_FOE_FOLLOW_END_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19306]Parece que el FOE nos dej吋.[n][f 1 6 65535][e]

[msg P3_HERO2_FOE_FOLLOW_END__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19307]斡El FOE ya no viene![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_FOLLOW_END__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19308]Nos escapamos... Qu姻 alivio.[n][f 1 6 65535][e]

[msg P3_HERO2_KANSI_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19369]斡Todos est茨n en alerta![n][f 1 6 65535][e]

[msg P3_HERO2_KANSI_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19370]Ser茨 un problema si nos encuentran. 斡Ten cuidado![n][f 1 6 65535][e]

[msg P3_HERO2_KANSI_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19371]斡No puedes atraparnos![n][f 1 6 65535][e]

[msg P3_HERO2_DENKISAKU_REACT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19372]Si no apagamos la electricidad, nos[n]quemaremos a un crujiente.[n][f 1 6 65535][e]

[msg P3_HERO2_DENKISAKU_REACT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19373]Una puerta el姻ctrica, eh... 斡Parece que[n]tenemos que apagar la electricidad primero![n][f 1 6 65535][e]

[msg P3_HERO2_DENKISAKU_REACT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19374]斡Cuidado! 斡Hay una puerta el姻ctrica![n][f 1 6 65535][e]

[msg P3_HERO2_KYOUHU_REACTION]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19375]斡Aaaaaaahhhh![n][f 1 6 65535][e]

[msg P3_HERO2_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19376]斡Eek![n][f 1 6 65535][e]

[msg P3_HERO2_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19377]夷De ninguna manera?[n][f 1 6 65535][e]

[msg P3_HERO2_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19324]斡Parece que podemos seguir adelante![n][f 1 6 65535][e]

[msg P3_HERO2_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19325]Bueno, tenemos que ir a la siguiente zona![n][f 1 6 65535][e]

[msg P3_HERO2_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19326]Creo que podemos seguir adelante.[n][f 1 6 65535][e]

[msg P3_HERO2_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19327]斡Mira! 斡Una caja de tesoros![n][f 1 6 65535][e]

[msg P3_HERO2_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19328]Hay una caja de tesoros. 斡Abran![n][f 1 6 65535][e]

[msg P3_HERO2_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19329]Una caja de tesoros. 夷Qu姻 hay dentro?[n][f 1 6 65535][e]

[msg P3_HERO2_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19330]Algo sobre este 茨rea me est茨 molestando...[n][f 1 6 65535][e]

[msg P3_HERO2_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19331]Tiene que haber algo aqu胤. 斡Miremos por ah胤![n][f 1 6 65535][e]

[msg P3_HERO2_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19332]夷No hay algo extra隠o en este lugar?[n][f 1 6 65535][e]

[msg P3_HERO2_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19333]斡Un interruptor! 斡Vamos a dar un heave-ho![n][f 1 6 65535][e]

[msg P3_HERO2_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19334]斡Encontr姻 un interruptor! 斡Adelante![n][f 1 6 65535][e]

[msg P3_HERO2_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19335]夷No es un interruptor?[n][f 1 6 65535][e]

[msg P3_HERO2_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19336]夷Crees que podemos pasar por all胤?[n][f 1 6 65535][e]

[msg P3_HERO2_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19337]Creo que hay un atajo.[n][f 1 6 65535][e]

[msg P3_HERO2_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19338]斡Muy bien, un atajo![n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]?[n][f 1 6 65535][e]

[msg P3_HERO2_FOE_WARNING_NEA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19309]斡Todav胤a hay un FOE cerca! 斡Precauci吋n![n][f 1 6 65535][e]

[msg P3_HERO2_FOE_WARNING_NEA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19310]Parece que FOE sigue por aqu胤.[n][f 1 6 65535][e]

[msg P3_HERO2_FOE_WARNING_NEA_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19311]FOE hiriendo hacia nosotros![n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HP10_1]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HP10_2]
[f 0 5 65278][f 2 1]◆CONT威CTELO 10% DE LA VISTA[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_HP10_3]
[f 0 5 65278][f 2 1]◆CONTINUAR LA B郁SQUEDA DE LA LUZ[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HPTP10_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19312]斡S胤, esto es duro![n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HPTP10__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19313]夷Por qu姻 no volvemos a nuestra base?[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HPTP10__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19314]Estoy m茨s cansado de lo que pens姻...[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_TP10_1]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_TP10_2]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_PARTY_TP10_3]
[f 0 5 65278][f 2 1]■ CONTRASE謂A[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19315]Hrrgh... 斡Alguien, por favor, curame![n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19316]Creo que mi salud est茨 perdiendo...[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19317]No puedo seguir... Mi salud es demasiado baja...[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19318]Tan agotado... 夷Podemos descansar un poco?[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19319]Mi resistencia ha sido estirada demasiado lejos...[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19320]No m茨s... Estoy fuera de energ胤a...[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_BATTLE_]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_BATTLE__2]
[f 0 5 65278][f 2 1]◆Recibir 90% escrito[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_BATTLE__3]
[f 0 5 65278][f 2 1]【justificadamente[n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19321]Espero que el pr吋ximo sea as胤 tambi姻n![n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19322]斡Tranquilo![n][f 1 6 65535][e]

[msg P3_HERO2_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19323]斡Eso fue un pedazo de pastel![n][f 1 6 65535][e]

[msg P3_HERO2_BATTLE_CHANGE_D]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg P3_HERO2_BATTLE_CHANGE_D_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg P3_HERO2_BATTLE_CHANGE_D_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_DUNGEON]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg P3_HERO2_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1](DGP郁BLICA)[n][f 1 6 65535][e]

[msg P3_HERO2_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19360]斡Vamos![n][f 1 6 65535][e]

[msg P3_HERO2_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19361]斡D姻jame manejarlo![n][f 1 6 65535][e]

[msg P3_HERO2_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19362]斡Somos un escuadr吋n incre胤ble; vamos a[n]mantenerlo as胤![n][f 1 6 65535][e]

[msg P3_HERO2_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19363]Vale, esto no terminar茨 en ning雨n[n]momento, 斡espero![n][f 1 6 65535][e]

[msg P3_HERO2_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19364]斡Tenemos nuestras 吋rdenes, todos![n][f 1 6 65535][e]

[msg P3_HERO2_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19365]Estoy muy emocionada, ahora.[n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19352]Parece que tenemos una manera de ir...[n]夷Estamos bien en salud?[n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19353]Parece que todo se ha extendido...[n]Tengamos cuidado al continuar.[n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19354]斡El mapa se llena muy bien![n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19355]Creo que estamos a mitad de camino?[n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19356]斡Mantengamos esto y aceleremos![n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19357]Creo que s吋lo tenemos un poco m茨s que ir?[n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19358]斡Qu姻 sentido de logro![n][f 1 6 65535][e]

[msg P3_HERO2_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19359]斡Perfecto! Lo hicimos.[n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_AL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19342]斡Me encanta![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_AL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19343]斡Claro que no lo olvidaremos ahora![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_KA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19344]Bien, podemos ir a otro piso desde aqu胤.[n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_KA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19345]斡Ahora podemos seguir adelante sin perdernos![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_CHANGE_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19346]斡Bien, ese color es f茨cil de ver![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_CHANGE__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19347]斡Esto me hace querer intentar mapear tambi姻n![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_DE]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19348]Formas de mejorar la legibilidad.[n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_ICON_DE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19349]斡S胤, dejemos todo lo que no necesitamos![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19350]斡Tenemos que asegurarnos de no olvidar eso![n][f 1 6 65535][e]

[msg P3_HERO2_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19351]夷Tal vez deber胤a hacerlo? 斡Haha, s吋lo bromeaba![n][f 1 6 65535][e]

[msg P3_HERO2_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19366]斡Vamos, vamos![n][f 1 6 65535][e]

[msg P3_HERO2_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19367]斡Vamos a salir de aqu胤![n][f 1 6 65535][e]

[msg P3_HERO2_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19368]斡Por aqu胤![n][f 1 6 65535][e]

[msg P3_HERO2_KARITORU_ENCOUN]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg P3_HERO2_KARITORU_ENCOUN_2]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay nada que ver[n][f 1 6 65535][e]

[msg P3_HERO2_KARITORU_ENCOUN_3]
[f 0 5 65278][f 2 1]? ? Todav胤a no hay 姻xito[n][f 1 6 65535][e]

