[msg JUSTINE_FOE_FOLLOW_START]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59300]Es el...[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59301]El FOE te encontr吋.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59302]Ahora te est茨 persiguiendo.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59303]El FOE se acerca.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59304]Ten en cuenta que el FOE est茨 cerca.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59305]Por favor, procede con cautela.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59306]Parece que pueden relajarse, Caroline.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59307]El FOE dej吋 de perseguirte.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59308]Parece que el FOE ha dejado de perseguirlos,[n]Caroline.[n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59375]Avanza sin dejar que te ilumine.[n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59376]Hasta que apagues el interruptor, evita las luces.[n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59377]Ev胤talos y que no te vean.[n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59378]A menos que impida la electricidad, no puede[n]proceder.[n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59379]Es muy probable que haya un interruptor para desactivar la energ胤a.[n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59380]Si encuentras el interruptor podr茨s avanzar.[n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59381]斡Un viento poderoso![n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59382]Trata de usar el viento a tu favor, quiz茨s puedas aumentar tu movimiento.[n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59383]夷E-Est茨s bien...?[n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59309]Parece ser uno. Por favor, confirmalo.[n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59310]Excelente trabajo, Caroline. No esperaba[n]menos de ti.[n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59311]Parece que hay escaleras delante.[n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59336]Debe ser un cofre del tesoro.[n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59337]Qu姻 suerte. Has tropezado con un cofre del[n]tesoros.[n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59338]Eso debe ser lo que otros llaman "tesoro".[n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59339]Es evidente que hay algo ah胤.[n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59340]Siento algo en ese lugar.[n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59341]Ser胤a buena idea investigar la zona.[n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59342]Debe ser... alg雨n tipo de interruptor.[n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59343]Toma nota, hay un interruptor cerca.[n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59344]Algo deber胤a cambiar si usas el interruptor.[n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59345]Puede haber una manera de pasar por la pared.[n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59346]Probablemente, esa pared  se puede atravesar.[n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59347]Por favor, revisa las paredes cercanas.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59387]Caroline... 夷Crees que estar茨n bien?[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59388]S吋lo conc姻ntrate en la curaci吋n.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59389]Recuerda que volver tambi姻n una opci吋n.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59309]El FOE todav胤a te persigue. Mantente alerta,[n]Caroline.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59310]Contin雨a con precauci吋n.[n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59311]El FOE contin雨a acech茨ndote.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59315]Veo que todos han agotado sus reservas de[n]energ胤a.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59316]Deber胤amos abortar la misi吋n.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59317]Es obvio que todos est茨n fatigados.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59318]Eso es inusualmente compasivo por tu parte, Caroline... Y estoy de acuerdo.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59319]Veo que la salud del grupo est茨 disminuyendo constantemente.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59320]Puede ser mejor para parar y curarse.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59312]夷No te est茨s arriesgando demasiado?[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59313]Parece que su salud y la energ胤a son peligrosamente bajas.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59314]Por favor, extiende una mano de ayuda.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59327]Caroline, deber胤amos dejarlos descansar.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59328]Todos est茨n agotados... Hag茨moslos regresar y descansar, Caroline.[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59329]Podr胤as enfrentar m茨s dificultades si contin雨as luchando en tu estado actual.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59318]Recluso, tu salud est茨 muy baja. 夷Quiz茨s deber胤as tomar un descanso?[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59319]La salud del prisionero es muy[n]baja.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59320]Alguien debe curar al prisionero.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59324]Todas las se隠ales apuntan al agotamiento...[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59325]Ay, se est茨n quedando sin energ胤a.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59326]Han sido empujados a su l胤mite.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59390]Tienes demasiadas cosas.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59391]Ser胤a conveniente que fueras organizado.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59392]Tienes demasiadas cosas. Recomiendo[n]organizarlas.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59330]Tienes raz吋n, Caroline. Ahora podemos estar[n]tranquilas.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59331]Fue una pelea estupenda.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59332]Parece que todav胤a tienes algo de lucha en ti.[n][f 1 6 65535][e]

[msg JUSTINE_BATTLE_CHANGE_DU]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg JUSTINE_BATTLE_CHANGE_DU_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg JUSTINE_BATTLE_CHANGE_DU_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59390]Tienes demasiadas cosas.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59391]Ser胤a conveniente que fueras organizado.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59392]Tienes demasiadas cosas. Recomiendo[n]organizarlas.[n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59369]夷Est茨s empezando tu exploraci吋n?[n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59370]Entonces proporcionaremos respaldo.[n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59371]Ahora, empecemos.[n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59372]Pongamos en marcha esta proyecci吋n especial.[n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59373]Brindaremos ayuda hasta el final.[n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59374]Bueno, entonces, empecemos esto.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59361]Esto solo es el comienzo.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59362]Parece que has progresado mucho en el mapa.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59363]Esto debe estar cerca de la mitad...[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59364]Dir胤a que finalmente has llegado a la mitad.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59365]S吋lo necesitamos explorar un poco m茨s para[n]completar este piso.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59366]Solo un poco m茨s y completaremos este piso.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59367]Buenas noticias. Terminamos el mapa.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59368]Hemos explorado cada rinc吋n de este piso.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_ALL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59351]No est茨 mal.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59352]No est茨 mal para un prisionero.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_KAI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59353]Seguramente este excelente desempe隠o es el resultado de nuestra rehabilitaci吋n.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_KAI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59354]Vas a marcar la escalera, 夷no?[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_CHANGE_C]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59355]Estoy interesada en la versi吋n final del mapa.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_CHANGE_C_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59356]As胤 que ese es el color que usaras.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_DEL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59357]Los errores deben ser rectificados.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59358]Mantener el mapa limpio es una buena idea.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59359]夷Tomando notas? Probablemente, tuviste una mala experiencia con eso antes...[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59360]Ahora no tendremos que depender de nuestros recuerdos.[n][f 1 6 65535][e]

[msg JUSTINE_DOOR_OPEN_1]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg JUSTINE_DOOR_OPEN_2]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg JUSTINE_DOOR_OPEN_3]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59384]El Segador se acerca. Por favor, ten cuidado.[n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59385]Por favor, ten cuidado, porque hay un Segador rondando.[n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59386]Es el Segador... Tu 雨nica oportunidad es mantener el enfoque.[n][f 1 6 65535][e]

