[msg MARGARET_FOE_FOLLOW_STAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55300]Eso es... una Film Ob...[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_START_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57300]斡F-O-E![n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_STAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55301]Hay un FOE persigui姻ndote.[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_START__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57301]斡Cuidado, todos![n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_STAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55302]Te siguen.[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_START__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57302]斡Oh! F-O-E! 斡F-O-E![n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55303]Tranquilo, es un FOE.[n][f 1 6 65535][e]

[msg NANAKO_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57303]*Jadeo* 夷Qu姻...?[n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55304]Es bastante grande, pero, por supuesto, todo te parece grande a ti.[n][f 1 6 65535][e]

[msg NANAKO_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57304]*Jadeo* 斡Es enorme![n][f 1 6 65535][e]

[msg MARGARET_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55305]Tengan cuidado de que hay un FOE cerca.[n][f 1 6 65535][e]

[msg NANAKO_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57305]斡Eeek! 斡Est茨 muy cerca![n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55306]Bien hecho. Has perdido el FOE.[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57306]Eso fue aterrador.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55307]Tu escape fue exitoso.[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57307]Oh, el F-O-E se ha ido.[n][f 1 6 65535][e]

[msg MARGARET_FOE_FOLLOW_END__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55308]Afortunadamente, dej吋 de perseguirte.[n][f 1 6 65535][e]

[msg NANAKO_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57308]夷El F-O-E se ha ido? 夷Estamos a salvo ahora?[n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55375]Si esas luces logran tocarte, seguramente te[n]ver茨n.[n][f 1 6 65535][e]

[msg NANAKO_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57375]斡Si entras en una, te ver茨n![n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55376]Hay focos aqu胤.[n][f 1 6 65535][e]

[msg NANAKO_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57376]斡Se astuto para que no te encuentren![n][f 1 6 65535][e]

[msg MARGARET_KANSI_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55377]Ten cuidado al pasar.[n][f 1 6 65535][e]

[msg NANAKO_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57377]斡Es como el escondite! 斡No tienes que dejar[n]que te encuentren![n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55378]Para continuar, ser茨 necesario desactivar la[n]puerta el姻ctrica.[n][f 1 6 65535][e]

[msg NANAKO_DENKISAKU_REACTIO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57378]Es todo zappy... 夷Podemos apagarlo?[n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55379]Esa puerta es un desafortunado obst茨culo.[n][f 1 6 65535][e]

[msg NANAKO_DENKISAKU_REACTIO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57379]斡Cuidado! 斡No te emociones![n][f 1 6 65535][e]

[msg MARGARET_DENKISAKU_REACT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55380]Es probable que haya un interruptor para[n]apagar la energ胤a. Espero que puedas[n]encontrarlo.[n][f 1 6 65535][e]

[msg NANAKO_DENKISAKU_REACTIO_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57380]夷Hay un interruptor para apagar la elerg胤a?[n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55381]Qu姻 fuerte viento.[n][f 1 6 65535][e]

[msg NANAKO_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57381]*斡Jadeo!* 夷Te est茨n matando?[n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55382]Cuidado con d吋nde pisan, todos.[n][f 1 6 65535][e]

[msg NANAKO_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57382]斡El viento es fuerte![n][f 1 6 65535][e]

[msg MARGARET_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55383]斡Es una brisa![n][f 1 6 65535][e]

[msg NANAKO_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57383]*Jadeo* 斡Volamos![n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55333]Bien hecho. Has encontrado las escaleras.[n][f 1 6 65535][e]

[msg NANAKO_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57333]斡S胤! 夷Te est茨s moviendo?[n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55334]Progreso notable. 夷Est茨s listo para ir m茨s[n]lejos?[n][f 1 6 65535][e]

[msg NANAKO_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57334]斡Oh! 斡Me encanta este juego! 斡Espio, con mi[n]peque隠o ojo, una escalera![n][f 1 6 65535][e]

[msg MARGARET_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55335]Por fin, has encontrado las escaleras.[n][f 1 6 65535][e]

[msg NANAKO_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57335]斡Ah胤 est茨n las escaleras![n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55336]Eso parece ser un cofre del tesoro. 夷Planeas[n]abrirlo, no?[n][f 1 6 65535][e]

[msg NANAKO_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57336]斡Un cofre del tesoro! 夷Qu姻 hay en 姻l?[n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55337]Un cofre del tesoro. 夷Qu姻 podr胤a haber dentro?[n][f 1 6 65535][e]

[msg NANAKO_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57337]斡Vaya, encontraste un cofre del tesoro![n][f 1 6 65535][e]

[msg MARGARET_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55338]Espero que encuentres algo que valga la pena[n]en esa cofre del tesoro.[n][f 1 6 65535][e]

[msg NANAKO_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57338]斡Veo un tesoro![n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55339]Puede que muy bien deses echar un vistazo[n]m茨s cerca all胤.[n][f 1 6 65535][e]

[msg NANAKO_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57339]夷Qu姻 es eso?[n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55340]夷Qu姻 podr胤a ser?[n][f 1 6 65535][e]

[msg NANAKO_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57340]夷...Huh? 夷Qu姻 es eso?[n][f 1 6 65535][e]

[msg MARGARET_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55341]No s姻 qu姻 es, pero hay algo adelante.[n][f 1 6 65535][e]

[msg NANAKO_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57341]Oye, hay algo aqu胤.[n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55342]Hay un cambio adelante.[n][f 1 6 65535][e]

[msg NANAKO_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57342]斡Un interruptor! 夷Puedo tocarlo?[n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55343]Apuesto a que hay un interruptor cerca.[n][f 1 6 65535][e]

[msg NANAKO_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57343]斡Interruptor, interruptor![n][f 1 6 65535][e]

[msg MARGARET_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55344]夷Crees que deber胤as ver que hace ese[n]interruptor?[n][f 1 6 65535][e]

[msg NANAKO_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57344]夷Vas a usar el interruptor? 夷Seguro?[n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55345]Esa pared se puede atravesar.[n][f 1 6 65535][e]

[msg NANAKO_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57345]斡Puedes caminar por esa pared![n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55346]Hay un pasaje oculto cerca.[n][f 1 6 65535][e]

[msg NANAKO_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57346]斡Mira esa pared![n][f 1 6 65535][e]

[msg MARGARET_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55347]Esa pared... Hay algo ah胤.[n][f 1 6 65535][e]

[msg NANAKO_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57347]Esa pared se ve extra隠a.[n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55387]No hay duda de que est茨s muy herido.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57387]No te ves bien. 斡Vuelve al cine![n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55388]Estoy de acuerdo. 夷Tal vez deber胤as regresar[n]por ahora?[n][f 1 6 65535][e]

[msg NANAKO_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57388]斡Es demasiado peligroso seguir![n][f 1 6 65535][e]

[msg MARGARET_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55389]No puedo recomendar seguir adelante.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57389]Estoy preocupada por todos...[n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55309]El FOE ha vuelto. Deber胤as estar alerta.[n][f 1 6 65535][e]

[msg NANAKO_FOE_WARNING_NEAR_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57309]斡D姻jalos en paz![n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55310]Eso es correcto, as胤 que mejor vigila tus[n]alrededores.[n][f 1 6 65535][e]

[msg NANAKO_FOE_WARNING_NEAR__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57310]斡El F-O-E sigue aqu胤![n][f 1 6 65535][e]

[msg MARGARET_FOE_WARNING_NEA_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55311]Un FOE se acerca. Ten cuidado.[n][f 1 6 65535][e]

[msg NANAKO_FOE_WARNING_NEAR__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57311]斡Tenemos que hacer nuestro mejor esfuerzo![n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55315]Te sugiero que te retires por ahora.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57315]S胤, 斡volvamos![n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55316]Desafortunadamente, todo el equipo est茨 al[n]borde del colapso...[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57316]斡No quiero que pierdas![n][f 1 6 65535][e]

[msg MARGARET_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55317]S胤, no ser胤a prudente seguir adelante as胤.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57317]夷Est茨s bien? 夷Debemos regresar?[n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55321]La salud de todos se acerca r茨pidamente a un[n]nivel peligroso.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57321]No corras demasiados riesgos. 斡Eso es lo que dijo[n]mi profesor![n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55322]En serio, deber胤as echar un vistazo a la[n]salud de tu grupo.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57322]斡Tomen una siesta, todos![n][f 1 6 65535][e]

[msg MARGARET_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55323]Deber胤as curar a todos como tu primera[n]prioridad.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57323]Todos parecen tan lastimados...[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55312]Tu salud y energ胤a est茨n agotadas.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57312]Oh no... Tengo miedo por todos...[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55313]Debes hacer de la curaci吋n de todos tu primera prioridad.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57313]斡Te tienes que curar antes de que sea demasiado[n]tarde![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HPTP10__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55314]Por desgracia, has perdido mucha salud y[n]energ胤a.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57314]*jadeo* 斡Ayuda![n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55327]Hay mucha energ胤a en el grupo.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57327]夷Por qu姻 todos se ven tan cansados?[n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55328]Me preocupa cada vez m茨s sus grandes p姻rdidas[n]de energ胤a.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57328]夷A雨n van a seguir...?[n][f 1 6 65535][e]

[msg MARGARET_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55329]Parece que el grupo est茨 sufriendo una[n]falta de energ胤a.[n][f 1 6 65535][e]

[msg NANAKO_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57329]夷Tal vez deber胤an volver?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55318]Deber胤as priorizar la curaci吋n.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57318]斡Vas a perder si sigues adelante![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55319]夷Puedo sugerir restaurar tu salud?[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57319]S胤. 斡Si est茨s cansado, descansa![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55320]夷Considerar胤as restaurar tu salud primero?[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57320]夷Est茨s lastimando?[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55324]夷Hay algo que puedas hacer para ayudar?[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57324]Parece que te vas a desmayar...[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55325]Estoy de acuerdo. Ser胤a imprudente.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57325]No deber胤as seguir adelante cuando est姻s tan[n]cansado...[n][f 1 6 65535][e]

[msg MARGARET_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55326]Est茨s totalmente sin de la resistencia.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57326]Tom姻monos un descanso en grupo, 斡ya que estamos cansados![n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55390]Necesitas hacer algo de limpieza.[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57390]斡Tu bolsa est茨 llena![n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55391]Tienes un demasiados de objetos.[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57391]斡Soy buena para ordenar cosas![n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_BATTLE__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55392]夷Sabes que puedes dejarle algunos[n]objetos a Theodore?[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57392]斡Oh no, tu bolsa est茨 tan llena![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55330]Parece que te va bien.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57330]斡Yo tambi姻n lo estoy haciendo bien![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55331]Todav胤a hay alguien que parece estar en buenas[n]condiciones.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57331]斡Todav胤a podemos seguir![n][f 1 6 65535][e]

[msg MARGARET_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55332]Deber胤as seguir adelante mientras puedas.[n][f 1 6 65535][e]

[msg NANAKO_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57332]斡Lo est茨s haciendo genial![n][f 1 6 65535][e]

[msg NANAKO_BATTLE_CHANGE_DUN]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg NANAKO_BATTLE_CHANGE_DUN_2]
[f 0 5 65278][f 2 1]■ト {\cHFF}[n][f 1 6 65535][e]

[msg NANAKO_BATTLE_CHANGE_DUN_3]
[f 0 5 65278][f 2 1]■ト {}[n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55390]Necesitas hacer algo de limpieza.[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57390]斡Tu bolsa est茨 llena![n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55391]Tienes un demasiados de objetos.[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57391]斡Soy buena para ordenar cosas![n][f 1 6 65535][e]

[msg MARGARET_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55392]夷Sabes que puedes dejarle algunos[n]objetos a Theodore?[n][f 1 6 65535][e]

[msg NANAKO_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57392]斡Oh no, tu bolsa est茨 llena![n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55369]Te apoyar姻 'Detr茨s de c茨maras', como dicen aqu胤.[n][f 1 6 65535][e]

[msg NANAKO_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57369]斡D姻jenme la navegaci吋n![n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55370]夷Has terminado los preparativos? Entonces[n]v茨monos.[n][f 1 6 65535][e]

[msg NANAKO_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57370]斡Seamos buenos compa隠eros de equipo![n][f 1 6 65535][e]

[msg MARGARET_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55371]夷Est茨s preparado?[n][f 1 6 65535][e]

[msg NANAKO_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57371]斡Estoy lista![n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55372]Ambas te brindaremos apoyo, en lo que sea[n]posible.[n][f 1 6 65535][e]

[msg NANAKO_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57372]斡La proyecci吋n especial est茨 comenzando![n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55373]Si todo el mundo est茨 listo, empecemos.[n][f 1 6 65535][e]

[msg NANAKO_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57373]夷Est茨s listo?[n][f 1 6 65535][e]

[msg MARGARET_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55374]Empecemos la proyecci吋n especial.[n][f 1 6 65535][e]

[msg NANAKO_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57374]斡Yo tambi姻n ayudar姻! 斡Podemos hacerlo![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55361]Te est茨s volviendo muy bueno en esto.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57361]Todav胤a hay mucho que explorar. 斡Pero puedes[n]hacerlo![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55362]En realidad, acabas de empezar.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57362]斡El mapa est茨 un poco hecho![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55363]Parece que est茨s a mitad de camino.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57363]斡El mapa est茨 medio hecho![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55364]Est茨s explorando a buen ritmo.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57364]斡Jeje, a mitad de camino![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55365]No queda mucho de este piso.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57365]Casi. 斡Puedes hacerlo![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55366]Ya casi terminas este piso. Te deseo suerte.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57366]斡El mapa est茨 casi terminado![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55367]Probablemente conozcas este piso como la[n]palma de tu mano.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57367]斡S胤! 斡Todo est茨 hecho![n][f 1 6 65535][e]

[msg MARGARET_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55368]Bien hecho. Has completado este piso.[n][f 1 6 65535][e]

[msg NANAKO_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57368]Yaaaay. 斡Terminaste el mapa![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_AL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55351]Parece que tu mapa es muy preciso.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_ALL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57351]斡Eso es un A+![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_AL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55352]Est茨s ejerciendo un juicio s吋lido.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_ALL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57352]Vaya. 斡Este mapa es el mejor dibujo que he[n]visto![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_KA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55353]Con ese nivel de habilidad, no deber胤as tener[n]miedo de perderte.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_KAID]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57353]斡Siento que nunca nos perderemos![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_KA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55354]Vamos a marcar estas escaleras de abajo.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_KAID_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57354]斡Ahora no tenemos nada que temer![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_CHANGE_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55355]Apruebo tu sensibilidad art胤stica.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_CHANGE_CO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57355]夷En qu姻 mapa se est茨 convirtiendo?[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_CHANGE__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55356]Espero ver el mapa cuando est姻 listo.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_CHANGE_CO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57356]斡Vaya, eres bueno dibujando fotos![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_DE]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55357]夷Algo de limpieza?[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_DEL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57357]斡Soy buena para limpiar![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_ICON_DE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55358]Por supuesto, es bueno corregir errores[n]siempre que sea posible.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_ICON_DEL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57358]夷Has quitado algo? 夷Est茨s dibujando algo otra[n]vez?[n][f 1 6 65535][e]

[msg MARGARET_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55359]No debes olvidar detalles importantes.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57359]斡Yo tambi姻n soy una buena escritora![n][f 1 6 65535][e]

[msg MARGARET_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55360]Escribir notas para m茨s tarde es un h茨bito excelente.[n][f 1 6 65535][e]

[msg NANAKO_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57360]Tambi姻n escribir姻 una nota. As胤, no lo[n]olvidar姻.[n][f 1 6 65535][e]

[msg NANAKO_DOOR_OPEN_1]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg NANAKO_DOOR_OPEN_2]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg NANAKO_DOOR_OPEN_3]
[f 0 5 65278][f 2 1]↑[n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55384]斡El Segador est茨 aqu胤! 斡No te muevas![n][f 1 6 65535][e]

[msg NANAKO_KARITORU_ENCOUNT_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57384]斡El Segador! 斡Es el![n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55385]Sigue alerta. Se acerca un enemigo poderoso.[n][f 1 6 65535][e]

[msg NANAKO_KARITORU_ENCOUNT__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57384]斡Viene el Segador![n][f 1 6 65535][e]

[msg MARGARET_KARITORU_ENCOUN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55386]El Segador est茨 cerca. Mantente alerta.[n][f 1 6 65535][e]

[msg NANAKO_KARITORU_ENCOUNT__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57384]斡No! 斡El Segador se acerca r茨pidamente![n][f 1 6 65535][e]

