[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54002][f 6 1 2 0 0 4]Hello and welcome. Will you be[n]attempting a special screening?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 3][f 3 1 1 0 0 25067]Yes, we'd like to try.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 6][f 3 1 1 0 0 0]Based on the description, it sounds like[n]we just have to defeat the enemies,[n]right...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 0]Hmhm. Rest assured, you won't be[n]tasked with doing anything[n]unreasonable... yet.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Now, on to business. Might I ask that[n]you defeat eight Basalts?[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Sounds easy.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No problem.[f 2 7 1 64 2 32][e]

[msg MSG_005 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 6][f 3 1 1 0 0 27067]Mhm. We can handle that.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 6][f 3 1 1 0 0 25071]That should be fine. I doubt we'll have[n]any issues at our current strength.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 0]That's very reassuring to hear.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I will be watching you from here with[n]popcorn in hand.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54006][f 6 1 2 0 0 6]Let us now begin the special screening![n][f 1 3 65535][f 1 1][e]

