[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54007]For this special screening, all of you will[n]be required to complete a certain[n]mission.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Mission?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]I would like you to reach the location[n]that I specify.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 4018]...Huh? That's all? That sounds easy![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 54029]Perhaps, but things rarely go as planned.[n]Such is the way of the world.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Say what!?[f 2 7 1 64 10 0][e]
[f 0 5 65278][f 2 1]Saw that coming...[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Not a problem.[f 2 7 1 64 2 32][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23091]Come on, you should've seen that[n]coming.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 4 6][f 3 1 1 0 0 21082][f 6 1 2 0 0 9]Dude, does anything faze you? Even just[n]a little?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 3 6][f 3 1 1 0 0 3033]Wow... Always playin' it cool.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 6 2 1][f 3 1 1 0 0 54010]That said, it seems the syndicate has[n]recently become aware of our plans...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As a result, security has been raised to[n]the maximum level.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]Guard detail and searchlight activity will[n]be megatons heavier than usual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Ugh... This is a pain just hearin'[n]about it...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 1 0 1][f 4 6 66 2 0 3][f 3 1 1 0 0 22003]That's...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4049]Yeah, it's perfect![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Slipping past searchlights is totally[n]something a phantom thief would do![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 65 8 1 1][f 3 1 1 0 0 21010][f 6 1 2 0 0 4]What's got those two so worked up?[n]Somethin' happen?[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]They're motivated.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]They're good friends.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]We can't let them show us up.[f 2 7 1 64 0 32][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 0][f 3 1 1 0 0 21009]Well, that's cool, I guess...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Honestly, though, it's a pretty weird[n]pairing, now that I think about it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 0][f 3 1 1 0 0 21013][f 6 1 2 0 0 4]Well, that's cool, I guess... Still, they[n]weren't always that close, were they?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 21082][f 6 1 2 0 0 6]What is this, a competition!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I'm just sayin', it's kind of a weird[n]pairing, don't you think?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Well, they are different from each other.[n]They don't look like they'd have[n]anything in common...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 4][f 3 1 1 0 0 9049]A sweet-toothed girl from the city and[n]a meat-lover from the country...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Both so different yet so pretty! I can't[n]bear to choose between them![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 1 0 1][f 4 6 66 2 0 4][f 3 1 1 0 0 22005][f 6 1 2 0 0 4]Hey. What're you guys mumbling about[n]over there?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4123][f 6 1 2 0 0 6]You're gonna get left behind![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 7 0 0 1][f 3 1 1 0 0 0]They really are worked up... Guess we[n]should get movin' too.[n][f 1 3 65535][f 1 1][e]

