[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54125]For this special screening, you will be[n]tasked with gathering the specified[n]ingredients.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If I recall, these Tingly Kernels were[n]used in the latest popcorn recipe...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54113]Would you be so kind as to bring some to[n]my foolish younger brother?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 1 1][f 3 1 1 0 0 56113]That would be most appreciated...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I believe you can find Tingly Kernels[n]near damp places like ponds or rivers.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]A place as rife with vegetation as[n]Junessic Land should be perfect.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23072]Okay then, I say we give him a hand.[n]He is always helping us, after all.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Plus, we'll get some more of that new[n]popcorn. Two birds, one stone. Make[n]sure you're ready, and we'll get going.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Distant scream]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 3 1 1 0 0 27104]Aaaaaaaaaaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 10 0 3][f 4 6 80 10 0 0][f 3 1 1 0 0 56094][f 6 1 2 0 0 0]Wh-What was that...!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23046][f 6 1 2 0 0 6]Come on, let's go check it out![n][f 1 3 65535][f 1 1][e]

