[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 25 12 0 1][f 3 1 1 0 0 25089]First, let's locate the dinosaur. Who[n]knows what'll happen to it if we don't.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Rise, do you sense it nearby?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 100 1][f 3 1 1 0 0 6517][f 3 1 6 0 0 500]Hmm... One sec.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 4 99 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Oh! I'm getting something small near[n]here![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 12 1 1][f 3 1 1 0 0 0]I just hope we don't run into some kinda[n]carnivore...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]If that happens, you're the decoy.[n]We'll help the dino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I don't wanna be a bear-ger and fries[n]combo! You're coming with me,[n]Yosuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 1][f 3 1 1 0 0 0]Good point. A dish does need a little[n]something to add color―like parsley.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]So I'm just a garnish...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 0][f 3 1 1 0 0 0]That's a good idea. Not everyone likes[n]the way animals smell either.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Are you saying I stink!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 0][f 3 1 1 0 0 27094]And if the dinosaur is wounded, we'll[n]need to heal it as well.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 0]I'm not sure if medicine for humans will[n]work, though... It's probably best if we[n]use something else.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 4][f 3 1 1 0 0 25068]That's true. Hopefully we can find some[n]herbs somewhere around here...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 0][f 3 1 1 0 0 0]But, first things first: we need to rescue[n]that dinosaur.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 27122]Let's hurry. I want to reunite it with its[n]mom.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 5069]Right, we can't leave it alone. Let's find[n]it ASAP.[n][f 1 3 65535][f 1 1][e]

