[msg MSG_000 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8022]I must say, this place is impeccably clean;[n]I can't find a single trace of dust.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Yeah, it's like the complete opposite of[n]the dinosaur movie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 1][f 3 1 1 0 0 0]No kiddin'. No grass or giant bones[n]anywhere.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 3 1 1 0 0 22113]Y'know, I get that those bones are just[n]dead dinosaurs, but isn't it kinda freaky[n]when you look 'em in the eyes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 3][f 3 1 1 0 0 22091]Ugh, I just remembered all of it... I'm so[n]glad there's nothing like that here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28084]Yes. Still, this spotless scenery brings[n]issues of its own.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]For example, take those dinosaur bones[n]Panther just mentioned...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Those were a good indicator of whether[n]or not an area was dangerous.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]What do you mean?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]How could you tell?[f 2 7 1 20 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28086]If you analyze the bones, you can make[n]a good guess as to when the dinosaur[n]died.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And if you know that, then you can[n]estimate how far away its killer is.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 8075]I see. Fresh bones would mean danger is[n]close by. Otherwise it's safe...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Unfortunately, there's nothing like that[n]in this movie; we'll need to be more[n]careful.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 3][f 3 1 1 0 0 21092]Tsk, you should've just said so.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28033]Haha, sorry.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm a newcomer here, so I didn't want[n]to act like I was in charge.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 3][f 3 1 1 0 0 0]Wow, Crow, you're so cool.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 6][f 3 1 1 0 0 17002]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]That's right, Koromaru-kun. Your nose[n]won't be as effective against the[n]mechanical enemies here. [n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It seems this sci-fi city will prove quite[n]the challenge.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]A new special screening:[n]"Beast Hunt"[n]has been added to the box office.[n][f 1 3 65535][f 1 1][e]

