[msg MSG_000 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8113]It amazes me that a gate of this size[n]moves so effortlessly.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's likely the controls for it are far[n]beyond our current level of technology.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 3][f 3 1 1 0 0 5032]Hehe, you seem more talkative than[n]usual, Naoto-kun.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 6][f 3 1 1 0 0 0]It's not exactly machinery, but she does[n]like those secret bases with doors that[n]go "Nhreeee―CRUSH!"[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 8 0 1][f 3 1 1 0 0 8010]Th-That's... It's kind of embarrassing...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 6][f 3 1 1 0 0 14548]Secret bases? You mean like a lab or a[n]research institute!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]Huh? U-Um... Yes.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]That's cool.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I'd like to see that.[f 2 7 1 20 0 32][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 8053]No, it was just a labyrinth my heart[n]created, and, besides, it's gone now...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 6][f 3 1 1 0 0 24008]A secret base created by one's heart[n]that's neither a Palace nor Mementos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24049]How very intriguing. If only I'd been[n]able to see it with my own eyes![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 3][f 3 1 1 0 0 17002]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 6][f 3 1 1 0 0 0]Your secret lab sure is popular,[n]Naoto-kun.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 8136]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]I feel sort of foolish about being[n]embarrassed earlier.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8097]...Ah, we need to keep searching for that[n]container.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It should be just a little further. Let's[n]keep going.[n][f 1 3 65535][f 1 1][e]

