[msg MSG_000 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 24073]Well now, I'd say we're much closer to[n]the container than before.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 3][f 3 1 1 0 0 17001]Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 24032]Haha, what is it? Those sparkly eyes tell[n]me you want something.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 3][f 3 1 1 0 0 17002]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 6][f 3 1 1 0 0 0]I think he wants you to play with him,[n]Fox.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 6][f 3 1 1 0 0 26532][f 3 1 6 0 0 500]Ohh, good for you, Fox. I'm sure you[n]two'll get along great.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 100 6][f 3 1 1 0 0 14530][f 3 1 6 0 0 500]It looks like Koro-chan's interested in[n]Fox's tail.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It is fluffy, after all. Maybe he thinks[n]you're like him.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 3][f 3 1 1 0 0 17002]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 24076]Now that I look at you, you are rather[n]cute.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0]It certainly feels different playing with a[n]dog. I've grown somewhat accustomed[n]to cats lately.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 6][f 3 1 1 0 0 23035]What do you mean "somewhat"!? Also,[n]I'm not a cat![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 0]The joke's basically a tradition at this[n]point...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 8033]I like cats...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Not only are they cute, but they also[n]have an air of nobility about them.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 23053]See, Naoto gets it. You may touch[n]my paw if you like.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 6][f 3 1 1 0 0 23036]...I'm not a cat, though![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 100 1][f 3 1 1 0 0 14502]Um, I don't mean to spoil the fun, but[n]we should probably get going.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 1][f 3 1 1 0 0 0]The container is just up ahead. Be[n]careful, everyone.[n][f 1 3 65535][f 1 1][e]

