[msg MSG_000 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 12013]This is it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 10 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 10]It's really crowded here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 4][f 3 1 1 0 0 13006]Now then, let's split up and ask around.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 1][f 3 1 1 0 0 10109]How'd it go?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 1 3][f 3 1 1 0 0 11089]It's the same as last time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 3][f 3 1 1 0 0 0]Multiple perps ganged up on a lone[n]woman and took her wallet.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 6][f 3 1 1 0 0 0]Apparently, it happened so fast, no one[n]knows where they came from nor where[n]they disappeared to.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_1 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 24013][f 6 1 2 0 0 9]Our enemies certainly know how to[n]avoid detection.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]That's not good.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Just like phantom thieves.[f 2 7 1 20 4 32][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 23 6 0 1][f 3 1 1 0 0 23038][f 6 1 2 0 0 10]It's too bad we can't pick up their trail...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 12 10 0 1][f 3 1 1 0 0 12034][f 6 1 2 0 0 0]You don't mean―!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 4][f 3 1 1 0 0 23084][f 6 1 2 0 0 2]No! Stop confusing everyone, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 22 10 1 1][f 3 1 1 0 0 22112]But I gotta say, the people are behaving[n]a lot differently now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 3][f 3 1 1 0 0 0]Seriously. I kinda thought they'd be[n]more "whatever" about all this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 4][f 3 1 1 0 0 13020][f 6 1 2 0 0 4]Hm? What do you mean?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 21012]This city used to be ruled by a real[n]scumbag, and everybody here just did[n]what he said.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]They were completely dependent on[n]him. No one ever stood up for[n]themselves...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 22113]But now it looks like the people are[n]starting to act on their own.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014_1 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]A few of them even came over and[n]talked to us, hoping it would help solve[n]the case.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 4][f 3 1 1 0 0 13075]Oh? How interesting...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 3][f 3 1 1 0 0 0]Those at the top will often affect those[n]below... I think this film is proof of that.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 6 1 1][f 3 1 1 0 0 13023]Those at the top...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 3][f 3 1 1 0 0 25003][f 6 1 2 0 0 4]What's wrong?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 1 1][f 3 1 1 0 0 13078]Nothing...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13069]We still have one more crime scene to[n]check. Let's ask around there as well.[n][f 1 3 65535][f 1 1][e]

