[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54115]Welcome back, everyone.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Even those once-terrifying FOEs were[n]nothing but mere playthings against[n]your current strength.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I cannot help but be surprised by the[n]rate at which you've grown.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 79 1 0 4][f 4 6 78 4 0 1][f 3 1 1 0 0 58118]Hmph, she's exaggerating. We were[n]falling asleep over here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 4][f 3 1 1 0 0 59060]You may have won the battle, yes, but[n]your slow pace made for a rather[n]dull viewing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 54084]Dull, you say...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 74 12 100 1]I could've sworn I witnessed you two[n]cheering on [f 6 1 30 0 0 0] and[n]his team the whole way through...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Do you mean to say it was all some[n]sort of illusion?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 79 1 0 4][f 4 6 78 10 0 1][f 3 1 1 0 0 58059]N-No![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 78 4 0 1][f 3 1 1 0 0 0]W-We were just monitoring on the[n]Inmate's rehabilitation progress![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 4][f 3 1 1 0 0 59041]Correct. We were simply performing[n]our duties.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 3][f 3 1 1 0 0 0]*giggle* They must be really worried[n]about you, [f 6 1 30 0 0 0]-kun.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 3][f 3 1 1 0 0 3030]Well, you were technically the lead role[n]in that showing. I guess they're kinda[n]like your fans.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Don't fall for me now.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Want my autograph?[f 2 7 1 64 0 32][e]

[msg MSG_009 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 10 0 1][f 3 1 1 0 0 58093]......![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 10 0 4][f 3 1 1 0 0 59066]......![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 8 0 1][f 3 1 1 0 0 58052]D-Don't be so full of yourself! Show[n]some respect![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 8 0 4][f 3 1 1 0 0 59067]I-It is merely our job to monitor you at[n]all times.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]We are to know everything about you,[n]Inmate...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 3][f 3 1 1 0 0 26042]Mwehehe, textbook excuses. I'm getting[n]embarrassed just watching.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 12 0 1][f 3 1 1 0 0 58017]Autograph...? What, you mean signing[n]your name?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hmph, humans. Why waste your time[n]with something so stupid...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's pointless...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 1 0 4][f 3 1 1 0 0 59059]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 79 6 0 4][f 3 1 1 0 0 0]I'll have him sign a corner of my notes[n]later.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 4 0 1][f 3 1 1 0 0 58037]Hey, no fair![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 3][f 3 1 1 0 0 26042]Mwehehe, well aren't you popular.[n]Treat your fans well, you hear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54029]In any case, you've performed quite[n]admirably, Phantom Thieves.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You've lived up to your viewers'[n]expectations. It would seem that[n]stealing hearts is indeed your specialty.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54026]Once again, well done.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've readied your reward. Please take it.[n][f 1 3 65535][f 1 1][e]

