[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 6 2 100 1][f 3 1 1 0 0 6570][f 3 1 6 0 0 500][f 6 1 2 0 0 7]Here we are! See? There's a lot, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 1][f 3 1 1 0 0 24030][f 6 1 2 0 0 1]Yes... We can eat these! This one...[n]That one...! Hahahaha! It's a gold mine![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Oh, please... It's just a buncha grass...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 6][f 3 1 1 0 0 22006]Well, whatever, let's gather what we[n]can. I'm sure Fox'll tell us if it's good or[n]not.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 3 1 1 0 0 0]We decided to gather some edible[n]wild plants...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 26533][f 3 1 6 0 0 500]A bunch of Persona-users collecting[n]wild plants... You don't see that every day.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 1 0][f 3 1 1 0 0 11091][f 6 1 2 0 0 9]Ughhh... My back's startin' to hurt. I'm[n]gonna take a break...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0]C'mon, Junpei. Giving up already? You[n]noob.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11083][f 6 1 2 0 0 6]No way! I'm just gettin' started![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 6 1 9 0 0 1][f 3 1 1 0 0 11106]Energy charge complete, aaand... it's[n]time for Junpei, Ace Collective![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Here we go! Double blades, baby![n]Woooooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 4 0 1][f 3 1 1 0 0 10055][f 6 1 2 0 0 6]You idiot! You're getting it all over me![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 24 1 0 1][f 4 6 27 6 1 3][f 3 1 1 0 0 27003][f 6 1 2 0 0 4]Fox, what about this one?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24073]This one's good. A little bit of salt after[n]it's fried, and it should taste great.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]This one's a bit bitter, but if we can[n]prepare it well enough...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 18045][f 6 1 2 0 0 4]Huh... You know your stuff.[n]Why is that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 0]Are you referring to my knowledge of[n]wild plants?[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]He really likes them.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]It's because he's poor.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]He's just a weirdo.[f 2 7 1 20 0 32][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24067]Well, I like wild plants. To be able to[n]survive off nature's blessings alone[n]is a truly wonderful thing.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]But, truthfully, there is another reason...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 24029][f 6 1 2 0 0 6]Exactly! And, as a poor man, this is an[n]excellent way to save money![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 24036][f 6 1 2 0 0 0]A weirdo!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0]Nature is food to me... Wild plants[n]included. I had to learn this to stay alive.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12031]It's almost like you're training. Still, it[n]doesn't exactly seem like you're doing it[n]willingly. [n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24074]Right. I may be fortunate enough to go[n]to school, but I don't necessarily have[n]the money to live as I please.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Nor do I have a family for support.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 1 0 0][f 3 1 1 0 0 18068]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 24079]If I'm to keep pursuing beauty, I need[n]money. Art supplies are far from cheap,[n]but I can't make any compromises.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]That said, I can't create anything if I'm[n]dead. It is this struggle that fuels me.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24031]I strive to insert every part of my being[n]into my art... It's what's kept me going[n]all this time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 12076]That's a pretty stoic way of thinking...[n]But I like it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 24063][f 6 1 2 0 0 6]Yes, you understand me, Sanada-san![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 12070]Yeah. I know the feeling of making[n]sacrifices to get what you truly want.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If it means getting stronger... then I'm[n]more than willing to risk my life.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 1 0 6][f 3 1 1 0 0 0]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 6][f 3 1 1 0 0 18030][f 6 1 2 0 0 9]Damn... To think there's another clumsy[n]dumbass here.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 6][f 3 1 1 0 0 0]Okay, screw it. I'll let you guys[n]eat all you want. Just go get[n]some more ingredients.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]We've gathered up a lot of wild plants.[n]This should be enough.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12078]...No, not yet.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 0][f 3 1 1 0 0 12130][f 6 1 2 0 0 6]There isn't enough protein! We won't[n]build any muscle from this![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 1][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]Whaaa―!? You're really gonna worry[n]about that!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I do agree that plants might not be[n]enough. Perhaps if we had some type of[n]meat or fish?[n][f 1 3 65535][f 1 1][e]

[sel SEL_031 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Definitely meat.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Let's do fish.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Protein powder?[f 2 7 1 20 0 32][e]

[msg MSG_032 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4134][f 6 1 2 0 0 7]Oh, me too! Meat, meat, meat![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]But we all ready used up all the frozen[n]meat in the containers...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031][f 6 1 2 0 0 4]Hmph, there's meat roaming around all[n]over this place. Want me to go get[n]us some?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 2]Don't be stupid. You're not gonna run[n]off by yourself again, are you?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23045][f 6 1 2 0 0 6]Fish! That sounds great![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23053][f 6 1 2 0 0 6]Heheh! I'll finally get to eat some sushi![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]What? Prehistoric sushi!? I feel like[n]it'd take some serious guts to eat[n]that kind of fish raw...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 6][f 3 1 1 0 0 0]Sorry, but I can't make sushi. The best I[n]can do is cook the fish.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 12030]I suppose that'll work. It'll definitely[n]provide protein.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 2]Hell no. Go get some real food.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 7 1 1][f 3 1 1 0 0 24101][f 6 1 2 0 0 3]Ngh... My vision is blurring...! I don't[n]think I can go on...[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 0]Look, this guy's gonna die from hunger[n]if we don't do somethin' fast.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]Fish is probably our best bet. Pretty[n]sure there'd be some kinda river or[n]something like that around here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 100 1][f 3 1 1 0 0 14615][f 3 1 6 0 0 500]Now that you mention it, I do[n]remember seeing what looked like[n]a pond earlier.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 1][f 3 1 1 0 0 0]It's at the northeastern corner of this[n]floor. Perhaps you should take a look?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 2 0 1][f 3 1 1 0 0 23072][f 6 1 2 0 0 6]Okay, we're off to catch some fish! Let's[n]go before Fox faints![n][f 1 3 65535][f 1 1][e]

