[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 16 1 0 1][f 4 6 21 12 0 3][f 3 1 1 0 0 21001][f 6 1 2 0 0 4]How you holdin' up, Ken? Not runnin'[n]outta steam, are ya?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16031][f 6 1 2 0 0 4]*chuckle* Don't underestimate me just[n]because I'm still in grade school.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've honed my skills in Tartarus, you[n]know.[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Ah, that's right.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Tartarus?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]It's got nothing on the Palaces.[f 2 7 1 20 6 32][e]

[msg MSG_003 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 3 0 0][f 3 1 1 0 0 16072]Yeah. I've fought tons of Shadows there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 6][f 3 1 1 0 0 0]Sounds a lot like Mementos and the[n]Palaces.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 16009]It's where we usually fight Shadows.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 6][f 3 1 1 0 0 0]Sounds a lot like Mementos and the[n]Palaces.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23033]Hey, we've never seen Tartarus before,[n]so we can't say that for sure.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]But if it's a nest for Shadows, it's[n]probably pretty similar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 16039][f 6 1 2 0 0 4]Palaces... Is that where you do most of[n]your phantom thief stuff?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 18 1 0][f 3 1 1 0 0 0]Yeah. Warped desires can cause[n]someone to form a Palace in their heart.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0]The core of those desires rests deep[n]within that Palace... And that's the[n]Treasure we're after.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 1 0][f 3 1 1 0 0 16086]So that's why you're called the Phantom[n]Thieves that steals hearts...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's all so unbelievable.[n][f 1 3 65535][f 1 1][e]

[sel SEL_011 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]The feeling's mutual.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]You still don't believe us?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]The same goes for SEES.[f 2 7 1 20 0 32][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 3 6][f 3 1 1 0 0 21031][f 6 1 2 0 0 4]You said it. What about all that crap[n]with the Tartarus and the Dark Hour?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 6][f 3 1 1 0 0 0]That sounds way more farfetched, man.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 16078]Well, as a member of SEES, I'm pretty[n]used to hearing crazy stories...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 0][f 3 1 1 0 0 0]But all this stuff about phantom thieves[n]is just...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 6][f 3 1 1 0 0 0][f 3 1 6 0 0 500]I get you. It does sound like something[n]straight out of a comic book.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 3 6][f 3 1 1 0 0 21031]I know, right? You're an extracurricular[n]squad of students who fight Shadows[n]during an hour nobody knows about...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]That sounds way crazier than anything[n]on our end.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 0 3 6][f 3 1 1 0 0 0]Hey, we've still got a lot of work to do.[n]We'd better keep moving.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 1][f 3 1 1 0 0 22122][f 6 1 2 0 0 6]Yeah, you're right. Let's stay focused for[n]these last two![n][f 1 3 65535][f 1 1][e]

