[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 2 1][f 3 1 1 0 0 54115]Welcome back, everyone.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It appears you had a successful hunt.[n]Congratulations.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]This is the reward for this time. Please[n]accept it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 1][f 4 6 13 12 0 3][f 3 1 1 0 0 13024]Thanks for your help,[n][f 6 1 26 0 0 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm sure the versions of us in your[n]world can rest easy knowing you're[n]in charge.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19030]Hehe... I hope so.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]It helps when everyone here is just as[n]supportive![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 18 1 0 6][f 4 6 12 2 0 3][f 3 1 1 0 0 12031]All I can really do is train and keep[n]fighting... Still, I'll do my best to help[n]out.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And, Shinji, I won't force you, but if[n]you're ever interested in training, just[n]let me know, and I'll make us a routine![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 18008]Yeah, yeah. When the time comes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 4 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19130][f 6 1 2 0 0 7]*giggle* We're counting on you guys![n][f 1 3 65535][f 1 1][e]

