[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 3][f 3 1 1 0 0 54125]The objective of this next special[n]screening is quite simple.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You must defeat one of the KNS-1000s[n]found within "A.I.G.I.S."[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 1][f 3 1 1 0 0 0]I take it, by "KNS-1000," you mean the[n]surveillance-type FOE, correct?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15071]I see. A troublesome opponent indeed.[n]However, I do possess some data on[n]said enemy.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]This is a perfect opportunity to[n]calibrate my energy levels.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Aigis, do you still need some time?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15074]Nonsense. All systems are functioning[n]properly.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However, I was not designed to fight in[n]these films.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]In order to see that we accomplish our[n]missions, I must acquire some combat[n]experience.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Are you okay?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Don't push yourself.[f 2 7 1 64 0 32][e]

[msg MSG_006 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15023]I appreciate the sentiment,[n][f 6 1 30 0 0 0]-san.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However, I am an anti-Shadow weapon.[n]My duty is to protect all of you.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]More difficult battles surely lie ahead,[n]and if I am to protect you, I will need to[n]be prepared.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 6][f 3 1 1 0 0 22047]That's... pretty cool.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]We'll work together.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Don't bear it all by yourself.[f 2 7 1 64 0 32][e]

[msg MSG_009 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 10 0 1][f 3 1 1 0 0 15017][f 6 1 2 0 0 4]Work... together?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 0][f 6 1 30 0 0 0] is right, Aigis. We're[n]a team.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]There's no need for you to bear it all by[n]yourself. We'll work together.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 1][f 3 1 1 0 0 15069]Understood! Then, let us all go to the[n]special screening together![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 6 0 1][f 3 1 1 0 0 0]Is that a no? I was hoping to provide[n]assistance...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 0][f 6 1 30 0 0 0] is right, Aigis. You[n]don't have to bear it all to yourself.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]We're a team. We should all work[n]together.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 1][f 3 1 1 0 0 15030]Thank you, both of you. Let us all do our[n]best![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2006]Okay, [f 6 1 30 0 0 0], let's head[n]out once we're ready.[n][f 1 3 65535][f 1 1][e]

