[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 100 3][f 3 1 1 0 0 6509][f 3 1 6 0 0 500][f 6 1 2 0 0 3]Hmm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What's wrong?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 7 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]It looks like the road splits up ahead.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]One path continues east and makes a[n]big loop to the north...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 6][f 3 1 1 0 0 14503][f 3 1 6 0 0 500]And the other path leads due north and[n]makes a smaller loop.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Based on our position, that would be[n]the shorter of the two paths.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9016][f 6 1 2 0 0 6]Shorter it is! Everyone follow me![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 12 1 0][f 3 1 1 0 0 23082]Wait. The shortest path isn't always the[n]best option.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 0][f 3 1 1 0 0 0]If experience has taught me anything,[n]it's that the easy path tends to be a[n]trap...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9090]Lecture, lecture, lecture... If this were a[n]complaining contest, you'd win hands[n]down.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23034][f 6 1 2 0 0 2]Who's complaining!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Well, I think you could make a case for[n]either. Which path do you think we[n]should we take, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]The shorter path.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]The longer path.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]We need more info.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9029][f 6 1 2 0 0 6]See? What'd I tell you!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23029][f 6 1 2 0 0 6]I knew you'd understand, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 22013]Yeah, it'd be nice if we knew a little[n]more about what's waiting for us down[n]each path.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 17 12 0 1][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]Bark, bark![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hm? What is it, Koromaru?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 4][f 3 1 1 0 0 0]He seems to be saying he can smell[n]something down each path.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 4019]Really? I don't smell anything.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And I'm pretty sure I could pick up the[n]smell of meat from anywhere within a[n]mile and a half of this place.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 6 0 1][f 3 1 1 0 0 3094][f 6 1 2 0 0 9]There goes the meat freak... Like that's[n]anything to be proud of.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 0]Koromaru has a much better sense of[n]smell than us, so he might actually be[n]onto something.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 6][f 3 1 1 0 0 26517][f 3 1 6 0 0 500]There's no real way to tell from here.[n]We'll have to get closer.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You'll wanna get as much info as you[n]can before you make a decision.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 1][f 3 1 1 0 0 9067]I say we check out the shorter path first![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Let's gooo![n][f 1 3 65535][f 1 1][e]

