[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54007]The objective of this special[n]screening...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Is to clear the specified floor of[n]A.I.G.I.S.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 3][f 3 1 1 0 0 0]That's it? We already know that floor[n]pretty well. Won't this be easy?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54036]But one must remember that you[n]cannot judge a book by its coveralls.[n]Things are not always as they seem.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As such, the layout of the floor has[n]become terribly complex.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Your task is to navigate the labyrinthine[n]passages and return safely.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]What happened?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Who's responsible for this?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54084]Well... I'm afraid I don't have further[n]details on the matter.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 3][f 3 1 1 0 0 0]When you say the layout's become[n]complex... How exactly did it change?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Well... If I were to give a more visual[n]example, it now resembles Junpei's[n]room.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 6][f 3 1 1 0 0 10095]Ugh, that's already more than I[n]wanted to know.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 10 0 3][f 3 1 1 0 0 0]Ngh... You mean to say we have to[n]navigate such a nightmare?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]Um, guys? Words can hurt too, y'know.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 69 12 0 1][f 3 1 1 0 0 25112]There's no point discussing it here.[n]Let's go in and see for ourselves.[n][f 1 3 65535][f 1 1][e]

[sel SEL_011 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Agreed.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]We're gonna get lost...[f 2 7 1 64 0 32][e]

[msg MSG_012 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 6][f 3 1 1 0 0 27068]Right. We have a splendid map, and[n]helpful navigators besides![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 6][f 3 1 1 0 0 26107]Don't worry. You already got a map,[n]and we'll be navigating for you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 1][f 3 1 1 0 0 0]Yeah, we'll be here to support you.[n]Make sure to come straight back if[n]it gets too rough out there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 23072]All right! Then it's settled.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It might be a long trek, and we might[n]get lost. Make sure we're prepared.[n][f 1 3 65535][f 1 1][e]

