[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 25 12 0 1][f 3 1 1 0 0 25109]Whew, we've covered a lot of ground.[n]I think a break would do us good―[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]W-What!? An earthquake? Are we[n]under attack?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 12 16 1 0][f 4 6 4 0 2 0][f 3 1 1 0 0 4107][f 6 1 2 0 0 6]Here goes! The Satonaka-style secret[n]art... Dragon Kiiick![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Not bad! But too slow![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0]You're amazing, Master! You were so[n]fast, I didn't even see you move![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031]You've got a pretty amazing kick[n]yourself, Chie. If I'd taken that head-[n]on, I would've been sent flying.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]What are you two doing!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 0]Nothing to worry about! Just doing[n]some training. A little mock battle[n]to get the blood pumping.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Someone'll get hurt...[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Now that's diligence.[f 2 7 1 20 2 32][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4051][f 6 1 2 0 0 6]Don't sweat it. We're used to this![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]You may be used to this, but I'M not...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25091][f 6 1 2 0 0 9]I'm glad to see you so proactive,[n]but do you really need to train[n]all the way out here?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 0][f 3 1 1 0 0 0]Huh... Maybe we overdid it a little,[n]but I just couldn't contain myself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Heheh, I know what you mean. You[n]gotta eat well, and fight well. That's[n]how you become the strongest![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25011][f 6 1 2 0 0 4]Is this all you two ever―I mean,[n]do you always train this hard?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hmm, my usual routine is to do some[n]running, then I practice my kicks...[n]Finally, I wrap up with a beef bowl![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 0]Yeah. You gotta launch your body[n]into a tough workout, then seal the[n]deal with a healthy bite of protein.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 7 0 0][f 3 1 1 0 0 25091][f 6 1 2 0 0 3]*sigh*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Recklessly swinging at each other[n]isn't training. You have to think about[n]training your mind, too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The same applies to your diet. You[n]can't just eat protein and nothing else.[n]You have to think about balance.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 7 1 0][f 3 1 1 0 0 12075]Oh, that's right! You practice aikido,[n]right, Queen? Well, I can't deny the[n]insight of a fellow fistfighter...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]So I'm part of this now, too, am I...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 4115][f 6 1 2 0 0 4]...Oh! I just had a totally great idea![n]What if Queen comes up with a[n]new training course for us?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Good point. If we train the same way[n]all the time, we'll get too used to it.[n]Can you help us, Queen?[n][f 1 3 65535][f 1 1][e]

[sel SEL_022 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Give it a try.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]You can do it.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Sounds like fun.[f 2 7 1 20 2 32][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 25014]I suppose I could...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]But if I'm going to do that, I need to[n]gauge everyone's strength so I can[n]come up with realistic milestones...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25053][f 6 1 2 0 0 9]Oh, not you too... Though I suppose[n]I wouldn't mind teaching you.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]But if I'm going to do that, I need to[n]gauge everyone's strength so I can[n]come up with realistic milestones...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25036][f 6 1 2 0 0 9]Is this really the time to say that?[n]Well, I suppose I don't mind teaching[n]you...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]But if I'm going to do that, I need to[n]gauge everyone's strength so I can[n]come up with realistic milestones...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 0][f 3 1 1 0 0 0]Oh, Queen! Mitsuru-san says we[n]should head out soon.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 0][f 3 1 1 0 0 0]Okay, we should get going for now.[n]We can discuss your regimen[n]another time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 4][f 3 1 1 0 0 4132][f 6 1 2 0 0 6]You got it, Coach![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 25 0 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]...Coach?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 4][f 3 1 1 0 0 0]Um, okay then... Let's go.[n][f 1 3 65535][f 1 1][e]

