[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 1 100 1][f 4 6 80 2 0 4][f 6 1 2 0 0 7][f 3 1 1 0 0 56028]Eff, eff, FOE. Now that it's crushed,[n]ex-FOE...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 6 1 2 0 0 9][f 3 1 1 0 0 0]...I'm terribly sorry. It appears my[n]brother is overcome with delirium.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]You're the one who told me to do this![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 74 12 100 1][f 3 1 1 0 0 54026]You have successfully executed the[n]executioner! Scrapped it to scrap[n]metal![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It appears you can take on any[n]obstacle the enemy throws[n]at you...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hm...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 3 1 1 0 0 11108]Grrrraah! Junpei Iori's not outta the[n]game yet![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Kanji]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 3 1 1 0 0 7131]Ngaaahhh! I ain't gonna lose![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 3 1 1 0 0 0]Whoa![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Kanji]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 3 1 1 0 0 0]Wh-Whoa![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 1][f 3 1 1 0 0 23091]Yikes, that was a pretty bad fall...[n]Rest in peace, guys.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 0]Hah! Careful there. Even when you're[n]at your limits, you gotta stay focused.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Guh, hah... Not bad... Junpei-san.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Thought you... dropped out...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 1 3][f 3 1 1 0 0 11102][f 6 1 2 0 0 10]Phew... I, uh... I'm not sure, but...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've got... someone... I gotta protect.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So... I still... gotta get stronger.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 2 6][f 3 1 1 0 0 7048]Man, Junpei-san...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 8 2 6][f 3 1 1 0 0 0]Maybe I was wrong about you.[n]You got some real grit after all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 3][f 3 1 1 0 0 0]Huh...? Maybe that was too serious...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 3][f 3 1 1 0 0 0]Bah, nevermind! I better get back to[n]the jokes. Can't just be Junpei, the[n]Straight-faced Detective![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 14 1 6][f 3 1 1 0 0 7092]Man, don't get embarrassed by that![n]You got something you wanna[n]protect, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Then let's get even stronger![n]Akihiko-san can help us![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 3][f 3 1 1 0 0 0]Uh, well... Maybe that can wait until[n]next time...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 7 1 0 0][f 4 6 12 12 0 1][f 3 1 1 0 0 12029][f 6 1 2 0 0 6]I heard it all![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0]Already made you a training regimen.[n]I've got it covered![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 0]I said next time! Didn't you hear[n]THAT part!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 2 6][f 3 1 1 0 0 0]Junpei-san... You got this! I'm[n]cheerin' for ya![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 12032]Don't worry, Kanji. I've made you a[n]training regimen too![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]...What?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 1][f 3 1 1 0 0 0]Now, let's start with warmups![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]One thousand squats! Go![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 3][f 3 1 1 0 0 11104][f 6 1 2 0 0 1]Noooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Kanji]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 3][f 3 1 1 0 0 0]Wh-Why meeee!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 12 0 1][f 3 1 1 0 0 0]They're having so much fun. I guess[n]this is what they call "teen spirit"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2065]And off they go into the sunset.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 4][f 3 1 1 0 0 0]I'm not sure being a teenager usually[n]involves this much screaming...[n][f 1 3 65535][f 1 1][e]

