[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 54002]Thank you all for waiting.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I would like to let you know that the[n]special screening you all requested[n]is now ready.[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Wait, what request?[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]I don't remember...[f 2 7 1 64 6 32][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 100 0][f 3 1 1 0 0 54023]Hm? How curious...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]I was sure I heard you all wanted[n]to fight an FOE in Hikari's movie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 1 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]The FOE in my movie...? You mean[n]the cute teddie bear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 9043][f 6 1 2 0 0 8]Oh, over here! You were looking for[n]a beary adorable Teddie bear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 0]Oh, not you, Teddie... It is a bear, but[n]it's the bear from my movie, so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 11]Awww... How can Hikarin bear that[n]unbearable ab-bearation, but still[n]think I'm overbearing...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Just grin and bear it, Teddie.[n]That bear bear-ly has the bearlike[n]bearing you bear.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 6][f 3 1 1 0 0 0]Approaching speeds of fifteen[n]bears per minute.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3111]Look, jokes aside... Are we seriously[n]fighting this bear? Who even put in[n]that request...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54059]Why, Teddie here assured me that[n]everyone already agreed to this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 9 0 0 3][f 3 1 1 0 0 0]Hrmm... I guess I did say that.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 0]It was you!? You can't just make[n]these decisions on your own![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 3][f 3 1 1 0 0 0]Aw, c'mon! Don't you guys want to[n]find out who's the bearest of them[n]all?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 1][f 3 1 1 0 0 0]Don't drag us into your weird[n]bear complex![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1087]Don't get too worked up, Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015_1 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]It'll be a powerful opponent, but it's[n]always good when we can learn[n]from a tough fight.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 8 1 0][f 3 1 1 0 0 0]Well, yeah... I guess so, but...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 6][f 3 1 1 0 0 0]Right. Teddie-san, you aim to[n]prepare yourself for even greater[n]battles ahead, do you not?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 3][f 3 1 1 0 0 9030]Absolutely, positively! Sensei, Ai-chan,[n]you two totally get me![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]*sigh* ...You seriously need to learn[n]when to stop talking.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]A fight against that bear FOE, huh...?[n]What do you say, [f 6 1 30 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_021 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Let's take it on.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Might as well.[f 2 7 1 64 4 32][e]

[msg MSG_022 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 3][f 3 1 1 0 0 9041][f 6 1 2 0 0 7]Yaaay! That settles it! This bear's[n]all hyped up and ready to go![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0]Sorry about this. We didn't mean[n]to drag you into our dumb bear's[n]shenanigans.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 74 0 100 1][f 3 1 1 0 0 54059]Has it been decided?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Let us begin! It's time for a Teddie[n]Showdown! Double bear-relled[n]battle! Lights, camera, action![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Action![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 3][f 3 1 1 0 0 0]23 bears-per-minute action![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 6][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Uh, are we making this a thing...?[n]Action![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 4 0 3][f 3 1 1 0 0 61194]You're going up against a pretty[n]tough bear. It sure will be action![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 3101][f 6 1 2 0 0 9]Ugh... now "bear"'s lost all meaning...[n][f 1 3 65535][f 1 1][e]

