[msg MSG_000 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 9042][f 6 1 2 0 0 1]Hooray! We did it![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 3][f 3 1 1 0 0 15040]Congratulations, Teddie-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_1 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 0][f 3 1 1 0 0 0]You have vanquished all lesser bears,[n]and rightfully claimed the title of[n]"bearest of them all."[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Thank you, Ai-chan! I couldn't have[n]done it without everyone's help![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1071]It was a good battle. That finishes[n]the mission, too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Sensei, I did it! Aw, I can't let anyone[n]see me cry now that I'm a bear[n]legend...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 4][f 3 1 1 0 0 6530][f 3 1 6 0 0 500]Hahaha... You did great, Teddie.[n]You can come home now![n][f 1 3 65535][f 1 1][e]

