[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 19 2 3 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19044][f 6 1 2 0 0 1]Yes! We beat it, guys![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]You really carried us through that fight,[n]Joker. I'd say that makes you our[n]leading man![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 1][f 3 1 1 0 0 27004][f 6 1 2 0 0 4]Oh? What's this...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]There's something on the ground...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]That Shadow must have dropped this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 4][f 3 1 1 0 0 25021][f 6 1 2 0 0 4]Isn't it a piece of film? It's almost[n]completely covered in soot, though...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0]Whatever else it is, it counts as[n]a trophy of our victory![n][f 1 3 65535][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Obtained Sooty Film![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 0][f 3 1 1 0 0 25067]Well, we've accomplished our goal.[n]Let's go report to Elizabeth.[n][f 1 3 65535][f 1 1][e]

