[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 0 1][f 3 1 1 0 0 0]I'm calling it here! This match is over.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 4][f 3 1 1 0 0 56028]Well fought. I suppose that's my win.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_1 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]If you'd like another bout once you've[n]grown stronger, I'll happily accept a[n]challenge anytime.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 54059]If you wish for a return match, please[n]speak to me at the box office.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 1 0 0][f 3 1 1 0 0 0]Until next time, then.[n][f 1 3 65535][f 1 1][e]

