[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54029]Well, everyone, the time has finally[n]come.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You've acquired four pieces of film.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Of those, three have regained their[n]shine, and only one remains sooty...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 3][f 3 1 1 0 0 0]So, once we display our ability to[n]one last arbiter of power...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 0][f 6 1 30 0 0 0]'s power of the wild[n]card will change somehow.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 3][f 3 1 1 0 0 3085][f 6 1 2 0 0 6]I dunno if I got all that, but what it[n]comes down to is that something[n]crazy's gonna happen, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 1][f 3 1 1 0 0 0]Loosely speaking, I suppose that's[n]about right...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 54039]Now then! Answer the following![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 0 3][f 3 1 1 0 0 14064]Aah! You surprised me...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 0][f 3 1 1 0 0 0]In this crucial moment of fate,[n]who shall appear as the next[n]governor of power?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Uh, what's she getting all worked up[n]about? Does she even need to ask?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 6][f 3 1 1 0 0 11091]Nah, I think this one's more about the[n]showmanship.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]I can't hear you! Anyone?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Well then! You're the leader here,[n][f 6 1 30 0 0 0]. Let's have you answer![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 23 0 3 6][f 3 1 1 0 0 23091][f 6 1 2 0 0 9]Hey, you should probably answer...[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 64 1 0 3]Elizabeth![f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]Elizabeth?[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]Elizabeth!?[f 2 7 1 64 12 0][e]

[msg MSG_013 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 100 0][f 3 1 1 0 0 54001]My, what a shock! You are correct![n]I suppose you aren't a leader for[n]nothing, [f 6 1 30 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_013_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]I, Elizabeth, shall strive to prove[n]myself worthy of this honored role.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013_2 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Then, let us go to the Velvet Room,[n]and we shall―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...Ah, but before that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 6][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19020]Huh...? Where's she going?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Is that the Kamoshidaman sign?[n]What's she doing over there...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 0]Retrieving something from behind it,[n]apparently.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 0][f 4 6 11 10 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Hot dogs...? Wait, that's where she[n]was hiding hers!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Whoa. She's just... gonna eat 'em[n]all right now, huh.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]Oh, she's coming back...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 54038]Pardon my stepping away. I am now[n]fully charged and ready to fight![n][f 1 3 65535][f 1 1][e]

[msg MSG_018_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0]Once you are likewise ready, please[n]speak to m―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]*burp*[n][f 1 3 65535][f 1 1][e]

[sel SEL_019 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]We're ready whenever.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]We need some time.[f 2 7 1 64 6 32][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 54059]Understood. Then let us move to[n]a more suitable location.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54059]Understood. By all means, make[n]sure you're fully prepared.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]Are you prepared to do this?[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]I am.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]I need a bit more time.[f 2 7 1 64 6 32][e]

[msg MSG_024 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54059]Understood. Then let us move to[n]a more suitable location.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54059]Understood. I shall wait for as long[n]as you require.[n][f 1 3 65535][f 1 1][e]

