[msg MSG_000 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 1][f 3 1 1 0 0 14001][f 6 1 2 0 0 4]Rise, Futaba... 夷Podr胤a tener un[n]momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 70 1 0 6][f 4 6 6 0 0 3][f 3 1 1 0 0 0]夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 0][f 3 1 1 0 0 0]Um... Tenemos muchos combates por delante en[n]este mundo, as胤 que...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Creo que es seguro decir que tendremos grandes[n]batallas por delante, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26068][f 6 1 2 0 0 6]Seguro. Estoy recibiendo un mont吋n de "jefe[n]final que viene" vibraciones.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 7 0 0][f 3 1 1 0 0 0]As胤 que... estaba pensando que todos van a[n]necesitar nuestro apoyo m茨s que nunca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 70 1 0 0][f 4 6 6 0 0 0][f 3 1 1 0 0 6016][f 6 1 2 0 0 4]Vale, 夷quieres mejorar nuestra energ胤a de[n]navegaci吋n de alguna manera?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤. Quiero ver si hay algo que podamos hacer[n]para construir nuestro poder en algo[n]m茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Como entrenar en una c茨mara de tiempo[n]hiperb茨rica! 斡Podr胤a entrar en eso![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0]Oh, pero s吋lo para m胤, no estoy sentado bajo[n]ninguna cascada. Lo que hagamos, ser茨[n]mejor que no sea trabajo manual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 0 0][f 3 1 1 0 0 6009][f 6 1 2 0 0 3]La mayor parte de nuestra navegaci吋n es a[n]trav姻s de nuestras Personas. Supongo que[n]no podemos mejorar tan f茨cilmente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 0]S胤, no es como si pudi姻ramos conectar a un[n]drag吋n con una colecci吋n de bolas a cambio[n]de m茨s poder...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]... Pero tal vez haya alguna clase de potencia[n]que podamos usar. 夷O algunos[n]tramposos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 6 1 0 0][f 4 6 14 10 0 0][f 3 1 1 0 0 14115]Ya sabes... Esto fue antes de unirme al[n]Escuadr吋n de Ejecuci吋n Extracurricular[n]Especializado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mitsuru-senpai realiz吋 tareas de navegante[n]utilizando una m茨quina que ayud吋 a amplificar[n]sus habilidades de b雨squeda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Le ayud吋 a buscar mejor? 夷As胤 que fue como[n]un radar personal?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 0][f 3 1 1 0 0 14071]S胤. Era alg雨n tipo de m茨quina, pero ayud吋 a[n]refinar sus poderes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 0][f 3 1 1 0 0 0]Obviamente no podemos usar Mitsuru-senpai,[n]pero si pudi姻ramos dise隠ar un sistema de[n]comunicaciones similar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 0][f 3 1 1 0 0 6072]斡Oh! 斡Es una buena idea! A veces parece que[n]realmente tenemos problemas para[n]contactarlos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No ser胤a genial si tuvi姻ramos alguna m茨quina[n]de comunicaci吋n que nos dijera lo que[n]todos estaban haciendo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 0]Estoy de acuerdo. Y creo que puedo hacer uno,[n]si podemos encontrar las partes[n]correctas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 26116]Si necesitas partes, la pel胤cula de Ribbon[n]podr胤a ser un buen lugar para ver.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hay una tonelada de Sombras y FOEs all胤 que[n]probablemente dejar胤a cosas que podemos[n]usar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 3 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]No s姻 si funcionar茨, pero definitivamente[n]vale la pena intentarlo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Por qu姻 no empezamos ahora? 斡Esperen aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 3 0 0][f 4 6 70 6 3 6][f 3 1 1 0 0 26055][f 6 1 2 0 0 4]斡Hola! 夷Ad吋nde vas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6030][f 6 1 2 0 0 6]斡Soy baaack![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 2 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Rise, 夷eso es...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 0][f 3 1 1 0 0 0]Le cont姻 a Elizabeth nuestra historia y la[n]hice hacer un boleto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Pedimos una petici吋n! "Por favor, recoge[n]una maquinaria"![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 4][f 3 1 1 0 0 26062]斡GJ Rise![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Buscar esas partes por nuestra cuenta habr胤a[n]sido como jugar en modo arriesgado![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Bueno, ten en cuenta que ni siquiera pueden[n]recogerlo, pero podemos ser pacientes,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 14069][f 6 1 2 0 0 6]Definitivamente. 斡Espero que acepten nuestra[n]solicitud pronto![n][f 1 3 65535][f 1 1][e]

[msg MSG_024]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "Red Social"[n]se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

