[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 0 1][f 4 6 76 0 1 4][f 3 1 1 0 0 56025]Nada menos que incre胤ble. Acepto mi p姻rdida.[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Nos diste una dura pelea.[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]Eso fue una brisa.[f 2 7 1 64 2 32][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 56028]Eres muy amable. S吋lo espero que podamos[n]tener otro combate alg雨n d胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 56043]斡Me alegro de o胤rlo! Has crecido bastante[n]fuerte, m茨s de lo que hab胤a anticipado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 8 1 0][f 3 1 1 0 0 0]Entonces, 夷est茨s acabado, hermana? 夷Por qu姻[n]me pediste semejante pelea?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 10 0 0][f 3 1 1 0 0 0]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]La pel胤cula que parec胤a sooty est茨 brillando[n]d姻bilmente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hey, la pel胤cula va todo brillante![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 3][f 3 1 1 0 0 24047]Es d姻bil, s胤... pero lo extra隠amente hermoso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 0 1][f 3 1 1 0 0 0]Es como pens姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 0]Cuando adquiriste la pel胤cula, no fue nada[n]m茨s que un simple pedazo de basura...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero a trav姻s de su portador mostrando[n]suficiente poder, creo que recuperar茨 su brillo[n]original.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 4][f 3 1 1 0 0 0]斡Ya veo! As胤 que esa fue tu intenci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 30 0 0 0]Reclamaba la victoria contra m胤, y al hacerlo,[n]mostraba una gran fuerza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 71 12 0 1][f 3 1 1 0 0 0]Um, you said this film is related to[n][f 6 1 29 0 0 0]-kun's power of the wild[n]card, correct?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 1 0 0][f 3 1 1 0 0 27131][f 6 1 2 0 0 4]夷Qu姻 tal, [f 6 1 29 0 0 0]? 夷Te sientes[n]diferente?[n][f 1 3 65535][f 1 1][e]

[sel SEL_011 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]No, en realidad no.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]El poder fluye a trav姻s de m胤...[f 2 7 1 64 2 32][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 72 12 0 1][f 3 1 1 0 0 28013]Mmm... Tengo que decir que no veo mucho cambio[n]en el exterior.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 72 12 0 1][f 3 1 1 0 0 28018]夷En serio? Te ves igual que nunca...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Grrrr... estoy bastante agitado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 0 0][f 3 1 1 0 0 54037]夷Podr胤a haber sido mal mi juicio? No, eso no[n]puede ser...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 8 1 4][f 3 1 1 0 0 0]No debes perder la esperanza, hermana.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Los combat胤 como 茨rbitro del poder, y al[n]hacerlo, la pel胤cula claramente sufri吋 alg雨n[n]cambio.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que al menos, tu conjetura estaba cerca[n]de la verdad, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 3][f 3 1 1 0 0 0]Cierto. Hay varias posibilidades para esto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷No es la 雨nica pel胤cula de su tipo? Si[n]recogemos m茨s...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 0 1][f 3 1 1 0 0 54035][f 6 1 2 0 0 6]...![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 3][f 3 1 1 0 0 25009]We found this film after a special[n]screening where we needed[n][f 6 1 30 0 0 0] to fight, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 0][f 3 1 1 0 0 0]Podr胤a ver que hay otros ex茨menes como 姻l,[n]tal vez tambi姻n requerir gente[n]espec胤fica...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 74 12 1 0][f 3 1 1 0 0 0]Por un momento, me di a la desesperaci吋n.[n]Sin embargo, ahora veo un mundo de[n]posibilidades que se abre ante m胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 0]Bueno, esperemos hasta que encontremos estos[n]otros ex茨menes. Las posibilidades son[n]ilimitadas, despu姻s de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ahaha... Ella retrocede r茨pido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 74 12 0 0][f 3 1 1 0 0 0]En cualquier caso, [f 6 1 30 0 0 0]... T雨 y[n]tus aliados han puesto una maravillosa[n]exhibici吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tu pelea contra Theo estaba separado de los[n]espect茨culos especiales, pero he preparado[n]una humilde recompensa para ti.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Por favor aceptelo m茨s tarde, como muestra[n]de gratitud de nosotros que gobiernan el[n]poder.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 6][f 3 1 1 0 0 21045][f 6 1 2 0 0 7]夷De verdad? 斡Muchas gracias, se隠ora![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 2 0 0][f 3 1 1 0 0 0]*chuckle* No, gracias.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Nada nos complace m茨s que ver su crecimiento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Theodore]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 76 2 0 4][f 3 1 1 0 0 56060]De hecho. Debo agradecerte tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 1 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 1 1][f 3 1 1 0 0 0]夷Entonces, Theo? 夷C吋mo les recompensar茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 8 1 4][f 3 1 1 0 0 0]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54004]T雨 gobiernas el poder, igual que yo. 夷Tienes[n]alg雨n tipo de regalo para ofrecer por[n]sus problemas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]夷Eh? Bueno, esto es tan repentino..[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 1 0][f 3 1 1 0 0 0]No vas a avergonzar a tu hermana, 夷verdad?[n]斡Adelante![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 8 1 1][f 3 1 1 0 0 56011]斡Lo s姻! 夷Qu姻 tal esto?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 1 0 0][f 4 6 76 2 0 1][f 3 1 1 0 0 0]Te dar姻 una de mis mayores creaciones, algo[n]que he hecho con el m茨ximo cuidado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 3][f 3 1 1 0 0 0]斡Estamos recibiendo una maestr胤a certificada[n]de Theodore! Entonces, 夷qu姻 es?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Nada menos que una obra maestra. Presento el[n]orgullo de mi oficio...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡El Hot Dog Artesanal al Estilo Terciopelo![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 74 1 0 1][f 4 6 76 1 0 4][f 4 6 71 12 0 3][f 3 1 1 0 0 27011][f 6 1 2 0 0 4]...Um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 3][f 3 1 1 0 0 5017]...夷Un hot dog? 夷Tu obra maestra es simplemente una salchicha en un pan...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 0]S胤. Es maravillosamente adecuado para emparejar[n]con ver pel胤culas! Por favor, prueba[n]uno hoy.[n][f 1 3 65535][f 1 1][e]

[sel SEL_036 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]夷Publicidad un nuevo producto?[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]No puedo esperar.[f 2 7 1 64 2 32][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 3][f 3 1 1 0 0 26015]S胤, esto parece un infomercial. Tal vez perdi吋[n]su vocaci吋n de vendedor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 1][f 3 1 1 0 0 56029]Gracias. Su anhelo reivindica todos mis[n]esfuerzos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 0 0 1][f 3 1 1 0 0 0]Era muy particular acerca de la relaci吋n de[n]la carne, el nivel de tostada de bun, y[n]el volumen 吋ptimo de ketchup.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 1][f 3 1 1 0 0 0]斡Ha sido un 姻xito con mis hermanas tambi姻n![n]Estoy seguro de que no decepcionar茨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 3][f 3 1 1 0 0 0]Necesitas un cambio de carrera, Theodore...[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 76 8 1 0][f 3 1 1 0 0 56104]Hermana, creo que robaste todo el lote de hot dogs que acabo de terminar de hacer...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷No vas a donar algunos en mi nombre, junto[n]con tu recompensa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 1 0 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 0]Gracias a Dios, se ha evitado una crisis.[n]Usted pregunt吋 en el momento perfecto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Afortunadamente, tengo uno que queda a mano.[n]Te lo presento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 1 0][f 3 1 1 0 0 56052]夷S吋lo queda uno? 夷No me digas que ya has[n]devorado el resto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 64 1 0 3][f 4 6 74 12 0 0][f 3 1 1 0 0 54007]斡Ahora! Como este caso ha sido perfectamente[n]envuelta, llamemos a esta reuni吋n por[n]ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Seguir姻 investigando la verdadera naturaleza[n]de esa pel胤cula.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]En particular, permanecer姻 en la b雨squeda de[n]ex茨menes especiales que exijan la[n]participaci吋n de alguien.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 1 0][f 3 1 1 0 0 0]Bueno, entonces, hasta la pr吋xima vez.[n][f 1 3 65535][f 1 1][e]

[msg SYS_MES_000]
[f 0 5 65278][f 2 1]El efecto del [f 4 4 3 0 1593] aument吋 su stock de Persona por [f 0 1 2][n][f 2 4 0][f 0 1 0][n].[n][f 1 3 65535][f 1 1][e]

