[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 701][f 6 1 3 0 0 2]Well then, everyone... I, Theodore,[n]will be your opponent.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 702][f 6 1 3 0 0 2]Allow me to witness your strength[n]firsthand.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 703][f 6 1 3 0 0 2]Hm... I see. You fascinate me[n]almost as much as popcorn.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 704][f 6 1 3 0 0 2]But this is nowhere near the extent[n]of your power, is it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 705][f 6 1 3 0 0 2]I do take a certain pride in my[n]strength. And that pride will not[n]allow me to falter so soon.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 706][f 6 1 3 0 0 2]Impressive... Ah, but the compliments[n]can wait until the dust has settled.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 707][f 6 1 3 0 0 2]Now, allow me to witness the full[n]scope of your power.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 708][f 6 1 3 0 0 2]Magnificent... So this is your power...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 709][f 6 1 3 0 0 2]I have now witnessed it for myself.[n][f 1 3 65535][f 1 1][e]

