[msg MSG_BTL_TUTORIAL_842_ENC]
[f 0 5 65278][f 2 1]Reserved[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_101]
[f 0 5 65278][f 2 1]"Link Boost"[n]Teammates can provide assistance through[n]a [f 0 1 2]Link Boost[f 0 1 0], which is activated when[n]someone hits an enemy and the affinity of[n]the attack is one the enemy is weak against.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_102]
[f 0 5 65278][f 2 1]The Link Boost makes the next acting[n]party member gain two effects.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_103]
[f 0 5 65278][f 2 1]Continue attacking enemy weaknesses on[n]the same turn, and you'll be given more[n]and more Link Boost effects to choose from![n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_104]
[f 0 5 65278][f 2 1]Take advantage of this very useful chain[n]attack in order to gain an edge in battle.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_HP_]
[f 0 5 65278][f 2 1]Reserved[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_HP__2]
[f 0 5 65278][f 2 1]Reserved[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_HP__3]
[f 0 5 65278][f 2 1]Reserved[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_842_BTL]
[f 0 5 65278][f 2 1]Reserve[n][f 1 1][e]

