[msg MSG_000 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 6 2 1][f 3 1 3 0 0 101]HAHAHA![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 2 1 0][f 3 1 3 0 0 102][f 6 1 2 0 0 6]The pinnacle of absolute justice is here![n]You'd better be prepared, criminals![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 1 0][f 3 1 3 0 0 103]Heh! We'll show you the power of[n]the Phantom Thieves![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 6 2 1][f 3 1 3 0 0 105]HAHAHA![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 3 0 0 106][f 6 1 2 0 0 0]Our attacks aren't doin' shit!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 1 6][f 3 1 3 0 0 107]They seem to be hitting him, but...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 118][f 6 1 3 0 0 1]See? It's exactly as I said.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007_5 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 4 1 0][f 3 1 3 0 0 109][f 6 1 2 0 0 6]This is the power of absolute justice...[n]My power as the unquestionable ruler![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 3 0 0 113][f 6 1 2 0 0 0]Are we really powerless to him!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 1 1][f 3 1 3 0 0 108][f 6 1 2 0 0 3]It's like my body's gotten so tired[n]all of a sudden...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 3][f 3 1 3 0 0 114]Ngh, I can't move like I want to...[n]It's like I truly can't defy his will...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 6][f 3 1 3 0 0 115][f 6 1 2 0 0 10]Grrr... We're gonna be in real trouble[n]here![n][f 1 3 65535][f 1 1][e]

