[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 1][f 3 1 1 0 0 26635][f 6 1 2 0 0 0]Hmmm!? I'm getting a different reading[n]from that Shadow in the back...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I feel like something's up with it![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 0]A special Shadow, you say? How[n]interesting.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 24068]We can either focus our attacks on it[n]now or deal with the others first... The[n]decision is yours, Joker.[n][f 1 3 65535][f 1 1][e]

