[msg MSG_000 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 501][f 6 1 3 0 0 2]My presence is necessary to those who[n]flee reality. Defying me is so foolish...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 502][f 6 1 3 0 0 2]You are but puny, pitiful children to me.[n]Give up now, and cast yourselves away.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 99 1][f 3 1 3 0 0 503][f 6 1 2 0 0 6]Everyone, hold out as long as you can![n]We have to keeping playing that movie![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 0][f 3 1 3 0 0 504]We need the minds of the theatergoers[n]to change! Please![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 4][f 3 1 3 0 0 505][f 6 1 2 0 0 1]C'mon, you've gotta hang in there![n]We'll do our best over here too![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 506][f 6 1 3 0 0 2]Innumerable humans have come here,[n]craving structure and safety.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 507][f 6 1 3 0 0 2]Your resistance to my salvation is[n]nothing but utter conceitedness.[n][f 1 3 65535][f 1 1][e]

