[msg MSG_000 [Ryuji]]
ムメEs un callejポn sin salida?!

[msg MSG_001 [Ann]]
ムメNo hay ninguna salida?!

[msg MSG_002 [Yusuke]]
ムMira! メQu〒 es eso?

[msg MSG_003 [Ann]]
ムメEh?! Estホ brillando, pero... メQu〒...?

[msg MSG_004 [Futaba]]
ムEso es! Parece que podemos escapar,[n]ムpor ahボ! Y parece estar libre de[n]enemigos.

[msg MSG_005 [Ryuji]]
メEstホs segura?

[msg MSG_006 [Futaba]]
ムEso creo!

[msg MSG_007 [Ryuji]]
ムメEso crees?!

[msg MSG_008 [Morgana]]
メQu〒 hacemos, Joker? No hay otra salida.[n]メDebemos ir por allボ?

[sel SEL_009 top]
Hagホmoslo.
Qu〒 deberボamos hacer...

[msg MSG_010 [Futaba]]
ムOye, no hay tiempo para pensar! ムEsa[n]Sombra se estホ acercando muy rホpido!
...ムEstホ justo ahボ!

[msg MSG_011 [Ryuji]]
ムメQU※ DEMONIOS ES ESO?!

[msg MSG_012 [Yusuke]]
ムNunca he visto nada igual en mi vida!

[msg MSG_013 [Futaba]]
Estoy sintiendo un poder enorme en 〒l...[n]ムEs demasiado peligroso para nosotros!

[msg MSG_014 [Morgana]]
No hay tiempo para pensarlo. Retirarnos[n]es nuestra マnica opciポn.

[msg MSG_015 [Ryuji]]
ムMaldita sea, parece que estamos todos[n]dentro!

[msg MSG_016 [Morgana]]
ムSalten!

