[msg MSG_000 [Ryuji]]
斡夷Es un callej吋n sin salida?!

[msg MSG_001 [Ann]]
斡夷No hay ninguna salida?!

[msg MSG_002 [Yusuke]]
斡Mira! 夷Qu姻 es eso?

[msg MSG_003 [Ann]]
斡夷Eh?! Est茨 brillando, pero... 夷Qu姻...?

[msg MSG_004 [Futaba]]
斡Eso es! Parece que podemos escapar,[n]斡por ah胤! Y parece estar libre de[n]enemigos.

[msg MSG_005 [Ryuji]]
夷Est茨s segura?

[msg MSG_006 [Futaba]]
斡Eso creo!

[msg MSG_007 [Ryuji]]
斡夷Eso crees?!

[msg MSG_008 [Morgana]]
夷Qu姻 hacemos, Joker? No hay otra salida.[n]夷Debemos ir por all胤?

[sel SEL_009 top]
Hag茨moslo.
Qu姻 deber胤amos hacer...

[msg MSG_010 [Futaba]]
斡Oye, no hay tiempo para pensar! 斡Esa[n]Sombra se est茨 acercando muy r茨pido!
...斡Est茨 justo ah胤!

[msg MSG_011 [Ryuji]]
斡夷QU畏 DEMONIOS ES ESO?!

[msg MSG_012 [Yusuke]]
斡Nunca he visto nada igual en mi vida!

[msg MSG_013 [Futaba]]
Estoy sintiendo un poder enorme en 姻l...[n]斡Es demasiado peligroso para nosotros!

[msg MSG_014 [Morgana]]
No hay tiempo para pensarlo. Retirarnos[n]es nuestra 雨nica opci吋n.

[msg MSG_015 [Ryuji]]
斡Maldita sea, parece que estamos todos[n]dentro!

[msg MSG_016 [Morgana]]
斡Salten!

