[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 65 0 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 4]Entonces, 夷cu茨l es el plan para hoy?[n]Todav胤a tenemos tiempo hasta la fecha[n]limite.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 67 12 0 4][f 3 1 1 0 0 2]Una cosa que podr胤amos hacer es intentar[n]fortalecernos en Mementos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Pero decidamos despu姻s de que llegue la[n]se隠orita Ann. Nos envi吋 un mensaje[n]diciendo que casi llega...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 1][f 3 1 1 0 0 4][f 6 1 2 0 0 6]斡Perd吋n por llegar tarde! La sesi吋n de[n]fotos duro m茨s de lo esperado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 5]Oh, hablando del rey de Roma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 6][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷Eh? 夷Para qu姻 es ese folleto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 7]斡Ah, esto? Alguien me lo dio mientras[n]estaba en el set.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]夷Un festival de cine estudiantil del[n]instituto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 67 0 0 0][f 3 1 1 0 0 9]夷Qu姻 es eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 4][f 3 1 1 0 0 10]Bueno, es un evento donde los estudiantes[n]hacen sus propias pel胤culas, las[n]proyectan y las califican, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 1][f 3 1 1 0 0 11]Env胤o mis pinturas a exposiciones de[n]arte, as胤 que tiene sentido que haya[n]un equivalente para las pel胤culas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 4][f 3 1 1 0 0 12]Ni siquiera sab胤a que los estudiantes[n]del instituto pod胤an hacer una[n]pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 13]Escritura de guiones, direcci吋n,[n]filmaci吋n... Pensar que algunos de nuestra[n]edad est茨n haciendo todo eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 65 7 0 1][f 3 1 1 0 0 14]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 15]Oye, Ryuji se qued吋 callado de repente.[n]夷Este festival te dej吋 sin palabras[n]o algo as胤? 夷Mmm?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 16][f 6 1 2 0 0 4]No, solo pens姻 que suena genial... Oye,[n]夷por qu姻 no lo comprobamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 6][f 3 1 1 0 0 17]夷Oh? Es raro escuchar ese lenguaje de[n]ti, Ryuji.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 67 12 0 6][f 3 1 1 0 0 18]夷Verdad? Apuesto a que va a llover[n]ma隠ana.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 19]No, ser茨 un tif吋n en toda regla.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 20][f 6 1 2 0 0 2]斡Argh! 斡夷Qu姻 demonios?! 斡Tambi姻n me[n]gustan las pel胤culas, bien?![n][f 1 3 65535][f 1 1][e]

[msg MSG_018_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 4 0][f 3 1 1 0 0 21]Adem茨s, no s姻 c吋mo decirlo, pero...[n]tengo esta sensaci吋n de que tenemos que[n]ir a ver eso...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 65 6 4 0][f 3 1 1 0 0 22][f 6 1 2 0 0 3]斡Ah, maldici吋n! 斡夷Qu姻 me pasa?![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 6][f 3 1 1 0 0 23][f 6 1 2 0 0 9]Uh, no tiene sentido que nos preguntes[n]a nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 24]Dejando de lado el berrinche de Ryuji,[n]la verdad es que tambi姻n tengo bastante[n]curiosidad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 25]Hablar de pel胤culas de culto amateur me[n]emociona bastante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 67 12 0 1][f 3 1 1 0 0 26]夷Una pel胤cula, eh? He visto algunas con[n][f 6 1 30 0 0 0] fueron bastante interesantes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 4][f 3 1 1 0 0 27][f 6 1 2 0 0 4]Ahora me est茨 entrando ganas de ir[n]tambi姻n. Oye, 夷por qu姻 no vamos todos[n]juntos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 1][f 3 1 1 0 0 28]Eso me recuerda, nunca hemos ido a ver[n]una juntos. Esta parece ser una buena[n]oportunidad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Hemos estado progresando a buen ritmo,[n]as胤 que 夷por qu姻 no tomamos un descanso[n]hoy?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 68 2 0 1][f 3 1 1 0 0 30][f 6 1 2 0 0 7]Estoy de acuerdo. Esto podr胤a brindarme[n]alguna especie de inspiraci吋n[n]art胤stica.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 4][f 3 1 1 0 0 31]斡Quiero ver una pel胤cula de ciencia[n]ficci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 1 1][f 3 1 1 0 0 32][f 6 1 2 0 0 6]Uh, no hay forma de que un estudiante[n]de secundaria pueda hacer una pel胤cula[n]de ciencia ficci吋n solo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 7 11 0 0][f 4 6 66 12 0 1][f 3 1 1 0 0 33]Entonces, [f 6 1 30 0 0 0] 夷cu茨l es el plan para[n]hoy?[n][f 1 3 65535][f 1 1][e]

[sel SEL_028 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Veamos algunas pel胤culas.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Tomemos un descanso juntos.[f 2 7 1 64 0 32][e]

[msg MSG_029 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 4][f 3 1 1 0 0 34][f 6 1 2 0 0 7]斡O胤ste al chico![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 1][f 3 1 1 0 0 35]De acuerdo, vayamos todos juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 67 12 0 4][f 3 1 1 0 0 36]Veamos... la ubicaci吋n est茨 impresa aqu胤[n]en el folleto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 1][f 3 1 1 0 0 37][f 6 1 2 0 0 7]*risa* Tomemos un respiro y disfrutemos[n]de un rato libre juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 65 12 0 1][f 3 1 1 0 0 38]Vamos, 斡prep茨rate, [f 6 1 30 0 0 0]![n][f 1 3 65535][f 1 1][e]

