[msg MSG_000]
[f 0 5 65278][f 2 1][f 0 6 255 255]Qu姻 gran pel胤cula, 夷verdad?[n][f 1 2 70][f 1 1][e]

[msg MSG_001_01]
[f 0 5 65278][f 2 1][f 0 6 255 255]Y ahora...[n][f 1 2 30][f 1 1][e]

[msg MSG_001_02]
[f 0 5 65278][f 2 1][f 0 6 255 255]Nos gustar胤a que el director de la[n]pel胤cula anterior tomara el escenario.[n][f 1 2 135][f 1 1][e]

[msg MSG_002]
[f 0 5 65278][f 2 1][f 0 6 255 255]Todo el mundo, por favor, darle la[n]bienvenida con una c茨lida ronda de aplausos.[n][f 1 2 88][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 0 6 255 255]Perm胤tame presentarle...[n][f 1 2 35][f 1 1][e]

[msg MSG_004_01]
[f 0 5 65278][f 2 1][f 0 6 255 255]Describi吋 sus propias luchas en la[n]pel胤cula "New Cinema Laberrinth". Su nombre es..[n][f 1 2 170][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 0 6 255 255]　[n][f 1 2 30][f 1 1][e]

