[msg MSG_000 [Marie]]
Okay, permボteme explicarte cポmo [f 0 1 2]comunicarte con otros mundos[f 0 1 0].
La cuestiポn es que aparentemente hay un montポn de mundos ademホs de este por ahボ.
Entonces, en esos otros mundos, hay otros "tマ"...
Y todos estホn tratando de comunicarse con tu mundo desde el suyo.

[msg MSG_000_1 [Marie]]
Asボ que si quieres ponerte en contacto con ese otro "tマ", puedes utilizar tu [f 0 1 2]Libro[f 0 1 0].
Tu Libro puede contener la informaciポn de tu equipo y una Persona Secundaria.
Cuando intercambias un Libro con otro "tマ", ambos podrホn invocar las Personas Secundarias dentro de los Libros.
Obviamente, todavボa tendrホ un precio, pero podrボas conseguir una Persona realmente fuerte.

[msg MSG_000_2 [Marie]]
Pero primero necesitaremos un nombre. Asボ los otros "tマ" podrホn diferenciarte y demホs.

[msg MSG_000_3 [Marie]]
Mmm... Bueno, es un nombre que se coloca en el Libro, asボ que...

[msg MSG_000_4 [Marie]]
ムLlam〒moslo tu [f 0 1 2]Nombre del Libro[f 0 1 0]!
Puedes cambiarlo cuando quieras, asボ que solo dame algo para apuntar.

[msg MSG_001 [Morgana]]
Un Nombre del Libro, メeh...?

[msg MSG_001_5 [Morgana]]
メPor qu〒 no usamos el nombre de nuestro equipo de Ladrones Fantasma?

[msg MSG_002 [Marie]]
Eh, メsu qu〒?

