[msg MSG_000]
夷Desde d吋nde deseas comenzar? *Esta[n]depuraci吋n es para confirmaci吋n de[n]misi吋n.

[sel SEL_001 top]
Desde el principio.
Desde el Cap.1
Desde el Cap.2
Desde el Cap.3
Desde el Cap.4
Desde el Cap.5

[msg MSG_002]
Iniciar gameplay.

[msg MSG_003]
Omitiendo el pr吋logo y comenzando desde[n]el cap胤tulo 1.

[msg MSG_004]
Iniciando gameplay desde el Cap.2.

[msg MSG_005]
Iniciando gameplay desde el Cap.3.

[msg MSG_006]
Iniciando gameplay desde el Cap.4.

[msg MSG_007]
Iniciando gameplay desde el Cap.5.

