[sel FCL_NETWORK_MSG_YN top]
[f 0 5 65278][f 2 1]{dialog}[e]
[f 0 5 65278][f 2 1]{dialog}[e]

[sel FCL_NETWORK_SUBPERSONA_C top]
[f 0 5 65278][f 2 1]{dialog}[e]
[f 0 5 65278][f 2 1]{dialog}[e]

[msg FCL_NETWORK_SETTING]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_SETTING_SUCC]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_SETTING_EXIS]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_SETTING_FULL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_SETTING_EULA]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_SETTING_PARE]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_ALERT]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_MAKE]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SD_WRITIN]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SD_NONE]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SD_SHORTA]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SD_PHOTO_]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SD_ERROR]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_MAKE_SUCC]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_LOAD]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_LOAD_SUCC]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_SAVING]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_INVALID_D]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_QR_DECODE_ER]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_INBOX_RECEIV]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_INBOX_CHECKI]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_DELE [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65201]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_DELE_2 [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_SUMM [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65201]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_SUMM_2 [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_SUMM_3]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_EXIS [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_EXIS_2 [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_MONE [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_MONE_2 [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_STOC [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_STOC_2 [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_LV_M [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_PERSONA_LV_E [Elizabeth]]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_ATTACH_M [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65202]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_ATTACH_E [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65202]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_INPUT_ATTENT]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_INPUT_NGWORD]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_INPUT_NUMBER]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_NAME_OPEN]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[sel FCL_NETWORK_NAME_OPEN_SE top]
[f 0 5 65278][f 2 1]{dialog}[e]
[f 0 5 65278][f 2 1]{dialog}[e]

[msg FCL_NETWORK_EDIT_SAVE]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_EDIT_CANCEL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_NOT_EDIT_PER [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_NETWORK_NOT_EDIT_PER_2 [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

