[sel FCL_PERSONA_YN top]
[f 0 5 65278][f 2 1]{dialog}[e]
[f 0 5 65278][f 2 1]{dialog}[e]

[msg FCL_PERSONA_LVUP]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_PARAMUP]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_GETSKILL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_RMSKILL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_RMSKILL_Q]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_RMSKILL0]
[f 0 5 65278][f 2 1][f 0 1 1][f 2 4 0][f 0 1 0]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_RMSKILL1]
[f 0 5 65278][f 2 1][f 0 1 1][f 2 4 1][f 0 1 0]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_RMSKILL2]
[f 0 5 65278][f 2 1][f 0 1 1][f 2 4 0][f 0 1 0]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SKILLSHIFT]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SKILLSHIFTCA]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SKILLSHIFTCH]
[f 0 5 65278][f 2 1][f 0 1 1][f 2 4 0][f 0 1 0]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SKILLSHIFTUP]
[f 0 5 65278][f 2 1][f 0 1 1][f 2 4 0][f 0 1 0]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SHIFT]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SHIFTCANCEL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_SHIFT1]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_GET_SKILLCARD0]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_GET_SKILLCARD1]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_SKILLCARD_TUTORIAL]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_SKILL_FRAME]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_MOVIE_BONUS]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_EVOLUTION_FI]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_EVOLUTION_PR]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_EVOLUTION_NO]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg FCL_PERSONA_EVOLUTION_SK]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

