[msg BR_RISE_GETSKILL_TRDEYE]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_ENMY_S]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_TRSR_S]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_W_SACH]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_HP]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_Z_ESCP]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_SP]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_HPSONG]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_SPSONG]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_H_ANYZ]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

[msg BR_RISE_GETSKILL_F_ANYZ]
[f 0 5 65278][f 2 1]{dialog}[n][f 1 1][e]

