import re

replacements = {
    "レdolo de Sacrificio": "レdolo de Sacrificio",
    "Anillo de Oscuridad": "Anillo de Oscuridad",
    "Pendiente de Hierro": "Pendiente de Hierro",
    "Divisor de armadura": "Divisor de armadura",
    "Protecciｶポn Completa": "Protec. Completa",
    "Revuelta Vanguardia": "Revuelta Vanguardia",
    "Ojo Crｶボtico Verdadero": "Ojo Crｶボtico Real",
    "Dｶ〒jame llegar a ellos": "Dｶ〒jame llegar",
    "Sentimientos de Hikari": "Sentimientos de Hikari",
    "ちゎれぼぺぽよる ぽま ろまれよるよれ": "ちゎれぼぺぽよる ぽま ろまれよるよれ",
    "Bendiciｶポn del Alivio": "Bendic. de Alivio",
    "Enlace de Golpe ｶレgnea": "Enlace-Golpe ｶレgneo",
    "Enlace de Golpe Helado": "Enlace-Golpe Helado",
    "Enlace de Golpe Elｶ〒ctrico": "Enlace-Golpe Elｶ〒c.",
    "Enlace de Golpe de Viento": "Enlace-Golpe Vien.",
    "Observador del Dolor": "Observador de Dolor",
    "Enlace de Golpe Psｶボquico": "Enlace-Golpe Psｶボ.",
    "Enlace de Golpe Nuclear": "Enlace-Golpe Nucl.",
    "Dominio de Desenfreno": "Dominio Desenfreno",
    "Tｶボtulo Conquistador": "Tｶボtulo Conquistador",
    "Absorber electricidad": "Abs. electricidad",
    "Potenciac. de electr.": "Potenc. electrico",
    "Potenciac. de viento": "Potenc. de viento",
    "Amplificac. de hielo": "Amplific. de hielo",
    "Amplific. de electr.": "Amplific. electrico",
    "Perforaciｶポn de Reina": "Perforaciｶポn de Reina",
    "Aumento de Ataque I": "Aumen. de Ataque I",
    "Aumento de Ataque II": "Aumen. de Ataque II",
    "Aumento de Ataque III": "Aumen. Ataque III",
    "Aumento de Defensa I": "Aumen. de Defensa I",
    "Aumento de Defensa II": "Aumen. Defensa II",
    "Aumento de Defensa III": "Aumen. Defensa III",
    "Aumento de Afinidad I": "Aumen. Afinidad I",
    "Aumento de Afinidad II": "Aumen. Afinidad II",
    "Aumento de Afinidad III": "Aumen. Afinidad III",
    "Aumento de Magia II": "Aumen. de Magia II",
    "Aumento de Magia III": "Aumen. de Magia III",
    "Resistir electricidad": "Resistir elec.",
    "Resistir psicoquin.": "Resistir psico.",
    "Anular Petrificaciｶポn": "Anular Petrific.",
    "Abalorio de resurrec.": "Abalorio resurrec.",
    "Curaciｶポn de Ataduras": "Curaciｶポn de Atadu.",
    "Esfera desvanecedora": "Esfera desvaneced.",
    "Botella de Claridad": "Botella de Claridad",
    "Cadena de abalorios": "Cadena de abalorios",
    "Renovaciｶポn de Tesoro": "Renovar Tesoro",
    "Piedra de Resurrecciｶポn": "Piedra de Resurrec.",
    "Piedra de Curaciｶポn L": "Piedra Curativa L",
    "Palomitas Tropicales": "Palomitas Tropicales",
    "Anular Muerte instantｶホnea": "Anular Muerte inst.",
    "Anular Estados Alterados": "Anular Estados Alt.",
    "Aumento de Habilidad": "Aumento de Hab.",
    "Rec. de Aturdimiento": "Rec. de Aturdición",
    "Fin de Sobrecalentamiento": "Fin de Sobrecalen.",
    "Aumento de Bendiciｶポn": "Aumento Bendiciｶポn",
    "Aumento de Maldiciｶポn": "Aumento Maldiciｶポn",
    "Amplificador Nuclear": "Ampl. Nuclear",
    "Amplificador Psｶボquico": "Ampl. Psｶボquico",
    "Amplificador de Bendiciｶポn": "Ampl. de Bendiciｶポn",
    "Amplificador de Maldiciｶポn": "Ampl. de Maldiciｶポn",
    "Fuego de Intercepciｶポn": "Fuego Intercepciｶポn",
    "Potenc. estado alter.": "Potenc. Estados Alt.",
    "Increment. Estados Alt.": "Increm. Estados Alt.",
    "Ankh Viento-Elｶ〒ctrico": "Ankh Viento-Elｶ〒c.",
    "Tecnologｶボa de Barrera": "Tecnol. de Barrera",
    "Lluvia de Puｶワaladas": "Lluvia de Puｶワaladas",
    "Destructor de Armas": "Destructor de Armas",
    "Patada de Kamoshida": "Patada de Kamoshida",
    "Borrador de Piernas": "Borrador de Piernas",
    "Protecciｶポn Completa": "Protec. Completa",
    "Potenciac. de electr.": "Potenc. de electr.",
    "Potenciac. de viento": "Potenc. de viento",
    "Enlace de Gran Unidad": "Enlace Gran Unidad",
    "Estilo Puｶワo de Hierro": "Estilo Puｶワo Hierro",
    "Estilo Sin Esfuerzo": "Estilo Sin Esfuerzo",
    "Colmillo de Tormenta": "Colmillo  Tormenta",
    "Colmillo Tempestuoso": "Colmi. Tempestuoso",
    "Autorrecuperaciｶポn 25%": "Autorrec. 25%",
    "Autorrecuperaciｶポn 40%": "Autorrec. 40%",
    "Autorrecuperaciｶポn 70%": "Autorrec. 70%",
    "Capa de Desesperaciｶポn": "Capa de Desesp.",
    "Desesperaciｶポn Infinita": "Desesp. Infinita",
    "Recuperaciｶポn Urgente": "Recuperac. Urgente",
    "Tempestad de Llamas": "Tempestad en Llamas",
    "Aceleraciｶポn Temporal": "Aceleraciｶポn Temporal",
    "Enlace de Golpe-Viento": "Enlace Golpe-Viento",
    "Entrenamiento Aｶ〒reo": "Entrenamiento Aｶ〒reo",
    "Misiｶポn de Confianza": "Misiｶポn de Confianza",
    "Cuarteto de Belleza": "Cuarteto de Belleza",
    "Muerte de un Solo Disparo": "Disparo Instantán.",
    "Atadura Fｶボsica-Agilidad": "Atadura Fｶボsica-Ag",
    "Inyecciｶポn somnｶボfera": "Inyecciｶポn somnｶボfera",
    "Visiｶポn de Detective": "Visiｶポn de Detective",
    "Postura de Contraataque": "Postura Contraataque",
    "Barreras de machismo": "Barreras machismo",
    "Postura de Acometida": "Postura Acometida",
    "Golpe de contraataque": "Golpe contraataque",
    "Perforaciｶポn de Emperatriz": "Perfo. Emperatriz",
    "Estilo de Contraataque": "Estilo Contraataque",
    "Experto en Meriendas": "Experto en Merienda",
    "Prohibiciｶポn de Detective": "Prohibic. Detective",
    "Cuerpo de Inmunidad": "Cuerpo de Inmunidad",
    "Paseo por el Paraｶボso": "Paseo en el Paraｶボso",
    "Corte de Guillotina": "Corte de Guillotina",
    "Cuchilla de Guillotina": "Cuchilla Guillotina",
    "Mordida Castigadora": "Mordida Castigadora",
    "Triturador de Brazos": "Tritura Brazos",
    "Reducciｶポn de Costos": "Reducciｶポn de Costos",
    "Destreza de Resistencia": "Destreza de Resist.",
    "Talento de Resistencia": "Talento de Resist.",
    "Genio de Resistencia": "Genio de Resist.",
    "Destreza de Agilidad": "Destreza de Agil.",
    "Talento de Agilidad": "Talento de Agil."
}

with open('skillnametable_prereplace.ebl', 'r', encoding='utf-8') as file:
    file_contents = file.read()

for old_term, new_term in replacements.items():
    file_contents = re.sub(r'\b' + re.escape(old_term) + r'\b', new_term, file_contents)

with open('skillnametable_prereplace.ebl', 'w', encoding='utf-8') as file:
    file.write(file_contents)
