[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]We've returned above ground...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 2 0 1][f 3 1 1 0 0 22097][f 6 1 2 0 0 7]*sigh* We're finally outta there...[n]Sweet, fresh air![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0]It's too early to celebrate―now comes[n]the important part.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Since we've secured our route to the[n]switchboard, we can turn off the lights[n]whenever we please.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 1][f 3 1 1 0 0 0]All that's left is to determine how we'll[n]steal the statue from the square.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 0][f 3 1 1 0 0 0]Let's head back to work out the details[n]of the operation.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]If we stick around here, some backup[n]for our unconscious friend might[n]show up.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 24 12 0 1][f 3 1 1 0 0 24114]Well then, shall we return to the theater,[n]Joker?[n][f 1 3 65535][f 1 1][e]

