[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 1 3][f 3 1 1 0 0 1][f 6 1 2 0 0 0]So, that was totally Kamoshida,[n]right!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 1 6][f 3 1 1 0 0 2]There's no way he's a hero of justice![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 1][f 3 1 1 0 0 3][f 6 1 2 0 0 4]Who is this Kamoshida that you[n]speak of? Do you all know him?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 4]Yeah, he's a former teacher at our[n]school. Basically, he's an effin'[n]criminal scumbag.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 4 0 0][f 3 1 1 0 0 5][f 6 1 2 0 0 2]But, why is Kamoshida in that movie?[n]And what's up with the goofy costume!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 68 12 0 0][f 3 1 1 0 0 6]That trailer made him out to be the[n]protagonist―is he in any other films[n]here?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 7]I have no idea―that movie you just[n]previewed has been the only one[n]playing all this time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 6][f 3 1 1 0 0 8][f 6 1 2 0 0 4]What do you mean?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 9]It's truly odd... Ever since the anomaly[n]occurred, only that movie has been[n]playing in here.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10][f 6 1 2 0 0 4]Are you aware of the strange[n]projectionist currently in[n]the projection room?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 11]I don't suppose you mean that eerie,[n]black object―the one that's all spongy?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 70 10 0 0][f 3 1 1 0 0 12][f 6 1 2 0 0 0]That's the projectionist!? It's not some[n]doll―it's alive!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 13]We just call him that since he plays[n]the films, but we've no idea who or[n]what he may truly be.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]That bizarre being appeared in the[n]projection room after the anomaly[n]struck this theater...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15]We know not his intentions―only that[n]he continues to play the same film,[n]over and over.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 2 4][f 3 1 1 0 0 16]He scares me... I-I don't want to get[n]near him...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 17]For the time being, we've been calling[n]him "Doe."[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 65 12 0 0][f 3 1 1 0 0 18]Dough? Like, cookie dough, dough?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Nagi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 3 0 0 1]No, it comes from John Doe.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 65 6 0 1][f 3 1 1 0 0 20][f 6 1 2 0 0 4]John who? Is that some kinda foreigner?[n]You know anyone with that name,[n][f 6 1 30 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1]I bet he's a legendary musician.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Sounds like some famous actor.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]It's just a placeholder name.[f 2 7 1 64 0 32][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 4][f 3 1 1 0 0 21]Uh, that's not the name of some[n]celebrity...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 72 0 0 1][f 3 1 1 0 0 22]It's the name used for an unidentified[n]male corpse―primarily in police[n]investigations and autopsies.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 23]That's right! I'm surprised you knew.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24]It's the name used for an unidentified[n]male corpse―primarily in police[n]investigations and autopsies.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 4][f 4 6 84 1 0 1][f 4 6 68 12 0 3][f 3 1 1 0 0 25][f 6 1 2 0 0 4]Has Doe done anything else besides[n]screening that movie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 4 3 0][f 3 1 1 0 0 26]No... Nothing at all. He doesn't even[n]react when we speak to him.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27]He's a wholly mysterious oddity. We try[n]our best not to interact with him.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 4 2 0][f 3 1 1 0 0 28]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 29]Reminds me of how I used to be...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 12 0 1][f 3 1 1 0 0 30]Hm? Did you say something, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 31]Oh, nah. It's nothing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 66 12 0 1][f 3 1 1 0 0 32][f 6 1 2 0 0 4]But the movie Doe's playing―why is[n]Kamoshida in it at all, let alone in[n]the starring role?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 33]Is there some kind of connection[n]between Doe and Kamoshida?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 34]Or, perhaps it's a connection between[n]this theater and Kamoshida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 1][f 3 1 1 0 0 35]Please wait a moment. It seems that[n]you've misunderstood...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 36]Only since you all arrived here has[n]the movie become this one entitled[n]"Kamoshidaman."[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 37][f 6 1 2 0 0 4][f 6 1 3 0 0 3]"Become"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Nagi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 38][f 6 1 3 0 0 1]Before your arrival, the movie playing[n]in here was not titled "Kamoshidaman."[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 6][f 3 1 1 0 0 39][f 6 1 2 0 0 0]Wait, what!? Then, Kamoshida wasn't[n]originally the star?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 40]The film's plot was the same, but the face[n]and name of the hero were entirely[n]different.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Ann]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 41][f 6 1 2 0 0 4][f 6 1 3 0 0 3]How could a movie character suddenly[n]change like that, though?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 42]So, all of these strange events,[n]including the adaptive film, are[n]tied to the anomaly...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 43]Your own leaping out of a movie as[n]well... This has been an unending[n]series of surprises.[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 4][f 4 6 65 0 0 0][f 3 1 1 0 0 44][f 6 1 2 0 0 4]Huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 45]...What did you just say?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 4]We leapt out of the film?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 47]Yes―you all suddenly popped out[n]of the theater's screen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 0][f 3 1 1 0 0 48][f 6 1 2 0 0 0]Wait, wait! How does that make[n]any sense!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 49]But, you did indeed appear from the[n]screen... Hikari-san, you witnessed it[n]too, no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 81 4 2 0][f 3 1 1 0 0 50]Mmhm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 51]It was such a shock to us that we[n]hurriedly hid ourselves amongst[n]the seats.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 8 1 0][f 3 1 1 0 0 52][f 6 1 2 0 0 10]Uh, yeah, it's seriously impossible to[n]just pass through a movie screen like―[n][f 1 3 65535][f 1 1][e]

