[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 0 99 1][f 3 1 1 0 0 26633][f 6 1 2 0 0 1][f 3 1 6 0 0 500]Joker! Wait! Stop, stoooop![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Ah―What is it!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Is there a trap ahead?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]No, it's about something back here,[n]in the movie theater![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Remember that door we found that had[n]"Authorized Personnel Only" on it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 21 12 0 0][f 3 1 1 0 0 21012]Oh, you mean that locked one? What[n]about it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]I suddenly picked up a bizarre, super-[n]strong reading beyond that door.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]A reading? You mean an enemy?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 100 0][f 3 1 1 0 0 26515][f 6 1 2 0 0 10]No, it's totally new to me―some strange[n]presence, and even Nagi doesn't know[n]what it could be...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0]It's highly unlikely to be Queen and[n]Noir, but I still think we should[n]check it out.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 0]If so, then we'll need to return to the[n]movie theater... It's your call.[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Let's head back now.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Let's go check it out.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 26572][f 6 1 2 0 0 6]Okay, come back as quick as you can![n]I'll be waiting![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 6][f 3 1 1 0 0 0]A mysterious presence, eh? I'm curious[n]as to what it could be...[n][f 1 3 65535][f 1 1][e]

