[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]The entrance to the screening room...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 27 0 0 0] and Yusuke are[n]working with Nagi...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 1][f 3 1 1 0 0 0]Ah, [f 6 1 30 0 0 0].[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]How's it going so far?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Any issues to report?[f 2 7 1 64 0 32][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24067]We were just asking Nagi-san if she[n]could find the supplies that I need.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 1 0 3][f 4 6 19 12 0 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Nagi-san! Did you have any luck?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 64065]Yes―just as you predicted, there were[n]unused ones in the supply room.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]I've also found the set of tools you[n]requested. Still... they're rather old,[n]so I'm unsure if they'll be of any use.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 1][f 3 1 1 0 0 0]No, this is more than enough. The rest[n]is dependent on my artistic skills...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Thank you for your assistance, Nagi-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19107][f 6 1 2 0 0 6]Mm, I think we got this![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]That reminds me, what kind of art[n]do you usually make, Yusuke-kun?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]Well... Hm, how should I describe it?[n]This is difficult to put into words...[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Art portraying beautiful women.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Nude portraiture.[f 2 7 1 64 4 32][e]
[f 0 5 65278][f 2 1]The very essence of beauty.[e]

[msg MSG_010 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 24009]There is that, but that's not all...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]What I'm attempting to depict is[n]beauty itself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 4][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19018][f 6 1 2 0 0 4]Nude... Ohh, like sketching nude[n]models?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 0]Unfortunately though, I've never had[n]the chance to do that. I only hope the[n]opportunity presents itself again...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 0]But, what I truly want to depict is[n]nothing less than beauty itself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 1 0][f 3 1 1 0 0 24049][f 6 1 2 0 0 6]As I'd hoped, [f 6 1 30 0 0 0]―you truly[n]understand me![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]Just as he said, what I strive to depict[n]is nothing less than beauty itself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 68 1 0 1][f 4 6 19 0 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Beauty?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 0]Yes, but I do not mean superficial[n]beauty.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]There is both beauty and foulness within[n]one's heart. I wish to capture the fierce,[n]yet heartrending conflict of―[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19032]Um, sorry! You seem to have a lot to say[n]about this, so maybe... you can tell me[n]about it later?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]We probably ought to get back to work![n][f 1 3 65535][f 1 1][e]

[msg MSG_017]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 2 32 3][f 3 1 1 0 0 0]It seems things are okay here. I should[n]head back for the time being...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 8 32 3][f 3 1 1 0 0 0]It seems things are okay here. Maybe[n]I should go check on the others...[n][f 1 3 65535][f 1 1][e]

[sel SEL_019 top]
[f 0 5 65278][f 2 1]Akechi and Elizabeth[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ann and Ryuji[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana and Futaba[f 2 7 1 64 2 32][e]

