[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]Movie theater, box office...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Akechi is talking to Elizabeth...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 74 1 0 4][f 4 6 72 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ah, you've stopped by.[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Hope I'm not intruding.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]I'm in rarefied air here.[f 2 7 1 64 0 32][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 28033]It's nothing so serious.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]There was just something that made me[n]curious earlier, so I wanted to ask her[n]about it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 0 0][f 3 1 1 0 0 0]Aha, so this must be what is called an[n]"interrogation"... I'm rather excited[n]to be experiencing this firsthand.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]You're interrogating her?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]That's exciting to you?[f 2 7 1 64 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 0][f 3 1 1 0 0 28078]As I said before, it's nothing so serious―[n]merely a simple question.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 0]Well, that is unfortunate―I was hoping[n]to experience it with a serving of[n]"Katsu Dune"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 10 1 0][f 3 1 1 0 0 0]Haha, you mean how cop shows offer pork[n]bowls to suspects when they interrogate[n]them? That's purely fictional.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]This is merely to satisfy my personal[n]curiosity.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28010][f 6 1 3 0 0 1]You mentioned earlier that nothing[n]meaningless happens in the Velvet[n]Room...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 3 0 0 1]Then, how would you explain[n][f 6 1 26 0 0 0]-san's presence?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]What do you mean?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]She's... the one behind all this!?[f 2 7 1 64 8 32][e]

[msg MSG_011 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 0 0][f 3 1 1 0 0 54031]*chuckle* To think you'd come to such[n]a conclusion... Truly, you are well-suited[n]for detective duties.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 72 12 0 0][f 3 1 1 0 0 0]If memory serves me correctly,[n][f 6 1 26 0 0 0]-san came here[n]through the Velvet Room...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]What I want to ask is, if that in itself[n]has any meaning to it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 0 0][f 3 1 1 0 0 54056]Yes, I do believe that the solo arrival[n]of [f 6 1 27 0 0 0] is no mere[n]coincidence...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However, that does not apply to her[n]alone.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 10 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What do you mean?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 1 0][f 3 1 1 0 0 0]Since you've also encountered[n]attendants of the Velvet Room...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Your presence here was also inevitable,[n]and there is some meaning to it...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]A meaning, hm... But that meaning[n]doesn't involve you directly, correct?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So, all our answers lie beyond the end[n]of the movie...[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]I'm curious how it'll end.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Let's work on the plan.[f 2 7 1 64 0 32][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 54031]Whether or not you reach that end is[n]dependent on you all...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You all seem to be scheming[n]something... It's making my heart[n]race just witnessing you all in action.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 0]Our plan must succeed if we're to learn[n]everything.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 54056]Yes, I believe that would be a most wise[n]decision.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Whether or not you reach the movie's[n]end is wholly dependent on you all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 0]Yes―and for that, we need to ensure this[n]plan succeeds.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022]
[f 0 5 65278][f 2 1][f 4 6 64 2 32 0][f 3 1 1 0 0 0]It seems things are okay here. I should[n]head back for the time being...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023]
[f 0 5 65278][f 2 1][f 4 6 64 8 32 0][f 3 1 1 0 0 0]It seems things are okay here. Maybe[n]I should go check on the others...[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 6 1 27 0 0 0] and Yusuke[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ann and Ryuji[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana and Futaba[f 2 7 1 64 2 32][e]

