[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 4 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 1][f 6 1 2 0 0 4]This is... the movie theater?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2]I never would've imagined that world[n]could be connected to a place like this...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 1][f 3 1 1 0 0 3][f 6 1 2 0 0 9]Yeah, we freaked out at first too.[n]Actually, we're still having a hard[n]time believin' it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 2 2 1][f 3 1 1 0 0 4]Welcome, Miss [f 6 1 26 0 0 0].[n]I am Nagi, the curator here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 2 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 5]Oh, hello! Nice to meet you.[n]I'm [f 6 1 28 0 0 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]Everyone told me a bit about this[n]theater before we got here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 7]I've been watching everything from[n]here. I'm relieved to see that[n]you're not hurt.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 10 0 1][f 3 1 1 0 0 14][f 6 1 27 0 0 0]! Thank goodness you're[n]all right.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 15][f 6 1 2 0 0 6]Oh, Theo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 3 1 1 0 0 16]I'm so sorry I worried you. Everyone[n]here helped me find you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 76 0 0 0][f 3 1 1 0 0 17]Please allow me to express my gratitude[n]to you as well...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 6 1 0][f 3 1 1 0 0 18]Thank you so much for saving[n]my precious guest.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]We just do what's right.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]You're in our debt now.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]So, you two are... close?[f 2 7 1 64 0 32][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 19]Yeah, what he said! We'd never ditch[n]somebody in trouble.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 0 1 0][f 3 1 1 0 0 20]My... Your kind consideration is greatly[n]appreciated.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 21][f 6 1 2 0 0 4]So, I'd like to ask something―how are[n]you two affiliated?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 0 0 0][f 3 1 1 0 0 22]I see... Since we've become indebted[n]to you, then it's only proper to repay[n]that debt.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 0][f 3 1 1 0 0 23][f 6 1 2 0 0 4]Let's see... Would 100 packs of takoyaki[n]suffice?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 6][f 3 1 1 0 0 24][f 6 1 2 0 0 0]T-Takoyaki!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 25]I'd greatly appreciate it. I'd also ask[n]that you dress them in both mustard[n]and mayonnaise.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 10 1 6][f 3 1 1 0 0 26]Geez, stop joking around! Theodore's[n]gonna take you seriously![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 68 12 0 0][f 3 1 1 0 0 27][f 6 1 2 0 0 4]So, I'd like to ask something―how are[n]you two affiliated?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 28][f 6 1 2 0 0 4]I've also been curious about that.[n]Would you mind if we ask how you[n]two are affiliated?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 19 0 2 4][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 29]Hmm, it's kinda hard to explain...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30][f 6 1 2 0 0 4]I guess he's someone that I've been[n]indebted to for some time now?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 31]Wow, that's vague! ...But, it's not like[n]I'd understand a more complicated[n]explanation.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 8][f 6 1 2 0 0 4]Wait, what in the world―Hey, guys?[n]Your clothes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 9]Oh, our clothes... So, they do return[n]to normal as we'd expected.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 11][f 6 1 2 0 0 4]...Return? Do your clothes transform[n]into those cool outfits from earlier?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 12]Uhhh, it's a long story, but basically,[n]it's like... a special feature we have?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 13][f 6 1 2 0 0 6]Whoa, that's amazing―so cool![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 4]Hey, y'know what? We haven't[n]introduced ourselves properly[n]yet.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 33]Oh, yeah. Welp, let's cover everything[n]so we can all share what we know so far.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 34]Phantom Thieves that steal hearts in[n]cognitive worlds... I had no idea![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35]From what I've heard, we can both use[n]Personas, but the rules behind it seem[n]pretty different.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 1 0][f 3 1 1 0 0 36]Your clothes don't change at all, huh[n][f 6 1 27 0 0 0]? Even though you use[n]Personas too...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 0][f 3 1 1 0 0 37][f 6 1 2 0 0 0]Whoa!!! Y-Y-You're... You're the[n]girl from the movie...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 3 6][f 3 1 1 0 0 38]Oh hey, Futaba, you finally turned up.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 39]You're the girl who was acting as[n]navigator for everybody, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 40][f 6 1 2 0 0 6]Thank you for rescuing me earlier![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 41]I-I-I didn't... d-didn't do anything[n]in p-particular![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 6][f 3 1 1 0 0 42]Oh, sorry about that. She's a bit...[n]shy around strangers.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 43]It's okay, everyone's a bit nervous in[n]the beginning. Nice to meet you,[n]Futaba-chan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 44][f 6 1 2 0 0 10]U-Um, r-right...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 2 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 45][f 6 1 2 0 0 6]Oh! Futaba-chan―those headphones![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 0]E-Eek![n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 47][f 6 1 2 0 0 7]They're so cool! Are you a music lover[n]too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 48]Wh-Whoooa! You can tell how good[n]these are!? No one else has ever[n]commented on them...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 49][f 6 1 28 0 0 0]... Could she be a fan[n]of stuff like that?[n][f 1 3 65535][f 1 1][e]

[sel SEL_040 top]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 64 1 0 1]You've got a new friend.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Make sure you play nice.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]She might be an otaku.[f 2 7 1 64 0 32][e]

[msg MSG_041 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 50]Yeah, there oughtn't be any bad apples[n]among audiophiles.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 51][f 6 1 2 0 0 6]R-Right―I'm sure I can manage to have[n]a nice time if we've got something[n]in common![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 52]Ooh, so she's an audio geek... I wanna[n]have a heart-to-heart with her about it![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 76 9 1 4][f 4 6 19 16 4 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 72][f 6 1 2 0 0 4]Oh yeah―Theo, what about the other[n]members of SEES? Have you seen Yukari,[n]or Junpei?[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 8 1 0][f 3 1 1 0 0 73]I cannot say for certain at this moment,[n]but the possibility is quite high that[n]they are here as well, somewhere...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 74]After all, [f 6 1 30 0 0 0] has come to this[n]world with his own companions in tow.[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 75][f 6 1 3 0 0 1]I see...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 3 1 1 0 0 76][f 6 1 2 0 0 4]Hey, you're all trying to rescue your[n]friends trapped inside the movie, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 64 1 0 3][f 4 6 23 2 0 6][f 3 1 1 0 0 77]You know it! They're our treasured[n]accomplices.[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 3 1 1 0 0 78][f 1 5][f 6 1 27 0 0 0][n][f 6 1 2 0 0 6]I thought so![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 79]If there's even the slightest possibility[n]my companions are here, I want to[n]look for them...[n][f 1 3 65535][f 1 1][e]

[msg MSG_048_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 2 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 80][f 6 1 2 0 0 6]So I've made up my mind―let me come[n]with you! I'll help you look for your own[n]friends, too![n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 81][f 6 1 2 0 0 6]Ooh, that would be great! You'd be[n]a priceless addition to the team![n][f 1 3 65535][f 1 1][e]

[msg MSG_049_5 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 0][f 3 1 1 0 0 82][f 6 1 2 0 0 4]Well, I'm all for her joining us, but[n]what do you say?[n][f 1 3 65535][f 1 1][e]

[sel SEL_050 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Of course.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]We'll make a great team.[f 2 7 1 64 0 32][e]

[msg MSG_051 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 83][f 6 1 2 0 0 7]Thanks, [f 6 1 30 0 0 0]-kun! I hope[n]we all get along well![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 6][f 3 1 1 0 0 84]Same here![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 85]Don't worry, if we search together,[n]I'm sure we'll find your companions[n]in no time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 86][f 6 1 2 0 0 6]Thanks, Takamaki-san![n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 87]Call me Ann![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 88][f 6 1 2 0 0 6]Plus, I've reached my wits' end being[n]surrounded by all these grungy guys![n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 3 0][f 3 1 1 0 0 89]Hey! Who're you callin' grungy!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 1 0 0][f 6 1 25 0 0 0][f 4 6 81 0 0 0][f 3 1 1 0 0 53]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 54]And you're Hikari-chan? Everyone told[n]me about you...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55][f 6 1 2 0 0 4]Would it be okay for me to stay here[n]too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 56]Huh? O-Oh, yes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 57][f 6 1 2 0 0 6]Thank you![n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 58][f 6 1 2 0 0 10]Ah... U-Um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 68 1 0 1][f 4 6 70 10 0 3][f 3 1 1 0 0 59][f 6 1 2 0 0 9]Wow... I swear, the new girl's social[n]skills are maxed out...[n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 60]Yes―I sense an outgoing vibe from her[n]that's rather rare...[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 1][f 3 1 1 0 0 61][f 6 1 2 0 0 4]Do you think Hikari'll be okay, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 0][f 3 1 1 0 0 62][f 6 1 2 0 0 0]Why're you asking me!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 66 6 1 0][f 3 1 1 0 0 63]Well... You know... You and Hikari are[n]both...[n][f 1 3 65535][f 1 1][e]

[sel SEL_066 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 6]You two are really similar.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]You're both pretty shy.[f 2 7 1 64 0 32][e]

[msg MSG_067 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 6][f 3 1 1 0 0 64]Hrgh! I mean, it's not like I hadn't[n]noticed it...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65][f 6 1 2 0 0 3]But, she reminds me of how I was[n]only a little while ago, and it makes[n]my heart hurt a bit...[n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 6][f 3 1 1 0 0 66][f 6 1 2 0 0 6]Wha―Hey, I'm not THAT shy![n][f 1 3 65535][f 1 1][e]

[msg MSG_068_5 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 67][f 6 1 2 0 0 10]But, she reminds me of how I was[n]only a little while ago, and it makes[n]my heart hurt a bit...[n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 0][f 3 1 1 0 0 68]I see...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 69]But―look at you now, Futaba! You're[n]able to talk to the rest of us like this...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 70]I'm sure Hikari will eventually open up[n]too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 71][f 6 1 3 0 0 3]Y-Yeah...[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 1][f 4 6 72 2 0 3][f 3 1 1 0 0 90]Well then, why don't we give[n][f 6 1 26 0 0 0]-san a quick tour[n]of this movie theater?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 91]While we do that, I'm sure we'll have[n]the opportunity to make use of our[n]facilities.[n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 10 0 4][f 3 1 1 0 0 92]Ah, that reminds me! Speaking of[n]facilities, I'd like to show you all[n]something.[n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 93][f 6 1 2 0 0 4]Ooh, what's that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 0][f 3 1 1 0 0 94]It's said that a picture is worth[n]a thousand words―now, please,[n]follow me...[n][f 1 3 65535][f 1 1][e]

