[msg MSG_000 [Makoto]]
Asボ que el objetivo es derrotar ocho Basaltos, メverdad?
No hay mucho mホs que decir, por lo que supongo que deberボamos hacer lo de siempre.

[sel SEL_001 top]
Terminemos esto rホpido.
Tom〒monos nuestro tiempo

[msg MSG_002 [Futaba]]
メEh? ムEspera un segundo, Joker!
Estoy detectando mホs seワales de FOE que de costumbre.
Y no solo eso, parece que los Basaltos estホn muy cerca de ellos.

[msg MSG_003 [P4 Hero]]
メPodrボa ser uno de los cambios que ocurren durante una proyecciポn especial?

[msg MSG_004 [Futaba]]
Parece que sボ. Y creo que los caminos normales podrボan estar bloqueados tambi〒n.

[msg MSG_005 [Akechi]]
Ya veo... Es como una versiポn corta de la pelボcula del laberinto que nos permite llegar al objetivo rホpidamente.

[msg MSG_006 [Haru]]
Dijiste que los Basaltos se encuentran cerca de los FOE, メno?

[msg MSG_007 [Makoto]]
Eso significa que lograremos nuestro objetivo mホs rホpido si nos dirigimos hacia ellos.
Es peligroso, pero probablemente sea el plan mホs eficiente.

[msg MSG_008 [Futaba]]
Pero, los FOE son muy fuertes.
Dejaremos que Joker decida, ムcomo siempre! ムContamos contigo Joker!

