[msg MSG_000 [Elizabeth]]
Bien hecho. Conseguiste derrotar a los[n]ocho Basalts.
Mis palmas estaban sudando tan[n]intensamente, casi perd胤 mi palomita y[n]mi cola...
Mirar a Makoto y Haru constantemente[n]hundir a sus enemigos era realmente[n]estimulante.

[msg MSG_001 [Haru]]
夷De verdad los hemos cortado...?

[msg MSG_002 [Ryuji]]
Bueno, con la forma en que ustedes dos[n]estaban pateando el culo y tocando[n]nombres, lo creo.

[msg MSG_003 [Morgana]]
Hola, Makoto. Dijiste que ten胤as algo en[n]tu mente antes. 夷Qu姻 fue?

[msg MSG_004 [Makoto]]
No iba a decir nada, pero ya sabes[n]tanto...

[msg MSG_005 [Haru]]
... Siento no haberte dicho antes.[n]Probablemente sea un buen momento.

[msg MSG_006 [Makoto]]
夷Sabes c吋mo nos capturaron en la[n]pel胤cula Kamoshidaman?
Quer胤amos hacer algo para compensar[n]todos los problemas que te causamos[n]all胤.

[msg MSG_007 [Haru]]
Ahora que estamos con todos de nuevo,[n]pensamos que intentar胤amos ayudar con la[n]proyecci吋n especial...
Si lo despejamos, conseguiremos equipos[n]que nos hagan m茨s fuertes, 夷verdad?

[msg MSG_008 [Naoto]]
Ya veo. As胤 que tu anhelo surgi吋 de un[n]deseo de ayudar a todos.

[msg MSG_009 [Makoto]]
Supongo que eso es todo...
Quer胤a mantenerlo en secreto, as胤 que...[n]Estoy un poco avergonzado ahora que todo[n]est茨 abierto.

[sel SEL_010 top]
Gracias.
Te resbalaste.

[msg MSG_011 [Haru]]
No, somos los que deben estar[n]agradeci姻ndote.
Si no hubieras venido por nosotros,[n]nunca habr胤amos escapado.

[msg MSG_012 [Morgana]]
Tienes raz吋n. Makoto puede parecer[n]perfecta, pero puede tener cuidado de[n]vez en cuando.

[msg MSG_013 [Makoto]]
Bueno...
Supongo que sucede en ocasiones...

[msg MSG_014 [Ann]]
斡Ahaha! 斡Pero sigues siendo s雨per[n]confiable!

[msg MSG_015 [Haru]]
Mako y yo simplemente quer胤amos mostrar[n]nuestra gratitud a todos.
Si no hubieras venido por nosotros,[n]nunca habr胤amos escapado.

[msg MSG_016 [Ryuji]]
Bueno, ustedes no tienen que arreglarse.
S吋lo logramos salvarte por esa punta que[n]nos diste sobre la estatua.

[msg MSG_017 [Yusuke]]
De hecho. T雨 tambi姻n nos ayudaste.
Adem茨s, es natural que los amigos se[n]ayuden. No hay necesidad de pagarnos.

[msg MSG_018 [Futaba]]
Whoa... Estoy orgulloso de ti, Inari.[n]Pens姻 que querr胤as pagar m茨s que nadie.

[msg MSG_019 [Yusuke]]
Qu姻 grosero...
No puedo decir que no a las comidas[n]gratis, pero no soy tan mezquino de un[n]individuo... Creo.

[msg MSG_020 [Ryuji]]
夷T雨 crees?

[msg MSG_021 [Haru]]
Hm, hm... Gracias de nuevo. Nos alegra[n]estar aqu胤.

[msg MSG_022 [Makoto]]
Y no nos referimos como parte de los[n]Ladrones Fantasma.
Eso es para [f 6 1 26 0 0 0] y el Equipo de[n]Investigaci吋n tambi姻n. Estamos juntos en[n]esto.

[msg MSG_023 [P3 Fem Protag]]
S胤! 斡Cu姻ntame!

[msg MSG_024 [P4 Hero]]
Como sea, nos alegra estar aqu胤 tambi姻n.

[msg MSG_025 [Elizabeth]]
斡Qu姻 final hermoso y feliz! Estoy muy[n]emocionada, estoy a punto de llorar.
Ahora bien, aqu胤 est茨 tu recompensa. Por[n]favor, ac姻ptalo.
Adem茨s, no te olvides de visitar La[n]tienda de Theo y vender los materiales[n]que has recogido...

