[msg MSG_000 [Kanji]]
斡Ja! 斡Dos menos! 斡Van a tener que hacerlo mejor si quieren derrotarnos!

[msg MSG_001 [Makoto]]
S胤, tiene mucho esp胤ritu. Es como tener otro Skull en el equipo.

[msg MSG_002 [Ryuji]]
Oye, no me parezco nada a 姻l... Yo no soy un mat吋n.

[sel SEL_003 top]
畏l es en realidad un tipo serio.
Entonces, 夷un delincuente?

[msg MSG_004 [Ryuji]]
斡夷Qu姻?! No iba en serio.

[msg MSG_005 [Makoto]]
Puede que no lo parezca, pero es verdad.

[msg MSG_006 [Ryuji]]
斡夷A qui姻n llamas un delincuente?!

[msg MSG_007 [Makoto]]
Bien, 姻l es muy violento, entiendo que la gente lo juzgue mal.

[msg MSG_008 [Makoto]]
畏l realmente se preocupa por sus amigos. Simplemente, se enfada muy f茨cilmente.

[msg MSG_009 [Ryuji]]
斡C茨-C茨llate! 斡Acabemos con esta mierda de una vez!

[msg MSG_010 [Rise]]
Ja, ja, ay, 夷te da vergüenza?
Parece que ustedes dos tienen m茨s en com雨n de lo que piensan. 夷Verdad, Kanji?

[msg MSG_011 [Kanji]]
...
Yo no me parezco en nada a 姻l.

[msg MSG_012 [Kanji]]
Vamos a dejarlo y a seguir movi姻ndonos. Gu胤anos, Joker.
斡Acabar姻 con el siguiente superr茨pido! 斡Solo mira!

[msg MSG_013 [Ryuji]]
夷Eh? 斡Y una mierda! 斡Ese es mi trabajo!

[msg MSG_014 [Futaba]]
斡Vamos, chicos! 斡Paren de perder el tiempo! 斡A este paso, la sombra va a resfriarse aqu胤 en ropa interior!
En cualquier caso, 斡esta ser茨 la 雨ltima! 斡Consulten el mapa y en marcha!

