[msg MSG_000 [Elizabeth]]
ムUna pelea de machos muy emocionante!
Fue una proyecciポn muy sudorosa―discマlpenme―y calurosa, y me ha dejado muy satisfecha.

[sel SEL_001 top]
Me alegra oボrlo.
Fue dura.

[msg MSG_002 [Elizabeth]]
Sボ, la sorprendente batalla cerca del final... Mis ojos han estado pegados a la pantalla hasta el final.
Y parece que un nuevo vボnculo se ha formado entre los dos "hombres".

[msg MSG_003 [Ryuji]]
...ムY entonces fue cuando le dimos la paliza a la sombra!
メQu〒 piensan? ムEs un ataque especial que se me acaba de ocurrir!

[msg MSG_004 [Kanji]]
ムSボii! ムEs perfecto! ムMARAVILLOSO!
Asボ que primero dir〒, "Aaah", y luego...

[msg MSG_005 [Ryuji]]
Aquボ lo he escrito. ムLo podemos practicar despu〒s!

[msg MSG_006 [Kanji]]
メPor qu〒 no le ponemos un nombre? ムAlgo sマper "masculino"!

[msg MSG_007 [Ryuji]]
ムBien pensado! メQu〒 hay de...?

[msg MSG_008 [Morgana]]
Parece que ahora se llevan bastante bien.

[msg MSG_009 [Kanji]]
ム...!
S-sボ...
...
...

[msg MSG_010 [Morgana]]
メP-por qu〒 se callan de repente? 

[msg MSG_011 [Ryuji]]
Has estado mirando un montポn a Morgana マltimamente.
Pensaba que era porque estabas buscando pelea.

[msg MSG_012 [Kanji]]
Oh... No, no es porque no me guste...

[msg MSG_013 [Ryuji]]
Quiero decir, sボ, un gato que habla es muy raro. Pero este... No es tan malo

[msg MSG_014 [Morgana]]
ムPara de decirme gato!

[msg MSG_015 [Kanji]]
Bien, te estaba mirホndolo solo porque...

[msg MSG_016 [Ryuji]]
メPor qu〒...?

[msg MSG_017 [Kanji]]
...do.

[msg MSG_018 [Ryuji]]
...メEh?

[msg MSG_019 [Kanji]]
L...i...

[msg MSG_020 [Ryuji]]
ムメQu〒?! ムDilo de una vez!

[msg MSG_021 [Kanji]]
ムAghhh! ムMira qu〒 lindo es!
ムメCポmo no puedo estar interesado en algo tan adorable?!
Quiero ver lo esponjoso que es... Como se sienten sus patitas...
ムEstoy a tope con esa mierda, ah!
*grito ahogado*

[msg MSG_022 [Ryuji]]
Ohh... Asボ que era por eso.
メPor qu〒 simplemente no lo dijiste? Tポmalo.

[msg MSG_023 [Kanji]]
メDe verdad?

[msg MSG_024 [Morgana]]
メQu〒? ムRyuji! No puedes...

[sel SEL_025 top]
Adelante
S〒 educado.
Te recomiendo sus patitas.

[msg MSG_026 [Morgana]]
ムメTマ tambi〒n?!

[msg MSG_027 [Kanji]]
B-bien, allホ voy...
E-estate quieto, Mona... S〒 bueno...

[msg MSG_028 [Morgana]]
ムEh!

[msg MSG_029 [Kanji]]
ムVuelve aquボ, Mona! ムD〒jame sentir lo esponjosa que es tu barbilla!

[msg MSG_030 [Morgana]]
ムメQu〒 clase de ladrポn se para cuando alguien se lo ordena?!
ムAaaahhh...!

