[msg MSG_000 [Rise]]
ムYa estホn! ムMisiポn completada! ムBuen trabajo, chicos!

[msg MSG_001 [Ryuji]]
Fue muy fホcil. ムVamos! ムメQui〒n es el siguiente?!

[msg MSG_002 [Kanji]]
ムJe! ムApenas he sudado! ムQu〒 sigan viniendo!

[msg MSG_003 [Ryuji]]
ムSomos imparables!

[msg MSG_004 [Kanji]]
ムClaro que sボ! Vamos a luchar hasta el final de la pelボ...

[msg MSG_005 [Kanji]]
Er...

[msg MSG_006 [Ryuji]]
Uhh...

[msg MSG_007 [Morgana]]
メChicos, aマn estホn con eso? ムAcepten que tienen cosas en comマn y luchen juntos!

[sel SEL_008 top]
Necesitamos su fuerza.
Paren de pelear.
Dejemos que los puワos hablen.

[msg MSG_009 [Ryuji]]
S-sボ... S〒 que...

[msg MSG_010 [Ryuji]]
E-eso no era una pelea...

[msg MSG_011 [Futaba]]
ムOhh! ムHe visto esto en algunos mangas que he leボdo! Dos chicos hablando a trav〒s de sus puワos.
Un poco clich〒, メno? Tambi〒n muy de la vieja escuela.

[msg MSG_012 [P4 Protag]]
O-oh, メsボ...?

[msg MSG_013 [Ryuji]]
...
Oye, me gustarボa conocerte mejor. Vamos a hablar hombre a hombre.
Supongo que lo siento por todo lo que dices.

[msg MSG_014 [Kanji]]
ム...!

[msg MSG_015 [Morgana]]
ムメS-Skull pidiendo disculpas?! ムメEsto es un sueワo?! ムメEstoy oyendo voces?!

[msg MSG_016 [Ryuji]]
ムCホllate, gato! メNo ves que me he estado preocupando por ti...?

[msg MSG_017 [Kanji]]
ムメ...?!
ムAaah!

[msg MSG_018 [Ryuji]]
ムArgh...!

[msg MSG_019 [Morgana]]
ムメMrow?!

[msg MSG_020 [Ryuji]]
メQu〒 demonios fue eso...?

[msg MSG_020_1 [Ryuji]]
ムメ...?!

[msg MSG_021 [Kanji]]
ムAmbos deberボan estar mejor concentrados, o serホn carne muerta!
Argh. Mierda...

[msg MSG_022 [Futaba]]
ムメUna sombra?! ムParece que aマn hay otra! ムEstホ justo encima de nosotros!

[msg MSG_022_02 [Futaba]]
ムメUna sombra?! ムParece que aマn hay otra! ムEstホ justo encima de nosotros!

[msg MSG_023 [Morgana]]
ムKanji! ムメEstホs bien?!
※l lo hizo para protegernos...

[msg MSG_024 [Ryuji]]
Bastardo... ムFuera de aquボ!
ムAcabemos con 〒l, Joker! ムNadie ataca a nuestros amigos y se sale con la suya!

[msg MSG_025 [Futaba]]
ムAquボ viene!

