[msg MSG_000 [Chie]]
Entonces, solo tenemos que ir dポnde dice el mapa y derrotar allボ a los enemigos, メverdad?

[msg MSG_001 [Ryuji]]
ムJe! ムPan comido! Vamos por aquボ...

[msg MSG_002 [Kanji]]
ムMuy bien! Vamos por aquボ...

[msg MSG_003 [Ryuji]]
...メEh?

[msg MSG_004 [Kanji]]
...メQu〒?

[msg MSG_005 [Chie]]
ムBieeen, chicos, no se pelen!
Perdポn. Creo que Kanji estホ un poco emocionado.

[msg MSG_006 [Teddie]]
メKanjiii, qu〒 te ocurre? Si eres bueno, te dar〒 una bananaaa.

[msg MSG_007 [Kanji]]
N-No me trates como un animal, ムmaldiciポn!

[msg MSG_008 [Ann]]
No, no. Discマlpenos a nosotros tambi〒n.
Skull se enfada muy fホcilmente. Es como un gorila salvaje.

[msg MSG_009 [Ryuji]]
ムメQu〒 demonios?! メTambi〒n me estホs tratando como un animal?

[sel SEL_010 top]
Dejen de pelear.
Los vamos a dejar detrホs.

[msg MSG_011 [Ryuji]]
Tss...

[msg MSG_012 [Kanji]]
...Culpa mボa.

[msg MSG_013 [Futaba]]
Ja, ja, ja. Es difボcil ser el jefe cuando tienes dos grandes niワos que cuidar.
ムNo importa con que enemigo empecemos! ムElige y lidera el camino, Joker!

