[msg MSG_000 [Kanji]]
ムJa! ムDos menos! ムVan a tener que hacerlo mejor si quieren derrotarnos!

[msg MSG_001 [Makoto]]
Sボ, tiene mucho espボritu. Es como tener otro Skull en el equipo.

[msg MSG_002 [Ryuji]]
Oye, no me parezco nada a 〒l... Yo no soy un matポn.

[sel SEL_003 top]
※l es en realidad un tipo serio.
Entonces, メun delincuente?

[msg MSG_004 [Ryuji]]
ムメQu〒?! No iba en serio.

[msg MSG_005 [Makoto]]
Puede que no lo parezca, pero es verdad.

[msg MSG_006 [Ryuji]]
ムメA qui〒n llamas un delincuente?!

[msg MSG_007 [Makoto]]
Bien, 〒l es muy violento, entiendo que la gente lo juzgue mal.

[msg MSG_008 [Makoto]]
※l realmente se preocupa por sus amigos. Simplemente, se enfada muy fホcilmente.

[msg MSG_009 [Ryuji]]
ムCホ-Cホllate! ムAcabemos con esta mierda de una vez!

[msg MSG_010 [Rise]]
Ja, ja, ay, メte da verg↓enza?
Parece que ustedes dos tienen mホs en comマn de lo que piensan. メVerdad, Kanji?

[msg MSG_011 [Kanji]]
...
Yo no me parezco en nada a 〒l.

[msg MSG_012 [Kanji]]
Vamos a dejarlo y a seguir movi〒ndonos. Guボanos, Joker.
ムAcabar〒 con el siguiente superrホpido! ムSolo mira!

[msg MSG_013 [Ryuji]]
メEh? ムY una mierda! ムEse es mi trabajo!

[msg MSG_014 [Futaba]]
ムVamos, chicos! ムParen de perder el tiempo! ムA este paso, la sombra va a resfriarse aquボ en ropa interior!
En cualquier caso, ムesta serホ la マltima! ムConsulten el mapa y en marcha!

