[msg MSG_000 [Rise]]
メEstホ todo el mundo preparado?
La localizaciポn que especificポ Elizabeth es una alcantarilla justo al norte de aquボ.

[msg MSG_001 [Futaba]]
Si la memoria no me falla, tendremos que escabullirnos entre un montポn de luces de bマsqueda para llegar.

[msg MSG_002 [Yosuke]]
Ese tipo de cosas son la especialidad de los Ladrones Fantasma, メno?

[sel SEL_003 top]
Estamos acostumbrados a esto.
D〒janoslo a nosotros
ムVamos a la carga!

[msg MSG_004 [Yusuke]]
Sボ, evitar ser detectados es habitual cuando nos infiltramos en un Palacio.

[msg MSG_005 [Teddie]]
メCポmo estホis siempre tan tranquilos? Es casi inquietante...

[msg MSG_006 [Naoto]]
*Risita* Contamos contigo

[msg MSG_007 [Ryuji]]
ムSボ! Al final del dボa, ムtodo depende de la fuerza bruta!

[msg MSG_008 [Morgana]]
ムY vosotros os llamホis Ladrones Fantasmas!

[msg MSG_009 [Kanji]]
Entonces, solo tenemos que evitar ser detectados, メverdad?

[msg MSG_010 [Morgana]]
メCre〒is que estar〒is bien? Esto necesita precisiポn y sutileza.

[msg MSG_011 [Rise]]
En ese caso, ムKanji serボa perfecto en esto!

[msg MSG_012 [Kanji]]
Y-Yo no soy nada especial...

[msg MSG_013 [Yukiko]]
Chie tambi〒n es bastante ホgil. Quizホs podrボa encajar bien.

[msg MSG_014 [Chie]]
Soy bastante atl〒tica, pero no exactamente sutil, メsabes?

[msg MSG_015 [Ann]]
ムNo te preocupes! ムTマ solo sボgueme!

[msg MSG_016 [Chie]]
ムV-Vale!

[msg MSG_017 [Teddie]]
Hmm... Ellas parecen llevarse bastante bien. Que cel-oso estoy...

[msg MSG_018 [Morgana]]
Dejad de perder el tiempo. Tenemos una alcantarilla que encontrar.

