[msg MSG_000 [Ann]]
Whew... Parece que lo logramos.

[msg MSG_001 [Chie]]
Hombre, esto realmente te cansa...

[msg MSG_002 [Ann]]
Dices eso, pero lo manejaste[n]perfectamente.

[msg MSG_003 [Chie]]
夷En serio? Hehe... Probablemente es s吋lo[n]porque eres un buen profesor, Panther...

[msg MSG_004 [Ann]]
S吋lo te di una peque隠a pista, es todo.
Incluso podr胤as ser cortado para los[n]Ladrones Fantasma, Chie.

[sel SEL_005 top]
De nada.
夷Y el Equipo de Investigaci吋n?
Ser茨 una vida doble.

[msg MSG_006 [Yukiko]]
Incluso si te uniste al Fantasma[n]Thieves, siempre estaremos ah胤 para ti,[n]Chie.

[msg MSG_007 [Teddie]]
El equipo de investigaci吋n y los[n]ladrones fantasmas, 夷eh?
Con alguien tan apasionado como t雨,[n]Chie, apuesto a que lo har胤as genial en[n]ambos!

[msg MSG_008 [Chie]]
斡Ser姻 investigador de d胤a, ladr吋n[n]fantasma de noche! 夷Algo as胤?

[msg MSG_009 [Teddie]]
Con alguien tan apasionado como t雨,[n]Chie, apuesto a que lo har胤as genial en[n]ambos!

[msg MSG_010 [Teddie]]
El equipo de investigaci吋n y los[n]ladrones fantasmas, 夷eh?
Con alguien tan apasionado como t雨,[n]Chie, apuesto a que lo har胤as genial en[n]ambos!

[msg MSG_011 [Yukiko]]
Incluso si te uniste al Fantasma[n]Thieves, siempre estaremos ah胤 para ti,[n]Chie.

[msg MSG_012 [Ann]]
S胤, seguro que ser胤as un gran ladr吋n de[n]fantasmas, Chie!

[msg MSG_013 [Chie]]
Awww geez, ustedes me est茨n haciendo[n]rubor.
No conseguir茨s nada fuera de m胤 excepto[n]por alguna goma de carne...

[msg MSG_014 [Yosuke]]
No, gracias. Estamos bien.

[msg MSG_015 [Chie]]
A雨n as胤, estoy muy feliz de o胤rte decir[n]eso, Panther...

[msg MSG_016 [Ann]]
夷Eh?

[msg MSG_017 [Chie]]
Eres una supermodelo de la ciudad.
S胤, eres bonita, pero tambi姻n eres[n]elegante. Est茨s encima de todas las[n]雨ltimas modas y cosas.

[msg MSG_018 [Teddie]]
Hrrm, ya veo... Es verdad que tu belleza[n]est茨 igual con nuestras chicas del[n]pa胤s...
Y usted es una dama de moda beary,[n]Panther.

[msg MSG_019 [Ann]]
夷T雨 crees?

[msg MSG_020 [Yosuke]]
Bueno, s胤, puedes encontrar todas las[n]雨ltimas tendencias de moda en la ciudad,[n]夷no?

[msg MSG_021 [Yukiko]]
夷Alguna vez te relajas en los clubes[n]nocturnos de Shibuya o comes sushi en[n]Ginza?

[sel SEL_022 top]
No hay clubes nocturnos para nosotros.
A veces comemos sushi.
夷Por qu姻 hablas as胤?

[msg MSG_023 [Yukiko]]
斡Oh, entonces, tenemos que golpear all胤!

[msg MSG_024 [Ryuji]]
夷Qu姻? 夷Hab姻is estado en un club[n]nocturno?

[msg MSG_025 [Kanji]]
Bueno, Senpai nos arrastr吋...

[msg MSG_026 [Yosuke]]
夷Hablas en serio?

[msg MSG_027 [Yusuke]]
Eso no es decir que es bueno porque es[n]caro, pero ciertamente es delicioso...

[msg MSG_028 [Yukiko]]
Pens姻 que as胤 eran las celebridades de[n]la ciudad.

[msg MSG_029 [Futaba]]
Pero ustedes tienen un 胤dolo nacional en[n]su grupo...

[msg MSG_030 [Chie]]
Hombre, la ciudad suena genial.[n]Probablemente tengan mucho que hacer ah胤[n]arriba.
El 雨nico lugar donde tenemos que salir[n]es Junes.

[msg MSG_031 [Ann]]
夷Junios?

[msg MSG_032 [Chie]]
夷Es como un supermercado?
Pero tambi姻n vende electr吋nica, ropa y[n]cosas. Incluso hay una corte de comida[n]en el techo.

[msg MSG_033 [Ann]]
斡Eso es conveniente! Estoy tan celoso.[n]Me encantar胤a comprobarlo alg雨n d胤a.

[msg MSG_034 [Chie]]
夷Eh? It's not that out of the ordinary,[n]is it...?

[msg MSG_035 [Yosuke]]
La ciudad no tiene grandes almacenes[n]as胤.

[msg MSG_036 [Chie]]
Muy bien, te mostrar姻 la pr吋xima vez. 斡Y[n]Yosuke puede tratarte en la corte de[n]comida!

[msg MSG_037 [Yosuke]]
夷Por qu姻 yo? Bien, lo que sea,[n]probablemente s吋lo pedir茨 filete de[n]nuevo de todos modos...
Bueno, es algo que esperar cuando[n]regresemos. Ahora mismo necesitamos[n]encontrar ese agujero.
Vamos, chicos.

