[msg MSG_000 [Morgana]]
斡Maldita sea! Todav胤a est茨 de pie.

[msg MSG_001 [Chie]]
斡D姻jalo ya!
Bien, te terminar姻 con mi t姻cnica[n]secreta de kung fu!

[msg MSG_002 [Ann]]
夷Qu姻? 斡Espera, Chie! 斡Yo tambi姻n voy!

[sel SEL_003 top]
斡Espera!
斡Es demasiado peligroso!

[msg MSG_004 [Morgana]]
Demasiado tarde! 斡Ya se han ido!

[msg MSG_005 [P4 Hero]]
No te preocupes, Chie suele ser bastante[n]duro en estas situaciones. Estar茨n bien.

[msg MSG_006 [Chie]]
斡Aqu胤 va! 斡Hiiiyah!

[msg MSG_007 [Ann]]
斡M-Yo tambi姻n! 斡Aqu胤 voy! 斡Hiiiyah!

