[msg MSG_000 [Elizabeth]]
Para esta proyecci吋n especial, todos[n]ustedes ser茨n obligados a completar una[n]determinada misi吋n.

[msg MSG_001 [Yosuke]]
夷Misi吋n?

[msg MSG_002 [Elizabeth]]
Me gustar胤a que llegaras a la ubicaci吋n[n]que especifique.

[msg MSG_003 [Chie]]
夷Huh? 夷Eso es todo? 斡Eso suena f茨cil!

[msg MSG_004 [Elizabeth]]
Tal vez, pero las cosas raramente van[n]como estaba planeado. Tal es el camino[n]del mundo.

[sel SEL_005 top]
夷Qu姻?
Lo vi venir...
No hay problema.

[msg MSG_006 [Morgana]]
Vamos, deber胤as haber visto eso venir.

[msg MSG_007 [Ryuji]]
Amigo, 夷algo te molesta? 夷Incluso un[n]poco?

[msg MSG_008 [Yosuke]]
Siempre tocando bien.

[msg MSG_009 [Elizabeth]]
Dicho esto, parece que el sindicato se[n]ha vuelto consciente recientemente de[n]nuestros planes...
Como resultado, la seguridad se ha[n]elevado al nivel m茨ximo.
Los detalles de la guardia y la[n]actividad de b雨squeda ser茨n megatones[n]m茨s pesados de lo habitual.

[msg MSG_010 [Ryuji]]
Esto es un dolor que escucha sobre[n]eso...

[msg MSG_011 [Ann]]
Eso es...

[msg MSG_012 [Chie]]
斡S胤, es perfecto!
Deslizar los focos de b雨squeda es algo[n]que un ladr吋n fantasma har胤a!

[msg MSG_013 [Ryuji]]
夷Qu姻 tienen esos dos tan preparados?[n]夷Algo sucede?

[sel SEL_014 top]
Est茨n motivados.
Son buenos amigos.
No podemos dejar que nos muestren.

[msg MSG_015 [Ryuji]]
Bueno, eso es genial, supongo...
Honestamente, sin embargo, es un par muy[n]raro, ahora que lo pienso.

[msg MSG_016 [Ryuji]]
Bueno, eso es genial, supongo... Still,[n]they weren't always that close, were[n]they?

[msg MSG_017 [Ryuji]]
夷Qu姻 es esto, una competencia?
Solo digo que es un par raro, 夷no crees?

[msg MSG_018 [Yosuke]]
Bueno, son diferentes entre s胤. No[n]parecen tener nada en com雨n...

[msg MSG_019 [Teddie]]
Una chica dulce de la ciudad y un amante[n]de la carne del pa胤s...
Ambos tan diferentes pero tan bonito![n]斡No puedo soportar elegir entre ellos!

[msg MSG_020 [Ann]]
Hola. 夷Qu姻 est茨n murmurando por ah胤?

[msg MSG_021 [Chie]]
斡Te vas a quedar atr茨s!

[msg MSG_022 [Kanji]]
Realmente est茨n arreglados... Supongo[n]que deber胤amos irnos tambi姻n.

