[msg MSG_000 [Makoto]]
Bueno, llegamos al agujero. 夷Eso es todo[n]lo que necesit茨bamos hacer?

[msg MSG_001 [Elizabeth]]
S胤, eso bastar茨.
Nuestras intenciones deben ser claras.[n]Dudo que el sindicato haga un movimiento[n]pronto...

[msg MSG_002 [Makoto]]
... 夷Syndicate?

[msg MSG_003 [Elizabeth]]
Nada. S吋lo hablaba conmigo mismo. M茨s[n]importante...
Bien hecho superando esos obst茨culos y[n]completando la misi吋n.
Parece que el MVP, o deber胤a decir,[n]liderar el papel femenino, no era otro[n]que Chie.

[msg MSG_004 [Chie]]
夷M-me?

[msg MSG_005 [Ann]]
斡S胤, fuiste realmente incre胤ble al[n]final!
Fue como ver una pel胤cula de acci吋n. No[n]pod胤a mirar lejos.

[msg MSG_006 [Chie]]
Ahaha... Es un poco embarazoso escuchar[n]todo eso de ti, Ann.
En mi opini吋n, eres m茨s genial que yo.
Eres preciosa, tu ingl姻s es genial, 斡y[n]eres un ladr吋n fantasma! 斡Est茨s en otra[n]liga!

[sel SEL_007 top]
Eso no es verdad.
Eres incre胤ble.
Creo que Risette es el m茨s genial.

[msg MSG_008 [Ryuji]]
S胤, no seas tan duro contigo mismo. Las[n]notas de Ann son terribles fuera del[n]ingl姻s.

[msg MSG_009 [Ann]]
斡No tan terrible como el tuyo!
Sinceramente, creo que eres m茨s genial[n]que yo, Chie.

[msg MSG_010 [Chie]]
夷Eh?

[msg MSG_011 [Ann]]
S胤. Sinceramente, creo que eres m茨s[n]genial que yo, Chie.

[msg MSG_012 [Chie]]
夷Eh?

[msg MSG_013 [Rise]]
夷Yo?

[msg MSG_014 [Ryuji]]
Bueno, ella es un 胤dolo nacional.

[msg MSG_015 [Chie]]
Rise es incre胤ble, pero supongo que[n]ahora estoy acostumbrado a ella...
Tambi姻n es m茨s joven que yo. Siento que[n]eso hace que la comparaci吋n sea un poco[n]diferente.

[msg MSG_016 [Ann]]
Supongo que tengo muchas cosas para[n]m胤...
Pero por eso, nunca he sabido lo que[n]quiero hacer o lo que quiero trabajar.
Siempre he estado inspirada por personas[n]que intentan ser las m茨s dif胤ciles de[n]conseguir bueno en algo que les gusta.

[msg MSG_017 [Chie]]
夷Inspirado?

[msg MSG_018 [Ann]]
S胤. Siempre te excitas tanto cuando[n]hablas de cosas como kung fu o carne.

[msg MSG_019 [Yosuke]]
Dir姻...

[msg MSG_020 [Ann]]
Pero creo que me inspiraste incluso[n]antes de eso...
Supongo que cuando te veo haciendo lo[n]tuyo, as胤 es como quiero ser. Yo tambi姻n[n]quiero hacer lo m胤o.

[msg MSG_021 [Chie]]
夷C吋mo quieres ser...?
Tampoco he pensado mucho en mi futuro,[n]pero...
S姻 que quiero ser m茨s fuerte para[n]proteger a mis amigos.

[sel SEL_022 top]
夷No eres igual, Ann?
Ustedes dos son iguales.

[msg MSG_023 [Ann]]
S胤. No pude proteger a alguien muy[n]importante para m胤...
Me dije que crecer胤a m茨s fuerte para que[n]nadie m茨s tuviera que pasar por lo que[n]hizo.

[msg MSG_024 [Chie]]
夷Por eso quer胤as aprender kung fu?

[msg MSG_025 [Ann]]
No era tanto el kung fu que me[n]interesaba, ya que era la fuerza de tu[n]coraz吋n.
Lo siento... Supongo que ahora parece[n]que te enga隠姻.

[msg MSG_026 [Chie]]
斡De ninguna manera! Es bueno saber que[n]estoy luchando junto a alguien que[n]siente lo mismo!
Adem茨s, todo esto fue una gran[n]experiencia de aprendizaje.
Apuesto a que, si trabajamos juntos,[n]podemos crecer a雨n m茨s. Es como esas[n]palabras de sabidur胤a...

[sel SEL_027 top]
夷Te refieres a un proverbio?
All-you-eat steak skewers."
"Dos cabezas son mejores que una."

[msg MSG_028 [Chie]]
S胤, un proverbio. 夷Pero cu茨l era?

[msg MSG_029 [Naoto]]
Una frase relativa al trabajo en[n]equipo... "Dos cabezas son mejores que[n]una", tal vez?

[msg MSG_030 [Chie]]
斡S胤, s胤! 斡Eso es!

[msg MSG_031 [Chie]]
Eso suena incre胤ble... 斡Espera, no, no[n]es eso!

[msg MSG_032 [Naoto]]
Una frase relativa al trabajo en[n]equipo... "Dos cabezas son mejores que[n]una", tal vez?

[msg MSG_033 [Chie]]
斡S胤, s胤! 斡Eso es!

[msg MSG_034 [Chie]]
S胤, creo que eso es todo..?

[msg MSG_035 [Naoto]]
Una frase que sugiere usar el trabajo en[n]equipo para lograr un objetivo.

[msg MSG_036 [Ann]]
Trabajo en equipo, 夷eh? 斡S胤, estoy[n]seguro de que podemos hacer eso!
As胤 como trabaj茨bamos juntos para[n]aprovechar esas sombras como "斡BAM!"

[msg MSG_037 [Chie]]
S胤, si alguien se pone de nuestro lado[n]malo, est茨n recibiendo una dosis doble[n]de "BAM!"

[sel SEL_038 top]
Suena bien.
Suena aterrador.

[msg MSG_039 [P4 Hero]]
S胤.

[msg MSG_040 [Elizabeth]]
Un ladr吋n de fantasmas sexy y un maestro[n]de kung fu sin miedo...
Parecer胤a que un nuevo v胤nculo ha[n]comenzado a florecer al concluir esta[n]misi吋n.
Tambi姻n, mis disculpas por el ligero[n]retraso, pero aqu胤 est茨 su recompensa.

