[msg MSG_000 [Ann]]
Uff... Parece que lo hemos logrado.

[msg MSG_001 [Chie]]
Tボo, esto si que cansa...

[msg MSG_002 [Ann]]
Dices eso, ムpero lo has hecho perfectamente!

[msg MSG_003 [Chie]]
メD-De verdad? Jejeje... Seguramente sea porque eres una profesora excelente, Panther...

[msg MSG_004 [Ann]]
Yo solo te he dado una pequeワa pista, eso es todo.
Puede que incluso est〒s hecha para formar parte de los Ladrones Fantasma.

[sel SEL_005 top]
Eres bienvenida a unirte.
メY el Equipo de Investigaciポn?
Serホ una dobre vida.

[msg MSG_006 [Yukiko]]
Aunque te unieras a los Ladrones Fantasma, estaremos aquボ siempre para ti, Chie.

[msg MSG_007 [Teddie]]
El Equipo de Investigaciポn Y los Ladrones Fantasma, メhm?
Con alguien tan apasionada como tマ, Chie, seguro que lo harボas genial en ambos.

[msg MSG_008 [Chie]]
ムSerボa como, investigadora por el dボa, y ladrポn fantasma por la noche! メAlgo asボ?

[msg MSG_009 [Teddie]]
Con alguien tan apasionada como tマ, Chie, seguro que lo harボas genial en ambos.

[msg MSG_010 [Teddie]]
El Equipo de Investigaciポn Y los Ladrones Fantasma, メhm?
Con alguien tan apasionada como tマ, Chie, seguro que lo harボas genial en ambos.

[msg MSG_011 [Yukiko]]
Aunque te unieras a los Ladrones Fantasma, estaremos aquボ siempre para ti, Chie.

[msg MSG_012 [Ann]]
Sボ, ムestoy segura de que serボas un genial Ladrポn Fantasma, Chie!

[msg MSG_013 [Chie]]
Ay, estホis haciendo que me sonroje.
No conseguirボais nada conmigo, excepto quizホs algマn chicle de carne...

[msg MSG_014 [Yosuke]]
Oh, no gracias. Estamos bien.

[msg MSG_015 [Chie]]
Aun asボ, me alegra mucho oボrte decir eso, Panther...

[msg MSG_016 [Ann]]
メEh?

[msg MSG_017 [Chie]]
Eres como una supermodelo de la ciudad.
Sボ, eres muy guapa, pero tambi〒n tienes estilo. Estホs a la マltima en moda y esas cosas.

[msg MSG_018 [Teddie]]
Hmm, ya veo... Es verdad que tu belleza estホ a la altura de nuestras chicas del campo...
Y tマ eres una grandi-osa dama a la moda, Panther.

[msg MSG_019 [Ann]]
メDe verdad piensas eso?

[msg MSG_020 [Yosuke]]
Pues sボ, en la ciudad se pueden encontrar las マltimas tendencias de moda, メno?

[msg MSG_021 [Yukiko]]
メVais a menudo a los clubes nocturnos de Shibuya, o a comer sushi en Ginza?

[sel SEL_022 top]
No hay clubes nocturnos para nosotros.
A veces comemos sushi.
メPor qu〒 estホs hablando asボ?

[msg MSG_023 [Yukiko]]
Oh, entonces, ムte hemos ganado!

[msg MSG_024 [Ryuji]]
メQu〒? メHab〒is estado de verdad en un club nocturno?

[msg MSG_025 [Kanji]]
Sボ, Senpai nos llevポ allボ...

[msg MSG_026 [Yosuke]]
メEn serio...?

[msg MSG_027 [Yusuke]]
Eso no quiere decir que sea bueno porque es caro, pero desde luego es delicioso...

[msg MSG_028 [Yukiko]]
Pensaba que asボ hablaban los famosos de ciudad.

[msg MSG_029 [Futaba]]
Pero vosotros ten〒is una idol nacional en vuestro grupo...

[msg MSG_030 [Chie]]
Tボo, la ciudad suena genial. Seguro que pod〒is hacer muchas cosas allボ.
Prホcticamente, el マnico lugar que tenemos para pasar el rato es el Junes.

[msg MSG_031 [Ann]]
メJunes?

[msg MSG_032 [Chie]]
Oh, メserボa como un supermercado?
Pero tambi〒n vende cosas de electrポnica, ropa y esas cosas. Hay incluso una zona de comida en la azotea.

[msg MSG_033 [Ann]]
Wow, ムqu〒 chulo! Qu〒 envidia me da. Me gustarボa ir allボ algマn dボa.

[msg MSG_034 [Chie]]
メEh? Es de lo mホs normal, メno?

[msg MSG_035 [Yosuke]]
En la ciudad realmente no hay grandes almacenes asボ.

[msg MSG_036 [Chie]]
Muy bien, entonces, ムos lo enseワar〒 la prポxima vez! ムY Yosuke puede invitaros a la zona de comida!

[msg MSG_037 [Yosuke]]
ムメPor qu〒 yo?! Bien, da igual, de todos modos seguramente volvホis a pedir filetes...
Bien, es algo que tenemos que pensar cuando volvamos. Ahora tenemos que encontrar esa alcantarilla.
Vamos, chicos.

