[msg MSG_000 [Morgana]]
斡Joder...! Sigue en pie.

[msg MSG_001 [Chie]]
Ugh, 斡d姻jalo ya!
Bien, 斡acabar姻 contigo con mi t姻cnica secreta de kung-fu!

[msg MSG_002 [Ann]]
斡夷Qu姻?! 斡Espera, Chie! 斡Yo tambi姻n voy!

[sel SEL_003 top]
斡Esperad!
斡Es muy peligroso!

[msg MSG_004 [Morgana]]
斡Muy tarde! 斡Ya se han ido!

[msg MSG_005 [P4 Hero]]
No os preocup姻is, Chie es muy dura en estas situaciones. Estar茨n bien.

[msg MSG_006 [Chie]]
斡All茨 vamos! 斡Hiiiyah!

[msg MSG_007 [Ann]]
斡Y-Yo tambi姻n! 斡All茨 voy! 斡Hiiiyah!

