[msg MSG_000 [Elizabeth]]
Bienvenidos de vuelta. Supongo que encontraron la amonita...

[msg MSG_001 [P4 Hero]]
... Sボ, pero...

[msg MSG_002 [Makoto]]
Estホn un poco ocupados ahora... メTe importarボa darles un momento?

[msg MSG_003 [Elizabeth]]
メOcupados?

[msg MSG_004 [Yusuke]]
Siento que ahora formo parte del mundo antiguo...
ムYo soy la amonita! ムLa amonita es yo!

[msg MSG_005 [Yukiko]]
Absolutamente... ムS〒 exactamente lo que quieres decir, Yusuke! ムViva las amonitas!

[msg MSG_006 [Elizabeth]]
...
Por favor, avisadme cuando acaben.

[msg MSG_007 [Makoto]]
Perdポn por esto...

[msg MSG_008 [Teddie]]
Me estホ empezando a preocupar que hayamos perdido a la antigua Yuki para siempre...

[msg MSG_009 [Haru]]
メPero no estホs emocionado por ver el arte de Yukiko? Ella podrホ finalmente dejar que sus emociones fluyan.

[msg MSG_010 [Yusuke]]
Few... Yo dirボa que no estホ tan mal. メQu〒 hay de ti, Amagi?

[msg MSG_011 [Yukiko]]
ムYo tambi〒n he dibujado uno!

[msg MSG_012 [Yusuke]]
ムE-Esto es...!

[sel SEL_013 top]
Una explosiポn.
メUna amonita?
No estoy seguro...

[msg MSG_014 [Yusuke]]
Si, ムes una explosiポn de imaginaciポn! ムUn big bang del arte!

[msg MSG_015 [Yusuke]]
La amonita ha abandonado, no, explotado su caparazポn... ムQu〒 maravilloso!

[msg MSG_016 [Yusuke]]
Efectivamente. Tanta creatividad me ha dejado a mボ tambi〒n sin palabras... ムEs verdaderamente alucinante!

[msg MSG_017 [Yukiko]]
No... Yo solo he seguido tu consejo, Yusuke
Tマ me enseワaste a dejarme llevar... No habボa hecho nada parecido antes, pero...
Nunca pens〒 que me sentirボa asボ de bien...

[msg MSG_018 [Yusuke]]
No... Esto fue enteramente obra tuya.
... Debo de darte las gracias.

[msg MSG_019 [Yukiko]]
メEh?

[msg MSG_020 [Yusuke]]
Dibujar no es tan simple como tener destreza o conocimiento.
Es un arte que nace del alma, de las experiencias pasadas. Son estas cosas las que dan lugar a la creatividad...
Creボa que debボa enseワarte, pero resulta que has acabado enseワホndome tマ a mボ.

[msg MSG_021 [Yukiko]]
No del todo. Mi arte no se compara en nada al tuyo.
Si te parece bien, メcrees que podrボa quedarme tu dibujo?
Si quiero decorar la posada, necesito algo tan expresivo como esto.

[msg MSG_022 [Yusuke]]
Me enorgullece oボr eso.
Y, メpodrボa pedirte que me dieras tu dibujo, Amagi?
Quiero recordar el sentimiento de inspiraciポn que he tenido hoy.

[msg MSG_023 [Yukiko]]
ムPor supuesto!

[msg MSG_024 [Chie]]
メHan podido dibujar sus cuadros?

[msg MSG_025 [Yukiko]]
ムSボ! ムMira!

[msg MSG_026 [Chie]]
Wow... Es realmente algo...

[msg MSG_027 [Makoto]]
Sボ, es... definitivamente マnico, pero creo que tambi〒n es bonito por esa razポn.
Ustedes dos parecen muy conectados.

[msg MSG_028 [Teddie]]
Al trabajar juntos, ムobtuvieron una doble explosiポn de creatividad!

[msg MSG_029 [Yusuke]]
ム...!

[msg MSG_030 [Yukiko]]
ムYusuke...!

[msg MSG_031 [Yusuke]]
ムSボ...! ムDeberボamos de poder usar esto en combate!

[msg MSG_032 [Chie]]
Oh, ahボ van de nuevo.

[msg MSG_033 [Futaba]]
Estar en la misma onda de Inari... Ella tiene mucho talento...

[msg MSG_034 [Yusuke]]
Me gustarボa agradeceros a todos.
Con esto, los Ladrones Fantasma ahora serホn aマn mホs poderosos.

[sel SEL_035 top]
Contamos contigo.
Suena bien.

[msg MSG_036 [Yusuke]]
Dejホdmelo a mボ.

[msg MSG_037 [Yukiko]]
Oh, es verdad. Prometボ que os darボa algo a cambio.

[msg MSG_038 [Teddie]]
メAlgo a cambio?

[msg MSG_039 [Yukiko]]
Mmm. Estaba planeando cocinarle algo a Yusuke como forma de agradecerle...

[msg MSG_040 [Chie]]
ムメPor qu〒 no lo habボas dicho antes?! ムTe ayudar〒!

[msg MSG_041 [Teddie]]
E-Eso probablemente sea...

[msg MSG_042 [Kanji]]
Una mala idea. Alguien la va a palmar...

[msg MSG_043 [P4 Hero]]
... Si vas a cocinar algo, nos gustarボa echar una mano tambi〒n.

[msg MSG_044 [Kanji]]
ムS-Sボ! Si Yukiko nos lo quiere agradecer, ムentonces le ayudaremos nosotros tambi〒n!

[msg MSG_045 [Yusuke]]
Tus amigos son increボbles, Amagi.

[msg MSG_046 [Yukiko]]
ムSボ! ムDe ahora en adelante tendr〒 que esforzarme aマn mホs por todos!

