[msg MSG_000 [Rise]]
ムOh! Siento que hay agua por aquボ cerca. ムDeberボan de estar ya casi!

[msg MSG_001 [Ryuji]]
Oye, メde verdad vamos a encontrar alguna de esas amonitas aquボ? Vivボan en el oc〒ano, メno?

[msg MSG_002 [Makoto]]
Asボ es. Supuestamente, las amonitas vivボan en el fondo del oc〒ano.
Se dice que esos fポsiles se han encontrado en rボos y lagos que antes formaban parte del oc〒ano.

[msg MSG_003 [Yusuke]]
Ahh. Podremos desenterrar el mundo antiguo con nuestras propias manos... ムEsto sin duda despertarホ mi creatividad!

[msg MSG_004 [Chie]]
Um... メFox siempre es asボ?

[sel SEL_005 top]
Bastante.
Estホ mホs tranquilo que de costumbre.

[msg MSG_006 [Futaba]]
En realidad, ahora no estホ tan mal.
Quiero decir, el otro dボa querボa escalar el Monte Fuji solo para poder pintar el amanecer.

[msg MSG_007 [Chie]]
ムメEn serio?!

[msg MSG_008 [Futaba]]
Sボ, bastante en serio.
Quiero decir, el otro dボa querボa escalar el Monte Fuji solo para poder pintar el amanecer.

[msg MSG_009 [Haru]]
Sボ... Al menos pudimos evitar que subiera solo con su uniforme.

[msg MSG_010 [Ryuji]]
Normalmente, es tranquilo, pero cuando se pone asボ, nunca se sabe lo que podrボa hacer...
El tipo es un aut〒ntico loco por el arte. Simplemente no sabe contenerse.

[msg MSG_011 [Yusuke]]
メUn loco, dices? Deberボas saber que yo tengo mejores notas que tマ...

[msg MSG_012 [Ryuji]]
ムEso no es lo que estoy diciendo! ムNo me desprecies asボ!

[msg MSG_013 [Yukiko]]
メNo sabe contenerse? Honestamente, me da un poco de envidia.

[msg MSG_014 [Chie]]
Yukiko...

[msg MSG_015 [Yukiko]]
Yo siempre he tratado de actuar correctamente y cumplir las expectativas de todos.
Quizホ eso aparezca tambi〒n en mis dibujos.

[msg MSG_016 [Yusuke]]
Asボ que era eso... No te preocupes, Amagi.
La pasiポn que tienes en tu corazポn es real.
ムTe ayudar〒 a soportarlo todo! ムAhora, vete! ムExponte al mundo!

[sel SEL_017 top]
Vamos a parar aquボ.
Quizホ deberボas contenerte.
ムAyuda! ムPolicia!

[msg MSG_018 [Makoto]]
Fox... メPodrボa hablar contigo un momento?

[msg MSG_019 [Yusuke]]
Y-Yo solo estoy intentando enseワarle a Amagi las maravillas del arte...

[msg MSG_020 [Chie]]
Sボ, sボ, dボselo al juez.

[msg MSG_021 [Futaba]]
Olvidホndonos del bicho raro por ahora, ムya casi estamos! ムAdelante!

