[msg MSG_000 [Ann]]
Bueno, ya estamos. 斡Estoy segura de que esta vez encontraremos alguna!

[msg MSG_001 [Yusuke]]
斡Vale! 斡Encontrar姻 una amonita, cueste lo que cueste!

[msg MSG_002 [Ryuji]]
Bro, no encuentro una mierda... Quiero decir, 夷qu姻 es de hecho una amonita?

[sel SEL_003 top]
Ni idea.
Es como una caracola.
Una criatura de otro universo.

[msg MSG_004 [Yosuke]]
斡夷Quieres decir que estabas buscando sin siquiera saber lo que era?!

[msg MSG_005 [Makoto]]
*suspiro* Una amonita es un tipo de criatura marina con un caparaz吋n.
M茨s espec胤ficamente, es como un calamar o un pulpo que vive dentro de un caparaz吋n.

[msg MSG_006 [Makoto]]
Correcto, una amonita es un tipo de criatura marina con un caparaz吋n.
M茨s espec胤ficamente, es como un calamar o un pulpo que vive dentro de un caparaz吋n.

[msg MSG_007 [Kanji]]
斡夷En serio?!

[msg MSG_008 [Makoto]]
Podr胤a parecerlo, 斡pero no! Es un tipo de criatura marina con un caparaz吋n.
M茨s espec胤ficamente, es como un calamar o un pulpo que vive dentro de un caparaz吋n.

[msg MSG_009 [Yusuke]]
Calamares y pulpos... Me est茨 entrando hambre solo de o胤rlo.

[msg MSG_010 [Yukiko]]
Sabes Fox, tu inter姻s por la comida es realmente asombroso.

[msg MSG_011 [Yusuke]]
Perd胤 a mis padres cuando era joven, y debido a esto, tuve dificultades con el dinero.
Hab胤a un hombre que me cuidaba, pero por diversas razones, me he vuelto a encontrar solo.

[msg MSG_012 [Yukiko]]
Oh... Siento o胤r eso. 

[msg MSG_013 [Yusuke]]
No, est茨 muy bien. Actualmente, los materiales de arte son mi mayor gasto...
De esos no puedo prescindir. Incluso si eso significara comer hierba de nuevo.

[msg MSG_014 [Yukiko]]
S胤 que te apasiona el arte.

[msg MSG_015 [Yusuke]]
Bueno, no estar胤a aqu胤 si estuviera realmente solo.
He tenido un mont吋n de apoyo de mis amigos. Ellos me salvaron y me dieron un lugar al que pertenecer.

[msg MSG_016 [Yukiko]]
Creo que ahora lo entiendo.
La raz吋n por la que puedo ser yo misma es porque estoy rodeada de gente que me acepta tal y como soy.

[msg MSG_017 [Yusuke]]
Correcto. Con pasi吋n o sin pasi吋n, no puedo hacerlo solo.
No s姻 cuantas veces me ha dado de comer la cafeter胤a donde Joker vive...

[msg MSG_018 [Yukiko]]
Siento que eso es un poco diferente.
Pero, si te falta comida, 夷por qu姻 no te preparo algo para darte las gracias?

[msg MSG_019 [Yusuke]]
斡夷Qu姻?! 斡夷Est茨s segura?!

[msg MSG_020 [Chie]]
斡Eeey! 夷Han encontrado algo?

[msg MSG_021 [Yukiko]]
No, a雨n no.

[msg MSG_022 [Naoto]]
Entonces quiz茨s deber胤amos ir a otro sitio.
Rise ha dicho que ha detectado m茨s agua al este de aqu胤.

[msg MSG_023 [Yukiko]]
Entonces, 斡es all胤 adonde tenemos que ir despu姻s! 斡Vamos, Fox!

[msg MSG_024 [Yusuke]]
S胤, 斡vamos!

[msg MSG_025 [Chie]]
Ey, 斡esperad el par de dos! 夷No me digas que ahora Yukiko est茨 loca por el arte tambi姻n?

[msg MSG_026 [Futaba]]
Supongo que Fox realmente la ha impresionado.
De todas formas, tenemos m茨s agua al este. 斡Vamos a comprobarlo!

