[msg MSG_000 [Futaba]]
斡La tercera vez es el encanto! 斡Lo[n]tenemos!

[msg MSG_001 [Kanji]]
斡S胤! 斡Hag茨moslo!

[msg MSG_002 [Yusuke]]
夷Hm? 夷Podr胤a ser...?

[msg MSG_003 [Ryuji]]
斡Oh! 夷Encontraste uno?

[msg MSG_004 [Yusuke]]
No, s吋lo esta hierba extra隠a. 夷Es alg雨n[n]tipo de algas?
Tal vez probar姻 un mordisco...

[msg MSG_005 [Ryuji]]
斡Amigo, de ninguna manera! 斡Eso te[n]arruinar茨 el est吋mago!

[msg MSG_006 [Naoto]]
夷Algas marinas? Eso significar胤a...

[msg MSG_007 [Yukiko]]
Fox! 斡Mira esto!

[msg MSG_008 [Kanji]]
夷M茨s algas?

[msg MSG_009 [Yusuke]]
斡Mira! 斡Es una amonestaci吋n real!

[msg MSG_010 [Yukiko]]
斡Vaya! 斡Nunca hab胤a visto uno de verdad![n]斡Realmente existen!

[msg MSG_011 [Naoto]]
Esto debe ser agua de mar.
Es probable que el agua aqu胤 fuera parte[n]del oc姻ano antes de que la forma de la[n]tierra cambiara.

[msg MSG_012 [Yusuke]]
El patr吋n en su c茨scara... Sus[n]tent茨culos... Nunca imagin姻 que podr胤a[n]ver a una criatura tan antigua de cerca.
Debo tener suerte...

[msg MSG_013 [Ryuji]]
Ni siquiera pienses en comerlo...

[msg MSG_014 [Yusuke]]
夷Por qu姻 lo comer胤a? 夷Te sientes bien,[n]Skull?

[msg MSG_015 [Ryuji]]
S胤... Lo siento.

[msg MSG_016 [Rise]]
Misi吋n cumplida! 斡Vuelvan todos!

[msg MSG_017 [Yusuke]]
Ohh, simplemente no puedo esperar a[n]capturar esta emoci吋n que siento ahora[n]mismo!

[msg MSG_018 [Yukiko]]
斡Mhm! 斡Yo tambi姻n! Creo que ahora[n]finalmente podr姻 dibujar sin tener nada[n]atr茨s!

[msg MSG_019 [Morgana]]
Bueno, ah胤 lo tienes. Vamos, Joker.

