[msg MSG_000 [Futaba]]
ムObjetivo localizado! ムQu〒 se lo quede!

[msg MSG_001 [Ryuji]]
Sabes, ahora que estoy viendo la carne, o arma, o lo que sea... Esa cosa es malditamente gigante.

[msg MSG_002 [Yusuke]]
Lo sabボa. Cuanto mホs lo veo, mi curiosidad y mi apetito se hacen mホs fuertes.

[msg MSG_003 [Chie]]
Oh, tボo, メeso es pollo frito? Eso podrボa alimentar como, cinco, no, ムdiez personas!

[msg MSG_004 [Yosuke]]
Ey, esperad, chicos. Es muy peligroso entrar ahボ solos.
Nosotros tambi〒n estamos aquボ, asボ que no se lo queden todo para ustedes, メcorrecto?

[msg MSG_005 [Chie]]
... Tienes razポn. Tenemos que dividirlo en partes iguales.

[msg MSG_006 [Yosuke]]
ムNo me referボa a la carne! ムDecボa que no te llevaras toda la gloria!

[msg MSG_007 [Kanji]]
メEh? Suenas muy entusiasmado, Yosuke.

[msg MSG_008 [Yosuke]]
Jaja. Sボ, supongo...
ムMuy bien, acabemos con este tipo!

