[msg MSG_000 [Chie]]
*sniff* *sniff*
S胤... 斡Eso es! 斡El olor de la carne jugosa!

[msg MSG_001 [Yusuke]]
Hm, s胤. Yo tambi姻n estoy percibiendo el d姻bil aroma a carne del sur...

[msg MSG_002 [Ryuji]]
夷Eh? Yo no puedo oler ninguna maldita cosa.

[msg MSG_003 [Yosuke]]
No te preocupes, est茨s bien. Solo tienen un extra隠o sentido del olfato.

[msg MSG_004 [Teddie]]
Hrm, hrm... 斡Yo tambi姻n lo puedo oler! 斡El dulce aroma de la ternera!

[msg MSG_005 [Ann]]
夷Eh? Pensaba que el FOE llevaba pollo, no ternera.

[msg MSG_006 [Futaba]]
Bueno, pollo o ternera, definitivamente detecto un FOE al sur.

[msg MSG_007 [Yosuke]]
Oh, 夷estamos cerca? 斡Muy bien, vamos!

[msg MSG_008 [Rise]]
斡Esperad, chicos! 斡Siento un mont吋n de cajas del tesoro al norte!

[msg MSG_009 [Morgana]]
斡夷T-Tesoro?!

[msg MSG_010 [Makoto]]
Oh, es verdad. En las proyecciones especiales, no solo el 茨rea es diferente, sino que el dise隠o tambi姻n, 夷verdad?
Supongo que esta vez tambi姻n se aplica a las cajas del tesoro.

[msg MSG_011 [Yusuke]]
Hmm. As胤 que o tomamos el camino corto y vamos directos a por la carne, o tomamos el largo y conseguimos el tesoro...

[msg MSG_012 [Chie]]
Ngh... Yo realmente quiero esa carne, pero el tesoro...

[msg MSG_013 [Morgana]]
El FOE objetivo est茨 al sur, pero una monta隠a de tesoros nos espera si vamos hacia el norte...
Como siempre, 斡te lo dejamos a ti, Joker!

