[msg MSG_000 [Futaba]]
斡Objetivo avistado! 斡D姻jalo tener!

[msg MSG_001 [Ryuji]]
Ya sabes, ahora que estoy viendo esa[n]carne, o arma, o lo que sea de nuevo...[n]Esa cosa es enorme.

[msg MSG_002 [Yusuke]]
Lo sab胤a. Cuanto m茨s lo veo, m茨s fuerte[n]ser茨 mi curiosidad y apetito.

[msg MSG_003 [Chie]]
夷Es pollo frito? 斡Eso podr胤a alimentar,[n]como, cinco personas, no!

[msg MSG_004 [Yosuke]]
Espera, chicos. Es demasiado peligroso[n]cargar all胤 solo.
Estamos aqu胤 tambi姻n, as胤 que no lo[n]tomes todo por ti, 夷de acuerdo?

[msg MSG_005 [Chie]]
... Tienes raz吋n. Tenemos que dividirlo[n]uniformemente.

[msg MSG_006 [Yosuke]]
斡No hablaba de la carne! 斡Dije que no se[n]lleve toda la gloria!

[msg MSG_007 [Kanji]]
夷Eh? Suenas bastante bombeado,[n]Yosuke-senpai.

[msg MSG_008 [Yosuke]]
Haha. S胤, supongo que...
斡De acuerdo, derribamos a este tipo!

