[msg MSG_000 [Yosuke]]
ムSボ! ムLo logramos!

[msg MSG_001 [Chie]]
ムWoohoo! ムCarne! ムCarne! ムCarne!

[msg MSG_002 [Naoto]]
Quizホ se est〒n olvidando de la verdadera razポn por la que vinimos... Era derrotar al FOE.

[msg MSG_003 [Chie]]
ムNo hay que preocuparse por los detalles, Naoto! ムBien estホ lo que bien acaba!

[msg MSG_004 [Yusuke]]
Ahora, sin mホs dilaciポn, comencemos el festボn...

[msg MSG_005 [Yusuke]]
メHm? ムメQu〒 es eso?!

[msg MSG_006 [Yosuke]]
Estホ mホs duro que una piedra... Sea lo que sea, definitivamente no es carne.

[msg MSG_007 [Chie]]
ムメQu〒eee?! ムメQu〒 quieres decir?!

[msg MSG_008 [Naoto]]
Parece ser una imitaciポn muy realista.
Aunque parezca estar hecho de carne por fuera, en verdad estホ hecho de madera.

[msg MSG_009 [Makoto]]
Bueno... Tenボa la sensaciポn de que podrボa ser el caso viendo cポmo el FOE la usaba como arma.

[msg MSG_010 [Chie]]
メEntonces no podemos com〒rnoslo? Entonces, メde dポnde venボa ese delicioso aroma a carne?

[msg MSG_011 [Akechi]]
Tengo la sensaciポn de que probablemente venボa de la hamburgueserボa de al lado.

[msg MSG_012 [Chie]]
メE- En serio...?

[msg MSG_013 [Yusuke]]
Ngh... Otra vez, estaba preparado para un festボn, y otra vez me decボs que no puedo comer. Qu〒 decepciポn mホs terrible.
Aun asボ... ムNo todo ha sido en vano!
La construcciポn, la t〒cnica de coloreado... ムApenas se distingue del original! ムNo debo olvidar esto!

[msg MSG_014 [Ann]]
Oh... Ahボ va otra vez...

[msg MSG_015 [Morgana]]
Bueno, si no nos lo podemos comer, no nos lo podemos comer.
Dirボa que ya hemos acabado aquボ. Volvamos al cine por ahora.

