[msg MSG_000 [Yosuke]]
... T胤o, no importa cuanto avancemos, siempre es lo mismo una y otra vez.
Plantas y bichos gigantes hasta donde alcanza la vista. 夷Y dinosaurios tambi姻n? Este lugar es una locura...

[msg MSG_001 [Naoto]]
Como es normal, los caminos tampoco est茨n asfaltados, haciendo dif胤cil que avancemos...

[msg MSG_002 [Kanji]]
Bueno, al menos uno de nosotros lo est茨 haciendo bien.

[msg MSG_003 [Yusuke]]
斡Ahh, qu姻 naturaleza m茨s exquisita! 斡Ni con una monta隠a de cuadernos ser胤a suficiente para captar toda esta belleza!

[msg MSG_004 [Ann]]
Oh, s胤, no os preocup姻is por 姻l.

[msg MSG_005 [Yosuke]]
Shhh, est茨 muy concentrado... 夷No se perder茨 y ser茨 comido, no?

[msg MSG_006 [Morgana]]
Honestamente, Fox es m茨s propenso a comerse a alguno de los dinosaurios...

[msg MSG_007 [Yosuke]]
斡夷Qu姻 demonios?! 斡Eso es algo que podr胤a esperar de Chie!

[msg MSG_008 [Chie]]
斡Eh! 斡Ni siquiera mi apetito me har胤a coger un dinosaurio y empezar a masticarlo!
... No es que me oponga a probar un dinosaurio o algo as胤. 斡Ninguna carne est茨 mala!

[msg MSG_009 [P3 Fem Protag]]
Hmm... aparte de la carne de dinosaurio, me pregunto cu茨ndo podremos volver a comer carne.

[sel SEL_010 top]
Hay perritos calientes en el cine.
Creo que he visto alguna antes...
Hay que conformarse con agua.

[msg MSG_011 [Chie]]
Quiero decir, los perritos calientes son geniales, pero la carne de dinosaurio es m茨s... BAM, 夷sab姻is?
斡Quiero comerme un trozo de carne tan grande que parezca que nunca pueda acabarlo!

[msg MSG_012 [Chie]]
斡夷Espera, en serio?! 斡夷D吋nde?!

[msg MSG_013 [Ryuji]]
S胤, yo creo que tambi姻n. 夷D吋nde estaba...?

[msg MSG_014 [Chie]]
Aww... Agua...
Se que me estoy quejando, pero el agua no me va ni lo m茨s m胤nimo.

[msg MSG_015 [Yusuke]]
Entonces, 夷d吋nde encontramos ese pedazo de carne gigante?

[msg MSG_016 [Ryuji]]
Eso era lo que est茨bamos diciendo. No est茨 aqu胤...
斡Espera, qu姻! 夷De d吋nde demonios has salido?

[msg MSG_017 [Yusuke]]
He o胤do que alguien mencionaba carne. Mi est吋mago est茨 listo.

[msg MSG_018 [Yosuke]]
Este chico es igual de raro que Chie...
Mira, perd吋n por decepcionarte, pero seguramente no comeremos carne por un tiempo.

[msg MSG_019 [Yusuke]]
Entonces... 夷No hay... carne?
Y yo que estaba preparado para un fest胤n... Ahora a雨n tengo m茨s hambre...

[msg MSG_020 [Chie]]
S胤, toda esta charla sobre carne tambi姻n me est茨 dando hambre...

[msg MSG_021 [Morgana]]
*suspiro* Esos dos son una pareja de carn胤voros.
Invit姻mosles a comer carne la pr吋xima vez que podamos, Joker.

[msg MSG_022]
Una nueva proyecci吋n especial: "Carne y el Arte de la Amistad" ha sido a隠adida a la taquilla.

