[msg MSG_000 [Futaba]]
斡Mira, otro oficial! 斡Vamos a[n]investigar!

[msg MSG_001 [Naoto]]
Perm胤tame.

[msg MSG_002 [Naoto]]
Gracias por esperar.
"El oficial con el coche n雨mero 77-55 es[n]real. Vinimos juntos para patrullar la[n]zona"
... As胤 que dice.

[msg MSG_003 [Futaba]]
Y el n雨mero en su coche es...
11-10. Tiene dobles.

[msg MSG_004 [Naoto]]
Tenemos lo que necesitamos. Sigamos.

[msg MSG_005]
Dijo que el oficial con el auto numerado[n]'77-55' es real, y vinieron aqu胤[n]juntos...

