[msg MSG_000 [Futaba]]
斡Muy bien! 斡Le hemos derrotado!

[msg MSG_001 [Makoto]]
Fue muy r茨pido en revelarse. Pensaba que iba a intentar hacerse el tonto.

[msg MSG_002 [Naoto]]
Normalmente, eso es lo que har胤an. Sin embargo, esto es una proyecci吋n especial.
Es esencialmente una pel胤cula, por lo que imagino que la sombra seguir胤a alg雨n tipo de regla para desarrollar el final.
Supuse que si encontr茨bamos la correcta, se ver胤a obligada a revelar su verdadero yo. Pens姻 que val胤a la pena intentarlo.

[sel SEL_003 top]
Brillante.
Eso fue asombroso, Detective.

[msg MSG_004 [Naoto]]
Por favor, no ha sido solo cosa m胤a. Lo hemos resuelto todos juntos.

[msg MSG_005 [Chie]]
S胤, 斡Oracle tambi姻n es maravillosa! 斡Ella se acordaba de todos esos testimonios!

[msg MSG_006 [Futaba]]
Jejeje. Tengo una muy buena memoria.
斡Un gran detective necesita un buen asistente! Llamadme Watson.

[msg MSG_007 [Naoto]]
夷Oh? Oracle, 夷lees novelas de detectives?

[msg MSG_008 [Futaba]]
He le胤do las cl茨sicas e incluso las m茨s nuevas y populares alguna vez.
斡Es impresionante cuantas historias puedes contar sobre casas viejas e islas desiertas!

[msg MSG_009 [Naoto]]
*risita* Me gustar胤a investigar la escena de un crimen en un lugar de esos alg雨n d胤a.
Aunque es raro que uno se encuentre una escena del crimen como las que se hallan en las novelas.
夷Cu茨ntas veces han o胤do que un detective encuentra de casualidad una escena de un crimen? En realidad eso no funciona as胤.
Tampoco puedes ver a gente merodeando por ah胤 sabiendo que hay un asesino suelto.
A diferencia del mundo de la ficci吋n, el trabajo de detective es bastante sencillo.

[msg MSG_010 [Futaba]]
斡Totalmente! 斡Esas personas que se escapan solas...!
斡Ya tendr胤as que estar muy loco para hacer eso!

[msg MSG_011 [Naoto]]
Jajaja. Es eso lo que la gente espera de las novelas de detectives, supongo.
Sin cosas como esas, los cr胤menes no ocurrir胤an, y los detectives no tendr胤an nada con lo que trabajar.

[msg MSG_012 [Futaba]]
S胤. Esas historias no ser胤an tan divertidas si solo fuera, "La polic胤a vino esta ma隠ana".

[msg MSG_013 [Naoto]]
Exactamente. El detective estar胤a sin trabajo.
Hablando de lo que se espera, he notado algo interesante...

[msg MSG_014 [Morgana]]
Eeey, no quiero estropear la diversi吋n, pero...

[msg MSG_015 [Kanji]]
夷De qu姻 demonios est茨is hablando...?

[msg MSG_016 [Naoto]]
M-Mis disculpas. Supongo que me he dejado llevar por la conversaci吋n.

[msg MSG_017 [Futaba]]
Hey, ha sido una charla divertida. 斡Volvamos a hablar sobre eso dentro de poco!

[msg MSG_018 [Naoto]]
Por supuesto, si quieres.
Entonces, volvamos. Deber胤amos compartir nuestros resultados con Elizabeth.

[msg MSG_019 [Akechi]]
... Hmm. Ha sido todo un espect茨culo, Pr胤ncipe Detective. Muy entretenido.

