[msg MSG_000 [Rise]]
ムVolved aquボ! ムLo han hecho genial, Naoto y Futaba!

[msg MSG_001 [Makoto]]
Sボ, me ha impresionado mucho la memoria de Futaba y la capacidad de anホlisis de Shirogane.
Gracias a vosotras dos, hemos sido capaces de resolver el crimen.

[sel SEL_002 top]
ムBuen trabajo!
Una pareja perfecta.
Todo es gracias a mボ.

[msg MSG_003 [Futaba]]
ムOhh! ムSuenas como un jefe de policボa!

[msg MSG_004 [Naoto]]
Gracias. Me hace feliz oボr que digas eso.
Por supuesto, no podemos olvidar que contamos con tu ayuda, [f 6 1 30 0 0 0].

[msg MSG_005 [Futaba]]
ムSボ! ムQuizホs podrボamos convertirlo en algo!

[msg MSG_006 [Naoto]]
*risita* Eres una genial compaワera, Futaba. Me encantarボa volver a trabajar contigo.

[msg MSG_007 [Morgana]]
Vamos... Deja que tengan su momento.

[msg MSG_008 [Naoto]]
*risita* Por su puesto, no lo podrボamos haber hecho sin tu liderazgo.

[msg MSG_009 [Haru]]
ムPero los detectives son superguais! ムMe qued〒 absolutamente asombrada!

[msg MSG_010 [Teddie]]
ムYo tambi〒n! ムQuiero ver mホs!

[msg MSG_011 [Rise]]
Oh, quizホs Akechi podrボa ir la prポxima vez. ムSerボa la vieja Detective Prボncipe contra el mホs moderno!

[msg MSG_012 [Yukiko]]
ムWow! ムEso serボa genial! ムSeguro que resolverボan el crimen rapidボsimo!

[msg MSG_013 [Akechi]]
Haha. Espero poder ser de ayuda.
Por cierto, lo que he visto hoy ha sido genial. Realmente me ha ayudado a ampliar mis horizontes.
Si alguna vez tenemos la oportunidad, d〒jame ayudarte, Prボncipe Detective.

[msg MSG_014 [Naoto]]
Serボa un honor. Si ese momento llega, por favor, hazlo.

