[msg MSG_000 [Naoto]]
Allボ hay otro. Voy a hablar con 〒l.

[msg MSG_001 [Futaba]]
ムVamos, Prボncipe Detective! ムEncuentra al culpable!

[msg MSG_002 [Naoto]]
Perdポn por la espera.
"El oficial con un doble 7 estホ actuando de modo sospechoso."
... Eso es todo lo que he podido obtener.

[msg MSG_003 [Futaba]]
メUn doble 7? Parece mホs un nマmero de la suerte... Quizホs la sombra quiera tener suerte.
El nマmero del coche de este tipo es...
44-11. Un doble 4 y 1.

[msg MSG_004 [Naoto]]
Gracias, Oracle. Vamos a seguir.

[msg MSG_005]
Dijo que el policボa con un doble 7 actuaba de forma sospechosa...

