[msg MSG_000 [Ryuji]]
Tsk. 'Ni un callej吋n sin salida.

[msg MSG_001 [Naoto]]
...

[msg MSG_002 [P4 Hero]]
夷Qu姻 pasa, Naoto? 夷Algo en tu mente?

[msg MSG_003 [Naoto]]
Nada. Hay algo que he estado intentando[n]averiguar.
夷Por qu姻 estas pel胤culas se ponen como[n]laberintos?

[sel SEL_004 top]
Es una coincidencia.
Es para hacernos perder.
No lo he pensado.

[msg MSG_005 [Naoto]]
Es una posibilidad. Sin embargo, siento[n]que est茨n demasiado bien dise隠ados para[n]ser una coincidencia.

[msg MSG_006 [Futaba]]
斡Aseg雨rate de llenar el mapa para que[n]eso no suceda!

[msg MSG_007 [Naoto]]
S胤. Sus dise隠os son muy complejos.

[msg MSG_008 [Ann]]
Ahora que lo mencionas... Es raro. 夷Por[n]qu姻 son as胤?

[msg MSG_009 [Futaba]]
He estado pensando en ello tambi姻n.
Es como si alguien estuviera tratando de[n]evitar que vayamos m茨s lejos.

[msg MSG_010 [Naoto]]
Este laberinto es representativo del[n]estado mental... Es una hip吋tesis[n]interesante.

[msg MSG_011 [Ann]]
夷Pero qui姻n har胤a algo tan malo?

[msg MSG_012 [Naoto]]
No estoy seguro... Aunque, basado en la[n]experiencia pasada, no est茨 fuera de la[n]cuesti吋n.

[msg MSG_013 [Chie]]
S胤, no s姻 qu姻 est茨 pasando, pero[n]definitivamente te hace usar la cabeza.
Si fuera yo, no ser胤a capaz de resolver[n]ninguno de estos trucos.

[msg MSG_014 [Ryuji]]
Tampoco soy bueno en eso. Se lo dejo a[n]Joker.
Oracle tambi姻n. Puede que sea valiente,[n]pero tambi姻n es una genio.

[msg MSG_015 [Futaba]]
"Bratty" no era necesario, 夷verdad?
Eso dijo, me gustan los juegos de[n]rompecabezas. D姻jame esas cosas.

[msg MSG_016 [Yukiko]]
Tambi姻n tenemos a Naoto. Es detective,[n]despu姻s de todo.

[msg MSG_017 [Naoto]]
Por favor, no soy nada comparado con[n]Oracle.
Pero si hay algo que pueda hacer, estar姻[n]m茨s que dispuesto a ayudar.

[sel SEL_018 top]
Contamos contigo.
Mu姻stranos esas habilidades de[n]detective.

[msg MSG_019 [Naoto]]
Ser胤a un honor. Vamos a trabajar juntos[n]para resolver esto.
Y lo mismo pasa contigo, Oracle, si[n]fueras tan amable como para ofrecernos[n]consejos cuando estamos aturdidos.

[msg MSG_020 [Futaba]]
斡S胤! 斡Hagamos todo lo posible!

[msg MSG_021]
Una nueva proyecci吋n especial: "斡Officer[n]Imposter!" se ha a隠adido a la taquilla.

