[msg MSG_000 [Elizabeth]]
En el prポximo capボtulo de Dragon Ba... quiero decir, la prポxima proyecciポn especial...

[msg MSG_001 [Futaba]]
Oh hoh. Esta prポxima parece que es de mホs de 9000...

[msg MSG_002 [Yusuke]]
メMホs de 9000? メA qu〒 te refieres?

[msg MSG_003 [Futaba]]
ムメQu〒?! ムメNo lo sabes?! ムTodo el mundo lo conoce!

[msg MSG_004 [Naoto]]
メEs asボ? Me temo que yo tampoco lo entiendo...

[msg MSG_005 [Elizabeth]]
ムSilencio, por favor! Las proyecciones especiales no debe tomarse a la ligera...
ムSi no os callホis, se enfrentarホn a mi poder de 530,000!

[msg MSG_006 [Ryuji]]
Oh, ella va a por todas con esto...

[msg MSG_007 [Naoto]]
メQu〒 tenemos que hacer, Elizabeth? Por favor, explボcanoslo.

[msg MSG_008 [Elizabeth]]
Me alegro de que preguntes.
ムEsta proyecciポn especial pide que encuentren a un imitador de policボa!
Una sombra estホ creando confusiポn entre los ciudadanos de Ciudad Kamo.

[sel SEL_009 top]
Eso es imperdonable.
メQuieres que nos hagamos cargo de eso?

[msg MSG_010 [Kanji]]
ムClaro que sボ! ムEncontraremos a la sombra y nos la cargaremos!

[msg MSG_011 [Elizabeth]]
Puede que no sea tan fホcil como lo aparenta.
La sombra estホ disfrazada como uno de los policボas que patrullan la ciudad.
Para encontrarla, necesitarホn encontrar y hablar con cada uno de ellos.

[msg MSG_012 [Chie]]
ムWow! メEntonces va a ser como una investigaciポn? ムSeremos como detectives de verdad!

[msg MSG_013 [Naoto]]
La pregunta es: メel policボa falso admitirホ que 〒l es el falso?

[msg MSG_014 [Elizabeth]]
La sombra seguramente tenderホ a mentir para evitar ser capturada.
Por lo tanto, tendrホn que hablar con todos los policボas.

[msg MSG_015 [Ann]]
Pero, メcポmo sabemos cuホl de ellos estホ mintiendo?

[msg MSG_016 [Naoto]]
Ah... Es como un acertijo de lポgica.

[msg MSG_017 [Chie]]
メAcertijo de lポgica?

[msg MSG_018 [Naoto]]
Es un tipo de acertijo donde tienes que identificar una contradicciポn entre toda la informaciポn que recibas.
En este caso, debemos hablar con los policボas y encontrar la contradicciポn en sus testimonios.

[msg MSG_019 [Futaba]]
ムEntonces tenemos que encontrar la mentira! ムSuena divertido!

[sel SEL_020 top]
Lo pillo.
Es un poco confuso...

[msg MSG_021 [Ann]]
メEn serio? Yo no entendido nada de eso... Eres muy inteligente, [f 6 1 30 0 0 0].

[msg MSG_022 [Futaba]]
ムNo se preocupen! ムYo os cubro las espaldas!

[msg MSG_023 [Naoto]]
No tienen por qu〒 preocuparos. No estホ tan mal una vez que lo intentas.
Lo primero y mホs importante, tendremos que encontrar a los policボas.

[msg MSG_024 [Akechi]]
Veamos qu〒 puedes hacer, Prボncipe Detective.

