[msg MSG_000 [Haru]]
夷As胤 que ese es el falso? Me pregunto si lo admitir茨.

[sel SEL_001 top]
Acabemos con 姻l.
Vamos a escuchar lo que dice.

[msg MSG_002 [Naoto]]
Esperad, deber胤amos volver a comprobarlo.
Ir姻 a asegurarme. Por favor, dejadme ocuparme de esto.

[msg MSG_003 [Naoto]]
De acuerdo, asegur姻monos.
Tengo una idea. Por favor, esperad aqu胤.

[msg MSG_004 [Serious Policeman]]
夷Qu姻? 夷T雨 otra vez? Estamos de servicio, deja de molestarnos.

[msg MSG_005 [Naoto]]
斡As胤 que t雨 eres el falso!
斡Rev姻late! 斡Tu farsa acaba ahora!

[msg MSG_006 [Futaba]]
斡Guau! 斡Hay un giro dr茨stico de los acontecimientos!

[msg MSG_007 [Serious Policeman]]
斡夷Q-Qu姻 est茨s diciendo?! 斡夷Qui姻n eres t雨?!

[msg MSG_008 [Naoto]]
Aqu胤 est茨 lo que me dijiste antes.
"El polic胤a con el n雨mero de coche 11-10 me parece sospechoso."
Digamos que tus sospechas eran correctas. Eso significar胤a que el oficial con el coche 11-10 es un mentiroso y un farsante...
Sin embargo, el polic胤a 11-10 afirm吋 que el polic胤a 77-55 era real.
Si el polic胤a 11-10 estuviera mintiendo sobre el polic胤a 77-55, entonces habr胤a m茨s de un mentiroso.
Por lo tanto, 斡t雨 eres el mentiroso!

[msg MSG_009 [Serious Policeman]]
斡Joder! 斡Qu姻 cr胤a m茨s loca! Voy a necesitar algunos refuerzos...
斡夷...?!
...
...斡OOOOOOHN!

[msg MSG_010 [Chie]]
斡Vaya! 斡Se ha transformado!

[msg MSG_011 [Futaba]]
斡Parece que nuestra hip吋tesis era correcta! 斡Aqu胤 viene!

