[msg MSG_000 [Futaba]]
Tendremos que encontrar a esos polic胤as primero. 斡Veamos que nos tienen que decir!

[sel SEL_001 top]
夷Por qu姻 est茨s aqu胤?
Esto es peligroso.

[msg MSG_002 [Futaba]]
P-Perd吋n... Parec胤a divertido, as胤 que pens姻 en acompa隠aros.
斡No os molestar姻! 斡Por favor, dejadme ir con vosotros!

[msg MSG_003 [Morgana]]
Eso no deber胤a ser un problema, 夷verdad? De todos modos, ella suele venir con nosotros.

[msg MSG_004 [Futaba]]
斡Oh, mirad! 斡Aqu胤 est茨 nuestro primer sospechoso!

[msg MSG_005 [Makoto]]
... Pero, por c吋mo est茨 vestido, parece que ser茨 dif胤cil hablar con 姻l.

[msg MSG_006 [Naoto]]
Por favor, permitidme ocuparme de esto.

[msg MSG_007 [Naoto]]
Perdona, 夷puedo preguntarte una cosa?
夷Es verdad que hay un polic胤a falso que est茨 causando disturbios por aqu胤?

[msg MSG_008 [Fat Policeman]]
夷Qui姻n eres? 夷D吋nde has escuchado eso?

[msg MSG_009 [Naoto]]
Oh, es solo un rumor... Pero, como ciudadana, me gustar胤a tener m茨s informaci吋n.

[msg MSG_010 [Fat Policeman]]
Hm, de acuerdo. Es importante compartir este tipo de informaci吋n con el p雨blico.
El polic胤a falso va en un coche marcado con un doble uno.
Por favor, informadnos si lo encontr茨is. Son muy peligrosos, as胤 que intentad no acercaros mucho.

[msg MSG_011 [Naoto]]
Gracias por la informaci吋n. T雨 tambi姻n ten cuidado.

[msg MSG_012 [Futaba]]
Wow, eso fue r茨pido. Buen trabajo, Detective.

[msg MSG_013 [Naoto]]
Tendremos que encontrar al resto de polic胤as y obtener m茨s informaci吋n.

[msg MSG_014 [Yusuke]]
"El polic胤a falso va en un coche marcado con un doble uno".
... As胤 que, 夷esta es nuestra pista?

[msg MSG_015 [Naoto]]
Eso no es lo 雨nico que hemos aprendido.
El oficial que hemos interrogado conduc胤a un coche marcado con los n雨meros "77-55."
Teng茨moslo tambi姻n en cuenta. Podr胤a ayudarnos a encontrar una respuesta.

[msg MSG_016 [Futaba]]
斡No te preocupes! 斡Seguro que lo recordar姻!

[msg MSG_017 [Morgana]]
斡Muy bien! 斡Sigamos con la b雨squeda!

[msg MSG_018 [Naoto]]
Kamo City es realmente grande...
Deber胤amos mejor marcar las localizaciones de los polic胤as en el mapa.

[msg MSG_019 [Futaba]]
Okay, 斡Skull! 夷D吋nde est茨n esos polic胤as?

[msg MSG_020 [Ryuji]]
夷Por qu姻 me preguntas a m胤?

[sel SEL_021 top]
夷Quiz茨s en la estaci吋n?
夷Quiz茨s en otra escena del crimen?
Busquemos sus coches.

[msg MSG_022 [Ryuji]]
No s姻 donde los encontraremos. Aunque s胤 que he visto algunos coches de polic胤a...

[msg MSG_023 [Futaba]]
斡Es verdad! 斡Hab胤a coches de polic胤a por aqu胤!

[msg MSG_024 [Futaba]]
斡Eso es! 斡Bien pensado, Joker!
斡Hab胤a algunos coches de polic胤a por aqu胤! A lo mejor encontramos algunos cerca.

[msg MSG_025 [Naoto]]
Entonces, vamos a buscar por la zona. Con un poco de suerte los encontraremos pronto.

[msg MSG_026 [Futaba]]
Oh, 斡ya s姻!
Si quieren saber d吋nde se encuentran los coches de polic胤a, 斡preguntadme a m胤!

[msg MSG_027 [Naoto]]
Eso ser胤a de gran ayuda. 夷Pero qu姻 piensas hacer exactamente?

[msg MSG_028 [Futaba]]
Si puedo hackear el sistema inform茨tico de la ciudad, sabremos exactamente d吋nde encontrarlos.
Usaban una terminal para controlar los reflectores, 夷verdad? Hackear姻 desde all胤. Jejejeje.

[msg MSG_029 [Morgana]]
夷Sabes? A veces me das miedo...

[msg MSG_030 [Naoto]]
Entonces, pensemos una estrategia.
Si queremos hablar con los polic胤as, tendremos que encontrar primero sus coches.
Y si queremos saber d吋nde est茨n los coches, tendremos que encontrar la terminal de los reflectores.

[sel SEL_031 top]
Entendido.
Vayamos yendo.

[msg MSG_032 [Naoto]]
Podemos o buscar los coches por nuestra cuenta o dirigirnos a la terminal. Eso ya te lo dejamos a ti, Joker.
Empecemos con la b雨squeda.

[msg MSG_033 [Futaba]]
斡Entendido! 斡Esto va a ser divertido! 斡Es hora de investigar!

[msg MSG_034]
Dijo que el falso polic胤a estaba en el coche con doble uno.

