[msg MSG_000 [Futaba]]
Tenemos que encontrar a esos polic胤as[n]primero. 斡Vamos a ver qu姻 tienen que[n]decir!

[sel SEL_001 top]
夷Por qu姻 est茨s aqu胤?
Es peligroso aqu胤..

[msg MSG_002 [Futaba]]
Lo siento... 畏ste se ve胤a divertido, as胤[n]que pens姻 que me ir胤a bien.
斡No los molestar姻! 斡Por favor, d姻jame ir[n]contigo!

[msg MSG_003 [Morgana]]
No deber胤a ser un problema, 夷verdad?[n]Normalmente est茨 con nosotros.

[msg MSG_004 [Futaba]]
斡Mira! 斡Hay nuestro primer sospechoso!

[msg MSG_005 [Makoto]]
... Pero con c吋mo estamos vestidos,[n]podr胤a ser dif胤cil para nosotros hablar[n]con ellos.

[msg MSG_006 [Naoto]]
Por favor, d姻jame manejar esto.

[msg MSG_007 [Naoto]]
Disculpe, 夷puedo preguntarle algo?
夷Es verdad que hay un oficial de polic胤a[n]falso causando un disturbio por aqu胤?

[msg MSG_008 [Polic胤a Gordo]]
夷Qui姻n eres? 夷D吋nde has o胤do eso?

[msg MSG_009 [Naoto]]
Es s吋lo un rumor... Pero como ciudadano[n]apreciar胤a algo de informaci吋n.

[msg MSG_010 [Polic胤a Gordo]]
Hm, por supuesto. Es importante[n]compartir este tipo de informaci吋n con[n]el p雨blico.
El oficial falso est茨 montando en un[n]coche marcado con doble 1s.
Por favor, h茨blanos si los encuentras.[n]Son muy peligrosos, as胤 que aseg雨rate de[n]no acercarte demasiado.

[msg MSG_011 [Naoto]]
Gracias por la informaci吋n. Ten cuidado[n]tambi姻n.

[msg MSG_012 [Futaba]]
Eso fue r茨pido. Buen trabajo, detective.

[msg MSG_013 [Naoto]]
Tendremos que encontrar a los otros[n]polic胤as y reunir m茨s informaci吋n.

[msg MSG_014 [Yusuke]]
"El oficial falso est茨 montando en un[n]coche marcado con doble 1s."
... 夷As胤 que esta es nuestra pista?

[msg MSG_015 [Naoto]]
No es todo lo que hemos aprendido.
El oficial que entrevistamos condujo un[n]coche marcado con los n雨meros "77-55"
Tengamos esto en mente tambi姻n. Deber胤a[n]ayudar a darnos una respuesta.

[msg MSG_016 [Futaba]]
斡No te preocupes! 斡Me asegurar姻 de[n]recordarlo!

[msg MSG_017 [Morgana]]
斡Muy bien! 斡Mantengamos la b雨squeda!

[msg MSG_018 [Naoto]]
Kamo City ciertamente es grande...
Mejor marcaremos las ubicaciones de los[n]oficiales en el mapa.

[msg MSG_019 [Futaba]]
斡Bien, Skull! 夷D吋nde est茨n esos[n]polic胤as?

[msg MSG_020 [Ryuji]]
夷Por qu姻 me est茨s molestando?

[sel SEL_021 top]
夷Quiz茨s en la estaci吋n?
夷Quiz茨s otra escena del crimen?
Busquemos sus coches.

[msg MSG_022 [Ryuji]]
No s姻 d吋nde vamos a encontrar eso. He[n]visto algunos coches de polic胤a, sin[n]embargo...

[msg MSG_023 [Futaba]]
斡As胤 es! 斡Hab胤a coches de polic胤a por[n]aqu胤!

[msg MSG_024 [Futaba]]
斡Ah胤 tienes! 斡Buen pensamiento, Joker!
斡Hab胤a coches de polic胤a por aqu胤! Quiz茨[n]encontremos algo cerca.

[msg MSG_025 [Naoto]]
Entonces, busquemos la zona. Con suerte,[n]los encontraremos pronto.

[msg MSG_026 [Futaba]]
斡Lo s姻!
斡Si quieres saber d吋nde est茨n los autos[n]de la polic胤a, preg雨ntame!

[msg MSG_027 [Naoto]]
Eso ser胤a muy 雨til. 夷Pero qu姻 planeas[n]hacer exactamente?

[msg MSG_028 [Futaba]]
Si puedo hackear el sistema inform茨tico[n]de la ciudad, sabremos exactamente d吋nde[n]encontrarlos.
Usaron un terminal para controlar los[n]reflectores, 夷verdad? Voy a hackear[n]desde all胤. Heheh.

[msg MSG_029 [Morgana]]
Sabes, a veces me asustas...

[msg MSG_030 [Naoto]]
Pensemos en una estrategia, entonces.
Si queremos hablar con los agentes de[n]polic胤a, primero tendremos que localizar[n]los coches de la polic胤a.
Y si queremos saber d吋nde est茨n los[n]coches de la polic胤a, tendremos que[n]encontrar una terminal de b雨squeda.

[sel SEL_031 top]
Lo tengo.
Vamos.

[msg MSG_032 [Naoto]]
Podemos buscar los coches por nuestra[n]cuenta o dirigirse a un terminal de[n]b雨squeda. Te lo dejaremos, Joker.
Empecemos, 夷de acuerdo?

[msg MSG_033 [Futaba]]
斡Entendido! 斡Esto va a ser divertido![n]斡Es hora de investigar!

[msg MSG_034]
Dijo que el oficial falso est茨 en el[n]coche con dobles...

