[msg MSG_000 [Yusuke]]
...

[sel SEL_001 top]
夷Qu姻 pasa?
夷Tienes hambre o algo?

[msg MSG_002 [Yusuke]]
Oh... Lo siento, estaba mirando este[n]graffiti.

[msg MSG_003 [Yusuke]]
Bueno, podr胤a comer, pero estoy lejos de[n]morir de hambre.
Estaba mirando este graffiti.

[msg MSG_004 [Yusuke]]
Mira aqu胤. Es inacabado.

[msg MSG_005 [Ryuji]]
S胤, no es como los otros. 夷Tal vez se[n]aburrieron a mitad de camino?

[msg MSG_006 [Yusuke]]
No, eso es poco probable.
Puedo sentir la vacilaci吋n del artista[n]aqu胤, su sufrimiento...
Sus manos fueron obligadas a dejar de[n]pintar contra su voluntad. Justo aqu胤.

[msg MSG_007 [P3 Fem Protag]]
Wow, Fox. 夷C吋mo lo averiguaste todo?

[msg MSG_008 [Yusuke]]
Graffiti es un crimen, pero hay una[n]cualidad art胤stica que no puede ser[n]descartada.
へ ょよ ゆま るまみもまるよ ぺ ゅぺ ろイぼょもぼぺテ ばゎもまるよ ぽまぼもる ゅよれ[n]れまょろもゆもまょろよれ ぽまゅ ぼるまぺぽよる を まゅ ゆまょれぺゃま りゎま[n]ろるぺろぺょ ぽま ろるぺょれゆもろもる ぺ ゅぺ れよぼもまぽぺぽテテテ!
斡S胤, viene a m胤! 斡Este pozo de[n]inspiraci吋n simplemente no dejar茨 de[n]fluir!
Ahh, tal vez llenar姻 los huecos y lo[n]terminar姻 para ellos...!
斡Urgh! No... 斡Sigue, mi mano...!

[msg MSG_009 [Ryuji]]
Welp, est茨 en ello otra vez.

[msg MSG_010 [Morgana]]
Nunca me ha importado mucho el graffiti.
Pero es un crimen, 夷verdad? Si Queen se[n]entera, estar胤as degustando el pu隠o de[n]hierro de la justicia con seguridad.

[msg MSG_011 [Ann]]
Oye, 夷cu茨nto tiempo van a quedarse ah胤?[n]斡Queen y Noir nos est茨n esperando![n]斡Vamos!

[msg MSG_012 [Yusuke]]
Mis disculpas, estaba distra胤do...[n]Cierto. Son nuestra m茨xima prioridad.
Ahora, salgamos. 斡Debemos destronar a[n]ese falso h姻roe!

[msg MSG_013]
Hay un graffiti inacabado en la pared...

