[msg MSG_000]
Dice "COOL KAMOSHIDAMAN" en la pared...

[msg MSG_001 [Yusuke]]
Esto no parece inacabado.

[msg MSG_002 [Ryuji]]
COOL... 夷Kamoshidaman?
夷Crees que ten胤a demasiado calor con ese[n]traje ajustado o algo as胤? 夷Y tal vez la[n]gente quer胤a ayudar a enfriarlo?

[msg MSG_003 [Ann]]
No, tonto. Obviamente significa, como,[n]"genial" aqu胤.

[msg MSG_004 [Ryuji]]
斡Ugh, en realidad est茨n ELOGIANDO a[n]Kamoshidaman! Tienes que estar[n]bromeando.

[msg MSG_005 [Akechi]]
La gente de esta ciudad alguna vez lo[n]vio como un h姻roe. Probablemente eso[n]qued吋 de entonces.
Entonces de nuevo, pueden estar teniendo[n]segundos pensamientos.

[msg MSG_006 [Morgana]]
Probablemente tengas raz吋n. De cualquier[n]manera, sigamos buscando el graffiti que[n]cambi吋.

[msg MSG_007]
Dice "COOL KAMOSHIDAMAN" en la pared...

[msg MSG_008 [Yusuke]]
Mmm... Esto no parece el dibujo que[n]buscamos. Queremos el que sea diferente[n]de los dem茨s.

