[msg MSG_000 [Yusuke]]
...

[sel SEL_001 top]
夷Qu姻 ocurre?
夷Tienes hambre o algo as胤?

[msg MSG_002 [Yusuke]]
Oh... Perd吋n, solo estaba mirando este grafiti.

[msg MSG_003 [Yusuke]]
Bueno, ciertamente podr胤a comer algo, pero estoy lejos de morirme de hambre.
Solo estaba mirando este grafiti.

[msg MSG_004 [Yusuke]]
Mira aqu胤. Est茨 sin acabar.

[msg MSG_005 [Ryuji]]
Oh, s胤, no es como los otros. A lo mejor se aburrieron cuando llevaban la mitad.

[msg MSG_006 [Yusuke]]
No, eso parece poco probable.
Puedo sentir aqu胤 la duda del artista, su sufrimiento...
Esas manos fueron forzadas a parar de pintar en contra de su voluntad. Justo aqu胤.

[msg MSG_007 [P3 Fem Protag]]
Wow, Fox. 夷C吋mo te has dado cuenta de todo eso?

[msg MSG_008 [Yusuke]]
Hacer graffitis es un crimen, pero tienen una cualidad art胤stica que no se puede pasar por alto.
Y no me refiero solo a la t姻cnica. 斡Me refiero a los sentimientos del creador y el mensaje que intentan transmitir a la sociedad...!
S胤, 斡viene a por m胤! Esta fuente de inspiraci吋n no parar茨 de fluir.
Ahh, 斡quiz茨s puedo rellenar los huecos y terminarlo por 姻l...!
Urgh! No... 斡Quieta, mano...!

[msg MSG_009 [Ryuji]]
Bueno, ya est茨 otra vez as胤.

[msg MSG_010 [Morgana]]
Hmm, nunca me hab胤a preocupado mucho por los grafitis.
Pero es un crimen, 夷verdad? Si Queen lo viera, seguro que probar胤ais el pu隠o de la justicia.

[msg MSG_011 [Ann]]
Hey, 夷cu茨nto tiempo m茨s vais a estar ah胤 quietos? 斡Queen y Noir nos est茨n esperando! 斡Vamos!

[msg MSG_012 [Yusuke]]
Mis disculpas, me he distra胤do... Bien. Acabemos con nuestra prioridad.
Ahora, v茨monos. 斡Debemos destronar a ese falso h姻roe!

[msg MSG_013]
Hay algunos grafitis sin acabar en esta pared...

