[msg MSG_000 [Kanji]]
Increボble. Estaban realmente escondidos debajo de las hojas.

[msg MSG_001 [Haru]]
*risita* En verdad, es muy sorprendente. Nunca habボa visto unos tan grandes antes.

[msg MSG_002 [Teddie]]
ムAhh! ムNo me los acerques mホs con esa bonita sonrisa en tu cara!

[msg MSG_003 [Kanji]]
Diablos, Teddie. メNo soportas un pequeワo gusano?
Espera un segundo, メqu〒 pasa, chicas? Estホn muy alejadas...

[msg MSG_004 [Chie]]
Ahaha... No soy la mホs fan de esos bichos...

[msg MSG_005 [Ann]]
Sabes, hay otros aquボ que serボan mejor para esto.

[msg MSG_006 [Morgana]]
Lo pillo. Son un poco asquerosos cuando los ves de cerca.

[sel SEL_007 top]
Estoy en ello.
Tampoco me gustan los bichos...
メQuieres un mordisco, Mona?

[msg MSG_008 [Morgana]]
Bien, Joker. No dudaste ni un poquito.

[msg MSG_009 [Ann]]
Puedes depender de alguien que actマa asボ de rホpido.

[msg MSG_010 [Morgana]]
Pero aun asボ, metiste tus manos en ese montポn de hojas. Eso fue muy valiente...

[msg MSG_011 [Yusuke]]
Por supuesto. Es el lボder de los Ladrones Fantasma, despu〒s de todo.

[msg MSG_012 [Morgana]]
ムNo! ムNo me trates como si fuera un gato callejero! ムHey, aparta eso de mi vista!

[msg MSG_013 [P4 Hero]]
Siempre el primero en actuar... No esperaba menos.

[msg MSG_014 [Yosuke]]
メHm? メQu〒 te pasa, bro?

[msg MSG_015 [P4 Hero]]
Nada... Bueno, parece que lo hemos encontrado, pero, メserホ suficiente?

[msg MSG_016 [Haru]]
Hmm... Parecen menos de lo que esperホbamos.

[msg MSG_017 [Kanji]]
ムSin problema! ムSenpai podrボa atrapar un pez sin usar nada si 〒l quisiera!

[sel SEL_018 top]
メDe verdad?
Contamos contigo.
ムYo tambi〒n puedo!

[msg MSG_019 [P4 Hero]]
Aprecio vuestra confianza, pero no creo que sea posible.

[msg MSG_020 [P4 Hero]]
Me alegra escuchar eso, pero no creo que sea posible.

[msg MSG_021 [Yusuke]]
メQu〒...? Y pensar que ambos se han convertido en unos increボbles pescadores...

[msg MSG_022 [P4 Hero]]
Aprecio el sentimiento, pero no creo que sea posible.

[msg MSG_023 [Haru]]
Bueno, entonces, podrボamos seguir buscando en otro sitio.
Estoy seguro de que hay mホs sitios con hojas como estas.

[msg MSG_024 [Morgana]]
Bien, entonces sigamos buscando.
Encontraremos mホs hojas en el resto de Puntos del Tesoro. ムVamos!

