[msg MSG_000 [Futaba]]
ムBuen trabajo! ムMisiポn completada!

[msg MSG_001 [Yukiko]]
Gracias, Futaba. Buen trabajo apoyホndonos.

[msg MSG_002 [Chie]]
ムHa sido divertido! ムMe sentボa como un ladrポn fantasma de verdad!

[sel SEL_003 top]
Lo has hecho bien.
Tienes que entrenar mホs.

[msg MSG_004 [Chie]]
ムSボ! ムHe conseguido el sello de aprobaciポn del lボder de los ladrones fantasma!

[msg MSG_005 [Chie]]
Haha, ムsolo estoy empezando! ムAl final lo conseguir〒!

[msg MSG_006 [Morgana]]
ムNo estホn nada mal! Tendremos que hacernos mホs fuertes.

[msg MSG_007 [Elizabeth]]
Bien hecho
Estaba tan fascinada por la fascinante bマsqueda del tesoro, que casi se me olvida respirar.
Fue una exhibiciポn de lo mホs hホbil. Era como ver una pelボcula de un ladrポn fantasma.

[msg MSG_008 [P4 Hero]]
Por cierto, メcuホnto valen estos tesoros?

[msg MSG_009 [Chie]]
Probablemente, un montポn, メverdad? Estaban resguardados por dinosaurios.
メCre〒n que nos sirva un suministro de boles de ternera de por vida, o eso es mucho?

[msg MSG_010 [Yosuke]]
メBoles de ternera? メEso es en lo マnico que piensas?

[msg MSG_011 [Haru]]
Hmm... Pasa algo con esta corona...
No se siente lo suficientemente pesada para ser oro real, y estas joyas no parecen en absoluto aut〒nticas...

[msg MSG_012 [Ann]]
メQu〒? メNos hemos equivocado en algマn sitio?

[msg MSG_013 [Chie]]
Despu〒s de todo el trabajo duro...

[msg MSG_014 [Elizabeth]]
No, no, no hay necesidad de preocuparos.
El objetivo de esta proyecciポn especial era mostrar a los estimados Ladrones Fantasma en acciポn.
ムApuesto a que la autenticidad del tesoro es irrelevante en comparaciポn con la sobresaliente actuaciポn de todos!

[msg MSG_015 [Yosuke]]
Realmente estホs tratando de amortiguar el golpe...

[msg MSG_016 [Naoto]]
*risita* No es una gran p〒rdida.
Ha sido una experiencia muy valiosa. Realmente me he sentido un ladrポn fantasma.

[msg MSG_017 [Ryuji]]
Nosotros tambi〒n nos hemos divertido. Hace tiempo que no hacボamos de ladrones fantasma.

[msg MSG_018 [Elizabeth]]
Ahh, parece que la conmovedora conclusiポn estホ a punto de llegar.
El tesoro puede ser falso, ムpero los lazos que han forjado son definitivamente reales!

[msg MSG_019 [Futaba]]
ムYa estホ! ムEl clich〒 del buen final!

[msg MSG_020 [Elizabeth]]
Espero con impaciencia su prポxima exposiciポn.

