[msg MSG_000 [Ann]]
Chu-rros, chu-rros, 斡dulces y azucarados, churroooooooos!

[msg MSG_001 [P3 Fem Protag]]
*risita* Panther seguro que est茨 de buen humor. Aunque, yo tambi姻n estoy emocionada.

[msg MSG_002 [Morgana]]
斡Yo estoy de buen humor solo de verla!

[msg MSG_003 [Ryuji]]
T胤o, realmente te gustan los dulces. 夷Es en lo 雨nico que piensas?

[msg MSG_004 [Ann]]
斡C茨llate! 斡Al menos no soy un cabeza hueca como t雨!

[msg MSG_005 [Ryuji]]
夷Cabeza hueca...?
斡夷A qui姻n le has llamado cabeza hueca...?!

[msg MSG_006 [Rise]]
夷Te encantan tanto los dulces y, aun as胤, tienes un cuerpo como ese?

[msg MSG_007 [P3 Fem Protag]]
S胤, mola mucho que seas modelo. Debes de entrenar cuando nadie te ve.

[msg MSG_008 [Ann]]
Jaja... Suelo ceder mis antojos a menudo, y normalmente tengo que entrenar duro para volver a ponerme en forma.

[msg MSG_009 [Rise]]
Aun as胤, 斡seguramente seas una de las mejores! Qu姻 envidia.

[msg MSG_010 [Ann]]
V-Vamos chicos, est茨is haciendo que me sonroje.
Pero tambi姻n me pone muy feliz escucharos decir eso, as胤 que 斡gracias!

[msg MSG_011 [Rise]]
Tienes estilo y sabes vestirte. 夷Podr胤as ense隠arme a combinar mis atuendos?

[msg MSG_012 [P3 Fem Protag]]
斡Oh! 斡A m胤 tambi姻n!
Quiz茨s despu姻s de que Theo nos haga los churros, podemos charlar mientras comemos.

[msg MSG_013 [Rise]]
斡Suena genial! 斡Preparar姻 algo de t姻!

[msg MSG_014 [Ryuji]]
... Bueno, se est茨n divirtiendo.

[msg MSG_015 [Kanji]]
S胤... Probablemente ser茨 un rato.

[msg MSG_016 [Futaba]]
Toda esta feminidad... 斡Es demasiado que manejar!
斡Deber胤ais ir mejor a por la canela! 斡No podemos defraudarles!
Nos acercamos a nuestros objetivos, 斡as胤 que dir胤gete al que quieras!

