[msg MSG_000 [Elizabeth]]
Perd吋name, [f 6 1 30 0 0 0].
夷Conoces de casualidad esa cosa que es tan popular entre los j吋venes y modernos a la que llaman "chu-rros"?

[msg MSG_001 [P3 Fem Protag]]
夷Quieres decir "churros", como el aperitivo?

[sel SEL_002 top]
No, no s姻.
He o胤do hablar de ellos.
Me encantan.

[msg MSG_003 [Rise]]
夷Huh? 夷En serio?
斡Son como donuts alargados y delgados cubiertos con canela y az雨car!

[msg MSG_004 [Rise]]
Entonces, 夷nunca te has comido ninguno?
斡Son como donuts alargados y delgados cubiertos con canela y az雨car!

[msg MSG_005 [P3 Fem Protag]]
*risita* [f 6 1 30 0 0 0], 夷eres un gran fan de los dulces?

[msg MSG_006 [Ann]]
Por fuera est茨 crujiente, por dentro superblando, y est茨 repleto de dulces y azucaradas golosinas.

[msg MSG_007 [Rise]]
Est茨n muy buenos, y son realmente pr茨cticos. Es el snack perfecto para llevarte al cine.

[msg MSG_008 [Elizabeth]]
Ah... As胤 que es como dicen los rumores: mejora la experiencia de ir al cine.
斡Me encantar胤a probar esos "churros"!
Habi姻ndolo pensado, le he pedido a Theo o que me haga algunos o le atravesar姻 su est吋mago con un cuchillo como tributo.

[msg MSG_009 [P3 Fem Protag]]
Ahaha... Es todo un pedido... 夷Tenemos los ingredientes?

[msg MSG_010 [Elizabeth]]
Le he hecho reunir los ingredientes, pero se ha quejado de que "faltaba una cosa".
Seg雨n 姻l, necesitamos algo llamado "Ka-ne-la", que se conoce por su seductor aroma.

[msg MSG_011 [Rise]]
Oh, es verdad, los churros tienen ese olor a canela, 夷no? Sin eso, sentir胤as que falta algo.

[msg MSG_012 [Elizabeth]]
... Dicho esto, podr胤an por favor ofrecer su ayuda a esta pobre mujer.
He o胤do que una planta conocida como "Helecho de Canela" se puede encontrar en alg雨n lugar de la pel胤cula de dinosaurios.
Si no os importa reunir algunas para m胤... No gratis, por supuesto.

[sel SEL_013 top]
Entendido.
Parece un rollo...

[msg MSG_014 [Ann]]
斡S胤, decidido entonces! 斡Vamos a buscar canela!

[msg MSG_015 [P3 Fem Protag]]
*risita* Pareces muy emocionada. Apuesto a que vas a por los churros.

[msg MSG_016 [Ann]]
Hehe, me has pillado.
斡Qu姻 bien suenan ahora los churros calentitos!

[msg MSG_017 [Rise]]
Oh, 斡estoy con vosotros en esto! 斡Voy a ser la mejor navegante que pueda!

[msg MSG_018 [Ann]]
Ay, vamos, Elizabeth nos necesita. Vamos a ayudarle.
Adem茨s, probablemente podamos comer churros cuando acabemos, 夷verdad?

[msg MSG_019 [P3 Fem Protag]]
*risita* 夷Eso era lo que quer胤as, Ann?

[msg MSG_020 [Ann]]
Jeje, me descubriste.
斡Qu姻 bien suenan ahora los churros calentitos!

[msg MSG_021 [Rise]]
Oh, 斡por favor di que s胤, [f 6 1 30 0 0 0]! 斡Prometo que ser姻 la mejor navegante que pueda!

[msg MSG_022 [Elizabeth]]
Aprecio la amabilidad de todos.
Puede que sea ego胤sta por mi parte, pero he preparado esto como una proyecci吋n especial.

[msg MSG_023 [Rise]]
斡Ha sido r茨pido!

[msg MSG_024 [Elizabeth]]
Y, adem茨s, ya he determinado las localizaciones de los Helechos de Canela. Qu姻 incre胤ble casualidad.
Ser胤a mejor que las apuntarais.

[msg MSG_025]
La localizaci吋n de los Helechos de Canela han sido a隠adidas en el mapa.

[msg MSG_026 [Ann]]
Perfecto. 斡Vayamos yendo!

