[msg MSG_000 [Elizabeth]]
Bien hecho. He recibido los Helechos de Canela que me trajeron.
Intent〒 darle uno a Theo, pero se quejポ diciendo cosas como, "Estホ amargo", y "Aマn no estホ maduro."

[msg MSG_001 [Akechi]]
O-Oh... Se lo ha comido crudo... Debo admitir que siento lホstima por 〒l.

[msg MSG_002 [Elizabeth]]
Y pensar que tenボamos que secarlo y luego molerlo hasta convertirlo en un polvo fino...
Parece que me equivocaba.

[msg MSG_003 [Futaba]]
メEso es todo lo que tenボas que decir...?

[msg MSG_004 [Elizabeth]]
Ahora bien, una vez que todos est〒n listos, podemos finalmente empezar a hacer esos "churros"
Ademホs, creo que tenemos suficientes ingredientes para empezar a venderlos de ahora en adelante.

[msg MSG_005 [Ann]]
ムEso significa que podremos comerlos cuando queramos! ムMe alegro de que hici〒ramos todo este trabajo!

[sel SEL_006 top]
Es emocionante.
No comas demasiados.

[msg MSG_007 [Ann]]
ムSボ! ムVamos a comernos algunos juntos! Nos ayudarホn a relajarnos cuando estemos cansados.

[msg MSG_008 [P3 Fem Protag]]
Tenemos mucho tiempo para hablar, Theo necesitarホ trabajar aマn mホs duro.

[msg MSG_009 [Ann]]
Jaja, lo s〒, lo s〒. Dame un respiro.
ムTendr〒 que luchar lo mホs duro que pueda y quemar estas calorボas!

[msg MSG_010 [P3 Fem Protag]]
Jeje, no te olvides de nuestro tiempo de charlar. Theo tendrホ que trabajar extra para seguir el ritmo.

[msg MSG_011 [Rise]]
ムOh, estoy tan emocionada! ムTenemos mucho de qu〒 hablar!

[msg MSG_012 [Ryuji]]
Tボo, las chicas se hacen amigas tan jodidamente rホpido...

[msg MSG_013 [Yusuke]]
Suelen hablar mucho para conocerse. Es un ホmbito en el que nunca podrボa superarles.

[msg MSG_014 [P4 Hero]]
Bueno, todos hemos tenido la suerte de encontrarnos aquボ, asボ que deberボamos hacer todo lo posible por fortalecer estas nuevas amistades.

