[msg MSG_000 [Theodore]]
Few... Gracias por la espera.
Las palomitas ya estホn listas. Por favor, sボrvanse.

[msg MSG_001 [Akechi]]
Gracias.
Ademホs, si no es mucho pedir, te agradecerボamos que mantuvieras en secreto este nuevo lote.

[msg MSG_002 [Theodore]]
Por supuesto.
Juro por las palomitas que no se lo dir〒 a nadie. Tienes mi palabra.

[msg MSG_003 [Naoto]]
Ahora solo tenemos que dejar el disfraz de Teddie frente a la sala de proyecciポn.

[msg MSG_004 [Akechi]]
Muy bien. Pongamos en marcha nuestro plan.

