[msg MSG_000 [Akechi]]
Pues bien, pongホmonos a reunir esos ingredientes, メde acuerdo?
Solo necesitamos Granos Explosivos, メverdad?

[msg MSG_001 [Naoto]]
Sボ, pero no serボa prudente buscar a ciegas.
Theodore nos dio un consejo de dポnde encontrarlas...

[sel SEL_002 top]
Lugares brillantes.
Lugares con viento.
Lugares hマmedos.

[msg MSG_003 [Teddie]]
メOh? メDijo eso?

[msg MSG_004 [Akechi]]
No, dijo que deberボamos buscar en algマn sitio hマmedo.
En cuyo caso, probablemente deberボamos concentrar nuestra bマsqueda cerca de zonas de agua.

[msg MSG_005 [Naoto]]
Sボ, ha mencionado buscar en lugares hマmedos.
En cuyo caso, probablemente deberボamos concentrar nuestra bマsqueda cerca de zonas de agua.

[msg MSG_006 [Teddie]]
Por cierto, メpor qu〒 necesitamos las palomitas?

[msg MSG_007 [Akechi]]
Ahora mismo solo tenemos pruebas circunstanciales, asボ que no nos queda mホs remedio que atrapar al culpable in fraganti.

[msg MSG_008 [Naoto]]
Por lo tanto, le pediremos a Theodore que vuelva a hacer sus nuevas palomitas.
Y las utilizaremos como cebo para atraer al culpable, メcorrecto?

[msg MSG_009 [Akechi]]
Sボ. Ademホs, nadie sospecharホ nada; pensarホn que simplemente estamos intentando ayudar a Theodore.

[msg MSG_010 [Teddie]]
Hrmm... Que fabul-oso.

[msg MSG_011 [Akechi]]
*risita* Eres muy simpホtico.

[msg MSG_012 [Naoto]]
Encontraremos los Granos Explosivos cerca del agua. Comencemos nuestra bマsqueda.

