[msg MSG_000 [Naoto]]
Esto debe ser lo que encontr吋 Theodore.

[msg MSG_001 [Teddie]]
夷Oho? Veamos... *Sniff* *sniff*
夷Hrrrm?

[msg MSG_002 [Naoto]]
夷Qu姻 pasa?

[msg MSG_003 [Teddie]]
Qu姻 extra隠o... No tiene ning雨n olor[n]tantalizantemente cargado de antes.

[msg MSG_004 [Yusuke]]
夷Qu姻?
D姻jame ver... *Sniff*
Tienes raz吋n... 斡No est茨 ah胤, el olor[n]que me dispar吋 a trav姻s de la nariz y en[n]mi cabeza!

[msg MSG_005 [Ryuji]]
夷Qu姻 eres, un perro?
Pero esto es definitivamente por lo que[n]vinimos aqu胤, 夷verdad? 夷Qu姻 m茨s podemos[n]hacer?

[msg MSG_006 [Yukiko]]
As胤 es. Theodore dijo que us吋 un[n]"certain something" para dar al producto[n]final su carga.

[msg MSG_007 [Naoto]]
へぺ わまよテテテ びイぼょもぼぺれ ぼゎゅもょぺるもぺれ ぼよゆよ まゅ ぺれぺぽよ[n]れまぼよ れま らゎまぽまょ ゎろもゅもんぺる らぺるぺ みよるろぺゅまぼまる まゅ[n]れぺほよる ぽま ょゎまぼまれ を れまゆもゅゅぺれテ
Tal vez lo mismo debe hacerse aqu胤...

[msg MSG_008 [Yukiko]]
夷Entonces deber胤a quemarlo? Eso podr胤a[n]sacar el olor.

[msg MSG_009 [Yusuke]]
No, no queremos el olor de carb吋n...
Necesita ser m茨s... 雨nico, casi[n]electrizante.

[msg MSG_010 [Akechi]]
Un sabor electrizante... 夷Qu姻 tendr胤as[n]que hacer para conseguir algo as胤?

[sel SEL_011 top]
Crush it.
Congela.
夷En realidad electrificarlo?

[msg MSG_012 [Naoto]]
Cierto. Pimienta crujiente es la manera[n]de sacar su sabor.
夷Pero eso nos dar茨 la propiedad[n]electrizante que necesitamos?

[msg MSG_013 [Haru]]
... 夷Y si realmente lo elegimos?

[msg MSG_014 [Naoto]]
No creo que congelar nos dar茨 la[n]propiedad electrizante que necesitamos.

[msg MSG_015 [Haru]]
... 夷Y si realmente lo elegimos?

[msg MSG_016 [Yosuke]]
夷Usando electricidad para obtener un[n]gusto electrizante? De ninguna manera es[n]tan simple...

[msg MSG_017 [Yusuke]]
斡Eso es! 斡La primera vez que com胤 esa[n]palomita, ese fue el efecto que sent胤!

[msg MSG_018 [Yosuke]]
夷Est茨s bromeando?

[msg MSG_019 [Akechi]]
Theodore dijo que us吋 un "certen algo"[n]para darle su cargo, as胤 que es posible.

[msg MSG_020 [Kanji]]
夷Es hora de que entre?

[msg MSG_021 [Naoto]]
No. No podemos estar seguros del nivel[n]de energ胤a, o deber胤a decir nivel de[n]carga, necesitamos.
S吋lo tenemos un suministro limitado de[n]n雨cleos. No podemos quemarlos a todos...

[msg MSG_022 [Futaba]]
Theodore mencion吋 usar un "certain[n]something", como si fuera muy listo para[n]averiguarlo...

[msg MSG_023 [Akechi]]
Ya veo...
夷Tienes idea de lo que podr胤a ser ese[n]"certen algo"?

[sel SEL_024 top]
A Persona.
Un rayo.
Una puerta el姻ctrica.

[msg MSG_025 [Yosuke]]
Ya lo descartamos, 夷verdad?

[msg MSG_026 [Akechi]]
Es probable que algo produzca un shock[n]el姻ctrico pero no se utiliza normalmente[n]para cocinar. Debe ser...

[msg MSG_027 [Naoto]]
Una de las puertas electrificadas aqu胤.

[msg MSG_028 [Morgana]]
夷C吋mo sabr胤a d吋nde va a atacar el rayo?

[msg MSG_029 [Akechi]]
Es probable que algo produzca un shock[n]el姻ctrico pero no se utiliza normalmente[n]para cocinar. Debe ser...

[msg MSG_030 [Naoto]]
Una de las puertas electrificadas aqu胤.

[msg MSG_031 [Akechi]]
Tienes raz吋n. Eso sin duda producir胤a un[n]choque el姻ctrico.

[msg MSG_032 [Morgana]]
Bueno, no lo sabremos hasta que lo[n]intentemos. Busquemos una de esas[n]puertas.

