[msg MSG_000 [Theodore]]
Phew... Gracias por esperar, todos.
El palomita est茨 listo ahora. Por favor,[n]ay雨dense.

[msg MSG_001 [Akechi]]
Gracias.
Adem茨s, si no es demasiado pedir, lo[n]apreciar胤amos si mantuvieras este nuevo[n]lote un secreto.

[msg MSG_002 [Theodore]]
Por supuesto.
Juro por las palomitas, no le dir姻 a[n]nadie. Tienes mi palabra.

[msg MSG_003 [Naoto]]
Ahora, todo lo que tenemos que hacer es[n]dejar el disfraz de Teddie delante de la[n]sala de proyecci吋n.

[msg MSG_004 [Akechi]]
Cierto. Pongamos nuestro plan en acci吋n.

