[msg MSG_000 [Elizabeth]]
Una historia muy conmovedora de dos dinosaurios... Qu姻 bonito.
Realmente me calent吋 el coraz吋n. De hecho, dir胤a que alcanz吋 temperaturas de m茨s de 2000 grados.

[msg MSG_001 [Kanji]]
夷Quedar胤a algo de ti...?
De todos modos, estoy contento de que el peque隠胤n pudiera encontrar a su madre.

[msg MSG_002 [Yosuke]]
Puede parecer que no le importa mucho, pero a Kanji se le llenaron los ojos de l茨grimas cuando esos dos se reencontraron.

[msg MSG_003 [Kanji]]
斡夷Qu姻?! 斡夷Qu姻 demonios est茨s diciendo?! 斡S-Solo ten胤a alergia!

[msg MSG_004 [Teddie]]
Jeje, Kanji se avergüenza con tanta facilidad.

[msg MSG_005 [Haru]]
Bueno, solo pudieron reencontrarse gracias a todos los aqu胤 presentes.
Gracias, Yukiko, por trabajar tan duro para ayudarlos.

[msg MSG_006 [Yukiko]]
Yo... Haru...
Me alegro mucho de que nos hayamos conocido.

[msg MSG_007 [Haru]]
夷Eh?

[msg MSG_008 [Yukiko]]
Puede que sea un poco atrevido, pero me he dado cuenta de que nos parecemos mucho.
Y al darme cuenta de eso, de repente me sent胤 m茨s cercana a ti...

[msg MSG_009 [Haru]]
*risita* He sentido lo mismo.
Estaba pensando en c吋mo podr胤amos hablar m茨s, para que as胤 pueda conocerte mejor

[msg MSG_010 [Yukiko]]
Me alegra escuchar eso. A m胤 tambi姻n me encantar胤a hablar m茨s contigo.

[msg MSG_011 [Haru]]
No hace falta ser tan educada, Yukiko. Simplemente seamos buenas amigas.

[msg MSG_012 [Yukiko]]
斡Cierto!

[msg MSG_013 [Morgana]]
Parece que se llevan muy bien. 斡Seguid as胤, chicos!

[msg MSG_014 [Yukiko]]
斡Claro que s胤! 斡Quemar姻 a todos nuestros enemigos!

[msg MSG_015 [Haru]]
No te olvides de m胤. 斡Acabar姻 con hasta el 雨ltimo enemigo que nos encontremos!

[msg MSG_016 [Ryuji]]
Jaja... Me alegro de que os llev姻is bien...

[msg MSG_017 [Kanji]]
Son una pareja bastante aterradora...

[msg MSG_018 [Haru]]
Oh, 斡eso me recuerda! Teddie estaba diciendo algo sobre "meter ficha"
夷Estabais jugando a un juego? 夷Cre姻is que me pueda unir la pr吋xima vez?

[msg MSG_019 [Yukiko]]
夷Teddie dijo eso...?

[msg MSG_020 [Teddie]]
斡Eeeek! N-No s姻 de qu姻 est茨s habl...

[msg MSG_021 [Yukiko]]
斡Te convertir姻 en cenizas! 斡Konohana Sakuya!

[msg MSG_022 [Teddie]]
斡Yaaargh! 斡Ya estamos otra vez!

[msg MSG_023 [Haru]]
Wow, 夷esto es parte de un juego? Dejadme probar...
斡Eh, t胤o bueno! 夷Quieres subir una colina y talar algunos 茨rboles conmigo?

[msg MSG_024 [Yosuke]]
斡夷Esa es tu idea para meter ficha?! Espera... 斡As胤 que prefieres una colina!

[msg MSG_025 [Yukiko]]
Oh, entonces, 夷qu姻 tal esto?
斡T雨! 夷Est茨s dispuesto a dedicar tu vida a mantener la larga historia y tradiciones de la posada Amagi?

[msg MSG_026 [Ryuji]]
斡Eso no me suena a meter ficha!

