[msg MSG_000_0]
Es un callej吋n sin salida...

[msg MSG_000 [Ryuji]]
... S吋lo s姻, como, los lugares[n]regulares, 夷sabes? Ll姻vala a una peque隠a[n]tienda de ramen y eres bueno, 夷verdad?

[msg MSG_001 [Yosuke]]
斡Idiotas! Chicas como lugares que son[n]rom茨nticos!
En alg雨n lugar como una colina o un[n]faro, un lugar donde puedes ver las[n]estrellas y esas cosas!

[msg MSG_002 [Ryuji]]
夷Una colina? No tenemos ninguno.

[msg MSG_003 [Kanji]]
夷Qu姻 tal una monta隠a?

[msg MSG_004 [Yosuke]]
斡No seas est雨pido! 斡Eso es totalmente[n]exagerado!
Quiero decir un lugar donde se pone un[n]poco de fr胤o por la noche, y los dos[n]naturalmente se acercan... 夷Sabes?

[msg MSG_005 [Kanji]]
No... En realidad no.

[msg MSG_006 [Yukiko]]
Parece que se est茨n divirtiendo mucho[n]all胤.

[msg MSG_007 [Haru]]
夷Colinas y estrellas? Me pregunto de qu姻[n]est茨n hablando.

[msg MSG_008 [Yosuke]]
夷Has o胤do todo eso?
Estamos tratando de ver qui姻n puede[n]venir con el mejor plan de citas.

[msg MSG_009 [Ryuji]]
No puedes preguntar a alguien cu茨l ser胤a[n]su cita ideal...
Quiero decir, 夷no puedes ir a donde[n]quieres ir? 夷Como un gimnasio o algo[n]as胤?

[msg MSG_010 [Yosuke]]
夷No crees que el mejor lugar para tomar[n]una chica para una cita va a ser super[n]diferente de donde quieres ir?

[msg MSG_011 [Kanji]]
No estoy seguro de tu colina,[n]Yosuke-senpai. Me siento como si hubiera[n]un mont吋n de errores 'n' mierda ...

[msg MSG_012 [Ryuji]]
夷No ser胤a m茨s f茨cil preguntar?
斡Oye! Ramen o una colina, 夷qu姻 se[n]siente?

[msg MSG_013 [Haru]]
夷Hm? 夷S吋lo tengo esas dos opciones?

[msg MSG_014 [Yukiko]]
Deber胤a ser sobre con qui姻n vas, no[n]donde vas.

[msg MSG_015 [Teddie]]
Si estamos juntos, Yuki, podemos[n]divertirnos sin importar a d吋nde[n]vayamos!
Y tal vez finalmente puedas marcar con[n]un..

[msg MSG_016 [Yukiko]]
斡Quema todo, Konohana Sakuya!

[msg MSG_017 [Teddie]]
斡Aaah! 斡Fue una broma!

[msg MSG_018 [Yosuke]]
Yukiko es despiadado. Pensar que es tan[n]dama cuando est茨 callada...

[msg MSG_019 [Ryuji]]
Hablando de damas, Noir es una dama.
Quiero decir, ella es la heredera de esa[n]gran compa隠胤a.

[msg MSG_020 [Haru]]
Yo... No soy diferente de nadie m茨s.

[msg MSG_021 [Yosuke]]
Vamos. 夷Esa elegancia? 夷Ese noble aura?[n]Eso es lo tuyo.

[msg MSG_022 [Yukiko]]
S胤, la forma en que te llevas siempre es[n]tan hermosa.

[msg MSG_023 [Haru]]
てるぺぼもぺれテ ぬもれ らぺぽるまれ まるぺょ ゆゎを まれろるもぼろよれ ぼよょ[n]ぼよれぺれ ぺれウデ ぺれウ りゎま れゎらよょむよ りゎま まれ れカゅよ ゅぺ[n]れまむゎょぽぺ ょぺろゎるぺゅまんぺ まょ まれろま らゎょろよテ
Pero eres tan adorable, Yukiko. Eres[n]graciosa, y tus modales son tan[n]majestuosos.

[msg MSG_024 [Yukiko]]
Gracias.
S吋lo estoy haciendo lo que me[n]ense隠aron...

[msg MSG_025 [Haru]]
Oh... As胤 que tambi姻n es lo mismo para[n]ti.

[msg MSG_026 [Yusuke]]
Eso puede ser cierto, pero cuando Noir[n]lucha, ella es el ep胤tome de la palabra[n]"bold"
Y esa imprevisibilidad s吋lo mejora su[n]elegancia.
Ambas damas son refinadas, pero dentro[n]de ellas mienten corazones apasionados.[n]Quiz茨s tengan algo en com雨n.

[msg MSG_027 [Kanji]]
... 夷Entonces, Ramen o una colina?

[msg MSG_028 [Haru]]
夷Hm? 夷Todav胤a estamos hablando de esto?[n]No tiene sentido, 夷no crees?

[msg MSG_029 [Yukiko]]
S胤. Incre胤blemente in雨til.

[msg MSG_030 [Yosuke]]
Haha... Pens姻 que...

[msg MSG_031 [Ryuji]]
Esos dos har胤an un gran equipo...

[msg MSG_032]
Una nueva proyecci吋n especial: "Los Ties[n]que Bind" se ha a隠adido a la taquilla.

