[msg MSG_000 [Elizabeth]]
A most moving tale of two dinosaurs...[n]How beautiful.
It truly warmed my heart. In fact, I'd[n]say it reached temperatures of over 2000[n]degrees.

[msg MSG_001 [Kanji]]
Would there even be anythin' left of[n]you...?
Anyway, I'm just glad the little guy was[n]able to find his mom.

[msg MSG_002 [Yosuke]]
Y'know, it may look like he doesn't care[n]all that much, but Kanji had tears in[n]his eyes when those two reunited.

[msg MSG_003 [Kanji]]
Wha―!? The hell're you talkin' about!?[n]I-I just have allergies!

[msg MSG_004 [Teddie]]
Hehe, Kanji's so easily embarrassed.

[msg MSG_005 [Haru]]
Well, they were only able to reunite[n]thanks to everyone here.
Thank you, Yukiko-chan, for working so[n]hard to help them.

[msg MSG_006 [Yukiko]]
I... Haru-san...
I'm so glad we got to meet each other.

[msg MSG_007 [Haru]]
Huh?

[msg MSG_008 [Yukiko]]
This might be a bit forward, but I[n]realized we're very much alike.
And upon realizing that, I suddenly felt[n]close to you...

[msg MSG_009 [Haru]]
*giggle* I felt the same way.
I was thinking about how we should talk[n]some more, so I can get to know you[n]better.

[msg MSG_010 [Yukiko]]
I'm happy to hear that. I would very[n]much like to talk more with you as well.

[msg MSG_011 [Haru]]
There's no need to be so proper,[n]Yukiko-chan. Let's just be good friends.

[msg MSG_012 [Yukiko]]
Right!

[msg MSG_013 [Morgana]]
Looks like you two are getting along[n]just fine. Keep it up, you guys!

[msg MSG_014 [Yukiko]]
Of course! I'll burn all of our enemies[n]to a crisp!

[msg MSG_015 [Haru]]
Don't forget about me. I'll chop down[n]every last foe we come across!

[msg MSG_016 [Ryuji]]
Haha... Glad you two are getting[n]along...

[msg MSG_017 [Kanji]]
They're a pretty scary pair...

[msg MSG_018 [Haru]]
Oh, that reminds me! Teddie was saying[n]something about "scoring."
Were you playing a game? Do you think I[n]can come along next time?

[msg MSG_019 [Yukiko]]
Teddie said what...?

[msg MSG_020 [Teddie]]
Eeeek! I-I don't know what you're talki―

[msg MSG_021 [Yukiko]]
I'll turn you to ash! Konohana Sakuya!

[msg MSG_022 [Teddie]]
Yaaargh! Here we go again!

[msg MSG_023 [Haru]]
Wow, is this part of the game? Let me[n]try...
Hey, hot stuff! You wanna hike up a hill[n]and chop down some trees with me?

[msg MSG_024 [Yosuke]]
That's your idea of scoring!? Wait... So[n]you WOULD prefer a hill!

[msg MSG_025 [Yukiko]]
Oh, then, how about this?
You there! Are you willing to devote[n]your life to upholding the long-standing[n]history and traditions of the Amagi Inn?

[msg MSG_026 [Ryuji]]
That don't sound like scorin' to me!

