[msg MSG_000 [Yukiko]]
Hemos vuelto con algunas hierbas. Espera solo un poco mホs, メokay?

[msg MSG_001 [Young herbivore]]
*gimoteo*

[msg MSG_002]
Molimos las hierbas y tratamos al joven dinosaurio...

[msg MSG_003 [Haru]]
Allホ vamos. Deberボa sentirse mejor pronto.

[msg MSG_004 [Young herbivore]]
ムKyu!

[msg MSG_005 [Yukiko]]
Jeje, parece que ahora estホs mejor. Qu〒 manera de aguantar, Kyubei.

[msg MSG_006 [Young herbivore]]
ムKyu, kyu, kyu!

[msg MSG_007 [Chie]]
ムメCuホndo le has puesto nombre?!

[msg MSG_008 [P4 Hero]]
Aunque sigo sin ver a su madre.
Podrボamos pedirle a Margaret que lo cuide, pero...

[sel SEL_009 top]
Sigamos buscando.
Volvamos por ahora.

[msg MSG_010 [Haru]]
Cierto, no podemos dejarlo aquボ.

[msg MSG_011 [Haru]]
No quiero dejarlo aquボ. Yo digo que busquemos un poco mホs.

[msg MSG_012 [Futaba]]
Hey, ムespera un segundo! Esa voz...

[msg MSG_013 [Naoto]]
Es d〒bil, pero yo tambi〒n la oigo. Podrボa ser...

[msg MSG_014 [Young herbivore]]
ムKyuuu!

[msg MSG_015 [Mother herbivore]]
ムRrrr!

[msg MSG_016 [Makoto]]
Debe ser su madre... Me alegro de que se hayan encontrado.

[msg MSG_017 [Yukiko]]
Parecen muy felices.

[msg MSG_018 [Haru]]
Mhm, Kyu parece mucho mejor ahora. Parece que todo lo que querボa era estar cerca de su madre.

[msg MSG_019 [Yukiko]]
......
En realidad, supongo que todos los padres se preocupan por sus hijos...

[msg MSG_020 [Haru]]
メYukiko?

[msg MSG_021 [Yukiko]]
Oh, um... lo siento.
Tengo una sensaciポn extraワa al verlos...

[msg MSG_022 [Haru]]
メSensaciポn extraワa?

[msg MSG_023 [Yukiko]]
Cuando era pequeワa, nunca me costポ ser sincera con mis sentimientos.
No me preocupaba por nada, y podボa divertirme cada dボa.
Pero, un dボa, las cosas se complicaron entre mi familia y...
No pude ser honesta con mis sentimientos nunca mホs, como lo que estホ sintiendo Kyubei ahora mismo...

[msg MSG_024 [Haru]]
Oh... Sabes, Yukiko, soy como tマ.
Odiaba estar sujeta a las reglas de la casa. Me decボa a mボ misma que no iba a dejar que mis padres me mangonearan...

[msg MSG_025 [Yukiko]]
メTマ tambi〒n, Noir? No tenボa idea...

[msg MSG_026 [Haru]]
Pero me di cuenta de algo.
Quizホs atarme era su forma de demostrarme que me querボan.

[msg MSG_027 [Yukiko]]
メDe verdad lo crees?
Pero... Todavボa quiero tomar mis propias decisiones.

[msg MSG_028 [Haru]]
Por supuesto. Me parece estupendo. No deberボas tener que mentirte a ti misma y ceder ante lo que dice todo el mundo.
Aunque pienses diferente a ellos, seguro que se alegrarボan de que sigas aquello en lo que crees.

[msg MSG_029 [Yukiko]]
Sボ... Tienes razポn.

[msg MSG_030 [Young herbivore]]
ムKyu!

[msg MSG_031 [Yukiko]]
メHm? メQu〒 ocurre, Kyubei?

[msg MSG_032 [Haru]]
Parece que lleva algo.

[msg MSG_033 [Yukiko]]
メUna piedra? Es muy bonita...

[msg MSG_034 [Chie]]
メQuizホs sea para agradecernos por toda nuestra ayuda?

[msg MSG_035 [Yukiko]]
Oh... Muchas gracias, Kyubei.

[msg MSG_036 [Young herbivore]]
ムKyu, kyu!

[msg MSG_037 [Haru]]
No te pierdas nunca mホs, メentendido? ムCuボdate mucho, Kyu!

[msg MSG_038 [Young herbivore]]
ムKyu!

[msg MSG_039 [Chie]]
ムWow, realmente lo entienden! Esos dos son increボbles...

[msg MSG_040 [Morgana]]
Supongo que eso es todo por ahora. Volvamos.

