[msg MSG_000 [Teddie]]
Woo! 斡Una puerta cubierta de vid!

[msg MSG_001 [Haru]]
Supongo que estoy levantada. Echar姻 un[n]vistazo.

[msg MSG_002 [Haru]]
斡Ah胤! 斡Encontr姻 uno!

[msg MSG_003 [Morgana]]
斡Bien! 夷Cu茨nto m茨s necesitamos...?

[msg MSG_004 [Haru]]
Esto deber胤a ser suficiente.
Ahora solo necesitamos molerlos y[n]aplicarlos a la herida del dinosaurio, y[n]deber胤a estar bien.

[msg MSG_005 [Yukiko]]
Me alegra o胤r eso. 夷Qu姻 dices si[n]regresamos?

