[msg MSG_000 [Elizabeth]]
Ahora, para esta proyecci吋n especial...
Deb姻is ir a Junessic Land y acabar con la tiran胤a incontrolada de la Bestia Carn胤vora.

[msg MSG_001 [Rise]]
Carn胤voro... espera, 夷no es uno de esos FOEs?

[msg MSG_002 [Elizabeth]]
Correcto. Es una amenaza mucho m茨s maliciosa que cualquier otro dinosaurio.
Devorando todo a la vista, es la definici吋n de B-E-S-T-I-A.
Actualmente, est茨 desmadrado, haciendo lo que le da la gana, donde le da la gana...
Si no se hace algo pronto, seguro que tarde o temprano ir茨 contra vosotros... o eso me temo.

[msg MSG_003 [Shinjiro]]
La mierda que est茨s diciendo no concuerda con tu expresi吋n...

[msg MSG_004 [Akihiko]]
Wow, parece un oponente terror胤fico.

[msg MSG_005 [Shinjiro]]
Igual que t雨...
Entonces, 夷c吋mo encontramos esta cosa? 夷Pueden las navegadoras encontrarlo por nosotros?

[msg MSG_006 [Rise]]
Hmm, se est茨 moviendo mucho, no creo que podamos determinar su localizaci吋n exacta.
Ojal茨 tuvi姻ramos alg雨n tipo de pista de d吋nde podr胤a estar...

[sel SEL_007 top]
Busquemos huesos.
Cerca de su presa.

[msg MSG_008 [Akechi]]
Buena idea. Todo lo que tenemos que hacer es buscar las huellas dejadas por esa Bestia Carn胤vora.
Si est茨 atacando y comiendo todo lo que ve, entonces podremos seguir su rastro de alimentaci吋n...

[msg MSG_009 [Shinjiro]]
Y finalmente nos encontraremos cara a cara con el bastardo, 夷eh? Bastante horripilante.

[msg MSG_010 [Akechi]]
As胤 que tendremos que encontrar rastros de su 雨ltima comida... En otras palabras, huesos frescos de dinosaurio.
夷Suena bien, [f 6 1 30 0 0 0]?

[sel SEL_011 top]
Te lo dejo a ti.
Lo que t雨 quieras.

[msg MSG_012 [Akechi]]
夷Yo...?
Ja, ja, muy bien. Supongo que deber胤a poner m茨s de mi parte de ahora en adelante.

[msg MSG_013 [Akechi]]
Ja, ja, 夷est茨s diciendo que quieres que me encargue de esto?
Muy bien. Ten胤a curiosidad por esta Bestia Carn胤vora de todos modos.

[msg MSG_014 [Akihiko]]
Sea lo que sea, seguramente sea fuete. Estoy impaciente por conocerlo.

[msg MSG_015 [Akechi]]
Ja, ja, me alegro de que podamos contar contigo. Yo tambi姻n intentar姻 cumplir las expectativas.

