[msg MSG_000 [Koromaru]]
斡Arf, arf!

[msg MSG_001 [Akechi]]
S胤, huesos. Es justo como dijiste, Koromaru.

[sel SEL_002 top]
夷Te importar胤a echar un vistazo?
夷Esto no es peligroso?

[msg MSG_003 [Akechi]]
Ciertamente. Veamos...

[msg MSG_004 [Akechi]]
Ja, ja, no te preocupes. D姻jame echar un vistazo m茨s de cerca.

[msg MSG_005 [Akechi]]
S胤, esta es sin duda una de sus comidas. Aunque, es bastante viejo.
Si seguimos el rastro, seguro que al final encontramos a la bestia.

[msg MSG_006 [Chie]]
Wow, eres incre胤ble, Koromaru... Muku nunca podr胤a hacer eso.

[msg MSG_007 [Koromaru]]
*sniff* *sniff* *sniff*
斡Arf, arf!

[msg MSG_008 [Ken]]
Koromaru parece muy entusiasmado. Dice que el rastro lleva al norte.

[msg MSG_009 [Akechi]]
Muy bien. Vamos al norte entonces.

