[msg MSG_000 [Elizabeth]]
Ahora, para esta proyecciポn especial...
Deben ir a Junessic Land y acabar con la tiranボa incontrolada de la Bestia Carnボvora.

[msg MSG_001 [Rise]]
Carnボvoro... espera, メno es uno de esos FOEs?

[msg MSG_002 [Elizabeth]]
Correcto. Es una amenaza mucho mホs maliciosa que cualquier otro dinosaurio.
Devorando todo a la vista, es la definiciポn de B-E-S-T-I-A.
Actualmente, estホ desmadrado, haciendo lo que le da la gana, donde le da la gana...
Si no se hace algo pronto, seguro que tarde o temprano irホ contra ustedes... o eso me temo.

[msg MSG_003 [Shinjiro]]
La mierda que estホs diciendo no concuerda con tu expresiポn...

[msg MSG_004 [Akihiko]]
Wow, parece un oponente terrorボfico.

[msg MSG_005 [Shinjiro]]
Igual que tマ...
Entonces, メcポmo encontramos esta cosa? メPueden las navegadoras encontrarlo por nosotros?

[msg MSG_006 [Rise]]
Hmm, se estホ moviendo mucho, no creo que podamos determinar su localizaciポn exacta.
Ojalホ tuvi〒ramos algマn tipo de pista de dポnde podrボa estar...

[sel SEL_007 top]
Busquemos huesos.
Cerca de su presa.

[msg MSG_008 [Akechi]]
Buena idea. Todo lo que tenemos que hacer es buscar las huellas dejadas por esa Bestia Carnボvora.
Si estホ atacando y comiendo todo lo que ve, entonces podremos seguir su rastro de alimentaciポn...

[msg MSG_009 [Shinjiro]]
Y finalmente nos encontraremos cara a cara con el bastardo, メeh? Bastante horripilante.

[msg MSG_010 [Akechi]]
Asボ que tendremos que encontrar rastros de su マltima comida... En otras palabras, huesos frescos de dinosaurio.
メSuena bien, [f 6 1 30 0 0 0]?

[sel SEL_011 top]
Te lo dejo a ti.
Lo que tマ quieras.

[msg MSG_012 [Akechi]]
メYo...?
Ja, ja, muy bien. Supongo que deberボa poner mホs de mi parte de ahora en adelante.

[msg MSG_013 [Akechi]]
Ja, ja, メestホs diciendo que quieres que me encargue de esto?
Muy bien. Tenボa curiosidad por esta Bestia Carnボvora de todos modos.

[msg MSG_014 [Akihiko]]
Sea lo que sea, seguramente sea fuete. Estoy impaciente por conocerlo.

[msg MSG_015 [Akechi]]
Ja, ja, me alegro de que podamos contar contigo. Yo tambi〒n intentar〒 cumplir las expectativas.

