[msg MSG_000 [Morgana]]
Uf, qu姻 alivio. Es bueno saber que ahora estamos fuera del men雨.

[msg MSG_001 [Akechi]]
Excelente. Creo que mi trabajo aqu胤 est茨 hecho.

[msg MSG_002 [Koromaru]]
斡Arf, arf!

[msg MSG_003 [Ken]]
Est茨 preguntando si est茨s bien, Crow.

[msg MSG_004 [Akechi]]
Ja, ja, 夷estabas preocupado por m胤? Eres muy listo, 夷lo sab胤as?

[msg MSG_005 [Ken]]
......

[sel SEL_006 top]
夷Qu姻 ocurre?
夷Est茨is bien?

[msg MSG_007 [Ken]]
Oh, no es nada.
Solo estaba pensando en el gran trabajo que han hecho estos dos.

[msg MSG_008 [Akechi]]
Muy bien, entonces lo 雨nico que queda es reportar nuestro 姻xito. 夷Nos vamos yendo?

