[msg MSG_000 [Teddie]]
Hrrm!? I found some dinosaur bones!
Such terrible table manners. It was[n]clearly eating with its hands.

[msg MSG_001 [Yosuke]]
You're the last one who should be[n]judging someone's table manners...

[msg MSG_002 [Rise]]
Can you check the bones, Crow?

[msg MSG_003 [Akechi]]
Yes, I'm looking at them right now.
These bones are starting to wear down.[n]They must be very old.

[sel SEL_004 top]
That won't do.
Let's try somewhere else.

[msg MSG_005 [Koromaru]]
Arf!

[msg MSG_006 [Akechi]]
Haha, Koromaru-kun seems to agree.
We're looking for fresh sets of bones.[n]Let's keep our eyes open.

