[msg MSG_000 [Morgana]]
Vaya, eso es un alivio. Es bueno saber[n]que estamos fuera del men雨 ahora.

[msg MSG_001 [Akechi]]
Excelente. Creo que mi trabajo aqu胤 est茨[n]hecho.

[msg MSG_002 [Koromaru]]
斡Arf, Arf!

[msg MSG_003 [Ken]]
Pregunta si est茨s bien, Crow.

[msg MSG_004 [Akechi]]
Haha, 夷estabas preocupada por m胤? Eres[n]muy fuerte, 夷lo sabes?

[msg MSG_005 [Ken]]
...

[sel SEL_006 top]
夷Qu姻 pasa?
夷Est茨s bien?

[msg MSG_007 [Ken]]
No es nada.
Estaba pensando qu姻 gran trabajo[n]hicieron esos dos.

[msg MSG_008 [Akechi]]
Muy bien, todo lo que queda es reportar[n]nuestro 姻xito. 夷Vamos?

