[msg MSG_000 [Theodore]]
Hola. 夷C吋mo est茨n?

[msg MSG_001 [Elizabeth]]
斡Villain!
Ese atuendo sospechoso... 斡Alto ah胤! 斡Te[n]cortar姻 donde est茨s!

[msg MSG_002 [Theodore]]
S-sister, por favor. Soy yo, Theodore.

[msg MSG_003 [Elizabeth]]
夷Hm?
Parece que he saltado el arma. Ahora que[n]te miro m茨s de cerca, veo que eres mi[n]hermano.

[msg MSG_004 [P3 Fem Protag]]
夷Teo? 夷Qu姻 haces aqu胤?

[msg MSG_005 [Theodore]]
Sobre eso... Vine aqu胤 porque tengo una[n]petici吋n.

[sel SEL_006 top]
夷Una petici吋n?
夷Pasa algo?

[msg MSG_007 [Theodore]]
Bueno, si eres capaz...
Hay algo que me gustar胤a ponerme las[n]manos encima.
斡Lo llaman "Futurista Gizmo"!

[msg MSG_008 [Naoto]]
夷Futurista Gizmo...?

[msg MSG_009 [Theodore]]
S胤. La pel胤cula "Tierra Ju茨tica" que[n]pasaste por...
Aparentemente, es el hogar de una[n]multitud de tecnolog胤a de pr吋xima[n]generaci吋n.

[msg MSG_010 [Makoto]]
Ahora que lo mencionas, esa pel胤cula[n]tiene lugar en el futuro.
Las personas all胤 fueron capaces de[n]revivir los dinosaurios con su[n]tecnolog胤a.

[msg MSG_011 [Junpei]]
Pero si estamos hablando del futuro, 夷no[n]ser胤a mejor "A.I.G.I.S".?
Hay m茨s tecnolog胤a all胤, 夷sabes?

[msg MSG_012 [Naoto]]
Sobre eso...

[msg MSG_013 [Fuuka]]
La tecnolog胤a utilizada en "Tierra[n]Ju茨tica" es un poco diferente de la[n]tecnolog胤a que vimos en "A.I.G.I.S."
Lo que se encuentra en "A.I.G.I.S." se[n]deriva de la f胤sica ficticia...

[msg MSG_014 [Naoto]]
斡S胤, eso es exactamente!
Y la tecnolog胤a encontrada en "Tierra[n]Ju茨tica" se derivaba de la f胤sica del[n]mundo real.
はよる ゅよ ろぺょろよデ もょぼゅゎれよ れも ぺゆほぺれ らまゅウぼゎゅぺれ[n]ぼよょろもまょまょ まゅ ゆもれゆよ ろもらよ ぽま ぽもれらよれもろもわよデ らゎまぽまょ[n]まれろぺる めまぼめぺれ ぽま ゆぺろまるもぺゅまれ ぼよゆらゅまろぺゆまょろま[n]ぽもみまるまょろまれテ

[msg MSG_015 [Ryuji]]
R-right... Entonces... 夷 f胤sica?

[msg MSG_016 [Futaba]]
Mmm... Est茨n sintonizando a los normies[n]para que puedan hablar geek unos con[n]otros.

[msg MSG_017 [Theodore]]
Ustedes dos saben mucho.

[msg MSG_018 [Naoto]]
, 夷est茨 bien contigo si buscamos este[n]"Futurista Gizmo"?

[sel SEL_019 top]
Vale.
Bien por m胤.

[msg MSG_020 [Theodore]]
Much appreciated, [f 6 1 30 0 0 0].
Y si lo consideramos una proyecci吋n[n]especial, podr姻 presentarte con una[n]recompensa.
Con eso, hermana, 夷podr胤as crear un...

[msg MSG_021 [Elizabeth]]
...

[msg MSG_022 [Theodore]]
夷Sister?

[msg MSG_023 [Elizabeth]]
夷De d吋nde viene este misterioso y[n]disfrazado...?

[msg MSG_024 [Theodore]]
*suspira*

[msg MSG_025]
Una nueva proyecci吋n especial:[n]"Long-lost Tech" se ha a隠adido a la[n]taquilla.

