[msg MSG_000 [Theodore]]
Hola a todos. メQu〒 tal estホn?

[msg MSG_001 [Elizabeth]]
... ムVillano!
Ese traje sospechoso... ムAlto ahボ! ムTe cortar〒 donde estホs parado!

[msg MSG_002 [Theodore]]
H-Hermana, por favor. Soy yo, Theodore.

[msg MSG_003 [Elizabeth]]
メHm?
Oh, parece que me he confundido. Ahora que te veo de cerca, veo que solo eres mi hermano.

[msg MSG_004 [P3 Fem Protag]]
メTheo? メQu〒 estホs haciendo aquボ?

[msg MSG_005 [Theodore]]
Sobre eso... He venido aquボ porque tenボa una solicitud.

[sel SEL_006 top]
メUna solicitud?
メOcurre algo?

[msg MSG_007 [Theodore]]
Bueno, si son capaces...
Hay algo que me gustarボa tener en mis manos.
ムLo llaman "Gizmo Futurista"!

[msg MSG_008 [Naoto]]
メGizmo Futurista...?

[msg MSG_009 [Theodore]]
Sボ. La pelボcula de "Junessic Land" que explorasteis...
Aparentemente, es hogar de una gran multitud de tecnologボa de nueva generaciポn.

[msg MSG_010 [Makoto]]
Ahora que lo mencionas, esa pelボcula ocurre en el futuro.
La gente allボ podボa revivir dinosaurios con su tecnologボa.

[msg MSG_011 [Junpei]]
Pero, si estamos hablando sobre el futuro, メno serボa mejor "A.I.G.I.S."?
Allボ hay mucha mホs tecnologボa, メsabes?

[msg MSG_012 [Naoto]]
Hmm, sobre eso...

[msg MSG_013 [Fuuka]]
La tecnologボa usada en "Junessic Land" es un poco diferente a la tecnologボa que vimos en "A.I.G.I.S."
Lo que se encuentra en "A.I.G.I.S." se derivポ de la fボsica ficticia...

[msg MSG_014 [Naoto]]
Sボ, ムes eso exactamente!
Y la tecnologボa encontrada en "Junessic Land" se derivポ de la fボsica del mundo real.
Por lo tanto, aunque ambas pelボculas contengan el mismo tipo de dispositivos, pueden estar fabricadas con materiales totalmente distintos.

[msg MSG_015 [Ryuji]]
B-Bien... Entonces... メFボsica?

[msg MSG_016 [Futaba]]
Hmm... Estホn dejando fuera a los normies para que los frikis puedan hablar entre sボ.

[msg MSG_017 [Theodore]]
Ah, ustedes dos saben un montポn.

[msg MSG_018 [Naoto]]
, メte parece bien que busquemos ese "Gizmo Futurista"?

[sel SEL_019 top]
Okay.
Me parece bien.

[msg MSG_020 [Theodore]]
Muy agradecido, [f 6 1 30 0 0 0].
Y si lo consideramos una proyecciポn especial, les podr〒 regalar una recompensa.
Con eso, Hermana, podrボas crear una...

[msg MSG_021 [Elizabeth]]
...

[msg MSG_022 [Theodore]]
... メHermana?

[msg MSG_023 [Elizabeth]]
ムメD-De dポnde ha salido este misterioso granuja disfrazado?!

[msg MSG_024 [Theodore]]
*suspiro*

[msg MSG_025]
Una nueva proyecciポn especial: "Tecnologボa Perdida" ha sido aワadida a la taquilla.

