[msg MSG_000 [Ryuji]]
Este contenedor est茨 roto. Parece que tambi姻n est茨 abierto.

[msg MSG_001 [Akechi]]
Est茨 demasiado oscuro para ver nada, pero sin duda es lo bastante grande para que quepa una persona dentro.

[msg MSG_002 [Teddie]]
... 斡Holaaa!
斡Yosukeee! Si est茨s ah胤, 斡sal! 斡Somos nosotros!

[msg MSG_003]
......
No hay respuesta...

[msg MSG_004 [Yukiko]]
No creo que est姻 aqu胤.

[msg MSG_005 [Teddie]]
Hm, Yosuke es t胤mido... Quiz茨s le d姻 mucha vergüenza salir afuera.
斡Yosukeee! 斡Sal de ah胤胤胤!
斡Tenemos una pantera supersexy, una belleza enmascarada y una dama con pinchos con nosotros!

[msg MSG_006 [Ann]]
Pantera supersexy...

[msg MSG_007 [Haru]]
斡Belleza enmascarada...!

[msg MSG_008 [Makoto]]
夷Dama con pinchos...?

[msg MSG_009 [Teddie]]
Hm... A雨n nada...
夷Saldr胤as si te esperaran unas enfermeras sexys?

[msg MSG_010 [Ryuji]]
... 夷Por qu姻 dices eso tan fuerte? Ahora nunca querr茨 salir.

[msg MSG_011 [P4 Hero]]
No parece estar por aqu胤. Sigamos buscando.

[msg MSG_012]
Es un contenedor roto... No hay nada dentro.

