[msg MSG_000 [Elizabeth]]
Bravo, bravo. Me quito el sombrero ante vuestras habilidades de investigaciポn.

[msg MSG_001 [Junpei]]
Realmente nos hiciste pasar un mal rato. Fue difボcil imaginarse todo sin apenas informaciポn.

[msg MSG_001_1 [Junpei]]
Pero la gente de Ciudad Kamo podrホ dormir tranquila esta noche, gracias a mボ...

[sel SEL_002 top]
メJunpei, superdetective?
......

[msg MSG_003 [Mitsuru]]
...J-Junpei, superdetective...

[msg MSG_004 [Junpei]]
メEh?

[msg MSG_005 [Yukari]]
ムメQu〒...!?

[msg MSG_006 [Mitsuru]]
... Tenボa el presentimiento de que ibas a decir eso.

[sel SEL_007 top]
Eso es pensar como Junpei.
メTe encuentras bien?
Eso ha sido bonito...

[msg MSG_008 [Mitsuru]]
ムメPuedes dejar de hablar sobre eso?!

[msg MSG_009 [Mitsuru]]
D-Dijiste que deberボa probarlo, asボ que lo hice...

[msg MSG_010 [Mitsuru]]
ムNo actマes como si fuera tan conmovedor...!

[msg MSG_011 [Ryuji]]
Bueno, realmente solo hemos resuelto el caso gracias a toda la informaciポn que hemos conseguido de la gente de alrededor.

[msg MSG_012 [Ann]]
No creo que hubieran hecho nada parecido antes. Realmente han cambiado.

[msg MSG_013 [Junpei]]
Supongo que lo mホs importante es el que manda. Asボ es el mundo.

[msg MSG_014 [Yukari]]
Porque sabes tanto sobre eso...

[msg MSG_015 [Elizabeth]]
Ahora bien, aquボ estホ tu recompensa. Por favor, ac〒ptala.

[msg MSG_016 [Mitsuru]]
Perdポname, pero me gustarボa que tuvieras esto.

[msg MSG_017 [Makoto]]
メGuantes?

[msg MSG_018 [Mitsuru]]
Son guantes de moto. Querボa agradecerte todo lo que has hecho por mボ esta vez.

[msg MSG_019 [Makoto]]
No necesitas agradec〒rmelo... Ademホs, aマn ni siquiera tengo el carnet.

[msg MSG_020 [Mitsuru]]
メEn serio? Despu〒s de ver tu Persona, supuse...

[msg MSG_021 [Makoto]]
Creo que solo es una representaciポn de cポmo me siento.

[msg MSG_021_1 [Makoto]]
Responsabilidad, normas... Yo solo quiero tirar todas esas cosas y despegar a toda velocidad.

[msg MSG_022 [Mitsuru]]
Parece que ambas tenemos una carga similar despu〒s de todo.

[msg MSG_022_1 [Mitsuru]]
Tengo esa misma sensaciポn de libertad cuando voy en moto...

[msg MSG_022_2 [Mitsuru]]
No quiero obligarte a aceptar estos guantes, pero...

[msg MSG_022_3 [Mitsuru]]
Viendo que llevas la misma carga que yo, quiero que algマn dボa conozcas esa sensaciポn del viento en la cara.

[msg MSG_023 [Makoto]]
Kirijo...

[msg MSG_023_1 [Makoto]]
Gracias. メQu〒 te parece si ambas vamos en moto a algマn sitio cuando me saque mi carnet?

[msg MSG_024 [Mitsuru]]
Por supuesto. Una vez que volvamos al mundo real...

[msg MSG_024_1 [Mitsuru]]
Montemos juntas, ムa todo gas!

[msg MSG_025 [Makoto]]
Sボ, ムes una promesa!

