[msg MSG_000 [Junpei]]
Bueno, eso es todo. Realmente les he mostrado a esas sombras mi poder...

[msg MSG_001 [Mitsuru]]
ムIori!

[msg MSG_002 [Junpei]]
ムAay...! ムPerdポn! ムTienes razポn, me he estado desviando mucho!

[msg MSG_003 [Mitsuru]]
No, yo solo querボa decirte... buen trabajo.

[msg MSG_003_1 [Mitsuru]]
Tマ tambi〒n, Takeba. Bien hecho.

[msg MSG_004 [Yukari]]
Oh, eh, gracias...

[msg MSG_005 [Ryuji]]
ムGracias, Kirijo!

[msg MSG_006 [Ann]]
メEstホs bien, Mitsuru?

[msg MSG_007 [Mitsuru]]
Sボ, estoy bien, gracias a todos.

[msg MSG_008 [Makoto]]
*risita* Creo que lo has hecho muy bien, メno?

[msg MSG_009 [Mitsuru]]
メTe refieres como cebo? Eso solo ha funcionado porque todos me ayudasteis.

[msg MSG_010 [Makoto]]
No, me refiero a toda la operaciポn. Creo que tu equipo se coordinポ contigo perfectamente.

[msg MSG_010_1 [Makoto]]
Incluso Iori. ※l liderポ la carga cuando tendimos la trampa.

[msg MSG_011 [Mitsuru]]
Mmm... メPero solo lo estaba haciendo porque tenボa miedo de que me enfadara con 〒l?

[sel SEL_012 top]
No es por eso.
Es posible.
Lo inspiraste.

[msg MSG_013 [Makoto]]
Cierto. Creo que todo el mundo se dio cuenta de tu determinaciポn liderando el grupo.

[msg MSG_013_1 [Makoto]]
Por eso todos dieron un paso al frente.

[msg MSG_014 [Makoto]]
Bueno, tambi〒n podrボa ser... pero creo que no era la マnica razポn.

[msg MSG_014_1 [Makoto]]
Creo que todo el mundo se dio cuenta de tu determinaciポn liderando el grupo.

[msg MSG_014_2 [Makoto]]
Por eso todos dieron un paso al frente.

[msg MSG_015 [Makoto]]
Cierto. Creo que todo el mundo se ha dado cuenta de que, aunque seas estricta, eres muy responsable con tu equipo.

[msg MSG_016 [Mitsuru]]
Y-Ya veo... Muy bien, entonces.

[msg MSG_016_1 [Mitsuru]]
Aun asボ, preferirボa que se abrieran un poco mホs a mボ...

[msg MSG_017 [Ann]]
メQue se abrieran...? Quizホs solo necesites acercarte un poco mホs a ellos.

[sel SEL_018 top]
メCポmo compartir un hobby?
Come algunos dulces con todos.

[msg MSG_019 [Ryuji]]
ムAhボ estホ! Es fホcil hablar sobre cosas en las que ambos estホn interesados.

[msg MSG_020 [Mitsuru]]
Un hobby... Supongo que me gustan las motos...

[msg MSG_021 [Ryuji]]
Ey, ムeso es genial! ムA los chicos le encantan las motos! ムSon tan guais!

[msg MSG_021_1 [Ryuji]]
Yo nunca he vuelto a ver a Queen igual despu〒s de verla acribillar a las sombras en su moto.

[msg MSG_022 [Makoto]]
ムSkull! ムNo digas eso...!

[msg MSG_023 [Mitsuru]]
... メAcribillar? No estoy segura de a qu〒 te refieres, pero no creo que Iori est〒 muy interesado en las motos.

[msg MSG_024 [Ann]]
Sボ... No parece que tマ y Junpei compartan intereses...
Si ese es el caso, tu マnica opciポn podrボa ser intentar hacer algo que le guste...

[msg MSG_025 [Ann]]
ムOh, buena idea! ムQueen y yo empezamos a llevarnos bien despu〒s de que sali〒ramos a comer crêpes juntas!

[msg MSG_026 [Mitsuru]]
Dulces... Me gusta el t〒 de la tarde. Quizホs invite a Iori la prポxima vez...

[msg MSG_027 [Makoto]]
Hmm... Bueno, nosotros lo disfrutarボamos, pero, por algマn motivo, no parece que sea algo que Iori harボa...
Llegados a este punto,  tu マnica opciポn podrボa ser intentar hacer algo que le guste...

[msg MSG_028 [Mitsuru]]
Algo que le guste... Eso serホ difボcil.

[msg MSG_028_1 [Mitsuru]]
Imagino que tマ tuviste que superar un problema similar, メverdad?

[msg MSG_029 [Makoto]]
Sボ. Al principio no era mホs que un montポn de cabezazos y malentendidos casi todos los dボas.

[msg MSG_029_1 [Makoto]]
Pero las cosas acabarホn saliendo bien siempre que no te rindas.

[msg MSG_030 [Mitsuru]]
Ya veo... Creo que estoy empezando a entenderte un poco mejor ahora.

[msg MSG_031 [Makoto]]
*risita* Bueno, deberボamos de volver ya.

