[msg MSG_000 [Akihiko]]
This is it.

[msg MSG_001 [Ken]]
It's really crowded here.

[msg MSG_002 [Mitsuru]]
Now then, let's split up and ask around.

[msg MSG_003 [Yukari]]
How'd it go?

[msg MSG_004 [Junpei]]
It's the same as last time.

[msg MSG_004_1 [Junpei]]
Multiple perps ganged up on a lone woman[n]and took her wallet.

[msg MSG_005 [Yusuke]]
Apparently, it happened so fast, no one[n]knows where they came from nor where[n]they disappeared to.

[msg MSG_005_1 [Yusuke]]
Our enemies certainly know how to avoid[n]detection.

[sel SEL_006 top]
That's not good.
Just like phantom thieves.

[msg MSG_007 [Morgana]]
It's too bad we can't pick up their[n]trail...

[msg MSG_008 [Akihiko]]
You don't mean―!?

[msg MSG_009 [Morgana]]
No! Stop confusing everyone, Joker!

[msg MSG_010 [Ann]]
But I gotta say, the people are behaving[n]a lot differently now.

[msg MSG_011 [Ryuji]]
Seriously. I kinda thought they'd be[n]more "whatever" about all this.

[msg MSG_012 [Mitsuru]]
Hm? What do you mean?

[msg MSG_013 [Ryuji]]
This city used to be ruled by a real[n]scumbag, and everybody here just did[n]what he said.

[msg MSG_013_1 [Ryuji]]
They were completely dependent on him.[n]No one ever stood up for themselves...

[msg MSG_014 [Ann]]
But now it looks like the people are[n]starting to act on their own.

[msg MSG_014_1 [Ann]]
A few of them even came over and talked[n]to us, hoping it would help solve the[n]case.

[msg MSG_015 [Mitsuru]]
Oh? How interesting...

[msg MSG_016 [Yusuke]]
Those at the top will often affect those[n]below... I think this film is proof of[n]that.

[msg MSG_017 [Mitsuru]]
Those at the top...

[msg MSG_018 [Makoto]]
What's wrong?

[msg MSG_019 [Mitsuru]]
Nothing...

[msg MSG_019_1 [Mitsuru]]
We still have one more crime scene to[n]check. Let's ask around there as well.

