[msg MSG_000 [Junpei]]
Well, that's that. Man, I really showed[n]those Shadows this time...

[msg MSG_001 [Mitsuru]]
Iori!

[msg MSG_002 [Junpei]]
Eek...! Sorry! You're right, I was[n]messin' around too much!

[msg MSG_003 [Mitsuru]]
No, I just want to say... good job.

[msg MSG_003_1 [Mitsuru]]
You too, Takeba. Well done.

[msg MSG_004 [Yukari]]
Oh, uh, thanks...

[msg MSG_005 [Ryuji]]
Thanks, Kirijo-san!

[msg MSG_006 [Ann]]
Are you okay, Mitsuru-san?

[msg MSG_007 [Mitsuru]]
Yes, I'm fine, thanks to all of you.

[msg MSG_008 [Makoto]]
*chuckle* I think you did pretty well,[n]don't you?

[msg MSG_009 [Mitsuru]]
You mean as the bait? That only worked[n]because I had everyone's help.

[msg MSG_010 [Makoto]]
No, I meant the whole operation. I[n]thought your team coordinated with you[n]perfectly.

[msg MSG_010_1 [Makoto]]
Even Iori-kun. He led the charge when we[n]sprung the trap.

[msg MSG_011 [Mitsuru]]
Hrrm... But wasn't he only doing that[n]because he was afraid of me getting[n]angry at him?

[sel SEL_012 top]
That's not it.
It's possible.
You inspired him.

[msg MSG_013 [Makoto]]
Right. I think everyone noticed your[n]determination in leading the group.

[msg MSG_013_1 [Makoto]]
That's why they all stepped up.

[msg MSG_014 [Makoto]]
Well, that might've been part of it...[n]but I doubt that was the only reason.

[msg MSG_014_1 [Makoto]]
I think everyone noticed your[n]determination in leading the group.

[msg MSG_014_2 [Makoto]]
That's why they all stepped up.

[msg MSG_015 [Makoto]]
Right. I think everyone realizes that,[n]although you're strict, you feel a great[n]sense of responsibility for your team.

[msg MSG_016 [Mitsuru]]
I-I see... Very well, then.

[msg MSG_016_1 [Mitsuru]]
Still, I would prefer if they opened up[n]to me a little more...

[msg MSG_017 [Ann]]
Opened up...? Maybe you just need to[n]create some kind of opportunity.

[sel SEL_018 top]
Like a shared hobby?
Eat some sweets with everyone.

[msg MSG_019 [Ryuji]]
There you go! It's easy to talk about[n]things you're both interested in.

[msg MSG_020 [Mitsuru]]
A hobby... I suppose I like[n]motorcycles...

[msg MSG_021 [Ryuji]]
Hey, that's great! Guys love[n]motorcycles! They're cool as hell!

[msg MSG_021_1 [Ryuji]]
I never looked at Queen the same way[n]after seeing her mow down Shadows on her[n]motorcycle.

[msg MSG_022 [Makoto]]
Skull! Don't say that...!

[msg MSG_023 [Mitsuru]]
...Mow down? I'm not sure what you mean,[n]but I don't think Iori has much interest[n]in motorcycles.

[msg MSG_024 [Ann]]
Yeah... It doesn't seem like you and[n]Junpei-kun would share any interests...
If that's the case, your only choice[n]might be to try doing something he[n]likes...

[msg MSG_025 [Ann]]
Oh, good idea! Queen and I started[n]getting along again after we went and[n]ate cr○pes together!

[msg MSG_026 [Mitsuru]]
Sweets... I do enjoy afternoon tea.[n]Perhaps I'll invite Iori next time...

[msg MSG_027 [Makoto]]
Hmm... Well, we enjoyed that, but, for[n]some reason, that doesn't exactly sound[n]like Iori-kun's thing...
At this point, your only choice might be[n]to try doing something he likes...

[msg MSG_028 [Mitsuru]]
Something he likes... That will be[n]difficult.

[msg MSG_028_1 [Mitsuru]]
I imagine you had to overcome a similar[n]problem?

[msg MSG_029 [Makoto]]
Yes. At first, it was nothing but a[n]bunch of headbutting and[n]misunderstanding almost every day.

[msg MSG_029_1 [Makoto]]
But things will work out eventually as[n]long as you don't give up.

[msg MSG_030 [Mitsuru]]
I see... I think I'm beginning to[n]understand you a little better now.

[msg MSG_031 [Makoto]]
*chuckle* Well, we should be heading[n]back now.

