[msg MSG_000 [P3 Fem Protag]]
Este es el lugar.

[msg MSG_001 [Akihiko]]
夷Es una escena del crimen? No veo nada[n]inusual por aqu胤.

[msg MSG_002 [Makoto]]
Tal vez terminaron su investigaci吋n y ya[n]limpiaron...

[msg MSG_003 [Junpei]]
夷En serio? No encontramos ni una sola[n]pista...

[msg MSG_003_1 [Junpei]]
*sigh* Welp, ah胤 va mi motivaci吋n.

[msg MSG_004 [Yukari]]
Te est茨s rindiendo demasiado r茨pido.

[msg MSG_005 [Ann]]
夷Soy yo o hay mucha gente aqu胤?

[sel SEL_006 top]
Hay algo que ver.
Es una escena del crimen.
Nos hemos convertido en famosos...

[msg MSG_007 [Ann]]
S胤, supongo que una escena del crimen[n]llamar胤a la atenci吋n de la gente.

[msg MSG_008 [Yukari]]
Estoy bastante seguro de que no est茨n[n]aqu胤 para vernos.

[msg MSG_009 [Ann]]
Entiendo. Probablemente quieran ver la[n]escena del crimen.

[msg MSG_010 [Makoto]]
Alguien aqu胤 podr胤a saber qu姻 pas吋.

[msg MSG_011 [Mitsuru]]
Vamos a preguntar, entonces.

[msg MSG_012 [Makoto]]
Vale, Skull, t雨 y los chicos se dirigen[n]por ah胤. Panther, lleva a las chicas.

[msg MSG_012_1 [Makoto]]
Nos separaremos y veremos qu姻 podemos[n]aprender.

[msg MSG_013 [Ryuji]]
斡Lo tengo!

[msg MSG_014 [Ann]]
斡D姻melo!

[msg MSG_015 [Mitsuru]]
...

[msg MSG_016 [Ken]]
夷Mitsuru?

[msg MSG_017 [Mitsuru]]
Oh, perd吋name. S胤, tambi姻n deber胤amos[n]preguntar.

[msg MSG_018 [Ryuji]]
Estamos acabados al final.

[msg MSG_019 [Yusuke]]
Parece que un robo ocurri吋 aqu胤; alguien[n]le rob吋 su billetera.

[msg MSG_020 [Ann]]
Parece que tambi姻n hab胤a m雨ltiples[n]perps. They surrounded the victim and[n]charged in all at once.

[msg MSG_020_1 [Ann]]
La v胤ctima ni siquiera ten胤a tiempo para[n]reaccionar.

[msg MSG_021 [Yukari]]
O胤mos casi la misma historia.

[msg MSG_022 [Akihiko]]
Ganando a alguien as胤... 斡Eso es muy[n]bajo! 斡No se escapar茨n con esto!

[msg MSG_023 [Junpei]]
Pero no obtuvimos ninguna pista de d吋nde[n]est茨n los culpables o c吋mo se ven... 夷Y[n]ahora qu姻?

[sel SEL_024 top]
Es demasiado pronto para rendirse.
Vamos a revisar otra escena del crimen.

[msg MSG_025 [Makoto]]
S胤. Elizabeth marc吋 otros lugares para[n]nosotros.

[msg MSG_025_1 [Makoto]]
Podemos aprender algo que sirva de[n]pista.

[msg MSG_026 [Morgana]]
Bien, vamos a otra escena del crimen.

