[msg MSG_000 [Morgana]]
畏ste es el 雨ltimo.

[msg MSG_001 [Ryuji]]
斡Muy bien, veamos qu姻 podemos averiguar!

[msg MSG_002 [Junpei]]
No aprend胤 nada...

[msg MSG_002_1 [Junpei]]
Dame un descanso r茨pido...

[sel SEL_003 top]
斡Deja de abofetear!
Junpei!

[msg MSG_004 [Junpei]]
夷Qu姻? 斡Lo tienes todo mal! No estaba[n]abofeteando ni nada...

[msg MSG_004_1 [Junpei]]
Solo eres t雨, Joker. No me asustes as胤,[n]hombre, pens姻 que eras Mitsuru-senpai.

[msg MSG_005 [Mitsuru]]
夷Oh...? 夷Hay alg雨n problema con que est姻[n]aqu胤?

[msg MSG_006 [Junpei]]
夷Ack?

[msg MSG_006_1 [Junpei]]
斡No! Ya sabes, creo que perd胤 a algunas[n]personas, as胤 que voy a hacer un poco[n]m茨s asombro...

[msg MSG_007 [Mitsuru]]
Hmph...

[msg MSG_008 [Makoto]]
Bueno, est茨 de pie otra vez, as胤 que[n]supongo que funcion吋.

[msg MSG_009 [Mitsuru]]
Siento que tuvieras que ver otra muestra[n]vergonzosa de liderazgo.

[msg MSG_009_1 [Mitsuru]]
Fue una falta de comunicaci吋n por mi[n]parte. Verte solo lo hace m茨s claro.

[msg MSG_010 [Makoto]]
夷Yo?

[msg MSG_011 [Mitsuru]]
Eres un presidente del consejo[n]estudiantil y un anciano entre tus[n]compa隠eros...

[msg MSG_011_1 [Mitsuru]]
Y, a diferencia de m胤, has construido[n]una base de confianza adecuada con los[n]miembros m茨s j吋venes de tu grupo.

[sel SEL_012 top]
Ahora tiene...
Al principio ten胤a bastante miedo.
Realmente se afloj吋.

[msg MSG_013 [Mitsuru]]
... 夷No siempre fue as胤?

[msg MSG_014 [Makoto]]
Bueno, no. Durante mucho tiempo, me[n]sent胤 separado de todos los dem茨s como[n]t雨 ahora.

[msg MSG_014_1 [Makoto]]
Pero desde que conoc胤 a todos, creo que[n]he cambiado algo...

[msg MSG_014_2 [Makoto]]
Si hay algo, soy envidiable de ti,[n]Kirijo.

[msg MSG_015 [Mitsuru]]
夷Envidioso? 夷De m胤?

[msg MSG_016 [Makoto]]
En mi caso, no dir胤a que fuera bueno[n]haciendo amigos o nada. Creo que no[n]ten胤a sentido de la antiguedad.

[msg MSG_016_1 [Makoto]]
Verdaderamente, respeto esa presencia[n]ordenante...

[msg MSG_017 [Mitsuru]]
... 夷As胤 es como lo ves?
Parece que ambos tenemos nuestras[n]debilidades.

[msg MSG_018 [Yukari]]
斡Oh, Mitsuru-senpai!

[msg MSG_019 [Mitsuru]]
夷C吋mo est茨n las cosas? 夷Alguna[n]informaci吋n 雨til?

[msg MSG_020 [Yukari]]
La misma historia, alguien fue saltado[n]por varios atacantes y le robaron sus[n]valores.

[msg MSG_021 [Junpei]]
Estos tipos son bastante pat姻ticos para[n]atacar a las se隠oritas.

[msg MSG_022 [Mitsuru]]
夷Todas las v胤ctimas son mujeres?

[msg MSG_023 [Junpei]]
Era una chica de la misma edad que[n]nosotros, como el 雨ltimo lugar.

[msg MSG_024 [Makoto]]
Como el 雨ltimo lugar, dices... 夷Y la[n]primera v胤ctima?

[msg MSG_025 [Ryuji]]
Creo que o胤 algo de que era una joven...

[msg MSG_026 [Yusuke]]
S胤, es probable que aumente sus[n]posibilidades de 姻xito en comparaci吋n[n]con los hombres musculares.

[msg MSG_026_1 [Yusuke]]
Sin embargo, estos ladrones son la[n]escoria de la tierra.

[msg MSG_027 [Makoto]]
De acuerdo. Pero conocer su objetivo[n]habitual puede ser 雨til para nosotros...

[sel SEL_028 top]
夷Util?
Podemos cederlos.

[msg MSG_029 [Makoto]]
Si sabemos que s吋lo apuntan a las[n]chicas, entonces podemos ponerles una[n]trampa.

[msg MSG_030 [Morgana]]
Ya veo. Vamos a atraerlos.

[msg MSG_031 [Makoto]]
Cierto. Si sabemos que s吋lo apuntan a[n]las chicas, entonces podemos ponerles[n]una trampa.

[msg MSG_032 [Ken]]
夷Pero no ser茨 peligroso para quien[n]juegue el cebo?

[msg MSG_033 [Makoto]]
Creo que podr胤a defenderme, pero con mi[n]apariencia...

[msg MSG_034 [Yukari]]
Ahaha... S胤, dudo que quieran atacar a[n]un ladr吋n fantasma...

[msg MSG_034_1 [Yukari]]
夷Debo ir?

[msg MSG_035 [Mitsuru]]
No, lo har姻. Como anciano del grupo, es[n]mi trabajo correr el riesgo.

[sel SEL_036 top]
Por favor.
No decepciones a tu guardia.
夷Quieres que me cruce?

[msg MSG_037 [Makoto]]
S胤, estaremos listos para saltar en[n]cualquier momento, as胤 que no tendr茨s[n]que preocuparte.

[msg MSG_038 [Mitsuru]]
Lo s姻. Esa fue mi intenci吋n desde el[n]principio.

[msg MSG_039 [Ryuji]]
No creas que va a funcionar, amigo...

[msg MSG_040 [Mitsuru]]
Aprecio tu preocupaci吋n, pero estar姻[n]bien.

[msg MSG_041 [Mitsuru]]
斡Yamagishi!

[msg MSG_042 [Fuuka]]
斡S胤, se隠ora!

[msg MSG_043 [Mitsuru]]
夷Puedes encontrarnos una buena ubicaci吋n[n]para atraer a los ladrones?

[msg MSG_044 [Fuuka]]
D姻jame ver... 夷Qu姻 tal el callej吋n[n]trasero cerca del centro del mapa?

[msg MSG_044_1 [Fuuka]]
Mitsuru-senpai esperar茨 all胤 en espera.[n]El resto de ustedes cubrir茨n las salidas[n]y los atacar茨n desde ambos lados.

[msg MSG_045 [Mitsuru]]
Gracias. Marcar姻 la ubicaci吋n en el[n]mapa.

[msg MSG_046 [Makoto]]
No podemos dejarles escapar con m茨s[n]robos. Vayamos al callej吋n.

