[msg MSG_000 [Elizabeth]]
Bravo, bravo. Mi sombrero est茨 fuera de[n]tus habilidades de investigaci吋n.

[msg MSG_001 [Junpei]]
Realmente nos diste un mal momento, ya[n]sabes. Fue dif胤cil imaginarlo todo con[n]cerca de ninguna informaci吋n.

[msg MSG_001_1 [Junpei]]
Pero la gente de Kamo City puede dormir[n]bien esta noche, gracias a m胤...

[sel SEL_002 top]
Junpei, 夷Superdetective?
...

[msg MSG_003 [Mitsuru]]
J-junpei, Superdetective...

[msg MSG_004 [Junpei]]
夷Eh?

[msg MSG_005 [Yukari]]
夷Qu姻...?

[msg MSG_006 [Mitsuru]]
... Ten胤a la sensaci吋n de que ibas a[n]decir eso.

[sel SEL_007 top]
Eso es pensar como Junpei.
夷Te sientes bien?
Eso fue hermoso...

[msg MSG_008 [Mitsuru]]
夷Puedes dejar de hablar de eso?

[msg MSG_009 [Mitsuru]]
Dijiste que deb胤a intentarlo, as胤 que...

[msg MSG_010 [Mitsuru]]
No act雨es como si fuera tan[n]conmovedor...!

[msg MSG_011 [Ryuji]]
Bueno, s吋lo resolvimos el caso por toda[n]la informaci吋n que obtuvimos de la gente[n]de la ciudad.

[msg MSG_012 [Ann]]
No creo que hubieran hecho algo as胤[n]antes. Realmente han cambiado.

[msg MSG_013 [Junpei]]
Supongo que lo m茨s importante es el tipo[n]al mando. Ese es el camino del mundo.

[msg MSG_014 [Yukari]]
Porque sabes mucho sobre eso...

[msg MSG_015 [Elizabeth]]
Ahora bien, aqu胤 est茨 tu recompensa. Por[n]favor, ac姻ptalo.

[msg MSG_016 [Mitsuru]]
Perd吋name, pero me gustar胤a que tuvieras[n]esto.

[msg MSG_017 [Makoto]]
夷Gloves?

[msg MSG_018 [Mitsuru]]
Son guantes de moto. Quer胤a darte las[n]gracias por todo lo que hiciste por m胤[n]esta vez.

[msg MSG_019 [Makoto]]
No necesitas agradecerme... Adem茨s, a雨n[n]no tengo mi licencia.

[msg MSG_020 [Mitsuru]]
夷En serio? Despu姻s de ver a tu Persona,[n]asum胤...

[msg MSG_021 [Makoto]]
Creo que es s吋lo una representaci吋n de[n]c吋mo me siento.

[msg MSG_021_1 [Makoto]]
Responsabilidad, regulaciones... S吋lo[n]quiero tirar todas esas cosas a toda[n]velocidad.

[msg MSG_022 [Mitsuru]]
Parece que ambos cargamos una carga[n]similar despu姻s de todo.

[msg MSG_022_1 [Mitsuru]]
Siento el mismo sentido de la libertad[n]cuando estoy montando mi moto.

[msg MSG_022_2 [Mitsuru]]
No te obligar姻 a aceptar estos guantes,[n]pero...

[msg MSG_022_3 [Mitsuru]]
Al ver como soportas la misma carga que[n]yo, quiero que sepas ese sentimiento del[n]viento en tu cara alg雨n d胤a.

[msg MSG_023 [Makoto]]
Kirijo...

[msg MSG_023_1 [Makoto]]
Gracias. 夷Qu姻 dices si ambos sacamos[n]nuestras bicicletas en alg雨n lugar, una[n]vez que consiga mi licencia?

[msg MSG_024 [Mitsuru]]
Por supuesto. Una vez que volvamos al[n]mundo real...

[msg MSG_024_1 [Mitsuru]]
斡Vamos juntos, trineo!

[msg MSG_025 [Makoto]]
斡S胤, es una promesa!

