[msg MSG_000 [Junpei]]
ムTachホn! ムJunpei ha obtenido un objeto raro!

[msg MSG_001 [P3 Fem Protag]]
Esto va mucho mejor de lo que me esperaba. Supongo que no serホ tan difボcil estando todos nosotros.

[msg MSG_002 [Morgana]]
Los Ladrones Fantasma multiplicados por tres... Aunque en este momento, no me siento mucho como un ladrポn.

[sel SEL_003 top]
Eso es el triple de poder de ataque.
Eso significa un tercio de tiempo en pantalla...

[msg MSG_004 [P3 Fem Protag]]
Exactamente. Imagina lo fホcil que serボa explorar La Tホrtaro con tanta gente.

[msg MSG_005 [Junpei]]
Sボ, pero me preocuparボa dejar a alguien atrホs cada vez que subi〒ramos al siguiente piso.

[msg MSG_006 [P3 Fem Protag]]
ムメEso es lo que te preocupa?!

[msg MSG_007 [Junpei]]
No, tiene razポn. Los fans de Junpei de todo el mundo van a estar muy decepcionados.

[msg MSG_008 [Yukari]]
メDe qu〒 estホs hablando? Incluso [f 6 1 27 0 0 0] ha perdido la fe en ti.

[msg MSG_009 [P3 Fem Protag]]
...

[msg MSG_010 [Junpei]]
Y no en broma. ムSe ha quedado sin palabras!

[msg MSG_011 [P3 Fem Protag]]
Lo siento... Es que me siento muy emocionada en este momento.

[msg MSG_012 [Yukari]]
メEh? メQu〒 parte te ha hecho emocionarte?

[msg MSG_013 [P3 Fem Protag]]
Bueno, solo pensaba que, sin importar el espacio o tiempo en el que est〒, Junpei sigue siendo tan tonto como siempre.

[msg MSG_014 [Junpei]]
ムメAhora me estホs despreciando?!

[msg MSG_015 [P3 Fem Protag]]
ムJa, ja, ja, no lo pienses mucho! ムVamos, encontremos al prポximo enemigo!

[msg MSG_016 [Junpei]]
ムEy! ムEsperad un segundo!

[msg MSG_017 [Yukari]]
メQu〒 estホn haciendo...?

[msg MSG_018 [Fuuka]]
*risita* Creo que esa es la forma de Junpei de ser considerado.

[sel SEL_019 top]
Sボ.
メCポmo?

[msg MSG_020 [Yukari]]
Probablemente quiera asegurarse de que [f 6 1 27 0 0 0] no se sienta incポmoda.

[msg MSG_021 [Fuuka]]
se estaba riendo.

[msg MSG_022 [Fuuka]]
Estaba intentando ayudar a que [f 6 1 27 0 0 0] se sintiera mホs a gusto.

[msg MSG_023 [Yukari]]
Ese Junpei... Siempre intentando ayudar.

[msg MSG_024 [Fuuka]]
Pero creo que estホ ayudホndola a abrirse un poco.
Entonces, メdeberボamos irnos yendo? Nuestro prポximo destino es 3-F.

[msg MSG_025 [Yukari]]
Entendido. No queremos quedarnos detrホs de Junpei, メno?

[msg MSG_026 [Fuuka]]
Pero creo que estホ ayudホndola a abrirse un poco.
Entonces, メdeberボamos irnos yendo? Nuestro prポximo destino es 3-F.

[msg MSG_027 [Yukari]]
Entendido. No queremos quedarnos detrホs de Junpei, メno?

[msg MSG_028 [Fuuka]]
Pero creo que estホ ayudホndola a abrirse un poco.
Entonces, メdeberボamos irnos yendo? Nuestro prポximo destino es o 4-B o 3-F.

[msg MSG_029 [Yukari]]
Entendido. No queremos quedarnos detrホs de Junpei, メno?

