[msg MSG_000 [Ken]]
Materiales raros... Siento que esto[n]probar茨 nuestra paciencia.

[sel SEL_001 top]
Vamos a golpear a cada enemigo que[n]vemos.
Necesitamos los lugares de los enemigos.

[msg MSG_002 [Akihiko]]
S胤. Si hacemos eso, estamos seguros de[n]conseguir esos materiales eventualmente.

[msg MSG_003 [Shinjiro]]
Estar胤amos perdiendo el tiempo. 夷No hay[n]una manera de ir directo a los que[n]tienen lo que necesitamos?

[msg MSG_004 [Mitsuru]]
Buen pensamiento. Queremos buscar s吋lo a[n]los enemigos que tienen los materiales[n]necesarios.

[msg MSG_005 [Fuuka]]
Hay un gran n雨mero de esos Phantom Mages[n]Theo mencionados alrededor de la zona[n]4-B.

[msg MSG_006 [Rise]]
斡Tambi姻n tenemos un mont吋n de arenas[n]flotantes en 3-F!

[msg MSG_007 [Mitsuru]]
Ya veo... 夷Hm? Deber胤a haber un objetivo[n]m茨s.

[msg MSG_008 [Futaba]]
El Rampage Drive... No parece ser[n]exclusivo de ninguna ubicaci吋n.

[msg MSG_009 [Ryuji]]
As胤 que tendremos que estar atentos,[n]夷s胤?

[msg MSG_010 [Futaba]]
S胤, pero ninguna ubicaci吋n de[n]configuraci吋n significa que podr胤amos[n]encontrarlos en cualquier momento.
斡Derriba esos Rampage Drives mientras[n]busca a los otros dos enemigos!

[msg MSG_011 [Fuuka]]
Si los materiales que caen las sombras[n]son duros, entonces es probable que[n]tambi姻n lo sean.
Aseg雨rate de usar tus Personas[n]sabiamente, 斡y darte una ventaja!

[msg MSG_012 [P3 Fem Protag]]
斡Bien!

[msg MSG_013 [Yukari]]
As胤 que 4-B o 3-F, 夷verdad? Te dejaremos[n]la decisi吋n.

[msg MSG_014 [Junpei]]
斡Muy bien, vamos!

