[msg MSG_000 [Fuuka]]
ムParece que ya tenemos todo lo que necesitamos!

[msg MSG_001 [P3 Fem Protag]]
ムBuen trabajo!
Volvamos al cine e informemos a Elizabeth.

[msg MSG_002 [Yukari]]
Tマ tambi〒n hiciste un buen trabajo, [f 6 1 27 0 0 0]. メTe va bien?

[msg MSG_003 [P3 Fem Protag]]
Ja, ja, ja, sボp. ムMe va genial!

[msg MSG_004 [Yukari]]
Oh, quiero decir... S〒 que lo has pasado mal desde que te trajeron aquボ...
Tマ lo has tenido mucho mホs difボcil que todos nosotros, pero tマ tambi〒n eres la mホs brillante y la mホs divertida.

[msg MSG_005 [P3 Fem Protag]]
Bueno, ahora mismo, no tengo papel de lボder, asボ que es todo lo que puedo hacer.
No tendrボa nada si me quitaran eso.

[sel SEL_006 top]
Eso ayuda mucho.
Eso es realmente importante.
Tマ eres el alma de la fiesta.

[msg MSG_007 [Junpei]]
Claro. Si te sientes de bajポn, entonces el resto del grupo tambi〒n estaremos de bajポn.

[msg MSG_008 [Yukari]]
Mm. A diferencia de otra persona que conozco, haces un buen trabajo.

[msg MSG_009 [Fuuka]]
Creo que mantener la fiesta animada es muy importante.

[msg MSG_010 [P3 Fem Protag]]
Van a hacer que me sonroje...
Solo estoy intentando poner de mi parte para el equipo...

[msg MSG_011 [Akihiko]]
Ey, [f 6 1 27 0 0 0], メtienes un segundo? Mitsuru te estホ llamando.

[msg MSG_012 [P3 Fem Protag]]
Ahora mismo voy.
Les dejo los materiales a ustedes.

[msg MSG_013 [Junpei]]
Aマn parece que hay algo de distancia entre nosotros...

[msg MSG_014 [Fuuka]]
Antes tambi〒n parecボa que estaba siendo modesta.

[msg MSG_015 [Junpei]]
メNo hay ningマn tipo de objeto mホgico o algo asボ que acerque los corazones?

[sel SEL_016 top]
メObjeto mホgico?
メQu〒 tal un regalo?

[msg MSG_017 [Junpei]]
Oh, solo era un ejemplo.

[msg MSG_018 [Yukari]]
ムOh, eso es!

[msg MSG_019 [Fuuka]]
メQu〒 pasa, Yukari?

[msg MSG_020 [Yukari]]
Es bueno demostrar a tus compaワeros que les aprecias de vez en cuando, メverdad?
Acercaos, chicos... Yo digo que... Y entonces...

[msg MSG_021 [Junpei]]
Oh, bien... Eres muy intrigante, Yuka.

[msg MSG_022 [Fuuka]]
*risita* No puedo esperar a ver su reacciポn.

[msg MSG_023 [Yukari]]
Deberボamos darnos prisa y darle esto a Theodore.
ムVamos!

