[msg MSG_000 [Elizabeth]]
メOh? Han venido en el momento perfecto.
Justo sucede que hay una solicitud para ver una cierta proyecciポn especial.
El ticket ya ha sido registrado en la taquilla. Por favor, echad un vistazo.

[sel SEL_001 top]
メUna solicitud?
メDe qui〒n?

[msg MSG_002 [Elizabeth]]
Sボ, era de nada menos que...

[msg MSG_003 [Cocky voice]]
*risita* No era mucho problema, メno?

[msg MSG_004 [Calm voice]]
Sボ, creo que estホbamos en nuestro derecho.

[msg MSG_005 [Elizabeth]]
Bien...

[msg MSG_006 [Cocky voice]]
*risita* Era de nosotras.

[msg MSG_007 [Calm voice]]
Y cumplir〒is dicha solicitud como deseamos.

[msg MSG_008 [Futaba]]
ムWhoa! ムメDe dポnde han salido las gemelas?!
メQu〒 ocurre? メOs sentボais solas?

[msg MSG_009 [Justine]]
Apenas... Solo hemos venido a deciros nuestras ポrdenes.

[msg MSG_010 [Caroline]]
Sボ. Si dejamos que las cosas sigan asボ, todas vuestras pelボculas van a resultar muy fホciles.
Pensamos en organizar algunas pruebas para ayudar en su rehabilitaciポn

[msg MSG_011 [Elizabeth]]
Vuestro objetivo en esta proyecciポn especial es...
... Derrotar a los Seidoptera que residen en Junessic Land.

[msg MSG_012 [P4 Hero]]
メEse FOE? Esto va a ser duro.

[msg MSG_013 [Chie]]
ムPero deberボa de ser una buena batalla considerando lo fuertes que somos ahora!

[msg MSG_014 [Ryuji]]
Tambi〒n nos sentimos mホs cポmodos en este lugar. No deberボa ser muy difボcil, ahora que nuestro equipo es mホs grande.

[msg MSG_015 [Justine]]
... Quizホs. Sin embargo, hay dos FOEs. Deb〒is derrotarlos a ambos.

[msg MSG_016 [P4 Hero]]
メDos?

[msg MSG_017 [Caroline]]
*risita* メYa os hab〒is asustado?
No serボa divertido ver cポmo lo hacボais tan fホcilmente.

[msg MSG_018 [Justine]]
Ahora, que comience la proyecciポn especial. Daos prisa y entretenednos.

[sel SEL_019 top]
Supongo que deberボamos intentarlo.
No hemos dicho que sボ.

[msg MSG_020 [Caroline]]
ムBien dicho! ムAhora, salid de aquボ y acabad con ellas!

[msg MSG_021 [Justine]]
Esa es una buena mentalidad. Quizホs podrボamos elevar un poco nuestras expectativas.

[msg MSG_022 [Justine]]
メPiensas escabullirte, Recluso? Esta prueba es tambi〒n por tu propio bien.

[msg MSG_023 [Caroline]]
Sボ, si ni siquiera puedes conseguir esto, entonces olvボdate de tener 〒xito en tu rehabilitaciポn.

[msg MSG_024 [Makoto]]
Tienen razポn. Luchar contra enemigos fuertes puede servirnos para ganar experiencia.

[msg MSG_025 [Ann]]
Hmm... Ellas nos han ayudado mucho. Quizホs deberボamos escucharlas.

[msg MSG_026 [Elizabeth]]
Parece que hab〒is tomado una decisiポn.
Suban las cortinas. ムLa batalla estホ a punto de comenzar!

[msg MSG_027 [Justine]]
Como estrellas de este espectホculo, deb〒is dar el mホximo de vuestras capacidades.

[msg MSG_028 [Caroline]]
Os veremos desde aquボ. ムNo se permiten pasos en falso, Recluso!

