[msg MSG_000 [Yusuke]]
Ngh...
At this rate... I'm going to collapse...

[sel SEL_001 top]
Are you okay?
You can barely stand.

[msg MSG_002 [Yusuke]]
Joker... I think this is it for me...

[msg MSG_003 [Yusuke]]
As I'm sure you've already guessed...[n]I'm very hungry...
I nearly took a bite out of Mona's tail[n]because it looked like an eel... My[n]stomach is beyond empty!

[msg MSG_004 [Akihiko]]
What's wrong, Fox? You feelin' sick or[n]something?

[msg MSG_005 [Yusuke]]
My hunger has bested me.
Normally, I'd resort to eating[n]beansprouts or radish leaves, but I[n]can't do that here...
This is shameful of me to ask, but...[n]will you spare me some food?

[msg MSG_006 [Akihiko]]
Heh, you should've just said so. Here,[n]take this.

[msg MSG_007 [Yusuke]]
Ahh! This is...!

[msg MSG_008 [Akihiko]]
A protein bar! Not only is it healthy,[n]but it's also easy to eat.

[msg MSG_009 [Akihiko]]
In order to stay fit, you have to be[n]sure to exercise AND get plenty of[n]nutrition.
You can exercise all you want, but[n]without any nutrition, it's pointless.
That's why you gotta take protein!
It's best to take it roughly 45 minutes[n]after you work out, so I carry...

[msg MSG_010 [Yusuke]]
*sigh* Thank you. That was quite nice.

[msg MSG_011 [Akihiko]]
Wha...!? You're finished already!?

[msg MSG_012 [Yusuke]]
Yes... But I'm far from full... In fact,[n]I'm hungrier than ever.

[msg MSG_013 [Yusuke]]
Ugh... How humiliating... I suppose this[n]is where I die...

[msg MSG_014 [Akihiko]]
Stay with me, Fox!
I can't leave a man behind... I'll just[n]have to ask him.

[msg MSG_015 [Shinjiro]]
...So, you want me to make you[n]somethin'?

[msg MSG_016 [Akihiko]]
Yeah, something that'll energize us.
It's been so long since I've eaten[n]anything made by you. I wonder what we[n]should have you make...

[msg MSG_017 [Shinjiro]]
How come you're callin' the shots here?

[msg MSG_018 [Akihiko]]
Who cares about the details!?
Besides, you almost never cook for me![n]It's not fair.

[msg MSG_019 [Shinjiro]]
*sigh* And I thought you were trying to[n]help someone... Selfish bastard.
Whatever... Everyone'll be happy if I[n]make some food, right?

[sel SEL_020 top]
Yes, please.
I want some too.

[msg MSG_021 [Shinjiro]]
Man, you're high maintenance.
The question now is: do we have any[n]ingredients?

[msg MSG_022 [Yusuke]]
Hrgh, that's right...! Is there any[n]grass nearby?

[msg MSG_023 [Akihiko]]
I have some backup protein. It's powder,[n]though.

[msg MSG_024 [Shinjiro]]
*sigh* I can't make anything with this.

[msg MSG_025 [Yusuke]]
Ngh... Well, if we don't have any[n]ingredients, then we'll just have to[n]find some!
I, Fox, will do anything for a delicious[n]meal!

[msg MSG_026 [Akihiko]]
Heh... Looks like you're up to the task.[n]Okay, me too. I'll give it my best shot.

[msg MSG_027 [Shinjiro]]
Just how hungry are you guys...?
Either way, I can't do anything until[n]you get those ingredients.

[msg MSG_028]
A new special screening: "The Price of a[n]Free Meal" has been added to the box[n]office.

