[msg MSG_000 [Akihiko]]
Muy bien. Deber胤amos estar bien por un tiempo.

[msg MSG_001 [Yusuke]]
斡Ja, ja, ja, ja! 斡Aquellos que retrasan mi comida no tienen perd吋n!

[msg MSG_002 [Yukiko]]
Es incre胤ble lo que hace por comida... Casi me recuerda a Chie y su amor por la carne.

[msg MSG_003 [Chie]]
斡夷Eso no es tan malo, verdad?!

[msg MSG_004 [Yosuke]]
No s姻... Creo que es m茨s o menos lo mismo.

[msg MSG_005 [Yusuke]]
En cualquier caso, hemos eliminado la amenaza. 斡Volvamos a los peces!

