[msg MSG_000 [Akihiko]]
Muy bien. Deberボamos estar bien por un tiempo.

[msg MSG_001 [Yusuke]]
ムJa, ja, ja, ja! ムAquellos que retrasan mi comida no tienen perdポn!

[msg MSG_002 [Yukiko]]
Es increボble lo que hace por comida... Casi me recuerda a Chie y su amor por la carne.

[msg MSG_003 [Chie]]
ムメEso no es tan malo, verdad?!

[msg MSG_004 [Yosuke]]
No s〒... Creo que es mホs o menos lo mismo.

[msg MSG_005 [Yusuke]]
En cualquier caso, hemos eliminado la amenaza. ムVolvamos a los peces!

