[msg MSG_000 [Ken]]
Fantasmas ladrones, 夷eh?

[msg MSG_001 [Morgana]]
夷Hm? 夷Qu姻 pasa?

[msg MSG_002 [Ken]]
Nada. Es s吋lo... cambiar en un disfraz y[n]luchar contra el mal suena como algo que[n]ver胤as en un c吋mic.
Entonces... 夷por qu姻 se convirtieron en[n]ladrones fantasma?

[sel SEL_003 top]
Nos equivocamos.
Simplemente sucedi吋.
Porque est茨 bien.

[msg MSG_004 [Ken]]
夷Error?

[msg MSG_005 [Ryuji]]
Adultos de mierda Buncha... Todos vimos[n]de primera mano lo desordenados que[n]pueden ser.

[msg MSG_006 [Ryuji]]
Bueno, s胤, empez吋 as胤...
はまるよ まょろよょぼまれ めもぼもゆよれ ょゎまれろるぺ ゆまろぺ ぽま ぽまろまょまる[n]ぺ ろよぽよれ まれよれ もぽもよろぺれ りゎま らまょれぺほぺょ りゎま らよぽウぺょ[n]めぺぼまる ゅよ りゎま りゎもれもまるぺょテ

[msg MSG_007 [Morgana]]
Bueno, supongo que es verdad.
Suena bastante bien para herir el mal en[n]nombre de la justicia, 夷no?

[msg MSG_008 [Ann]]
Est茨bamos planeando que fuera una cosa[n]de una sola vez...
Pero entonces nos dimos cuenta de que no[n]姻ramos los 雨nicos adultos aprovechando.
As胤 que seguimos adelante, esperando que[n]podamos hacer una diferencia.

[msg MSG_009 [Morgana]]
Y as胤 nacieron los Fantasmas,[n]protegiendo a los d姻biles y cambiando[n]los corazones de los imp胤os!

[msg MSG_010 [Ken]]
Cambiar los corazones de los malvados...
...

[msg MSG_011 [Morgana]]
夷Est茨s bien, Ken?

[msg MSG_012 [Ken]]
Estoy bien. 斡Gracias por compartir!

[msg MSG_013 [Ann]]
... 夷Qu姻 pasa con Ken?

[msg MSG_014 [Ryuji]]
Bueno, 姻l es esa edad, 夷sabes?
Cada tipo tiene un tiempo cuando quiere[n]ser un superh姻roe.

[msg MSG_015 [Ann]]
夷En serio?

[msg MSG_016]
Una nueva proyecci吋n especial: "Una[n]Lecci吋n en Justicia" se ha a隠adido a la[n]taquilla.

