[msg MSG_000 [Futaba]]
Nuestros objetivos son tres Guardian Machines. Tened cuidado.

[msg MSG_001 [Morgana]]
斡Vamos, Ken, intenta mantener el ritmo!

[msg MSG_002 [Ken]]
As胤 que los ladrones fantasma se mantienen en las sombras y eliminan a sus enemigos en silencio, 夷no?

[sel SEL_003 top]
El sigilo es el camino a seguir.
Todo el tiempo.
Qu姻 mal que no lo podamos hacer aqu胤...

[msg MSG_004 [Ken]]
As胤 que es verdad...
夷Tambi姻n salt茨is muros y os escabull胤s de los l茨seres de seguridad?

[msg MSG_005 [Ann]]
S胤, lo hemos hecho unas cuantas veces.

[msg MSG_006 [Ann]]
S胤. Eso definitivamente hace las cosas m茨s f茨ciles

[msg MSG_007 [Ryuji]]
No bromeo. Ya habr胤amos terminado la proyecci吋n si fuera como siempre.
Piensa en todos los muros que tuvimos que saltar y en los l茨seres de seguridad que tuvimos que sortear.

[msg MSG_008 [Ken]]
A-As胤 que es verdad...

[msg MSG_009 [Morgana]]
Pareces bastante familiarizado con estas cosas, Ken.

[msg MSG_010 [Ken]]
夷Eh? Oh, bueno... He aprendido un mont吋n de libros y pel胤culas.

[msg MSG_011 [Morgana]]
Estupendo. Podr胤as tener incluso m茨s potencial que Skull.

[msg MSG_012 [Ryuji]]
斡夷Qu姻 has dicho?!

[msg MSG_013 [Ann]]
Vale, vale, gu茨rdalo para las Sombras. Debemos irnos.

[sel SEL_014 top]
Comencemos la misi吋n.
Vamos a empezar.
S胤guenos.

[msg MSG_015 [Ken]]
斡S胤!

