[msg MSG_000 [Ann]]
ムOtra sombra menos! ムYa solo queda una!

[msg MSG_001 [Ryuji]]
Je, ムesto no es nada comparado con robar un Tesoro!

[msg MSG_002 [Ken]]
Oh, メy qu〒 le ocurre a una persona cuando le roban su Tesoro?

[sel SEL_003 top]
Tienen un despertar de corazポn.
Se entregan a ellos mismos.
Se echan a llorar.

[msg MSG_004 [Ann]]
Eso solo ocurre porque se sienten culpables por lo que han hecho.

[msg MSG_005 [Morgana]]
Es porque sus retorcidos deseos desaparecen junto con su Palacio.
Su conciencia cede ante su culpabilidad, por lo que acaban confesホndolo todo.

[msg MSG_006 [Ken]]
Asボ que eso es un despertar de corazポn... Es bastante aterrador cuando lo piensas.

[msg MSG_007 [Ryuji]]
Por eso todos acordamos nuestro objetivo antes de hacer ir a por 〒l. No queremos abusar de ese poder.

[msg MSG_008 [Ken]]
Abusar...

[msg MSG_009 [Ann]]
... メKen?

[msg MSG_010 [Ken]]
Oh, perdポn. Estoy aprendiendo mucho, eso es todo.

[msg MSG_011 [Morgana]]
Continuemos con la lecciポn mホs tarde. Vホmonos por ahora.

[msg MSG_012 [Ken]]
ムC-Cierto!

