[msg MSG_000 [Akihiko]]
Dos menos, quedan dos. Esa no estuvo tan mal.

[msg MSG_001 [Shinjiro]]
Sボ, bueno, aマn no ha terminado.

[msg MSG_002 [Akihiko]]
Perdポn, Shinji, pero esta competiciポn es mボa. Sin rencores, メde acuerdo?

[msg MSG_003 [Shinjiro]]
Sボ, seguro... Tonto del culo.

[msg MSG_004 [Mitsuru]]
ムParad vosotros dos! ムメNo os da verg↓enza actuar de esa forma en frente de personas mホs jポvenes?!

[msg MSG_005 [Akihiko]]
No te preocupes, Mitsuru. Shinji se calmarホ una vez que acabe todo esto.

[msg MSG_006 [Shinjiro]]
Oh, メcomo si fuera a perder? ムTe vas a comer esas palabras, mierdecilla!

[msg MSG_007 [P3 Fem Protag]]
*risita* ムOkay, vamos! ムA por el tercero!

[msg MSG_008 [Mitsuru]]
Uf... No puedo mirar...

