[msg MSG_000 [Akihiko]]
Dos menos, quedan dos. Esa no estuvo tan mal.

[msg MSG_001 [Shinjiro]]
S胤, bueno, a雨n no ha terminado.

[msg MSG_002 [Akihiko]]
Perd吋n, Shinji, pero esta competici吋n es m胤a. Sin rencores, 夷de acuerdo?

[msg MSG_003 [Shinjiro]]
S胤, seguro... Tonto del culo.

[msg MSG_004 [Mitsuru]]
斡Parad vosotros dos! 斡夷No os da vergüenza actuar de esa forma en frente de personas m茨s j吋venes?!

[msg MSG_005 [Akihiko]]
No te preocupes, Mitsuru. Shinji se calmar茨 una vez que acabe todo esto.

[msg MSG_006 [Shinjiro]]
Oh, 夷como si fuera a perder? 斡Te vas a comer esas palabras, mierdecilla!

[msg MSG_007 [P3 Fem Protag]]
*risita* 斡Okay, vamos! 斡A por el tercero!

[msg MSG_008 [Mitsuru]]
Uf... No puedo mirar...

