[msg MSG_000 [P3 Fem Protag]]
ムBien hecho, chicos! ムUno menos!

[msg MSG_001 [Akihiko]]
メQui〒n ha sido el ganador esta vez? Dボnoslo, [f 6 1 27 0 0 0].

[msg MSG_002 [P3 Fem Protag]]
Hmm... Aマn es muy pronto para decirlo. Despu〒s de todo, es al mejor de cuatro.

[msg MSG_003 [Shinjiro]]
Al siguiente. Acabemos con esto.

[msg MSG_004 [Akihiko]]
Recuerda, Shinji, si gano tendrホs que hacer un entrenamiento especial conmigo.

[msg MSG_005 [Shinjiro]]
ムJa! Y si yo gano, ムtienes que parar de decir eso!

[msg MSG_006 [Mitsuru]]
Dios mボo... Su estupidez me supera...
Sin embargo, a este ritmo, imagino que superaremos esta criba sin demasiados problemas. Sigamos asボ.

[msg MSG_007 [P3 Fem Protag]]
ムCierto!

