[msg MSG_000 [P3 Fem Protag]]
斡Buena suerte, chicos! 斡Ese es uno[n]abajo!

[msg MSG_001 [Akihiko]]
Who was the winner that time? Tell us,.

[msg MSG_002 [P3 Fem Protag]]
Mmm... Es demasiado pronto para decirlo.[n]Es mejor de cuatro, despu姻s de todo.

[msg MSG_003 [Shinjiro]]
A la siguiente. Terminemos con esto.

[msg MSG_004 [Akihiko]]
Recuerda, Shinji, si Gan姻, est茨s[n]haciendo entrenamiento especial conmigo.

[msg MSG_005 [Shinjiro]]
Hah! 斡Y si gano, tienes que callarte!

[msg MSG_006 [Mitsuru]]
Dios m胤o... Su estupidez est茨 m茨s all茨[n]de m胤...
Sin embargo, a este ritmo, imagino que[n]pasaremos por esta prueba sin demasiados[n]problemas. Vamos a seguir.

[msg MSG_007 [P3 Fem Protag]]
斡Muy bien!

