[msg MSG_000 [Mitsuru]]
, parece que estホs encajando muy bien con los demホs.

[msg MSG_001 [P3 Fem Protag]]
*risita* Me siento casi como volver a casa.
No es difボcil llevarse bien con todos cuando actマan como siempre.

[msg MSG_002 [Akihiko]]
メOh? メEntonces no hay mucha diferencia entre nosotros y los de tu mundo?

[msg MSG_003 [P3 Fem Protag]]
ムEfectivamente! Mitsuru siempre es supermadura y confiable.
Shinjiro siempre es muy amable, a menudo se escapa para pasear a Koromaru y le hace comida.

[msg MSG_004 [Shinjiro]]
ムメEh...?!

[msg MSG_005 [P3 Fem Protag]]
Y siempre que salgo con Akihiko, se convierte en una especie de rutina de entrenamiento...
Asボ que acabo corriendo de vuelta a la residencia, llena de sudor.

[msg MSG_006 [Shinjiro]]
*suspiro* Joder, Aki, tambi〒n eres un grano en el culo en ese mundo...

[msg MSG_007 [Akihiko]]
ムメMe estホs llamando un grano en el culo?! Es importante que entrenes a diario.
Estoy seguro de que mi otro yo solo lo hace porque se preocupa por ti, [f 6 1 27 0 0 0].

[msg MSG_008 [P3 Fem Protag]]
メEh? Seguro... Ja, ja, ja...

[msg MSG_009 [Akihiko]]
Si puedes seguir mi rutina, entonces estホs en buena forma.
Muy bien, entonces, quizホs deberボamos de entrenar mホs tarde. Nos vamos a debilitar si holgazaneamos tanto.

[msg MSG_010 [Shinjiro]]
Eso es lo que te decボa. No tienes que escuchar lo que dice Aki si no quieres.

[msg MSG_011 [P3 Fem Protag]]
ムOh, no! ムNo es que no lo quiera hacer!
ムDe todos modos, sentボa la necesidad de moverme por ahボ!

[msg MSG_012 [Akihiko]]
メVes? メLo has oボdo?

[msg MSG_013 [Shinjiro]]
Tch... Si dejas la rutina de Aki, quien sabe lo que terminarホ haci〒ndote.
... Ey. Si estホs pensando en entrenar, hホzmelo saber.

[msg MSG_014 [Akihiko]]
ムメVas a entrenar conmigo finalmente, Shinji?!
Je, muy bien... ムIr〒 con una rutina increボble!

[msg MSG_015 [Shinjiro]]
Eso no es lo que estoy diciendo, tonto del culo.

[msg MSG_016 [Mitsuru]]
Ugh... Francamente, me preocuparボa dejar a [f 6 1 26 0 0 0] justo con ustedes dos.
Ambos deberボas controlar sus temperamentos. メEntendido?

[msg MSG_017]
Una nueva proyecciポn especial: "Confianza Trascendental" ha sido aワadida a la taquilla.

