[msg MSG_000 [Elizabeth]]
Esta prueba especial le exigir茨 cazar un[n]n雨mero espec胤fico de objetivos.
Aunque tambi姻n podr胤as recurrir a[n]eliminar cualquier cosa y todo lo que[n]viene a tu manera...
ひまぺ ぼゎぺゅ れまぺ れゎ ぽまぼもれもカょデ ぽまほま ぽまゆよれろるぺる ゎょぺ[n]まゑらまるもまょぼもぺ まゆよぼもよょぺょろまデ まれぼぺゅよみるもぺょろま を[n]ぼよゆらゅまろぺテ ィはよる みぺわよるデ もょろイょろぺゅよ!
... Ah胤 lo tienes, un candidato seguro[n]para la buena pel胤cula del a隠o.
Sus objetivos esta vez son los Rampage[n]Drives encontrados en "A.I.G.I.S."
Quiero que derrotes cuatro de ellos.

[msg MSG_001 [Akihiko]]
Suena bien. 斡Tengo ganas de pelear!

[msg MSG_002 [P3 Fem Protag]]
斡Muy bien! 斡Se trata de hacer el primer[n]movimiento!

[msg MSG_003 [Akihiko]]
Me gusta tu actitud, [f 6 1 27 0 0 0]! 斡Vamos a[n]golpearlos muertos!

[msg MSG_004 [Shinjiro]]
Ser茨 mejor que no vayan a esto sin un[n]plan.

[msg MSG_005 [Elizabeth]]
Marcar姻 las ubicaciones de estas Sombras[n]en tu mapa.
Buena suerte, todos.

