[msg MSG_000 [Elizabeth]]
Bienvenido a todos.
Parece que has tenido una caza exitosa.[n]Felicitaciones.
Esta es la recompensa por este tiempo.[n]Por favor, ac姻ptalo.

[msg MSG_001 [Mitsuru]]
Thanks for your help, [f 6 1 26 0 0 0].
Estoy seguro de que las versiones de[n]nosotros en tu mundo pueden descansar[n]f茨cil sabiendo que est茨s a cargo.

[msg MSG_002 [P3 Fem Protag]]
Hehe... Eso espero.
斡Ayuda cuando todo el mundo aqu胤 es tan[n]solidario!

[msg MSG_003 [Akihiko]]
Todo lo que puedo hacer es entrenar y[n]seguir luchando... A雨n as胤, har姻 todo lo[n]posible para ayudar.
Y, Shinji, no te forzar姻, pero si alguna[n]vez te interesa entrenar, av胤same, 斡y[n]nos har姻 una rutina!

[msg MSG_004 [Shinjiro]]
S胤, s胤. Cuando llegue el momento.

[msg MSG_005 [P3 Fem Protag]]
*giggle* 斡Contamos con ustedes!

