[msg MSG_000 [Junpei]]
ムメEh?! ムメHa cambiado la historia?!

[msg MSG_001 [Chie]]
No s〒 por qu〒 pregunto esto, pero... メCポmo acaba la historia?

[msg MSG_002 [Yukiko]]
La marioneta le enseワa los fundamentos de cocinar a la niワa, y esta se convierte en una chef profesional.
Despu〒s, las dos montan un pequeワo restaurante en la ciudad y viven felices para siempre.

[msg MSG_003 [Junpei]]
ムメFelices?! ムメPor qu〒 felices?!

[msg MSG_004 [Yukari]]
*suspiro* Esto es agotador.
Y, Junpei, メpodrボas dejar de contar historias estマpidas? Nos estホs haciendo perder el tiempo.

[msg MSG_005 [Junpei]]
ムメQu〒?! ムPero si me han callado justo antes de que pudiera llegar a la mejor parte!

[msg MSG_006 [Yukiko]]
Y ahボ lo tienen, amigos. Sintonicen la semana que viene para otro emocionante episodio de "Yukiko, Cr〒elo o No".

[msg MSG_007 [Chie]]
メEh? メOtro episodio?

[msg MSG_008 [Makoto]]
*suspiro* Vamos, basta de chホchara. Pongホmonos de nuevo en marcha.

[msg MSG_009 [Makoto]]
ムEeek!

[msg MSG_010 [Junpei]]
メEh? メTe has asustado asボ como asボ?

[msg MSG_011 [Futaba]]
S〒 que es raro ver a Queen ser miedosa, pero no tenemos tiempo para quedarnos parados.
Ese sonido era o una sombra o un robot... Sea lo que sea, no es amistoso, asボ que estad en guardia.

[msg MSG_012 [Makoto]]
Y-ya s〒. Tenemos que mantenernos concentrados con los enemigos de nuestro alrededor.

[msg MSG_013 [Yukari]]
Ngh, serボa bueno si pudi〒ramos evitarlos... Supongo que serホ mejor que sigamos.

