[msg MSG_000 [Elizabeth]]
The objective of this special screening[n]is to deactivate A.I.G.I.S.'s new[n]security system and escape.
The technology found there certainly is[n]surprising―dare I say, out of this world[n]or perhaps O.M.G.
In light of this change in security, I'd[n]like you to investigate.

[msg MSG_001 [Junpei]]
Ohh, it sounds like it's time for part[n]two of "Junpei's Believe It, or Don't"!

[msg MSG_002 [Yukari]]
Wha―? Don't do that!
I'm serious! You better not!

[msg MSG_003 [Junpei]]
Hey, hey, I gotcha! I'll make sure the[n]mood's right and everything!

[msg MSG_004 [Yukari]]
You "got" nothing!

[msg MSG_005 [Makoto]]
I-It's okay. It may be creepy there, but[n]at least it's not too dark... right?

[sel SEL_006 top]
I'm here for you.
I've got a bad feeling...
Worst comes to worst, we fight.

[msg MSG_007 [Makoto]]
Thanks. I feel a lot safer hearing you[n]say that.

[msg MSG_008 [Makoto]]
S-Stop that. Nothing's going to happen!

[msg MSG_009 [Makoto]]
Hopefully, it's an enemy we can actually[n]hit...
Please don't let it be anything[n]non-corporeal...

[msg MSG_010 [Yukiko]]
*giggle* I can't wait to see what's in[n]store. Let's go.

[msg MSG_011 [Chie]]
Er... Yukiko's having fun.
Come to think of it, I don't wanna see[n]any G-words either, got it!?

[msg MSG_012 [Akihiko]]
What are you all so afraid of?
I dunno what kind of security system[n]they've got, but if any Shadows show up,[n]we beat 'em down. Simple as that.

[msg MSG_013 [Junpei]]
Well, we're not talkin' about Shadows,[n]but... they're kinda close, right?

[msg MSG_014 [Yukari]]
They're nowhere near close! Look, can we[n]just hurry and get this over with?

[msg MSG_015 [Makoto]]
Well, the security system's been[n]changed, so we'll need to proceed[n]carefully.
Watch your step out there,-kun.

