[msg MSG_000 [Yukiko]]
Oh, it looks like a dead end. All I see[n]here are those cheery flowers.

[msg MSG_001 [Makoto]]
Cheery? More like creepy... It's[n]definitely animated, though.
It evokes a different kind of disgust[n]than the other movie...

[sel SEL_002 top]
Other movie?
You mean A.I.G.I.S.?

[msg MSG_003 [Yukari]]
I think she means A.I.G.I.S.

[msg MSG_004 [Makoto]]
Yes, that's the one. I can't believe[n]that research facility sought to erase[n]everyone's individuality.

[msg MSG_005 [Makoto]]
Yes, that's the one. I can't believe[n]that research facility sought to erase[n]everyone's individuality.

[msg MSG_006 [Yukari]]
Yeah, I think I know what you mean...
It is kinda off-putting knowing there's[n]nothing but robots living there...

[msg MSG_007 [Yukiko]]
There could be more than just robots.[n]Maybe there's, you know... Those things[n]that start with a G...

[msg MSG_008 [Makoto]]
L-Let's not talk about those!

[msg MSG_009 [Junpei]]
Huh? Not a fan of scary stories, Queen?
Well, then, Junpei Iori's got just the[n]story for you...

[msg MSG_010 [Yukiko]]
Ooh, I wanna hear this.

[msg MSG_011 [Junpei]]
Oh? Interested?
Ahem... Good evening, ladies and[n]gentlemen, and welcome to "Junpei's[n]Believe It, or Don't"...

[msg MSG_012 [Yukari]]
Any more of that, and I'm going to slap[n]you.

[msg MSG_013 [Junpei]]
Y-Yo, don't gimme that evil stare,[n]Yuka-tan! It's even scarier than the[n]G-word!

[msg MSG_014 [Makoto]]
All right, this conversation is over! We[n]need to keep moving!

[msg MSG_015 [Junpei]]
Aww. Well, we can pick this up the next[n]time we're in A.I.G.I.S., or―

[msg MSG_016 [Yukari]]
Why don't you just tell it to yourself?[n]Let's go, everyone.

[msg MSG_017 [Junpei]]
Wait! Don't just leave me here!

[msg MSG_018]
A new special screening: "Investigate[n]A.I.G.I.S.!" has been added to the box[n]office.

