[msg MSG_000 [Yukari]]
Phew... Parece que pasamos por las[n]puertas de alguna manera.

[msg MSG_001 [Ryuji]]
Esos cambios de seguridad no[n]significaron nada para nosotros. Tenemos[n]esto, no hay problema.

[msg MSG_002 [Morgana]]
No te relajes todav胤a, Skull. Te vas a[n]poner nervioso si no prestas atenci吋n.

[msg MSG_003 [Makoto]]
Tengo que decir, sin embargo, que la[n]cantidad de m茨quinas junto con la falta[n]de gente es bastante inquietante...

[msg MSG_004 [Junpei]]
夷Oh? 夷Tienes miedo, Queen?

[msg MSG_005 [Makoto]]
斡N-no, por supuesto que no!
Adem茨s, no hay evidencia que apoye la[n]existencia de... Espadas G.

[msg MSG_006 [Makoto]]
夷Aaah?
Hola... 夷Has o胤do algo?

[sel SEL_007 top]
A G-word?
Es tu imaginaci吋n.
Hay algo ah胤...

[msg MSG_008 [Chie]]
斡No, no, no! 斡Para! 斡No quiero o胤rlo!

[msg MSG_009 [Makoto]]
斡C茨lmate! No hay manera...

[msg MSG_010 [P4 Hero]]
No, definitivamente escuchamos algo. No[n]estamos seguros de qu姻...

[msg MSG_011 [Chie]]
夷Podemos dejar de hablar de esto? 斡Las[n]palabras G no existen! 斡No hay manera!

[msg MSG_012 [Yukiko]]
Dicen que hablar as胤 atrae a fantasmas,[n]夷sabes?

[msg MSG_013 [Chie]]
斡Aaaah! 斡No lo digas! 斡No lo digas!

[msg MSG_014 [Yukiko]]
Tienes raz吋n. Es algo redondo, rojo.

[msg MSG_015 [Chie]]
斡Aaaaah! 斡Basta!

[msg MSG_016 [Teddie]]
Yuki, 夷c吋mo pudiste? 斡Soy un oso dulce y[n]peque隠o!

[msg MSG_017 [Yukiko]]
Es s吋lo Teddie. Lo siento. Teddie, no[n]pod胤a ver muy claramente...

