[msg MSG_000 [Elizabeth]]
El objetivo de esta pr吋xima proyecci吋n especial es muy simple.
Deben derrotar uno de los KNS-1000 que se encuentran en "A.I.G.I.S."

[msg MSG_001 [Fuuka]]
Entiendo que con "KNS-1000" te refieres al FOE de vigilancia, 夷verdad?

[msg MSG_002 [Aigis]]
Ya veo. De hecho, es un oponente problem茨tico. Sin embargo, poseo algunos datos de este enemigo.
Esta es una oportunidad perfecta para calibrar mis niveles de energ胤a.

[msg MSG_003 [P3 Hero]]
Aigis, 夷todav胤a necesitas algo de tiempo?

[msg MSG_004 [Aigis]]
Tonter胤as. Todos los sistemas funcionan correctamente.
Sin embargo, no fui dise隠ada para luchar en esas pel胤culas.
Para que cumplamos nuestras misiones, debo conseguir experiencia en combate.

[sel SEL_005 top]
夷Est茨s bien?
No te fuerces.

[msg MSG_006 [Aigis]]
Agradezco es sentimiento, [f 6 1 30 0 0 0].
Sin embargo, sigo siendo un arma antisombras. Mi deber es protegeros a todos.
Seguramente me esperan batallas m茨s dif胤ciles, y si quiero protegeros, tendr姻 que estar preparada.

[msg MSG_007 [Ann]]
Eso es... bastante guay.

[sel SEL_008 top]
Trabajaremos juntos.
No te encargues de todo t雨 sola.

[msg MSG_009 [Aigis]]
夷Trabajar... juntos?

[msg MSG_010 [P3 Hero]]
 tiene raz吋n, Aigis. Somos un equipo.
No tienes por qu姻 encargarte de todo t雨 sola. Trabajaremos juntos.

[msg MSG_011 [Aigis]]
斡Entendido! 斡Entonces, vayamos todos juntos a la proyecci吋n especial!

[msg MSG_012 [Aigis]]
夷Eso es un no? Esperaba poder ayudar...

[msg MSG_013 [P3 Hero]]
 tiene raz吋n, Aigis. No tienes que encargarte de todo t雨 sola.
Somos un equipo. Deber胤amos de trabajar todos juntos.

[msg MSG_014 [Aigis]]
Muchas gracias a ambos. 斡Hag茨moslo lo mejor posible!

[msg MSG_015 [P3 Hero]]
Okay, [f 6 1 30 0 0 0], salgamos cuando estemos listos.

