[msg MSG_000 [Fuuka]]
Ahora, por favor, dir胤janse al KNS-1000.

[msg MSG_001 [Aigis]]
斡Entendido! 斡Har姻 todo lo posible por destruir al objetivo!

[msg MSG_002 [Rise]]
Hay varios KNS-1000, pero parece que pueden escoger el que quieran.
Como siempre, eso te lo dejamos a ti, Joker.

[msg MSG_003 [Futaba]]
Parece que el mapa est茨 preparado para la proyecci吋n especial. Quiz茨s podamos recorrerlo si tenemos tiempo.
En cualquier caso, 斡no pierdan de vista el mapa y vigilad sus pasos!

