[msg MSG_000 [Elizabeth]]
El objetivo de esta prポxima proyecciポn especial es muy simple.
Deben derrotar uno de los KNS-1000 que se encuentran en "A.I.G.I.S."

[msg MSG_001 [Fuuka]]
Entiendo que con "KNS-1000" te refieres al FOE de vigilancia, メverdad?

[msg MSG_002 [Aigis]]
Ya veo. De hecho, es un oponente problemホtico. Sin embargo, poseo algunos datos de este enemigo.
Esta es una oportunidad perfecta para calibrar mis niveles de energボa.

[msg MSG_003 [P3 Hero]]
Aigis, メtodavボa necesitas algo de tiempo?

[msg MSG_004 [Aigis]]
Tonterボas. Todos los sistemas funcionan correctamente.
Sin embargo, no fui diseワada para luchar en esas pelボculas.
Para que cumplamos nuestras misiones, debo conseguir experiencia en combate.

[sel SEL_005 top]
メEstホs bien?
No te fuerces.

[msg MSG_006 [Aigis]]
Agradezco es sentimiento, [f 6 1 30 0 0 0].
Sin embargo, sigo siendo un arma antisombras. Mi deber es protegeros a todos.
Seguramente me esperan batallas mホs difボciles, y si quiero protegeros, tendr〒 que estar preparada.

[msg MSG_007 [Ann]]
Eso es... bastante guay.

[sel SEL_008 top]
Trabajaremos juntos.
No te encargues de todo tマ sola.

[msg MSG_009 [Aigis]]
メTrabajar... juntos?

[msg MSG_010 [P3 Hero]]
 tiene razポn, Aigis. Somos un equipo.
No tienes por qu〒 encargarte de todo tマ sola. Trabajaremos juntos.

[msg MSG_011 [Aigis]]
ムEntendido! ムEntonces, vayamos todos juntos a la proyecciポn especial!

[msg MSG_012 [Aigis]]
メEso es un no? Esperaba poder ayudar...

[msg MSG_013 [P3 Hero]]
 tiene razポn, Aigis. No tienes que encargarte de todo tマ sola.
Somos un equipo. Deberボamos de trabajar todos juntos.

[msg MSG_014 [Aigis]]
Muchas gracias a ambos. ムHagホmoslo lo mejor posible!

[msg MSG_015 [P3 Hero]]
Okay, [f 6 1 30 0 0 0], salgamos cuando estemos listos.

