[msg MSG_000 [Elizabeth]]
Esta pr吋xima prueba especial promete ser[n]una aventura bastante llena de acci吋n...
Es una b雨squeda de tesoros. 斡Tu tarea[n]ser茨 localizar el tesoro escondido[n]dentro de la selva!

[sel SEL_001 top]
夷Qu姻 m茨s es nuevo?
Eso es lo nuestro.
夷Tesoro oculto?

[msg MSG_002 [Morgana]]
S胤. Encontrar tesoro es la especialidad[n]de Ladrones Fantasma.
夷Qu姻 clase de tesoro es?

[msg MSG_003 [Elizabeth]]
Parece ser una especie de artefacto[n]preciado un investigador destinado a[n]ofrecer a su amante...
Esperando hacerlo cuando su[n]investigaci吋n estaba completa, lo[n]escondi吋 para su custodia.

[msg MSG_004 [Rise]]
... Lo que le pas吋 al investigador..

[msg MSG_005 [Elizabeth]]
Aqu胤 hay un mapa de la ubicaci吋n del[n]tesoro... 夷Oh? Parece que hay algo en la[n]espalda...
"Una vez que termine este trabajo,[n]finalmente se lo propongo"
"Esta obra es la pura encarnaci吋n de la[n]belleza y el alusi吋n. A ella le[n]encanta..."

[msg MSG_006 [Futaba]]
Supongo que tent吋 el destino...

[msg MSG_007 [Ann]]
夷As胤 que fue un regalo para su novia...?[n]Tengo curiosidad por lo que era.

[msg MSG_008 [Yukari]]
Dijo que era la encarnaci吋n de la[n]belleza. 夷Quiz茨 sea una joya?

[msg MSG_009 [Rise]]
斡Qu姻 rom茨ntico!

[msg MSG_010 [Junpei]]
Las chicas est茨n emocionadas por esto...

[msg MSG_011 [Teddie]]
Ooh! 斡Esto es!

[msg MSG_012 [Yosuke]]
夷Eh? 夷De qu姻 est茨s hablando?

[msg MSG_013 [Teddie]]
Quien encuentre el tesoro primero ser茨[n]coronado la mascota n雨mero uno!

[sel SEL_014 top]
夷Una mascota n雨mero uno?
夷Por qu姻?

[msg MSG_015 [Teddie]]
El deber de una mascota es hacer feliz a[n]las damas y proporcionar consuelo cuando[n]lo necesiten...
ねぺろゎるぺゅゆまょろまデ れも まょぼよょろるぺる まゅ ろまれよるよ めぺぼま[n]みまゅもん ぺ ろよぽよれデ まょろよょぼまれ まれ ゃゎれろよ りゎま まゅ りゎま ゅよ[n]まょぼゎまょろるぺ ぼよょれもむゎま まゅ ろウろゎゅよ!

[msg MSG_016 [Koromaru]]
Woof...

[msg MSG_017 [Aigis]]
Koromaru dice que no tiene idea de lo[n]que est茨s hablando.

[msg MSG_018 [Morgana]]
Lo dijiste. A nadie le importa tu tonto[n]concurso...

[msg MSG_019 [Teddie]]
夷Oho...? Bueno, si no hay competencia,[n]entonces supongo que gan姻 por defecto.
Y luego me pongo bonita Ann todo para m胤[n]mismo...

[msg MSG_020 [Morgana]]
斡Arrrgh! 夷D吋nde te vas?

[msg MSG_021 [Teddie]]
斡Si no te gusta, intenta quitarme el[n]t胤tulo!

[msg MSG_022 [Morgana]]
Maldici吋n... 斡Bien, lo har姻! Pero vamos[n]a tener una cosa clara...
斡No me importa tu est雨pido t胤tulo! S吋lo[n]estoy haciendo esto para hacer feliz a[n]Lady Ann!

[msg MSG_023 [Yukari]]
Se est茨 calentando bastante all胤. 夷Est茨n[n]bien?

[sel SEL_024 top]
Est茨n bien.
En realidad es conveniente.
Morgana va a ganar.

[msg MSG_025 [Futaba]]
Bueno, es una b雨squeda de tesoros. Es[n]bueno que todos est姻n motivados.

[msg MSG_026 [Morgana]]
...
Cierto. 斡No hay forma de perder a un oso[n]pervertido!

[msg MSG_027 [Haru]]
夷Y t雨, Koro?

[msg MSG_028 [Koromaru]]
斡斡Arf! Arf, 斡Arf!

[msg MSG_029 [Aigis]]
"El concurso es de poco inter姻s para m胤,[n]pero con gusto ayudar姻 a buscar el[n]tesoro..."
... As胤 dice Koromaru.

[msg MSG_030 [Teddie]]
斡Entonces eso lo resuelve! 斡Que empiece[n]el primer Mascot Match-up!
斡Que los hombres m茨s valientes, vengan!

[msg MSG_031 [Morgana]]
斡S胤!

[msg MSG_032 [Koromaru]]
斡Arf!

