[msg MSG_000 [Rise]]
Este camino se desv胤a un poco, pero definitivamente nos llevar茨 al tesoro.

[msg MSG_001 [Koromaru]]
斡Arf, arf!

[msg MSG_002 [Ann]]
斡夷Koro?! 夷Qu姻 ocurre?

[msg MSG_003 [Aigis]]
Parece que est茨 diciendo, "Huelo el tesoro. Seguidme".

[msg MSG_004 [Chie]]
夷Tesoro? Hmm... Definitivamente no huele como la carne...

[msg MSG_005 [Yosuke]]
夷Por qu姻 est茨s tan segura de que el tesoro sea carne? 夷D吋nde est茨 la belleza y/o encanto en eso?

[msg MSG_006 [Yusuke]]
Mmm, carne de un rico color rub胤 complementada con l胤neas de grasa blanca como la nieve... 斡Yo dir胤a que la carne tiene una belleza propia!

[msg MSG_007 [Teddie]]
Hmph, 斡eso no les gustar茨 a las damas!
Crees que tienes todo resuelto, 夷eh? Pues bien, no eres rival para esta nariz de oso...
*sniff sniff* *sniff sniff* 斡夷Hrmmm?!

[sel SEL_008 top]
No me digas que...
夷Tesoro?

[msg MSG_009 [Teddie]]
Esta tentadora sensaci吋n cosquilleando mis Teddie-sentidos... 斡Tiene que ser un tesoro!
Y no estoy hablando de una o dos m胤seras piezas. 斡Estoy hablando de todo un tesoro!

[msg MSG_010 [Ryuji]]
Oye, parece que esos dos est茨n a punto de darte una lecci吋n. 夷Vas a estar bien?
... 夷Mona? Ey...

[msg MSG_011 [Morgana]]
Miauuuuu... Tesooooooro...

[msg MSG_012 [Ryuji]]
斡No, tu tambi姻n!

[msg MSG_013 [Yusuke]]
El tesoro es esencialmente su menta gatuna.

[msg MSG_014 [Ann]]
Bueno, no es lo mismo que el Tesoro en un Palacio, pero supongo que se puso un poco nerviosa por Teddie y Koro...

[msg MSG_015 [Futaba]]
Este camino es m茨s largo, pero parece que hay tesoros por el camino.
夷Qu姻 piensas, Joker?

[sel SEL_016 top]
Sigamos por aqu胤.
Confiar姻 en mis instintos.
El camino corto es mejor.

[msg MSG_017 [Ryuji]]
S胤, no podemos darnos la vuelta ahora que sabemos d吋nde est茨 el tesoro.

[msg MSG_018 [Ann]]
Entonces, 斡a por 姻l!

[msg MSG_019 [Ryuji]]
斡Claro que s胤! No ser胤amos ladrones fantasmas si dej茨ramos pasar un tesoro que tenemos delante.

[msg MSG_020 [Ann]]
斡S胤! 斡El tesoro es nuestro!

[msg MSG_021 [Ryuji]]
夷Qu姻? 夷No vamos a por el tesoro?
Oh, bueno, t雨 eres el l胤der.

[msg MSG_022 [Ann]]
Entonces, 夷quieres volver?

