[msg MSG_000 [Morgana]]
Aquボ es...

[msg MSG_001 [Ann]]
Aunque la verdad es que no veo nada aquボ...

[msg MSG_002 [Futaba]]
Sボ. Tampoco ayuda que no sepamos cポmo se ve el tesoro.
Quizホs, echen un vistazo por ahボ. Deberボa haber algo que encaje.

[msg MSG_003 [Yukari]]
No creo que nada de esto encaje...

[msg MSG_004 [Junpei]]
Cierto... Es solo un montポn de plantas...

[msg MSG_005 [Teddie]]
ムWOOOAH! ムAquボ estホ! ムEs aquボ! ムY lo he encontrado yo primero!

[msg MSG_006 [Morgana]]
ムメQu〒?!

[msg MSG_007 [Teddie]]
ムSボ, aquボ estホ! ムEs precioso, seductor, y serボa un regalo perfecto!
Aquボ tienen, seワoritas. ムDe mボ para ustedes!

[msg MSG_008 [Ann]]
Um... Yo no llamarボa a esto hermoso...

[msg MSG_009 [Yukari]]
Lo siento, pero... Sボ, de ninguna forma.

[msg MSG_010 [Yukiko]]
Deja eso donde lo encontraste ahora mismo, Teddie.

[msg MSG_011 [Teddie]]
ムメQu〒?! メQu〒 le podrボa ocurrir a este perfecto escarabajo rinoceronte dorado?!

[sel SEL_012 top]
Los bichos no son buenos.
Me lo llevo.
Creo que solo te gusta a ti.

[msg MSG_013 [Mitsuru]]
La mayorボa de las personas, tanto hombres como mujeres, comparten el desprecio por los insectos.
El sentido comマn dicta que no son los regalos mホs adecuados.

[msg MSG_014 [Yusuke]]
Concuerdo. Una criatura de este tamaワo y color es absolutamente extraordinaria.

[msg MSG_015 [Mitsuru]]
Cierto, pero el sentido comマn dicta que no son los regalos mホs adecuados.

[msg MSG_016 [Mitsuru]]
Cierto. Puede que lo veas como un buen regalo, pero no mucha gente estarボa contenta de recibir esto.

[msg MSG_017 [Yosuke]]
Definitivamente no es lo que estamos buscando.

[msg MSG_018 [Teddie]]
Nooo...No puede ser...

[msg MSG_019 [Morgana]]
ムLo encontr〒!
Algo tan bello y colorido como esto seguro que se gana el corazポn de cualquier chica.
Y no solo eso, sino que, ademホs, es comestible. Es un regalo que...

[msg MSG_020 [Futaba]]
Sボ, sボ, ens〒ワanoslo ya.

[msg MSG_021 [Morgana]]
Deleiten sus ojos con... ムEsto!

[msg MSG_021_02 [Morgana]]
Tengo un buen ojo para la belleza, メno creen?

[sel SEL_022 top]
メEso es bonito?
Parece venenoso.
Devu〒lvelo.

[msg MSG_023 [Morgana]]
ムClaro que es bonito! ムメCierto, seワoritas?!

[msg MSG_024 [Makoto]]
......

[msg MSG_025 [Haru]]
......

[msg MSG_026 [Futaba]]
Sボ, ese color me grita "peligroso".

[msg MSG_027 [Fuuka]]
Una vez vi a una rana parecida en un libro. Creo que era extremadamente venenosa...

[msg MSG_028 [Morgana]]
ムP-Pero esto no es una rana venenosa!

[msg MSG_029 [Morgana]]
ムメPor qu〒?!

[msg MSG_030 [Naoto]]
Ese color... Por alguna razポn, me da mala espina...

[msg MSG_031 [Yukari]]
... Asqueroso.

[msg MSG_032 [Morgana]]
ムメNi siquiera se ve bonito?!

[msg MSG_033 [Aigis]]
Escaneo completado. Detecto compuestos tポxicos en una concentraciポn muy superior al umbral letal.

[msg MSG_034 [Morgana]]
ムUrrrrrrgh...!

[msg MSG_035 [Ann]]
Nunca vamos a encontrar esta cosa...

[msg MSG_036 [Koromaru]]
ムGuau, guau!

[msg MSG_037 [Chie]]
メHm? メHay algo en los arbustos?

[msg MSG_038 [Koromaru]]
Awooo.

[msg MSG_039 [Yusuke]]
Oho... Ahora, esto es hermoso...

[msg MSG_040 [Haru]]
Oh, y huele de maravilla...

[msg MSG_041 [Fuuka]]
Nunca antes habボa visto este tipo de flor. Puede que incluso sea una nueva especie.

[msg MSG_042 [Teddie]]
P-P-Pero si solo es una flor. Eso no cuenta como un tesoro...

[msg MSG_043 [Morgana]]
S-Sボ, es verdad. Puede que no sea eso...

[msg MSG_044 [Yosuke]]
Lo dicen los que trajeron un bicho y una fruta venenosa...

[msg MSG_045 [Naoto]]
メHm? Aquボ hay algo enterrado.
Es una especie de placa; parece que hay algo grabado en ella...
"Te ofrezco esta flor, mi amor."

[msg MSG_046 [Mitsuru]]
Ya veo. Asボ que el investigador puso todos sus sentimientos en esta マnica flor.
No hay duda de que este es el tesoro que dejポ.

[sel SEL_047 top]
Supongo que ya tenemos nuestro ganador.
Bien hecho, Koromaru.

[msg MSG_048 [Koromaru]]
ムAwooo!

[msg MSG_049 [Teddie]]
ムGrraaaaahhh...!

[msg MSG_050 [Morgana]]
ムMiauuuuu...!

[msg MSG_051 [Futaba]]
Vale, olvボdense de esos dos llorones...
ムVolved todos!

