[msg MSG_000 [Teddie]]
ムTesoro, tesoro[f 0 1 1]!

[msg MSG_001 [Koromaru]]
ムWoof! ムWoof!

[msg MSG_002 [Ann]]
Era realmente un tesoro escondido. Menos mal que vinimos por aquボ.

[msg MSG_003 [Morgana]]
メVen? Esto no hubiera ocurrido si hubi〒ramos tomado el camino corto.

[msg MSG_004 [Teddie]]
Ngh...
ムP-Pero encontramos el tesoro gracias a mi nariz!
ムNo soy un gato que empieza a babear a la primera seワal de tesoro!

[msg MSG_005 [Morgana]]
ムNo estaba babeando! Mejor cホllate tマ... Tマ...

[sel SEL_006 top]
Dejad de pelear.
Todos lo hicieron bien.
Di algo, Panther.

[msg MSG_007 [Ann]]
Sボ. Estamos aquボ porque trabajamos juntos.
Ademホs, no hay tiempo para pelear. ムAマn no hemos encontrado el gran premio!

[msg MSG_008 [Ann]]
Tienes razポn. Estamos aquボ porque trabajamos juntos.
ムSigamos asボ y vayamos a por el gran premio!

[msg MSG_009 [Ann]]
メYo...?
Eh... ムBuen trabajo, chicos! No podrボamos haber llegado tan lejos sin ustedes.

[msg MSG_010 [Morgana]]
Bueno, si dices eso, seワorita Ann...

[msg MSG_011 [Teddie]]
Escuche, escuche. Yo tampoco puedo molestar a una dama tan encantadora.

[msg MSG_012 [Yosuke]]
Okay, vamos a por el gran premio.

[msg MSG_013 [Yukari]]
メAlguna idea de lo que puede ser?
Nada de lo que hemos encontrado hasta ahora ha sido especialmente bonito o seductor.

[msg MSG_014 [Junpei]]
Va a ser algo que le gustarボa a una chica, メverdad? Apuesto a que es...

[sel SEL_015 top]
Ropa.
Dulces.
Dinero.

[msg MSG_016 [Junpei]]
Sボ. Algo muy elegante con volantes o cintas o lo que sea. A las chicas les encanta eso.

[msg MSG_017 [Yukari]]
Eh, creo que quieres decir que a TI te encantan.
Ademホs, メpor qu〒 se tomarボa la molestia de esconder algo asボ en la selva?

[msg MSG_018 [Ann]]
Bueno, me gustan los dulces, pero...

[msg MSG_019 [Yosuke]]
Nah, メqui〒n esconderボa algo asボ en la jungla?

[msg MSG_020 [Yukari]]
Bueno, supongo que es mejor dejar que se compre algo que le guste a que regalarle algo sin pensarlo mucho...

[msg MSG_021 [Junpei]]
Sボ, muy romホntico...

[msg MSG_022 [Teddie]]
No, no, eso no servirホ.
Lo que mホs feliz harボa a una chica es, obviamente, un beso apasionado en...

[msg MSG_023 [Koromaru]]
ムBark, bark!

[msg MSG_024 [Teddie]]
ムメQu〒?!

[msg MSG_025 [Aigis]]
Dijo que si lo vuelves a hacer, serホs escoltado fuera de las instalaciones.

[msg MSG_026 [Rise]]
Es como conocer y saludar...

[msg MSG_027 [Morgana]]
Muy buena, Koromaru.
Deshagホmonos de este muワeco y encontremos ese tesoro.
ムYa casi estamos!

[msg MSG_028 [Koromaru]]
ムArf!

