[msg MSG_000 [Morgana]]
Esto es...

[msg MSG_001 [Ann]]
No veo nada aqu胤, pero...

[msg MSG_002 [Futaba]]
S胤. No ayuda que ni siquiera sepamos[n]c吋mo es el tesoro.
Tal vez echar un vistazo por ah胤. Debe[n]haber algo que se ajuste a la cuenta.

[msg MSG_003 [Yukari]]
No creo que esto se ajuste a ning雨n[n]proyecto de ley...

[msg MSG_004 [Junpei]]
Palabra... Son s吋lo un mont吋n de[n]plantas...

[msg MSG_005 [Teddie]]
斡WOOOAH! 斡Ah胤 est茨! 斡Est茨 aqu胤! 斡Y lo[n]encontr姻 primero!

[msg MSG_006 [Morgana]]
夷Qu姻?

[msg MSG_007 [Teddie]]
斡S胤, esto es! 斡Es hermoso, atractivo y[n]har胤a un gran regalo!
Aqu胤 est茨n, se隠oritas. 斡De m胤 a ti!

[msg MSG_008 [Ann]]
Um... No llamar胤a a esta hermosa...

[msg MSG_009 [Yukari]]
Lo siento, pero... S胤, de ninguna[n]manera.

[msg MSG_010 [Yukiko]]
Pon eso donde lo encontraste ahora[n]mismo, Teddie.

[msg MSG_011 [Teddie]]
Wh-夷Qu姻? What could possibly be wrong[n]with this perfectly fine golden[n]rhinoceros beetle?!

[sel SEL_012 top]
Los errores no son buenos.
Lo tomar姻.
Creo que s吋lo te gusta.

[msg MSG_013 [Mitsuru]]
La mayor胤a de las personas, hombres y[n]mujeres por igual, mantienen un[n]desprecio compartido por los insectos.
El sentido com雨n dicta que no son los[n]regalos m茨s adecuados.

[msg MSG_014 [Yusuke]]
Estoy de acuerdo. Una criatura de tama隠o[n]y color como este es absolutamente[n]notable.

[msg MSG_015 [Mitsuru]]
Claro, pero el sentido com雨n dicta que[n]no son los regalos m茨s adecuados.

[msg MSG_016 [Mitsuru]]
Cierto. Usted podr胤a verlo como un buen[n]regalo, pero no mucha gente estar胤a[n]feliz de recibir esto.

[msg MSG_017 [Yosuke]]
Definitivamente no es lo que estamos[n]buscando.

[msg MSG_018 [Teddie]]
Nooo... No puede ser...

[msg MSG_019 [Morgana]]
斡Lo encontr姻!
Algo tan hermoso y tan colorido como[n]esto es seguro ganar el coraz吋n de[n]cualquier chica.
No s吋lo eso, pero, como un bono a隠adido,[n]tambi姻n es comestible. Es un regalo[n]que..

[msg MSG_020 [Futaba]]
S胤, s胤, ens姻隠anos ya.

[msg MSG_021 [Morgana]]
斡Saca tus ojos... esto!

[msg MSG_021_02 [Morgana]]
Tengo un buen ojo para la belleza, 夷no[n]crees?

[sel SEL_022 top]
夷Eso es hermoso?
Parece venenoso.
Devuelve eso.

[msg MSG_023 [Morgana]]
斡Por supuesto que es hermoso! 夷Verdad,[n]se隠oritas?

[msg MSG_024 [Makoto]]
...

[msg MSG_025 [Haru]]
...

[msg MSG_026 [Futaba]]
S胤, ese color me grita "peligroso".

[msg MSG_027 [Fuuka]]
Una vez vi una rana que parec胤a as胤 en[n]un libro. Creo que fue extremadamente[n]venenoso...

[msg MSG_028 [Morgana]]
斡Pero esto no es una rana venenosa!

[msg MSG_029 [Morgana]]
夷Por qu姻?

[msg MSG_030 [Naoto]]
Este color... Por alguna raz吋n, env胤a[n]shivers a mi columna...

[msg MSG_031 [Yukari]]
...Gross.

[msg MSG_032 [Morgana]]
夷Ni siquiera se ve bien?

[msg MSG_033 [Aigis]]
Esc茨ner completo. Detecto compuestos[n]t吋xicos en una concentraci吋n muy[n]superior al umbral letal.

[msg MSG_034 [Morgana]]
Urrrrrrgh...!

[msg MSG_035 [Ann]]
Nunca vamos a encontrar esta cosa...

[msg MSG_036 [Koromaru]]
斡Barco, corteza!

[msg MSG_037 [Chie]]
夷Hm? 夷Hay algo en los arbustos?

[msg MSG_038 [Koromaru]]
Awooo.

[msg MSG_039 [Yusuke]]
Esto es hermoso...

[msg MSG_040 [Haru]]
Y huele maravilloso...

[msg MSG_041 [Fuuka]]
Nunca hab胤a visto este tipo de flor[n]antes. Incluso podr胤a ser una nueva[n]especie.

[msg MSG_042 [Teddie]]
B-b-Pero es s吋lo una flor. Eso no cuenta[n]como un tesoro...

[msg MSG_043 [Morgana]]
S胤, es verdad. Puede que no sea eso...

[msg MSG_044 [Yosuke]]
Dice que los tipos que escogieron un[n]bicho y una fruta venenosa...

[msg MSG_045 [Naoto]]
夷Hm? Hay algo enterrado aqu胤.
Es una especie de placa; parece que hay[n]algo grabado en ella...
"Te ofrezco esta flor, mi amor."

[msg MSG_046 [Mitsuru]]
Ya veo. As胤 que el investigador puso[n]todos sus sentimientos en esta sola[n]flor.
No hay duda de que este es el tesoro que[n]dej吋 atr茨s.

[sel SEL_047 top]
Supongo que tenemos a nuestro ganador.
Bien hecho, Koromaru.

[msg MSG_048 [Koromaru]]
斡Awooo!

[msg MSG_049 [Teddie]]
斡Grraaaahhh...!

[msg MSG_050 [Morgana]]
Mrowwwww...!

[msg MSG_051 [Futaba]]
De acuerdo, no te preocupes por esos dos[n]llorones...
斡Vuelvan todos!

