[msg MSG_000 [Rise]]
Hmm...

[msg MSG_001 [Ann]]
What's wrong?

[msg MSG_002 [Rise]]
It looks like the road splits up ahead.
One path continues east and makes a big[n]loop to the north...

[msg MSG_003 [Fuuka]]
And the other path leads due north and[n]makes a smaller loop.
Based on our position, that would be the[n]shorter of the two paths.

[msg MSG_004 [Teddie]]
Shorter it is! Everyone follow me!

[msg MSG_005 [Morgana]]
Wait. The shortest path isn't always the[n]best option.
If experience has taught me anything,[n]it's that the easy path tends to be a[n]trap...

[msg MSG_006 [Teddie]]
Lecture, lecture, lecture... If this[n]were a complaining contest, you'd win[n]hands down.

[msg MSG_007 [Morgana]]
Who's complaining!?

[msg MSG_008 [Ann]]
Well, I think you could make a case for[n]either. Which path do you think we[n]should we take, Joker?

[sel SEL_009 top]
The shorter path.
The longer path.
We need more info.

[msg MSG_010 [Teddie]]
See? What'd I tell you!?

[msg MSG_011 [Morgana]]
I knew you'd understand, Joker!

[msg MSG_012 [Ann]]
Yeah, it'd be nice if we knew a little[n]more about what's waiting for us down[n]each path.

[msg MSG_013 [Koromaru]]
Bark, bark!

[msg MSG_014 [Yukari]]
Hm? What is it, Koromaru?

[msg MSG_015 [Aigis]]
He seems to be saying he can smell[n]something down each path.

[msg MSG_016 [Chie]]
Really? I don't smell anything.
And I'm pretty sure I could pick up the[n]smell of meat from anywhere within a[n]mile and a half of this place.

[msg MSG_017 [Yosuke]]
There goes the meat freak... Like that's[n]anything to be proud of.

[msg MSG_018 [Ken]]
Koromaru has a much better sense of[n]smell than us, so he might actually be[n]onto something.

[msg MSG_019 [Futaba]]
There's no real way to tell from here.[n]We'll have to get closer.
You'll wanna get as much info as you can[n]before you make a decision.

[msg MSG_020 [Teddie]]
I say we check out the shorter path[n]first!
Let's gooo!

