[msg MSG_000 [Elizabeth]]
... Sin embargo, el estポmago de [f 6 1 16 0 0] realmente no conoce lボmites.
Ciertamente, creo que su capacidad gastronポmica estホ muy por encima de la de los humanos corrientes.

[msg MSG_001 [Margaret]]
Me lo imagino. Tマ tambi〒n verホs que mi invitado tiene una habilidad asombrosa para ello.

[msg MSG_002 [Junpei]]
Vaya, saltan chispas. メEsas dos se estホn fulminando con la mirada?

[msg MSG_003 [Theodore]]
Bueno, empezポ inocentemente...
Estaban discutiendo las capacidades de sus respectivos invitados, [f 6 1 16 0 0] y [f 6 1 13 0 0 0]...
No se ponボan de acuerdo sobre qui〒n comボa mホs, y ahora se ha convertido en toda una discusiポn.

[msg MSG_004 [Yosuke]]
メCポmo ocurren estas cosas...?
Cielos. Si esos dos ni siquiera estホn aquボ, esto va a durar para siempre.

[sel SEL_005 top]
Vamos a llamarles.
ムEy, [f 6 1 16 0 0]!
ムEy, [f 6 1 13 0 0 0]!

[msg MSG_006 [P3 Hero]]
... Tengo un mal presentimiento.

[msg MSG_007 [P4 Hero]]
Sボ. Estoy empezando a pensar que necesitamos un plan de escape...

[msg MSG_008 [Margaret]]
Ah, estホn ahボ.

[msg MSG_009 [P3 Hero]]
... Muy tarde, supongo.

[msg MSG_010 [P4 Hero]]
Ah, vaya...

[msg MSG_011 [Elizabeth]]
Permボtanme que me explique. El hecho es, etc〒tera, etc〒tera, etc〒tera...
Nos gustarボa decidir el ganador entre ustedes dos de una vez por todas.

[msg MSG_012 [P3 Hero]]
Esto es con muy poca anticipaciポn...

[msg MSG_013 [Margaret]]
Las reglas son sencillas.
Su マnica tarea es comer todo lo que puedan en el tiempo asignado.

[sel SEL_014 top]
Suena bastante fホcil.
Oh, esto estarホ bien.
メComer qu〒?

[msg MSG_015 [Chie]]
Sボ, es como un concurso de comer todo lo que puedas. Pero, メqu〒 comida tenemos por aquボ?

[msg MSG_016 [Ann]]
Tマ no participas, メverdad?

[msg MSG_017 [Makoto]]
Por favor, no lo compliques mホs...
Ademホs, メtenemos tanta comida para ellos?

[msg MSG_018 [Haru]]
Tenemos un montポn de palomitas, pero no s〒 si son adecuadas para una competiciポn como esta...

[msg MSG_019 [P3 Hero]]
Ah, qu〒 pena. Y tampoco tenemos utensilios de cocina. Supongo que es imposible...

[msg MSG_020 [Hikari]]
Nosotros... podrボamos tener algunos utensilios.

[msg MSG_021 [P3 Hero]]
... Oh. Eso es... genial.

[msg MSG_022 [Hikari]]
Creo que vi algunos en el puesto de comida... Un momento...

[msg MSG_023 [Hikari]]
Esto es...

[msg MSG_024 [Chie]]
メUna bandeja cuadrada?

[msg MSG_025 [Fuuka]]
Oh... Esto es un colador para una freidora.

[msg MSG_026 [Chie]]
ムOh! ムPodemos freボr algunas cosas! ムHagamos pollo frito! ムO quizホs unas croquetas!

[msg MSG_027 [Shinjiro]]
No tendrボamos los ingredientes para eso. Todo lo que tenemos es un montポn de harina...

[sel SEL_028 top]
メDonuts?
メUdon?
メSoba?

[msg MSG_029 [Shinjiro]]
Sボ, eso servirホ.

[msg MSG_030 [Shinjiro]]
Eso no se frボe, genio. Y no tenemos sopa.
Supongo que podrボamos hacer donuts o algo asボ.

[msg MSG_031 [Chie]]
ムMe gusta! ムMe comer〒 todos los que puedan hacer!

[msg MSG_032 [Shinjiro]]
No podrホ ser. No estホ hecho con harina, y no se frボe.
Supongo que podrボamos hacer donuts o algo asボ.

[msg MSG_033 [Ann]]
ムDonuts...!

[msg MSG_034 [P4 Hero]]
ムメMasa frita y pesada?!

[msg MSG_035 [Elizabeth]]
Entonces estホ decidido. ムAquボ comienza la mayor competiciポn de comer donuts de todos los...!

[msg MSG_036 [Theodore]]
Um, Hermana... Perdポn por interrumpirte, pero...
Creo que la freidora necesita algunas piezas mホs para funcionar.

[msg MSG_037 [Elizabeth]]
...

[msg MSG_038 [Margaret]]
Entonces supongo que el veredicto tendrホ que esperar.

[msg MSG_039 [Elizabeth]]
Sボ... Nadie puede escapar de nuestro juicio final.

[msg MSG_040 [P3 Hero]]
メJuicio... final?

[msg MSG_041 [Elizabeth]]
メOh? Parece que otra proyecciポn especial ha sido aワadida.
El objetivo de esta misiポn es conseguir dos "Dispositivos Cognitivos" en A.I.G.I.S.

[msg MSG_042 [Theodore]]
ムAh! Eso es exactamente lo que necesitamos para arreglar la freidora.

[sel SEL_043 top]
Un poco demasiado perfecto...
Menuda coincidencia.

[msg MSG_044 [Margaret]]
Sボ... Muy casual, de hecho.

[msg MSG_045 [P4 Hero]]
...

[msg MSG_046 [Elizabeth]]
Esta tarea no solo les harホ ganar la recompensa estホndar...
ムGanarホn la oportunidad de comer todos los donuts que puedan!

[msg MSG_047 [Futaba]]
ムWhoa!

[msg MSG_048 [Yusuke]]
ムメTodos los que podamos comer?!

[msg MSG_049 [Elizabeth]]
Parece que sus esperanzas estホn puestas en ti.

[msg MSG_050 [P3 Hero]]
...

[msg MSG_051 [Elizabeth]]
Asボ que espero que todos acepten esta misiポn.

[msg MSG_052]
Una nueva proyecciポn especial: "Banquete de Comodボn" ha sido aワadida a la taquilla.

