[msg MSG_000 [P3 Hero]]
No parece que haya mucho por aquボ...

[msg MSG_001 [P4 Hero]]
Sボ, por aquボ tampoco.

[msg MSG_002 [Haru]]
Perdonadme, pero estaba pensando...
メDe verdad son tan comilones? Nunca lo hubiera imaginado...

[msg MSG_003 [P4 Hero]]
Sボ, no lo s〒. Nunca me he considerado como tal.

[msg MSG_004 [Yosuke]]
Hala, hala, hombre. Cualquiera que pueda terminar el Mega de ternera de Aiya es definitivamente algマn tipo de monstruo...
Esa cosa estホ cargada con muchボsima ternera, メverdad?

[msg MSG_005 [Yukiko]]
Los マnicos capaces de terminarlo son [f 6 1 13 0 0 0], o quizホs Chie.

[msg MSG_006 [P4 Hero]]
Eso sボ que era una batalla...

[msg MSG_007 [P3 Hero]]
Je.  Parece muy impresionante.

[msg MSG_008 [Junpei]]
Ey, ムmira qui〒n estホ hablando! Tマ tambi〒n comes como un animal, メverdad?

[msg MSG_009 [Yukari]]
Fideos extra en tu ramen, takoyaki para comer rホpido... Creo que tienes una buena reputaciポn en el centro comercial Paulownia.

[msg MSG_010 [Aigis]]
Su ingesta supera la capacidad estimada de su organismo, pero sus constantes vitales y su expresiポn no indican ninguna dificultad.

[msg MSG_011 [Ryuji]]
Esos dos son realmente increボbles... No me extraワa que el equipo azul est〒 encima de ellos.

[sel SEL_012 top]
Son invencibles.
Estoy a su nivel.

[msg MSG_013 [Ryuji]]
メEh? Pero si tマ tambi〒n puedes con el desafボo Big Bang, メno?

[msg MSG_014 [Yosuke]]
Espera, ムメtマ tambi〒n?!

[msg MSG_015 [Ryuji]]
Ahora que lo pienso, venciste el desafボo Big Bang.

[msg MSG_016 [Haru]]
Yo dirボa que hay que tener muchas agallas para terminar eso...

[msg MSG_017 [Kanji]]
Je. メAsボ que su lボder es igual?
Supongo que si quieres ser el jefe, tienes que comer toneladas de comida.

[msg MSG_018 [Yosuke]]
Vamos, no puede ser... Comer solo depende de lo grande que es tu estポmago, メverdad?

[sel SEL_019 top]
Hace falta coraje.
Hace falta conocimiento.
Hace falta destreza.
Hace falta gentileza.

[msg MSG_020 [P4 Hero]]
Cierto. Para comer bien, necesitas entender tus lボmites, saber controlar tu ritmo...
El valor de enfrentarse a una marea implacable de comida, y la diligencia de perseverar ante un reto colosal.

[msg MSG_021 [Aigis]]
Esas son las habilidades necesarias para ser un lボder.

[msg MSG_022 [Yosuke]]
Oh. Eh... vale. Perdポn.

[msg MSG_023 [P4 Hero]]
No te preocupes por eso. Vamos a encontrar las partes que necesitamos.

[msg MSG_024 [P3 Hero]]
Sボ. Sigamos movi〒ndonos.

[msg MSG_025 [Mitsuru]]
メAsボ que un apetito voraz es la clave del verdadero liderazgo? Fascinante...

[msg MSG_026 [Junpei]]
Eh, no s〒 si quieres usar a estos tipos como referencia...

