[msg MSG_000 [Elizabeth]]
...Sin embargo, [f 6 1 16 0 0] el est吋mago[n]realmente no sabe l胤mite.
Ciertamente, creo que su capacidad[n]gastron吋mica est茨 mucho m茨s all茨 de la[n]de los humanos comunes...

[msg MSG_001 [Margaret]]
Me pregunto. Encontrar茨s que mi invitado[n]tambi姻n tiene una habilidad increible.

[msg MSG_002 [Junpei]]
S胤, las chispas est茨n volando. 夷Esos dos[n]se miran?

[msg MSG_003 [Theodore]]
Bueno, empez吋 inocentemente lo[n]suficiente...
Estaban discutiendo las capacidades de[n]sus respectivos invitados [f 6 1 16 0 0] y[n][f 6 1 13 0 0 0] ...
No pod胤an estar de acuerdo en qui姻n era[n]el comedor m茨s voraz, y ahora se ha[n]convertido en un argumento.

[msg MSG_004 [Yosuke]]
夷C吋mo sucede esto?
Dios. Si esos dos ni siquiera est茨n[n]aqu胤, esto va a continuar para siempre.

[sel SEL_005 top]
Vamos a llamarlos.
Hey, [f 6 1 16 0 0]!
Hey, [f 6 1 13 0 0 0]!

[msg MSG_006 [P3 Hero]]
... Tengo un mal presentimiento sobre[n]esto.

[msg MSG_007 [P4 Hero]]
S胤. Estoy empezando a pensar que[n]necesitamos un plan de escape...

[msg MSG_008 [Margaret]]
Ah, ah胤 est茨s.

[msg MSG_009 [P3 Hero]]
... Demasiado tarde, supongo.

[msg MSG_010 [P4 Hero]]
Ah, geez...

[msg MSG_011 [Elizabeth]]
Perm胤tame explicarlo. El hecho es,[n]etc姻tera, etc姻tera, etc姻tera...
Nos gustar胤a decidir el ganador entre[n]ustedes dos de una vez por todas.

[msg MSG_012 [P3 Hero]]
Esto es muy corto aviso...

[msg MSG_013 [Margaret]]
Las reglas son simples.
Tu 雨nica tarea es comer tanto como[n]puedas dentro del tiempo asignado.

[sel SEL_014 top]
Suena f茨cil.
Esto ser茨 bueno.
Comer qu姻?

[msg MSG_015 [Chie]]
S胤, es como un concurso para comer.[n]夷Pero qu姻 comida tenemos aqu胤?

[msg MSG_016 [Ann]]
No te vas a unir, 夷verdad?

[msg MSG_017 [Makoto]]
Por favor, no compliques esto m茨s...
Adem茨s, 夷tenemos tanta comida para[n]comer?

[msg MSG_018 [Haru]]
Tenemos muchas palomitas de ma胤z, pero[n]no estoy seguro de que sea adecuado para[n]una competencia como esta...

[msg MSG_019 [P3 Hero]]
Qu姻 verguenza. Y tampoco tenemos[n]suministros para cocinar. Supongo que es[n]imposible..

[msg MSG_020 [Hikari]]
Podr胤amos tener algunos suministros de[n]cocina.

[msg MSG_021 [P3 Hero]]
... Eso es... genial.

[msg MSG_022 [Hikari]]
Creo que vi algo en el stand de[n]concesi吋n... Un momento...

[msg MSG_023 [Hikari]]
Esto es...

[msg MSG_024 [Chie]]
夷Una cosa de bandeja cuadrada?

[msg MSG_025 [Fuuka]]
Oh... Este es un asedio para una[n]freidora profunda.

[msg MSG_026 [Chie]]
斡Oh! 斡Podemos fre胤r algo profundo![n]斡Hagamos pollo frito! O tal vez incluso[n]algunas croquetas!

[msg MSG_027 [Shinjiro]]
No tendr胤amos los ingredientes para eso.[n]Todo lo que tenemos es una tonelada de[n]harina...

[sel SEL_028 top]
夷Donuts?
夷T雨on?
Soba?

[msg MSG_029 [Shinjiro]]
S胤, eso funcionar茨 bien.

[msg MSG_030 [Shinjiro]]
No fr胤es eso, genio. Y no tenemos sopa.
Supongo que podr胤amos hacer donuts o[n]algo as胤.

[msg MSG_031 [Chie]]
斡Me gusta eso! 斡Me comer姻 tanto como[n]ustedes!

[msg MSG_032 [Shinjiro]]
No est茨 pasando. No est茨 hecho con[n]harina, y no est茨 frito.
Supongo que podr胤amos hacer donuts o[n]algo as胤.

[msg MSG_033 [Ann]]
Donuts...!

[msg MSG_034 [P4 Hero]]
Fried, heavy dough?!

[msg MSG_035 [Elizabeth]]
Entonces se decide. Aqu胤 comienza la[n]mayor competencia de donut-comeraci吋n de[n]todos -

[msg MSG_036 [Theodore]]
Hermana... Me disculpo por interrumpir,[n]pero...
Creo que la freidora profunda necesita[n]m茨s partes antes de que funcione.

[msg MSG_037 [Elizabeth]]
...

[msg MSG_038 [Margaret]]
Entonces supongo que el veredicto tendr茨[n]que esperar.

[msg MSG_039 [Elizabeth]]
S胤... Ninguno puede escapar de nuestro[n]juicio final.

[msg MSG_040 [P3 Hero]]
Final... juicio?

[msg MSG_041 [Elizabeth]]
夷Oh? Parece que se ha a隠adido otra[n]prueba especial.
El objetivo de esta misi吋n es obtener[n]dos dispositivos cognitivos en[n]A.I.G.I.S.

[msg MSG_042 [Theodore]]
斡Ah! Eso es exactamente lo que[n]necesitamos para arreglar la freidora.

[sel SEL_043 top]
Un poco demasiado perfecto...
Qu姻 coincidencia.

[msg MSG_044 [Margaret]]
S胤... Muy fortuito.

[msg MSG_045 [P4 Hero]]
...

[msg MSG_046 [Elizabeth]]
Esta tarea no s吋lo te ganar茨 la[n]recompensa est茨ndar...
Ganar茨s la oportunidad de todos los[n]donuts que puedas comer!

[msg MSG_047 [Futaba]]
Whoa!

[msg MSG_048 [Yusuke]]
夷Todo lo que podemos comer?

[msg MSG_049 [Elizabeth]]
Parece que sus esperanzas est茨n contigo.

[msg MSG_050 [P3 Hero]]
...

[msg MSG_051 [Elizabeth]]
As胤 que espero que acepten esta misi吋n.

[msg MSG_052]
Una nueva proyecci吋n especial: "Wildcard[n]Buffet" se ha a隠adido a la taquilla.

