[msg MSG_000 [Elizabeth]]
Gracias por traer las partes. Aquボ tienen su recompensa.

[msg MSG_001 [Elizabeth]]
Como prometボ, tambi〒n pueden comer los donuts que desean...
 y [f 6 1 13 0 0 0], ムos concedo el privilegio de participar en el concurso de comida!

[msg MSG_002 [P3 Hero]]
No parece que tengamos el "privilegio" de rechazarlo.

[msg MSG_003 [P4 Hero]]
Sボ. Estoy preparando mi estポmago...

[msg MSG_004 [Theodore]]
Ahora, preparar〒 la freidora. Por favor, denme un momento.

[msg MSG_005 [Theodore]]
Gracias por esperar.
La freidora estホ reparada, y ahora estホ lista para producir muchボsimos donuts.

[msg MSG_006 [Shinjiro]]
メCポmo es que acab〒 en el equipo de cocina...?

[msg MSG_007 [Theodore]]
Mis disculpas, pero me temo que serボa demasiado para mボ solo.

[msg MSG_008 [Margaret]]
Permボtanme repasar las reglas. Su objetivo es simple.
El que consiga comer mホs donuts que su oponente dentro del tiempo lボmite serホ declarado vencedor.
メEstホn listos?

[msg MSG_009 [P4 Hero]]
He llegado tan lejos. Ya no hay marcha atrホs.
... Y si vamos a hacer esto, quiero enfrentarte en tu mejor momento.

[msg MSG_010 [P3 Hero]]
... Espero sobrevivir.

[msg MSG_011 [Elizabeth]]
Ahora... ムQue comience el desafボo del comodボn!

[msg MSG_012 [Kanji]]
ムCreemos en ti, Lボder!

[msg MSG_013 [Aigis]]
 , ムs〒 que puedes hacerlo!

[msg MSG_014 [Ann]]
ムBuena suerte a los dos!

[msg MSG_015 [Elizabeth]]
Un plato mホs de donuts, por favor.

[msg MSG_016 [Margaret]]
Otro mホs por aquボ tambi〒n. Dense prisa.

[msg MSG_017 [Haru]]
Los donuts estホn desapareciendo tan rホpidamente...

[msg MSG_018 [Shinjiro]]
ムAquボ estホn! ムCorran!

[msg MSG_019 [Kanji]]
ムLボder! ムEstホ caliente y reci〒n hecho! ムD〒jame soplar para que se enfrボe!

[msg MSG_020 [Aigis]]
ムEntonces usar〒 un ventilador de aire acondicionado...!

[msg MSG_021 [P4 Hero]]
...Hngh...

[msg MSG_022 [P3 Hero]]
...Gh...

[msg MSG_023 [Makoto]]
Ambos estホn comiendo mucho, pero parece que se estホ poniendo difボcil.

[sel SEL_024 top]
メTal vez algo de agua?
メTal vez cambiar de sabor?

[msg MSG_025 [Ryuji]]
Sボ, comer nada mホs que donuts te dejarボa la boca seca...

[msg MSG_026 [Akihiko]]
No. Si beben agua ahora, se expandirホn en su estポmago.
Por eso luchan contra las ganas de beber.

[msg MSG_027 [Makoto]]
Cierto... Deben de estar cansados de comer el mismo sabor todo el rato...

[msg MSG_028 [Rise]]
ムSi quieren aumentar su hambre, tal vez deberボan probar algo picante! ムTengo salsa superpicante!

[msg MSG_029 [Fuuka]]
Algマn tipo de ホcido ayudarボa a vaciar su estポmago, メverdad? メQu〒 tal un poco de vinagre?

[msg MSG_030 [Yosuke]]
ムメEstホs intentando matarlo?!

[msg MSG_031 [Margaret]]
Pase lo que pase, se les acaba el tiempo...

[msg MSG_032 [Elizabeth]]
3, 2, 1... ムSe acabポ el tiempo!
Empecemos el recuento.

[msg MSG_033 [Junpei]]
メQ-Qui〒n ha ganado...?

[msg MSG_034 [Yosuke]]
No se puede saber con solo mirar los platos...

[msg MSG_035 [Theodore]]
Ahora, declarar〒 el veredicto...
Parece que han comido exactamente la misma cantidad de donuts. Esta batalla concluye como un empate decisivo.

[msg MSG_036 [P4 Hero]]
...

[msg MSG_037 [P3 Hero]]
...

[msg MSG_038 [Kanji]]
Parece que gastaron toda su energボa...

[msg MSG_039 [Margaret]]
メUn partido igualado...? Bueno, me lo esperaba.

[msg MSG_040 [Elizabeth]]
Sボ. Me atrevo a decir que estoy bastante satisfecha.

[msg MSG_041 [Ryuji]]
Si sabボas que iba a ser un empate, メpor qu〒 hicieron que se enfrentaran?

[sel SEL_042 top]
メUn experimento?
Solo se aburrボan.

[msg MSG_043 [Margaret]]
ムYa lo creo! Querボamos probar el verdadero potencial de los Comodines.

[msg MSG_044 [Margaret]]
No hay necesidad de mentir. Solo querボamos poner a prueba el potencial de los comodines.

[msg MSG_045 [Elizabeth]]
Sボ. Ahora sabemos la verdad.

[msg MSG_046 [Junpei]]
メEso era todo lo que querボan? Chicos, creo que ya pueden quejarse...

[msg MSG_047 [P4 Hero]]
... No ha estado mal, [f 6 1 16 0 0].

[msg MSG_048 [P3 Hero]]
Lo mismo va para ti, [f 6 1 13 0 0 0].

[msg MSG_049 [Junpei]]
メQu〒 cojo...? ムMボralos ahora! ムTerminaron con una extraワa conexiポn de donuts!

[msg MSG_050 [P3 Hero]]
Me imaginaba que la gran competiciポn de comida iba a ser un rollo... pero fue divertida.
Creo que esto me ha permitido conocerte un poco mejor.

[msg MSG_051 [P4 Hero]]
Lo mismo digo. Estoy deseando trabajar contigo a partir de ahora.

[msg MSG_052 [Elizabeth]]
ムY asボ se contentan con compartir el primer puesto! Permボtanme recompensar sus esfuerzos con este trofeo.

[msg MSG_053 [Yosuke]]
メCuホndo hicieron esto...?

[msg MSG_054 [Ann]]
Bueno, al menos pudimos verlos competir. Ahora es nuestro turno, asボ que, ムa por los donuts!

[msg MSG_055 [Shinjiro]]
Oh, sobre eso.

[msg MSG_056 [Theodore]]
Hemos hecho que trabaje demasiado. Parece que la freidora se ha vuelto a romper.
Y esta vez, me temo que una simple sustituciポn de piezas no serホ suficiente.

[msg MSG_057 [Yusuke]]
メQu〒...? Mis donuts...

[msg MSG_058 [Shinjiro]]
... Relホjense. Har〒 un par de tandas de donuts cuando lleguemos a casa.

[msg MSG_059 [Teddie]]
ムEntonces hagamos nosotros tambi〒n una fiesta de donuts cuando volvamos!

[msg MSG_060 [P3 Hero]]
Creo que pasar〒 de los donuts por un tiempo...

[msg MSG_061 [P4 Hero]]
Qu〒 casualidad. Yo tambi〒n...

