[msg MSG_000 [Elizabeth]]
Por fin ha llegado el momento...
No solo podremos decidir el ganador, sino que tendremos una montaワa de donuts...
Es como matar ochenta pホjaros de un tiro.

[msg MSG_001 [Yukari]]
No estoy segura de la parte de la competiciポn, pero lo de comer todos los donuts que podamos suena genial.

[msg MSG_002 [Ann]]
Sボ. Aunque me preocupa que acabemos comiendo demasiado.

[msg MSG_003 [P4 Hero]]
......

[msg MSG_004 [P3 Hero]]
... Vamos.

[sel SEL_005 top]
Chicos, lo tienen difボcil.
Mis condolencias.

[msg MSG_006 [P3 Hero]]
Hemos llegado hasta aquボ y todo el mundo parece muy entusiasmado.

[msg MSG_007 [P4 Hero]]
Sボ. Asボ que hagホmoslo lo mejor que podamos.

[msg MSG_008 [Kanji]]
L-Lボder... ムTマ eres el mホs hombre!

