[msg MSG_000 [Koromaru]]
ムGuau!

[msg MSG_001 [P3 Fem Protag]]
Oh, メes esto lo que estホbamos buscando? Eh... メEsta cosa?

[msg MSG_002 [Junpei]]
ムメNo creen que es importante saber el nombre de lo que estamos buscando?!

[msg MSG_003 [Aigis]]
Se llama controlador de motor, y sボ, parece que esto es lo que estホbamos buscando.
No parece estar daワado. Todo lo que queda es llevar esto al robot y podemos comenzar las reparaciones.

[msg MSG_004 [Ken]]
ムQu〒 buenas noticias! ムVolvamos enseguida!

