[msg MSG_000 [Aigis]]
, メpuedo hablar contigo un momento?

[msg MSG_001 [P3 Fem Protag]]
メQu〒 ocurre, Aigis?

[msg MSG_002 [Aigis]]
*mira fijamente*

[msg MSG_003 [P3 Fem Protag]]
メQ-Qu〒 estホs haciendo?

[msg MSG_004 [Aigis]]
Este sentimiento... Lo sabボa. Eres igual que [f 6 1 15 0 0 0]

[msg MSG_005 [Koromaru]]
ムArf arf!

[msg MSG_006 [Aigis]]
Koromaru dice que 〒l tambi〒n siente algo de ti similar a [f 6 1 15 0 0 0].
メQu〒 podrボa ser...?

[sel SEL_007 top]
Ella lo acaricia de la misma forma.
Huele comida de perro en ella.
Es por las feromonas.

[msg MSG_008 [Koromaru]]
ムArf!

[msg MSG_009 [Aigis]]
Dice que disfruta mucho de sus caricias, pero que no es eso.

[msg MSG_010 [P3 Fem Protag]]
メEh? No tengo comida para perros... aunque antes sボ que tenボa.

[msg MSG_011 [Aigis]]
No, no creo que esa sea la respuesta.

[msg MSG_012 [P3 Fem Protag]]
ムメQu〒?! メEstoy emitiendo feromonas?

[msg MSG_013 [Aigis]]
No, no creo que esa sea la respuesta.

[msg MSG_014 [P3 Fem Protag]]
Hmm... メEntonces qu〒 ocurre?

[msg MSG_015 [Ken]]
Koromaru es muy amigable, incluso con los extraワos. Aun asボ, esto parece diferente...
Todo lo que puedo decir con seguridad es que Koromaru siente algo especial en ti, [f 6 1 27 0 0 0].

[msg MSG_016 [Koromaru]]
ムArf!

[msg MSG_017 [Aigis]]
Qu〒 peculiar... Esto es realmente un misterio.

[msg MSG_018]
Una nueva proyecciポn especial: "A Fated Crossover" ha sido aワadida a la taquilla.

