[msg MSG_000 [Elizabeth]]
Los objetivos han sido eliminados.
Una feroz batalla contra poderosos[n]tiranos... Podr胤as haber hecho historia[n]de cine.
Hay pocas cosas m茨s agradables que[n]enraizar a mi equipo con una boca llena[n]de palomitas.

[msg MSG_001 [Junpei]]
Me alegra que se divierta...

[msg MSG_002 [Elizabeth]]
Aqu胤 est茨 su recompensa por este tiempo.
Esto te permitir茨 convocar a la Persona[n]"Fenrir"
Con suerte, lo pondr茨s a buen uso.

[msg MSG_003 [Morgana]]
斡Muy bien, esto ayudar茨 mucho!

[msg MSG_004 [Yosuke]]
Creo que los MVP eran Ken y Futaba.
Esos eran unos oponentes locos, pero nos[n]mantuvieron en marcha.

[msg MSG_005 [Rise]]
S胤. Eran s雨per motivadores.
夷No ten胤as miedo, Ken? Esos[n]Tyranniqueens eran enormes.

[msg MSG_006 [Ken]]
Haha, necesitar茨 m茨s que eso para[n]asustar a Featherman.
Adem茨s, pens姻 que tal vez podr胤a recrear[n]esa famosa escena donde luchan contra el[n]monstruo gigante.

[msg MSG_007 [Rise]]
夷Escena famosa?

[msg MSG_008 [Futaba]]
Featherman Temporada 1, Episodio 13! 斡Un[n]episodio de m茨s dios a este d胤a!
Normalmente luchan como robots cuando un[n]enemigo crece todo grande...

[msg MSG_009 [Yosuke]]
S胤. Todos salen de su base y se[n]conectan, 夷verdad?

[msg MSG_010 [Ken]]
S胤, pero esta vez los robots estaban[n]bajo inspecci吋n, y no pod胤an usarlos.

[msg MSG_011 [Yosuke]]
Esa es una situaci吋n extra隠amente[n]realista para ese show...

[msg MSG_012 [Futaba]]
夷Y qu姻 hacen nuestros h姻roes?
斡Se juntan y derrotan al monstruo como[n]nosotros!

[msg MSG_013 [Ken]]
Con cada 雨ltima onza de su coraje,[n]corren hasta sus pies y hacen un ataque[n]especial!
斡Esa escena es genial! Me sentar胤a all胤[n]y lo mirar胤a una y otra vez.
Fue tan emocionante poder hacer algo[n]as胤.

[msg MSG_014 [Ann]]
No entiendo lo que est茨 pasando, pero[n]definitivamente suena genial.

[msg MSG_015 [Futaba]]
斡Si quieres, puedo prestarte el DVD![n]斡Hay muchos m茨s episodios que ver!

[sel SEL_016 top]
Tal vez la pr吋xima vez...
Por favor.

[msg MSG_017 [P3 Hero]]
Haha, te tomar姻 en eso. Podemos verlo[n]juntos, Ken.

[msg MSG_018 [P3 Hero]]
Hahaha, 夷est茨s saltando en el carro de[n]banda, Feather Joker?

[msg MSG_019 [P3 Hero]]
O sea, buen trabajo. Cuento con ustedes.

[msg MSG_020 [Ken]]
斡Por supuesto!

[msg MSG_021 [Futaba]]
斡S胤, d姻janoslo!

[msg MSG_022 [Kanji]]
Hola... 夷Crees que puedo entrar en eso?
Ser姻 Amarillo, el que le gusta el[n]curry...

[msg MSG_023 [Futaba]]
Whoa! 斡Es el monstruo del Skull! 斡Atr茨s,[n]demonio!

[msg MSG_024 [Ken]]
Una bestia persistente, 夷no? 斡Te[n]derrotaremos esta vez!

[msg MSG_025 [Kanji]]
斡Grrrahh! 斡Dije que quiero ser Amarillo!

