[msg MSG_000 [Junpei]]
Whoa... Ya puedo sentir a ese Tyranniqueen mirホndome.

[msg MSG_001 [Futaba]]
Nuestro objetivo son los Tyranniqueen. Dos de ellos, para ser exactos.
Todo el mundo tiene claro el objetivo aquボ, メverdad? ムEncontrar a esos enemigos y derribarlos! ムTan fホcil como contar 1-2-3!

[msg MSG_002 [Mitsuru]]
Una batalla contra un FOE sin trucos ni artimaワas... Suena bastante fホcil.

[msg MSG_003 [Futaba]]
ムVamos, vamos, Phoenix Rangers! ムPor la seguridad de Junessic Land!

