[msg MSG_000 [Elizabeth]]
Los objetivos han sido eliminados.
Una feroz batalla contra poderosos tiranos... Es muy posible que hayan hecho historia en el cine.
Ah, hay pocas cosas mホs agradables que animar a mi equipo con la boca llena de palomitas.

[msg MSG_001 [Junpei]]
Me alegro de que se est〒 divirtiendo...

[msg MSG_002 [Elizabeth]]
Aquボ estホ tu recompensa por esta vez.
Les permitirホ invocar la Persona "Fenrir."
Espero que le d〒 un buen uso.

[msg MSG_003 [Morgana]]
ムMuy bien, esto ayudarホ mucho!

[msg MSG_004 [Yosuke]]
Creo que esta vez los MVP fueron Ken y Futaba.
Eran rivales muy duros, pero nos mantuvieron en pie.

[msg MSG_005 [Rise]]
Ja, ja, sボ. Eran supermotivadores.
メNo tenボas miedo, Ken? Esos Tyranniqueens eran enormes.

[msg MSG_006 [Ken]]
Ja, ja, harホ falta mホs que eso para asustar a Featherman.
Ademホs, creo que podrボa recrear esa famosa escena donde luchan contra el monstruo gigante.

[msg MSG_007 [Rise]]
メFamosa escena?

[msg MSG_008 [Futaba]]
ムFeatherman Temporada 1, Episodio 13! ムUn episodio perfecto hasta el dボa de hoy!
Suelen luchar en forma de robots cuando un enemigo se hace grande...

[msg MSG_009 [Yosuke]]
Ah, sボ. Todos salen de su base y se conectan, メverdad?

[msg MSG_010 [Ken]]
Sボ, pero esta vez los robots estaban siendo revisados, asボ que no podボan usarlos.

[msg MSG_011 [Yosuke]]
Es una situaciポn extraワamente realista para ese programa...

[msg MSG_012 [Futaba]]
ムメY qu〒 hacen nuestros h〒roes?!
ムSe unen y derrotan al monstruo como nosotros hicimos!

[msg MSG_013 [Ken]]
ムCon todo su coraje, corren a sus pies y le hacen un ataque especial!
ムEsa escena es genial! Me sentarボa a verla una y otra vez.
Fue muy emocionante poder hacer algo asボ.

[msg MSG_014 [Ann]]
Yo... realmente no entiendo lo que estホ ocurriendo, pero suena guay.

[msg MSG_015 [Futaba]]
ムSi quieres, te puedo dejar el DVD! ムHay un montポn de episodios que ver!

[sel SEL_016 top]
Quizホs la prポxima vez...
Sボ, por favor.

[msg MSG_017 [P3 Hero]]
Ja, ja, te tomo la palabra. Podemos verlo juntos, Ken.

[msg MSG_018 [P3 Hero]]
Ja, ja, ja, メte estホs subiendo al carro, Feather Joker?

[msg MSG_019 [P3 Hero]]
De todos modos, buen trabajo. Cuento con ustedes.

[msg MSG_020 [Ken]]
ムPor supuesto!

[msg MSG_021 [Futaba]]
ムSボ, d〒janoslo a nosotros!

[msg MSG_022 [Kanji]]
E-Ey... メCrees que puedo entrar en eso?
Ser〒 Bマho Amarillo, ese al que gusta el curry...

[msg MSG_023 [Futaba]]
ムWhoa! ムEs la monstruosa gran calavera! ムAtrホs, demonio!

[msg MSG_024 [Ken]]
Bestia persistente, メverdad? ムEsta vez te derrotaremos!

[msg MSG_025 [Kanji]]
ムGrrrahh! ムDije que querボa ser Bマho Amarillo!

