[msg MSG_000 [Futaba]]
斡Tyranniqueen, justo delante! 斡Monstruo! 斡Se te acab吋 el tiempo!

[msg MSG_001 [Yosuke]]
Je, je, je, Oracle s胤 que est茨 desempe隠ando su papel.

[msg MSG_002 [Ken]]
斡Prep茨rate, Tyranniqueen! 斡No nos quedaremos de brazos cruzados mientras destrozas el lugar!

[msg MSG_003 [Yukari]]
Ja, ja, ja, parece que Ken tambi姻n. Esto se ha hecho muy divertido.

[msg MSG_004 [Ken]]
斡Feather Joker! 斡Danos la se隠al!

[sel SEL_005 top]
斡Hag茨moslo!
斡Es la hora del espect茨culo!
斡Cambio de plumas!

[msg MSG_006 [Junpei]]
Je, je, je, 斡lo est茨s sintiendo! 斡Muy bien!

[msg MSG_007 [Junpei]]
Vamos, ya est茨s disfrazado. Aqu胤 es donde dices, "斡Vamos!"

[msg MSG_008 [Futaba]]
斡Terminemos con esto, Joker! 斡A por 姻l!

