[msg MSG_000 [Elizabeth]]
Asボ que han conseguido desentraワar la verdad del complejo laberinto y han logrado volver a salvo.
Al igual que la palabra «GROW» les guio, el camino que siguieron fue el de la superaciポn personal.

[msg MSG_001 [Yosuke]]
Tenボa el presentimiento de que sacarボas ese tema.

[msg MSG_002 [P4 Hero]]
Je... Suena familiar.

[msg MSG_003 [Yukari]]
Aunque, es raro. Todo el laberinto realmente cambiポ de alguna forma.

[msg MSG_004 [P3 Hero]]
Quizホ tenga algマn significado oculto... o quizホ le est〒 dando demasiadas vueltas.

[msg MSG_005 [Teddie]]
ムEl corazポn de un laberinto puede cambiar! ムIgual que el corazポn de una bella doncella!

[msg MSG_006 [Rise]]
ムJa, ja, ja! Lo que tマ digas.

[msg MSG_007 [Shinjiro]]
メSigues por aquボ?

[msg MSG_008 [Akechi]]
Ja, ja, ja... Mira quien habla.
Perdポn, no querボa preocuparte. No tienes que sentirte obligado a hablarme.

[msg MSG_009 [Shinjiro]]
Nah, no es eso.
Parece que somos iguales, eso es todo. Es agradable hablar con otro tipo que no encaja.

[msg MSG_010 [Akechi]]
メTマ y yo...? メIguales?

[msg MSG_011 [Shinjiro]]
Ademホs, puedo decir que eres...

[msg MSG_012 [Akihiko]]
ムShinji, 〒chame una mano! ムTe conseguボ un guante, asボ que ayマdame a hacer algunos ejercicios!
ムEy, Shinji! メA dポnde has ido?

[msg MSG_013 [Akechi]]
Parece que te necesitan en otra parte. Vamos, no te preocupes por mボ.

[msg MSG_014 [Akechi]]
Sospecho... que no somos tan parecidos como crees.
He elegido mi propio camino. Me temo que eso es todo.

[msg MSG_015 [Shinjiro]]
...
Mira, no conozco tu vida, pero d〒jame decirte esto.
He hecho muchas cosas malas. Ojalホ pudiera deshacer algunas. Pero como no puedo, intento vivir sin arrepentimientos.
Eso es todo. Nos vemos.

[msg MSG_016 [Akechi]]
...
De verdad que lo siento... pero es que no lo entiendo.

[msg MSG_017 [Akechi]]
... "Arrepentimientos", en efecto.

