[msg MSG_000 [Teddie]]
ムHay dos dispositivos warp aquボ! メCuホl tomamos?

[msg MSG_001 [Naoto]]
Hmm... Esta es la primera bifurcaciポn en el camino que hemos encontrado.
Si nos equivocamos en este punto, podrボamos ralentizar considerablemente nuestros avances.

[msg MSG_002 [Junpei]]
Ehh, メy qu〒 hay de ese papel que nos encontramos? メQu〒 decボa?

[sel SEL_003 top]
GROWL.
GROW.
CROW.

[msg MSG_004 [Ann]]
No, era "GROW". Estoy segura de que no tenボa ninguna "L" extra.

[msg MSG_005 [Teddie]]
Pero una "L" harボa que fuera mホs rudo...

[msg MSG_006 [Ann]]
No gruワas, estoy bastante acostumbrada a corregir a la gente sobre las "L" y las "R"...

[msg MSG_007 [Teddie]]
ムGrrr... Rrrrgh... Grrrawr!
ムGrrAWK!
Ups... Me he torcido la lengua...

[msg MSG_008 [Yosuke]]
メRealmente tienes una lengua ahボ dentro...? Eso es nuevo para mボ.

[msg MSG_009 [Makoto]]
Asボ es, decボa "GROW". Significa crecer, como una planta haci〒ndose mホs grande. O una persona madurando, supongo.

[msg MSG_010 [Ryuji]]
Bro, メasボ es cポmo lo dices? Pens〒 que rimaba con "chow".

[msg MSG_011 [Makoto]]
Deberボas de prestar mホs atenciポn en ingl〒s... Si escucharas a la profesora, sabrボas cポmo se pronuncia.

[msg MSG_012 [Ryuji]]
Si, sボ...

[msg MSG_013 [Ann]]
No, era "GROW". Con una "G", no una "C".

[msg MSG_014 [Naoto]]
"CROW". Como el ave carroワera, supongo.

[msg MSG_015 [Rise]]
Crow, メeh? メEse no era el nombre en clave de Akechi?

[msg MSG_016 [Junpei]]
メCrow es un estudiante y un detective, eh? ムEspero que no se desplume del estr〒s!

[msg MSG_017 [Yukari]]
*suspiro* Hay que tener agallas decir semejantes tonterボas con tanto entusiasmo.

[msg MSG_018 [Shinjiro]]
Ey, メno te vas a unir a la conversaciポn?

[msg MSG_019 [Akechi]]
ムVaya, vaya, una charla con Aragaki! Esto es raro.
Aマn soy bastante nuevo en el grupo, y no se me da bien lidiar con multitudes, asボ que prefiero mantener mi distancia.

[msg MSG_020 [Shinjiro]]
メAh, sボ? Bueno, pues como quieras.

[msg MSG_021 [Akechi]]
メQu〒 hay de ti?
Siempre te veo caminar unos pasos por detrホs del grupo. メHay algマn motivo de ello?

[msg MSG_022 [Shinjiro]]
Bah... No tengo una buena razポn. Es solo algo que hago.

[msg MSG_023 [Akechi]]
Ja, ja, no querボa ofenderte. No tienes que contホrmelo si no quieres.

[msg MSG_024 [Akechi]]
Realmente se llevan bien, メverdad?
Cuando estoy en medio de ellos, es demasiado para mボ...

[msg MSG_025 [Shinjiro]]
...

[msg MSG_026 [Akechi]]
Bueno, supongo que me siento mホs cポmodo asボ.

[msg MSG_027 [Shinjiro]]
... Como ahora

[msg MSG_028 [Akechi]]
ムVaya! Parece que volvemos a movernos.
メEra "GROW"? Me pregunto cuホl serホ el camino correcto...

