[msg MSG_000 [Ryuji]]
Un club nocturno. 夷Alguna idea de donde deber胤amos buscar?

[msg MSG_001 [Yusuke]]
Yo no estoy muy familiarizado con esos sitios.
Por la conversaci吋n de antes, parece que [f 6 1 16 0 0] es un experto...

[msg MSG_002 [P3 Hero]]
No soy un experto... Solo voy a veces.

[msg MSG_003 [Shinjiro]]
夷Al Escapade en el Centro comercial Paulownia...?

[msg MSG_004 [Kanji]]
斡Oh! 斡Conozco ese sitio! 斡Fuimos all胤 durante nuestro viaje escolar!

[msg MSG_005 [Teddie]]
S胤, 斡nos lo pasamos muy bien!

[msg MSG_006 [Yosuke]]
Creo que ustedes se emborracharon solo con el ambiente...
夷As胤 que all胤 es donde t雨 y tus amigos pasan el rato, [f 6 1 15 0 0 0]?

[msg MSG_007 [P3 Hero]]
No, normalmente voy solo.

[msg MSG_008 [Kanji]]
H-Hala... Eres como un adulto...
夷Qu姻 demonios haces en las discotecas y bares si vas solo?

[sel SEL_009 top]
Hablar con los adultos.
Trabajar.
Escuchar las quejas de los borrachos.

[msg MSG_010 [P3 Hero]]
S胤. Conoces todo tipo de gente interesante que probablemente no conocer胤as de otra manera.
Como un monje...

[msg MSG_011 [P3 Hero]]
夷Trabajar, eh...? Es dif胤cil acorarse de todos los pedidos, 夷verdad?
Siempre hab胤a un monje pidi姻ndome que le llevara bebidas...

[msg MSG_012 [P3 Hero]]
Oyes cosas que normalmente no oir胤as.
Como un monje predicando, por ejemplo...

[msg MSG_013 [Junpei]]
斡夷Un monje?! 斡夷Conociste a un monje en un club nocturno?!

[msg MSG_014 [Ken]]
 nunca deja de sorprendernos...

[msg MSG_015 [Ryuji]]
Supongo que as胤 son las cosas con estos tipos...

[sel SEL_016 top]
夷Estos tipos?
夷De qu姻 est茨s hablando?

[msg MSG_017 [Ryuji]]
斡Siempre est茨s haciendo amigos! 斡Como esa doctora y la chica del shogi!

[msg MSG_018 [Teddie]]
斡夷Qu姻 has dicho?! 斡Cu姻ntame m茨s! 斡Por favor! 斡Tengo que saberlo!

[msg MSG_019 [P3 Hero]]
Mira, esto es divertido y todo, pero 夷podemos irnos?
Los clubes nocturnos suelen encontrarse en los rincones m茨s alejados de la ciudad o en lo m茨s profundo de ella.

[msg MSG_020 [Akihiko]]
 tiene raz吋n. Vamos.

