[msg MSG_000 [P3 Hero]]
Uf... Eso soluciona el problema.
Un club nocturno para sombras. No ves eso todos los d胤as.

[msg MSG_001 [Yosuke]]
Tuvimos que esforzarnos mucho porque ALGUIEN se apresur吋 y prob吋 cada truco est雨pido del libro para entrar...

[msg MSG_002 [Junpei]]
Perd吋n por eso... Supongo que fue muy inmaduro... Ser un adulto es m茨s dif胤cil de lo que pensaba.
Pero a雨n no me rindo. 斡Nos esperan muchos m茨s para胤sos para adultos en la ciudad que nunca duerme!

[msg MSG_002_1 [Teddie]]
斡Ese es el esp胤ritu, Junpei! 斡Me quedo contigo esta noche!

[msg MSG_003 [Fuuka]]
Umm...

[msg MSG_004 [Teddie]]
Perd吋n, Fuu, tendr茨s que dejar un mensaje. Nos dirigimos al para胤so...

[msg MSG_005 [Fuuka]]
Pero... Mitsuru...

[msg MSG_005_1 [Mitsuru]]
Todos ustedes van a asumir la responsabilidad por actuar tan imprudentemente.

[msg MSG_005_2 [Mitsuru]]
夷Quieren ser adultos? Bien, os llevar姻 al para胤so...

[msg MSG_006 [Futaba]]
Je, je, je. Oh, los chicos est茨n en problemas. Parece que os va a tocar a todos.

[msg MSG_007 [Yosuke]]
夷Qu姻? 斡Ey! 斡D姻jame fuera de esto!
斡Ey, Kanji! 斡Ens姻隠ale una lecci吋n a este oso tonto!

[msg MSG_008 [Kanji]]
斡S胤 se隠or!

[msg MSG_009 [Teddie]]
斡N-Noo! Mi edad adulta... 斡Se me escapa!

[msg MSG_010 [Junpei]]
Perd吋n, Teddie. Lo intentamos... Realmente lo intentamos...

[msg MSG_011 [P3 Hero]]
... Ja, ja. Bueno, al menos hemos acabado la proyecci吋n. Volvamos una vez que hayamos terminado de ser castigados.

