[msg MSG_000 [Yusuke]]
It doesn't look like there are any[n]nightclubs around here... I wonder if we[n]can get some kind of hint.

[msg MSG_001 [Ken]]
Elizabeth said only VIPs can get in, so[n]maybe the entrance is hidden.

[msg MSG_002 [Kanji]]
VIPs, huh...? Think we'll see any monks?

[msg MSG_003 [Junpei]]
As if, man...
The late night brings out sexy women[n]and...

[sel SEL_004 top]
Journalists.
Non-conformists.
Creeps.

[msg MSG_005 [Shinjiro]]
Huh... That where you get your intel?[n]Not bad...

[msg MSG_006 [Morgana]]
Oh, like Lala Escargot? She's quite a[n]character...

[msg MSG_007 [Akihiko]]
Escargot? Is she French?

[msg MSG_008 [Yosuke]]
I can only imagine...

[msg MSG_009 [Ryuji]]
Yeah, man. There's all kinds of weirdos[n]runnin' around at night.

[msg MSG_010 [Kanji]]
I guess the city's just as crazy as[n]people say...

[msg MSG_011 [P4 Hero]]
It can be... You just have to be[n]careful...

[msg MSG_012 [Ken]]
You must know a lot of people too,[n]Joker.

[msg MSG_013 [Morgana]]
As the leader of the Phantom Thieves,[n]it's his job to make connections.

[msg MSG_014 [Ryuji]]
Thanks to this guy, we're able to[n]strategize and get better weapons.

[msg MSG_015 [Ken]]
Even if you have a duty to fulfill,[n]walking the city at night...?
You must have a lot of guts to do[n]something like that.

[sel SEL_016 top]
It's scary at first.
It's exciting.
Things tend to work out.

[msg MSG_017 [Ryuji]]
I'm still iffy about that airsoft shop[n]guy...

[msg MSG_018 [Morgana]]
Yeah, some people can be pretty[n]intimidating.
But you guys are good now.

[msg MSG_019 [P3 Hero]]
They might seem scary in the beginning, but[n]you learn pretty quickly that there's more to[n]people than meets the eye.

[msg MSG_020 [P3 Hero]]
Yeah, it can be pretty exciting to learn[n]about a world so different from your[n]own.

[msg MSG_021 [P3 Hero]]
Yeah, sometimes. You just have to be[n]willing to take a chance.

[msg MSG_022 [Shinjiro]]
Man, you guys ain't scared of nothin'.

[msg MSG_023 [Koromaru]]
Woof, woof!

[msg MSG_024 [Ken]]
Something up ahead, Koromaru?

[msg MSG_025 [Junpei]]
Oh? Did he get a whiff of the nightclub?[n]Let's check it out!

