[msg MSG_000 [Elizabeth]]
Gracias a ti, Pude ver la vida nocturna[n]de la ciudad.
Aprecio tu trabajo duro. Aqu胤 est茨 tu[n]recompensa.

[msg MSG_001 [Junpei]]
Bueno, terminamos nuestra misi吋n, pero[n]parece que falta algo...

[msg MSG_002 [Teddie]]
Est茨bamos tan cerca de experimentar[n]finalmente la emoci吋n del mundo[n]adulto...
斡Pero uno de estos d胤as, podr姻 seguir[n]con nuestros dos maestros de la noche!

[msg MSG_003 [Yosuke]]
Pens姻 que era tu Maestro. 夷Lo est茨s[n]enga隠ando?

[msg MSG_004 [Teddie]]
斡Por supuesto que no! 斡El Maestro est茨[n]en otro nivel! 斡Es brillante como el[n]sol!
Pero esos dos son tan agitados como la[n]luz de las estrellas y la luz de la[n]luna. Tan misterioso...
斡Si pudiera ser tan genial!

[msg MSG_005 [Yosuke]]
Hablador liso, este...
Pero s胤, tienen algo sobre ellos.

[msg MSG_006 [Ken]]
es muy maduro para su edad, pero parece[n]que usted tambi姻n, [f 6 1 30 0 0 0].
Conoces a tanta gente y lugares que no.

[sel SEL_007 top]
En realidad no.
Puedo mostrarte las cuerdas.

[msg MSG_008 [Yusuke]]
Es dif胤cil creer que haya venido a Tokio[n]hace medio a隠o.
Ver a [f 6 1 30 0 0 0] me hace sentir que deber胤a[n]salir m茨s a menudo.

[msg MSG_009 [Ken]]
夷Eh? 夷En serio?

[msg MSG_010 [Ryuji]]
Ten cuidado. Mantenlo fuera demasiado[n]tarde, y ser茨s rodado por la polic胤a de[n]nuevo.

[msg MSG_011 [P3 Hero]]
*chuckle* You really are amazing,.

[msg MSG_012 [Junpei]]
Oye, ahora. Est茨s muy bien.
Estoy un poco celosa. Ni siquiera[n]Junpei, el Superdetective tiene[n]habilidades como ustedes.

[msg MSG_013 [P3 Hero]]
Veo...
Ten胤a la sensaci吋n de que me conectar胤a[n]contigo de alguna manera. Supongo que[n]ahora s姻 por qu姻.
Es bueno saber que tienes mi espalda.

[sel SEL_014 top]
Sentirse es mutuo.
Estamos juntos en esto.

[msg MSG_015 [P3 Hero]]
S胤. Vamos a seguir.

[msg MSG_016 [Teddie]]
Ohh! 斡Mira eso! 斡Una nueva amistad nace[n]entre los dos gurus de la vida nocturna!
斡Yo digo que todos salgamos y[n]celebremos!

[msg MSG_017 [Junpei]]
S胤, empecemos en el camino hacia la edad[n]adulta...

[msg MSG_018 [Mitsuru]]
夷Oh? 夷Vas a huir otra vez?

[msg MSG_019 [Makoto]]
夷No han aprendido su lecci吋n?

[msg MSG_020 [Junpei]]
Bueno... Nosotros...

[msg MSG_021 [Teddie]]
斡Ay雨danos!

[sel SEL_022 top]
...
夷Has o胤do algo?

[msg MSG_023 [P3 Hero]]
...

[msg MSG_024 [P3 Hero]]
No.

[msg MSG_025 [Teddie]]
斡Sheesh, la gente de la ciudad es tan[n]meeeaan!

