[msg MSG_000 [Elizabeth]]
Me gustarボa informarles de que se ha aワadido una nueva proyecciポn especial.
Aunque esta puede ser un poco sugerente para algunos...

[msg MSG_001 [Teddie]]
... ムメHm?! ムMi nariz dice que esto es algo... maduro[f 0 1 1]!

[msg MSG_002 [Elizabeth]]
Me gustarボa que localizaran un lugar secreto en Kamo City.
Allボ, hombres y mujeres festejan toda la noche. Se mueven y se pelean, entregホndose a sus deseos terrenales...

[msg MSG_003 [Yusuke]]
メSe mueven y pelean...?

[msg MSG_004 [Kanji]]
メUn lugar popular secreto?

[msg MSG_005 [Yosuke]]
Whoa, whoa... Eso parece peligroso.

[sel SEL_006 top]
メNo quieres ir?
Puedes quedarte aquボ.

[msg MSG_007 [Yosuke]]
No he dicho eso. En realidad, siento algo de curiosidad.

[msg MSG_008 [Kanji]]
Me pregunto por qu〒...

[msg MSG_009 [Yosuke]]
ムCホllate!

[msg MSG_010 [Akechi]]
Un lugar popular nocturno... Probablemente se refiera a...

[sel SEL_011 top]
メUn arcade?
Un club nocturno.
Unos baワos termales.

[msg MSG_012 [Yosuke]]
Bueno, los arcades SON un sitio para divertirse...

[msg MSG_013 [Naoto]]
Pero no son exactamente un lugar para adultos, メverdad?
Elizabeth se estホ refiriendo mホs bien a un club nocturno.

[msg MSG_014 [P4 Hero]]
メTe refieres a dポnde van los hombres a ponerse...?

[msg MSG_015 [Kanji]]
ムメPor qu〒 me miras a mボ?!

[msg MSG_016 [Naoto]]
No s〒 a qu〒 te refieres, pero Elizabeth se estホ refiriendo mホs bien a un club nocturno.

[msg MSG_017 [Elizabeth]]
Correcto.
Hay bastantes clubs nocturnos populares y exclusivos en Kamo City que solo son accesibles para la gente VIP.

[msg MSG_018 [Ann]]
Un club nocturno, メeh?

[msg MSG_019 [Makoto]]
No me gusta como suena eso.

[msg MSG_020 [P3 Hero]]
Oh, メno?

[msg MSG_021 [Yosuke]]
"Oh, メno?"... メEs que vas a clubs a menudo o algo asボ?

[msg MSG_022 [Teddie]]
*silbido* ムEres un chico malo! ムEntonces te dejamos esto a ti!

[sel SEL_023 top]
Contamos contigo.
Yo tambi〒n soy noctホmbulo.

[msg MSG_024 [Ryuji]]
メNo has estado yendo a ese club en Shinjuku...?

[msg MSG_025 [Ryuji]]
Es verdad. Sigues yendo a ese club en Shinjuku, メno?

[msg MSG_026 [Teddie]]
ムメQu〒?! ムTenemos aquボ  a otro chico malo!

[msg MSG_027 [Junpei]]
Bueno, parece que tenemos aquボ a una pareja de veteranos. Parece un trabajo para nosotros, chicos.

[msg MSG_028 [Ann]]
Uh... メLos chicos?

[msg MSG_029 [Junpei]]
Es demasiado peligroso que las chicas paseen por la ciudad de noche, メverdad?
Es mejor dejarnos tomar la iniciativa en esto.

[msg MSG_030 [Yukari]]
... メQu〒 estホs tramando, Junpei?

[msg MSG_031 [Junpei]]
N-Nada. Solo estoy intentando ser un caballero...

[msg MSG_032 [P3 Hero]]
No creo que sea peligroso...

[msg MSG_033 [Junpei]]
Vamos a un lugar para adultos, メcierto? Tal vez tengamos algo de "diversiポn adulta"...

[msg MSG_034 [Fuuka]]
メJunpei?

[msg MSG_035 [Junpei]]
ムOh, nada, nada! Solo digo que nos ocuparemos de ello.

[sel SEL_036 top]
Lo tenemos.
Pueden confiar en nosotros.

[msg MSG_038 [Mitsuru]]
Hm... Bueno, si insisten, supongo que podemos dejホrselo a ellos.

[msg MSG_039 [Yukari]]
メEstホs segura?

[msg MSG_040 [Mitsuru]]
Solo tienen que encontrar el club nocturno. メQu〒 es lo peor que podrボa pasar?

[msg MSG_041 [Junpei]]
ムBien dicho, Kirijo! ムMuy bien, a por ello!

[msg MSG_042 [Elizabeth]]
Genial. Ahora estホ en manos de los chicos malos.

