[msg MSG_000 [Yusuke]]
No parece que haya clubes nocturnos por aqu胤... Me pregunto si podemos conseguir alg雨n tipo de pista.

[msg MSG_001 [Ken]]
Elizabeth dijo que solo pod胤a entrar gente VIP, as胤 que quiz茨s la entrada est茨 oculta.

[msg MSG_002 [Kanji]]
夷VIP, eh? 夷Creen que hemos visto alg雨n monje?

[msg MSG_003 [Junpei]]
Como si as胤 fuera, bro...
La noche saca a relucir mujeres sexys y...

[sel SEL_004 top]
Periodistas.
Inconformistas.
Tipos espeluznantes.

[msg MSG_005 [Shinjiro]]
Eh... 夷De ah胤 sacas tu informaci吋n? No est茨 mal...

[msg MSG_006 [Morgana]]
Oh, 夷como Lala Escargot? Ella es todo un personaje...

[msg MSG_007 [Akihiko]]
夷Escargot? 夷Es francesa?

[msg MSG_008 [Yosuke]]
Me imagino...

[msg MSG_009 [Ryuji]]
S胤, bro. Hay todo tipo de bichos raros durante la noche.

[msg MSG_010 [Kanji]]
Supongo que la ciudad es tan loca como la gente dice...

[msg MSG_011 [P4 Hero]]
Puede ser... Solo tienes que tener cuidado...

[msg MSG_012 [Ken]]
Debes de conocer a un mont吋n de gente, Joker.

[msg MSG_013 [Morgana]]
Como l胤der de los Ladrones Fantasma, es su trabajo hacer contactos.

[msg MSG_014 [Ryuji]]
Gracias a este tipo, podemos elaborar estrategias y conseguir mejores armas.

[msg MSG_015 [Ken]]
Aunque tengas deberes que cumplir, 夷pasear por la ciudad por la noche...?
Debes tener muchas agallas para hacer algo como eso.

[sel SEL_016 top]
Al principio da miedo.
Es emocionante.
Las cosas tienden a funcionar.

[msg MSG_017 [Ryuji]]
Sigo dudando de ese tipo de la tienda de airsoft...

[msg MSG_018 [Morgana]]
S胤, alguna gente puede ser muy intimidante.
Pero ustedes est茨n bien ahora.

[msg MSG_019 [P3 Hero]]
Pueden parecer aterrador al principio, pero aprendes bastante r茨pido que hay m茨s en las personas de lo que parece a simple vista.

[msg MSG_020 [P3 Hero]]
S胤, puede ser muy emocionante conocer un mundo tan diferente al tuyo.

[msg MSG_021 [P3 Hero]]
S胤, a veces. Solo tienes que estar dispuesto a correr el riesgo.

[msg MSG_022 [Shinjiro]]
Bro, ustedes no tienen miedo de nada.

[msg MSG_023 [Koromaru]]
斡Woof, woof!

[msg MSG_024 [Ken]]
夷Hay algo m茨s adelante, Koromaru?

[msg MSG_025 [Junpei]]
夷Oh? 夷Ha olido el club nocturno? 斡Vamos a comprobarlo!

