[msg MSG_000 [Ryuji]]
夷Ves esa se隠al? Hay una mierda de gente[n]aqu胤 tambi姻n.

[msg MSG_001 [Yusuke]]
Este lugar parece muy popular. Esto debe[n]ser todo.

[msg MSG_002 [P3 Hero]]
Bueno, Elizabeth dijo que todo lo que[n]necesit茨bamos era encontrar el lugar,[n]as胤 que parece que hemos terminado aqu胤.
Vamos..

[msg MSG_003 [Junpei]]
斡Espera! 夷Quieres irte a casa?
Llegamos tan lejos, y ni siquiera[n]quieres ver c吋mo es?!

[msg MSG_004 [Teddie]]
斡As胤 es! 斡A veces un oso tiene que[n]luchar por su derecho a la fiesta!
Y con eso... 斡Carga!

[msg MSG_005 [Junpei]]
斡Eso no es justo! 斡No te apresures solo!

[msg MSG_006 [Yosuke]]
斡Hola! 斡Chicos!

[msg MSG_007 [Teddie]]
No fue de utilidad... El guardia no me[n]dej吋 entrar...

[msg MSG_008 [Shinjiro]]
S吋lo es VIP. Probablemente necesitemos[n]alg雨n tipo de membres胤a o algo as胤.

[msg MSG_009 [Teddie]]
No... No es s吋lo VIP.

[msg MSG_010 [Yosuke]]
夷Eh? Entonces, 夷por qu姻 no pudiste[n]entrar?

[msg MSG_011 [Junpei]]
Los chicos no pueden entrar solos.
Seguridad dice que los chicos s吋lo[n]pueden entrar si tienen chicas con[n]ellos.

[msg MSG_012 [Teddie]]
Es un mundo duro para nosotros chicos[n]solitarios...

[msg MSG_013 [Junpei]]
斡No estoy sola! Maldici吋n... Si tuviera[n]mi dulce Chidorita...
Esto requiere medidas dr茨sticas. Si[n]pedimos ayuda a nuestras encantadoras[n]damas, estoy seguro de que..

[msg MSG_014 [Yukari]]
No.

[msg MSG_015 [Mitsuru]]
夷Nos vas a usar? Y te llamas un[n]caballero...

[msg MSG_016 [Junpei]]
Quiero convertirme en un adulto. D姻jame[n]ser uno...

[msg MSG_016_1 [Kanji]]
Puedes empezar por no ser tan beb姻...[n]Vamos, volvamos.

[msg MSG_016_2 [Teddie]]
斡Espera! 斡Tenemos profesionales con[n]nosotros! 斡Quiz茨 puedan ayudar!
斡Maestros de la noche! 斡Ens姻隠anos tus[n]caminos! 斡Por favor!

[msg MSG_017 [P3 Hero]]
夷Nuestras formas...?
夷Alguna idea de c吋mo podemos enga隠ar a[n]la seguridad?

[sel SEL_018 top]
夷Ropa cruzada?
夷Encontrar algunas chicas?
夷Un soborno?

[msg MSG_019 [Teddie]]
斡Ah! 斡Es una gran idea! 斡Si no hay[n]chicas, entonces me convertir姻 en una!
斡Estar胤as fuera de tu mente para no caer[n]por esta cara bonita m胤a!

[msg MSG_020 [Yosuke]]
No, no hay manera de que eso vaya a...

[msg MSG_021 [Kanji]]
Teddie se ha ido, amigo...

[msg MSG_022 [Teddie]]
斡S胤! 斡Hay una idea! 斡Vamos a hacer algo[n]bonito, bonito, pretties y bingo,[n]estamos dentro!

[msg MSG_023 [Yosuke]]
Como cualquier chica estar胤a de acuerdo[n]en venir con nosotros. Vamos a...

[msg MSG_024 [Kanji]]
Teddie se ha ido, amigo...

[msg MSG_025 [Teddie]]
Oh-hoh... 夷Un poco de acci吋n[n]insuficiente, dices? Realmente eres un[n]chico malo.

[msg MSG_026 [Yosuke]]
Bueno, 夷con qu姻 diablos se supone que[n]debemos sobornarlos?

[msg MSG_027 [Teddie]]
Puede que no tenga dinero dentro de m胤,[n]pero tengo caramelos.
斡Los traer姻 con una sorpresa de caramelo[n]medio comido!

[msg MSG_028 [Teddie]]
斡No funcion吋!

[msg MSG_029 [Junpei]]
斡Dah! 斡Pensaban que ibas a venir con[n]ellos!

[msg MSG_030 [Yosuke]]
斡Mierda, tenemos compa隠胤a!

[msg MSG_031 [P3 Hero]]
夷Sombras? Supongo que es una pelea,[n]entonces.

[sel SEL_032 top]
Hag茨moslo.
Lo hacemos juntos.

[msg MSG_033 [P3 Hero]]
Bien, podemos tomarlos. 斡Vamos!

