[msg MSG_000 [Elizabeth]]
にぺれ ぼよれぺれ るまれゎゅろぺるよょ ほぺれろぺょろま ぽもみまるまょろまれ ぽま ゅよ[n]りゎま めぺほウぺ もゆぺむもょぺぽよテテテ ひもょ まゆほぺるむよデ わまよ りゎま[n]めぺれ ぼゎゆらゅもぽよ ろゎ よほゃまろもわよテ
Debo decir, sin embargo... Tengo un[n]inter姻s leve en que esta chica hable yo[n]mismo.
Alg雨n d胤a, me gustar胤a acoger a una[n]chica hablar entre los residentes de la[n]Habitaci吋n Terciopelo.
Cuando llegue ese momento, Theo ser茨[n]incluido como Theoko... o tal vez[n]Theobeth.

[msg MSG_001 [Haru]]
Ahaha... 夷Teodoro terminar茨 como Teddie?

[msg MSG_002 [Teddie]]
Nuh-uh-uh. No puedes imitar tan[n]f茨cilmente esa belleza.

[msg MSG_003 [Chie]]
Entonces, 夷por qu姻 exactamente quieres[n]unirte a la charla de chicas tanto,[n]Teddie?

[msg MSG_004 [Teddie]]
Bueno... Todo el mundo siempre parece[n]que se est茨n divirtiendo tanto.
Pens姻, si me uniera, ser胤a capaz de[n]aprender m茨s sobre ustedes. Y no s吋lo[n]eso...
Pero pens姻 que podr胤amos ser mejores[n]amigos tambi姻n.

[msg MSG_005 [Yukiko]]
Teddie...

[msg MSG_006 [Rise]]
Deber胤as haberlo dicho.

[msg MSG_007 [Haru]]
S胤. Si ese es el caso, entonces no tiene[n]que ser s吋lo nosotras chicas. Todos[n]podr胤amos charlar juntos.

[msg MSG_008 [Teddie]]
夷En serio? 夷Me vas a dejar unir?
夷Puedo entrar en el para胤so de tu chica[n]secreta y hablar de esto y eso?

[msg MSG_009 [Yukiko]]
Claro que puedes. Pero si tienes alguna[n]idea divertida, te asar姻.

[msg MSG_010 [Teddie]]
Eek... Pero entonces el para胤so se asar茨[n]conmigo...!
斡No importa! Como miembro de la brigada[n]de belleza, voy a seguir d茨ndole todo lo[n]que tengo!
斡Ai, Rise, Haru! 斡Robamos los corazones[n]de todos juntos!

[msg MSG_011 [Haru]]
斡S胤, vamos a hacerlo!

[msg MSG_012 [Rise]]
斡Lo tienes! 斡No pienses que voy a dejar[n]que me golpees en lo que respecta a la[n]dulzura!

[msg MSG_013 [Aigis]]
Seguir姻 tu ejemplo y perforar姻 el[n]coraz吋n de todos, Teddie!

