[msg MSG_000 [Junpei]]
メCuホnto tiempo llevamos yendo y viniendo? No aguanto mホs...
ムVamos, Joker, por favor! ムメPodemos tomar un descanso?!

[sel SEL_001 top]
Sigamos caminando.
Muy bien.
Solo un poco.

[msg MSG_002 [Junpei]]
Maldiciポn, Joker, メpor qu〒 tienes que ser asボ? ムTe lo suplico!

[msg MSG_003 [Junpei]]
ムEso es lo que me gusta oボr, Joker! ムEres lo mホs!

[msg MSG_004 [Akihiko]]
メEso es todo lo que tienes, Junpei? Puede que necesites trabajar en tu resistencia.
Entrenar cuando estホs cansado puede enseワarte a conocer tus lボmites. ムLevホntate! ムEntrenar〒 contigo!

[msg MSG_005 [Junpei]]
ムImposible! ムMorirボa a mitad del salto!

[msg MSG_006 [Mitsuru]]
Espera, Akihiko. El cansancio de Iori es perfectamente entendible.
No solo es un laberinto complicado, sino que nos enfrentamos a enemigos mホs feroces. Cualquiera se cansarボa.

[msg MSG_007 [Junpei]]
S-Si, ムメves?!
Solo estaba preocupado por los demホs, メves? ムMe duele el corazポn de pensar en los pobres pies del resto!

[msg MSG_008 [Yukari]]
No s〒...

[msg MSG_009 [Mitsuru]]
De todos modos, es mejor no forzarnos. Tomemos un descanso y repongamos fuerzas.

[msg MSG_010 [Ryuji]]
ムPero parece que no hemos avanzado en todo este tiempo! Esto se estホ volviendo molesto.

[msg MSG_011 [Haru]]
De todos modos, si estamos tranquilos y nos seguimos moviendo, seguro que llegamos allボ.
Aunque sea un callejポn sin salida, podemos aワadirlo al mapa. ムY de todos modos, eso nos acercarホ mホs a nuestro destino!

[msg MSG_012 [Naoto]]
Ja... Al menos es optimista. Supongo que tienes razポn.
Tomemos un descanso.

[msg MSG_013 [Morgana]]
Hmm... Mitsuru y Noir siempre estホn tan tranquilas. Y cuando hablan, todo el mundo las escucha.
Tambi〒n son tan grandiosas. メEs esto lo que significa ser «noble»?

[sel SEL_014 top]
Asボ deberボamos de ser.
Yo tambi〒n soy tranquilo.
No lo s〒...

[msg MSG_015 [Yosuke]]
Ja, ja... No s〒 si eso se puede adquirir. Supongo que tienes que nacer con eso.
Pero ellas tambi〒n son tan guapas... Probablemente, harボa cualquier cosa que me pidieran...

[msg MSG_016 [Chie]]
Si todo lo que quieres es que una chica fuerte te pisotee, yo puedo hacer que eso suceda.

[msg MSG_017 [Yosuke]]
Ja, ja. Eres un lボder, y tienes una extraワa dignidad...
Pero las dos son tan guapas... Harボa cualquier cosa que me pidieran...

[msg MSG_018 [Chie]]
Si todo lo que quieres es que una chica fuerte te pisotee, yo puedo hacer que eso suceda.

[msg MSG_019 [Yosuke]]
Quiero decir... Son tan tranquilas, que te hace sentir que saben exactamente lo que estホn haciendo.
Pero, por encima de ello, ambas son tan guapas... Harボa cualquier cosa que me pidieran...

[msg MSG_020 [Chie]]
Si todo lo que quieres es que una chica fuerte te pisotee, yo puedo hacer que eso suceda.

[msg MSG_021 [Shinjiro]]
Bueno, supongo que es cierto que la gente con autoridad tiende a comportarse de cierta manera.
Estホn acostumbrados a controlar a la gente. Asボ es Mitsuru.

[msg MSG_022 [Yusuke]]
Hm... Noir tiene un comportamiento similar. Aunque es un poco mホs sutil que el de Kirijo...

[msg MSG_023 [Morgana]]
Ya veo... Puede ser porque ambas son herederas. Supongo que de ahボ viene el carisma.

[msg MSG_024]
Una nueva proyecciポn especial "Presiポn Heredera" ha sido aワadida a la taquilla.

