[msg MSG_000 [Futaba]]
Holy crap! She wasn't kidding about[n]those Treasure Spots!

[msg MSG_001 [Morgana]]
Mee-YOW! Look at all the treasure!
Let's get going, Joker! I can hear it[n]calling my name!

[msg MSG_002 [Haru]]
*giggle* Calm down, Mona-chan.
We can't just charge in. Let's take a[n]look at the map, and move carefully.

[msg MSG_003 [Futaba]]
Hmm... Like Zabby said, there's more[n]warp points around here, too.

[msg MSG_004 [Mitsuru]]
She did mention that the Treasure Spots[n]lay beyond the new warps... if I recall.
Then I suppose we'll have to find new[n]ways around the warp points and[n]subsequent doors.

[sel SEL_005 top]
I'm on it.
Sounds like a pain.

[msg MSG_006 [Mitsuru]]
In other words, our usual approach. Not[n]terribly demanding...

[msg MSG_007 [Mitsuru]]
*chuckle* Giving up before we've even[n]begun? At least give it a try.

[msg MSG_008 [Haru]]
There were three locations, correct?[n]Then let's find the first one.

[msg MSG_009 [Futaba]]
Alright! Then let's go look for those[n]Treasure Spots! Keep your eyes out,[n]guys!

