[msg MSG_000 [Yukiko]]
斡Y ese es el tercero!

[msg MSG_001 [Haru]]
Buen trabajo, todos. 斡Estoy tan contenta[n]de poder tener 姻xito juntos!

[msg MSG_002 [Junpei]]
Whew... Eso fue un largo paseo, pero me[n]siento casi refrescante.
Creo que todos me vieron en acci吋n...[n]S胤, esta pel胤cula va a ser un cl茨sico[n]atemporal.

[msg MSG_003 [Mitsuru]]
*chuckle* Lo hiciste bien. Si tuvieras[n]tan 姻tica de trabajo todo el tiempo.

[msg MSG_004 [Ryuji]]
Bueno, fue divertido. Supongo que estos[n]ex茨menes no son tan malos.

[msg MSG_005 [Morgana]]
Hey, yo tambi姻n he puesto trabajo! 斡Si[n]necesitas un cazador de tesoros, soy tu[n]tipo!

[msg MSG_006 [Haru]]
*giggle* Espero que podamos hacer m茨s de[n]este tipo de misiones.
Volvamos a informarle a Elizabeth.

