[msg MSG_000 [Junpei]]
How long have we been going back and[n]forth like this? I can't take it any[n]more...
C'mon, Joker, please! Can't we take a[n]break!?

[sel SEL_001 top]
Keep walking.
Fine.
Just a little one.

[msg MSG_002 [Junpei]]
Dang, Joker, why you gotta be like that?[n]I'm beggin' you here!

[msg MSG_003 [Junpei]]
That's what I like to hear, Joker! You[n]da man!

[msg MSG_004 [Akihiko]]
Is that all you've got, Junpei? You[n]might need to work on your stamina.
Training when you're already tired can[n]teach you about your limits. Stand up![n]I'll train with you!

[msg MSG_005 [Junpei]]
No way! I'd die mid-jumping-jack!

[msg MSG_006 [Mitsuru]]
Hold on, Akihiko. Iori's fatigue is[n]perfectly understandable.
Not only is this a complicated maze,[n]we're facing more and more vicious[n]enemies. Anyone would get tired.

[msg MSG_007 [Junpei]]
Y-Yeah, see!?
I was just worried about everyone else,[n]see? My heart's aching, thinking about[n]everyone's poor feet!

[msg MSG_008 [Yukari]]
I don't know about that...

[msg MSG_009 [Mitsuru]]
Either way, it's best not to force[n]ourselves. Let's take a break and[n]replenish our energy.

[msg MSG_010 [Ryuji]]
But it feels like we've been goin'[n]nowhere this whole time! It's getting[n]annoying.

[msg MSG_011 [Haru]]
Either way, if we stay calm and keep[n]moving, I'm sure we'll get there.
Even if it's a dead end, we can still[n]enter that in the map. And that'll bring[n]us one step closer anyway!

[msg MSG_012 [Naoto]]
Hah... That's optimistic, at least. I[n]suppose you have a point.
Let's take a break.

[msg MSG_013 [Morgana]]
Hmm... Mitsuru and Noir are always so[n]calm. And when they speak, everyone[n]listens.
They're both so regal, too. Is this what[n]it means to be "nobility"?

[sel SEL_014 top]
We should be like that.
I'm calm too.
I don't know...

[msg MSG_015 [Yosuke]]
Haha... I don't know if you can just[n]pick it up. You've gotta be born with[n]it, I think.
But they're both so beautiful, too...[n]I'd probably do anything they asked...

[msg MSG_016 [Chie]]
If all you wanted was a powerful girl to[n]step on you, I could make that happen.

[msg MSG_017 [Yosuke]]
Haha. I mean, you are a leader, and you[n]do have a weird kinda dignity...
But both of them are so gorgeous... I'd[n]do anything they asked me to...

[msg MSG_018 [Chie]]
If all you wanted was a powerful girl to[n]step on you, I could make that happen.

[msg MSG_019 [Yosuke]]
I mean... They're so calm, it makes you[n]feel like they know exactly what they're[n]doing.
But on top of that, they're both so[n]beautiful... I'd do anything they asked[n]me to...

[msg MSG_020 [Chie]]
If all you wanted was a powerful girl to[n]step on you, I could make that happen.

[msg MSG_021 [Shinjiro]]
Well, I guess it's true that people with[n]authority tend to carry themselves a[n]certain way.
They're just used to controlling people.[n]That's how Mitsuru is.

[msg MSG_022 [Yusuke]]
Hm... Noir has a similar bearing. It's a[n]bit more subtle than Kirijo-san's,[n]though...

[msg MSG_023 [Morgana]]
I see... It might be because they're[n]both heiresses. Guess that's where the[n]charisma comes from.

[msg MSG_024]
A new special screening: "Heir Pressure"[n]has been added to the box office.

