[msg MSG_000 [Elizabeth]]
La proyecci吋n especial esta vez es una[n]exploraci吋n de A.I.G.I.S.
Esta vez, el suelo designado es[n]absolutamente lleno de tesoros!
Y as胤, tu gloriosa misi吋n esta vez es[n]reunir todo el rid胤culo que puedas[n]encontrar.

[msg MSG_001 [Morgana]]
Hehehehehe... Tesoro, 夷eh? 斡Tienes mi[n]atenci吋n!

[msg MSG_002 [Ryuji]]
No te emociones demasiado, maldito gato.[n]Tenemos que atacar a Treasure Spots,[n]夷verdad?

[msg MSG_003 [Elizabeth]]
Por desgracia, no ser茨 tan f茨cil.
Junto con estos nuevos Puntos de Tesoro,[n]tambi姻n hay nuevos puntos de Warping.
Encontrar茨s el tesoro pasado estas[n]nuevas zonas warp.

[msg MSG_004 [Junpei]]
夷Las zonas de Warp nos van a tirar por[n]todas partes? Eso va a arruinar mi[n]Perspectiva Ace...

[msg MSG_005 [Ryuji]]
斡Maldita sea! Ser胤a mucho m茨s sencillo[n]si pudi姻ramos golpear a un monstruo duro[n]y conseguir los bienes.

[sel SEL_006 top]
Deja de quejarte.
No bromees.

[msg MSG_007 [Haru]]
Debo decir que estoy de acuerdo. Estas[n]proyecciones tambi姻n tienen su propio[n]encanto.
Ciertamente, las pel胤culas de acci吋n[n]llamativas son emocionantes, pero no[n]cuando todos son un p雨blico pueden ver.

[msg MSG_008 [Haru]]
夷Oh? 夷No es tu tipo de pel胤cula? Creo[n]que estos tienen cierto encanto.
Ciertamente, las pel胤culas de acci吋n[n]llamativas son emocionantes, pero no[n]cuando todos son un p雨blico pueden ver.

[msg MSG_009 [Ryuji]]
夷Eh? Espera, 夷qu姻 p雨blico?

[msg MSG_010 [Mitsuru]]
Hah. Un punto justo.
Cualquier pel胤cula puede ser[n]magn胤fica... Todos los actores de[n]primera clase saben que esto es verdad.

[msg MSG_011 [Junpei]]
夷Eh? Bueno, yo soy un actor de primera[n]clase. 斡Podr胤a haberte dicho eso!
斡Entonces vamos a intentarlo! 斡Las[n]estrellas no pueden elegir sus trabajos!

[msg MSG_012 [Ryuji]]
De acuerdo, de acuerdo, vamos a[n]conseguir este show en el camino.
Tiene que haber Sombras ah胤 fuera, as胤[n]que vamos a patear sus culos, conseguir[n]el bot胤n, y hacernos nuevas armas.

[msg MSG_013 [Haru]]
斡Sab胤a que vendr胤as! 斡Vamos a usar esta[n]oportunidad para hacernos m茨s poderosos!

[msg MSG_014 [Mitsuru]]
Tener protectores como t雨 hace mucho[n]para aliviar nuestras mentes. Ahora[n]podemos reunir tesoros en paz.
Contamos con ustedes dos.

[msg MSG_015 [Junpei]]
斡Lo tienes!

[msg MSG_016 [Ryuji]]
Haha... Bueno, nos hizo bien. Supongo[n]que no podemos ganar, 夷eh?

[msg MSG_017 [Shinjiro]]
Dios. Es como si estuvieran lavados de[n]cerebro. A雨n as胤, admiro que...
Heh. Bueno, si vas a ser un l胤der, tal[n]vez puedas aprender una o dos cosas.

[msg MSG_018 [Mitsuru]]
El dise隠o del piso probablemente va a[n]cambiar... Tendremos que investigar.

[msg MSG_019 [Haru]]
Entonces una vez que estemos listos,[n]vamos a empezar. 斡Con suerte[n]encontraremos algo que valga la pena!

