[msg MSG_000 [Junpei]]
Bueno, ムya estamos aquボ! Bro, este sitio grita ciencia ficciポn mires por donde mires.
Entonces, tenemos que buscar un huevo, メverdad?

[msg MSG_001 [Ann]]
Ey, ムmirad allボ!

[msg MSG_002 [Futaba]]
メLa foto del monitor ha cambiado? Ahora es una flecha.

[msg MSG_003 [Ann]]
Oh, sボ, recuerdo esto de cuando era pequeワa.
En las bマsquedas de huevos de Pascua, hay carteles como estos para ayudarte a encontrar los escondites.

[msg MSG_004 [Junpei]]
Oh, ムdejen que Panther nos enseワe algunas cosas del extranjero!
Dices que solo tenemos que seguir las flechas, メverdad?

[msg MSG_005 [Futaba]]
Hmm, メentonces hay un huevo de Pascua escondido al final del camino?
Muuuuy bien, Joker. ムFボjate en los monitores y sigue esas flechas!

