[msg MSG_000 [Junpei]]
Oye, as胤 son huevos de Pascua, como...[n]夷huevos reales?

[msg MSG_001 [Ann]]
A veces son huevos duros, pero tambi姻n[n]pueden ser contenedores en forma de[n]huevo llenos de dulces y cosas.

[msg MSG_002 [Haru]]
Creo que tambi姻n hay famosos, como los[n]de la Rusia Imperial.

[msg MSG_003 [Naoto]]
He o胤do hablar de eso. Te refieres a los[n]huevos de Faberg, 夷verdad?
Vienen en muchos colores y dise隠os[n]diferentes. Al menos valen varios[n]cientos de millones de yenes.

[msg MSG_004 [Junpei]]
夷Millones? 夷En serio?

[msg MSG_005 [Naoto]]
Tal vez eso es lo que nos espera al[n]final de esta proyecci吋n... Supongo que[n]podemos so隠ar. *chuckle*

[msg MSG_006 [Junpei]]
斡Rrraaaaah! 斡Eso nos har茨 millonarios![n]Aqu胤 viene Junpei, Ace Det-egg-tive!

[msg MSG_007 [Futaba]]
Recuerda d吋nde estamos, sin embargo. No[n]creo que encontremos algo as胤 aqu胤.
... Y no est茨 escuchando.

[msg MSG_008 [Junpei]]
斡Espera, peque隠o huevo! 斡Vamos en[n]camino!

