[msg MSG_000 [Junpei]]
Yo, an arrow! Looks like we gotta go[n]that way.

[msg MSG_001 [Ann]]
This is kinda fun. It's almost making me[n]feel like a little kid again.

[msg MSG_002 [Futaba]]
I know, it's so exciting!
Looks like there aren't too many hint[n]arrows. Careful not to miss anything.

[msg MSG_003]
The arrow is pointing to the left. Let's[n]try going that way...

[msg MSG_004]
The arrow is pointing to the left. Let's[n]try going that way...

