[msg MSG_000 [Junpei]]
Hey, so are Easter eggs, like... real[n]eggs?

[msg MSG_001 [Ann]]
Sometimes they're hard-boiled eggs, but[n]they can also be egg-shaped containers[n]filled with candy and stuff.

[msg MSG_002 [Haru]]
I think there's also really famous ones[n]too―like the ones from Imperial Russia.

[msg MSG_003 [Naoto]]
I've heard of those. You're referring to[n]Faberg〒 eggs, yes?
They come in many different colors and[n]designs. They're worth several hundred[n]million yen at least.

[msg MSG_004 [Junpei]]
Millions!? Seriously!?

[msg MSG_005 [Naoto]]
Perhaps that's what's waiting for us at[n]the end of this screening... I suppose[n]we can dream. *chuckle*

[msg MSG_006 [Junpei]]
Rrraaaaah! That thing's gonna make us[n]zillionaires! Here comes Junpei, Ace[n]Det-egg-tive!

[msg MSG_007 [Futaba]]
Remember where we are, though. I don't[n]think we're gonna find anything like[n]that here.
...Aaand he's not listening.

[msg MSG_008 [Junpei]]
Just you wait, little egg! We're on our[n]way!

