[msg MSG_000 [Futaba]]
Parece que vamos al final, chicos!

[msg MSG_001 [Junpei]]
Ya era hora... As胤 que este es nuestro[n]huevo de Pascua, 夷eh?
Espera, 夷qu姻?

[sel SEL_002 top]
Es s吋lo una foto.
T姻cnicamente es un huevo.

[msg MSG_003 [Junpei]]
夷Eso es todo? 夷Y mi mill吋n de yenes?

[msg MSG_004 [Ann]]
Ahaha, eso es un poco de decepci吋n, pero[n]no est茨 mal, 夷verdad?
Intentando encontrarlo fue divertido.[n]Fue como un juego.

[msg MSG_005 [Haru]]
Creo que tengo una mejor idea de c吋mo[n]era la Pascua para ti, Panther.

[msg MSG_006 [Futaba]]
Supongo que los videojuegos no son los[n]雨nicos tipos de juegos.
Necesitar姻 familiarizarme con los otros[n]tipos m茨s participativos tambi姻n.

[msg MSG_007 [Junpei]]
夷Crees que si lo hacemos por segunda[n]vez, un jefe secreto aparecer茨 y soltar茨[n]el verdadero tesoro? 夷Quiz茨?

[msg MSG_008 [Futaba]]
D姻jalo, Junpei. El juego termin吋...

