[msg MSG_000 [Rise]]
斡Bienvenidos, chicos!

[msg MSG_001 [Junpei]]
Phew, estoy totalmente vencido... Nunca[n]quiero volver a correr...

[msg MSG_002 [P3 Fem Protag]]
夷Est茨n bien? 夷Todos siguen vivos?

[msg MSG_003 [Aigis]]
Teddie estaba buscando brevemente a los[n]fiordos, pero aparte de eso, no hay[n]problemas importantes.

[msg MSG_004 [Fuuka]]
Qu姻 alivio... Estaba tan preocupada por[n]todos ustedes.

[msg MSG_005 [Ryuji]]
斡Todo fue gracias a nuestros navegantes![n]斡Muchas gracias!

[msg MSG_006 [Morgana]]
S胤, fue una ejecuci吋n perfecta. Lo[n]hicimos con seguridad porque ustedes[n]tres estaban sincronizados.

[msg MSG_007 [Rise]]
Lo s姻, 夷verdad? 斡Estamos en la misma[n]longitud de onda!
Desde que empezamos a trabajar juntos,[n]hemos llegado a comprender el estilo y[n]el ritmo del otro.

[msg MSG_008 [Fuuka]]
Cierto. 夷C吋mo lo describo? Nos asentamos[n]en roles. Ahora ni siquiera tenemos que[n]pensarlo.

[sel SEL_009 top]
Un escuadr吋n de 姻lites, 夷eh?
Trabajas bien juntos.

[msg MSG_010 [Futaba]]
Mwehehe. 斡Tenemos una gran qu胤mica, eso[n]es todo!

[msg MSG_011 [P3 Hero]]
Oh, trajimos todas las partes que[n]ustedes pidieron. 夷Es esto lo que[n]necesitabas?

[msg MSG_012 [Fuuka]]
斡Muchas gracias! S胤, esto deber胤a[n]funcionar bien.
Ahora, tenemos que construirlo...

[msg MSG_013 [Futaba]]
Est茨 bien... 夷Crees que podemos hacer[n]algo con todos esos cables?

[msg MSG_014 [Fuuka]]
ぬゆめゆテ つれろぺれ らぺるろまれ まれろァょ まょ れよるらるまょぽまょろまゆまょろま[n]ほゎまょぺれ ぼよょぽもぼもよょまれデ ぺれウ りゎま ろぺゅ わまん ょよ[n]ょまぼまれもろまゆよれ ろよぽよれ ゅよれ ぼよょぽゎぼろよるまれ[n]ぼよょまぼろぺぽよれテテテ
夷Podr胤a abrir un nuevo puerto en la red[n]inal茨mbrica, Futaba?

[msg MSG_015 [Junpei]]
Mira estos dos nerding fuera. Una mirada[n]a esas partes, y tienen ese brillo en[n]sus ojos...
A雨n as胤, Risette es un navegante, y no[n]se vuelve loca por esas cosas.

[msg MSG_016 [Rise]]
Es verdad, pero...
Ahora que he llegado a trabajar con[n]otros navegantes, he aprendido muchas[n]cosas nuevas.

[msg MSG_017 [Futaba]]
Quiero decir, lo mismo aqu胤!
Nunca pens姻 que estar胤a apoyando con un[n]胤dolo, pero...
夷A qui姻n le importa si es famosa? Me[n]trata como a un amigo.
Y tambi姻n Fuuka, as胤 que... tenerlos[n]alrededor me hace m茨s confiado. Como si[n]tuviera que tomarlo en serio.

[msg MSG_018 [Rise]]
斡Correcto! Puedo navegar solo, pero con[n]ambos de mi lado, me siento mucho m茨s[n]fuerte.
夷No crees que podemos hacer mucho m茨s[n]con los tres?
No estamos mejorando solos... Nos[n]ayudamos.

[msg MSG_019 [Fuuka]]
Rise, Futaba... Siento lo mismo hacia[n]ustedes dos.
Despu姻s de todo, no somos solo[n]compa隠eros de equipo. 斡Somos amigos!

[msg MSG_020 [Futaba]]
F-Amigos...
Mwehehehe... Sin conexi吋n Y amigos en[n]l胤nea!

[msg MSG_021 [Fuuka]]
Tengo una sugerencia...
Creo que hay otras formas de fortalecer[n]nuestra navegaci吋n adem茨s de usar esa[n]m茨quina.

[msg MSG_022 [Futaba]]
夷Qu姻, sin este dispositivo de[n]comunicaciones?

[msg MSG_023 [Fuuka]]
Um... Tal vez m茨s como adem茨s.
Si pudi姻ramos agregar su informaci吋n de[n]combate m茨s r茨pido, podr胤amos hacer m茨s[n]para ayudarles en la batalla, 夷verdad?

[msg MSG_024 [Futaba]]
Con el dispositivo de comunicaciones,[n]podemos ver m茨s, y conseguir una mejor[n]idea de la situaci吋n de batalla.
Y dependiendo de lo que est姻 pasando,[n]tal vez podr胤amos usar nuestras Personas[n]para apoyarlas f胤sicamente.

[msg MSG_025 [Rise]]
Apoyo f胤sico... Entonces, 夷como cosas de[n]recuperaci吋n de sanaci吋n y enfermedad?

[msg MSG_026 [Futaba]]
斡S胤! 斡As胤 es! 斡Esta ser茨 una gran ayuda[n]para todos!
Bien, vamos a golpear este gadget[n]juntos! 斡Llamo a una reuni吋n de[n]navegantes!

[msg MSG_027 [Yosuke]]
Ah胤 van con las partes. Son como un[n]hurac茨n.
Bueno, tenemos todo lo que quer胤an, as胤[n]que supongo que esta solicitud est茨[n]hecha.

[msg MSG_028 [Yusuke]]
Espera. Siento que olvidamos algo[n]importante.

[msg MSG_029 [Yosuke]]
夷Eh? 夷Algo que olvidamos?

[sel SEL_030 top]
Reportando a Elizabeth.
No lo s姻.
夷La cena de esta noche?

[msg MSG_031 [Yosuke]]
斡Oh! 斡Correcto!

[msg MSG_032 [Yosuke]]
Ahora que lo mencionas, tal vez hab胤a[n]una cosa m茨s... 夷pero qu姻?

[msg MSG_033 [Akechi]]
Si tuviera que adivinar, 夷le informar胤a[n]a Elizabeth?

[msg MSG_034 [Yosuke]]
斡Oh, cierto! Hombre, he estado tan[n]ausente 雨ltimamente...
斡Espera! 斡Eso no es de lo que estoy[n]hablando!

[msg MSG_035 [Akechi]]
Si tuviera que adivinar, 夷le informar胤a[n]a Elizabeth?

[msg MSG_036 [Elizabeth]]
Hmhmhm... Y por fin recuerdas mi[n]existencia...

[msg MSG_037 [Yosuke]]
夷De d吋nde vienes?

[msg MSG_038 [Elizabeth]]
He estado aqu胤 detr茨s de ti, todo este[n]tiempo...
Como un cachorro abandonado, esperando[n]sin ayuda, pregunt茨ndose por qu姻 el[n]maestro no ha vuelto...

[msg MSG_039 [P3 Hero]]
Uh... Lo siento.

[msg MSG_040 [Elizabeth]]
No, no... Est茨 bien... No te[n]preocupes...
Ni siquiera cruz吋 mi mente para[n]otorgarles maldiciones eternas. Ni una[n]vez.
Adem茨s, esta proyecci吋n me permiti吋 ver[n]algo maravilloso.
Ahora bien, aqu胤 est茨 tu recompensa. Por[n]favor, ac姻ptalo.

[msg MSG_041 [Elizabeth]]
El trabajo en equipo de los navegantes[n]fue simplemente excepcional. Espero[n]ansiosamente sus nuevas explotaciones.

[msg MSG_042 [Morgana]]
Si los lazos de los navegantes se[n]fortalecen, su apoyo ser茨 a雨n mejor.
Fue definitivamente una prueba especial[n]productiva, de todos modos.

[msg MSG_043 [Ryuji]]
斡S胤! 斡Mantengamos esto arriba!

