[msg MSG_000 [Rise]]
ムBienvenidos de vuelta, chicos!

[msg MSG_001 [Junpei]]
Uf, estoy totalmente derrotado... No quiero volver a correr a ningマn sitio...

[msg MSG_002 [P3 Fem Protag]]
メEstホn bien? メTodo el mundo sigue vivo?

[msg MSG_003 [Aigis]]
Teddie estuvo aワorando los fiordos, pero aparte de eso, sin mayores problemas.

[msg MSG_004 [Fuuka]]
Oh, qu〒 alivio... Estaba tan preocupada por todos ustedes.

[msg MSG_005 [Ryuji]]
ムTodo fue gracias a nuestras navegadoras! ムMuchボsimas gracias!

[msg MSG_006 [Morgana]]
Sボ, fue una ejecuciポn perfecta. Salimos sanos y salvos porque las tres estaban sincronizadas.

[msg MSG_007 [Rise]]
Lo s〒, メverdad? ムNosotras estamos en la misma onda!
Desde que comenzamos a trabajar juntas, hemos llegado a entender el estilo y el ritmo de cada una.

[msg MSG_008 [Fuuka]]
Cierto. メCポmo lo describo...? Creo que nos hemos acostumbrado a nuestros roles. Ahora ni siquiera tenemos que pensar en ello.

[sel SEL_009 top]
Un escuadrポn de 〒lites, メeh?
Trabajan muy bien juntas.

[msg MSG_010 [Futaba]]
Mue, je, je. Tenemos mucha quボmica, eso es todo.

[msg MSG_011 [P3 Hero]]
Oh, hemos traボdo todas las piezas que nos pidieron. メSon estas las que necesitan?

[msg MSG_012 [Fuuka]]
Oh, ムmuchボsimas gracias! Sボ, estas deberボan funcionar.
Ahora solo tenemos que construirlo...

[msg MSG_013 [Futaba]]
Hm, de acuerdo... メCrees que podemos hacer algo con todos esos cables?

[msg MSG_014 [Fuuka]]
Mmhm. Las piezas estホn en sorprendentes buenas condiciones, asボ que puede que no necesitemos conectar todos los conductores...
メPodrボas abrir un nuevo puerto en la red inalホmbrica, Futaba?

[msg MSG_015 [Junpei]]
Vaya, mira esas dos como disfrutan. Miran esas piezas, y tienen ese brillo en sus ojos...
Aun asボ, Risechi es navegante y no se vuelve loca por esas cosas.

[msg MSG_016 [Rise]]
Hmm. Quiero decir, eso es cierto, pero...
Ahora que he estado trabajando con otros navegadores, he aprendido un montポn de nuevas cosas.

[msg MSG_017 [Futaba]]
ムL-Lo mismo digo!
Nunca pens〒 que estarボa brindando apoyo junto a una idol, pero...
En este punto, メa qui〒n le importa si es famosa? A mボ me trata como una amiga.
Y Fuuka igual... tener a las dos cerca me da mホs confianza. Como si tuviera que tomホrmelo mホs en serio.

[msg MSG_018 [Rise]]
ムCierto! Puedo navegar yo sola, pero con ambas a mi lado, me siento mucho mホs fuerte.
メNo creen que podemos hacer mucho mホs las tres juntas?
No mejoramos solos... Nos ayudamos mutuamente.

[msg MSG_019 [Fuuka]]
Rise, Futaba... Siento lo mismo por ustedes dos.
No somos compaワeras, despu〒s de todo. ムSomos amigas!

[msg MSG_020 [Futaba]]
A-Amigas...
Mue, je, je... ムAmigas offline y online!

[msg MSG_021 [Fuuka]]
Oh, tengo una sugerencia...
Creo que hay otras formas con las que podemos fortalecer nuestra navegaciポn ademホs de usar esa mホquina.

[msg MSG_022 [Futaba]]
メQu〒, sin este dispositivo de comunicaciポn?

[msg MSG_023 [Fuuka]]
Um... Tal vez mホs bien ademホs de 〒l.
Si pudi〒ramos agregar su informaciポn de combate mホs rホpido, podrボamos hacer mホs para ayudarlos en la batalla, メverdad?

[msg MSG_024 [Futaba]]
Con el dispositivo de comunicaciポn, podemos ver mホs, y tener una mejor idea de la situaciポn de la batalla.
Y dependiendo de lo que est〒 ocurriendo, quizホs podamos usar nuestras Personas para apoyarlos fボsicamente.

[msg MSG_025 [Rise]]
Apoyo fボsico... メComo habilidades de curaciポn y de recuperaciポn?

[msg MSG_026 [Futaba]]
ムSボ! ムEso es! ムSerホ de gran ayuda para todos!
ムBien, vamos a montar este cacharro! ムConvoco reuniポn de navegadoras!

[msg MSG_027 [Yosuke]]
Y allホ van con las piezas. Son como un huracホn.
Bueno, tenemos todo lo que querボamos, asボ que supongo que la solicitud estホ completada.

[msg MSG_028 [Yusuke]]
Espera. Siento que nos estamos olvidando de algo importante.

[msg MSG_029 [Yosuke]]
メEh? メHemos olvidado algo?

[sel SEL_030 top]
Informar a Elizabeth.
No lo s〒.
メLa cena de hoy?

[msg MSG_031 [Yosuke]]
ムOh! ムCierto!

[msg MSG_032 [Yosuke]]
Ahora que lo dices, puede ser que haya algo mホs... メPero qu〒?

[msg MSG_033 [Akechi]]
Si tuviera que adivinar, メserボa informar a Elizabeth?

[msg MSG_034 [Yosuke]]
ムOh, cierto! Bro, マltimamente estoy tan distraボdo...
Espera, no, ムmaldita sea! ムNo estoy hablando de eso!

[msg MSG_035 [Akechi]]
Si tuviera que adivinar, メserボa informar a Elizabeth?

[msg MSG_036 [Elizabeth]]
Hmhmhm... Finalmente, se acuerdan de mi existencia...

[msg MSG_037 [Yosuke]]
ムメQu〒 diablos, de dポnde saliste?!

[msg MSG_038 [Elizabeth]]
He estado detrホs de ustedes todo este tiempo...
Como un cachorro abandonado, esperando impotente, preguntホndose por qu〒 el amo no ha vuelto...

[msg MSG_039 [P3 Hero]]
Uh... Perdポn por eso.

[msg MSG_040 [Elizabeth]]
No, no... No pasa nada... No se preocupen...
Ni siquiera se me pasポ por la cabeza lanzarles maldiciones eternas. Ni una sola vez.
Ademホs, esta proyecciポn me permitiポ vislumbrar algo realmente maravilloso.
Ahora bien, aquボ estホ su recompensa. Por favor, ac〒ptenla.

[msg MSG_041 [Elizabeth]]
El trabajo en equipo de las navegadoras fue sencillamente excepcional. Espero con impaciencia sus nuevas hazaワas.

[msg MSG_042 [Morgana]]
Si los lazos de los navegantes se estrechan, su apoyo serホ aマn mayor.
En cualquier caso, fue una proyecciポn especial muy productiva.

[msg MSG_043 [Ryuji]]
ムSボ! ムSigamos asボ!

