[msg MSG_000 [Fuuka]]
Rise, Futaba... 夷Podr胤a tener un[n]momento?

[msg MSG_001 [Rise]]
夷Qu姻 pasa?

[msg MSG_002 [Fuuka]]
Um... Tenemos muchos combates por[n]delante en este mundo, as胤 que...
Creo que es seguro decir que tendremos[n]grandes batallas por delante, 夷verdad?

[msg MSG_003 [Futaba]]
Seguro. Estoy recibiendo un mont吋n de[n]"jefe final que viene" vibraciones.

[msg MSG_004 [Fuuka]]
As胤 que... estaba pensando que todos van[n]a necesitar nuestro apoyo m茨s que nunca.

[msg MSG_005 [Rise]]
Vale, 夷quieres mejorar nuestra energ胤a[n]de navegaci吋n de alguna manera?

[msg MSG_006 [Fuuka]]
S胤. Quiero ver si hay algo que podamos[n]hacer para construir nuestro poder en[n]algo m茨s.

[msg MSG_007 [Futaba]]
斡Como entrenar en una c茨mara de tiempo[n]hiperb茨rica! 斡Podr胤a entrar en eso!
Oh, pero s吋lo para m胤, no estoy sentado[n]bajo ninguna cascada. Lo que hagamos,[n]ser茨 mejor que no sea trabajo manual.

[msg MSG_008 [Rise]]
La mayor parte de nuestra navegaci吋n es[n]a trav姻s de nuestras Personas. Supongo[n]que no podemos mejorar tan f茨cilmente...

[msg MSG_009 [Futaba]]
S胤, no es como si pudi姻ramos conectar a[n]un drag吋n con una colecci吋n de bolas a[n]cambio de m茨s poder...
... Pero tal vez haya alguna clase de[n]potencia que podamos usar. 夷O algunos[n]tramposos?

[msg MSG_010 [Fuuka]]
Ya sabes... Esto fue antes de unirme al[n]Escuadr吋n de Ejecuci吋n Extracurricular[n]Especializado...
ぬもろれゎるゎ-れまょらぺも るまぺゅもんカ ろぺるまぺれ ぽま ょぺわまむぺょろま[n]ゎろもゅもんぺょぽよ ゎょぺ ゆァりゎもょぺ りゎま ぺをゎぽカ ぺ ぺゆらゅもみもぼぺる[n]れゎれ めぺほもゅもぽぺぽまれ ぽま ほグれりゎまぽぺテ

[msg MSG_011 [Futaba]]
夷Le ayud吋 a buscar mejor? 夷As胤 que fue[n]como un radar personal?

[msg MSG_012 [Fuuka]]
S胤. Era alg雨n tipo de m茨quina, pero[n]ayud吋 a refinar sus poderes.
のほわもぺゆまょろま ょよ らよぽまゆよれ ゎれぺる ぬもろれゎるゎ-れまょらぺもデ[n]らまるよ れも らゎぽもイるぺゆよれ ぽもれまォぺる ゎょ れもれろまゆぺ ぽま[n]ぼよゆゎょもぼぺぼもよょまれ れもゆもゅぺるテテテ

[msg MSG_013 [Rise]]
斡Oh! 斡Es una buena idea! A veces parece[n]que realmente tenemos problemas para[n]contactarlos.
夷No ser胤a genial si tuvi姻ramos alguna[n]m茨quina de comunicaci吋n que nos dijera[n]lo que todos estaban haciendo?

[msg MSG_014 [Fuuka]]
Estoy de acuerdo. Y creo que puedo hacer[n]uno, si podemos encontrar las partes[n]correctas.

[msg MSG_015 [Futaba]]
Si necesitas partes, la pel胤cula de[n]Ribbon podr胤a ser un buen lugar para[n]ver.
Hay una tonelada de Sombras y FOEs all胤[n]que probablemente dejar胤a cosas que[n]podemos usar.

[msg MSG_016 [Rise]]
No s姻 si funcionar茨, pero[n]definitivamente vale la pena intentarlo!
夷Por qu姻 no empezamos ahora? 斡Esperen[n]aqu胤!

[msg MSG_017 [Futaba]]
斡Hola! 夷Ad吋nde vas?

[msg MSG_018 [Rise]]
斡Soy baaack!

[msg MSG_019 [Fuuka]]
Rise, 夷eso es...?

[msg MSG_020 [Rise]]
Le cont姻 a Elizabeth nuestra historia y[n]la hice hacer un boleto.
斡Pedimos una petici吋n! "Por favor,[n]recoge una maquinaria"!

[msg MSG_021 [Futaba]]
斡GJ Rise!
斡Buscar esas partes por nuestra cuenta[n]habr胤a sido como jugar en modo[n]arriesgado!

[msg MSG_022 [Rise]]
Bueno, ten en cuenta que ni siquiera[n]pueden recogerlo, pero podemos ser[n]pacientes, 夷verdad?

[msg MSG_023 [Fuuka]]
Definitivamente. 斡Espero que acepten[n]nuestra solicitud pronto!

[msg MSG_024]
Una nueva proyecci吋n especial: "Red[n]Social" se ha a隠adido a la taquilla.

