[msg MSG_000 [Lab security]]
PRESENCIA NO AUTORIZADA DETECTADA. TODAS LAS UNIDADES VAYAN A POR LOS INTRUSOS.

[msg MSG_001 [Kanji]]
Maldiciポn, ムメaマn mホs?! ムSiguen viniendo!

[msg MSG_002 [Teddie]]
Estamos acabados... Veo una luz al final del tマnel...

[msg MSG_003 [Kanji]]
ムAguanta, Teddie! ムNo vayas hacia la luz!

[msg MSG_004 [Rise]]
ムEstamos de vuelta! ムEl anホlisis estホ completo!

[msg MSG_005 [Fuuka]]
Los sistemas de seguridad se han activado. Estホ enviando mマltiples enemigos a su posiciポn.
No tiene sentido intentar detener el sistema de seguridad, asボ que hemos dado prioridad a sacarles de allボ sanos y salvos.

[msg MSG_006 [Mitsuru]]
メTenemos una ruta de escape?

[msg MSG_007 [Futaba]]
ムPor supuesto! ムLes guiaremos fuera! ムPor aquボ!

[msg MSG_008 [Morgana]]
ムMuy bien! ムSalgamos de aquボ!

