[msg MSG_000 [Elizabeth]]
Bienvenidos de vuelta. Aquボ estホ su recompensa por esta proyecciポn especial.

[msg MSG_001 [Akihiko]]
Entonces creo que tienes una idea de lo fuertes que somos... メNotas algo que debamos mejorar?

[msg MSG_002 [Chie]]
ムEstamos listos por este entrenamiento especial, Entrenadora!

[msg MSG_003 [Makoto]]
Sボ, he anotado algunas cosas que creo que les faltan.

[msg MSG_004 [Chie]]
ムGracias! Veamos...
...

[msg MSG_005 [Akihiko]]
メQu〒 es esto...?

[msg MSG_006 [Chie]]
メUn menマ?

[sel SEL_007 top]
メQu〒 ocurre?
メEsto es entrenar?
Supongo que cuenta.

[msg MSG_008 [Makoto]]
Estoy segura de que lo he dicho antes. Ambos ya son muy fuertes.
En cuanto a entrenamiento, no hay mucho mホs que les pueda ofrecer.

[msg MSG_009 [Chie]]
メPero todo un cambio de dieta...? Y... todo son pescados y verduras...

[msg MSG_010 [Akihiko]]
Hay ALGO de carne, pero la proporciポn parece muy pequeワa... メEstホs segura de que hay suficiente proteボna?

[msg MSG_011 [Makoto]]
Hay proteボnas vegetales, al igual que proteボnas cホrnicas. Necesitan un equilibrio de ambas.
Si quieren obtener todos los nutrientes necesarios, no pueden rechazar las verduras.
Y tambi〒n quieren entrenar su cerebro, メverdad? Entonces deberボan de comer pescado.

[msg MSG_012 [Chie]]
Tiene sentido, por supuesto, pero... apenas hay carne...

[msg MSG_013 [Akihiko]]
No, si este menマ nos hace mホs fuertes, entonces...

[msg MSG_014 [Chie]]
... ムMaestro!

[msg MSG_015 [Akihiko]]
Gracias, Makoto. Usaremos este menマ y nos volveremos mホs fuertes gracias a 〒l.

[msg MSG_016 [Makoto]]
No, yo deberボa de agradecerles a ustedes.
Observar su devociポn por volverse mホs fuertes, me ha hecho pensar en mis propias razones.
メPor qu〒 me quiero hacer fuerte?

[sel SEL_017 top]
メPara luchar contra enemigos fuertes?
メPara proteger a alguien?

[msg MSG_018 [Makoto]]
Eso es lo que Satonaka y Sanada dirボan, pero...
Si quieres ser capaz de parar enemigos fuetes, メno es porque quieres proteger a alguien de ellos?
Proteger a la gente requiere fuerza... Yo tambi〒n aspiraba a esa fuerza. Querボa ser como 〒l.

[msg MSG_019 [Makoto]]
Sボ. Exactamente.
Si quieres ser capaz de parar enemigos fuetes, メno es porque quieres proteger a alguien de ellos?
Proteger a la gente requiere fuerza... Yo tambi〒n aspiraba a esa fuerza. Querボa ser como 〒l.

[msg MSG_020 [Chie]]
Te refieres a tu padre, メverdad...? Suena como un h〒roe de verdad. Apuesto a que 〒l protegiポ a la gente.
A veces desearボa ser como los h〒roes de las pelボculas. Saltando en picado, salvando a mis amigos del peligro...
ムEs por eso por lo que me quiero hacer aマn mホs fuerte!

[msg MSG_021 [Akihiko]]
Sボ. Es por eso por lo que necesito poder confiar en mis puワos... para no perder a nadie importante para mボ de nuevo.
Si me ayuda a conseguirlo, pasar〒 por lo que sea.

[msg MSG_022 [Makoto]]
Chicos...

[sel SEL_023 top]
Todos ustedes son asボ.
No pierdas contra ellos.

[msg MSG_024 [Makoto]]
Je... Tal vez. Supongo que deberボa unirme a su entrenamiento, メeh?

[msg MSG_025 [Makoto]]
Supongo que no. Quizホs serボa mejor que me uniera a su entrenamiento, メeh?

[msg MSG_026 [Akihiko]]
Por supuesto. Nos alegrarボa tenerte. Podrボamos empezar ahora mismo.
Oh, pero primero tenemos que comer para reponer toda la energボa que hemos perdido.

[msg MSG_027 [Chie]]
ムBooool de terneraaaa!

[msg MSG_028 [Makoto]]
メUn segundo? メQu〒 pasa con el menマ que les acabo de enseワar?

[msg MSG_029 [Akihiko]]
Pero dice que la carne es buena una vez al dボa. Y ya es hora de que coma un poco.

[msg MSG_030 [Chie]]
ムSボ! ムNo pienses, si〒ntelo!

[msg MSG_031 [Akihiko]]
La verdad, Makoto, es que yo tambi〒n te estaba observando en la マltima batalla...
Tienes a pensar demasiado las cosas. A veces necesitas マnicamente confiar en tu intuiciポn.

[sel SEL_032 top]
メEsa es su debilidad?
Eso es cierto.
Esto tambi〒n es entrenar.

[msg MSG_033 [Makoto]]
メYo pienso demasiado las cosas...? Supongo que no puedo negar eso.

[msg MSG_034 [Chie]]
En otras palabras, esto es tambi〒n un entrenamiento para ti, Makoto.
La cuestiポn es, ムno pienses! ムSi〒ntelo! ムSiente el poder de la CARNE!

[msg MSG_035 [Makoto]]
ムメEspera, qu〒?! ムEy!

[msg MSG_036 [Elizabeth]]
... Parece que se ha forjado un nuevo vボnculo.
Y con eso, se vuelve a bajar el telポn. Hasta la prポxima...

