[msg MSG_000 [Makoto]]
Uf, hemos avanzado bastante. Creo que un descanso nos irボa bien...

[msg MSG_001 [Makoto]]
ムメQ-Qu〒?! メUn terremoto? メNos estホn atacando?

[msg MSG_002 [Chie]]
ムAllホ va! El arte secreto al estilo Satonaka... ムPatada Dragポn!

[msg MSG_003 [Akihiko]]
ムNo estホ mal! ムPero ha sido demasiado lenta!

[msg MSG_004 [Chie]]
ムEres alucinante, Maestro! ムFuiste tan rホpido, que ni siquiera te vi moverte!

[msg MSG_005 [Akihiko]]
Tマ tambi〒n tienes una patada increボble, Chie. Si la hubiera recibido de frente, habrボa salido volando.

[msg MSG_006 [Makoto]]
ムメQu〒 estホn haciendo ustedes dos?!

[msg MSG_007 [Akihiko]]
ムNada por lo que preocuparse! Solo estホbamos entrenando. Un pequeワo simulacro de batalla como calentamiento.

[sel SEL_008 top]
Alguien saldrホ herido...
Eso sボ que es diligencia.

[msg MSG_009 [Chie]]
No te preocupes. ムEstamos acostumbrados!

[msg MSG_010 [Makoto]]
Puede que est〒n acostumbrados a esto, pero YO NO...

[msg MSG_011 [Makoto]]
Me alegra verles tan activos, pero メrealmente necesitan entrenar aquボ?

[msg MSG_012 [Akihiko]]
Eh... Quizホs nos pasamos un poco, pero es que no podボa contenerme.

[msg MSG_013 [Chie]]
Je, je, je. S〒 lo que quieres decir. Tienes que comer y luchar bien. ムAsボ es como te haces el mホs fuerte!

[msg MSG_014 [Makoto]]
メEsto es todo lo que hacen? メSiempre entrenan tan duro?

[msg MSG_015 [Chie]]
Hmm, mi rutina habitual es correr un poco y despu〒s practicar mis patadas... Finalmente, ムacabo con un buen bol de carne!

[msg MSG_016 [Akihiko]]
Sボ. Tienes que preparar tu cuerpo para un entrenamiento intenso y luego acabar con un buen bocado de proteボnas.

[msg MSG_017 [Makoto]]
*suspiro*
Golpearse imprudentemente no es entrenarse. Tambi〒n hay que pensar en entrenar la mente.
Lo mismo aplica para su dieta. No puedes comer マnicamente proteボnas. Tienes que pensar en una comida equilibrada.

[msg MSG_018 [Akihiko]]
Oh, ムes cierto! Tマ practicas aikido, メverdad, Queen? Bueno, no puedo negar la opiniポn de una compaワera luchadora...

[msg MSG_019 [Makoto]]
Asボ que entonces ahora yo tambi〒n participo en esto, メno...?

[msg MSG_020 [Chie]]
... ムOh! ムAcabo de tener una idea genial! メY si Queen nos prepara un nuevo curso de formaciポn?

[msg MSG_021 [Akihiko]]
Buena idea. Si siempre entrenamos de la misma forma, nos acostumbraremos. メPuedes ayudarnos, Queen?

[sel SEL_022 top]
Int〒ntalo.
Puedes hacerlo.
Suena divertido.

[msg MSG_023 [Makoto]]
Supongo que podrボa...
Pero si voy a hacerlo, necesito medir las fuerzas de cada uno para poder establecer objetivos realistas...

[msg MSG_024 [Makoto]]
Oh, no, tマ tambi〒n... Aunque supongo que no me importarボa enseワarte.
Pero si voy a hacerlo, necesito medir las fuerzas de cada uno para poder establecer objetivos realistas...

[msg MSG_025 [Makoto]]
メEs realmente el momento de decir eso? Bueno, supongo que no me importa enseワarte...
Pero si voy a hacerlo, necesito medir las fuerzas de cada uno para poder establecer objetivos realistas...

[msg MSG_026 [Haru]]
ムOh, Queen! Mitsuru dice que deberボamos de seguir pronto.

[msg MSG_027 [Makoto]]
Bien, deberボamos irnos por ahora. Podemos discutir su entrenamiento en otro momento.

[msg MSG_028 [Chie]]
ムEntendido, Entrenadora!

[msg MSG_029 [Makoto]]
... メEntrenadora?
Um, bien... Vホmonos.

