[msg MSG_000 [Kanji]]
Guh... hah... T-Toma esa... ムpedazo de...!

[msg MSG_001 [Junpei]]
Whoof... urgh... Estoy reventado... No puedo moverme.

[msg MSG_002 [Yusuke]]
メSobrevivieron a ese riguroso atletismo y aun asボ ganaron la batalla...? Bravo.

[msg MSG_003 [Akihiko]]
ムBuen trabajo, ustedes dos!
Ha sido una simulaciポn perfecta de verse obligado a luchar despu〒s de haber alcanzado sus lボmites.

[msg MSG_004 [Kanji]]
Aマn... no s〒... de qu〒 estホs hablando, pero... Definitivamente he sobrepasado mis propios lボmites...

[msg MSG_005 [Junpei]]
Uf... maldiciポn... Nunca lo volver〒 a hacer...

[msg MSG_006 [Akihiko]]
Entrenar te ayuda a estar preparado contra cualquier enemigo o situaciポn. Ahボ es cuando sabes que eres fuerte.
De otra forma, no serホs capaz de proteger lo que es importante cuando llegue el momento.

[msg MSG_007 [Junpei]]
Cierto... Tengo que proteger...
...

[msg MSG_008 [Akihiko]]
Bien, conc〒ntrense. ムVamos a entrenar tambi〒n en el camino de vuelta!

[msg MSG_009 [Shinjiro]]
D〒jame detenerte, idiota. Vas a matar a esos dos.

[msg MSG_010 [Akihiko]]
Hm. メPiensas eso?
Bueno, nunca quieres exceder tus lボmites. Es una pena, pero serホ mejor que nos detengamos aquボ.

[msg MSG_011 [Kanji]]
ムNnnraaagh! ムPuedo seguir, maldiciポn!
ムSi Akihiko puede hacer esto, yo tambi〒n! ムQuiero ganar!

[msg MSG_012 [Akihiko]]
ムEse es el espボritu! ムHora de sobrepasar tus lボmites!
メQu〒 hay de ti, Junpei?

[msg MSG_013 [Junpei]]
Sボ, eh, paso... Bro, no puedo ni moverme...

[msg MSG_014 [Akihiko]]
Muy bien. No te fuerces. Solo c〒ntrate en relajarte.
Muy bien... ムHagamos un entrenamiento fホcil y volvamos corriendo al cine! ムEs una carrera!

[msg MSG_015 [Kanji]]
ムAdelante!

[msg MSG_016 [Junpei]]
メEn serio...? Yo no he firmado... para ser un Superatleta...
... Bluh.

