[msg MSG_000 [Elizabeth]]
Fo, fo, F-O-E. Si lo lees al rev〒s, E-O-F...
... Ya basta, Theo

[msg MSG_001 [Theodore]]
ムメY-Yo...?!

[msg MSG_002 [Kanji]]
Uh, メpodrボas ir al grano?

[msg MSG_003 [Elizabeth]]
ムEjem! Ahora bien...

[msg MSG_004 [Elizabeth]]
A TODOS LOS OCUPANTES: HOLA. HOLA. NUEVO TICKET DISPONIBLE.
EXTERMINAR AL FOE: SCM-8801. UBICACIロN: A.I.G.I.S.
EXTERMINAR AL FOE: SCM-8801. EXTERMINAR AL FOE: SCM-8801. 

[msg MSG_005 [Junpei]]
メPor qu〒 habla como un robot...?

[msg MSG_006 [Akihiko]]
"SCM-8801," メeh? Ese es el robot ejecutor.

[msg MSG_007 [Elizabeth]]
El FOE presentaba una amenaza mortal anteriormente, pero creo que ahora deberボa de ser un reto mホs razonable.
メPor qu〒 no pueban todos su fuerza contra 〒l?

[sel SEL_008 top]
Hagホmoslo.
No lo s〒...

[msg MSG_009 [Akihiko]]
Sボ, me ha llamado la atenciポn. No hay nada como un oponente poderoso para ayudarte a hacerte mホs fuerte.

[msg MSG_010 [Akihiko]]
メQu〒 ocurre? No es propio de ti dudar. No creo que nos haga pasar un mal rato.

[msg MSG_011 [Junpei]]
Oh, conozco esa mirada en su rostro... Nunca cambia, メeh?

[msg MSG_012 [Yukari]]
Ja, ja, ja, bueno, estamos hablando de Akihiko. Tal vez pueda ayudarte a fortalecerte.

[msg MSG_013 [Akihiko]]
メQu〒 opinas, Junpei? Con mi entrenamiento, podrボamos llevarte a tus lボmites.

[msg MSG_014 [Junpei]]
ムメEh?! Espera, ムメde dポnde saliポ ESO?!

[msg MSG_015 [Akihiko]]
No te contengas. Hay algunos lugares a los que solo puedes llegar con un entrenamiento doloroso e intenso.
ムVamos allホ, Junpei! ムAlcanzaremos esas alturas juntos!

[msg MSG_016 [Junpei]]
Maldiciポn, estホ totalmente concentrado...
ムPagarホs por esto, Yuka! Bueno, ahora que ya no hay escapatoria... eh...

[msg MSG_017 [Kanji]]
メEstホs bien, Junpei? Te ves muy sospechoso.

[msg MSG_018 [Junpei]]
ムAh! ムKanji! ムEn el momento perfecto!
Mira, bro, no es nada personal... No tengo nada contra ti, ムpero si caigo, te llevar〒 conmigo!

[msg MSG_019 [Kanji]]
メD-De qu〒 estホs hablando?

[msg MSG_020 [Junpei]]
ムEste tipo es demasiado bueno para que yo me encargue de 〒l! Pero tマ eres bastante fuerte, メverdad? ムVamos, ayマdame!

[msg MSG_021 [Kanji]]
メB-Bueno? メFuerte?
ムメQu〒, tengo que "encargarme" de chicos buenos y sudorosos?! ムメEsto te parece una maldita sauna?!

[msg MSG_022 [Junpei]]
メD-De dポnde ha salido eso?

[msg MSG_023 [Kanji]]
Oh, nada. Culpa mボa.
Era algo sobre un FOE, entrenar y ese tipo de mierda, メverdad?

[msg MSG_024 [Junpei]]
ムSボ! Eso es. Vamos, somos bros, メverdad? ムAmbos podemos entrenar! ムVayamos a por el oro! ムAlcancemos las estrellas!

[msg MSG_025 [Kanji]]
Mira, no s〒 de qu〒 estホs hablando, pero no me importarボa entrenar.

[msg MSG_026 [Junpei]]
ムUf, eres un tボo legal...! ムAhihiko! ムTenemos a otro en el club!

[msg MSG_027 [Kanji]]
Bro, メcポmo acabo siempre en esto...?

