[msg MSG_000 [Elizabeth]]
Eff, eff, F-O-E. If you read it[n]backwards, E-O-F...
...That's enough of that, Theo.

[msg MSG_001 [Theodore]]
M-Me...!?

[msg MSG_002 [Kanji]]
Uh, could you get to the point?

[msg MSG_003 [Elizabeth]]
Ahem! Now then...

[msg MSG_004 [Elizabeth]]
ALL OCCUPANTS: HELLO. HELLO. NEW TICKET[n]AVAILABLE.
EXTERMINATE FOE: SCM-8801. LOCATION:[n]A.I.G.I.S.
EXTERMINATE FOE: SCM-8801. EXTERMINATE[n]FOE: SCM-8801...

[msg MSG_005 [Junpei]]
What's with the robot-speak...?

[msg MSG_006 [Akihiko]]
"SCM-8801," huh? That's the executioner[n]robot.

[msg MSG_007 [Elizabeth]]
The FOE presented a deadly threat to you[n]before, but I believe it should now be a[n]more reasonable challenge.
Why don't you all test your strength[n]against it?

[sel SEL_008 top]
Let's do it.
I don't know...

[msg MSG_009 [Akihiko]]
Yeah, it's got my attention. There's[n]nothing like a powerful opponent to help[n]you get stronger.

[msg MSG_010 [Akihiko]]
What's wrong? It's unlike you to[n]hesitate. I don't think it'll give us a[n]hard time.

[msg MSG_011 [Junpei]]
Uh-oh, I know that look on his face...[n]He never changes, huh?

[msg MSG_012 [Yukari]]
Hahah, well, this is Akihiko-senpai[n]we're talking about. Maybe he can help[n]you toughen up.

[msg MSG_013 [Akihiko]]
What do you think, Junpei? With my[n]training, we could push you to your[n]limits.

[msg MSG_014 [Junpei]]
Huh!? Wait, where did THAT come from!?

[msg MSG_015 [Akihiko]]
Don't hold back. There are some places[n]where only intense, painful training can[n]bring you to...
Let's push ourselves, Junpei! We'll[n]reach those heights together!

[msg MSG_016 [Junpei]]
Crap, he's totally in the zone right[n]now...
You'll pay for this, Yuka-tan! Well, now[n]that there's no escape... uh...

[msg MSG_017 [Kanji]]
You okay, Junpei-san? You're lookin'[n]awfully shifty.

[msg MSG_018 [Junpei]]
Ah! Kanji! Perfect timing!
Look, buddy, nothing personal... I got[n]nothing against you, but if I go down,[n]I'm takin' you with me!

[msg MSG_019 [Kanji]]
Wh-What're you talkin' about?

[msg MSG_020 [Junpei]]
This guy's way too hot for me to handle![n]But you're pretty buff, right? C'mon,[n]help me out!

[msg MSG_021 [Kanji]]
H-Hot? Buff?
What, I gotta "handle" hot and sweaty[n]guys!? This look like a goddamn sauna to[n]you!?

[msg MSG_022 [Junpei]]
Wh-Where did that come from?

[msg MSG_023 [Kanji]]
Uh, nothin'. My bad.
It was somethin' about FOEs and training[n]and that kinda crap, right?

[msg MSG_024 [Junpei]]
Yeah! That's the one. Come on, we're[n]bros, right? We can both train! Go for[n]the gold! Reach for the stars!

[msg MSG_025 [Kanji]]
Look, I dunno what you're talkin' about,[n]but I wouldn't mind training...

[msg MSG_026 [Junpei]]
Phew, you're a standup guy...![n]Akihiko-senpai! We got another one in[n]the club!

[msg MSG_027 [Kanji]]
Man, how do I always get roped into this[n]crap...?

