[msg MSG_000 [Ryuji]]
Let's see, this is near where the mark[n]on the map was... right?

[msg MSG_001 [Junpei]]
And there are flowers here! All right,[n]let's shake 'em down!

[msg MSG_002 [Yosuke]]
Hey, we're looking for a "black thing."[n]Any of you seen it around here?

[msg MSG_003 [Shrill Flower]]
Oh my my my, look at all of you. You're[n]looking for the "black thing," you say?

[msg MSG_004 [Smiling Flower]]
Yes, yes, we know it oh-so-well. Listen[n]close, and I will tell...
Along a dark, blocked path, a house[n]stands a-swirl in wrath. Seen through a[n]door, infused with evil long ignored.

[msg MSG_005 [Ryuji]]
Okay, somewhere in that silly muddle I[n]heard about a house through a door? On a[n]blocked path?
Like one of those dead ends that only[n]appear in special screenings?

[msg MSG_006 [Yosuke]]
All right, let's keep going! No time to[n]stop and smell the roses!

[msg MSG_007 [Shrill Flower]]
Oh, but you must take care, great care.
They want it all to themselves, all to[n]themselves... And they wait... Lurking[n]in the dark recesses of that house.

[msg MSG_008 [Smiling Flower]]
They won't let you have it. Never[n]ever...

[msg MSG_009 [Hikari]]
Wha...?

[msg MSG_010 [P4 Hero]]
This isn't going to be as easy as we[n]hoped.

[msg MSG_011 [P3 Hero]]
Or as safe, it sounds like. Are they[n]talking about Shadows waiting for us?

[msg MSG_012 [Hikari]]
...Maybe we should just leave...

[sel SEL_013 top]
Are you giving up?
Are you scared?

[msg MSG_014 [Hikari]]
Yes... I don't want to put everyone in[n]danger for my sake.

[msg MSG_015 [Hikari]]
No. I'm fine, as long as you're all[n]here.
But I don't want to put everyone in[n]danger just for my sake.

[msg MSG_016 [Junpei]]
Hikari, dickory, dock, don't worry 'bout this[n]petal-talk! Seriously... we'll protect you;[n]the flowers are just scaredy-plants.
Just leave it all to Junpei Iori and[n]seeds. Uh, SEES!

[msg MSG_017 [Yosuke]]
That's right. We made you a promise,[n]didn't we?
The customer is always right! That's the[n]mentality I learned at Junes!

[msg MSG_018 [Hikari]]
Iori-kun, Hanamura-kun...

[msg MSG_019 [Ryuji]]
Heck, with this many people, we'll send[n]those Shadows home crying to their[n]Shadow mommies.
The Phantom Thieves don't abandon[n]anyone.

[sel SEL_020 top]
That's right.
All for one and one for all!

[msg MSG_021 [Ryuji]]
Yeah! We can't turn down a request from[n]a friend, after all.

[msg MSG_022 [Ryuji]]
Hell yeah! We can't turn down a request[n]from a friend, after all.

[msg MSG_023 [Hikari]]
Friends...
Thank you... I'm so happy you're here[n]for me.

[msg MSG_024 [Junpei]]
Then let's leave this music show and get[n]OUR show on the road!
Follow my lead, Pollen-hair and[n]Grump-face!

[msg MSG_025 [Ryuji]]
Who put you in charge, Mister[n]Inappropriate-to-Flowers?

[msg MSG_026 [Yosuke]]
Yeah, you offended them almost as much[n]as you offend us!

[msg MSG_027 [Junpei]]
I mean, they were being delicate little[n]flowers... literally!
Let's just go! Come on, you gotta keep[n]up, Hikari-chan!

[msg MSG_028 [Hikari]]
Okay!

[msg MSG_029 [Yukari]]
*sigh* Well, they're in good spirits.[n]Were those three always that close?

[msg MSG_030 [Ann]]
I think they just click because they're[n]all such goofballs!
At least it keeps them motivated, haha.

[msg MSG_031 [Chie]]
Hopefully they don't get too carried[n]away.

[msg MSG_032 [P4 Hero]]
Don't worry. Yosuke always comes through[n]when he needs to.

[msg MSG_033 [P3 Hero]]
We can count on Junpei as well. I think[n]things will work out.
Now then, we're looking for something in[n]a house, right?

[msg MSG_034 [Futaba]]
A house that's through a door. Let's get[n]house-hunting!

