[msg MSG_000 [Elizabeth]]
Ahora, para esta proyecciポn especial, buscarホn una posesiポn perdida, pero muy valiosa para Hikari...
El マnico inconveniente es que... ムnadie sabe qu〒 ha perdido!

[msg MSG_001 [Hikari]]
S〒 que era muy, muy especial.

[msg MSG_002 [Elizabeth]]
Objeto de Hikari, dポnde estホs, me pregunto que serホs...
En alguna escena de su pelボcula, una estrella de cine de verdad...
Pero me estoy desviando. Imagino que tendrホn que buscar posibles candidatos en la pelボcula.

[msg MSG_003 [Yosuke]]
メEn serio piensas que deberボamos ir sin ninguna idea de lo que estamos buscando?
Supongo que podemos encargarnos de la lucha y la exploraciポn, pero... メSabrホs lo que estamos buscando, Hikari?

[msg MSG_004 [Hikari]]
... Sボ, creo que me estoy empezando a acordar poco a poco. Perdポn por no ser mホs fiable.

[msg MSG_005 [Junpei]]
ムNo te sientas culpable! ムRelax, relax!

[msg MSG_006 [Makoto]]
Entonces la pelボcula en la que entramos es "Hikari", メcierto?
メPuedes al menos recordar en qu〒 lugar de la pelボcula podrボa estar?

[msg MSG_007 [Hikari]]
Lo siento... No lo s〒...

[msg MSG_008 [Elizabeth]]
Y con esa nota desalentadora, pongamos toda la atenciポn en mボ ahora, メde acuerdo?
Segマn este libro supersecreto que nunca sale de mis manos...
Las flores de esa pelボcula podrボan darles una pista sobre el paradero de su presa.

[msg MSG_009 [Ryuji]]
メLas flores? メTe refieres a esas cosas con cara? メEsos que parecボan juguetes que cantaban?

[msg MSG_010 [Hikari]]
メPueden dar pistas? メA qu〒 te refieres?

[msg MSG_011 [Elizabeth]]
メQue a qu〒 me refiero? Ni yo lo s〒, je, je. Tendrホn que ir y verlo.

[msg MSG_012 [Junpei]]
ムSボ, lo averiguaremos una vez que lleguemos allボ, chicos! Quiero decir, ver para creer, メno?
Uh, ムsiempre y cuando alguien averigüe cポmo llegar allボ! メA dポnde vamos otra vez?

