[msg MSG_000 [Chie]]
There are the fruits! Boy, they look[n]delicious!

[msg MSG_001 [Akechi]]
Looks like they're around these dead[n]ends.

[msg MSG_002 [Aigis]]
Elizabeth informed us that there are[n]four locations in total.
There are three areas remaining. Let us[n]proceed while watching for Shadows.

[msg MSG_003 [Yosuke]]
All right, that's the second one.

[msg MSG_004 [Makoto]]
Sure is hard to find these without any[n]hints. And the next one could be worse.

[msg MSG_005 [Naoto]]
Don't get too anxious. It has to be[n]somewhere.
There are only two more locations. Let's[n]keep going.

[msg MSG_006 [Haru]]
This is the third! Only one more to go!

[msg MSG_007 [Mitsuru]]
*chuckle* It's a strange feeling.
Instead of running around like crazy,[n]I'm walking and thinking to myself, "Ah,[n]what a nice little stroll this is."

[msg MSG_008 [Yusuke]]
Indeed... It's relaxing. We should thank[n]Elizabeth.

[msg MSG_009 [P3 Hero]]
I doubt she put that much thought into[n]this, but let's enjoy it while we can.
The next one is going to be the last.

[msg MSG_010 [Futaba]]
Aaaand that's the last one! Thus ends[n]the dangerous fruit-collecting mission!

[msg MSG_011 [Ken]]
We walked a long way, and I don't even[n]feel tired.

[msg MSG_012 [Koromaru]]
Bark bark!

[msg MSG_013 [Aigis]]
Koromaru-san says he's happy that he[n]didn't have to beg to go on a walk.
But we must head back now. Elizabeth is[n]waiting for our return.

