[msg MSG_000 [Elizabeth]]
Recorrer un mundo de cuento de hadas recolectando fruta...
Dios mボo, era como un sueワo en la pantalla. Estaba tan relajada que me estaba quedando dormida... Oh, メhe dicho eso en voz alta?
Eso fue una exageraciポn juguetona. Lo que querボa decir es que disfrut〒 mucho de una experiencia tan tranquila y agradable.

[msg MSG_001 [Yosuke]]
Ella estaba durmiendo.

[msg MSG_002 [Ken]]
Definitivamente.

[sel SEL_003 top]
Fue una misiポn divertida.
Fue un fastidio.

[msg MSG_004 [P3 Fem Protag]]
Lo マnico que hicimos fue pasear, pero me lo pas〒 bien igualmente.

[msg MSG_005 [Morgana]]
Y proporcionポ tiempo de calidad para hablar con los compaワeros, algo importante que se olvida en un grupo de este tamaワo.

[msg MSG_006 [P3 Fem Protag]]
*risita* FUE un largo paseo en el que no ocurriポ gran cosa.
Pero pudimos relajarnos un poco. Y pude hablar con todo el mundo.

[msg MSG_007 [P4 Hero]]
Entonces supongo que no estuvo tan mal. Parece que al menos subiポ la moral de todos.
Asボ que gracias, Elizabeth.

[msg MSG_008 [Elizabeth]]
*risita* ... No tienen que agradec〒rmelo.
Mi recompensa fue tiempo para descansar, mホs moral y, por supuesto...
ムUn montポn de fruta reci〒n recogida!
Me voy a comer todo esto, y entonces la misiポn estarホ completa.

[msg MSG_009 [P3 Hero]]
Esa es Elizabeth, tan astuta como siempre...

