[msg MSG_000 [Chie]]
ムAhボ estホn las frutas! ムVaya, se ven deliciosas!

[msg MSG_001 [Akechi]]
Parece que estホn por estos callejones sin salida.

[msg MSG_002 [Aigis]]
Elizabeth nos informポ de que habボa cuatro localizaciones en total.
Aマn quedan tres zonas. Prosigamos mientras estamos pendientes de las Sombras.

[msg MSG_003 [Yosuke]]
Muy bien, esa es la segunda.

[msg MSG_004 [Makoto]]
Seguro que es difボcil encontrarlas sin ninguna pista. Y la siguiente podrボa ser aマn peor.

[msg MSG_005 [Naoto]]
No est〒s tan inquieta. Tiene que estar en algマn lugar.
Ya solo quedan dos lugares. Sigamos.

[msg MSG_006 [Haru]]
ムEsta es la tercera! ムSolo falta una!

[msg MSG_007 [Mitsuru]]
*risita* Es una sensaciポn extraワa.
En vez de correr como loca, voy andando y pensando: "Ah, qu〒 paseo mホs agradable".

[msg MSG_008 [Yusuke]]
En efecto... Es relajante. Deberボamos de agradec〒rselo a Elizabeth.

[msg MSG_009 [P3 Hero]]
Dudo que ella haya pensado mucho en esto, pero disfrutemos mientras podamos.
La siguiente serホ la マltima.

[msg MSG_010 [Futaba]]
ムYyyyyy esta es la マltima! ムAsボ termina la peligrosa misiポn de recolectar fruta!

[msg MSG_011 [Ken]]
Hemos caminado mucho y aun asボ no me siento cansado.

[msg MSG_012 [Koromaru]]
ムBark bark!

[msg MSG_013 [Aigis]]
Koromaru dice que estホ feliz de no haber tenido que suplicar para ir de paseo.
Pero ahora debemos regresar. Elizabeth nos estホ esperando.

