[msg MSG_000 [Elizabeth]]
Bien hecho, todos. Trajiste la[n]proyecci吋n a un final agradable. Muy los[n]auteurs del cine, todos ustedes lo son.
Aqu胤 est茨 tu recompensa.

[msg MSG_001 [Margaret]]
Me gustar胤a agradecerle personalmente[n]tambi姻n. Fue amable de tu parte cumplir[n]con la petici吋n de Marie.
夷Marie? 夷No tienes algo que darles?

[msg MSG_002 [Marie]]
Bueno... Hay esto...

[sel SEL_003 top]
夷Qu姻 pasa?
夷Nos est茨s dando algo?

[msg MSG_004 [Marie]]
斡N-n-N-nada! 斡No es nada!
Definitivamente no es como si te[n]estuviera agradeciendo o algo as胤, por[n]dejarme entrar contigo en la pel胤cula.

[msg MSG_005 [Marie]]
夷Eh? Bueno... ya sabes...
Quiero decir, no es como si me estuviera[n]sintiendo feliz que me dejaras acompa隠ar[n]dentro de la pel胤cula o algo as胤.

[msg MSG_006 [Marie]]
El punto es... Gracias. Quiero que[n]tengas esto.

[msg MSG_007 [Futaba]]
びよぽぺわウぺ れもむゎもまょぽよ まゅ ぼゅァれもぼよ むゎもカょ ぽま びれゎょぽまるま[n]ぺ ゅぺ ぼぺるろぺテテテ ぴょ らるウれぼゎゅよ まゑろまるもよる まれぼよょぽま ゎょ[n]もょろまるもよる れゎぺわま を るよゆァょろもぼよテテテ

[msg MSG_008 [P4 Hero]]
Por cierto, Marie, 夷Terminaste tu poema?

[msg MSG_009 [Marie]]
S胤, creo que est茨 casi hecho...
斡No! 斡No es un poema! Es m茨s como... una[n]expresi吋n de patos...

[msg MSG_010 [Akechi]]
夷No es b茨sicamente un poema?

[msg MSG_011 [Marie]]
斡No, no es as胤! 斡Tienes miedo de que[n]seas el peor!

[msg MSG_012 [P4 Hero]]
Sin embargo, nos encantar胤a ver el[n]producto terminado en alg雨n momento.

[sel SEL_013 top]
S胤, esperando.
夷Aunque la tortura?

[msg MSG_014 [P4 Hero]]
斡Por supuesto!

[msg MSG_015 [P4 Hero]]
... Tienes raz吋n.

