[msg MSG_000 [Singing flower]]
Este es mi santuario... Escondido de todos.

[msg MSG_001 [Marie]]
Por siempre invisible para ti, mientras mホs me enamoro. Es aquボ, en este... en este... ムTengo que decir qu〒 es el santuario!

[sel SEL_002 top]
Un lugar para dormir, y soワar...
Solo tu propia habitaciポn.
Un templo.

[msg MSG_003 [Marie]]
メUn lugar para dormir y soワar? メComo soワar con el amado?
Sボ, puedes codiciar la dulce fruta prohibida, y soワar con ella convierte cualquier lugar donde duermas en tu santuario...

[msg MSG_004 [Marie]]
Claro, esa es la idea. Pero mホs que en tu habitaciポn, en un verdadero santuario es imposible que entre nadie mホs.
El lugar en el que es fボsicamente imposible que entre nadie son tus sueワos. Asボ que el santuario es la cama...

[msg MSG_005 [Marie]]
Eso estホ cerca. Un templo es un lugar especial, pero necesito un lugar donde solo yo pueda entrar. Como... ムMis sueワos! ムEn mi propia cama!
Sボ, puedes codiciar la dulce fruta prohibida, y soワar con ella convierte cualquier lugar donde duermas en tu santuario...

[msg MSG_006 [P3 Hero]]
Oye, estホ en racha.

[msg MSG_007 [Marie]]
Cuando estoy contigo, me disfrazo de ホngel, aunque la envidia arda en mi interior...
No soy mホs que una chica inocente que no puede evitar su amor... Sabes, creo que esta es mi mayor obra maestra hasta ahora...

[sel SEL_008 top]
Eso fue un verdadero pathos.
Qu〒 inspirador.

[msg MSG_009 [Marie]]
ムAAAAAAAHHH! ムメP-P-Por qu〒 todos me estaban escuchando?!

[msg MSG_010 [Yusuke]]
Bueno, lo estabas diciendo todo en voz alta...
Y ademホs, メde verdad quieres negarle al mundo tu arte? メTus hermosas palabras que hacen que a uno le tiemblen las rodillas?

[msg MSG_011 [Marie]]
ムLa adulaciポn no te llevarホ a ninguna parte! ... メDe verdad crees que es hermoso?

[msg MSG_012 [Marie]]
ムQuiero decir, no me importa! Vamos, volvamos ya. Estoy cansada.

[msg MSG_013 [P4 Hero]]
*risita* Claro, vホmonos.

