[msg MSG_000 [Flor Cantando]]
Este es mi santuario... Escondido de[n]todos.

[msg MSG_001 [Marie]]
はぺるぺ れもまゆらるま もょわもれもほゅま らよる ろもデ ぼよゆよ ゆァれ まょ まゅ[n]ぺゆよる ゆま ぼぺもむよテ つれろァ ぺりゎウデ まょ まれろよテテテ まょ[n]まれろまテテテ ィねまぼまれもろよ ぽまぼもる ゅよ りゎま まれ まゅ[n]れぺょろゎぺるもよ!

[sel SEL_002 top]
Un lugar para dormir, y so隠ar...
S吋lo tu propia habitaci吋n.
Un santuario.

[msg MSG_003 [Marie]]
夷Un lugar para dormir y so隠ar? 夷Como el[n]sue隠o del amado?
S胤, puedes codiciar la fruta dulce,[n]prohibida y so隠ar con ella hace donde[n]duermas tu santuario...

[msg MSG_004 [Marie]]
Claro, esa es la idea. Pero a雨n m茨s que[n]tu habitaci吋n, un verdadero santuario es[n]imposible para que alguien m茨s entre.
ィつゅ ゅゎむぺる りゎま まれ みウれもぼぺゆまょろま もゆらよれもほゅま らぺるぺ[n]りゎま ぺゅむゎもまょ ゆァれ まょろるま まょ ろゎれ れゎまォよれ! だれウ りゎま[n]まゅ れぺょろゎぺるもよ まれ ゎょぺ ぼぺゆぺテテテ

[msg MSG_005 [Marie]]
つれろァ ぼまるぼぺテ ぴょ れぺょろゎぺるもよ まれ ゎょ ゅゎむぺる まれらまぼもぺゅデ[n]らまるよ ょまぼまれもろよ ゎょ ゅゎむぺる ぽよょぽま れカゅよ らゎまぽよ[n]まょろるぺるテ ぢよゆよテテテ ゆもれ れゎまォよれ! ィつょ ゆも らるよらもぺ[n]ぼぺゆぺ!
S胤, puedes codiciar la fruta dulce,[n]prohibida y so隠ar con ella hace donde[n]duermas tu santuario...

[msg MSG_006 [P3 Hero]]
Est茨 en un rollo.

[msg MSG_007 [Marie]]
Cuando estoy contigo, me disfrazo de[n]茨ngel incluso como la envidia quema[n]dentro de m胤...
Soy un inocente que no puede ayudar a su[n]amor pecaminoso... Sabes, creo que esta[n]es mi mayor obra maestra a雨n...

[sel SEL_008 top]
Eso fue verdaderos patos.
Qu姻 inspirador.

[msg MSG_009 [Marie]]
斡GYAAAAAH! 夷Por qu姻 me escuchaste?

[msg MSG_010 [Yusuke]]
Bueno, estabas diciendo todo en voz[n]alta...
Y adem茨s, 夷realmente quieres negar al[n]mundo tu arte? 夷Tus hermosas palabras[n]que hacen d姻bil a uno en las rodillas?

[msg MSG_011 [Marie]]
斡La adulaci吋n no te llevar茨 a ning雨n[n]lado! 夷Realmente crees que es hermoso?

[msg MSG_012 [Marie]]
斡No me importa! Vamos, volvamos, ya.[n]Estoy cansada.

[msg MSG_013 [P4 Hero]]
*chuckle* Claro, vamos.

