[msg MSG_000 [Teddie]]
Time to pay for your crimes! Come[n]quietly and no one gets hurt!

[msg MSG_001 [Ryuji]]
So what do we do? Just charge in and[n]grab it?

[msg MSG_002 [Hikari]]
Wait... You might scare it again.
Come here.

[msg MSG_003]
The butterfly grew smaller, and landed[n]on Hikari's finger...

[msg MSG_004 [Hikari]]
Hee hee... Aw, you're so cute.

[msg MSG_005 [Yukari]]
Whoa! Hikari-chan, that was amazing! How[n]did you do that!?

[msg MSG_006 [Hikari]]
Well... I just sort of wanted to do it,[n]and it happened. Maybe because it's my[n]movie...

[sel SEL_007 top]
Good going.
You surprised me.
Adorable...

[msg MSG_008 [Hikari]]
Thank you, Joker. I'm just glad I could[n]help.

[msg MSG_009 [Hikari]]
*giggle* I surprised myself, too.

[msg MSG_010 [Hikari]]
U-Um―
O-Oh, the butterfly... Yeah. I think[n]it's cute too.

[msg MSG_011 [Junpei]]
A gorgeous girl, and a pretty little[n]butterfly on her finger. Like a princess[n]right outta Destinyland...

[msg MSG_012 [Morgana]]
All right. We got the butterfly! Mission[n]accomplished!
Let's go home.

[msg MSG_013 [Teddie]]
Look over here! This place is chock-full[n]of flowers!

[msg MSG_014 [Haru]]
You're right! What a lovely scent,[n]too... It really is a wonderful place.

[msg MSG_015]
There are colors all around us, and it[n]smells like a fresh garden...

[msg MSG_016 [Yosuke]]
Hey, we've been walking for ages. Why[n]don't we take a break here?

[sel SEL_017 top]
Sounds good.
Better head back...

[msg MSG_018 [Teddie]]
Hurray! Kick back for snacktime!

[msg MSG_019 [P4 Hero]]
We might as well relax. It's a nice[n]place to do it.

[msg MSG_020 [Teddie]]
Huh? Aw, Joker, are you homesick?
C'mon, it'll just be for a little bit! I[n]wanna have a picnic with everyone!

[msg MSG_021 [P4 Hero]]
Sorry. Do you mind letting Teddie have[n]this?

[msg MSG_022]
We decided to take a break in this[n]location...

[msg MSG_023 [Teddie]]
Oh! I see a butterfly!

[msg MSG_024 [Ann]]
There's a lot here, too. Probably going[n]for the flowers, I guess.

[msg MSG_025 [Teddie]]
They're all so gorgeous!
I wanna catch butterflies like Hikarin!

[msg MSG_026 [Teddie]]
C'mon over, gang! Just follow my[n]pheromones!

[msg MSG_027]
The butterflies are swarming...

[msg MSG_028 [Hikari]]
...!
Teddie, no! Get back!

[msg MSG_029 [Fuuka]]
I'm sensing a lot of Shadows nearby all[n]of a sudden! Everyone, get ready to[n]defend yourselves!

[msg MSG_030 [Futaba]]
They're all Shadows! Here they come!

