[msg MSG_000 [Elizabeth]]
Muchas gracias por obtener lo que ped胤.
Esto es hermoso. Me encargar姻 de ello.

[msg MSG_001 [Hikari]]
Me alegra que te guste... Trabajamos muy[n]duro para atraparlo.

[sel SEL_002 top]
夷Qu姻 har茨s con eso?
夷Te gustan las mariposas?

[msg MSG_003 [Elizabeth]]
Nada en particular. Aunque...
Me gustar胤a pasar un tiempo relajando,[n]viendo bailar en vuelo.

[msg MSG_004 [Elizabeth]]
Supongo que podr胤as decir eso.
Verlo tejer y bailar en el aire inspira[n]cierta calma.

[msg MSG_005 [Yukari]]
Se puso un poco conmovedor cerca del[n]final, pero creo que lo disfrut姻.
Vamos otra vez, Hikari.

[msg MSG_006 [Hikari]]
Gracias... Yo tambi姻n me divert胤. Espero[n]que me dejes venir contigo otra vez.

