[msg MSG_000 [Ann]]
Tantos cines...
Ella es la que hizo todo esto, 夷verdad?

[msg MSG_001 [Naoto]]
夷Dijo que era algo dado forma f胤sica? Y[n]mencion吋 el inconsciente colectivo,[n]tambi姻n...

[msg MSG_002 [Teddie]]
夷Qu姻 es un inconsciente? 夷Es como so隠ar?

[msg MSG_003 [Morgana]]
によれ ぽまれまよれ もょぼよょれぼもまょろまれ まれろァょ まょろまるるぺぽよれ[n]ぽまょろるよ ぽま ゅよれ ぼよるぺんよょまれ めゎゆぺょよれデ ろよろぺゅゆまょろま[n]れまらぺるぺぽよれ ぽま れゎ ゆまょろま ぼよょれぼもまょろまテ
Un sue隠o s吋lo te muestra un parpadeo de[n]esa voluntad inconsciente. Es como un[n]mensaje de tu propia mente.
Bueno, eso puede ser demasiado profundo[n]para los aficionados...

[msg MSG_004 [Mitsuru]]
Est茨s muy bien informado. 夷D吋nde[n]aprendiste todo esto?

[msg MSG_005 [Morgana]]
斡Es sentido com雨n! 斡Cuando eres un[n]experto como yo, viene naturalmente!
Espera, 夷c吋mo est茨? 夷Lo s姻?

[msg MSG_006 [Ryuji]]
*Suspira...* A veces no s姻 nada de ti.

[msg MSG_007]
Una nueva proyecci吋n especial: "La[n]mariposa perdida" se ha a隠adido a la[n]taquilla.

