[msg MSG_000 [Hikari]]
ムAllボ! ムJusto en ese agujero!
メEh? ムEspera!

[msg MSG_001]
La mariposa bajポ por el agujero...

[msg MSG_002 [Teddie]]
ムGrrr! ムEsa mariposa no sabe cuホndo rendirse!

[msg MSG_003 [Hikari]]
Quizホs vio a toda la gente que estamos y se asustポ...

[msg MSG_004 [Yukari]]
Quiero perseguirla, pero no podemos bajar por aquボ.

[sel SEL_005 top]
Demos un rodeo.
Encontremos el interruptor.

[msg MSG_006 [Hikari]]
Cierto. Si vamos a la planta de abajo, seguro que podremos encontrarla de nuevo.

[msg MSG_007 [Morgana]]
ムMuy bien! ムEntonces busquemos un interruptor y sigホmosla!

