[msg MSG_000 [Ryuji]]
Maldita sea, un callej吋n sin salida.
Sab胤a que deb胤amos tomar ese giro[n]derecho... El retroceso es un dolor.

[msg MSG_001 [Futaba]]
Deja de quejarte, Skull. 夷Qu姻 tiene de[n]malo tomar la ruta esc姻nica?

[msg MSG_002 [Ann]]
ィひウ! ひもまゆらるま りゎま ろま らもまるぽまれ まょ ゅぺ ぼもゎぽぺぽデ[n]れもまゆらるま まょぼゎまょろるぺれ ぺゅむゎょぺ ょゎまわぺ ろもまょぽぺ りゎま[n]ょゎょぼぺ ろま めぺれ ぽぺぽよ ぼゎまょろぺ ぺょろまれ!

[msg MSG_003 [Naoto]]
Y algo similar podr胤a suceder dentro de[n]las pel胤culas, supongo.
Lo que primero percibimos como un desv胤o[n]innecesario puede llevar a algo 雨til.
Y el viaje extra nos da la oportunidad[n]de ganar m茨s experiencia de combate, as胤[n]que no es todo malo.

[msg MSG_004 [Ryuji]]
Bueno, supongo que nunca habr胤amos[n]llegado tan lejos sin un par de giros[n]equivocados en el camino...
Mejor da la vuelta, de todos modos.[n]Vamos, Joker.

[msg MSG_005]
Una nueva proyecci吋n especial: "A Look[n]Inward" se ha a隠adido a la taquilla.

