[msg MSG_000 [Teddie]]
夷Eh? 夷Esto es un callej吋n sin salida?[n]斡Entonces eso significa que hemos[n]terminado!

[msg MSG_001 [Junpei]]
Espera un segundo. 夷Y si este objetivo[n]es una trampa?
夷Va a abrir el piso y dejarnos abajo un[n]pozo de pico o algo as胤?

[msg MSG_002 [Junpei]]
斡Gah! 夷Qu姻?

[msg MSG_003 [Voz Sonora]]
Bien hecho, todos. Has alcanzado el[n]objetivo.

[msg MSG_004 [Junpei]]
Eso me asust吋... Es la se隠ora de[n]antes...

[msg MSG_005 [Voz Sonora]]
Observ姻 las decisiones que tomaste, y[n]las encontr姻 bastante intrigantes.
Tal vez ya est茨s al tanto, pero no hubo[n]respuesta correcta a las preguntas que[n]le胤ste.
Simplemente quer胤a saber c吋mo pensar胤as,[n]y lo que sentir胤as en respuesta a ellos.

[sel SEL_006 top]
Fue interesante.
Dej吋 un mal gusto.

[msg MSG_007 [Voz Sonora]]
Hmhm... Me alegra que hayas disfrutado.
Estoy seguro de que el tiempo que[n]pasaste deliberando no fue[n]desperdiciado.

[msg MSG_008 [Voz Sonora]]
夷Oh? 夷No fue por tu gusto?
びぺゅ わまん ゅぺれ らるまむゎょろぺれ まるぺょ ゎょ らよぼよ ぽもみウぼもゅまれデ[n]らまるよ まれぺ まゑろるまゆもぽぺぽ れカゅよ まれろぺほぺ ぽまれろもょぺぽぺ ぺ[n]らるよわよぼぺる るまれらゎまれろぺれ れまるもぺれテ

[msg MSG_009 [Voz Sonora]]
つょ ぼゎぺゅりゎもまる ぼぺれよデ ぼよゆよ ゆも ぺむるぺぽまぼもゆもまょろよ らよる[n]ゎょ まれらまぼろァぼゎゅよ ろぺょ みぺれぼもょぺょろまデ めま らるまらぺるぺぽよ ゎょ[n]るまむぺゅよ ゆよぽまれろよテ

[msg MSG_010 [Voz Sonora]]
Parece que eres un pensador muy l吋gico.
夷Mantendr胤as esa fortaleza en una[n]crisis? 夷Actuar胤as con calma, sin sombra[n]por tensi吋n o emoci吋n?
Ahora, por favor acepta esto.

[msg MSG_011]
Hay algo en el suelo...
斡Recibido Logos Mirror!

[msg MSG_012 [Voz Sonora]]
Pareces ser gente muy amable. Pero m茨s[n]que eso...
Tienes una resoluci吋n inquebrantable[n]para proteger lo que es importante para[n]ti... Tal convicci吋n acerca a otros.
Ahora, por favor acepta esto.

[msg MSG_013]
Hay algo en el suelo...
斡Recibido Espejo Romano!

[msg MSG_014 [Voz Sonora]]
Pareces seguir tus instintos, y eres muy[n]honesto con tus sentimientos.
Tal intuici吋n naturalmente equilibrada[n]es seguro resonar con muchos otros.
Ahora, por favor acepta esto.

[msg MSG_015]
Hay algo en el suelo...
斡Recibido Sense Mirror!

[msg MSG_016 [Voz Sonora]]
Bueno, bueno... Usted exhibe una manera[n]雨nica de pensar de hecho. Es bastante[n]diferente a la mayor胤a de los dem茨s.
Son tales individuos que a menudo traen[n]la revoluci吋n al mundo. Recuerda[n]agudizar y confiar en esos instintos.
Ahora, por favor acepta esto.

[msg MSG_017]
Hay algo en el suelo...
斡Recibido Maverick Mirror!

[msg MSG_018 [Voz Sonora]]
Usted puede encontrar que su perspectiva[n]sobre estas opciones cambiar茨 con el[n]tiempo...
Si la oportunidad se presenta, te animo[n]a pensar en tus decisiones de nuevo.
Aunque nuestro tiempo era corto, no[n]obstante era una experiencia valiosa.
Ahora bien, les pido adi吋s a todos.

[msg MSG_019 [Junpei]]
Qu姻 voz sexy... Quienquiera que sea,[n]apuesto a que es una chica total.

[msg MSG_020 [Yukari]]
Ugh. 夷Esa es la primera cosa de tu boca?[n]Tenemos que encontrar un carrito para[n]presionarte.

[msg MSG_021 [Chie]]
Sheesh, he tenido pruebas que fueron m茨s[n]f茨ciles que esas dos preguntas measly!

[msg MSG_022 [Akechi]]
Estaban bastante emocionados.
Adem茨s, tenemos una visi吋n de c吋mo[n]piensa Joker. Me gust吋 mucho eso.

[msg MSG_023 [Morgana]]
Parece que es el final. Ya era hora de[n]volver.

