[msg MSG_000 [Teddie]]
Huh? Is this a dead end? Then that means[n]we're done!

[msg MSG_001 [Junpei]]
H-Hey, wait a sec. What if this goal is[n]a trap...?
Is the floor gonna open up and drop us[n]down a spike pit or something...?

[msg MSG_002 [Junpei]]
Gah! What!?

[msg MSG_003 [Sonorous voice]]
Well done, everyone. You have reached[n]the goal.

[msg MSG_004 [Junpei]]
*sigh* That scared me... It's just that[n]lady from before...

[msg MSG_005 [Sonorous voice]]
I observed the choices you made, and I[n]found them quite intriguing.
Perhaps you're already aware, but there[n]was no right answer to the questions you[n]read.
I simply wanted to know how you would[n]think, and what you would feel in[n]response to them.

[sel SEL_006 top]
It was interesting.
It left a bad taste.

[msg MSG_007 [Sonorous voice]]
Hmhm... I'm certainly glad you enjoyed.
I'm certain the time you spent[n]deliberating was not wasted.

[msg MSG_008 [Sonorous voice]]
Oh? Was it not to your liking?
Perhaps the questions were a bit dire,[n]but that extremity was only meant to[n]provoke serious answers.

[msg MSG_009 [Sonorous voice]]
In any case, as my thanks for such a[n]fascinating show, I've prepared a modest[n]gift.

[msg MSG_010 [Sonorous voice]]
It seems you're a very logical thinker.
Would you maintain that fortitude in a[n]crisis? Would you act with calm,[n]unclouded by tension or emotion?
Now, please accept this.

[msg MSG_011]
There's something on the ground...
Received Logos Mirror!

[msg MSG_012 [Sonorous voice]]
You seem to be very kindhearted people.[n]But more than that...
You have an unwavering resolve to[n]protect what's important to you... Such[n]conviction draws others closer.
Now, please accept this.

[msg MSG_013]
There's something on the ground...
Received Roman Mirror!

[msg MSG_014 [Sonorous voice]]
You seem to follow your instincts, and[n]you are very honest with your feelings.
Such naturally balanced intuition is[n]sure to resonate with many others.
Now, please accept this.

[msg MSG_015]
There's something on the ground...
Received Sense Mirror!

[msg MSG_016 [Sonorous voice]]
Well, well... You exhibit a unique way[n]of thinking indeed. It's quite unlike[n]most others.
It is such individuals who often bring[n]revolution to the world. Remember to[n]sharpen and trust those instincts.
Now, please accept this.

[msg MSG_017]
There's something on the ground...
Received Maverick Mirror!

[msg MSG_018 [Sonorous voice]]
You may find that your perspective on[n]these choices will change with time...
Should the opportunity present itself, I[n]encourage you to think on your decisions[n]again.
Though our time was short, it was[n]nonetheless a valuable experience.
Now then, I bid you all farewell.

[msg MSG_019 [Junpei]]
*sigh* What a sexy voice... Whoever she[n]is, I bet she's a total babe.

[msg MSG_020 [Yukari]]
Ugh. That's the first thing out of your[n]mouth? We need to find a cart to push[n]YOU under.

[msg MSG_021 [Chie]]
Sheesh, I've had tests that were easier[n]than those two measly questions!

[msg MSG_022 [Akechi]]
They were rather thought-provoking.
Plus, we got a glimpse of the way Joker[n]thinks. I quite enjoyed that.

[msg MSG_023 [Morgana]]
Looks like that's the end of it. It's[n]about time we headed back.

