[msg MSG_000 [Elizabeth]]
Now then, the goal of this special[n]screening...
You must reach the designated area in[n]Hikari's movie. Quite a simple[n]objective.
...Oh?

[msg MSG_001 [Shinjiro]]
What?

[msg MSG_002 [Elizabeth]]
Well, there is a note here that says[n]"you may take either path."

[sel SEL_003 top]
What does that mean?
What's with the note?

[msg MSG_004 [Elizabeth]]
I can't say... I don't know anything[n]about the screening beyond what's[n]documented here.

[msg MSG_005 [Mitsuru]]
Does that mean that there are multiple[n]paths to this goal...?

[msg MSG_006 [Akihiko]]
Maybe they're sending us to either hell[n]or purgatory, and it's up to us to pick.

[msg MSG_007 [Yosuke]]
Dude, this is weird enough without these[n]crazy ideas...

[msg MSG_008 [Kanji]]
Well, can't just stand here thinkin'[n]about it. We'd better go take a look.

[msg MSG_009 [Koromaru]]
Arf!

