[msg MSG_000 [Elizabeth]]
ィぴょ ぼぺるるもろよ みゎまるぺ ぽまゅ ぼよょろるよゅ れま らるまよぼゎらぺ[n]めぺぼもぺ ゅよれ ろるぺほぺゃぺぽよるまれ ぼよょぽまょぺぽよれ! はまるよ まょ まゅ[n]グゅろもゆよ ゆよゆまょろよデ ぽまぼもぽま れゎ ぽまれろもょよ!
... Tal vez s吋lo fueron dos preguntas,[n]pero pueden haber mostrado una gran[n]comprensi吋n de sus corazones.
Mientras esto era un poco de salida de[n]las proyecciones especiales habituales,[n]disfrut姻 sin embargo.

[msg MSG_001 [Futaba]]
夷Pero qui姻n hizo esas se隠ales en primer[n]lugar? 夷Y qu姻 hay de la espeluznante[n]mujer que anuncia?

[msg MSG_002 [Junpei]]
En realidad, ahora que lo pienso, esa[n]voz sexy era un poco familiar...
夷Te suenan las campanas?

[sel SEL_003 top]
Ni idea.
夷Elizabeth?
Era familiar...

[msg MSG_004 [Junpei]]
斡Pero mi Babe Radar se est茨 volviendo[n]salvaje!
Alguien muy sexy, muy maduro, con ese[n]tipo de aura sofisticada para ella...

[msg MSG_005 [Elizabeth]]
Desafortunadamente, no fui yo.
つれ ゆァれ らるよほぺほゅま まょぼよょろるぺるゆま まょ ゆも ぺれもまょろよ[n]ぽゎるぺょろま ゅぺれ らるよをまぼぼもよょまれデ ぽまわよるぺょぽよ らぺゅよゆもろぺれ[n]ぽま ゆぺウん を めよろ ぽよむれ ぼよょ ろよろぺゅ ぺほぺょぽよょよテ

[msg MSG_006 [P4 Hero]]
Me alegra que haya disfrutado del[n]espect茨culo, como siempre.

[msg MSG_007 [Junpei]]
No, tengo la sensaci吋n de que es alguien[n]mayor y m茨s maduro que Elizabeth...

[msg MSG_008 [Junpei]]
Lo s姻, 夷verdad? Y sent胤 que era alguien[n]s雨per reciente, como justo despu姻s de[n]llegar a este Cine.
Alguien muy sexy, muy maduro, con ese[n]tipo de aura sofisticada para ella...

[msg MSG_009 [Elizabeth]]
Quiz茨 nunca sepamos la verdad. Pero en[n]cuanto a mi especulaci吋n sobre los[n]motivos del orquestador...
Creo que ella estaba intrigada por ti, y[n]fue impulsada por un deseo de comprender[n]mejor a todos ustedes.

[msg MSG_010 [P4 Hero]]
Bueno, s吋lo puedo esperar que tenga lo[n]que quer胤a fuera de ella.

[msg MSG_011 [Elizabeth]]
夷Qui姻n puede decir?
Espero que siga observando tus haza隠as[n]en los juicios por venir.
En cualquier caso, fue un espect茨culo[n]muy entretenido. Por favor, contin雨e con[n]el buen trabajo.

