[msg MSG_000 [Ann]]
夷Qu姻 es eso?

[msg MSG_001 [Yusuke]]
斡Silencio! Algo est茨 pasando.

[msg MSG_002 [Voz Sonora]]
Hola, y bienvenido.
Hoy tengo un poco de diversi吋n preparada[n]para ti.
Eso dijo, no es nada dif胤cil. Las reglas[n]son muy simples.
Adelante, ver茨s dos se隠ales. Cada uno[n]tiene una pregunta impresa en ellos.
Por favor responda a las preguntas,[n]luego proceda de acuerdo con sus[n]respuestas.
*chuckle* Me pregunto qu姻 pensar茨s, una[n]vez que veas d吋nde te guiar茨n tus[n]respuestas?

[msg MSG_003 [Ken]]
夷Se ha ido?

[msg MSG_004 [Ryuji]]
夷Qui姻n era? 夷Un enemigo?

[msg MSG_005 [Fuuka]]
No sent胤 ninguna hostilidad de ellos...[n]Parec胤a que s吋lo estaban explicando las[n]reglas.

[msg MSG_006 [Akihiko]]
エつょろよょぼまれ ろよぽよ ゅよ りゎま ろまょまゆよれ りゎま めぺぼまる まれ[n]るまれらよょぽまる らるまむゎょろぺれ れよほるま れもむょよれ? びまょぽるまゆよれ[n]りゎま わまる ゅぺれ らるまむゎょろぺれ らるもゆまるよテテテ

[msg MSG_007 [Morgana]]
De acuerdo, el primer orden de negocio[n]es encontrar esos signos. Vamos, Joker.

