[msg MSG_000 [Elizabeth]]
Ahora, el objetivo de esta proyecci吋n[n]especial...
Debes llegar al 茨rea designada en la[n]pel胤cula de Hikari. Un objetivo muy[n]simple.
...Oh?

[msg MSG_001 [Shinjiro]]
夷Qu姻?

[msg MSG_002 [Elizabeth]]
Bueno, hay una nota aqu胤 que dice[n]"puedes tomar cualquier camino"

[sel SEL_003 top]
夷Qu姻 significa eso?
夷Qu姻 pasa con la nota?

[msg MSG_004 [Elizabeth]]
No puedo decir... No s姻 nada sobre la[n]proyecci吋n m茨s all茨 de lo documentado[n]aqu胤.

[msg MSG_005 [Mitsuru]]
夷Eso significa que hay m雨ltiples caminos[n]a este objetivo...?

[msg MSG_006 [Akihiko]]
Tal vez nos env胤an al infierno o al[n]purgatorio, y depende de nosotros[n]escoger.

[msg MSG_007 [Yosuke]]
Amigo, esto es bastante raro sin estas[n]ideas locas...

[msg MSG_008 [Kanji]]
Bueno, no puedes estar aqu胤 pensando en[n]ello. Ser茨 mejor que echemos un vistazo.

[msg MSG_009 [Koromaru]]
斡Arf!

