[msg MSG_000 [Fuuka]]
斡Lo hiciste!
斡Lo lograste sin que la m雨sica se[n]desvaneciera!

[msg MSG_001 [Ann]]
Whew... Lo hicimos, de alguna manera.

[msg MSG_002 [Fuuka]]
S胤. Definitivamente lo cerramos, pero lo[n]que importa es que hayamos terminado.

[msg MSG_002_1 [Fuuka]]
斡Te ver姻 en el Cine!

[msg MSG_003 [P3 Fem Protag]]
Vale, ahora todo lo que tenemos que[n]hacer es entregar esto a Elizabeth!

[msg MSG_004 [Fuuka]]
斡Parece que acabaste con unos pasos para[n]ahorrar! Buen trabajo.
斡Te ver姻 en el Cine!

[msg MSG_005 [P3 Fem Protag]]
Vale, ahora todo lo que tenemos que[n]hacer es entregar esto a Elizabeth!

[msg MSG_006 [Fuuka]]
斡Terminaste con pasos para ahorrar! Buen[n]trabajo.
斡Te ver姻 en el Cine!

[msg MSG_007 [P3 Fem Protag]]
Vale, ahora todo lo que tenemos que[n]hacer es entregar esto a Elizabeth!

