[msg MSG_000 [P3 Fem Protag]]
S胤! 斡Lo logramos, chicos!

[msg MSG_000_1 [P3 Fem Protag]]
Realmente nos llevaste a trav姻s de esa[n]lucha, Joker. 斡Dir胤a que eso te[n]convierte en nuestro l胤der!

[msg MSG_001 [Haru]]
夷Oh? 夷Qu姻 es esto?

[msg MSG_002]
Hay algo en el suelo...

[msg MSG_003 [Morgana]]
Esa Sombra debe haber dejado esto.

[msg MSG_004 [Makoto]]
夷No es una pel胤cula? Est茨 casi[n]completamente cubierto de holl胤n, sin[n]embargo...

[msg MSG_005 [Morgana]]
Sea lo que sea, cuenta como un trofeo de[n]nuestra victoria!

[msg MSG_006]
斡Obtenido Sooty Film!

[msg MSG_007 [Makoto]]
Bueno, hemos logrado nuestro objetivo.[n]Vamos a informarle a Elizabeth.

