[msg MSG_000 [Elizabeth]]
, ha sido un espectホculo digno de un merecido "bravo".

[msg MSG_000_1 [Elizabeth]]
Incluso contra un enemigo que superaba todas mis expectativas, han actuado de forma magnボfica.

[msg MSG_001 [Ryuji]]
ムJe, je, je! Estamos hablando de nuestro lボder. メQu〒 te esperabas?

[msg MSG_002 [Elizabeth]]
Tu talento era notable al inicio, pero has hecho grandes progresos...

[msg MSG_002_1 [Elizabeth]]
Como alguien que controla el poder, estar〒 observando tu progreso con gran, gran inter〒s.
Miiiiiiiiira...

[msg MSG_003 [Elizabeth]]
メHm...?

[msg MSG_003_1 [Elizabeth]]
... Han encontrado algo realmente raro.

[msg MSG_004]
Parece que estホ hablando sobre esa pelボcula de hollボn que encontramos antes...

[msg MSG_005 [Elizabeth]]
Si no te importa, メpodrボa echarle un vistazo?

[msg MSG_006]
Le he entregado la "Pelボcula de Hollボn" a Elizabeth...

[msg MSG_007 [Elizabeth]]
...
Hmmmm.
Interesante. Muy interesante.

[msg MSG_008 [Morgana]]
メEs algo importante?

[msg MSG_009 [Elizabeth]]
 fue llamado especボficamente a esta proyecciポn especial para derrotar a un poderoso oponente...

[msg MSG_009_1 [Elizabeth]]
メPodrボa ser...?

[msg MSG_010 [Makoto]]
メQu〒 podrボa ser...?

[msg MSG_011 [Elizabeth]]
...

[msg MSG_011_1 [Elizabeth]]
Si mi teorボa es correcta, un poder extraordinario reside en ese objeto.
Tiene un gran potencial... lo bastante poderoso como para definir tu destino, [f 6 1 30 0 0 0], y el de tus amigos.

[msg MSG_012 [Ann]]
ムNo puede ser! ムEso suena increボble!

[msg MSG_013 [Akechi]]
Pero... parece igual que siempre.

[msg MSG_013_1 [Akechi]]
メQuiere decir eso que falta algマn elemento?

[msg MSG_014 [Elizabeth]]
Naturalmente, no puedo asegurarlo. Aunque... es una posibilidad.

[msg MSG_014_1 [Elizabeth]]
Si te parece bien, me gustarボa tomarme un tiempo para reflexionar.

[sel SEL_015 top]
Te lo dejamos a ti.
Estaremos esperando.

[msg MSG_016 [Elizabeth]]
ムPues bien! Me encargar〒 de descifrar sus secretos.
No duden en consultarme en el mostrador y les dir〒 si he hecho algマn progreso.

[msg MSG_017 [Futaba]]
Bueno, eso sボ que fue un giro. ムTodo depende de ti, Zabby!

[msg MSG_018 [Elizabeth]]
Hmhm... Bueno, no puedo negar que todo esto me interesa enormemente.

[msg MSG_018_1 [Elizabeth]]
Ahora, perdポn por el retraso, pero aquボ tienen su merecida recompensa por sus esfuerzos.

