[msg MSG_000 [Elizabeth]]
Buen trabajo. ムHan salido victoriosos de una batalla muy feroz! Solo puedo alabaros. 
Y justo como habボa predicho, han conseguido otra parte de pelボcula.

[msg MSG_001 [P4 Hero]]
Pero definitivamente ha visto dボas mejores.

[msg MSG_001_1 [P4 Hero]]
Si es igual que la otra, solo tenemos que desplegar nuestro poder para activarla, メno?

[msg MSG_002 [Makoto]]
メEso significa que tendremos que luchar otra vez contra Theodore...?

[sel SEL_003 top]
Traedlo.
Tengo que prepararme...

[msg MSG_004 [Elizabeth]]
Hmhm... Lo has dicho como un verdadero bribポn apasionado.

[msg MSG_004_1 [Elizabeth]]
Por supuesto... o eso dirボa yo, pero hay que respetar las normas.

[msg MSG_005 [Elizabeth]]
No hay necesidad de estar tan inquieto.
Despu〒s de todo, hay normas que deben ser respetadas. Mientras tanto, puedes prepararte mental y fボsicamente.

[msg MSG_006 [Elizabeth]]
Aparte de eso, han completado la peticiポn. La sombra estホ derrotada.

[msg MSG_006_1 [Elizabeth]]
Y por eso, les debo una recompensa apropiada. De hecho, [f 6 1 13 0 0 0] nos deleitポ con una magnボfica actuaciポn.
Una vez que est〒n totalmente preparados para desplegar su poder, vengan a hablar conmigo, como la otra vez.

[msg MSG_007 [Morgana]]
No sabemos a qui〒n nos enfrentaremos esta vez. Sea quien sea, no serホ fホcil.

[msg MSG_007_1 [Morgana]]
Aceptaremos su desafボo cuando nos hayamos preparado. Serホ un combate serio, eso seguro.

