[msg MSG_000 [P3 Hero]]
Parece que lo hemos conseguido. Lo han hecho genial, chicos.

[msg MSG_001 [Yusuke]]
Hemos acabado con gracia. Ahora, メeso completa nuestra tarea?

[msg MSG_002 [P3 Hero]]
Oh, ey...

[msg MSG_003]
Hay algo en el suelo...

[msg MSG_004 [P3 Hero]]
Lo sabボa. Es justo como la que tマ y [f 6 1 13 0 0 0] encontraron.

[msg MSG_005]
ムObtuviste una Pelボcula de Hollボn!

[msg MSG_006 [P3 Hero]]
メEsta es ya la tercera? Ya es hora de que averig↓emos qu〒 son en realidad...

[msg MSG_006_1 [P3 Hero]]
En cualquier caso, volvamos. Serホ mejor avisar a Elizabeth.

