[msg MSG_000 [P3 Hero]]
Well, we're pretty close now.

[msg MSG_000_1 [P3 Hero]]
Yeah, that's a tough one all right. I[n]can feel its power from here.

[msg MSG_001 [Futaba]]
Man, [f 6 1 16 0 0]. You say that, but you're[n]still so calm! I guess that's why you're[n]a leader, too.

[msg MSG_001_1 [Futaba]]
Well, we're counting on you. Time for[n]your big starring role!

[msg MSG_002 [P3 Hero]]
Right. I'll give it a try.

[msg MSG_003 [Akihiko]]
Eyes up. Here it comes!

