[msg MSG_000 [P3 Hero]]
Parece que lo hemos conseguido. Lo han hecho genial, chicos.

[msg MSG_001 [Yusuke]]
Hemos acabado con gracia. Ahora, 夷eso completa nuestra tarea?

[msg MSG_002 [P3 Hero]]
Oh, ey...

[msg MSG_003]
Hay algo en el suelo...

[msg MSG_004 [P3 Hero]]
Lo sab胤a. Es justo como la que t雨 y [f 6 1 13 0 0 0] encontraron.

[msg MSG_005]
斡Obtuviste una Pel胤cula de Holl胤n!

[msg MSG_006 [P3 Hero]]
夷Esta es ya la tercera? Ya es hora de que averigüemos qu姻 son en realidad...

[msg MSG_006_1 [P3 Hero]]
En cualquier caso, volvamos. Ser茨 mejor avisar a Elizabeth.

