[msg MSG_000 [Margaret]]
夷Oh? 夷Ya se acab吋? Qu姻 pena. Estaba[n]empezando a disfrutarme.

[msg MSG_000_1 [Margaret]]
夷Tal vez me met胤 en esto demasiado[n]r茨pido? Pens姻 que podr胤as seguir...

[msg MSG_001 [Elizabeth]]
Mi hermana es la ganadora de este[n]combate.
Si quieres desafiarla de nuevo, por[n]favor h茨blame en la taquilla.

[msg MSG_002 [Margaret]]
Trate de dejarme disfrutar un poco m茨s[n]la pr吋xima vez. Es una promesa, 夷verdad?

