[msg MSG_000 [Elizabeth]]
Je, je, je... Parece que todos nuestros actores est茨n presentes.

[msg MSG_001 [P3 Fem Protag]]
Theo, esa ropa...

[msg MSG_002 [Theodore]]
Ah, 夷esto?
Bueno, es una rara oportunidad para m胤. El protocolo pide que me vista adecuadamente.

[msg MSG_003 [Rise]]
Pero no eres nuestro enemigo, Theodore. Luchar contra ti se siente mal...

[msg MSG_004 [Theodore]]
Por favor, no dejen que eso os moleste. Despu姻s de todo, no es una simple pelea, sino un combate formal.
Luchemos sin rencores. Yo tambi姻n lo dar姻 todo.

[msg MSG_005 [Elizabeth]]
Hmm... Confieso que me alivia ver que te haya gustado la idea, Theo.

[msg MSG_006 [Theodore]]
Quiz茨 simplemente tengamos una inclinaci吋n natural a este tipo de cosas.

[msg MSG_007 [P3 Fem Protag]]
夷Una inclinaci吋n natural?

[msg MSG_008 [Theodore]]
Presidimos el poder. Normalmente, nos limitamos a observar mientras recorren su camino...
Pero cuanto m茨s fuertes se hacen, m茨s hambre sentimos... de luchar contra ustedes y probar su poder por nosotros mismos.
La orden de mi hermana ciertamente me sorprendi吋, pero ahora me doy cuenta... Anhelo la emoci吋n de la batalla.

[msg MSG_009 [Futaba]]
Halaaa... 斡Esa frase parece sacada del mon吋logo de un superjefe! 斡夷Esto es como un Omega Theodore?!

[msg MSG_010 [Theodore]]
Ahora, comencemos. Por favor, no se contengan.

[sel SEL_011 top]
Hag茨moslo.
夷Est茨n preparados?

[msg MSG_012 [Theodore]]
S胤. Perm胤tanme ser testigo de todo el alcance de su poder.

[msg MSG_012_1 [Theodore]]
Bueno, entonces... 斡All茨 voy!

[msg MSG_013 [Theodore]]
Pues bien. Comencemos una vez m茨s. Espero grandes cosas...

