[msg MSG_000 [Elizabeth]]
Heheheh... Parecer胤a que todos nuestros[n]actores est茨n presentes.

[msg MSG_001 [P3 Fem Protag]]
Theo, esas ropas...

[msg MSG_002 [Theodore]]
夷Esto?
Bueno, esta es una rara oportunidad para[n]m胤. Etiquette exige que me ponga el[n]traje adecuado.

[msg MSG_003 [Rise]]
Pero no eres nuestro enemigo, Theodore.[n]Luchar contra ti se siente mal...

[msg MSG_004 [Theodore]]
Por favor, no dejes que eso te moleste.[n]Despu姻s de todo, esto no es una mera[n]pelea, es un combate formal.
Combatamos sin sentimientos. Voy a darle[n]todo esto tambi姻n.

[msg MSG_005 [Elizabeth]]
Hmhm... Confieso que me alivia ver que[n]te has calentado, Theo.

[msg MSG_006 [Theodore]]
Quiz茨s simplemente tengamos una[n]inclinaci吋n natural a este tipo de[n]cosas.

[msg MSG_007 [P3 Fem Protag]]
夷Una inclinaci吋n natural?

[msg MSG_008 [Theodore]]
Presidimos el poder. Normalmente,[n]simplemente observamos mientras caminas[n]por tu camino...
はまるよ ぼゎぺょろよ ゆァれ みゎまるろま ぼるまんぼぺれデ ゆァれ れまょろもるまゆよれ[n]ゎょ ぼもまるろよ めぺゆほるまテテテ らぺるぺ ゅゎぼめぺる ぼよょろるぺ ろも を[n]れぺほよるまぺる ろゎ らよぽまる ょよれよろるよれ ゆもれゆよれテ
El mandato de mi hermana ciertamente me[n]sorprendi吋, pero ahora me doy cuenta...[n]Anhelo la emoci吋n de la batalla.

[msg MSG_009 [Futaba]]
Whoaaa... 斡Esa l胤nea sali吋 directamente[n]de un mon吋logo de superboss postjuego![n]夷Esto es como Omega Theodore?

[msg MSG_010 [Theodore]]
Ahora, empecemos. Por favor, no retengas[n]nada.

[sel SEL_011 top]
Hag茨moslo.
夷Est茨s listo?

[msg MSG_012 [Theodore]]
S胤. Perm胤tanme dar testimonio del[n]alcance total de su poder.

[msg MSG_012_1 [Theodore]]
Bueno entonces... 斡Aqu胤 voy!

[msg MSG_013 [Theodore]]
Bueno entonces. Empecemos una vez m茨s.[n]Esperar姻 grandes cosas...

