[msg MSG_000 [Elizabeth]]
Je, je, je... Parece que todos nuestros actores estホn presentes.

[msg MSG_001 [P3 Fem Protag]]
Theo, esa ropa...

[msg MSG_002 [Theodore]]
Ah, メesto?
Bueno, es una rara oportunidad para mボ. El protocolo pide que me vista adecuadamente.

[msg MSG_003 [Rise]]
Pero no eres nuestro enemigo, Theodore. Luchar contra ti se siente mal...

[msg MSG_004 [Theodore]]
Por favor, no dejen que eso os moleste. Despu〒s de todo, no es una simple pelea, sino un combate formal.
Luchemos sin rencores. Yo tambi〒n lo dar〒 todo.

[msg MSG_005 [Elizabeth]]
Hmm... Confieso que me alivia ver que te haya gustado la idea, Theo.

[msg MSG_006 [Theodore]]
Quizホ simplemente tengamos una inclinaciポn natural a este tipo de cosas.

[msg MSG_007 [P3 Fem Protag]]
メUna inclinaciポn natural?

[msg MSG_008 [Theodore]]
Presidimos el poder. Normalmente, nos limitamos a observar mientras recorren su camino...
Pero cuanto mホs fuertes se hacen, mホs hambre sentimos... de luchar contra ustedes y probar su poder por nosotros mismos.
La orden de mi hermana ciertamente me sorprendiポ, pero ahora me doy cuenta... Anhelo la emociポn de la batalla.

[msg MSG_009 [Futaba]]
Halaaa... ムEsa frase parece sacada del monポlogo de un superjefe! ムメEsto es como un Omega Theodore?!

[msg MSG_010 [Theodore]]
Ahora, comencemos. Por favor, no se contengan.

[sel SEL_011 top]
Hagホmoslo.
メEstホn preparados?

[msg MSG_012 [Theodore]]
Sボ. Permボtanme ser testigo de todo el alcance de su poder.

[msg MSG_012_1 [Theodore]]
Bueno, entonces... ムAllホ voy!

[msg MSG_013 [Theodore]]
Pues bien. Comencemos una vez mホs. Espero grandes cosas...

