[msg MSG_000 [Elizabeth]]
Ah... Y ahora, todo lo que queda es[n]decepci吋n.
No porque haya sido mejorada, sino[n]porque nuestra actuaci吋n se ha acercado.

[sel SEL_001 top]
Eras fuerte.
Eso no fue muy dif胤cil.

[msg MSG_002 [Elizabeth]]
No... mientras Tengo un poco de[n]conocimiento de este juego duro, todav胤a[n]estoy bastante inexperto.

[msg MSG_003 [Elizabeth]]
*chuckle* En verdad, tu fuerza nunca[n]deja de sorprenderme.

[msg MSG_004 [Margaret]]
Fue una pelea maravillosa. Sent胤 un[n]resplandor en mi coraz吋n solo por la[n]mirada.

[msg MSG_005 [Elizabeth]]
夷Hermana? No sab胤a que estabas aqu胤.

[msg MSG_006 [Margaret]]
S胤. Esperaba ver esta batalla.
No s吋lo pretend胤a presenciar el poder[n]que han alimentado aqu胤...

[msg MSG_006_1 [Margaret]]
Quer胤a ver qu姻 posibilidades hay m茨s[n]all茨 de su magn胤fica exhibici吋n.

[msg MSG_007 [P3 Fem Protag]]
Oh, cierto, esa pel胤cula...

[msg MSG_008]
La pel胤cula que parec胤a sooty est茨[n]brillando d姻bilmente...
...!
Las cuatro piezas de pel胤cula brillan[n]poderosamente juntas...!

[msg MSG_009 [P4 Hero]]
夷Es...?

[msg MSG_010 [P4 Hero]]
Ngh...!

[msg MSG_011]
Una luz brillante inunda la zona...

[msg MSG_012 [P4 Hero]]
Esa luz ahora...

[msg MSG_013 [P3 Hero]]
Es como... algo ha cambiado dentro de[n]m胤.

[msg MSG_014 [P3 Fem Protag]]
夷Es esto mi...?

[msg MSG_015]
Siento un nuevo poder dentro de mi[n]coraz吋n...

[msg MSG_016 [Margaret]]
*chuckle* Parece que todos hab姻is[n]captado una nueva posibilidad.

[msg MSG_017 [Elizabeth]]
Ha sido una alegr胤a y un privilegio[n]presenciar una vista tan rara.
Si pudiera preguntar... 夷C吋mo te[n]sientes?

[sel SEL_018 top]
Es... incre胤ble.
Es dif胤cil de decir.

[msg MSG_019 [Margaret]]
S胤, de verdad.
No puedo esperar a ver lo que puedes[n]lograr de aqu胤 en adelante.

[msg MSG_020 [Margaret]]
Hmhm... Supongo que est茨 bien por ahora.

[msg MSG_020_1 [Margaret]]
Pero ese poder seguramente te ayudar茨 a[n]elegir tus propios caminos por venir.

[msg MSG_021 [Elizabeth]]
De cualquier manera... es asombroso[n]saber que has ganado a todos los que[n]gobiernan el poder. 斡Me incluyo!

[msg MSG_022 [Margaret]]
Estoy seguro de que esto ser茨 una gran[n]sorpresa para nuestro maestro.

[msg MSG_022_1 [Margaret]]
Has hecho bien en venir hasta ahora.[n]Aunque quiz茨s todo esto era simplemente[n]tu destino..?

[msg MSG_023 [Akechi]]
Dir胤a que es gracias a que nos[n]mantengamos al d胤a con esas proyecciones[n]especiales.

[msg MSG_023_1 [Akechi]]
Despu姻s de todo, ah胤 fue donde empez吋[n]todo esto.

[msg MSG_024 [Junpei]]
斡S胤, no habr胤amos llegado a ninguna[n]parte sin esos! Te hace preguntar qui姻n[n]estaba tirando de las cuerdas.

[msg MSG_025 [Hikari]]
...

[msg MSG_025_1 [Hikari]]
Um... Bueno, no s姻 si alguien lo prepar吋[n]deliberadamente... pero he estado[n]pensando en ello.
Me pregunto si es m茨s como... las[n]proyecciones especiales suceden basadas[n]en tus emociones? O... deseos, supongo?

[msg MSG_026 [Naoto]]
Ya veo. Una hip吋tesis interesante...
Nuestros recuerdos parec胤an alterar los[n]personajes de esas pel胤culas que hemos[n]estado investigando.
M茨s importante a雨n, la pel胤cula de[n]Hikari parec胤a profundamente reflexiva[n]en su propia mentalidad y perspectiva.

[msg MSG_027 [Akechi]]
夷As胤 que, de forma similar, las[n]proyecciones especiales reflejan nuestra[n]propia conciencia...?

[msg MSG_028 [Hikari]]
Cierto. Como querer acercarse a todo el[n]mundo, o quiz茨s querer ser m茨s fuerte...
Si deseas todas esas cosas lo[n]suficiente, 夷entonces quiz茨s se[n]convirtieron en pel胤culas?

[msg MSG_029 [P4 Hero]]
Eso puede ser verdad. Eso explicar胤a por[n]qu姻 aprendimos que Unison Skill...

[msg MSG_030 [Teddie]]
斡Las toneladas de mis deseos tambi姻n se[n]hicieron realidad!

[msg MSG_031 [Yukiko]]
Quer胤a conocer mejor a todos, y eso se[n]hizo realidad. Ahora todos somos amigos,[n]夷no?

[msg MSG_032 [P3 Fem Protag]]
Si he aprendido algo, es que puedes[n]hacer realidad cualquier deseo si te[n]aferras a 姻l con todo tu coraz吋n.

[msg MSG_033 [Junpei]]
夷Me est茨s diciendo que nuestros[n]pensamientos pueden convertirse en[n]pel胤culas? 斡No puedo soportarlo m茨s!

[msg MSG_033_1 [Junpei]]
斡Quiero una pel胤cula en la que yo sea la[n]estrella! 斡Con chicas guapas, una[n]persecuci吋n en coche y explosiones!

[msg MSG_034 [Yukari]]
Ya tenemos suficientes de tus delirios.[n]No necesito un boleto personal para[n]ellos.

[msg MSG_035 [Elizabeth]]
En cualquier caso, est茨 claro que todos[n]ustedes han crecido enormemente en este[n]mundo de las pel胤culas.
Creo que la libertad ya est茨 a tu[n]alcance. Sigue esforz茨ndote, y estoy[n]seguro de que tendr茨s 姻xito.

[sel SEL_036 top]
Gracias.
Espero que nos ayudes.

[msg MSG_037 [Elizabeth]]
No necesitas agradecerme. Has llegado[n]hasta aqu胤 casi completamente bajo tu[n]propio poder.

[msg MSG_038 [Elizabeth]]
Entiendo. Har姻 todo lo que pueda para[n]ayudarte.

[msg MSG_039 [Elizabeth]]
Me disculpo por no mencionarlo hasta[n]ahora, pero tambi姻n tengo una recompensa[n]por ti. Por favor, util胤zalo bien.
Ahora, ir姻 en camino. Reunamos en la[n]taquilla.

[msg PERSONA_STOCK_UP_MSG]
ひゎらまるぺる まれろま よるぽまぺゅ めぺ みよるろぺゅまぼもぽよ まゅ らよぽまる ぽま[n]ゅぺ ろぺるゃまろぺ れぺゅわぺゃまテ ひゎ れろよぼや ぽま はまるれよょぺ めぺ[n]ぺゎゆまょろぺぽよ まょ [f 0 1 2] はつぱひのねだねだぬつねぴぬソ[f 0 1 0] テ

[msg SYS_MES_000]
El efecto de [f 4 4 3 0 1596] ha[n]aumentado el impulso EXP de los Bonos[n]Finales.

