[msg MSG_000 [Elizabeth]]
...

[msg MSG_001 [Margaret]]
Well, well. Elizabeth, speechless?[n]Wonders never cease.

[msg MSG_002 [Theodore]]
Considering the sheer power we all[n]witnessed, I suppose I cannot blame her.

[msg MSG_003 [Elizabeth]]
We govern power...
To overcome all of us―together, no[n]less―is no simple feat...

[sel SEL_004 top]
It's proof of our growth.
Felt pretty simple to me.
Honestly, it was rough.

[msg MSG_005 [Elizabeth]]
Yes... We have witnessed that ourselves.

[msg MSG_006 [Elizabeth]]
My, so calm and composed... What could[n]one call that knowing smile?[n]"Irritatingly, ferociously smug"?

[msg MSG_007 [Elizabeth]]
Well, these things happen when we[n]unleash our full power.

[msg MSG_008 [Theodore]]
This fire in my heart, this thrill[n]coursing through me... A battle of such[n]magnitude is quite rare.
Indeed... you have all grown[n]magnificently.

[msg MSG_009 [Elizabeth]]
I feel as if I've finally glimpsed the[n]true reason we were summoned here...

[msg MSG_010 [Margaret]]
Yes, I must agree. Perhaps this is the[n]form our own journey must take.
You may see this as a mere diversion, a[n]byroad branching from your ordinary[n]lives...

[msg MSG_010_1 [Margaret]]
However... whatever road you walk, the[n]path you take brings change upon you and[n]all those you affect.
As we clashed, I felt the proof of your[n]growth... and felt my own understanding[n]deepen.

[msg MSG_011 [Justine]]
Inmate. Seeing you acquire and control[n]such superb power is... vindicating, as[n]your wardens.

[msg MSG_012 [Caroline]]
Hmph... That was pretty satisfying.[n]Nothing else here could ever be a threat[n]to you now.

[msg MSG_013 [Elizabeth]]
Well then, here is your due reward.[n]Please accept it.

[msg MSG_014 [Theodore]]
It may be that we cannot do much else to[n]aid you here...
But as ones bound to support you in your[n]journeys, we will continue to serve your[n]needs.

[msg MSG_015 [Caroline]]
Yeah. And not just Persona fusions,[n]either.
If you ever want to fight us again, go[n]to the box office.
We'll take a rematch anytime. You better[n]be thankful!

[msg MSG_016 [Justine]]
Don't think it will go so well for you[n]next time. Take that to heart, Inmate.

[msg MSG_017 [Margaret]]
Either way, I owe you my gratitude.[n]Thank you for showing us such a[n]magnificent glimmer of life.

[msg MSG_018 [Elizabeth]]
As you have overcome this final test, we[n]shall postpone judgment of your hot dog[n]heist for another time.

[msg MSG_019 [Junpei]]
Now that I think about it... you give us[n]hot dogs all the time, Elizabeth.

[msg MSG_020 [Elizabeth]]
Gulp.

[msg MSG_021 [Rise]]
Oh yeah, you're right... She's the one[n]who keeps giving us hot dogs.
I've seen her taking some out from[n]behind the Kamoshidaman sign.

[msg MSG_022 [Elizabeth]]
Double gulp!

[msg MSG_023 [Caroline]]
W-Wait, that's where I was hiding my own[n]hot dogs! Don't tell me...

[msg MSG_024 [Elizabeth]]
Heheheh... So, the truth finally comes[n]out.

[msg MSG_024_1 [Elizabeth]]
The true mastermind was actually with[n]you all along...! Or so it goes. These[n]stories always require a twist.

[msg MSG_025 [Ken]]
Well, I guess so... but that means he[n]was falsely accused for stealing―

[msg MSG_026 [Caroline]]
W-Well! At least it means we got a good[n]sense of your power!
Let's just put this hot dog case behind[n]us. Better be grateful, Inmate!

[msg MSG_027 [Justine]]
About that. Assuming the prisoners are[n]innocent of grand hot dog larceny...
Does this mean... Elizabeth was the one[n]who robbed us?

[msg MSG_028 [Elizabeth]]
Indeed, I was the one who raided[n]Caroline's secret stash.
However, I cannot account for Justine's[n]missing share.

[msg MSG_029 [Justine]]
...

[msg MSG_030 [Caroline]]
Uh, well... I mean, that's...!
I-It must be the Persona-users! I know[n]nothing!
I-I mean, if you hide them in an[n]easy-to-find place like the projection[n]room, of course they'll get stolen!

[msg MSG_031 [Margaret]]
...

[msg MSG_032 [Theodore]]
...

[msg MSG_033 [Justine]]
...Caroline, you have ketchup on your[n]cheek.

[msg MSG_034 [Caroline]]
Wh-What!? Why didn't you tell me[n]sooner!?

[msg MSG_035 [Justine]]
I lied.

[msg MSG_036 [Caroline]]
Gah! H-How dare you, Justine!? That's[n]not fair!

[msg MSG_037 [Justine]]
I see. And so the truth becomes clear.
Caroline, you had been snacking on my[n]share of hot dogs behind my back.
When all the hot dogs disappeared... you[n]seized the opportunity to force all the[n]blame onto the prisoner.
...Perhaps he's not alone in needing[n]rehabilitation?

[msg MSG_038 [Caroline]]
That's not true! I only snacked on a[n]little of yours!
But then all of my hot dogs suddenly[n]disappeared, so I... I had no choice...

[sel SEL_039 top]
You're the culprit!
Just admit it.

[msg MSG_040 [Caroline]]
Th-This would've never happened if my[n]share hadn't disappeared! If she[n]hadn't...

[msg MSG_041 [Elizabeth]]
...Well! I'm a very busy woman, and I[n]have many things to do.

[msg MSG_041_1 [Elizabeth]]
Everyone, I bid you farewell.

[msg MSG_042 [Margaret]]
...And off she goes.

[msg MSG_043 [Theodore]]
Elizabeth...
So, that WAS ketchup I spotted around[n]your mouth...

[msg MSG_044 [Justine]]
Inmate, you already have power beyond[n]all reasonable limits.

[msg MSG_045 [Caroline]]
I don't think anyone here can rival your[n]power anymore. Good work.

[msg MSG_046 [Theodore]]
Such perfectly coordinated attack and[n]defense! A superb showing.

[msg MSG_047 [Margaret]]
Thank you once again. I welcome each[n]chance to witness that unique, glorious[n]spark of life within you.

[msg MSG_048 [Elizabeth]]
Well then, I hope we can continue to be[n]of assistance to you.

[msg MSG_049 [Caroline]]
Phew... You put up more of a fight than[n]I expected, Inmate.

[msg MSG_050 [Justine]]
Indeed. You should be proud you were[n]able to push us so far.

[msg MSG_051 [Margaret]]
However, I'm certain this is not the[n]end. There is yet further power within[n]you, sleeping dormant...

[msg MSG_052 [Theodore]]
Here is your promised reward. Please use[n]it well.

[msg MSG_053 [Elizabeth]]
You are free to challenge us again[n]whenever you please. This is a true[n]ordeal, after all.

[msg MSG_053_1 [Elizabeth]]
Please excuse us, then.

[msg MSG_054 [Caroline]]
Phew... You put up more of a fight than[n]I expected, Inmate.

[msg MSG_055 [Justine]]
Indeed. You should be proud you were[n]able to push us so far, Inmate.

[msg MSG_056 [Margaret]]
However, I'm certain this is not the[n]end. There is yet further power within[n]you, sleeping dormant...

[msg MSG_057 [Theodore]]
We will look forward to the day that you[n]reach new heights.

[msg MSG_058 [Elizabeth]]
Please feel free to speak to me again[n]whenever you please.

[msg MSG_058_1 [Elizabeth]]
Please excuse us, then.

[msg MSG_059 [Caroline]]
Hm... Meh. I guess you pass.

[msg MSG_060 [Justine]]
Really? I am left rather unsatisfied.

[msg MSG_061 [Margaret]]
But our guests have shown us the extent[n]of their power. Shouldn't they be[n]compensated for their efforts?

[msg MSG_062 [Theodore]]
True, I suppose. Then please accept this[n]token.

[msg MSG_063 [Elizabeth]]
We encourage you to challenge us again[n]whenever you please. This is a true[n]ordeal, after all.

[msg MSG_063_1 [Elizabeth]]
Please excuse us, then.

[msg MSG_064 [Caroline]]
Hm... Meh. I guess you pass.

[msg MSG_065 [Justine]]
Really? I am left rather unsatisfied.

[msg MSG_066 [Margaret]]
However, we have a measure of their[n]current strength.

[msg MSG_067 [Theodore]]
I'm certain you still have greater[n]potential slumbering within you. I hope[n]one day to see it realized.

[msg MSG_068 [Elizabeth]]
We encourage you to challenge us again[n]whenever you please. This is a true[n]ordeal, after all.

[msg MSG_068_1 [Elizabeth]]
Please excuse us, then.

[msg MSG_069 [Caroline]]
*sigh* Completely unacceptable. What's[n]the matter with you, Inmate?

[msg MSG_070 [Justine]]
Yes. Disappointing, at best.

[msg MSG_071 [Margaret]]
Did we misjudge your skills? Then again,[n]the results speak for themselves...

[msg MSG_072 [Theodore]]
Well then, please accept this. A token[n]of our appreciation for the bout.

[msg MSG_073 [Elizabeth]]
Everyone, you are free to challenge us[n]again whenever you please. This is a[n]true ordeal, after all.
Until the time comes, and you gain the[n]power to overcome us... we shall[n]patiently await you here.

