[msg MSG_000 [Caroline]]
Vamos, Recluso. Ser茨 mejor que no[n]retengas nada!
Pr茨cticamente estamos doblando las[n]reglas para tener este combate contigo.[n]夷Te gusta ese tratamiento especial?

[msg MSG_001 [Justine]]
Nunca te he visto tan alto en esp胤ritus,[n]Caroline.
Supongo que puedes estar tan entusiasta[n]como quieras, siempre y cuando no nos[n]despiertes.

[msg MSG_002 [Caroline]]
夷Qu姻? 斡No soy "enthusi茨stico"!
斡Y m胤rate! 斡Has estado hablando mucho[n]m茨s de lo habitual!

[msg MSG_003 [Justine]]
...
No puedo imaginar lo que quieres decir.

[sel SEL_004 top]
夷Ya han terminado?
Esto es adorable.

[msg MSG_005 [Caroline]]
斡C茨llate! 斡Todo esto es culpa tuya!

[msg MSG_006 [Justine]]
Correcto. Tu presencia es[n]desconcertante.

[msg MSG_007 [Akechi]]
Bueno, bueno. Me parece una fijaci吋n,[n]Joker.

[msg MSG_008 [Caroline]]
A-adora - 夷Qu姻 significa eso?

[msg MSG_009 [Justine]]
H-hrmph. No te molestes en aplacarnos.[n]No tenemos piedad de ti.

[msg MSG_010 [Caroline]]
斡S胤, es cierto!

[msg MSG_011 [Akechi]]
El tartamudeo y el ruborismo no est茨[n]ayudando exactamente a su caso.

[msg MSG_012 [Elizabeth]]
斡Bien! Esta introducci吋n es muy larga.

[msg MSG_012_1 [Elizabeth]]
Aprecio que el papel de tsundere sea un[n]poco lento, pero 夷puedo pedir que[n]empieces pronto?

[msg MSG_013 [Justine]]
No tienes que dec胤rnoslo dos veces.
Ven, Caroline. Nuestros hot dogs nos[n]esperan.

[msg MSG_014 [Caroline]]
Heh heh... Entendido. 斡Es hora de que te[n]ense隠emos una lecci吋n, recluso!

[msg MSG_015 [Caroline]]
でまめテテテ ちゎまょよデ ぱまぼゅゎれよデ らぺるまぼまれ ほぺれろぺょろま[n]ぼよょみもぺぽよ まれろぺ わまんテ はまるよ ょよ もゆらよるろぺ ぼゎァょろぺれ[n]わまぼまれ ゅよ もょろまょろまれデ ろよぽぺわウぺ らまるぽまるァれテ

[msg MSG_016 [Justine]]
Al menos intenta poner una lucha. Ahora,[n]empecemos.

