[msg MSG_000 [Man with glasses]]
[f 0 5 65278][f 2 1][f 4 6 83 12 4 9][f 3 1 1 0 0 1][f 6 1 3 0 0 2]...Hikari, you're such a good girl for[n]trying not to cause any trouble[n]for anyone.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2]Even when I was gone for such a long[n]time at work, you never raised a single[n]fuss.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 83 0 5 0][f 3 1 1 0 0 3]I know that I've made you feel lonely[n]so many times, but you still cheered me[n]on with my job.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 83 1 5 0][f 3 1 1 0 0 4]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 83 0 5 0][f 3 1 1 0 0 5]You truly grew up to be a wonderful girl.[n]You're my pride and joy.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Man with glasses]]
[f 0 5 65278][f 2 1][f 4 6 83 12 4 0][f 3 1 1 0 0 6][f 6 1 3 0 0 2]Still... it makes me a little sad when I see[n]you force a smile so you won't stand out[n]from the crowd.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7]I... I want you to live your life to your[n]fullest, however you wish.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Your smile, and your existence... Those[n]are my greatest reasons to live.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Man with glasses]]
[f 0 5 65278][f 2 1][f 4 6 83 2 5 9][f 3 1 1 0 0 9]Heheh... This is bad, I'm starting to get[n]embarrassed now, of all times...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10]Ahem...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 83 12 4 0][f 3 1 1 0 0 11]I truly look forward to the day I get to[n]see the movie you've made, Hikari.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12]Your father will always be watching[n]over you. Never forget that.[n][f 1 3 65535][f 1 1][e]

