[msg MSG_000 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 1][f 3 1 1 0 0 16002]...Just as I expected, this floor has[n]a musical atmosphere too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Swaying flowers and musical notes...[n]This place has the same sing-songy feel[n]about it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Y'know, I've never actually watched[n]a musical.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]The people in 'em just start singin'[n]at the drop of a hat, yeah? That's[n]too unrealistic for me...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 1][f 3 1 1 0 0 61055][f 6 1 2 0 0 6]That's not true, though![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sound films have existed since the 1920s[n]when talking pictures overlaid with[n]music were―[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 11 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]O-Oh, okay...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 6 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Oh... I'm sorry. I didn't mean to get loud[n]like that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]Nah, it's fine. I dunno anything about[n]'em, so feel free to lay it on me.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 61152]*chuckle* Thanks. I'm glad to hear it.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Now that I think about it, I couldn't help[n]but talk a lot when it came to movies...[n]People were always put off by it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24036]"Put off"!? But, the passion that people[n]display when speaking of what they love[n]is so heartening![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 6][f 3 1 1 0 0 0]Plus, sometimes hearing about others'[n]interests can get you into them too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 22031][f 6 1 2 0 0 6]I love musicals![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It may not have been a movie, but when[n]I saw one live on Broadway, I got[n]goosebumps![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 6][f 3 1 1 0 0 0]I agree. When you hear a large group of[n]people's voices and see their movement[n]come together, it's so moving.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's true that people don't burst into song[n]in real life... but I feel like there are some[n]moments when your heart turns to song.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 61162][f 6 1 2 0 0 0]See!? You get it! There are times even in[n]real life when your emotions grow so[n]strong that you feel like singing![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]But I'm not much of a singer myself, so[n]I experience that through the characters[n]in the musicals.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 0]Yeah! Sadness, happiness, and even[n]anger are expressed so vividly with[n]song and dance.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]Yeah. The actors express every kind of[n]emotion and mood with their bodies,[n]to all sorts of musical genres.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]The musical's ability to directly express[n]human emotion is what really appeals[n]to me.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I can still remember when I found out[n]that dialogue isn't the only way to[n]communicate a message to an audience.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5032]*giggle* You must really love musicals,[n]Hikari-chan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]*gasp* I'm sorry! There I go, ranting[n]again...[n][f 1 3 65535][f 1 1][e]

[sel SEL_016 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]It's pretty surprising, actually.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]You're so passionate.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]You're quite the enthusiast.[f 2 7 1 20 2 32][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 6][f 3 1 1 0 0 21067]Right? I never thought you could get[n]so heated.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So, musicals let you express strong[n]emotions like that through singin'[n]and dancin', huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 6][f 3 1 1 0 0 25068]She must love musicals because she's[n]that way deep down, and musicals[n]often directly express such emotion.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 6][f 3 1 1 0 0 26542][f 3 1 6 0 0 500]Mweheheh... An enthusiast won't stop[n]once they get going on their topic. I'm[n]so happy to see Hikari this fired up![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 81 1 0 0][f 4 6 5 2 0 0][f 3 1 1 0 0 5032]I admit I'm a bit jealous that you have[n]something that you're so passionate[n]about...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I hope I can find something that[n]fascinates me the same way―you know,[n]like Chie with her kung fu and meat.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 1 6][f 3 1 1 0 0 0]C'mon, I don't think meat counts![n]I mean, I do love it and all, but, still...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ooh, but I AM fascinated with kung fu.[n]Do you wanna watch "Trial of the[n]Dragon" with me sometime, Yukiko?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 61168][f 6 1 2 0 0 6]That's that famous kung fu movie! I've[n]seen it too―it even got my blood boiling![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 14 1 0][f 3 1 1 0 0 4066][f 6 1 2 0 0 6]Yeah, that's what I'm talkin' about! I get[n]so pumped that I can't help but yell,[n]"Hwa-taaaa!" myself![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Man, you sure know your stuff,[n]Hikari-chan. To think you'd get what's[n]great about even that movie![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]U-Um... Does anyone else have[n]a favorite movie?[n][f 1 3 65535][f 1 1][e]

[sel SEL_025 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]The Cake Knight Rises.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Love Possibly.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Mes Miserable.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I can't think of any.[f 2 7 1 20 6 32][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 1][f 3 1 1 0 0 23073]Ah, yes. I thought it'd be a standard hero[n]flick, but it was surprisingly thought-[n]provoking about social awareness.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 6][f 3 1 1 0 0 22032]I saw it too! I couldn't hold back[n]the waterworks for that one.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 1][f 3 1 1 0 0 23116]Oh yeah, that was a musical too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 18 1 1][f 3 1 1 0 0 0]I felt like I learned about human[n]kindness due to that bishop's[n]merciless nature...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 1][f 3 1 1 0 0 23098]Seriously? When we get back, let's go[n]watch something.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 2 0 3][f 3 1 1 0 0 0]I think "Like A Dragon" would be[n]my choice. It was pretty thrilling...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 1][f 3 1 1 0 0 0]That's the yakuza movie, right!? I can[n]remember getting a chill down my spine[n]from just how intense it was.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 0][f 3 1 1 0 0 25048]You really do know your stuff, don't you,[n]Hikari-chan?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm surprised that you're acquainted[n]with so many different types of movies[n]and not just the musicals.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Is there a reason you fell in love with[n]movies, Hikarin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Huh...? My reason?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61013]My... reason...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 0 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hikari-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]Hm? Oh... It's probably because I've[n]been watching movies ever since I can[n]remember.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]But... I can't recall any more than that[n]right now...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10032]I see. Well, we might be able to learn[n]some more if we keep goin' through[n]this movie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 0]Mmhm... I need to make sure to watch[n]it all. Let's keep going, everyone.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 12 0 4][f 3 1 1 0 0 23072]Make sure everyone stays on guard.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]This film may look all cheery, but don't[n]forget―it's crawling with Shadows![n][f 1 3 65535][f 1 1][e]

