[sel ITEM_POINT_SEL top]
Search cautiously
Search thoroughly
Cancel

[sel ITEM_POINT_FORCE_BTL_SEL top]
Search
Cancel

[sel SHORTCUT_SEL top]
Use
Don't use

[sel ENTRANCE_SEL top]
Head back
Don't head back

[msg MSG_000 [Ann]]
Hey! It looks like we can gather some[n]stuff here! What's the plan?

[msg MSG_001 [Ann]]
Okay! Let's keep our eyes open for any[n]Shadows!

[msg MSG_002 [Ann]]
Sounds good! Let's focus on gathering!

[msg MSG_003 [Ann]]
Looks risky. Maybe we should come back[n]later.

[msg MSG_004 [Ann]]
Looks like that's everything.

[msg MSG_005]
This is ours!

[msg MSG_006]
All right!

[msg MSG_007]
Yay!

[msg MSG_008 [Ann]]
Th-That was creepy. Let's stop here.

[msg MSG_009]
Pretty cool, yeah!?

[msg MSG_010]
Things are heating up!

[msg MSG_011]
Nice!

[msg MSG_012 [Ann]]
Oh! I see a shortcut! Should we go[n]through?

[msg MSG_013 [Ann]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Ann]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Ann]]
Doesn't look like we can go through.

[msg MSG_016 [Ann]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Ann]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Ann]]
H-Hey, I've got bad feeling about this[n]place.

[msg MSG_019 [Ann]]
R-Right... Got it.

[msg MSG_020 [Ann]]
Yeah, we probably should do that now.

[msg MSG_021 [Ann]]
Phew... I thought that was it for us.

[msg MSG_022 [Ann]]
Aren't there, like, a ton of Shadows[n]here? What should we do?

[msg MSG_023 [Ann]]
Okay! Let's be careful!

[msg MSG_024 [Ann]]
Yeah, we probably should do that now.

[msg MSG_025 [Ann]]
Phew... That was close.

[msg MSG_026 [Ann]]
This way takes us back to the theater,[n]right? You wanna go?

[msg MSG_027]
Look out!

