[sel ITEM_POINT_SEL top]
Search cautiously
Search thoroughly
Cancel

[sel ITEM_POINT_FORCE_BTL_SEL top]
Search
Cancel

[sel SHORTCUT_SEL top]
Use
Don't use

[sel ENTRANCE_SEL top]
Head back
Don't head back

[msg MSG_000 [Caroline]]
ここは採取できるようだな。 どうする？（※ダミーです）

[msg MSG_001 [Caroline]]
そうだな。 敵に気をつけて探すか。（※ダミーです）

[msg MSG_002 [Caroline]]
うむ。 では、専念して探すとしよう。（※ダミーです）

[msg MSG_003 [Caroline]]
今は止めておくのか？ 分かった。（※ダミーです）

[msg MSG_004 [Caroline]]
もう見つからないようだな。（※ダミーです）

[msg CARO_MSG_005]
Not bad.

[msg JUS_MSG_005]
Very nice.

[msg CARO_MSG_006]
I suppose that's fine.

[msg JUS_MSG_006]
Good work.

[msg CARO_MSG_007]
Not bad.

[msg JUS_MSG_007]
That's not too bad.

[msg MSG_008 [Caroline]]
勘付かれたか。 採取はここまでにしよう。（※ダミーです）

[msg CARO_MSG_009]
A good find!

[msg JUS_MSG_009]
Is that...!?

[msg CARO_MSG_010]
That's not bad at all!

[msg JUS_MSG_010]
Wonderful...

[msg CARO_MSG_011]
I'll allow you to be praised!

[msg JUS_MSG_011]
You shall be praised.

[msg MSG_012 [Caroline]]
ショートカットか。 どうする？通っておくか？（※ダミーです）

[msg MSG_013 [Caroline]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Caroline]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Caroline]]
こちらは通れんようだな。（※ダミーです）

[msg MSG_016 [Caroline]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Caroline]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Caroline]]
ヤバそうな雰囲気だがどうする? (戦闘オタカラスポット 発見MSG（仮）)

[msg MSG_019 [Caroline]]
探してみよう (戦闘オタカラスポット 探すMSG（仮）)

[msg MSG_020 [Caroline]]
今回はやめておこう (戦闘オタカラスポット やめるMSG（仮）)

[msg MSG_021 [Caroline]]
危なかったな (戦闘オタカラスポット 戦闘終了MSG（仮）)

[msg MSG_022 [Caroline]]
ここはシャドウの気配が強いな。 まわりにシャドウがいそうだが、どうする？[n](雑魚戦闘オタカラスポット 発見MSG（仮）)

[msg MSG_023 [Caroline]]
いたぞ、シャドウだ！ (雑魚戦闘オタカラスポット 探すMSG（仮）)

[msg MSG_024 [Caroline]]
そうだな、行こう (雑魚戦闘オタカラスポット やめるMSG（仮）)

[msg MSG_025 [Caroline]]
ふーあぶなかった。あっ、なんか落ちてる！ (雑魚戦闘オタカラスポット[n]戦闘終了MSG（仮）)

[msg MSG_026 [Caroline]]
出入り口がある。 戻るか？ (出入り口MSG（仮）)

[msg CARO_MSG_027]
Look out!

[msg JUS_MSG_027]
Look out!

