[sel ITEM_POINT_SEL top]
Search cautiously
Search thoroughly
Cancel

[sel ITEM_POINT_FORCE_BTL_SEL top]
Search
Cancel

[sel SHORTCUT_SEL top]
Use
Don't use

[sel ENTRANCE_SEL top]
Head back
Don't head back

[msg MSG_000 [Teddie]]
I found a Treasure Spot! Wanna grab some[n]stuff?

[msg MSG_001 [Teddie]]
Leave it all to me!

[msg MSG_002 [Teddie]]
I'm gonna find it first!

[msg MSG_003 [Teddie]]
Oh, not this one? You got it!

[msg MSG_004 [Teddie]]
We've cleaned the place out!

[msg MSG_005]
Dig here! Dig here!

[msg MSG_006]
Niiiice!

[msg MSG_007]
Got it!

[msg MSG_008 [Teddie]]
Whew... We got through it. And we got[n]some loot, too!

[msg MSG_009]
Nyoink!

[msg MSG_010]
Woohoo!

[msg MSG_011]
Bingo!

[msg MSG_012 [Teddie]]
I've found a shortcut! Wanna take it?

[msg MSG_013 [Teddie]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Teddie]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Teddie]]
Aww, we can't get through...

[msg MSG_016 [Teddie]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Teddie]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Teddie]]
Something doesn't smell right about this[n]place!

[msg MSG_019 [Teddie]]
Okay! Time to do this!

[msg MSG_020 [Teddie]]
Yep yep! Smart move!

[msg MSG_021 [Teddie]]
Guh... phew... That Shadow was beary bad[n]news...

[msg MSG_022 [Teddie]]
*sniff sniff* Smells like a whole load[n]of Shadows...

[msg MSG_023 [Teddie]]
Okay! Let's do this!

[msg MSG_024 [Teddie]]
Backing out, right? Roger that!

[msg MSG_025 [Teddie]]
Are we done?

[msg MSG_026 [Teddie]]
Huh? We going back to the theater?

[msg MSG_027]
Look out!

