[sel ITEM_POINT_SEL top]
Search cautiously
Search thoroughly
Cancel

[sel ITEM_POINT_FORCE_BTL_SEL top]
Search
Cancel

[sel SHORTCUT_SEL top]
Use
Don't use

[sel ENTRANCE_SEL top]
Head back
Don't head back

[msg MSG_000 [Yosuke]]
Hey, it's a Treasure Spot! Wanna check[n]it out?

[msg MSG_001 [Yosuke]]
Roger! Let's keep an eye out!

[msg MSG_002 [Yosuke]]
Just gonna loot the place, huh? No[n]problem!

[msg MSG_003 [Yosuke]]
Oh. We're leaving it alone?

[msg MSG_004 [Yosuke]]
Ho-kay... that should be everything!

[msg MSG_005]
Don't mind if I do!

[msg MSG_006]
Sweet!

[msg MSG_007]
Got it!

[msg MSG_008 [Yosuke]]
Holy crap, that was close! How about we[n]call it here?

[msg MSG_009]
All right!

[msg MSG_010]
A rare item!

[msg MSG_011]
Niiice!

[msg MSG_012 [Yosuke]]
Whoa, that's a shortcut! We gonna go[n]through?

[msg MSG_013 [Yosuke]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Yosuke]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Yosuke]]
So much for that way, huh?

[msg MSG_016 [Yosuke]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Yosuke]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Yosuke]]
Hey... Something's weird. You feel that?[n]What do we do?

[msg MSG_019 [Yosuke]]
Y-Yeah... Long as we're careful.

[msg MSG_020 [Yosuke]]
Yeah. Who knows what could pop out.

[msg MSG_021 [Yosuke]]
What the heck was that!? I'm just glad[n]we survived...

[msg MSG_022 [Yosuke]]
Huh? There're Shadows out here... What's[n]the plan?

[msg MSG_023 [Yosuke]]
Sweet! Let's knock 'em dead!

[msg MSG_024 [Yosuke]]
Okay, you're the boss.

[msg MSG_025 [Yosuke]]
Whew... Is that all of 'em?

[msg MSG_026 [Yosuke]]
This should lead back to the theater.[n]Want to take a break?

[msg MSG_027]
Look out!

