[sel ITEM_POINT_SEL top]
Search cautiously
Search thoroughly
Cancel

[sel ITEM_POINT_FORCE_BTL_SEL top]
Search
Cancel

[sel SHORTCUT_SEL top]
Use
Don't use

[sel ENTRANCE_SEL top]
Head back
Don't head back

[msg MSG_000 [Ken]]
Uh, it looks like we could gather some[n]items here. What do you want to do?

[msg MSG_001 [Ken]]
I get it. You want to be cautious.

[msg MSG_002 [Ken]]
Yeah! Let's go for something really[n]cool!

[msg MSG_003 [Ken]]
We're not going to check it out? Well,[n]okay, I think I understand why...

[msg MSG_004 [Ken]]
And... got it! The last one!

[msg MSG_005]
All right!

[msg MSG_006]
Ooh.

[msg MSG_007]
Wow!

[msg MSG_008 [Ken]]
That was hard. Anyone else want to take[n]a break?

[msg MSG_009]
There we go!

[msg MSG_010]
Oooooh...

[msg MSG_011]
Awesome, congratulations!

[msg MSG_012 [Ken]]
A shortcut! Should we go through?

[msg MSG_013 [Ken]]
A shortcut! Should we go through?

[msg MSG_014 [Ken]]
A shortcut! Should we go through?

[msg MSG_015 [Ken]]
Aw... We can't go through this way...

[msg MSG_016 [Ken]]
Aw... We can't go through this way...

[msg MSG_017 [Ken]]
Aw... We can't go through this way...

[msg MSG_018 [Ken]]
Oh, um... Doesn't this area seem pretty[n]dangerous?

[msg MSG_019 [Ken]]
Right! Let's look real close!

[msg MSG_020 [Ken]]
I get it. Let's be ready!

[msg MSG_021 [Ken]]
That was scary, kinda! I thought we were[n]going to lose...

[msg MSG_022 [Ken]]
...I'm sensing a whole lot of Shadows[n]here.

[msg MSG_023 [Ken]]
Okay! Let's be careful!

[msg MSG_024 [Ken]]
I get it.

[msg MSG_025 [Ken]]
I knew there would be Shadows!

[msg MSG_026 [Ken]]
Are we going back to the theater?

[msg MSG_027]
Look out!

