[msg BTL_MES_000_000]
Dummy

[msg BTL_MES_000_001]
Attack it with a [f 0 1 2]Physical skill[f 0 1 0]!

[msg BTL_MES_000_002]
Attack it with a [f 0 1 2]Fire skill[f 0 1 0]!

[msg BTL_MES_000_003]
Attack it with an [f 0 1 2]Ice skill[f 0 1 0]!

[msg BTL_MES_000_004]
Attack it with an [f 0 1 2]Electricity skill[f 0 1 0]!

[msg BTL_MES_000_005]
Attack it with a [f 0 1 2]Wind skill[f 0 1 0]!

[msg BTL_MES_000_006]
Attack it with a [f 0 1 2]Psychokinesis skill[f 0 1 0]!

[msg BTL_MES_000_007]
Attack it with a [f 0 1 2]Nuclear skill[f 0 1 0]!

[msg BTL_MES_000_008]
Make sure you use a [f 0 1 2]physical[n]attacknext!

[msg BTL_MES_000_009]
Make sure you use a [f 0 1 2]Fire attacknext!

[msg BTL_MES_000_010]
Make sure you use an [f 0 1 2]Ice attacknext!

[msg BTL_MES_000_011]
Make sure you use an [f 0 1 2]Electricity[n]attacknext!

[msg BTL_MES_000_012]
Make sure you use a [f 0 1 2]Wind attacknext!

[msg BTL_MES_000_013]
Make sure you use a [f 0 1 2]Psychokinesis[n]attack[f 0 1 0] next!

[msg BTL_MES_000_014]
Make sure you use a [f 0 1 2]Nuclear[n]attacknext!

[msg BTL_MES_000_015]
Oh no! It rewrote its security[n]programming!

[msg BTL_MES_000_016]
Yes! We got past its firewall!

[msg BTL_MES_000_017]
Nice! Hacking successful!

[msg BTL_MES_000_018]
Analysis at 10%!

[msg BTL_MES_000_019]
Analysis at 20%!

[msg BTL_MES_000_020]
Analysis at 30%!

[msg BTL_MES_000_021]
Analysis at 40%!

[msg BTL_MES_000_022]
Analysis at 50%!

[msg BTL_MES_000_023]
Analysis at 60%!

[msg BTL_MES_000_024]
Analysis at 70%!

[msg BTL_MES_000_025]
Analysis at 80%!

[msg BTL_MES_000_026]
Analysis at 90%!

[msg BTL_MES_000_027]
Wh-Whoa, hold on! What was that just[n]now!?

[msg BTL_MES_000_028]
N-No way...!

[msg BTL_MES_000_029]
Everyone!

[msg BTL_MES_000_030]
Ah...

[msg BTL_MES_000_031]
No way... Guys! ...Everyone!

[msg BTL_MES_000_032]
I... I'm not getting any readings[n]from them...

[msg BTL_MES_000_033]
D-Did... we lose?

[msg BTL_MES_000_034]
Ngh... Nnh!

[msg BTL_MES_000_035]
H-Hikari!

[msg BTL_MES_000_036]
H-Hikari-chan...

[msg BTL_MES_000_037]
Please, run! At this rate, she'll[n]even take you down!

[msg BTL_MES_000_038]
Hikari!

[msg BTL_MES_000_039]
Hikari-chan!

[msg BTL_MES_000_040]
I heard your voice, Hikari-chan.

[msg BTL_MES_000_041]
Sorry for the wait.

[msg BTL_MES_000_042]
Leave the rest to us.

[msg BTL_MES_000_043]
Guys!

[msg BTL_MES_000_044]
Guys... I'll save you...

[msg BTL_MES_000_045]
If my cheers can help everyone...

[msg BTL_MES_000_046]
There's something even I can do!

[msg BTL_MES_000_047]
If I can aid everyone...

