[msg BTL_MES_007_000]
Dummy

[msg BTL_MES_007_001]
We can't back down from this one!

[msg BTL_MES_007_002]
＜声のみ＞やってやんぜコラァ！ ぜってー負けねえ！

[msg BTL_MES_007_003]
I-It's an F-F-something! This ain't[n]good!

[msg BTL_MES_007_004]
＜声のみ＞クソッ！ 退くしかねえのかよ…！

[msg BTL_MES_007_005]
Hey! I think we can win this one,[n]yeah?

[msg BTL_MES_007_006]
Oh shit! A rare one!

[msg BTL_MES_007_007]
＜声のみ＞オラオラオラー！ 逃がさねーぞ！

[msg BTL_MES_007_008]
＜声のみ＞わーったぜ、ナビ

[msg BTL_MES_007_009]
＜声のみ＞おうよ！ あんがとな、りせ！

[msg BTL_MES_007_010]
＜声のみ＞山岸さん、了解っス

[msg BTL_MES_007_011]
Whoa! This one's a little much for[n]us, ain't it?

[msg BTL_MES_007_012]
＜声のみ＞クッソ…ケツ向けんのは癪だけど、 やられるワケにいかねーし…

[msg BTL_MES_007_013]
Never seen one of those. Wanna look[n]for a weakness?

[msg BTL_MES_007_014]
＜声のみ＞うっス！ 了解っス！

[msg BTL_MES_007_015]
Piece of cake!

[msg BTL_MES_007_016]
＜声のみ＞これならボコれそうだぜ やるぜコラァ！

[msg BTL_MES_007_017]
Heh, weaklings. This'll be over in no[n]time.

[msg BTL_MES_007_018]
＜声のみ＞ヨユーっスね！ 瞬殺してやんぜ！

[msg BTL_MES_007_019]
Yo, is there somethin' off about that[n]Shadow?

[msg BTL_MES_007_020]
＜声のみ＞うおっ！？ 逃げらんねぇ！

[msg BTL_MES_007_021]
＜声のみ＞乱入かよコラ！ 聞いてねーぞ！

[msg BTL_MES_007_022]
Uuuuugh, dammit! We're in deep shit!

[msg BTL_MES_007_023]
＜声のみ＞くっそ… マジかよ！？

[msg BTL_MES_007_024]
＜声のみ＞ちょっ、大丈夫っスか先輩！ 手当てしねぇと…！

[msg BTL_MES_007_025]
＜声のみ＞ヤベー状況になってっスね… フォローしねぇと！

[msg BTL_MES_007_026]
＜声のみ＞花村先輩、ヤベェ！ 回復しねぇと！

[msg BTL_MES_007_027]
＜声のみ＞里中先輩、マジかよ！？ 助けねーと！

[msg BTL_MES_007_028]
＜声のみ＞天城先輩、ヤベェっスよ！ 回復しねーと！

[msg BTL_MES_007_029]
＜声のみ＞ダミー

[msg BTL_MES_007_030]
＜声のみ＞ダミー

[msg BTL_MES_007_031]
＜声のみ＞おい直斗、しっかりしろ！ チッ…なんとかしねーと！

[msg BTL_MES_007_032]
＜声のみ＞クマがヤベェことになってんぞ！ どうにかしねーと！

[msg BTL_MES_007_033]
＜声のみ＞岳羽さんがピンチっスよ！ 回復しねぇと！

[msg BTL_MES_007_034]
＜声のみ＞伊織さんがヤベェ状態だぜ！ フォローしねーと！

[msg BTL_MES_007_035]
＜声のみ＞ちょっ、真田さんヤベェぞ！ 早くなんとかしねーと！

[msg BTL_MES_007_036]
＜声のみ＞うおっ、桐条さんがヤベェ…！ どうにかしねーと！

[msg BTL_MES_007_037]
＜声のみ＞ダミー

[msg BTL_MES_007_038]
＜声のみ＞アイギスさん、おかしくなってんぞ！？ 早く回復しねぇと！

[msg BTL_MES_007_039]
＜声のみ＞大丈夫かよ、天田！？ チッ、助けねーと…！

[msg BTL_MES_007_040]
＜声のみ＞コロマルがヤベェ！ すぐ助けねぇと！

[msg BTL_MES_007_041]
＜声のみ＞うおっ、荒垣さん！？ なんとかしねぇと、ヤベェ！

[msg BTL_MES_007_042]
＜声のみ＞おい、大丈夫かよ！？ 手当てしねぇと…！

[msg BTL_MES_007_043]
＜声のみ＞くっそ、ジョーカーが… 早く助けねーと！

[msg BTL_MES_007_044]
＜声のみ＞スカルがヤベェぞ！？ 回復しねーと！

[msg BTL_MES_007_045]
＜声のみ＞パンサー、マジかよ！？ 早く助けねーと！

[msg BTL_MES_007_046]
＜声のみ＞モナがおかしなことになってんぞ！ 回復しねーと！

[msg BTL_MES_007_047]
＜声のみ＞フォックス、ヤバくねぇか？ 早く助けねーと！

[msg BTL_MES_007_048]
＜声のみ＞うおっ、クイーンが…！ とっとと回復しねーと！

[msg BTL_MES_007_049]
＜声のみ＞ダミー

[msg BTL_MES_007_050]
＜声のみ＞ノワールがヤベェ！ どうにかしねーと！

[msg BTL_MES_007_051]
＜声のみ＞クロウがやられてんぞ！ 回復しねーと！

[msg BTL_MES_007_052]
＜声のみ＞おっしゃあ！ ぶっ潰す！

[msg BTL_MES_007_053]
All right! I'm on it!

[msg BTL_MES_007_054]
＜声のみ＞ウオオオオ！ このまま、突っ走ってやらぁ！

[msg BTL_MES_007_055]
I can hit its weakness!

[msg BTL_MES_007_056]
Baton Passin' sounds like a good[n]idea!

[msg BTL_MES_007_057]
All right! My time to shine!

[msg BTL_MES_007_058]
＜声のみ＞さすが先輩！ 期待してるッス！

[msg BTL_MES_007_059]
＜声のみ＞おっしゃ！ やっちまってください！

[msg BTL_MES_007_060]
＜声のみ＞花村先輩、やる気じゃ ねーっスか！

[msg BTL_MES_007_061]
＜声のみ＞おっ、里中先輩！ 燃えてっスね！

[msg BTL_MES_007_062]
＜声のみ＞天城先輩、すげー… やる気ありすぎんだろ

[msg BTL_MES_007_063]
＜声のみ＞ダミー

[msg BTL_MES_007_064]
＜声のみ＞ダミー

[msg BTL_MES_007_065]
＜声のみ＞いっちまえ、直斗！

[msg BTL_MES_007_066]
＜声のみ＞おいクマ！ 気合いれろよ！

[msg BTL_MES_007_067]
＜声のみ＞岳羽さんに まかせるっス！

[msg BTL_MES_007_068]
＜声のみ＞伊織さんなら やってくれんだろ！

[msg BTL_MES_007_069]
＜声のみ＞真田さん！ あとは頼んだぜ！

[msg BTL_MES_007_070]
＜声のみ＞桐条さんならキメてくれんだろ！

[msg BTL_MES_007_071]
＜声のみ＞ダミー

[msg BTL_MES_007_072]
＜声のみ＞思いっきり暴れろ、アイギスさん！

[msg BTL_MES_007_073]
＜声のみ＞やる気すげぇじゃねーか、天田 やっちまえ！

[msg BTL_MES_007_074]
＜声のみ＞よっしゃ、コロマル！ 頼むぜ！

[msg BTL_MES_007_075]
＜声のみ＞荒垣さん、頼んだっス！

[msg BTL_MES_007_076]
＜声のみ＞期待してっからな！

[msg BTL_MES_007_077]
＜声のみ＞ジョーカー！ アンタの力、見せてくれ！

[msg BTL_MES_007_078]
＜声のみ＞スカル！ 遠慮はいらねーかんな！

[msg BTL_MES_007_079]
＜声のみ＞パンサー、まかせたっスよ！

[msg BTL_MES_007_080]
＜声のみ＞モナ！ 頼りにしてっからな！

[msg BTL_MES_007_081]
＜声のみ＞フォックス、キメてくれ！

[msg BTL_MES_007_082]
＜声のみ＞クイーン、ぶちかましちまえ！

[msg BTL_MES_007_083]
＜声のみ＞ダミー

[msg BTL_MES_007_084]
＜声のみ＞へへっ！ ノワール、期待してんぜ！

[msg BTL_MES_007_085]
＜声のみ＞クロウ、ぶちかましてくれ！

[msg BTL_MES_007_086]
All right! Ready to charge in!

