[msg BTL_MES_019_000]
Dummy

[msg BTL_MES_019_001]
We have to win, no matter the odds!

[msg BTL_MES_019_002]
＜声のみ＞大丈夫！ 私たちなら、勝てるって信じてる！

[msg BTL_MES_019_003]
This FOE is quite the menace...

[msg BTL_MES_019_004]
＜声のみ＞うん！ みんな、撤収ー！

[msg BTL_MES_019_005]
Ooh, we might actually manage to take[n]this one down!

[msg BTL_MES_019_006]
Hey, rare Shadow! You're going[n]nowhere!

[msg BTL_MES_019_007]
＜声のみ＞確実に捕らえる！

[msg BTL_MES_019_008]
＜声のみ＞わかったよ、ナビ！

[msg BTL_MES_019_009]
＜声のみ＞了解、りせちゃん！

[msg BTL_MES_019_010]
＜声のみ＞オッケー、風花！

[msg BTL_MES_019_011]
Huh? No way! It looks super strong!

[msg BTL_MES_019_012]
＜声のみ＞ええと…戦う？ それとも撤退する？

[msg BTL_MES_019_013]
Looks like we've been graced with a[n]new enemy. Time to run some tests!

[msg BTL_MES_019_014]
＜声のみ＞そうだね、色々試してみよう！

[msg BTL_MES_019_015]
I think we can win this...

[msg BTL_MES_019_016]
＜声のみ＞全力でいくね…！

[msg BTL_MES_019_017]
All right, chaaaarge!

[msg BTL_MES_019_018]
＜声のみ＞全部まとめて ボッコボコにしちゃおっか！

[msg BTL_MES_019_019]
Huh? Something about the Shadow[n]changed...

[msg BTL_MES_019_020]
＜声のみ＞うそでしょ！？ どうしよう…！

[msg BTL_MES_019_021]
＜声のみ＞もう！ こんな時に来ないでよ！

[msg BTL_MES_019_022]
This is a pretty bad situation, isn't[n]it...

[msg BTL_MES_019_023]
＜声のみ＞た、大変！ 手当てしなきゃ！

[msg BTL_MES_019_024]
＜声のみ＞大丈夫！？ はやく助けなきゃ！

[msg BTL_MES_019_025]
＜声のみ＞無茶はだめだよ！ 今、助けるからね！

[msg BTL_MES_019_026]
＜声のみ＞陽介くん、大丈夫！？ ここは私に任せて！

[msg BTL_MES_019_027]
＜声のみ＞千枝が危ない！ 待ってて、助けるから！

[msg BTL_MES_019_028]
＜声のみ＞雪子がピンチ！ 今、助けるからね！

[msg BTL_MES_019_029]
＜声のみ＞ダミー

[msg BTL_MES_019_030]
＜声のみ＞完二くん、大丈夫！？ 無理は禁物だよ！

[msg BTL_MES_019_031]
＜声のみ＞あっ、直斗くんが！ このままじゃ危ない！

[msg BTL_MES_019_032]
＜声のみ＞クマくん、平気！？ 何とかしなきゃ！

[msg BTL_MES_019_033]
＜声のみ＞ゆかりがピンチになってる！ 助けないと！

[msg BTL_MES_019_034]
＜声のみ＞順平、大丈夫！？ 何とかしないと…！

[msg BTL_MES_019_035]
＜声のみ＞あっ、真田先輩！ 大変…何とかしないと！

[msg BTL_MES_019_036]
＜声のみ＞ウソ、美鶴先輩！？ しっかりしてください！

[msg BTL_MES_019_037]
＜声のみ＞ダミー

[msg BTL_MES_019_038]
＜声のみ＞アイギスが大変なことに…！ すぐ助けるから！

[msg BTL_MES_019_039]
＜声のみ＞あっ、天田くんがピンチ！ 何とかしなきゃ！

[msg BTL_MES_019_040]
＜声のみ＞ああっ、コロマル！ すぐ助けるから！

[msg BTL_MES_019_041]
＜声のみ＞荒垣先輩、無茶しないでください！ すぐに助けます！

[msg BTL_MES_019_042]
＜声のみ＞ダミー

[msg BTL_MES_019_043]
＜声のみ＞大変、ジョーカーが！ すぐに助けるから！

[msg BTL_MES_019_044]
＜声のみ＞うそ、スカルが！ はやく助けなきゃ！

[msg BTL_MES_019_045]
＜声のみ＞パンサー、大丈夫！？ いま助けるから！

[msg BTL_MES_019_046]
＜声のみ＞モナが大変！ すぐに何とかしなきゃ！

[msg BTL_MES_019_047]
＜声のみ＞フォックス、大丈夫！？ 助けるから、踏ん張って！

[msg BTL_MES_019_048]
＜声のみ＞クイーン、しっかり！ 助けるから、待ってて！

[msg BTL_MES_019_049]
＜声のみ＞ダミー

[msg BTL_MES_019_050]
＜声のみ＞大変、ノワールが…！ すぐ助けるから、待ってて！

[msg BTL_MES_019_051]
＜声のみ＞クロウ、どうしたの！？ 大変、すぐに助けなきゃ！

[msg BTL_MES_019_052]
＜声のみ＞弱点はどんどん狙ってこー！

[msg BTL_MES_019_053]
Don't hold back now! Let's do this!

[msg BTL_MES_019_054]
＜声のみ＞よーっし！ 次、いこっか！

[msg BTL_MES_019_055]
I can hit it where it's weak! What do[n]you say?

[msg BTL_MES_019_056]
Baton Pass would be a good way to go[n]as well!

[msg BTL_MES_019_057]
Leave it to me! To victory!

[msg BTL_MES_019_058]
＜声のみ＞うん！ボッコボコにしちゃえ！

[msg BTL_MES_019_059]
＜声のみ＞うん、任せたよっ！

[msg BTL_MES_019_060]
＜声のみ＞陽介くん、思いっきりやっちゃって！

[msg BTL_MES_019_061]
＜声のみ＞千枝、ぶっとばせー！

[msg BTL_MES_019_062]
＜声のみ＞燃やし尽くしちゃえ、雪子！

[msg BTL_MES_019_063]
＜声のみ＞ダミー

[msg BTL_MES_019_064]
＜声のみ＞完二くん、たのんだー！

[msg BTL_MES_019_065]
＜声のみ＞直斗くん、キメちゃって！

[msg BTL_MES_019_066]
＜声のみ＞クマくん、やっちゃえー！

[msg BTL_MES_019_067]
＜声のみ＞ゆかりなら 絶対にキメてくれる！

[msg BTL_MES_019_068]
＜声のみ＞順平、たまにはカッコいいとこ見せて！

[msg BTL_MES_019_069]
＜声のみ＞真田先輩、やっちゃってください！

[msg BTL_MES_019_070]
＜声のみ＞美鶴先輩、ブリリアントにお願いします！

[msg BTL_MES_019_071]
＜声のみ＞ダミー

[msg BTL_MES_019_072]
＜声のみ＞頼んだ！ アイギスならキメてくれるはず！

[msg BTL_MES_019_073]
＜声のみ＞天田くん、頑張って！

[msg BTL_MES_019_074]
＜声のみ＞コロマル、いっけー！

[msg BTL_MES_019_075]
＜声のみ＞荒垣先輩、信じてます！

[msg BTL_MES_019_076]
＜声のみ＞ダミー

[msg BTL_MES_019_077]
＜声のみ＞ジョーカー、派手に決めちゃって！

[msg BTL_MES_019_078]
＜声のみ＞いっけー、スカル！

[msg BTL_MES_019_079]
＜声のみ＞パンサー、遠慮はいらないからね！

[msg BTL_MES_019_080]
＜声のみ＞モナ、メラメラに 燃えてるねー！

[msg BTL_MES_019_081]
＜声のみ＞フォックス、華麗に決めちゃって！

[msg BTL_MES_019_082]
＜声のみ＞クイーンの実力、見せつけちゃって！

[msg BTL_MES_019_083]
＜声のみ＞ダミー

[msg BTL_MES_019_084]
＜声のみ＞遠慮はいらないよ！ ノワール、暴れちゃえ！

[msg BTL_MES_019_085]
＜声のみ＞クロウ、期待してるからね！

[msg BTL_MES_019_086]
I've got this... Prepare to be[n]amazed!

