[msg BTL_MES_022_000]
Dummy

[msg BTL_MES_022_001]
We can't stop here!

[msg BTL_MES_022_002]
＜声のみ＞まかせて！ 絶対に負けないから！

[msg BTL_MES_022_003]
An FOE!? There's no way we can fight[n]that right now!

[msg BTL_MES_022_004]
＜声のみ＞うん、了解 今は無茶しないでおくね

[msg BTL_MES_022_005]
We might be able to win this...

[msg BTL_MES_022_006]
A rare Shadow! Don't let it get away!

[msg BTL_MES_022_007]
＜声のみ＞オッケー！ あいつ、狙ってみる！

[msg BTL_MES_022_008]
＜声のみ＞オッケー！ ナビ、ありがとう！

[msg BTL_MES_022_009]
＜声のみ＞りせちゃん、了解！

[msg BTL_MES_022_010]
＜声のみ＞風花ちゃん、了解！ まかせて！

[msg BTL_MES_022_011]
Crap, this one looks tough... What do[n]we do?

[msg BTL_MES_022_012]
＜声のみ＞ね、ねえ、戦うの？ なんか、やばくない…？

[msg BTL_MES_022_013]
We've never seen this one before.[n]Should we try to find its weakness?

[msg BTL_MES_022_014]
＜声のみ＞どうする？ 何から試そっか

[msg BTL_MES_022_015]
No big. We got this.

[msg BTL_MES_022_016]
＜声のみ＞だいじょーぶ！ まかせてって！

[msg BTL_MES_022_017]
Think we can get it in one shot?

[msg BTL_MES_022_018]
＜声のみ＞ふふっ お仕置きして、あ・げ・る！

[msg BTL_MES_022_019]
What's this thing's deal!?

[msg BTL_MES_022_020]
＜声のみ＞もしかしなくても… ピンチ！？

[msg BTL_MES_022_021]
＜声のみ＞ああもう！ どうするの、コレ！

[msg BTL_MES_022_022]
This doesn't look good!

[msg BTL_MES_022_023]
＜声のみ＞ちょ、みんなヤバい！ 助けなきゃ…！

[msg BTL_MES_022_024]
＜声のみ＞ちょっとヤバくない？ 回復しなきゃ！

[msg BTL_MES_022_025]
＜声のみ＞ちょっとちょっと大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_026]
＜声のみ＞陽介くんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_027]
＜声のみ＞千枝ちゃん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_028]
＜声のみ＞雪子ちゃん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_029]
＜声のみ＞ダミー

[msg BTL_MES_022_030]
＜声のみ＞完二くんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_031]
＜声のみ＞直斗くん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_032]
＜声のみ＞クマくんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_033]
＜声のみ＞ゆかりちゃん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_034]
＜声のみ＞順平くんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_035]
＜声のみ＞真田さん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_036]
＜声のみ＞美鶴さん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_037]
＜声のみ＞ダミー

[msg BTL_MES_022_038]
＜声のみ＞アイギス大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_039]
＜声のみ＞乾くんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_040]
＜声のみ＞コロちゃん大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_041]
＜声のみ＞荒垣さんがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_042]
＜声のみ＞無茶しちゃってるよ！ 回復しなきゃ！

[msg BTL_MES_022_043]
＜声のみ＞ジョーカー大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_044]
＜声のみ＞スカルがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_045]
Dummy

[msg BTL_MES_022_046]
＜声のみ＞モナがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_047]
＜声のみ＞フォックスがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_048]
＜声のみ＞クイーン大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_049]
＜声のみ＞ダミー

[msg BTL_MES_022_050]
＜声のみ＞ノワール大丈夫？ 回復しなきゃ！

[msg BTL_MES_022_051]
＜声のみ＞クロウがヤバイね… 回復が必要なんじゃない？

[msg BTL_MES_022_052]
＜声のみ＞オッケー！ 一網打尽ね！

[msg BTL_MES_022_053]
We may have a chance! Let's keep at[n]it!

[msg BTL_MES_022_054]
＜声のみ＞あったりまえじゃない！ いくわよー！

[msg BTL_MES_022_055]
Oh! I think we can hit its weakness!

[msg BTL_MES_022_056]
Are we doing a Baton Pass?

[msg BTL_MES_022_057]
Oh! Looks like I'm up!

[msg BTL_MES_022_058]
＜声のみ＞うん！頼りにしてるからね！

[msg BTL_MES_022_059]
＜声のみ＞うん！任せたよ！

[msg BTL_MES_022_060]
＜声のみ＞陽介くん、頼りにしてるよ！

[msg BTL_MES_022_061]
＜声のみ＞千枝ちゃん、いっけええええ！

[msg BTL_MES_022_062]
＜声のみ＞雪子ちゃん、頑張って！

[msg BTL_MES_022_063]
＜声のみ＞ダミー

[msg BTL_MES_022_064]
＜声のみ＞完二くん！ 後はまかせたからね！？

[msg BTL_MES_022_065]
＜声のみ＞直斗くん、かっこいいじゃん！

[msg BTL_MES_022_066]
＜声のみ＞クマくん、ファイト…！

[msg BTL_MES_022_067]
＜声のみ＞ゆかりちゃん、まかせたからね！

[msg BTL_MES_022_068]
＜声のみ＞順平くんならやってくれるでしょ！

[msg BTL_MES_022_069]
＜声のみ＞真田さん、 一気にきめちゃってください！

[msg BTL_MES_022_070]
＜声のみ＞美鶴さんったら頼もしいー！

[msg BTL_MES_022_071]
＜声のみ＞ダミー

[msg BTL_MES_022_072]
＜声のみ＞ゴーゴー、アイギス！

[msg BTL_MES_022_073]
＜声のみ＞乾くん、よろしく！

[msg BTL_MES_022_074]
＜声のみ＞コロマル、頼りにしてるからね！

[msg BTL_MES_022_075]
＜声のみ＞荒垣さん、お願いします！

[msg BTL_MES_022_076]
＜声のみ＞やっちゃえ、やっちゃえ！

[msg BTL_MES_022_077]
＜声のみ＞やった！ ジョーカー、いっけー！

[msg BTL_MES_022_078]
＜声のみ＞スカルも 頼りになるじゃん！

[msg BTL_MES_022_079]
＜声のみ＞ダミー

[msg BTL_MES_022_080]
＜声のみ＞モナー！ がーんーばーれー！

[msg BTL_MES_022_081]
＜声のみ＞フォックス、集中集中！

[msg BTL_MES_022_082]
＜声のみ＞キャー！ クイーンったら、かっこいいー！

[msg BTL_MES_022_083]
＜声のみ＞ダミー

[msg BTL_MES_022_084]
＜声のみ＞ノワール、頼りになるね！

[msg BTL_MES_022_085]
＜声のみ＞クロウなら やってくれるよね

[msg BTL_MES_022_086]
I think I can handle this! Leave it[n]to me!

