[msg BTL_MES_026_000]
Dummy

[msg BTL_MES_026_001]
This enemy looks rather formidable...

[msg BTL_MES_026_002]
I will be praying for everyone's[n]success.

[msg BTL_MES_026_003]
An FOE... This looks dangerous...

[msg BTL_MES_026_004]
Yes, I recommend an immediate[n]withdrawal.

[msg BTL_MES_026_005]
This FOE... You may be able to defeat[n]it now.

[msg BTL_MES_026_006]
That enemy's defenses are strong. It[n]would be best if you devised a plan.

[msg BTL_MES_026_007]
This enemy has frighteningly powerful[n]abilities. Be on your guard.

[msg BTL_MES_026_008]
とろれ らめをれもぼぺゅ ぺろろぺぼやれ ぺるま るぺろめまる[n]ぽぺょむまるよゎれテテテ っよょ'ろ ゅまろ をよゎる むゎぺるぽ ぽよゐょテ

[msg BTL_MES_026_009]
That enemy's magic attacks are[n]trouble. Keep an eye on your health.

[msg BTL_MES_026_010]
The more damage it receives, the more[n]it struggles. Fell it in one blow.

[msg BTL_MES_026_011]
Oh... A rare enemy?

[msg BTL_MES_026_012]
You've met with a rare enemy. It[n]would be a shame to let it escape.

[msg BTL_MES_026_013]
This enemy is capable of attacking[n]everyone at once.

[msg BTL_MES_026_014]
It appears this one can attack the[n]entire party at once.

[msg BTL_MES_026_015]
The enemy's attacks have an area[n]effect. Don't forget to guard.

[msg BTL_MES_026_016]
とろ ゅよよやれ ゅもやま もろ ぼぺょ ゎれま ぺるまぺ ぺろろぺぼやれテテテ[n]っよょ'ろ みよるむまろ ろよ むゎぺるぽデ まわまるをよょまテ

[msg BTL_MES_026_017]
The enemy is capable of using instant[n]kill attacks...

[msg BTL_MES_026_018]
It appears it can use instant kill[n]attacks... Truly a fearsome enemy.

[msg BTL_MES_026_019]
Affinity attacks are useless right[n]now. Focus on physical attacks.

[msg BTL_MES_026_020]
Precisely. Affinity attacks are[n]ineffective.

[msg BTL_MES_026_021]
A powerful attack is coming up next.

[msg BTL_MES_026_022]
I advise you double down on defense.

[msg BTL_MES_026_023]
This is a powerful enemy... Stay[n]alert.

[msg BTL_MES_026_024]
The enemy appears to be rather[n]powerful... Stay alert, everyone.

[msg BTL_MES_026_025]
ぶま'わま ょよ ぽぺろぺ よょ ろめもれ よょまテテテ とろ ゐよゎゅぽ ほま[n]ほまれろ ろよ むぺろめまる ゆよるま もょみよるゆぺろもよょ みもるれろテ

[msg BTL_MES_026_026]
We need more information first. Try[n]testing a wide range of attacks.

[msg BTL_MES_026_027]
It seems you and the enemy are equal[n]in strength.

[msg BTL_MES_026_028]
びめまを ゅよよや ろよ ほま ぺほよゎろ まりゎぺゅ もょ れろるまょむろめテ[n]びめぺろ れぺもぽデ ぽよょ'ろ ゎょぽまるまれろもゆぺろま ろめまゆテ

[msg BTL_MES_026_029]
とろ れままゆれ ろめまを ぺるま ほまょまぺろめ をよゎテテテ へよゎ れめよゎゅぽ[n]めぺわま ょよ ろるよゎほゅま ぽまみまぺろもょむ ろめまゆテ

[msg BTL_MES_026_030]
They're weak... I'd say they pose[n]little threat.

[msg BTL_MES_026_031]
The enemy's appearance has changed.[n]Perhaps you can strike its weakness.

[msg BTL_MES_026_032]
I believe it's now possible to strike[n]its weakness.

[msg BTL_MES_026_033]
と ぺゆ ゎょぺほゅま ろよ ゅよぼぺろま ぺょ まれぼぺらま るよゎろまテ とろ[n]れままゆれ をよゎ'ゅゅ めぺわま ろよ めよゅぽ よゎろ みよる ょよゐテテテ

[msg BTL_MES_026_034]
...In that case, you'll have to hold[n]out for the time being.

[msg BTL_MES_026_035]
An FOE joined the battle...?

[msg BTL_MES_026_036]
The situation has changed. I advise[n]you adjust accordingly!

[msg BTL_MES_026_037]
You should be mindful of your[n]remaining health.

[msg BTL_MES_026_038]
Be careful. Someone's health is[n]dangerously low.

[msg BTL_MES_026_039]
Yosuke has sustained significant[n]damage.

[msg BTL_MES_026_040]
Chie's health has reached critical.[n]Do be careful.

[msg BTL_MES_026_041]
Be wary of Yukiko's remaining health.

[msg BTL_MES_026_042]
ダミー

[msg BTL_MES_026_043]
Kanji has very little health[n]remaining.

[msg BTL_MES_026_044]
Naoto's health has been severely[n]depleted...

[msg BTL_MES_026_045]
Teddie has taken quite a beating...[n]He appears to be in trouble.

[msg BTL_MES_026_046]
Yukari looks rather unwell. Perhaps[n]you should offer some assistance.

[msg BTL_MES_026_047]
Junpei is going to fall if you don't[n]offer support.

[msg BTL_MES_026_048]
Akihiko's condition is quite[n]severe...

[msg BTL_MES_026_049]
Be careful. Mitsuru has very little[n]health remaining.

[msg BTL_MES_026_050]
ダミー

[msg BTL_MES_026_051]
Careful, Aigis. You won't be able to[n]last much longer.

[msg BTL_MES_026_052]
Ken's situation is dangerous.

[msg BTL_MES_026_053]
Keep an eye on Koromaru's health.

[msg BTL_MES_026_054]
Shinjiro's health is concerning.

[msg BTL_MES_026_055]
Someone is very low on health.

[msg BTL_MES_026_056]
Caution! Someone has sustained[n]serious damage.

[msg BTL_MES_026_057]
It's dangerous to leave Skull as he[n]is now...

[msg BTL_MES_026_058]
Please be mindful of Panther's[n]health. It's dangerously low.

[msg BTL_MES_026_059]
Will Mona be all right in this[n]condition...?

[msg BTL_MES_026_060]
Fox has taken significant damage.

[msg BTL_MES_026_061]
I believe Queen is in danger.

[msg BTL_MES_026_062]
ダミー

[msg BTL_MES_026_063]
Be mindful of Noir's health.

[msg BTL_MES_026_064]
It appears Crow is about to faint...[n]What will you do?

[msg BTL_MES_026_065]
Let's see... I suggest you prioritize[n]recovering your health first.

[msg BTL_MES_026_066]
Oh my... It appears someone has been[n]petrified...

[msg BTL_MES_026_067]
Someone has been hexed...

[msg BTL_MES_026_068]
Someone has been poisoned...

[msg BTL_MES_026_069]
ひよゆまよょま めぺれ みぺゅゅまょ ぺれゅままらテテテ びめまを'ゅゅ ほま もょ[n]ぽぺょむまる もみ ろめまを ぽよょ'ろ ゐぺやま ゎら れよよょテ

[msg BTL_MES_026_070]
Someone is confused. Stay cautious.

[msg BTL_MES_026_071]
Someone has been paralyzed... They[n]may have trouble moving...

[msg BTL_MES_026_072]
Someone seems to be dizzy...

[msg BTL_MES_026_073]
Someone has had their magic bound...

[msg BTL_MES_026_074]
Someone has been strength bound...

[msg BTL_MES_026_075]
Someone has been agility bound...

[msg BTL_MES_026_076]
Does anyone possess any recovery[n]skills? The situation is dire.

[msg BTL_MES_026_077]
One of these enemies is weak to[n]physical attacks.

[msg BTL_MES_026_078]
One of these enemies is weak to Fire.

[msg BTL_MES_026_079]
The enemy appears to be weak to Ice.

[msg BTL_MES_026_080]
An enemy is weak to the Wind[n]affinity.

[msg BTL_MES_026_081]
The enemy is weak to Electricity.

[msg BTL_MES_026_082]
Nuclear attacks should prove[n]effective here...

[msg BTL_MES_026_083]
This enemy appears to be weak to[n]Psychokinesis.

[msg BTL_MES_026_084]
One of these is weak to Bless.

[msg BTL_MES_026_085]
One of these enemies is weak to[n]Curse.

[msg BTL_MES_026_086]
This enemy appears to be weak to[n]physical attacks...

[msg BTL_MES_026_087]
The enemy appears to be weak to Fire.

[msg BTL_MES_026_088]
You can use Ice to strike its[n]weakness.

[msg BTL_MES_026_089]
Wind is effective against this enemy.

[msg BTL_MES_026_090]
One of these enemies is weak to[n]Electricity.

[msg BTL_MES_026_091]
I suggest using Nuclear skills to[n]strike its weakness.

[msg BTL_MES_026_092]
There is an enemy present that is[n]weak to Psychokinesis...

[msg BTL_MES_026_093]
Do you have any Bless skills? One of[n]the enemies is weak to them.

[msg BTL_MES_026_094]
It appears the enemy is weak to[n]Curse.

[msg BTL_MES_026_095]
Well then, now is your time to shine,[n]"Big Bro"...

[msg BTL_MES_026_096]
*chuckle* Now that you know, your[n]victory is assured.

[msg BTL_MES_026_097]
...There you have it, Yosuke. Don't[n]disappoint us.

[msg BTL_MES_026_098]
...I see. Did you hear that, Chie?

[msg BTL_MES_026_099]
...Do you mean to say it's a perfect[n]match for you, Yukiko?

[msg BTL_MES_026_100]
Dummy

[msg BTL_MES_026_101]
Oh...? In that case, this may be the[n]perfect opponent for you, Kanji.

[msg BTL_MES_026_102]
This may be your moment, Naoto.

[msg BTL_MES_026_103]
Well then, shall we leave this to[n]you, Teddie? *chuckle*

[msg BTL_MES_026_104]
It seems it's your turn, Yukari.

[msg BTL_MES_026_105]
I've no doubt that you'll meet[n]everyone's expectations, Junpei.

[msg BTL_MES_026_106]
In that case, should Akihiko be the[n]one to go?

[msg BTL_MES_026_107]
I am looking forward to seeing[n]Mitsuru in action.

[msg BTL_MES_026_108]
ダミー

[msg BTL_MES_026_109]
I believe Aigis would be best suited[n]for this.

[msg BTL_MES_026_110]
By all means, I would very much like[n]to observe your capabilities, Ken.

[msg BTL_MES_026_111]
In other words, Koromaru, you're the[n]ideal choice in this situation.

[msg BTL_MES_026_112]
Well, Shinjiro, I believe you're up.

[msg BTL_MES_026_113]
Then, we'd best take the opportunity.[n]Good luck, everyone.

[msg BTL_MES_026_114]
...Then, you have your target.

[msg BTL_MES_026_115]
...So it would seem. Can you take[n]care of it, Skull?

[msg BTL_MES_026_116]
I see... Then, I suppose it's[n]Panther's turn.

[msg BTL_MES_026_117]
...Well then, do you think you can[n]handle it, Mona?

[msg BTL_MES_026_118]
Don't worry. Fox is perfectly suited[n]to handle this situation.

[msg BTL_MES_026_119]
Perhaps Queen can do something about[n]this...

[msg BTL_MES_026_120]
ダミー

[msg BTL_MES_026_121]
Well, well. I do believe this is[n]Noir's forte...

[msg BTL_MES_026_122]
In that case, it would seem it's[n]Crow's turn.

[msg BTL_MES_026_123]
Things are going well...

[msg BTL_MES_026_124]
The enemy is still standing...

[msg BTL_MES_026_125]
ひゎぼめ ぺ ゅぺぼや よみ ろまょれもよょテ はぺを ゆよるま[n]ぺろ-ろまょれもよょテテテ びめぺろ ゐぺれ ぺ ソゼ-らよもょろ らゎょテ

[msg BTL_MES_026_126]
There is no cause for concern.[n]However, you shouldn't be complacent.

[msg BTL_MES_026_127]
Why not try using a Baton Pass to aim[n]for its weakness?

[msg BTL_MES_026_128]
A Baton Pass will allow you to strike[n]its weakness.

[msg BTL_MES_026_129]
It seems you've been boosted...

[msg BTL_MES_026_130]
Someone appears to have been[n]boosted...

[msg BTL_MES_026_131]
Yosuke has earned a boost.

[msg BTL_MES_026_132]
It seems Chie has gained a boost.

[msg BTL_MES_026_133]
Yukiko's condition appears to have[n]been boosted.

[msg BTL_MES_026_134]
ダミー

[msg BTL_MES_026_135]
Kanji has received a boost.

[msg BTL_MES_026_136]
Naoto's condition has been boosted.

[msg BTL_MES_026_137]
Teddie has gained a boost.

[msg BTL_MES_026_138]
Yukari earned herself a boost.

[msg BTL_MES_026_139]
Junpei has been given a boost.

[msg BTL_MES_026_140]
*chuckle* Akihiko is now even more[n]charged thanks to a boost...

[msg BTL_MES_026_141]
Oh... Mitsuru has received a boost.

[msg BTL_MES_026_142]
ダミー

[msg BTL_MES_026_143]
Oh? Aigis has received a boost.

[msg BTL_MES_026_144]
Ken has earned a boost. He's sure to[n]perform well.

[msg BTL_MES_026_145]
Koromaru just received a boost.

[msg BTL_MES_026_146]
Shinjiro earned a boost... *chuckle*[n]I wonder how this will play out.

[msg BTL_MES_026_147]
のめ? とろ れままゆれ れよゆまよょま めぺれ るまぼまもわまぽ ぺ ほよよれろテ[n]びめまを'るま れゎるま ろよ ほま まわまょ れろるよょむまるテ

[msg BTL_MES_026_148]
Oh... It appears someone has earned a[n]boost.

[msg BTL_MES_026_149]
Skull has earned a boost.

[msg BTL_MES_026_150]
Panther has received a boost.

[msg BTL_MES_026_151]
Mona has received a boost...[n]*chuckle* Take them all down.

[msg BTL_MES_026_152]
Fox received a boost. This looks[n]promising.

[msg BTL_MES_026_153]
Queen has received a boost.

[msg BTL_MES_026_154]
ダミー

[msg BTL_MES_026_155]
Noir seems to have acquired a boost.

[msg BTL_MES_026_156]
Crow has earned a boost. Use it to[n]its full potential.

[msg BTL_MES_026_157]
You can aim for its weakness. Don't[n]waste the opportunity.

[msg BTL_MES_026_158]
You can now strike its weakness. How[n]will you proceed?

[msg BTL_MES_026_159]
Support is ready to use whenever you[n]wish.

[msg BTL_MES_026_160]
Support is prepared and ready.[n]Perhaps now is a good time.

[msg BTL_MES_026_161]
Wow... That one looks really scary...

[msg BTL_MES_026_162]
You can do it, everyone!

[msg BTL_MES_026_163]
*gasp* It's an F-O...thing!

[msg BTL_MES_026_164]
Run, everyone!

[msg BTL_MES_026_165]
Oh, it's a Film... Hehe... I forgot[n]what they're called.

[msg BTL_MES_026_166]
That one looks really tough. Do you[n]think you can beat it?

[msg BTL_MES_026_167]
That one looks really strong. Be[n]careful.

[msg BTL_MES_026_168]
It's got really strong phy... P-H-Y―[n]physical attacks! Watch out!

[msg BTL_MES_026_169]
It uses magic attacks. Magic can be[n]really scary sometimes...

[msg BTL_MES_026_170]
The more you hit that one, the harder[n]it fights. You gotta beat it quick.

[msg BTL_MES_026_171]
Ooh, that one's shiny. It's so[n]pretty!

[msg BTL_MES_026_172]
Wow! It's all sparkly!

[msg BTL_MES_026_173]
Wha―? That one looks really tough...

[msg BTL_MES_026_174]
Does that mean it's dangerous?

[msg BTL_MES_026_175]
Th-That one looks strong... Is[n]everyone okay?

[msg BTL_MES_026_176]
Okay! I won't forget it!

[msg BTL_MES_026_177]
I don't really know why, but... I'm[n]scared...

[msg BTL_MES_026_178]
Um... What does that mean?

[msg BTL_MES_026_179]
Um... I think you have to use[n]physical attacks for now!

[msg BTL_MES_026_180]
Um... I don't really know what's[n]going on, but I'm cheering for you!

[msg BTL_MES_026_181]
The next attack is gonna be a big[n]one!

[msg BTL_MES_026_182]
Make sure you block! Don't forget!

[msg BTL_MES_026_183]
*gasp* This doesn't look good!

[msg BTL_MES_026_184]
U-Um... If it looks dangerous, we[n]should run away!

[msg BTL_MES_026_185]
Um... We've never seen that one[n]before.

[msg BTL_MES_026_186]
Okay, then, let's try all kinds of[n]attacks!

[msg BTL_MES_026_187]
Ah! We're under attack!

[msg BTL_MES_026_188]
B-Be careful!

[msg BTL_MES_026_189]
This should be an easy one!

[msg BTL_MES_026_190]
We should still be careful!

[msg BTL_MES_026_191]
Um... that one looks kind of[n]different now.

[msg BTL_MES_026_192]
Yeah! I'm sure we can beat them now!

[msg BTL_MES_026_193]
Oh no... There's no way out!

[msg BTL_MES_026_194]
Wha―!? Wh-What do we do...?

[msg BTL_MES_026_195]
*gasp* A really scary one showed up!

[msg BTL_MES_026_196]
Aaah... What do we do?

[msg BTL_MES_026_197]
*gasp* Big Bro is in trouble!

[msg BTL_MES_026_198]
Someone's really hurt! What do we[n]do!?

[msg BTL_MES_026_199]
What's wrong, Yosuke?

[msg BTL_MES_026_200]
Chie looks hurt...

[msg BTL_MES_026_201]
Yukiko can barely stand!

[msg BTL_MES_026_202]
ダミー

[msg BTL_MES_026_203]
Kanji looks like he's in trouble!

[msg BTL_MES_026_204]
Naoto looks like she needs help...

[msg BTL_MES_026_205]
Teddie! Are you okay!?

[msg BTL_MES_026_206]
Yukari doesn't look too good.

[msg BTL_MES_026_207]
Are you okay, Junpei?

[msg BTL_MES_026_208]
Akihiko is in trouble!

[msg BTL_MES_026_209]
Mitsuru needs help...

[msg BTL_MES_026_210]
ダミー

[msg BTL_MES_026_211]
Aigis looks tired...

[msg BTL_MES_026_212]
Are you hurt, Ken?

[msg BTL_MES_026_213]
Oh no! Koro-chan!

[msg BTL_MES_026_214]
Shinjiro looks hurt...

[msg BTL_MES_026_215]
Oh no! Someone's in trouble!

[msg BTL_MES_026_216]
*gasp* Someone looks really hurt! Be[n]careful!

[msg BTL_MES_026_217]
Skull looks really hurt...

[msg BTL_MES_026_218]
Panther, are you all right!?

[msg BTL_MES_026_219]
Ah! Mona looks really beat-up!

[msg BTL_MES_026_220]
Fox looks like he's in trouble!

[msg BTL_MES_026_221]
Queen looks really hurt...

[msg BTL_MES_026_222]
Dummy

[msg BTL_MES_026_223]
Stay in it, Noir!

[msg BTL_MES_026_224]
Crow's in trouble...

[msg BTL_MES_026_225]
Quick, someone help!

[msg BTL_MES_026_226]
Oh no, you've been turned to stone!

[msg BTL_MES_026_227]
You were hexed? How do we fix it?

[msg BTL_MES_026_228]
Ah! Someone's been poisoned!

[msg BTL_MES_026_229]
You can't sleep now! Wake up!

[msg BTL_MES_026_230]
Something seems wrong... What[n]happened?

[msg BTL_MES_026_231]
Ah! Someone's been shocked!

[msg BTL_MES_026_232]
They passed out...? Hold on!

[msg BTL_MES_026_233]
You can't use magic right now!

[msg BTL_MES_026_234]
Um... your strength is bound.

[msg BTL_MES_026_235]
You've been slowed down.

[msg BTL_MES_026_236]
Oh no! We have to do something!

[msg BTL_MES_026_237]
That one doesn't like... Oh! Physical[n]attacks!

[msg BTL_MES_026_238]
That one doesn't like heat.

[msg BTL_MES_026_239]
It looks like that one hates the[n]cold!

[msg BTL_MES_026_240]
That one is weak to strong winds!

[msg BTL_MES_026_241]
That one hates being shocked!

[msg BTL_MES_026_242]
That enemy's weak to... Nu-cle-ar?[n]Yeah, that!

[msg BTL_MES_026_243]
That enemy doesn't like... Psy? Yeah,[n]that's its weakness!

[msg BTL_MES_026_244]
That one's weak to Bless!

[msg BTL_MES_026_245]
Curse...? I don't really know what[n]that is, but you should use it!

[msg BTL_MES_026_246]
Oh! One of these enemies hates[n]physical attacks!

[msg BTL_MES_026_247]
One of them doesn't like heat! Maybe[n]it'll run away if it gets too hot?

[msg BTL_MES_026_248]
Um, that one... That one can't handle[n]the cold!

[msg BTL_MES_026_249]
That one doesn't like Wind.

[msg BTL_MES_026_250]
That one... Oh! That one hates[n]electric attacks!

[msg BTL_MES_026_251]
Um... Nu... clear? That's its[n]weakness!

[msg BTL_MES_026_252]
What is... Psy? Whatever it is, the[n]enemy doesn't like it!

[msg BTL_MES_026_253]
Oh, I remember! It hates Bless!

[msg BTL_MES_026_254]
That enemy doesn't like Curse...![n]What's Curse?

[msg BTL_MES_026_255]
You can do it, big bro!

[msg BTL_MES_026_256]
I'm cheering for you!

[msg BTL_MES_026_257]
Yosuke can win with the power of[n]Junes, right?

[msg BTL_MES_026_258]
You can do it, Chie!

[msg BTL_MES_026_259]
Go for it, Yukiko!

[msg BTL_MES_026_260]
ダミー

[msg BTL_MES_026_261]
I'm cheering for you, Kanji!

[msg BTL_MES_026_262]
Go Naoto, go!

[msg BTL_MES_026_263]
You can do it, Teddie!

[msg BTL_MES_026_264]
Go for it, Yukari!

[msg BTL_MES_026_265]
I believe in you, Junpei!

[msg BTL_MES_026_266]
Go for it, Akihiko!

[msg BTL_MES_026_267]
Don't give up, Mitsuru!

[msg BTL_MES_026_268]
ダミー

[msg BTL_MES_026_269]
I'm cheering for you, Aigis!

[msg BTL_MES_026_270]
I'm cheering for you, Ken!

[msg BTL_MES_026_271]
You can do it, Koro-chan!

[msg BTL_MES_026_272]
Go, Shinjiro!

[msg BTL_MES_026_273]
I believe in you!

[msg BTL_MES_026_274]
I'm cheering for you!

[msg BTL_MES_026_275]
Go for it, Skull!

[msg BTL_MES_026_276]
You can do it, Panther!

[msg BTL_MES_026_277]
You can do it, Mona!

[msg BTL_MES_026_278]
I'm cheering for you, Fox!

[msg BTL_MES_026_279]
I believe in you, Queen!

[msg BTL_MES_026_280]
ダミー

[msg BTL_MES_026_281]
I believe in you, Noir!

[msg BTL_MES_026_282]
You can do it, Crow!

[msg BTL_MES_026_283]
Everybody is so strong!

[msg BTL_MES_026_284]
Everyone's doing great!

[msg BTL_MES_026_285]
Yeah! You're all amazing!

[msg BTL_MES_026_286]
You can win for sure! I just know it!

[msg BTL_MES_026_287]
Oh! You can switch now!

[msg BTL_MES_026_288]
Yeah, I think so too!

[msg BTL_MES_026_289]
Wow, big bro got a boost! That's[n]amazing!

[msg BTL_MES_026_290]
Wow, you got a boost!

[msg BTL_MES_026_291]
Ah! Yosuke got a boost!

[msg BTL_MES_026_292]
Ooh, look! Chie got a boost! Wow!

[msg BTL_MES_026_293]
Ah! Yukiko's been boosted!

[msg BTL_MES_026_294]
ダミー

[msg BTL_MES_026_295]
Kanji's been boosted! Go, go, go!

[msg BTL_MES_026_296]
Naoto's been boosted!

[msg BTL_MES_026_297]
Teddie got a boost! Wow!

[msg BTL_MES_026_298]
Yukari's been boosted! She looks so[n]cool!

[msg BTL_MES_026_299]
Junpei's been boosted! Cool!

[msg BTL_MES_026_300]
Wow, Akihiko got a boost! I'm[n]cheering for you!

[msg BTL_MES_026_301]
Mitsuru got a boost! Go, Mitsuru!

[msg BTL_MES_026_302]
ダミー

[msg BTL_MES_026_303]
Aigis got a boost! She looks so cool!

[msg BTL_MES_026_304]
Wow! Ken got a boost!

[msg BTL_MES_026_305]
Koro-chan got a boost! Cool!

[msg BTL_MES_026_306]
Shinjiro got a boost!

[msg BTL_MES_026_307]
Wow, you look so strong after that[n]boost!

[msg BTL_MES_026_308]
Oh! Someone got a boost! You can do[n]it!

[msg BTL_MES_026_309]
Skull got a boost! Wow!

[msg BTL_MES_026_310]
Panther got a boost!

[msg BTL_MES_026_311]
Ah! Mona got a boost!

[msg BTL_MES_026_312]
Fox has been boosted!

[msg BTL_MES_026_313]
Queen got a boost! Wow!

[msg BTL_MES_026_314]
ダミー

[msg BTL_MES_026_315]
Wow, Noir got a boost!

[msg BTL_MES_026_316]
Crow's been boosted! Wow!

[msg BTL_MES_026_317]
Wow! That's so cool!

[msg BTL_MES_026_318]
Wow... You look so strong!

[msg BTL_MES_026_319]
Oh, support's ready. Do you think you[n]should use it?

[msg BTL_MES_026_320]
Support's ready! Use it when you need[n]it!

