[msg BTL_MES_026_000]
DUMMY

[msg BTL_MES_026_001]
Hm... This guy's worth fighting.

[msg BTL_MES_026_002]
There you have it! Now, take care of[n]them!

[msg BTL_MES_026_003]
W-Whoa! That guy's way above your[n]league!

[msg BTL_MES_026_004]
Fall back! Retreat! Get going[n]already!

[msg BTL_MES_026_005]
Hm... Perhaps you truly are strong[n]enough...

[msg BTL_MES_026_006]
That one's tough. You'll need to take[n]a different approach.

[msg BTL_MES_026_007]
That one has a strong attack. Don't[n]let it catch you off guard.

[msg BTL_MES_026_008]
This guy's physical attack is a[n]nuisance. Don't you forget that.

[msg BTL_MES_026_009]
Watch out for its magic attacks. Stay[n]alert!

[msg BTL_MES_026_010]
It gets violent when it grows weak.[n]Kill it quickly!

[msg BTL_MES_026_011]
Wow... The way it shines...

[msg BTL_MES_026_012]
Hey, don't let it escape!

[msg BTL_MES_026_013]
Hm... This one has an attack that'll[n]hit all of you at once!

[msg BTL_MES_026_014]
Keep an eye on your allies! Are they[n]doing all right?

[msg BTL_MES_026_015]
That one has an attack that hits[n]multiple targets!

[msg BTL_MES_026_016]
Hey, don't forget to guard!

[msg BTL_MES_026_017]
This one... It's got an instant kill[n]attack!

[msg BTL_MES_026_018]
Hey! Stay alert!

[msg BTL_MES_026_019]
Hey, don't use any affinity attacks[n]right now!

[msg BTL_MES_026_020]
Then use your physical attacks!

[msg BTL_MES_026_021]
Watch out! Huge hit, incoming!

[msg BTL_MES_026_022]
Prepare for impact!

[msg BTL_MES_026_023]
This one seems to be quite tough.

[msg BTL_MES_026_024]
Hey, don't push yourself too hard! We[n]can't have you dying here!

[msg BTL_MES_026_025]
Hm? We've never seen that one[n]before...

[msg BTL_MES_026_026]
First things first―try out different[n]skills!

[msg BTL_MES_026_027]
The Shadow here is perfect for you!

[msg BTL_MES_026_028]
In other words, it's easy prey![n]Finish it!

[msg BTL_MES_026_029]
Eh, just a small fry.

[msg BTL_MES_026_030]
Hmph! Then it shouldn't take long!

[msg BTL_MES_026_031]
Hm? The Shadow's affinities changed!

[msg BTL_MES_026_032]
Now's your chance! Exploit its[n]weakness!

[msg BTL_MES_026_033]
Tch... No good!

[msg BTL_MES_026_034]
In other words, we couldn't escape![n]Keep yourselves alive!

[msg BTL_MES_026_035]
What? Now!?

[msg BTL_MES_026_036]
It's an FOE! This is NOT good!

[msg BTL_MES_026_037]
Careful! You almost have a man down!

[msg BTL_MES_026_038]
Hey, is that guy's health okay!?

[msg BTL_MES_026_039]
Hey, is Yosuke okay like that?

[msg BTL_MES_026_040]
Is Chie going to be fine!?

[msg BTL_MES_026_041]
H-Hey, we might lose Yukiko at this[n]rate!

[msg BTL_MES_026_042]
Dummy

[msg BTL_MES_026_043]
Are we going to leave Kanji like[n]that?

[msg BTL_MES_026_044]
Naoto's at her limit.

[msg BTL_MES_026_045]
Hey! Someone take care of Teddie!

[msg BTL_MES_026_046]
Whoa! Yukari's in danger!

[msg BTL_MES_026_047]
Hey! Junpei's not doing so well!

[msg BTL_MES_026_048]
Are we just leaving Akihiko like[n]that?

[msg BTL_MES_026_049]
Hey! Someone take care of Mitsuru[n]already!

[msg BTL_MES_026_050]
Dummy

[msg BTL_MES_026_051]
Watch Aigis' health!

[msg BTL_MES_026_052]
Ken looks like he's about finished.

[msg BTL_MES_026_053]
Hey! Someone keep an eye on Koromaru!

[msg BTL_MES_026_054]
Shinjiro's not going to make it!

[msg BTL_MES_026_055]
Someone's going to die at this rate!

[msg BTL_MES_026_056]
Hey! Are you gonna survive, Joker!?

[msg BTL_MES_026_057]
Skull's in danger!

[msg BTL_MES_026_058]
Hm? Is Panther going to be okay!?

[msg BTL_MES_026_059]
Hmm... Mona might drop soon.

[msg BTL_MES_026_060]
Hey! Someone, support Fox!

[msg BTL_MES_026_061]
Is Queen getting assistance anytime[n]soon?

[msg BTL_MES_026_062]
Dummy

[msg BTL_MES_026_063]
Noir's health has reached its[n]limit...

[msg BTL_MES_026_064]
Crow might not make it...

[msg BTL_MES_026_065]
Hurry up and get healed already!

[msg BTL_MES_026_066]
Tch―petrification!

[msg BTL_MES_026_067]
Hey―an ally's been hexed!

[msg BTL_MES_026_068]
Look out for the poison! Wait―you're[n]already poisoned!?

[msg BTL_MES_026_069]
Wake up that sleepyhead!

[msg BTL_MES_026_070]
Damn, they're confused...

[msg BTL_MES_026_071]
An ally's been paralyzed!

[msg BTL_MES_026_072]
Crap! They've been stunned...

[msg BTL_MES_026_073]
Their magic attacks are sealed.[n]That's a problem...

[msg BTL_MES_026_074]
Watch it―your strength is bound.

[msg BTL_MES_026_075]
Damn, their agility's been bound...

[msg BTL_MES_026_076]
Deal with it! Then, get even with[n]them!

[msg BTL_MES_026_077]
You can use physical attacks to hit[n]its weak points!

[msg BTL_MES_026_078]
That one's weak against Fire!

[msg BTL_MES_026_079]
Ice is a strong choice for handling[n]this one!

[msg BTL_MES_026_080]
That Shadow's weak to Wind...

[msg BTL_MES_026_081]
Electricity is its weakness!

[msg BTL_MES_026_082]
There's a Shadow that's weak against[n]the Nuclear affinity!

[msg BTL_MES_026_083]
Psychokinesis is what we need to use[n]against this one...

[msg BTL_MES_026_084]
The Bless affinity is the one you[n]want to use against this enemy!

[msg BTL_MES_026_085]
Use the Curse affinity to utilize its[n]weakness!

[msg BTL_MES_026_086]
Hey! Try hitting them with your[n]physical attack!

[msg BTL_MES_026_087]
There's a Shadow that's weak against[n]Fire... Time to watch it burn up!

[msg BTL_MES_026_088]
Freeze the Shadows and knock them[n]down!

[msg BTL_MES_026_089]
If you want to take advantage of its[n]weakness, use the Wind affinity!

[msg BTL_MES_026_090]
Weak against Electricity, huh... Time[n]to bring out the electric chair!

[msg BTL_MES_026_091]
With the Nuclear affinity, you'll be[n]able to abuse its weakness!

[msg BTL_MES_026_092]
There's a Shadow that's weak against[n]Psychokinesis.

[msg BTL_MES_026_093]
You can strike its weakness with the[n]Bless affinity! Bless it away!

[msg BTL_MES_026_094]
びめまを'るま ゐまぺや ぺむぺもょれろ ろめま ぢゎるれま ぺみみもょもろをテ[n]ぢゎるれま ろめまゆ ろよ ぺょ まろまるょぺゅ らゎょもれめゆまょろ!

[msg BTL_MES_026_095]
Know what you need to do?

[msg BTL_MES_026_096]
There's no reason NOT to use it! Do[n]you hear me?

[msg BTL_MES_026_097]
Yosuke, don't let us down!

[msg BTL_MES_026_098]
Do it, Chie!

[msg BTL_MES_026_099]
Yukiko's got this.

[msg BTL_MES_026_100]
Dummy

[msg BTL_MES_026_101]
Kanji! Try being useful for once!

[msg BTL_MES_026_102]
Naoto―now's your chance to shine!

[msg BTL_MES_026_103]
Teddie, show 'em that you're not just[n]a teddy bear!

[msg BTL_MES_026_104]
Yukari, you know what to do?

[msg BTL_MES_026_105]
Do it, Junpei!

[msg BTL_MES_026_106]
Akihiko, use every cell in your body!

[msg BTL_MES_026_107]
Mitsuru―you're up!

[msg BTL_MES_026_108]
Dummy

[msg BTL_MES_026_109]
Aigis, this is right down your alley,[n]isn't it?

[msg BTL_MES_026_110]
How about it, Ken? This is where you[n]can show off!

[msg BTL_MES_026_111]
Go, Koromaru!

[msg BTL_MES_026_112]
Finish it off, Shinjiro!

[msg BTL_MES_026_113]
Good! Go get 'em!

[msg BTL_MES_026_114]
Joker! It's up to you!

[msg BTL_MES_026_115]
Skull, you've got this!

[msg BTL_MES_026_116]
Panther, do some good for us!

[msg BTL_MES_026_117]
Go, Mona! Go finish them off!

[msg BTL_MES_026_118]
Hurry up and finish it, Fox!

[msg BTL_MES_026_119]
This should be easy for you, Queen!

[msg BTL_MES_026_120]
Dummy

[msg BTL_MES_026_121]
Now go, Noir!

[msg BTL_MES_026_122]
Crow, do you think you've got this?

[msg BTL_MES_026_123]
Good, keep going.

[msg BTL_MES_026_124]
Now... what's next?

[msg BTL_MES_026_125]
Take your time―but not too much.

[msg BTL_MES_026_126]
This is making me want to join the[n]fray.

[msg BTL_MES_026_127]
Hey, how about passing the baton?

[msg BTL_MES_026_128]
So, do a Baton Pass!

[msg BTL_MES_026_129]
Hm? There's someone who's boosted!

[msg BTL_MES_026_130]
Good, good―he's boosted!

[msg BTL_MES_026_131]
Take a look―Yosuke's boosted!

[msg BTL_MES_026_132]
Chie has been boosted!

[msg BTL_MES_026_133]
Hey, Yukiko is boosted!

[msg BTL_MES_026_134]
Dummy

[msg BTL_MES_026_135]
Oh! Kanji is boosted now!

[msg BTL_MES_026_136]
Naoto's boosted!

[msg BTL_MES_026_137]
Teddie has a nice boost going on!

[msg BTL_MES_026_138]
Nice boost, Yukari!

[msg BTL_MES_026_139]
Oh? Junpei's boosted!

[msg BTL_MES_026_140]
Looks like Akihiko has been boosted.

[msg BTL_MES_026_141]
Look at Mitsuru! She's boosted!

[msg BTL_MES_026_142]
Dummy

[msg BTL_MES_026_143]
Good, Aigis is in boost mode!

[msg BTL_MES_026_144]
Ken has a boost!

[msg BTL_MES_026_145]
Koromaru's boosted!

[msg BTL_MES_026_146]
Shinjiro is boosted now.

[msg BTL_MES_026_147]
Someone in the party has been[n]boosted.

[msg BTL_MES_026_148]
Whoa! Nice boost, Joker!

[msg BTL_MES_026_149]
Skull's been boosted.

[msg BTL_MES_026_150]
Good, Panther's been boosted!

[msg BTL_MES_026_151]
Check it out―Mona's boosted!

[msg BTL_MES_026_152]
Take a look at Fox! He's been[n]boosted!

[msg BTL_MES_026_153]
Queen, nice boost!

[msg BTL_MES_026_154]
Dummy

[msg BTL_MES_026_155]
Ah... Noir's boosted.

[msg BTL_MES_026_156]
Crow's been boosted!

[msg BTL_MES_026_157]
And you can strike its weakness![n]...Make sure you kill it!

[msg BTL_MES_026_158]
だょぽ をよゎ'わま むよろ ぺょ ぺみみもょもろを ろめぺろ ろめま[n]ひめぺぽよゐ'れ ゐまぺや ぺむぺもょれろ! とろ'れ よゎる ぼめぺょぼま!

[msg BTL_MES_026_159]
Support's ready anytime.

[msg BTL_MES_026_160]
Ready to support. Use it when you[n]can!

[msg BTL_MES_026_161]
It looks like we are up against a[n]strong enemy.

[msg BTL_MES_026_162]
Do be careful.

[msg BTL_MES_026_163]
This... is not good.

[msg BTL_MES_026_164]
I agree. I recommend escaping at[n]once.

[msg BTL_MES_026_165]
Perhaps with the ability you have[n]now, you'll be able to defeat it.

[msg BTL_MES_026_166]
ちゎろデ もろ れままゆれ ゅもやま もろ'ゅゅ ほま めぺるぽ ろよ ぼるぺぼや[n]もろれ ぽまみまょれまテ ぶま ゆゎれろ みもょぽ ぺ ゐぺをテ

[msg BTL_MES_026_167]
It is preparing for a massive attack.[n]Please use caution.

[msg BTL_MES_026_168]
Its physical attacks may cause you[n]problems... Do be careful.

[msg BTL_MES_026_169]
This enemy's strength is in its magic[n]attacks. Do not forget this.

[msg BTL_MES_026_170]
びめもれ まょまゆを むぺもょれ れろるまょむろめ ぺれ もろ むまろれ[n]もょゃゎるまぽテ とろ'ぽ ほま ほまれろ ろよ みもょもれめ もろ りゎもぼやゅをテ

[msg BTL_MES_026_171]
That must be... a rare Shadow.

[msg BTL_MES_026_172]
It seems to be a rare Shadow―do not[n]let it escape.

[msg BTL_MES_026_173]
Be aware of its attacks. It'll hit[n]every one of you.

[msg BTL_MES_026_174]
Please be aware of your health.

[msg BTL_MES_026_175]
This Shadow uses an attack that hits[n]multiple targets.

[msg BTL_MES_026_176]
Don't forget to defend.

[msg BTL_MES_026_177]
This one uses instant kill[n]abilities... Please be careful.

[msg BTL_MES_026_178]
Don't let your guard down.

[msg BTL_MES_026_179]
It's useless to attempt affinity[n]attacks right now.

[msg BTL_MES_026_180]
It's probably for the best to use[n]physical attacks here.

[msg BTL_MES_026_181]
An enormous attack is on its way...

[msg BTL_MES_026_182]
Do not forget to guard.

[msg BTL_MES_026_183]
This opponent is too strong for you.

[msg BTL_MES_026_184]
If you're in danger, I recommend that[n]you escape.

[msg BTL_MES_026_185]
There's an enemy that we don't have[n]any data on...

[msg BTL_MES_026_186]
We may want to figure out its nature[n]first.

[msg BTL_MES_026_187]
They're neither strong nor weak...

[msg BTL_MES_026_188]
Defeat it quickly and expertly.

[msg BTL_MES_026_189]
This enemy isn't even worth your[n]time.

[msg BTL_MES_026_190]
Now, hurry up and get rid of them.

[msg BTL_MES_026_191]
Hm, it looks like the enemy's[n]affinity has changed.

[msg BTL_MES_026_192]
Now's your chance to hit its[n]weakness.

[msg BTL_MES_026_193]
I could not find you an escape[n]route...

[msg BTL_MES_026_194]
I don't see a way out.

[msg BTL_MES_026_195]
It has caught up...

[msg BTL_MES_026_196]
It's an FOE―be careful.

[msg BTL_MES_026_197]
Be aware of your allies' state.

[msg BTL_MES_026_198]
It looks like they may need some[n]help.

[msg BTL_MES_026_199]
Are you just going to ignore Yosuke's[n]condition?

[msg BTL_MES_026_200]
Chie's not in a good situation.

[msg BTL_MES_026_201]
Yukiko might end up defeated.

[msg BTL_MES_026_202]
Dummy

[msg BTL_MES_026_203]
I wonder if Kanji is going to make it[n]to the end.

[msg BTL_MES_026_204]
Is Naoto doing all right?

[msg BTL_MES_026_205]
Teddie doesn't seem to be doing so[n]well.

[msg BTL_MES_026_206]
Keep an eye on Yukari's health.

[msg BTL_MES_026_207]
Is Junpei going to be left as is?

[msg BTL_MES_026_208]
It seems like Akihiko is in danger.

[msg BTL_MES_026_209]
You might want to keep an eye on[n]Mitsuru's health.

[msg BTL_MES_026_210]
Dummy

[msg BTL_MES_026_211]
Is Aigis going to be okay?

[msg BTL_MES_026_212]
Ken is at his limit.

[msg BTL_MES_026_213]
Be aware of Koromaru.

[msg BTL_MES_026_214]
Are we leaving Shinjiro behind?

[msg BTL_MES_026_215]
A party member might faint rather[n]soon...

[msg BTL_MES_026_216]
Joker, do you intend on dying here?

[msg BTL_MES_026_217]
Skull's health is getting a little[n]low.

[msg BTL_MES_026_218]
Are you going to let Panther die?

[msg BTL_MES_026_219]
Watch Mona's health.

[msg BTL_MES_026_220]
If no one does anything about Fox, he[n]might die.

[msg BTL_MES_026_221]
Are you just going to leave Queen[n]like that?

[msg BTL_MES_026_222]
Dummy

[msg BTL_MES_026_223]
Noir might faint pretty soon.

[msg BTL_MES_026_224]
Do you intend on leaving Crow in his[n]current condition?

[msg BTL_MES_026_225]
I recommend prioritizing healing up[n]first.

[msg BTL_MES_026_226]
Someone has become petrified.

[msg BTL_MES_026_227]
Someone appears to be cursed.

[msg BTL_MES_026_228]
Hm, someone is poisoned.

[msg BTL_MES_026_229]
There is someone currently snoozing.

[msg BTL_MES_026_230]
It seems like they've become[n]confused...

[msg BTL_MES_026_231]
It looks like someone has been[n]paralyzed.

[msg BTL_MES_026_232]
It looks like they're dizzy...

[msg BTL_MES_026_233]
Their magic is bound.

[msg BTL_MES_026_234]
It looks like their strength has been[n]bound.

[msg BTL_MES_026_235]
とろ れままゆれ をよゎる ぺむもゅもろを めぺれ ほままょ ほよゎょぽテテテ と'ゆ[n]むよもょむ ろよ よるぽまる をよゎ ぺるよゎょぽ ぺょをゐぺをれテ

[msg BTL_MES_026_236]
Shouldn't you take care of that at[n]once?

[msg BTL_MES_026_237]
A physical attack will do the trick.

[msg BTL_MES_026_238]
There's an enemy weak against Fire.[n]Burn them to a crisp.

[msg BTL_MES_026_239]
If you want to aim for its weakness,[n]use an Ice attack.

[msg BTL_MES_026_240]
There's a Shadow that's weak against[n]the Wind affinity.

[msg BTL_MES_026_241]
That one is weak against Electricity.

[msg BTL_MES_026_242]
The Nuclear affinity would be useful[n]here.

[msg BTL_MES_026_243]
These Shadows are weak against[n]Psychokinesis.

[msg BTL_MES_026_244]
That enemy must be the one that's[n]weak against the Bless affinity.

[msg BTL_MES_026_245]
If you want to hit its weakness, try[n]using the Curse affinity.

[msg BTL_MES_026_246]
Weak against physical attacks... What[n]a spineless Shadow.

[msg BTL_MES_026_247]
There's a Shadow that is weak to[n]Fire.

[msg BTL_MES_026_248]
That Shadow there is weak to Ice.

[msg BTL_MES_026_249]
You will be able to strike its[n]weakness with the Wind affinity.

[msg BTL_MES_026_250]
Electricity might be what you want to[n]use against this one.

[msg BTL_MES_026_251]
The Shadow there is weak against the[n]Nuclear affinity.

[msg BTL_MES_026_252]
ぶもろめ ろめま はれをぼめよやもょまれもれ ぺみみもょもろをデ をよゎ'ゅゅ ほま[n]ぺほゅま ろよ れろるもやま もろれ ゐまぺやょまれれテ

[msg BTL_MES_026_253]
Bless the Shadow and that'll be its[n]end.

[msg BTL_MES_026_254]
Use the Curse affinity to take[n]advantage of its weakness.

[msg BTL_MES_026_255]
There is no need to hold back.

[msg BTL_MES_026_256]
You do understand, don't you?

[msg BTL_MES_026_257]
Yosuke, you had better live up to our[n]expectations.

[msg BTL_MES_026_258]
Chie, you're up.

[msg BTL_MES_026_259]
I'm sure you'll do well, Yukiko.

[msg BTL_MES_026_260]
Dummy

[msg BTL_MES_026_261]
Kanji, show us how a man should be.

[msg BTL_MES_026_262]
Well, Naoto, it is up to you.

[msg BTL_MES_026_263]
You've got this, Teddie, yes?

[msg BTL_MES_026_264]
Yukari, I assume you've got this?

[msg BTL_MES_026_265]
Junpei, will you be more useful here?

[msg BTL_MES_026_266]
Hm... Akihiko, I hope you got this.

[msg BTL_MES_026_267]
Mitsuru, you should be able to land[n]an attack.

[msg BTL_MES_026_268]
Dummy

[msg BTL_MES_026_269]
Go, Aigis.

[msg BTL_MES_026_270]
Ken, perhaps now you should shine.

[msg BTL_MES_026_271]
Go get it, Koromaru.

[msg BTL_MES_026_272]
Perhaps this is where Shinjiro should[n]come in.

[msg BTL_MES_026_273]
Can't someone here handle this task?

[msg BTL_MES_026_274]
Joker, this looks like a job for you.

[msg BTL_MES_026_275]
Now, Skull―go make yourself useful.

[msg BTL_MES_026_276]
Perhaps this is up to you, Panther.

[msg BTL_MES_026_277]
Mona, isn't this your territory?

[msg BTL_MES_026_278]
Fox, would you handle this?

[msg BTL_MES_026_279]
Queen, this is where you can show[n]off.

[msg BTL_MES_026_280]
Dummy

[msg BTL_MES_026_281]
Go show them how to use an axe, Noir.

[msg BTL_MES_026_282]
Finish them off, Crow.

[msg BTL_MES_026_283]
What's our next move?

[msg BTL_MES_026_284]
Being able to battle like this is[n]rather refreshing.

[msg BTL_MES_026_285]
Be on your guard.

[msg BTL_MES_026_286]
Stay calm and choose your actions[n]wisely.

[msg BTL_MES_026_287]
You'd be able to strike a weakness if[n]you switch amongst yourselves.

[msg BTL_MES_026_288]
This may be the best solution if you[n]would like to strike a weakness.

[msg BTL_MES_026_289]
It looks like he's boosted.

[msg BTL_MES_026_290]
Someone in the party is boosted.

[msg BTL_MES_026_291]
Yosuke is boosted.

[msg BTL_MES_026_292]
Take a look―Chie is boosted.

[msg BTL_MES_026_293]
It looks like Yukiko just boosted.

[msg BTL_MES_026_294]
Dummy

[msg BTL_MES_026_295]
Kanji's currently boosted.

[msg BTL_MES_026_296]
Naoto has boosted.

[msg BTL_MES_026_297]
It looks like Teddie's now boosted.

[msg BTL_MES_026_298]
Yukari has just boosted.

[msg BTL_MES_026_299]
Junpei is currently boosted.

[msg BTL_MES_026_300]
Akihiko appears to be boosted.

[msg BTL_MES_026_301]
Mitsuru is currently boosted.

[msg BTL_MES_026_302]
Dummy

[msg BTL_MES_026_303]
Aigis has entered boost mode.

[msg BTL_MES_026_304]
Ken has been boosted.

[msg BTL_MES_026_305]
Koromaru is in boost mode.

[msg BTL_MES_026_306]
Shinjiro has been boosted.

[msg BTL_MES_026_307]
Someone in the party is now boosted.

[msg BTL_MES_026_308]
It looks like you're boosted, Joker.

[msg BTL_MES_026_309]
Skull is now boosted.

[msg BTL_MES_026_310]
Panther has boosted.

[msg BTL_MES_026_311]
It looks like Mona has been boosted.

[msg BTL_MES_026_312]
Fox is boosted.

[msg BTL_MES_026_313]
Queen has boosted.

[msg BTL_MES_026_314]
Dummy

[msg BTL_MES_026_315]
It appears Noir is boosted.

[msg BTL_MES_026_316]
Crow is boosted.

[msg BTL_MES_026_317]
You can aim for its weakness... This[n]is your chance.

[msg BTL_MES_026_318]
Abusing its weakness is your best[n]bet.

[msg BTL_MES_026_319]
It looks like you can now ask for our[n]support.

[msg BTL_MES_026_320]
Perhaps you can include our support[n]in your battle strategy.

