[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 1][f 3 1 1 0 0 1][f 6 1 2 0 0 2]夷Qu姻, "exposici吋n de castigo"? 夷Qu姻 demonios[n]hicimos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 2]Ahora estoy m茨s preocupado por Queen y[n]Noir...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Aunque su captura explica por qu姻 nunca[n]respondieron a las llamadas de Oracle.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 4][f 6 1 2 0 0 6]斡No tenemos idea de lo que va a pasar con[n]esas dos! 斡Tenemos que encontrarlas lo[n]antes posible![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5][f 6 1 3 0 0 3]Por lo que acabamos de escuchar, parecen[n]estar en alg雨n lugar llamado "Plaza[n]Kamoshida"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 12 0 1][f 3 1 1 0 0 6]Espera, puede ser una trampa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7][f 6 1 2 0 0 4]夷Qu姻 dices, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1]Vamos all茨 de todos modos.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Avancemos con precauci吋n.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 8]Creo que no ten胤a que preguntar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 12 0 1][f 3 1 1 0 0 9]Oracle, 夷puedes decirnos d吋nde est茨 esa[n]plaza?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 0][f 3 1 6 0 0 500][f 3 1 1 0 0 10][f 6 1 2 0 0 3]No creo que pueda... Parece que tendr茨n que[n]seguir avanzando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 11]Tambi姻n hay esos carteles que vimos... Eso[n]significa que ya estamos en el punto de[n]mira.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12]Tendremos que seguir con m茨s precauci吋n de[n]aqu胤 en adelante. 斡Vamos, Joker![n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1]Lo tengo.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]D姻jamelo a m胤.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]No me siento bien...[f 2 7 1 20 6 32][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 7]斡Excelente! Contamos contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 14][f 6 1 2 0 0 7]斡Con tanta confianza![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 15][f 6 1 2 0 0 6]夷Por qu姻 te pones los pies fr胤os ahora? 斡Queen[n]y Noir cuentan con nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 4][f 3 1 1 0 0 16]No te preocupes. Te cubriremos la espalda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 4][f 3 1 1 0 0 17]S胤, estoy seguro de que podemos hacer esto.[n]斡Vamos a salvar a esas dos![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 23 12 0 0][f 3 1 1 0 0 18]Muy bien. 斡Ladrones, mu姻vanse![n][f 1 3 65535][f 1 1][e]

