[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 1][f 3 1 1 0 0 1]斡Muy bien! 斡Apresur姻monos a salvar a[n]Makoto y Haru![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 2]El interior de esta pel胤cula parece[n]bastante grande. Espero que no nos[n]perdamos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Futaba, 夷puedes apoyarnos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 1][f 3 1 1 0 0 4][f 6 1 2 0 0 3]He estado haciendo algunas pruebas, y[n]parece que no puedo hacerlo como[n]siempre.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]Parece un poco inestable, o... como si[n]no pudiera entender claramente la[n]informaci吋n de su ubicaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷Quiz茨 est茨 sufriendo alg雨n tipo de[n]interferencia?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 7]Es posible que quien trajo esa anomal胤a[n]est姻 manipulando sus lecturas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 65 0 0 1][f 3 1 1 0 0 8]Aunque no podemos dejar a nuestras[n]amigas. Tenemos que irnos, con o sin[n]navegaci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 9]No te preocupes, estoy bastante ubicado[n]con mi sexto sentido. 斡Es la intuici吋n[n]de mi lado salvaje![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 10][f 6 1 2 0 0 6]斡No conf胤o en eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 4 1][f 3 1 1 0 0 11][f 6 1 2 0 0 4]Mm... 夷Te sirve esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 12]夷Mm? 夷Es... un cuaderno?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 13]Mmhm... 夷Te sirve?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 6][f 3 1 1 0 0 14][f 6 1 2 0 0 5]Ooh, 斡Fant茨stico! 斡Podemos hacerlo a la[n]antigua![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 15]Ya veo, no tendremos que preocuparnos[n]por perdernos si dibujamos nuestro[n]propio mapa en el cuaderno.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 1][f 4 6 70 12 0 0][f 3 1 1 0 0 16][f 6 1 30 0 0 0], al explorar la pel胤cula, dibuja el[n]camino y sus alrededores.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Mientras mantengas esa cosa actualizada,[n]definitivamente no te perder茨s...[n]斡Eso espero![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 23 12 0 3][f 3 1 1 0 0 18][f 6 1 2 0 0 4]夷Seguro que podemos usarla, Hikari? 夷No[n]la necesitas para algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 19]La ten胤a cuando me despert姻 aqu胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20]No s姻 lo que estaba haciendo con eso,[n]as胤 que supongo que puedes usarla...[n]Bueno... Me gustar胤a que lo uses.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 7][f 4 6 66 2 0 6][f 3 1 1 0 0 21]Entonces, 斡no importa! 斡Muchas gracias![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 7 2 0][f 3 1 1 0 0 22]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 68 12 0 1][f 3 1 1 0 0 23][f 6 1 30 0 0 0], creo que deber胤amos dejarte el mapa[n]a ti.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1]Bien, yo me encargar姻.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Pero t雨 est茨s m茨s calificado.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Lo har茨s bien, Ryuji.[f 2 7 1 64 0 32][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 24]S胤, tal tarea ser胤a mejor para nuestro[n]l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 25]Es verdad, estoy seguro de que har胤a un[n]mejor mapa, pero si me lo das...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26][f 6 1 2 0 0 4]Creo que usar胤a todo el cuaderno en[n]cuesti吋n de minutos... 夷Est茨n bien con[n]eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 8 1 6][f 3 1 1 0 0 27][f 6 1 2 0 0 6]斡Por supuesto que no! 夷Pensabas ponerte[n]a dibujar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 3 6][f 3 1 1 0 0 28]Sabes qu姻, es mejor dejarte esto, ya[n]que eres nuestro l胤der y todo eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 1][f 3 1 1 0 0 29][f 6 1 2 0 0 6]斡No puedo hacer esa clase de cosas! 斡Lo[n]juro, tengo cosas como el este y[n]oeste mezclados todo el tiempo![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 30][f 6 1 2 0 0 9]No podemos perdernos en esta pel胤cula...[n]Este trabajo es mejor para nuestro[n]l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 12 0 1][f 3 1 1 0 0 31]A雨n tienen la intenci吋n de entrar ah胤...[n]Por favor, aseg雨rense de que no[n]presionarse demasiado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 7]斡No nos malinterpretes! Esto ser茨 pan[n]comido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 1 1][f 3 1 1 0 0 33][f 6 1 2 0 0 10]Si saltamos a esa pantalla, entraremos[n]en la pel胤cula... 夷Verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 4][f 3 1 1 0 0 34]Este es un proceso muy diferente de c吋mo[n]entramos en Palacios.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 16 1 0][f 3 1 1 0 0 35][f 6 1 2 0 0 1]斡Muy bien! 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_028_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 3][f 4 6 65 17 1 0][f 3 1 1 0 0 36][f 6 1 3 0 0 3]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 0][f 3 1 1 0 0 37][f 6 1 2 0 0 4]...夷No vas a entrar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 38][f 6 1 2 0 0 10]夷Por qu姻 tengo que ir primero? 斡Yusuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 39][f 6 1 2 0 0 9]Nosotros, los humanos, parecemos tener[n]dificultades para acercarnos a lo[n]desconocido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 40]Vamos... 夷En serio, chicos? [f 6 1 30 0 0 0], t雨[n]deber胤as saltar primero. 斡Haznos[n]sentir orgullosos![n][f 1 3 65535][f 1 1][e]

[sel SEL_033 top]
[f 0 5 65278][f 2 1]D姻jamelo a m胤.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Despu姻s de ti, Morgana.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Saltemos juntos.[f 2 7 1 64 0 32][e]

[msg MSG_034 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 4][f 3 1 1 0 0 41][f 6 1 2 0 0 7]斡Ese es nuestro l胤der! 斡Realmente eres[n]genial en esto![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 42]Oh, bien, solo salto y…[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 43][f 6 1 1 0 0 1][f 6 1 2 0 0 1]斡M茨s bien, demonios no![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 44]Tienes que dar el salto de la fe como[n]l胤der de los Ladrones Fantasma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 4][f 3 1 1 0 0 45][f 6 1 2 0 0 4]Entonces, 夷debemos tomarnos las manos[n]y dar un paso a la vez?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 8 1 1][f 3 1 1 0 0 46][f 6 1 2 0 0 6]夷Por qu姻 darle tanto suspenso? 斡Esto no[n]es el fin de una pel胤cula infantil![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 47]Lo siento, [f 6 1 30 0 0 0], tienes que tomar el[n]salto de fe como nuestro l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 70 2 0 1][f 3 1 1 0 0 48]Est茨 decidido. 斡Vamos [f 6 1 30 0 0 0]![n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 0 1][f 3 1 1 0 0 49]Tengan cuidado...[n][f 1 3 65535][f 1 1][e]

