[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23072]Vayamos a nuestra reuni吋n de estrategia[n]sobre c吋mo robaremos la estatua de Kamoshidaman.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0][f 6 1 2 0 6]La frase[n]"reuni吋n estrat姻gica" suena tan genial...[n]斡S吋lo grita "a ladrones fantasmas"![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 4][f 3 1 1 0 0 22032]Haha, parece que est茨 en la misma[n]longitud de onda que nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0]Gracias a [f 6 1 27 0 0 0], hemos[n]asegurado nuestra ruta a la centralita.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 0]Ahora podemos apagar las luces de la[n]estatua cuando queramos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 0][f 3 1 1 0 0 0]Robando una estatua bajo la cubierta de[n]la oscuridad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hemos sacado un atraco similar en el[n]pasado... Creo que podemos manejar esta vez tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 0][f 3 1 1 0 0 23016]La pregunta es, 夷c吋mo tomamos[n]f胤sicamente la estatua?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 66 1 0 0][f 4 6 72 0 0 0][f 3 1 1 0 0 0]Aunque parece ser m茨s ligero de lo que[n]parece, escapar con 姻l a mano puede ser[n]demasiado dif胤cil...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]C吋mo cambiar la estatua... Oye, 夷tienes[n]alguna idea?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Podr胤amos meterlo con una gr雨a.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Alguien actuar茨 como una distracci吋n.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Nada viene a la mente.[f 2 7 1 64 6 32][e]

[msg MSG_010 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19029][f 6 1 2 0 6]Eso me[n]hace pensar en el juego de la gr雨a![n]Suena divertido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 4][f 3 1 1 0 0 0]Pero no hab胤a suficiente espacio para[n]un esquema tan grande.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]Me sonaba bien. Acabamos de bajar de[n]arriba y sacarlo de la plaza...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 0][f 3 1 1 0 0 23017]Una t茨ctica de distracci吋n, eh... No[n]est茨 mal, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 65 2 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Deber胤amos meter a Morgana desde el[n]final de un poste de pesca?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23035][f 6 1 2 0 0 6]斡No soy una especie de cebo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quiero decir, hay una posibilidad de[n]que el cebo pueda ser capturado y terminar[n]con Makoto y Haru![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 6 0 0][f 1 5][f 6 1 28 0 0 0]Es un buen punto. Ojal茨 pudi姻semos[n]arrancarlo antes de ser atrapados...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 0 2 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 19008]*sigh* Si tan s吋lo[n]tuvi姻ramos superpotencias como Kamoshidaman...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 4][f 3 1 1 0 0 0]Podr胤amos simplemente bajar del cielo[n]con una "HAHAHAHA!" y hacer como un 茨rbol[n]con la estatua...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Esta operaci吋n ser胤a muy f茨cil si eso[n]fuera posible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 66 0 1 1][f 3 1 1 0 0 22116][f 6 1 2 0 0 6]斡Espera, creo que eso funcionar胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 funcionar胤a?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Robando desde el cielo![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 6][f 3 1 1 0 0 24022][f 6 1 2 0 0 4]Parece que te han impresionado con la[n]inspiraci吋n. 夷Nos dir胤as m茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 0]Claro, as胤 que esto tomar茨 ayuda de[n]todos, empezando por Yusuke...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]Ya veo. As胤 que vamos a cogerlos y[n]ponerlos aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 2 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19048][f 6 1 2 0 6]斡Eso[n]suena como un gran plan![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]夷Verdad? 夷Verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 68 1 0 3][f 4 6 23 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Es nuestra Se隠ora Ann! Pero todo se[n]reduce a esta pregunta: Yusuke, 夷puedes sacarlo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]Sin duda. Har姻 el apoyo impresionante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 65 2 0 0][f 3 1 1 0 0 21043][f 6 1 2 0 0 6]Kickass! 斡Vamos por las cosas que necesitamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 0]Ryuji y yo iremos al lugar de Theodore.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Necesitaremos toneladas de cosas, as胤[n]que 姻l tiene que ser el que haga esto por nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 0]S胤. Nos aseguraremos de que nos ponga bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 68 1 0 3][f 4 6 19 0 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0]Yusuke-kun y me encargar姻[n]de los suministros que necesitamos de[n]Nagi-san y llegar a trabajar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]La mayor parte ser茨 en Yusuke-kun, pero[n]har姻 lo que necesite para hacerlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24029]Y juro hacer el art胤culo perfecto.[n]Usando mis habilidades para tal tarea...[n]Estoy deseando hacer esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oye... 夷Puedo hablar con Hikari un poco?[n][f 1 3 65535][f 1 1][e]

[sel SEL_036 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷Pas吋 algo?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Est茨s preocupado?[f 2 7 1 64 0 32][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 26011]Nada como eso... S吋lo quiero hablar con[n]ella un poco m茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 0][f 3 1 1 0 0 26074]S胤... Quiero hablar con ella un poco m茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 0]Entonces ir姻 contigo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si Futaba va sola, puede que ni[n]siquiera termine diciendo lo que est茨 en su mente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26026][f 6 1 2 0 0 6]Mona... 斡Eso ayudar胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 72 12 0 1][f 3 1 1 0 0 0]... 夷Ser胤a aceptable que vaya donde[n]est茨 Elizabeth tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Elizabeth?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 0][f 3 1 1 0 0 28033]Lo siento, hay algo que deseo[n]preguntarle... Me disculpo por la raz吋n personal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 1][f 3 1 1 0 0 0]Bueno, estoy seguro de que estar茨 bien[n]ya que tenemos todo lo dem茨s cubierto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0][f 6 1 30 0 0 0], mant姻n la vista sobre el progreso de[n]todos hasta que se hagan todos los preparativos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Es lo mejor para no dejar a todos a sus[n]propios dispositivos. 斡Aseg雨rate de que[n]todo se cuide![n][f 1 3 65535][f 1 1][e]

[msg MSG_045]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 7 6 0 0][f 4 6 64 1 0 0][f 3 1 1 0 0 0]Todos se fueron a sus misiones...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 64 8 32 0][f 3 1 1 0 0 0]夷Qui姻n deber胤a comprobarlo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_046 top]
[f 0 5 65278][f 2 1][f 6 1 27 0 0 0]and Yusuke[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ann and Ryuji[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana y Futaba[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Akechi y Elizabeth[f 2 7 1 64 2 32][e]

