[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 4]Oye, 夷esa estatua se acaba de mover?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 2]S胤, tambi姻n lo vi. Eso es extra隠o, pero... 夷C吋mo podr胤a una brisa tan suave[n]mover una estatua de ese tama隠o?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 32 4 1 1][f 3 1 1 0 0 3][f 6 1 2 0 0 6]夷Qu姻 est茨n murmurando? 斡Espero que est姻n preparados para tu penitencia, criminales![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 0 1 3][f 4 6 23 12 1 6][f 3 1 1 0 0 4][f 6 1 2 0 0 6]斡Aqu胤 viene, Joker![n][f 1 3 65535][f 1 1][e]

