[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 1][f 3 1 1 0 0 1][f 6 1 2 0 0 10]No sirve de nada. No est茨n aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 3]Incluso encontramos todas esas puertas[n]cerradas. 夷Qu姻 est茨 pasando aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 6][f 3 1 1 0 0 3]Es como si fu姻ramos esp胤ritus... Todo[n]este lugar es un verdadero misterio.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 4]Todas las se隠ales apuntan a que esto es[n]un cine, pero hay algo extra隠o...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]No hemos encontrado ning雨n rastro de[n]ellas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 65 4 1 1][f 3 1 1 0 0 6][f 6 1 2 0 0 4]En serio, 夷c吋mo diablos terminamos aqu胤?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1]Apuesto a que ca胤mos de arriba.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Quiz茨s por ese lado?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Creo que nos levantamos hacia arriba.[f 2 7 1 64 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 4][f 3 1 1 0 0 7]No recuerdo ninguna sensaci吋n de caer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 65 10 1 0][f 3 1 1 0 0 8]Espera, 夷qu姻 importa, hacia arriba o[n]hacia abajo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 4][f 3 1 1 0 0 9]Cierto... Se sent胤a m茨s como un[n]desplazamiento horizontal que uno vertical.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 65 10 1 0][f 3 1 1 0 0 10]夷Pero de d吋nde?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 7][f 4 6 72 2 0 4][f 3 1 1 0 0 11]Oh, 夷como si nos fuera bien aqu胤? Ja,[n]ja, es una manera divertida de decirlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 65 10 1 0][f 3 1 1 0 0 12]Espera, 夷de qu姻 est茨s hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [La Voz De Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 1]斡Chicos! 斡Vengan aqu胤 un segundo![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 68 1 0 4][f 4 6 66 0 1 1][f 3 1 1 0 0 14][f 6 1 2 0 0 6]斡Quiz茨 Morgana encontr吋 algo![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 15]Vamos, [f 6 1 30 0 0 0].[n][f 1 3 65535][f 1 1][e]

