[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0]Es un placer conocerlos a todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 2]Algún tipo de destino debe haber hecho que nuestros caminos se cruzaran - es un placer conocerte también.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 3]As胤 que, um, hay algo[n]que he tenido curiosidad desde que te vi[n]por primera vez a todos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4][f 6 1 2 0 0 4]No son s吋lo tus m茨scaras, pero todos[n]tus trajes... me hacen pensar en ladrones fantasma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 5][f 6 1 2 0 0 10]斡Mierda, esto es malo! 夷Ella descubri吋[n]qui姻nes somos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 6][f 6 1 2 0 4]夷Qui姻n eres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 14 1 6][f 3 1 1 0 0 7][f 6 1 2 0 0 6]¡Skull, idiota! ¡Deja de delatarnos![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 24 0 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]Esto no es bueno... 夷C吋mo explicar[n]nuestro atuendo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Sólo vamos a hacer cosplay.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Estos son nuestros uniformes para el trabajo.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Somos los ladrones Fantasma..[e]

[msg MSG_008 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 9][f 6 1 2 0 4]夷Es eso lo[n]que es popular ahora? O, 夷son para alguna[n]clase de fiesta de disfraces?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 6][f 3 1 1 0 0 10][f 6 1 2 0 0 10]S-Sí... algo así! Todos estamos como, '¡Fiesta, woohoo, wooo!'[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 11]Woohoo...? No entiendo lo[n]que quieres decir, pero suena divertido![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 12][f 6 1 2 0 4]¿Entonces su trabajo es hacer cosplay de ladrones fantasma, o son todos ladrones que fueron contratados para hacer cosplay...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 6][f 3 1 1 0 0 13]S胤... No pienses demasiado en ello.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012_5 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 1 0][f 3 1 1 0 0 14]Los ladrones fantasma están muy de moda en este momento, así que más o menos simplemente... ¿seguimos la corriente? ¿O algo así?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 1 0][f 3 1 1 0 0 15][f 6 1 2 0 0 6]¡No llames 'algo así' a nuestra tapadera![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0]夷En serio? No lo entiendo,[n]斡pero suena divertido![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 17][f 6 1 2 0 4]"Los" Ladrones Fantasma?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 1 6][f 3 1 1 0 0 18][f 6 1 2 0 0 6]¿¡La corregiste!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 24 4 1 0][f 3 1 1 0 0 19]Pero... no parece comprender completamente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 28 12 0 0][f 3 1 1 0 0 20]¿Es posible que no estés al tanto de los Ladrones Fantasma?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 21][f 6 1 2 0 4]¿Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 6][f 3 1 1 0 0 22][f 6 1 2 0 0 0]¡De ninguna manera! Ha estado en todas partes, en las noticias y en internet todos los días últimamente...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23]¿De verdad no has oído hablar de los 'Ladrones Fantasma de Corazones'?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 0 0][f 1 5][f 6 1 28 0 0 0]Lo siento, no tengo idea... y veo[n]las noticias muy regularmente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 21 12 0 1][f 3 1 1 0 0 25]¡Vaya, realmente no lo sabe! ¿Tal vez los Ladrones Fantasma no son famosos a nivel nacional todavía?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 26][f 6 1 2 0 0 3]Las noticias pueden variar según la prefectura. Pero, aún así...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 4][f 3 1 1 0 0 27]Bueno, ¿esto no funciona para nuestra conveniencia?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28]Creo que deber胤amos priorizar escapar[n]de aqu胤 en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 29]Oh, cierto... Los ciudadanos de los que[n]nos escondimos probablemente se[n]refer胤an a ella cuando hablaban de "otro criminal"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30]Si ese es el caso, no deber胤amos[n]charlar aqu胤 m茨s tiempo, deber胤amos volver al[n]Cine donde es m茨s seguro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 0 0 1][f 1 5][f 6 1 28 0 0 0]夷Cine? Lo siento, pero no tengo idea[n]de d吋nde est茨 uno por aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 32]Parece que sabemos m茨s de lo que est茨[n]pasando ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 0 0 33][f 6 1 2 0 0 0]¡Vaya! ¿El gato habló?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 34][f 6 1 1 0 0 1][f 6 1 2 0 0 6]斡No soy un gato![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35][f 6 1 2 0 0 6]¿¡Y AHORA te estás sorprendiendo por esto!? ¡Hace apenas un segundo estábamos luchando juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 36][f 6 1 2 0 4]Oh s胤,[n]tienes raz吋n... Entonces, 姻l es un[n]usuario de Persona tambi姻n, supongo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_031 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]As胤 es.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Es solo un pequeño miau-miau.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Es una larga historia...[f 2 7 1 20 0 32][e]

[msg MSG_032 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 14 1 6][f 3 1 1 0 0 37][f 6 1 1 0 0 1][f 6 1 2 0 0 6]¡Ni hablar! No importa lo adorable que lo hagas sonar, simplemente, ¡NI HABLAR![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 38]...Ahora estoy agotado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 18 1 6][f 3 1 1 0 0 39]Eso es correcto. Tomo esta forma debido a la distorsión de Mementos, donde se entrelazan los deseos colectivos y los pensamientos inconscientes de la humanidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 40][f 6 1 2 0 4]¿Mementos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 41]S胤, s胤, hablaremos de todo eso m茨s tarde.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 20 1 0 3][f 4 6 24 0 0 1][f 3 1 1 0 0 42]Eso puede ser cierto para Morgana, pero ¿no deberíamos explicarnos también?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 43]Todos somos usuarios de Persona... Estoy seguro de que ella comprendería nuestras circunstancias.[n][f 1 3 65535][f 1 1][e]

[sel SEL_037 top]
[f 0 5 65278][f 2 1]Es verdad.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Salgamos de esta pel胤cula primero.[f 2 7 1 20 0 32][e]

[msg MSG_038 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 44]Podemos hablar de ello mientras[n]volvemos al Cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 45]Estoy de acuerdo. Deber胤amos reunirla[n]con Theodore lo antes posible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 2 1][f 1 5][f 6 1 28 0 0 0][f 3 1 0 0 46]Si me puedes llevar con Theo, ¡entonces por favor, déjame unirme a ustedes![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 6][f 3 1 1 0 0 47]Entonces est茨 decidido, regresemos al Cine.[n][f 1 3 65535][f 1 1][e]

