[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]Cine, taquilla...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Akechi est茨 hablando con Elizabeth...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 74 1 0 4][f 4 6 72 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ah, has venido.[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Espero no interrumpir.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Hay algo raro en el ambiente.[f 2 7 1 64 0 32][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 28033]No es nada serio.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Algo me dio curiosidad antes, as胤 que quería preguntar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 0 0][f 3 1 1 0 0 0]Aja, as胤 que esto debe ser lo que llaman "interrogaci吋n"... Estoy bastante emocionada de experimentarlo en persona.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷La est茨s interrogando?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Eso te emociona?[f 2 7 1 64 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 0][f 3 1 1 0 0 28078]Como dije, no es nada serio, una simple pregunta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 0]Bueno, eso es lamentable. Estaba esperando experimentarlo con una porci吋n de "Katsu Dune".[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 10 1 0][f 3 1 1 0 0 0]Ja, ja, ja, 夷te refieres a las series polic胤acas donde ofrecen comida a los sospechosos cuando los interrogan? Eso es puramente ficticio.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Esto es simplemente para satisfacer mi curiosidad personal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28010][f 6 1 3 0 0 1]Mencionaste anteriormente que nada sin sentido ocurre en la Habitaci吋n Terciopelo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 3 0 0 1]Entonces, 夷c吋mo explicar胤as la presencia de [f 6 1 26 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷Qu姻 quieres decir?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷斡Ella... es la responsable de todo esto!?[f 2 7 1 64 8 32][e]

[msg MSG_011 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 0 0][f 3 1 1 0 0 54031]*risa* Pensar que llegar胤as a esa conclusi吋n... Est茨s bien adaptado a las tareas de detective.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 72 12 0 0][f 3 1 1 0 0 0]Si la memoria no me falla, [f 6 1 26 0 0 0] vino aqu胤 a trav姻s de la Habitaci吋n Terciopelo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Lo que quiero preguntar es si eso tiene alg雨n significado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 0 0][f 3 1 1 0 0 54056]S胤, creo que su llegada no es una simple coincidencia...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin embargo, eso no solo aplica en ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 10 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 quieres decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 1 0][f 3 1 1 0 0 0]Dado que tambi姻n te has encontrado con asistentes de la Habitaci吋n Terciopelo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Su presencia aqu胤 tambi姻n era inevitable y tiene alg雨n significado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Un significado, 夷eh...? Pero ese significado no te involucra directamente, ¿verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que todas nuestras respuestas est茨n más allá del final de la película...[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Tengo curiosidad por ver c吋mo terminar茨.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Vamos a trabajar en el plan.[f 2 7 1 64 0 32][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 54031]Si alcanzan o no ese final depende de ustedes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todos parecen estar tramando algo... Solo con presenciarlos, mi coraz吋n se acelera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 0]Nuestro plan debe tener 姻xito si queremos descubrirlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 54056]S胤, creo que esa sería una sabia decisi吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si alcanzan o no el final de la pel胤cula depende completamente de todos ustedes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 0]S胤, y para lograrlo, necesitamos asegurarnos de que este plan tenga 姻xito.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022]
[f 0 5 65278][f 2 1][f 4 6 64 2 32 0][f 3 1 1 0 0 0]Parece que las cosas van bien por aqu胤. Debería volver por ahora...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023]
[f 0 5 65278][f 2 1][f 4 6 64 8 32 0][f 3 1 1 0 0 0]Parece que las cosas van bien por aqu胤. Tal vez debería ver a los dem茨s...[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 6 1 27 0 0 0]y Yusuke[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ann y Ryuji[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana y Futaba[f 2 7 1 64 2 32][e]

