[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 1]As胤 que entramos por la pantalla, 夷verdad?[n]Me estoy poniendo nervioso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 2]... 夷T雨 tambi姻n vas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0]　　[n][f 3 1 1 0 0 3]Hikari-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 4]Pero, 夷por qu姻? Ni siquiera est茨s buscando[n]a la misma gente...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]Si vas con ellos, quiz茨 ni siquiera encuentres[n]a quien est茨s buscando...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 2 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 6]Tienes raz吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7]Pero nada es seguro en este mundo, y este[n]problema no va a resolverse.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Cuando pens姻 en lo que quer胤a hacer, me di[n]cuenta de que quer胤a ir con ellos. Eso es[n]todo lo que hab胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 9][f 6 1 2 0 0 4]夷Porque... te rescataron? 夷Para recompensarlos[n]por lo que hicieron?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 10]Bueno, por supuesto que hay eso! Pero lo m茨s[n]importante es que entiendo muy bien su[n]situaci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]... Tambi姻n me faltan compa隠eros que son[n]importantes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 12]Compa隠eros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 4]夷Suceder胤a que tus amigos desaparecidos[n]tambi姻n fueran usuarios de Persona?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 14 2 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 14]S胤, todo el mundo en SEES es! 夷Ves este[n]brazalete? Eso significa Escuadr吋n de[n]Ejecuci吋n Extracurricular Especializado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 15]Oh, eso es genial, es como prueba de que eres[n]parte de un equipo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 16]Heheh, 夷verdad? Aunque soy el 雨nico miembro[n]aqu胤 ahora...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 17]斡No te preocupes, tenemos la espalda! 斡Hagamos[n]lo mejor de nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 18]Ooh, 斡tengo que ser parte de los Fen吋menos[n]hasta que encuentre a todos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]O... 夷te parece bien?[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Esa fue nuestra intenci吋n.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]No creo que debas.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Pero, tu traje...[f 2 7 1 64 8 32][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 20][f 6 1 2 0 0 7]斡S胤! No s姻 por qu姻, pero parece que ya encajas[n]perfectamente con nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 6][f 3 1 1 0 0 21]Vaya, daaaamn... Sus habilidades sociales[n]son realmente m茨s de dios...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 0][f 4 6 23 12 0 6][f 3 1 1 0 0 22]S胤, terminar茨s haciendo da隠o o peor si saltas[n]a esta l胤nea de trabajo sin pensar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 4 0 1][f 3 1 1 0 0 23][f 6 1 2 0 0 2]斡Detengan eso, ustedes dos! 斡Sin asustar a[n]nuestro nuevo miembro![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 0 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 24]Hmm... 夷As胤 que esta ropa no funcionar茨?[n]夷Tiene una m茨scara un deber absoluto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 25]La pintura corporal siempre es una opci吋n.[n]Tengo mucha curiosidad sobre c吋mo se siente[n]cepillarse directamente sobre la piel[n]de una persona.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 1][f 3 1 1 0 0 26]Mejor para ah胤, Inari... Siento que te van[n]a arrestar a este ritmo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 0 3][f 3 1 1 0 0 27]夷Pero, compa隠eros? No entiendo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 1][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 28]Hikari-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 29]No es nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 1][f 3 1 1 0 0 30]Hikari-san...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 1][f 3 1 1 0 0 31][f 6 1 2 0 0 10]斡Hikari![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 1 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 4]夷Hm?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 33][f 6 1 3 0 0 1]Sol胤a pensar que es m茨s f茨cil estar solo[n]tambi姻n, pero... Conoc胤 a todos, y...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028_5 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 34][f 6 1 2 0 0 0]Hoy en d胤a, s姻 que no es malo tener amigos.[n]R-Right, [f 6 1 30 0 0]!?[n][f 1 3 65535][f 1 1][e]

[sel SEL_029 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]No est茨 nada mal.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Soy m茨s fuerte con mis amigos.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Por qu姻 me preguntas?[f 2 7 1 64 0 32][e]

[msg MSG_030 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 35]Ya veo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 36]Pero... Todav胤a no lo entiendo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 37][f 6 1 2 0 0 6]Oh, vamos, esta cosa se supone que es tu[n]trabajo, [f 6 1 30 0 0]![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 38][f 6 1 2 0 0 10]A-A-A-Anyway! 斡Los compa隠eros son geniales![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 39]No lo entiendo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 6][f 3 1 1 0 0 40][f 6 1 2 0 0 4]Ven ahora, 夷no hay algo m茨s importante en[n]este momento?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 41]Parece que la pel胤cula no cambiar茨 hasta que[n]progresas m茨s dentro de ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 42]Mmhm... No pas吋 nada hasta ahora... No hab胤a[n]habido ning雨n cambio en absoluto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 43]Pero, cuando todos vinieron aqu胤... la trama[n]empez吋 a progresar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 44]Hmm... Eso significa que tenemos que volver[n]all胤... Estoy preocupada por las damas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 72 0 0 3][f 3 1 1 0 0 45]Cierto. Si vamos a aprender algo sobre este[n]lugar, tenemos que volver a la pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 46][f 6 1 2 0 0 6]Muy bien, Joker, danos la se隠al de infiltraci吋n[n]cuando est姻s listo![n][f 1 3 65535][f 1 1][e]

