[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 1][f 3 1 6 0 0 500][f 3 1 1 0 0 26633]Espera, no de esa manera. Es al rev姻s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 0]Cierto. Necesitamos encontrar al dinosaurio[n]herido. Estar胤a al este de aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 5 1 0 3][f 4 6 27 12 0 1][f 3 1 1 0 0 27014]As胤 que por aqu胤. Estoy empezando a preocuparme...[n]斡R茨pido![n][f 1 3 65535][f 1 1][e]

