[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19009]Uhm, as胤 que s吋lo tenemos que derrotar los[n]objetivos en los lugares que Elizabeth[n]especific吋, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 0]夷Eso es todo lo que necesitamos hacer? Ser茨[n]f茨cil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 13004]Recuerda que estas sombras no son d姻biles.[n]No dudes en correr si las cosas salen de[n]la mano.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0]Especialmente t雨, Akihiko. Te calientas[n]demasiado f茨cilmente. Establece un buen[n]ejemplo para los hombres de clase inferior.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12093]Lo s姻. Dame cr姻dito.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 1][f 3 1 1 0 0 18129]夷Ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻, no me crees, Shinji?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]Trate de ser el que tiene que riendarte cada[n]vez que te escapas por tu cuenta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 0][f 3 1 1 0 0 12062][f 6 1 2 0 0 6]夷Y t雨, Shinji? Has estado hablando con nosotros[n]por qui姻n sabe cu茨nto tiempo...![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 6 0 1][f 3 1 1 0 0 13040]Esto de nuevo... Ser茨n un momento.[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Por favor di algo, Mitsuru.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Ayuda, [f 6 1 27 0 0 0].[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Vamos a dejarlos estar.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 13078]Aunque yo interviniera, solo seguir胤an.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Quiz茨s sea porque se conocen desde que eran[n]ni隠os. Lo juro, son tan inmaduros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13078]No creo que pueda ayudar si lo intent吋.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Son estos dos de los que estamos hablando.[n]Empezar茨 de nuevo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 13078][f 6 1 2 0 0 4]Nunca terminar茨. No tienes la intenci吋n de[n]esperarlo, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19030]斡Est茨 bien, tengo una idea! 斡D姻melo![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What do you plan to do,[n][f 6 1 26 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 12 1 0 1][f 4 6 18 1 0 4][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19071]Shinjiro-senpai! 斡Akihiko-senpai! 斡Escucha![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Esta es una misi吋n de caza, 夷por qu姻 no[n]tenemos una competencia para ver cu茨l de[n]ustedes es el mejor luchador?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12018][f 6 1 2 0 0 4]Una competencia, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]As胤 es. Pero no puedes derrotar a los[n]enemigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Estamos juntos en esto, as胤 que volar solo[n]est茨 fuera de los l胤mites.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esto ser茨 sobre observar a tus compa隠eros de[n]equipo y hacer todo lo posible para[n]apoyarlos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 3 1 1 0 0 19031][f 6 1 2 0 0 4]Decidiremos al ganador bas茨ndose en su[n]rendimiento general. 夷Trato?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031]Interesante. Acepto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si gano, entonces tienes que entrenar conmigo,[n]Shinji.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 0][f 3 1 1 0 0 18050]夷Qu姻? 夷Por qu姻 demonios tendr胤a que hacerlo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻, no tienes miedo de perder, verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 9 1 0][f 3 1 1 0 0 18093][f 6 1 2 0 0 2]Peque隠o... No hay forma de perderte, Aki.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 9 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Muy bien, es un duelo, Shinji![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 9 1 0][f 3 1 1 0 0 18129]No vengas a llorarme m茨s tarde.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]夷D吋nde est茨n estos enemigos? Estoy listo para[n]ellos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 9 1 0][f 3 1 1 0 0 12002]夷Intentas ir solo? Eso es contra las reglas.[n]斡Ni un punto![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 0][f 3 1 1 0 0 18058]夷Qu姻? Eso no cuenta. A雨n no hemos empezado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Trabajar juntos es clave, 夷de acuerdo? 斡Buena[n]suerte, chicos![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 13 2 0 1][f 3 1 1 0 0 13031]Para pensar que podr胤as domar a esos dos...[n]No est茨 mal, [f 6 1 26 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19130]Ahaha, estoy acostumbrado. 斡Los que conozco[n]son as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 13109][f 6 1 2 0 0 9]夷Son as胤 tambi姻n? Ya me est茨 dando dolor de[n]cabeza...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 0]De cualquier manera, gracias a [f 6 1 26 0 0 0][n]finalmente podemos avanzar. Vamos.[n][f 1 3 65535][f 1 1][e]

