[msg MSG_000 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 3][f 3 1 1 0 0 4118][f 6 1 2 0 0 6]斡Muy bien! 斡Hay m茨s lugares de tesoros por[n]aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 0]Nyeheheh... No importa cu茨ntas veces encuentre[n]tesoro, todav胤a tengo esa prisa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 4][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Eso se encarga de la primera. 斡Dos lugares[n]a la izquierda, chicos![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 27 1 0 4][f 4 6 13 0 0 1][f 3 1 1 0 0 13006]Bien. Al siguiente punto warp. Deber胤amos[n]encontrar m茨s tesoros all胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 0]Es una zona bastante grande, as胤 que tal vez[n]deber胤amos marcar d吋nde hemos estado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Est茨 bien! 斡Entonces vamos! 斡El tesoro me[n]espera![n][f 1 3 65535][f 1 1][e]

