[msg MSG_000 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Ohhh... Las gloriosas ruedas de sol a trav姻s[n]del cielo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Mientras los p茨jaros un-twitter lo dan la[n]bienvenida cerca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 0]Y lo veo con mi ojo adorado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21054][f 6 1 2 0 0 6]夷Qu姻? 夷Las voces vienen de estas cosas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Deben ser las flores que est茨bamos buscando.[n]Podr胤an saber algo, dijo Elizabeth.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 1 1][f 3 1 1 0 0 0]夷Pero es posible para nosotros comunicarse[n]con ellos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Parece que tienen buen vocabulario![f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No lo sabremos hasta que lo intentemos.[f 2 7 1 20 0 32][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 1][f 3 1 1 0 0 21069]S胤. No parecen peligrosos, as胤 que podr胤a[n]darle una oportunidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 0]Muy bien, mu姻stranos c吋mo est茨 hecho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 21012]Vale. 斡Bud! Oye, amigo, 夷tienes un segundo?[n]Estamos buscando algo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Eres una flor extra隠a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]斡Pero mira c吋mo brilla su polen en el sol![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 21082][f 6 1 2 0 0 10]Eso no es polen, es mi pelo, ya raro. De[n]todos modos, estamos buscando esta cosa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 0]Canta con nosotros, flor justa![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]斡No soy una "flosca de la cara"![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 0]斡Alaba el sol dorado en el firmamento[n]celestial![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 21035][f 6 1 2 0 0 1]斡Aqu胤 no hay sol ni firma celestial! 夷Lo[n]escuchar茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Lo siento chicos... Pero son delirios...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 1 0][f 3 1 1 0 0 0]No te preocupes... Al menos a雨n tienes tu[n]pelo de polen.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cuando vas calvo puedes culpar a las abejas[n]por llevarte el pelo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5030][f 6 1 2 0 0 1]斡Hahaha! Oh, eso es gracioso... *Snort*[n]BWHAHAHAHAHAHAHAHAHAHAHAHAHAHA![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡C茨llate, no es tan gracioso![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 6][f 3 1 1 0 0 0]Ni siquiera lo intentes. Una vez que Yukiko[n]ha sido despedido, no hay parar sus[n]risitas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 2 0 1][f 3 1 1 0 0 11031]夷Por qu姻 no me dejas manejar esto?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]斡Con mis poderes de persuasi吋n, les contar姻[n]dulcemente en derramar los frijoles![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]斡Por qu姻 hola, amiguitos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Puedo decir que hoy hueles hermosa! 斡Qu姻[n]olor![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]斡Nunca! 斡Qu姻 cosa incre胤blemente inapropiada[n]para decir![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]夷Tu madre no te ense隠吋 modales cuando eras[n]una semilla?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11061][f 6 1 2 0 0 4]夷Eh? Espera, 夷qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 0]斡Vuelve a cantar! Ahem... Cuando los rayos[n]brillan sobre m胤 me regocijo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 11083]斡Vamos! S吋lo quiero preguntar por esta cosa[n]que estamos buscando...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 0]Por el tiempo eterno, todos nos basamos en[n]este sol por elecci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Junpei]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 11 5 0 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Um... Est茨n muy cautelosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 12002][f 6 1 2 0 0 4]夷Qu姻 pas吋 con tus incre胤bles poderes de[n]persuasi吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Amigo, no pueden ser razonados con![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]斡Hora de cambiar! 斡Ir姻 despu姻s![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Despu姻s de todo, realic姻 mis habilidades de[n]gente en Junes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 9103][f 6 1 2 0 0 6]斡Guau! 斡Vamos, Yosuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 3][f 3 1 1 0 0 0]斡Mira y aprende![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 3 1 1 0 0 3132]斡BIENVENIDO![n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 3][f 3 1 1 0 0 0]Hm, eso siempre funcion吋 en Junes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No lo entiendo; simplemente segu胤an cantando[n]esas palabras. 夷Qu姻 parece ser una[n]met茨fora para algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 4112]Tal vez algo en la mente de Hikari...[n]夷Pero qu姻 se supone que hagamos ahora?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]No nos vamos a ning雨n lado a este ritmo.[n]夷Alguien tiene alguna otra idea brillante?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 7 0 0][f 3 1 1 0 0 0]No tenemos ninguna otra pista...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]No sabemos nada m茨s sobre la "cosa negra"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 4][f 3 1 1 0 0 0]夷Quieres saber sobre lo negro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 2 0 0 4][f 3 1 1 0 0 0]Bueno, bueno. 夷Por qu姻 no lo dijiste?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3062][f 6 1 2 0 0 0]夷Ahora responden?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 0][f 4 6 21 12 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡C茨llate, Yosuke! Hey, amigos, 夷qu姻 es[n]exactamente "lo negro"? 夷D吋nde podemos[n]encontrarlo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Hehehehehehehehehehehe. La "cosa negra" fue[n]quitada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Flor Alegre]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Y abajo abajo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Flor Relajada]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Quer胤an todo para ellos mismos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Um... Realmente no entiendo lo que est茨n[n]diciendo, pero b茨sicamente podr胤a haber algo[n]abajo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 81 1 1 3][f 4 6 21 12 0 1][f 3 1 1 0 0 21003]Hikari, 夷te suena esto?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷O sientes algo bajo tierra?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 0]Um... Es s吋lo un sentimiento vago, pero siento[n]algo por aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 0]No puedo explicarlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 0]No tienes que hacerlo. Toda esta pel胤cula[n]est茨 basada en tu mente, Hikari.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28031]Deber胤amos investigar cualquier sentimiento[n]que tengas, no importa lo vago.[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0]Si姻ntate, Hikari. Encontraremos lo que[n]sea que est姻s buscando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 61147]Muchas gracias... Es un alivio tener la ayuda[n]de todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 11 12 0 1][f 3 1 1 0 0 0]As胤 que tenemos que estar seguros de mencionar[n]"cosa negra" donde quiera que vayamos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Despu姻s de todo, otras flores podr胤an saber[n]m茨s sobre ello. Intentemos buscar en el[n]piso debajo de este![n][f 1 3 65535][f 1 1][e]

