[msg MSG_000 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 6 1 2 0 0 1][f 3 1 1 0 0 0]斡Hora de pagar sus cr胤menes! 斡Ven tranquilo[n]y nadie sale herido![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 11 0 3][f 3 1 1 0 0 21013]夷Y qu姻 hacemos? 夷S吋lo cobra y lo agarra?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 1][f 3 1 1 0 0 0]Espera... Podr胤as asustarlo de nuevo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 1][f 3 1 1 0 0 0]Ven aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]La mariposa creci吋 m茨s peque隠a, y aterriz吋[n]en el dedo de Hikari...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 1][f 3 1 1 0 0 61151]Hee hee... Eres tan linda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 0 3][f 3 1 1 0 0 0]Whoa! 斡Hikari, eso fue incre胤ble! 夷C吋mo[n]hiciste eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 1][f 3 1 1 0 0 0]Bueno... S吋lo quer胤a hacerlo, y sucedi吋. Tal[n]vez porque es mi pel胤cula...[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Bien hecho.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Me sorprendiste.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Adorable...[f 2 7 1 20 0 32][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 0 1][f 3 1 1 0 0 61147]Gracias. Joker. Me alegro de poder ayudar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 1][f 3 1 1 0 0 61172]Yo tambi姻n me sorprend胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 1][f 3 1 1 0 0 61168]U-um..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 8 0 1][f 3 1 1 0 0 0]La mariposa... S胤. Creo que tambi姻n es lindo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 4][f 3 1 1 0 0 0]Una chica preciosa, y una peque隠a mariposa[n]en su dedo. Como una princesa de[n]Destinyland...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 23106]Muy bien. 斡Tenemos la mariposa! Misi吋n[n]cumplida![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Vamos a casa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 4][f 3 1 1 0 0 0]斡Mira aqu胤! 斡Este lugar est茨 lleno de flores![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 27031]斡Tienes raz吋n! Qu姻 aroma tan encantador,[n]tambi姻n... Realmente es un lugar[n]maravilloso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Hay colores a nuestro alrededor, y huele como[n]un jard胤n fresco...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0]Oye, hemos estado caminando durante siglos.[n]夷Por qu姻 no tomamos un descanso aqu胤?[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Suena bien.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Mejor retroceder...[f 2 7 1 20 0 32][e]

[msg MSG_018 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 9041]斡Hurra! 斡Retrocede para el aperitivo![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Tambi姻n podr胤amos relajarnos. Es un buen[n]lugar para hacerlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 4][f 3 1 1 0 0 9023]夷Eh? Joker, 夷est茨s enfermo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 4][f 3 1 1 0 0 0]斡Vamos, ser茨 un poco! 斡Quiero hacer un picnic[n]con todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Lo siento. 夷Te importa dejar que Teddie tenga[n]esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Decidimos tomar un descanso en esta[n]ubicaci吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 4][f 3 1 1 0 0 0]斡Oh! 斡Veo una mariposa![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 3][f 3 1 1 0 0 22116]Tambi姻n hay mucho aqu胤. Probablemente ir por[n]las flores, supongo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 0]斡Son todos tan hermosos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Quiero coger mariposas como Hikarin![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 4][f 3 1 1 0 0 0]斡Vamos, pandilla! 斡Sigan mis feromonas![n][f 1 3 65535][f 1 1][e]

[msg MSG_027]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Las mariposas est茨n enjambre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 1][f 3 1 1 0 0 0]...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Teddie, no! 斡Atr茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 100 4][f 3 1 1 0 0 14534][f 3 1 6 0 0 500]斡Estoy viendo muchas sombras cerca de repente![n]斡Prep茨rense para defenderse![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 11 0 3][f 4 6 26 10 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500]斡Son todas sombras! 斡Aqu胤 vienen![n][f 1 3 65535][f 1 1][e]

