[msg MSG_000 [Ryuji]]
Entonces, 夷cu茨l es el plan para hoy?[n]Todav胤a tenemos tiempo hasta la fecha[n]limite.

[msg MSG_001 [Morgana]]
Una cosa que podr胤amos hacer es intentar[n]fortalecernos en Mementos.
Pero decidamos despu姻s de que llegue la[n]se隠orita Ann. Nos envi吋 un mensaje[n]diciendo que casi llega...

[msg MSG_002 [Ann]]
斡Perd吋n por llegar tarde! La sesi吋n de[n]fotos duro m茨s de lo esperado.

[msg MSG_003 [Futaba]]
Oh, hablando del rey de Roma.

[msg MSG_004 [Makoto]]
夷Eh? 夷Para qu姻 es ese folleto?

[msg MSG_005 [Ann]]
斡Ah, esto? Alguien me lo dio mientras[n]estaba en el set.

[msg MSG_006 [Ryuji]]
夷Un festival de cine estudiantil del[n]instituto?

[msg MSG_007 [Morgana]]
夷Qu姻 es eso?

[msg MSG_008 [Haru]]
Bueno, es un evento donde los[n]estudiantes hacen sus propias pel胤culas,[n]las proyectan y las califican, 夷no?

[msg MSG_009 [Yusuke]]
Env胤o mis pinturas a exposiciones de[n]arte, as胤 que tiene sentido que haya un[n]equivalente para las pel胤culas.

[msg MSG_010 [Ann]]
Ni siquiera sab胤a que los estudiantes[n]del instituto pod胤an hacer una pel胤cula.

[msg MSG_011 [Makoto]]
Escritura de guiones, direcci吋n,[n]filmaci吋n... Pensar que algunos de[n]nuestra edad est茨n haciendo todo eso.

[msg MSG_012 [Ryuji]]
...

[msg MSG_013 [Futaba]]
Oye, Ryuji se qued吋 callado de repente.[n]夷Este festival te dej吋 sin palabras o[n]algo as胤? 夷Mmm?

[msg MSG_014 [Ryuji]]
No, solo pens姻 que suena genial... Oye,[n]夷por qu姻 no lo comprobamos?

[msg MSG_015 [Yusuke]]
夷Oh? Es raro escuchar ese lenguaje de[n]ti, Ryuji.

[msg MSG_016 [Morgana]]
夷Verdad? Apuesto a que va a llover[n]ma隠ana.

[msg MSG_017 [Futaba]]
No, ser茨 un tif吋n en toda regla.

[msg MSG_018 [Ryuji]]
斡Argh! 斡夷Qu姻 demonios?! 斡Tambi姻n me[n]gustan las pel胤culas, bien?!

[msg MSG_018_5 [Ryuji]]
Adem茨s, no s姻 c吋mo decirlo, pero...[n]tengo esta sensaci吋n de que tenemos que[n]ir a ver eso...
斡Ah, maldici吋n! 斡夷Qu姻 me pasa?!

[msg MSG_019 [Ann]]
Uh, no tiene sentido que nos preguntes a[n]nosotros...

[msg MSG_020 [Futaba]]
Dejando de lado el berrinche de Ryuji,[n]la verdad es que tambi姻n tengo bastante[n]curiosidad.
Hablar de pel胤culas de culto amateur me[n]emociona bastante.

[msg MSG_021 [Morgana]]
夷Una pel胤cula, eh? He visto algunas con[n][f 6 1 30 0 0 0] fueron bastante interesantes.

[msg MSG_022 [Haru]]
Ahora me est茨 entrando ganas de ir[n]tambi姻n. Oye, 夷por qu姻 no vamos todos[n]juntos?

[msg MSG_023 [Makoto]]
Eso me recuerda, nunca hemos ido a ver[n]una juntos. Esta parece ser una buena[n]oportunidad.
Hemos estado progresando a buen ritmo,[n]as胤 que 夷por qu姻 no tomamos un descanso[n]hoy?

[msg MSG_024 [Yusuke]]
Estoy de acuerdo. Esto podr胤a brindarme[n]alguna especie de inspiraci吋n art胤stica.

[msg MSG_025 [Futaba]]
斡Quiero ver una pel胤cula de ciencia[n]ficci吋n!

[msg MSG_026 [Ryuji]]
Uh, no hay forma de que un estudiante de[n]secundaria pueda hacer una pel胤cula de[n]ciencia ficci吋n solo.

[msg MSG_027 [Ann]]
Entonces, [f 6 1 30 0 0 0] 夷cu茨l es el plan para[n]hoy?

[sel SEL_028 top]
Veamos algunas pel胤culas.
Tomemos un descanso juntos.

[msg MSG_029 [Ryuji]]
斡O胤ste al chico!

[msg MSG_030 [Makoto]]
De acuerdo, vayamos todos juntos.

[msg MSG_031 [Morgana]]
Veamos... la ubicaci吋n est茨 impresa aqu胤[n]en el folleto.

[msg MSG_032 [Haru]]
*risa* Tomemos un respiro y disfrutemos[n]de un rato libre juntos.

[msg MSG_033 [Ryuji]]
Vamos, 斡prep茨rate, [f 6 1 30 0 0 0]!

