[msg MSG_000 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8118]There's another one. I'll speak with him.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 3][f 3 1 1 0 0 0]Go, Detective Prince! Find the culprit![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]My apologies for the wait.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8093]"The officer with double 7s is acting[n]suspicious."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...That's all I learned.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 3][f 3 1 1 0 0 26023]Double 7s? Sounds more like a lucky[n]number... Maybe the Shadow's tryna[n]stay lucky?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]This guy's car number is...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]44-11. Doubles of both 4 and 1.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 8026]Thank you, Oracle. Let's keep going.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]He said the officer with double 7s is[n]acting suspicious...[n][f 1 3 65535][f 1 1][e]

