[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 26115]Ohh. There's the terminal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Gimme just a sec. Let's see if I can get[n]what we need.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]Very well. I suppose we can take a break,[n]then.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 0 4][f 3 1 1 0 0 26073]Done.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 3 1 1 0 0 8059]Huh!? Already?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 4][f 3 1 1 0 0 26045]Hehehe. Piece of cake. All I did was take[n]a look.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 12 0 4][f 3 1 1 0 0 0]Joker, I'm gonna tell you where the cars[n]are at. Mark them on your map.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]The locations of the police cars have[n]been added to the map.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]This'll make things a little easier.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The officers should be at their cars.[n]Let's be on our way.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 12 0 1][f 3 1 1 0 0 0]Looks like we don't need this anymore.[n]We already know where the cars are.[n][f 1 3 65535][f 1 1][e]

