[msg MSG_000 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 1][f 3 1 1 0 0 24008]......[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]What's wrong?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Are you hungry or something?[f 2 7 1 20 0 32][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24027]Oh... Sorry, I was just looking at this[n]graffiti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 24051]Well, I certainly could eat, but I'm[n]far from starving.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]I was just looking at this graffiti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0]Look here. It's unfinished.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oh yeah, it ain't like the others. Maybe[n]they got bored halfway through?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 24078]No, that's unlikely.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I can feel the artist's hesitation here,[n]their suffering...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Their hands were forced to stop[n]painting against their will. Right here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]Wow, Fox. How did you figure all of[n]that out?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 5 1 0][f 3 1 1 0 0 0]Graffiti is a crime, but there's an artistic[n]quality to it that can't be dismissed.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]And I don't just mean the technique.[n]I mean the creator's feelings and the[n]message they try to convey to society...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 3 1 1 0 0 0]Yes, it's coming to me! This well of[n]inspiration simply won't stop flowing![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ahh, perhaps I'll fill in the blanks and[n]finish it for them...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 24099][f 6 1 2 0 0 6]Urgh! No... Be still, my hand...![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Welp, he's at it again.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 0]Hmm, I've never really cared much for[n]graffiti.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 0]But it's a crime, right? If Queen found[n]out, you'd be tasting the iron fist of[n]justice for sure.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 6][f 3 1 1 0 0 22092]Hey, how long are you guys gonna[n]stand there? Queen and Noir are[n]waiting for us! Let's go![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 24 0 0 0][f 3 1 1 0 0 0]My apologies, I was distracted... Right.[n]They're our top priority.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Now then, let's be off. We must[n]dethrone that false hero![n][f 1 3 65535][f 1 1][e]

[msg MSG_013]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]There's some unfinished graffiti here[n]on the wall...[n][f 1 3 65535][f 1 1][e]

