[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 6 28 2 0 3][f 3 1 1 0 0 28106]Now then, let's get to gathering those[n]ingredients, shall we?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]All we need are Tingly Kernels,[n]isn't that right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 8067]Yes, but it wouldn't be wise to search[n]blindly.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 1 0][f 3 1 1 0 0 0]Theodore gave us a tip on where to[n]find some...[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Bright places.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Windy places.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Damp places.[f 2 7 1 20 2 32][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 4][f 3 1 1 0 0 9023][f 6 1 2 0 0 4]Oh? He said that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28083]No, he said we should look somewhere[n]damp.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]In which case, we should probably[n]concentrate our search near bodies of[n]water.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8071]Yes, he mentioned searching in damp[n]locations.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]In which case, we'll want to[n]concentrate our search near bodies of[n]water.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]By the way, why do we need the[n]popcorn?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 28008]We currently only have circumstantial[n]evidence, so we have no choice but[n]to catch the culprit in the act.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 8075]Therefore, we'll ask Theodore to make[n]his new popcorn again...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]And we'll use that as bait to lure in the[n]culprit, correct?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 0][f 3 1 1 0 0 0]Yes. Plus, no one will suspect anything;[n]they'll think we're just trying to help[n]Theodore.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 0]Hrrm... How bear-y clever.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 28031]*chuckle* You're too kind.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 20 1 0 3][f 4 6 8 12 0 0][f 3 1 1 0 0 0]We'll find Tingly Kernels near the[n]water. Let's begin our search.[n][f 1 3 65535][f 1 1][e]

