[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 6 2 1][f 3 1 1 0 0 54036]It would seem those two caused quite a[n]stir...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]This was clearly negligence on[n]Theo's part. Fear not. I shall give[n]him a strict talking-to after this.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Here is your reward for this time. Please[n]accept it.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54115]Excellent work, everyone.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 8 1 0 1][f 4 6 72 2 0 3][f 3 1 1 0 0 28031]This case certainly was interesting.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 0]Yes, I agree.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...Seeing the two of them reminded me[n]a little of my old self.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Your old self?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]You were like that?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 8012]Well, I just mean that I understand what[n]it feels like when you can't be honest[n]with yourself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 0]That's unexpected. I'd say you seem[n]much more mature than those two.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 8136]There was once a time when I tried[n]to suppress who I really was in order[n]to become my ideal self.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's thanks to my friends that I was able[n]to accept my true self...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 0]Your true self, huh...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Akechi-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 28078]Oh, I was just thinking that you've got[n]some wonderful friends. Detectives[n]typically work solo, you know?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm glad I was able to team up with you[n]this time around.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8031]*chuckle* It was rather thrilling for me[n]as well.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Another Detective Prince... I feel as[n]though working with you will help me[n]sharpen my deductive skills.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 28068]Indeed. Let's keep working together to[n]see that we all make it home safely.[n][f 1 3 65535][f 1 1][e]

