[msg MSG_000 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 6][f 3 1 1 0 0 17002]Arf! Woof, woof![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 3][f 3 1 1 0 0 16029]Look, more bones! We're really making[n]progress, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Yes, thanks to Koromaru-kun. All right,[n]it looks like it's my turn.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 1][f 3 1 1 0 0 28072]These certainly look like leftovers, and[n]they're pretty recent too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 3][f 3 1 1 0 0 12054]What!? Is it finally time for the[n]face-off!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]Haha, sorry, not quite yet.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I said recent, but it's still been some time[n]since these bones were left behind.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 6][f 3 1 1 0 0 17002]Bark, bark, bark![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]I see. So we should make our way east[n]now?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ken]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 16 10 0 3][f 3 1 1 0 0 16039]......![n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]You can understand him?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I think he said west.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28078]Oh, no, not really. I just sort of pictured[n]him saying that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Was I right, Amada-kun?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 3][f 3 1 1 0 0 0]...Yeah. It sounds like Koromaru's[n]saying to head east.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28033]Hm? Was I wrong?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 3][f 3 1 1 0 0 0]...No, you were right, Crow. Koromaru[n]said to head east.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 1][f 3 1 1 0 0 6548]Wow, Crow and Koro-chan make a[n]pretty good team.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6614]Okay then, we're heading east![n][f 1 3 65535][f 1 1][e]

