[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 19 12 0 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19009][f 6 1 2 0 0 4]Uhm, so we just have to defeat the[n]targets at the locations Elizabeth[n]specified, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 0]That's all we need to do? That'll[n]be easy.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 13004]Just remember, these Shadows aren't[n]weak. Don't hesitate to run if things get[n]out of hand.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0]Especially you, Akihiko. You get heated[n]far too easily. Set a good example for[n]the underclassmen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12093]I know. Give me some credit.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 1][f 3 1 1 0 0 18129]Hah, do you now...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What, you don't believe me, Shinji?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]Try being the one who has to rein you in[n]every time you run off on your own.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 0][f 3 1 1 0 0 12062][f 6 1 2 0 0 6]Wha―Well, what about you, Shinji!?[n]You've been talking down to us for who[n]knows how long...![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 6 0 1][f 3 1 1 0 0 13040]*sigh* This again... They'll be a moment.[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Please say something, Mitsuru.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Help, [f 6 1 27 0 0 0].[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Let's leave them be.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 13078]Even if I were to intervene, they'd just[n]keep going.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Perhaps it's because they've known[n]each other since they were kids. I swear,[n]they're so immature...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13078]I don't think [f 6 1 26 0 0 0] could[n]help if she tried.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's these two we're talking about. It'll[n]just start up again.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 13078][f 6 1 2 0 0 4]It'll never end. You don't intend to wait[n]it out, do you?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19030][f 6 1 2 0 0 6]It's okay, I have an idea! Just leave[n]it to me![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What do you plan to do,[n][f 6 1 26 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 12 1 0 1][f 4 6 18 1 0 4][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19071][f 6 1 2 0 0 1]Shinjiro-senpai! Akihiko-senpai![n]Listen up![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]This is a hunting mission, so why don't[n]we have a competition to see which one[n]of you is the better fighter?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 12018][f 6 1 2 0 0 4]A competition, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]That's right. But you can't just defeat[n]the enemies.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]We're in this together, so flying solo's[n]off limits.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]This will be about observing your[n]teammates and doing your best to[n]support them.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 3 1 1 0 0 19031][f 6 1 2 0 0 4]We'll decide the winner based on their[n]overall performance. Deal?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031]Heh... Interesting. I accept.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If I win, then you have to train with me,[n]Shinji.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 0][f 3 1 1 0 0 18050]Wha―!? Why the hell would I have to[n]do that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What, you're not afraid of losing,[n]are you?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 9 1 0][f 3 1 1 0 0 18093][f 6 1 2 0 0 2]You little... There's no way I'd lose to[n]you, Aki.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 9 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]All right, it's a duel, Shinji![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 9 1 0][f 3 1 1 0 0 18129]Hah, don't come crying to me later.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]So where're these enemies? I'm ready[n]for 'em.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 9 1 0][f 3 1 1 0 0 12002]Trying to go at it alone...? That's against[n]the rules. Minus one point![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 0][f 3 1 1 0 0 18058]What!? That doesn't count. We haven't[n]even started yet.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Working together is key, okay? Good[n]luck, you guys![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 13 2 0 1][f 3 1 1 0 0 13031]To think you'd be able to tame those[n]two... Not bad, [f 6 1 26 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19130][f 6 1 2 0 0 6]Ahaha, I'm used to it. The ones I know[n]are just like that![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 13109][f 6 1 2 0 0 9]*sigh* They're like that over there too?[n]It's already giving me a headache...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 0]Either way, thanks to [f 6 1 26 0 0 0][n]we can finally move forward.[n]Let's get going.[n][f 1 3 65535][f 1 1][e]

