[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54010]This next special screening promises to[n]be a rather action-packed adventure...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]It's a treasure hunt. Your task will be to[n]locate the hidden treasure deep within[n]the jungle![n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]What else is new?[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]That's our thing.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Hidden treasure?[f 2 7 1 64 0 32][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23069]Yeah. Finding treasure is the Phantom[n]Thieves' specialty.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]So what kind of treasure is it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 54016]It seems to be some sort of prized[n]artifact a researcher intended to offer to[n]his lover...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hoping to do so once his research was[n]complete, he hid it for safekeeping.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 0 0][f 3 1 1 0 0 0]...What happened to the researcher―[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54023]Here is a map of the treasure's[n]location... Oh? There appears to be[n]something scribbled on the back...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 0]"Once this job is over, I'll finally propose[n]to her."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]"This work is the sheer embodiment of[n]both beauty and allure. She's sure to[n]love it..."[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 0][f 3 1 1 0 0 26096]Guess he tempted fate...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0]So it was a present to his girlfriend...?[n]I'm kinda curious about what it was.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]He said it was the embodiment of[n]beauty. Maybe it's some kind of jewel?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6030][f 6 1 2 0 0 6]Wow, that's so romantic![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 10 0 1][f 3 1 1 0 0 0]The girls sure are excited about this...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 10 0 1][f 3 1 1 0 0 9062][f 6 1 2 0 0 1]Ooh! This is it![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Huh!? What're you goin' on about!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 9029][f 6 1 2 0 0 6]Whoever finds the treasure first will be[n]crowned the number-one mascot![n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Number-one mascot?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Why?[f 2 7 1 64 0 32][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9012]A mascot's duty is to make the ladies[n]happy and provide comfort whenever[n]they need it...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Naturally, if finding the treasure makes[n]everyone happy, then it's only fair that[n]the one who finds it gets the title![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 6 0 0][f 3 1 1 0 0 17004]Woof...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 6][f 3 1 1 0 0 0]Koromaru-san says he has no idea[n]what you're talking about.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 6 0 0][f 3 1 1 0 0 23092][f 6 1 2 0 0 9]You said it. No one cares about your[n]silly little contest...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 1 0][f 3 1 1 0 0 9016][f 6 1 2 0 0 4]Oho...? Well, if there's no competition,[n]then I guess I win by default.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0]And then I get pretty Ann-chan all to[n]myself...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23064][f 6 1 2 0 0 6]Arrrgh! Where do you get off!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 9135][f 6 1 2 0 0 6]If you don't like it, just try and take the[n]title from me![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 5 0 0][f 3 1 1 0 0 23099][f 6 1 2 0 0 6]Dammit... Fine, I'll do it! But let's get[n]one thing straight...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I don't care about your stupid title![n]I'm only doing this to make Lady[n]Ann happy![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 1][f 3 1 1 0 0 10003][f 6 1 2 0 0 4]It's getting pretty heated over there. Are[n]they okay?[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]They're fine.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]It's actually convenient.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana's gonna win.[f 2 7 1 64 0 32][e]

[msg MSG_025 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 6][f 3 1 1 0 0 26114]Well, it is a treasure hunt. It's good for[n]everyone to be motivated.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23015][f 6 1 30 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Right. There's no way I'm losing to some[n]pervy bear![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 17 1 0 3][f 4 6 71 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What about you, Koro-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]Arf! Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 6][f 3 1 1 0 0 0]"The contest is of little interest to me,[n]but I'll gladly help look for the[n]treasure..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...So says Koromaru-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9068][f 6 1 2 0 0 6]Then, that settles it! Let the first-ever[n]Mascot Match-up begin![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 1][f 3 1 1 0 0 9107][f 6 1 2 0 0 6]May the manliest of all men,[n]come on down![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 6][f 3 1 1 0 0 23108][f 6 1 2 0 0 6]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 0][f 3 1 1 0 0 17001][f 6 1 2 0 0 6]Arf![n][f 1 3 65535][f 1 1][e]

