[msg MSG_000 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 1][f 3 1 1 0 0 27011]So we just have to get through this[n]floor, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]She told us the layout has become[n]terribly complex, but it doesn't seem[n]that way...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 3][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Hrrm...? Whoa, the warp points are[n]in different places![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1017]That's not good. Those things were[n]already confusing to begin with.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]Not to mention we don't have any[n]information besides our objective.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If only we had some kind of hint[n]to help us find our way...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 1][f 3 1 1 0 0 17002]Arf arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Koromaru has a piece of paper[n]in his mouth...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 4][f 3 1 1 0 0 16009]Hey... There's something written[n]here.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 1][f 3 1 1 0 0 0]G, R, O, W...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 3 1 1 0 0 0]It spells "GROW"... Does it mean, like,[n]physically or metaphorically?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 4][f 3 1 1 0 0 13013]Perhaps it's some kind of code?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]In any case, it's safe to say this is[n]some manner of clue for the sake[n]of this special screening.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 1][f 3 1 1 0 0 0]So the warp points are different,[n]and we've got this paper that says[n]"G-R-O-W"...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]What do you think of all this,[n]Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Not sure yet.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Aha, I get it...[f 2 7 1 20 0 32][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 8089]We don't have enough clues to say[n]for certain right now. Maybe if we[n]keep moving, we'll learn more.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 3 1 1 0 0 8049]Really!? And with so few clues...[n]Impressive deduction.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]In any case, we'll follow your lead,[n]Joker. Let's keep moving for now.[n][f 1 3 65535][f 1 1][e]

