[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 100 1][f 3 1 1 0 0 54001]Yet another special screening has been[n]added.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 0]It seems this screening will take place[n]within Kamo City.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Having lost their hero, the townspeople[n]need encouragement as they set off[n]toward a new tomorrow...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Such is the heartfelt setup for this[n]showing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 1][f 3 1 1 0 0 25015]Encouraging the people... This seems a[n]little different from what we're[n]normally tasked with.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Well, we are the ones who took down[n]Kamoshidaman...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I won't exactly say we're responsible,[n]but... you think maybe we should take[n]this one?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 1][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2066]Yeah. We should help if we can.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]All right, then let's get out there and[n]make it happen![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Not so faaast! Eliza-blocker on![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 7096][f 6 1 2 0 0 9]Wh-What're you doin'...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 0][f 3 1 1 0 0 0]For this special screening, a certain[n]special condition has been[n]implemented...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You will be required to bring a special[n]set of members on this outing.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Said special individuals include: Aigis, Haru[n]Okumura, and Rise Kujikawa![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Those three must take part.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 9023][f 6 1 2 0 0 4]Huh? Why's that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 0][f 3 1 1 0 0 0]Well, according to my source...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Those chosen babes gotta use them[n]bomb-ass powers and bring happiness[n]to the hearts of the people, YO![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]...So I'm told.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 11008][f 6 1 2 0 0 9]There's no way that's what was written[n]down...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]So basically, the triple beauties are the[n]stars of this show?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]Indeed. I believe it should suffice if[n]you include those three in your active[n]party.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Beauties...? I'm included in that too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Heyyy, Beauty Thief on the scene![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 0][f 3 1 1 0 0 27050][f 6 1 2 0 0 4]...Shall I wring your neck?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]No, I was, uh, just joking![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Hrrm... A special girl's-themed[n]screening... This is sure to lead to some[n]girl talk![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]In that case, I can't let myself be beat in[n]the looks department![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 1][f 3 1 1 0 0 6032]Ahaha, you seem pretty fired up,[n]Teddie. You must be confident.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0]I've already told myself I'm going to[n]become the fairest of them all.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Once I empower everyone with my[n]unmatched beauty...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I will enter the secret world of girls[n]and finally know the pleasures of[n]girl talk![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15106]This would mean your aspirations to[n]participate in girl talk hinge on this[n]screening.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 0 1][f 3 1 1 0 0 0]Teddie's motivations aside, if the[n]screening requires it, then I guess we[n]don't have much choice.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]I'm just a navigator, but I'll do my best![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 4][f 3 1 1 0 0 27002][f 6 1 2 0 0 4]Is it all right if we handle this screening,[n][f 6 1 30 0 0 0]-kun?[n][f 1 3 65535][f 1 1][e]

[sel SEL_021 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]It's all you.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]I'm a little worried.[f 2 7 1 64 4 32][e]
[f 0 5 65278][f 2 1]I'll do my best too.[f 2 7 1 64 0 32][e]

[msg MSG_022 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 4][f 3 1 1 0 0 15069]Understood. We will ensure the mission[n]is a success.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Prepare to feast your eyes on my[n]oh-so-refreshing beauty! Here comes[n]Teddie![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3014][f 6 1 2 0 0 9]I know what you mean. I know all too[n]well...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 0]Don't worry! Teddie, beauty amongst[n]beauties, is here to help![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]That's exactly WHY we're worried![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3013][f 6 1 2 0 0 4]Well, it doesn't sound like we'll be[n]fighting any FOEs, so it should be fine...[n]I think?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 4][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]That's true. Just don't push yourselves if[n]it gets too tough.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11071]Yeah! Honestly, I'm pretty stoked too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Being surrounded by all these girls...[n]I'm one step closer to Junpei's Harem[n]Dream Team...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 1][f 3 1 1 0 0 0]You know, Junpei...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]You're really... REALLY disgusting.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Why you gotta shoot me down like[n]that!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 71 1 0 3][f 4 6 15 1 0 4][f 4 6 6 12 0 1][f 3 1 1 0 0 6016]So, Haru-san and Aigis need to be in the[n]main party, and I'm on navigator[n]duty, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Let's head out once[n][f 6 1 30 0 0 0]-san finishes[n]organizing the party![n][f 1 3 65535][f 1 1][e]

