[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 1][f 3 1 1 0 0 11045]Yo, an arrow! Looks like we gotta[n]go that way.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 3][f 3 1 1 0 0 0]This is kinda fun. It's almost making me[n]feel like a little kid again.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 4][f 3 1 1 0 0 26567][f 3 1 6 0 0 500][f 6 1 2 0 0 6]I know, it's so exciting![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Looks like there aren't too many hint[n]arrows. Careful not to miss anything.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 8 32 3][f 3 1 1 0 0 0]The arrow is pointing to the left.[n]Let's try going that way...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1][f 4 6 20 8 32 3][f 3 1 1 0 0 0]The arrow is pointing to the left.[n]Let's try going that way...[n][f 1 3 65535][f 1 1][e]

