[msg MSG_000 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 100 1][f 3 1 1 0 0 14543][f 3 1 6 0 0 500][f 6 1 2 0 0 7]Good job, everyone! That's the first[n]one![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 0]All right! We just need two more,[n]right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]But this is gonna power up our[n]navigators, huh? Wonder what[n]powers they'll get?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 6][f 3 1 1 0 0 12015]Hm... Maybe something like[n]Auto-Protein? It can automatically[n]give us a boost of protein![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Well... I'd like something cooler.[n]Maybe they'll be able to generate[n]beam sabers for us![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Sorry to break it to you, guys, but[n]beam sabers aren't in the cards.[n]Or protein, either.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 0][f 4 6 12 6 0 0][f 3 1 1 0 0 0]Bah, figures...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 7 0 0][f 3 1 1 0 0 16078][f 6 1 2 0 0 9]O-Of course not...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 100 1][f 3 1 1 0 0 0]We're looking to increase our speed[n]and our information streaming so[n]we can work even better as a group.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 2 100 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I think I should be able to hack[n]something like that together...[n]I'm sure it'll help![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 3 2 0 0][f 3 1 1 0 0 0]You say that like it's easy, but the[n]fact that you can just invent new[n]tech like that is amazing...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 4][f 3 1 1 0 0 6530][f 3 1 6 0 0 500]I know, right? It's crazy what[n]Oracle and Fuuka-chan can do with[n]all this engineering stuff![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]They're our navigator dream team![n]They can do anything![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 8 100 0][f 3 1 1 0 0 0]O-Oh, I don't know... Your navigation[n]skills are just as good as ours.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 0]Yeah! She's accurate, she keeps[n]things simple, and hello, she's an IDOL![n]Who wouldn't love having her around?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1071]Each navigator is different and unique.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]But there's one thing they all have,[n]and that's incredible skill. That's why[n]we can explore without worrying.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 8 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Eheheh... Well, when Senpai says[n]it like that...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]But this'll help us power up even more![n]So be ready, okay?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 100 1][f 3 1 1 0 0 14625][f 6 1 2 0 0 6]Do your best to find the last two[n]pieces, everyone![n][f 1 3 65535][f 1 1][e]

