[msg MSG_000 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 1][f 3 1 1 0 0 12005][f 6 1 2 0 0 4]So, Kanji. I hear you want training[n]too? You want to break your limits?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 3][f 3 1 1 0 0 0]Uh... I wanna break SOMEthin',[n]I guess.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 0]All right! Then let's head to the FOE's[n]position![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]First, we'll do bunny hops all the[n]way there![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 7 11 0 3][f 4 6 11 10 0 6][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]At least let us walk! And what do you[n]mean by "first"!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 0]It's the first part of your training![n]I'm not gonna waste a single[n]opportunity.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Crawling on the ground, running at[n]full speed, walking on our hands...[n]We've got a lot of distance to cover.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 11 7 0 6][f 4 6 7 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Hopefully we won't die before we[n]even get to the FOE...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 12 2 0 1][f 3 1 1 0 0 12108]Let's get moving, Joker![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]The gong's already rung! Junpei,[n]Kanji, don't fall behind![n][f 1 3 65535][f 1 1][e]

