[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 3][f 3 1 1 0 0 3043]Yeah! That's what happens when we get[n]serious![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 1][f 3 1 1 0 0 0]Not bad, everyone. But not quite as[n]awesome as me.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Sorry, but that's just the reality of[n]working alongside a SEES ace such as[n]myself. I can't help being MVP.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Nah man, I was the MVP. I was out in[n]front of everyone![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]What!? Dude, it was me! Nobody would[n]have had the flowers' hint without me![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 4029]They sure seem chatty over there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 3][f 4 6 5 2 0 4][f 3 1 1 0 0 0]Well, at least they make a good team.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 1][f 3 1 1 0 0 0]Alright then, let's ask [f 6 1 16 0 0 0],[n]the leader of SEES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 2 13 0 3][f 4 6 11 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Who did the best this time? Me, myself,[n]or I?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 3 4][f 3 1 1 0 0 21035][f 6 1 2 0 0 2]The hell kinda question is that!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 0]Haha, I can't answer that. You all did[n]really well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 21 1 0 4][f 4 6 11 1 0 1][f 4 6 1 0 1 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]He's right. All three of you did great.[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]You're awesome, Skull.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]I'm counting on you.[f 2 7 1 20 0 32][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 0 0][f 3 1 1 0 0 21033]Oh, uh, thanks... Um, yeah, I'm not[n]used to praise, so I dunno what to say...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 1][f 4 6 1 2 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]No need to explain. My partner,[n]Yosuke, can't accept praise either. But[n]I too feel unbeatable with him.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 8 0 1][f 3 1 1 0 0 0]Whoa, not you too...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Wait, did you say "unbeatable"? Did[n]you... overhear us talking earlier?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 4][f 3 1 1 0 0 11044][f 6 1 2 0 0 4]Aw, geez. Don't tell me [f 6 1 27 0 0 0][n]and [f 6 1 16 0 0 0] might've heard, too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]Yep. We heard every word.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And I'd like to offer you my heartfelt[n]thanks, Junpei.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 10]No! I'd rather you make fun of me![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2024]I thank you as well, Junpei. Let's have a[n]good rivalry.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 8 0 4][f 3 1 1 0 0 0]Oh, uh, sure...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Wait, didn't you hear what I just said!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 21 13 0 1][f 4 6 22 2 0 3][f 3 1 1 0 0 22030]Haha, you're so loud that we could hear[n]everything you said, Skull.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Maybe now you'll be quiet when we[n]tell you to be.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Dammit, this is so embarrassing. Even[n]Panther's joined in...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]...Argh, I don't got time for this![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 1 0 3][f 3 1 1 0 0 61050]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What about leaving behind this mushy[n]stuff and doing our mission? Hikari, did[n]you find what you were looking for?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 3][f 3 1 1 0 0 0]...Yes! This is the thing I sensed.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 4][f 3 1 1 0 0 3044][f 6 1 2 0 0 6]Hey, you did it! Congrats, Hikari-chan![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]I couldn't have done it without you all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025_2 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]Glad it all worked out. If you ever need[n]a helping hand again, you know where[n]to find me.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11030]I'll come runnin' to Hikari in a hikurry![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Uh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Hikari in a hikurry? That joke's so bad[n]I don't even know what to say...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 21012]Man, I almost feel sorry for your[n]buddy, [f 6 1 16 0 0 0]...[n][f 1 3 65535][f 1 1][e]

