[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 0 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54002]This special screening this time is a[n]bit fanciful, a bit ethereal, like a[n]fairy tale...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'd like for you to find a butterfly in[n]Hikari's movie, and bring it here.[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1]Sounds easy.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]I don't like bugs...[f 2 7 1 64 0 32][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 4][f 3 1 1 0 0 61185]Now that I think about it, there were[n]a lot in my movie. They were all so[n]beautiful...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 4][f 3 1 1 0 0 4010]S-Same here... But I think I can[n]handle butterflies.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 3][f 3 1 1 0 0 0]So we have to go catch a butterfly?[n]A specific one, or any of them?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]If we're going through the trouble[n]anyway, I'd prefer you catch a real[n]lunker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 4][f 3 1 1 0 0 26013]Can butterflies be "lunkers"?[n]Isn't that a fish thing?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 3][f 4 6 70 4 0 4][f 3 1 1 0 0 0]I better not see you trying to eat[n]one, Inari. I don't care how much[n]protein they have![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 3][f 3 1 1 0 0 0]Insects? Even I have my limits.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Though... Perhaps if there was no[n]other choice...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 4][f 4 6 8 10 0 1][f 3 1 1 0 0 0]I-Is it too late to raise objections?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 4][f 3 1 1 0 0 12075]Interesting. You said they're full of[n]protein?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 3][f 3 1 1 0 0 0]How about you stop right there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 0 0 3][f 4 6 71 12 0 1][f 3 1 1 0 0 0]*giggle* It sounds almost like a[n]picnic, doesn't it? Surrounded by[n]flowers, looking for butterflies...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 23074]With all those Shadows around, we[n]can't let our guards down... but[n]I guess we can relax a little.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Okay... Once we're ready, let's go.[n][f 1 3 65535][f 1 1][e]

