[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54035]An out-of-control cart careens toward[n]the doomed workers! But at the last[n]moment, [f 6 1 30 0 0 0] decides their fate![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...Perhaps it was only two questions,[n]but they may have shown great[n]insight into your hearts.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]While this was a bit of a departure[n]from the usual special screenings,[n]I enjoyed it nonetheless.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 26013]But who made those signs in the[n]first place? And what about the[n]spooky announcer lady?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11113]Actually, now that I think of it, that[n]sexy voice was kinda familiar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ring any bells for you, [f 6 1 30 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]No idea.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Elizabeth?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]It WAS familiar...[f 2 7 1 64 0 32][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 8 0 1][f 3 1 1 0 0 11030]Man, but my Babe Radar is going[n]wild![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Someone real sexy, real mature,[n]with that kinda sophisticated aura[n]to her...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54067]Most unfortunately, it was not me.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I am more likely to be found in my seat[n]during screenings, devouring popcorn[n]and hot dogs with wild abandon.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]I'm glad you enjoyed the show,[n]as usual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11013]Nah, I get the feeling it's someone[n]older and more mature than[n]Elizabeth...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11050]I know, right? And it felt like it[n]was someone super recent, like[n]just after we got to this theater.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 8 0 1][f 3 1 1 0 0 0]Someone real sexy, real mature,[n]with that kinda sophisticated aura[n]to her...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]We may never know the truth.[n]But as for my speculation on the[n]orchestrator's motives...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I believe she was intrigued by you,[n]and was driven by a desire to better[n]understand you all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Well, I can only hope she got what[n]she wanted out of it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54031]Who can say?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I expect she will continue observing[n]your exploits in the trials to come.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54113]In any case, it was a most entertaining[n]show. Please continue to keep up the[n]good work.[n][f 1 3 65535][f 1 1][e]

