[msg MSG_000 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 18068]So we went right... and that means[n]you pushed the guy onto the tracks.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I guess you stopped the cart, but[n]you stone-cold killed a guy to do it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 3 1 1 0 0 0]But, I mean... this way, we saved[n]five people![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]U-Um... Somehow, that doesn't[n]really make me feel better...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7038]Arrrgh! What the hell is this!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Screw all these carts and tracks[n]and switches! I'm gonna stop the[n]damn thing myself![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]Calm down, Tatsumi-kun. This is[n]all a hypothetical scenario.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 13013]Still, it makes you think.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Just like before, it's a question of[n]sacrificing one life to save five.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However, having to directly push a[n]man to his death makes it feel[n]a bit less... passive.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]I imagine that's the point. Whoever[n]prepared this wanted us to reflect[n]on that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]When faced with a difficult choice,[n]what would go through our minds,[n]and what would we do...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 23009]That kinda creeps me out... It's like[n]they're trying to see into the depths[n]of our hearts.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Still, maybe thinking about these[n]things is what makes us human.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 25 0 0 1][f 3 1 1 0 0 25112]At any rate, we've answered both[n]questions. Shall we make our way[n]to the end?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 18068]So we went left... That means you[n]didn't push the guy onto the tracks.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Which means it kept going, and hit[n]the five workers... Sounds pretty[n]messy.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 3][f 3 1 1 0 0 0]Still, at least the big guy gets to[n]survive.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Otherwise, we would've had to[n]push him onto the tracks[n]ourselves...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I don't know if I could have done it.[n]Even if it'd have saved five people.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 0]If Kanji were there, he could just[n]jump in front of the cart and[n]smack it away![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 3][f 3 1 1 0 0 0]Yeah. He's so tough, that cart[n]wouldn't budge him at all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7072]Hell yeah! All I need is one punch[n]to send it flying![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 8091]I'm not sure the workers would be[n]any better off in that case...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 13013]All joking aside, it is strange.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Just like before, it's a question of[n]sacrificing one life to save five.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However, having to directly push a[n]man to his death makes it feel[n]a bit less... passive.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]I imagine that's the point. Whoever[n]prepared this wanted us to reflect[n]on that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]When faced with a difficult choice,[n]what would go through our minds,[n]and what would we do...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 23009]That kinda creeps me out... It's like[n]they're trying to see into the depths[n]of our hearts.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Still, maybe thinking about these[n]things is what makes us human.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 25 12 0 1][f 3 1 1 0 0 25112]At any rate, we've answered both[n]questions. Shall we make our way[n]to the end?[n][f 1 3 65535][f 1 1][e]

