[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 1][f 3 1 1 0 0 22065]Whoa, what's that!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 3][f 3 1 1 0 0 0]Shh, quiet! Something's happening.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Sonorous voice]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 55029]Hmhm... Hello, and welcome.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]Today, I have a little diversion[n]prepared for you.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]That said, it's nothing too difficult.[n]The rules are quite simple.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]Up ahead, you will see two signs.[n]Each has a question printed on[n]them.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]Please answer the questions, then[n]proceed in accordance with your[n]answers.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]*chuckle* I wonder what you will[n]think, once you see where your[n]answers will lead you?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 1][f 3 1 1 0 0 16020]Is it gone...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 3][f 3 1 1 0 0 0]Who was that? An enemy?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 1][f 3 1 1 0 0 0]Hm. I didn't sense any hostility from[n]them... It seemed like they were[n]just explaining the rules.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 3][f 3 1 1 0 0 12014]So all we have to do is answer[n]questions on signs? We'll have to[n]see the questions first...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]All right, first order of business is to[n]find those signs. Let's go, Joker.[n][f 1 3 65535][f 1 1][e]

