[msg MSG_000 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9041]There we go! One down, one left![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 1 3][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Whew... We actually did it...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]Man, that bear was crazy! Hard to[n]see it as cute when it's trying to[n]rip our faces off...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 0][f 4 6 1 2 0 4][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1077]But no matter how aggressive it is,[n]we still beat it. And we'll beat the[n]next one, too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 14 1 0][f 3 1 1 0 0 9037]Now it's time for the final round![n]Winner takes all! This is for the title[n]of Bear Supreme![n][f 1 3 65535][f 1 1][e]

