[msg MSG_000 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 100 1][f 3 1 1 0 0 14613][f 3 1 6 0 0 500]Okay, everyone. Let's go over the plan[n]one more time, just to be clear.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 0][f 3 1 1 0 0 0]First, we need to get to the spot[n]Elizabeth marked on the map, and[n]capture the music there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19067]We've gotta get it in the music box,[n]right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 100 0][f 3 1 1 0 0 0]Yes, that's right.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_1 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 0][f 3 1 1 0 0 0]After we've captured the music, we[n]have to "reach the theater entrance[n]within 46 steps."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Also, make sure not to use a Goho-M[n]or a Goba-K.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_2 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 100 0][f 3 1 1 0 0 0]If we fail, we have to do it all over[n]again, so we need to be careful.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 6][f 3 1 1 0 0 22069]Okay... Then let's head out and find[n]that music.[n][f 1 3 65535][f 1 1][e]

