[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 54031]These special screenings have been[n]one masterpiece after another...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]As I sit and observe your exploits,[n]I have been consuming popcorn[n]at near-mach speeds.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 3][f 3 1 1 0 0 0]*giggle* Well, I suppose we have[n]completed a fair number of them.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]And now, the time has come once[n]more for a very special screening![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 3][f 3 1 1 0 0 24016]Ah, then... another task that calls[n]for a specific cast.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 0][f 3 1 1 0 0 0]Yes. Exactly correct.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It would seem a vicious new enemy[n]has emerged in the depths of[n]Junessic Land...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Your task will be to slay this Shadow.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Again?[f 2 7 1 64 4 32][e]
[f 0 5 65278][f 2 1]About time.[f 2 7 1 64 12 0][e]

[msg MSG_006 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 100 1][f 3 1 1 0 0 54023]My, I never imagined you would react[n]so grumpily. I hope this sour expression[n]begets sweet results.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 0]Man, this lady won't take no[n]for an answer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 54001]I do appreciate your patience. Indeed,[n]I've been looking forward to this[n]myself.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 6][f 3 1 1 0 0 0]So, does [f 6 1 29 0 0 0]-kun have to fight[n]this one too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 0]Absolutely, undeniably, exactly wrong.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Lo and behold, the ticket for this[n]showing reads: "Cast: [f 6 1 13 0 0 0]."[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 1 10 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1019][f 6 1 2 0 0 4]Me...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]I ask that you ensure [f 6 1 13 0 0 0][n]participates in this battle.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]All right. I'll do what I can.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 6][f 3 1 1 0 0 25015]And once we win against this Shadow?[n]Will we be fighting Theodore again?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Well, I couldn't ruin the surprise waiting[n]behind the proverbial door number[n]two. Please use your imagination.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]First, please focus on bringing your[n]strength to bear against this deadly[n]foe.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54110]Good luck to you all.[n][f 1 3 65535][f 1 1][e]

