[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54031]Everyone, I apologize deeply for the[n]long wait.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've studied that film you discovered,[n]and come up with some theories.[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Let's hear it.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]What did you find out?[f 2 7 1 64 12 0][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 54059]Well, please keep in mind that this[n]is mostly speculation, but...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]In the special screening in question,[n][f 6 1 30 0 0 0] engaged in battle, as[n]requested on its ticket.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The film was left behind by the Shadow[n]defeated by [f 6 1 30 0 0 0]'s might.[n]In other words...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]I hypothesize that his power is[n]directly responsible for the film's[n]appearance.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Which power?[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]I don't get it.[f 2 7 1 64 6 32][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 54056]I refer to your limitless possibilities.[n]What we call the power of the[n]wild card.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 54023]My, have you still not realized?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]I refer to the limitless possibilities[n]slumbering within you. We know it[n]as the power of the wild card.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]And those with the power of the wild[n]card never gain such power without[n]reason.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]In other words, that film is a key―[n]one meant to draw out further[n]possibilities from within you...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 3][f 3 1 1 0 0 28008]Hmm... That seems like a bit of a[n]reach to me, but let's suppose this[n]film actually is a "key" to his power.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007_1 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 30 0 0 0] himself doesn't seem[n]to have changed much... How do you[n]explain that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_008_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]For the sake of answering this query,[n]allow me to offer an idea of my own.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 74 4 100 1][f 3 1 1 0 0 54005][f 6 1 2 0 0 1]Theo! Theo! Come here at once![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Theo! Theooooo! Don't make me[n]get the soybean powder―[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 4 0 3][f 3 1 1 0 0 56034][f 6 1 2 0 0 10]Th-That's enough, Sister![n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 0][f 3 1 1 0 0 0]Even the mere mention of it...[n]I can feel my tongue shriveling,[n]drying into lifeless dust...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 4 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]The hell kinda PTSD is that...?[n]What did she do to you, man?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 6][f 3 1 1 0 0 56021]Goodness! What a pleasant surprise[n]to see you all gathered here.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So, Sister? What did you need of me?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Theo, surely you have not forgotten[n]that you are one who governs power?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0][f 3 1 1 0 0 0]Why, certainly not.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]However I may be dressed, I take[n]pride in performing my duties.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54006]Well then. Have a bout with them[n]right now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 10 0 0][f 3 1 1 0 0 56052]...Huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016_1 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]A bout...? You want me to fight[n][f 6 1 30 0 0 0] and his companions!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Indeed! Naturally, there's no need[n]to hold back.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Of course, I ask the same of you all[n]as well. Please fight as if you wish[n]to kill him.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]This makes no sense.[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]I'm totally lost.[f 2 7 1 64 6 32][e]

[msg MSG_019 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 4 0 6][f 3 1 1 0 0 56032]Yes, this is ridiculous. Look, they're[n]all struggling to keep up with you...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 54084]Oh...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Are you back-sassing me? I didn't know[n]you had such an attitude problem, Theo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]O-Oh, no... Believe me, there was[n]no variety of sass intended...![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 2 0][f 3 1 1 0 0 54027][f 6 1 30 0 0 0], I truly apologize if[n]this suggestion is too sudden or[n]brash...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 80 1 0 0][f 4 6 74 12 100 0][f 3 1 1 0 0 0]However, I believe this battle will[n]bear fruitful results indeed.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]This is but a step to solving the[n]mystery of that film, and delving into[n]the possibilities of the wild card.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]This is for the power of the[n]wild card...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 3][f 3 1 1 0 0 25021][f 6 1 2 0 0 4]How is fighting Theodore going to[n]solve anything?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 0]I shall happily explain further once[n]you've beaten the crap out of Theo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 0][f 3 1 1 0 0 54031][f 6 1 2 0 0 1]Come now, and I shall witness it all![n]Theo VS. everyone! Round 1! FIGHT![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 3][f 3 1 1 0 0 0]Whoa, Zabby's hyped.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 1][f 3 1 1 0 0 56087][f 6 1 2 0 0 9]...Well, I'm sure you know by now.[n]Once my sister seizes on an idea,[n]there is little point resisting.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Would you do as my sister says,[n]and have a bout with me?[n][f 1 3 65535][f 1 1][e]

[sel SEL_028 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Bring it on.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]I'll need a moment.[f 2 7 1 64 6 32][e]

[msg MSG_029 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 56063]Understood.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I shall go prepare myself as well.[n]Let us meet in the Velvet Room.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 56103]Of course. Please speak to me[n]again once you are prepared.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 0][f 3 1 1 0 0 0]Ah, welcome. Are you ready[n]for our bout?[n][f 1 3 65535][f 1 1][e]

[sel SEL_032 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]We're ready.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Not yet.[f 2 7 1 64 6 32][e]

[msg MSG_033 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Understood.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I shall go prepare myself as well.[n]Let us meet in the Velvet Room.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]In that case, please speak to me[n]again once you are prepared.[n][f 1 3 65535][f 1 1][e]

