[msg P4_HERO_FOE_FOLLOW_START]
斡Nos ha visto un FOE!

[msg P4_HERO_FOE_FOLLOW_START_2]
Hay un FOE cerca...

[msg P4_HERO_FOE_FOLLOW_START_3]
斡Cuidado! Es un FOE.

[msg P4_HERO_FOE_NEAR_1]
Hay un FOE cerca.

[msg P4_HERO_FOE_NEAR_2]
Hay un FOE por ah胤.

[msg P4_HERO_FOE_NEAR_3]
Es un FOE... Cuidado.

[msg P4_HERO_FOE_FOLLOW_END_1]
Lo sacudimos...

[msg P4_HERO_FOE_FOLLOW_END_2]
Parece que se rindi吋.

[msg P4_HERO_FOE_FOLLOW_END_3]
Parece que lo perdimos.

[msg P4_HERO_KANSI_REACTION_1]
No deber胤amos meternos con eso...

[msg P4_HERO_KANSI_REACTION_2]
Debemos cuidar nuestros pasos...

[msg P4_HERO_KANSI_REACTION_3]
夷Podremos pasar a trav姻s de eso?

[msg P4_HERO_DENKISAKU_REACTI]
Eso no se ve bien.

[msg P4_HERO_DENKISAKU_REACTI_2]
Una puerta el姻ctrica... No la toques.

[msg P4_HERO_DENKISAKU_REACTI_3]
Tenemos que apagar la energ胤a de[n]alguna manera...

[msg P4_HERO_KYOUHU_REACTION_]
夷Qu姻

[msg P4_HERO_KYOUHU_REACTION__2]
斡Whoa!

[msg P4_HERO_KYOUHU_REACTION__3]
斡Agh!

[msg P4_HERO_STAIR_FIND_1]
Parece que podemos seguir adelante.

[msg P4_HERO_STAIR_FIND_2]
夷Listo para el siguiente zona?

[msg P4_HERO_STAIR_FIND_3]
Podemos seguir adelante. 夷Estamos[n]listos?

[msg P4_HERO_TREASURE_FIND_1]
Un cofre del tesoro... 夷Vas a[n]abrirlo?

[msg P4_HERO_TREASURE_FIND_2]
Veo un cofre del tesoro.

[msg P4_HERO_TREASURE_FIND_3]
Un cofre del tesoro... Me pregunto[n]qu姻 hay dentro.

[msg P4_HERO_CHECK_WALL_1]
夷Qu姻 es eso?

[msg P4_HERO_CHECK_WALL_2]
Hay algo ah胤.

[msg P4_HERO_CHECK_WALL_3]
Algo est茨 aqu胤... Echemos un vistazo[n]m茨s de cerca.

[msg P4_HERO_SWITCH_FIND_1]
Hemos encontrado un interruptor.

[msg P4_HERO_SWITCH_FIND_2]
Hay un interruptor por all胤.

[msg P4_HERO_SWITCH_FIND_3]
Eso es un interruptor.

[msg P4_HERO_SHORTCUT_FIND_1]
Podemos pasar por all胤.

[msg P4_HERO_SHORTCUT_FIND_2]
夷Hm? Eso parece un atajo.

[msg P4_HERO_SHORTCUT_FIND_3]
Mira, podemos usar eso como un atajo.

[msg P4_HERO_PARTY_DEAD_1]
?

[msg P4_HERO_PARTY_DEAD_2]
?

[msg P4_HERO_PARTY_DEAD_3]
?

[msg P4_HERO_FOE_WARNING_NEAR]
Un FOE se dirige a nosotros.

[msg P4_HERO_FOE_WARNING_NEAR_2]
Es un FOE. Mantente en guardia.

[msg P4_HERO_FOE_WARNING_NEAR_3]
Hay un FOE detr茨s de nosotros.

[msg P4_HERO_PARTY_HPTP10_1]
■ CONTRASE謂A

[msg P4_HERO_PARTY_HPTP10_2]
■ CONTRASE謂A

[msg P4_HERO_PARTY_HPTP10_3]
■ CONTRASE謂A

[msg P4_HERO_PARTY_HP10_1]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg P4_HERO_PARTY_HP10_2]
◆CONT威CTELO 10% DE LA VISTA

[msg P4_HERO_PARTY_HP10_3]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg P4_HERO_1PERSON_HPTP10_1]
Ngh... Quiz茨s deber胤amos descansar.

[msg P4_HERO_1PERSON_HPTP10_2]
Uf... Me vendr胤a bien un descanso...

[msg P4_HERO_1PERSON_HPTP10_3]
No me encuentro muy bien...

[msg P4_HERO_PARTY_TP10_1]
■ CONTRASE謂A

[msg P4_HERO_PARTY_TP10_2]
■ CONTRASE謂A

[msg P4_HERO_PARTY_TP10_3]
■ CONTRASE謂A

[msg P4_HERO_1PERSON_HP10_1]
Estoy herido...

[msg P4_HERO_1PERSON_HP10_2]
Estoy en las 雨ltimas...

[msg P4_HERO_1PERSON_HP10_3]
Siento que voy a colapsar...

[msg P4_HERO_1PERSON_TP10_1]
Lo siento, no tengo energ胤a...

[msg P4_HERO_1PERSON_TP10_2]
Uf... Esto es dif胤cil...

[msg P4_HERO_1PERSON_TP10_3]
No es bueno... Estoy sin energ胤as...

[msg P4_HERO_ITEM_90_BATTLE_1]
【justificadamente

[msg P4_HERO_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg P4_HERO_ITEM_90_BATTLE_3]
【justificadamente

[msg P4_HERO_1PERSON_HP80_1]
Todav胤a estamos en forma.

[msg P4_HERO_1PERSON_HP80_2]
No hay problema.

[msg P4_HERO_1PERSON_HP80_3]
Mantengamos el ritmo.

[msg P4_HERO_BATTLE_CHANGE_DU]
■: [f 0 1 4]\cHFF

[msg P4_HERO_BATTLE_CHANGE_DU_2]
■: [f 0 1 4]\cHFF

[msg P4_HERO_BATTLE_CHANGE_DU_3]
■:

[msg P4_HERO_ITEM_90_DUNGEON_]
(DGP郁BLICA)

[msg P4_HERO_ITEM_90_DUNGEON__2]
(DGP郁BLICA)

[msg P4_HERO_ITEM_90_DUNGEON__3]
(DGP郁BLICA)

[msg P4_HERO_DUNGEON_START_1]
Permanezcamos en guardia.

[msg P4_HERO_DUNGEON_START_2]
No he olvidado nada, 夷verdad?

[msg P4_HERO_DUNGEON_START_3]
Si parece peligroso, siempre podemos[n]retroceder.

[msg P4_HERO_QUEST_START_1]
Empecemos.

[msg P4_HERO_QUEST_START_2]
Vamos juntos hasta el final.

[msg P4_HERO_QUEST_START_3]
Vamos, chicos.

[msg P4_HERO_TOUHA_25_1]
Creo que estoy empezando a sentir[n]este piso...

[msg P4_HERO_TOUHA_25_2]
Todav胤a hay mucho terreno que cubrir.

[msg P4_HERO_TOUHA_50_1]
Supongo que estamos a mitad de camino[n].

[msg P4_HERO_TOUHA_50_2]
El mapa est茨 tomando forma[n]lentamente.

[msg P4_HERO_TOUHA_75_1]
Uf... hemos recorrido un largo[n]camino.

[msg P4_HERO_TOUHA_75_2]
Un poco m茨s, y este piso ser茨[n]nuestro.

[msg P4_HERO_TOUHA_100_1]
Hemos visto todo lo que hay que ver[n]por aqu胤.

[msg P4_HERO_TOUHA_100_2]
Bien. Este piso est茨 hecho.

[msg P4_HERO_MAPPING_ICON_ALL]
Buena colocaci吋n.

[msg P4_HERO_MAPPING_ICON_ALL_2]
Eso nos vendr茨 bien.

[msg P4_HERO_MAPPING_ICON_KAI]
Se ve bien.

[msg P4_HERO_MAPPING_ICON_KAI_2]
Eso har茨 m茨s f茨cil moverse.

[msg P4_HERO_MAPPING_CHANGE_C]
夷Un favorito tuyo?

[msg P4_HERO_MAPPING_CHANGE_C_2]
Elegante.

[msg P4_HERO_MAPPING_ICON_DEL]
Buena elecci吋n.

[msg P4_HERO_MAPPING_ICON_DEL_2]
A veces tambi姻n tienes que borrar[n]cosas.

[msg P4_HERO_MAPPING_MEMO_1]
S胤, guardar notas puede ser 雨til.

[msg P4_HERO_MAPPING_MEMO_2]
Buena idea. Ahora no lo olvidaremos.

[msg P4_HERO_DOOR_OPEN_1]
斡Por aqu胤!

[msg P4_HERO_DOOR_OPEN_2]
Muy bien, vamos.

[msg P4_HERO_DOOR_OPEN_3]
Sigamos.

[msg P4_HERO_KARITORU_ENCOUNT]
? ? Todav胤a no hay nada que ver

[msg P4_HERO_KARITORU_ENCOUNT_2]
? ? Todav胤a no hay nada que ver

[msg P4_HERO_KARITORU_ENCOUNT_3]
? ? Todav胤a no hay 姻xito

