[msg SANADA_FOE_FOLLOW_START_]
Parece que un FOE nos sigue...

[msg SANADA_FOE_FOLLOW_START__2]
Un FOE... 夷Deber胤amos luchar?

[msg SANADA_FOE_FOLLOW_START__3]
Un FOE viene tras nosotros...

[msg SANADA_FOE_NEAR_1]
Un FOE est茨 cerca... Cuidado.

[msg SANADA_FOE_NEAR_2]
Conozco esa sensaci吋n... Es un FOE.

[msg SANADA_FOE_NEAR_3]
斡Un FOE!

[msg SANADA_FOE_FOLLOW_END_1]
Parece que ya no nos sigue...

[msg SANADA_FOE_FOLLOW_END_2]
夷Ya se rindi吋? Jaj茨. Pensar胤as que[n]tendr胤a m茨s agallas.

[msg SANADA_FOE_FOLLOW_END_3]
夷No vamos a luchar? Es una pena.

[msg SANADA_KANSI_REACTION_1]
Ser茨 mejor que seamos cautelosos.

[msg SANADA_KANSI_REACTION_2]
Si nos atrapan, entonces lucharemos.

[msg SANADA_KANSI_REACTION_3]
La sigilo no es usualmente mi[n]estilo...

[msg SANADA_DENKISAKU_REACTIO]
Una puerta el姻ctrica... Tendremos que[n]rodearla.

[msg SANADA_DENKISAKU_REACTIO_2]
Sin dolor, sin ganancia, supongo...[n]Pero esto no es bueno.

[msg SANADA_DENKISAKU_REACTIO_3]
Odio estas trampas.

[msg SANADA_KYOUHU_REACTION_1]
斡Agh, maldici吋n!

[msg SANADA_KYOUHU_REACTION_2]
夷Qu姻...

[msg SANADA_KYOUHU_REACTION_3]
斡Whoa!

[msg SANADA_STAIR_FIND_1]
Escaleras... Vamos.

[msg SANADA_STAIR_FIND_2]
Veamos qu姻 tipo de desaf胤os nos[n]esperan...

[msg SANADA_STAIR_FIND_3]
Parece que podemos seguir yendo por[n]all胤.

[msg SANADA_TREASURE_FIND_1]
Un cofre del tesoro.

[msg SANADA_TREASURE_FIND_2]
Un cofre del tesoro... 夷Quieres[n]abrirlo?

[msg SANADA_TREASURE_FIND_3]
Me pregunto qu姻 hay dentro... 夷Crees[n]que es prote胤na?

[msg SANADA_CHECK_WALL_1]
Parece extra隠o. Vamos a comprobarlo.

[msg SANADA_CHECK_WALL_2]
Hay algo ah胤... Me pregunto qu姻 es.

[msg SANADA_CHECK_WALL_3]
夷Qu姻 es eso? 夷Deber胤amos revisar?

[msg SANADA_SWITCH_FIND_1]
Un interruptor... 夷Alguna idea de lo[n]que hace?

[msg SANADA_SWITCH_FIND_2]
Parece que es un interruptor. 夷Qu姻[n]vamos a hacer?

[msg SANADA_SWITCH_FIND_3]
夷Lo presionamos?

[msg SANADA_SHORTCUT_FIND_1]
Creo que podemos pasar por esto.

[msg SANADA_SHORTCUT_FIND_2]
Parece que podemos tomar un atajo.

[msg SANADA_SHORTCUT_FIND_3]
Un atajo... Vamos.

[msg SANADA_PARTY_DEAD_1]
?

[msg SANADA_PARTY_DEAD_2]
?

[msg SANADA_PARTY_DEAD_3]
?

[msg SANADA_FOE_WARNING_NEAR_]
斡No ha terminado todav胤a!

[msg SANADA_FOE_WARNING_NEAR__2]
夷Ves ese FOE...? Todav胤a nos sigue.

[msg SANADA_FOE_WARNING_NEAR__3]
夷Un FOE? Bueno, estoy calentado.

[msg SANADA_PARTY_HPTP10_1]
■ CONTRASE謂A

[msg SANADA_PARTY_HPTP10_2]
■ CONTRASE謂A

[msg SANADA_PARTY_HPTP10_3]
■ CONTRASE謂A

[msg SANADA_PARTY_HP10_1]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg SANADA_PARTY_HP10_2]
◆CONT威CTELO 10% DE LA VISTA

[msg SANADA_PARTY_HP10_3]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg SANADA_1PERSON_HPTP10_1]
夷Fue eso una... campana de ring...?

[msg SANADA_1PERSON_HPTP10_2]
Tal vez tenga que rendirme...

[msg SANADA_1PERSON_HPTP10_3]
Ngh... hah... 夷Es esto tan lejos como[n]puedo llegar...?

[msg SANADA_PARTY_TP10_1]
■ CONTRASE謂A

[msg SANADA_PARTY_TP10_2]
■ CONTRASE謂A

[msg SANADA_PARTY_TP10_3]
■ CONTRASE謂A

[msg SANADA_1PERSON_HP10_1]
A este ritmo, ser姻 noqueado...[n]Necesito curaci吋n.

[msg SANADA_1PERSON_HP10_2]
Pens姻 que tenia buena resistencia...

[msg SANADA_1PERSON_HP10_3]
Esto se est茨 poniendo mal... 夷Alguien[n]puede curarme?

[msg SANADA_1PERSON_TP10_1]
斡Maldici吋n! 斡Mi cuerpo no me hace[n]caso!

[msg SANADA_1PERSON_TP10_2]
No puedo ser noqueado ahora... 斡No[n]aqu胤!

[msg SANADA_1PERSON_TP10_3]
Uf... hah... Ugh, soy pat姻tico...

[msg SANADA_ITEM_90_BATTLE_1]
【justificadamente

[msg SANADA_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg SANADA_ITEM_90_BATTLE_3]
【justificadamente

[msg SANADA_1PERSON_HP80_1]
Esto ni siquiera ser茨 suficiente para[n]calentar.

[msg SANADA_1PERSON_HP80_2]
Prefiero luchar contra alguien m茨s[n]fuerte.

[msg SANADA_1PERSON_HP80_3]
斡Buenas t茨cticas! 斡Lo hicimos!

[msg SANADA_BATTLE_CHANGE_DUN]
■ト [f 0 1 4]\cHFF

[msg SANADA_BATTLE_CHANGE_DUN_2]
■ト [f 0 1 4]\cHFF

[msg SANADA_BATTLE_CHANGE_DUN_3]
■ト

[msg SANADA_ITEM_90_DUNGEON_1]
(DGP郁BLICA)

[msg SANADA_ITEM_90_DUNGEON_2]
(DGP郁BLICA)

[msg SANADA_ITEM_90_DUNGEON_3]
(DGP郁BLICA)

[msg SANADA_DUNGEON_START_1]
Muy bien, vamos.

[msg SANADA_DUNGEON_START_2]
Estoy listo. Hag茨moslo.

[msg SANADA_DUNGEON_START_3]
Ap雨rate. Tengo que seguir en modo[n]entrenamiento.

[msg SANADA_QUEST_START_1]
夷D吋nde est茨 el objetivo? Terminemos[n]esto.

[msg SANADA_QUEST_START_2]
Esto es perfecto para el[n]entrenamiento.

[msg SANADA_QUEST_START_3]
Es hora de ver cu茨n fuerte me he[n]vuelto.

[msg SANADA_TOUHA_25_1]
夷Puede este piso ser m茨s grande...?

[msg SANADA_TOUHA_25_2]
Apenas estamos empezando. Todos[n]mantengan los ojos abiertos.

[msg SANADA_TOUHA_50_1]
夷Estamos cerca de la mitad?

[msg SANADA_TOUHA_50_2]
Casi a mitad de camino. 夷C吋mo est茨n[n]todos?

[msg SANADA_TOUHA_75_1]
Estamos a punto de terminar con este[n]piso.

[msg SANADA_TOUHA_75_2]
夷Est茨s cansado? Toma una prote胤na.

[msg SANADA_TOUHA_100_1]
斡Mantengamos el ritmo!

[msg SANADA_TOUHA_100_2]
斡Eso fue un buen entrenamiento!

[msg SANADA_MAPPING_ICON_ALL_]
S胤, eso parece correcto.

[msg SANADA_MAPPING_ICON_ALL__2]
Es un trabajo detallado. Estoy[n]impresionado.

[msg SANADA_MAPPING_ICON_KAID]
Fue definitivamente en ese lugar.

[msg SANADA_MAPPING_ICON_KAID_2]
Hm. As胤 es como lo recuerdo.

[msg SANADA_MAPPING_CHANGE_CO]
Es un alivio verlo tan organizado.

[msg SANADA_MAPPING_CHANGE_CO_2]
Oh, huh. Eso lo hace bastante claro.

[msg SANADA_MAPPING_ICON_DEL_]
夷Desech茨ndolo, eh?

[msg SANADA_MAPPING_ICON_DEL__2]
No hay nada de malo en deshacerse del[n]peso muerto.

[msg SANADA_MAPPING_MEMO_1]
Ahora no lo olvidaremos.

[msg SANADA_MAPPING_MEMO_2]
夷Quieres que incluya nuestro programa[n]de entrenamiento?

[msg SANADA_DOOR_OPEN_1]
Por aqu胤.

[msg SANADA_DOOR_OPEN_2]
Vamos.

[msg SANADA_DOOR_OPEN_3]
Hah. No puedo esperar...

[msg SANADA_KARITORU_ENCOUNT_]
? ? Todav胤a no hay nada que ver

[msg SANADA_KARITORU_ENCOUNT__2]
? ? Todav胤a no hay nada que ver

[msg SANADA_KARITORU_ENCOUNT__3]
? ? Todav胤a no hay 姻xito

