[msg P4_HERO_FOE_FOLLOW_START]
ムNos ha visto un FOE!

[msg P4_HERO_FOE_FOLLOW_START_2]
Hay un FOE cerca...

[msg P4_HERO_FOE_FOLLOW_START_3]
ムCuidado! Es un FOE.

[msg P4_HERO_FOE_NEAR_1]
Hay un FOE cerca.

[msg P4_HERO_FOE_NEAR_2]
Hay un FOE por ahボ.

[msg P4_HERO_FOE_NEAR_3]
Es un FOE... Cuidado.

[msg P4_HERO_FOE_FOLLOW_END_1]
Lo sacudimos...

[msg P4_HERO_FOE_FOLLOW_END_2]
Parece que se rindiポ.

[msg P4_HERO_FOE_FOLLOW_END_3]
Parece que lo perdimos.

[msg P4_HERO_KANSI_REACTION_1]
No deberボamos meternos con eso...

[msg P4_HERO_KANSI_REACTION_2]
Debemos cuidar nuestros pasos...

[msg P4_HERO_KANSI_REACTION_3]
メPodremos pasar a trav〒s de eso?

[msg P4_HERO_DENKISAKU_REACTI]
Eso no se ve bien.

[msg P4_HERO_DENKISAKU_REACTI_2]
Una puerta el〒ctrica... No la toques.

[msg P4_HERO_DENKISAKU_REACTI_3]
Tenemos que apagar la energボa de[n]alguna manera...

[msg P4_HERO_KYOUHU_REACTION_]
メQu〒

[msg P4_HERO_KYOUHU_REACTION__2]
ムWhoa!

[msg P4_HERO_KYOUHU_REACTION__3]
ムAgh!

[msg P4_HERO_STAIR_FIND_1]
Parece que podemos seguir adelante.

[msg P4_HERO_STAIR_FIND_2]
メListo para el siguiente zona?

[msg P4_HERO_STAIR_FIND_3]
Podemos seguir adelante. メEstamos[n]listos?

[msg P4_HERO_TREASURE_FIND_1]
Un cofre del tesoro... メVas a[n]abrirlo?

[msg P4_HERO_TREASURE_FIND_2]
Veo un cofre del tesoro.

[msg P4_HERO_TREASURE_FIND_3]
Un cofre del tesoro... Me pregunto[n]qu〒 hay dentro.

[msg P4_HERO_CHECK_WALL_1]
メQu〒 es eso?

[msg P4_HERO_CHECK_WALL_2]
Hay algo ahボ.

[msg P4_HERO_CHECK_WALL_3]
Algo estホ aquボ... Echemos un vistazo[n]mホs de cerca.

[msg P4_HERO_SWITCH_FIND_1]
Hemos encontrado un interruptor.

[msg P4_HERO_SWITCH_FIND_2]
Hay un interruptor por allボ.

[msg P4_HERO_SWITCH_FIND_3]
Eso es un interruptor.

[msg P4_HERO_SHORTCUT_FIND_1]
Podemos pasar por allボ.

[msg P4_HERO_SHORTCUT_FIND_2]
メHm? Eso parece un atajo.

[msg P4_HERO_SHORTCUT_FIND_3]
Mira, podemos usar eso como un atajo.

[msg P4_HERO_PARTY_DEAD_1]
?

[msg P4_HERO_PARTY_DEAD_2]
?

[msg P4_HERO_PARTY_DEAD_3]
?

[msg P4_HERO_FOE_WARNING_NEAR]
Un FOE se dirige a nosotros.

[msg P4_HERO_FOE_WARNING_NEAR_2]
Es un FOE. Mantente en guardia.

[msg P4_HERO_FOE_WARNING_NEAR_3]
Hay un FOE detrホs de nosotros.

[msg P4_HERO_PARTY_HPTP10_1]
■ CONTRASEヰA

[msg P4_HERO_PARTY_HPTP10_2]
■ CONTRASEヰA

[msg P4_HERO_PARTY_HPTP10_3]
■ CONTRASEヰA

[msg P4_HERO_PARTY_HP10_1]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg P4_HERO_PARTY_HP10_2]
◆CONTミCTELO 10% DE LA VISTA

[msg P4_HERO_PARTY_HP10_3]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg P4_HERO_1PERSON_HPTP10_1]
Ngh... Quizホs deberボamos descansar.

[msg P4_HERO_1PERSON_HPTP10_2]
Uf... Me vendrボa bien un descanso...

[msg P4_HERO_1PERSON_HPTP10_3]
No me encuentro muy bien...

[msg P4_HERO_PARTY_TP10_1]
■ CONTRASEヰA

[msg P4_HERO_PARTY_TP10_2]
■ CONTRASEヰA

[msg P4_HERO_PARTY_TP10_3]
■ CONTRASEヰA

[msg P4_HERO_1PERSON_HP10_1]
Estoy herido...

[msg P4_HERO_1PERSON_HP10_2]
Estoy en las マltimas...

[msg P4_HERO_1PERSON_HP10_3]
Siento que voy a colapsar...

[msg P4_HERO_1PERSON_TP10_1]
Lo siento, no tengo energボa...

[msg P4_HERO_1PERSON_TP10_2]
Uf... Esto es difボcil...

[msg P4_HERO_1PERSON_TP10_3]
No es bueno... Estoy sin energボas...

[msg P4_HERO_ITEM_90_BATTLE_1]
【justificadamente

[msg P4_HERO_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg P4_HERO_ITEM_90_BATTLE_3]
【justificadamente

[msg P4_HERO_1PERSON_HP80_1]
Todavボa estamos en forma.

[msg P4_HERO_1PERSON_HP80_2]
No hay problema.

[msg P4_HERO_1PERSON_HP80_3]
Mantengamos el ritmo.

[msg P4_HERO_BATTLE_CHANGE_DU]
■: [f 0 1 4]\cHFF

[msg P4_HERO_BATTLE_CHANGE_DU_2]
■: [f 0 1 4]\cHFF

[msg P4_HERO_BATTLE_CHANGE_DU_3]
■:

[msg P4_HERO_ITEM_90_DUNGEON_]
(DGPヮBLICA)

[msg P4_HERO_ITEM_90_DUNGEON__2]
(DGPヮBLICA)

[msg P4_HERO_ITEM_90_DUNGEON__3]
(DGPヮBLICA)

[msg P4_HERO_DUNGEON_START_1]
Permanezcamos en guardia.

[msg P4_HERO_DUNGEON_START_2]
No he olvidado nada, メverdad?

[msg P4_HERO_DUNGEON_START_3]
Si parece peligroso, siempre podemos[n]retroceder.

[msg P4_HERO_QUEST_START_1]
Empecemos.

[msg P4_HERO_QUEST_START_2]
Vamos juntos hasta el final.

[msg P4_HERO_QUEST_START_3]
Vamos, chicos.

[msg P4_HERO_TOUHA_25_1]
Creo que estoy empezando a sentir[n]este piso...

[msg P4_HERO_TOUHA_25_2]
Todavボa hay mucho terreno que cubrir.

[msg P4_HERO_TOUHA_50_1]
Supongo que estamos a mitad de camino[n].

[msg P4_HERO_TOUHA_50_2]
El mapa estホ tomando forma[n]lentamente.

[msg P4_HERO_TOUHA_75_1]
Uf... hemos recorrido un largo[n]camino.

[msg P4_HERO_TOUHA_75_2]
Un poco mホs, y este piso serホ[n]nuestro.

[msg P4_HERO_TOUHA_100_1]
Hemos visto todo lo que hay que ver[n]por aquボ.

[msg P4_HERO_TOUHA_100_2]
Bien. Este piso estホ hecho.

[msg P4_HERO_MAPPING_ICON_ALL]
Buena colocaciポn.

[msg P4_HERO_MAPPING_ICON_ALL_2]
Eso nos vendrホ bien.

[msg P4_HERO_MAPPING_ICON_KAI]
Se ve bien.

[msg P4_HERO_MAPPING_ICON_KAI_2]
Eso harホ mホs fホcil moverse.

[msg P4_HERO_MAPPING_CHANGE_C]
メUn favorito tuyo?

[msg P4_HERO_MAPPING_CHANGE_C_2]
Elegante.

[msg P4_HERO_MAPPING_ICON_DEL]
Buena elecciポn.

[msg P4_HERO_MAPPING_ICON_DEL_2]
A veces tambi〒n tienes que borrar[n]cosas.

[msg P4_HERO_MAPPING_MEMO_1]
Sボ, guardar notas puede ser マtil.

[msg P4_HERO_MAPPING_MEMO_2]
Buena idea. Ahora no lo olvidaremos.

[msg P4_HERO_DOOR_OPEN_1]
ムPor aquボ!

[msg P4_HERO_DOOR_OPEN_2]
Muy bien, vamos.

[msg P4_HERO_DOOR_OPEN_3]
Sigamos.

[msg P4_HERO_KARITORU_ENCOUNT]
? ? Todavボa no hay nada que ver

[msg P4_HERO_KARITORU_ENCOUNT_2]
? ? Todavボa no hay nada que ver

[msg P4_HERO_KARITORU_ENCOUNT_3]
? ? Todavボa no hay 〒xito

