[msg YUKIKO_FOE_FOLLOW_START_]
ムParece que el FOE nos persigue!

[msg YUKIKO_FOE_FOLLOW_START__2]
ムEs el FOE! ムCuidado!

[msg YUKIKO_FOE_FOLLOW_START__3]
ムUn FOE se acerca hacia nosotros!

[msg YUKIKO_FOE_NEAR_1]
ムEs un FOE! ムCuidado!

[msg YUKIKO_FOE_NEAR_2]
Un FOE estホ cerca. Deberボamos tener[n]cuidado.

[msg YUKIKO_FOE_NEAR_3]
メNo es el FOE?

[msg YUKIKO_FOE_FOLLOW_END_1]
Parece que se dio por vencido.

[msg YUKIKO_FOE_FOLLOW_END_2]
Gracias a dios que logramos escapar.

[msg YUKIKO_FOE_FOLLOW_END_3]
Uf... Se fue.

[msg YUKIKO_KANSI_REACTION_1]
Silenciosa... Silenciosa...

[msg YUKIKO_KANSI_REACTION_2]
Esto es bastante estresante.

[msg YUKIKO_KANSI_REACTION_3]
Debemos tener cuidado de no ser[n]atrapados.

[msg YUKIKO_DENKISAKU_REACTIO]
Esta trampa estホ resultando ser un[n]obstホculo bastante grande.

[msg YUKIKO_DENKISAKU_REACTIO_2]
メNo podrボamos destruir esta puerta?

[msg YUKIKO_DENKISAKU_REACTIO_3]
Serボa mucho mホs fホcil si pudiera[n]quemar esto...

[msg YUKIKO_KYOUHU_REACTION_1]
ムJa, ja, ja!

[msg YUKIKO_KYOUHU_REACTION_2]
ムメEh?!

[msg YUKIKO_KYOUHU_REACTION_3]
ムWhoa!

[msg YUKIKO_STAIR_FIND_1]
メCrees que podemos seguir desde aquボ?

[msg YUKIKO_STAIR_FIND_2]
Parece que podemos ir al siguiente[n]piso.

[msg YUKIKO_STAIR_FIND_3]
Creo que podemos seguir adelante.[n]メPor qu〒 no lo intentamos?

[msg YUKIKO_TREASURE_FIND_1]
ムMira, es un tesoro!

[msg YUKIKO_TREASURE_FIND_2]
Es un tesoro. メDeberボamos abrirlo?

[msg YUKIKO_TREASURE_FIND_3]
Me pregunto qu〒 hay dentro.

[msg YUKIKO_CHECK_WALL_1]
Oh, ムMira por ahボ!

[msg YUKIKO_CHECK_WALL_2]
Hmm... siento que hay algo aquボ.

[msg YUKIKO_CHECK_WALL_3]
メPor qu〒 no echamos un vistazo por[n]aquボ?

[msg YUKIKO_SWITCH_FIND_1]
Oh, un interruptor.

[msg YUKIKO_SWITCH_FIND_2]
Vamos a tener que presionar el[n]interruptor, メno?

[msg YUKIKO_SWITCH_FIND_3]
メNo parece un interruptor?

[msg YUKIKO_SHORTCUT_FIND_1]
Creo que podemos pasar por allボ.

[msg YUKIKO_SHORTCUT_FIND_2]
メCrees que podemos usar eso como un[n]atajo?

[msg YUKIKO_SHORTCUT_FIND_3]
Creo que podemos pasar por ahボ.

[msg YUKIKO_PARTY_DEAD_1]
?

[msg YUKIKO_PARTY_DEAD_2]
?

[msg YUKIKO_PARTY_DEAD_3]
?

[msg YUKIKO_FOE_WARNING_NEAR_]
ムEl FOE todavボa se acerca!

[msg YUKIKO_FOE_WARNING_NEAR__2]
Nos siguen. Tengamos cuidado.

[msg YUKIKO_FOE_WARNING_NEAR__3]
ムEl FOE todavボa nos persigue!

[msg YUKIKO_PARTY_HPTP10_1]
■ CONTRASEヰA

[msg YUKIKO_PARTY_HPTP10_2]
■ CONTRASEヰA

[msg YUKIKO_PARTY_HPTP10_3]
■ CONTRASEヰA

[msg YUKIKO_PARTY_HP10_1]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg YUKIKO_PARTY_HP10_2]
◆CONTミCTELO 10% DE LA VISTA

[msg YUKIKO_PARTY_HP10_3]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg YUKIKO_1PERSON_HPTP10_1]
Lo siento, no puedo seguir...

[msg YUKIKO_1PERSON_HPTP10_2]
Esto no es bueno. Creo que estoy en[n]mi lボmite...

[msg YUKIKO_1PERSON_HPTP10_3]
メCrees que podrボamos tomar un[n]descanso...?

[msg YUKIKO_PARTY_TP10_1]
■ CONTRASEヰA

[msg YUKIKO_PARTY_TP10_2]
■ CONTRASEヰA

[msg YUKIKO_PARTY_TP10_3]
■ CONTRASEヰA

[msg YUKIKO_1PERSON_HP10_1]
Alguien, por favor, cマreme...

[msg YUKIKO_1PERSON_HP10_2]
Mi salud estホ muy baja...

[msg YUKIKO_1PERSON_HP10_3]
Por favor, alguien me cura...

[msg YUKIKO_1PERSON_TP10_1]
Nnh... no creo que tenga mホs[n]energボa...

[msg YUKIKO_1PERSON_TP10_2]
Me estoy cansando...

[msg YUKIKO_1PERSON_TP10_3]
No sirve de nada... no creo que pueda[n]moverme ni un centボmetro mホs...

[msg YUKIKO_ITEM_90_BATTLE_1]
【justificadamente

[msg YUKIKO_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg YUKIKO_ITEM_90_BATTLE_3]
【justificadamente

[msg YUKIKO_1PERSON_HP80_1]
ムJeje! ムEsto no es nada para[n]nosotros!

[msg YUKIKO_1PERSON_HP80_2]
Puedo seguir. D〒jamelo a mボ.

[msg YUKIKO_1PERSON_HP80_3]
Creo que podemos mantener el ritmo.

[msg YUKIKO_BATTLE_CHANGE_DUN]
■: [f 0 1 4]\cHFF

[msg YUKIKO_BATTLE_CHANGE_DUN_2]
■: [f 0 1 4]\cHFF

[msg YUKIKO_BATTLE_CHANGE_DUN_3]
■:

[msg YUKIKO_ITEM_90_DUNGEON_1]
(DGPヮBLICA)

[msg YUKIKO_ITEM_90_DUNGEON_2]
(DGPヮBLICA)

[msg YUKIKO_ITEM_90_DUNGEON_3]
(DGPヮBLICA)

[msg YUKIKO_DUNGEON_START_1]
No se arriesguen demasiado.

[msg YUKIKO_DUNGEON_START_2]
No olvidamos nada, メverdad?

[msg YUKIKO_DUNGEON_START_3]
Deberボamos estar preparados para[n]cualquier cosa.

[msg YUKIKO_QUEST_START_1]
Hagamos todo lo posible para tener[n]〒xito.

[msg YUKIKO_QUEST_START_2]
ムVamos con cuidado!

[msg YUKIKO_QUEST_START_3]
No te preocupes, estoy segura de que[n]podemos hacerlo.

[msg YUKIKO_TOUHA_25_1]
Siento que todavボa tenemos mucho mホs[n]por explorar...

[msg YUKIKO_TOUHA_25_2]
Todavボa nos queda camino por recorrer, pero[n]sigamos haciendo lo mejor que podamos.

[msg YUKIKO_TOUHA_50_1]
Creo que estamos a mitad de camino.

[msg YUKIKO_TOUHA_50_2]
Mm, estamos en racha. ムSigamos asボ!

[msg YUKIKO_TOUHA_75_1]
Uf... Hemos caminado bastante.

[msg YUKIKO_TOUHA_75_2]
Solo un poco mホs y este piso estarホ[n]terminado.

[msg YUKIKO_TOUHA_100_1]
Hemos recorrido cada parte de este[n]piso. Bien hecho.

[msg YUKIKO_TOUHA_100_2]
ムHemos recorrido cada parte de este[n]piso!

[msg YUKIKO_MAPPING_ICON_ALL_]
El mapa se ve realmente bien,[n]gracias.

[msg YUKIKO_MAPPING_ICON_ALL__2]
Wow, ムEste mapa es muy preciso!

[msg YUKIKO_MAPPING_ICON_KAID]
Estoy segura de que serホ マtil si[n]sabemos dポnde estホn las escaleras.

[msg YUKIKO_MAPPING_ICON_KAID_2]
Es bueno marcar puntos de inter〒s.

[msg YUKIKO_MAPPING_CHANGE_CO]
Ah, メUsarホs ese color?

[msg YUKIKO_MAPPING_CHANGE_CO_2]
Tienes un ojo agudo para el arte. Tal[n]vez yo tambi〒n lo intente.

[msg YUKIKO_MAPPING_ICON_DEL_]
Es mejor tirar cosas que no[n]necesitamos.

[msg YUKIKO_MAPPING_ICON_DEL__2]
Mmhm, mucho mホs limpio ahora.

[msg YUKIKO_MAPPING_MEMO_1]
Es importante tomar notas.

[msg YUKIKO_MAPPING_MEMO_2]
Asegマrate de escribirlo para que no[n]se te olvide.

[msg YUKIKO_DOOR_OPEN_1]
Supongo que vamos por este camino.

[msg YUKIKO_DOOR_OPEN_2]
Sigamos.

[msg YUKIKO_DOOR_OPEN_3]
メQu〒 crees que hay al otro lado?

[msg YUKIKO_KARITORU_ENCOUNT_]
? ? Todavボa no hay nada que ver

[msg YUKIKO_KARITORU_ENCOUNT__2]
? ? Todavボa no hay nada que ver

[msg YUKIKO_KARITORU_ENCOUNT__3]
? ? Todavボa no hay 〒xito

