[msg YUKIKO_FOE_FOLLOW_START_]
斡Parece que el FOE nos persigue!

[msg YUKIKO_FOE_FOLLOW_START__2]
斡Es el FOE! 斡Cuidado!

[msg YUKIKO_FOE_FOLLOW_START__3]
斡Un FOE se acerca hacia nosotros!

[msg YUKIKO_FOE_NEAR_1]
斡Es un FOE! 斡Cuidado!

[msg YUKIKO_FOE_NEAR_2]
Un FOE est茨 cerca. Deber胤amos tener[n]cuidado.

[msg YUKIKO_FOE_NEAR_3]
夷No es el FOE?

[msg YUKIKO_FOE_FOLLOW_END_1]
Parece que se dio por vencido.

[msg YUKIKO_FOE_FOLLOW_END_2]
Gracias a dios que logramos escapar.

[msg YUKIKO_FOE_FOLLOW_END_3]
Uf... Se fue.

[msg YUKIKO_KANSI_REACTION_1]
Silenciosa... Silenciosa...

[msg YUKIKO_KANSI_REACTION_2]
Esto es bastante estresante.

[msg YUKIKO_KANSI_REACTION_3]
Debemos tener cuidado de no ser[n]atrapados.

[msg YUKIKO_DENKISAKU_REACTIO]
Esta trampa est茨 resultando ser un[n]obst茨culo bastante grande.

[msg YUKIKO_DENKISAKU_REACTIO_2]
夷No podr胤amos destruir esta puerta?

[msg YUKIKO_DENKISAKU_REACTIO_3]
Ser胤a mucho m茨s f茨cil si pudiera[n]quemar esto...

[msg YUKIKO_KYOUHU_REACTION_1]
斡Ja, ja, ja!

[msg YUKIKO_KYOUHU_REACTION_2]
斡夷Eh?!

[msg YUKIKO_KYOUHU_REACTION_3]
斡Whoa!

[msg YUKIKO_STAIR_FIND_1]
夷Crees que podemos seguir desde aqu胤?

[msg YUKIKO_STAIR_FIND_2]
Parece que podemos ir al siguiente[n]piso.

[msg YUKIKO_STAIR_FIND_3]
Creo que podemos seguir adelante.[n]夷Por qu姻 no lo intentamos?

[msg YUKIKO_TREASURE_FIND_1]
斡Mira, es un tesoro!

[msg YUKIKO_TREASURE_FIND_2]
Es un tesoro. 夷Deber胤amos abrirlo?

[msg YUKIKO_TREASURE_FIND_3]
Me pregunto qu姻 hay dentro.

[msg YUKIKO_CHECK_WALL_1]
Oh, 斡Mira por ah胤!

[msg YUKIKO_CHECK_WALL_2]
Hmm... siento que hay algo aqu胤.

[msg YUKIKO_CHECK_WALL_3]
夷Por qu姻 no echamos un vistazo por[n]aqu胤?

[msg YUKIKO_SWITCH_FIND_1]
Oh, un interruptor.

[msg YUKIKO_SWITCH_FIND_2]
Vamos a tener que presionar el[n]interruptor, 夷no?

[msg YUKIKO_SWITCH_FIND_3]
夷No parece un interruptor?

[msg YUKIKO_SHORTCUT_FIND_1]
Creo que podemos pasar por all胤.

[msg YUKIKO_SHORTCUT_FIND_2]
夷Crees que podemos usar eso como un[n]atajo?

[msg YUKIKO_SHORTCUT_FIND_3]
Creo que podemos pasar por ah胤.

[msg YUKIKO_PARTY_DEAD_1]
?

[msg YUKIKO_PARTY_DEAD_2]
?

[msg YUKIKO_PARTY_DEAD_3]
?

[msg YUKIKO_FOE_WARNING_NEAR_]
斡El FOE todav胤a se acerca!

[msg YUKIKO_FOE_WARNING_NEAR__2]
Nos siguen. Tengamos cuidado.

[msg YUKIKO_FOE_WARNING_NEAR__3]
斡El FOE todav胤a nos persigue!

[msg YUKIKO_PARTY_HPTP10_1]
■ CONTRASE謂A

[msg YUKIKO_PARTY_HPTP10_2]
■ CONTRASE謂A

[msg YUKIKO_PARTY_HPTP10_3]
■ CONTRASE謂A

[msg YUKIKO_PARTY_HP10_1]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg YUKIKO_PARTY_HP10_2]
◆CONT威CTELO 10% DE LA VISTA

[msg YUKIKO_PARTY_HP10_3]
◆CONTINUAR LA B郁SQUEDA DE LA LUZ

[msg YUKIKO_1PERSON_HPTP10_1]
Lo siento, no puedo seguir...

[msg YUKIKO_1PERSON_HPTP10_2]
Esto no es bueno. Creo que estoy en[n]mi l胤mite...

[msg YUKIKO_1PERSON_HPTP10_3]
夷Crees que podr胤amos tomar un[n]descanso...?

[msg YUKIKO_PARTY_TP10_1]
■ CONTRASE謂A

[msg YUKIKO_PARTY_TP10_2]
■ CONTRASE謂A

[msg YUKIKO_PARTY_TP10_3]
■ CONTRASE謂A

[msg YUKIKO_1PERSON_HP10_1]
Alguien, por favor, c雨reme...

[msg YUKIKO_1PERSON_HP10_2]
Mi salud est茨 muy baja...

[msg YUKIKO_1PERSON_HP10_3]
Por favor, alguien me cura...

[msg YUKIKO_1PERSON_TP10_1]
Nnh... no creo que tenga m茨s[n]energ胤a...

[msg YUKIKO_1PERSON_TP10_2]
Me estoy cansando...

[msg YUKIKO_1PERSON_TP10_3]
No sirve de nada... no creo que pueda[n]moverme ni un cent胤metro m茨s...

[msg YUKIKO_ITEM_90_BATTLE_1]
【justificadamente

[msg YUKIKO_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg YUKIKO_ITEM_90_BATTLE_3]
【justificadamente

[msg YUKIKO_1PERSON_HP80_1]
斡Jeje! 斡Esto no es nada para[n]nosotros!

[msg YUKIKO_1PERSON_HP80_2]
Puedo seguir. D姻jamelo a m胤.

[msg YUKIKO_1PERSON_HP80_3]
Creo que podemos mantener el ritmo.

[msg YUKIKO_BATTLE_CHANGE_DUN]
■ト [f 0 1 4]\cHFF

[msg YUKIKO_BATTLE_CHANGE_DUN_2]
■ト [f 0 1 4]\cHFF

[msg YUKIKO_BATTLE_CHANGE_DUN_3]
■ト

[msg YUKIKO_ITEM_90_DUNGEON_1]
(DGP郁BLICA)

[msg YUKIKO_ITEM_90_DUNGEON_2]
(DGP郁BLICA)

[msg YUKIKO_ITEM_90_DUNGEON_3]
(DGP郁BLICA)

[msg YUKIKO_DUNGEON_START_1]
No se arriesguen demasiado.

[msg YUKIKO_DUNGEON_START_2]
No olvidamos nada, 夷verdad?

[msg YUKIKO_DUNGEON_START_3]
Deber胤amos estar preparados para[n]cualquier cosa.

[msg YUKIKO_QUEST_START_1]
Hagamos todo lo posible para tener[n]姻xito.

[msg YUKIKO_QUEST_START_2]
斡Vamos con cuidado!

[msg YUKIKO_QUEST_START_3]
No te preocupes, estoy segura de que[n]podemos hacerlo.

[msg YUKIKO_TOUHA_25_1]
Siento que todav胤a tenemos mucho m茨s[n]por explorar...

[msg YUKIKO_TOUHA_25_2]
びよぽぺわウぺ ょよれ りゎまぽぺ ぼぺゆもょよ らよる るまぼよるるまるデ らまるよ[n]れもむぺゆよれ めぺぼもまょぽよ ゅよ ゆまゃよる りゎま らよぽぺゆよれテ

[msg YUKIKO_TOUHA_50_1]
Creo que estamos a mitad de camino.

[msg YUKIKO_TOUHA_50_2]
Mm, estamos en racha. 斡Sigamos as胤!

[msg YUKIKO_TOUHA_75_1]
Uf... Hemos caminado bastante.

[msg YUKIKO_TOUHA_75_2]
Solo un poco m茨s y este piso estar茨[n]terminado.

[msg YUKIKO_TOUHA_100_1]
Hemos recorrido cada parte de este[n]piso. Bien hecho.

[msg YUKIKO_TOUHA_100_2]
斡Hemos recorrido cada parte de este[n]piso!

[msg YUKIKO_MAPPING_ICON_ALL_]
El mapa se ve realmente bien,[n]gracias.

[msg YUKIKO_MAPPING_ICON_ALL__2]
Wow, 斡Este mapa es muy preciso!

[msg YUKIKO_MAPPING_ICON_KAID]
Estoy segura de que ser茨 雨til si[n]sabemos d吋nde est茨n las escaleras.

[msg YUKIKO_MAPPING_ICON_KAID_2]
Es bueno marcar puntos de inter姻s.

[msg YUKIKO_MAPPING_CHANGE_CO]
Ah, 夷Usar茨s ese color?

[msg YUKIKO_MAPPING_CHANGE_CO_2]
Tienes un ojo agudo para el arte. Tal[n]vez yo tambi姻n lo intente.

[msg YUKIKO_MAPPING_ICON_DEL_]
Es mejor tirar cosas que no[n]necesitamos.

[msg YUKIKO_MAPPING_ICON_DEL__2]
Mmhm, mucho m茨s limpio ahora.

[msg YUKIKO_MAPPING_MEMO_1]
Es importante tomar notas.

[msg YUKIKO_MAPPING_MEMO_2]
Aseg雨rate de escribirlo para que no[n]se te olvide.

[msg YUKIKO_DOOR_OPEN_1]
Supongo que vamos por este camino.

[msg YUKIKO_DOOR_OPEN_2]
Sigamos.

[msg YUKIKO_DOOR_OPEN_3]
夷Qu姻 crees que hay al otro lado?

[msg YUKIKO_KARITORU_ENCOUNT_]
? ? Todav胤a no hay nada que ver

[msg YUKIKO_KARITORU_ENCOUNT__2]
? ? Todav胤a no hay nada que ver

[msg YUKIKO_KARITORU_ENCOUNT__3]
? ? Todav胤a no hay 姻xito

