[msg JUNPEI_FOE_FOLLOW_START_]
ムEs un FOE!

[msg JUNPEI_FOE_FOLLOW_START__2]
ムUn FOE nos persigue!

[msg JUNPEI_FOE_FOLLOW_START__3]
ムAmigo! ムUn FOE viene por aquボ!

[msg JUNPEI_FOE_NEAR_1]
Maldiciポn, ムun ENEMIGO!

[msg JUNPEI_FOE_NEAR_2]
Por favor, que no nos note... Por[n]favor, que no nos note...

[msg JUNPEI_FOE_NEAR_3]
Hagamos esto de manera bien[n]tranquila.

[msg JUNPEI_FOE_FOLLOW_END_1]
Parece que lo perdimos.

[msg JUNPEI_FOE_FOLLOW_END_2]
Ja, como si fu〒ramos lo suficientemente[n]tontos como para enfrentar eso de frente.

[msg JUNPEI_FOE_FOLLOW_END_3]
ムJunpei Iori vive para ver otro dボa!

[msg JUNPEI_KANSI_REACTION_1]
ムShh! Mira por dポnde pisas.

[msg JUNPEI_KANSI_REACTION_2]
ムAquボ viene el maestro ninja Junpei!

[msg JUNPEI_KANSI_REACTION_3]
Me estホ poniendo nervioso...

[msg JUNPEI_DENKISAKU_REACTIO]
Nope. No podemos atravesar eso...

[msg JUNPEI_DENKISAKU_REACTIO_2]
Me pregunto si hay un interruptor[n]para apagar el poder...

[msg JUNPEI_DENKISAKU_REACTIO_3]
メEs una especie de nueva terapia de[n]choque...? ムEh, despu〒s de ti!

[msg JUNPEI_KYOUHU_REACTION_1]
ムEstoy volando!

[msg JUNPEI_KYOUHU_REACTION_2]
メWhoa?

[msg JUNPEI_KYOUHU_REACTION_3]
メHablas en serio?

[msg JUNPEI_STAIR_FIND_1]
メOh? メSon las escaleras que veo?

[msg JUNPEI_STAIR_FIND_2]
Parece que podemos pasar a la[n]siguiente zona. メEstホs listo?

[msg JUNPEI_STAIR_FIND_3]
Y si pones tu atenciポn en el frente,[n]verホs una escalera.

[msg JUNPEI_TREASURE_FIND_1]
ムEncontr〒 un cofre del tesoro!

[msg JUNPEI_TREASURE_FIND_2]
メHm? メEs un tesoro?

[msg JUNPEI_TREASURE_FIND_3]
メEso es... un tesoro?

[msg JUNPEI_CHECK_WALL_1]
Hay algo sospechoso ahボ...

[msg JUNPEI_CHECK_WALL_2]
Echemos un vistazo mホs de cerca.

[msg JUNPEI_CHECK_WALL_3]
メHay algo ahボ? Lo hay, メno?

[msg JUNPEI_SWITCH_FIND_1]
ムTa da da da da! ムAdelante!

[msg JUNPEI_SWITCH_FIND_2]
ムEncontr〒 un interruptor!

[msg JUNPEI_SWITCH_FIND_3]
ムOye, veo un interruptor!

[msg JUNPEI_SHORTCUT_FIND_1]
Hey, creo que vi un atajo!

[msg JUNPEI_SHORTCUT_FIND_2]
Parece un atajo.

[msg JUNPEI_SHORTCUT_FIND_3]
ムPodemos pasar por ahボ!

[msg JUNPEI_PARTY_DEAD_1]
?

[msg JUNPEI_PARTY_DEAD_2]
?

[msg JUNPEI_PARTY_DEAD_3]
?

[msg JUNPEI_FOE_WARNING_NEAR_]
Oh, Dios, ese FOE todavボa nos[n]persigue!

[msg JUNPEI_FOE_WARNING_NEAR__2]
ムMaldita sea, esa cosa es terca! Las[n]chicas no lo aprecian, メsabes?

[msg JUNPEI_FOE_WARNING_NEAR__3]
Parece que quiere amigos... Eh, ムno[n]gracias!

[msg JUNPEI_PARTY_HPTP10_1]
■ CONTRASEヰA

[msg JUNPEI_PARTY_HPTP10_2]
■ CONTRASEヰA

[msg JUNPEI_PARTY_HPTP10_3]
■ CONTRASEヰA

[msg JUNPEI_PARTY_HP10_1]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg JUNPEI_PARTY_HP10_2]
◆CONTミCTELO 10% DE LA VISTA

[msg JUNPEI_PARTY_HP10_3]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg JUNPEI_1PERSON_HPTP10_1]
No puedo seguir...

[msg JUNPEI_1PERSON_HPTP10_2]
Sin salud, sin energボa. ムJunpei estホ[n]fuera de combate!

[msg JUNPEI_1PERSON_HPTP10_3]
Lo siento, pero estoy agotado.[n]Ayマdame a leeeevantarme.

[msg JUNPEI_PARTY_TP10_1]
■ CONTRASEヰA

[msg JUNPEI_PARTY_TP10_2]
■ CONTRASEヰA

[msg JUNPEI_PARTY_TP10_3]
■ CONTRASEヰA

[msg JUNPEI_1PERSON_HP10_1]
Mi salud estホ prホcticamente[n]agotada...

[msg JUNPEI_1PERSON_HP10_2]
ムAyuda! ムTe lo advierto!

[msg JUNPEI_1PERSON_HP10_3]
Mi salud estホ en rojo... メPuedes[n]ayudarme?

[msg JUNPEI_1PERSON_TP10_1]
Ergh... Mi energボa no se ve muy bien.

[msg JUNPEI_1PERSON_TP10_2]
Mierda, casi no tengo energボa...

[msg JUNPEI_1PERSON_TP10_3]
Lo siento, estoy sin energボa...[n]Hombre, estoy agotado...

[msg JUNPEI_ITEM_90_BATTLE_1]
【justificadamente

[msg JUNPEI_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg JUNPEI_ITEM_90_BATTLE_3]
【justificadamente

[msg JUNPEI_1PERSON_HP80_1]
Hmm. Eso fue bastante fホcil, メeh?

[msg JUNPEI_1PERSON_HP80_2]
ムLos buenos siempre ganan!

[msg JUNPEI_1PERSON_HP80_3]
ムSボ! メQui〒n es el hombre?

[msg JUNPEI_BATTLE_CHANGE_DUN]
■: [f 0 1 4]\cHFF

[msg JUNPEI_BATTLE_CHANGE_DUN_2]
■: [f 0 1 4]\cHFF

[msg JUNPEI_BATTLE_CHANGE_DUN_3]
■:

[msg JUNPEI_ITEM_90_DUNGEON_1]
(DGPヮBLICA)

[msg JUNPEI_ITEM_90_DUNGEON_2]
(DGPヮBLICA)

[msg JUNPEI_ITEM_90_DUNGEON_3]
(DGPヮBLICA)

[msg JUNPEI_DUNGEON_START_1]
ムVamos a poner esto en marcha!

[msg JUNPEI_DUNGEON_START_2]
Muy bien, vamos.

[msg JUNPEI_DUNGEON_START_3]
ムY estoy en marcha!

[msg JUNPEI_QUEST_START_1]
Vamos a terminar esto rホpido.

[msg JUNPEI_QUEST_START_2]
ムEs un trabajo para un h〒roe!

[msg JUNPEI_QUEST_START_3]
ムPuedo manejar esto solo!

[msg JUNPEI_TOUHA_25_1]
Todavボa hay un largo camino por[n]recorrer. Cuida tu salud, メsボ?

[msg JUNPEI_TOUHA_25_2]
Dios, todavボa estamos tan lejos..?

[msg JUNPEI_TOUHA_50_1]
メCrees que estamos a mitad de camino?

[msg JUNPEI_TOUHA_50_2]
ムEste mapa estホ lleno!

[msg JUNPEI_TOUHA_75_1]
ムHemos llenado una tonelada!

[msg JUNPEI_TOUHA_75_2]
ムEsperamos que el resto de esos[n]espacios est〒n seguros!

[msg JUNPEI_TOUHA_100_1]
ムTada! ムEl mapa estホ terminado![n]ムBien!

[msg JUNPEI_TOUHA_100_2]
ムBuen trabajo en la cartografボa!

[msg JUNPEI_MAPPING_ICON_ALL_]
ムOye, buena!

[msg JUNPEI_MAPPING_ICON_ALL__2]
Tienes un buen mapa. Impresionante.

[msg JUNPEI_MAPPING_ICON_KAID]
ムSボ, asボ!

[msg JUNPEI_MAPPING_ICON_KAID_2]
ムDing ding ding! ムTenemos un ganador!

[msg JUNPEI_MAPPING_CHANGE_CO]
Es bueno cambiar las cosas.

[msg JUNPEI_MAPPING_CHANGE_CO_2]
Vaya, eres muy detallado, メeh?

[msg JUNPEI_MAPPING_ICON_DEL_]
Verte poner los toques finales en ese[n]mapa... Es hermoso.

[msg JUNPEI_MAPPING_ICON_DEL__2]
メCポmo pudiste tirar eso? Sポlo[n]bromeaba.

[msg JUNPEI_MAPPING_MEMO_1]
Aquボ, d〒jame firmar mi nombre... メEh? メQu〒[n]quieres decir con que no lo necesitas?

[msg JUNPEI_MAPPING_MEMO_2]
Eh, eso es conveniente.

[msg JUNPEI_DOOR_OPEN_1]
Perdポname.

[msg JUNPEI_DOOR_OPEN_2]
ムVamos!

[msg JUNPEI_DOOR_OPEN_3]
ムMuy bien! ムHagホmoslo!

[msg JUNPEI_KARITORU_ENCOUNT_]
? ? Todavボa no hay nada que ver

[msg JUNPEI_KARITORU_ENCOUNT__2]
? ? Todavボa no hay nada que ver

[msg JUNPEI_KARITORU_ENCOUNT__3]
? ? Todavボa no hay 〒xito

