[msg FUTABA_FOE_FOLLOW_START_]
ムUn FOE se acerca!

[msg FUTABA_FOE_FOLLOW_START__2]
ムNos estホ siguiendo!

[msg FUTABA_FOE_FOLLOW_START__3]
ムEl FOE estホ cerca!

[msg FUTABA_FOE_NEAR_1]
ムEl FOE estホ delante! ムTen cuidado!

[msg FUTABA_FOE_NEAR_2]
ムWhoa! ムMuy cerca!

[msg FUTABA_FOE_NEAR_3]
ムEstホ cerca! ムCuidado!

[msg FUTABA_FOE_FOLLOW_END_1]
Ahora podemos relajarnos. ムSe ha ido!

[msg FUTABA_FOE_FOLLOW_END_2]
Muy bien, lo logramos.

[msg FUTABA_FOE_FOLLOW_END_3]
Whew... ムLo perdimos!

[msg FUTABA_KANSI_REACTION_1]
ムHay un patrポn! ムObserva[n]detenidamente!

[msg FUTABA_KANSI_REACTION_2]
Mantengan la calma y estarホn bien!

[msg FUTABA_KANSI_REACTION_3]
Bien, ten cuidado...

[msg FUTABA_DENKISAKU_REACTIO]
ムTenemos que hacer algo con la puerta[n]primero!

[msg FUTABA_DENKISAKU_REACTIO_2]
ムNo toques eso! ムMala idea!

[msg FUTABA_DENKISAKU_REACTIO_3]
Deberボamos poder pasar si detienes la[n]electricidad.

[msg FUTABA_KYOUHU_REACTION_1]
ムHeeey!

[msg FUTABA_KYOUHU_REACTION_2]
ムUstedes iban volando!

[msg FUTABA_KYOUHU_REACTION_3]
メEstホn bien?

[msg FUTABA_STAIR_FIND_1]
ムMira! ムUna escalera!

[msg FUTABA_STAIR_FIND_2]
ムCerca de las escaleras! ムSolo un[n]poco mホs!

[msg FUTABA_STAIR_FIND_3]
ムMuy bien! ムAl siguiente piso!

[msg FUTABA_TREASURE_FIND_1]
メHm? ムEstoy viendo un tesoro por[n]delante!

[msg FUTABA_TREASURE_FIND_2]
メVes eso? ムTesoro!

[msg FUTABA_TREASURE_FIND_3]
ムAhボ estホ! ムEl tesoro, justo[n]enfrente!

[msg FUTABA_CHECK_WALL_1]
ムJusto ahボ! メVes algo?

[msg FUTABA_CHECK_WALL_2]
Hay algo allボ. メQuieres echar un[n]vistazo?

[msg FUTABA_CHECK_WALL_3]
Algo huele mal aquボ. Serボa mejor[n]echar un vistazo.

[msg FUTABA_SWITCH_FIND_1]
メUn interruptor?

[msg FUTABA_SWITCH_FIND_2]
ムMira! ムUn interruptor!

[msg FUTABA_SWITCH_FIND_3]
Y... ムBingo! ムApaga el interruptor!

[msg FUTABA_SHORTCUT_FIND_1]
ムOh! ムParece que podemos pasar por[n]aquボ!

[msg FUTABA_SHORTCUT_FIND_2]
ムUn camino escondido! ムBien!

[msg FUTABA_SHORTCUT_FIND_3]
ムParece que podemos pasar por aquボ!

[msg FUTABA_PARTY_DEAD_1]
ムNo podemos seguir asボ! ムCorre!

[msg FUTABA_PARTY_DEAD_2]
ムMierda! ムPodrボa ser una buena idea[n]retroceder!

[msg FUTABA_PARTY_DEAD_3]
ムSal de ahボ! ムEs demasiado peligroso!

[msg FUTABA_FOE_WARNING_NEAR_]
ムFOE cerca! ムCuidado!

[msg FUTABA_FOE_WARNING_NEAR__2]
ムTodavボa podemos! ムMantente alerta!

[msg FUTABA_FOE_WARNING_NEAR__3]
ムViene, chicos!

[msg FUTABA_PARTY_HPTP10_1]
No podemos trabajar asボ...

[msg FUTABA_PARTY_HPTP10_2]
ムNo te preocupes! ムVuelve aquボ!

[msg FUTABA_PARTY_HPTP10_3]
ムHey, no te esfuerces demasiado!

[msg FUTABA_PARTY_HP10_1]
Se les ve agotados... Tal vez[n]deberボan tomar un descanso.

[msg FUTABA_PARTY_HP10_2]
ムCマrate o regresa!

[msg FUTABA_PARTY_HP10_3]
ムEvita ser derrotado a toda costa!

[msg FUTABA_1PERSON_HPTP10_1]
メEstホn todos bien?

[msg FUTABA_1PERSON_HPTP10_2]
ムPreparados!

[msg FUTABA_1PERSON_HPTP10_3]
Estamos en serios aprietos si no nos[n]curamos rホpido.

[msg FUTABA_PARTY_TP10_1]
ムRealmente se estホn esforzando al[n]mホximo!

[msg FUTABA_PARTY_TP10_2]
ムTu resistencia estホ bajando! ムNo te[n]exijas demasiado!

[msg FUTABA_PARTY_TP10_3]
ムParaaaaa! ムSe estホn exigiendo[n]demasiado!

[msg FUTABA_1PERSON_HP10_1]
ムEstホs perdiendo salud! メTe puedes[n]curar?

[msg FUTABA_1PERSON_HP10_2]
ムNo estarボa de mホs descansar un poco!

[msg FUTABA_1PERSON_HP10_3]
ムEs peligroso pelear de esa asボ!

[msg FUTABA_1PERSON_TP10_1]
Estホs sin resistencia... メVas a[n]continuar?

[msg FUTABA_1PERSON_TP10_2]
No te exijas demasiado, メde acuerdo?

[msg FUTABA_1PERSON_TP10_3]
ムAsegマrese de descansar cuando[n]puedas!

[msg FUTABA_ITEM_90_BATTLE_1]
ムParece que tu inventario estホ casi[n]lleno!

[msg FUTABA_ITEM_90_BATTLE_2]
Llevas mucho... Tal vez deberボas[n]regresar.

[msg FUTABA_ITEM_90_BATTLE_3]
Quizホs deberボas organizar tus cosas.

[msg FUTABA_1PERSON_HP80_1]
No estホ mal, chicos.

[msg FUTABA_1PERSON_HP80_2]
ムBuen trabajo! ムVamos a seguir!

[msg FUTABA_1PERSON_HP80_3]
ムLo estamos haciendo bien! ムSigue!

[msg RISE_FUTABA_MAKASETA_1]
ムEs todo tuyo, Oracle!

[msg RISE_FUTABA_MAKASETA_2]
ムEstホs despierta, Oracle! ムVe por[n]ellos!

[msg RISE_FUTABA_MAKASETA_3]
ムPrepホrate para un pase de Baton,[n]Oracle!

[msg RISE_FUTABA_ANSWER_1]
ムGracias, Rise! ムLo tengo desde aquボ!

[msg RISE_FUTABA_ANSWER_2]
ムCambio de Rise! ムOracle en el[n]micrポfono!

[msg RISE_FUTABA_ANSWER_3]
Muy bien, ムtengo esto! ムVamos,[n]chicos!

[msg FUKA_FUTABA_MAKASETA_1]
ムTe dejar〒 el resto ahora, Oracle!

[msg FUKA_FUTABA_MAKASETA_2]
ムHora de cambiar! ムEspero aprender[n]mucho de ti!

[msg FUKA_FUTABA_MAKASETA_3]
ムAhora lo entregar〒 a Oracle!

[msg FUKA_FUTABA_ANSWER_1]
Muy bien, Fuuka, ムme lo llevo de[n]aquボ!

[msg FUKA_FUTABA_ANSWER_2]
ムEso fue genial, Fuuka! ムD〒jenme el[n]resto!

[msg FUKA_FUTABA_ANSWER_3]
ムCubrindo a Fuuka! ムContinマen,[n]chicos!

[msg FUTABA_ITEM_90_DUNGEON_1]
ムParece que tu inventario estホ casi[n]lleno!

[msg FUTABA_ITEM_90_DUNGEON_2]
Llevas mucho... Tal vez deberボas[n]regresar.

[msg FUTABA_ITEM_90_DUNGEON_3]
Quizホs deberボas organizar tus cosas.

[msg FUTABA_DUNGEON_START_1]
ムLa navegaciポn se va!

[msg FUTABA_DUNGEON_START_2]
ムAdelante!

[msg FUTABA_DUNGEON_START_3]
ムMuy bien! ムEmpecemos!

[msg FUTABA_QUEST_START_1]
ムVamos!

[msg FUTABA_QUEST_START_2]
ムD〒jenme el apoyo!

[msg FUTABA_QUEST_START_3]
ムNo decepciones a tu guardia!

[msg FUTABA_TOUHA_25_1]
Vamos a llenar ese mapa!

[msg FUTABA_TOUHA_25_2]
メCポmo va el mapa?

[msg FUTABA_TOUHA_50_1]
ムA mitad!

[msg FUTABA_TOUHA_50_2]
ムAquボ es donde se pone difボcil!

[msg FUTABA_TOUHA_75_1]
ムParece que estホ casi hecho! ムGenial!

[msg FUTABA_TOUHA_75_2]
メDポnde mホs podemos ir?

[msg FUTABA_TOUHA_100_1]
ムGenial! ムEl mapa estホ hecho!

[msg FUTABA_TOUHA_100_2]
ムHm! ムBuen trabajo!

[msg FUTABA_MAPPING_ICON_ALL_]
ムEso no es nada malo!

[msg FUTABA_MAPPING_ICON_ALL__2]
ムBuen trabajo!

[msg FUTABA_MAPPING_ICON_KAID]
Ahボ vamos.

[msg FUTABA_MAPPING_ICON_KAID_2]
ムPerfectamente colocado!

[msg FUTABA_MAPPING_CHANGE_CO]
Tienes buen gusto.

[msg FUTABA_MAPPING_CHANGE_CO_2]
Ooh. Se ve divertido.

[msg FUTABA_MAPPING_ICON_DEL_]
Eres un monstruo muy bueno.

[msg FUTABA_MAPPING_ICON_DEL__2]
メQu〒? メLo estホs tirando?

[msg FUTABA_MAPPING_MEMO_1]
ムHaz una nota!

[msg FUTABA_MAPPING_MEMO_2]
メQu〒 estホs haciendo?

[msg FUTABA_DOOR_OPEN_1]
↑

[msg FUTABA_DOOR_OPEN_2]
↑

[msg FUTABA_DOOR_OPEN_3]
↑

[msg FUTABA_KARITORU_ENCOUNT_]
Es el Segador... ムEste va a ser duro!

[msg FUTABA_KARITORU_ENCOUNT__2]
Conozco este sentimiento... ムEs el[n]Segador!

[msg FUTABA_KARITORU_ENCOUNT__3]
ムUno duro en el camino! ムPrepホrate!

