[msg MONA_FOE_FOLLOW_START_1]
ムEl FOE nos vio!

[msg MONA_FOE_FOLLOW_START_2]
ムEl grande nos vio!

[msg MONA_FOE_FOLLOW_START_3]
ムEh-oh, nos estホ persiguiendo!

[msg MONA_FOE_NEAR_1]
ムHay un FOE cerca!

[msg MONA_FOE_NEAR_2]
ムEs un FOE!

[msg MONA_FOE_NEAR_3]
ムFOE! ムAtrホs!

[msg MONA_FOE_FOLLOW_END_1]
Muy bien, escapamos.

[msg MONA_FOE_FOLLOW_END_2]
Uf, parece que logramos escapar.

[msg MONA_FOE_FOLLOW_END_3]
Uf, eso me mantuvo alerta...

[msg MONA_KANSI_REACTION_1]
Presta atenciポn a su movimiento.

[msg MONA_KANSI_REACTION_2]
Mant〒n la calma mientras avanzas.

[msg MONA_KANSI_REACTION_3]
Escucha. Tenemos que hacer esto con[n]cuidado.

[msg MONA_DENKISAKU_REACTION_]
Mew... Me estホ erizando el pelaje...

[msg MONA_DENKISAKU_REACTION__2]
メQu〒 hacemos?

[msg MONA_DENKISAKU_REACTION__3]
No lo toques, esta cosa es peligrosa.

[msg MONA_KYOUHU_REACTION_1]
ムメMiau?!

[msg MONA_KYOUHU_REACTION_2]
ムWhoa! ムEste viento!

[msg MONA_KYOUHU_REACTION_3]
ムWhoa!

[msg MONA_STAIR_FIND_1]
ムUn camino se abre!

[msg MONA_STAIR_FIND_2]
ムMuy bien, un nuevo camino!

[msg MONA_STAIR_FIND_3]
Vamos a seguir, メverdad, Joker?

[msg MONA_TREASURE_FIND_1]
Ooh, ムTesoro!

[msg MONA_TREASURE_FIND_2]
ムOye, veo un tesoro!

[msg MONA_TREASURE_FIND_3]
ムMrowroooow! ムTesoro!

[msg MONA_CHECK_WALL_1]
Esto parece sospechoso.

[msg MONA_CHECK_WALL_2]
Debe haber algo aquボ.

[msg MONA_CHECK_WALL_3]
Hay algo aquボ...

[msg MONA_SWITCH_FIND_1]
メLos interruptores no te dan ganas de[n]usarlos?

[msg MONA_SWITCH_FIND_2]
Mira, un interruptor.

[msg MONA_SWITCH_FIND_3]
Un interruptor, メeh? ムTen cuidado!

[msg MONA_SHORTCUT_FIND_1]
Parece que podemos tomar un atajo.

[msg MONA_SHORTCUT_FIND_2]
ムCreo que podemos tomar un atajo!

[msg MONA_SHORTCUT_FIND_3]
メCrees que podemos pasar por ahボ?

[msg MONA_PARTY_DEAD_1]
?

[msg MONA_PARTY_DEAD_2]
?

[msg MONA_PARTY_DEAD_3]
?

[msg MONA_FOE_WARNING_NEAR_1]
ムEl FOE todavボa nos persigue!

[msg MONA_FOE_WARNING_NEAR_2]
ムFOE! ムAquボ viene!

[msg MONA_FOE_WARNING_NEAR_3]
No bajes la guardia. ムTodavボa nos[n]sigue!

[msg MONA_PARTY_HPTP10_1]
■ CONTRASEヰA

[msg MONA_PARTY_HPTP10_2]
■ CONTRASEヰA

[msg MONA_PARTY_HPTP10_3]
■ CONTRASEヰA

[msg MONA_PARTY_HP10_1]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg MONA_PARTY_HP10_2]
◆CONTミCTELO 10% DE LA VISTA

[msg MONA_PARTY_HP10_3]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg MONA_1PERSON_HPTP10_1]
No me des por vencido aマn... Nngh...

[msg MONA_1PERSON_HPTP10_2]
Oye, メpor qu〒 no tomamos un[n]descanso...?

[msg MONA_1PERSON_HPTP10_3]
Esto es malo...

[msg MONA_PARTY_TP10_1]
■ CONTRASEヰA

[msg MONA_PARTY_TP10_2]
■ CONTRASEヰA

[msg MONA_PARTY_TP10_3]
■ CONTRASEヰA

[msg MONA_1PERSON_HP10_1]
No creo que pueda durar mucho mホs...

[msg MONA_1PERSON_HP10_2]
Estoy empezando a cansarme...

[msg MONA_1PERSON_HP10_3]
メAlguien puede curarme?

[msg MONA_1PERSON_TP10_1]
No creo que pueda ir mホs lejos...

[msg MONA_1PERSON_TP10_2]
Tenemos que asegurarnos de no[n]arriesgarnos, メde acuerdo...?

[msg MONA_1PERSON_TP10_3]
Esto es bastante difボcil...

[msg MONA_ITEM_90_BATTLE_1]
【justificadamente

[msg MONA_ITEM_90_BATTLE_2]
◆Recibir 90% escrito

[msg MONA_ITEM_90_BATTLE_3]
【justificadamente

[msg MONA_1PERSON_HP80_1]
No olvides curarte, メde acuerdo?

[msg MONA_1PERSON_HP80_2]
Bien, sigamos.

[msg MONA_1PERSON_HP80_3]
Vamos, chicos.

[msg MONA_BATTLE_CHANGE_DUNGE]
■: [f 0 1 4]\cHFF

[msg MONA_BATTLE_CHANGE_DUNGE_2]
■: [f 0 1 4]\cHFF

[msg MONA_BATTLE_CHANGE_DUNGE_3]
■:

[msg MONA_ITEM_90_DUNGEON_1]
(DGPヮBLICA)

[msg MONA_ITEM_90_DUNGEON_2]
(DGPヮBLICA)

[msg MONA_ITEM_90_DUNGEON_3]
(DGPヮBLICA)

[msg MONA_DUNGEON_START_1]
ムD〒jamelo a mボ!

[msg MONA_DUNGEON_START_2]
De acuerdo, vamos a entrar.

[msg MONA_DUNGEON_START_3]
ムHagホmoslo!

[msg MONA_QUEST_START_1]
ムEstaba esperando esto!

[msg MONA_QUEST_START_2]
Vamos.

[msg MONA_QUEST_START_3]
Hora de trabajar.

[msg MONA_TOUHA_25_1]
El mapa estホ empezando a tomar forma.

[msg MONA_TOUHA_25_2]
Oh, finalmente estamos empezando a[n]tener una idea de este lugar.

[msg MONA_TOUHA_50_1]
Estamos a mitad de camino.

[msg MONA_TOUHA_50_2]
Estamos a la mitad.

[msg MONA_TOUHA_75_1]
Realmente tendremos que aprovecharlo[n]al mホximo a partir de ahora.

[msg MONA_TOUHA_75_2]
Sポlo un poco mホs.

[msg MONA_TOUHA_100_1]
ムRuta completada!

[msg MONA_TOUHA_100_2]
Hemos terminado.

[msg MONA_MAPPING_ICON_ALL_1]
No estホ mal.

[msg MONA_MAPPING_ICON_ALL_2]
Mmm, buen trabajo.

[msg MONA_MAPPING_ICON_KAIDAN]
Ahora tenemos un camino claro.

[msg MONA_MAPPING_ICON_KAIDAN_2]
ムEso pasa por nuestra ruta!

[msg MONA_MAPPING_CHANGE_COLO]
Cambiar colores, メeh?

[msg MONA_MAPPING_CHANGE_COLO_2]
Ooh, Impresionante.

[msg MONA_MAPPING_ICON_DEL_1]
Es importante ser organizado.

[msg MONA_MAPPING_ICON_DEL_2]
メSeguro que no necesitas eso?

[msg MONA_MAPPING_MEMO_1]
Ooh, buen trabajo.

[msg MONA_MAPPING_MEMO_2]
ムNo queremos olvidar eso!

[msg MONA_DOOR_OPEN_1]
Por aquボ.

[msg MONA_DOOR_OPEN_2]
ムSボgueme!

[msg MONA_DOOR_OPEN_3]
Vamos.

[msg MONA_KARITORU_ENCOUNT_1]
? ? Todavボa no hay nada que ver

[msg MONA_KARITORU_ENCOUNT_2]
? ? Todavボa no hay nada que ver

[msg MONA_KARITORU_ENCOUNT_3]
? ? Todavボa no hay 〒xito

