[msg P3_HERO2_FOE_FOLLOW_STAR]
ムParece que el FOE nos vio!

[msg P3_HERO2_FOE_FOLLOW_STAR_2]
ムUn FOE nos persigue!

[msg P3_HERO2_FOE_FOLLOW_STAR_3]
ムCuidado! ムUn FOE nos persigue!

[msg P3_HERO2_FOE_NEAR_1]
ムHay un FOE cerca!

[msg P3_HERO2_FOE_NEAR_2]
ムEl FOE nos vio!

[msg P3_HERO2_FOE_NEAR_3]
Maldiciポn, hay un FOE...

[msg P3_HERO2_FOE_FOLLOW_END_]
Parece que el FOE nos dejポ en paz.

[msg P3_HERO2_FOE_FOLLOW_END__2]
ムEl FOE ya no nos sigue!

[msg P3_HERO2_FOE_FOLLOW_END__3]
Escapamos... Qu〒 alivio.

[msg P3_HERO2_KANSI_REACTION_]
ムVaya, todos estホn en alerta mホxima!

[msg P3_HERO2_KANSI_REACTION__2]
Serホ un problema si nos encuentran.[n]ムTen cuidado!

[msg P3_HERO2_KANSI_REACTION__3]
ムNo puedes atraparnos!

[msg P3_HERO2_DENKISAKU_REACT]
Si no apagamos la energボa, nos[n]convertiremos en cenizas.

[msg P3_HERO2_DENKISAKU_REACT_2]
Una puerta el〒ctrica, eh... ムParece que[n]tenemos que apagar la energボa primero!

[msg P3_HERO2_DENKISAKU_REACT_3]
ムCuidado! ムUna puerta el〒ctrica!

[msg P3_HERO2_KYOUHU_REACTION]
ムAaaaaaahhhh!

[msg P3_HERO2_KYOUHU_REACTION_2]
ムEek!

[msg P3_HERO2_KYOUHU_REACTION_3]
ムメDe verdad?!

[msg P3_HERO2_STAIR_FIND_1]
ムParece que podemos seguir adelante!

[msg P3_HERO2_STAIR_FIND_2]
ムBueno, tenemos que ir a la siguiente[n]zona!

[msg P3_HERO2_STAIR_FIND_3]
Creo que podemos seguir adelante.

[msg P3_HERO2_TREASURE_FIND_1]
ムMira! ムUn cofre del tesoro!

[msg P3_HERO2_TREASURE_FIND_2]
Hay un cofre del tesoro. ムVamos a[n]abrirlo!

[msg P3_HERO2_TREASURE_FIND_3]
Un cofre del tesoro. ムメQu〒 hay[n]dentro?!

[msg P3_HERO2_CHECK_WALL_1]
Algo en esta zona me estホ[n]molestando...

[msg P3_HERO2_CHECK_WALL_2]
Debe haber algo aquボ. ムVamos a[n]buscar!

[msg P3_HERO2_CHECK_WALL_3]
メNo hay algo extraワo en este[n]lugar...?

[msg P3_HERO2_SWITCH_FIND_1]
ムOh, un interruptor! ムDemos un buen[n]tirポn!

[msg P3_HERO2_SWITCH_FIND_2]
ムEncontr〒 un interruptor! ムAdelante!

[msg P3_HERO2_SWITCH_FIND_3]
メNo es un interruptor?

[msg P3_HERO2_SHORTCUT_FIND_1]
メCrees que podamos pasar por allボ?

[msg P3_HERO2_SHORTCUT_FIND_2]
Creo que hay un atajo.

[msg P3_HERO2_SHORTCUT_FIND_3]
ムBien, un atajo!

[msg P3_HERO2_PARTY_DEAD_1]
?

[msg P3_HERO2_PARTY_DEAD_2]
?

[msg P3_HERO2_PARTY_DEAD_3]
?

[msg P3_HERO2_FOE_WARNING_NEA]
ムTodavボa hay un FOE cerca! ムAlerta!

[msg P3_HERO2_FOE_WARNING_NEA_2]
Parece que el FOE sigue por aquボ.

[msg P3_HERO2_FOE_WARNING_NEA_3]
ムFOE lanzホndose hacia nosotros!

[msg P3_HERO2_PARTY_HPTP10_1]
■ CONTRASEヰA

[msg P3_HERO2_PARTY_HPTP10_2]
■ CONTRASEヰA

[msg P3_HERO2_PARTY_HPTP10_3]
■ CONTRASEヰA

[msg P3_HERO2_PARTY_HP10_1]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg P3_HERO2_PARTY_HP10_2]
◆CONTミCTELO 10% DE LA VISTA

[msg P3_HERO2_PARTY_HP10_3]
◆CONTINUAR LA BヮSQUEDA DE LA LUZ

[msg P3_HERO2_1PERSON_HPTP10_]
Sボp, esto es difボcil.

[msg P3_HERO2_1PERSON_HPTP10__2]
メPor qu〒 no volvemos a nuestra base?

[msg P3_HERO2_1PERSON_HPTP10__3]
*jadeo* Estoy mホs cansada de lo que[n]pens〒...

[msg P3_HERO2_PARTY_TP10_1]
■ CONTRASEヰA

[msg P3_HERO2_PARTY_TP10_2]
■ CONTRASEヰA

[msg P3_HERO2_PARTY_TP10_3]
■ CONTRASEヰA

[msg P3_HERO2_1PERSON_HP10_1]
Hrrgh... ムAlguien, por favor, cマreme!

[msg P3_HERO2_1PERSON_HP10_2]
Creo que mi salud estホ bajando...

[msg P3_HERO2_1PERSON_HP10_3]
No puedo seguir... Mi salud es[n]demasiado baja...

[msg P3_HERO2_1PERSON_TP10_1]
Tan exhausta... メPodemos descansar un[n]poco?

[msg P3_HERO2_1PERSON_TP10_2]
Mi resistencia ha sido llevada al[n]lボmite...

[msg P3_HERO2_1PERSON_TP10_3]
No mホs... Estoy sin energボa...

[msg P3_HERO2_ITEM_90_BATTLE_]
【justificadamente

[msg P3_HERO2_ITEM_90_BATTLE__2]
◆Recibir 90% escrito

[msg P3_HERO2_ITEM_90_BATTLE__3]
【justificadamente

[msg P3_HERO2_1PERSON_HP80_1]
Espero que el prポximo sea asボ[n]tambi〒n!

[msg P3_HERO2_1PERSON_HP80_2]
ムPan comido!

[msg P3_HERO2_1PERSON_HP80_3]
ムEso fue pan comido!

[msg P3_HERO2_BATTLE_CHANGE_D]
■: [f 0 1 4]\cHFF

[msg P3_HERO2_BATTLE_CHANGE_D_2]
■: [f 0 1 4]\cHFF

[msg P3_HERO2_BATTLE_CHANGE_D_3]
■:

[msg P3_HERO2_ITEM_90_DUNGEON]
(DGPヮBLICA)

[msg P3_HERO2_ITEM_90_DUNGEON_2]
(DGPヮBLICA)

[msg P3_HERO2_ITEM_90_DUNGEON_3]
(DGPヮBLICA)

[msg P3_HERO2_DUNGEON_START_1]
ムAvancemos!

[msg P3_HERO2_DUNGEON_START_2]
ムD〒jame encargarme de esto!

[msg P3_HERO2_DUNGEON_START_3]
Somos un escuadrポn increボble;[n]mantengホmoslo asボ.

[msg P3_HERO2_QUEST_START_1]
ムOk, esto terminarホ rホpido, con[n]suerte!

[msg P3_HERO2_QUEST_START_2]
Tenemos nuestras ポrdenes, ムVamos!

[msg P3_HERO2_QUEST_START_3]
Estoy muy emocionada, ahora.

[msg P3_HERO2_TOUHA_25_1]
Parece que todavボa nos queda un[n]trecho... メEstamos bien de salud?

[msg P3_HERO2_TOUHA_25_2]
Parecen estar dispersos... Tengamos[n]cuidado al continuar.

[msg P3_HERO2_TOUHA_50_1]
ムEl mapa se estホ llenando muy bien!

[msg P3_HERO2_TOUHA_50_2]
メCreo que estamos a mitad de camino?

[msg P3_HERO2_TOUHA_75_1]
ムSigamos asボ y avancemos con[n]determinaciポn!

[msg P3_HERO2_TOUHA_75_2]
Creo que nos falta un poquito mホs,[n]メverdad?

[msg P3_HERO2_TOUHA_100_1]
ムQu〒 sensaciポn de logro!

[msg P3_HERO2_TOUHA_100_2]
ムPerfecto! Lo hicimos.

[msg P3_HERO2_MAPPING_ICON_AL]
ムMe encanta!

[msg P3_HERO2_MAPPING_ICON_AL_2]
ムBueno, no olvidaremos eso ahora!

[msg P3_HERO2_MAPPING_ICON_KA]
Bien, podemos ir a otro piso desde[n]aquボ.

[msg P3_HERO2_MAPPING_ICON_KA_2]
ムAhora podemos seguir adelante sin[n]perdernos!

[msg P3_HERO2_MAPPING_CHANGE_]
ムGenial, ese color va a resaltar!

[msg P3_HERO2_MAPPING_CHANGE__2]
ムEsto me hace querer intentar mapear[n]tambi〒n!

[msg P3_HERO2_MAPPING_ICON_DE]
Formas de mejorar la legibilidad.

[msg P3_HERO2_MAPPING_ICON_DE_2]
ムSボ, dejemos todo lo que no[n]necesitamos!

[msg P3_HERO2_MAPPING_MEMO_1]
ムTenemos que asegurarnos de no[n]olvidar eso!

[msg P3_HERO2_MAPPING_MEMO_2]
メTal vez deberボa garabatear en[n]eso...? ムJa, solo bromeo!

[msg P3_HERO2_DOOR_OPEN_1]
ムVamos, vamos!

[msg P3_HERO2_DOOR_OPEN_2]
ムVamos a salir de aquボ!

[msg P3_HERO2_DOOR_OPEN_3]
ムPor aquボ!

[msg P3_HERO2_KARITORU_ENCOUN]
? ? Todavボa no hay nada que ver

[msg P3_HERO2_KARITORU_ENCOUN_2]
? ? Todavボa no hay nada que ver

[msg P3_HERO2_KARITORU_ENCOUN_3]
? ? Todavボa no hay 〒xito

