[msg P5_HERO_FOE_FOLLOW_START]
【FOEが追尾開始】 4ミーメ7セージ１

[msg P5_HERO_FOE_FOLLOW_START_2]
【FOEが追尾開始】 4ミーメ7セージ２

[msg P5_HERO_FOE_FOLLOW_START_3]
【FOEが追尾開始】 4ミーメ7セージ３

[msg P5_HERO_FOE_NEAR_1]
【FOEが近い】 4ミーメ7セージ１

[msg P5_HERO_FOE_NEAR_2]
【FOEが近い】 4ミーメ7セージ２

[msg P5_HERO_FOE_NEAR_3]
【FOEが近い】 4ミーメ7セージ３

[msg P5_HERO_FOE_FOLLOW_END_1]
【FOEO追尾がきsた】 4ミーメ7セージ１

[msg P5_HERO_FOE_FOLLOW_END_2]
【FOEO追尾がきsた】 4ミーメ7セージ２

[msg P5_HERO_FOE_FOLLOW_END_3]
【FOEO追尾がきsた】 4ミーメ7セージ３

[msg P5_HERO_KANSI_REACTION_1]
【監視吋メラリ威クション】 4ミーメ7セージ１

[msg P5_HERO_KANSI_REACTION_2]
【監視吋メラリ威クション】 4ミーメ7セージ２

[msg P5_HERO_KANSI_REACTION_3]
【監視吋メラリ威クション】 4ミーメ7セージ３

[msg P5_HERO_DENKISAKU_REACTI]
【電気柵リ威クション】 4ミーメ7セージ１

[msg P5_HERO_DENKISAKU_REACTI_2]
【電気柵リ威クション】 4ミーメ7セージ２

[msg P5_HERO_DENKISAKU_REACTI_3]
【電気柵リ威クション】 4ミーメ7セージ３

[msg P5_HERO_KYOUHU_REACTION_]
【強風リ威クション】 4ミーメ7セージ１

[msg P5_HERO_KYOUHU_REACTION__2]
【強風リ威クション】 4ミーメ7セージ２

[msg P5_HERO_KYOUHU_REACTION__3]
【強風リ威クション】 4ミーメ7セージ３

[msg P5_HERO_STAIR_FIND_1]
【階段発見】 4ミーメ7セージ１

[msg P5_HERO_STAIR_FIND_2]
【階段発見】 4ミーメ7セージ２

[msg P5_HERO_STAIR_FIND_3]
【階段発見】 4ミーメ7セージ３

[msg P5_HERO_TREASURE_FIND_1]
【宝箱発見】 4ミーメ7セージ１

[msg P5_HERO_TREASURE_FIND_2]
【宝箱発見】 4ミーメ7セージ２

[msg P5_HERO_TREASURE_FIND_3]
【宝箱発見】 4ミーメ7セージ３

[msg P5_HERO_CHECK_WALL_1]
【調Zpsr壁リ威クション】 4ミーメ7セージ１

[msg P5_HERO_CHECK_WALL_2]
【調Zpsr壁リ威クション】 4ミーメ7セージ２

[msg P5_HERO_CHECK_WALL_3]
【調Zpsr壁リ威クション】 4ミーメ7セージ３

[msg P5_HERO_SWITCH_FIND_1]
【ス姻75確認】 4ミーメ7セージ１

[msg P5_HERO_SWITCH_FIND_2]
【ス姻75確認】 4ミーメ7セージ２

[msg P5_HERO_SWITCH_FIND_3]
【ス姻75確認】 4ミーメ7セージ３

[msg P5_HERO_SHORTCUT_FIND_1]
【ショー:吋7:発見】 4ミーメ7セージ１

[msg P5_HERO_SHORTCUT_FIND_2]
【ショー:吋7:発見】 4ミーメ7セージ２

[msg P5_HERO_SHORTCUT_FIND_3]
【ショー:吋7:発見】 4ミーメ7セージ３

[msg P5_HERO_PARTY_DEAD_1]
【パー.斡O半分以上が死zHいr】 4ミーメ7セージ１

[msg P5_HERO_PARTY_DEAD_2]
【パー.斡ーO半分以上が死zHいr】 4ミーメ7セージ２

[msg P5_HERO_PARTY_DEAD_3]
【パー.斡ーO半分以上が死zHいr】 4ミーメ7セージ３

[msg P5_HERO_FOE_WARNING_NEAR]
【追尾状態OFOEが近い】 4ミーメ7セージ１

[msg P5_HERO_FOE_WARNING_NEAR_2]
【追尾状態OFOEが近い】 4ミーメ7セージ２

[msg P5_HERO_FOE_WARNING_NEAR_3]
【追尾状態OFOFが近い】 4ミーメ7セージ３

[msg P5_HERO_PARTY_HPTP10_1]
【パー.斡全体OＨＰＴＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_PARTY_HPTP10_2]
【パー.斡全体OＨＰＴＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_PARTY_HPTP10_3]
【パー.斡全体OＨＰＴＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_PARTY_HP10_1]
【パー.斡全体OＨＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_PARTY_HP10_2]
【パー.斡全体OＨＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_PARTY_HP10_3]
【パー.斡全体OＨＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_1PERSON_HPTP10_1]
【パー.斡誰かOＨＰＴＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_1PERSON_HPTP10_2]
【パー.斡誰かOＨＰＴＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_1PERSON_HPTP10_3]
【パー.斡誰かOＨＰＴＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_PARTY_TP10_1]
【パー.斡全体OＴＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_PARTY_TP10_2]
【パー.斡全体OＴＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_PARTY_TP10_3]
【パー.斡全体OＴＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_1PERSON_HP10_1]
【本人OＨＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_1PERSON_HP10_2]
【本人OＨＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_1PERSON_HP10_3]
【本人OＨＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_1PERSON_TP10_1]
【本人OＴＰが１０％以下】 4ミーメ7セージ１

[msg P5_HERO_1PERSON_TP10_2]
【本人OＴＰが１０％以下】 4ミーメ7セージ２

[msg P5_HERO_1PERSON_TP10_3]
【本人OＴＰが１０％以下】 4ミーメ7セージ３

[msg P5_HERO_ITEM_90_BATTLE_1]
【威姻.ム枠が９０％以上（バ:ル後）】 4ミーメ7セージ１

[msg P5_HERO_ITEM_90_BATTLE_2]
【威姻.ム枠が９０％以上（バ:ル後）】 4ミーメ7セージ２

[msg P5_HERO_ITEM_90_BATTLE_3]
【威姻.ム枠が９０％以上（バ:ル後）】 4ミーメ7セージ３

[msg P5_HERO_1PERSON_HP80_1]
【パー.斡誰かOＨＰが８０％以上】 4ミーメ7セージ１

[msg P5_HERO_1PERSON_HP80_2]
【パー.斡誰かOＨＰが８０％以上】 4ミーメ7セージ２

[msg P5_HERO_1PERSON_HP80_3]
【パー.斡誰かOＨＰが８０％以上】 4ミーメ7セージ３

[msg P5_HERO_BATTLE_CHANGE_DU]
【バ:ルかp4ンジョン担当Y)ビ切q替え】 4ミーメ7セージ１

[msg P5_HERO_BATTLE_CHANGE_DU_2]
【バ:ルかp4ンジョン担当Y)ビ切q替え】 4ミーメ7セージ２

[msg P5_HERO_BATTLE_CHANGE_DU_3]
【バ:ルかp4ンジョン担当Y)ビ切q替え】 4ミーメ7セージ３

[msg P5_HERO_ITEM_90_DUNGEON_]
【威姻.ム枠が９０％以上（ＤＧ出入q）】 4ミーメ7セージ１

[msg P5_HERO_ITEM_90_DUNGEON__2]
【威姻.ム枠が９０％以上（ＤＧ出入q）】 4ミーメ7セージ２

[msg P5_HERO_ITEM_90_DUNGEON__3]
【威姻.ム枠が９０％以上（ＤＧ出入q）】 4ミーメ7セージ２

[msg P5_HERO_DUNGEON_START_1]
【4ンジョン開始】 4ミーメ7セージ１

[msg P5_HERO_DUNGEON_START_2]
【4ンジョン開始】 4ミーメ7セージ２

[msg P5_HERO_DUNGEON_START_3]
【4ンジョン開始】 4ミーメ7セージ３

[msg P5_HERO_QUEST_START_1]
【ク夷ス:開始】 4ミーメ7セージ１

[msg P5_HERO_QUEST_START_2]
【ク夷ス:開始】 4ミーメ7セージ２

[msg P5_HERO_QUEST_START_3]
【ク夷ス:開始】 4ミーメ7セージ３

[msg P5_HERO_TOUHA_25_1]
【踏破率２５％】 4ミーメ7セージ１

[msg P5_HERO_TOUHA_25_2]
【踏破率２５％】 4ミーメ7セージ２

[msg P5_HERO_TOUHA_50_1]
【踏破率５０％】 4ミーメ7セージ１

[msg P5_HERO_TOUHA_50_2]
【踏破率５０％】 4ミーメ7セージ２

[msg P5_HERO_TOUHA_75_1]
【踏破率７５％】 4ミーメ7セージ１

[msg P5_HERO_TOUHA_75_2]
【踏破率７５％】 4ミーメ7セージ２

[msg P5_HERO_TOUHA_100_1]
【踏破率１００％】 4ミーメ7セージ１

[msg P5_HERO_TOUHA_100_2]
【踏破率１００％】 4ミーメ7セージ２

[msg P5_HERO_MAPPING_ICON_ALL]
【威姻コン（階段除く）y正確L配置した】 4ミーメ7セージ１

[msg P5_HERO_MAPPING_ICON_ALL_2]
【威姻コン（階段除く）y正確L配置した】 4ミーメ7セージ２

[msg P5_HERO_MAPPING_ICON_KAI]
【階段威姻コンy正確L配置した】 4ミーメ7セージ１

[msg P5_HERO_MAPPING_ICON_KAI_2]
【階段威姻コンy正確L配置した】 4ミーメ7セージ２

[msg P5_HERO_MAPPING_CHANGE_C]
【基本色以外Hマ7ピン雨した】 4ミーメ7セージ１

[msg P5_HERO_MAPPING_CHANGE_C_2]
【基本色以外Hマ7ピン雨した】 4ミーメ7セージ２

[msg P5_HERO_MAPPING_ICON_DEL]
【いpKい威姻コンy捨Gた】 4ミーメ7セージ１

[msg P5_HERO_MAPPING_ICON_DEL_2]
【いpKい威姻コンy捨Gた】 4ミーメ7セージ２

[msg P5_HERO_MAPPING_MEMO_1]
【メモy配置した】 4ミーメ7セージ１

[msg P5_HERO_MAPPING_MEMO_2]
【メモy配置した】 4ミーメ7セージ２

[msg P5_HERO_DOOR_OPEN_1]
Vamos.

[msg P5_HERO_DOOR_OPEN_2]
Por aqu胤.

[msg P5_HERO_DOOR_OPEN_3]
Sigamos adelante.

[msg P5_HERO_KARITORU_ENCOUNT]
【刈q取riOI夷ン吋胤ン:した】 4ミーメ7セージ１

[msg P5_HERO_KARITORU_ENCOUNT_2]
【刈q取riOI夷ン吋胤ン:した】 4ミーメ7セージ２

[msg P5_HERO_KARITORU_ENCOUNT_3]
【刈q取riOI夷ン吋胤ン:した】 4ミーメ7セージ３

