[msg THEODOR_FOE_FOLLOW_START]
斡Todo el mundo, un FOE los est茨[n]persiguiendo!

[msg THEODOR_FOE_FOLLOW_START_2]
Ay, parece que el FOE te ha visto.

[msg THEODOR_FOE_FOLLOW_START_3]
夷Eh? 斡Oh, te ruego que tengas[n]cuidado!

[msg THEODOR_FOE_NEAR_1]
斡Cuidado!

[msg THEODOR_FOE_NEAR_2]
斡Atenci吋n! 斡Hay un FOE!

[msg THEODOR_FOE_NEAR_3]
*jadeo* Esto podr胤a resultar[n]desastroso. 斡Ten cuidado!

[msg THEODOR_FOE_FOLLOW_END_1]
Parece que el FOE ha perdido las[n]ganas de perseguirte.

[msg THEODOR_FOE_FOLLOW_END_2]
Bien hecho. Estoy impresionado.

[msg THEODOR_FOE_FOLLOW_END_3]
Han logrado perder al FOE.

[msg THEODOR_KANSI_REACTION_1]
Deber胤as avanzar evitando las luces.

[msg THEODOR_KANSI_REACTION_2]
Sigue avanzando lo m茨s[n]silenciosamente posible.

[msg THEODOR_KANSI_REACTION_3]
Por favor, evita esas luces.

[msg THEODOR_DENKISAKU_REACTI]
No podr茨s avanzar a menos que[n]detengas la energ胤a.

[msg THEODOR_DENKISAKU_REACTI_2]
Debe haber un interruptor...

[msg THEODOR_DENKISAKU_REACTI_3]
Una puerta el姻ctrica... Esto me recuerda a[n]la de mi hermana... mejor olv胤dalo, no es[n]nada.

[msg THEODOR_KYOUHU_REACTION_]
斡Cuidado con las r茨fagas de viento!

[msg THEODOR_KYOUHU_REACTION__2]
"夷Por qu姻 no podr胤as quiz茨s montar en[n]el viento?"

[msg THEODOR_KYOUHU_REACTION__3]
"斡Oh! 斡Qu姻 terrible vendaval!"

[msg THEODOR_STAIR_FIND_1]
Hermana, creo que las escaleras est茨n[n]justo adelante...

[msg THEODOR_STAIR_FIND_2]
斡S胤, son las escaleras!

[msg THEODOR_STAIR_FIND_3]
Impresionante, hermana. Tienes una[n]aguda habilidad de observaci吋n.

[msg THEODOR_TREASURE_FIND_1]
斡Una recompensa en forma de cofre del[n]tesoro!

[msg THEODOR_TREASURE_FIND_2]
Tengo curiosidad por el contenido del[n]cofre del tesoro.

[msg THEODOR_TREASURE_FIND_3]
Un cofre del tesoro. Debo decir que estoy[n]emocionado de ver lo que hay dentro.

[msg THEODOR_CHECK_WALL_1]
斡Hay algo intrigante ah胤!

[msg THEODOR_CHECK_WALL_2]
夷Qu姻 es eso? 夷Podr胤as investigar?

[msg THEODOR_CHECK_WALL_3]
Creo que hay algo cerca.

[msg THEODOR_SWITCH_FIND_1]
Hay un interruptor. 夷Qu姻 hacemos?

[msg THEODOR_SWITCH_FIND_2]
夷Intentamos presionar ese[n]interruptor?

[msg THEODOR_SWITCH_FIND_3]
Parece que es un interruptor.

[msg THEODOR_SHORTCUT_FIND_1]
Esta pared... siento que tiene algo[n]m茨s de lo que parece.

[msg THEODOR_SHORTCUT_FIND_2]
夷Por qu姻 no revisamos esa pared?

[msg THEODOR_SHORTCUT_FIND_3]
Puede que haya propiedades desconocidas en[n]la pared que est茨 adelante.

[msg THEODOR_PARTY_DEAD_1]
斡夷C-chicos?! 夷Est茨n bien?

[msg THEODOR_PARTY_DEAD_2]
Por favor, considera regresar aqu胤.

[msg THEODOR_PARTY_DEAD_3]
Primero deber胤as curarte.

[msg THEODOR_FOE_WARNING_NEAR]
El FOE todav胤a est茨 decidido a[n]atraparte, me temo.

[msg THEODOR_FOE_WARNING_NEAR_2]
No se rendir茨...

[msg THEODOR_FOE_WARNING_NEAR_3]
Chicos, por favor tengan tanta[n]precauci吋n como puedan.

[msg THEODOR_PARTY_HPTP10_1]
Hermana, por favor c茨lmate. Solo[n]necesitan reagruparse y curarse.

[msg THEODOR_PARTY_HPTP10_2]
Me preocupan tus niveles de[n]agotamiento. Deber胤as regresar.

[msg THEODOR_PARTY_HPTP10_3]
Parece que mi hermana desea que[n]regreses.

[msg THEODOR_PARTY_HP10_1]
La salud de todos est茨 bastante[n]agotada.

[msg THEODOR_PARTY_HP10_2]
Deber胤as considerar la curaci吋n[n]inmediatamente.

[msg THEODOR_PARTY_HP10_3]
Por favor, prioriza la curaci吋n de[n]tus heridas.

[msg THEODOR_1PERSON_HPTP10_1]
夷No est茨 tu salud y tu resistencia[n]bastante baja?

[msg THEODOR_1PERSON_HPTP10_2]
夷Por qu姻 no te curas en este momento?

[msg THEODOR_1PERSON_HPTP10_3]
Parece que apenas puedes mantenerte[n]en pie... 夷Quiz茨 deber胤as curarte?

[msg THEODOR_PARTY_TP10_1]
La energ胤a de todos es baja...[n]夷Quieren hablar de eso?

[msg THEODOR_PARTY_TP10_2]
Deber胤as cambiar tu estrategia por tu[n]energ胤a.

[msg THEODOR_PARTY_TP10_3]
斡Bien dicho, hermana! 斡Eso es un[n]consejo maravilloso!

[msg THEODOR_1PERSON_HP10_1]
Por favor, ten cuidado con tu salud.

[msg THEODOR_1PERSON_HP10_2]
Te pido que primero te cures.

[msg THEODOR_1PERSON_HP10_3]
夷Est茨s estable de salud?

[msg THEODOR_1PERSON_TP10_1]
Sugiero que cambies tus t茨cticas de[n]batalla.

[msg THEODOR_1PERSON_TP10_2]
夷Tienes suficiente energ胤a para esto?

[msg THEODOR_1PERSON_TP10_3]
夷Has atendido tus necesidades de[n]energ胤a?

[msg THEODOR_ITEM_90_BATTLE_1]
斡夷Hermana?! 斡夷Tiraste mis posesiones[n]m茨s preciadas?!

[msg THEODOR_ITEM_90_BATTLE_2]
夷No est茨 tu inventario un poco lleno?

[msg THEODOR_ITEM_90_BATTLE_3]
Por favor, ven a mi tienda si[n]necesitas ordenar tus cosas.

[msg THEODOR_1PERSON_HP80_1]
斡Todo el mundo, un trabajo incre胤ble,[n]de verdad!

[msg THEODOR_1PERSON_HP80_2]
斡夷H-hermana?!, 斡por favor abstente de[n]agitar los brazos as胤!

[msg THEODOR_1PERSON_HP80_3]
夷Hermana? Tal vez ser胤a mejor que guardes[n]tu baile de alegr胤a para ti misma...

[msg THEODOR_BATTLE_CHANGE_DU]
■: [f 0 1 4]\cHFF

[msg THEODOR_BATTLE_CHANGE_DU_2]
■: [f 0 1 4]\cHFF

[msg THEODOR_BATTLE_CHANGE_DU_3]
■:

[msg THEODOR_ITEM_90_DUNGEON_]
斡夷Hermana?! 斡夷Tiraste mis posesiones[n]m茨s preciadas?!

[msg THEODOR_ITEM_90_DUNGEON__2]
夷No est茨 tu inventario un poco lleno?

[msg THEODOR_ITEM_90_DUNGEON__3]
Por favor, ven a mi tienda si[n]necesitas ordenar tus cosas.

[msg THEODOR_DUNGEON_START_1]
...Y yo, Th-Theodore, quienes[n]actuaremos como tu navegador.

[msg THEODOR_DUNGEON_START_2]
Y su hermano, Theodore. Por favor,[n]ten paciencia con nosotros.

[msg THEODOR_DUNGEON_START_3]
Bueno, vamos a empezar la[n]exploraci吋n.

[msg THEODOR_QUEST_START_1]
La proyecci吋n especial ha comenzado.

[msg THEODOR_QUEST_START_2]
Mi hermana y yo te acompa隠aremos[n]hasta el final.

[msg THEODOR_QUEST_START_3]
夷Empezamos?

[msg THEODOR_TOUHA_25_1]
Parece que acabas de empezar a[n]recorrer este piso.

[msg THEODOR_TOUHA_25_2]
Probablemente haya m茨s por venir.

[msg THEODOR_TOUHA_50_1]
Qu姻 afortunado... Has llegado a la[n]mitad.

[msg THEODOR_TOUHA_50_2]
Han llegado a la mitad. Claramente,[n]son los indicados para esta tarea.

[msg THEODOR_TOUHA_75_1]
Solo queda un poquito de piso sin[n]explorar.

[msg THEODOR_TOUHA_75_2]
斡Un poco m茨s y este mapa est茨[n]completo!

[msg THEODOR_TOUHA_100_1]
斡Incre胤ble! 斡El mapa est茨 completo!

[msg THEODOR_TOUHA_100_2]
El mapa est茨 completo. Lo han hecho[n]bien.

[msg THEODOR_MAPPING_ICON_ALL]
Est茨s dibujando el mapa con[n]precisi吋n.

[msg THEODOR_MAPPING_ICON_ALL_2]
Hermana... 夷Es eso verdad...?

[msg THEODOR_MAPPING_ICON_KAI]
Tienes un excelente conocimiento de[n]d吋nde est茨n las escaleras.

[msg THEODOR_MAPPING_ICON_KAI_2]
夷Eh? 斡Hermana, no he preparado nada[n]de eso!

[msg THEODOR_MAPPING_CHANGE_C]
Qu姻 incre胤ble buen gusto art胤stico.

[msg THEODOR_MAPPING_CHANGE_C_2]
Espero ver el mapa en su 雨ltima y[n]gloriosa versi吋n.

[msg THEODOR_MAPPING_ICON_DEL]
斡夷Hermana?! 斡夷Quieres deshacerte de[n]m胤?!

[msg THEODOR_MAPPING_ICON_DEL_2]
Siempre es mejor volver y corregir[n]tus errores.

[msg THEODOR_MAPPING_MEMO_1]
Esa atenci吋n al detalle es[n]espl姻ndida.

[msg THEODOR_MAPPING_MEMO_2]
Bien, lo est茨s notando.

[msg THEODOR_DOOR_OPEN_1]
↑

[msg THEODOR_DOOR_OPEN_2]
↑

[msg THEODOR_DOOR_OPEN_3]
↑

[msg THEODOR_KARITORU_ENCOUNT]
Ojal茨 fuera mentira, 斡pero viene el[n]Segador!

[msg THEODOR_KARITORU_ENCOUNT_2]
El Segador se est茨 acercando a ti.[n]斡Por favor, cu胤date!

[msg THEODOR_KARITORU_ENCOUNT_3]
Estoy sintiendo algo, y es 斡el[n]Segador!

