[msg MSG_000 [P4 Protag]]
[f 0 5 65278][f 2 1][f 4 6 1 10 0 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1018]What is this room?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Look at that huge machine...[n]Is it a projector?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 0]That seems to be accurate. I have[n]confirmed four of them within[n]visual range.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 7 6 0 1][f 3 1 1 0 0 7095]Ain't there somethin' weird about the[n]light comin' from that projector?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The colors seem all gross. Is the movie[n]messed up somehow?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 0]It looks like it's the negatives of a film[n]that are being screened.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 1][f 3 1 1 0 0 61172]That's right. The reason that negatives[n]make people feel sick is the inversion[n]of colors flipping the light and dark...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The film is de-inverted during printing,[n]so in the end, the colors come out like[n]you normally see them on the screen.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Oh, I see...[f 2 7 1 20 8 32][e]
[f 0 5 65278][f 2 1]Is there more to this?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]*snore*[f 2 7 1 20 8 32][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 100 4][f 3 1 1 0 0 26533][f 3 1 6 0 0 500][f 6 1 2 0 0 9]She can't help it, she's an enthusiast.[n]Just be polite―smile, nod along...[n]There you go.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 100 4][f 3 1 1 0 0 26534][f 6 1 2 0 0 10]Hey, no dozing off! You have to listen[n]until she's finished.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 0]Since any inverted film is called[n]"negatives," re-reversed ones could[n]be referred to as the "positives."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]There's also something called "reversal[n]film" that records positive images right[n]away, instead of negative images...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 0]But movies tend to be shot in negatives[n]because touch-ups and duplication are[n]easier with that type of film.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 7 4 0 0][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]R-Right. I, uh... I didn't get any of that.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 1 0][f 3 1 1 0 0 0]Oh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8031]You seem to be quite an expert on[n]the matter, Hikari-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Huh? Oh, um... I guess I get really[n]worked up when talking about[n]movies...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 2 0 0][f 3 1 1 0 0 0]That's fine. Gettin' worked up over[n]something you like is normal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hmm, negative images and positive[n]images... Don't those remind you of[n]something, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_016 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Negative emotions.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Positive emotions.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I don't know what you mean.[f 2 7 1 20 6 32][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 23115][f 6 1 2 0 0 6]Exactly―that![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 6][f 3 1 1 0 0 0]Based on what we've experienced, they[n]certainly seem like analogous concepts...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 6][f 3 1 1 0 0 28072]I think he means in regards to positive[n]and negative human emotions. They[n]certainly seem like analogous concepts...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Y-Yeah, "analogous concepts"... Just like,[n]uh... pork cheek and pork butt, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 3 0 1 0][f 3 1 1 0 0 3035][f 6 1 2 0 0 6]Do you have any clue what we're talking[n]about? And is meat REALLY the only[n]thing on your mind!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 27 12 0 1][f 3 1 1 0 0 0]Well, for example, cheerful people are[n]called "positive," while gloomy people[n]are referred to as "negative"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0]Ahh, I get it. This is starting to make[n]sense now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 24 4 1 1][f 3 1 1 0 0 24112]What we really need to determine[n]is where these negatives are being[n]screened.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 100 0][f 3 1 1 0 0 0][f 3 1 6 0 0 500][f 6 1 2 0 0 4]Hmm... Do you think it has anything to[n]do with the film that you're walking on?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 1][f 3 1 1 0 0 0]Oh, good point. This film covering the[n]ground―is this more of the negatives?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 0][f 3 1 1 0 0 14504][f 3 1 6 0 0 500]It seems to head into all sorts of[n]directions. We'll keep looking into it.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If we find anything out, we'll update[n]you right away.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 0]Please do so.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0]It seems we should leave our questions[n]about this to our navigators. We have[n]our own duties to carry out here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16122][f 6 1 2 0 0 6]Yes, let's get moving![n][f 1 3 65535][f 1 1][e]

