[msg MSG_000 [Futaba]]
Oye, parece que Zabby se estホ cansando[n]de esperar a que ustedes vengan a[n]descubrir lo que tiene que decir...
Ella estホ acurrucada junto a la mホquina de[n]entradas... Navegar mientras me fulmina con la[n]mirada en silencio se estホ volviendo realmente[n]incポmodo.

[msg MSG_001 [Ann]]
Oh, sボ, dijo que la mホquina empezポ a[n]brillar de repente. メDeberボamos volver,[n]Joker?

[sel SEL_002 top]
Sボ, volvamos.
Lo comprobaremos mホs tarde.
Iremos cuando podamos.

[msg MSG_003 [Teddie]]
Mmm, uno no debe hacer esperar a una[n]dama. Debes ser un caballero de corazポn,[n]Joker.

[msg MSG_004 [Teddie]]
Mmm, メesto es parte de algマn plan para[n]hacerte el difボcil? Tienes las[n]habilidades para ser un gigolポ, Joker...

[msg MSG_005 [Futaba]]
Oh, esa lボnea significa que nunca[n]aparecerホs...

[msg MSG_006 [Teddie]]
Ah, la forma en que esquivas casualmente[n]asuntos como ese traiciona tus talentos[n]como gigolポ...

[msg MSG_007 [Teddie]]
Parece que ha aparecido un rival serio,[n]メverdad, Maestro?

[msg MSG_008 [P4 Hero]]
メMmm? メQu〒 quieres decir con eso?
Si se siente sola, メno es nuestro deber[n]ir y pasar tiempo con ella?

[msg MSG_009 [Futaba]]
ムWhoa, esa fue la lボnea de un jugador[n]importante! Apuesto a que eres del tipo[n]elocuente protagonista.

[msg MSG_010 [Morgana]]
No entiendo de qu〒 estホn hablando[n]todos... pero al menos deberボamos ir a[n]escuchar lo que ella tiene que decir.
Estamos en un buen punto, asボ que[n]volvamos. Continuaremos la bマsqueda de[n]Yosuke despu〒s de eso.

