[msg MSG_000 [Akechi]]
Esta isla parece ser bastante grande.

[msg MSG_001 [Makoto]]
Cierto... Debe haber sido necesario,[n]considerando lo grandes que son los[n]dinosaurios.

[msg MSG_002 [Futaba]]
...夷Mmm?

[msg MSG_003 [Makoto]]
夷Qu姻 pasa, Oracle? 夷Encontraste algo?

[msg MSG_004 [Futaba]]
Bueno... Estoy recibiendo lecturas de[n]algo mucho m茨s fuerte que lo de antes...

[msg MSG_005 [Yusuke]]
夷Son FOEs?

[msg MSG_006 [Haru]]
Oh, no, 夷podr胤an ser los T-Rex de los[n]que est茨bamos hablando?

[msg MSG_007 [Ryuji]]
Mierda... Solo hab胤a pensado en un[n]T-Rex, pero un FOEs ser胤a a雨n m茨s loco.

[sel SEL_008 top]
Es una locura.
Estaremos bien.
Vamos a correr.

[msg MSG_009 [Ryuji]]
夷Verdad? Esos tipos son monstruos de[n]pel胤culas cl茨sicas.
Como un feroz T-Rex comi姻ndole la cabeza[n]a cualquiera que huya de 姻l...

[msg MSG_010 [Morgana]]
Vaya, 夷realmente est茨n asust茨ndose?

[msg MSG_011 [Ryuji]]
Oh, pero tenemos un gato aqu胤, quiz茨[n]pueda ser una buena carnada.

[msg MSG_012 [Morgana]]
N-noooo 斡Espera, no soy sabroso! 斡Ni un[n]gato!

[msg MSG_013 [Ryuji]]
Dices eso, pero esos tipos son monstruos[n]cl茨sicos de las pel胤culas.
Como un feroz T-Rex comi姻ndole la cabeza[n]a cualquiera que huya de 姻l...

[msg MSG_014 [Morgana]]
夷Qu姻 es esto? 夷Te est茨s volviendo loco,[n]Skull?

[msg MSG_015 [Ryuji]]
Oh, pero tenemos un gato aqu胤, quiz茨[n]pueda ser una buena carnada.

[msg MSG_016 [Morgana]]
N-noooo 斡Espera, no soy sabroso! 斡Ni un[n]gato!

[msg MSG_017 [Ryuji]]
斡Espera un segundo!
Si empiezas a correr de un T-Rex, 斡solo[n]te pondr茨s m茨s en peligro!

[msg MSG_018 [Akechi]]
Ah, el cl茨sico clich姻... El primero en[n]huir es el primero en ser comido.

[msg MSG_019 [P3 Fem Protag]]
ィつれ わまるぽぺぽ りゎま ゅよれ ぽもょよれぺゎるもよれ ぼぺるょウわよるよれ れよょ[n]ろまるるもほゅまれテテテ らまるよ まれろよを れまむゎるぺ ぽま りゎま[n]まれろぺるまゆよれ ほもまょ れも ょよれ りゎまぽぺゆよれ ゃゎょろよれ!

[msg MSG_020 [Haru]]
斡Aj茨! 斡Si la situaci吋n empeora, lo[n]partir姻 por la mitad con mi hacha!

[msg MSG_021 [Ann]]
斡Ja, ja, ja, entonces lo asar姻 vivo con[n]mis llamas!

[msg MSG_022 [Makoto]]
Me pregunto si sus ojos son su punto[n]d姻bil. Podr胤a intentar comprobarlo.

[msg MSG_023 [Morgana]]
Creo que las chicas son m茨s valientes[n]que nosotros...

[msg MSG_024 [Ryuji]]
No podemos permitir que nos superen...[n]斡Vamos a dar lo mejor de nosotros[n]tambi姻n, Joker!

