[msg MSG_000]
Junessic Land, Fin de la Isla...

[msg MSG_001 [Kanji]]
ムFinalmente los alcanzamos! ムHola,[n]dinos!

[msg MSG_002 [Herbボvoro Tボmido]]
...

[msg MSG_003 [Yosukesaurio]]
...

[msg MSG_004 [Kanji]]
Vaya, メcuホl es su problema?

[msg MSG_005 [Teddie]]
Mmm, se estホn comportando raro... メPasa[n]algo?

[msg MSG_006 [Yosukesaurio]]
...No estホ aquボ.

[msg MSG_007 [Yosuke]]
メEh? メEstホn deprimidos porque perdieron[n]algo?

[msg MSG_008 [Herbボvoro Malhumorado]]
Claro que no. Es el paraボso para[n]herbボvoros... ムTodo fue inventado!

[msg MSG_009 [Makoto]]
Espera, メeste lugar es el supuesto[n]paraボso?

[msg MSG_010 [Yusuke]]
Parece ser un lote vacボo cercado.

[msg MSG_011 [Yosuke]]
Bueno, メmiraron las indicaciones de[n]nuevo? Tal vez este es el lugar[n]equivocado...

[msg MSG_012 [Yosukesaurio]]
ムRevis〒 el libro cuando llegamos aquボ![n]ムEste es el lugar exacto que[n]describieron!
Hemos recorrido toda la isla y aマn no[n]encontramos nuestro paraボso...

[sel SEL_013 top]
Tal vez hay un camino oculto.
メIntentaron con la contraseワa secreta?
Supongo que es hora de rendirse.

[msg MSG_014 [Yosuke]]
Sボ, lo que 〒l dijo. Tal vez hay un[n]pasaje oculto que los lleva a otro[n]lugar.

[msg MSG_015 [Chie]]
Entonces, メhay una palabra secreta que[n]tenemos que adivinar? メTenemos alguna[n]pista?

[msg MSG_016 [Yukiko]]
No, Chie, ムla contraseワa secreta siempre[n]es "ホbrete s〒samo"!

[msg MSG_017 [Akechi]]
Mm... No quiero arruinar la fiesta, pero[n]no hay nada en lo que escribir una[n]contraseワa.

[msg MSG_018 [Yosuke]]
ムメQu〒 te pasa?!

[msg MSG_019 [Rise]]
No sirve de nada... Revisamos toda la[n]zona, pero parece que esto no es mホs que[n]un callejポn sin salida.

[msg MSG_020 [Futaba]]
Incluso cuando ampliamos nuestro[n]alcance, no vimos nada que se pareciera[n]a un paraボso.

[msg MSG_021 [Herbボvoro Enorme]]
ムVaya "paraボso" este! ムNo me hagas reボr![n]ムHemos sido engaワados, todos nosotros!

[msg MSG_022 [Herbボvoro Malhumorado]]
...メNo eres tマ el que nos dijo de este[n]"paraボso"?

[msg MSG_023 [Yosukesaurio]]
ムメQu〒...?! ムメYo?!
Solo lo leボ en algマn libro humano...[n]ムFue solo informaciポn!

[msg MSG_024 [Herbボvoro Malhumorado]]
Nos arrastraste a todos a esto, メy ahora[n]intentas echarnos la culpa?

[msg MSG_025 [Yosukesaurio]]
Ninguno de ustedes cuestiono la idea.[n]Solo dijeron: "ムSi hay un paraボso para[n]nosotros, iremos!"
Es por eso que todos hemos estado[n]arriesgando nuestras vidas...

[msg MSG_026 [Herbボvoro Testarudo]]
ムExacto! La vida de toda la manada estホ[n]en peligro, ムy es tu culpa!

[msg MSG_027 [Yosukesaurio]]
Pero eso es... Eso es porque pens〒 que[n]serボa lo mejor para nosotros...

[msg MSG_028 [Herbボvoro Malhumorado]]
ムEmpecemos la votaciポn!
ムTodos los que piensen que es su culpa[n]estemos en peligro, levanten la mano!

[msg MSG_029 [Herbボvoro Inquieto]]
Entonces, eh... メQu〒 deberボamos votar?

[msg MSG_030 [Herbボvoro Tボmido]]
S-si todos dicen que es su culpa...[n]entonces yo lo creo tambi〒n...

[msg MSG_031 [Yosukesaurio]]
No... Pero yo... ムTienen que escucharme!

[msg MSG_032 [Herbボvoro Malhumorado]]
Parece que es unホnime. Asボ que...
ムTodos los que piensan que deberボamos[n]expulsarlo por poner en peligro a la[n]manada, levanten la mano!

[msg MSG_033 [Herbボvoro Enorme]]
ムSボ!

[msg MSG_034 [Herbボvoro Inquieto]]
Sボ.

[msg MSG_035 [Herbボvoro Tボmido]]
...S-sボ.

[msg MSG_036 [Yosukesaurio]]
ムE-esperen un momento!
Si me echan... メQu〒 se supone que har〒?

[msg MSG_037 [Herbボvoro Enorme]]
Esta manada siempre ha seguido la regla[n]de la mayorボa. メNo lo recuerdas?

[msg MSG_038 [Herbボvoro Inquieto]]
Cuando fuimos atacados por ese[n]carnボvoro, te uniste a la votaciポn...
Y... esto no es diferente, メverdad?

[msg MSG_039 [Yosukesaurio]]
ム...!

[msg MSG_040 [Ryuji]]
ムDejen de atacar al chico! ムメPor qu〒[n]todos lo critican?!

[msg MSG_041 [P4 Hero]]
No puedo creer esto... No hay forma de[n]que asボ es como resuelvan sus problemas.

[sel SEL_042 top]
Tenemos que intervenir.
Esto estホ mal.
Dej〒moslos en paz.

[msg MSG_043 [Yosuke]]
Sボ, apresur〒monos y detengホmoslos...[n]ムEstホn a punto de expulsarlo de la[n]manada!

[msg MSG_044 [Naoto]]
Estoy de acuerdo con Joker, saltemos y[n]pongamos fin a esto.

[msg MSG_045 [Yosuke]]
メE-estホs bromeando?
Lo siento, pero... ムSimplemente, no[n]puedo ignorar esto!

[msg MSG_046 [Yosuke]]
ムEspera un momento! メNo son todos parte[n]del mismo grupo?
Todo lo que estホn haciendo es votar por[n]lo que otro piensa. メEso define a la[n]mayorボa?

[msg MSG_047 [Herbボvoro Tボmido]]
B-bien...

[msg MSG_048 [Herbボvoro Malhumorado]]
ムSomos presas indefensas! ムNunca[n]sobreviviremos si no nos mantenemos y[n]actuamos juntos!

[msg MSG_049 [Herbボvoro Enorme]]
メPuedes entender siquiera lo que se[n]siente vivir constantemente con miedo a[n]los carnボvoros?
Los que se comportan de forma egoボsta[n]deben ser expulsados. ムEs la マnica[n]manera de sobrevivir!

[msg MSG_050 [Naoto]]
Entendemos lo que dices...
Sin embargo, son capaces de utilizar[n]m〒todos de autopreservaciポn ademホs de[n]expulsar a quienes causan problemas.
メNo serボa mejor elegir un medio de[n]supervivencia en el que nadie sea[n]sacrificado?

[msg MSG_051 [Herbボvoro Enorme]]
Estホ bien, メy cuホles son esos medios?
No es que queramos hacerlo... ムEsta es[n]la マnica manera en que podemos[n]protegernos!

[msg MSG_052 [Herbボvoro Malhumorado]]
ムS-sボ! Si obedecemos la decisiポn de la[n]mayorボa, sabemos que hemos hecho lo[n]correcto.

[msg MSG_053 [Herbボvoro Inquieto]]
A-ademホs... メNo eras bastante amigable[n]con esos humanos?
Todo esto sucediポ porque tambi〒n creボste[n]en un libro humano...

[msg MSG_054 [Yosukesaurio]]
Yo... ムNo quise que esto pasara!

[msg MSG_055 [Herbボvoro Enorme]]
No importa, ya estホ decidido. Tomamos[n]una votaciポn y la mayorボa decidiポ[n]expulsarte.

[msg MSG_056 [Yosukesaurio]]
ムN-no, por favor! No quiero estar[n]solo...

[msg MSG_057 [Herbボvoro Malhumorado]]
Si estホs tan decidido a no ser[n]expulsado, ムentonces demuestra que[n]realmente estホs de nuestro lado!

[msg MSG_058 [Herbボvoro Enorme]]
ムLos humanos son quienes nos engaワaron[n]para venir aquボ, con ese terrible libro!
Si compartes la misma opiniポn, メno[n]deberボas poder hacer que esos humanos[n]allボ paguen por ello?

[msg MSG_059 [Yosukesaurio]]
メQu〒? ムメHacer que ellos... hacer que[n]paguen?!

[msg MSG_060 [Ann]]
ムOye, メde dポnde sacaste esa idea?! ムEse[n]libro no tiene nada que ver con[n]nosotros!

[msg MSG_061 [Herbボvoro Malhumorado]]
Si quieres volver a unirte a nuestro[n]grupo, debes demostrar que encajas con[n]nosotros.

[msg MSG_062 [Yosuke]]
ムMaldita sea, esto es tan estマpido!

[msg MSG_063 [Yosukesaurio]]
Yo... Yo, ah...

[msg MSG_064 [Morgana]]
ムOye, mant〒n la compostura, no te[n]limites a estar de acuerdo con ellos!

[msg MSG_065 [Yosukesaurio]]
No... no quiero ser abandonado...
ムYo no hice nada malo! ムTodo es porque[n]ustedes, los humanos, metieron sus[n]estマpidas narices en esto!

