[msg MSG_000 [Yosuke]]
斡Bien! 斡夷Soy yo o cambiamos todo?!

[msg MSG_001 [Rise]]
斡Seguro que s胤! 斡Todos ten胤an sonrisas[n]tan felices al final!

[msg MSG_002 [Hikari]]
Bienvenidos.

[msg MSG_003 [Ann]]
斡Gracias! 夷Te aseguraste de ver toda la[n]pel胤cula hasta el final?

[msg MSG_004 [Hikari]]
Mmm, lo hice.

[msg MSG_005 [Futaba]]
Eh, O-oye, Hikari... 夷Qu姻 opinas al[n]respecto?

[msg MSG_006 [Hikari]]
Um...

[msg MSG_007 [Nagi]]
Est茨 bien... Puedes decirles c吋mo te[n]sentiste, con tus propias palabras.

[msg MSG_008 [Hikari]]
Mmm... Bueno...
La pel胤cula fue realmente...[n]maravillosa.

[msg MSG_009 [Futaba]]
斡夷E-en serio?!

[msg MSG_010 [Hikari]]
Mmm... De verdad.

[msg MSG_011 [Futaba]]
Ya veo. Me alegra escuchar eso...

[msg MSG_012 [P3 Fem Protag]]
Oye, Hikari... 夷Qu姻 te gusto de la[n]pel胤cula?

[msg MSG_013 [Hikari]]
Se enfrent吋 al carn胤voro... Aunque[n]estaba solo...
Todos los dem茨s estaban en contra,[n]pero... 姻l reuni吋 el valor para[n]hacerlo...

[msg MSG_014 [Futaba]]
夷Te refieres al Yosukesaurio, 夷verdad?[n]夷Y? 夷Y?

[msg MSG_015 [Hikari]]
Y luego, los otros herb胤voros estaban[n]realmente asustados... pero tambi姻n[n]encontraron el coraje.
Actu吋 seg雨n lo que realmente sent胤a...[n]pero no se qued吋 solo con eso...

[msg MSG_016 [Yosuke]]
Eso es porque los amigos pueden decir lo[n]que realmente sienten, 夷verdad,[n]compa隠ero?

[msg MSG_017 [P4 Hero]]
Correcto.

[msg MSG_018 [Hikari]]
Hasta ahora, pensaba que ten胤a que[n]pensar y decir lo mismo que mis amigos.
De lo contrario, no podr胤a estar con[n]ellos... Pensaba que era natural seguir[n]a la multitud...
Pero eso no era verdad. Es exactamente[n]como dijiste, Futaba...

[msg MSG_019 [Futaba]]
Hikari, 夷me llamaste por mi nombre?

[msg MSG_020 [Nagi]]
Al igual que con la pel胤cula anterior,[n]el final al que guiaste esta pel胤cula[n]fue simplemente magn胤fico.

[msg MSG_021 [Hikari]]
夷Tambi姻n lo crees, Nagi?

[msg MSG_022 [Nagi]]
S胤. La violencia por n雨meros siempre[n]ocurre en los grupos...
Solo puedo suponer que muchos fueron[n]maltratados en esa pel胤cula hasta que[n]ustedes entraron y la cambiaron.
Es innegable que tales problemas tambi姻n[n]pueden ocurrir en nuestro mundo...

[msg MSG_023 [Hikari]]
...

[msg MSG_024 [Nagi]]
Sin embargo, gracias a ustedes, pudimos[n]presenciar un nuevo resultado.
Al igual que Hikari y los dinosaurios[n]que aparecieron en esa pel胤cula... yo[n]tambi姻n me siento muy feliz.
Por favor, perm胤tanme expresar mi[n]gratitud tambi姻n...
Muchas gracias por esa maravillosa[n]pel胤cula.

[sel SEL_025 top]
Solo hicimos lo que siempre hacemos.
No hay necesidad de agradecimientos.
Por supuesto, lo hicimos genial.

[msg MSG_026 [Chie]]
斡Vaya, trat吋 toda esa pesadilla como si[n]fuera pan comido!

[msg MSG_027 [Teddie]]
*silbido* 斡Qu姻 genial!

[msg MSG_028 [Morgana]]
Vaya, qu姻 presumido...
Aunque, en realidad, 斡lo hicimos genial[n]all胤 dentro!

[msg MSG_029 [Doe]]
...

[msg MSG_030 [Chie]]
斡Aaaaaaah! 斡me sorprendiste!

[msg MSG_031 [P4 Hero]]
Doe...

[msg MSG_032 [P4 Hero]]
As胤 que, eso es Doe...

[msg MSG_033 [Doe]]
Nghh... Nnnghhh...

[msg MSG_034 [Haru]]
Su expresi吋n... 夷Est茨 a punto de soltar[n]otra llave?

[msg MSG_035 [Hikari]]
A-ah...

[msg MSG_036 [P3 Fem Protag]]
Hikari, ven!

[msg MSG_037 [Doe]]
Ngh... 斡Nghhhhh!

[msg MSG_038 [Yosuke]]
斡夷Qu姻...?! Me hablaste de esto, 斡夷pero[n]realmente acaba de salir una llave de[n]sus ojos?!

[msg MSG_039 [Yukiko]]
夷Podr胤a ser una llave para la puerta[n]principal?

[msg MSG_040 [Naoto]]
S胤, creo que es la segunda. Prob姻mosla.

