[msg MSG_000 [Akechi]]
Esta isla parece ser bastante grande.

[msg MSG_001 [Makoto]]
Cierto... Debe haber sido necesario, considerando lo grandes que son los dinosaurios.

[msg MSG_002 [Futaba]]
...メMmm?

[msg MSG_003 [Makoto]]
メQu〒 pasa, Oracle? メEncontraste algo?

[msg MSG_004 [Futaba]]
Bueno... Estoy recibiendo lecturas de algo mucho mホs fuerte que las anteriores...

[msg MSG_005 [Yusuke]]
メSon FOEs?

[msg MSG_006 [Haru]]
Oh, no, メserホn los T-Rex de los que estホbamos hablando?

[msg MSG_007 [Ryuji]]
Mierda... Solo habボa pensado en los T-Rex, pero un FOE serボa aマn mホs loco.

[sel SEL_008 top]
Es una locura.
Estaremos bien.
Vamos a correr.

[msg MSG_009 [Ryuji]]
メVerdad? Esos tipos son monstruos de pelボculas clホsicas.
Como un feroz T-Rex comi〒ndole la cabeza a cualquiera que huya de 〒l...

[msg MSG_010 [Morgana]]
Ah, メrealmente estホn asustホndose?

[msg MSG_011 [Ryuji]]
Oh, pero tenemos un gato aquボ, quizホ pueda sea una buena carnada.

[msg MSG_012 [Morgana]]
N-noooo ムEspera, no soy sabroso! ムNI UN GATO!

[msg MSG_013 [Ryuji]]
Dices eso, pero esos tipos son monstruos clホsicos de pelボculas.
Como un feroz T-Rex comi〒ndole la cabeza a cualquiera que huya de 〒l...

[msg MSG_014 [Morgana]]
メQu〒 es esto? メTe estホs volviendo loco, Skull?

[msg MSG_015 [Ryuji]]
Oh, pero tenemos un gato aquボ, quizホ pueda ser una buena carnada.

[msg MSG_016 [Morgana]]
N-noooo ムEspera, no soy sabroso! ムNI UN GATO!

[msg MSG_017 [Ryuji]]
ムEspera un segundo!
Si empiezas a correr de un T-Rex, ムsolo te pondrホs mホs en peligro!

[msg MSG_018 [Akechi]]
Ah, el clホsico clich〒... El primero en huir es el primero en ser comido.

[msg MSG_019 [P3 Fem Protag]]
ムEs verdad que los dinosaurios carnボvoros son terribles... pero estoy segura de que estaremos bien si nos mantenemos juntos!

[msg MSG_020 [Haru]]
ムAjホ! ムSi la situaciポn empeora, lo partir〒 por la mitad con mi hacha!

[msg MSG_021 [Ann]]
ムJa, ja, ja, entonces lo asar〒 vivo con mis llamas!

[msg MSG_022 [Makoto]]
Me pregunto si sus ojos son su punto d〒bil. Podrボa intentar comprobarlo.

[msg MSG_023 [Morgana]]
Creo que las chicas son mホs valientes que nosotros...

[msg MSG_024 [Ryuji]]
No podemos permitir que nos superen... ムVamos a dar lo mejor de nosotros tambi〒n, Joker!

