[msg MSG_000 [Ryuji]]
Esa parece ser una puerta realmente[n]peligrosa...

[msg MSG_001 [Morgana]]
S胤, mi intuici吋n de ladr吋n fantasma est茨[n]gritando "PELIGRO" ahora mismo.

[sel SEL_002 top]
No tocar, 夷entendido?
Intentemos tocarlo.
Es tu imaginaci吋n.

[msg MSG_003 [Ryuji]]
夷Est茨s intentando enga隠arme para que lo[n]toque?

[msg MSG_004 [Naoto]]
Por favor, esperen. Creo que ser胤a mejor[n]no tocarlo tan descuidadamente.

[msg MSG_005 [Naoto]]
Por favor, espera un momento. 夷Por qu姻[n]no lo investigamos m茨s?

[msg MSG_006 [Yosukesaurio]]
斡Oh! 斡S姻 lo que es!
Es una m茨quina para atrapar carn胤voros.[n]斡[f 0 1 2]Si la tocas, recibes una superdescarga[n]el姻ctrica.[f 0 1 0]!

[msg MSG_007 [Yusuke]]
夷Mmm? 夷Eso significa que hay una[n]corriente el姻ctrica corriendo a trav姻s[n]de ella?

[msg MSG_008 [Ann]]
Espera, si esto es para dinosaurios[n]grandes y aterradores, 夷no ser胤a a雨n[n]peor si un humano lo toca?

[msg MSG_009 [Morgana]]
Parece que no hay nada que podamos[n]hacer, entonces...

[msg MSG_010 [Yosukesaurio]]
斡No te preocupes! 斡Conozco un buen[n]truco!

[msg MSG_011 [Haru]]
夷Sabes c吋mo evitar esto?

[msg MSG_012 [Yosukesaurio]]
斡Claro! Este tipo de puertas tambi姻n[n]est茨n en otros lugares.
Si recuerdo bien, tienen[f 0 1 2]cajas de metal[n]cerca de ellos, con palancas[f 0 1 0]...
Cuando bajas la palanca, la [f 0 1 2]parte que[n]produce la descarga el姻ctrica se detiene[n]un momento[f 0 1 0].

[msg MSG_013 [Kanji]]
Entonces, 夷todo lo que tenemos que hacer[n]es pasar mientras est茨 apagada?

[msg MSG_014 [Ryuji]]
B茨sicamente, estamos buscando un[n]interruptor para la puerta. 斡Vamos a[n]encontrarlo!

