[msg MSG_000 [Ryuji]]
メUna jaula? メQu〒 hace algo asボ en la[n]selva?

[msg MSG_001 [Makoto]]
メRecuerdas el trホiler de la pelボcula?[n]Esto parece ser un parque temホtico donde[n]las personas pueden ver dinosaurios.

[msg MSG_002 [Yusuke]]
Entonces, estas jaulas son para mantener[n]a los dinosaurios bajo control.

[msg MSG_003 [Akechi]]
メSerホ posible mover esto? La base parece[n]estar construida para ser rotada. Pero,[n]lo mホs importante...
La historia mencionポ que los humanos[n]abandonaron este lugar hace mucho tiempo, y no[n]parece haber sido usado, recientemente...

[msg MSG_004 [Ann]]
Entonces, メestホs diciendo que...[n]adelante, habrホ...

[msg MSG_005 [Futaba]]
Podrボa haber dinosaurios corriendo por[n]aquボ, tanto herbボvoros como carnボvoros.

[msg MSG_006 [Ryuji]]
ムメMierda, de verdad?!

[msg MSG_007 [Futaba]]
No te preocupes. Les avisar〒 si hay[n]peligro cerca.

[msg MSG_008 [Haru]]
Por favor, Oracle. Contamos contigo.

[msg MSG_009 [Futaba]]
ムSボ! ムD〒jamelo a mボ!

