[msg MSG_000 [Ryuji]]
ムEsto es increボble! メDポnde estamos?

[msg MSG_001 [Haru]]
Parece el trホiler de la pelボcula que vimos antes. Nunca habボa visto ninguna de estas plantas... ムSon increボbles!

[msg MSG_002 [Morgana]]
Esto es como una jungla real... Un dinosaurio podrボa aparecer en cualquier momento.

[msg MSG_003 [Akechi]]
En "Kamoshidaman", las personas que estaban en el trホiler aparecieron tal como las vimos...
Los dinosaurios deberボan aparecer en esta pelボcula.

[sel SEL_004 top]
Esto es increボble.
Me estoy poniendo nervioso.
ムRaaaargh!

[msg MSG_005 [Makoto]]
En serio. Bueno, no creo poder ayudar si aparece uno.
Debemos movernos con precauciポn y mantenernos en guardia para lidiar con cualquier cosa que pueda aparecer.

[msg MSG_006 [Ann]]
ムメEh?! メEstホs planeando perseguir dinosaurios o algo asボ? En serio, por favor no...

[msg MSG_007 [Makoto]]
Intentemos movernos con precauciポn y mantenernos en guardia para lidiar con cualquier cosa que pueda aparecer.

[msg MSG_008 [Ann]]
ムメQu〒?!
ムO-oye! Eso no es gracioso, メsabes?

[msg MSG_009 [Makoto]]
Oh, vamos. Deja de burlarte...
Pero, ahora que lo pienso, deberボamos ser cautelosos, por si de repente somos atacados por algo.

[msg MSG_010 [Yusuke]]
...Por cierto, s〒 que tenemos la intenciポn de cambiar el final de esta pelボcula, pero メqu〒 se supone que hagamos exactamente?

[msg MSG_011 [Ryuji]]
Fue bastante fホcil saber qu〒 hacer en Kamoshidaman, solo tenボamos que golpear al malo.

[msg MSG_012 [Akechi]]
Creo que no fue tan simple...

[msg MSG_013 [Morgana]]
メCrow?

[msg MSG_014 [Akechi]]
Lo siento... Estaba hablando conmigo mismo.
En cualquier caso, quizホs los dinosaurios del trホiler son la clave para cambiar esta pelボcula...

[msg MSG_015 [Makoto]]
Los que estaban decidiendo las cosas por la regla de la mayorボa, メno?

[msg MSG_016 [Akechi]]
Segマn el trホiler, los dinosaurios parecボan estar discutiendo sobre si salvar o no a su compaワero.

[msg MSG_016_5 [Akechi]]
El que insistiポ en el rescate fue exiliado por los otros por disentir del grupo...
Si vamos a cambiar algo, メno serボa el lugar indicado para empezar?

[sel SEL_017 top]
Tienes razポn.
Supongo que podemos intentarlo.

[msg MSG_018 [Yusuke]]
No tenemos mホs pistas. メPor qu〒 no buscamos a esos dinosaurios?

[msg MSG_019 [Makoto]]
Estoy de acuerdo, empecemos con lo que podemos hacer.

[msg MSG_020 [Futaba]]
Parece que este lugar se complica mホs adelante de tu ubicaciポn.
ムJoker, asegマrate de dibujar el mapa, por si surge algo!

