[msg MSG_000 [Makoto]]
Uf... Parece que todav胤a nos queda un[n]trecho por recorrer. 夷Est茨n todos bien[n]de salud?

[msg MSG_001 [Yukiko]]
Esto no es nada.
斡Pero vaya, tu ropa realmente cambia! Es[n]tan sorprendente, 夷hay alg雨n truco[n]detr茨s de eso?

[msg MSG_002 [Makoto]]
S姻 que es asombroso y todo, pero es un[n]poco vergonzoso que te miren as胤...

[msg MSG_003 [Naoto]]
Estoy de acuerdo en que su ropa es[n]intrigante, pero los apodos, como Joker[n]y cosas as胤...
夷Podr胤an ser nombres clave?

[msg MSG_004 [Akechi]]
*risa* 夷Ha encontrado la detective una[n]teor胤a que funcione?

[msg MSG_005 [Naoto]]
B-bueno, no... Es simplemente mi propia[n]curiosidad.

[msg MSG_006 [Yusuke]]
Dado que provocamos tanto a la sociedad,[n]pr茨cticamente estamos obligados a[n]realizar nuestro trabajo de inc吋gnito.
Esa es la raz吋n por la que decidimos[n]usar nombres en clave entre nosotros[n]durante nuestras misiones.

[msg MSG_007 [Teddie]]
斡Oooooh! 斡Eso suena tan genial!

[msg MSG_008 [Yukiko]]
Oye, yo tambi姻n quiero un nombre en[n]clave.

[msg MSG_009 [Chie]]
斡夷Qu姻... Yukiko?!

[msg MSG_010 [Yukiko]]
Quiero decir, es tan genial. 夷T雨 tambi姻n[n]quieres uno, Naoto?

[msg MSG_011 [Naoto]]
夷Eh? Y-yo... Mm... Solo estaba pensando[n]en lo 雨tiles que podr胤an ser si tambi姻n[n]los tuvi姻ramos...

[msg MSG_012 [Yukiko]]
Chie, Es mejor decidir nuestros nombres[n]en clave pronto. 夷Cu茨les ser茨n?

[msg MSG_013 [Chie]]
斡夷C吋mo me involucr姻 en esto?!
Quiero decir, pensar en un nombre clave[n]tan de repente... 斡No soy experta en[n]eso!

[msg MSG_014 [Morgana]]
Supongo que no hay forma, 斡d姻jalo en[n]manos de los profesionales!
Joker, piensa en un nombre genial de[n]ladr吋n fantasma para Yukiko.

[sel SEL_015 top]
Princesa Escarlata.
Fuego Negro.
Azafata.

[msg MSG_016 [Yusuke]]
Ya veo, un nombre clave derivado de su[n]apariencia y su actitud. Es adecuado...[n]aunque tambi姻n un poco largo.

[msg MSG_017 [Ann]]
Entonces, 夷qu姻 tal Princesa Escarlata?[n]夷No suena m茨s lindo?

[msg MSG_018 [Ryuji]]
Todo lo que hiciste fue invertir las[n]palabras. Todav胤a es demasiado para un[n]nombre en clave.

[msg MSG_019 [Yukiko]]
Ooh, me gusta. Suena fuerte.

[msg MSG_020 [Ryuji]]
斡夷Te gusta?!

[msg MSG_021 [Yusuke]]
Pero, 夷por qu姻 negro? Ella solo lleva[n]rojo.

[msg MSG_022 [Teddie]]
Podr胤a ser... 夷Has visto a trav姻s de[n]Yuki, hasta su verdadera naturaleza?

[msg MSG_023 [Yukiko]]
夷Has dicho algo, Teddie? *risa* 夷Quieres[n]ser quemado?

[msg MSG_024 [Yusuke]]
Entiendo. Fuego Negro... realmente[n]encarna su verdadera naturaleza despu姻s[n]de todo.

[msg MSG_025 [Ryuji]]
夷Siquiera lo est茨s intentando? 斡Eso es[n]tan aburrido! Al menos dale un toque m茨s[n]interesante.

[msg MSG_025_5 [Ryuji]]
Oye, 夷qu姻 tal Okami? La palabra japonesa[n]para la due隠a de un hotel suena mucho[n]m茨s intimidante que "Azafata", 夷verdad?

[msg MSG_026 [Ann]]
Eres tan tonto... De hecho, considerando que a[n]los hu姻spedes extranjeros les encanta usar[n]t姻rminos como sushi y geisha, Okami no est茨[n]mal...

[msg MSG_027 [Chie]]
Parece que van a empezar a brotar[n]palabras japonesas como teriyaki y[n]tempura para nuestros nombres clave...

[msg MSG_028 [Yukiko]]
Bien, t雨 eres la siguiente, Naoto.

[msg MSG_029 [Naoto]]
夷Eh? 夷Realmente vamos a hacer esto con[n]todos...?

[msg MSG_030 [Yusuke]]
Veamos... 夷Qu姻 tal Se隠orita Platino?

[msg MSG_031 [Ryuji]]
夷Qu姻? 夷Por qu姻 "Se隠orita"...

[msg MSG_032 [Ann]]
Cierto, creo que "Se隠orita" suena un[n]poco prudente. 夷No ser胤a mejor Chica[n]Platino?

[msg MSG_033 [Ryuji]]
Espera, 斡no! Quiero decir, 斡夷por qu姻[n]est茨n usando "Se隠orita" y "Chica" para[n]Naoto?!

[msg MSG_034 [Haru]]
夷Por qu姻 no? Naoto es una chica.

[msg MSG_035 [Ryuji]]
夷Qu-eh? 斡夷De verdad?! 斡夷Lo sab胤as,[n]Joker?!

[sel SEL_036 top]
Por supuesto que lo sab胤a.
No ten胤a idea...

[msg MSG_037 [Ryuji]]
夷En serio? 斡夷Cu茨ndo lo averiguaste?!

[msg MSG_038 [Ryuji]]
夷Verdad? 斡夷No hab胤a forma de que lo[n]supiera, cierto?!

[msg MSG_039 [Ann]]
Quiz茨s es porque eres un poco denso.[n]Pens姻 que todo el mundo lo sab胤a.

[msg MSG_040 [Ryuji]]
斡No tiene nada que ver con que sea[n]denso! Simplemente... no ten胤a ni idea.[n]Quiero decir, no puedo creerlo...

[msg MSG_041 [Naoto]]
斡夷V-vamos a dejar de hablar de esto?![n]Rise, 斡t雨 sigues!

[msg MSG_042 [Rise]]
夷Yo? Oh, 夷qu姻 tipo de nombre crees que[n]ser胤a bueno para m胤?

[msg MSG_043 [Ryuji]]
Para Risette, 夷eh... Idol? Pero eso[n]parece tan obvio.

[msg MSG_044 [Teddie]]
Adem茨s, eso podr胤a confundir a los dem茨s[n]haci姻ndoles pensar en m胤, soy un idol[n]tambi姻n.

[msg MSG_045 [Chie]]
S胤, s胤...

[msg MSG_046 [Rise]]
夷Supongo que Kung Fu para ti, Chie? O[n]tal vez algo relacionado con la carne...

[msg MSG_047 [Haru]]
Carne... Mmm... 夷Sirloin?

[msg MSG_048 [Yukiko]]
斡Oh, eso es Chie! Y tambi姻n es m茨s f茨cil[n]de decir que Filete Mignon.

[msg MSG_049 [Chie]]
夷Qu姻 pasa con estos nombres clave? 斡Son[n]solo cortes de carne! 斡Vamos...!

[msg MSG_050 [Ann]]
Bueno, el siguiente es Kanji… Dado que[n]llevas una camiseta de esqueleto,[n]夷quiz茨s Skull... Parte 2?

[msg MSG_051 [Kanji]]
夷Qu姻? 夷Por qu姻 soy una secuela?

[msg MSG_052 [Yukiko]]
Mmm... Bueno, siempre est茨s gritando[n]"maldici吋n", as胤 que... 夷Cr茨neo Maldito?
Ja, ja, ja... Eso suena tan rid胤culo...[n]*Resoplido* Ja, ja, ja, 斡ja, ja, ja, ja!

[msg MSG_053 [Kanji]]
Ni siquiera me importa... Quiero decir,[n]夷cu茨nto m茨s vamos a seguir con esto?

[msg MSG_054 [Teddie]]
Oh, el m胤o a雨n no se ha decidido. Quiz茨s[n]algo como "Ni隠o bonito" u "Osito[n]lindo"...

[msg MSG_055 [Ryuji]]
El tuyo es Ted. Terminamos.

[msg MSG_056 [Teddie]]
斡Grrrrr! 斡Todav胤a no hemos terminado!
Hay tantos para elegir, como "Idol de[n]Todos" o "Querido muchacho"...[n]斡Simplemente, no puedo elegir uno!

[msg MSG_057 [Yusuke]]
Aun as胤, es Ted.

[msg MSG_058 [Makoto]]
Mmm. Ted.

[msg MSG_059 [Teddie]]
Q-qu姻 cruel... A este ritmo, 斡lo 雨nico[n]que puedo hacer es esperar que el[n]Maestro me vengue!

[msg MSG_060 [Ann]]
Un nombre en clave para [f 6 1 13 0 0 0], 夷eh...?[n]夷Qu姻 crees que ser胤a bueno, Joker?

[sel SEL_061 top]
Kingpin.
Maestro.
Lobo Yasogami.

[msg MSG_062 [P4 Hero]]
Kingpin...

[msg MSG_063 [Yusuke]]
Eso es sorprendentemente apropiado, por[n]alguna raz吋n.

[msg MSG_064 [Ryuji]]
Debe ser por esa pelea con Joker cuando[n]nos conocimos.

[msg MSG_065 [Teddie]]
斡Ese es nuestro Maestro! 斡Un nombre de[n]c吋digo con dignidad!

[msg MSG_066 [P4 Hero]]
夷Maestro? Se siente un poco raro ser[n]llamado as胤 por alguien que no sea[n]Teddie...

[msg MSG_067 [Teddie]]
斡Lo llamo Maestro porque tenemos una[n]relaci吋n especial entre nosotros! 斡Ese[n]nombre clave es solo para Teddie!

[msg MSG_068 [P4 Hero]]
斡夷Lobo Yasogami?!

[msg MSG_069 [Yusuke]]
Ah... Eso es bastante impresionante.[n]Tiene un tono fuerte y digno.

[msg MSG_070 [Ryuji]]
Oh, vamos... 夷No es demasiado extremo?

[msg MSG_071 [P4 Hero]]
Lobo Yasogami... Interesante...

[msg MSG_072 [Naoto]]
斡Oh! Sorprendente o no como pueda ser,[n]parece que le gusta.

[msg MSG_073 [Yukiko]]
Si esto es para [f 6 1 13 0 0 0], puede ser una[n]buena idea mencionar Nanako de alguna[n]manera.

[msg MSG_074 [Kanji]]
Como... 夷El hermano de Nanako?

[msg MSG_075 [P4 Hero]]
No est茨 mal.

[msg MSG_076 [Haru]]
Mm... 夷Qui姻n es Nanako? 夷Es familiar de[n][f 6 1 12 0 0 0]?

[msg MSG_077 [P4 Hero]]
S胤, es mi prima, est茨 en la escuela[n]primaria. Vivo con ella y su padre.

[msg MSG_078 [Ryuji]]
As胤 que es como Joker y Oracle.

[msg MSG_079 [Futaba]]
斡Oye! 斡Soy m茨s grande que una colegiala,[n]Skull!

[msg MSG_080 [Ryuji]]
夷Eso es lo que te enfad吋?

[msg MSG_081 [Morgana]]
*Suspira* Ya no tengo idea de lo que[n]est茨 pasando...

[msg MSG_082 [Naoto]]
夷Por qu姻 no dejamos lo de los nombres de[n]c吋digo? No creo que logremos nada bueno[n]a este paso...

[sel SEL_083 top]
Es verdad.
Qu姻 decepci吋n.

[msg MSG_084 [Yukiko]]
Ah, eso fue divertido. Pensemos en m茨s[n]nombres clave m茨s tarde.

[msg MSG_085 [Chie]]
Est茨 bien... al final, todo lo que[n]hicimos aqu胤 fue hablar sin parar, de[n]todos modos.

[msg MSG_086 [Morgana]]
Bueno, dado que ustedes no necesitan[n]identidades secretas, creo que tampoco[n]necesitan nombres en clave.
Vamos a concentrarnos en salir de aqu胤.

