[msg MSG_000 [Marie]]
*suspiro* Bien, escucha. Voy a explicar esto una vez...
Te ayudar〒 a conectarte con "mundos que no estホn aquボ". Hay gente como tマ en esos mundos.
Y cuando digo "como tマ", tambi〒n me refiero a que estホn atrapados en sus mundos.
Se llama "StreetPass". Estoy bastante segura de que te ayudarホn de alguna manera.

[msg MSG_001 [Marie]]
*suspiro* Bueno, escucha. Voy a explicar esto una vez...
Te ayudar〒 a conectarte con "mundos que no estホn aquボ". Hay gente como tマ en esos mundos.
Y cuando digo "como tマ", tambi〒n me refiero a que estホn atrapados en sus mundos.
Estoy bastante segura de que te ayudarホn de alguna manera.

[msg MSG_002]
Ahora puedes usar "StreetPass"

[msg MSG_003 [Ryuji]]
Bien, entonces te dejaremos todo eso.

[msg MSG_004 [Margaret]]
*risita* Te has acostumbrado a proporcionar esas explicaciones...
Todo lo que queda ahora es mejorar tus poemas...

[msg MSG_005 [Marie]]
ムLALALAAAA! ムメQu〒 dijiste?! ムメQu〒?! ムNo tengo ni idea de lo que estホs hablando!

[msg MSG_005_5 [Marie]]
M-mホs importante, [f 6 1 30 0 0 0]! ムメTienes mホs preguntas?!

[sel SEL_006 top]
Estoy bien.
メQu〒 es eso de la poesボa?

[msg MSG_007 [Marie]]
Aprendes sorprendidamente rホpido... a diferencia de cierta persona.

[msg MSG_008 [Margaret]]
Oh, querida, メa qui〒n podrボas estar refiri〒ndote? *risita*

[msg MSG_009 [Marie]]
Argh...

[msg MSG_010 [Chie]]
Es bastante obvio, pero Margaret es bastante sホdica, メno?

[msg MSG_011 [Marie]]
ムメEres tonta?! ムDije que no tengo ni idea!
No hay poesボa en ningマn lado, メentendido? ムSerホ mejor que no andes fisgoneando por ahボ!

[msg MSG_012 [Ann]]
ムVaya, es como un libro abierto! ムEs la mホs fホcil de leer!

[msg MSG_013 [Morgana]]
Me pregunto si es la naturaleza humana o mi lado de ladrポn fantasma, lo que me hace querer revisar aマn mホs ahora...

[msg MSG_014 [Margaret]]
Si〒ntete libre de pasar y vernos siempre que necesites nuestra ayuda.
Estoy segura de que podremos cumplir con tus expectativas.

[msg MSG_015 [P4 Hero]]
Bien, gracias.
, volvamos cuando la necesitemos.

