[msg MSG_000 [Ryuji]]
斡Bien! 斡Ese idiota nos sigui吋!

[msg MSG_001 [Futaba]]
El interruptor debe estar cerca...[n]斡Electrifica la puerta!

[msg MSG_002 [Kanji]]
Muy bien, 斡hag茨moslo!

[msg MSG_003 [Kanji]]
斡夷Eh?! 斡夷No funciona?!

[msg MSG_004 [P3 Fem Protag]]
斡D姻jame intentarlo!

[msg MSG_005 [P3 Fem Protag]]
斡夷Eh...?! 斡夷Est茨 roto?!

[msg MSG_006 [Akechi]]
No est茨 encendido... Parece que la[n]energ胤a est茨 apagada.
Eso explica por qu姻 la puerta estaba[n]abierta.

[msg MSG_007 [Ann]]
斡Eh! 斡夷C吋mo lo encendemos?!

[msg MSG_008 [Naoto]]
Quiz茨s haya una fuente de energ胤a de[n]respaldo en alg雨n lugar.

[msg MSG_009 [Ryuji]]
斡Fuente de energ胤a de respaldo! 斡Vamos a[n]buscarla!

[msg MSG_010 [Carn胤voro Llamativo]]
斡GRRRROOOOOOOOAR!

[msg MSG_011 [Yusuke]]
斡Esto es malo! 斡Est茨 a punto de pasar[n]por la puerta!

[msg MSG_012 [P4 Hero]]
Entonces... Lo detendr姻.

[msg MSG_013 [Teddie]]
斡夷Maestro?! 斡N-no puedes...!

[sel SEL_014 top]
斡斡Yo tambi姻n voy!!
斡Espera!

[msg MSG_015 [Ann]]
No sirve de nada, 斡no puede escucharnos![n]斡Ya est茨 cerca!

[msg MSG_016]
斡No puedo dejar que [f 6 1 12 0 0 0] se enfrente a[n]ese carn胤voro solo...!

[msg MSG_017 [Chie]]
斡夷T-t雨 tambi姻n, Joker?!

