[msg MSG_000 [Yusuke]]
メSon... huesos de dinosaurio?

[msg MSG_001 [Ann]]
ムメPor qu〒 estホn en el suelo asボ?!

[sel SEL_002 top]
Muriポ aquボ.
Se lo comieron.
Son solo una r〒plica.

[msg MSG_003 [Makoto]]
Es verdad, pero la verdadera pregunta es por qu〒 muriポ.
Es posible que muriera por causas naturales... pero todavボa hay otra posibilidad.

[msg MSG_004 [Ann]]
メSe lo... comieron?
Entonces, メeso significa que hay un... "Tiranosaurio Rex"?

[msg MSG_005 [Ryuji]]
メQu〒 otra cosa podrボa comerse algo asボ de... enorme?

[msg MSG_006 [Yusuke]]
Bueno, podrボa hacerlo si tuviera la suficiente hambre.

[msg MSG_007 [Haru]]
El comentario de Fox aparte, un dinosaurio que podrボa comerse algo tan grande podrボa ser...

[msg MSG_008 [Akechi]]
Aun asボ, parecen muy detallados... Creo que es seguro decir que son huesos reales de dinosaurio.

[msg MSG_009 [Makoto]]
Pero, メpor qu〒 estホn aquボ? メPodrボa haber muerto de causas naturales?

[msg MSG_010 [Ann]]
No me digas que... メSe lo comieron?
Entonces, メeso significa que hay un... "Tiranosaurio Rex"?

[msg MSG_011 [P3 Fem Protag]]
メUn Tiranosaurio Rex?
Bueno, no hay garantボa que lo sea, ムpero todo es posible aquボ!

[msg MSG_012 [Ryuji]]
Los T-Rex son carnボvoros superfuertes, メverdad?

[msg MSG_013 [Yusuke]]
El mホs famoso de todos... ムEs obligatorio en una pelボcula de dinosaurios!

[msg MSG_014 [Makoto]]
メPor qu〒 estホs tan emocionado?

[msg MSG_015 [Yusuke]]
ムPresenciar dinosaurios vivos con mis propios ojos, esta es una oportunidad マnica! Claro que estoy emocionado.

[msg MSG_016 [Haru]]
Pero podrボa ser otro FOE...

[msg MSG_017 [Yusuke]]
Estホ bien para mボ. ムLo importante es que sean grandes y llenos de vida!
ムNo puedo esperar a verlo! Si es posible, me gustarボa dibujarlo desde mマltiples ホngulos...

[msg MSG_018 [Futaba]]
Oye, Fox... Si vas a hacer algo imprudente, hazlo tマ solo.
Solo ignポralo, y si te sientes en peligro, regresa, メde acuerdo?

