[msg MSG_000 [Yosuke]]
ムChicos! ムMe encontraron!

[msg MSG_001 [Morgana]]
メEstホ con el herbボvoro que estホbamos[n]buscando?

[msg MSG_002 [Carnボvoro Llamativo]]
ムGRRRROOOOOOOOAR!

[msg MSG_003 [Teddie]]
ムAaaaah! ムSe va a comer a Yosuke si no[n]hacemos algo!

[msg MSG_004 [Kanji]]
ムAguanta! ムVamos por ti!
Oye, ムpollo carnボvoro! ムVen y atrホpanos!

[msg MSG_005 [Morgana]]
ムEspera! ムEse carnボvoro es[n]increボblemente fuerte!

[msg MSG_006 [Kanji]]
メEntonces qu〒 se supone que hagamos? ムSe[n]lo comerホ!

[msg MSG_007 [P4 Hero]]
Si tan solo pudi〒ramos alejar a ese[n]carnボvoro de ellos...

[msg MSG_008 [P3 Fem Protag]]
ムOh, ya s〒! メPodrボa ser マtil esa cosa?
Ya sabes, eso que encontramos de[n]camino...

[sel SEL_009 top]
メTe refieres a la puerta?
メTe refieres a la cuerda?
メTe refieres a la trampa?

[msg MSG_010 [Makoto]]
ムExacto! ムVimos una que estaba abierta!

[msg MSG_011 [Ryuji]]
ムメEres un domador de dinosaurios?! ムNo[n]tenemos ninguna cuerda!

[msg MSG_012 [Yukiko]]
Mmm, un domador de dinosaurios...
Oh, tal vez ella quiso decir que[n]podrボamos llevarlo hacia esa puerta[n]el〒ctrica.

[msg MSG_013 [Makoto]]
ムEso es! ムVimos una que estaba abierta!

[msg MSG_014 [Ann]]
メUna trampa? No recuerdo ninguna[n]trampa...

[msg MSG_015 [Akechi]]
Creo que [f 6 1 26 0 0 0] se referボa a esa puerta[n]el〒ctrica.

[msg MSG_016 [Makoto]]
ムEso es! ムVimos una que estaba abierta!

[msg MSG_017 [Ryuji]]
Entonces, ムtodo lo que tenemos que hacer[n]es ir allボ y atraparlo!

[sel SEL_018 top]
Ejecutemos ese plan.
メCポmo hacemos eso?
Tマ puedes, Skull.

[msg MSG_019 [Haru]]
メPero cポmo vamos a dirigir al carnボvoro[n]hacia la puerta?

[msg MSG_020 [Chie]]
メCポmo? Quiero decir... ムメCポmo vamos a[n]atraparlo?!

[msg MSG_021 [Ryuji]]
Sボ, solo voy a... espera, ムメcポmo esperas[n]que haga tal cosa?!

[msg MSG_022 [Teddie]]
ムD〒jame eso a mボ! Tengo una piedra de[n]aquボ, asボ que solo voy a apuntar y...
ムOye, comete ESTO!

[msg MSG_023 [Ann]]
ムWahhh! メAcaba de lanzarle una piedra a[n]un carnボvoro?

[msg MSG_024 [Teddie]]
ムUn lanzamiento perfecto! ムメVieron mi[n]t〒cnica impecable?!

[msg MSG_025 [Carnボvoro Llamativo]]
ムGWOOOOOOOOOOO!

[msg MSG_026 [Chie]]
ムAah! ムメNo lo acabamos de hacer enfadar[n]mホs?!

[msg MSG_027 [Teddie]]
ムLo hice a propポsito para que venga tras[n]nosotros!

[msg MSG_028 [Yukiko]]
Ah, entonces estamos utilizando una[n]estrategia de seワuelo.

[msg MSG_029 [Rise]]
Escuchen, ムRegresen por donde vinieron![n]Corran lo mホs rホpido que puedan, ムa por[n]esa puerta!

[msg MSG_030 [P4 Hero]]
Parece que nuestra misiポn acaba de[n]empezar. ムVamos a rescatar a Yosuke!

[msg MSG_031 [Chie]]
ムEntendido! ムDe todos modos, tenemos[n]cosas mホs importantes que hacer que[n]volver al cine!

[msg MSG_032 [Futaba]]
De acuerdo, ムpero no tienen mucho[n]tiempo! ムTienen que correr!

