[msg MSG_000 [Futaba]]
Joker, 斡espera! 斡Detente, paraaa!

[msg MSG_001 [Makoto]]
夷Por qu姻 tanto alboroto? 斡夷Un enemigo?!

[msg MSG_002 [Futaba]]
No lo s姻, 斡pero algo se acerca a ustedes[n]incre胤blemente r茨pido!

[sel SEL_003 top]
夷Es un dinosaurio?
夷Es un FOE?
夷Es Mona?

[msg MSG_004 [Ann]]
斡夷En serio?! 夷Eso significa que viene[n]hacia nosotros?

[msg MSG_005 [Morgana]]
S胤, me estoy acercando con mi s雨per...
斡Reacciona! 斡He estado alado tuyo todo[n]el tiempo!

[msg MSG_006 [Futaba]]
Estos no son dinosaurios ni FOEs...[n]Bas茨ndome en su velocidad...
No puede ser... 斡夷Podr胤an ser humanos?!

[msg MSG_007 [Ryuji]]
夷En serio? 夷Hay alguien m茨s aqu胤 adem茨s[n]de nosotros?

[msg MSG_008 [Haru]]
Oh, tal vez esto es a lo que Oracle se[n]refer胤a cuando entramos a la pel胤cula...
Ya sabes, 夷sobre m雨ltiples presencias[n]poderosas?

[msg MSG_009 [P3 Fem Protag]]
斡Oye! 斡Quiz茨s sean mis compa隠eros!

[msg MSG_010 [Akechi]]
Tiene sentido... Si son humanos con un[n]poder fuerte, podr胤as tener raz吋n.
Sin embargo, normalmente no deber胤a[n]haber humanos en esta pel胤cula.[n]Probablemente, sea mejor ir con cuidado.

[msg MSG_011 [P3 Fem Protag]]
Tienes raz吋n. Adem茨s, me intriga la[n]parte de la alta velocidad.

[msg MSG_012 [Futaba]]
Tus preguntas est茨n a punto de ser[n]contestadas... 斡Se est茨n acercando!

[msg MSG_013 [Yusuke]]
Parece que no hay tiempo para pensarlo.[n]Joker, 夷qu姻 hacemos?

[sel SEL_014 top]
Hagamos el primer movimiento.
Veamos qu姻 pasa.

[msg MSG_015 [Morgana]]
Bien, te lo dejamos. Toma tu pistola,[n]para intimidar...
Si estamos tratando con humanos, solo[n]ver eso deber胤a darte una ventaja.

[msg MSG_016 [Makoto]]
Espero que eso funcione a nuestro[n]favor... Aunque manteng茨monos alerta.

[msg MSG_017 [Futaba]]
斡Aqu胤 vienen! 斡Prep茨rate!

