[msg MSG_000 [Margaret]]
Los he estado esperando.

[msg MSG_001 [P4 Hero]]
メQu〒 pasa?

[msg MSG_002 [Margaret]]
Desde que fui citada aquボ, he querido ayudarlos de alguna manera...
Y lo que se me ocurriポ es la "Fusiポn de Sacrificio", es una mejor forma de fortalecer a sus Personas.

[sel SEL_003 top]
メFortalecer?
メSacrificar?

[msg MSG_004 [Yusuke]]
メPuedes fortalecer a nuestras Personas?

[msg MSG_005 [Margaret]]
Sボ. Al fusionar Personas, su Persona podrホ crecer.

[msg MSG_006 [Yusuke]]
Eso suena bastante ominoso.

[msg MSG_007 [Margaret]]
*risita* No te pedir〒 que ofrezcas la tuya como sacrificio ni nada por el estilo, asボ que tポmatelo con calma.
Esto implica fusionar Personas para fortalecer a tu Persona.

[msg MSG_008 [Ryuji]]
メNo es lo mismo que las fusiones normales?

[msg MSG_009 [Margaret]]
La fusiポn es el medio para crear una nueva Persona a partir de mマltiples Personas.
Las Fusiones de Sacrificio consisten en utilizar a una sola Persona para fortalecer el crecimiento de otra en especボfico.
La Persona original crecerホ y la sacrificada desaparecerホ.

[msg MSG_010 [Makoto]]
Una se vuelve mホs fuerte, mientras que la otra se pierde... Eso definitivamente serボa considerado un sacrificio.

[msg MSG_011 [Akechi]]
メSe puede hacer con la Principal y Secundaria?

[msg MSG_012 [Margaret]]
Sボ. Es posible ayudar a ambas a crecer...
Aunque, naturalmente, serホs incapaz de sacrificar a tu Persona principal.

[msg MSG_013 [Teddie]]
Pero espera, メno hay mホs? メAlgo asボ como a un costo mホs alto?

[msg MSG_014 [Margaret]]
Por supuesto, pedir〒 una compensaciポn, una cantidad razonable. Sin embargo, ya que esto es para mi propia investigaciポn tambi〒n...
Si la Persona que va a desaparecer estホ siendo sacrificada por primera vez, serホ gratuito.
Sin embargo, cuando esa Persona sea sacrificada nuevamente, pedir〒 ser compensada.

[msg MSG_015 [Haru]]
メEntonces, todas las Personas pueden ser sacrificadas gratis la primera vez?

[msg MSG_016 [Margaret]]
Es correcto.

[msg MSG_017 [Chie]]
ムOh... esto es una manera asombrosa para que todos nos volvamos mホs fuertes!

[msg MSG_018 [P4 Hero]]
Gracias, Margaret. Aprecio tu cooperaciポn.

[msg MSG_019 [Margaret]]
...No, mi papel aquボ tambi〒n es obra del destino.
Con tu llegada, se ha producido un cambio en las pelボculas: los programas distorsionados se estホn corrigiendo.
Puede que todos ustedes hayan sido asignados a roles como usuarios de Persona para lograr esto.

[msg MSG_019_1 [P4 Hero]]
メFuimos asignados a tales roles?

[msg MSG_019_2 [Margaret]]
Sボ, y creo que fuimos llamadas aquボ para supervisar eso... Entonces, メMarie?

[msg MSG_020 [Marie]]
Ugh... メDe verdad tengo que hacerlo?

[msg MSG_021 [Margaret]]
Tendrホs mucho tiempo para escribir tus poemas, asボ que no te preocupes por eso.

[msg MSG_022 [Marie]]
E-eso no... No son solo mis poemas, ムson mi pathos!
ムEstマpidaterribleMargarettマereslapeor! ムSolo d〒jalo, メde acuerdo?!

