[msg MSG_000 [Yosuke]]
ムBien! ムメSoy yo o cambiamos todo?!

[msg MSG_001 [Rise]]
ムSeguro que sボ! ムTodos tenボan sonrisas[n]tan felices al final!

[msg MSG_002 [Hikari]]
Bienvenidos.

[msg MSG_003 [Ann]]
ムGracias! メTe aseguraste de ver toda la[n]pelボcula hasta el final?

[msg MSG_004 [Hikari]]
Mmm, lo hice.

[msg MSG_005 [Futaba]]
Eh, O-oye, Hikari... メQu〒 opinas al[n]respecto?

[msg MSG_006 [Hikari]]
Um...

[msg MSG_007 [Nagi]]
Estホ bien... Puedes decirles cポmo te[n]sentiste, con tus propias palabras.

[msg MSG_008 [Hikari]]
Mmm... Bueno...
La pelボcula fue realmente...[n]maravillosa.

[msg MSG_009 [Futaba]]
ムメE-en serio?!

[msg MSG_010 [Hikari]]
Mmm... De verdad.

[msg MSG_011 [Futaba]]
Ya veo. Me alegra escuchar eso...

[msg MSG_012 [P3 Fem Protag]]
Oye, Hikari... メQu〒 te gusto de la[n]pelボcula?

[msg MSG_013 [Hikari]]
Se enfrentポ al carnボvoro... Aunque[n]estaba solo...
Todos los demホs estaban en contra,[n]pero... 〒l reuniポ el valor para[n]hacerlo...

[msg MSG_014 [Futaba]]
メTe refieres al Yosukesaurio, メverdad?[n]メY? メY?

[msg MSG_015 [Hikari]]
Y luego, los otros herbボvoros estaban[n]realmente asustados... pero tambi〒n[n]encontraron el coraje.
Actuポ segマn lo que realmente sentボa...[n]pero no se quedポ solo con eso...

[msg MSG_016 [Yosuke]]
Eso es porque los amigos pueden decir lo[n]que realmente sienten, メverdad,[n]compaワero?

[msg MSG_017 [P4 Hero]]
Correcto.

[msg MSG_018 [Hikari]]
Hasta ahora, pensaba que tenボa que[n]pensar y decir lo mismo que mis amigos.
De lo contrario, no podrボa estar con[n]ellos... Pensaba que era natural seguir[n]a la multitud...
Pero eso no era verdad. Es exactamente[n]como dijiste, Futaba...

[msg MSG_019 [Futaba]]
Hikari, メme llamaste por mi nombre?

[msg MSG_020 [Nagi]]
Al igual que con la pelボcula anterior,[n]el final al que guiaste esta pelボcula[n]fue simplemente magnボfico.

[msg MSG_021 [Hikari]]
メTambi〒n lo crees, Nagi?

[msg MSG_022 [Nagi]]
Sボ. La violencia por nマmeros siempre[n]ocurre en los grupos...
Solo puedo suponer que muchos fueron[n]maltratados en esa pelボcula hasta que[n]ustedes entraron y la cambiaron.
Es innegable que tales problemas tambi〒n[n]pueden ocurrir en nuestro mundo...

[msg MSG_023 [Hikari]]
...

[msg MSG_024 [Nagi]]
Sin embargo, gracias a ustedes, pudimos[n]presenciar un nuevo resultado.
Al igual que Hikari y los dinosaurios[n]que aparecieron en esa pelボcula... yo[n]tambi〒n me siento muy feliz.
Por favor, permボtanme expresar mi[n]gratitud tambi〒n...
Muchas gracias por esa maravillosa[n]pelボcula.

[sel SEL_025 top]
Solo hicimos lo que siempre hacemos.
No hay necesidad de agradecimientos.
Por supuesto, lo hicimos genial.

[msg MSG_026 [Chie]]
ムVaya, tratポ toda esa pesadilla como si[n]fuera pan comido!

[msg MSG_027 [Teddie]]
*silbido* ムQu〒 genial!

[msg MSG_028 [Morgana]]
Vaya, qu〒 presumido...
Aunque, en realidad, ムlo hicimos genial[n]allボ dentro!

[msg MSG_029 [Doe]]
...

[msg MSG_030 [Chie]]
ムAaaaaaah! ムme sorprendiste!

[msg MSG_031 [P4 Hero]]
Doe...

[msg MSG_032 [P4 Hero]]
Asボ que, eso es Doe...

[msg MSG_033 [Doe]]
Nghh... Nnnghhh...

[msg MSG_034 [Haru]]
Su expresiポn... メEstホ a punto de soltar[n]otra llave?

[msg MSG_035 [Hikari]]
A-ah...

[msg MSG_036 [P3 Fem Protag]]
Hikari, ven!

[msg MSG_037 [Doe]]
Ngh... ムNghhhhh!

[msg MSG_038 [Yosuke]]
ムメQu〒...?! Me hablaste de esto, ムメpero[n]realmente acaba de salir una llave de[n]sus ojos?!

[msg MSG_039 [Yukiko]]
メPodrボa ser una llave para la puerta[n]principal?

[msg MSG_040 [Naoto]]
Sボ, creo que es la segunda. Prob〒mosla.

