[sel FCL_PERSONA_YN top]
S胤
No

[msg FCL_PERSONA_LVUP]
斡 ha subido de nivel!

[msg FCL_PERSONA_PARAMUP]
斡El nivel de ha aumentado en !

[msg FCL_PERSONA_GETSKILL]
斡 ha aprendido!

[msg FCL_PERSONA_RMSKILL]
Todos los espacios de habilidades est茨n[n]llenos. Por favor, selecciona una[n]habilidad para borrar.

[msg FCL_PERSONA_RMSKILL_Q]
夷Eliminar ?

[msg FCL_PERSONA_RMSKILL0]
olvidar茨.

[msg FCL_PERSONA_RMSKILL1]
ha reemplazado.

[msg FCL_PERSONA_RMSKILL2]
se ha mejorado a!

[msg FCL_PERSONA_SKILLSHIFT]
......?
＞『』に 何かが起こりそうだ……
＞やらせてみますか？

[msg FCL_PERSONA_SKILLSHIFTCA]
＞『』の泣き声を聞いた…

[msg FCL_PERSONA_SKILLSHIFTCH]
se ha mejorado a!

[msg FCL_PERSONA_SKILLSHIFTUP]
ha cambiado a!

[msg FCL_PERSONA_SHIFT]
＞ペルソナ『』から 何かが産み落とされようとしている…
＞見届けますか？

[msg FCL_PERSONA_SHIFTCANCEL]
＞『』から 『受胎の兆候』が消えた…

[msg FCL_PERSONA_SHIFT1]
＞なんと、『』は 『』を生んだ！

[msg FCL_GET_SKILLCARD0]
夷...?
＞『』は 何かを差し出した・・・

[msg FCL_GET_SKILLCARD1]
＞なんと、『』から スキルカード『』を手に入れた！

[msg FCL_SKILLCARD_TUTORIAL]
『スキルカード』は、 あなたのペルソナに使えるアイテムです。[n]カードに封じられたスキルを、 ペルソナが覚えます。
スキルカードは使用すると無くなりますが、 覚えたスキルは、[n]合体で継承させることができます。

[msg FCL_SKILL_FRAME]
斡Los espacios de habilidades de han[n]aumentado!

[msg FCL_MOVIE_BONUS]
＞映画を見たことで各種能力にボーナス値が付いた！

[msg FCL_PERSONA_EVOLUTION_FI]
＞『』は 『』に転生した！

[msg FCL_PERSONA_EVOLUTION_PR]
斡Parece que un poder oculto ha[n]despertado en ...!

[msg FCL_PERSONA_EVOLUTION_NO]
斡 mantuvo su forma, pero se ha vuelto[n]m茨s poderosa!

[msg FCL_PERSONA_EVOLUTION_SK]
斡 ha sido mejorada!

