[msg NOFFICE_HELLO_ELIZABETH_ [Elizabeth]]
メQu〒 entrada te gustarボa?

[msg NOFFICE_HELLO_ELIZABETH__2 [Elizabeth]]
Te he estado esperando.

[msg NOFFICE_HELLO_ELIZABETH__3 [Elizabeth]]
Bienvenido a la taquilla.

[msg NOFFICE_EXP_ELIZABETH [Elizabeth]]
メEn qu〒 puedo ayudarte?

[msg NOFFICE_OUT_ELIZABETH_NU [Elizabeth]]
Gracias por tu patrocinio.

[msg NOFFICE_OUT_ELIZABETH_NU_2 [Elizabeth]]
Espero tu prポxima visita.

[msg NOFFICE_OUT_ELIZABETH_NU_3 [Elizabeth]]
Te ver〒 de nuevo.

[msg NOFFICE_ACCEPT_OUT_ELIZA [Elizabeth]]
Buena suerte.

[msg NOFFICE_ACCEPT_OUT_ELIZA_2 [Elizabeth]]
Ten cuidado.

[msg NOFFICE_ACCEPT_OUT_ELIZA_3 [Elizabeth]]
Rezar〒 por tu 〒xito.

[msg BBOARD_BATTLE_BEFORE_THE [Theodore]]
Theodore antes de la batalla

[msg BBOARD_BATTLE_BEFORE_MAR [Margaret]]
Margaret antes de la batalla

[msg BBOARD_BATTLE_BEFORE_TWI [Twins]]
Gemelas antes de la batalla

[msg BBOARD_BATTLE_BEFORE_ELI [Elizabeth]]
Elizabeth antes de la batalla

[msg BBOARD_BATTLE_BEFORE_ALL [Elizabeth]]
Todos los 5 antes de la batalla

[sel SEL_BBOARD_BATTLE_BEFORE top]
Estoy listo.
Un momento.

[msg BBOARD_BATTLE_START_ELIZ [Elizabeth]]
Not used

[msg BBOARD_BATTLE_LATER_ELIZ [Elizabeth]]
Not used

