[sel PARTY_EDIT_YESNO top]
S胤
No

[sel PARTY_EDIT_YESNO_CALL top]
S胤
No

[sel PARTY_EDIT_YESNO_CALL_DE top]
S胤
No

[sel PARTY_EDIT_YESNO_REGIST_ top]
S胤
No

[msg MSG_ORGIA000]
Explicaci吋n del modo Desenfreno. Aunque[n]no es muy complicado...
斡De acuerdo! 斡Espero verla!

[msg PARTY_EDIT_MSG_CALL_COMF]
夷Usar este grupo?

[msg PARTY_EDIT_MSG_SET_COMFI]
夷Registrar [f 2 4 0]?

[msg PARTY_EDIT_MSG_DEL_COMFI]
夷Eliminar [f 2 4 0]?

[msg PARTY_EDIT_MSG_CANCEL_CR]
夷Salir sin guardar el grupo?

[msg PARTY_EDIT_MSG_NAME_ENTR]
Ingresa un nombre para este grupo[n]utilizando la pantalla t茨ctil.

[msg PARTY_EDIT_MSG_CANCEL_ED]
夷Deseas salir sin cambiar la formaci吋n[n]del grupo?

[msg PARTY_EDIT_MSG_PARTY_ALL]
Nadie en tu grupo est茨 en condiciones de[n]combatir.

[msg PARTY_EDIT_MSG_LEADER_NO]
El l胤der del equipo no ha sido elegido.[n]Aseg雨rate de tener uno.

[msg PARTY_EDIT_MSG_NO_MEMBER]
Selecciona aliados para agregar al[n]grupo.

[msg PARTY_EDIT_MSG_LEADER_NO_2]
Elige un l胤der de grupo, alguien con el[n]poder del comod胤n.

[msg PARTY_EDIT_MSG_FIRST_NAV]
No se ha elegido a un navegador.[n]斡Necesitas uno!

[msg PARTY_EDIT_MSG_DUNGEON_N]
Olvidaste elegir un navegador de campo.

[msg PARTY_EDIT_RISKY_INVALID]
Cuando tu dificultad est茨 configurada en[n]"Arriesgado", debes incluir [f 6 1 30 0 0 0] en el[n]grupo.

