[msg MSG_BEST_1_1 [P4 Hero]]
Me siento preparado. 夷Te importa si me[n]uno a la pelea?

[msg MSG_BEST_1_2 [P4 Hero]]
夷Te importa si me uno a la acci吋n? Estoy[n]en forma en este momento.

[msg MSG_BEST_2_1 [P3 Hero]]
夷Crees que podr胤a unirme a ti? Siento[n]que lo har姻 mejor de lo habitual.

[msg MSG_BEST_2_2 [P3 Hero]]
Siento que estoy en forma. 夷Te importa[n]si vengo contigo?

[msg MSG_BEST_3_1 [Yosuke]]
Oye, 夷te importar胤a llevarme contigo?[n]斡Estoy en racha!

[msg MSG_BEST_3_2 [Yosuke]]
Jeje, me siento imparable. 斡Ll姻vame[n]contigo y no te decepcionar姻!

[msg MSG_BEST_4_1 [Chie]]
Estoy llena de energ胤a y lista para[n]traer el 斡"BAM"!

[msg MSG_BEST_4_2 [Chie]]
斡Hiiiyah! 斡Mi indicador de energ胤a est茨[n]lleno! 斡D姻jame enfrentarlos!

[msg MSG_BEST_5_1 [Yukiko]]
Oye, d姻jame pelear tambi姻n. Siento que[n]estoy en plena forma en este momento.

[msg MSG_BEST_5_2 [Yukiko]]
Siento algo ardiendo por dentro. 斡Siento[n]que puedo hacer cualquier cosa!

[msg MSG_BEST_6_1 [Rise]]
斡S胤, mi voz est茨 en excelente forma[n]ahora mismo! 斡D姻jame encargarme de la[n]navegaci吋n!

[msg MSG_BEST_6_2 [Rise]]
斡Los niveles de energ胤a est茨n al 100%![n]Deber胤a estar listo para empezar.

[msg MSG_BEST_7_1 [Kanji]]
斡Ponme ah胤! 斡Puedo con ellos!

[msg MSG_BEST_7_2 [Kanji]]
斡S胤, me siento genial! 斡Los enfrentar姻 a[n]todos!

[msg MSG_BEST_8_1 [Naoto]]
夷Crees que pueda unirme? Estoy en[n]excelente forma en este momento.

[msg MSG_BEST_8_2 [Naoto]]
Estoy bien de salud y energ胤a. Listo[n]para pelear.

[msg MSG_BEST_9_1 [Teddie]]
斡Oh, yo! 斡El胤geme a m胤! 斡Me siento muy[n]confiado!

[msg MSG_BEST_9_2 [Teddie]]
斡Hrrrrraaah! 斡Poder de Teddie al m茨ximo![n]斡D姻jame encargarme de esto!

[msg MSG_BEST_10_1 [Yukari]]
S胤, me siento bien. Puedo resistir un[n]golpe si lo necesitas.

[msg MSG_BEST_10_2 [Yukari]]
Parece que estoy en buena forma en este[n]momento. 夷Te importar胤a llevarme[n]contigo?

[msg MSG_BEST_11_1 [Junpei]]
Jeje, 斡me siento emocionado! 斡La leyenda[n]de Junpei Iori comienza justo despu姻s de[n]esto!

[msg MSG_BEST_11_2 [Junpei]]
斡Oh, s胤, estoy en la zona! Debes[n]llevarme contigo.

[msg MSG_BEST_12_1 [Akihiko]]
Jeje, estos pu隠os est茨n listos para[n]pelear. Col吋came en primera fila.

[msg MSG_BEST_12_2 [Akihiko]]
Me siento m茨s afilado de lo habitual.[n]斡D姻jame salir y demostrarlo!

[msg MSG_BEST_13_1 [Mitsuru]]
Parece que estoy en plena forma. 夷Te[n]importar胤a llevarme contigo?

[msg MSG_BEST_13_2 [Mitsuru]]
Estoy en perfectas condiciones.[n]斡Nuestros enemigos no tienen ninguna[n]oportunidad!

[msg MSG_BEST_14_1 [Fuuka]]
Um... me siento bastante bien en este[n]momento. 斡Creo que puedo ayudar!

[msg MSG_BEST_14_2 [Fuuka]]
夷Puedo intentar navegar? Me siento[n]bastante segura en este momento.

[msg MSG_BEST_15_1 [Aigis]]
Salida al m茨ximo. 斡Perm胤teme poner a[n]prueba mi habilidad!

[msg MSG_BEST_15_2 [Aigis]]
斡Estoy en 吋ptima condici吋n! 斡Permiso[n]para desplegar!

[msg MSG_BEST_16_1 [Ken]]
斡Me siento genial! 斡D姻jame unirme a la[n]pelea!

[msg MSG_BEST_16_2 [Ken]]
Um... 夷Podr胤as dejarme pelear? 斡Te[n]prometo que no te arrepentir茨s!

[msg MSG_BEST_17_1 [Koromaru]]
斡Guau, guau!

[msg MSG_BEST_17_2 [Koromaru]]
斡Guau! 斡Auuuu!

[msg MSG_BEST_18_1 [Shinjiro]]
Oye, 夷te importa si me uno? No te[n]arrepentir茨s.

[msg MSG_BEST_18_2 [Shinjiro]]
Huh, no me siento nada mal en este[n]momento. Perm胤teme hacerles algo de[n]da隠o.

[msg MSG_BEST_19_1 [P3 Fem Protag]]
Oye, 夷te importa si voy contigo?[n]斡Prometo darlo todo!

[msg MSG_BEST_19_2 [P3 Fem Protag]]
斡Siento que podr胤a enfrentar al mundo[n]entero! 斡Vamos a por ello!

[msg MSG_BEST_64_1 [Morgana]]
Oh, est茨s en sinton胤a. 斡Mu姻stranos de[n]qu姻 est茨s hecho!

[msg MSG_BEST_64_2 [Morgana]]
Oye, te ves bien. 斡Sal ah胤 y derrota a[n]algunas Sombras!

[msg MSG_BEST_65_1 [Ryuji]]
Oye, 夷te importa si me uno? Siento que[n]quiero soltarme un poco.

[msg MSG_BEST_65_2 [Ryuji]]
Amigo, estoy s雨per emocionado. Perm胤teme[n]encargarme de esto.

[msg MSG_BEST_66_1 [Ann]]
Oye, 夷puedo ir? 斡Estoy lista!

[msg MSG_BEST_66_2 [Ann]]
斡S胤! 斡Estoy en llamas! 斡Lista para la[n]pelea!

[msg MSG_BEST_67_1 [Morgana]]
斡Llevame ah胤 afuera! Puedo sentir que[n]voy a hacerlo genial.

[msg MSG_BEST_67_2 [Morgana]]
Nyahaha... Estoy en plena forma. Este es[n]mi momento para brillar.

[msg MSG_BEST_68_1 [Yusuke]]
Por favor, perm胤teme unirme. Conf胤o en[n]que cumplir姻 tus expectativas.

[msg MSG_BEST_68_2 [Yusuke]]
斡Estoy lleno de inspiraci吋n! 斡Este es mi[n]momento!

[msg MSG_BEST_69_1 [Makoto]]
夷Puedo ir? Siento que estoy en buena[n]forma.

[msg MSG_BEST_69_2 [Makoto]]
Estoy rebosante de energ胤a. Perm胤teme[n]ayudar.

[msg MSG_BEST_70_1 [Futaba]]
斡Me siento 3 veces m茨s poderosa! 斡Vamos[n]all茨!

[msg MSG_BEST_70_2 [Futaba]]
斡Estoy lista! 斡Siento que podr胤a navegar[n]con los ojos cerrados!

[msg MSG_BEST_71_1 [Haru]]
夷Est茨 bien si me encargo de esto? Te[n]prometo que me las arreglar姻.

[msg MSG_BEST_71_2 [Haru]]
*risa* Me siento genial. Creo que podr姻[n]ser de gran ayuda.

[msg MSG_BEST_72_1 [Akechi]]
Siento que podr胤a ayudar. 夷Me dejas[n]unirme?

[msg MSG_BEST_72_2 [Akechi]]
夷Estar胤a bien si me encargo de esto? Me[n]siento inusualmente capaz en este[n]momento.

[msg MSG_QUEST_32_0 [Rise]]
夷Te diriges a la proyecci吋n especial?
Tengo la navegaci吋n. 斡Aseg雨rate de que[n]Aigis y Haru est姻n en el grupo!

[msg MSG_QUEST_32_1 [Aigis]]
夷Vas a la proyecci吋n especial, verdad?
Por favor, comprueba que Haru y yo[n]estemos en el grupo, y que Rise nos[n]navega.

[msg MSG_QUEST_32_2 [Haru]]
夷Vas a la proyecci吋n especial?
Aseg雨rate de que Aigis y yo estemos en[n]el grupo, y que Rise sea la navegadora.

[msg MSG_QUEST_47 [Morgana]]
Si vas a la proyecci吋n especial,[n]aseg雨rate de llevarme en el grupo[n]principal.

[msg MSG_QUEST_48 [P4 Hero]]
Si te diriges a la proyecci吋n especial,[n]aseg雨rate de llevarme contigo.

[msg MSG_QUEST_49 [P3 Hero]]
Si vas a la proyecci吋n especial,[n]necesito estar en el grupo.

[msg MSG_QUEST_50 [P3 Fem Protag]]
Si vas a la proyecci吋n especial,[n]aseg雨rate de incluirme en el grupo.

[msg MSG_EX_BEST_00]
※Force quest targets to enter Great[n]Condition.

