[msg MSG_BEST_1_1 [P4 Hero]]
Me siento preparado. メTe importa si me uno a la pelea?

[msg MSG_BEST_1_2 [P4 Hero]]
メTe importa si me uno a la acciポn? Estoy en forma ahora mismo.

[msg MSG_BEST_2_1 [P3 Hero]]
メCrees que podrボa unirme? Siento que lo har〒 mejor de lo habitual.

[msg MSG_BEST_2_2 [P3 Hero]]
Siento que estoy en forma. メTe importa si voy contigo?

[msg MSG_BEST_3_1 [Yosuke]]
Oye, メte importarボa llevarme contigo? ムEstoy en racha!

[msg MSG_BEST_3_2 [Yosuke]]
Je, je, me siento imparable. ムLl〒vame contigo, no te decepcionar〒!

[msg MSG_BEST_4_1 [Chie]]
Estoy llena de energボa y lista para traer el ム"BAM"!

[msg MSG_BEST_4_2 [Chie]]
ムHiiiyah! ムMi energボa estホ al mホximo! ムD〒jame enfrentarlos!

[msg MSG_BEST_5_1 [Yukiko]]
Oye, d〒jame pelear tambi〒n. Siento que estoy en plena forma en este momento.

[msg MSG_BEST_5_2 [Yukiko]]
Siento algo ardiendo por dentro. ムSiento que puedo hacer cualquier cosa!

[msg MSG_BEST_6_1 [Rise]]
ムSボ, mi voz estホ en excelente forma ahora mismo! ムD〒jame encargarme de la navegaciポn!

[msg MSG_BEST_6_2 [Rise]]
ムMis niveles de energボa estホn al 100%! Lista para empezar.

[msg MSG_BEST_7_1 [Kanji]]
ムPonme ahボ! ムPuedo con ellos!

[msg MSG_BEST_7_2 [Kanji]]
ムSボ, me siento genial! ムLos enfrentar〒 a todos!

[msg MSG_BEST_8_1 [Naoto]]
メCrees que pueda unirme? Estoy en excelente forma en este momento.

[msg MSG_BEST_8_2 [Naoto]]
Estoy bien de salud y energボa. Lista para pelear.

[msg MSG_BEST_9_1 [Teddie]]
ムOh, yo! ムElボgeme a mボ! ムMe siento muy confiado!

[msg MSG_BEST_9_2 [Teddie]]
ムHrrrrraaah! ムPoder de Teddie al mホximo! ムD〒jame encargarme de esto!

[msg MSG_BEST_10_1 [Yukari]]
Sボ, me siento bien. Puedo resistir un golpe si lo necesitas.

[msg MSG_BEST_10_2 [Yukari]]
Parece que estoy en buena forma en este momento. メTe importarボa llevarme contigo?

[msg MSG_BEST_11_1 [Junpei]]
Je, je, ムme siento emocionado! ムLa leyenda de Junpei Iori comienza justo ahora!

[msg MSG_BEST_11_2 [Junpei]]
ムOh, sボ, estoy en la zona! Debes llevarme contigo.

[msg MSG_BEST_12_1 [Akihiko]]
Je, je, estos puワos estホn listos para pelear. Colポcame en la primera fila.

[msg MSG_BEST_12_2 [Akihiko]]
Me siento mホs afilado de lo habitual. ムD〒jame salir y demostrarlo!

[msg MSG_BEST_13_1 [Mitsuru]]
Parece que estoy en plena forma. メTe importarボa llevarme contigo?

[msg MSG_BEST_13_2 [Mitsuru]]
Estoy en perfectas condiciones. ムNuestros enemigos no tienen ninguna oportunidad!

[msg MSG_BEST_14_1 [Fuuka]]
Mm... me siento bastante bien en este momento. ムCreo que puedo ayudar!

[msg MSG_BEST_14_2 [Fuuka]]
メPuedo intentar navegar? Me siento bastante segura en este momento.

[msg MSG_BEST_15_1 [Aigis]]
Output al mホximo. ムPermボteme poner a prueba mi habilidad!

[msg MSG_BEST_15_2 [Aigis]]
ムEstoy en ポptimas condiciones! ムPermiso para desplegar!

[msg MSG_BEST_16_1 [Ken]]
ムMe siento genial! ムD〒jame unirme a la pelea!

[msg MSG_BEST_16_2 [Ken]]
Mm... メPodrボas dejarme pelear? ムTe prometo que no te arrepentirホs!

[msg MSG_BEST_17_1 [Koromaru]]
ムGuau, guau!

[msg MSG_BEST_17_2 [Koromaru]]
ムGuau! ムAuuuu!

[msg MSG_BEST_18_1 [Shinjiro]]
Oye, メte importa si me uno? No te arrepentirホs.

[msg MSG_BEST_18_2 [Shinjiro]]
Ah, no me siento nada mal en este momento. Permボteme hacerles algo de daワo.

[msg MSG_BEST_19_1 [P3 Fem Protag]]
Oye, メte importa si voy contigo? ムPrometo darlo todo!

[msg MSG_BEST_19_2 [P3 Fem Protag]]
ムSiento que podrボa enfrentar al mundo entero! ムVamos a por ello!

[msg MSG_BEST_64_1 [Morgana]]
Oh, estホs en sintonボa. ムMu〒stranos de qu〒 estホs hecho!

[msg MSG_BEST_64_2 [Morgana]]
Oye, te ves bien. ムSal ahボ y derrota a algunas Sombras!

[msg MSG_BEST_65_1 [Ryuji]]
Oye, メte importa si me uno? Siento que quiero soltarme un poco.

[msg MSG_BEST_65_2 [Ryuji]]
Estoy superemocionado. Permボteme encargarme de esto.

[msg MSG_BEST_66_1 [Ann]]
Oye, メpuedo ir? ムEstoy lista!

[msg MSG_BEST_66_2 [Ann]]
ムSボ! ムEstoy en llamas! ムLista para la pelea!

[msg MSG_BEST_67_1 [Morgana]]
ムLl〒vame ahボ fuera! Puedo sentir que lo har〒 genial.

[msg MSG_BEST_67_2 [Morgana]]
Je, je... Estoy en plena forma. Este es mi momento de brillar.

[msg MSG_BEST_68_1 [Yusuke]]
Por favor, permボteme unirme. Confボo en que cumplir〒 tus expectativas.

[msg MSG_BEST_68_2 [Yusuke]]
ムEstoy lleno de inspiraciポn! ムEste es mi momento!

[msg MSG_BEST_69_1 [Makoto]]
メPuedo ir? Siento que estoy en buena forma.

[msg MSG_BEST_69_2 [Makoto]]
Estoy rebosante de energボa. Permボteme ayudar.

[msg MSG_BEST_70_1 [Futaba]]
ムMe siento 3 veces mホs poderosa! ムVamos allホ!

[msg MSG_BEST_70_2 [Futaba]]
ムEstoy lista! ムSiento que podrボa navegar con los ojos cerrados!

[msg MSG_BEST_71_1 [Haru]]
メEstホ bien si me encargo? Te prometo que me las arreglar〒.

[msg MSG_BEST_71_2 [Haru]]
*risita* Me siento genial. Creo que podr〒 ser de gran ayuda.

[msg MSG_BEST_72_1 [Akechi]]
Creo que podrボa ayudar. メMe dejas unirme?

[msg MSG_BEST_72_2 [Akechi]]
メEstホ bien si me encargo de esto? Me siento inusualmente capaz.

[msg MSG_QUEST_32_0 [Rise]]
メTe diriges a la proyecciポn especial?
Tengo la navegaciポn. ムAsegマrate de que Aigis y Haru est〒n en el grupo!

[msg MSG_QUEST_32_1 [Aigis]]
メVas a la proyecciポn especial, verdad?
Por favor, comprueba que Haru y yo estemos en el grupo, y que Rise haga de navegaciポn.

[msg MSG_QUEST_32_2 [Haru]]
メVas a la proyecciポn especial?
Asegマrate de que Aigis y yo estemos en el grupo, y que Rise haga de navegaciポn.

[msg MSG_QUEST_47 [Morgana]]
Si vas a la proyecciポn especial, asegマrate de llevarme en el grupo principal.

[msg MSG_QUEST_48 [P4 Hero]]
Si te diriges a la proyecciポn especial, asegマrate de llevarme contigo.

[msg MSG_QUEST_49 [P3 Hero]]
Si vas a la proyecciポn especial, necesito estar en el grupo.

[msg MSG_QUEST_50 [P3 Fem Protag]]
Si vas a la proyecciポn especial, asegマrate de incluirme en el grupo.

[msg MSG_EX_BEST_00]
※Force quest targets to enter Great Condition.

