[msg MSG_BEST_1_1 [P4 Hero]]
Me siento preparado. メTe importa si me[n]uno a la pelea?

[msg MSG_BEST_1_2 [P4 Hero]]
メTe importa si me uno a la acciポn? Estoy[n]en forma en este momento.

[msg MSG_BEST_2_1 [P3 Hero]]
メCrees que podrボa unirme a ti? Siento[n]que lo har〒 mejor de lo habitual.

[msg MSG_BEST_2_2 [P3 Hero]]
Siento que estoy en forma. メTe importa[n]si vengo contigo?

[msg MSG_BEST_3_1 [Yosuke]]
Oye, メte importarボa llevarme contigo?[n]ムEstoy en racha!

[msg MSG_BEST_3_2 [Yosuke]]
Jeje, me siento imparable. ムLl〒vame[n]contigo y no te decepcionar〒!

[msg MSG_BEST_4_1 [Chie]]
Estoy llena de energボa y lista para[n]traer el ム"BAM"!

[msg MSG_BEST_4_2 [Chie]]
ムHiiiyah! ムMi indicador de energボa estホ[n]lleno! ムD〒jame enfrentarlos!

[msg MSG_BEST_5_1 [Yukiko]]
Oye, d〒jame pelear tambi〒n. Siento que[n]estoy en plena forma en este momento.

[msg MSG_BEST_5_2 [Yukiko]]
Siento algo ardiendo por dentro. ムSiento[n]que puedo hacer cualquier cosa!

[msg MSG_BEST_6_1 [Rise]]
ムSボ, mi voz estホ en excelente forma[n]ahora mismo! ムD〒jame encargarme de la[n]navegaciポn!

[msg MSG_BEST_6_2 [Rise]]
ムLos niveles de energボa estホn al 100%![n]Deberボa estar lista para empezar.

[msg MSG_BEST_7_1 [Kanji]]
ムPonme ahボ! ムPuedo con ellos!

[msg MSG_BEST_7_2 [Kanji]]
ムSボ, me siento genial! ムLos enfrentar〒 a[n]todos!

[msg MSG_BEST_8_1 [Naoto]]
メCrees que pueda unirme? Estoy en[n]excelente forma en este momento.

[msg MSG_BEST_8_2 [Naoto]]
Estoy bien de salud y energボa. Lista[n]para pelear.

[msg MSG_BEST_9_1 [Teddie]]
ムOh, yo! ムElボgeme a mボ! ムMe siento muy[n]confiado!

[msg MSG_BEST_9_2 [Teddie]]
ムHrrrrraaah! ムPoder de Teddie al mホximo![n]ムD〒jame encargarme de esto!

[msg MSG_BEST_10_1 [Yukari]]
Sボ, me siento bien. Puedo resistir un[n]golpe si lo necesitas.

[msg MSG_BEST_10_2 [Yukari]]
Parece que estoy en buena forma en este[n]momento. メTe importarボa llevarme[n]contigo?

[msg MSG_BEST_11_1 [Junpei]]
Jeje, ムme siento emocionado! ムLa leyenda[n]de Junpei Iori comienza justo despu〒s de[n]esto!

[msg MSG_BEST_11_2 [Junpei]]
ムOh, sボ, estoy en la zona! Debes[n]llevarme contigo.

[msg MSG_BEST_12_1 [Akihiko]]
Jeje, estos puワos estホn listos para[n]pelear. Colポcame en primera fila.

[msg MSG_BEST_12_2 [Akihiko]]
Me siento mホs afilado de lo habitual.[n]ムD〒jame salir y demostrarlo!

[msg MSG_BEST_13_1 [Mitsuru]]
Parece que estoy en plena forma. メTe[n]importarボa llevarme contigo?

[msg MSG_BEST_13_2 [Mitsuru]]
Estoy en perfectas condiciones.[n]ムNuestros enemigos no tienen ninguna[n]oportunidad!

[msg MSG_BEST_14_1 [Fuuka]]
Um... me siento bastante bien en este[n]momento. ムCreo que puedo ayudar!

[msg MSG_BEST_14_2 [Fuuka]]
メPuedo intentar navegar? Me siento[n]bastante segura en este momento.

[msg MSG_BEST_15_1 [Aigis]]
Salida al mホximo. ムPermボteme poner a[n]prueba mi habilidad!

[msg MSG_BEST_15_2 [Aigis]]
ムEstoy en ポptima condiciポn! ムPermiso[n]para desplegar!

[msg MSG_BEST_16_1 [Ken]]
ムMe siento genial! ムD〒jame unirme a la[n]pelea!

[msg MSG_BEST_16_2 [Ken]]
Um... メPodrボas dejarme pelear? ムTe[n]prometo que no te arrepentirホs!

[msg MSG_BEST_17_1 [Koromaru]]
ムGuau, guau!

[msg MSG_BEST_17_2 [Koromaru]]
ムGuau! ムAuuuu!

[msg MSG_BEST_18_1 [Shinjiro]]
Oye, メte importa si me uno? No te[n]arrepentirホs.

[msg MSG_BEST_18_2 [Shinjiro]]
Huh, no me siento nada mal en este[n]momento. Permボteme hacerles algo de[n]daワo.

[msg MSG_BEST_19_1 [P3 Fem Protag]]
Oye, メte importa si voy contigo?[n]ムPrometo darlo todo!

[msg MSG_BEST_19_2 [P3 Fem Protag]]
ムSiento que podrボa enfrentar al mundo[n]entero! ムVamos a por ello!

[msg MSG_BEST_64_1 [Morgana]]
Oh, estホs en sintonボa. ムMu〒stranos de[n]qu〒 estホs hecho!

[msg MSG_BEST_64_2 [Morgana]]
Oye, te ves bien. ムSal ahボ y derrota a[n]algunas Sombras!

[msg MSG_BEST_65_1 [Ryuji]]
Oye, メte importa si me uno? Siento que[n]quiero soltarme un poco.

[msg MSG_BEST_65_2 [Ryuji]]
Amigo, estoy sマper emocionado. Permボteme[n]encargarme de esto.

[msg MSG_BEST_66_1 [Ann]]
Oye, メpuedo ir? ムEstoy lista!

[msg MSG_BEST_66_2 [Ann]]
ムSボ! ムEstoy en llamas! ムLista para la[n]pelea!

[msg MSG_BEST_67_1 [Morgana]]
ムLlevame ahボ afuera! Puedo sentir que[n]voy a hacerlo genial.

[msg MSG_BEST_67_2 [Morgana]]
Nyahaha... Estoy en plena forma. Este es[n]mi momento para brillar.

[msg MSG_BEST_68_1 [Yusuke]]
Por favor, permボteme unirme. Confボo en[n]que cumplir〒 tus expectativas.

[msg MSG_BEST_68_2 [Yusuke]]
ムEstoy lleno de inspiraciポn! ムEste es mi[n]momento!

[msg MSG_BEST_69_1 [Makoto]]
メPuedo ir? Siento que estoy en buena[n]forma.

[msg MSG_BEST_69_2 [Makoto]]
Estoy rebosante de energボa. Permボteme[n]ayudar.

[msg MSG_BEST_70_1 [Futaba]]
ムMe siento 3 veces mホs poderosa! ムVamos[n]allホ!

[msg MSG_BEST_70_2 [Futaba]]
ムEstoy lista! ムSiento que podrボa navegar[n]con los ojos cerrados!

[msg MSG_BEST_71_1 [Haru]]
メEstホ bien si me encargo de esto? Te[n]prometo que me las arreglar〒.

[msg MSG_BEST_71_2 [Haru]]
*risa* Me siento genial. Creo que podr〒[n]ser de gran ayuda.

[msg MSG_BEST_72_1 [Akechi]]
Siento que podrボa ayudar. メMe dejas[n]unirme?

[msg MSG_BEST_72_2 [Akechi]]
メEstarボa bien si me encargo de esto? Me[n]siento inusualmente capaz en este[n]momento.

[msg MSG_QUEST_32_0 [Rise]]
メTe diriges a la proyecciポn especial?
Tengo la navegaciポn. ムAsegマrate de que[n]Aigis y Haru est〒n en el grupo!

[msg MSG_QUEST_32_1 [Aigis]]
メVas a la proyecciポn especial, verdad?
Por favor, comprueba que Haru y yo[n]estemos en el grupo, y que Rise nos[n]navega.

[msg MSG_QUEST_32_2 [Haru]]
メVas a la proyecciポn especial?
Asegマrate de que Aigis y yo estemos en[n]el grupo, y que Rise sea la navegadora.

[msg MSG_QUEST_47 [Morgana]]
Si vas a la proyecciポn especial,[n]asegマrate de llevarme en el grupo[n]principal.

[msg MSG_QUEST_48 [P4 Hero]]
Si te diriges a la proyecciポn especial,[n]asegマrate de llevarme contigo.

[msg MSG_QUEST_49 [P3 Hero]]
Si vas a la proyecciポn especial,[n]necesito estar en el grupo.

[msg MSG_QUEST_50 [P3 Fem Protag]]
Si vas a la proyecciポn especial,[n]asegマrate de incluirme en el grupo.

[msg MSG_EX_BEST_00]
※Force quest targets to enter Great[n]Condition.

