[msg OKAERI_ERROR]
Si esto sale, es un bug. ムRepポrtalo,[n]por favor!

[msg town_okaeri_HIKARI_mes01]
...メEstホs... herido...?

[msg town_okaeri_HIKARI_mes02]
Bienvenido...

[msg town_okaeri_HIKARI_mes03]
ムSon TODOS...! Me alegra que hayan[n]vuelto.

[msg town_okaeri_HIKARI_mes04]
Vamos a asegurarnos de estar listos[n]antes de salir.

[msg town_okaeri_HIKARI_mes05]
ムBienvenidos!

[msg town_okaeri_NAGI_mes01]
Asegマrense de descansar lo necesario.

[msg town_okaeri_NAGI_mes02]
Me alegra que est〒s a salvo.

[msg town_okaeri_RYUJI_mes]
Uf, estoy hecho polvo.

[msg town_okaeri_ANN_mes]
Ja... ムBuen trabajo!

[msg town_okaeri_MONA_mes]
ムTodos lo hicieron excelente!

[msg town_okaeri_YUSUKE_mes]
Fue una experiencia bastante[n]estimulante.

[msg town_okaeri_FUTABA_mes]
Mis ojos... Todo esto hace que me[n]duela la cabeza.

[msg town_okaeri_AKECHI_mes]
Justo a tiempo. Necesitamos un[n]respiro.

[msg town_okaeri_P3HERO2_mes]
ムAsegur〒monos de estar preparados!

[msg town_okaeri_MAKOTO_mes]
Deberボamos descansar mientras[n]podamos.

[msg town_okaeri_HARU_mes]
ムNada como un poco de ejercicio!

[msg town_okaeri_P4HERO_mes]
Buen trabajo.

[msg town_okaeri_CHIE_mes]
ムNo puedo luchar con el estポmago[n]vacボo!

[msg town_okaeri_YUKIKO_mes]
El descanso tambi〒n es importante.

[msg town_okaeri_RISE_mes]
ムBuen trabajo, chicos!

[msg town_okaeri_KANJI_mes]
ムIr〒 a prepararme para la prポxima[n]carrera!

[msg town_okaeri_NAOTO_mes]
Aprovechemos esta oportunidad para[n]descansar.

[msg town_okaeri_KUMA_mes]
メY? メMe veボa genial no?

[msg town_okaeri_YOUSUKE_mes]
ムVamos a tomar un descanso, y[n]regresar!

[msg town_okaeri_YUKARI_mes]
Mis piernas me estホn matando...

[msg town_okaeri_JUNPEI_mes]
ムEs hora de un descanso!

[msg town_okaeri_SANADA_mes]
Bien... Un pequeワo enfriamiento[n]muscular debe ayudar.

[msg town_okaeri_MITURU_mes]
El reaprovisionamiento es crucial[n]para la victoria.

[msg town_okaeri_FUKA_mes]
ムBuen trabajo!

[msg town_okaeri_AMADA_mes]
Creo que aマn puedo seguir luchando...

[msg town_okaeri_KOROMARU_mes]
Arf, ムArf!

[msg town_okaeri_ARAGAKI_mes]
Respiremos. Luego volvemos a entrar.

[msg town_okaeri_P3HERO_mes]
No tiene nada de malo tomarse un[n]respiro.

[msg town_okaeri_AEGIS_mes]
ムSolicito mantenimiento!

[msg town_returnitem_RYUJI_me]
メNos hemos quedado sin Talue-Gos?

[msg town_returnitem_ANN_mes]
メTienen suficientes Talue-Gos?

[msg town_returnitem_MONA_mes]
ムAsegマrate de llevar algunos[n]Talue-Gos!

[msg town_returnitem_YUSUKE_m]
Los Talue-Gos son importantes. No[n]debemos olvidarlos.

[msg town_returnitem_FUTABA_m]
ムOye, trae algunos Talue-Gos!

[msg town_returnitem_AKECHI_m]
メTenemos Talue-Gos, no?

[msg town_returnitem_P3HERO2_]
ムNo olvides traer Talue-Gos!

[msg town_returnitem_MAKOTO_m]
No olvides que necesitamos Talue-Gos.

[msg town_returnitem_HARU_mes]
Deberボamos comprar algunos Talue-Gos[n]primero, メno?

[msg town_returnitem_P4HERO_m]
Deberボas ir a buscar Talue-Gos.

[msg town_returnitem_CHIE_mes]
メNo necesitamos algunos Talue-Gos?

[msg town_returnitem_YUKIKO_m]
メPor qu〒 no compramos Talue-Gos?

[msg town_returnitem_RISE_mes]
ムNecesitamos Talue-Gos!

[msg town_returnitem_KANJI_me]
Oye, deberボas tomar uno de esos[n]Talue-Gos...

[msg town_returnitem_NAOTO_me]
Aconsejo que llevemos algunos[n]Talue-Gos.

[msg town_returnitem_KUMA_mes]
メNos quedamos sin Talue-Gos?

[msg town_returnitem_YOUSUKE_]
ムVamos por unos Talue-Gos!

[msg town_returnitem_YUKARI_m]
メConseguiste un Talue-Go?

[msg town_returnitem_JUNPEI_m]
No vendrボa mal un Talue-Go.

[msg town_returnitem_SANADA_m]
Serホ mejor que tengas algunos[n]Talue-Gos a mano.

[msg town_returnitem_MITURU_m]
メAマn nos quedan algunos Talue-Gos?

[msg town_returnitem_FUKA_mes]
メSeguro que no necesitas Talue-Gos?

[msg town_returnitem_AMADA_me]
メNo deberボamos llevar al menos un[n]Talue-Go?

[msg town_returnitem_ARAGAKI_]
Talue-Gos. No lo olvides.

[msg town_returnitem_P3HERO_m]
メEstarホs bien sin Talue-Gos?

[msg town_returnitem_AEGIS_me]
ムDebemos comprar Talue-Gos!

[msg town_new_quest_RYUJI_mes]
メNo deberボamos revisar la taquilla?

[msg town_new_quest_ANN_mes]
Echemos un vistazo a la taquilla.

[msg town_new_quest_MONA_mes]
Deberボamos revisar la taquilla con[n]frecuencia.

[msg town_new_quest_YUSUKE_me]
Creo que alguien nos vigila desde la[n]taquilla...

[msg town_new_quest_FUTABA_me]
Revisa la taquilla de vez en cuando.

[msg town_new_quest_AKECHI_me]
メQu〒, no pasaremos por la taquilla?

[msg town_new_quest_P3HERO2_m]
ムDeberボamos revisar la taquilla!

[msg town_new_quest_MAKOTO_me]
メQuizホ deberボamos pasar por la[n]taquilla?

[msg town_new_quest_HARU_mes]
メNo iremos a la taquilla?

[msg town_new_quest_P4HERO_me]
メNo deberボamos pasar por la taquilla?

[msg town_new_quest_CHIE_mes]
メVas a revisar la taquilla?

[msg town_new_quest_YUKIKO_me]
メPor qu〒 no pasamos por la taquilla?

[msg town_new_quest_RISE_mes]
ムVamos a revisar la taquilla!

[msg town_new_quest_KANJI_mes]
メSeguro que no deberボamos pasar por[n]la taquilla?

[msg town_new_quest_NAOTO_mes]
Una visita a la taquilla no serボa[n]mala idea...

[msg town_new_quest_KUMA_mes]
ムLa taquilla me estホ llamando!

[msg town_new_quest_YOUSUKE_m]
メQuieres pasar por la taquilla?

[msg town_new_quest_YUKARI_me]
Echemos un vistazo a la taquilla.

[msg town_new_quest_JUNPEI_me]
ムDebemos revisar la taquilla!

[msg town_new_quest_SANADA_me]
メNo vamos a la taquilla?

[msg town_new_quest_MITURU_me]
メNo serボa buena idea revisar la[n]taquilla?

[msg town_new_quest_FUKA_mes]
メNo deberボas revisar la taquilla?

[msg town_new_quest_AMADA_mes]
メDeberボamos pasar por la taquilla?

[msg town_new_quest_ARAGAKI_m]
メQu〒, vamos a la taquilla?

[msg town_new_quest_P3HERO_me]
メVamos a revisar la taquilla?

[msg town_new_quest_AEGIS_mes]
メNo necesitas pasar por la taquilla?

[msg town_persona_max_RYUJI_m]
Creo que tienes demasiadas Personas.

[msg town_persona_max_ANN_mes]
ムTienes demasiadas Personas!

[msg town_persona_max_MONA_me]
ムTenemos que hacer espacio para mホs[n]Personas!

[msg town_persona_max_YUSUKE_]
No podemos llevar mホs Personas...

[msg town_persona_max_FUTABA_]
ムNo puedes llevar mホs Personas!

[msg town_persona_max_AKECHI_]
No parece que podamos llevar mホs[n]Personas.

[msg town_persona_max_P3HERO2]
Parece que estamos al lボmite de[n]Personas.

[msg town_persona_max_MAKOTO_]
Tenemos demasiadas Personas.

[msg town_persona_max_HARU_me]
Parece que no podemos obtener mホs[n]Personas...

[msg town_persona_max_P4HERO_]
Parece que estホs al lボmite de[n]Personas...

[msg town_persona_max_CHIE_me]
ムTienes demasiadas Personas!

[msg town_persona_max_YUKIKO_]
Creo que esto es lo mホximo que[n]podemos llevar...

[msg town_persona_max_RISE_me]
Estホs al lボmite de Personas.

[msg town_persona_max_KANJI_m]
メNo podemos obtener mホs Personas?

[msg town_persona_max_NAOTO_m]
No puedes tener mホs Personas...

[msg town_persona_max_KUMA_me]
ムTienes demasiadas Osonas en tus[n]manos!

[msg town_persona_max_YOUSUKE]
Parece que tienes demasiadas[n]Personas.

[msg town_persona_max_YUKARI_]
メNo estホs al lボmite de Personas?

[msg town_persona_max_JUNPEI_]
Oye, メsabes que tienes "Personas" por[n]todas partes?

[msg town_persona_max_SANADA_]
Parece que llevas demasiadas[n]Personas...

[msg town_persona_max_MITURU_]
Tu lボmite de Personas estホ lleno.

[msg town_persona_max_FUKA_me]
Parece que estホs en el lボmite de[n]Personas...

[msg town_persona_max_AMADA_m]
Parece que no puedes llevar mホs[n]Personas.

[msg town_persona_max_ARAGAKI]
Oye. Estホs al lボmite de Personas.

[msg town_persona_max_P3HERO_]
Creo que son todas las que podemos[n]llevar...

[msg town_persona_max_AEGIS_m]
ムNuestro lボmite de Personas estホ al[n]mホximo de capacidad!

[msg town_item_max_RYUJI_mes]
メNo crees que podrボamos aligerar la[n]carga?

[msg town_item_max_ANN_mes]
Llevas un montポn de cosas, メeh?

[msg town_item_max_MONA_mes]
Vendamos un tesoro y aligeremos la[n]carga.

[msg town_item_max_YUSUKE_mes]
Una bolsa demasiado llena es un poco[n]inマtil, メno crees?

[msg town_item_max_FUTABA_mes]
Oye, ムllevas demasiadas cosas!

[msg town_item_max_AKECHI_mes]
Sugiero aligerar la carga...

[msg town_item_max_P3HERO2_me]
メPor qu〒 llevamos esto?

[msg town_item_max_MAKOTO_mes]
Veamos qu〒 podemos hacer para no[n]llevar tanto.

[msg town_item_max_HARU_mes]
Quizホ deberボamos llevar menos cosas.

[msg town_item_max_P4HERO_mes]
Deberボas hacer espacio en tu bolsa de[n]objetos.

[msg town_item_max_CHIE_mes]
ムDiablos! Llevamos demasiadas cosas.

[msg town_item_max_YUKIKO_mes]
メNo serボa mejor si aligeramos la[n]carga?

[msg town_item_max_RISE_mes]
ムTu bolsa de objetos estホ llena!

[msg town_item_max_KANJI_mes]
Tu bolsa estホ llena.

[msg town_item_max_NAOTO_mes]
Parece que estamos sobrecargados.

[msg town_item_max_KUMA_mes]
ムNuestra bolsa es demasiado pesada!

[msg town_item_max_YOUSUKE_me]
メCrees que podrボamos dejar algo de[n]equipaje?

[msg town_item_max_YUKARI_mes]
メNo necesitamos un poco de espacio[n]para objetos?

[msg town_item_max_JUNPEI_mes]
ムTu bolsa estホ demasiado llena!

[msg town_item_max_SANADA_mes]
ムTienes demasiadas cosas! ムNo hay[n]donde llevar la proteボna!

[msg town_item_max_MITURU_mes]
Antes de irnos, aconsejo que limpiar[n]nuestra bolsa.

[msg town_item_max_FUKA_mes]
メTal vez deberボas hacer espacio en el[n]inventario?

[msg town_item_max_AMADA_mes]
Espera, creo que llevamos demasiadas[n]cosas.

[msg town_item_max_ARAGAKI_me]
メDe verdad tienes que llevar toda esa[n]mierda?

[msg town_item_max_P3HERO_mes]
Esa bolsa de objetos parece que va a[n]estallar.

[msg town_item_max_AEGIS_mes]
Estado del inventario: ムlleno!

[msg town_bg00_HIKARI_mes01]
Nagi...

[msg town_bg00_HIKARI_mes02]
Sボ...

[msg town_bg00_NAGI_mes01]
Intentemos ayudar como podamos.

[msg town_bg00_NAGI_mes02]
No tienes que tener miedo, Hikari.

[msg town_bg00_DOE_mes01]
...

[msg town_bg00_ANN_mes01]
Me pregunto qu〒 le pasa a este[n]lugar...

[msg town_bg00_ANN_mes02]
メQuieres echar un vistazo a la[n]tienda?

[msg town_bg00_ANN_mes03]
Me pregunto cuホnto llevan aquボ.

[msg town_bg00_YUSUKE_mes01]
Primero debemos saciar nuestra[n]hambre.

[msg town_bg00_YUSUKE_mes02]
No hay otros invitados aquボ,[n]parece...

[msg town_bg00_YUSUKE_mes03]
Las entradas son gratis, メverdad? No[n]tengo mucho dinero...

[msg town_bg00_FUTABA_mes01]
Inari, tu estポmago gruワe demasiado[n]fuerte.

[msg town_bg00_FUTABA_mes02]
Estoy preocupada por Makoto y Haru...

[msg town_bg00_FUTABA_mes03]
ムEs como si hubi〒ramos reservado un[n]cine entero para nosotros!

[msg town_bg00_AKECHI_mes01]
Este fenポmeno merece ser investigado.

[msg town_bg00_AKECHI_mes02]
Deberボamos darnos prisa. Tenemos que[n]salvarlas.

[msg town_bg00_AKECHI_mes03]
ムIntrigante! Este mundo es un[n]misterio...

[msg town_bg01_HIKARI_mes01]
...

[msg town_bg01_HIKARI_mes02]
Mmm, bueno... Ustedes...

[msg town_bg01_HIKARI_mes03]
Un festival de cine...

[msg town_bg01_RYUJI_mes01]
Mierda... No puedo dejar de comer.

[msg town_bg01_RYUJI_mes02]
Vamos, メpodrボan relajarse?

[msg town_bg01_RYUJI_mes03]
Creo que [f 6 1 30 0 0 0] y [f 6 1 27 0 0 0] se llevarボan[n]bien.

[msg town_bg01_MONA_mes01]
ムArgh, casi me haces derramarlo!

[msg town_bg01_MONA_mes02]
ムEste jugo es muy sabroso!

[msg town_bg01_FUTABA_mes01]
Je, je, je, ムQu〒 lento!

[msg town_bg01_FUTABA_mes02]
ムJe, je, je!

[msg town_bg01_P3HERO2_mes01]
Creo que el mホs parecido es Screen[n]Shot en la Isla del Puerto Tatsumi.

[msg town_bg01_P3HERO2_mes02]
ムTenemos un festival de cine en[n]Screen Shot en verano!

[msg town_bg01_P3HERO2_mes03]
ムOh, vives en el segundo piso de una[n]cafeterボa!

[msg town_bg02_HIKARI_mes01]
M-mmm... Bueno...

[msg town_bg02_HIKARI_mes02]
Y-yo... um...

[msg town_bg02_HIKARI_mes03]
メEh? ムE-en serio!

[msg town_bg02_NAGI_mes01]
Oh... *risita*

[msg town_bg02_NAGI_mes02]
Oh, Hikari...

[msg town_bg02_MAKOTO_mes01]
メHas visto "Like A Dragon", Hikari?

[msg town_bg02_MAKOTO_mes02]
メUn paraボso para dinosaurios...? Me[n]pregunto si eso realmente existe...

[msg town_bg02_MAKOTO_mes03]
メEstホn todos comiendo bien? La dieta[n]puede ser poco saludable...

[msg town_bg02_HARU_mes01]
No puedo esperar a ver "Pach-Saw" en[n]el cine.

[msg town_bg02_HARU_mes02]
Asegマrate de comer tus verduras[n]tambi〒n.

[msg town_bg02_CHIE_mes01]
Hikari, メalguna vez viste "Trial of[n]the Dragon"? メEl golpe de kung-fu?

[msg town_bg02_CHIE_mes02]
ムEstoy segura de que lo[n]averiguaremos! Verdad. メHikari?

[msg town_bg02_CHIE_mes03]
ムLa carne es la raボz de todas las comidas![n]ムLa carne nunca te traiciona!

[msg town_bg02_YUKIKO_mes01]
ム"Un texto perdido" me hizo reボr tan[n]fuerte que me doliポ el estポmago!

[msg town_bg02_YUKIKO_mes02]
*grito ahogado* Esto debe ser lo que[n]llaman "charla de chicas".

[msg town_bg02_RISE_mes01]
No puedo esperar por ver "Roman Paid[n]Holiday".

[msg town_bg02_RISE_mes02]
Cierto, el equilibrio es importante.[n]Tengo que pensar en la nutriciポn.

[msg town_bg02_RISE_mes03]
Mmm... Lホstima que nuestros sensores[n]no puedan ver mホs allホ del laberinto.

[msg town_bg03_MONA_mes01]
ムBASTAAA!

[msg town_bg03_MONA_mes02]
ムQuボtame las manos de encima![n]Arruinas mi pelaje.

[msg town_bg03_TEODOA_mes01]
Aunque parezca un objeto, con gusto[n]te ayudar〒 con mi tienda...

[msg town_bg03_YUSUKE_mes01]
Increボble... ムQu〒 forma tan[n]vanguardista!

[msg town_bg03_YUSUKE_mes02]
ムEspera, no te muevas! ムSolo otras[n]tres horas!

[msg town_bg03_AKECHI_mes01]
Es un honor tener la oportunidad de[n]charlar, Shirogane.

[msg town_bg03_AKECHI_mes02]
メQu〒 piensas de esto, Shirogane?

[msg town_bg03_KANJI_mes01]
Vamos, メsolo un poco? ムUn poquito![n]ムPor favor!

[msg town_bg03_KANJI_mes02]
Debo haber muerto y llegado al[n]cielo...

[msg town_bg03_NAOTO_mes01]
Bueno... si puedo ayudar, claro.

[msg town_bg03_NAOTO_mes02]
Creo que poco podemos hacer en este[n]caso...

[msg town_bg03_KUMA_mes01]
Nooo... S-se me estホn durmiendo las[n]piernas...

[msg town_bg03_KUMA_mes02]
Si miras tanto... me picarホ todo...

[msg town_bg04_DOE_mes01]
...

[msg town_bg04_ZABES_mes01]
...

[msg town_bg04_ANN_mes01]
メSabes tejer? ムVaya!

[msg town_bg04_ANN_mes02]
ムOh, eso es increボble!

[msg town_bg04_ANN_mes03]
メQuieres jugo, Kanji? メO soda?

[msg town_bg04_P3HERO2_mes01]
ムSボ! ムTrabajemos juntos y hagamos lo[n]mejor que podamos!

[msg town_bg04_P3HERO2_mes02]
Una vez que terminemos de descansar,[n]ムvolvamos a la pelボcula!

[msg town_bg04_P4HERO_mes01]
Es bueno tener amigos de nuestro[n]lado.

[msg town_bg04_P4HERO_mes02]
Tienes razポn. Serホ mejor que permanezcamos[n]alerta mientras avanzamos.

[msg town_bg04_KANJI_mes01]
ムD-Deja de mirar, maldita sea, o te[n]coser〒!

[msg town_bg04_KANJI_mes02]
Hay muchas clases, pero... conectas[n]asボ, y...

[msg town_bg04_KANJI_mes03]
No, la soda me da tos. Prefiero el[n]jugo.

[msg town_bg05_HIKARI_mes01]
Folletos... メTal vez deberボa leerlos[n]mホs tarde?

[msg town_bg05_HIKARI_mes02]
S-sボ... estar〒 esperando.

[msg town_bg05_TEO_mes01]
ムS-sボ! ムVoy!

[msg town_bg05_RYUJI_mes01]
Vamos a correr mucho, asボ que[n]necesitamos un nivel de azマcar alto.

[msg town_bg05_RYUJI_mes02]
Tres hot dogs y una orden grande de[n]papas. ムAh, y una soda!

[msg town_bg05_MAKOTO_mes01]
Ryuji, メcuホnta soda bebiste?

[msg town_bg05_MAKOTO_mes02]
Ah, eso es para la pelボcula de[n]Kamoshidaman de la sala 1.

[msg town_bg05_MAKOTO_mes03]
Una vez que hayamos descansado,[n]deberボamos volver a la pelボcula.

[msg town_bg05_YOUSUKE_mes01]
Vaya, incluso tienen folletos aquボ.

[msg town_bg05_YOUSUKE_mes02]
ムOye, Ryuji! Pide una bebida para mボ[n]tambi〒n, メsボ?

[msg town_bg05_YOUSUKE_mes03]
ムOye, Hikari! Espero que te guste el[n]final de la pelボcula.

[msg town_bg06_HIKARI_mes01]
Em, buena suerte, Futaba.

[msg town_bg06_HIKARI_mes02]
El poder de proporcionar apoyo, oh...[n]Eso es increボble...

[msg town_bg06_HIKARI_mes03]
メEres buena con las computadoras,[n]Futaba? Me encanta eso...

[msg town_bg06_YUSUKE_mes01]
Las palomitas estホn bien, pero me[n]gustarボa tener comida de verdad...

[msg town_bg06_YUSUKE_mes02]
ムメQ-qu〒 es esto?! ムEstホ delicioso!

[msg town_bg06_YUSUKE_mes03]
Barras de proteボna... メTambi〒n las[n]conseguirホ Theodore?

[msg town_bg06_FUTABA_mes01]
ムVamos a cambiar la pelボcula! ムMira,[n]Hikari!

[msg town_bg06_FUTABA_mes02]
ムSボ, d〒janoslo a nosotros!

[msg town_bg06_FUTABA_mes03]
Eso es... voy a arreglar esto, y...[n]Excelente. Mweheheh...

[msg town_bg06_RISE_mes01]
Ahora que tambi〒n tenemos a Fuuka,[n]ムestamos listas para el apoyo!

[msg town_bg06_RISE_mes02]
Tenemos que compartir toda nuestra[n]informaciポn. ムAunque no parezca relevante!

[msg town_bg06_SANADA_mes01]
Una barra de proteボnas, y una de las[n]mejores... メQuieres mホs?

[msg town_bg06_ZABES_mes01]
Ya veo...

[msg town_bg06_FUKA_mes01]
Podemos compartir la carga entre[n]nosotras. ムY ahora tenemos a Futaba!

[msg town_bg06_FUKA_mes02]
Tienes razポn. ムDemos el mejor apoyo[n]que podamos!

[msg town_bg07_DOE_mes01]
...

[msg town_bg07_P3HERO2_mes01]
Eso es... ムQu〒 chico tan listo,[n]Koromaru!

[msg town_bg07_P3HERO2_mes02]
ムJa, ja, ja, eso hace cosquillas![n]ムVaya, Koromaru!

[msg town_bg07_HARU_mes01]
ムKoro es tan suave! ムY tan lindo!

[msg town_bg07_HARU_mes02]
Je, je... Tu cola es esponjosa, Koro.

[msg town_bg07_YUKIKO_mes01]
ムKanetsugu, si〒ntate!

[msg town_bg07_ZABES_mes01]
Oh, Oso Teddie... Las llamas de celos[n]arden con fuerza...

[msg town_bg07_KUMA_mes01]
メCポmo se atreven? ムYo estoy aquボ...!

[msg town_bg07_KUMA_mes02]
Ese pequeワo...

[msg town_bg07_YUKARI_mes01]
Es tan agradable tener a Koro cerca.[n]ムEs muy listo! ムBuen chico!

[msg town_bg07_KOROMARU_mes01]
ムArf arf!

[msg town_bg07_KOROMARU_mes02]
ムWoof!

[msg town_bg07_KOROMARU_mes03]
*Jadeo jadeo*

[msg town_bg08_FUTABA_mes01]
ムOh! ムQu〒 bien!

[msg town_bg08_FUTABA_mes02]
H-hola, Naoto. ムEstamos comparando[n]los datos de Ribbon!

[msg town_bg08_HARU_mes01]
Fuuka, gracias por todo tu apoyo.

[msg town_bg08_HARU_mes02]
Este caf〒 tiene un sabor tan rico. Es[n]muy delicioso.

[msg town_bg08_HARU_mes03]
Futaba y Naoto estホn tan intrigadas[n]por Aigis.

[msg town_bg08_NAOTO_mes01]
Mmm, Aigis... メCポmo usas ese brazo?

[msg town_bg08_NAOTO_mes02]
メEstホs recopilando datos de Aigis,[n]Futaba?

[msg town_bg08_ZABES_mes01]
*risita* ムQu〒 acontecimientos tan[n]conmovedores!

[msg town_bg08_FUKA_mes01]
ムOh, tu habilidad con el hacha es[n]increボble! Estoy asombrada, Haru.

[msg town_bg08_FUKA_mes02]
ムOh! Este t〒 es delicioso.

[msg town_bg08_FUKA_mes03]
Algo parece haber llamado su[n]atenciポn...

[msg town_bg08_AEGIS_mes01]
ムEste brazo... se usa asボ!

[msg town_bg08_AEGIS_mes02]
Una vez que mis brazos sean[n]aprobados, comenzar〒 las pruebas.

[msg town_bg09_ZABES_mes01]
Oh, Koromaru descubriポ qui〒n estaba[n]robando sus bocadillos...

[msg town_bg09_MONA_mes01]
メPodrボan bajar la voz? Intento[n]relajarme.

[msg town_bg09_MONA_mes02]
Mmm... Sushi... Atマn... Zzz...

[msg town_bg09_MONA_mes03]
Vamos a descansar por hoy.

[msg town_bg09_MAKOTO_mes01]
Puede ayudarnos probar varias[n]combinaciones de miembros del equipo.

[msg town_bg09_MAKOTO_mes02]
Este es finalmente el マltimo.[n]Concentr〒monos.

[msg town_bg09_MAKOTO_mes03]
Ah, bueno. Podemos pasarlo por alto[n]mientras estemos aquボ, supongo.

[msg town_bg09_KUMA_mes01]
ムGyaaaaaah! ムLo siento!

[msg town_bg09_KUMA_mes02]
ムLo juro, no soy tan delicioso como[n]parezco!

[msg town_bg09_MITURU_mes01]
Nuestro grupo ha crecido. Necesitamos[n]conocernos.

[msg town_bg09_MITURU_mes02]
Estoy de acuerdo. Deberボamos[n]prepararnos.

[msg town_bg09_MITURU_mes03]
Honestamente... Qu〒 grupo tan alborotado.[n]Incluso Koromaru estホ irritado...

[msg town_bg09_KOROMARU_mes01]
ムGuau!

[msg town_bg09_KOROMARU_mes02]
Grrrrrr...

[msg town_bg10_ZABES_mes01]
Haaabitaciポn, oh terciopelo... Mi amo[n]tiene una nariz muy grande...

[msg town_bg10_RYUJI_mes01]
Uh. メAsボ que necesitan esto para[n]invocar a los suyos?

[msg town_bg10_RYUJI_mes02]
ムPerdポn, perdポn! A veces la[n]hipocresボa se apodera de mボ.

[msg town_bg10_AKECHI_mes01]
Bueno, cuando lo dices asボ, es[n]difボcil de explicar...

[msg town_bg10_AKECHI_mes02]
Por supuesto. Pero el trabajo de detective[n]no es tan glamoroso como en la TV...

[msg town_bg10_AKECHI_mes03]
メTienes planes para el futuro, Amada?

[msg town_bg10_YOUSUKE_mes01]
ムVaya, los Evocadores son impresionantes![n]Son geniales, pero un poco aterradores...

[msg town_bg10_YOUSUKE_mes02]
ムGah, idiota! ムNo me digas eso!

[msg town_bg10_JUNPEI_mes01]
Sボ. Ponlo en tu cabeza, tira el[n]gatillo y ムbam! ムPersona!

[msg town_bg10_JUNPEI_mes02]
Sigue siendo inquietante incluso cuando[n]sabes que es un Evocador, メverdad?

[msg town_bg10_AMADA_mes01]
メAsボ que eres detective, Akechi?[n]メCポmo te conviertes en uno?

[msg town_bg10_AMADA_mes02]
メPuedes enseワarme mホs sobre ser[n]detective mホs tarde?

[msg town_bg10_AMADA_mes03]
No s〒 si es un plan... pero quiero[n]volverme mホs fuerte.

[msg town_bg11_HIKARI_mes01]
ムEres increボble! ムSigue asボ!

[msg town_bg11_HIKARI_mes02]
ムLo tienes, Satonaka!

[msg town_bg11_HIKARI_mes03]
ムEstホs a la cabeza, Sanada! ムSigue[n]asボ, Aragaki!

[msg town_bg11_YUSUKE_mes01]
Esto es realmente delicioso... ムNo[n]puedo parar! ムNo voy a parar!

[msg town_bg11_YUSUKE_mes02]
La variedad de sabor a proteボnas no[n]es mala, tampoco...

[msg town_bg11_TEO_mes01]
ムQu〒 apetito! ムApenas puedo cumplir[n]la demanda de palomitas!

[msg town_bg11_HARU_mes01]
*risita* Este es el マltimo. Necesitar〒[n]mi fuerza.

[msg town_bg11_HARU_mes02]
Theodore, メme das un poco de t〒? Earl[n]Grey estarボa bien.

[msg town_bg11_CHIE_mes01]
ムOh! ムNo sabボa que era posible tragar[n]palomitas!

[msg town_bg11_CHIE_mes02]
ムHraaaaah! ムAquボ viene! ムPoder[n]femenino, desatado!

[msg town_bg11_CHIE_mes03]
Hrgh, tengo la boca seca... ムSi esto[n]fuera carne, ganarボa!

[msg town_bg11_YUKARI_mes01]
Wow, メCポmo pueden comer tanto...?

[msg town_bg11_YUKARI_mes02]
ムOh, t〒 de rosa mosqueta para mボ, por[n]favor!

[msg town_bg11_SANADA_mes01]
ムEs mi victoria, Shinji!

[msg town_bg11_SANADA_mes02]
Vamos, Shinji. メEs lo mejor que[n]tienes?

[msg town_bg11_ARAGAKI_mes01]
Tss. No puedo perder...

[msg town_bg11_ARAGAKI_mes02]
Tss. ムDe ninguna manera voy a ser derrotado[n]por un idiota relleno de palomitas!

[msg town_bg12_ANN_mes01]
ムEstホ bien! ムNos van a echar!

[msg town_bg12_ANN_mes03]
Ya voy a entrar. Hagホmoslo.

[msg town_bg12_P4HERO_mes01]
S〒 que podemos hacerlo. Pase lo que[n]pase.

[msg town_bg12_P4HERO_mes02]
El tiempo finalmente ha llegado... No[n]podemos perder.

[msg town_bg12_P4HERO_mes03]
Mostr〒mosle de qu〒 somos capaces.

[msg town_bg12_YOUSUKE_mes01]
メDeberボamos formar un cボrculo, o algo[n]asボ?

[msg town_bg12_YOUSUKE_mes02]
ムHagホmoslo, compaワero!

[msg town_bg12_YOUSUKE_mes03]
Muy bien. ムVamos, chicos!

[msg town_bg12_MITURU_mes01]
Debemos asegurarnos de que estamos[n]completamente preparados.

[msg town_bg12_MITURU_mes02]
Ha... Es hora de que terminemos con[n]esto.

[msg town_bg12_MITURU_mes03]
Vamos. Nuestra determinaciポn decidirホ[n]esto.

[msg town_bg12_P3HERO_mes01]
Armemos nuestra fuerza.

[msg town_bg12_P3HERO_mes02]
Esto es algo que podemos hacer.

[msg town_bg12_P3HERO_mes03]
メEstホn todos listos?

[msg town_bg12_AEGIS_mes01]
Vamos. Lucharemos juntos.

[msg town_bg12_AEGIS_mes02]
Voy a darlo todo. No perderemos.

[msg town_bg12_AEGIS_mes03]
Todos los preparativos completados.[n]Limitadores listos.

