[msg TOWN_DAMMY]
Dummy

[msg TOWN_PRE_PARTY_JOIN]
Ahora puedes usar [f 0 1 2]editar Grupo[f 0 1 0]. Adem茨s de las[n]ediciones de grupo que ya pod胤as hacer, ahora[n]puedes registrar y cargar grupos, y tambi姻n[n]cambiar de navegantes.

[msg TOWN_TUTORIAL_CAMP_PERSO]
PERSONA[f 0 1 0] se ha a隠adido al men雨. Usa X[n]para abrirlo.
Puedes equipar y cambiar Personas[n]Secundarias en la opci吋n [f 0 1 2]PERSONA[f 0 1 0] en el[n]men雨.

[msg TOWN_TUTORIAL_PARTY_JOIN]
Un nuevo miembro se ha unido a tu grupo[f 0 1 0], 斡as胤[n]que las posibilidades de tu grupo se han[n]ampliado! 夷Por qu姻 no pruebas diferentes[n]combinaciones de grupo?

[msg TOWN_TUTORIAL_VELVET_OPE]
La [f 0 1 2]Habitaci吋n Terciopelo[f 0 1 0] ahora est茨[n]disponible. All胤 puedes crear nuevas Personas[n]a trav姻s de fusiones e invocarlas desde el[n]Compendio de Personas.

[msg TOWN_TUTORIAL_NOFFICE_OP]
La [f 0 1 2]Oficina de Enfermer胤a[f 0 1 0] ahora est茨[n]disponible. Los miembros del grupo[n]heridos pueden recibir tratamiento all胤.

[msg TOWN_TUTORIAL_SHOP_OPEN]
La [f 0 1 2]Tienda[f 0 1 0] ahora est茨 disponible. Puedes[n]comprar y vender equipo y objetos aqu胤,[n]as胤 como almacenarlos.

[msg TOWN_TUTORIAL_DUNGEON_OP]
Ahora puedes seleccionar [f 0 1 2]Entrar en la[n]Pel胤cula[f 0 1 0]. Podr茨s ingresar al laberinto y[n]continuar la historia o aceptar solicitudes.

[msg MSG_FCL_QUEST_OPEN [Futaba]]
斡Parece que ahora hay una taquilla de[n]cine!

[msg TOWN_TUTORIAL_ODEKAKE_OP]
Ahora puedes dar [f 0 1 2]Paseos[f 0 1 0] por la escuela y[n]pasar tiempo con tus compa隠eros.

[msg TOWN_TUTORIAL_VELVET_TRI]
Ahora puedes realizar la [f 0 1 2]Fusi吋n Avanzada[f 0 1 0][n]en la Habitaci吋n Terciopelo, que fusiona[n]tres Personas juntas.

[msg TOWN_TUTORIAL_NOFFICE_QU]
Ahora puedes aceptar [f 0 1 2]"Solicitudes"[f 0 1 0] en la[n]Oficina de Enfermer胤a.

[msg TOWN_TUTORIAL_CAMP_QUEST]
Verifica tus solicitudes actuales en[n][f 0 1 2]SISTEMA[f 0 1 0] en el men雨.

[msg TOWN_TUTORIAL_CAMP_QUEST_2 [Futaba]]
Mira las solicitudes que has aceptado.

[msg TOWN_TUTORIAL_CAMP_QUEST_3 [Futaba]]
Tambi姻n puedes ver los [f 0 1 2]detalles[f 0 1 0] de una[n]solicitud seleccion茨ndola.

[msg TOWN_TUTORIAL_QUEST_REPO]
Una vez hayas cumplido los requisitos de una[n]solicitud, ve a la Oficina de Enfermer胤a y[n][f 0 1 2]reporta[f 0 1 0] la solicitud. 斡Despu姻s de todo, no[n]recibir茨s ninguna recompensa si no la[n]reportas!

[msg TOWN_TO_DUNGEON]
T雨 o uno de los miembros de tu grupo no[n]tienen una Persona Secundaria equipada.

[msg TOWN_TO_GREED1]
挨拶１。

[msg TOWN_TO_GREED2]
挨拶２。

[msg MSG_TUTORIAL_PROTO_START]
【プロ:２ＲＯＭＳＴＡＲＴ】 ”ク夷ス:受注施設”かp[n]”ヒーローベル:y探せ”y受注しG 迷宮探索y開始しGくAさい。

[msg MSG_TUTORIAL_QUEST1]
Las misiones se pueden acceder en las[n]instalaciones de solicitud.

[msg MSG_TUTORIAL_QUEST2]
Despu姻s de completar una solicitud,[n]rep吋rtala en las instalaciones de[n]solicitud.

[msg MSG_SHOP_OPEN [Futaba]]
斡Hubo un fuerte ruido cerca de la[n]tienda!

[msg MSG_V_ROOM_ONLY [Futaba]]
Veamos qu姻 nos ofrece la Habitaci吋n[n]Terciopelo.

[msg MSG_TUTORIAL_NAVI_OPEN_S]
Debido a un miembro adicional, ahora puedes[n]clasificar a los navegadores en especialidades[n]de [f 0 1 2]combate[f 0 1 0] y [f 0 1 2]exploraci吋n[f 0 1 0]. Hazlo en la[n][f 0 1 2]configuraci吋n de Navegadores[f 0 1 0] en "Grupo"[n]mientras est茨s en el cine.

[msg MSG_DEBUG_BEST_01 [Futaba]]
※,バ7雨用 5回以上連戦しGいた＆既L絶好調O人が いたOH、絶好調終了！

[msg MSG_DEBUG_BEST_02 [Futaba]]
※,バ7雨用 ハズレ！誰i絶好調LKqeせz！

[msg MSG_DEBUG_BEST_03 [Futaba]]
※,バ7雨用 威3リ！誰かが絶好調LKqeす！

[msg MSG_SUB_PERSONA_OPEN]
Las [f 0 1 2]Personas Secundarias[f 0 1 0] se han[n]desbloqueado.

[msg MSG_CAMP_MENU_OPEN]
Presiona el [f 0 1 2]Bot吋n X[f 0 1 0] para abrir el Men雨.[n]Ah胤 puedes usar objetos o habilidades, y[n]ver el estado de tu grupo.
Mientras investigas, presiona [f 0 1 2]START[f 0 1 0] en[n]el men雨 para realizar una suspensi吋n de[n]guardado.

[msg MSG_SHOP_OPEN_GUIDE]
Ahora puedes usar la [f 0 1 2]Tienda[f 0 1 0]. Compra[n][f 0 1 2]objetos[f 0 1 0] y [f 0 1 2]equipamiento[f 0 1 0] para avanzar con[n]seguridad en el calabozo.

[msg MSG_FCL_ITE_RETURN_ALERT [Futaba]]
斡Oye, detente ah胤! No tenemos ning雨n[n]Talue-Gos. 斡Necesitamos Talue-Gos!

[msg PERSONA_STOCK_UP_MSG]
Ahora que otra persona con el poder del[n]comod胤n se ha unido, tu inventario de[n]Personas ha aumentado a [f 0 1 2][f 2 4 0][f 0 1 0].

[msg MSG_KARI_JOIN_HAMUKO]
P3女性主人公が加入しeした！ ※仲間加入画像くreHO仮表示！！

[msg MSG_KARI_JOIN_HARUMAKO]
春I真が加入しeした！ ※仲間加入画像くreHO仮表示！！

[msg MSG_KARI_JOIN_P4MAJORITY]
陽介除くＰ４メンバーが加入しeした！ ※仲間加入画像くreHO仮表示！！

[msg MSG_KARI_JOIN_YOSUKE]
陽介が加入しeした！ ※仲間加入画像くreHO仮表示！！

[msg MSG_KARI_JOIN_P3MAJORITY]
キ3ロー威姻/スy除くＰ３メンバーが 加入しeした！※仮表示！！

[msg MSG_KARI_JOIN_KITAAI]
キ3ロー威姻/スが加入しeした！ ※仲間加入画像くreHO仮表示！！

