[msg WSHOP_HELLO_MARGARET [Margaret]]
★未使用！

[msg WSHOP_HELLO_NAGI_0 [Nagi]]
ムOh, vaya, estホs aquボ!

[msg WSHOP_HELLO_NAGI_1 [Nagi]]
Bienvenido.

[msg WSHOP_HELLO_THEODORE_0 [Theodore]]
Hola y bienvenido.

[msg WSHOP_HELLO_THEODORE_1 [Theodore]]
Bienvenido. Me alegra verte.

[msg WSHOP_HELLO_THEODORE_2 [Theodore]]
Te he estado esperando.

[msg WSHOP_HELLO_NANAKO [Nanako]]
Not used

[msg WSHOP_WARNING [Theodore]]
★未使用！

[msg WSHOP_DISCOUNT1_P1 [Theodore]]
Ah, bienvenido.
メOh...? Veo que tienes un [f 4 4 3 0 1636].
ムFelicidades! ムEse es uno de mis cupones[n]hechos a mano!
Esto te darホ un [f 0 1 2]descuento del 10% en[n]todos los productos[f 0 1 0].
Que continマen con una experiencia de[n]compra satisfactoria.

[msg WSHOP_DISCOUNT1_P2 [Theodore]]
Ah, bienvenido.
メOh...? Veo que tienes un [f 4 4 3 0 1637].
ムFelicidades! ムEse es uno de mis cupones[n]hechos a mano!
Esto te darホ un [f 0 1 2]descuento del 10% en[n]todos los productos[f 0 1 0].
Que continマen con una experiencia de[n]compra satisfactoria.

[msg WSHOP_DISCOUNT1_P3 [Theodore]]
Ah, bienvenido.
メOh...? Veo que tienes un [f 4 4 3 0 1638].
ムFelicidades! ムEse es uno de mis cupones[n]hechos a mano!
Esto te darホ un [f 0 1 2]descuento del 10% en[n]todos los productos[f 0 1 0].
Que continマen con una experiencia de[n]compra satisfactoria.

[msg WSHOP_DISCOUNT2_P1 [Theodore]]
Ah, bienvenido.
Ohh... Veo que llevas un [f 4 4 3 0 1637] y[n]un [f 4 4 3 0 1638].
ムFelicidades! Cada te darホ un descuento[n]del 10%.
Esto te darホ un [f 0 1 2]descuento del 20% en[n]todos los productos[f 0 1 0].
Te agradezco por tu continuo patrocinio.

[msg WSHOP_DISCOUNT2_P2 [Theodore]]
Ah, bienvenido.
Ohh... Veo que llevas un [f 4 4 3 0 1636] y[n]un [f 4 4 3 0 1638].
ムFelicidades! Cada te darホ un descuento[n]del 10%.
Esto te darホ un [f 0 1 2]descuento del 20% en[n]todos los productos[f 0 1 0].
Te agradezco por tu continuo patrocinio.

[msg WSHOP_DISCOUNT2_P3 [Theodore]]
Ah, bienvenido.
Ohh... Veo que llevas un [f 4 4 3 0 1636] y[n]un [f 4 4 3 0 1637].
ムFelicidades! Cada te darホ un descuento[n]del 10%.
Esto te darホ un [f 0 1 2]descuento del 20% en[n]todos los productos[f 0 1 0].
Te agradezco por tu continuo patrocinio.

[msg WSHOP_DISCOUNT3_P1 [Theodore]]
Ah, bienvenido.
Dios mボo... ムParece que has reunido[n]todos los cupones!
Esto te darホ un [f 0 1 2]descuento del 30% en[n]todos los productos[f 0 1 0]!
Rezo para que continマes comprando aquボ[n]como siempre.

[msg WSHOP_NO_SHOP [Theodore]]
Not used

[msg WSHOP_CONSUMPTION_OPEN [Theodore]]
Not used

[msg WSHOP_EQUIPMENT_OPEN [Theodore]]
Not used

[msg WSHOP_ADD_PRODUCT [Theodore]]
Not used

[msg WSHOP_DISCOUNT_PQ2 [Theodore]]
Not used

[msg WSHOP_TALK_DUMMY_MARGARE [Margaret]]
Not used

[msg WSHOP_TALK_DUMMY_THEODOR [Theodore]]
Not used

[msg WSHOP_OUT_MARGARET [Margaret]]
★未使用！

[msg WSHOP_OUT_NAGI_0 [Nagi]]
Vuelve pronto.

[msg WSHOP_OUT_NAGI_1 [Nagi]]
Cuボdate.

[msg WSHOP_OUT_THEODORE_0 [Theodore]]
Gracias por tu visita.

[msg WSHOP_OUT_THEODORE_1 [Theodore]]
Ten cuidado ahボ afuera.

[msg WSHOP_OUT_THEODORE_2 [Theodore]]
Espero tu prポxima visita.

[msg WSHOP_OUT_NANAKO [Nanako]]
Not used

[msg WSHOP_THEO_SHOP_1ST_IN_M]
"Aumentar el inventario de la tienda"[n][f 0 1 2]Vendiendo materiales[f 0 1 0] obtenidos en los[n]laberintos, Theodore podrホ utilizar su mホquina[n]de palomitas para [f 0 1 2]crear nuevos productos[f 0 1 0].
"Completando pedidos de nuevos productos"[n]Algunos productos nuevos pueden requerir[n][f 0 1 2]mマltiples unidades del mismo material[f 0 1 0].[n]Cualquier material que sea necesario estarホ[n]marcado con [f 0 1 2]Necesario[f 0 1 0].

[msg WSHOP_THEO_SHOP_1ST_IN_M_2]
Presiona el [f 0 1 2]botポn Y[f 0 1 0] para ver el objeto[n]con mホs detalle.

[msg WSHOP_THEO_SHOP_1ST_IN_M_3]
"Materiales insuficientes" Puedes ver[n]informaciポn de diferentes materiales, como sus[n]ubicaciones y cポmo obtenerlos. Asegマrate de[n]aprovechar esta funciポn si deseas agregar un[n]producto especボfico a la tienda.
No solo recibirホs dinero por vender,[n]sino que tambi〒n podrホs fabricar nuevos[n]productos.

[msg WSHOP_TUTORIAL_UNKNOWN]
"Evaluar" Cuando utilizas [f 0 1 2]Evaluar[f 0 1 0] en un objeto[n]no identificado, obtendrホs [f 0 1 2]un accesorio que[n]puede ofrecer una variedad de beneficios[f 0 1 0].[n]Intenta evaluar objetos siempre que puedas.

[msg WSHOP_HELLO_NEWYEAR [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_HELLO_RAIN [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_HELLO_THUNDER [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_HELLO_SNOW [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_HELLO_SELL_RAIN [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_HELLO_SELL_THUNDER [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_00_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_00_010 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_02_001 [AいAp．Oヰヤジ]]
Not used

[sel SEL_WSHOP_QUSET_02_010 top]
Sボ
No

[msg MSG_WSHOP_QUSET_02_021 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_02_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_02_020 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_02_030 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_02_040]
Not used

[msg MSG_WSHOP_QUSET_02_050 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_10_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_10_010 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_12_001 [AいAp．Oヰヤジ]]
Not used

[sel SEL_WSHOP_QUSET_12_010 top]
Sボ
No

[msg MSG_WSHOP_QUSET_12_021 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_12_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_12_020 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_12_030 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_12_040]
Not used

[msg MSG_WSHOP_QUSET_12_050 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_20_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_20_010 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_22_001 [AいAp．Oヰヤジ]]
Not used

[sel SEL_WSHOP_QUSET_22_010 top]
Sボ
No

[msg MSG_WSHOP_QUSET_22_021 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_22_000 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_22_020 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_22_030 [AいAp．Oヰヤジ]]
Not used

[msg MSG_WSHOP_QUSET_22_040]
Not used

[msg MSG_WSHOP_QUSET_22_050 [AいAp．Oヰヤジ]]
Not used

[msg WSHOP_EXP_EFFECT_T [Theodore]]
Mientras compres artボculos con un alto[n]poder de ataque y armadura, deberボas[n]estar bien.
Sin embargo, ciertos equipos podrボan[n]tener propiedades interesantes.
Por ejemplo, algunos pueden infligir[n]estados alterados, mientras que otros[n]aumentarホn tu fuerza y magia.
Incluso hay equipo que te permitirホ[n]aumentar la cantidad de dinero obtenido[n]al enfrentarte a las Sombras.
Al evaluar la situaciポn, puedes elegir[n]equipo que te d〒 ventaja incluso antes[n]de una batalla.

[msg WSHOP_EXP_DLC_ITEM_0 [Theodore]]
Un paquete dirigido a ti llegポ mientras[n]estabas fuera.
No tengo dudas de que su contenido serホ[n]マtil en tu aventura. Por favor,[n]ac〒ptalo.

[msg WSHOP_EXP_DLC_ITEM_1 [Theodore]]
Oh, parece que no hay espacio en tu[n]mochila.
Vuelve cuando hayas liberado algo de[n]espacio.

[msg WSHOP_EXP_DLC_ITEM_2 [Theodore]]
Por favor, acepta esto.

[msg WSHOP_EXP_DLC_ITEM_3 [Theodore]]
Esta es una implementaciポn temporal. Por[n]favor, ac〒ptala.
ムRecibiste [f 2 5 3 65535 0]!

[msg WSHOP_EXP_DLC_ITEM_4 [Theodore]]
Esta es una implementaciポn temporal. Por[n]favor, ac〒ptala.
ムRecibiste [f 2 5 3 65535 0]!

[msg WSHOP_EXP_DLC_ITEM_5 [Theodore]]
Esta es una implementaciポn temporal. Por[n]favor, ac〒ptala.
ムRecibiste [f 2 5 3 65535 0]!

[msg WSHOP_EXP_HELLO_THEODORE [Theodore]]
メHay algo en lo que pueda ayudarte?

[msg WSHOP_EXP_HELLO_NAGI [Nagi]]
メTienes alguna pregunta?

[sel WSHOP_EXP_ITEM_ADD_ABOUT top]
Vender materiales
Obtener materiales especiales
Volver

[msg WSHOP_EXP_ITEM_ADD_ABOUT_2 [Theodore]]
説明y聞く選択肢用 4ミーメ7セージ

[msg WSHOP_EXP_NEW_ITEM_T [Theodore]]
Vender los materiales que encuentres en[n]los laberintos puede permitirme crear[n]nuevos productos.
Sin embargo, dependiendo del producto,[n]es posible que necesites una cantidad[n]especボfica de materiales
Estos materiales se marcarホn como[n]"Necesario" en la lista.
Si deseas saber qu〒 materiales me[n]faltan, selecciona "Materiales".
Esta informaciポn deberボa ser マtil si[n]alguna vez te encuentras sin un material[n]especボfico.

[msg WSHOP_EXP_RARE_MATERIAL_ [Theodore]]
Algunas Sombras son capaces de soltar[n]"materiales raros".
Para obtener estos materiales, debes[n]derrotar a estas Sombras bajo[n]"Condiciones especボficas".
Quizホs podrボas intentar acabar con ellas[n]atacando sus debilidades o iniciando un[n]ataque combinado.
Si me traes "materiales raros", es[n]posible que pueda usarlos para crear[n]poderoso equipo.
Te recomiendo que intentes derrotar[n]Sombras con una variedad de m〒todos y[n]veas qu〒 sucede.

