[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 0 3][f 3 1 1 0 0 26058][f 6 1 2 0 0 6]Wha―We're locked in!? Talk about[n]a clich〒 turn of events![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 10 0 1][f 3 1 1 0 0 3098][f 6 1 2 0 0 0]Oh shit, is this some kind of trap!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 1 0][f 3 1 1 0 0 13037]Quiet! I can hear something.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNITS TK-00, 03, 05, 06, 08.[n]UNITS YS-01, 06.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT IW-04. UNIT UIY-2249.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]INITIATING THE "KNOWLEDGE"[n]EVALUATION EXAM. PLEASE ANSWER[n]THE FOLLOWING QUESTIONS.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]NOTE: COOPERATION IS REQUIRED[n]IN THIS TEST. IF A TASK IS FAILED, ALL[n]WILL FACE THE CONSEQUENCES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]EACH UNIT WILL BE CONSIDERED[n]CRITICALLY ERRONEOUS AND[n]DISPOSED OF IMMEDIATELY.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 1][f 3 1 1 0 0 23058][f 6 1 2 0 0 0]"Disposed of"!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Well, this is pretty much what I'd[n]expected. We need to solve the[n]problems before we're "disposed of."[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 1 1][f 3 1 1 0 0 3054][f 6 1 2 0 0 10]Dude, I'm not ready to die yet! Oh no...[n]I really need to find the bathroom...[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Aren't you chief of operations?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Just hold it.[f 2 7 1 20 6 32][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 1 0][f 3 1 1 0 0 3041][f 6 1 2 0 0 6]Yeah, but I'm more of a "deep thinker"[n]type! Oh man, I'm so nervous, my[n]stomach's starting to churn![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 1 0][f 3 1 1 0 0 3041][f 6 1 2 0 0 10]I-I will, but... I'm so nervous, my[n]stomach's starting to churn![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 6][f 3 1 1 0 0 25037]Calm down, will you? We can't leave[n]this place until we answer the questions.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]THE EXAM WILL NOW COMMENCE.[n]CHEATING WILL RESULT IN[n]PUNISHMENT FOR ALL UNITS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]THESE QUESTIONS HAVE MULTIPLE[n]ANSWERS. PLEASE PROVIDE ONE[n]CORRECT ANSWER PER UNIT.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]YOU MAY REPLY IN ANY ORDER, BUT[n]ALL ANSWERS MUST BE PROVIDED[n]PROMPTLY.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 8 0 0 1][f 3 1 1 0 0 8022]This exam... It's the type that becomes[n]more difficult to answer, the further[n]we get through the questions.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It'd be best if those who are more[n]confident in their knowledge would[n]answer later in the order.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3031]Going first is so nerve-wracking, right[n]guys? I'll go ahead and take the lead so―[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23078][f 6 1 2 0 0 6]No! I should... boost the party's morale[n]by leading the charge! Yeah.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3084]Oh no―I'll take the plunge for you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 0 6][f 3 1 1 0 0 26005]If you're both so insecure about this,[n]then you two can go first.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 23099][f 6 1 2 0 0 10]But―It's not that I'm insecure! I just...[n]wanted to set an example for the[n]Phantom Thieves![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]By the way, how much do you know,[n]Ribbon?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 35 1 0 3][f 4 6 26 10 0 6][f 3 1 1 0 0 26016]Ohhh, she wanted nothing to do with[n]that excuse.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35002]I AM CAPABLE OF ANSWERING[n]GENERAL QUERIES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Then, I guess Ribbon-san would be best[n]to go in the middle? Leave the last to me.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 8067]I have no objections to that. I don't mind[n]being in the latter half as well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 6 1 9 0 0 1][f 3 1 1 0 0 0]WE SHALL NOW BEGIN. QUESTION 1...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]PROVIDE AN IDIOM THAT CONTAINS[n]TWO OR MORE NUMBERS IN IT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 6][f 3 1 1 0 0 23021][f 6 1 2 0 0 3]Wh-What? Two numbers?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 23045][f 6 1 2 0 0 5]Oh, I've got one! Obviously, "killing[n]two birds with one stone"![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 1][f 3 1 1 0 0 3030][f 6 1 2 0 0 7]Heheh, I thought of one right away too.[n]"One in a million"![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35002]MY ANSWER IS, "NINE-TO-FIVE JOB."[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 25 12 0 1][f 3 1 1 0 0 25089]Then, I'll go with, "as easy as one-two-[n]three." Joker, would you care to go next?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028_05 [Makoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]We need another idiom with two or[n]more numbers in it. Think hard![n][f 1 3 65535][f 1 1][e]

[sel SEL_029 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Two heads are better than one.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Two's company; three's a crowd.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Nothing beats eating meat.[f 2 7 1 20 8 32][e]

[msg MSG_030 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 1][f 3 1 1 0 0 13031]People working together can achieve[n]greater results than when alone...[n]That actually describes us quite well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 4][f 3 1 1 0 0 0]If we put all of our heads together,[n]I'm certain we can change this movie[n]in no time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 1][f 3 1 1 0 0 23033]Well, that counts, but... I would've liked[n]a more spirited idiom.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 6][f 3 1 1 0 0 26032][f 6 1 2 0 0 4]More spirited, huh? How about, "all for[n]one and one for all"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]"One in a million" sounds like a spirited[n]way to describe our own leader.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 1][f 3 1 1 0 0 3036][f 6 1 2 0 0 6]What's that, your Chie impression!? It[n]doesn't even have ONE number in it![n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Plus, it's not really an idiom. You need[n]to give an answer that fits the exam's[n]parameters.[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 2 0 3][f 3 1 1 0 0 26072][f 6 1 2 0 0 5]Welp, I'm up. I'll go with, "nine times[n]out of ten"![n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 13006]Then, mine shall be, "six of one, half[n]a dozen of the other."[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 4][f 3 1 1 0 0 8013]I'll go with "getting eighty-sixed." Please[n]take care of the last one, Akechi-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 28067][f 6 1 2 0 0 4]No problem. How about "a hundred-to-[n]one shot"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]ALL ANSWERS ARE CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 16 1 1][f 3 1 1 0 0 23109]Whew... We managed to squeak by[n]that one.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Crap, I didn't even know half of those.[n]Something about eighty sixes, and―[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]NOW, FOR THE NEXT QUESTION...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]THE RESPONDENT WILL BE SELECTED[n]AT RANDOM. EACH SPECIFIED UNIT[n]MUST ANSWER IMMEDIATELY.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 0][f 3 1 1 0 0 23060][f 6 1 2 0 0 0]We have more!? And it's random now!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]WE SHALL NOW BEGIN. QUESTION 2...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]LIST SEVEN METALLIC ELEMENTS.[n]HOWEVER, "GOLD," "SILVER," AND[n]"COPPER" WILL NOT BE ACCEPTED.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 13 2 0 1][f 3 1 1 0 0 13031]That's common knowledge. We should[n]be able to clear this one just as easily[n]as the last.[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 4][f 3 1 1 0 0 3061][f 6 1 2 0 0 4]Wait, really!? Metallic... elements?[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]I think we should leave "that" certain[n]element for Yosuke-senpai...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Good idea. It seems that we'll be[n]randomly selected, so I'll make sure[n]not to give "that" answer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26070]A-yep. Anyone could guess "that" one.[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 3054][f 6 1 2 0 0 0]Hang on―what's the "that" you're all[n]talking about!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]COMMENCING QUESTION 2.[n]UNIT TK-08...[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 28072]Looks like I'm the first one up.[n]"Beryllium."[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. NEXT, UNIT TK-05...[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 25017]I suppose this truly is random. Well[n]then―"molybdenum."[n][f 1 3 65535][f 1 1][e]

[msg MSG_056_1 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. NEXT, UNIT YS-06...[n][f 1 3 65535][f 1 1][e]

[msg MSG_056_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 4][f 3 1 1 0 0 8013]Well then, I shall go with, "tungsten."[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. NEXT, UNIT IW-04...[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 3][f 3 1 1 0 0 13069]"Palladium."[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. NEXT, UNIT TK-06...[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 26 12 0 6][f 3 1 1 0 0 26042]"Manganese." Y'know, you don't really[n]see manganese batteries anymore...[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. NEXT, UNIT UIY-2249...[n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 1][f 3 1 1 0 0 35002]"PLATINUM."[n][f 1 3 65535][f 1 1][e]

[msg MSG_062_1 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Oh crap... I can't figure it out! What's[n]"that" metallic element?[n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 6 1 9 0 0 1][f 3 1 1 0 0 0]NEXT, UNIT TK-00...[n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 1][f 3 1 1 0 0 23072][f 6 1 2 0 0 4]Your turn, Joker. Make sure you say[n]a metallic element that's not gold,[n]silver, copper, or "that" one, all right?[n][f 1 3 65535][f 1 1][e]

[sel SEL_066 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Aluminum.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Titanium.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Spare change.[f 2 7 1 20 8 32][e]

[msg MSG_067 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 1][f 3 1 1 0 0 8033]Oh no... He said "that" one.[n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT TK-03...[n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23032]Heheh, I know this all too well.[n]"Sodium."[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT. UNIT YS-01...[n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3041][f 6 1 2 0 0 3]It's no use, I can't think of anything![n]Something other than aluminum that's[n]hard... Umm, umm...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0]H-How about... Calcium? Bones are[n]hard, so maybe―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Oh, but there's no way that's metalli―[n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3042][f 6 1 2 0 0 6]Oh, what!? For real!? Man, am I glad[n]I just blurted out whatever popped in[n]my head![n][f 1 3 65535][f 1 1][e]

[msg MSG_075 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]How is he our chief of operations...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_076 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_077 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 8 1 6][f 3 1 1 0 0 28072]Heh, how fitting―a "sci-fi-sounding"[n]element. Plus, he left "that" one for[n]Hanamura-kun.[n][f 1 3 65535][f 1 1][e]

[msg MSG_078 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT YS-01...[n][f 1 3 65535][f 1 1][e]

[msg MSG_079 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 6 0 1][f 3 1 1 0 0 3020][f 6 1 2 0 0 4]"That" one... An easy one... Maybe I see it[n]all the time at the Junes food court? So,[n]food... Cookies... Plastic wrap... Foil...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 3045][f 6 1 2 0 0 0]Oh! Is it "Aluminum"!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_080 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_081 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3042][f 6 1 2 0 0 6]What? For real!? I said the right thing!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_082 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]How is he our chief of operations...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_083 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 1 0 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT TK-03...[n][f 1 3 65535][f 1 1][e]

[msg MSG_084 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052][f 6 1 2 0 0 5]Heheh, I know this all too well.[n]"Sodium."[n][f 1 3 65535][f 1 1][e]

[msg MSG_085 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_086 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 1 6][f 3 1 1 0 0 26029][f 6 1 2 0 0 4]Oh? Are you actually trolling us, Joker?[n][f 1 3 65535][f 1 1][e]

[msg MSG_087 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 25036][f 6 1 2 0 0 9]Now's not the time for jokes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Can you give a serious answer this time?[n]Coins are usually gold, silver, or copper,[n]so try to come up with a different one.[n][f 1 3 65535][f 1 1][e]

[sel SEL_088 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Aluminum.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Nickel.[f 2 7 1 20 0 32][e]

[msg MSG_089 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_090 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 1 0][f 3 1 1 0 0 25109]Whew, thank goodness. Don't scare us[n]like that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_091 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_092 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 0 0][f 3 1 1 0 0 26018]Whoa! He doubled down on the "spare[n]change" and STILL got it right! He really[n]is the ultimate Joker...[n][f 1 3 65535][f 1 1][e]

[msg MSG_093 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 1 0 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT TK-03...[n][f 1 3 65535][f 1 1][e]

[msg MSG_094 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23052]Heheh, I know this all too well.[n]"Sodium."[n][f 1 3 65535][f 1 1][e]

[msg MSG_095 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_096 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 1 0 1][f 4 6 8 2 0 4][f 3 1 1 0 0 8106][f 6 1 2 0 0 6]Okay, Yosuke-senpai―you're the last to[n]go. All you have to do is say "that" one![n][f 1 3 65535][f 1 1][e]

[msg MSG_097 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3054][f 6 1 2 0 0 10]Oh, sure. So, ah... What do you mean by[n]"that" one?[n][f 1 3 65535][f 1 1][e]

[msg MSG_098 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UNIT YS-01...[n][f 1 3 65535][f 1 1][e]

[msg MSG_099 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3020][f 6 1 2 0 0 4]"That" one... An easy one... Maybe I see it[n]all the time at the Junes food court? So,[n]food... Cookies... Plastic wrap... Foil...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 3045][f 6 1 2 0 0 0]Oh! Is it "Aluminum"!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_100 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_101 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3042][f 6 1 2 0 0 6]What? For real!? I said the right thing!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_102 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]How is he our chief of operations...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_103 [Exam system AI]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 9 0 0 1][f 3 1 1 0 0 0]NOW, FOR THE FINAL QUESTION...[n][f 1 3 65535][f 1 1][e]

[msg MSG_104 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 1][f 3 1 1 0 0 25095][f 6 1 2 0 0 4]Huh? There's STILL more?[n][f 1 3 65535][f 1 1][e]

[msg MSG_105 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]At least this is the last one―the end is[n]within sight.[n][f 1 3 65535][f 1 1][e]

[msg MSG_106 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]THERE ARE TWO GATES UP AHEAD,[n]LABELED OVERHEAD WITH AN O[n]AND AN X.[n][f 1 3 65535][f 1 1][e]

[msg MSG_107 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]UPON HEARING THE FINAL QUESTION,[n]PLEASE PASS THROUGH THE GATE[n]LABELED WITH THE CORRECT ANSWER.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]IF YOU SELECT THE WRONG GATE,[n]YOU WILL BE IMMEDIATELY DISPOSED[n]OF VIA LETHAL ELECTRICAL CURRENT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_108 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 3059][f 6 1 2 0 0 0]Wha―We'll get fried!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_109 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]We can't peek past the gates for a hint,[n]either...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 0]Look―the electric current's running[n]near the foot of the entrances.[n][f 1 3 65535][f 1 1][e]

[msg MSG_110 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 6 0 1][f 3 1 1 0 0 25040]So, we have to get a running start and[n]hurdle over one of those? That seems[n]like a strange way to answer a question.[n][f 1 3 65535][f 1 1][e]

[msg MSG_111 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 26138][f 6 1 2 0 0 6]Nope! Nope nope nope! No way![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]C'mon, this is supposed to be a test of[n]knowledge! Demanding athletic feats[n]from us now? That's cheating![n][f 1 3 65535][f 1 1][e]

[msg MSG_112 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 0]...Still, we're in the midst of the exam.[n]We don't have any choice but to answer[n]it. Let's hear the question first, at least.[n][f 1 3 65535][f 1 1][e]

[msg MSG_113 [Exam system AI]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]COMMENCING QUESTION 3...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]IS "INDIVIDUALITY" A BENEFICIAL[n]ATTRIBUTE FOR A UNIT?[n][f 1 3 65535][f 1 1][e]

[msg MSG_114 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 26063][f 6 1 2 0 0 0]Huh!? What kind of question is that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_115 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 3 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]This is clearly an "O." No question![n][f 1 3 65535][f 1 1][e]

[msg MSG_116 [Ribbon]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 35 0 1 0][f 3 1 1 0 0 35014]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_117 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 12 0 3][f 3 1 1 0 0 0]Hold on a moment―we're in the midst[n]of an inspection for mass-produced[n]robots.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Our own beliefs may not necessarily[n]be the correct answer for an exam in[n]this world.[n][f 1 3 65535][f 1 1][e]

[msg MSG_118 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 1][f 3 1 1 0 0 13023][f 6 1 2 0 0 3]If we consider the principles espoused[n]by this movie, "X" would appear to be[n]the correct one...[n][f 1 3 65535][f 1 1][e]

[msg MSG_119 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 0 0 1][f 3 1 1 0 0 23013][f 6 1 2 0 0 4]Is individuality good or bad here...[n]Which answer should we go with,[n]Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_120 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]X.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]O.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]☆.[f 2 7 1 20 4 32][e]

[msg MSG_121 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 25008]Right. I'm not pleased with the answer,[n]but this is a question intended for this[n]world's robots, not ourselves in reality.[n][f 1 3 65535][f 1 1][e]

[msg MSG_122 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I know what you mean, but it still pisses[n]me off... Screw this exam, man![n][f 1 3 65535][f 1 1][e]

[msg MSG_123 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 4][f 3 1 1 0 0 25017]I can understand how you feel, Joker,[n]but this is a question that robots are[n]supposed to answer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_124 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]That rebellious attitude is admirable,[n]but it wouldn't do us any good if it[n]got us electrocuted here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_125 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 1][f 3 1 1 0 0 3071]Of course! Let's jump through "☆" and―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 3036][f 6 1 2 0 0 6]Wait―c'mon! "O" or "X" are the only[n]options![n][f 1 3 65535][f 1 1][e]

[msg MSG_126 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]*sigh* Could you two comedians[n]cut the routine short and take this[n]seriously, please?[n][f 1 3 65535][f 1 1][e]

[msg MSG_127 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 7 6 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 13023][f 6 1 2 0 0 4]The answer that seems to fit the laws[n]of this world is "X." No one has any[n]objections to this, correct?[n][f 1 3 65535][f 1 1][e]

[msg MSG_128 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35002]THAT IS CORRECT.[n][f 1 3 65535][f 1 1][e]

[msg MSG_129 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 6][f 3 1 1 0 0 0]Poor Ribbon...[n][f 1 3 65535][f 1 1][e]

[msg MSG_130 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Now that we have our answer, all that's[n]left is to jump through the gate. Is[n]everyone ready?[n][f 1 3 65535][f 1 1][e]

[msg MSG_131 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 1][f 3 1 1 0 0 3068]No backing down now! Why don't we[n]all go through at the same time?[n][f 1 3 65535][f 1 1][e]

[msg MSG_132 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 12 0 1][f 3 1 1 0 0 0]Very well. Let's leave the timing[n]to our leader.[n][f 1 3 65535][f 1 1][e]

[msg MSG_133 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 23072]All right, everybody! Follow Joker![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23108][f 6 1 2 0 0 6]Once we get past here, the security[n]release switch should be on the other[n]side. Let's knock this exam out![n][f 1 3 65535][f 1 1][e]

[msg MSG_134]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Meanwhile, in the "Power" exam room...[n][f 1 3 65535][f 1 1][e]

[msg MSG_135 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1016][f 6 1 2 0 0 4]Now that I think about it, wouldn't this[n]be easier if we just put ourselves on[n]the scale?[n][f 1 3 65535][f 1 1][e]

[msg MSG_136 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 9029][f 6 1 2 0 0 6]Now that's our Sensei for you! I've been[n]thinking the same thing this entire time![n][f 1 3 65535][f 1 1][e]

[msg MSG_137 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 6][f 3 1 1 0 0 21040][f 6 1 2 0 0 0]Don't gimme that bullshit! You looked[n]like you were wetting your suit until like[n]three seconds ago![n][f 1 3 65535][f 1 1][e]

[msg MSG_138 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 12031]Heh... That's pretty good.[n][f 1 3 65535][f 1 1][e]

[msg MSG_139 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 18 4 0 0][f 3 1 1 0 0 18036][f 6 1 2 0 0 6]Hey, quit wastin' time chuckling at[n]frivolous shit and line up for the scale![n][f 1 3 65535][f 1 1][e]

[msg MSG_140 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 4][f 3 1 1 0 0 4055][f 6 1 2 0 0 0]Ah―Hang on! Can we, uh... not hop on[n]there one at a time? Please!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_141]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Meanwhile, in the "Adaptability" exam[n]room...[n][f 1 3 65535][f 1 1][e]

[msg MSG_142 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19107][f 6 1 2 0 0 6]I'll go first, so―everyone, just follow[n]my lead![n][f 1 3 65535][f 1 1][e]

[msg MSG_143 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 1][f 3 1 1 0 0 27067]Right! I'll do my best![n][f 1 3 65535][f 1 1][e]

[msg MSG_144 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 4][f 3 1 1 0 0 16067]Yeah, me too![n][f 1 3 65535][f 1 1][e]

[msg MSG_145 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 10 0 1][f 3 1 1 0 0 22048]Wow, [f 6 1 27 0 0 0]-chan's really[n]doing a great job.[n][f 1 3 65535][f 1 1][e]

[msg MSG_146 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 3][f 3 1 1 0 0 10068]Yeah, she's a natural leader.[n][f 1 3 65535][f 1 1][e]

[msg MSG_147 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 6][f 3 1 1 0 0 17001][f 6 1 2 0 0 6]Arf![n][f 1 3 65535][f 1 1][e]

