[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Each team pressed a release switch and[n]returned to the rendezvous point...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 8 1 1][f 3 1 1 0 0 11101][f 6 1 2 0 0 9]*groan* Oh, my back...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Man... I could not be happier to be[n]done with that. Like, seriously.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 10041]I never thought they'd make us do a test[n]like that for adaptability... I thought[n]I was gonna die back there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0]It seems that all three of the tests were[n]merciless. We were on thin ice ourselves[n]at times...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 0]But, I'm relieved that all of the teams[n]managed to complete them safely.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 28067]Now that all three switches have been[n]pressed, we can finally proceed past[n]the security measures.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 35 1 0 1][f 3 1 1 0 0 35022]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]What's the matter, Ribbon?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35002]EVERYONE HAS DIFFERENT ABILITIES,[n]BUT IT SEEMED THAT YOU ALL[n]COMPLEMENTED ONE ANOTHER.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]SOME WERE SKILLED, SOME LACKED[n]SKILL... THIS IS NOT UNIFORMITY.[n]DOES THAT NOT BOTHER YOU?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 3051]Well, it's just a part of our individuality.[n]That Overseer seems to deny it, though.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35014]INDIVIDUALITY...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 12 6 1 3][f 3 1 1 0 0 12031]Plus, we each had a leader who brought[n]such a scattered bunch together into[n]a working team.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 6][f 3 1 1 0 0 0]Indeed. We must thank our three[n]leaders for that mission.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19030][f 6 1 2 0 0 6]Eheheh, it just makes me happy that[n]I was able to be useful. Still, this was[n]the result of everyone working together![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Right―it's thanks to our companions[n]doing their best.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 1 0][f 3 1 1 0 0 13031]Ha... You have a point. This is the fruit[n]of everyone's hard work.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 24 4 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I'm still curious, though―how did they[n]create such elaborate facilities for[n]these tests?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 0]Oh, about that. They seem to have been[n]holographic simulations.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Basically, it was like virtual reality.[n]All the rooms were actually empty.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]So, that tester device thing didn't even[n]exist?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 3 0][f 3 1 1 0 0 0]Yep. As you'll see, if I press here...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Mweheheh! Now we can get through[n]without being hassled by any more[n]exams![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 1][f 3 1 1 0 0 0]For real!? That's awesome... But kind of[n]a bummer, too...[n][f 1 3 65535][f 1 1][e]

[sel SEL_021 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]I'm right there with you.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]So, what was the point of all that?[f 2 7 1 20 4 32][e]
[f 0 5 65278][f 2 1]Should we take the exam again?[f 2 7 1 20 0 32][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Know what I mean? We went through[n]all that―and it was all just a bunch of[n]bullshit![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Well, it's hard to accept when all that[n]effort was for nothing but a simulation.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Still, we were able to unlock the door[n]to the lab thanks to those efforts, so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]That's not what I mean! We busted our[n]asses in there, but it was basically[n]just some kinda game, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]It's like, we got tired over nothin'...[n]Or maybe it's more like, that was all[n]just one big lie!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Still, I'm never doin' one of those again[n]if I can avoid it...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 14 2 100 1][f 3 1 1 0 0 14614][f 6 1 2 0 0 6][f 3 1 6 0 0 500]Everyone, we've confirmed that the[n]research facility's security has been[n]lifted―the entrance is open![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 4][f 3 1 1 0 0 0]Not only that, it seems like you can[n]come and go through that door[n]freely now.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Then again, it looks like you still have[n]a long way to go, so be careful as you[n]proceed![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23108][f 6 1 2 0 0 6]I see―roger that. Well everyone, let's go![n][f 1 3 65535][f 1 1][e]

