[msg MSG_000 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 501][f 6 1 3 0 0 2]Mi presencia es necesaria para aquellos que desean escapar de su realidad. Desafiarme es una tonter胤a...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 502][f 6 1 3 0 0 2]Son solo ni隠os lamentables e insignificantes para m胤. R胤ndanse ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 99 1][f 3 1 3 0 0 503][f 6 1 2 0 0 6]斡Aguanten! 斡Tenemos que seguir reproduciendo la pel胤cula![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 0][f 3 1 3 0 0 504]Necesitamos cambiar su forma de pensar. 斡Por favor![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 4][f 3 1 3 0 0 505][f 6 1 2 0 0 1]斡Vamos, tienes que aguantar! 斡Nosotras haremos nuestro mejor esfuerzo![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 506][f 6 1 3 0 0 2]Han venido innumerables humanos, ansiosos de encontrar seguridad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 507][f 6 1 3 0 0 2]Su resistencia a mi salvaci吋n no es m茨s que una perdida de tiempo.[n][f 1 3 65535][f 1 1][e]

