[msg MSG_000 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 900][f 6 1 3 0 0 2]斡Ustedes, criminales insignificantes, est茨n perturbando el orden del mundo![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 901][f 6 1 2 0 0 6][f 6 1 3 0 0 2]斡Es hora de que perezcan! 斡M胤renme, soy la justicia![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 4 1 7][f 3 1 3 0 0 902]La justicia ciega no es m茨s que basura egoc姻ntrica.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 4 0 8][f 3 1 3 0 0 903][f 6 1 2 0 0 6]斡Eres un falso h姻roe que no representa nada... debes entrar en raz吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 904][f 6 1 3 0 0 2]斡USTEDES son las que deben entrar en raz吋n! 斡JA, JA, JA![n][f 1 3 65535][f 1 1][e]

