[msg MSG_000 [Chica Bien Vestida]]
Iori, se dirige hacia ti. ムMantente en[n]guardia!

[msg MSG_001 [Chico Con Gorra De B〒isbol]]
Je, je, je, ムno hay forma de que algo[n]como esto me derribe!

[msg MSG_002 [Chico Con Gorro]]
Oye, no es momento de bromear. ムEstos[n]bastardos no nos dejan en paz!

[msg MSG_003 [Chica Animada]]
ムメNo pueden rendirse de una vez?![n]メCuホndo acabarホ esto?

[msg MSG_004 [Chica Tranquila]]
...ムEs inマtil! ムVienen refuerzos!

[msg MSG_005 [Robot Producido En Masa]]
ELIMINAR ENTIDADES DESCONOCIDAS.[n]ムELIMINAR IRREGULARIDADES!

[msg MSG_006 [Chico Agresivo]]
Tch... ムNo vamos a ir a ninguna parte[n]asボ!

[msg MSG_007 [Robot Producido En Masa]]
ELIMINAR ENTIDADES DESCONOCIDAS.[n]ムELIMINAR IRREGULARIDADES!

[msg MSG_008 [Niワo Sombrボo]]
*jadeo* *jadeo* ムNo vamos a perder aquボ!

[msg MSG_009 [Chica Tranquila]]
Ken estホ en peligro, ムsu salud es baja!

[msg MSG_010 [Chico Agresivo]]
ムNgh..! Esto no se ve bien. Nos superan[n]en nマmero...

[msg MSG_011 [Perro]]
ムArf, Arf!

[msg MSG_012 [P3 Fem Protag]]
ムChicos!

[msg MSG_013 [Chica Bien Vestida]]
ムメQui〒n estホ ahボ?!

[msg MSG_014 [P4 Hero]]
Guardemos la reuniポn para despu〒s,[n]ムellos necesitan nuestra ayuda!

