[msg MSG_000 [Ribbon]]
...
メYO... YO..?

[msg MSG_001 [Aigis]]
メTe recuperaste?

[msg MSG_002 [P3 Hero]]
Ribbon... Gracias a dios despertaste.

[msg MSG_003 [Ribbon]]
YO... YO...

[msg MSG_004 [Yukari]]
メCポmo estホs? メRecuerdas qui〒n eres?

[msg MSG_005 [Ribbon]]
YO SOY... UIY-2249...

[msg MSG_006 [Haru]]
Ah...

[msg MSG_007 [Ribbon]]
...No, soy Ribbon... Ribbon es mi[n]nombre.

[msg MSG_008 [Futaba]]
ムRibbon!

[msg MSG_009 [Yosuke]]
ムBien! ムLo hicimos!

[msg MSG_010 [Ribbon]]
メQu〒 me paso...?

[msg MSG_011 [Aigis]]
Perdiste una gran cantidad de energボa debido a[n]la activaciポn de tu Modo Desenfreno, y habボa[n]un error en tu secuencia de arranque.
Por eso te conectamos temporalmente a mi[n]sistema e intentamos restaurarlo.

[msg MSG_012 [Mitsuru]]
Fue una apuesta arriesgada, pero parece[n]haber sido un 〒xito.
Pero, pensar que tambi〒n tenボas un Modo[n]Desenfreno... メQu〒 fue lo que hiciste,[n]Oracle?

[msg MSG_013 [Futaba]]
ムMweheheh! Todo lo que hice fue ayudar a[n]desactivar sus limitaciones.
Simplemente, reescribボ su programaciポn[n]para que Ribbon pudiera activarlo a[n]voluntad.

[msg MSG_014 [Ribbon]]
Sボ, elegボ luchar contigo.

[msg MSG_015 [Akihiko]]
Fue una actitud admirable. Parece que[n]has cambiado un poco, Ribbon.

[msg MSG_016 [Yusuke]]
Y es gracias a ti que la Madre[n]Computadora ya no estホ. Ahora eres[n]libre.

[sel SEL_017 top]
Buen trabajo.
メY ahora qu〒?

[msg MSG_018 [Naoto]]
Sin embargo, este no es el verdadero[n]final.
メQu〒 serホ de este mundo y Ribbon ahora?

[msg MSG_019 [Naoto]]
Es una buena pregunta. メQu〒 planeas[n]hacer ahora, Ribbon?

[msg MSG_020 [Ribbon]]
Creo que, eventualmente, mホs de mis[n]compaワeros conseguirホn su[n]individualidad.
Debo prepararme para cuando ese momento[n]llegue, quiero crear un mundo donde podamos[n]vivir juntos, en un lugar sin miedo a ser[n]eliminados.

[msg MSG_021 [Morgana]]
ムEso es increボble! ムTe animaremos![n]メVerdad, Joker?

[sel SEL_022 top]
Dejamos este mundo para ti.
Confiポ en ti, Ribbon.

[msg MSG_023 [Ribbon]]
Gracias. Prometo hacer que ese sueワo se[n]convierta en realidad.

[msg MSG_024 [Aigis]]
Es un objetivo admirable.

[msg MSG_025 [Ribbon]]
Aigis, gracias a ti...
Ambas somos robots, pero eras tan libre[n]que al principio estaba muy confundida.

[msg MSG_026 [P3 Hero]]
メHas oボdo eso, Aigis?

[msg MSG_027 [Aigis]]
No soy especial. Sin embargo, hablando[n]hipot〒ticamente, si hubiera algo[n]especial sobre mボ...
メEntonces tus compaワeros me[n]aceptarボan... por qui〒n soy realmente?

[msg MSG_028 [Ribbon]]
メSi ellos... te aceptarボan?

[msg MSG_029 [Futaba]]
No somos los マnicos que piensan asボ.[n]Estoy segura de que habrホ otros que te[n]acepten tal como eres.
Por eso tambi〒n deberボas hacer nuevos[n]compaワeros. Si haces eso, seguro que todos los[n]dボas estarホn llenos de diversiポn.

[msg MSG_030 [Aigis]]
Ribbon-san, por favor, af〒rrate a eso[n]que te hace "especial".

[msg MSG_031 [Ribbon]]
Sボ... ムHar〒 lo mejor que pueda!

[msg MSG_032 [Aigis]]
ムMe alegra escucharlo!

[msg MSG_033 [Futaba]]
ムConvi〒rtete en la mejor robot, Ribbon![n]Prom〒teme que harホs eso, メde acuerdo?

[msg MSG_034 [Ribbon]]
Te lo prometo, Oracle.

[msg MSG_034_5 [Ribbon]]
Gracias a todos los demホs. Por favor,[n]cuボdense...

[msg MSG_035 [Ken]]
Ahボ va ella...

[msg MSG_036 [P3 Fem Protag]]
Supongo que hemos cerrado este caso,[n]メeh? Hemos convertido el final en uno[n]feliz...

[msg MSG_037 [Yosuke]]
Esto sボ que es raro. メTマ tambi〒n te[n]estホs poniendo nostホlgica, [f 6 1 27 0 0 0]?

[msg MSG_038 [P3 Fem Protag]]
Mmhm... Siento que estoy abrumada por[n]mis emociones.
Ribbon estuvo sola todo este tiempo...[n]Supongo que me sigo comparando con ella.

[sel SEL_039 top]
メEstホs bien?
メTe sientes sola?
Estamos todos juntos en esto.

[msg MSG_040 [P3 Fem Protag]]
ムGracias, estoy bien! Ademホs, este no[n]fue un final triste.
Ribbon serホ capaz de sentir que ahora[n]pertenece a un lugar...

[msg MSG_040_3 [P3 Fem Protag]]
...Y eso me hace sentirme feliz por[n]ella.

[msg MSG_040_5 [Mitsuru]]
Mm... Suenas casi como si te estuvieras[n]describiendo.

[msg MSG_041 [Teddie]]
Si necesitas llorar, te presto mi pecho.[n]ムVamos, desahポgate con Teddie!

[msg MSG_042 [P3 Fem Protag]]
ムGracias, pero estoy bien! Ademホs, este[n]no fue un final triste.
Ribbon serホ capaz de sentir que ahora[n]pertenece a un lugar...

[msg MSG_042_5 [P3 Fem Protag]]
...Y eso me hace sentir tan feliz por[n]ella.

[msg MSG_043 [Mitsuru]]
Mm... Suenas casi como si te estuvieras[n]describiendo.

[msg MSG_045 [Mitsuru]]
Sボ, asボ es.

[msg MSG_046 [Mitsuru]]
Es natural que no pudieras evitar[n]simpatizar con Ribbon, ella tambi〒n se[n]sentボa sola en su mundo...
Pero ahora, ninguno de nosotros estホ[n]solo, メno?

[msg MSG_047 [P3 Fem Protag]]
メHuh?

[msg MSG_048 [Mitsuru]]
Como alguien que lucha junto a ti, has[n]demostrado tu lealtad y fiabilidad lo[n]suficiente como para ganar nuestra confianza.
Si quieres que lo ponga mホs claro, creo[n]que puedo hablar por todos cuando digo[n]que eres nuestra compaワera.

[msg MSG_049 [P3 Fem Protag]]
ムMitsuru...!

[msg MSG_052 [Junpei]]
Asボ es. Puedes confiar en mボ mホs que en[n]el yo que tマ conoces, メsabes?
ムSoy el verdadero h〒roe destinado a[n]salvar el mundo! ムD〒jamelo a mボ, EL[n]Junpei Iori! ...Bueno, Un Junpei.

[msg MSG_053 [Yukari]]
Uf, se me revuelve el estポmago solo de[n]pensar en mマltiples Junpeis....
Solo uno ya es demasiado para nosotros.

[msg MSG_054 [Junpei]]
ムOye! ムSi hubiera uno menos de mボ, no[n]existirボa en absoluto!

[msg MSG_055 [P3 Fem Protag]]
ムJa, ja, ja!

[msg MSG_056 [Fuuka]]
*risa* Bueno, entonces, espero que[n]podamos ser aマn mホs unidos de ahora en[n]adelante.
ムHar〒 lo que pueda con los refuerzos,[n]ムasボ que vamos a escapar de este mundo!

