[msg MSG_000 [Yosuke]]
...メEh? メUn callejポn sin salida?

[msg MSG_001 [Haru]]
Eso parece. メDeberボamos regresar?

[msg MSG_002 [Koromaru]]
ムBark! ムBark bark!

[msg MSG_003 [Ken]]
メQu〒 pasa, Koromaru?

[msg MSG_004 [Shinjiro]]
Un conducto de ventilaciポn...
Bien, parece conectar con el otro lado.[n]Me impresiona que lo vieras.

[msg MSG_005 [Aigis]]
Koromaru dice: "Podemos pasar por aquボ".

[msg MSG_006 [Akechi]]
Ya veo. No hay otra opciポn.

[msg MSG_007 [Yukari]]
ムメQu〒?! No querrホs decir que...

[msg MSG_008 [Ryuji]]
Bien, Hora de entrar en ese conducto,[n]メverdad, Joker?

[sel SEL_009 top]
Por supuesto.
Lo de siempre para nosotros.

[msg MSG_010 [Yukari]]
Hrgh, lo sabボa. Bueno, no sirve de nada[n]quejarse...

[msg MSG_011 [P4 Hero]]
Hemos seguido a los Ladrones fantasma[n]sin preguntar, hasta ahora...
Aunque, pensホndolo bien, arrastrarse a[n]trav〒s de un conducto de ventilaciポn no[n]es algo que experimentarボa normalmente.

[msg MSG_012 [Ann]]
Ja, ja, lo siento... Supongo que te[n]acostumbraras entre mホs est〒s con[n]nosotros.

[msg MSG_013 [Junpei]]
No me molesta. ムEsta es una experiencia[n]invaluable para nosotros!

[msg MSG_014 [Akihiko]]
Mm, estホs muy interesado en esto. メPor[n]qu〒 tanto entusiasmo?

[msg MSG_015 [Yukari]]
Apuesto a que es por alguna fantasボa[n]estマpida como "sentirse como un espボa".

[msg MSG_016 [Junpei]]
ムOye! No es estマpida...
ムSolo quiero parecer cool y elegante[n]mientras estoy con los Ladrones Fantasma[n]y el Equipo de Investigaciポn!

[sel SEL_017 top]
メCool?
メElegante?
メA cuホl quieres unirte?

[msg MSG_018 [P3 Hero]]
Mm, parece Joker no te ve de esa[n]forma...

[msg MSG_019 [Junpei]]
ムメQu〒〒〒〒?!

[msg MSG_020 [Morgana]]
Tsk Tsk. Si quieres ser cool y elegante,[n]ムtienes que ser mホs como yo!

[msg MSG_021 [Ryuji]]
Uh, tampoco te vemos de esa forma.

[msg MSG_022 [Naoto]]
En cualquier caso, si no hay otra ruta,[n]tendremos que usarlo.

[msg MSG_023 [P4 Hero]]
Muy bien, hagホmoslo.

[msg MSG_024 [Yukari]]
Espera, メrealmente vamos a hacerlo?[n]ムメTiene que ser aquボ?!

[msg MSG_025 [Akihiko]]
メQu〒 pasa Yukari? メTienes miedo?

[msg MSG_026 [Yukari]]
Uh, Bueno... Mi falda es corta, asボ[n]que... Ya sabes...

[msg MSG_027 [Akihiko]]
Entiendo. Dado que es corta, te preocupa[n]tu debilidad defensiva.
En ese caso, solo d〒jamela a mボ, te[n]proteger〒 por detrホs.

[msg MSG_028 [Yukari]]
ムNo es lo que querボa decir! ムY no hay[n]forma de que te deje ir detrホs!
ムSi una chica no va detrホs, voy al[n]マltimo!

[msg MSG_029 [P3 Hero]]
De acuerdo, vamos a decidir en qu〒 orden[n]vamos a entrar.

[msg MSG_030 [Ken]]
Mm... Joker, tienes experiencia viajando[n]por conductos, メno?
Es primera vez, asボ que... メTienes algマn[n]consejo?

[sel SEL_031 top]
No tengas miedo.
Cierra los ojos.
Aprende de la experiencia.

[msg MSG_032 [Yusuke]]
Es verdad. El miedo es tu peor enemigo.

[msg MSG_033 [Ken]]
Y-ya veo... ムEs マtil saberlo! ムGracias!

[msg MSG_034 [Yusuke]]
Exacto. Si te pierdes en la oscuridad,[n]simplemente intuye tu camino con tu[n]sexto sentido.

[msg MSG_035 [Ann]]
Espera. メCierras los ojos en los[n]conductos de ventilaciポn Fox?

[msg MSG_036 [Yusuke]]
Ha... A veces, sボ.

[msg MSG_037 [Ken]]
ムEs マtil saberlo!

[msg MSG_038 [Makoto]]
No, Amada... Definitivamente, deberボas[n]mantener tus ojos abiertos.

[msg MSG_039 [Ken]]
Ah... eso serホ complicado...
ムPero asボ es como lo hacen los Ladrones[n]Fantasma! ムVoy a fingir que soy un[n]ladrポn fantasma y probar mi destreza!

[msg MSG_040 [P4 Hero]]
Tengo una pregunta... Teddie, メvas a[n]pasar con ese cuerpo?

[msg MSG_041 [Haru]]
Oh, ahora que lo mencionas... メCポmo ha[n]llegado hasta aquボ?

[msg MSG_042 [Teddie]]
Je, je, je... ムNo subestimes mis[n]habilidades acrobaticas!

[msg MSG_043 [Yosuke]]
メSupongo que... solo lo meteremos ahボ?

[msg MSG_044 [Morgana]]
ムGenial! ムVamos, sボganos el paso!

