[msg MSG_000]
En de A.I.G.I.S., Zona 1...

[msg MSG_001 [Chie]]
Ahora que estamos aqu胤, vaya... 斡Esto se[n]ve tan diferente de Yasoinaba!

[msg MSG_002 [Makoto]]
Es como si todo estuviera hecho con CGI.[n]Todo es tan plano y uniforme.

[msg MSG_003 [Ann]]
斡Gah! 斡夷Qu姻 est茨 pasando...?!

[msg MSG_004 [Interfaz De Seguridad]]
VERIFICACI遺N DE IDENTIDAD EN PROGRESO...[n]斡ERROR DE VERIFICACI遺N!
NO SE ENCONTRARON REGISTROS. REGISTRANDO[n]NUEVOS MODELOS...

[msg MSG_005 [Yukiko]]
夷Verificaci吋n? 夷Nuevos modelos?

[msg MSG_006 [Interfaz De Seguridad]]
REGISTRANDO ID INDIVIDUALES: TK-00 A[n]TRAV畏S DE 08― YS-00 A TRAV畏S DE 07―[n]IW-00...

[msg MSG_007 [Naoto]]
Usar n雨meros de serie en lugar de un[n]nombre es bastante com雨n en historias de[n]ciencia ficci吋n dist吋pica.

[msg MSG_008 [Yosuke]]
斡Vaya, este lugar realmente es como una[n]pel胤cula de ciencia ficci吋n! Quiero decir, eso[n]es exactamente lo que es, 斡pero aun as胤!

[msg MSG_009 [Futaba]]
斡Es como un para胤so tecnol吋gico!

[msg MSG_010 [Yukiko]]
斡Los entornos de ciencia ficci吋n son[n]divertidos por su estilo tan distintivo! Creo[n]que entiendo por qu姻 a la gente le encanta.

[sel SEL_011 top]
夷Eres cin姻fila?
S胤, son geniales.

[msg MSG_012 [Yukiko]]
Mmm... no solo de pel胤culas de ciencia[n]ficci吋n. Veo todo tipo de g姻neros.

[msg MSG_013 [Makoto]]
Eso me sorprende. Pens姻 que a Yukiko le[n]gustar胤a algo m茨s tradicional...

[msg MSG_014 [Yosuke]]
Bueno, Yukiko es un... paquete de[n]sorpresas. S胤.

[msg MSG_015 [Yukiko]]
夷Eh? 夷Qu姻 significa eso?

[msg MSG_016 [P4 Hero]]
Significa que no deber胤amos juzgar por[n]las apariencias...

[msg MSG_017 [Yusuke]]
La arquitectura geom姻trica es una uni吋n[n]de belleza y funcionalidad... 斡Hace que[n]mi coraz吋n baile de alegr胤a!

[msg MSG_018 [Kanji]]
Es divertido pensar en estas cosas,[n]como, 夷qu姻 come la gente del futuro?

[msg MSG_019 [Chie]]
斡S胤, s胤! 斡Tengo curiosidad! 夷Crees que[n]podr胤amos conseguir carne sint姻tica?

[msg MSG_020 [Makoto]]
El tr茨iler dijo que es una sociedad[n]post-humanidad, as胤 que no creo que haya[n]comida aqu胤.
La tecnolog胤a de este mundo es[n]impresionante, pero todo es tan[n]artificial... Es bastante extra隠o.

[msg MSG_021 [Haru]]
Un mundo de ciencia ficci吋n, eh...

[msg MSG_022 [Morgana]]
夷Est茨s bien, Noir?

[msg MSG_023 [Haru]]
S胤, este lugar me record吋 el Palacio de[n]mi padre...
Pero ahora me estoy acostumbrando.[n]Gracias por preguntar.

[msg MSG_024 [Teddie]]
斡Es hora de cambiar esta pel胤cula! 夷Por[n]d吋nde debemos empezamos?

[msg MSG_025 [P3 Fem Protag]]
Supongo que deber胤amos empezar buscando[n]a ese robot de la cinta roja...

[msg MSG_026 [Ann]]
Bueno, no podemos andar buscando con[n]estos enemigos por todas partes... 夷Qu姻[n]vamos a hacer?

[msg MSG_027 [Teddie]]
夷Est茨s nerviosa, Ann? Tengo una mano[n]libre, si quieres sostenerla.

[msg MSG_028 [Morgana]]
斡Al姻jate, oso! 斡No vas a poner tu mano[n]en Panther bajo MI supervisi吋n!

[msg MSG_029 [Teddie]]
Ohhhh, est茨 bien. Podemos cada uno[n]sostener una de sus manos para que sea[n]justo.

[msg MSG_030 [Morgana]]
夷Eh? Bueno... Supongo que est茨 bien.

[msg MSG_031 [Ann]]
斡No! Eh... Nuestras alturas son muy[n]diferentes. Me doler胤a la espalda.

[msg MSG_032 [Morgana]]
Noooo...

[msg MSG_033 [P4 Hero]]
Um... volvamos a la pel胤cula, 夷no?
夷Hay alguna objeci吋n para buscar primero[n]a ese robot del list吋n?

[msg MSG_034 [Naoto]]
Ninguna. Ese robot probablemente tiene[n]la clave de esta pel胤cula.

[sel SEL_035 top]
Aqu胤 tampoco hay objeciones.
Quiero carne sint姻tica primero.

[msg MSG_036 [P3 Fem Protag]]
斡Entonces est茨 decidido! 斡Intentemos[n]encontrarlo lo m茨s r茨pido posible!

[msg MSG_037 [Akechi]]
斡Ja, ja, ja! Eso me recuerda, 夷sabes cu茨l es[n]el ingrediente est茨ndar para la carne[n]fabricada en pel胤culas de ciencia ficci吋n?

[msg MSG_038 [Chie]]
Eh, 夷cu茨l es? 斡Ahora estoy a雨n m茨s[n]curiosidad!

[msg MSG_039 [Naoto]]
Por qu姻, eh... 夷Por qu姻 no hablamos de[n]eso m茨s tarde? Concentr姻monos en la[n]b雨squeda por ahora.

[msg MSG_040 [Morgana]]
斡Vamos, mov茨monos! 斡Mantengan la guardia[n]alta!

