[msg MSG_000 [Aigis]]
...

[msg MSG_001 [P3 Fem Protag]]
...夷Aigis? 夷Qu姻 pasa? 夷Tengo algo en la[n]cara?

[msg MSG_002 [Junpei]]
夷Qu姻 pasa, Ai?
斡Est茨s mirando tanto a [f 6 1 27 0 0 0] que estoy[n]empezando a sentirme un poco celoso!

[msg MSG_003 [Aigis]]
Todos los dijeron antes, pero yo tambi姻n[n]tengo curiosidad sobre el tema.
Conoc胤 a [f 6 1 27 0 0 0] hace poco...
Sin embargo, siento algo que me atrae[n]hacia ella.

[msg MSG_004 [Yukiko]]
夷Podr胤a ser la misma sensaci吋n de la que[n]est茨bamos hablando?
O no me digas... 夷Puedes ver algo que[n]solo es visible con tus ojos rob吋ticos?

[msg MSG_005 [Chie]]
斡B-basta! 夷Quieres decir que puede...[n]ver esp胤ritus?

[msg MSG_006 [Aigis]]
No tengo capacidades para detectar[n]fen吋menos sobrenaturales. 夷Te refieres a[n]otra funci吋n?

[msg MSG_007 [Futaba]]
斡Oh, yo tambi姻n tengo curiosidad! 夷Qu姻[n]otras funciones especiales tienes[n]cargadas?

[sel SEL_008 top]
Ella puede hacer Electrocardiogramas.
Ella tiene visi吋n de rayos X.
Ella puede ver el aura de la gente.

[msg MSG_009 [Yukiko]]
斡S胤, eso! 斡Apuesto a que puede disparar[n]rayos X por sus ojos y analizar nuestros[n]吋rganos con electricidad!

[msg MSG_010 [Naoto]]
M-mm... 夷Puedes hacer eso?

[msg MSG_011 [Aigis]]
Desafortunadamente, no.

[msg MSG_012 [Naoto]]
Eso pensaba...

[msg MSG_013 [Chie]]
斡夷Puedes ver QU畏?! 斡夷Mi aura?!

[msg MSG_014 [Yosuke]]
Apuesto a que la de Chie est茨 en t姻rmino[n]medio...

[msg MSG_015 [Chie]]
Prefiero que mi carne est姻 poco hecha,[n]as胤 que me gustar胤a que mi fuera m茨s[n]roja que rosa, gracias.

[msg MSG_016 [Yosuke]]
斡Estaba siendo sarc茨stico! Quiero decir,[n]dudo mucho que tenga funciones[n]ps胤quicas.

[msg MSG_017 [Aigis]]
No estoy segura de si se podr胤a llamar[n]adecuadamente una funci吋n, pero...

[msg MSG_018 [Yosuke]]
Espera, 斡夷puedes?!

[msg MSG_019 [Mitsuru]]
Debe significar que es capaz de percibir[n]asuntos que son m茨s espirituales, en[n]lugar de solo verlos como una m茨quina.

[msg MSG_020 [Yukari]]
S胤, 夷es algo como... un coraz吋n?

[msg MSG_021 [Aigis]]
S胤... siento que es una analog胤a[n]apropiada.

[msg MSG_025 [P3 Fem Protag]]
...

[msg MSG_026 [Aigis]]
...[f 6 1 27 0 0 0] tambi姻n es muy importante para[n]m胤.

[msg MSG_027 [P3 Fem Protag]]
斡夷Eh?!

[msg MSG_028 [Aigis]]
Al igual que a [f 6 1 16 0 0], proteger姻 a[n]tambi姻n.

[msg MSG_029 [P3 Fem Protag]]
...Gracias. Escuchar eso de ti me hace[n]sentir segura.

[msg MSG_033 [Junpei]]
Bueno, ahora que todos estamos en[n]sinton胤a de nuevo, 斡continuemos d茨ndolo[n]todo!

[msg MSG_034 [Koromaru]]
斡Guau!

