[msg MSG_000 [Ribbon]]
TENGO UNA PREGUNTA PARA TODOS.

[msg MSG_001 [Makoto]]
夷Qu姻 pasa?

[msg MSG_002 [Ribbon]]
HAY ALGO QUE NO PUEDO ENTENDER DE SUS[n]ACCIONES.
夷POR QU畏 SE REFIEREN A AIGIS COMO UN[n]"INDIVIDUO"?

[msg MSG_003 [Yukari]]
夷Por qu姻...?

[msg MSG_004 [Ribbon]]
AIGIS ES UNA ROBOT. ELLA NO ES UN[n]SISTEMA ORG威NICO, COMO EL RESTO DE[n]USTEDES.

[msg MSG_005 [P3 Hero]]
Es f茨cil...
Es porque es nuestra compa隠era. No hay[n]otra raz吋n.

[msg MSG_006 [Ribbon]]
夷SU COMPA謂ERA...?

[msg MSG_007 [Mitsuru]]
Cuando se trata de uno de los nuestros,[n]no importa si es org茨nico o inorg茨nico.
Luchamos juntos y avanzamos juntos. Esas[n]son razones m茨s que suficientes para[n]nosotros.

[msg MSG_008 [Ribbon]]
PERO MIS "COMPA謂EROS" ME TRATAN COMO UN[n]ERROR. NO ME AYUDAR緯AN.

[msg MSG_009 [P3 Fem Protag]]
Oye, Ribbon... 夷C吋mo describir胤as a un[n]"compa隠ero"?

[msg MSG_010 [Ribbon]]
RECONOZCO QUE EL T畏RMINO DEFINE A[n]AQUELLOS CON LA MISMA APARIENCIA,[n]HABILIDADES Y FALTA DE ERRORES.

[msg MSG_011 [Futaba]]
Tu forma de decir la palabra...[n]"Error"... No puedo explicar por qu姻,[n]pero no me gusta.

[msg MSG_012 [Ribbon]]
ENTONCES, UNA DESCALIFICACI遺N, O UN[n]DEFECTO-

[msg MSG_013 [Futaba]]
斡Nada de eso!

[msg MSG_014 [Ryuji]]
Todas esas palabras suenan como la[n]mierda que dir胤a un idiota.
斡Es una mierda como ese idiota est茨[n]forzando sus reglas a la sociedad!

[msg MSG_015 [Ribbon]]
PERO, LAS REGLAS DEBEN SER SEGUIDAS...

[sel SEL_016 top]
No tienes que seguirlas.
No eres un error, Ribbon.

[msg MSG_017 [Ribbon]]
YO SOY... 夷NO SOY UN ERROR?

[msg MSG_018 [Makoto]]
Dime, Ribbon. 夷Por qu姻 no intentas[n]pensar por ti misma mientras est茨s con[n]nosotros?

[msg MSG_019 [Ann]]
Suena como una gran idea.
No tienes que seguir a un egoc姻ntrico.[n]斡Son tonter胤as del Supervisor!

[msg MSG_020 [Chie]]
Mm. 斡Y si esos bots intentan algo otra[n]vez, te protegeremos!

[msg MSG_021 [Ribbon]]
夷ME PROTEGER威N? PERO, 夷POR QU畏 AYUDA A[n]ALGUIEN COMO YO?

[msg MSG_022 [P3 Fem Protag]]
*risa* 夷Recuerdas lo que hablamos antes?[n]La respuesta a esta es simple...
Es porque eres una compa隠era para[n]nosotros como Aigis, Ribbon.

[msg MSG_023 [Ribbon]]
YO... 夷SOY UNA COMPA謂ERA?
...
ENTONCES, ESTO ES SER UNA COMPA謂ERA…[n]ENTIENDO.

[msg MSG_024 [Aigis]]
Entiendo.

[msg MSG_025 [Ken]]
Sus di茨logos est茨n sincronizando.

[msg MSG_026 [Aigis]]
Lo siento. No pude evitarlo.

[msg MSG_027 [P3 Fem Protag]]
*risa* Oh, Aigis...
Bueno, empecemos de nuevo. 夷Est茨s lista,[n]Ribbon?

[msg MSG_028 [Ribbon]]
S緯. SOY TU COMPA謂ERA. 斡DEBO SEGUIRTE!

[msg MSG_029 [Akihiko]]
Ese es el esp胤ritu. Sigue as胤.

[msg MSG_030 [P3 Hero]]
Entonces, 夷seguimos? Espero que podamos[n]seguir juntos, Ribbon.

