[msg MSG_000 [Ribbon]]
TENGO UNA PREGUNTA PARA TODOS.

[msg MSG_001 [Makoto]]
メQu〒 pasa?

[msg MSG_002 [Ribbon]]
HAY ALGO QUE NO PUEDO ENTENDER DE SUS[n]ACCIONES.
メPOR QU※ SE REFIEREN A AIGIS COMO UN[n]"INDIVIDUO"?

[msg MSG_003 [Yukari]]
メPor qu〒...?

[msg MSG_004 [Ribbon]]
AIGIS ES UNA ROBOT. ELLA NO ES UN[n]SISTEMA ORGミNICO, COMO EL RESTO DE[n]USTEDES.

[msg MSG_005 [P3 Hero]]
Es fホcil...
Es porque es nuestra compaワera. No hay[n]otra razポn.

[msg MSG_006 [Ribbon]]
メSU COMPAヰERA...?

[msg MSG_007 [Mitsuru]]
Cuando se trata de uno de los nuestros,[n]no importa si es orgホnico o inorgホnico.
Luchamos juntos y avanzamos juntos. Esas[n]son razones mホs que suficientes para[n]nosotros.

[msg MSG_008 [Ribbon]]
PERO MIS "COMPAヰEROS" ME TRATAN COMO UN[n]ERROR. NO ME AYUDARレAN.

[msg MSG_009 [P3 Fem Protag]]
Oye, Ribbon... メCポmo describirボas a un[n]"compaワero"?

[msg MSG_010 [Ribbon]]
RECONOZCO QUE EL T※RMINO DEFINE A[n]AQUELLOS CON LA MISMA APARIENCIA,[n]HABILIDADES Y FALTA DE ERRORES.

[msg MSG_011 [Futaba]]
Tu forma de decir la palabra...[n]"Error"... No puedo explicar por qu〒,[n]pero no me gusta.

[msg MSG_012 [Ribbon]]
ENTONCES, UNA DESCALIFICACIロN, O UN[n]DEFECTO-

[msg MSG_013 [Futaba]]
ムNada de eso!

[msg MSG_014 [Ryuji]]
Todas esas palabras suenan como la[n]mierda que dirボa un idiota.
ムEs una mierda como ese idiota estホ[n]forzando sus reglas a la sociedad!

[msg MSG_015 [Ribbon]]
PERO, LAS REGLAS DEBEN SER SEGUIDAS...

[sel SEL_016 top]
No tienes que seguirlas.
No eres un error, Ribbon.

[msg MSG_017 [Ribbon]]
YO SOY... メNO SOY UN ERROR?

[msg MSG_018 [Makoto]]
Dime, Ribbon. メPor qu〒 no intentas[n]pensar por ti misma mientras estホs con[n]nosotros?

[msg MSG_019 [Ann]]
Suena como una gran idea.
No tienes que seguir a un egoc〒ntrico.[n]ムSon tonterボas del Supervisor!

[msg MSG_020 [Chie]]
Mm. ムY si esos bots intentan algo otra[n]vez, te protegeremos!

[msg MSG_021 [Ribbon]]
メME PROTEGERミN? PERO, メPOR QU※ AYUDA A[n]ALGUIEN COMO YO?

[msg MSG_022 [P3 Fem Protag]]
*risa* メRecuerdas lo que hablamos antes?[n]La respuesta a esta es simple...
Es porque eres una compaワera para[n]nosotros como Aigis, Ribbon.

[msg MSG_023 [Ribbon]]
YO... メSOY UNA COMPAヰERA?
...
ENTONCES, ESTO ES SER UNA COMPAヰERA…[n]ENTIENDO.

[msg MSG_024 [Aigis]]
Entiendo.

[msg MSG_025 [Ken]]
Sus diホlogos estホn sincronizando.

[msg MSG_026 [Aigis]]
Lo siento. No pude evitarlo.

[msg MSG_027 [P3 Fem Protag]]
*risa* Oh, Aigis...
Bueno, empecemos de nuevo. メEstホs lista,[n]Ribbon?

[msg MSG_028 [Ribbon]]
Sレ. SOY TU COMPAヰERA. ムDEBO SEGUIRTE!

[msg MSG_029 [Akihiko]]
Ese es el espボritu. Sigue asボ.

[msg MSG_030 [P3 Hero]]
Entonces, メseguimos? Espero que podamos[n]seguir juntos, Ribbon.

