[msg MSG_000 [Makoto]]
Bueno, al menos nos ocupamos de esa[n]cerradura sin problemas...

[msg MSG_001 [Morgana]]
Nos queda la マltima cerradura...
Aunque supongo que no es momento de[n]pensar en eso.

[msg MSG_002 [Futaba]]
ムAsボ es! ムTenemos que darnos prisa y[n]encontrar a Hikari!

[msg MSG_003 [Yusuke]]
Ese zumbido...

[msg MSG_004 [Intercomunicaciポn Del Teatro]]
Tenemos un anuncio para nuestros[n]clientes.
Una nueva pelボcula comenzarホ a[n]proyectarse en la sala 4 en breve.[n]Repito...

[msg MSG_005 [Intercomunicaciポn Del Teatro]]
Una nueva pelボcula... comenzarホ... a[n]proyectarse en... sala 4...
Por favor... ven a ver la pelボcula...[n]sin importar que...

[msg MSG_006 [Makoto]]
Espera, メesa マltima lボnea...?

[sel SEL_007 top]
Es de su invitaciポn.
No me suena...

[msg MSG_008 [Akechi]]
...Ya veo.
Fue lo mismo que decボa en la invitaciポn[n]de Hikari.

[msg MSG_009 [Yusuke]]
...メQu〒 estホ pasando aquボ?

[msg MSG_010 [Ann]]
Hikari, por favor, cuボdate...

[msg MSG_011 [Ryuji]]
ムArrgh! ムNo tiene seguir discutiendolo!
Esa cosa dijo sala 4, メverdad? ムEntremos[n]y salvemos a Hikari!

[msg MSG_012 [Rise]]
ムSe abriポ otra puerta del cine!

[msg MSG_013 [P3 Hero]]
Ese anuncio... Significa que otra[n]pelボcula empezポ a proyectarse, メcierto?

[msg MSG_014 [Ann]]
ムEspera! ムメQu〒 hay de Hikari?!

[msg MSG_015 [Fuuka]]
No logramos encontrarla... Ni siquiera[n]estoy segura de que ella todavボa est〒 en[n]el cine.

[msg MSG_016 [P4 Hero]]
Sボ, tampoco la encontramos. Solo queda[n]buscar en un lugar...

[msg MSG_017 [P3 Fem Protag]]
...Dentro de la pelボcula.

[msg MSG_018 [Kanji]]
Tenボa la sensaciポn de que ボbamos a[n]entrar. Estamos listos.

[msg MSG_019 [Koromaru]]
ムGuau!

[msg MSG_020 [Morgana]]
ムVamos! ムNo bajen la guardia!

