[msg MSG_000 [Yusuke]]
斡Miren!

[msg MSG_001 [Chie]]
夷Eh? 夷Qu姻 est茨 pasando?

[msg MSG_002 [Robot Con List吋n]]
TRAS REALIZAR UN AN威LISIS INTERNO, HE[n]IDENTIFICADO UN ERROR T畏CNICO.

[msg MSG_003 [Robot Producido En Masa A]]
TODOS LOS ERRORES DEBEN SER ELIMINADOS.

[msg MSG_004 [Robot Producido En Masa B]]
VEN CON NOSOTROS. RESTAURAREMOS TU[n]MEMORIA A SUS VALORES DE FABRICA.

[msg MSG_005 [Robot Con List吋n]]
ENTENDIDO.

[msg MSG_006 [Futaba]]
夷Es la robot del tr茨iler?

[msg MSG_007 [Yukari]]
Vaya, realmente tiene un parecido con[n]Aigis...

[msg MSG_008 [Fuuka]]
Um, m茨s importante... 斡Dijeron que van a[n]formatearla!

[sel SEL_009 top]
Debemos rescatarla.
Veamos que pasa.

[msg MSG_010 [Ryuji]]
斡S胤! 斡No podemos dejar que le hagan eso!

[msg MSG_011 [Akechi]]
Espera, debemos ser m茨s precavidos.
A雨n no nos han visto. Observemos un poco[n]primero…

[msg MSG_012 [Akechi]]
Estoy de acuerdo. Afortunadamente, a雨n[n]no nos han visto, as胤 que…

[msg MSG_013 [Akihiko]]
斡De ninguna manera, es nuestra[n]oportunidad! Podemos adelantarnos a[n]ellos ahora.

[msg MSG_014 [Shinjiro]]
Solo quieres golpearlos. Empieza a usar[n]tus 2 neuronas antes de hacer una[n]tonter胤a.

[msg MSG_015 [Akihiko]]
斡夷Qu姻?!

[msg MSG_016 [Mitsuru]]
夷Quieren dejar de discutir? 斡No tenemos[n]tiempo para esto!

[msg MSG_017 [P3 Fem Protag]]
Entonces, 斡hag茨moslo una competencia![n]夷Qu姻 tan r茨pido crees que podr胤as[n]derribar esos robots?

[msg MSG_018 [Akihiko]]
No me tomar胤a tres minutos.

[msg MSG_019 [Shinjiro]]
Lo har胤a en uno.

[msg MSG_020 [Akihiko]]
斡Entonces lo har姻 en 30 segundos!

[msg MSG_021 [Shinjiro]]
斡Mmm! 斡Espero que tu boca no est姻[n]escribiendo cheques, que tus pu隠os no[n]puedan cobrar!

[msg MSG_022 [Akihiko]]
斡Vuelve aqu胤, Shinji! 斡No voy a dejarte[n]tomar ventaja!

[msg MSG_023 [Junpei]]
斡Vaya! Sabes c吋mo manejarlos como a un[n]viol胤n.

[msg MSG_024 [P3 Fem Protag]]
斡Je, je, je, s胤! 斡Sucede todo el tiempo,[n]as胤 que s姻 exactamente c吋mo manejar su[n]competitividad!

[msg MSG_025 [Mitsuru]]
Vaya... 夷Tambi姻n act雨an como ni隠os en tu[n]mundo?
Bueno, en cualquier caso: gracias por[n]desactivar esa situaci吋n.

[msg MSG_026 [Makoto]]
No podemos quedarnos atr茨s.[n]斡Apoy姻moslos!

