[msg MSG_000 [Ryuji]]
夷Eh? Hay algo aqu胤 en el suelo.

[msg MSG_001 [Naoto]]
夷Es... un arma?

[sel SEL_002 top]
夷Es real?
He visto algo as胤 antes.

[msg MSG_003 [Makoto]]
Aunque no lo sea, 夷por qu姻 est茨 en la[n]pel胤cula?

[msg MSG_004 [Yusuke]]
S胤, creo que he visto algo asi antes...

[msg MSG_005 [P3 Fem Protag]]
斡Esperen! 斡Es un Evocador!

[msg MSG_006 [Ryuji]]
夷Te refieres a esa cosa con la que[n]invocas Personas?

[msg MSG_007 [P3 Fem Protag]]
S胤, 夷ven c吋mo tiene grabado 'SEES' en[n]ella?
La m胤a est茨 aqu胤 conmigo, 斡as胤 que esta[n]puede ser la de uno de mis compa隠eros!

[msg MSG_008 [Ann]]
Espera, 斡夷significa que tus amigos[n]realmente est茨n en esta pel胤cula?!

[msg MSG_009 [P3 Fem Protag]]
Probablemente. No s姻 de qui姻n es este[n]Evocador, pero...

[msg MSG_010 [Yosuke]]
Bueno, si la necesitan para invocar[n]personas, 夷no es malo que no la tengan?

[msg MSG_011 [P3 Fem Protag]]
Tal vez la perdieron despu姻s de ser[n]atacados. Espero que todos est姻n bien...

[msg MSG_012 [Chie]]
斡No te preocupes! 夷Recuerdas que Yosuke[n]result吋 estar bien?
斡Encontraremos a tus compa隠eros, [f 6 1 27 0 0 0]!

[sel SEL_013 top]
Por supuesto.
No te preocupes.

[msg MSG_014 [Morgana]]
Todos estamos de tu lado, as胤 que no[n]dudes en confiar en nosotros.

[msg MSG_015 [Yosuke]]
No solo los Ladrones Fantasma, todo el[n]equipo de investigaci吋n tambi姻n est茨[n]contigo.

[msg MSG_016 [P3 Fem Protag]]
Oh, chicos...
斡Muchas gracias! 斡Y tienen raz吋n,[n]debemos seguir movi姻ndonos por ahora!

[msg MSG_017 [P4 Hero]]
Estoy seguro de que tus compa隠eros[n]tambi姻n te est茨n buscando. Vamos a[n]reunirte con ellos.

