[msg MSG_000]
Cada equipo presionポ su interruptor y[n]regresポ al punto de encuentro...

[msg MSG_001 [Junpei]]
*gruワido* Ah, mi espalda...
No podrボa estar mホs feliz de haber[n]terminado eso. En serio.

[msg MSG_002 [Yukari]]
Nunca pens〒 que nos pondrボan una prueba[n]asボ... Pens〒 que iba a morir.

[msg MSG_003 [Naoto]]
Parece que los tres exホmenes fueron[n]implacables. Estuvimos al borde del[n]abismo en varias ocasiones...
Pero me alivia que todos los equipos[n]lograran completarlos con seguridad.

[msg MSG_004 [Akechi]]
Ahora que los tres interruptores han[n]sido presionados, finalmente podemos[n]desactivar las medidas de seguridad.

[msg MSG_005 [Ribbon]]
...

[msg MSG_006 [Makoto]]
メQu〒 pasa, Ribbon?

[msg MSG_007 [Ribbon]]
TODOS TIENEN HABILIDADES DIFERENTES,[n]PERO PARECレA QUE SE COMPLEMENTABAN UNO[n]AL OTRO.
ALGUNOS TENレAN UNAS HABILIDADES, OTROS[n]CARECレAN DE ELLAS... ESTO NO ES[n]UNIFORMIDAD. メNO TE MOLESTA ESO?

[msg MSG_008 [Yosuke]]
Bueno, es solo una parte de nuestra[n]individualidad. Aunque ese Supervisor[n]parezca negarlo.

[msg MSG_009 [Ribbon]]
INDIVIDUALIDAD...

[msg MSG_010 [Akihiko]]
Ademホs, cada uno tenボa un lボder que[n]convirtiポ a un grupo tan diferente a un[n]equipo de trabajo.

[msg MSG_011 [Mitsuru]]
Tienes razポn. Deberボamos agradecer a[n]nuestros tres lボderes por esa misiポn.

[msg MSG_012 [P3 Fem Protag]]
Je, je, je, me hace feliz poder ser[n]マtil. ムPero, este fue el resultado de[n]todos trabajando juntos!

[msg MSG_013 [P4 Hero]]
Exacto, es gracias a nuestros compaワeros[n]haciendo su mejor esfuerzo.

[msg MSG_014 [Mitsuru]]
Ja... Tienes un punto. Este es el fruto[n]del trabajo duro de todos.

[msg MSG_015 [Yusuke]]
Aunque tengo curiosidad, メcポmo crearon[n]instalaciones tan elaboradas para estas[n]pruebas?

[msg MSG_016 [Futaba]]
Oh, sobre eso. Parecen haber sido[n]simulaciones hologrホficas.
Bホsicamente, era como realidad virtual.[n]Todas las habitaciones estaban vacボas.

[msg MSG_017 [Shinjiro]]
メAsボ que esa cosa del dispositivo de[n]pruebas ni siquiera existボa?

[msg MSG_018 [Futaba]]
Sボ. Como verホs, si presiono aquボ...

[msg MSG_019 [Futaba]]
ムMweheheh! ムAhora podemos pasar sin ser[n]molestados por mホs exホmenes!

[msg MSG_020 [Ryuji]]
ムメEn serio?! Eso es impresionante...[n]Pero de todas formas...

[sel SEL_021 top]
Estoy aquボ contigo.
Pero, メCuホl era el punto de todo esto?
メQuieres hacer los exホmenes de nuevo?

[msg MSG_022 [Ryuji]]
メSabes a qu〒 me refiero? Pasamos por[n]todo eso, ムy todo era solo un montポn de[n]mierda!

[msg MSG_023 [Makoto]]
Bueno, es difボcil aceptar que todo ese[n]esfuerzo fue solo por una simulaciポn.
Aun asボ, logramos abrir la puerta al[n]laboratorio gracias a eso, asボ que...

[msg MSG_024 [Ryuji]]
ムNo, quiero decir! Nos esforzamos al[n]mホximo, pero bホsicamente fue solo una[n]especie de juego, メverdad?
Nos cansホbamos por nada... ムメO que todo[n]fue mホs bien una gran mentira?!

[msg MSG_025 [Kanji]]
Aun asボ, nunca volver〒 a hacer uno si[n]puedo evitarlo...

[msg MSG_026 [Fuuka]]
ムConfirmamos que la seguridad del centro[n]de investigaciポn ha sido desactivada![n]ムLa entrada estホ abierta!

[msg MSG_027 [Rise]]
No solo eso, parece que puedes pasar por[n]esa puerta ahora.
ムEntonces, parece que todavボa hay un[n]largo camino por recorrer, asボ que ten[n]cuidado mientras avanzas!

[msg MSG_028 [Morgana]]
Ya veo, entendido. Bueno, ムvamos!

