[msg MSG_000 [Makoto]]
斡Oracle! 斡夷C吋mo est茨?!

[msg MSG_001 [Futaba]]
Ella... todav胤a no se mueve... Sus luces[n]est茨n apagadas...

[msg MSG_002 [Haru]]
No... Intent吋 salvarnos, incluso si eso[n]significaba sacrificarse...

[msg MSG_003 [Yukiko]]
Ribbon era muy diferente de cuando la[n]conocimos, hab胤a cambiado tanto...

[msg MSG_004 [P3 Fem Protag]]
S胤... No hizo lo que le ordenaron. Pens吋[n]por s胤 misma, y actu吋 por sus propios[n]deseos...
Finalmente gan吋 una identidad... 斡No[n]puede terminar as胤!

[msg MSG_005 [Shinjiro]]
Tch... 斡夷No hay nada que podamos hacer?!

[sel SEL_006 top]
Tenemos que intentarlo.
夷Pero qu姻, exactamente?

[msg MSG_007 [Futaba]]
S胤... 斡Me niego a dejar que esto pase!

[msg MSG_008 [Fuuka]]
Aigis, 夷podr胤as echar un vistazo? Sus[n]configuraciones de dise隠o son similares[n]a las tuyas, tal vez...

[msg MSG_009 [Aigis]]
Entendido. Lo har姻.

[msg MSG_010 [Fuuka]]
Aigis, 夷podr胤as echar un vistazo? Sus[n]configuraciones de dise隠o son similares[n]a las tuyas, tal vez...

[msg MSG_011 [Aigis]]
Entendido. Lo har姻.

[msg MSG_012 [Futaba]]
斡Gracias!
Aguanta, Ribbon... 斡Estar茨s bien!

[msg MSG_013 [Kanji]]
Oracle... No sab胤a que te importaba[n]tanto...

[msg MSG_014 [Yusuke]]
Ella ha pasado por mucho.

[msg MSG_015 [Makoto]]
S胤, destacaba entre los dem茨s por todas[n]las cosas que solo ella pod胤a hacer...
Creo que los problemas de Ribbon con su[n]individualidad realmente resonaron en[n]Oracle.

[msg MSG_016 [Ken]]
Oh, ya entiendo...
La raz吋n por la que vino con nosotros a[n]la pel胤cula fue porque simpatiz吋 con[n]Ribbon en el trailer...

[msg MSG_017 [Futaba]]
斡Por favor despierta, Ribbon!
Estoy segura de que este ser茨 un gran[n]mundo de aqu胤 en adelante...
Trabajaste tan duro... Estoy segura de[n]que el mundo cambiar茨...
斡Pero necesitas verlo por ti misma! As胤[n]que... 斡Solo despierta!

[msg MSG_018 [Ann]]
S胤... Tiene raz吋n. Este va a ser un[n]mundo donde todos puedan vivir como[n]quieran.
Ser茨 un lugar maravilloso...

[msg MSG_019 [Aigis]]
斡Ribbon!

