[msg MSG_000 [Shinjiro]]
T雨 debes ser el responsable de este[n]lugar de mierda.

[msg MSG_001 [Junpei]]
夷C吋mo pudiste hacer esas cosas tan[n]terribles a Ribbon? 夷Es tan malo ser[n]diferente?

[msg MSG_002 [Madre Computadora]]
Todo lo que he hecho es tomar las[n]medidas apropiadas basadas en el[n]est茨ndar.
Su continua desobediencia a nuestro[n]est茨ndar demuestra la insensatez e[n]incorrecci吋n.

[msg MSG_003 [Junpei]]
斡Eh! 斡夷Por qu姻 est茨 Ikutsuki aqu胤 otra[n]vez?!

[msg MSG_004 [Mitsuru]]
T姻cnicamente, es un "Ikutsuki Robot". No[n]parece tener nada que ver con el real.

[msg MSG_005 [Chie]]
Uh, 斡夷Pero por qu姻 est茨 aqu胤?!

[msg MSG_006 [Madre Computadora]]
Me manifest姻 porque los robots anhelaban[n]mi existencia.
Ans胤an una sociedad unificada, sin[n]individualidad. As胤 que crearon un ser capaz[n]de establecer y defender esa sociedad.
Ese ser soy yo.
Estoy conectada a los circuitos de cada[n]robot...
Si aparece una irregularidad, puedo detectarla[n]inmediatamente. Ya que soy capaz de erradicar[n]estas irregularidades f茨cilmente.
En otras palabras, soy el guardi茨n de[n]los robots.

[msg MSG_007 [Kanji]]
夷Eh? 斡夷De qu姻 diablos est茨s hablando?![n]斡Est茨s diciendo tonter胤as!

[msg MSG_008 [Makoto]]
Cualquiera con individualidad perturba[n]la armon胤a de la sociedad, por lo que se[n]considera innecesaria en este mundo...
Entonces, 夷eres t雨 quien hace que los[n]robots se purguen al ser considerados[n]"errores"?

[msg MSG_009 [Madre Computadora]]
Si lo entienden tan bien, Act雨en de acuerdo a[n]errores que son y sigan el procedimiento[n]est茨ndar como todos los dem茨s.
Las existencias que se desv胤an de las[n]reglas no son m茨s que una vergüenza que[n]se debe corregir.

[msg MSG_010 [Yosuke]]
斡T雨 eres la que necesita ser corregida!

[msg MSG_011 [Yusuke]]
No impongas tus creencias sobre[n]nosotros.

[msg MSG_012 [Madre Computadora]]
Estas no son mis creencias. Son las[n]leyes de este mundo.
La individualidad de UIY-2249 es un defecto[n]que desaf胤a la armon胤a de nuestra sociedad...[n]Esa unidad debe ser tratada como tal.

[msg MSG_013 [Ribbon]]
MI INDIVIDUALIDAD ES... UN DEFECTO...

[msg MSG_014 [Futaba]]
斡Ribbon! 斡No dejes que esa est雨pida cosa[n]brillante te afecte!

[msg MSG_015 [Madre Computadora]]
Este robot es un defecto incapaz de[n]adherirse a las reglas de este mundo, y,[n]por lo tanto, es innecesario.

[msg MSG_016 [Ryuji]]
斡夷Qui姻n demonios crees que eres?!

[msg MSG_017 [Madre Computadora]]
Soy la voz que da las leyes a este[n]mundo.
Aquellos que no puedan entender mis[n]palabras necesitan ser eliminados como[n]inadaptados sociales.
UIY-2249...
Desaparece junto con las irregularidades[n]TK, YS y IW.

[sel SEL_018 top]
Basta de tonter胤as.
C茨llate.

[msg MSG_019 [P3 Hero]]
斡Eres t雨 quien va a desaparecer!

[msg MSG_020 [P4 Hero]]
斡S胤! 斡Nos negamos a aceptar sus leyes!

[msg MSG_021 [Madre Computadora]]
夷Qu姻 les impide entender?
Obedezcan mis palabras, y ser茨n felices.
Ya que se niegan a obedecerme, entonces[n]ser茨n eliminados.

[msg MSG_022 [P3 Fem Protag]]
Cuidado, 斡aqu胤 viene!

