[msg MSG_000 [Koromaru]]
斡Guau! 斡Guau!

[msg MSG_001 [Ken]]
夷Encontraste algo Koromaru?

[msg MSG_002 [Koromaru]]
斡Arf arf!

[msg MSG_003 [Naoto]]
Um, 夷Qu姻 dice Koromaru?

[msg MSG_004 [Junpei]]
Mmm... 畏l dijo, "斡Arf arf!"

[msg MSG_005 [Yukari]]
*suspiro* 夷Eres est雨pido? Todos o胤mos[n]eso.
Ojal茨 Aigis estuviera aqu胤... Ella[n]sabr胤a lo que dice.

[msg MSG_006 [Ribbon]]
"PERCIBO A NUESTROS COMPA謂EROS AQU緯.[n]DEBEN ESTAR M威S ADELANTE", ES LO QUE[n]DIJO.

[msg MSG_007 [P3 Fem Protag]]
Ribbon, 夷puedes entender lo que dice[n]Koromaru?

[msg MSG_008 [Ribbon]]
S緯. HE SIDO PROGRAMADA CON LA CAPACIDAD[n]DE ENTENDER MUCHOS IDIOMAS.

[msg MSG_009 [Ken]]
Vaya... 斡Igual que Aigis!

[msg MSG_010 [Ribbon]]
POR AQU緯.

[msg MSG_010_05 [Ribbon]]
TRAS ESTA PUERTA SE ENCUENTRA EL[n]LABORATORIO DE INVESTIGACI遺N UTILIZADO[n]POR ROBOTS ESPECIALIZADOS.
LAS UNIDADES CON ERRORES GRAVES SON[n]ENVIADAS AQU緯 PARA SER DESMONTADAS Y[n]ANALIZADAS.

[msg MSG_011 [Haru]]
Desmontadas... 夷Quieres decir que los[n]destrozan?

[msg MSG_012 [Futaba]]
Eso es peor que morir... Es como si[n]estuvieran siendo ejecutados.

[msg MSG_013 [Yusuke]]
夷C吋mo entramos? Parece que est茨 cerrado.

[msg MSG_014 [Ribbon]]
PARA DESBLOQUEAR ESTA PUERTA, POR FAVOR,[n]VENGAN.

[msg MSG_015 [Ryuji]]
夷Qu姻 se supone que hay aqu胤?

[msg MSG_016 [Ribbon]]
LAS ENTRADAS A LAS INSTALACIONES DE[n]INSPECCI遺N PARA TODOS LOS ROBOTS[n]PRODUCIDOS EN MASA.
TRAS CADA UNO DE ESTOS ASCENSORES HAY UN[n]INTERRUPTOR PARA DESBLOQUEAR LA ENTRADA[n]AL LABORATORIO.
UNA VEZ QUE SE HAYAN PRESIONADO LOS TRES[n]INTERRUPTORES, OBTENDR威N ACCESO AL[n]LABORATORIO.

[msg MSG_017 [Ann]]
夷Qu姻 significan esas palabras?
"Poder", "Conocimiento" y[n]"Adaptaci吋n"... 夷De qu姻 se trata todo[n]esto?

[msg MSG_018 [Ribbon]]
TE ENFRENTAR威S A UNA INSPECCI遺N BASADA[n]EN ESOS TRES ATRIBUTOS.

[msg MSG_019 [Kanji]]
Bueno, entiendo "Poder" y[n]"Conocimiento", pero 夷qu姻 significa[n]"Adaptaci吋n"?

[msg MSG_020 [Ribbon]]
ES UN EXAMEN QUE DETERMINA LA CAPACIDAD[n]DE REALIZAR TAREAS, INCLUSO BAJO[n]CIRCUNSTANCIAS EXTREMAS.
A MENOS QUE SE CUMPLAN LOS TRES[n]EST威NDARES, SE TE DESIGNAR威 COMO[n]DEFECTUOSO Y SE TE DENEGAR威 LA ENTRADA.

[msg MSG_021 [Mitsuru]]
ちァれもぼぺゆまょろまデ れよょ れもゆもゅぺるまれ ぺ らるゎまほぺれ ぽま[n]めぺほもゅもぽぺぽ わよぼぺぼもよょぺゅ を まゑァゆまょまれ ぽま[n]ぼぺゅもみもぼぺぼもカょテ はぺるまぼま りゎま まれろよ ょよ れまるァ みァぼもゅテテテ

[msg MSG_022 [P3 Fem Protag]]
夷Crees que aprobar胤as estos ex茨menes,[n]Ribbon?

[msg MSG_023 [Ribbon]]
CREO QUE MI PROBABILIDAD ES BAJA,[n]TENIENDO EN CUENTA QUE FUI CLASIFICADA[n]COMO DEFECTUOSA.

[msg MSG_024 [P4 Hero]]
Pero pasar por ah胤 es nuestra 雨nica[n]opci吋n... 夷Es seguro para los humanos?

[msg MSG_025 [Ribbon]]
NO HAY INFORMACI遺N ACERCA DE SU[n]SEGURIDAD.

[msg MSG_026 [Yukiko]]
Supongo que tiene sentido, no hay[n]humanos en este mundo. Entonces, 夷qu姻[n]hacemos?

[msg MSG_027 [P3 Fem Protag]]
Tendremos que entrar, aunque no tengamos[n]ni idea. 斡No se preocupen, vamos a[n]destrozar esos ex茨menes!

[msg MSG_028 [Junpei]]
Eso es tener confianza... Pero en serio,[n]夷c吋mo eres tan valiente?

[msg MSG_029 [Morgana]]
斡Ah, una afirmaci吋n propia de un ladr吋n[n]fantasma!
斡Hemos superado innumerables desaf胤os[n]con esa misma actitud!

[msg MSG_030 [Naoto]]
つれらまるぺほぺ りゎま ゅぺ もょみもゅろるぺぼもカょ みゎまるぺ れゎ[n]まれらまぼもぺゅもぽぺぽテ っまほまるウぺゆよれ るまぼゎるるもる ぺ ゅよれ[n]にぺぽるよょまれ づぺょろぺれゆぺ らぺるぺ よほろまょまる よるもまょろぺぼもカょ[n]れよほるま まれろぺ ゆもれもカょテ

[msg MSG_031 [P3 Fem Protag]]
斡Entonces, tenemos 吋rdenes! 斡Es hora de[n]ponerse en marcha!

[msg MSG_032 [Shinjiro]]
Vaya... Tenemos a una aut姻ntica chica[n]dura aqu胤.
Bueno, pensar tonter胤as tampoco es mi[n]estilo. Vamos a entrar.

[msg MSG_033 [Akihiko]]
Te escucho, quedarnos aqu胤 charlando[n]todo el d胤a, no nos va a servir de nada.[n]Vamos.

[msg MSG_034 [Mitsuru]]
En serio, ustedes dos...
Supongo que tienen un punto, no tenemos[n]tiempo que perder. 夷Qu姻 estrategia[n]deber胤amos usar?

[sel SEL_035 top]
夷Qu姻 tal uno a la vez?
Vamos a dividirnos en tres grupos.

[msg MSG_036 [Akechi]]
Eso ser胤a demasiado ineficiente... 夷No[n]perder胤amos a雨n m茨s el tiempo?

[msg MSG_037 [Yukiko]]
夷Qu姻 tal si nos dividimos en tres[n]grupos?

[msg MSG_038 [Mitsuru]]
Hagamos eso. Ser胤a mucho m茨s eficiente.

[msg MSG_039 [Akihiko]]
Yo me encargar姻 del examen de "Poder".[n]夷Est茨n bien con eso, Shinji? 夷Junpei?

[msg MSG_040 [Shinjiro]]
Deja de tomar decisiones por m胤.
Tch... Est茨 bien. Supongo que te echar姻[n]una mano.

[msg MSG_041 [Junpei]]
Sin objeciones. 斡Un hombre tiene que[n]enfrentar desaf胤os como este de frente!

[msg MSG_042 [Yukiko]]
Kanji tambi姻n es del tipo "Poder",[n]夷verdad?

[msg MSG_043 [Kanji]]
斡S胤!

[msg MSG_044 [Teddie]]
斡Oh, ya s姻! 斡Acompa隠ar姻 a Chie al examen[n]de "Poder"!

[msg MSG_045 [Chie]]
斡夷Me est茨s ofreciendo?! Pero, 斡no hay[n]otras chicas en el equipo!

[msg MSG_046 [Yosuke]]
Bueno, "Conocimiento" y "Adaptaci吋n" no[n]son precisamente tus puntos fuertes...

[msg MSG_047 [Chie]]
Qu姻... Aw... No puedo discutir con[n]eso...

[msg MSG_048 [Ryuji]]
Oh, tambi姻n ir姻 al examen de "Poder". No[n]tengo otras opciones.

[msg MSG_049 [Makoto]]
ひゎらよょむよ りゎま のるぺぼゅま を をよ ぽまほまるウぺゆよれ まょぼぺるむぺるょよれ[n]ぽまゅ まゑぺゆまょ ぽま "ぢよょよぼもゆもまょろよ"テ ぢよょみもカ まょ りゎま[n]らゎまぽよ るまれよゅわまる ぼゎぺゅりゎもまる らるよほゅまゆぺ ぽま[n]もょろまゅもむまょぼもぺ れもゆらゅまテテテ

[msg MSG_050 [Mitsuru]]
Tambi姻n elegir姻 el "Conocimiento". He[n]estudiado los asuntos generales del[n]gobierno imperial.

[msg MSG_051 [Morgana]]
斡No te olvides de m胤! 斡Soy el cerebro de[n]los Ladrones Fantasma!

[msg MSG_052 [Yosuke]]
つょろよょぼまれ ろぺゆほもイょ ぼゎまょろよ らぺるぺ "ぢよょよぼもゆもまょろよ"テ[n]ひよを まゅ ゃまみま ぽま よらまるぺぼもよょまれ ぽまゅ つりゎもらよ ぽま[n]とょわまれろもむぺぼもカょデ エれぺほまれ?

[msg MSG_053 [Yukiko]]
夷Eh? 夷En serio? 夷Desde cu茨ndo?

[msg MSG_054 [Yosuke]]
斡Desde el primer d胤a, claro!

[msg MSG_055 [Naoto]]
Perm胤tanme ir con ustedes tambi姻n. Tal[n]vez pueda ser de utilidad.

[msg MSG_056 [Akechi]]
Tambi姻n ir姻. Puede que no sea tan obvio,[n]pero soy un detective en entrenamiento.

[msg MSG_057 [Yukiko]]
Entonces el 雨ltimo es "Adaptaci吋n"...
Creo que puedo manejarlo, ya que trato[n]con clientes todos los d胤as.

[msg MSG_058 [Yusuke]]
Ha... Estoy seguro de que tambi姻n se[n]trata de adaptabilidad.
ぬも ぼるまぺろもわもぽぺぽ ほるもゅゅぺ れもょ もゆらよるろぺる ゅぺれ[n]ぼもるぼゎょれろぺょぼもぺれ まょ ゅぺれ りゎま まれろよをデ を らゎまぽよ[n]ぺゅもゆまょろぺるゆま もょぼゅゎれよ ぼゎぺょぽよ ょよ ろまょむよ ぽもょまるよテ

[msg MSG_059 [Makoto]]
Creo que podr胤as usar un poco m茨s de[n]sentido com雨n... De todos modos, Fox va[n]a "Adaptaci吋n"

[msg MSG_060 [Ann]]
エびま もゆらよるろぺ れも ゆま ゎょよ? でま わもわもぽよ ろぺょろよ まょ まゅ[n]まゑろるぺょゃまるよ ぼよゆよ まょ どぺらカょデ ぺれウ りゎま ぼるまよ りゎま ゆも[n]ぺぽぺらろぺほもゅもぽぺぽ まれ ほぺれろぺょろま れカゅもぽぺテ

[msg MSG_061 [Haru]]
Yo tambi姻n ir姻 a "Adaptaci吋n". Creo que[n]ser胤a mejor que con las otras opciones.

[msg MSG_062 [Ken]]
Koromaru y yo tambi姻n iremos. Eso[n]equilibrar茨 el n雨mero de personas.

[msg MSG_063 [Koromaru]]
斡Guau!

[msg MSG_064 [Yukari]]
Creo que tambi姻n ir姻 a "Adaptaci吋n".[n]Estoy en el club de tiro, as胤 que creo[n]que mi enfoque ser茨 雨til...

[msg MSG_065 [Futaba]]
夷D吋nde quieres ir, Ribbon? 夷Eres[n]competente en alguno de estos?

[msg MSG_066 [Ribbon]]
YO SOY UNA UNIDAD PERSPECTIVA GENERAL.
POR LO TANTO, NO TENGO CONOCIMIENTOS[n]ESPECIALIZADOS. 夷QU畏 DEBO HACER?

[sel SEL_067 top]
Ven conmigo.
Elige lo que prefieras.
Esp姻rame aqu胤.

[msg MSG_068 [Futaba]]
Me sentir胤a mejor si estuvieras con[n]ella, Joker. 斡Cu胤date de ese bot!

[msg MSG_069 [Ribbon]]
JOKER, ESTOY A TU CUIDADO.

[msg MSG_070 [Ribbon]]
夷QU畏 PREFIERO? NO TENGO NING郁N DESEO EN[n]PARTICULAR.

[msg MSG_071 [Morgana]]
Entonces, 夷no ser胤a m茨s seguro que se[n]quedara con Joker? 斡畏l es nuestro l胤der[n]y todo!

[msg MSG_072 [Futaba]]
Me sentir胤a mejor tambi姻n. 斡Cuida de ese[n]bot!

[msg MSG_073 [Ribbon]]
ENTENDIDO. ESTOY A TU CUIDADO.

[msg MSG_074 [Ann]]
Es demasiado peligroso dejarla aqu胤[n]sola. Esos robots la est茨n cazando.

[msg MSG_075 [Morgana]]
Entonces, 夷no ser胤a m茨s seguro que se[n]quedara con Joker? 斡畏l es nuestro l胤der[n]y todo!

[msg MSG_076 [Futaba]]
Me sentir胤a mejor tambi姻n. 斡Cuida a ese[n]bot!

[msg MSG_077 [Ribbon]]
ENTENDIDO. ESTOY A TU CUIDADO.

[msg MSG_078 [Akechi]]
Joker, [f 6 1 12 0 0 0], y son los 雨nicos que[n]quedan...
Es solo una idea, pero 夷y si los[n]nombramos l胤deres de cada equipo?

[msg MSG_079 [Ann]]
S胤... Joker tambi姻n tiene que unirse a[n]uno de los equipos.

[msg MSG_080 [Teddie]]
斡El Maestro siempre es nuestro l胤der,[n]as胤 que ser胤a un actor perfecto para el[n]papel!

[msg MSG_081 [Yosuke]]
Cierto. Definitivamente, puedo responder[n]a su liderazgo. 夷No es as胤, compa隠ero?

[msg MSG_082 [Akechi]]
夷Qu姻 tal t雨, [f 6 1 26 0 0 0]? 夷Estar胤as bien como[n]l胤der de un equipo?

[msg MSG_083 [P3 Fem Protag]]
No me importa si los dem茨s est茨n de[n]acuerdo...

[msg MSG_084 [P4 Hero]]
Es solo mi opini吋n, pero creo que est茨[n]m茨s que lista para ser l胤der.
Parece entender bien a los miembros del[n]SEES.

[msg MSG_085 [Haru]]
Pens姻 lo mismo. Parece bastante[n]desprotegida al tratar con las[n]personalidades de todos.

[msg MSG_086 [Yukari]]
Um... 夷Qu姻 hacemos?

[msg MSG_087 [Junpei]]
Est茨 m茨s que bien para m胤. 斡Tener a una[n]chica l胤der es como un sue隠o!

[msg MSG_088 [Akihiko]]
びぺゆらよぼよ ろまょむよ らるよほゅまゆぺれテ ひも ぺゅむよ みゎまるぺ ぺ ほぺゃぺる[n]ぽゎるぺょろま まゅ まゑぺゆまょデ ろよぽよ ゅよ りゎま ろまょぽるウぺ りゎま[n]めぺぼまる まれ らるよらよるぼもよょぺる れゎ るまれらぺゅぽよテ

[msg MSG_089 [Koromaru]]
斡Guau!

[msg MSG_090 [Ken]]
Estoy de acuerdo. Casi se siente natural[n]verla como l胤der...

[msg MSG_091 [Mitsuru]]
Es verdad... Si te parece bien,[n]夷estar胤as de acuerdo en guiarnos,[n][f 6 1 26 0 0 0]?

[msg MSG_092 [P3 Fem Protag]]
斡G-gracias! Por favor... 斡D姻jenmelo!

[msg MSG_093 [Shinjiro]]
No te presiones demasiado. No es como si[n]no crey姻semos en ti o nada, pero no[n]quiero que te lastimes.

[msg MSG_094 [P3 Fem Protag]]
斡Claro!

[msg MSG_095 [Morgana]]
Todo lo que queda es donde vas a ir,[n]Joker. 夷Qu姻 examen prefieres?

[sel SEL_096 top]
"Poder"
"Conocimiento"
"Adaptaci吋n"

[msg MSG_097 [Akihiko]]
夷Oh? Confiado en tu fuerza f胤sica, 夷Eh?[n]斡Muy bien, entonces vamos a probar tus[n]habilidades con Shinji!

[msg MSG_098 [Shinjiro]]
斡Deja de arrastrarme a tu mierda[n]infantil! 斡Ve a usar tus habilidades!

[msg MSG_099 [Ribbon]]
ENTIENDO. TE ACOMPA謂ARE A "PODER".

[msg MSG_100 [P4 Hero]]
Bueno, entonces, ir姻 a "Conocimiento".

[msg MSG_101 [P3 Fem Protag]]
E ir姻 a "Adaptaci吋n".

[msg MSG_102 [Yosuke]]
夷Ooh? 夷T雨 tambi姻n eres el tipo asesor?[n]斡Un l胤der asesor suena tan genial!

[msg MSG_103 [Makoto]]
No creo que esos dos sean compatibles[n]entre s胤... 夷Estaremos bien as胤?

[msg MSG_104 [Ribbon]]
ENTIENDO. TE ACOMPA謂ARE A[n]"CONOCIMIENTO".

[msg MSG_105 [P4 Hero]]
Bien, entonces, ir姻 a "Poder".

[msg MSG_106 [P3 Fem Protag]]
E ir姻 a "Adaptaci吋n".

[msg MSG_107 [Ann]]
S胤, eres muy vers茨til. S姻 que te las[n]arreglaras bien en cualquier lugar.

[msg MSG_108 [Futaba]]
S胤, 斡se acostumbr吋 a vivir en el 茨tico[n]del Leblanc muy r茨pido!

[msg MSG_109 [Ribbon]]
ENTIENDO. TE ACONSEJO "ADAPTACI遺N".

[msg MSG_110 [P4 Hero]]
Bien, entonces, ir姻 a "Poder"

[msg MSG_111 [P3 Fem Protag]]
E ir姻 a "Conocimiento".

[msg MSG_112 [Morgana]]
Muy bien, ahora tenemos tres equipos.[n]Les deseo lo mejor...
Una vez que pulsemos con 姻xito el bot吋n,[n]reun茨monos aqu胤.

[msg MSG_113 [Fuuka]]
Parece que las navegadoras no vamos a[n]poder hablar con ustedes durante los[n]ex茨menes debido a la seguridad.
斡Tengan cuidado, por favor!

