[msg MSG_000 [Shinjiro]]
Tマ debes ser el responsable de este[n]lugar de mierda.

[msg MSG_001 [Junpei]]
メCポmo pudiste hacer esas cosas tan[n]terribles a Ribbon? メEs tan malo ser[n]diferente?

[msg MSG_002 [Madre Computadora]]
Todo lo que he hecho es tomar las[n]medidas apropiadas basadas en el[n]estホndar.
Su continua desobediencia a nuestro[n]estホndar demuestra la insensatez e[n]incorrecciポn.

[msg MSG_003 [Junpei]]
ムEh! ムメPor qu〒 estホ Ikutsuki aquボ otra[n]vez?!

[msg MSG_004 [Mitsuru]]
T〒cnicamente, es un "Ikutsuki Robot". No[n]parece tener nada que ver con el real.

[msg MSG_005 [Chie]]
Uh, ムメPero por qu〒 estホ aquボ?!

[msg MSG_006 [Madre Computadora]]
Me manifest〒 porque los robots anhelaban[n]mi existencia.
Ansボan una sociedad unificada, sin[n]individualidad. Asボ que crearon un ser capaz[n]de establecer y defender esa sociedad.
Ese ser soy yo.
Estoy conectada a los circuitos de cada[n]robot...
Si aparece una irregularidad, puedo detectarla[n]inmediatamente. Ya que soy capaz de erradicar[n]estas irregularidades fホcilmente.
En otras palabras, soy el guardiホn de[n]los robots.

[msg MSG_007 [Kanji]]
メEh? ムメDe qu〒 diablos estホs hablando?![n]ムEstホs diciendo tonterボas!

[msg MSG_008 [Makoto]]
Cualquiera con individualidad perturba[n]la armonボa de la sociedad, por lo que se[n]considera innecesaria en este mundo...
Entonces, メeres tマ quien hace que los[n]robots se purguen al ser considerados[n]"errores"?

[msg MSG_009 [Madre Computadora]]
Si lo entienden tan bien, Actマen de acuerdo a[n]errores que son y sigan el procedimiento[n]estホndar como todos los demホs.
Las existencias que se desvボan de las[n]reglas no son mホs que una verg↓enza que[n]se debe corregir.

[msg MSG_010 [Yosuke]]
ムTマ eres la que necesita ser corregida!

[msg MSG_011 [Yusuke]]
No impongas tus creencias sobre[n]nosotros.

[msg MSG_012 [Madre Computadora]]
Estas no son mis creencias. Son las[n]leyes de este mundo.
La individualidad de UIY-2249 es un defecto[n]que desafボa la armonボa de nuestra sociedad...[n]Esa unidad debe ser tratada como tal.

[msg MSG_013 [Ribbon]]
MI INDIVIDUALIDAD ES... UN DEFECTO...

[msg MSG_014 [Futaba]]
ムRibbon! ムNo dejes que esa estマpida cosa[n]brillante te afecte!

[msg MSG_015 [Madre Computadora]]
Este robot es un defecto incapaz de[n]adherirse a las reglas de este mundo, y,[n]por lo tanto, es innecesario.

[msg MSG_016 [Ryuji]]
ムメQui〒n demonios crees que eres?!

[msg MSG_017 [Madre Computadora]]
Soy la voz que da las leyes a este[n]mundo.
Aquellos que no puedan entender mis[n]palabras necesitan ser eliminados como[n]inadaptados sociales.
UIY-2249...
Desaparece junto con las irregularidades[n]TK, YS y IW.

[sel SEL_018 top]
Basta de tonterボas.
Cホllate.

[msg MSG_019 [P3 Hero]]
ムEres tマ quien va a desaparecer!

[msg MSG_020 [P4 Hero]]
ムSボ! ムNos negamos a aceptar sus leyes!

[msg MSG_021 [Madre Computadora]]
メQu〒 les impide entender?
Obedezcan mis palabras, y serホn felices.
Ya que se niegan a obedecerme, entonces[n]serホn eliminados.

[msg MSG_022 [P3 Fem Protag]]
Cuidado, ムaquボ viene!

