[msg MSG_000 [Chico Con Auriculares]]
Asボ que este es el Cine... No puedo[n]creer que estuvi〒ramos dentro de una[n]pelボcula.

[msg MSG_001 [Junpei]]
メVerdad? ムPor fin pude debutar en la[n]gran pantalla!

[msg MSG_002 [Hikari]]
Me alegra que te hayan encontrado a[n]tiempo...

[msg MSG_003 [Chico Con Auriculares]]
Eres Hikari, メverdad? Un placer[n]conocerte. Todos me hablaron ti.

[msg MSG_004 [Hikari]]
Fueron a buscarte, y... Me alivia que[n]est〒s bien.

[msg MSG_005 [Chico Con Auriculares]]
Gracias por preocuparte por mボ.

[msg MSG_006 [Hikari]]
Oh, mm... Bueno, todos los demホs estaban[n]preocupados, asボ que...

[msg MSG_007 [Chico Con Auriculares]]
Por cierto, alguien me dijo que no[n]puedes recordar como llegaste aquボ...

[msg MSG_008 [Hikari]]
M-mmhm... Cuando me despert〒, ya estaba[n]aquボ...

[msg MSG_009 [Chico Con Auriculares]]
No te preocupes. Saldremos de este lugar[n]juntos.
...Aunque, puede sonar extraワo viniendo[n]de alguien que acaba de llegar.

[msg MSG_010 [Hikari]]
...

[msg MSG_011 [Chico Con Auriculares]]
メCポmo estホ Aigis?

[msg MSG_012 [Fuuka]]
Como sospechaba Mitsuru, parece que solo[n]estホ temporalmente desactivada.

[msg MSG_013 [Morgana]]
Futaba, メpodrボas echar un vistazo? Se te[n]dan bien esas cosas t〒cnicas, メverdad?

[msg MSG_014 [Futaba]]
Bueno, tengo habilidades de hackeo, pero[n]no soy mecホnica...
Pero har〒 lo que pueda. Puedo... Echar〒[n]un vistazo.

[msg MSG_015 [Nagi]]
En ese caso, por favor sボgueme...

[msg MSG_016 [Yusuke]]
メCポmo te fue, Futaba?

[msg MSG_017 [Futaba]]
Wow... Ella estホ compuesta de partes[n]locas con tecnologボa alucinante y, mm...[n]En fin, ムes simplemente una locura!

[sel SEL_018 top]
Ah, ya veo...
Eso no significa nada.

[msg MSG_019 [Yukiko]]
Tampoco lo entiendo, pero entiendo la[n]idea de que es una locura.

[msg MSG_020 [Futaba]]
Parece que tiene una funciポn de[n]autoreparaciポn, ムlas partes rotas se[n]estホn arreglando solas!
ムメQu〒 clase de tecnologボa es ESA?![n]ムParece mホs magia que ciencia ficciポn!

[msg MSG_021 [Mitsuru]]
Todas sus funciones parecen funcionar[n]normalmente. No hay problemas por el[n]momento.

[msg MSG_022 [Futaba]]
Apenas tiene energボa, pero a este ritmo,[n]debe recuperarse pronto.

[msg MSG_023 [Hikari]]
Ya veo... Me alegro de que ella tambi〒n[n]est〒 bien...

[msg MSG_024 [Akihiko]]
Lamento la molestia, pero vamos a tener[n]que dejar a Aigis bajo su cuidado hasta[n]que se recupere.

[msg MSG_025 [P4 Hero]]
Una coa menos de la que preocuparnos.

[msg MSG_026 [Chico Con Auriculares]]
Debo darles las gracias de nuevo por su[n]apoyo, incluyendo lo de Aigis. Estoy muy[n]agradecido.
Entonces... メY tマ eres...?

[msg MSG_027 [Kanji]]
ムCierto, todavボa no nos hemos[n]presentado! Soy Kanji Tatsumi, de primer[n]aワo en el Instituto Yasogami.

[msg MSG_028 [Chico Con Auriculares]]
メPrimer aワo? Asボ que eres mホs joven que[n]yo...

[msg MSG_029 [Chie]]
T〒cnicamente, podrボa ser incluso mホs[n]joven de lo que crees...

[msg MSG_030 [Chico Con Auriculares]]
メA qu〒 te refieres?

[msg MSG_031 [Akechi]]
Todos hemos venido de diferentes[n]lugares... y de diferentes momentos.
No solo eso, algunos de nosotros[n]aparentemente estamos lidiando con temas[n]aマn mホs anormales...

[msg MSG_032 [P3 Fem Protag]]
...

[msg MSG_033 [Akechi]]
Podemos dejar los detalles para mホs[n]tarde...
Pero, bホsicamente, hemos venido de[n]mundos distintos, por mホs raro que[n]suene.

[msg MSG_034 [Chico Con Auriculares]]
Ya veo... Muy bien, entonces.

[msg MSG_035 [Ann]]
メEstホs bien con eso?
Oye, me estホs empezando a recordar mucho[n]a [f 6 1 30 0 0 0]...

[sel SEL_036 top]
Creo que nos llevaremos bien.
Creo que estホs imaginando cosas.

[msg MSG_037 [Chie]]
Ahh, te entiendo. Tambi〒n se parece[n]mucho a nuestro lボder.

[msg MSG_038 [Chie]]
メEn serio? Sabes, 〒l es muy similar a[n]nuestro lボder tambi〒n.

[msg MSG_039 [Makoto]]
メAsボ que, tマ tambi〒n eres el lボder de[n]Takeba e Iori?

[msg MSG_040 [Chico Con Auriculares]]
Sボ, oh, cierto que aマn no te he dicho mi[n]nombre, メeh? Mi nombre es...

