[msg MSG_000 [Yukiko]]
Oh... Dejo de moverse.

[msg MSG_001 [Yukari]]
夷Estaremos bien? 斡Es tan oscuro, no[n]puedo ver nada!

[msg MSG_002 [Sistema De IA Para Ex茨menes]]
UNIDADES TK-00, 02, 04, 07. UNIDAD[n]YS-03.
UNIDADES IW-01, 07, 08. UNIDAD UIY-2249.
COMENZANDO LA PRUEBA DE "ADAPTACI遺N".

[msg MSG_003 [Yusuke]]
Esto no parece ser una trampa, pero 夷qu姻[n]pretenden exactamente que hagamos en la[n]oscuridad?

[msg MSG_004 [Haru]]
夷Eh? Hay una viga de metal que se[n]extiende sobre un horno enorme...

[msg MSG_004_1 [Haru]]
Y al otro lado... 夷Es un puente[n]levadizo?

[msg MSG_005 [Sistema De IA Para Ex茨menes]]
ANTE TI HAY UNA BARRA DE EQUILIBRIO.
LA CONDICI遺N EXTREMA DESIGNADA PARA EL[n]EXAMEN DE ADAPTACI遺N DE HOY ES[n]"ALTURAS".
SI NO PUEDE ADAPTARSE A ESTA DIF緯CIL[n]SUPERFICIE AL CAMINAR, SER威 DESECHADO.

[msg MSG_006 [Ann]]
Espera, 斡夷"Desechado"?!

[msg MSG_007 [Ken]]
Bueno, si no podemos adaptarnos,[n]acabaremos en el horno... esa s胤 que es[n]una forma de desechar de algo...

[msg MSG_008 [Ribbon]]
AS緯 FUNCIONA AQU緯 LA ELIMINACI遺N[n]CUALQUIER ROBOT CON UN ERROR FATAL ES[n]INMEDIATAMENTE DESECHADO.

[msg MSG_009 [Sistema De IA Para Ex茨menes]]
NOTA: EN ESTA PRUEBA SE REQUIERE[n]COOPERACI遺N. SI SE FALLA EN UNA TAREA,[n]TODOS AFRONTAR威N LAS CONSECUENCIAS.
CADA UNIDAD SE CONSIDERAR威 CR緯TICAMENTE[n]ERR遺NEA Y SE ELIMINAR威 SIMULT威NEAMENTE.
VAMOS A EMPEZAR EL EXAMEN.

[msg MSG_010 [Yukiko]]
As胤 que esto es lo que entienden por[n]adaptaci吋n. No tenemos m茨s remedio que[n]cruzar, 夷verdad?

[sel SEL_011 top]
Esto es aterrador...
Esto ser茨 pan comido.
Me encantan las alturas.

[msg MSG_012 [Yusuke]]
Mm, incluso Joker est茨 asustado por[n]esto.

[msg MSG_013 [Ann]]
夷Qu姻 es tan gracioso, Fox? Tienes que[n]cruzarlo tambi姻n.

[msg MSG_014 [Ken]]
夷En serio? 斡No me extra隠a que seas un[n]ladr吋n fantasma!

[msg MSG_015 [Ann]]
斡Eh, este examen no tiene nada que ver[n]con ser un ladr吋n fantasma! 斡No pongas[n]la vara tan alta!

[msg MSG_016 [Yusuke]]
S胤, estar tan cerca del cielo tambi姻n me[n]alegra. A veces puede brindar unas[n]vistas incre胤bles.

[msg MSG_017 [Ann]]
Oh, bien... Todo lo que veo desde aqu胤[n]es un final caluroso.

[msg MSG_018 [Yukari]]
Sabes, podr胤an llamar a este un "examen"[n]para robots...
Pero 夷esto no es m茨s bien una prueba de[n]vida o muerte para personas?

[msg MSG_019 [Yukiko]]
夷C吋mo cruzamos esto? Ser胤a m茨s f茨cil[n]imaginar si pudi姻ramos ver un ejemplo.

[msg MSG_020 [Koromaru]]
斡Guau!

[msg MSG_021 [Ken]]
Eh, 夷Koromaru?

[msg MSG_022 [Yukari]]
Vaya... 斡Lo hizo tan r茨pido!

[msg MSG_023 [Koromaru]]
斡Bark bark!

[msg MSG_024 [Ribbon]]
畏l dijo: "Todo estar茨 bien, todos. Solo[n]s胤ganme".

[msg MSG_025 [Ken]]
斡Wow, Koromaru! Tienes agallas.
Pero... no creo que podamos copiar su[n]m姻todo tan f茨cil.

[msg MSG_026 [Ann]]
S胤, ser胤a m茨s si pudi姻ramos ver un[n]ejemplo HUMANO.

[msg MSG_027 [Yusuke]]
En ese caso, deber胤amos dej茨rselo a[n]nuestro l胤der.

[msg MSG_028 [Yusuke]]
斡Mu姻stranos el camino, Joker!

[sel SEL_029 top]
Voy a destrozar esto.
Recoge mis cenizas si caigo.

[msg MSG_030 [Yusuke]]
Dudo que incluso quedaran cenizas... No,[n]斡Simplemente debo aceptar tu 雨ltima[n]petici吋n!

[msg MSG_031]
Parece que ha llegado mi hora...

[msg MSG_032 [Ken]]
Oh vaya, 斡No puedo creer que est姻 caminando[n]con tanta confianza! 斡No es de extra隠ar que[n]sea el l胤der de los Ladrones Fantasma!

[msg MSG_033 [Yukari]]
Su equilibrio es tan perfecto, incluso a[n]esa velocidad...

[msg MSG_034]
He cruzado la viga...

[msg MSG_035 [Yukiko]]
斡Lo hiciste, Joker! Empiezo a creer que[n]puedo hacerlo tambi姻n.

[msg MSG_036 [Ribbon]]
ESA FUE UNA MUESTRA VITAL. HE CALCULADO[n]LA RUTA M威S SEGURA PARA CRUZAR.

[msg MSG_037 [Yukari]]
夷Qu姻 quieres decir con la ruta m茨s[n]segura? 斡夷No hay solo una viga?!

[msg MSG_038 [Haru]]
Ah胤 va... Me pregunto si estar茨 bien.

[msg MSG_039 [Yusuke]]
Dijo que encontr吋 la ruta m茨s segura.[n]Dudo que caiga despu姻s de esos c茨lculos.

[msg MSG_040 [Ken]]
Parece que est茨 cruzando el centro de la[n]viga con calma...

[msg MSG_041 [Ann]]
Oh, 斡Lo logr吋!
Entonces... 夷Qui姻n sigue?

[msg MSG_042 [Haru]]
夷Puedo? Creo que podr胤a hacer un buen[n]trabajo copiando su enfoque.
Solo necesito canalizar mis habilidades[n]de ballet aqu胤, y... 斡Hup!

[msg MSG_043 [Yusuke]]
Oh, vaya, es majestuosa. Solo mira su[n]t姻cnica perfecta...

[msg MSG_044 [Yukiko]]
S胤, lo hizo como si nada. Bueno, creo[n]que ir姻 yo.
Apuesto a que esto ser茨 f茨cil si[n]simplemente pienso en la viga de acero[n]como el borde de un tatami.

[msg MSG_045 [Yukari]]
夷Qu姻 tienen que una cosa con la otra?[n]斡Espera! Oh, ella ya est茨 cruzando...

[msg MSG_046 [Ann]]
斡Yukiko tambi姻n tiene agallas!

[msg MSG_047 [Yusuke]]
斡Su apariencia desde atr茨s mientras cruza, con[n]su vida en juego, es una maravilla de[n]contemplar! 斡Ha conmovido lo m茨s profundo de[n]mi alma!
En ese caso, deber胤a ir yo. 斡Encarnar姻 a[n]la belleza misma con mi t姻cnica!

[sel SEL_048 top]
Tranquilo, Fox, simplemente ven aqu胤.
Hipnot胤zanos a todos, Fox.

[msg MSG_049 [Yusuke]]
Bien. Quema mi imagen en tus retinas.

[msg MSG_050]
Fox comenz吋 a cruzar la viga...
Ahora se balancea salvajemente...

[msg MSG_051 [Ann]]
夷Su enfoque no parece... extremadamente[n]peligroso?

[msg MSG_052 [Yukari]]
S胤, ese balanceo hace que parezca que[n]est茨 a punto de caer... Lo haga o no, no[n]se ve bien.

[msg MSG_053 [Yusuke]]
斡Aah!

[msg MSG_054 [Ann]]
斡Fox!

[msg MSG_055 [Yusuke]]
斡Haaa!

[msg MSG_056 [Yukari]]
Uh, 夷qu姻 est茨 haciendo? 夷Realmente...[n]est茨 arriesgando su vida por una broma?[n]夷Se supone que debo re胤rme, o...?

[msg MSG_057 [Yusuke]]
斡ESTO es la proporci吋n 茨urea del[n]equilibrio!

[msg MSG_058 [Ann]]
斡Vaya, no nos asustes as胤, Fox![n]Espera... ya est茨 del otro lado.

[msg MSG_059 [Yukari]]
Solo quedamos nosotros. 夷Qui姻n sigue?

[msg MSG_060 [Ann]]
Este es el tipo de situaci吋n que se vuelve m茨s[n]estresante cuanto m茨s esperamos... 夷Deber胤amos[n]ir todos juntos?

[msg MSG_061 [Yukari]]
斡Buena idea! 夷Quieres tomar la[n]delantera, Panther?

[msg MSG_062 [Ann]]
Preferir胤a ir en medio... o algo as胤.

[msg MSG_063 [Ken]]
Entonces, tomar姻 la delantera. Por[n]favor, s胤ganme.

[msg MSG_064 [Yukari]]
斡夷Quieres ir primero, Ken?!

[msg MSG_065 [Ken]]
斡S-s姻 que puedo hacerlo! Estar姻 bien...[n]mientras no mire hacia abajo.

[msg MSG_066 [Ann]]
斡夷Podemos ir despacio? Es aterrador, as胤[n]que tal vez deber胤a cerrar los ojos…

[msg MSG_067 [Yukari]]
斡No, no hagas eso! 斡Conc姻ntrate en la[n]viga y no en el suelo!

[msg MSG_068 [Ann]]
Oh maldici吋n, mis piernas est茨n[n]temblando...

[msg MSG_069 [Ken]]
斡Solo un poco m茨s! No pienses, 斡solo[n]sigue movi姻ndote!

[msg MSG_070 [Ann]]
Ah, finalmente lo logramos... Estaba[n]sudando balas.

[msg MSG_071 [Haru]]
Menos mal. 斡Bien hecho los tres!

[msg MSG_072 [Yukari]]
Uf... Siento que logr姻 cruzar esa viga[n]gracias a que Ken lider吋 el camino.

[msg MSG_073 [Ken]]
En realidad, yo tambi姻n ten胤a miedo... Pero,[n]夷al menos demostr姻 que puedo seguir cuando las[n]cosas se ponen dif胤ciles?

[sel SEL_074 top]
Lo hiciste genial.
Podr胤as ser un ladr吋n fantasma.

[msg MSG_075 [Ken]]
Je, je, je... Todo lo que hice fue[n]seguirte el paso.

[msg MSG_076 [Ann]]
Aun as胤, estuviste genial ah胤 fuera,[n]Ken. 斡Buen trabajo!

[msg MSG_077 [Koromaru]]
斡Arf arf!

[msg MSG_078 [Ann]]
Mm, te recibir胤amos con gusto en el[n]equipo, Ken.

[msg MSG_079 [Ken]]
夷En serio? Je, je, je, un ladr吋n[n]fantasma, eh... 斡Incre胤ble!

[msg MSG_080 [Koromaru]]
斡Arf arf!

[msg MSG_081 [Sistema De IA Para Ex茨menes]]
EN LA PR遺XIMA SECCI遺N.

[msg MSG_082 [Haru]]
A雨n no termina, 夷eh?

[msg MSG_083 [Sistema De IA Para Ex茨menes]]
A CONTINUACI遺N, DEBEN CRUZAR LA VIGA EN[n]MENOS DE 3 MINUTOS. TODAS LAS UNIDADES[n]DEBEN CRUZAR SIMULT威NEAMENTE.
SI ALGUNA UNIDAD CAE, TODAS LAS UNIDADES[n]SER威N DESECHADAS DEBIDO A LA[n]RESPONSABILIDAD COLECTIVA.

[msg MSG_084 [Yukari]]
夷Qu姻? 斡No puede hablar en serio![n]斡夷Tenemos que ir todos juntos y en menos[n]de tres minutos?!

[msg MSG_085 [Yukiko]]
斡Oh, apareci吋 otra!

[msg MSG_086 [Sistema De IA Para Ex茨menes]]
EL TEMPORIZADOR HA COMENZADO. INICIANDO[n]LA SEGUNDA SECCI遺N DEL EXAMEN...

[msg MSG_087 [Ann]]
Oye, espera un mo... 斡夷Ya?!

[msg MSG_088 [Yusuke]]
No tenemos tiempo para estrategias,[n]sig茨mosle el paso a Joker.

[msg MSG_089 [Haru]]
Aseg雨rense de no mirar hacia abajo.[n]斡Miren hacia adelante!

[msg MSG_090 [Yukari]]
Est茨 bien, puedo hacer esto... Acabo de[n]hacerlo hace un segundo, as胤 que...

[msg MSG_091 [Sistema De IA Para Ex茨menes]]
QUEDA 1 MINUTO.

[msg MSG_092 [Ken]]
夷Qu姻 hacemos? 斡Si no nos damos prisa, no[n]lo lograremos!

[msg MSG_093 [Yukiko]]
斡夷Qu姻?! Me tropec姻...

[msg MSG_094 [Haru]]
斡Me estoy resbalando!

[msg MSG_095 [Yukari]]
斡Mierda, me voy a caer!

[msg MSG_096 [Ann]]
斡Aah, alguien ay雨deme! 斡Socorro!

[sel SEL_097 top]
Salvar a Yukiko.
Salvar a Yukari.
Salvar a Panther.
Salvar a Noir.

[msg MSG_098 [Yukiko]]
夷Eh? Oh... Gracias.

[msg MSG_098_5 [Yukiko]]
斡Oh...!

[msg MSG_099 [Yukari]]
斡Ah, gracias por la ayuda!

[msg MSG_099_5 [Yukari]]
Espera, 斡夷qu姻...?!

[msg MSG_100 [Ann]]
斡Joker! 斡Gracias, eso me hace tan feliz!

[msg MSG_100_5 [Ann]]
斡Espera!

[msg MSG_101 [Haru]]
夷Eh? 夷Joker?! Gracias, me aferrar姻 a ti.

[msg MSG_101_5 [Haru]]
Espera, 斡夷qu姻?!

[msg MSG_102 [Yusuke]]
斡Ups! 斡Lo siento, Joker!

[msg MSG_103]
Fox se aferra firmemente a m胤...

[msg MSG_104 [Yusuke]]
Gracias a tu mano, logr姻 recuperar mi[n]equilibrio. Estoy muy agradecida.

[msg MSG_105 [Yukiko]]
...

[msg MSG_106 [Yukari]]
...

[msg MSG_107 [Ann]]
...

[msg MSG_108 [Haru]]
...

[msg MSG_109 [Ken]]
斡Oh, miren! 斡Casi lo hemos logrado!

[msg MSG_110 [Yusuke]]
Espl姻ndido, 斡vamos directo hacia la[n]meta!
...Oye, Joker, 夷qu姻 te detiene?

[msg MSG_111 [Ann]]
No puede correr, tiene a Fox pegado en[n]姻l.

[msg MSG_112 [Yusuke]]
Ah, s胤. Disculpa.

[msg MSG_113 [Haru]]
El interruptor deber胤a estar adelante.[n]斡Vamos!

[msg MSG_114 [Koromaru]]
斡Arf!

[msg MSG_115]
Mientras tanto, en la sala de examen[n]"Poder"...

[msg MSG_116 [P4 Hero]]
Ahora que lo pienso, 夷no ser胤a m茨s f茨cil[n]si simplemente nos pusi姻ramos en la[n]b茨scula?

[msg MSG_117 [Teddie]]
斡Eso es nuestro Maestro! 斡He estado[n]pensando lo mismo todo este tiempo!

[msg MSG_118 [Ryuji]]
斡No me vengas con esa mierda! 斡Parec胤a[n]que estabas mojando tu traje hace tres[n]segundos!

[msg MSG_119 [Akihiko]]
Je, je, je... Eso es bastante bueno.

[msg MSG_120 [Shinjiro]]
斡Deja de perder el tiempo con mierdas y[n]en fila para la escala!

[msg MSG_121 [Chie]]
斡Ah, espera! 夷Podemos, eh... no subirnos[n]uno por uno? 夷Por favor?

[msg MSG_122]
Mientras tanto, en la sala de examen de[n]"Conocimiento"...

[msg MSG_123 [Makoto]]
Excelente, Mona, otra respuesta[n]correcta. Eres el 雨ltimo, Hanamura.

[msg MSG_124 [Yosuke]]
B-bien... 斡Hora de mostrar mis[n]habilidades como jefe de operaciones!

[msg MSG_125 [P3 Fem Protag]]
Rel茨jate, Yosuke. Estar茨s bien si te[n]dejas llevar.

[msg MSG_126 [Naoto]]
tiene raz吋n, enf吋cate en mantener la[n]calma.

[msg MSG_127 [P3 Fem Protag]]
Si es necesario, estaremos aqu胤 para[n]ayudarte, 斡as胤 que mant姻n la confianza!

[msg MSG_128 [Morgana]]
Ah... ella es bastante buena en esto,[n]夷verdad?

[msg MSG_129 [Mitsuru]]
S胤, nos est茨 manteniendo unidos. Puedo[n]ver que es una l胤der natural.

