[msg MSG_000 [Rise]]
斡Esperen chicos! 斡Estamos recibiendo una[n]se隠al del piso de abajo!

[msg MSG_001 [Fuuka]]
Esta lectura... 斡Creo que lo m茨s[n]probable es que sea Aigis y nuestro[n]l胤der!

[msg MSG_002 [Shinjiro]]
Parece que finalmente los alcanzamos.

[msg MSG_003 [Mitsuru]]
Bien, debemos rescatarlos de[n]inmediato...

[msg MSG_004 [Koromaru]]
斡Guau! 斡Bark bark!

[msg MSG_005 [Ken]]
斡夷Koromaru...?!

[msg MSG_006 [Ribbon]]
ESA DIRECCI遺N... PARECE QUE KOROMARU HA[n]ENCONTRADO "LA PUERTA".

[msg MSG_007 [Ann]]
斡Vamos!

[msg MSG_008 [Morgana]]
Algo sobre una puerta, 夷eh? Mmm...[n]Joker. Vamos a investigar esto.

