[msg MSG_000 [Akechi]]
*suspiro* Hay enemigos por todas partes.[n]Esto va a frenar nuestro progreso.

[msg MSG_001 [Shinjiro]]
Hmph, qu姻 molestia. Ni siquiera tenemos[n]tiempo para descansar.

[msg MSG_002 [Teddie]]
Ooh, ooh... 斡Eso me recuerda! 夷Est茨s[n]mejor ahora, Ai?

[msg MSG_003 [Aigis]]
S胤, me he recuperado completamente. Me[n]disculpo por preocuparlos a todos.

[msg MSG_004 [Makoto]]
Fue t雨... Modo Desenfreno, 夷verdad? Fue[n]sorprendente.

[sel SEL_005 top]
夷Qu姻 es el Modo Desenfreno?
Fue genial.
Quiero verte hacer eso otra vez.

[msg MSG_006 [Aigis]]
Es una funci吋n especial cargada en mi[n]sistema, especialmente para el combate[n]ofensivo.

[msg MSG_007 [Ryuji]]
斡Maldita sea, debes sentirte tan bien al[n]eliminar a los enemigos as胤!

[msg MSG_008 [P3 Fem Protag]]
ぬゆデ ろもまょま れゎれ もょぼよょわまょもまょろまれデ れもょ まゆほぺるむよテ[n]っまれらゎイれ ぽま ゎれぺるゅよデ ろよぽぺれ れゎれ みゎょぼもよょまれ れま[n]ぽまれぺぼろもわぺょ ろまゆらよるぺゅゆまょろま めぺれろぺ りゎま れま[n]るまぼゎらまるぺテ

[msg MSG_009 [Futaba]]
斡Wow! 斡Ser capaz de cambiar los[n]engranajes y transformarse as胤 es el[n]sue隠o de una mech-lover!

[msg MSG_010 [Aigis]]
Es una funci吋n especial cargada en mi[n]sistema, especialmente para el combate[n]ofensivo.

[msg MSG_011 [Ryuji]]
斡Maldita sea, debes sentirte tan bien al[n]eliminar a los enemigos as胤!

[msg MSG_012 [P3 Fem Protag]]
ぬゆデ ろもまょま れゎれ もょぼよょわまょもまょろまれデ れもょ まゆほぺるむよテ[n]っまれらゎイれ ぽま ゎれぺるゅよデ ろよぽぺれ れゎれ みゎょぼもよょまれ れま[n]ぽまれぺぼろもわぺょ ろまゆらよるぺゅゆまょろま めぺれろぺ りゎま れま[n]るまぼゎらまるぺテ

[msg MSG_013 [P3 Fem Protag]]
どぺデ ゃぺデ ぺゎょりゎま まれ ぼよゆらゅもぼぺぽよデ っまれらゎイれ ぽま[n]ゎれぺるゅよデ ろよぽぺれ れゎれ みゎょぼもよょまれ れま ぽまれぺぼろもわぺょ[n]ろまゆらよるぺゅゆまょろま めぺれろぺ りゎま れま るまぼゎらまるぺテ

[msg MSG_014 [Aigis]]
Es una funci吋n especial cargada en mi[n]sistema, especialmente para el combate[n]ofensivo.

[msg MSG_015 [Yusuke]]
Es un ataque arriesgado, una espada de[n]doble filo.

[msg MSG_016 [Ryuji]]
No puedes moverte por un tiempo, 夷eh?[n]Suena como la bater胤a de Oracle.

[msg MSG_017 [Yukiko]]
夷Eh? 夷Oracle necesita una bater胤a?

[msg MSG_018 [Yosuke]]
斡Oh, vamos, no hay manera de que est姻[n]hablando en serio!
...夷Verdad?

[msg MSG_019 [Futaba]]
No est茨 hablando de una bater胤a real. Se[n]refiere a que colapso cuando me canso[n]demasiado.

[msg MSG_020 [Ribbon]]
夷HAY ALGUNA POSIBILIDAD DE QUE TAMBI畏N[n]TENGA UN MODO DESENFRENO?

[msg MSG_021 [Naoto]]
No estoy segura... Basado en la[n]apariencia de su modelo, que no me[n]parece una funci吋n est茨ndar...

[msg MSG_022 [Ribbon]]
YA VEO... ESO ES ALGO DECEPCIONANTE.

[msg MSG_023 [Yukari]]
Espera, 夷es decepcionante para ti?[n]夷Tambi姻n quieres usar el Modo[n]Desenfreno, Ribbon?

[msg MSG_024 [Ribbon]]
NO ME INCITA A ADQUIRIRLO DE FORMA[n]PROACTIVA, PERO AL NO TENER FUNCIONES DE[n]BATALLA...
AL MENOS SER緯A DE UTILIDAD EN ESE[n]MOMENTO, SI PUDIERA USARLO... ESO PENS畏.

[msg MSG_025 [P3 Fem Protag]]
Ribbon... No sab胤a que pensabas esas[n]cosas.

[msg MSG_026 [Ken]]
Pero, si Ribbon tuviera su propio Modo[n]Desenfreno, 夷c吋mo crees que ser胤a?

[sel SEL_027 top]
Ella dispara un pu隠o cohete.
Ella dispara l茨seres de sus ojos.
Todo su cuerpo comienza a brillar.

[msg MSG_028 [Kanji]]
Eso suena bastante clich姻.

[msg MSG_029 [Junpei]]
斡No, es mucho m茨s emocionante que un[n]clich姻! 斡Los chicos sue隠an con un pu隠o[n]cohete!

[msg MSG_030 [Yukiko]]
Pero 夷no crees que solo un golpe[n]ser胤a... decepcionante?
斡Creo que ser胤a mejor si tambi姻n[n]proyectara luces, pusiera m雨sica y[n]empezar茨 a bailar!

[msg MSG_031 [Ryuji]]
S胤, eso suena como algo que har胤a un[n]robot, pero... 夷no son los l茨seres un[n]poco "infantiles"?

[msg MSG_032 [Akechi]]
夷T雨 crees? Yo creo que ser胤a muy[n]pr茨ctico en combate.

[msg MSG_033 [Yukiko]]
Mm... 夷Pero no ser胤a insuficiente?
斡Creo que ser胤a mejor si tambi姻n[n]proyectara luces, pusiera m雨sica y[n]empezar茨 a bailar!

[msg MSG_034 [Yukiko]]
Oh, eso ser胤a genial.
斡Pero ser胤a incluso mejor si tambi姻n[n]pusiera m雨sica y comenzara a bailar!

[msg MSG_035 [Yosuke]]
夷Por qu姻 tendr胤a que bailar? 夷Qu姻 crees[n]que est茨 haciendo, liderar un desfile?

[msg MSG_036 [Teddie]]
ィひも まれ ゎょ ぽまれみもゅまデ りゎもまるよ ゎょもるゆま ろぺゆほもイょ![n]ィのほわもぺゆまょろまデ をよ れまるウぺ ゅぺ ほまゅゅまんぺ よみもぼもぺゅデ[n]れよらゅぺょぽよ ほまれよれ を れぺゅゎぽぺょぽよ ぺ ゆもれ みぺょれ!

[msg MSG_037 [Yusuke]]
Mm... Entonces puedes dejarme el dise隠o[n]de la carroza.

[msg MSG_038 [Yukiko]]
Si necesitas una carroza, puedo ayudar[n]con el dise隠o.

[msg MSG_039 [Yosuke]]
Espera... 斡No necesitamos nada de eso!

[msg MSG_040 [Mitsuru]]
Oh, parece que esto se nos est茨 saliendo[n]de las manos... Deber胤amos irnos.

[msg MSG_041 [Ribbon]]
S緯, ENTIENDO. VAMOS.

