[msg MSG_000]
Dentro del conducto de ventilaciポn...

[msg MSG_001 [Ken]]
Esto es mucho mホs oscuro de lo que[n]pensaba. No puedo ver nada frente a[n]mボ...

[msg MSG_002 [P3 Hero]]
Pensar que nos escabullimos a trav〒s de[n]un diminuto conducto como este... Es una[n]experiencia muy extraワa.

[msg MSG_003 [P4 Hero]]
ムPuede ser un poco pretencioso para mボ,[n]pero esto realmente me hace sentir como[n]un ladrポn fantasma!

[sel SEL_004 top]
Esto es muy emocionante.
Esto no es tan comマn para nosotros.

[msg MSG_005 [Futaba]]
Vamos, siempre estホs haciendo este tipo[n]de cosas, Joker.

[msg MSG_006 [P3 Hero]]
メEn serio? Pens〒 que era normal para[n]ustedes.

[msg MSG_007 [Futaba]]
Sボ, lo hacemos todo el tiempo. En este[n]punto nos podrボamos llamar Maestros de[n]los Ductos.

[msg MSG_008 [Naoto]]
Lホstima que no podemos ver mucho...[n]Serボa de gran ayuda si tuvi〒ramos alguna[n]fuente de luz.

[msg MSG_009 [Ann]]
Una fuente de luz... メTienes alguna[n]idea, Joker?

[sel SEL_010 top]
Las gafas de Oracle..
メEn las funciones de Aigis?
Usa tu fuego, Panther.

[msg MSG_011 [Futaba]]
Solo tengo un par. Y, por desgracia,[n]estホn diseワadas especボficamente para[n]mボ...
Pero te avisar〒 si encuentro algo マtil.

[msg MSG_012 [Yukiko]]
Ooh, メTus ojos brillan como faros?

[msg MSG_013 [Aigis]]
Me disculpo... No tengo incorporada[n]ninguna funciポn de ese tipo.

[msg MSG_014 [Naoto]]
ムEspera, espera! ムNo debemos usar fuego[n]en un espacio tan estrecho como este!

[msg MSG_015 [Yukiko]]
メSu fuego serホ suficiente? Puedo ayudar[n]tambi〒n...

[msg MSG_016 [Aigis]]
No recomiendo usar fuego aquボ, hay altas[n]probabilidades de ser cocinados vivos en[n]este conducto.

[msg MSG_017 [Chie]]
Hrgh, es tan oscuro y aterrador... メYa[n]casi salimos? メPodemos acabar con esto?

[msg MSG_018 [Chie]]
ムAck! ムAlgo me tocポ la cara! ムAlgo[n]peludo!

[msg MSG_019 [Koromaru]]
ムArf, arf!

[msg MSG_020 [Chie]]
Oh, メFuiste tマ, Koro? *suspiro* Me[n]asustaste...

[msg MSG_021 [Ryuji]]
メEh? Pero pens〒 que Koromaru estaba[n]delante de mボ... メQu〒 es lo que me toca[n]la cara?...

[msg MSG_022 [Yusuke]]
Soy yo. Fox.

[msg MSG_023 [Ryuji]]
ムメWaaaaaagh?!

[msg MSG_024 [Kanji]]
ムOye, qu〒 estホ pasando ahボ arr―
―ムMmph?!

[msg MSG_025 [Morgana]]
ムメMew?!

[msg MSG_026 [Kanji]]
Su-Suave...
Un pelaje tan suave y esponjoso en mi[n]rostro... Estoy en el cielo...

[msg MSG_027 [Morgana]]
ムMrooowgh! ムP-para! ムDeja de frotar tu[n]rostro contra mボ!

[msg MSG_028 [Kanji]]
ムOye! ムNo me patees asボ!
Oh... Vaya, esas patas-almohadillas...[n]Intenta patearme de nuevo...

[msg MSG_029 [Morgana]]
ムBien, nos vamos de aquボ AHORA MISMO![n]ムMu〒vete! ムMu〒vete!

[msg MSG_030 [Akechi]]
Mona, por favor deja de clavar tus[n]garras en mis piernas... A-ムAh! ムAh!

[msg MSG_031 [Chie]]
ムOye, tambi〒n me molestas aquボ, sabes![n]ムLa nariz de tu mホscara me sigue[n]pinchando, Crow!

[msg MSG_032 [Koromaru]]
ムGuau!

[msg MSG_033 [Ribbon]]
ムKOROMARU-SAN, メQU※ PASA? メPOR QU※[n]EMPUJAS MI ESPALDA?

[msg MSG_034 [Koromaru]]
ムArf, arf!

[msg MSG_035 [Ribbon]]
メ"ES DIVERTIDO JUGAR CON TODOS"?
メESTE ES EL SENTIMIENTO... DE DIVERSIロN?

[msg MSG_036 [Koromaru]]
ムAwoooo!

[msg MSG_037 [Ribbon]]
メME ESTミS DANDO UN EMPUJロN? メPARA QUE[n]PODAMOS SEGUIR AVANZANDO JUNTOS?

[msg MSG_038 [Koromaru]]
ムAwoooo!

[msg MSG_039 [Ribbon]]
KOROMARU... MUCHAS GRACIAS.

[msg MSG_040 [Junpei]]
Vamos, メqu〒 pasa Yosuke? メNo puedes ir[n]un poco mホs rホpido?

[msg MSG_041 [Yosuke]]
No te quejes conmigo. ムEsto es por[n]Teddie!

[msg MSG_042 [Yosuke]]
ムTeddie, eres demasiado grande para este[n]conducto! ムメPor qu〒 no te quitaste el[n]disfraz antes de entrar?!

[msg MSG_043 [Teddie]]
Estホ bien. Puedo ir mホs rapido si me[n]empujas, Yosuke.

[msg MSG_044 [Yosuke]]
メQu〒 eres, carne molida en una mホquina[n]de salchichas? ムDeja de ser perezoso y[n]mueve tu propio cuerpo!

[msg MSG_045 [Makoto]]
Uf... メVamos bastante lento, pero[n]supongo que todavボa progresamos?

[msg MSG_046 [Shinjiro]]
Estoy seguro de que saldremos[n]eventualmente, pero en serio... esta[n]cosa estホ demasiado apretada.

[msg MSG_047 [Akihiko]]
Arrastrarse es un buen entrenamiento.[n]Fortalece los abdominales y los mマsculos[n]dorsales para que puedas...

[msg MSG_048 [Shinjiro]]
Cホllate. ムUsa esos mマsculos y sigue[n]movi〒ndote!

[msg MSG_049 [Akihiko]]
メQu〒? Estoy aprovechando para decir algo[n]positivo en lugar de perder mi tiempo en[n]quejarme de estar atascado…

[msg MSG_050 [Mitsuru]]
メPodrボan callarse los dos? ムSi siguen[n]los congelar〒 a amb...
ムメQu〒...?!

[msg MSG_051 [Haru]]
Oh, lo siento, Mitsuru. Mi mano se[n]enganchポ en tu falda.

[msg MSG_052 [Mitsuru]]
Y-ya veo... Por favor, no me asustes[n]asボ. Es difボcil ver aquボ dentro.

[msg MSG_053 [Junpei]]
Oh, メQu〒? メMitsuru no es fan de la[n]oscuridad?
Bueno, es una debilidad sorprendente para[n]ella. Una revelaciポn impresionante que hace a[n]alguien como ella mホs adorable…

[msg MSG_054 [Mitsuru]]
Iori, メquieres que te congele a ti[n]tambi〒n?

[msg MSG_055 [Junpei]]
ムE-era broma! ムSolo estaba bromeando!

[msg MSG_056 [Yukari]]
Mm, メpodrボan darse prisa? Hemos estado[n]esperando aquボ atrホs por un buen rato.

[msg MSG_057 [P3 Fem Protag]]
*risa*

[msg MSG_058 [Yukari]]
メEh? メQu〒 es gracioso?

[msg MSG_059 [P3 Fem Protag]]
Es solo que ustedes actマan exactamente[n]como mis compaワeros.

[msg MSG_060 [Yukari]]
Mm, Ya veo...

[msg MSG_061 [P3 Fem Protag]]
Disculpa por mencionar algo tan extraワo.[n]ムVamos, sigamos adelante!

