[msg MSG_000 [Chica Bien Vestida]]
Iori, se dirige hacia ti. 斡Mantente en[n]guardia!

[msg MSG_001 [Chico Con Gorra De B姻isbol]]
Je, je, je, 斡no hay forma de que algo[n]como esto me derribe!

[msg MSG_002 [Chico Con Gorro]]
Oye, no es momento de bromear. 斡Estos[n]bastardos no nos dejan en paz!

[msg MSG_003 [Chica Animada]]
斡夷No pueden rendirse de una vez?![n]夷Cu茨ndo acabar茨 esto?

[msg MSG_004 [Chica Tranquila]]
...斡Es in雨til! 斡Vienen refuerzos!

[msg MSG_005 [Robot Producido En Masa]]
ELIMINAR ENTIDADES DESCONOCIDAS.[n]斡ELIMINAR IRREGULARIDADES!

[msg MSG_006 [Chico Agresivo]]
Tch... 斡No vamos a ir a ninguna parte[n]as胤!

[msg MSG_007 [Robot Producido En Masa]]
ELIMINAR ENTIDADES DESCONOCIDAS.[n]斡ELIMINAR IRREGULARIDADES!

[msg MSG_008 [Ni隠o Sombr胤o]]
*jadeo* *jadeo* 斡No vamos a perder aqu胤!

[msg MSG_009 [Chica Tranquila]]
Ken est茨 en peligro, 斡su salud es baja!

[msg MSG_010 [Chico Agresivo]]
斡Ngh..! Esto no se ve bien. Nos superan[n]en n雨mero...

[msg MSG_011 [Perro]]
斡Arf, Arf!

[msg MSG_012 [P3 Fem Protag]]
斡Chicos!

[msg MSG_013 [Chica Bien Vestida]]
斡夷Qui姻n est茨 ah胤?!

[msg MSG_014 [P4 Hero]]
Guardemos la reuni吋n para despu姻s,[n]斡ellos necesitan nuestra ayuda!

