[msg MSG_000 [Morgana]]
Eh, ムメQu〒 paso?!

[msg MSG_001 [Nagi]]
ムHikari fue secuestrada por Doe!

[msg MSG_002 [Futaba]]
ムメSecuestrada?! ムメD-de qu〒 estホs[n]hablando?!

[msg MSG_003 [Fuuka]]
Hikari estaba viendo el final de la[n]pelボcula con nosotros.

[msg MSG_004 [Rise]]
Entonces, Doe escupiポ la tercera llave.
Fuuka fue a recogerla, y yo estaba[n]tratando de contactar con ustedes.

[msg MSG_005 [Fuuka]]
Desviamos la mirada un momento... ムy Doe[n]se llevポ a Hikari!

[msg MSG_006 [Ryuji]]
Maldiciポn... ムEse esponjoso saco de[n]mierda!

[msg MSG_007 [Nagi]]
Me disculpo profundamente. Sucediポ[n]cuando me habボa alejado para abordar[n]otro asunto...
Busqu〒 por todas partes despu〒s de[n]escuchar lo que pasポ, pero no pude[n]encontrarla...

[msg MSG_008 [Naoto]]
Pensar que Doe harボa tal cosa... Bajamos[n]la guardia.
Y encima, la identidad de Doe sigue[n]siendo un misterio...

[sel SEL_009 top]
Debe ser el enemigo.
Es el acosador de Hikari.
Es una mascota malvada.

[msg MSG_010 [Akechi]]
Si Hikari fue secuestrada, entonces[n]podrボa ser el caso...
Pero ninguno de nosotros percibiポ[n]malicia de su parte, y eso es extraワo.

[msg MSG_011 [Yukiko]]
Ahora que lo pienso, estuvo mirando a[n]Hikari demasiado, y...
Ese tipo de mirada no es normal en[n]absoluto.

[msg MSG_012 [Akechi]]
Cierto, parecボa tener algマn tipo de[n]fijaciポn con ella.

[msg MSG_013 [Teddie]]
Si quiere ser una mascota, tiene que ser[n]adorablemente travieso como yo, no un...[n]ムUn rufiホn!
ムFue descalificado como mascota en el[n]momento en que secuestrポ a Hikarin!

[msg MSG_014 [Futaba]]
Pero... yo... hice lo mejor que pude...
ムメP-por qu〒?! ムLa pelボcula habボa[n]resultado ser tan bonita!

[msg MSG_015 [Aigis]]
Futaba...

[msg MSG_016 [Futaba]]
ムTodo lo que querボa era mostrarle a[n]Hikari su mensaje!
Una que demuestra que su individualidad[n]no es mala... ムQue en realidad es algo[n]bueno!

[msg MSG_017 [Yusuke]]
Futaba... Puedo entender cポmo te[n]sientes, pero deberボas tratar de[n]calmarte.

[msg MSG_018 [P4 Hero]]
Tiene razポn. Es aterrador, pero[n]necesitamos mantener la calma ahora.

[msg MSG_019 [Rise]]
Um, tengo que darles esto...

[msg MSG_020 [Akechi]]
La llave de la tercera cerradura...[n]Vamos a trabajar en nuestra ruta de[n]escape.

[msg MSG_021 [Ryuji]]
Pero... メVamos a dejar Hikari y a Doe?

[msg MSG_022 [Akechi]]
Bueno, tenemos un grupo bastante grande.[n]メPor qu〒 no nos asignamos diferentes[n]tareas?

[msg MSG_023 [Shinjiro]]
...Tiene razポn. Correr todos juntos no[n]nos harホ mucho bien.

[msg MSG_024 [Chie]]
De acuerdo, ムVamos a buscar a Hikari!
メPueden tマ y tus amigos ir y abrir la[n]cerradura, [f 6 1 30 0 0 0]?

[sel SEL_025 top]
Bien.
No me siento bien...

[msg MSG_026 [Ann]]
ムOye! ムNo te quejes!

[msg MSG_027 [Akihiko]]
Iremos a buscar alrededor del cine.[n]Buena suerte con la cerradura.

[msg MSG_028 [P4 Hero]]
De acuerdo, nos vemos aquボ dentro de un[n]rato.

[msg MSG_029 [Morgana]]
Vamos, [f 6 1 30 0 0 0] tenemos que ver esas[n]cerraduras.

