[msg MSG_000 [Ken]]
斡S胤! 斡Los derribamos a todos!

[msg MSG_001 [Koromaru]]
斡Awoooo!

[msg MSG_002 [Rise]]
夷Y ese robot? 夷Est茨 bien?

[msg MSG_003 [Robot Con List吋n]]
...

[msg MSG_004 [Futaba]]
Oye, 夷est茨s bien? Creo que llegamos a[n]tiempo...

[msg MSG_005 [Robot Con List吋n]]
夷QUI畏N ERES?
NO PED緯 AYUDA.

[msg MSG_006 [Yukari]]
夷Eh?

[msg MSG_007 [Robot Con List吋n]]
DEB緯 SER FORMATEADA DE ACUERDO CON EL[n]PROCEDIMIENTO GENERAL.

[msg MSG_008 [Futaba]]
夷Por qu姻 dices eso? 斡Ser formateada es[n]b茨sicamente lo mismo que morir!

[msg MSG_009 [Robot Con List吋n]]
SOY DIFERENTE DE LAS OTRAS UNIDADES. MIS[n]PROCESOS DE PENSAMIENTO SE HAN VUELTO[n]ANORMALES.
SOY UNA IRREGULARIDAD, LLENO DE ERRORES.[n]ME HE CONVERTIDO EN UNA UNIDAD[n]DEFECTUOSA.

[msg MSG_010 [Ryuji]]
夷Defectuosa? Todo lo que hiciste fue[n]darte cuenta de que te gustan las[n]flores, 夷verdad?

[msg MSG_011 [Robot Con List吋n]]
夷C遺MO SABES ESO?

[msg MSG_012 [Ryuji]]
No quiero explicarlo todo ahora mismo,[n]pero... te vimos en un tr茨iler.

[msg MSG_013 [Robot Con List吋n]]
夷TR威ILER?

[msg MSG_014 [Futaba]]
De todos modos, 斡no necesitas ser[n]formateada!
Deja de llamarte una irregularidad solo[n]porque hay algo diferente en ti.

[msg MSG_015 [Robot Con List吋n]]
PERO ESO ES LO QUE EL SUPERVISOR HA[n]ORDENADO. MI 郁NICO PROP遺SITO COMO UNIDAD[n]ES OBEDECERLE.

[sel SEL_016 top]
No tienes por qu姻 obedecerlo.
夷Qui姻n es el Supervisor?

[msg MSG_017 [Robot Con List吋n]]
夷POR QU畏?

[msg MSG_018 [Haru]]
ひも れよゅよ れもむゎもまるぺれ ゅぺれ カるぽまょまれ ぽま ゅよれ ぽまゆァれ[n]ろよぽぺ ろゎ わもぽぺデ ょよ めぺほるウぺ ゎょ れもむょもみもぼぺぽよ[n]らまるれよょぺゅ らぺるぺ まゑもれろもるデ エわまるぽぺぽ?

[msg MSG_019 [Robot Con List吋n]]
夷UN SIGNIFICADO PERSONAL PARA MI[n]EXISTENCIA?

[msg MSG_020 [Robot Con List吋n]]
AQUEL QUE NOS GU緯A HACIA LO QUE DEBEMOS[n]SER... ESO ES LO QUE DETERMINA MI[n]SIGNIFICADO DE EXISTIR.

[msg MSG_021 [Futaba]]
Tiene un control total sobre todos. 斡Nos[n]encargaremos de todo este sinsentido!

[msg MSG_022 [Robot Con List吋n]]
...

[msg MSG_023 [Mitsuru]]
Disculpa, 夷conoces a una robot llamada[n]Aigis? Se parece mucho a ti.

[msg MSG_024 [Yukari]]
Tambi姻n, un chico con una banda en el[n]brazo... tiene un flequillo largo que le[n]tapa uno de los ojos...

[msg MSG_025 [Robot Con List吋n]]
NO, NO HE VISTO A NING郁N HUMANO.

[msg MSG_026 [Yukari]]
Ya...

[msg MSG_027 [Robot Con List吋n]]
SIN EMBARGO, VI UN ROBOT CON UNA CINTA.[n]ERA DEL MISMO COLOR QUE LA M緯A.

[msg MSG_028 [Junpei]]
斡Esa tiene que ser Aigis!

[msg MSG_029 [Mitsuru]]
夷Sabes por casualidad a d吋nde fue ese[n]robot?

[msg MSG_030 [Robot Con List吋n]]
FUE CONSIDERADA UNA AMENAZA DE SEGURIDAD[n]Y LLEVADA AL LABORATORIO QUE EST威 M威S[n]ADELANTE.

[msg MSG_031 [Akihiko]]
斡夷Qu姻?!

[msg MSG_032 [Shinjiro]]
Tch... Estar茨 en serios problemas si no[n]nos apuramos hacia ese laboratorio.

[msg MSG_033 [Mitsuru]]
De acuerdo, mov茨monos de inmediato.

[msg MSG_034 [Futaba]]
斡Espera! 夷Qu姻 vamos a hacer con este[n]robot?

[sel SEL_035 top]
Llev姻mosla con nosotros.
Escond茨mosla en un lugar seguro.

[msg MSG_036 [Futaba]]
S胤, seguro que ser茨 雨til. 斡Oh, tal vez[n]ella pueda guiarnos hasta el[n]laboratorio!

[msg MSG_037 [Teddie]]
斡Es una excelente idea! Si algo le[n]sucede a esta preciosa robot, 斡yo la[n]proteger姻!

[msg MSG_038 [Fuuka]]
Eso suena como una buena idea. Si se[n]queda aqu胤, es probable que m茨s robots[n]aparezcan y la capturen.
Pero no puedo encontrar ning雨n lugar[n]cercano que seguro para ella...

[msg MSG_039 [Teddie]]
Entonces, 夷por qu姻 no servimos como su[n]escolta? Si algo le sucede a esta[n]preciosa robot, 斡yo la proteger姻!

[msg MSG_040 [Futaba]]
S胤, seguro que ser茨 雨til. 斡Quiz茨 pueda[n]guiarnos al laboratorio!

[msg MSG_041 [Robot Con List吋n]]
NO HE SIDO DESIGNADO COMO UNA GU緯A.

[msg MSG_042 [Yukari]]
Pero sabes d吋nde est茨 el laboratorio,[n]夷verdad? Todo lo que tendr胤as que hacer[n]es llevarnos all胤.

[msg MSG_043 [Robot Con List吋n]]
PERO, REALIZAR ACCIONES FUERA DE[n]NUESTROS PAR威METROS ESTABLECIDOS ES...

[msg MSG_044 [Ryuji]]
Bueno, no quieres ser formateada,[n]夷verdad?

[msg MSG_045 [Robot Con List吋n]]
夷...?

[msg MSG_046 [Ryuji]]
びま まれろよを らるまむゎょろぺょぽよ れも りゎもまるまれ れまる まゅもゆもょぺぽぺデ[n]よ れも れもゆらゅまゆまょろま まれろァれ れもむゎもまょぽよ まれよ らよるりゎま[n]ぺゅむゎもまょ ゆァれ ろま ゅよ よるぽまょよテ

[msg MSG_047 [Robot Con List吋n]]
夷SI QUIERO?
NO ENTIENDO. 夷POR QU畏 QUIERES[n]PROTEGERME?

[msg MSG_048 [P3 Fem Protag]]
Bueno, te pareces a Aigis... y ella es[n]nuestra compa隠era.
Pero supongo que... queremos que valores[n]tu capacidad de decidir.

[msg MSG_049 [Robot Con List吋n]]
夷DEBO VALORAR ESTA HABILIDAD?
夷POR QU畏?
夷POR QU畏... POR QU畏... QUIERO APRECIAR[n]LAS FLORES?
Y ESTE DESEO DE SABER POR QU畏... 夷ES[n]TAMBI畏N UN SENTIMIENTO?

[msg MSG_050 [Haru]]
夷Por qu姻 no vienes con nosotros al[n]laboratorio? Puede que encuentres las[n]respuestas all胤.

[msg MSG_051 [Akihiko]]
Suena como tu mejor opci吋n. A este paso,[n]vas a terminar siendo formateada,[n]夷verdad?
As胤 que, deber胤as dejar que tus[n]sentimientos te gu胤en ahora.

[msg MSG_052 [Robot Con List吋n]]
...
MUY BIEN... IR畏 CONTIGO. QUIERO CONOCER[n]ESTA SENSACI遺N DE QUERER SABER POR QU畏.

[msg MSG_053 [P3 Fem Protag]]
斡Eso lo decide!

[msg MSG_054 [Futaba]]
斡No te preocupes! Si sufres alguna falla[n]en el camino, te desarmar姻 y...

[msg MSG_055 [Naoto]]
斡夷Har茨s qu姻?!

[msg MSG_056 [Futaba]]
斡Je, je, je, ups! Mi error. Lo que quise[n]decir fue que... 斡Todo estar茨 bien y si[n]nada puede salir mal sale mal!

[msg MSG_057 [Morgana]]
Bueno, encontramos al robot que parece[n]ser la clave de esta pel胤cula. Una cosa[n]menos en la lista.

[msg MSG_058 [P4 Hero]]
Nuestro pr吋ximo paso es encontrar los[n]miembros restantes de SEES.
斡Vamos!

