[msg MSG_000 [Ken]]
ムSボ! ムLos derribamos a todos!

[msg MSG_001 [Koromaru]]
ムAwoooo!

[msg MSG_002 [Rise]]
メY ese robot? メEstホ bien?

[msg MSG_003 [Robot Con Listポn]]
...

[msg MSG_004 [Futaba]]
Oye, メestホs bien? Creo que llegamos a[n]tiempo...

[msg MSG_005 [Robot Con Listポn]]
メQUI※N ERES?
NO PEDレ AYUDA.

[msg MSG_006 [Yukari]]
メEh?

[msg MSG_007 [Robot Con Listポn]]
DEBレ SER FORMATEADA DE ACUERDO CON EL[n]PROCEDIMIENTO GENERAL.

[msg MSG_008 [Futaba]]
メPor qu〒 dices eso? ムSer formateada es[n]bホsicamente lo mismo que morir!

[msg MSG_009 [Robot Con Listポn]]
SOY DIFERENTE DE LAS OTRAS UNIDADES. MIS[n]PROCESOS DE PENSAMIENTO SE HAN VUELTO[n]ANORMALES.
SOY UNA IRREGULARIDAD, LLENO DE ERRORES.[n]ME HE CONVERTIDO EN UNA UNIDAD[n]DEFECTUOSA.

[msg MSG_010 [Ryuji]]
メDefectuosa? Todo lo que hiciste fue[n]darte cuenta de que te gustan las[n]flores, メverdad?

[msg MSG_011 [Robot Con Listポn]]
メCロMO SABES ESO?

[msg MSG_012 [Ryuji]]
No quiero explicarlo todo ahora mismo,[n]pero... te vimos en un trホiler.

[msg MSG_013 [Robot Con Listポn]]
メTRミILER?

[msg MSG_014 [Futaba]]
De todos modos, ムno necesitas ser[n]formateada!
Deja de llamarte una irregularidad solo[n]porque hay algo diferente en ti.

[msg MSG_015 [Robot Con Listポn]]
PERO ESO ES LO QUE EL SUPERVISOR HA[n]ORDENADO. MI ヮNICO PROPロSITO COMO UNIDAD[n]ES OBEDECERLE.

[sel SEL_016 top]
No tienes por qu〒 obedecerlo.
メQui〒n es el Supervisor?

[msg MSG_017 [Robot Con Listポn]]
メPOR QU※?

[msg MSG_018 [Haru]]
Si solo siguieras las ポrdenes de los demホs[n]toda tu vida, no habrボa un significado[n]personal para existir, メverdad?

[msg MSG_019 [Robot Con Listポn]]
メUN SIGNIFICADO PERSONAL PARA MI[n]EXISTENCIA?

[msg MSG_020 [Robot Con Listポn]]
AQUEL QUE NOS GUレA HACIA LO QUE DEBEMOS[n]SER... ESO ES LO QUE DETERMINA MI[n]SIGNIFICADO DE EXISTIR.

[msg MSG_021 [Futaba]]
Tiene un control total sobre todos. ムNos[n]encargaremos de todo este sinsentido!

[msg MSG_022 [Robot Con Listポn]]
...

[msg MSG_023 [Mitsuru]]
Disculpa, メconoces a una robot llamada[n]Aigis? Se parece mucho a ti.

[msg MSG_024 [Yukari]]
Tambi〒n, un chico con una banda en el[n]brazo... tiene un flequillo largo que le[n]tapa uno de los ojos...

[msg MSG_025 [Robot Con Listポn]]
NO, NO HE VISTO A NINGヮN HUMANO.

[msg MSG_026 [Yukari]]
Ya...

[msg MSG_027 [Robot Con Listポn]]
SIN EMBARGO, VI UN ROBOT CON UN LISTロN.[n]ERA DEL MISMO COLOR QUE EL MレO.

[msg MSG_028 [Junpei]]
ムEsa tiene que ser Aigis!

[msg MSG_029 [Mitsuru]]
メSabes por casualidad a dポnde fue ese[n]robot?

[msg MSG_030 [Robot Con Listポn]]
FUE CONSIDERADA UNA AMENAZA DE SEGURIDAD[n]Y LLEVADA AL LABORATORIO QUE ESTミ MミS[n]ADELANTE.

[msg MSG_031 [Akihiko]]
ムメQu〒?!

[msg MSG_032 [Shinjiro]]
Tch... Estarホ en serios problemas si no[n]nos apuramos hacia ese laboratorio.

[msg MSG_033 [Mitsuru]]
De acuerdo, movホmonos de inmediato.

[msg MSG_034 [Futaba]]
ムEspera! メQu〒 vamos a hacer con este[n]robot?

[sel SEL_035 top]
Llev〒mosla con nosotros.
Escondホmosla en un lugar seguro.

[msg MSG_036 [Futaba]]
Sボ, seguro que serホ マtil. ムOh, tal vez[n]ella pueda guiarnos hasta el[n]laboratorio!

[msg MSG_037 [Teddie]]
ムEs una excelente idea! Si algo le[n]sucede a esta preciosa robot, ムyo la[n]proteger〒!

[msg MSG_038 [Fuuka]]
Eso suena como una buena idea. Si se[n]queda aquボ, es probable que mホs robots[n]aparezcan y la capturen.
Pero no puedo encontrar ningマn lugar[n]cercano que seguro para ella...

[msg MSG_039 [Teddie]]
Entonces, メpor qu〒 no servimos como su[n]escolta? Si algo le sucede a esta[n]preciosa robot, ムyo la proteger〒!

[msg MSG_040 [Futaba]]
Sボ, seguro que serホ マtil. ムQuizホ pueda[n]guiarnos al laboratorio!

[msg MSG_041 [Robot Con Listポn]]
NO HE SIDO DESIGNADO COMO UNA GUレA.

[msg MSG_042 [Yukari]]
Pero sabes dポnde estホ el laboratorio,[n]メverdad? Todo lo que tendrボas que hacer[n]es llevarnos allボ.

[msg MSG_043 [Robot Con Listポn]]
PERO, REALIZAR ACCIONES FUERA DE[n]NUESTROS PARミMETROS ESTABLECIDOS ES...

[msg MSG_044 [Ryuji]]
Bueno, no quieres ser formateada,[n]メverdad?

[msg MSG_045 [Robot Con Listポn]]
メ...?

[msg MSG_046 [Ryuji]]
Te estoy preguntando si quieres ser eliminada,[n]o si simplemente estホs siguiendo eso porque[n]alguien mホs te lo ordeno.

[msg MSG_047 [Robot Con Listポn]]
メSI QUIERO?
NO ENTIENDO. メPOR QU※ QUIERES[n]PROTEGERME?

[msg MSG_048 [P3 Fem Protag]]
Bueno, te pareces a Aigis... y ella es[n]nuestra compaワera.
Pero supongo que... queremos que valores[n]tu capacidad de decidir.

[msg MSG_049 [Robot Con Listポn]]
メDEBO VALORAR ESTA HABILIDAD?
メPOR QU※?
メPOR QU※... POR QU※... QUIERO APRECIAR[n]LAS FLORES?
Y ESTE DESEO DE SABER POR QU※... メES[n]TAMBI※N UN SENTIMIENTO?

[msg MSG_050 [Haru]]
メPor qu〒 no vienes con nosotros al[n]laboratorio? Puede que encuentres las[n]respuestas allボ.

[msg MSG_051 [Akihiko]]
Suena como tu mejor opciポn. A este paso,[n]vas a terminar siendo formateada,[n]メverdad?
Asボ que, deberボas dejar que tus[n]sentimientos te guボen ahora.

[msg MSG_052 [Robot Con Listポn]]
...
MUY BIEN... IR※ CONTIGO. QUIERO CONOCER[n]ESTA SENSACIロN DE QUERER SABER POR QU※.

[msg MSG_053 [P3 Fem Protag]]
ムEso lo decide!

[msg MSG_054 [Futaba]]
ムNo te preocupes! Si sufres alguna falla[n]en el camino, te desarmar〒 y...

[msg MSG_055 [Naoto]]
ムメHarホs qu〒?!

[msg MSG_056 [Futaba]]
ムJe, je, je, ups! Mi error. Lo que quise[n]decir fue que... ムTodo estarホ bien y si[n]nada puede salir mal sale mal!

[msg MSG_057 [Morgana]]
Bueno, encontramos al robot que parece[n]ser la clave de esta pelボcula. Una cosa[n]menos en la lista.

[msg MSG_058 [P4 Hero]]
Nuestro prポximo paso es encontrar los[n]miembros restantes de SEES.
ムVamos!

