[msg chara_000]
[f 0 5 65278][f 2 1]Blank[n][e]

[msg chara_001]
[f 0 5 65278][f 2 1](Front Row)Siempre listo para una pelea,[n]es mejor con ataques de Corte y[n]El姻ctricos.[n][e]

[msg chara_002]
[f 0 5 65278][f 2 1](Front Row)Un luchador vers茨til, h茨bil[n]en todas las afinidades.[n][e]

[msg chara_003]
[f 0 5 65278][f 2 1](Front Row)Un luchador 茨gil que se[n]especializa en ataques de Corte y Viento.[n][e]

[msg chara_004]
[f 0 5 65278][f 2 1](Front Row)Una chica experta en kung fu[n]con alta evasi吋n y ataques cr胤ticos.[n][e]

[msg chara_005]
[f 0 5 65278][f 2 1](Back Row)Correcta, apropiada y mortal,[n]斡pero cuidado con su salud![n][e]

[msg chara_006]
[f 0 5 65278][f 2 1]None[n][e]

[msg chara_007]
[f 0 5 65278][f 2 1](Front Row)Protege a sus compa隠eros con[n]una alta defensa y ofensa.[n][e]

[msg chara_008]
[f 0 5 65278][f 2 1](Back Row)Un detective de peque隠o,[n]excelente en habilidades de enlace.[n][e]

[msg chara_009]
[f 0 5 65278][f 2 1](Front Row)Una autodenominada mascota[n]que ayuda al grupo en combate.[n][e]

[msg chara_00A]
[f 0 5 65278][f 2 1](Back Row)Una chica de mal humor que[n]sobresale en habilidades de Viento y[n]recuperaci吋n.[n][e]

[msg chara_00B]
[f 0 5 65278][f 2 1](Front Row)Un presumido con habilidades[n]equilibradas de ataque, defensa y[n]contraataque.[n][e]

[msg chara_00C]
[f 0 5 65278][f 2 1](Front Row)Un boxeador incomparable que[n]inflige un da隠o extremo.[n][e]

[msg chara_00D]
[f 0 5 65278][f 2 1](Front or Back)Sella las habilidades de[n]los enemigos y los derrota con magia[n]de Hielo.[n][e]

[msg chara_00E]
[f 0 5 65278][f 2 1]None[n][e]

[msg chara_00F]
[f 0 5 65278][f 2 1](Front or Back)Arma anti-sombras que[n]puede activar su Modo Desenfreno.[n][e]

[msg chara_010]
[f 0 5 65278][f 2 1](Back Row)Es genial con habilidades[n]f胤sicas y de Electricidad, 斡pero tiene[n]poca salud![n][e]

[msg chara_011]
[f 0 5 65278][f 2 1](Back Row)R茨pido y maneja magia de Fuego[n]y Oscuridad, 斡pero no es duradero![n][e]

[msg chara_012]
[f 0 5 65278][f 2 1](Front Row)El tipo m茨s duro del lugar,[n]pero extremadamente vulnerable a la[n]magia.[n][e]

[msg chara_013]
[f 0 5 65278][f 2 1](Back Row)Zen ataca, mientras que Rei[n]cura. Ambos utilizan habilidades[n]misteriosas...[n][e]

[msg chara_014]
[f 0 5 65278][f 2 1](Back Row)Zen ha recuperado sus recuerdos[n]y sus habilidades...[n][e]

