[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]All attacks have an [f 0 1 2]affinity[f 0 1 0], and both allies[n]and enemies may be [f 0 1 2]weak against them[f 0 1 0].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1][f 0 1 2]Learn an enemy's weakness[f 0 1 0] by using[n]attacks with different affinities.[n][f 1 1][e]

[msg BTL_TUTORIAL_mes03]
[f 0 5 65278][f 2 1][n]After you find the type of affinity that a [n]Shadow is weak to, a reminder will appear[n]above its head whenever you are about to[n]attack with that affinity. Use this to your[n]advantage to deal lots of damage, among[n]other extra [f 0 1 2]benefits[f 0 1 0]![n][f 1 1][e]

