[msg MSG_000]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Inside the air duct...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16039][f 6 1 9 0 0 1][f 6 1 2 0 0 10]I-It's much darker in here than I thought.[n]I can't see anything in front of me at all...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 0][f 6 1 9 0 0 1]To think we'd sneak through a tiny duct[n]like this... This is a pretty rare[n]experience.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 9 0 0 1]It may be a bit presumptuous of me,[n]but this really makes me feel like we're[n]phantom thieves![n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1]This is pretty exhilarating.[e]
[f 0 5 65278][f 2 1]This isn't all that common for us.[e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26142][f 6 1 9 0 0 1]C'mon, you're always doing this kinda[n]stuff, Joker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2018][f 6 1 9 0 0 1][f 6 1 2 0 0 4]Is that so? I thought this was your usual[n]kind of thing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Yeah, we do this all the time. It's to the[n]point that we could be called Duct[n]Masters.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8013][f 6 1 9 0 0 1]It truly is pitch black in this duct,[n]though... It'd be a big help if we[n]had some kind of light source.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22013][f 6 1 9 0 0 1][f 6 1 2 0 0 4]Hmm, some kind of light source...[n]Got any bright ideas, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1]Oracle's goggles.[e]
[f 0 5 65278][f 2 1]What about Aigis' functions?[e]
[f 0 5 65278][f 2 1]Use your fire, Panther.[e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26018][f 6 1 9 0 0 1]I only have the one pair. And,[n]unfortunately, they're designed[n]specifically for me...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]But I'll let you know if I find anything[n]useful.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5018][f 6 1 9 0 0 1]Ooh, do your eyes shine like headlights?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 3]I apologize―I lack any form of headlight[n]function.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Naoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8054][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Wait, wait, wait! We can't use fire in[n]an enclosed space like this![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Will her fire be enough, though? I can[n]help out if you need it...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]I do not recommend using fire here―[n]we are guaranteed to be cooked alive[n]within this air duct.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 3]Hrgh, it's so dark and scary... Are we[n]near the exit yet? Can we just get this[n]over with?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4103][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Ack! S-Something touched my face![n]It was all hairy![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17002][f 6 1 9 0 0 1]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4097][f 6 1 9 0 0 1]Oh, that was you, Koro-chan?[n]*sigh* That scared me...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 21018][f 6 1 9 0 0 1][f 6 1 2 0 0 4]Huh? But, I thought Koromaru was[n]in front of me―there's somethin' fluffy[n]touchin' my face...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24029][f 6 1 9 0 0 1]That's me. Fox.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 21103][f 6 1 9 0 0 1][f 6 1 2 0 0 0]Waaaaaagh!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7027][f 6 1 9 0 0 1]Hey, what's going on up th―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7099][f 6 1 9 0 0 1][f 6 1 2 0 0 0]―Mmph!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23104][f 6 1 9 0 0 1][f 6 1 2 0 0 0]Mew!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7098][f 6 1 9 0 0 1]Wh-Whoaa... So soft...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7137][f 6 1 9 0 0 1][f 6 1 2 0 0 8]Such soft, fluffy fur on my face...[n]I'm in heaven...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23105][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 6]Mrooowgh! Stop it! Quit rubbing your[n]face on my butt![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7099][f 6 1 9 0 0 1]Ow! Don't kick me like that![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7102][f 6 1 9 0 0 1][f 6 1 2 0 0 8]Oh... But damn, those paw pads...[n]Try kickin' me again...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23104][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Okay, we're getting out of here RIGHT[n]NOW!!! Move it! Move it![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28009][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Mona, please stop digging your claws[n]into my legs―O-Ow... Oww![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4054][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Hey, I'm hurtin' up here too, y'know![n]The nose on your mask keeps pokin' me,[n]Crow![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17001][f 6 1 9 0 0 1]Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35012][f 6 1 9 0 0 1][f 6 1 2 0 0 4]KOROMARU-SAN, WHAT IS THE[n]MATTER? WHY ARE YOU NUDGING[n]MY BACK?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17002][f 6 1 9 0 0 1][f 6 1 2 0 0 7]Arf, arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35014][f 6 1 9 0 0 1]"IT'S FUN PLAYING WITH EVERYONE"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]THIS IS THE FEELING... OF FUN?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17014][f 6 1 9 0 0 1]Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]ARE YOU GIVING ME A HELPING PUSH?[n]SO THAT WE MAY KEEP GOING[n]TOGETHER?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17014][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35025][f 6 1 9 0 0 1][f 6 1 2 0 0 7]KOROMARU-SAN... THANK YOU[n]SO MUCH.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]C'mon, what's with the holdup?[n]Yosuke, can't you go a bit faster?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Don't complain to me. The stoppage[n]is all thanks to Teddie up here![n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3034][f 6 1 9 0 0 1][f 6 1 2 0 0 0]Hey, Teddie, obviously you're too big[n]for this duct! Why didn't you take your[n]costume off before getting in!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Teddie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9031][f 6 1 9 0 0 1]It's okay. I can keep going if you push[n]me from behind, Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3059][f 6 1 9 0 0 1][f 6 1 2 0 0 6]What are you, ground meat in a sausage[n]machine!? Quit being lazy and move[n]your own body![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Makoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Whew... This is going rather slowly,[n]but I suppose we're still making[n]progress?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Shinjiro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]I'm sure we'll reach the exit eventually[n]But seriously... this thing is too cramped.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Akihiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Crawling is a good form of training.[n]Tightens up your abs and latissimus[n]dorsi muscles so you can―[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Shinjiro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18036][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Oh, shut up. Put those muscles to use[n]and just keep moving![n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Akihiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12034][f 6 1 9 0 0 1][f 6 1 2 0 0 2]What? I'm just using this opportunity[n]instead of wasting my time complaining[n]about being cramped―[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13034][f 6 1 9 0 0 1]Will you two quiet down!? Keep it up[n]and I'll freeze you both soli―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13104][f 6 1 9 0 0 1][f 6 1 2 0 0 0]Whaa―!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Haru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Oh―pardon me, Mitsuru-san. My hand[n]got caught on your skirt.[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]I-I see... Please don't surprise me like[n]that. It's hard to see in here, after all.[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11045][f 6 1 9 0 0 1]Oho, what's this? Is Mitsuru-senpai[n]not a fan of the dark?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 7]Well, that's a surprising weakness for[n]her. A stunning revelation that makes[n]someone like her more adorable―[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13047][f 6 1 9 0 0 1]Iori, do you wish to be frozen as well?[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]J-Just kidding! I was just joking![n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Um, could you guys please hurry it up?[n]We've been waiting back here for[n]a while now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19130][f 6 1 9 0 0 1]*giggle*[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10018][f 6 1 9 0 0 1][f 6 1 2 0 0 4]Huh? What's funny?[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 9 0 0 1]It's just that you guys act exactly like[n]the companions I know.[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Hmm, I see...[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19122][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Sorry for bringing up something so[n]weird. C'mon, let's keep going![n][f 1 3 65535][f 1 1][e]

