[msg MSG_000 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2012]Even now, I'm having trouble believing[n]that this is all just inside a movie...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 1 1][f 3 1 1 0 0 11009]Tons of stuff that only happen in movies[n]keep happening here, though.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 11012]Really, [f 6 1 16 0 0 0] and [f 6 1 27 0 0 0][n]are what's unbelievable right now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 1][f 3 1 1 0 0 12013]Parallel worlds, huh...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I'm not sure I get it, but it means there's[n]another set of us in some other world,[n]right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]...Yes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 4][f 3 1 1 0 0 13023]And our personalities in both worlds are[n]essentially the same, existing at the same[n]time.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]From what I've heard, our skills and[n]living conditions are the same as well.[n]So... why are only those two different?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 12 1 0 0][f 4 6 2 12 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2029]Pretty interesting, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 4][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]"Interesting"!? THAT'S all you have to[n]say about it? Man, you're just as[n]nonchalant as always...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 12013]"I am her and she's me..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ever since [f 6 1 16 0 0 0] said that, it's[n]become obvious that you two are[n]similar in some way.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 11 1 0 0][f 4 6 16 0 0 0][f 3 1 1 0 0 16039]Oh, I've been thinking that the entire[n]time...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 0][f 3 1 1 0 0 0]I mean, their personalities are different,[n]but... I can't explain it well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_1 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 10 12 0 1][f 3 1 1 0 0 10009]It does feel weird, though. I was sort[n]of confused at first...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]But now that I've gotten to know her[n]more, she fits in the group just like[n]a glove... I wonder why that is?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_2 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 1 12 0 4][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1029]The length of time spent together isn't[n]what matters―it's the depth of trust[n]that's been built.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_3 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16031]I agree with that.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_4 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 11 6 1 1][f 3 1 1 0 0 0]A-yep! Like they say: how beautiful it is[n]to have good friends![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 4][f 3 1 1 0 0 17001][f 6 1 2 0 0 6]Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 3][f 4 6 18 2 0 1][f 3 1 1 0 0 18113]Well, we were all saved in different ways[n]thanks to [f 6 1 27 0 0 0] bein' with us.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]She's our companion, and that's more[n]than enough for now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19026][f 6 1 2 0 0 6]Th-Thank you, Shinjiro-senpai![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 7]That's right! We're all companions![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 12 0 0 1][f 3 1 1 0 0 12013]Considering the situation we're in,[n]it's only natural that we feel down[n]at times...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 0]But, I think we can handle it if we[n]keep working together like this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 2 0 0 6][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2065]Me too. I can't wait to fight alongside[n]everyone else.[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Same here.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]I'm not stepping down as leader.[f 2 7 1 20 6 32][e]

[msg MSG_018 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23032]I feel like we can take down anything[n]with our combined strength![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21082][f 6 1 2 0 0 4]Dude, you really don't need to be[n]so hung up on that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 1][f 3 1 1 0 0 10032][f 6 1 2 0 0 6]Well then―why don't we keep moving?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2066]Yeah. I'd better prepare for what's[n]coming.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1029]I'm excited to see what our new[n]companions can do.[n][f 1 3 65535][f 1 1][e]

