[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 7][f 4 6 21 2 0 1][f 3 1 1 0 0 1]Alright, that's one more movie fixed up![n]Let's get back to the movie theater![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 2]Doe should have spat out another key[n]to the locks, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Hero]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 2 12 0 1][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 3]So, ah... Did you guys really say, when[n]the movie reaches the end, that the key[n]comes out of the projectionist's head?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 6][f 3 1 1 0 0 4]Yep![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 9 10 0 6][f 3 1 1 0 0 5]First, he's all, "Grrrrhhhhhaaaah!" and[n]flopping around, then it pours from[n]his face and lands with a thick "plop."[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yukari]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 9][f 4 6 10 6 0 1][f 3 1 1 0 0 6]Ugh, that sounds really gross...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 10][f 4 6 4 4 1 1][f 3 1 1 0 0 7]That's because Teddie did a TERRIBLE[n]job describing it![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]In reality, it comes out more like...[n]"bloop"? Or, I guess "poink" works[n]too?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 11 6 0 0][f 3 1 1 0 0 9][f 6 1 2 0 0 9]Ooh, I love the way "poink" sounds![n]But, "plop" is... a bit too real for me.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 14 2 99 1][f 3 1 6 0 0 500][f 3 1 1 0 0 10][f 6 1 2 0 0 6][f 6 1 1 0 0 1]E-Everyone! Listen![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 11]What's wrong?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 4 99 4][f 3 1 1 0 0 12][f 3 1 6 0 0 500][f 6 1 2 0 0 10]Senpai! Everyone! I'm sorry, it happened[n]when we looked away for a second![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Fuuka]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 13][f 6 1 2 0 0 6]Hikari-chan's...![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 19 0 4 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 14]Calm down, Fuuka. What's this about[n]Hikari-chan!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 4 100 0][f 3 1 1 0 0 15][f 6 1 2 0 0 1]Just, come back as fast as you can![n]Please![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 25 12 0 1][f 3 1 1 0 0 16][f 6 1 2 0 0 6]It seems to be an emergency. We should[n]hurry back![n][f 1 3 65535][f 1 1][e]

