[msg DG_MSG_QUEST_FIND]
[f 0 5 65278][f 2 1]You've found a quest![n][f 1 1][e]

[msg DG_MSG_QUEST_FIND_QUESTI]
[f 0 5 65278][f 2 1]You couldn't find a quest...[n]because you're already on a quest![n][f 1 1][e]

[msg DG_MSG_LOCK_DOOR_NO_OPEN]
[f 0 5 65278][f 2 1]It's locked.[n][f 1 1][e]

[sel DG_MSG_SEL_QUEST_CLEAR top]
[f 0 5 65278][f 2 1]Return to base[e]
[f 0 5 65278][f 2 1]Explore freely[e]

[msg DG_MSG_QST_PROGRESS_ENEM]
[f 0 5 65278][f 2 1]Defeated [f 2 4 0] x[f 2 4 1].[n][f 1 1][e]

