[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 21 12 0 1][f 3 1 1 0 0 21009][f 6 1 2 0 0 4]Just as I thought, I'm gettin' tired faster...[n]Takin' a break might not be the worst[n]idea.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 26 0 100 4][f 3 1 1 0 0 0]Yeah, keep an eye on your health.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]You're fighting in an unusual[n]environment. Make sure you[n]take the time to heal up, too![n][f 1 3 65535][f 1 1][e]

