[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 1 1][f 3 1 1 0 0 22018][f 6 1 2 0 0 4]What could this be?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 3 1 6 0 0 500]Hmm... I can't get a good reading from[n]where I am. Ergo, no idea! It's a mystery.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 23 1 0 3][f 4 6 21 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hey, animal noses are useful for this[n]kind of stuff―Mona, can't you tell[n]what it is by smelling it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23036]I―AM―A―HUMAN! Not some... police[n]dog![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0]...Even still, it does have a pretty shine[n]to it. It reminds me of a Treasure.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 6][f 3 1 1 0 0 0]A Treasure, hm...? Then, for our own[n]convenience, why don't we call this[n]a "Treasure Spot"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 0]It's possible that they provide highly[n]lucrative goods.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]Sounds good to me. That'll make it[n]easy to understand, for all of us.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 24 4 1 1][f 3 1 1 0 0 24091]So, that shine disappears once you[n]gather things from it...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 0]Such transience has a pleasing quality[n]to it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 4][f 3 1 1 0 0 0]...Anyway, we should check places that[n]have a shining light. Keep your eyes[n]peeled, Joker![n][f 1 3 65535][f 1 1][e]

