[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 1 1][f 3 1 1 0 0 22116][f 6 1 2 0 0 6]Oh! Over there![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]It's a, uh... was it "BLT"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28033]FOE.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 0]That's right. I believe it stands for[n]"Fried chicken On Egg"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Uh, what? Beef's way better with eggs[n]than chicken.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0]No―I stand by chicken. It's both cheap[n]and filling.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 0 100 3][f 3 1 1 0 0 26591][f 3 1 6 0 0 500]While we ignore those comedians...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0]I wanna remind you: that FOE is still[n]really powerful... At the very least, you[n]can't win against it right now. For sure.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Wait, that's not good! We won't be able[n]to go any further...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0]Hey, I just noticed―ain't that guy just[n]walking around the same area?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Couldn't we, like, slip past him[n]when the coast is clear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 0][f 3 1 1 0 0 26561][f 6 1 2 0 0 6]Ah, that's it! Good job, Skull! You're[n]actually useful sometimes![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0]SOME times!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 26 12 100 0][f 3 1 1 0 0 0]From the looks of it, this FOE's[n]patrolling a fixed route.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Even after checking more closely, I'm[n]still not getting an immediately hostile[n]reading from it...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's possible that it won't act unless[n]ordered by the police.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 22087][f 6 1 2 0 0 4]So it won't attack us unless we make[n]the first move?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Well then, why don't we observe[n]the FOE's movements for a moment?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If we work out its pattern, we'll surely[n]be able to evade it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0]Alright! The Phantom Thieves are[n]gettin' sneaky![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Let's do this, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 24 4 1 1][f 3 1 1 0 0 24008]It'll be quite troublesome if it catches up[n]to us while we're fighting other enemies.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0]Be sure to remain cautious while[n]running away from FOEs.[n][f 1 3 65535][f 1 1][e]

[msg MSG_TUTORIAL_FOE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]An FOE's movements can be seen[n][f 0 1 2]on the map[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]FOEs will keep moving even [f 0 1 2]while[n]you are in combat with other enemies[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If an FOE makes contact with you[n]while you are fighting other[n]enemies, it will [f 0 1 2]join the battle[f 0 1 0]![n][f 1 1][e]

[msg MSG_TUTORIAL_ENEMY_UI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The proximity gauge shows the[n][f 0 1 2]risk of a battle occurring[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 0 1 2]Gray means you are safe.[f 0 1 0]. But as you[n]move, the color changes from[n]green, to yellow, and finally to red.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 0 1 2]Red indicates a battle is imminent[f 0 1 0].[n]Keep an eye on this as you explore![n][f 1 1][e]

