[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 1][f 3 1 1 0 0 6635][f 3 1 6 0 0 500]Guys, just a sec! I'm sensing a presence[n]beyond that door... It's different from[n]anything we've encountered so far.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Just to be sure you're ready for anything[n]that could happen, you might want to[n]check if you're fully prepared...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 4 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]So there's a mystery presence past that[n]door? That's so scary... Do we really[n]have to go that way?[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Let's go.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]......[f 2 7 1 20 8 32][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4011][f 6 1 2 0 0 6]F-Fine, then, uh... You can lead the way,[n]Joker! After you, eheheh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]Did you hear that, Joker? You've been[n]called upon for the task.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You won't let the lady down, will you?[n]We'll all be right behind you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28033]Caution is a vital survival skill. If you're[n]uncertain of our success, let's prepare[n]ourselves before entering.[n][f 1 3 65535][f 1 1][e]

