[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26640][f 3 1 6 0 0 500]Joker―wait a sec! I'm getting an enemy[n]reading just beyond your location.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Can you handle it?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Of course.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Give me a moment.[f 2 7 1 20 0 32][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 25072]Very well then, let's keep going.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 24068]He raises a good point. We have nothing[n]to lose by preparing for the worst.[n]We should regroup before entering.[n][f 1 3 65535][f 1 1][e]

