[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 1][f 3 1 1 0 0 26058][f 6 1 2 0 0 1]Whoooa! I'm really in a sci-fi world![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26049]Seeing this stuff with my own two eyes[n]is such a huge difference! Oh man,[n]this is as real as it gets![n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Simmer down.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I get what you mean.[f 2 7 1 20 2 32][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 6][f 3 1 1 0 0 24031]He's right, Oracle. Why don't you just[n]relax a bit?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Hrgh... You're the last person I wanna[n]hear that from, Inari![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26042][f 6 1 2 0 0 6]Right!? Experiencing something like this[n]is a once-in-a-lifetime opportunity! No,[n]even rarer than that![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I can't wait to see all the technology[n]of this world![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 6][f 3 1 1 0 0 24031]Oracle, you're getting too worked up.[n]Why don't you just relax a bit?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Hrgh... You're the last person I wanna[n]hear that from, Inari![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26106][f 6 1 2 0 0 6]Okay! Time to buckle down and begin[n]our exploration![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 0]You're probably more than aware[n]already, but―I can't fight.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And don't you forget it![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 24076]Well, this is just as dangerous as our[n]usual work as Phantom Thieves. Don't[n]stray too far from the group, Oracle.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 26077][f 6 1 2 0 0 6]Aye aye, Cap'n![n][f 1 3 65535][f 1 1][e]

