[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 3][f 3 1 1 0 0 11063][f 6 1 2 0 0 0]Whoa!? What was that noise!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 1 1][f 3 1 1 0 0 0]Perhaps that FOE [f 0 1 2]destroyed the debris[f 0 1 0][n]that we saw earlier?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 3][f 3 1 6 0 0 500][f 3 1 1 0 0 0]I'll check on that for you. Let's see...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 28 1 0 0][f 4 6 14 10 100 0][f 3 1 1 0 0 14564][f 6 1 2 0 0 6]Wow, incredible! All that debris really[n]did get blown away![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 3][f 3 1 1 0 0 0]Man, that thing really is too strong.[n]If it ever catches us, we're done for...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Don't worry. We just need to make sure[n]we stay well ahead of it.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Furthermore, we know now that[n][f 0 1 2]blocked paths can be opened up[n]if we make use of that FOE[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28002]When we come across a path obstructed[n]with debris, we can get rid of it the same[n]way we just did.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 2 0 1][f 3 1 1 0 0 0]Right. When the time comes, make sure[n]you lure the FOE towards the debris,[n]Joker![n][f 1 3 65535][f 1 1][e]

