[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]There's some red fruit growing here...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 24047][f 6 1 2 0 0 4]Oh? You noticed it too, Joker? They look[n]edible enough... What do you think?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'd say it's worth trying... I think I'll take[n]a bite.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 3][f 3 1 1 0 0 22055][f 6 1 2 0 0 0]Whoa, Fox, what are you doing? That[n]looks like it'll give you a stomach ache![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 0]There's no need to worry! I've already[n]tasted it![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]It's crispy and bursting with juices...[n]Even a gourmet like myself thinks it's[n]delicious![n][f 1 3 65535][f 1 1][e]

[msg MSG_003_1 [Teddie]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]Sooo, I'm gonna go for seconds.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24057][f 6 1 2 0 0 0]Hrm!? Wait, leave some for me![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 0][f 3 1 1 0 0 0]Oh, sheesh! Say something, Joker![n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]Enjoy.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Hey, stop![f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Let's eat![f 2 7 1 20 2 32][e]

[msg MSG_007 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 25 12 0 1][f 3 1 1 0 0 25056][f 6 1 2 0 0 0]You're gonna let them eat it!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0]Some poisons are slow-acting. Teddie's[n]taste test doesn't guarantee that it's safe[n]to―[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 25 12 0 1][f 3 1 1 0 0 25068]You heard him. We're asking for trouble[n]at this point, so we shouldn't―[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 25 6 0 1][f 3 1 1 0 0 25039][f 6 1 2 0 0 9]*sigh* You too, Joker?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]It's dangerous to just carelessly[n]consume something we know nothing[n]about.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Some poisons are slow-acting. As our[n]leader, you should try having a better[n]sense of danger, and―[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 4][f 3 1 1 0 0 0]Mm... That was delicious.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 1][f 3 1 1 0 0 25062][f 6 1 2 0 0 0]No way! You're finished already?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]Underneath the refreshing acidity lies a[n]thick, honey-like sweetness... I give it[n]three stars![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0]See, I told you! C'mon, everyone, eat up![n][f 1 3 65535][f 1 1][e]

[msg MSG_013_1 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 16 1 0][f 3 1 1 0 0 9102][f 6 1 2 0 0 0]...Wait, hragh!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013_2 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Owww, oww! My tummy huuurts![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 1 0][f 3 1 1 0 0 24125][f 6 1 2 0 0 6]Hgh... It... My stomach's...![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 10]We tried to stop you! You've got to go[n]throw up right now![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 0]Hraaaarghhh... I... I think I see a field[n]of beautiful flowers...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 0]Me too... I'm seeing a mountain of[n]expensive sushi... Might this be heaven?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 4 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1034][f 6 1 2 0 0 1]Hang in there, you two! We'll head back[n]and have Margaret make an antidote...![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]...Hrm? Now I feel strangely awake.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]...Hm? Yes, I feel the same.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's as if I'm being reborn on the inside...[n]What is this sensation?[n][f 1 3 65535][f 1 1][e]

[msg MSG_DAMAGE_KUMA]
[f 0 5 65278][f 2 1][f 3 1 6 0 1 236]Teddie lost some HP![n][f 1 1][e]

[msg MSG_DAMAGE_YUSUKE]
[f 0 5 65278][f 2 1][f 3 1 6 0 1 236]Yusuke lost some HP![n][f 1 1][e]

[msg MSG_CURE_SP]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 302]Yusuke and Teddie recovered some SP![n][f 1 1][e]

[msg MSG_021 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 3][f 3 1 1 0 0 28075]I see. That fruit seems to have some sort[n]of awakening effect.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 0]Still, it's too dangerous to eat. There's[n]clearly some side effects as well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 0]True. However, it's better than being[n]hungry. That stomach pain was too[n]much to bear...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022_1 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]Furthermore, that refreshing feeling is[n]somewhat addictive. Perhaps I'll have[n]another...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 4 0 6][f 3 1 1 0 0 25035][f 6 1 2 0 0 2]Stop that![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0]*sigh* It's dangerous to stick around[n]here any longer. Let's go, Joker.[n][f 1 3 65535][f 1 1][e]

