[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]I don't need to keep my personality~[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 1][f 3 1 1 0 0 21040][f 6 1 2 0 0 6]Ugh, dammit! I can't get that trailer's[n]song outta my head![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]And those shitty-ass lyrics are makin'[n]me even more depressed...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 14 1 3][f 3 1 1 0 0 0]Then, let's fight against it and sing[n]lots of cheerful, happy songs![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]Count me in! I'll go first![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 3][f 3 1 1 0 0 10081]No.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 0]Aw, can't I sing just a little!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Not unless you want to make our ears[n]bleed.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11055][f 6 1 2 0 0 9]Dude, do you have to be so harsh!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 4][f 3 1 1 0 0 0]Well then, why don't I do a medley of[n]my stuff?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 3][f 3 1 1 0 0 4081]Uh, we'd obviously rather hear[n]Rise-chan, Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 26 2 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500][f 6 1 2 0 0 6]Ooh, that'd be great! I'd love to hear[n]Risette sing live![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]How often do we get to hear an idol sing[n]for just us!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 3][f 3 1 1 0 0 6530][f 3 1 6 0 0 500]*giggle* If it'll cheer everyone up, I'd be[n]happy to.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 0][f 3 1 1 0 0 0]But we can't let our guard down while[n]exploring, so maybe I'll save it for when[n]we all get back, okay?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]For real!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21043][f 6 1 2 0 0 1]Hell yeah! I'm so stoked! C'mon, let's[n]hurry![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 1 0 3][f 4 6 24 12 0 1][f 3 1 1 0 0 0]Skull's completely wrapped around her[n]finger.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]That's our Rise. She really knows how to[n]handle her fans.[n][f 1 3 65535][f 1 1][e]

