[msg MSG_000 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 64 0 0 3][f 4 6 79 0 0 4][f 4 6 78 0 0 1][f 3 1 1 0 0 0]Looks like you actually brought us[n]something useful for once, Inmate![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hand it over![n][f 1 3 65535][f 1 1][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Handed over [f 4 4 3 0 1602]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Justine]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hmm... How intriguing...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]This may help us to improve the[n]functionality of the Velvet Room.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Caroline]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Wait here, Inmate![n][f 1 3 65535][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 3 1 1 0 0 0]A few minutes later...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 0 0 4][f 4 6 78 0 0 1][f 3 1 1 0 0 0]*sigh* It was somewhat difficult, but[n]this should prove useful to your[n]rehabilitation.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You can now use [f 0 1 2]3-Layer Fusion[f 0 1 0]![n]This will require three Personas to initiate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Caroline]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Don't take our help for granted, Inmate![n][f 1 3 65535][f 1 1][e]

