[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]Todos se reunieron en el vest胤bulo[n]despu姻s de terminar sus preparativos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Est茨n todos listos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21068][f 6 1 2 0 0 6]斡S胤, totalmente![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 6][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0][f 6 1 2 0 7]Perfecto en[n]nuestro extremo, tambi姻n![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 23 12 0 0][f 3 1 1 0 0 0][f 6 1 30 0 0 0]夷qu姻 tal tus propios preparativos?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Una vez que salgamos, no podremos[n]volver aqu胤 por un tiempo. Si necesitas[n]cuidar de algo, ahora es el momento.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Necesito tiempo para prepararme.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Empecemos la misi吋n.[f 2 7 1 64 2 32][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23077][f 6 1 2 0 0 6]Mmhm, es mejor estar completamente[n]preparado. 斡Mejor seguro que lo siento![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 4][f 3 1 1 0 0 0]Una vez que estemos listos, vamos a la[n]plaza Kamoshida![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0][f 6 1 2 0 6] Esta misi吋n[n]tiene que ser un 姻xito, no importa qu姻![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23072][f 6 1 2 0 0 6]斡S胤, es hora de robar la estatua de[n]Kamoshidaman y rescatar a nuestros[n]compa隠eros de equipo![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 4][f 3 1 1 0 0 0]Empecemos dirigi姻ndose a la plaza Kamoshida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0][f 6 1 2 0 6] Esta misi吋n[n]tiene que ser un 姻xito, no importa qu姻! Let's go![n][f 1 3 65535][f 1 1][e]

