[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 1][f 3 1 1 0 0 1]Great, another movie that leaves[n]a bad taste in your mouth.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 3]Right? It was just the same as it was[n]with Kamoshidaman―like it's making[n]me feel kinda empty inside...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 4][f 3 1 1 0 0 3]It appears to be based on the principle[n]of majority rule.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]The movie makes it pretty clear that[n]whatever most people agree with is[n]correct, and no other opinions are valid.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 5][f 6 1 2 0 0 3]Whatever most people agree with, huh?[n]That's not really our kinda thing.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]I mean, we USED to choose our targets[n]based on their rep in society...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 71 6 0 1][f 3 1 1 0 0 7]Ryuji...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 8]But now, we know better.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9]We exact our justice without being[n]influenced by society's whims―that's[n]how the Phantom Thieves do things.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_05 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 68 0 0 3][f 3 1 1 0 0 10][f 6 1 2 0 0 4]Our methods aside―Hikari, is this[n]movie the one that you need to see?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 11]...I don't know.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 1 0 1][f 4 6 72 12 0 3][f 3 1 1 0 0 12][f 6 1 2 0 0 4]How about you, Nagi-san? Do you[n]have any knowledge of this film?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 13]No, none whatsoever.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 19 0 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 14][f 6 1 2 0 0 3]Hm... Hmmm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]What's up?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 1 2 3][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 16][f 6 1 3 0 0 3]Oh―well, it's not that big a deal...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 17]But, aren't normal dinosaur movies[n]more like―BLAAAAM! Or, something[n]like that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 1][f 3 1 1 0 0 18][f 6 1 2 0 0 6]Yeah, yeah![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 8 1 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]And they're all like, GRAAAAAAAARH![n]And KA-BOOOOM!!! Right?[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]GRAAAAAAAARH?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]KA-BOOOOM?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]They're also ROOOOOAAAAAAR.[f 2 7 1 64 0 32][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 8 1 0][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Ooh, yeah! And then it's all like,[n]BOOMBOOMBOOMBOOM!!![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 1][f 3 1 1 0 0 21]While I won't comment on the[n]explanation, I get your meaning.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]A dinosaur that wants to save her[n]companion, but can't speak up because[n]of the majority opinion...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 1][f 3 1 1 0 0 23]This is supposed to be a dinosaur movie,[n]but it's too realistic―as if we're watching[n]the painful difficulties of human life.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 0 0 0][f 3 1 1 0 0 24]Mmhm―how anyone disrupting the[n]peace is evil and everyone constantly[n]worries how others feel and think...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 25][f 6 1 2 0 0 4]The same could be said about the[n]Kamoshidaman movie too―why are[n]the stories like that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 1][f 3 1 1 0 0 26]This doesn't only apply to films, but[n]creators include messages of some kind[n]in their work quite often.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27]In this case, I suppose the filmmakers[n]are saying, "Cast aside who you are and[n]conform to what everyone else does..."[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 28][f 6 1 2 0 0 6]What? Giving up on what you actually[n]want to do for some bullshit like that?[n]That's no different from just bein' dead![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 29]I agree. No matter what those around[n]me may say, I have no intention of ever[n]giving up on art.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 6 0 0][f 3 1 1 0 0 30]Then again... I can kind of understand[n]the feeling of having to go along with[n]others...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 31]Had I not met you all, I would've just[n]gone with what my company and[n]the adults demanded of me...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 0 1][f 3 1 1 0 0 32][f 6 1 2 0 0 4]Was that movie... that odd?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 33][f 6 1 2 0 0 4]Huh? You didn't think anything was[n]off about it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 34]I'm just curious why you're...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35][f 6 1 2 0 0 4]Why do you feel so angry... or sad[n]about it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 36]Deep down, that dinosaur wants to save[n]her bud, but no one's willing to help,[n]so she can't... That's a real bummer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 37]But her companions were opposed to[n]the idea. If they tried to rescue that one,[n]everyone else would be put in danger...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 38]Still, it's possible that they could get[n]rescued―then everyone would be safe,[n]right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39][f 6 1 2 0 0 4]I think it's nonsense to make decisions[n]without even trying first.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 40]That's...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 84 12 0 0][f 3 1 1 0 0 41]Hikari-san, if you believe the movie[n]should remain as is, then I'm fine[n]with it as well...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 42]However, I'd only support that decision[n]if you truly want it. I don't want you to[n]repress your true self.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 43]My... true self? That movie... I...[n][f 1 3 65535][f 1 1][e]

[sel SEL_030 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]You're okay with how it is now?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Don't you want a different ending?[f 2 7 1 64 0 32][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 44]At first, I thought it was fine as is...[n]But, now...[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 45]A different ending? I hadn't even[n]thought of that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 4]Well then, for example―if you were[n]that dinosaur, what would you want[n]to do, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 47][f 6 1 2 0 0 4]Me?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 48]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_034_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 49]But... the other dinosaurs...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 50][f 6 1 2 0 0 6]B-But i-if you lie to your own[n]feelings... I-It'll just make things[n]more painful![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 51][f 6 1 2 0 0 10]Ah... Um, I mean... That's how I was, so...[n]S-Sorry...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 52][f 6 1 2 0 0 4]Lie...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 53][f 6 1 2 0 0 4]You saw how Kamoshidaman ended[n]and you were glad how that went, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 54][f 6 1 2 0 0 10]So, um... Basically...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 55]If it'll change again... If there's a different[n]ending to this...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 2 0][f 3 1 1 0 0 56]I think―I do want to see that...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 57][f 6 1 2 0 0 0]Really!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 65 0 0 6][f 3 1 1 0 0 58]Alright! Then, leave it to us![n][f 1 3 65535][f 1 1][e]

[msg MSG_040_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 3 6][f 3 1 1 0 0 59][f 6 1 2 0 0 6]Hey, [f 6 1 30 0 0 0]? Let's change this[n]movie, just like the first one![n][f 1 3 65535][f 1 1][e]

[sel SEL_041 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Yeah.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]We need to prioritize our escape.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]What does everyone else say?[f 2 7 1 64 0 32][e]

[msg MSG_042 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 60]I agree as well.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 61]I believe changing these movies will[n]lead to our escape from here in the end.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 62]No, I think that changing these movies[n]will be our fastest way to escape from[n]here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 63]Well, I agree with that plan, at least.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 64]I believe changing these movies will lead[n]to our escape from here in the end.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 0 0 1][f 3 1 1 0 0 65][f 6 1 2 0 0 4]When we changed it, a key came out of[n]Doe... You're banking on the same[n]happening this time too, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 66]That pattern hasn't been confirmed[n]yet, but I think it's likely.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 67]Even more so when you consider how[n]Doe is the one playing these bizarre[n]movies.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 70 2 0 1][f 3 1 1 0 0 68][f 6 1 2 0 0 6]Then that settles that! Let's go explore[n]that movie, [f 6 1 30 0 0 0]![n][f 1 3 65535][f 1 1][e]

