[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 19 10 0 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19018]斡...![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 1][f 3 1 1 0 0 0]Un ambiente diferente de la pel胤cula[n]anterior.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Esta parece ser una pel胤cula de ciencia[n]ficci吋n, pero ese tr茨iler me dejo[n]un mal sabor de boca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7037]Ser diferente es malo, 夷eh? 斡Qu姻 mierda![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 70 0 0 1][f 3 1 1 0 0 26039]Entonces, la individualidad es[n]irregularidad...[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷Qu姻 pasa?[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Qu姻 pasa, Futaba?[f 2 7 1 64 2 32][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 26008]No es nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 1 0 3][f 6 1 25 0 0 0][f 4 6 81 1 0 6][f 3 1 1 0 0 61004]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 4 2 0][f 3 1 1 0 0 64009][f 6 1 2 0 0 4]Hikari 夷qu姻 piensas sobre esta pel胤cula?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Ese robot est茨 siendo tan maltratado...[n]solo por ser diferente... Incluso[n]siendo llamado "el mal"...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si hubiera intentado ser como los dem茨s...[n]夷No habr胤a evitado todo ese[n]problema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 1][f 3 1 1 0 0 26135][f 6 1 2 0 0 0]夷Eh? 夷Realmente piensas eso, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 1][f 3 1 1 0 0 9040]Ohhh nooo... Todo el mundo tiene que[n]ser igual...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, 夷por qu姻 soy diferente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1029]Teddie...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]El Maestro, Yosuke y todos los dem茨s[n]son diferentes, pero... me gusta cada[n]uno de ellos por qui姻n son...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]Entonces... me pone triste pensar que[n]deber胤an ser iguales. Waaaaah...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 6][f 3 1 1 0 0 3051]斡Tiene raz吋n! Teddie es Teddie, y yo[n]soy yo, tal como deber胤a ser.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 81 6 2 0][f 3 1 1 0 0 61052]Yo, ah...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Yo siempre... Intente actuar normal y[n]mezclarme con la sociedad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Siempre hab胤a pensado eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 1][f 3 1 1 0 0 26135][f 6 1 2 0 0 4]夷Y ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 7 2 0][f 3 1 1 0 0 61055]Verlos cambiar esas pel胤culas... Me hizo[n]sentir mal...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 0]Pero, no estoy segura. No s姻 qu姻[n]pensar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 3 0][f 3 1 1 0 0 26031]Ah, ya veo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 2 0 1][f 3 1 1 0 0 4106][f 6 1 2 0 0 6]斡De todas formas! 斡Vamos a esa pel胤cula![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Cuanto antes la cambiemos, antes saldremos[n]de aqu胤. 斡Es hora de corregir[n]esa trama de mierda![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 0]斡S胤! Y, si despu姻s, Hikari podr胤a estar[n]menos confundida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 0 4 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19005]斡Esperen! Hay algo que deber胤an saber antes de que saltemos a la pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El robot principal del tr茨iler me pareci吋[n]familiar, y el t胤tulo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]夷Qu姻 quieres decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19113]Ese robot parec胤a una amiga m胤a... Su nombre es Aigis.[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷No es tambi姻n el t胤tulo de la pel胤cula?[f 2 7 1 64 8 32][e]
[f 0 5 65278][f 2 1]夷Eres amiga de un robot?[f 2 7 1 64 0 32][e]

[msg MSG_025 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 0][f 3 1 1 0 0 27094][f 6 1 2 0 0 4]El tr茨iler de la pel胤cula pronunci吋 el[n]t胤tulo como "A-I-gis", pero 夷t雨 lo[n]pronunciaste como "AI-gis"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La parte de "AI" significa inteligencia[n]artificial, pero 夷qu姻 significa[n]"GIS"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Mmm, y el nombre de mi amiga se escribe de igual. No creo que sea una simple coincidencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 1 0 3][f 4 6 9 10 0 6][f 3 1 1 0 0 9046]斡No importa! 斡夷Eres amiga de un robot?![n]Apenas puedo creerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 3][f 3 1 1 0 0 23016]S胤, esto se est茨 volviendo realmente[n]extra隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3010][f 6 1 2 0 0 9]夷Realmente acabamos de decir eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 6][f 3 1 1 0 0 9046]斡Eres amiga de un robot?! Apenas puedo[n]creerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 3][f 3 1 1 0 0 23016]S胤, esto se est茨 volviendo realmente[n]extra隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3010][f 6 1 2 0 0 9]夷Realmente acabamos de decir eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 1][f 4 6 71 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]El tr茨iler de la pel胤cula pronunci吋 el[n]t胤tulo como "A-I-gis", pero 夷t雨 lo[n]pronunciaste como "AI-gis"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La parte de "AI" significa inteligencia[n]artificial, pero 夷qu姻 significa[n]"GIS"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19068]Mmm, y el nombre de mi amiga se escribe de igual. No creo que sea una simple coincidencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19053]Es cierto que Aigis es una robot, pero no la considero diferente a mis otros amigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 3 1 1 0 0 0]Ella tiene su propia identidad y forma[n]de pensar. La tratamos como nuestra[n]compa隠era, no solo como un robot.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61012]Una compa隠era... con identidad...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 0]Lo que sabemos hasta ahora es que alguien[n]que conocemos tambi姻n est茨 en esa[n]pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 0]De hecho. Primero, el mundo de Kamoshidaman;[n]luego, el mundo de Yosukesaurio.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tiene sentido que lo mismo ocurra con[n]esta tercera pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 0][f 3 1 1 0 0 22113][f 6 1 2 0 0 4]Bueno, tal vez a la tercera va la vencida[n]y los compa隠eros de [f 6 1 27 0 0 0] est姻n[n]en esta, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19099]斡夷T雨 tambi姻n lo crees?! 斡Entonces, apresur姻monos a encontrarlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 64009]As胤 que van a cambiar la pel胤cula una[n]vez m茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 0]Si creen que est茨n en peligro, por favor[n]vuelvan aqu胤 de inmediato.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19129]斡Claro! 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 80 1 0 3][f 4 6 74 1 4 1][f 3 1 1 0 0 54014]...Theo. Tu invitada tiene tanta urgencia[n]de reunirse con sus compa隠eros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]En un momento como este... *masticar*[n]*masticar* 夷Qu姻 crees que deber胤amos[n]hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 0][f 3 1 1 0 0 0]Vigilarla. Eso es todo lo que podemos[n]hacer...[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 1 4 0][f 3 1 1 0 0 54016]Entonces... Centr姻monos en observar de[n]cerca, con palomitas... *masticar*[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Hermana... 夷Podr胤as concentrarte en[n]comer o hablar, y no hacer ambas cosas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 18 2 3][f 3 1 1 0 0 61133]Por favor, regresen a salvo...[n][f 1 3 65535][f 1 1][e]

