[msg MSG_000 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 2 1][f 3 1 1 0 0 1]As胤 que este es el Cine... No puedo[n]creer que estuvi姻ramos dentro de una[n]pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 7]夷Verdad? 斡Por fin pude debutar en la[n]gran pantalla![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 3]Me alegra que te hayan encontrado a[n]tiempo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 4]Eres Hikari, 夷verdad? Un placer conocerte.[n]Todos me hablaron ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 5]Fueron a buscarte, y... Me alivia que[n]est姻s bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 6]Gracias por preocuparte por m胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 7]Oh, mm... Bueno, todos los dem茨s estaban[n]preocupados, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 8]Por cierto, alguien me dijo que no puedes[n]recordar como llegaste aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 9]M-mmhm... Cuando me despert姻, ya estaba[n]aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 10]No te preocupes. Saldremos de este lugar[n]juntos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]...Aunque, puede sonar extra隠o viniendo[n]de alguien que acaba de llegar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 4 2 0][f 3 1 1 0 0 12]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 2 0 0 1][f 3 1 1 0 0 13][f 6 1 2 0 0 4]夷C吋mo est茨 Aigis?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 0][f 3 1 1 0 0 14]Como sospechaba Mitsuru, parece que solo[n]est茨 temporalmente desactivada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 1 0 3][f 4 6 23 0 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]Futaba, 夷podr胤as echar un vistazo? Se[n]te dan bien esas cosas t姻cnicas,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 16]Bueno, tengo habilidades de hackeo, pero[n]no soy mec茨nica...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]Pero har姻 lo que pueda. Puedo... Echar姻[n]un vistazo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 0 0 3][f 3 1 1 0 0 18]En ese caso, por favor s胤gueme...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19]夷C吋mo te fue, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 18 1 1][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Wow... Ella est茨 compuesta de partes[n]locas con tecnolog胤a alucinante y,[n]mm... En fin, 斡es simplemente una locura![n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Ah, ya veo...[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Eso no significa nada.[f 2 7 1 64 6 32][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 6][f 3 1 1 0 0 21]Tampoco lo entiendo, pero entiendo la[n]idea de que es una locura.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 18 1 0][f 3 1 1 0 0 22]Parece que tiene una funci吋n de[n]autoreparaci吋n, 斡las partes rotas se est茨n[n]arreglando solas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23][f 6 1 2 0 0 0]斡夷Qu姻 clase de tecnolog胤a es ESA?![n]斡Parece m茨s magia que ciencia ficci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 13 12 0 0][f 3 1 1 0 0 24]Todas sus funciones parecen funcionar[n]normalmente. No hay problemas por el[n]momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 25]Apenas tiene energ胤a, pero a este ritmo,[n]debe recuperarse pronto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 26]Ya veo... Me alegro de que ella tambi姻n[n]est姻 bien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 6][f 3 1 1 0 0 27]Lamento la molestia, pero vamos a tener[n]que dejar a Aigis bajo su cuidado[n]hasta que se recupere.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 2 1 0 1][f 4 6 1 0 0 3][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 28]Una coa menos de la que preocuparnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 29]Debo darles las gracias de nuevo por su[n]apoyo, incluyendo lo de Aigis. Estoy[n]muy agradecido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30]Entonces... 夷Y t雨 eres...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 6][f 3 1 1 0 0 31]斡Cierto, todav胤a no nos hemos presentado![n]Soy Kanji Tatsumi, de primer a隠o[n]en el Instituto Yasogami.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 10 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 0]夷Primer a隠o? As胤 que eres m茨s joven que[n]yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 6][f 3 1 1 0 0 33][f 6 1 2 0 0 9]T姻cnicamente, podr胤a ser incluso m茨s[n]joven de lo que crees...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 34][f 6 1 2 0 0 4]夷A qu姻 te refieres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 72 12 0 0][f 3 1 1 0 0 35]Todos hemos venido de diferentes lugares...[n]y de diferentes momentos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 36]No solo eso, algunos de nosotros[n]aparentemente estamos lidiando con temas[n]a雨n m茨s anormales...[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 19 7 0 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 37]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 2 1 0 1][f 4 6 72 0 0 3][f 3 1 1 0 0 38]Podemos dejar los detalles para m茨s[n]tarde...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39]Pero, b茨sicamente, hemos venido de mundos[n]distintos, por m茨s raro que suene.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 40]Ya veo... Muy bien, entonces.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 66 10 0 6][f 3 1 1 0 0 41][f 6 1 2 0 0 1]夷Est茨s bien con eso?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 42]Oye, me est茨s empezando a recordar mucho[n]a [f 6 1 30 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[sel SEL_036 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Creo que nos llevaremos bien.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Creo que est茨s imaginando cosas.[f 2 7 1 64 6 32][e]

[msg MSG_037 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 4][f 3 1 1 0 0 43]Ahh, te entiendo. Tambi姻n se parece[n]mucho a nuestro l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 4][f 3 1 1 0 0 44]夷En serio? Sabes, 姻l es muy similar a[n]nuestro l胤der tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 69 0 0 6][f 3 1 1 0 0 45][f 6 1 2 0 0 4]夷As胤 que, t雨 tambi姻n eres el l胤der de[n]Takeba e Iori?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 46]S胤, oh, cierto que a雨n no te he dicho[n]mi nombre, 夷eh? Mi nombre es...[n][f 1 3 65535][f 1 1][e]

