[msg MSG_000 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 1][f 3 1 1 0 0 35010]TENGO UNA PREGUNTA PARA TODOS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 25003][f 6 1 2 0 0 4]夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35002]HAY ALGO QUE NO PUEDO ENTENDER DE SUS[n]ACCIONES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷POR QU畏 SE REFIEREN A AIGIS COMO UN[n]"INDIVIDUO"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 0 0][f 3 1 1 0 0 10019]夷Por qu姻...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 0]AIGIS ES UNA ROBOT. ELLA NO ES UN SISTEMA[n]ORG威NICO, COMO EL RESTO DE USTEDES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 2031]Es f茨cil...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 3 1 1 0 0 0]Es porque es nuestra compa隠era. No hay[n]otra raz吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]夷SU COMPA謂ERA...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 6][f 3 1 1 0 0 13070]Cuando se trata de uno de los nuestros,[n]no importa si es org茨nico o[n]inorg茨nico.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 1 6][f 3 1 1 0 0 0]Luchamos juntos y avanzamos juntos. Esas[n]son razones m茨s que suficientes[n]para nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 6 0 0][f 3 1 1 0 0 35007]PERO MIS "COMPA謂EROS" ME TRATAN COMO UN[n]ERROR. NO ME AYUDAR緯AN.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19005]Oye, Ribbon... 夷C吋mo describir胤as a un "compa隠ero"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35002]RECONOZCO QUE EL T畏RMINO DEFINE A AQUELLOS[n]CON LA MISMA APARIENCIA, HABILIDADES[n]Y FALTA DE ERRORES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 26015][f 6 1 2 0 0 3]Tu forma de decir la palabra... "Error"...[n]No puedo explicar por qu姻, pero[n]no me gusta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 6 0 0][f 3 1 1 0 0 0]ENTONCES, UNA DESCALIFICACI遺N, O UN[n]DEFECTO-[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 0][f 3 1 1 0 0 26085][f 6 1 2 0 0 6]斡Nada de eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 21037]Todas esas palabras suenan como la mierda[n]que dir胤a un idiota.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Es una mierda como ese idiota est茨[n]forzando sus reglas a la sociedad![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 6 0 0][f 3 1 1 0 0 35007]PERO, LAS REGLAS DEBEN SER SEGUIDAS...[n][f 1 3 65535][f 1 1][e]

[sel SEL_016 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]No tienes que seguirlas.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]No eres un error, Ribbon.[f 2 7 1 20 0 32][e]

[msg MSG_017 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35022][f 6 1 2 0 0 4]YO SOY... 夷NO SOY UN ERROR?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Dime, Ribbon. 夷Por qu姻 no intentas pensar[n]por ti misma mientras est茨s con[n]nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 6][f 3 1 1 0 0 22067]Suena como una gran idea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]No tienes que seguir a un egoc姻ntrico.[n]斡Son tonter胤as del Supervisor![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 0]Mm. 斡Y si esos bots intentan algo otra[n]vez, te protegeremos![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]夷ME PROTEGER威N? PERO, 夷POR QU畏 AYUDA A[n]ALGUIEN COMO YO?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19031]*risa* 夷Recuerdas lo que hablamos antes? La respuesta a esta es simple...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es porque eres una compa隠era para nosotros[n]como Aigis, Ribbon.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35022][f 6 1 2 0 0 4]YO... 夷SOY UNA COMPA謂ERA?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 35 1 0 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35004]ENTONCES, ESTO ES SER UNA COMPA謂ERA…[n]ENTIENDO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 4][f 3 1 1 0 0 15124]Entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16030]Sus di茨logos est茨n sincronizando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 0][f 3 1 1 0 0 0]Lo siento. No pude evitarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19130]*risa* Oh, Aigis...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19006][f 6 1 2 0 0 4]Bueno, empecemos de nuevo. 夷Est茨s lista,[n]Ribbon?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 2 0 0][f 3 1 1 0 0 35002][f 6 1 2 0 0 6]S緯. SOY TU COMPA謂ERA. 斡DEBO SEGUIRTE![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 0]Ese es el esp胤ritu. Sigue as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 2065]Entonces, 夷seguimos? Espero que podamos seguir juntos, Ribbon.[n][f 1 3 65535][f 1 1][e]

