[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]Find Hikari's cherished possession![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Ask the flowers for more information[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]Reach the house beyond the door[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]テスト小目標３[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]テスト小目標４[n][e]

