[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]斡Obtenga art胤culos de Torretes Roaring![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Obtener 3 m茨s Gizmos futuristas[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]Obtener 2 Gizmos Futuristas m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Obtener 1 m茨s Gizmo futurista[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Derrota 1 m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_6]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_7]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_8]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_9]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_10]
[f 0 5 65278][f 2 1]斡Escapar![n][e]

