[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]斡Derrota al Sr. Oso![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Consulta el mapa para encontrar al[n]enemigo.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]斡Derrota a ambos Sr. Osos![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Derrota al Sr. Oso restante.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Dir胤gete m茨s profundamente en el[n]laberinto.[n][e]

