[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]Steal the Seidoptera's treasure![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Use your map to find FOE territory[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]Check the Treasure Spots[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Check the Treasure Spots[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Check the Treasure Spots[n][e]

