[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]斡Captura la gran mariposa![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Busca pistas sobre la mariposa.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]Dir胤gete al Acto 1.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Investiga en el Acto 1.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Dir胤gete al Acto 2.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
[f 0 5 65278][f 2 1]Investiga en el Acto 2.[n][e]

