[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]斡Recoge Cinnamon Fern.![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Encuentra 1 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]Encuentra 2 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Encuentra 3 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Encuentra 4 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
[f 0 5 65278][f 2 1]Encuentra 5 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_6]
[f 0 5 65278][f 2 1]Encuentra 6 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_7]
[f 0 5 65278][f 2 1]Encuentra 7 m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_8]
[f 0 5 65278][f 2 1]Verifica los puntos del tesoro.[n][e]

