[msg DG_OBJECTIVE_MSG_LARGE_0]
[f 0 5 65278][f 2 1]斡Consigue los ingredientes para[n]palomitas![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0]
[f 0 5 65278][f 2 1]Busca un punto de tesoro cerca del agua[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
[f 0 5 65278][f 2 1]斡Usa electricidad en los granos de ma胤z![n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
[f 0 5 65278][f 2 1]Encuentra tres m茨s.[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
[f 0 5 65278][f 2 1]Encuentra cuatro m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
[f 0 5 65278][f 2 1]Encuentra cinco m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_6]
[f 0 5 65278][f 2 1]Encuentra seis m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_7]
[f 0 5 65278][f 2 1]Encuentra siete m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_8]
[f 0 5 65278][f 2 1]Encuentra ocho m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_9]
[f 0 5 65278][f 2 1]Encuentra nueve m茨s[n][e]

[msg DG_OBJECTIVE_MSG_SMALL_0_10]
[f 0 5 65278][f 2 1]Revisa los puntos de tesoro.[n][e]

