[msg map_help_001_01]
Tap the pencil tool, and you can draw[n]walls on the map.

[msg map_help_001_02]
The eraser tool removes walls.

[msg map_help_002_01]
The brush tool colors in tiles.

[msg map_help_002_02]
The dustcloth tool erases floors.

[msg map_help_002_03]
Tapping the color button and selecting a[n]color will allow you to change the tint.

[msg map_help_003_01]
Place icons such as doors on the map by[n]dragging them.

[msg map_help_003_02]
To delete icons on the map, drag them to[n]the trash can with the pencil tool.

[msg map_help_004_01]
Tap the icon to change the color.

[msg map_help_005_01]
テスト1

[msg map_help_006_01]
Tap the floor number while the whole map[n]is displayed, and just that floor will[n]display.

[msg map_help_006_02]
Tap the labyrinth button to select the[n]labyrinth and floor.

[msg map_help_007_01]
ぶめまょ をよゎ ろぺら ろめま ぼよゆらぺれれ よょ ろめま ろよら ゅまみろデ をよゎ[n]ぼぺょ やままら ろめま らゅぺをまる もぼよょ みぺぼもょむ ゎら ゐめもゅま ろめま[n]ゆぺら ぼめぺょむまれ ぽもるまぼろもよょテ

[msg map_help_007_02]
Return it to its default settings by[n]tapping the compass again.

[msg map_help_008_01]
If you make a mistake, tap Undo to[n]cancel the last action.

[msg map_help_009_01]
Use Auto Pilot to move automatically.

[msg map_help_009_02]
Draw the route you would like to go with[n]the route pen in the Auto Pilot menu.

[msg map_help_009_03]
Travel the route you drew and tap the[n]move button to start moving[n]automatically.

[msg map_help_009_04]
By tapping the line that was drawn by[n]the route pen you can go backwards.

[msg map_help_009_05]
Use the route eraser to delete the Auto[n]Pilot line. Erase it from the end of the[n]line.

[msg map_help_010_01]
Drag the icons onto the free palette to[n]save your favorite icons.

[msg map_help_010_02]
Delete unwanted icons from the free[n]palette by dragging them to the trash[n]can.

[msg map_help_011_01]
っゎるもょむ れらまぼもぺゅ れぼるままょもょむれデ をよゎ ゐもゅゅ めぺわま ぺ[n]れらまぼもぺゅ れぼるままょもょむ らぺゅまろろまテ とろ ゐもゅゅ めぺわま もぼよょれ[n]をよゎ ぼぺょ らゅぺぼま よょゅを ぽゎるもょむ れぼるままょもょむれテ

[msg map_help_011_02]
However, you cannot place special[n]screening icons on top of others that[n]were placed at a different time.

