[msg eventitem_600]
ブランク ブランク

[msg eventitem_601]
Story of a queen in love with one of her[n]subjects. Alas, they can't be[n]together...

[msg eventitem_602]
Note about a move that, surely, is only[n]ever achievable by the manliest of men!

[msg eventitem_603]
Girly scroll advocating for honor among[n]thieves and kung fu masters.

[msg eventitem_604]
Sketch of an ammonite, whose spiral[n]shell can be drawn only by the soulful.

[msg eventitem_605]
Wild fish caught by two people who, of[n]course, have the power of the wild.

[msg eventitem_606]
Theodore's popcorn, salty enough to[n]stimulate the mind to solve mysteries.

[msg eventitem_607]
Stone owned by a lonely lost herbivore.[n]Holding it, you feel a warm family bond.

[msg eventitem_608]
Motorcycle gloves perfect for hanging on[n]while doing skids and slides.

[msg eventitem_609]
Ring made of Shadows, serving as proof[n]that friendship can form across worlds.

[msg eventitem_60A]
Handmade rice balls and a protein drink[n]for a well-balanced meal.

[msg eventitem_60B]
Calling card from Ryuji to Ken. Its[n]cryptic message says, "I'll be waiting."

[msg eventitem_60C]
Handmade medal that was awarded to the[n]conqueror of the Shadows.

[msg eventitem_60D]
Bright yellow beetle that Teddie found.[n]Could it be a sign of something?

[msg eventitem_60E]
Trophy given to the winner of a donut-[n]eating contest organized by the Wilds.

[msg eventitem_60F]
Extra part that was left over after[n]fixing the robot.

[msg eventitem_610]
Teddie made this to praise the Wilds'[n]maturity. Hopefully he'll imitate[n]them...

[msg eventitem_611]
Photo of a group of girls where they all[n]struck hilarious poses.

[msg eventitem_612]
Machine invented by the three navigators[n]to share information.

[msg eventitem_613]
Collection of recipes to make ideal[n]bodyguard food.

[msg eventitem_614]
Proof of 25% Persona registration,[n]giving 10% off when summoning from a[n]film.

[msg eventitem_615]
Proof of 50% Persona registration,[n]giving 15% off when summoning from a[n]film.

[msg eventitem_616]
Proof of 75% Persona registration,[n]giving 20% off when summoning from a[n]film.

[msg eventitem_617]
Proof of total Persona registration,[n]giving 25% off when summoning from a[n]film.

[msg eventitem_618]
Hikari's precious clapboard that she[n]donated as a token of appreciation.

[msg eventitem_619]
Script with a lovely scene that sprang[n]from the possibilities of 4 other[n]movies.

[msg eventitem_61A]
Live, wriggling bait which should[n]definitely attract some big fish.

[msg eventitem_61B]
Power gleaned from the kind of[n]friendship that changes your life[n]forever.

[msg eventitem_61C]
Card key that could be used to unlock[n]some otherwise stubborn doors...

[msg eventitem_61D]
Fragment of old film from the movie[n]"Kamoshidaman."

[msg eventitem_61E]
Fragment of old film from the movie[n]"Junessic Land."

[msg eventitem_61F]
Fragment of old film from the movie[n]"A.I.G.I.S."

[msg eventitem_620]
Fragment of old film from the movie[n]"Hikari."

[msg eventitem_621]
Live, wriggling bait which should[n]definitely attract some big fish.

[msg eventitem_622]
Corn kernels that have gotten all wet.

[msg eventitem_623]
Movie Pamphlet

[msg eventitem_624]
Movie Pamphlet

[msg eventitem_625]
Movie Pamphlet

[msg eventitem_626]
Movie Pamphlet

[msg eventitem_627]
Movie Pamphlet

[msg eventitem_628]
Movie Pamphlet

[msg eventitem_629]
Movie Pamphlet

[msg eventitem_62A]
Movie Pamphlet

[msg eventitem_62B]
Movie Pamphlet

[msg eventitem_62C]
Movie Pamphlet

[msg eventitem_62D]
Movie Pamphlet

[msg eventitem_62E]
Movie Pamphlet

[msg eventitem_62F]
Movie Pamphlet

[msg eventitem_630]
Movie Pamphlet

[msg eventitem_631]
Movie Pamphlet

[msg eventitem_632]
Movie Pamphlet

[msg eventitem_633]
Movie Pamphlet

[msg eventitem_634]
Movie Pamphlet

[msg eventitem_635]
Movie Pamphlet

[msg eventitem_636]
Movie Pamphlet

[msg eventitem_637]
Movie Pamphlet

[msg eventitem_638]
Movie Pamphlet

[msg eventitem_639]
Proof you beat a powerful foe.Boosts the[n]power of the wild card

[msg eventitem_63A]
Proof you beat a powerful foe.Get 150%[n]EXP with Finish Bonuses

[msg eventitem_63B]
Proof you beat a powerful foe. [f 0 1 3]Carry[n]Boost to next battle with Finish Bonuses

[msg eventitem_63C]
Proof you beat a powerful foe.Get 200%[n]EXP with Finish Bonuses

[msg eventitem_63D]
Mysterious, shiny bit of film collected[n]from a Shadow.

[msg eventitem_63E]
Mysterious, shiny bit of film collected[n]from a Shadow.

[msg eventitem_63F]
Mysterious, shiny bit of film collected[n]from a Shadow.

[msg eventitem_640]
Mysterious, shiny bit of film collected[n]from a Shadow.

[msg eventitem_641]
Mysterious, shiny bit of film collected[n]from a Shadow.

[msg eventitem_642]
Same projector as the one in the Velvet[n]Room. [f 0 1 3]Perform 3 Persona fusions

[msg eventitem_643]
貴重品ID_0x643

[msg eventitem_644]
貴重品ID_0x644

[msg eventitem_645]
Card on which a Persona power can be[n]stored. Have:

[msg eventitem_646]
Card on which a Persona power can be[n]stored. Have:

[msg eventitem_647]
What any stylish royal would wear in[n]hell. [f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Gemori

[msg eventitem_648]
Storage for organs needed in the after-[n]life. [f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Ammut

[msg eventitem_649]
Bulrush that once saved a rabbit's[n]life.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Hare of[n]Inaba

[msg eventitem_64A]
Strange plant that still bears rich[n]fruit.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Mayahuel

[msg eventitem_64B]
Lakewater home to a fairy[n]guardian.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for[n][f 0 1 3]Vivian

[msg eventitem_64C]
Frog queen who has also led[n]humans.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for[n][f 0 1 3]Dzelarhons

[msg eventitem_64D]
String woven by a dark faerie.Unlock[f 0 1 0][n][f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Fenrir

[msg eventitem_64E]
Sunny disk owned by the goddess of love.[n][f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Hathor

[msg eventitem_64F]
Relic with the power to rule the[n]world.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Longinus

[msg eventitem_650]
Crucifix of a girl who had a divine[n]vision.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Jeanne[n]d'Arc

[msg eventitem_651]
Tooth from a serpent with the wings of a[n]bat. [f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Vouivre

[msg eventitem_652]
Apparel of a vampire who wreaked havoc.[n][f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Kudlak

[msg eventitem_653]
Apparel of a vampire who was[n]blessed.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for[n][f 0 1 3]Kresnik

[msg eventitem_654]
One of six wings from a majestic[n]angel.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Seraph

[msg eventitem_655]
Headdress of a legendary emperor.Unlock[f 0 1 0][n][f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Huang Di

[msg eventitem_656]
Relic of a fairy who longed for[n]power.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Black[n]Frost

[msg eventitem_657]
Stuffed rabbit from Wonder-land.Unlock[f 0 1 0][n][f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Alice

[msg eventitem_658]
Book with the names of 7[n]archangels.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for[n][f 0 1 3]Michael

[msg eventitem_659]
Wood engraved with the fates of[n]all.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Norn

[msg eventitem_65A]
Knight's crest seen at the world's[n]end.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Pale Rider

[msg eventitem_65B]
Mandala with a sketch of a destructive[n]god. [f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Shiva

[msg eventitem_65C]
Symbol of 1 of the 7 sins,[n]gluttony.Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for[n][f 0 1 3]Beelzebub

[msg eventitem_65D]
Key to Hell's door, where the devil[n]lives. [f 0 1 1]Unlock[f 0 1 0] [f 0 1 3]special fusion[f 0 1 0] for [f 0 1 3]Lucifer

[msg eventitem_65E]
貴重品ID_0x65E

[msg eventitem_65F]
貴重品ID_0x65F

[msg eventitem_660]
Proof of 25% Persona registration,[n]giving 10% off when summoning from a[n]film.

[msg eventitem_661]
Proof of 50% Persona registration,[n]giving 15% off when summoning from a[n]film.

[msg eventitem_662]
Proof of 75% Persona registration,[n]giving 20% off when summoning from a[n]film.

[msg eventitem_663]
Proof of total Persona registration,[n]giving 25% off when summoning from a[n]film.

[msg eventitem_664]
Gives a 10% discount at the shop. Usable[n]with other discounts.

[msg eventitem_665]
Gives a 10% discount at the shop. Usable[n]with other discounts.

[msg eventitem_666]
Proof of your loyal patronage. Skill[n]Card Discount: 10%

[msg eventitem_667]
Map to the treasure hidden in[n]"Kamoshidaman."

[msg eventitem_668]
Map to the treasure hidden in "Junessic[n]Land."

[msg eventitem_669]
Map to the treasure hidden in[n]"A.I.G.I.S."

[msg eventitem_66A]
Map to the treasure hidden in "[f 6 1 40[n]0 0 0]."

[msg eventitem_66B]
Map to the treasure hidden in "Movie[n]Theater District."

[msg eventitem_66C]
貴重品ID_0x66C

[msg eventitem_66D]
Gold crown found in the treasure horde.

[msg eventitem_66E]
Gold crown found in the treasure horde.

[msg eventitem_66F]
Jungle fern emitting the scent of[n]cinnamon.

[msg eventitem_670]
Jungle fern emitting the scent of[n]cinnamon.

[msg eventitem_671]
Jungle fern emitting the scent of[n]cinnamon.

[msg eventitem_672]
Machinery made with futuristic tech[n]known only to a savvy few.

[msg eventitem_673]
Machinery made with futuristic tech[n]known only to a savvy few.

[msg eventitem_674]
Machinery made with parts not even the[n]savvy few will recognize.

[msg eventitem_675]
Machinery made with parts not even the[n]savvy few will recognize.

[msg eventitem_676]
Machinery made with parts not even the[n]savvy few will recognize.

[msg eventitem_677]
Fragrant fruit that looks edible, but[n]may still be a risky snack.

[msg eventitem_678]
Fragrant fruit that looks edible, but[n]may still be a risky snack.

[msg eventitem_679]
Fragrant fruit that looks edible, but[n]may still be a risky snack.

[msg eventitem_67A]
Fragrant fruit that looks edible, but[n]may still be a risky snack.

[msg eventitem_67B]
Jungle plant secreting a sticky goo with[n]medicinal properties.

[msg eventitem_67C]
Jungle plant secreting a sticky goo with[n]medicinal properties.

[msg eventitem_67D]
貴重品ID_0x67D

[msg eventitem_67E]
貴重品ID_0x67E

[msg eventitem_67F]
貴重品ID_0x67F

[msg eventitem_680]
貴重品ID_0x680

[msg eventitem_681]
貴重品ID_0x681

[msg eventitem_682]
貴重品ID_0x682

[msg eventitem_683]
貴重品ID_0x683

[msg eventitem_684]
貴重品ID_0x684

[msg eventitem_685]
貴重品ID_0x685

[msg eventitem_686]
貴重品ID_0x686

[msg eventitem_687]
貴重品ID_0x687

[msg eventitem_688]
貴重品ID_0x688

[msg eventitem_689]
貴重品ID_0x689

[msg eventitem_68A]
貴重品ID_0x68A

[msg eventitem_68B]
貴重品ID_0x68B

[msg eventitem_68C]
貴重品ID_0x68C

[msg eventitem_68D]
貴重品ID_0x68D

[msg eventitem_68E]
貴重品ID_0x68E

[msg eventitem_68F]
貴重品ID_0x68F

[msg eventitem_690]
Often used as a lifeline because of its[n]durable, corrosion-resistant material.

[msg eventitem_691]
Removes impurities from gases. Perfect[n]for science experiments.

[msg eventitem_692]
Statue with curious-looking eyes.[n]Holding it makes you feel lucky...

[msg eventitem_693]
Statue with curious-looking ears.[n]Holding it makes you feel safe...

[msg eventitem_694]
Statue with curious-looking lips.[n]Holding it makes you feel blessed...

[msg eventitem_695]
Used to make a device that reads the[n]body composition of Shadows.

[msg eventitem_696]
Used to make a special flute that has[n]the power to call upon evil.

[msg eventitem_697]
Tin-silver alloy used to make a bell[n]that can ward off evil.

[msg eventitem_698]
Black and white magatama said to contain[n]both body and spirit.

[msg eventitem_699]
Believed to reverse the attributes of[n]whatever is reflected in it.

[msg eventitem_69A]
貴重品ID_0x69A

[msg eventitem_69B]
貴重品ID_0x69B

[msg eventitem_69C]
貴重品ID_0x69C

[msg eventitem_69D]
貴重品ID_0x69D

[msg eventitem_69E]
貴重品ID_0x69E

[msg eventitem_69F]
貴重品ID_0x69F

[msg eventitem_6A0]
貴重品ID_0x6A0

[msg eventitem_6A1]
貴重品ID_0x6A1

[msg eventitem_6A2]
貴重品ID_0x6A2

[msg eventitem_6A3]
貴重品ID_0x6A3

[msg eventitem_6A4]
貴重品ID_0x6A4

[msg eventitem_6A5]
貴重品ID_0x6A5

[msg eventitem_6A6]
貴重品ID_0x6A6

[msg eventitem_6A7]
貴重品ID_0x6A7

[msg eventitem_6A8]
貴重品ID_0x6A8

[msg eventitem_6A9]
貴重品ID_0x6A9

[msg eventitem_6AA]
貴重品ID_0x6AA

[msg eventitem_6AB]
貴重品ID_0x6AB

[msg eventitem_6AC]
貴重品ID_0x6AC

[msg eventitem_6AD]
貴重品ID_0x6AD

[msg eventitem_6AE]
貴重品ID_0x6AE

[msg eventitem_6AF]
貴重品ID_0x6AF

[msg eventitem_6B0]
Sartorial decoration from a Card[n]Soldier.

[msg eventitem_6B1]
Arrow acquired at Theo's request, fired[n]by an FOE in the Group Date Cafe.

[msg eventitem_6B2]
Liquid half drunk by Teddie, swiped from[n]a table in the Group Date Cafe.

[msg eventitem_6B3]
Terrifying aluminum pacifier, found in[n]the Evil Spirit Club.

[msg eventitem_6B4]
Found in the Evil Spirit Club. Elizabeth[n]has the wrong idea...

[msg eventitem_6B5]
Note that reads: "33242X." What are[n]Elizabeth's secret feelings...?

[msg eventitem_6B6]
"Manly" is stitched on its back. Once[n]drenched in sweat, but now clean.

[msg eventitem_6B7]
Opens a box filled with Shadows. The key[n]emits a dark aura...

[msg eventitem_6B8]
Found within the Clock Tower. It is old,[n]and the hands have stopped...

[msg eventitem_6B9]
Has an incredible ability to pierce[n]anything, after sooo many prototypes.

[msg eventitem_6BA]
From Elizabeth. It looks like it can[n]only be used once.

[msg eventitem_6BB]
Made by Theodore to save materials. It[n]will start melting soon...

[msg eventitem_6BC]
The Reaper's chain, covered in rust.

[msg eventitem_6BD]
Yellow sphere found in a void at the End[n]of You in Wonderland.

[msg eventitem_6BE]
Pink sphere found in a void on the Group[n]Date Cafe's Big Day.

[msg eventitem_6BF]
Black sphere found in a void on the Evil[n]Spirit Club's Last Story.

[msg eventitem_6C0]
Red sphere found in a void at the Inaba[n]Pride Exhibit's Final Night.

[msg eventitem_6C1]
Corrupted by Hell's miasma. Use to[n]summon Turdak.

[msg eventitem_6C2]
Instills fear in all who see it. Use to[n]summon Basilisk.

[msg eventitem_6C3]
Japan's oldest sake, a rice wine. Use to[n]summon Ouyamatsumi.

[msg eventitem_6C4]
High-quality, yet refuses to stick! Use[n]to summon Warrior Zeus.

[msg eventitem_6C5]
Prize for defeating Elizabeth. Use to[n]summon Zeus+.

[msg eventitem_6C6]
Said to be the sturdiest material.

[msg eventitem_6C7]
Prize from the shooting gallery. You can[n]hardly resist squeezing it!

[msg eventitem_6C8]
Token of appreciation from Marie. Put[n]your ear to it and listen...

[msg eventitem_6C9]
May be used with other coupons.

[msg eventitem_6CA]
May be used with other coupons.

[msg eventitem_6CB]
Proof of your loyal patronage. Skill[n]Card Discount: 10%

[msg eventitem_6CC]
Proof of a great accomplishment. It's[n]very rare to receive this.

[msg eventitem_6CD]
Hairpin that represents purity, borne by[n]an angel of love.

[msg eventitem_6CE]
Something slimy that oozed out of an old[n]doll.

[msg eventitem_6CF]
Magnificent work from the festival guys.[n]It's painstakingly hand-drawn!

[msg eventitem_6D0]
Protects the protagonist from dying. Can[n]be reused if you return to school.

[msg eventitem_6D1]
Protects the protagonist from dying. But[n]it cannot be used at this time...

[msg eventitem_6D2]
貴重品ID_0x6D2

[msg eventitem_6D3]
貴重品ID_0x6D3

[msg eventitem_6D4]
貴重品ID_0x6D4

[msg eventitem_6D5]
貴重品ID_0x6D5

[msg eventitem_6D6]
貴重品ID_0x6D6

[msg eventitem_6D7]
貴重品ID_0x6D7

[msg eventitem_6D8]
貴重品ID_0x6D8

[msg eventitem_6D9]
貴重品ID_0x6D9

[msg eventitem_6DA]
貴重品ID_0x6DA

[msg eventitem_6DB]
貴重品ID_0x6DB

[msg eventitem_6DC]
貴重品ID_0x6DC

[msg eventitem_6DD]
貴重品ID_0x6DD

[msg eventitem_6DE]
貴重品ID_0x6DE

[msg eventitem_6DF]
貴重品ID_0x6DF

[msg eventitem_6E0]
貴重品ID_0x6E0

[msg eventitem_6E1]
貴重品ID_0x6E1

[msg eventitem_6E2]
貴重品ID_0x6E2

[msg eventitem_6E3]
貴重品ID_0x6E3

[msg eventitem_6E4]
貴重品ID_0x6E4

[msg eventitem_6E5]
貴重品ID_0x6E5

[msg eventitem_6E6]
貴重品ID_0x6E6

[msg eventitem_6E7]
貴重品ID_0x6E7

[msg eventitem_6E8]
貴重品ID_0x6E8

[msg eventitem_6E9]
貴重品ID_0x6E9

[msg eventitem_6EA]
貴重品ID_0x6EA

[msg eventitem_6EB]
貴重品ID_0x6EB

[msg eventitem_6EC]
貴重品ID_0x6EC

[msg eventitem_6ED]
貴重品ID_0x6ED

[msg eventitem_6EE]
貴重品ID_0x6EE

[msg eventitem_6EF]
貴重品ID_0x6EF

[msg eventitem_6F0]
貴重品ID_0x6F0

[msg eventitem_6F1]
貴重品ID_0x6F1

[msg eventitem_6F2]
貴重品ID_0x6F2

[msg eventitem_6F3]
貴重品ID_0x6F3

[msg eventitem_6F4]
貴重品ID_0x6F4

[msg eventitem_6F5]
貴重品ID_0x6F5

[msg eventitem_6F6]
貴重品ID_0x6F6

[msg eventitem_6F7]
貴重品ID_0x6F7

[msg eventitem_6F8]
貴重品ID_0x6F8

[msg eventitem_6F9]
貴重品ID_0x6F9

[msg eventitem_6FA]
貴重品ID_0x6FA

[msg eventitem_6FB]
貴重品ID_0x6FB

[msg eventitem_6FC]
貴重品ID_0x6FC

[msg eventitem_6FD]
貴重品ID_0x6FD

[msg eventitem_6FE]
貴重品ID_0x6FE

[msg eventitem_6FF]
貴重品枠最後

