[msg DG_OBJECTIVE_MSG_LARGE_0]
Get the ingredients for popcorn!

[msg DG_OBJECTIVE_MSG_SMALL_0]
Seek a Treasure Spot near water

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
Use electricity on Damp Kernels!

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
Find three more

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
Find four more

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
Find five more

[msg DG_OBJECTIVE_MSG_SMALL_0_6]
Find six more

[msg DG_OBJECTIVE_MSG_SMALL_0_7]
Find seven more

[msg DG_OBJECTIVE_MSG_SMALL_0_8]
Find eight more

[msg DG_OBJECTIVE_MSG_SMALL_0_9]
Find nine more

[msg DG_OBJECTIVE_MSG_SMALL_0_10]
Check the Treasure Spots

