[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 3042][f 6 1 2 0 0 6]You guys! You found me![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Is he with that herbivore we were trying[n]to find!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Gaudy carnivore]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 92 0 1 1][f 3 1 1 0 0 30904][f 6 1 1 0 0 1][f 6 1 2 0 0 6]GRRRROOOOOOOAR![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 6 0 3][f 3 1 1 0 0 0]Aaaaaah! Yosuke's gonna be swallowed[n]whole if we don't do something![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 6][f 3 1 1 0 0 0]Senpai! We're comin' for ya![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hey―meat-eating chicken! Come and[n]get us, dammit![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 3][f 3 1 1 0 0 23082]Wait! That carnivore's insanely strong![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 14 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 2]Then what're we supposed to do!?[n]Senpai's gonna get eaten![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 6 1 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]If only we could lure that carnivore[n]away from them...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 4 6][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19063][f 6 1 2 0 0 4]Oh, I know! Couldn't we use that thing?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You know, the thing we found on our[n]way here... It ought to take care of[n]that carnivore![n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 3 0 0][f 4 6 20 1 0 3]You mean the gate?[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]You mean the rope?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]You mean the trap?[f 2 7 1 20 0 32][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 1 6][f 3 1 1 0 0 25115][f 6 1 2 0 0 6]That's right! We saw one that was left[n]open![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 1 6][f 3 1 1 0 0 21022][f 6 1 2 0 0 6]What are you, a dino wrangler!?[n]We ain't got any rope![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 6 1 3][f 3 1 1 0 0 0]Hmm, a dino wrangler...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oh―maybe she meant that we could[n]lead the carnivore to that electric gate?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 25 6 1 6][f 3 1 1 0 0 25115][f 6 1 2 0 0 6]That's right! We saw one that was left[n]open![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 18 1 6][f 3 1 1 0 0 22018][f 6 1 2 0 0 3]Trap? I don't remember a trap...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 8 1 6][f 3 1 1 0 0 0]I believe [f 6 1 26 0 0 0]-san was[n]referring to that electric gate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 1 6][f 3 1 1 0 0 25115][f 6 1 2 0 0 6]Oh, that's right! We saw one that was[n]left open![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 3 6][f 3 1 1 0 0 0]So, all we gotta do is go there and[n]trap it![n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Let's go with that plan.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]How do we do that, though?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]You've got this, Skull.[f 2 7 1 20 2 32][e]

[msg MSG_019 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 27 6 0 3][f 3 1 1 0 0 27079][f 6 1 2 0 0 4]But how are we going to drive[n]the carnivore beyond the gate?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 4 1 3][f 3 1 1 0 0 4062][f 6 1 2 0 0 0]How? Well, we'll just... How ARE we[n]gonna trap it!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 1 6][f 3 1 1 0 0 21068][f 6 1 2 0 0 0]Yeah, I'll just―wait, don'tcha think[n]that's a bit out of my league!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 0 5 3][f 3 1 1 0 0 0]Leave this to me! I've got a nice-sized[n]rock right here, so I'll just take aim,[n]and...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 5 3][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 3 1 1 0 0 0]Hey―eat THIS![n][f 1 3 65535][f 1 2 50][f 1 1][e]

[msg MSG_023 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 9 1 0 0][f 4 6 22 14 2 6][f 3 1 1 0 0 22055][f 6 1 2 0 0 0]Wahhh! Did he just whip a rock at[n]a carnivore!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 0]And that's a perfect pitch! Did you all[n]see my flawless technique!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Gaudy carnivore]]
[f 0 5 65278][f 2 1][f 4 6 92 0 1 1][f 3 1 1 0 0 30904][f 6 1 1 0 0 1][f 6 1 2 0 0 6]GWOOOOOOOOO![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 1 0 3][f 4 6 4 10 0 6][f 3 1 1 0 0 4054][f 6 1 2 0 0 0]Aah! Didn't that just make it angrier!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I ticked it off on purpose so it'll come[n]after us![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 5069]Ah, so we're going with a decoy strategy.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 1 1 0 6][f 4 6 6 4 99 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500][f 6 1 2 0 0 6]Everyone, head back the way you just[n]came! Run as fast as you can―past that[n]gate![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 1 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Looks like our mission's begun. Let's[n]keep going until we rescue Yosuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 6][f 3 1 1 0 0 4077]Gotcha! We have more important things[n]to do than heading back to the movie[n]theater, anyway![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 1][f 3 1 6 0 0 500][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Right―but you don't have much time![n]You have to run for it![n][f 1 3 65535][f 1 1][e]

