[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]We've brought the frozen meat and[n]cooking equipment along with us[n]while hunting for a good cooking spot...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 24076]Hmm, if we're going to cook this meat,[n]why not do it around here?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]It's an open area, there's a water source[n]nearby... I'd say it's as safe a place[n]to cook as we could hope for.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]We may have only found a pot to[n]cook in, but we should be fine, so long[n]as we have a heat source for it...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]The only thing is that we have no[n]recipe to work from. Will that be a[n]problem?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 0]Naoto-kun, new discoveries are always[n]waiting to be made in cooking. We just[n]need to believe in ourselves![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 0][f 3 1 1 0 0 6573][f 3 1 6 0 0 500]Mmhm! Improvising a tasty dish with[n]a minimal number of ingredients is a[n]useful cooking skill, too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I'm getting fired up! Time for us gals[n]to bust out our culinary skills![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Let's get to it![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1081]W-Wait... Since there's only so much[n]meat, shouldn't we get a more reliable―[n]I mean, less experimental cook?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0]Y-Yeah, what he said! We'll handle[n]the cooking part of the bait, and you[n]can, uh...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]I know! You can go out and look for[n]other ingredients for us to use! Please!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 7033][f 6 1 2 0 0 9]You're kinda freakin' out there,[n]Yosuke-senpai―I get it, though...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 2]Hey, what's that supposed to mean!?[n]Does our cooking really upset you[n]so much?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]It's more freaky than upsetting.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]I'll be counting on you ladies.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]You'd be the best at gathering.[f 2 7 1 20 0 32][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 10 0 1][f 3 1 1 0 0 3057][f 6 1 2 0 0 0]Yeah, it's super fre―Wait, did you[n]really just say that out loud!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 0 1 1][f 3 1 1 0 0 3054][f 6 1 2 0 0 0]Wha!? Uh, you mean, like, you're[n]counting on them to gather a lot of[n]ingredients, yeah?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 3071][f 6 1 2 0 0 10]Yeah, what he said! We want you to use[n]your... feminine instincts, or whatever,[n]to find the best ingredients for us![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Don't forget, we need to start a fire to[n]cook the meat, right? That's why we feel[n]most suited for the cooking part of this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 27 2 0 1][f 3 1 1 0 0 0]Looking for ingredients does sound fun...[n]I feel like we can find lots of new and[n]interesting ones here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 4][f 3 1 1 0 0 22030][f 6 1 2 0 0 4]Ooh, I wanna do that too! What say we[n]leave the cooking to them and us gals[n]go on a little hunt?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 0]*chuckle* You make it sound like an[n]adventure... That seems more to my[n]taste as well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]In that case, how about we prepare[n]the food while you ladies search for[n]additional ingredients?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 5 2 0 1][f 3 1 1 0 0 5077]Sounds all right to me. We'll leave the[n]cooking up to you―this time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Okay, off we go―in search of new meats![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Um, we already have the meat, so why[n]don't we look for... other ingredients,[n]for flavor―like seaweed and shark fin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Don't tell me we're walking all the way[n]to the ocean to forage... At any rate,[n]we should get going.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 18 4 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19122][f 6 1 2 0 0 7]Yeah! Let's go, ladies![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 3][f 4 6 9 12 0 1][f 3 1 1 0 0 9096]Whew, it worked... Excellent job,[n]Yosuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]If we'd have left the cooking to them, we[n]wouldn't end up with bait―we'd get[n]a chemical weapon...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21011][f 6 1 2 0 0 4]Dude... Are the girls on your team[n]really that bad at cooking?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Don't even ask... There are things in this[n]world you're better off not knowing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]But have no fear! Our Sensei is a master[n]cook![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052]Oh? I'd bet Joker's skills stack up with[n][f 6 1 13 0 0 0]'s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]After all, he's lodging at a caf〒. When it[n]comes to cooking curry, he can't be beat![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 1 2 0 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]That's great to hear. Let's work together[n]so we can make sure this turns out well.[n][f 1 3 65535][f 1 1][e]

[sel SEL_031 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]I'm expecting top-tier cuisine.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]This is such a drag.[f 2 7 1 20 4 32][e]
[f 0 5 65278][f 2 1]I'll steal your appetites![f 2 7 1 20 0 32][e]

[msg MSG_032 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 1][f 3 1 1 0 0 3045][f 6 1 2 0 0 4]Oh, are you guys bonding over cooking?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0]Hell yeah, looks like this is gonna be[n]a real show! I can't wait to see what[n]they whip up.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 24016]Cooking in an unfamiliar setting can[n]be discomforting. The inconvenience[n]alone may seem impossible to handle...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 0]However, anything can be eaten once[n]it's been cooked―that is the one thing[n]I am most certain of.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]I don't know why, but, the way this guy[n]talks... I believe him.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 9061][f 6 1 2 0 0 6]Ohhh, his pride as a chef has been[n]ignited like a bonfire![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]It seems that we can expect something[n]great from them. I can't wait to taste[n]what they make.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]While you're droolin' over there, may I[n]remind you that we're doing all this to[n]make dino bait, not Fox food?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]After cleaning the meat and finishing[n]the other cooking preparations...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 28031]It seems that we're ready to cook[n]once the ladies return.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]Joker and [f 6 1 12 0 0 0]-kun both[n]handled everything so skillfully.[n]I'm impressed.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 2 0 0][f 3 1 1 0 0 0]It's already lookin' tasty and it's not even[n]cooked yet... I'm excited to see how this[n]turns out.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 26502][f 3 1 6 0 0 500]Hey, dudes―looks like the Gatherin'[n]Girls are back.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 1 0 1][f 4 6 4 12 0 4][f 3 1 1 0 0 0]Sorry about the wait![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]We collected a lot of ingredients.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ooh, perfect timin'. So, what did you[n]bring back?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 2 0 1][f 3 1 1 0 0 8068]This is what I found.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]...Um, is it some kind of grass?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 1][f 3 1 1 0 0 0]It appears to be some type of herb.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Here, give it a sniff―doesn't it smell[n]nice?[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 23103][f 6 1 2 0 0 9]Meowww!? That's a bit too grassy[n]for my nose...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 0]It is rather... pungent, but herbs can[n]complement the smell of meats well,[n]so these could be quite useful.[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4129][f 6 1 2 0 0 6]Okay, me next! Take a look...[n]Ta-daaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Holy shit, it's huge! What kinda egg[n]is this!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0]Eh, I dunno. I just saw it on the ground[n]and picked it up.[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3091][f 6 1 2 0 0 9]Dude, this thing better not end up[n]hatching on us...[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]It has a pleasant shape, but a bold, wild[n]pattern―I want to take it back for further[n]study instead of cracking it open...[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 12 0 1][f 3 1 1 0 0 5129]This is what I found―here you go.[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 10 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Is that... some kind of bug-eating pitcher[n]plant?[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 9056][f 6 1 2 0 0 10]My animal instincts... are telling me[n]that thing's dangerous...[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]Wouldn't it be cute as a serving dish?[n]I just picked it, so it's nice and fresh.[n][f 1 3 65535][f 1 1][e]

[sel SEL_060 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]That's a great idea.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]That thing is so creepy.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]We should cook it instead.[f 2 7 1 20 0 32][e]

[msg MSG_061 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 1][f 3 1 1 0 0 21055][f 6 1 2 0 0 0]Dude, are you for real!? If we use that as[n]a dish, it'll just eat the food itself![n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 6][f 3 1 1 0 0 24018]I suppose it doesn't appeal to everyone's[n]sense of beauty. However, I find it rather[n]magnificent.[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Right? I think it looks really neat too![n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1037][f 6 1 2 0 0 9]There's nothing more I can say...[n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5074]It's really fleshy and fibrous, so I bet it[n]has great texture. It seems like it would[n]be pretty healthy, too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_066 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Isn't Amagi-san next in line to be[n]the hostess of some historic inn?[n][f 1 3 65535][f 1 1][e]

[msg MSG_066_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]Did I hear that wrong? Please tell me[n]I did...[n][f 1 3 65535][f 1 1][e]

[msg MSG_067 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 6][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1037]No, you didn't... But, I know what[n]you mean...[n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 2 1 1][f 3 1 1 0 0 0]Aw, man... Everybody else gets to show[n]off a bunch of cool stuff, but all I got[n]were these...[n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]What is it, what is it? C'mon, show us![n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 23045][f 6 1 2 0 0 6]Ooooh, what an enticing aroma! Could[n]those be what I think they are?[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 1 0 1][f 4 6 27 12 0 4][f 3 1 1 0 0 0]They're wild matsutake mushrooms![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 27 0 0 0]-chan spotted them,[n]then the ladies of the Phantom Thieves[n]swiped every last one![n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3049][f 6 1 2 0 0 6]Daaaaamn! Those things are expensive―[n]and there's so many![n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]But, why are matsutake mushrooms[n]growing in a jungle?[n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 12 0 1][f 3 1 1 0 0 8130]I suspect they were most likely involved[n]in genetic manipulation experiments.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The researchers may have developed[n]them concurrently with the dinosaurs...[n]That's just my own speculation, though.[n][f 1 3 65535][f 1 1][e]

[msg MSG_075 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 2 3 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 6]So, the girls' total yield is a bunch of[n]herbs, some kind of egg, a pitcher plant,[n]and lots of matsutake mushrooms![n][f 1 3 65535][f 1 1][e]

[msg MSG_076 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 3][f 4 6 25 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]That pitcher plant is a bit... you know,[n]but the others seem quite usable, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_077 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24031]The pot has been brought up to proper[n]temperature, and the meat is ready[n]to go as well.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 16 1 0][f 3 1 1 0 0 0]Joker, [f 6 1 12 0 0 0]―we leave the rest[n]in your capable hands.[n][f 1 3 65535][f 1 1][e]

[msg MSG_078 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 1 12 0 6][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]I guess we'll cook the mushrooms first.[n]What should we do with them?[n][f 1 3 65535][f 1 1][e]

[sel SEL_079 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Quickly roast them over the fire.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Mince them up extremely fine.[f 2 7 1 20 0 32][e]

[msg MSG_080 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23045]Oooh―the moment they hit the flames,[n]this pleasant scent wafted my way...[n][f 1 3 65535][f 1 1][e]

[msg MSG_081 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]My appetite's been fully roused. I can[n]feel my tummy growling like mad![n][f 1 3 65535][f 1 1][e]

[msg MSG_082 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 25 10 0 1][f 3 1 1 0 0 25058][f 6 1 2 0 0 10]Huh? That's a... surprising method...[n][f 1 3 65535][f 1 1][e]

[msg MSG_083 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Whoa, they just keep getting smaller[n]and smaller, at such insane speed...[n]It almost feels like a waste![n][f 1 3 65535][f 1 1][e]

[msg MSG_084 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 1 0 0 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]All right, next up is the meat. How do you[n]think we should cook it?[n][f 1 3 65535][f 1 1][e]

[sel SEL_085 top]
[f 0 5 65278][f 2 1]Quickly sear it over high heat.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Simmer it slowly over low heat.[f 2 7 1 20 0 32][e]

[msg MSG_086 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 21 4 3 6][f 3 1 1 0 0 21057]Oh man, it looks sooooo good! It's got[n]those burn marks an' everything! I'm[n]gettin' hungry...[n][f 1 3 65535][f 1 1][e]

[msg MSG_087 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hungry? Try some of this, then![n][f 1 3 65535][f 1 1][e]

[msg MSG_088 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21024]Ooh, don't mind if I d―[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Augh, this is that bug-eatin' plant! It's[n]still moving; there's no way I'm gonna[n]eat this―Wait, why is it MOVING!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_089 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 1][f 3 1 1 0 0 4010][f 6 1 2 0 0 3]Grilling it so slowly is making me antsy...[n][f 1 3 65535][f 1 1][e]

[msg MSG_090 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 4][f 3 1 1 0 0 0]I agree with you there. I'd rather scorch[n]it with a strong flame.[n][f 1 3 65535][f 1 1][e]

[msg MSG_091 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]I'm begging you, Yukiko―please, don't[n]go anywhere near that fire...[n][f 1 3 65535][f 1 1][e]

[msg MSG_092 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 24 2 0 1][f 3 1 1 0 0 0]...Ah, this meat is beautifully browned.[n]I believe it's ready to plate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_093 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 4][f 3 1 1 0 0 0]Now, we should garnish it with[n]the mushrooms we prepared...[n][f 1 3 65535][f 1 1][e]

[msg MSG_094 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 20 10 0 3][f 4 6 4 2 0 1][f 3 1 5 0 5 122][f 3 1 1 0 0 0][f 6 1 2 0 0 6]And now we add the special sauce...[n]There―voila![n][f 1 3 65535][f 1 1][e]

[msg MSG_095 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3034][f 6 1 2 0 0 0]Wha―Chie! What the hell did you[n]just do!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_096 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]It's, uhh... Movie Meat with Foraged[n]Jungle Sauce?[n][f 1 3 65535][f 1 1][e]

[msg MSG_097 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]I meant what's IN the sauce! And when[n]did you even make that stuff!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_098 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 4][f 3 1 1 0 0 5032]We combined the egg white, the herbs,[n]and some liquid from the inside of the[n]pitcher plant, then boiled it all down.[n][f 1 3 65535][f 1 1][e]

[msg MSG_099 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 0]Um... They said not using the ingredients[n]they brought back would be a waste,[n]so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_099_5 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 8027][f 6 1 2 0 0 9]I couldn't stop them. I'm sorry.[n][f 1 3 65535][f 1 1][e]

[msg MSG_100 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 0]Good god, this dish appears to have[n]been... slimed![n][f 1 3 65535][f 1 1][e]

[msg MSG_101 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]It's, um... What do they call it? Organic?[n]Also, it's nice and green, and doesn't it[n]smell like something a dino would eat?[n][f 1 3 65535][f 1 1][e]

[msg MSG_102 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3036][f 6 1 2 0 0 6]Not in the least! It just reeks. It smells[n]like... grassy eggs![n][f 1 3 65535][f 1 1][e]

[msg MSG_103 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]What're we gonna do with this?[n]It's been turned into some kinda[n]mystery object.[n][f 1 3 65535][f 1 1][e]

[msg MSG_104 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 3][f 4 6 19 0 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Should we... do a taste test?[n][f 1 3 65535][f 1 1][e]

[msg MSG_105 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Huh!? But who's gonna―[n][f 1 3 65535][f 1 1][e]

[msg MSG_106 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 3 0 2 0][f 4 6 9 0 4 1][f 3 1 1 0 0 0]Alley-oop! Down your hatch.[n][f 1 3 65535][f 1 2 60][f 1 1][e]

[msg MSG_107 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3104][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 3]Hrgh!? Bluh! Ah, you moron! I-I don't[n]wanna die yet―Blech! Blech![n][f 1 3 65535][f 1 1][e]

[msg MSG_108 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 4 1 3][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 0]Yosuke... Please make it through this[n]alive...[n][f 1 3 65535][f 1 1][e]

[msg MSG_109 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3124][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 3]*cough* Urgh! *wheeze*[n][f 1 3 65535][f 1 1][e]

[msg MSG_110 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Are you okay!? Should we try to make[n]you throw up or something?[n][f 1 3 65535][f 1 1][e]

[msg MSG_111 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 1 0][f 3 1 1 0 0 3101][f 6 1 2 0 0 10]N-Nnnnngh... Hrrrrrghhhh![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]I-It's... It's...[n][f 1 3 65535][f 1 1][e]

[msg MSG_112 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 16 1 0][f 3 1 1 0 0 3123][f 6 1 1 0 0 1][f 6 1 2 0 0 1]It's... delicious!!![n][f 1 3 65535][f 1 1][e]

[msg MSG_113 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Are you for real!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_114 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Seriously! It's so good, it makes no[n]sense! Try it, you guys![n][f 1 3 65535][f 1 1][e]

[msg MSG_115 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 0 0 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 5 0 5 124][f 3 1 1 0 0 0]*munch munch*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 3 1 1 0 0 19124][f 6 1 2 0 0 6]Wow, he's right, this is good! It's creamy[n]and bursting with flavor![n][f 1 3 65535][f 1 1][e]

[msg MSG_116 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 4][f 3 1 1 0 0 0]Mm, this could be quite addicting...[n]The sauce adds a richness to the meat[n]that really complements the flavor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_117 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 21064][f 6 1 2 0 0 0]I can't believe it―that slime worked!?[n]Did it have some kinda chemical[n]reaction with the meat or something?[n][f 1 3 65535][f 1 1][e]

[msg MSG_118 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 24 4 1 1][f 3 1 1 0 0 0]What a unique harmony of flavor and[n]aroma! This sauce is nothing less than[n]a miraculous collaboration.[n][f 1 3 65535][f 1 1][e]

[msg MSG_119 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 1 0 3][f 4 6 4 4 1 1][f 3 1 1 0 0 4051][f 6 1 2 0 0 6]Hear that, Yosuke? Our cooking skills[n]can't be beat![n][f 1 3 65535][f 1 1][e]

[msg MSG_120 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No, this was a miracle combined with[n]a coincidence... If not for the meat, this[n]would just be eggy, grassy slime.[n][f 1 3 65535][f 1 1][e]

[msg MSG_121 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 0]In any case, I think we should be able[n]to lure the carnivore with this.[n][f 1 3 65535][f 1 1][e]

[msg MSG_122 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 4][f 3 1 1 0 0 8122]Let's go set the bait before it gets cold.[n][f 1 3 65535][f 1 1][e]

