[msg MSG_000]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Dentro del conducto de aire...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16039][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Es mucho m茨s oscuro aqu胤 de lo que pensaba.[n]No puedo ver nada delante de m胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 16 0 0 0]　[n][f 3 1 1 0 0 0]Pensar que nos escabullimos a trav姻s de un[n]diminuto conducto como este... Esta es[n]una experiencia muy rara.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 13 0 0 0]　[n][f 3 1 1 0 0 0]Puede ser un poco presuntuoso de m胤, pero[n]esto realmente me hace sentir como si[n]fu姻ramos ladrones fantasma![n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1]Esto es bastante estimulante..[e]
[f 0 5 65278][f 2 1]Esto no es tan com雨n para nosotros..[e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26142][f 6 1 9 0 0 1]Vamos, siempre est茨s haciendo este tipo de[n]cosas, Joker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Hero]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 16 0 0 0]　[n][f 3 1 1 0 0 2018]夷Es as胤? Pens姻 que era lo habitual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]S胤, lo hacemos todo el tiempo. Es hasta el[n]punto que podr胤amos llamar Maestros Duct.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8013][f 6 1 9 0 0 1]Realmente es negro de lanzamiento en este[n]conducto, sin embargo... Ser胤a una gran[n]ayuda si tuvi姻ramos alg雨n tipo de fuente[n]de luz.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22013][f 6 1 9 0 0 1][f 6 1 2 0 0 4]Una especie de fuente de luz... 夷Tienes alguna[n]idea brillante, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1]Las gafas de Oracle..[e]
[f 0 5 65278][f 2 1]夷Y las funciones de Aigis??[e]
[f 0 5 65278][f 2 1]Usa tu fuego, Panther..[e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26018][f 6 1 9 0 0 1]S吋lo tengo un par. Y, por desgracia, est茨n[n]dise隠ados espec胤ficamente para m胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Pero te avisar姻 si encuentro algo 雨til.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5018][f 6 1 9 0 0 1]夷Tus ojos brillan como faros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 3]Me disculpo... Me falta cualquier forma de[n]funci吋n de luz.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Naoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8054][f 6 1 9 0 0 1][f 6 1 2 0 0 10]斡Espera, espera, espera! 斡No podemos usar[n]fuego en un espacio cerrado como este![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]夷Su fuego ser茨 suficiente? Puedo ayudar si[n]lo necesitas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]No recomiendo usar fuego aqu胤, estamos[n]garantizados para ser cocinados vivos dentro[n]de este conducto de aire.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 3]Hrgh, es tan oscuro y aterrador... 夷Ya estamos[n]cerca de la salida? 夷Podemos acabar[n]con esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4103][f 6 1 9 0 0 1][f 6 1 2 0 0 6]斡Ack! 斡Algo me toc吋 la cara! 斡Todo era[n]peludo![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17002][f 6 1 9 0 0 1]Arf, 斡斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4097][f 6 1 9 0 0 1]夷Fuiste t雨, Koro-chan? Eso me asust吋...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 21018][f 6 1 9 0 0 1][f 6 1 2 0 0 4]夷Eh? Pero pens姻 que Koromaru estaba delante[n]de m胤... hay algo que me toca la cara...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24029][f 6 1 9 0 0 1]Soy yo. Fox.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 21103][f 6 1 9 0 0 1][f 6 1 2 0 0 0]夷Waaaaagh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7027][f 6 1 9 0 0 1]夷Qu姻 pasa[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7099][f 6 1 9 0 0 1][f 6 1 2 0 0 0]夷Mmph?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23104][f 6 1 9 0 0 1][f 6 1 2 0 0 0]夷Mew?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7098][f 6 1 9 0 0 1]Wh-whoaa... Tan suave...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7137][f 6 1 9 0 0 1][f 6 1 2 0 0 8]Tal piel suave y suave en mi cara... Estoy[n]en el cielo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23105][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 6]斡Srooowgh! 斡Basta! 斡Deja de frotarte la cara[n]en mi trasero![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7099][f 6 1 9 0 0 1]斡Ay! 斡No me patees as胤![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7102][f 6 1 9 0 0 1][f 6 1 2 0 0 8]Oh... Pero maldita sea, esas almohadillas...[n]Intenta patearme otra vez...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23104][f 6 1 9 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Vale, nos vamos de aqu胤 ahora mismo! 斡Mu姻vete![n]斡Mu姻vete![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28009][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Mona, por favor deja de cavar tus garras en[n]mis piernas... 斡Ay![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4054][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Yo tambi姻n estoy haciendo da隠o aqu胤. 斡La[n]nariz de tu m茨scara me sigue cagando, Crow![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17001][f 6 1 9 0 0 1]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35012][f 6 1 9 0 0 1][f 6 1 2 0 0 4]夷QU畏 PASA? 夷POR QU畏 ME EST威S PONIENDO[n]NERVIOSO?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17002][f 6 1 9 0 0 1][f 6 1 2 0 0 7]Arf, 斡斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35014][f 6 1 9 0 0 1]夷"ES DIVERTIDO JUGAR CON TODOS"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]ESTE ES EL SENTIMIENTO... 夷DE VERDAD?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17014][f 6 1 9 0 0 1]Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]夷ME EST威S DANDO UNA AYUDA? 夷PARA QUE PODAMOS[n]SEGUIR YENDO JUNTOS?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17014][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35025][f 6 1 9 0 0 1][f 6 1 2 0 0 7]KOROMARU-SAN... MUCHAS GRACIAS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Vamos, 夷qu姻 pasa con la espera? Yosuke, 夷no[n]puedes ir un poco m茨s r茨pido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]No te quejes conmigo. 斡La parada es gracias[n]a Teddie aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3034][f 6 1 9 0 0 1][f 6 1 2 0 0 0]Hey, Teddie, obviamente eres demasiado grande[n]para este conducto! 夷Por qu姻 no te[n]quitaste el disfraz antes de entrar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Teddie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9031][f 6 1 9 0 0 1]Est茨 bien. Puedo seguir adelante si me empujas[n]desde atr茨s, Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3059][f 6 1 9 0 0 1][f 6 1 2 0 0 6]夷Qu姻 eres, carne de tierra en una m茨quina de[n]salchicha? 斡Deja de ser perezoso y mueve[n]tu propio cuerpo![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Makoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Whew... Esto va bastante lentamente, pero[n]supongo que todav胤a estamos progresando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Shinjiro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Estoy seguro de que llegaremos a la salida[n]eventualmente pero en serio... esta cosa[n]est茨 demasiado apurada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Akihiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Crawling es una buena forma de entrenamiento.[n]Aprieta tus abdominales y m雨sculos[n]latissimus dorsi para que puedas..[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Shinjiro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18036][f 6 1 9 0 0 1][f 6 1 2 0 0 6]C茨llate. 斡Pon esos m雨sculos a usar y sigue[n]movi姻ndose![n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Akihiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12034][f 6 1 9 0 0 1][f 6 1 2 0 0 2]夷Qu姻? Estoy usando esta oportunidad en lugar[n]de perder mi tiempo quejarme de estar[n]atascado..[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13034][f 6 1 9 0 0 1]夷Quieren callarse? Sigue as胤 y te congelar姻[n]los dos soli..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13104][f 6 1 9 0 0 1][f 6 1 2 0 0 0]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Haru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Perd吋name, Mitsuru-san. Me cogieron la mano[n]en la falda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]Veo... Por favor, no me sorprenda as胤. Es[n]dif胤cil de ver aqu胤, despu姻s de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11045][f 6 1 9 0 0 1]夷Qu姻 es esto? 夷Mitsuru-senpai no es fan de[n]la oscuridad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 7]Bueno, es una debilidad sorprendente para[n]ella. Una revelaci吋n impresionante que hace[n]a alguien como ella m茨s adorable..[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13047][f 6 1 9 0 0 1]Iori, 夷quieres que te congelen tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 10]斡Bromea! 斡Estaba bromeando![n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]夷Podr胤an darse prisa? Hace tiempo que esperamos[n]aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 19130]*giggle*[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10018][f 6 1 9 0 0 1][f 6 1 2 0 0 4]夷Eh? 夷Qu姻 es gracioso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 0]Es s吋lo que ustedes act雨an exactamente como[n]los compa隠eros que conozco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Veo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 19122]Lo siento por traer algo tan raro. 斡Vamos,[n]vamos![n][f 1 3 65535][f 1 1][e]

