[msg MSG_000 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 1][f 3 1 1 0 0 36013]... Cari隠o, has progresado hasta aqu胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pareces estar causando estragos por[n]toda mi sociedad justa, como quieras.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 36 1 0 1][f 4 6 26 4 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]As胤 que, 夷eres el Overseer, r-right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 36007]De hecho. Soy el Supervisor que gu胤a a[n]los robots de este mundo a su forma leg胤tima.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 36 1 0 1][f 4 6 26 5 0 3][f 4 6 11 6 0 6][f 3 1 1 0 0 11039][f 6 1 2 0 0 3]Gah, esa cara... S姻 que no es el[n]verdadero, pero todav胤a me est茨 dando los jeebies...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Overseer]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 6 1 25 0 0 0][f 4 6 35 7 0 3][f 4 6 36 12 0 0][f 3 1 1 0 0 0]UIY-2249: has desobedecido tus[n]mandamientos y has actuado sobre tu capricho personal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]No recuerdo haberle dado tales 吋rdenes.[n]夷Por qu姻 desafiaste tus 吋rdenes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ribbon]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 35 7 0 0][f 3 1 1 0 0 35014]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 0][f 3 1 1 0 0 36013]Ya que no puedes funcionar como est茨s[n]programado, pareces ser defectuoso despu姻s de todo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Defectuoso, 夷eh?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Eso no es verdad.[f 2 7 1 20 6 32][e]

[msg MSG_008 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 0][f 3 1 1 0 0 36007]Eso es correcto. Tener pensamientos[n]innecesarios, no actuar como programado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 0]Tal unidad perturba la armon胤a del[n]mundo, y obviamente debe ser eliminada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 0][f 3 1 1 0 0 36015][f 6 1 2 0 0 4]Qu姻 afirmaci吋n extra隠a. UIY-2249 es un robot.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 0]Si un robot no puede funcionar como[n]programado, claramente son defectuosos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tal unidad perturba la armon胤a del[n]mundo, y obviamente debe ser eliminada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 0 0][f 3 1 1 0 0 26099][f 6 1 2 0 0 6]Ribbon ya tiene una voluntad propia.[n]斡No vayas a forzar tus propias expectativas en ella![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 36009]夷Mis expectativas? No, esto es[n]simplemente el conjunto de normas, y el orden[n]adecuado, de este mundo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aqu胤, todos obedecen estos est茨ndares y[n]bajos en la serenidad que ofrecen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Serenidad? 斡No me hagas re胤r! 斡El[n]sufrimiento de Ribbon-chan no me parece ser serenidad![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 0]Esto se debe 雨nicamente al hecho de que[n]esta unidad es un error.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esta unidad, que no puede aceptar los[n]est茨ndares de nuestro mundo, y no puede[n]funcionar como programado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 6 1 25 0 0 0][f 4 6 35 6 0 0][f 3 1 1 0 0 35022]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 0][f 3 1 1 0 0 36001]UIY-2249, usted es, sin duda, un error[n]que debe ser eliminado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 1 6][f 3 1 1 0 0 26104][f 6 1 2 0 0 6]Ribbon![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 6][f 3 1 1 0 0 4036][f 6 1 2 0 0 6]夷Qu姻? 夷C吋mo pudiste?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ribbon]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35017][f 6 1 3 0 0 3]YO SOY... EST威 BIEN... TODOS, POR FAVOR.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No seas est雨pido! 斡No podemos dejarte aqu胤 as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 36004][f 6 1 2 0 0 4]夷Sigues defendiendo ese error? 夷Tambi姻n[n]se est茨n rebelando contra los[n]est茨ndares de este mundo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_021 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Al diablo con tus est茨ndares.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]No es un error.[f 2 7 1 20 6 32][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 6][f 3 1 1 0 0 21073][f 6 1 2 0 0 6]斡S胤! 斡Te preocupa que otros vean que no[n]eres siempre lo correcto![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todo lo que estamos haciendo es salvar[n]a nuestro compa隠ero, de nuestro propio[n]libre albedr胤o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19075]Es verdad que se[n]necesitan algunas reglas para una sociedad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Pero no son por encadenar a otros y[n]hacer que hagan todo lo que dices![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 0 3 6][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Nunca voy a estar de acuerdo en que[n]todo el mundo tiene que ser lo mismo para[n]que la vida sea lo mejor![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Overseer]]
[f 0 5 65278][f 2 1][f 4 6 36 0 0 0][f 3 1 1 0 0 36015]Si ignoras nuestros est茨ndares,[n]entonces eres contaminantes para nuestra[n]sociedad... Deben eliminarse las irregularidades.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 36 12 0 0][f 3 1 1 0 0 0]Antes de deshacerme de esa unidad[n]defectuosa, te deshar姻 primero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 4 6][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2116]斡Aqu胤 viene, chicos![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 20 0 1 0][f 4 6 21 6 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Tr茨elo. 斡Te vamos a meter en pasta de ordenador![n][f 1 3 65535][f 1 1][e]

