[msg MSG_000 [Sistema De Seguridad]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]INICIANDO VERIFICACI遺N DE SEGURIDAD...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 1][f 3 1 1 0 0 11060][f 6 1 2 0 0 0]斡夷Q-qu姻 dem...?![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Sistema De Seguridad]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]TIPO DE UNIDAD VERIFICADA... IW. N郁MERO[n]DE MODELO VERIFICADO... 02. CONFIRMACI遺N[n]DEL NIVEL DE SEGURIDAD...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Sistema De Seguridad]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]ERROR. SOLO LAS UNIDADES CON AUTORIZACI遺N[n]ADMINISTRATIVA PUEDEN ACCEDER A[n]ESTA ZONA.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]ACCESO DENEGADO. AUMENTANDO NIVEL DE[n]SEGURIDAD. INICIANDO PROTOCOLO DE[n]INTERCEPTACI遺N DE SEGURIDAD.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 11 0 0][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]Espera, 夷qu姻? 斡夷"Autorizaci吋n[n]administrativa"?![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Qu姻 se supone que hagamos? 夷Hacer que[n]escaneen a otra persona?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0]No... Probablemente, sea lo mismo con[n]todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esto no es bueno... Si intent茨ramos[n]pasar a la fuerza, un mont吋n de robots[n]de seguridad nos estar茨n esperando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 6][f 3 1 1 0 0 10009][f 6 1 2 0 0 4]Esto significa que no podemos seguir[n]adelante a menos que tengamos la[n]autorizaci吋n, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Dijo algo sobre un tipo de unidad y un[n]n雨mero de modelo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 1][f 3 1 1 0 0 0]EL TIPO DE UNIDAD ES LA SECUENCIA DE[n]LETRAS AL PRINCIPIO DE NUESTRA[n]IDENTIFICACI遺N.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]ESTA SE DETERMINA SEG郁N LA F威BRICA EN[n]LA SOMOS CONSTRUIDOS, Y TAMBI畏N EL[n]TIPO DE MODELO.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y ENTONCES, SE ASIGNA UN N郁MERO DE[n]MODELO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24076]Creo que fui etiquetada como "TK-04"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que, para m胤, "TK" es mi tipo de[n]unidad y "04" es mi modelo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 6][f 3 1 1 0 0 0]El m胤o era "YS-03."[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 0]AHORA QUE LO PIENSO, TODOS USTEDES TIENEN[n]DIFERENTES TIPOS DE UNIDAD.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]LOS ROBOTS PRODUCIDOS EN MASA COMO YO[n]SUELEN TENER EL MISMO...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 0]PERO T郁 ERES HUMANO. LA INCONSISTENCIA[n]EN LOS N郁MEROS DE MODELO DESAF緯A LA[n]L遺GICA.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 3 12 0 0][f 3 1 1 0 0 3084]Es decir, podr胤amos ser humanos, pero[n]no somos exactamente la misma[n]persona...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Donde nacimos, donde crecimos, nuestros[n]nombres y nuestras personalidades,[n]todo es diferente. Somos individuos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 1 0][f 3 1 1 0 0 0]斡Ja, ja, ja! 斡Este oso recibi吋 su propio[n]n雨mero individual y todo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Yo soy "YS-07"![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 1][f 3 1 1 0 0 28132]Mm, parece que el tipo de unidad se[n]establece seg雨n nuestras asociaciones[n]habituales.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Nosotros, los ladrones, somos "TK", el[n]Equipo de Investigaci吋n es "YS", y[n]SEES es... Um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 6][f 3 1 1 0 0 0]Soy "IW-06". Esto indica que nuestro[n]tipo de unidad es "IW".[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 0]Creo que soy "IW-00".[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 18 1 0][f 3 1 1 0 0 9023][f 6 1 2 0 0 4]夷Hrmm? 夷Pero no se le asign吋 "IW-00" a[n]la dama tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 6][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]S-s胤... Creo que tambi姻n soy "IW-00"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 35 1 0 1][f 4 6 22 8 1 3][f 3 1 1 0 0 22019][f 6 1 2 0 0 4]Espera, 夷c吋mo es posible? 夷Varias personas[n]pueden tener la misma identificaci吋n[n]exacta?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 0]NO, ES IMPOSIBLE. ESTE ES EL PRIMER CASO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Podr胤a ser por eso de... universos[n]paralelos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 1 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]LA MISMA IDENTIFICACI遺N... NORMALMENTE,[n]SER緯AN TRATADOS COMO ERRORES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 26018][f 6 1 2 0 0 4]Tratados como errores, 夷eh?... Espera,[n]斡un error![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Ahhh, ya s姻! 斡Lo tengo! 斡Creo que[n]podr胤amos pasar por aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡Oh, 夷qu姻 pasa? 夷Qu姻 tienes en mente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 26045][f 6 1 2 0 0 4]夷Qu姻 pasar胤a si dos personas, con el[n]mismo tipo de unidad y modelo, intentar茨n[n]cruzar al mismo tiempo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 1][f 3 1 1 0 0 0]Bueno, Ribbon dijo que eso no es posible,[n]夷verdad? Entonces... 夷No romper胤a[n]el sistema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26029]斡Exacto! Es posible que no podamos[n]desactivarlo, pero al menos causar茨 un[n]error y se bloquear茨.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Entonces, usemos eso a nuestro favor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500]斡Entiendo! Mientras el sistema est姻[n]bloqueado, alguien podr胤a pasar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 0]Mweheheh... 夷Tambi姻n la notaste, Fuuka?[n]夷Esa terminal all胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 26 1 0 3][f 4 6 14 2 100 1][f 3 1 1 0 0 14567]S胤, si alguien logra pasar, podr胤a usar[n]esa terminal para desactivar la[n]seguridad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 6 100 0][f 3 1 1 0 0 0]Pero la pregunta es, 夷qui姻n ir茨? Podr胤a[n]ser dif胤cil para alguien que no sea[n]bueno con las computadoras...[n][f 1 3 65535][f 1 1][e]

[sel SEL_030 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Vamos, Skull.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Adelante, Oracle.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Adelante, Aigis.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Lo har姻 yo mismo.[f 2 7 1 20 4 32][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 1][f 3 1 1 0 0 21012][f 6 1 2 0 0 9]Uhhh... Si todo lo que tengo que hacer[n]es correr hasta all胤, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 4][f 3 1 1 0 0 0]Pero necesitamos a alguien capaz de[n]desactivar el sistema de seguridad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Aigis]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 15 12 0 1][f 3 1 1 0 0 0]Yo lo har姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 1 6][f 3 1 1 0 0 26058][f 6 1 2 0 0 6]斡Ni hablar! 夷Esperas un milagro acrob茨tico[n]de m胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0]Mmm. Si necesitamos a alguien que pueda[n]moverse r茨pido y tambi姻n pueda[n]desactivar el sistema de seguridad...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Aigis]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 15 0 0 1][f 3 1 1 0 0 0]Lo har姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15068]Entendido. Lo har姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21045][f 6 1 2 0 0 4]Oh, no hay de qu姻 preocuparse si Joker[n]se encarga. 夷Est茨s listo, amigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 0]Espera...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si ocurre lo peor, 夷no ser胤a mejor que[n]nuestro l胤der se quedara atr茨s con[n]nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 0]De acuerdo, yo me encargo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 6][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 0]... 夷Segura, Aigis?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15029]Si lograra acceder directamente al[n]terminal, saltarse el protocolo de[n]seguridad ser胤a "pan comido".[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso si eso fuera imposible, el[n]programa de seguridad deber胤a detenerse[n]si disparo lo suficiente a la[n]terminal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Es un buen punto. 斡Yo voto por Aigis![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 10 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, Joker, 夷qu姻 dices?[n][f 1 3 65535][f 1 1][e]

[sel SEL_046 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Tienes raz吋n.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Ten cuidado, Aigis.[f 2 7 1 20 0 32][e]

[msg MSG_047 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 0][f 3 1 1 0 0 15069]Entiendo. Ahora debo hacer, es pedirles[n]que se coloquen en posici吋n para[n]poder iniciar la operaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 2 12 0 0][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 0]De acuerdo. 夷Todo lo que tenemos que hacer es pasar por all胤 al mismo tiempo, verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Oye, si algo sale mal, cualquier cosa...[n]aseg雨rense de correr, 夷de acuerdo?[n]斡Atacar ser茨 nuestro 雨ltimo recurso![n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Entonces, aqu胤 vamos. Por favor, funciona...[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Sistema De Seguridad]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]TIPO DE UNIDAD VERIFICADA... IW. N郁MERO[n]DE MODELO...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]...ERROR. N郁MEROS DE MODELO DUPLICADOS.[n]BUSCANDO EL PROCEDIMIENTO ADECUADO...[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Sistema De Seguridad]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]ERROR CR緯TICO. ERROR. ERROR. ERROR ERROR[n]ERROR ERROR...[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 6][f 3 1 1 0 0 26106][f 6 1 2 0 0 1]斡Aqu胤 vamos!... 斡Ahora![n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 4 1 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Voy![n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 0]Bien... ahora desactivar姻 el sistema de[n]seguridad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 3][f 3 1 1 0 0 26043][f 6 1 2 0 0 1]斡S胤! 斡Lo hicimos![n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 0]Bueno... Parece que result吋 bien. Aunque fue un poco aterrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡La buena noticia es que podemos seguir[n]adelante![n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 6 0 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19033]畏l y yo somos errores, 夷eh?...[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 27 0 0 0], 夷qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19018]夷Mm? Oh, 斡N-no es nada![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 3 1 1 0 0 0]斡M茨s importante, que r茨pida fuiste! 斡Esa[n]es la Aigis que conozco![n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 0]S胤, la operaci吋n fue un 姻xito. Sin[n]complicaciones.[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 4][f 3 1 1 0 0 14618]斡Bien, tengan mucho cuidado adelante![n][f 1 3 65535][f 1 1][e]

