[msg MSG_000 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 2 1][f 3 1 1 0 0 1]As胤 que este es el Cine... No puedo creer[n]que estemos dentro de una pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 7]夷Verdad? 斡Finalmente tengo que hacer mi debut[n]en la pantalla de plata![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 3]Me alegra que te hayan encontrado a tiempo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 4]Eres Hikari, 夷verdad? Es un placer[n]conocerte. Todos me han hablado de ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 5]Fueron a buscarte, y... Me alivia que est姻s[n]bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 6]Gracias por preocuparte por m胤 tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 7]Oh, um... Bueno, todos los dem茨s estaban muy[n]preocupados, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 8]Por cierto, alguien me dijo que no puedes[n]recordar c吋mo o por qu姻 viniste aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 9]M-Mmhm... Cuando me despert姻, ya estaba[n]aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 10]No te preocupes. Saldremos de este lugar[n]juntos, seguro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]... Por supuesto, eso puede parecer extra隠o[n]viniendo de alguien que acaba de llegar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 4 2 0][f 3 1 1 0 0 12]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 2 0 0 1][f 3 1 1 0 0 13][f 6 1 2 0 0 4]夷C吋mo est茨 Aigis?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 0][f 3 1 1 0 0 14]Al igual que sospechaba Mitsuru-senpai, parece[n]que s吋lo est茨 temporalmente bajada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 1 0 3][f 4 6 23 0 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]Futaba, 夷puedes echar una mano ah胤? Eres[n]bueno en cosas de techy as胤, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 16]Bueno, tengo habilidades de pirater胤a, pero[n]no soy mec茨nico...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]斡Pero! Har姻 lo que pueda, y tomar姻 una[n]galleta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 0 0 3][f 3 1 1 0 0 18]En ese caso, por favor s胤gueme...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19]夷C吋mo te fue, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 18 1 1][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Omigod... Est茨 compuesta de todas estas partes[n]locas con tecnolog胤a loca y... 斡De[n]todos modos, es una locura![n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Ah, ya veo...[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Eso no significaba nada.[f 2 7 1 64 6 32][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 6][f 3 1 1 0 0 21]Tampoco lo entiendo, pero entiendo la idea[n]de que es una locura.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 18 1 0][f 3 1 1 0 0 22]Parece que tiene una funci吋n autom茨tica de[n]auto-reparaci吋n, 斡las partes rotas se[n]est茨n arreglando solas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23][f 6 1 2 0 0 0]夷Qu姻 clase de tecnolog胤a hace eso? 斡Esto no[n]es nada menos que un mago de ciencia[n]ficci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 13 12 0 0][f 3 1 1 0 0 24]Todas sus funciones parecen funcionar[n]normalmente. No hay problemas para el momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 0][f 3 1 1 0 0 25]Est茨 muy drenada, pero a este ritmo, debe[n]recuperarse muy pronto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 26]Ya veo... Me alegro de que ella tambi姻n est姻[n]bien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 6][f 3 1 1 0 0 27]Lamento ser una molestia, pero vamos a tener[n]que dejar a Aigis en su cuidado hasta[n]que se recupere.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 2 1 0 1][f 4 6 1 0 0 3][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 28]Al menos esa es una preocupaci吋n menos con[n]la que preocuparnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 3 1 1 0 0 29]Debo darle las gracias de nuevo por su apoyo,[n]incluyendo ayudar a Aigis. Estoy muy[n]agradecido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30]夷Y t雨 eres...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 6][f 3 1 1 0 0 31]斡S胤, todav胤a no nos hemos presentado! Soy[n]Kanji Tatsumi, un primer a隠o en Instituto[n]Yasogami.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 10 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 0]夷Primer a隠o? As胤 que eres m茨s joven que yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 6][f 3 1 1 0 0 33][f 6 1 2 0 0 9]T姻cnicamente, podr胤a ser incluso m茨s joven[n]de lo que crees...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 34][f 6 1 2 0 0 4]夷Qu姻 significa eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 72 12 0 0][f 3 1 1 0 0 35]Todos nos hemos originado en diferentes[n]lugares... y en diferentes momentos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 36]No s吋lo eso, algunos de nosotros aparentemente[n]estamos tratando con experiencias a雨n[n]m茨s an吋malas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 19 7 0 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 37]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 2 1 0 1][f 4 6 72 0 0 3][f 3 1 1 0 0 38]Podemos ahorrar los detalles para m茨s[n]tarde...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39]Pero, b茨sicamente, hemos venido de mundos[n]separados, tan duro como para creer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 40]Ya veo... Muy bien, entonces.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 66 10 0 6][f 3 1 1 0 0 41][f 6 1 2 0 0 1]夷Est茨s bien con eso?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 42]Estoy empezando a sentirme por 姻l que me[n]recuerda mucho...[n][f 1 3 65535][f 1 1][e]

[sel SEL_036 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Siento que nos llevar胤amos bien.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Creo que est茨s imaginando cosas.[f 2 7 1 64 6 32][e]

[msg MSG_037 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 4][f 3 1 1 0 0 43]Te entiendo. Es muy parecido a nuestro propio[n]l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 4][f 3 1 1 0 0 44]夷En serio? Sabes, 姻l es muy similar a nuestro[n]propio l胤der, tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 69 0 0 6][f 3 1 1 0 0 45][f 6 1 2 0 0 4]Entonces, 夷tambi姻n eres el l胤der de Takeba[n]e Iori?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Chico Con Auriculares]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 3 1 1 0 0 46]S胤, a雨n no te he dicho mi nombre. Mi nombre[n]es...[n][f 1 3 65535][f 1 1][e]

