[msg MSG_000]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]En la Sala 3...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 13023]As胤 que, para salir de este lugar, creen que necesitamos cambiar las películas que se muestran en estas salas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Entend胤 bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 25067]S胤, esa es nuestra teoría.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bas茨ndonos en lo que hemos visto de la pel胤cula y su tráiler, creo que el objetivo es permitir la individualidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 4][f 3 1 1 0 0 18007]As胤 que debemos cambiar su forma de pensar, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 1][f 3 1 1 0 0 0]Adem茨s, necesitamos encontrar a nuestro l胤der y a Aigis.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 12071]No t姻rmino de entendedor eso de "entrar en las pel胤culas", pero parece que no hay tiempo para discutirlo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0]Tambi姻n me preocupan nuestros compa隠eros. 斡Estoy listo para dejar que mis puños dirijan el camino![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 0]*Suspiro* Mira a este tipo, sonriendo como un ni隠o... 斡Es mejor que no te vea corriendo solo![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 4 1 1][f 3 1 1 0 0 26003]Uh, um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 pasa, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26099][f 6 1 2 0 0 6]Mm... 斡Tengo que pedirles un favor![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Quiero unirme a ustedes en esta misi吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 21022][f 6 1 2 0 0 0]夷Qu姻? ¿Quieres venir a la pel胤cula con nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, 夷puedo? ¿Por favor?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Eso podr胤a ser muy 雨til.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ser茨 peligroso...[f 2 7 1 64 0 32][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 6][f 3 1 1 0 0 3013][f 6 1 2 0 0 4]S胤, entiendo eso... pero 夷no es un poco peligroso para tu navegadora hacer algo así?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26099]斡No, no, no, no te preocupes! Me he infiltrado en Palacios y Mementos con los Ladrones Fantasma antes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Adem茨s, 斡mis habilidades de pirater胤a serían super雨tiles en un mundo de ciencia ficci吋n! ¡Har姻 más bien allí que aquí fuera![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 26083]Pero, pero... me he infiltrado en Palacios y Mementos con ustedes en el pasado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 0]Adem茨s, 斡mis habilidades de pirater胤a serían super雨tiles en un mundo de ciencia ficci吋n! ¡Har姻 más bien allí que aquí fuera![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 68 4 1 0][f 3 1 1 0 0 24076]Entiendo. Ella tiene un punto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Dado que el mundo de esta pel胤cula est茨 controlado con electr吋nica, tener a Futaba con nosotros sería especialmente 雨til.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 23 0 0 4][f 3 1 1 0 0 23015]夷Qu姻 hacemos? Personalmente, no creo que nos venga mal, pero depende de ti.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Vamos todos juntos.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ven con nosotros.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Espero que tengas las agallas.[f 2 7 1 64 8 32][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26024][f 6 1 2 0 0 6]斡S胤! ¡Muchas gracias! ¡No te arrepentir茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26067][f 6 1 2 0 0 6]斡Genial! ¡Vamos, compa隠eros de grupo![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26069][f 6 1 2 0 0 4]Estoy... bueno, estar姻 bien. 斡Todo estar茨 bien! ¡Juro que no causaré ning雨n problema! 夷De acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 81 0 0 0][f 3 1 1 0 0 61012][f 6 1 2 0 0 4]...夷De verdad quieres entrar ah胤, Futaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0]Creo que esa pel胤cula est茨 equivocada. Quiero ser yo quien la cambie, sin importar lo que cueste.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61052]No... No entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 3 0][f 3 1 1 0 0 26031]Est茨 bien, solo mira la pel胤cula por mí, 夷de acuerdo? Hasta el final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61076]Mmm, estar姻 viendo... Por favor, vuelve...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 0][f 3 1 1 0 0 26070]斡Entendido![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 13122]Bien, deber胤amos irnos. Estoy muy preocupada por nuestros compa隠eros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 4][f 3 1 1 0 0 0]Tengan cuidado. Por favor, no hagan nada imprudente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21068][f 6 1 2 0 0 6]斡No hay problema! ¡Seguiremos arrasando![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 64095]Esos usuarios de Persona... parecen ser muy confiables.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]Mmm... Son tan fuertes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 0]No es que no crea en ellos, pero no puedo evitar preguntarme...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Realmente podremos salir de este lugar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 61018][f 6 1 2 0 0 4]夷Podr胤amos estar atrapadas en este cine para siempre?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 64016]Solo estoy planteando una situaci吋n hipot姻tica:[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si tuvi姻ramos que quedarnos aqu胤 para siempre... 夷Qué harías, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61016]...No lo s姻.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puede que no pueda hacer nada al respecto, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 0]Hikari...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Doe]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 82 1 0 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 64148]Doe...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 0][f 3 1 1 0 0 61065][f 6 1 2 0 0 0]斡夷...!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Doe]]
[f 0 5 65278][f 2 1][f 4 6 82 0 0 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 2 0][f 3 1 1 0 0 0]夷Qu姻 est茨s...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 16 2 6][f 3 1 1 0 0 64130]Est茨 bien, Hikari, estoy aqu胤 contigo...[n][f 1 3 65535][f 1 1][e]

