[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 16 1 3][f 3 1 1 0 0 1][f 6 1 2 0 0 0]斡Oracle! 夷C吋mo est茨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 2 1][f 3 1 1 0 0 2][f 6 1 2 0 0 10]Ella... todav胤a no se mueve... Sus luces[n]est茨n apagadas, tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 0][f 3 1 1 0 0 3]No... Intent吋 salvarnos, incluso si significaba[n]sacrificarse...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 0][f 3 1 1 0 0 4]Ribbon-chan era completamente diferente de[n]cuando la conocimos, cambi吋 tanto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 5]S胤... No hizo lo que le ordenaron. Pens吋[n]por s胤 misma, y actu吋 por sus propios[n]deseos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 2 0 0 6]Finalmente gan吋 una identidad... 斡No puede[n]terminar as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 4 0 6][f 3 1 1 0 0 7][f 6 1 2 0 0 0]Tch... 夷No hay nada que podamos hacer?[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Tenemos que intentarlo al menos.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Pero qu姻, exactamente?[f 2 7 1 20 8 32][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 1 2 0][f 3 1 1 0 0 8][f 6 1 2 0 0 6][f 6 1 3 0 0 1]S胤... 斡Me niego a dejar que esto le pase![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 99 0][f 3 1 1 0 0 9][f 3 1 6 0 0 500]Aigis, 夷podr胤as echar un vistazo tambi姻n?[n]Sus configuraciones de dise隠o son similares,[n]as胤 que tal vez...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 10]Entendido. Lo dar姻 todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 99 0][f 3 1 1 0 0 11][f 3 1 6 0 0 500]Aigis, 夷podr胤as echar un vistazo tambi姻n?[n]Sus configuraciones de dise隠o son similares,[n]as胤 que tal vez...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 4][f 3 1 1 0 0 12]Entendido. Lo dar姻 todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 1 2 0][f 3 1 1 0 0 13][f 6 1 2 0 0 6][f 6 1 3 0 0 1]斡Gracias![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14][f 6 1 2 0 0 6]Aguanta, Ribbon... 斡Estar茨s bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 3][f 3 1 1 0 0 15]Oracle... No sab胤a que le importaba tanto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 1][f 3 1 1 0 0 16]Ha pasado por mucho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 4][f 3 1 1 0 0 17]S胤, se destac吋 de la multitud por todas las[n]cosas que pod胤a hacer que otros no[n]pod胤an...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18]Creo que los problemas de Ribbon con su[n]individualidad realmente resonaron con[n]Oracle.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 19]Lo entiendo ahora...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20]La raz吋n por la que vino con nosotros a la[n]pel胤cula fue porque simpatiz吋 con Ribbon-san[n]en el trailer...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 15 2 1 4][f 4 6 26 1 2 1][f 3 1 1 0 0 21][f 6 1 2 0 0 6]斡Por favor despierta, Ribbon![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]Estoy seguro de que ser茨 un gran mundo de[n]aqu胤 en adelante...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23]Trabajaste tan duro... Estoy seguro de que[n]el mundo cambiar茨...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24]斡Por eso necesitas verlo por ti mismo! As胤[n]que... 斡s吋lo despierta![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 1 0][f 3 1 1 0 0 25]S胤... Tiene raz吋n. 斡Lo s姻! Esto va a ser un[n]mundo donde todos puedan vivir como[n]quieran.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26]Ser茨 un lugar maravilloso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Aigis]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 27][f 6 1 2 0 0 1]Ribbon-san![n][f 1 3 65535][f 1 1][e]

