[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 0 1][f 3 1 1 0 0 26062][f 6 1 2 0 0 6]Whoaaaaaa! Esto... 斡Esto es incre胤ble![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 0][f 3 1 1 0 0 0]夷Podr胤a ser una instalaci吋n utilizada[n]por humanos en el pasado?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 28015]Probablemente...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Aunque ahora, parece ser utilizado por[n]los robots para crear m茨s robots.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 4045][f 6 1 2 0 0 6]Wowww... 斡Esto es en serio como una[n]pel胤cula de ciencia ficci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3031]No hay nada como eso. Estamos[n]literalmente dentro de una pel胤cula de ciencia ficci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 0][f 3 1 1 0 0 7019][f 6 1 2 0 0 4]Eh, ciencia ficci吋n... 夷Cu茨les son esas de nuevo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 3037][f 6 1 2 0 0 6]Como acabo de decir, 斡esto! 斡Esto,[n]ahora mismo! 斡Lo que est茨s mirando ahora es[n]ciencia ficci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 9019][f 6 1 2 0 0 4]Oho... Entonces, 夷son helados y jugos[n]vendidos en mundos ciencia ficci吋n tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3036][f 6 1 2 0 0 6]夷C吋mo lo sabr胤a? 斡Es lo 雨ltimo que[n]necesitas ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 1 0 3][f 4 6 11 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oye, 夷crees que Yosuke podr胤a ser el[n]tipo sensacional?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 22013]Ahora que lo mencionas, siempre est茨[n]hablando como si su vida dependiera de ello...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 1][f 3 1 1 0 0 3041][f 6 1 2 0 0 6]夷Qu姻 m茨s se supone que haga? 斡Si les[n]dejo seguir adelante, las cosas saldr茨n[n]del control m茨s r茨pido de lo que pueden parpadear![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No entiendes por qu姻 mi snark es tan[n]importante, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Entiendo.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]No lo entiendo...[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]夷Qui姻n es el Joker?[f 2 7 1 20 0 32][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]夷Verdad? En serio, trato de haceros un[n]servicio aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]Si te quedas con nosotros lo[n]suficiente, lo conseguir茨s... Incluso despu姻s de[n]que no quieras m茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3065][f 6 1 2 0 0 6]斡T雨! 斡No me hagas arrancar esa m茨scara![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 6][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Pero, realmente es[n]gracias a Yosuke que las conversaciones del[n]Equipo de Investigaci吋n pueden continuar[n]as胤 como lo hacen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3045][f 6 1 2 0 0 6]斡Es mi compa隠ero! Realmente entiendes mis cosas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 18 0 0 0][f 3 1 1 0 0 18129]Cuando se re雨ne un gran grupo de[n]personas, es natural que el problema venga[n]tambi姻n. Todo depende de las personalidades.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 0]Los miembros de SEES tambi姻n est茨n[n]llenos de personalidad...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 16009]Todos hemos crecido acostumbrados a[n]nuestro grupo por ahora, pero supongo que[n]parecer胤a extra隠o para un extra隠o.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero en realidad es muy divertido, ya[n]que tenemos tantos tipos diferentes de[n]personas juntas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 24067]De hecho. Los usuarios de Persona que[n]hemos encontrado son muy fascinantes y[n]rebosantes de personalidad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24031]Me ha hecho darme cuenta de lo ordinario que soy.[n][f 1 3 65535][f 1 1][e]

[sel SEL_022 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]夷Ordinario?[f 2 7 1 20 8 32][e]
[f 0 5 65278][f 2 1]Correcto.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]夷De qu姻 est茨s hablando?[f 2 7 1 20 0 32][e]

[msg MSG_023 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 6][f 3 1 1 0 0 21023][f 6 1 2 0 0 0]夷Est茨s bromeando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0]Definitivamente no eres ordinario, Fox.[n]Si algo, eres... extremadamente 雨nico.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24064][f 6 1 2 0 0 0]夷Qu姻? 夷Es verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 10 12 0 0][f 3 1 1 0 0 0]As胤 que no ten胤as ni idea, 夷eh? Bueno,[n]supongo que as胤 es como es para gente 雨nica...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 24029]Supongo que necesito estudiar a todos[n]los dem茨s de cerca y aprender a ser m茨s 雨nico.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0]Ya eres demasiado 雨nico... En toda[n]honestidad, eres como la encarnaci吋n[n]viviente de lo raro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 24022][f 6 1 2 0 0 4]夷Dije algo peculiar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 6][f 3 1 1 0 0 0]Definitivamente no eres ordinario, Fox.[n]Si algo, eres... extremadamente 雨nico.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24059][f 6 1 2 0 0 0]夷Qu姻? 夷Es verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 10 12 0 0][f 3 1 1 0 0 0]As胤 que no ten胤as ni idea, 夷eh? Bueno,[n]supongo que as胤 es como es para gente 雨nica...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24013]Desde mi punto de vista, todos los[n]dem茨s parec胤an mucho m茨s 雨nicos que yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24031]Pero, tal singularidad es esencial para[n]el arte, as胤 que he elegido aceptar su[n]entrada como alabanza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 35 1 0 1][f 4 6 19 6 0 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19079]Bueno,[n]eso est茨 todo bien y bien, pero ese tipo[n]de individualidad no es algo que alaban[n]en este mundo, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35002]CORRECTO. LA INDIVIDUALIDAD ES UNA[n]EMERGENCIA. DIFERIR DE OTROS ES SECUNDARIO.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]SI LA CONTAMINACI遺N ATENTA A LA[n]INDIVIDUALIDAD, LA ARMONIA DE ESTE MUNDO SER緯A[n]DESHONRADA...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y SU GESTI遺N SE HUBIERA IDO MUY BIEN.[n]LA INDIVIDUALIDAD ES UNA EVIL ES NUESTRO PROGRAMA.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 21009][f 6 1 2 0 0 3]Supongo que eso probablemente tenga[n]sentido para el Overseer, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 0 0][f 3 1 1 0 0 0]Se te dice que no deber胤as existir,[n]s吋lo porque eres diferente, o raro?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 4 0 0][f 3 1 1 0 0 26099][f 6 1 2 0 0 6]... 斡Eso no es m茨s que forzar las[n]normas de alguien a todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 4][f 3 1 1 0 0 0]Oracle...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 13 12 0 0][f 3 1 1 0 0 13023]Estoy de acuerdo... Adem茨s, un mundo[n]homogeneizado ser胤a demasiado blando, y[n]cualquier armon胤a en 姻l ser胤a artificial.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35007]DE ACUERDO CON ESO, A郁N NO ESTOY[n]OCULTANDO NADA, PERO UN ALTAR EN ESTE MUNDO.[n][f 1 3 65535][f 1 1][e]

[sel SEL_041 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]No eres un error.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]El Overseer est茨 equivocado.[f 2 7 1 20 0 32][e]

[msg MSG_042 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]夷ESO ES AS緯?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 11037]S胤, quien haya decidido todas estas[n]leyes de mierda est茨 totalmente equivocado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]En serio, habla de un gobernante[n]totalitario. Ni siquiera piensa en la gente,[n]s吋lo le importa mantener el orden.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 4038][f 6 1 2 0 0 2]斡Pensando que me est茨 cabreando! 斡No[n]puedo esperar a que le arranquen esas tonter胤as![n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 1][f 3 1 1 0 0 26106][f 6 1 2 0 0 6]De acuerdo. 斡Tenemos que cambiar esta[n]pel胤cula en una que sea menos opresiva y divertida![n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 6][f 3 1 1 0 0 17001]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23107][f 6 1 2 0 0 6]Bueno, entonces, vamos a avanzar! Esta[n]es la fortaleza del enemigo, as胤 que no[n]decepciones a tu guardia![n][f 1 3 65535][f 1 1][e]

