[msg MSG_0000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mitsuru parece estar perdido en el[n]pensamiento...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 1]Digamos, [f 6 1 26 0 0 0], sobre su mundo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 2]Se dirigi吋 al ba隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 3]Ya veo... *Suspira*[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 6][f 3 1 1 0 0 4]Est茨s mirando hacia abajo en los vertederos.[n]Quiero decir, puedo entender por qu姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 0 0 1][f 3 1 1 0 0 5]Si [f 6 1 27 0 0 0] est茨 diciendo la verdad,[n]entonces esto es a雨n m茨s como una historia[n]de ciencia ficci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷No significa que hay otro en el que no sepa[n]nada?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 7]Me he preguntado sobre ese tipo de cosas[n]antes, pero... 夷es realmente posible?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 8]Otro yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9][f 6 1 2 0 0 7]Oh hombre, 夷qu姻 pasa si ese yo es un modelo[n]totalmente atroz y un 姻xito con todas[n]las damas de todo el mundo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 6][f 3 1 1 0 0 10]No hay posibilidad de que existas as胤. La[n]雨nica manera que podr胤a suceder es si fueras[n]reencarnado como una persona[n]diferente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Adem茨s, considerando la forma en que te habl吋,[n]dudo que seas diferente en su mundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 14 12 0 3][f 3 1 1 0 0 12]Hay algo que olvid姻 mencionar antes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13]Cuando el Ladrones Fantasma y el Equipo de[n]Investigaci吋n llegaron a nuestro rescate[n]en la pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Por un momento, Luc胤a confundi吋 a[n][f 6 1 27 0 0 0] con nuestra l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 4][f 3 1 1 0 0 16]Oh, lo entiendo, sin embargo. Su personalidad[n]es diferente, pero tiene, como... una[n]vibra similar, de alguna manera?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Me recuerda a nuestro l胤der. No puedo[n]explicarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 18]S胤. Se supone que es mi primera vez que la[n]encuentro, pero se siente tan natural con[n]ella alrededor... 夷Por qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 17 0 0 1][f 3 1 1 0 0 19][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 4][f 3 1 1 0 0 20]Parece que Koromaru est茨 de acuerdo contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 18 0 0 3][f 3 1 1 0 0 21]Bueno, no estamos imaginando nada parado as胤.[n]Tr茨tala como todos y estar茨 bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 1][f 3 1 1 0 0 22]Tienes raz吋n. En cualquier caso, necesitamos[n]priorizar el rescate de nuestro l胤der[n]y Aigis.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0][f 6 1 27 0 0 0] Est茨 viendo a los estudiantes de Instituto[n]Gekkoukan desde una distancia...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 23]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 24][f 6 1 26 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 25]斡Aah! Me sorprendiste...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 3 1 1 0 0 26][f 6 1 2 0 0 4]Lo siento, me espaci姻... Eheh. 夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 6][f 3 1 1 0 0 27]夷Por qu姻 no te unes a ellos, a menos que sea[n]demasiado inc吋modo, o algo as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 28]Quiero decir, puedo entender por qu姻 est茨n[n]tan confundidos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Pero cuando pienso en c吋mo esto la est茨 haciendo sentir, es simplemente[n]desgarrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 30]斡Aha! Estoy totalmente bien, sin embargo,[n]cosas como universos paralelos es tan[n]ciencia ficci吋n![n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]No te presiones demasiado.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Estamos aqu胤 por ti.[f 2 7 1 64 0 32][e]

[msg MSG_024 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 31]*giggle* Gracias... Est茨s tratando de animarme,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 32]Bueno, [f 6 1 26 0 0 0], hab胤as estado[n]tan preocupado por tus compa隠eros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 33]Gracias, todos sois muy amables...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 34]Pero, incluso si no saben de m胤, todav胤a son[n]preciosos compa隠eros m胤os.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35]Eso nunca cambiar茨, y no quiero que lo haga.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 3 1 1 0 0 36][f 6 1 2 0 0 6]斡Por eso estoy planeando hacer mi mejor[n]esfuerzo para buscar a su l胤der y Aigis![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 37]... Eres tan fuerte, [f 6 1 26 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 38]*giggle* 夷T雨 crees? Probablemente sea porque[n]tengo a todos aqu胤 apoy茨ndome.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39]Si estuviera solo, no habr胤a podido llegar[n]hasta aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 1 0 0][f 3 1 1 0 0 40][f 6 1 2 0 0 6]...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 41]S胤, yo tambi姻n... Me alegro de conocerlos a[n]todos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 4 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 42]斡Muy bien! Seguir姻 haciendo lo mejor que[n]pueda, 斡s吋lo mira![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 43][f 6 1 2 0 0 6]Mmhm![n][f 1 3 65535][f 1 1][e]

