[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 1][f 3 1 1 0 0 1]Bueno, al menos nos ocupamos de esa cerradura[n]sin problemas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 2]Estamos en la 雨ltima cerradura...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Ahora no es el momento de pensar en eso, sin[n]embargo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 70 6 1 1][f 3 1 1 0 0 4]斡As胤 es! 斡Tenemos que darnos prisa y encontrar[n]a Hikari![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 3][f 3 1 1 0 0 5]Ese timbre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Intercomunicaci吋n Del Teatro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 9 0 0 1]Tenemos un anuncio para nuestros clientes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7][f 6 1 9 0 0 1]Una nueva pel胤cula comenzar茨 a aparecer en[n]el Cine 4 moment茨neamente. Repito...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Intercomunicaci吋n Del Teatro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8][f 6 1 9 0 0 1]Una nueva pel胤cula... empezar茨... mostrando...[n]Cine 4...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9][f 6 1 9 0 0 1]Por favor... ven a ver la pel胤cula... no[n]importa qu姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 10 0 1][f 3 1 1 0 0 10][f 6 1 2 0 0 0]Espera, 夷no era la 雨ltima l胤nea?[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Es de esa carta de invitaci吋n.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No puedo recordar de d吋nde viene...[f 2 7 1 64 8 32][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 4][f 3 1 1 0 0 11]Ya veo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12]Fue la misma petici吋n que el escrito en la[n]carta de invitaci吋n que Hikari[n]descubri吋.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yusuke]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 68 2 1 1][f 3 1 1 0 0 13]As胤 es... 夷Qu姻 est茨 pasando aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 1 0][f 3 1 1 0 0 14]Hikari, por favor est姻 a salvo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 7 11 0 0][f 4 6 65 6 4 1][f 3 1 1 0 0 15]斡Arrrgh! 斡No tiene sentido correr nuestras[n]bocas aqu胤![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16]Esa cosa dijo Cine 4, 夷verdad? 斡Entremos y[n]salvemos a Hikari![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Rise]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 6 2 1 1][f 3 1 1 0 0 17]斡Otra puerta de Cine est茨 abierta![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 4][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 18]Ese anuncio justo ahora... Significa que[n]otra pel胤cula empez吋 a tocar, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 66 0 1 0][f 3 1 1 0 0 19]斡Espera! 夷Qu姻 hay de Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Fuuka]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 10][f 4 6 14 6 0 1][f 3 1 1 0 0 20]No pod胤amos encontrarla en ning雨n lado, sin[n]embargo... Ni siquiera estoy segura de[n]que est姻 aqu胤 en el Cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 21]Lo mismo aqu胤 - no pod胤amos encontrarla[n]tampoco. Eso significa que el 雨nico lugar[n]que queda es...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 22]... Dentro de la pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 1][f 3 1 1 0 0 23]Ten胤a la sensaci吋n de que 胤bamos a entrar[n]ah胤. Estamos listos para ir siempre.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 4][f 3 1 1 0 0 24]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Morgana]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 23 12 1 0][f 3 1 1 0 0 25]斡Vamos, todos! 斡Que nadie deje caer a sus[n]guardias![n][f 1 3 65535][f 1 1][e]

