[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 19 10 0 3][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19018][f 6 1 2 0 6]...![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 1][f 3 1 1 0 0 0]Un ambiente diferente de la pel胤cula anterior.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Esta parece ser una pel胤cula de ciencia[n]ficci吋n, pero ese trailer dej吋 un poco[n]de mal gusto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7037]Ser diferente es malo, 夷eh? 斡Qu姻 mierda![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 70 0 0 1][f 3 1 1 0 0 26039]Entonces, la individualidad es inexcusable...[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷Qu姻 pasa?[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Qu姻 pasa, Futaba?[f 2 7 1 64 2 32][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 26008]No es nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 1 0 3][f 6 1 25 0 0 0][f 4 6 81 1 0 6][f 3 1 1 0 0 61004]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 4 2 0][f 3 1 1 0 0 64009][f 6 1 2 0 0 4]Oye, Hikari-san: 夷cu茨les son tus[n]sentimientos en esta pel胤cula hasta ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Ese robot est茨 siendo tratado tan[n]mal... todo por ser diferente... Incluso[n]siendo llamado "mal"...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si hubiera intentado ser lo mismo que[n]todos los dem茨s... 夷no podr胤a evitar todo[n]ese problema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 1][f 3 1 1 0 0 26135][f 6 1 2 0 0 0]夷Eh? 夷Realmente piensas eso, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 1][f 3 1 1 0 0 9040]Ohhh nooo... Todo el mundo tiene que[n]ser el mismo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, 夷por qu姻 existo como Teddie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0 1029]Teddie...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]Sensei y Yosuke y todos los dem茨s son[n]diferentes, y me gusta cada uno de ellos[n]por qui姻n son...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]As胤 que... me hace tan triste que todos[n]deber胤an ser iguales. Waaaaah...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 6][f 3 1 1 0 0 3051]斡Tiene la idea correcta! Teddie es[n]Teddie, y yo soy yo, como deber胤a ser.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 81 6 2 0][f 3 1 1 0 0 61052]Yo, ah...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ser胤a mejor que no me quedara...[n]Necesito actuar normal y mezclarme con la sociedad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Eso es lo que siempre pens姻... hasta ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 1][f 3 1 1 0 0 26135][f 6 1 2 0 0 4]夷Y ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 7 2 0][f 3 1 1 0 0 61055]Viendo a todos en esas pel胤culas...[n]Empec姻 a sentirme mal...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 0]Pero no estoy seguro. No puedo decirlo m茨s...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 3 0][f 3 1 1 0 0 26031]Ah, ya veo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 2 0 1][f 3 1 1 0 0 4106][f 6 1 2 0 0 6]斡Aaaaalright! 斡Levant姻monos en esa pel胤cula![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Cuanto antes lo cambiemos, antes[n]salimos de aqu胤. 斡Es hora de revisar esta[n]trama de mierda![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 0]斡Correcto! Y, si lo hacemos, Hikari[n]puede que no se sienta tan confundido con[n]sus sentimientos tampoco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 0 4 1][f 1 5][f 6 1 28 0 0 0][f 3 1 0 0 19005]Hang on, everyone! Hay[n]algo que deber胤as escuchar antes de que[n]saltemos a la pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El robot principal en ese trailer me[n]era familiar, lo mismo va para el t胤tulo, tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0][f 6 1 2 0 4]夷Qu姻 quieres decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19113] Ese robot con la[n]cinta parec胤a un amigo m胤o... Su nombre es Aigis.[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷No es tambi姻n el t胤tulo de la pel胤cula?[f 2 7 1 64 8 32][e]
[f 0 5 65278][f 2 1]夷Eres amigo de un robot?[f 2 7 1 64 0 32][e]

[msg MSG_025 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 0][f 3 1 1 0 0 27094][f 6 1 2 0 0 4]El trailer pronunci吋 el t胤tulo como[n]"A-I-gis", pero lo pronunciaste como "AI-gis"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que la parte "AI" significa[n]inteligencia artificial, pero la parte "GIS"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0]Mmhm, y el nombre de mi[n]amigo se escribe exactamente de la misma[n]manera. No puedo imaginar que sea una[n]mera coincidencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 1 0 3][f 4 6 9 10 0 6][f 3 1 1 0 0 9046]No te preocupes, 夷eres amigo de un[n]robot? Puedo creerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 3][f 3 1 1 0 0 23016]S胤, esto es realmente tomar un giro[n]para lo extra隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3010][f 6 1 2 0 0 9]夷Ustedes dos acaban de decir eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 6][f 3 1 1 0 0 9046]夷Eres amigo de un robot? Puedo creerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 3][f 3 1 1 0 0 23016]S胤, esto es realmente tomar un giro[n]para lo extra隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3010][f 6 1 2 0 0 9]夷Ustedes dos acaban de decir eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 1][f 4 6 71 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]El trailer pronunci吋 el t胤tulo como[n]"A-I-gis", pero lo pronunciaste como "AI-gis"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que la parte "AI" significa[n]inteligencia artificial, pero la parte "GIS"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 19068]Mmhm, y el nombre de[n]mi amigo se escribe de la misma manera.[n]No puedo imaginar que sea una mera coincidencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19053] Es cierto que Aigis[n]es un robot, pero no pensamos en ella[n]de manera diferente de lo que hacemos el[n]resto de nuestros amigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 3 1 1 0 0 0]Ella tiene su propia identidad, y sus[n]propias opiniones, tambi姻n. La tratamos[n]como nuestra compa隠era, no s吋lo un robot.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61012]Un compa隠ero... con identidad...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 0]Lo que hemos determinado hasta ahora es[n]que alguien que conocemos tambi姻n ha[n]sido lanzado a esta pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 0]De hecho. Primero, el mundo de[n]Kamoshidaman; luego, el mundo de Yosukesaurus.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]S吋lo tiene sentido que lo mismo[n]ocurrir胤a con esta tercera pel胤cula, tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 0][f 3 1 1 0 0 22113][f 6 1 2 0 0 4]Bueno, tal vez la tercera vez es el[n]encanto y [f 6 1 27 0 0]-chan los[n]compa隠eros est茨n en este, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19099][f 6 1 2 0 6]T雨 tambi姻n lo crees!? 斡Entonces, vamos a[n]apresurarnos y encontrarlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 64009]As胤 que est茨s decidido a editar la[n]pel胤cula una vez m茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 0]Si usted siente que usted est茨 en[n]cualquier peligro, por favor vuelva aqu胤 inmediatamente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19129][f 6 1 2 0 6]斡Por[n]supuesto! 斡Estaremos en camino ahora![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 80 1 0 3][f 4 6 74 1 4 1][f 3 1 1 0 0 54014]...Theo. Su invitado desea reunirse con[n]sus compa隠eros m茨s fervientemente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Durante tiempos como estos, un munch*[n]夷Cu茨l crees que ser胤a el mejor curso para tomar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 0][f 3 1 1 0 0 0]Tendremos que cuidarla. Es todo lo que[n]podemos hacer...[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 1 4 0][f 3 1 1 0 0 54016]Entonces... Centr姻monos en observarlos[n]de cerca, con palomitas en la mano... *Munch*[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Hermana... 夷Podr胤as concentrarte en[n]comer o hablar, y no hacer ambas cosas al[n]mismo tiempo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 18 2 3][f 3 1 1 0 0 61133]Todos... Por favor, vuelve a salvo...[n][f 1 3 65535][f 1 1][e]

