[msg MSG_000]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Dentro del Cine 3...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 13023]As胤 que, para salir de este lugar, crees que[n]necesitamos revisar el contenido de las[n]pel胤culas que se muestran en estos[n]Cines...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Puedo entender su explicaci吋n correctamente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 25067]S胤, eso es lo que pensamos hasta ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Basado en el contenido de la pel胤cula y su[n]trailer, creo que su objetivo es pintar[n]la individualidad en una luz negativa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 4][f 3 1 1 0 0 18007]As胤 que lo que dices es que acabamos de[n]destruir su forma de pensar, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 1][f 3 1 1 0 0 0]Adem茨s, necesitamos encontrar a nuestro l胤der[n]y Aigis-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 12071]No tengo todo este "ir dentro de las pel胤culas"[n]y lo que no, pero parece que no[n]tenemos tiempo para discutirlo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0]Tambi姻n me preocupan nuestros compa隠eros.[n]斡Estoy listo para dejar que mis pu隠os[n]dirijan el camino![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 0]Mira a este tipo, sonriendo como un ni隠o...[n]斡Mejor no verte ir corriendo sola![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 4 1 1][f 3 1 1 0 0 26003]Uh, um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 pasa, Futaba-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26099][f 6 1 2 0 0 6]Um... 斡Tengo un favor que pedir![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Quiero unirme a ustedes en la misi吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 21022][f 6 1 2 0 0 0]夷Qu姻? 夷Quieres venir a la pel胤cula con[n]nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, 夷verdad? 夷Por favor?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Eso podr胤a ser muy 雨til.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ser茨 peligroso...[f 2 7 1 64 0 32][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 6][f 3 1 1 0 0 3013][f 6 1 2 0 0 4]S胤, lo entiendo... 夷pero no es peligroso que[n]tu navegante haga algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26099]No, no, no te preocupes. He infiltrado Palacios[n]y Recuerdos con los Fantasmas en el[n]pasado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Adem茨s, mis habilidades de pirater胤a ser胤an[n]s雨per 雨tiles en un mundo de ciencia[n]ficci吋n! 斡Har姻 m茨s bien que aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 26083]Pero... He infiltrado Palacios y Recuerdos[n]con ustedes en el pasado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 0]Adem茨s, mis habilidades de pirater胤a ser胤an[n]s雨per 雨tiles en un mundo de ciencia[n]ficci吋n! 斡Har姻 m茨s bien que aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 68 4 1 0][f 3 1 1 0 0 24076]Ya veo. Tiene un punto v茨lido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Dado que el mundo de esta pel胤cula est茨[n]controlado con electr吋nica, tener Futaba con[n]nosotros ser胤a especialmente 雨til.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 23 0 0 4][f 3 1 1 0 0 23015]夷Cu茨l es tu decisi吋n? Personalmente, creo[n]que estar胤a bien, pero depende de ti.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Vamos todos juntos.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ven con nosotros.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Espero que tengas las agallas.[f 2 7 1 64 8 32][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26024][f 6 1 2 0 0 6]斡S胤! Muchas gracias, 斡no te arrepentir茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26067][f 6 1 2 0 0 6]斡Genial! 斡Adelante, compa隠eros de partido![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 26069][f 6 1 2 0 0 4]Bueno, estar姻 bien, estar茨 bien. 斡Juro que[n]no causar姻 ning雨n problema! 夷De acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 81 0 0 0][f 3 1 1 0 0 61012][f 6 1 2 0 0 4]... 夷De verdad quieres entrar ah胤,[n]Futaba-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0]Creo que esa pel胤cula est茨 mal. Quiero ser[n]el que lo cambie, no importa lo que sea[n]necesario.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61052]Yo... No entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 3 0][f 3 1 1 0 0 26031]Est茨 bien, por ahora, s吋lo mira la pel胤cula[n]para m胤, 夷de acuerdo? Hasta el final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61076]Estar姻 viendo... Por favor, vuelve a salvo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 0][f 3 1 1 0 0 26070]斡Entendido![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 13122]Bueno, deber胤amos estar en camino. Estoy[n]creciendo m茨s preocupado por nuestros[n]compa隠eros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 4][f 3 1 1 0 0 0]Ten cuidado, todos. Por favor, no hagas nada[n]imprudente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21068][f 6 1 2 0 0 6]斡Sin prob! 斡Seguiremos pateando el culo![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 0][f 3 1 1 0 0 64095]Esos persas... Parecen ser muy confiables.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]Mmhm... Son tan fuertes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 0]No decir que no creo en ellos, pero no puedo[n]evitar preguntarme...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Seremos realmente capaces de salir de este[n]lugar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 61018][f 6 1 2 0 0 4]夷Podr胤amos estar atrapados en este cine para[n]siempre?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 64016]S吋lo estoy proponiendo una situaci吋n[n]hipot姻tica:[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si resulta que debemos permanecer aqu胤 para[n]siempre... 夷qu姻 har胤as, Hikari-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61016]... No lo s姻.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puede que no pueda hacer nada al respecto,[n]pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 0]Hikari-san...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Doe]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 82 1 0 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 64148]Doe...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 0][f 3 1 1 0 0 61065][f 6 1 2 0 0 0]...!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Doe]]
[f 0 5 65278][f 2 1][f 4 6 82 0 0 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 2 0][f 3 1 1 0 0 0]夷Qu姻 eres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 16 2 6][f 3 1 1 0 0 64130]Est茨 bien, Hikari-san... Estoy aqu胤[n]contigo...[n][f 1 3 65535][f 1 1][e]

