[msg MSG_000 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 1][f 3 1 1 0 0 10109][f 6 1 2 0 0 3]斡Vaya! Este lugar es enorme. Siento que[n]todav胤a tenemos muchas maneras de ir,[n]tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻, ya cansado?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 10010][f 6 1 2 0 0 3]No, es algo m茨s mental. Explorar un lugar[n]desconocido como este puede ser agotador...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Pero, definitivamente puedo seguir adelante![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 25079]Eso plantea un buen punto, sin embargo,[n]tenemos unos cuantos miembros que son nuevos[n]en nuestro proceso. No deber胤amos[n]exagerar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Tomemos descansos peri吋dicos mientras avanzamos.[n]Todo esto ser胤a in雨til si nos llevamos[n]al agotamiento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 13023][f 6 1 2 0 0 4]As胤 que, he crecido curiosidad por ti Ladrones[n]Fantasma - 夷Tu vestido no te pesa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 4][f 3 1 1 0 0 0]Tambi姻n me he estado preguntando...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Partes de tu traje, como la capa y los picos,[n]parecen tan pesados, pero te mueves[n]tan r茨pido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11045][f 6 1 2 0 0 4]Ooh, 夷realmente vamos all胤?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Cuz quiero saber tambi姻n! 夷Cu茨les son los[n]secretos detr茨s de tu ropa?[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es una larga historia...[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]As胤 son las especificaciones.[f 2 7 1 20 2 32][e]

[msg MSG_008 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25089][f 6 1 2 0 0 9]Cierto, es bastante dif胤cil de explicar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 0]Es como son las especificaciones. Hecho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 0][f 3 1 1 0 0 22033][f 6 1 2 0 0 10]Heheh... Si tuviera una mejor explicaci吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 5 2 0 1][f 3 1 1 0 0 5032]Creo que son geniales. El atuendo de todos[n]es muy elegante, y les queda bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 28052]S胤, nuestras personalidades se expresan[n]claramente a trav姻s de ellas. Me gusta mucho[n]el m胤o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 0]Crow, tu m茨scara parece que hace un buen[n]trabajo cuidando tu nariz.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 4][f 3 1 1 0 0 4031][f 6 1 2 0 0 4]Eso es verdad, pero 夷no har胤a que alguien[n]estuviera delante de 姻l en la cabeza?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]Eso significa que tiene una s吋lida ofensa y[n]defensa. Cuando lo consideres, apuesto[n]a que es incluso mejor que gag gafas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 0][f 3 1 1 0 0 28033][f 6 1 2 0 0 4]Haha, gracias por el... elogio, supongo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 10 0 0 1][f 3 1 1 0 0 10089][f 6 1 2 0 0 4]夷Y qu姻 hay de lo que se llaman, como Joker[n]y Mona? 夷Son apodos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Son nuestros nombres de c吋digo.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Son nuestros nombres espirituales.[f 2 7 1 20 0 32][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 23052]As胤 es.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 14 1 6][f 3 1 1 0 0 23085][f 6 1 2 0 0 6]斡Vamos! 斡Son nombres de c吋digo![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 1][f 3 1 1 0 0 16047][f 6 1 2 0 0 4]Nombres de c吋digo... 夷C吋mo los eliges?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 26 12 0 0][f 3 1 1 0 0 0]Se basa principalmente en c吋mo lucen nuestros[n]trajes o nos hacen sentir. 夷Ustedes[n]tambi姻n quieren algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 4][f 3 1 1 0 0 11045][f 6 1 2 0 0 6]斡S胤! 斡S吋lo pensaba que era hora de que yo[n]tomara un t胤tulo![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0]Entonces, son como nombres de anillo... Eso[n]no suena mal. Yo tambi姻n tomar姻 uno, si[n]no te importa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 1][f 3 1 1 0 0 17001][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 1 0 3][f 4 6 12 1 0 1][f 4 6 8 0 0 4][f 3 1 1 0 0 8022]夷No hemos aprendido d吋nde nos lleva esta[n]conversaci吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 22032][f 6 1 2 0 0 6]Vamos, ser茨 divertido. 斡Tienes que ir con el[n]flujo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22017][f 6 1 2 0 0 4]As胤 que, si lo basamos en c吋mo se ve Sanada,[n]tal vez... 夷Boxer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 4][f 3 1 1 0 0 0]夷No es algo sencillo? El primer nombre clave[n]que viene a mi mente para 姻l es[n]Protein...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 4][f 3 1 1 0 0 18129]S胤, ve con eso. Incluso le encanta verter[n]prote胤na en polvo en su arroz.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 22 1 0 0][f 4 6 12 8 1 0][f 3 1 1 0 0 12002][f 6 1 2 0 0 2]斡Dame un respiro! 夷Puedes siquiera pensar en[n]un nombre de c吋digo para m胤 que no tiene[n]que ver con la prote胤na, Shinji?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 0][f 3 1 1 0 0 18093][f 6 1 2 0 0 6]Incluso si me tomara el tiempo para pensar[n]en uno, 斡todav胤a seguir胤as con la prote胤na[n]de todos modos! 夷Por qu姻 deber胤a[n]molestarme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 8 1 0][f 3 1 1 0 0 12062][f 6 1 2 0 0 2]斡No hagas que suene como si fuera lo 雨nico[n]que hablo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]S吋lo soy tan particular con la prote胤na porque[n]es el principal nutriente que el cuerpo[n]necesita..[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19090]Bueno, 斡as胤 que Akihiko-senpai es Protein![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Y la Srta. Pink para Yukari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 10 10 0 1][f 3 1 1 0 0 10019][f 6 1 2 0 0 0]夷Eh? 斡Yo tambi姻n voy a conseguir uno?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Eso es un punto! Tiene ese aire de autoridad,[n]斡pero tambi姻n suena lindo![n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19130]夷Verdad? Adem茨s, sus trajes y accesorios son[n]abrumadoramente rosados.[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 0 0][f 3 1 1 0 0 10050][f 6 1 2 0 0 0]夷C吋mo lo sabes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Claro, ya me conoces. Me olvid姻... Lo siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ken]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 17 1 0 4][f 4 6 16 12 0 1][f 3 1 1 0 0 16009]U-Um... 夷Puede Koromaru y yo conseguir c吋digos[n]tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Amada es una peladora de lanza, as胤 que[n]tal vez... 夷Lancer? 夷Es demasiado claro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19011]Si la Srta. Pink de Yukari, 夷qu姻 tal el Sr.[n]Black para Ken?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 1 0][f 3 1 1 0 0 16086]Se隠or Black... No est茨 mal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso en Featherman, Black se representa[n]como un tipo fresco, "lobo solitario" con[n]un alto nivel de madurez...[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19130]Plus, siempre est茨s tratando tan duro de[n]hacerte como caf姻 negro![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 10 0 0][f 3 1 1 0 0 16018][f 6 1 2 0 0 0]夷Eh? 夷Lo sabes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]¡Arf, Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24076]Veamos... Para Koromaru, 夷qu姻 tal, Hellbeast[n]Summoned from the Infernal Depths?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 6 0 0][f 3 1 1 0 0 17008]*whine*[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 0]Parece que tus nombres son demasiado pr吋ximos[n]para la escena del perro, Inari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 11 2 0 1][f 3 1 1 0 0 11006][f 6 1 2 0 0 4]Muy bien, yo siguiente, yo siguiente! Entonces,[n]夷qu姻 tipo de nombre de c吋digo crees[n]que me queda mejor?[n][f 1 3 65535][f 1 1][e]

[sel SEL_049 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Goatee.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Geezer.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Ace Detective.[f 2 7 1 20 2 32][e]

[msg MSG_050 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]夷Eso es todo lo que me ves?[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 1 0][f 3 1 1 0 0 5031][f 6 1 2 0 0 6]Eso es demasiado obvio... Snrk, Heehee...[n]Aha, ahahahahaha![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 6][f 3 1 1 0 0 27030]Ven ahora... Es grosero re胤rse de eso,[n]Yukiko... *Grecha*[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ustedes dos se divierten mucho con esto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 23071]S胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 4 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Junpei no es un geezer. 斡Es s吋lo un estudiante[n]del instituto que s吋lo se parece a un[n]geezer![n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11055][f 6 1 2 0 0 6]斡No est茨s ayudando! Si algo, entraste para[n]matar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11029][f 6 1 2 0 0 6]斡Oho, me conoces demasiado bien![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]Pero, acortar eso a Ace suena mucho m茨s fresco[n]y apropiado, 夷amirita? Acortarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 26 0 0 0][f 3 1 1 0 0 0]Entonces lo acortaremos a Geezer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11058][f 6 1 2 0 0 0]夷C吋mo sucedi吋 eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 18 1 0 1][f 4 6 19 0 2 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19011]Ahora, para el nombre de c吋digo de[n]Shinjiro-senpai... 夷Qu姻 tal Brood?[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 10 0 0][f 3 1 1 0 0 18050][f 6 1 2 0 0 0]夷Eh? 夷Est茨s diciendo que estoy de humor o[n]algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]斡No, no es eso! 斡Cuidarnos tan bien,[n]especialmente Koromaru! As胤 que, eres como[n]nuestra madre enferma...[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 4 1 0][f 3 1 1 0 0 18053][f 6 1 2 0 0 10]夷Qu姻? 夷Qu姻 est茨s...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 6][f 3 1 1 0 0 17001][f 6 1 2 0 0 1]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 5 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No cojas su lado, Koro-cha - Ahem -Koromaru![n][f 1 3 65535][f 1 1][e]

[msg MSG_066 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Entonces, el tipo ama a los perros, pero lo[n]mantiene en secreto, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_067 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 3][f 4 6 14 10 100 1][f 3 1 1 0 0 14548][f 3 1 6 0 0 500]You really know everyone so well,[n][f 6 1 27 0 0 0]. It's amazing![n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Yo tambi姻n s姻 todo sobre ti, Fuuka. Veamos,[n]el nombre de c吋digo de Fuuka...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Quiz茨 Hacker? 夷O, Killer Chef?[n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 0 0][f 3 1 1 0 0 26017]Pero "hacker" es mi trato tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]En ese caso, "maestro chef" tambi姻n es el[n]trato para las chicas de nuestro equipo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 1][f 3 1 1 0 0 4035][f 6 1 2 0 0 0]夷Excusarme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 100 1][f 3 1 1 0 0 14533][f 6 1 2 0 0 9]Oh... As胤 que, el yo en tu mundo no es tan[n]bueno en cocinar tampoco...[n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Uhhh, no es buena idea... Es m茨s como, podr胤a[n]resultar en una investigaci吋n de[n]asesinato?[n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 4][f 3 1 1 0 0 10011]Est茨s siendo demasiado honesto ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_075 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]斡Pero, wow! Supongo que realmente somos lo[n]mismo en tu mundo, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_076 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 13002][f 6 1 2 0 0 3]Muy bien todos, creo que es suficiente charlar.[n]Deber胤amos irnos y..[n][f 1 3 65535][f 1 1][e]

[msg MSG_077 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oh! We don't have one for[n]Mitsuru-senpai yet. Got anything,[n][f 6 1 27 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_078 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19013]C'est Magnifique... No, es m茨s una frase que[n]un nombre de c吋digo. 斡Oh! 夷Qu姻 tal la[n]Queen de ejecuci吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_079 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 10 0 0][f 3 1 1 0 0 13058][f 6 1 2 0 0 0]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_080 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 1][f 3 1 1 0 0 0]Tienes raz吋n... Mitsuru-senpai dice "ejecutar"[n]mucho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_081 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Por favor, para esto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_082 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 12 6 1 1][f 3 1 1 0 0 12031]De todos modos, realmente nos conoces bien,[n]夷no?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso estoy empezando a sentir que siempre[n]ha sido parte de nuestro grupo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_083 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19030]S胤... Tambi姻n me sorprende.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todos aqu胤 son exactamente como los compa隠eros[n]que conozco...[n][f 1 3 65535][f 1 1][e]

[msg MSG_084 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11032][f 6 1 2 0 0 4]Entonces, 夷debemos darle un nombre de c吋digo[n]tambi姻n, [f 6 1 27 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_085 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19018]... 夷Huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_086 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 0][f 3 1 1 0 0 0]Quiero decir, realmente no s姻 lo que ser胤a,[n]pero no deber胤amos dejarte fuera como la[n]雨nica persona sin uno![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 11001][f 6 1 2 0 0 4]Hey, [f 6 1 30 0 0] - 夷puedes venir con un nombre de c吋digo para [f 6 1 27 0 0 0][n]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_087 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Auriculares.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Spunky.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Demonio Deslumbrante.[f 2 7 1 20 4 32][e]

[msg MSG_088 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 26018][f 6 1 2 0 0 4]Pero Yosuke y yo tambi姻n tenemos auriculares.[n]夷No ser胤a confuso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_089 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 100 4][f 3 1 1 0 0 0]Nuestro propio l胤der tambi姻n usa auriculares.[n][f 1 3 65535][f 1 1][e]

[msg MSG_090 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 6 0 1][f 3 1 1 0 0 3031]Si alguien dijera, "斡Aud胤fonos!" y los cuatro[n]nos volteamos, ser胤a como una especie[n]de skit...[n][f 1 3 65535][f 1 1][e]

[msg MSG_091 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 1][f 3 1 1 0 0 22032][f 6 1 2 0 0 7]Es verdad, siempre es tan brillante y alegre.[n]Estar a su alrededor levanta nuestros[n]esp胤ritus.[n][f 1 3 65535][f 1 1][e]

[msg MSG_092 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]夷Eh? 夷En serio? Ahaha, eso es vergonzoso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_093 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 4][f 3 1 1 0 0 0]Es como una diosa social. Est茨 tan llena de[n]energ胤a que es honestamente ciega a[n]alguien como yo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_094 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19139]Demonio Deslumbrante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_095 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Llamar a una dama un demonio es un poco[n]exagerado, 夷no crees?[n][f 1 3 65535][f 1 1][e]

[msg MSG_096 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19029]斡Eso es genial y aterrador! 斡Me encanta![n][f 1 3 65535][f 1 1][e]

[msg MSG_097 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Qu姻... le gusta?[n][f 1 3 65535][f 1 1][e]

[msg MSG_098 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 6 0 1][f 3 1 1 0 0 13133][f 6 1 2 0 0 4]Cielos... 夷Est茨n todos satisfechos ahora?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0]Es hora de que nos mudemos de nuevo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_099 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 0][f 3 1 1 0 0 11061][f 6 1 2 0 0 4]Aww, pero 夷qu姻 hay de nuestros nombres de[n]c吋digo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_100 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 0]No hay ninguna raz吋n para que usemos nombres[n]de c吋digo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]De hecho, cualquier nombre confuso podr胤a[n]causar problemas al emitir 吋rdenes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_101 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 6][f 3 1 1 0 0 16011]S胤, supongo que es verdad... Pero se siente[n]como un poco de amortiguador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_102 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 10 1 0 1][f 4 6 19 2 3 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19024]Sin embargo, me hizo tan feliz que quer胤as[n]darme un nombre de c吋digo tambi姻n...[n]Gracias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_103 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]No fue gran cosa, pero si te gusta... De[n]nada, supongo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_104 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 4][f 3 1 1 0 0 23122]Parece que este fue un descanso 雨til para[n]todos. Bueno, salgamos.[n][f 1 3 65535][f 1 1][e]

