[msg MSG_0000]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mitsuru parece estar perdida en sus pensamientos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 0 0 1][f 3 1 1 0 0 1]Dime, [f 6 1 26 0 0 0]... sobre su mundo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 2]Ella se dirigi吋 al ba隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 3]Ya veo... *suspiro*[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 6][f 3 1 1 0 0 4]Pareces deca胤do. Quiero decir, puedo entender por qu姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 0 0 1][f 3 1 1 0 0 5]Si [f 6 1 27 0 0 0] est茨 diciendo la verdad, entonces todo esto se parece a雨n m茨s a una historia de ciencia ficci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷No significa que hay otro "yo" en alg雨n lugar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 7]He pensado en ese tipo de cosas antes, pero... 夷es realmente posible?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 8]Otro yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9][f 6 1 2 0 0 7]斡夷Qu姻 pasa si ESE yo es un modelo completamente apuesto y exitoso con las mujeres!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 6][f 3 1 1 0 0 10]No hay forma de que sea as胤. La 雨nica manera es si fueras reencarnado como otra persona.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Adem茨s, considerando la forma en la que te habl吋, dudo que seas diferente en su mundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 14 12 0 3][f 3 1 1 0 0 12]Hay algo que olvid姻 mencionar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13]Cuando el Ladrones Fantasma y el Equipo de Investigaci吋n llegaron a nuestro rescate en la pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Por un momento, Luc胤a confundi吋 a [f 6 1 27 0 0 0] como nuestrp l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 4][f 3 1 1 0 0 16]Oh, s胤, sin embargo. Su personalidad es diferente, pero tiene, como... 夷Una vibra similar, de alguna manera?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Me recuerda a nuestro l胤der. No puedo explicarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 18]S胤. Se supone que esta es la primera vez que la veo, pero se siente tan natural tenerla cerca... Me pregunto por qu姻 ser茨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 17 0 0 1][f 3 1 1 0 0 19][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 4][f 3 1 1 0 0 20]Parece que Koromaru est茨 de acuerdo contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 18 0 0 3][f 3 1 1 0 0 21]Bueno, no vamos a descubrir nada qued茨ndonos parados. Solo tr茨tala como a todos los dem茨s y estar茨 bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 1][f 3 1 1 0 0 22]Tienes raz吋n. En cualquier caso, necesitamos priorizar el rescate de nuestro l胤der y Aigis.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0][f 6 1 27 0 0 0]ve a los estudiantes del Instituto Gekkoukan desde lejos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 1 0 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 23]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 24][f 6 1 26 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 25]斡Ah! 斡Oh, me sorprendiste...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 3 1 1 0 0 26][f 6 1 2 0 0 4]Lo siento, me desconect姻 un poco... Eheheh. Entonces, 夷qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 6][f 3 1 1 0 0 27]夷Por qu姻 no te unes a ellos, a menos que sea demasiado inc吋modo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 28]Quiero decir, puedo entender por qu姻 est茨n tan confundidos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Pero cuando pienso en como est茨 haciendo sentir a [f 6 1 27 0 0 0], es simplemente desgarrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 30][f 6 1 2 0 0 6]斡Jajaja! Estoy bien, cosas como universos paralelos son tan de ciencia ficci吋n.[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]No te preocupes.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Estamos aqu胤 para ti.[f 2 7 1 64 0 32][e]

[msg MSG_024 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 31]*risa* Gracias... Est茨s tratando de animarme,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 32]Bueno, [f 6 1 26 0 0 0], estabas tan preocupado por tus compa隠eros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 33]Gracias, todos son muy amables...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 34]Pero, incluso si no me conocen, siguen siendo preciados compa隠eros para m胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35]Eso nunca cambiar茨, y no quiero que lo haga.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 3 1 1 0 0 36][f 6 1 2 0 0 6]斡Por eso har姻 mi mayor esfuerzo para encontrar a su l胤der y Aigis![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 37]...Eres tan fuerte, [f 6 1 26 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 38]*risa* 夷T雨 crees? Probablemente sea porque[n]tengo a todos aqu胤 apoy茨ndome.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39]Si estuviera sola, no habr胤a podido llegar hasta aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 1 0 0][f 3 1 1 0 0 40][f 6 1 2 0 0 6]斡...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 41]S胤, yo tambi姻n... Me alegro de conocerlos a todos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 4 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 42][f 6 1 2 0 0 7]斡Muy bien! Seguir姻 dando lo mejor de m胤 all胤, 斡solo esperen y ver茨n![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 43][f 6 1 2 0 0 6]斡...![n][f 1 3 65535][f 1 1][e]

