[msg DG_OBJECTIVE_MSG_LARGE_0]
ムConsigue ingredientes para palomitas!

[msg DG_OBJECTIVE_MSG_SMALL_0]
Busca un punto del tesoro cerca del agua

[msg DG_OBJECTIVE_MSG_SMALL_0_2]
ムUsa electricidad en los granos de maボz!

[msg DG_OBJECTIVE_MSG_SMALL_0_3]
Encuentra tres mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_4]
Encuentra cuatro mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_5]
Encuentra cinco mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_6]
Encuentra seis mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_7]
Encuentra siete mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_8]
Encuentra ocho mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_9]
Encuentra nueve mホs

[msg DG_OBJECTIVE_MSG_SMALL_0_10]
Comprueba los puntos del tesoro

