[msg MSG_000 [Ryuji]]
Is this a dead end!?

[msg MSG_001 [Ann]]
Isn't there any way out!?

[msg MSG_002 [Yusuke]]
Look! What's that?

[msg MSG_003 [Ann]]
Huh!? It's shining, but... wh-what is[n]it?

[msg MSG_004 [Futaba]]
Hey―that's it! Looks like we can escape[n]through there! And it seems to be[n]enemy-free!

[msg MSG_005 [Ryuji]]
Are you sure?

[msg MSG_006 [Futaba]]
...I think!

[msg MSG_007 [Ryuji]]
You THINK!?

[msg MSG_008 [Morgana]]
What should we do, Joker? There's no[n]other way out―should we go for it?

[sel SEL_009 top]
Let's do it.
What to do here...

[msg MSG_010 [Futaba]]
Hey, there's no time for debate! That[n]Shadow's closing in fast!
...It's right there!

[msg MSG_011 [Ryuji]]
WHAAAT THE EFFIN' HELL IS THAT!?

[msg MSG_012 [Yusuke]]
I've never seen anything like it in my[n]life!

[msg MSG_013 [Futaba]]
I'm sensing an insane power from it...[n]It's too dangerous for us!

[msg MSG_014 [Morgana]]
There's no time to think about it―[n]retreat's our only option!

[msg MSG_015 [Ryuji]]
Damn, looks like we're all in!

[msg MSG_016 [Morgana]]
Everyone, jump!

