[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19012]Hay algo sobre los ciudadanos aqu胤... Son[n]algo extra隠os.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oh, you got that feeling too,[n][f 6 1 27 0 0 0]-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Todo el mundo est茨 tratando de convencerse[n]de que un h姻roe de la justicia siempre[n]es correcto y no puede hacer nada malo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19080]Pero es como si se negaran a pensar en lo[n]que realmente importa: averiguar qu姻 es la[n]justicia...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es como si fueran con el flujo, la justicia[n]aqu胤 es absoluta, todo porque se les dice[n]que lo es.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 6][f 3 1 1 0 0 0]S胤, ninguno de ellos est茨 tratando de pensar[n]por s胤 mismo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Kamoshidaman no tiene raz吋n en primer lugar,[n]pero esta gente tampoco tiene sentido![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 1 0][f 3 1 1 0 0 22091]Si algo va en nombre de la justicia, este[n]lugar es m茨s bonito que Kamoshida antes de[n]que su coraz吋n fuera cambiado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 1 1][f 3 1 1 0 0 0]Bueno, eso es a雨n m茨s una raz吋n para que no[n]dally por aqu胤, entonces.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Vamos a apresurarnos con la operaci吋n de[n]rescate.[n][f 1 3 65535][f 1 1][e]

