[msg MSG_000 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 24022][f 6 1 2 0 0 4]Este interruptor se ve diferente a los anteriores... Oracle, 夷es diferente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 26 12 100 0][f 3 1 1 0 0 0]斡Ni idea![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Pero, tengo el presentimiento de que est茨 relacionado con esas luces como los anteriores![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21074][f 6 1 2 0 0 6]Bien, vamos a presionarlo, 斡no sabremos qu姻 hace a menos que lo probemos![n][f 1 3 65535][f 1 1][e]

