[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 6 0 0 500][f 3 1 1 0 0 26502]Se supone que vamos a la 3a Avenida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Bien, el lugar lleno de FOEs y reflectores,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23069]S胤, tendremos que pasar por all胤 con precauci吋n[n]extra. 斡Pero primero tenemos que ir[n]a la 3a Avenida![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 6 0 0 500][f 3 1 1 0 0 26572]Esta es la 3a Avenida, nuestro destino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Se supone que debemos ir al 茨rea llena de[n]reflectores y FOEs, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23069]As胤 es, tendremos que atravesar esa zona con[n]precauci吋n adicional. 斡Vamos![n][f 1 3 65535][f 1 1][e]

