[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 1][f 3 1 1 0 0 22046][f 6 1 2 0 0 0]斡Realmente hemos terminado! Espera,[n]夷esto es justo donde entramos?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]No puedo creer que nos haya llevado tan[n]lejos - parece que va a ser muy 雨til![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]S胤, apuesto a que si pasamos por un[n]茨rea y dejamos una escalera, no tendremos[n]que pasar por el mismo camino dos veces...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Es como... 夷C吋mo se llama...? Ya sabes,[n]un corto... No "shortcat"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 28017][f 6 1 2 0 0 4]夷Podr胤as decir "corte"?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]Eso es preciso, pero usar esto har茨[n]nuestra exploraci吋n mucho m茨s f茨cil.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si nos encontramos en una situaci吋n[n]similar de nuevo, tratemos de buscar[n]proactivamente la zona.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]Adem茨s, ser胤a mejor marcar esto en el[n]mapa para la pr吋xima vez.[n][f 1 3 65535][f 1 1][e]

