[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26640]斡Joker, retrocede! No es seguro, est茨[n]lleno de FOEs y luces.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 0]No hay necesidad de entrar en la trampa[n]del enemigo. Tenemos que priorizar[n]el rescate de Queen y Noir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Vamos a buscar otro camino.[n][f 1 3 65535][f 1 1][e]

