[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 1][f 3 1 1 0 0 22091][f 6 1 2 0 0 10]斡Eso fue agotador! 夷Cu茨nta vigilancia necesitan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Tienes raz吋n, deber胤an estar[n]conservando electricidad. Tales costos de utilidad[n]nunca deben tomarse a la ligera.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]De hecho, el miedo que sent胤 cuando vi[n]la factura el姻ctrica del mes pasado... 斡Ngh![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23083][f 6 1 2 0 0 9]Eso no tiene nada que ver con esto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]De nuevo, evadir los focos de b雨squeda[n]fue divertido. Es uno de los placeres de[n]ser un ladr吋n fantasma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 0]Funcion吋 desde que logramos pasar por[n]encima de ellos, pero qui姻n sabe qu姻[n]podr胤a haber pasado si nos destrozaron...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 100 1][f 3 1 1 0 0 26630][f 3 1 6 0 0 500]Buen trabajo, amigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Por cierto, ech姻 un vistazo y parece[n]que no hay m茨s focos de b雨squeda![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0]... En esta zona, al menos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Ack... Eso significa que hay m茨s en la[n]siguiente zona...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Esto es por el amor de la Queen y[n]Noir, Skull! 斡Mu姻strale algunas agallas![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21123]斡Est茨 bien, est茨 bien! Vamos, vamos a[n]ponernos nerviosos y seguir movi姻ndonos![n][f 1 3 65535][f 1 1][e]

