[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26572]Nuestro destino est茨 por delante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay muchos m茨s focos de b雨squeda en comparación[n]con las 茨reas anteriores... Y, incluso[n]estoy viendo FOEs m茨s adelante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0]As胤 que tenemos que evitar esas enormes FOEs,[n]mientras hacemos los reflectores...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Bueno, creo que deber胤amos dejar las órdenes[n]a Joker, como siempre... Confiamos en[n]ti para superar esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23120]No podemos permitirnos arruinar esto. Procedamos[n]m茨s cauteloso por aqu胤.[n][f 1 3 65535][f 1 1][e]

