[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 1 1][f 3 1 1 0 0 21057][f 6 1 2 0 0 0]夷Qui姻n es esa chica? 斡Est茨 siendo[n]atacada por Sombras![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0]夷No es... una Persona? 夷Qui姻n podr胤a ser?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 28015]Tal vez ella es la chica que Theodore[n]nos hab胤a mencionado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Si recuerdo correctamente, est茨[n]buscando a un estudiante de secundaria, una[n]mujer que usa auriculares...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0]Todos los detalles que nos proporcion吋 coinciden.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 1 1][f 3 1 1 0 0 23108][f 6 1 2 0 0 6]Si ese es el caso, 斡entonces vamos a[n]ayudarla! 斡Vamos, todos![n][f 1 3 65535][f 1 1][e]

