[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 25075]Ah, ya veo... La [f 0 1 2]jaula gira cuando[n]giras el interruptor[f 0 1 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]斡S胤! ¡Ahora podemos seguir![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 0]A pesar de que los humanos aqu胤[n]desaparecieron hace tiempo, la instalaci吋n[n]sigue funcionando. Qu姻 suerte para[n]nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0][f 3 1 6 0 0 500]斡Ah! Estoy recibiendo m雨ltiples se隠ales[n]fuertes adelante. Parecen ser FOEs.[n]Ten cuidado…[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 0][f 3 1 1 0 0 26518]夷Mm? Espera... Estoy recibiendo otra[n]se隠al...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 0]夷Eh? 夷Qu姻 podr茨 ser?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 0][f 3 1 1 0 0 0]No son Sombras, eso seguro. Es diferente[n]de los FOEs y los dinosaurios...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]No lo entiendo, 夷qu姻 es? 斡No puedo[n]identificarla![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Son un grupo de se隠ales fuertes, pero[n]solo s姻 eso. 斡Lo siento![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 25019][f 6 1 2 0 0 4]夷Eso qu姻 significa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]夷Un grupo de se隠ales fuertes? ¿Podr胤an ser...? Probablemente no, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 0 1 1][f 3 1 1 0 0 0]Mm, parece que no tenemos ni idea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 1 1][f 3 1 1 0 0 0]Avanza con cuidado, Joker.[n][f 1 3 65535][f 1 1][e]

