[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 1][f 3 1 1 0 0 6635][f 3 1 6 0 0 500]斡Chicos, un segundo! Estoy sintiendo[n]una presencia tras esa puerta... Es[n]diferente a todo lo que nos hemos[n]encontrado hasta ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Solo para estar seguros, tal vez quieras[n]comprobar si est茨s preparado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 4 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hay una presencia misteriosa tras esa[n]puerta? Eso es tan aterrador... 夷De[n]verdad tenemos que ir por ah胤?[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Vamos.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]...[f 2 7 1 20 8 32][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4011][f 6 1 2 0 0 6]B-bien, entonces... 斡Te seguimos, Joker![n]Despu姻s de ti, je, je, je...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]夷Escuchaste eso, Joker? Te han asignado[n]una tarea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No decepcionar茨s a la dama, 夷verdad?[n]Estaremos detr茨s de ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28033]La precauci吋n es una t姻cnica vital para[n]sobrevivir. Si no est茨s seguro de[n]lograrlo, prep茨rate antes de entrar.[n][f 1 3 65535][f 1 1][e]

