[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 21 6 0 1][f 3 1 1 0 0 21003][f 6 1 2 0 0 4]Oye, 夷no deber胤amos usar un icono[n]diferente para las puertas el姻ctricas en[n]lugar de reutilizar el de las jaulas[n]giratorias?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Es un buen punto.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Pid茨mosle a Fox que dise隠e uno.[f 2 7 1 20 2 32][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 24114][f 6 1 2 0 0 4]Mm, en ese caso... 夷Qu姻 tal algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 1][f 4 6 27 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Es fant茨stico! 斡Har茨 nuestro mapa a雨n[n]m茨s f茨cil de leer![n][f 1 3 65535][f 1 1][e]

[msg MSG_ICON_DENKISAKU_OPEN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El icono [f 0 1 2]Puerta El姻ctrica[f 0 1 0] se ha a隠adido[n]al mapa de la pantalla inferior.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si deseas revisar c吋mo utilizar este[n]icono...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Presiona [f 0 1 2]AYUDA[f 0 1 0] en la parte inferior[n]derecha del mapa y [f 0 1 2]Tipos de Iconos[f 0 1 0].[n][f 1 3 65535][f 1 1][e]

