[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19001]斡Rise! 夷Vamos por el camino correcto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 100 0][f 3 1 1 0 0 0][f 3 1 6 0 0 500]斡S胤! Solo deben seguir derecho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Mm? 夷Qu姻 es eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 1][f 3 1 1 0 0 7092][f 6 1 2 0 0 0]Ah, 斡夷En serio?! 夷Qu姻 demonios? 斡Hay un[n]mont吋n de malditos 茨rboles bloqueando[n]nuestro camino![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Joker, mira...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay marcas de garras en las estos[n]茨rboles.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Parecen reci姻n hechas.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]夷Marcas de dinosaurio?[f 2 7 1 20 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 0][f 3 1 1 0 0 28067]S胤, parece que no estaban bromeando[n]acerca de haber terminado con nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Espera, 斡夷est茨s diciendo que los herb胤voros[n]est茨n bloqueando nuestro camino[n]a prop吋sito?![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Pero, 夷por qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 28067]S胤, y parecen relativamente nuevas...[n]Parece que han bloqueado intencionalmente[n]nuestro camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Mmm... Eso significa que en serio no[n]quieren que los sigamos, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡夷A qui姻n le importa?! 斡No vamos a volver[n]ahora, despu姻s de todo lo que[n]pasamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Aunque, mira estos enormes 茨rboles,[n]tirados con tanta facilidad... Parece[n]que son verdaderos dinosaurios despu姻s[n]de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 21012][f 6 1 2 0 0 9]Sabes, es un buen punto... podr胤amos[n]estar en verdaderos problemas si los[n]molestamos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Por muy t胤midos que sean, no dejan de[n]ser dinosaurios...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Esto va a ser una molestia, pero supongo[n]que tendremos que buscar una forma[n]de pasar.[n][f 1 3 65535][f 1 1][e]

