[msg MSG_000 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 12 0 1][f 3 1 1 0 0 34005]斡Ah, aqu胤 est茨! 夷Ves? Hay algo que sale de[n]la caja aqu胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todo lo que tienes que hacer es tirar de eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 22 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Bien! 夷Por qu姻 no lo intentamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S吋lo tenemos que apretar este interruptor,[n]夷verdad? 夷Cu茨l es tu decisi吋n, Joker? 夷Lo[n]intentamos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]夷Por qu姻 no?[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]No.[f 2 7 1 20 6 32][e]

[msg MSG_004 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 1][f 3 1 1 0 0 7093][f 6 1 2 0 0 4]夷Eh? Nada est茨 pasando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0]Bueno, duh. Tenemos que volver a esa puerta..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hm? Un n雨mero...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Qu姻 es una cuenta atr茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 7063][f 6 1 2 0 0 10]斡Mierda! 夷Va a explotar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Qu姻? 斡Nadie me dijo nada sobre una[n]explosi吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]Por favor, c茨lmate. Echa un vistazo a la[n]pantalla...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esto probablemente nos muestra la cantidad[n]de tiempo que queda antes de reactivar la[n]corriente el姻ctrica en la puerta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 28086]B茨sicamente, necesitamos pasar la puerta[n]antes de que la cuenta regresiva llegue a[n]cero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Oh, qu姻... 斡Me asustaste![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]Esto es probable donde los humanos aqu胤[n]atraer胤an a los carn胤voros...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Si es as胤, habr胤an dise隠ado el dispositivo[n]para ser utilizado repetidamente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 0]Es un buen punto. Si el temporizador se agota[n]sobre nosotros, simplemente podemos[n]reactivarlo con esta caja de control.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No hay necesidad de preocuparse. Todo ir茨[n]bien si guardamos nuestro ingenio sobre[n]nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 1][f 3 1 1 0 0 21009][f 6 1 2 0 0 4]Ah, 夷quieres andar un poco m茨s?[n][f 1 3 65535][f 1 1][e]

