[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21018]夷Qu姻 demonios? Hay algo raro aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Ahhhh, 斡Qu姻 magn胤fico! El tono, el brillo, la forma... ¡Rebosa de sensibilidad estética![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Vamos, Fox... 夷Tenemos haremos esto otra vez? Tiene un agujero... 斡Es basura![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 27010]Tal vez, pero tambi姻n podr胤a ser de utilidad para nosotros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 0]夷Por qu姻 no lo llevamos con Theodore para que le eche un vistazo cuando regresemos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Noir tiene raz吋n. Ser胤a un desperdicio tirarlo antes de revisarlo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]El verdadero arte a menudo pasa por alto por un ojo sin entrenamiento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 0]Mi intuici吋n me dice... Esto es... 斡Mrow-ow![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0]Por la reacci吋n de Mona... parece que probablemente sea un Tesoro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 21 0 1 1][f 3 1 1 0 0 0]斡Muy bien! Entonces... gu茨rdalo, Joker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008]
[f 0 5 65278][f 2 1][f 4 6 20 2 32 0][f 3 1 1 0 0 0]Deber胤a mostr茨rselo a Theodore cuando volvemos al cine...[n][f 1 3 65535][f 1 1][e]

