[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 25089]Esto es...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Todav胤a no creo que podamos pasar por aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Hay tantas hojas, ni siquiera podemos[n]acercarnos m茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 1][f 3 1 1 0 0 0]De hecho: cortarlas parece demasiado[n]dif胤cil. Si pudi姻ramos acercarnos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 8 12 0 1][f 3 1 1 0 0 8013]Puede ser m茨s r茨pido para nosotros[n]buscar un camino diferente. Tiene que haber[n]alguna manera de evitar esto...[n][f 1 3 65535][f 1 1][e]

