[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26639][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡El interruptor de la puerta el姻ctrica[n]est茨 al noreste de su ubicaci吋n[n]actual![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 4][f 3 1 1 0 0 0][f 3 1 6 0 0 500]夷Recuerdas la puerta que estaba abierta?[n]斡Es por ah胤![n][f 1 3 65535][f 1 1][e]

