[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28072]Ah, justo como pensaba... Podemos alcanzar los troncos desde este lado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Podr胤amos cortarlas en partes m茨s peque隠as y sacarlos de nuestro camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]Necesitamos un hacha para eso…[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_05 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 27 12 0 1][f 3 1 1 0 0 27003][f 6 1 2 0 0 4]斡Oh! Si necesitas un hacha, 夷por qu姻 no me lo dejas a m胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 27 0 0 1][f 3 1 1 0 0 27003][f 6 1 2 0 0 6]夷Qu姻 te parece, Joker? 斡Creo que puedo sacar esos 茨rboles del camino![n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Adelante, Noir.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Vamos a dejarlos.[f 2 7 1 20 6 32][e]

[msg MSG_004 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 27077]斡S胤, d姻jamelo! Es solo una versi吋n ampliada de cortar le隠a...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Haru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 6]斡Aqu胤 vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_005_02 [Morgana]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0][f 3 1 1 0 0 23048]Wh-Whoa... 斡Santo cielo, Noir! Como... 夷¡C吋mo haces eso!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_04 [Teddie]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]斡Wooooow! ¡Es incre胤ble![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 27072][f 6 1 2 0 0 4]...斡Y ah胤 est茨! 夷Qu姻 tal?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 0]Gracias por el trabajo duro. Eso har茨 que explorar esta zona sea mucho más fácil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 0]No hace falta, 斡lo 雨nico que hice fue cortar![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todos los dem茨s ayudaron a mover los pedazos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 7030][f 6 1 2 0 0 6]Ah, 斡No fue nada![n][f 1 3 65535][f 1 1][e]

[msg MSG_009_02 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 0]斡S胤! No podíamos dejar que llevaras esa carga t雨 sola. ¡D姻janos el trabajo pesado a los hombres fuertes![n][f 1 3 65535][f 1 1][e]

[msg MSG_009_04 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]斡T郁 solo estabas mirando! Sheesh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 0][f 3 1 1 0 0 27031][f 6 1 2 0 0 6]*Risa* Gracias por su ayuda. 斡Bueno, sigamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 8069]Muy bien. Dejemos esto por ahora.[n][f 1 3 65535][f 1 1][e]

