[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 0 0 1][f 3 1 1 0 0 26002]No podemos ir por ah胤. Parece que tendremos[n]que encontrar otro camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 1][f 3 1 1 0 0 10013]Es un dolor en el trasero, pero no hay mucho[n]que podamos hacer al respecto. 夷Por qu姻[n]no nos vamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 0 0 1][f 3 1 1 0 0 26002]Espera, esa puerta no abrir茨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 1][f 3 1 1 0 0 10033][f 6 1 2 0 0 9]Eheh, supongo que tenemos que usar el conducto[n]otra vez... Qu姻 pena que no haya otra[n]forma de hacerlo.[n][f 1 3 65535][f 1 1][e]

