[msg MSG_000 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 35 1 0 1][f 4 6 7 0 0 3][f 3 1 1 0 0 7010][f 6 1 2 0 0 4]Ya sabes, me he preguntado... 夷Puedes pelear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35009]NO. NO TENGO NADA QUE HACER. POR FAVOR RECUERDA[n]ESTO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26031]斡No te preocupes! Todo lo que tienes que[n]hacer es seguirnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 6][f 3 1 1 0 0 10067][f 6 1 2 0 0 6]斡S胤, d姻jenos la lucha![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]夷ME TRAES TANTO, AUNQUE NO PUEDA PELEAR? NO[n]BEBES DE ESTO. ENTONCES, 夷POR QU畏?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Hay un beneficio.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]D姻jalo y s胤gueme.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35014]CLARO, PUEDO SERVIR COMO UN IDIOTA...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 6][f 3 1 1 0 0 26135][f 6 1 2 0 0 6]斡No hay escudos vivos! 斡Nadie te pidi吋 que[n]hicieras eso! S胤guenos, 夷vale?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35007]PERO...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 6][f 3 1 1 0 0 7107][f 6 1 2 0 0 6]No sudas todos los detalles. 斡Vamos, vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 10 12 0 3][f 3 1 1 0 0 10018][f 6 1 2 0 0 4]Espera, volver al cine est茨 bien para nosotros,[n]夷pero qu姻 hay de ella?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 1][f 3 1 1 0 0 0]Ahora que lo mencionas, 夷puede dejar esta[n]pel胤cula?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 3][f 3 1 1 0 0 0]No tengo idea de si habr胤a o no alg雨n efecto[n]malo para ella...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 26009]La maquinaria de precisi吋n es muy delicada.[n]No deber胤amos traerla a ning雨n escenario[n]para el que no est姻 dise隠ada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Deber胤amos tratar de esconderla en alguna[n]parte? 夷Y si la atraparon esos robots de[n]seguridad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 1][f 3 1 1 0 0 35008]SI ESTO TE PREOCUPA, CREO QUE HAY UNA[n]SOLUCI遺N.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]NO DEBER緯A SER IDENTIFICABLE CON LOS ROBOTS[n]DE SEGURIDAD SENSORS SI SUSPENDIO MIS[n]OPERACIONES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Suspender sus operaciones? 夷Te refieres a[n]la energ胤a baja?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35008]NO. TENGO UN MODUS OPERANDI. ESTOY A DISPOSICI遺N[n]DE LAS OPERACIONES DE MANTENIMIENTO[n]DE LA HUMANIDAD Y DE SUSPENSO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 3][f 3 1 1 0 0 24047]夷Oh? Suena 雨til. Entonces, seguir姻 adelante[n]y activar姻..[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Oye! 斡No vayas con su configuraci吋n sin su[n]permiso![n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 12 0 3][f 3 1 1 0 0 25009]Incluso si eres capaz de evitar sus sensores,[n]me preocupa dejarte aqu胤 al[n]descubierto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Por qu姻 no te cubres en alg雨n lugar antes[n]de hacer el modo de sue隠o?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1066]Estoy de acuerdo. Definitivamente parece[n]que ser胤a m茨s seguro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, nuestro pr吋ximo objetivo es encontrar[n]a los miembros restantes de SEES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 3 1 1 0 0 0]斡Vamos![n][f 1 3 65535][f 1 1][e]

