[msg MSG_000 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4058][f 6 1 2 0 0 0]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 0]La puerta se abri吋.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Por qu姻 te asustaste?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 4039][f 6 1 2 0 0 10]斡Eso no es! Es la puerta detr茨s de[n]nosotros - [f 0 1 2] de repente se cerr吋[f 0 1 0]![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 4 1 0 1][f 4 6 10 0 0 3][f 3 1 1 0 0 0]Tienes raz吋n. Tengo la sensaci吋n de que[n]hay alg雨n tipo de patr吋n para esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 1][f 3 1 1 0 0 16001][f 6 1 2 0 0 4]Te est茨s preguntando sobre eso tambi姻n,[n]夷eh? Bueno, probablemente deber胤amos[n]seguir movi姻ndonos por ahora, al menos.[n][f 1 3 65535][f 1 1][e]

