[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 3124][f 6 1 2 0 0 10]斡Ack! 斡Otro robot![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 3 11 0 1][f 4 6 21 12 1 3][f 3 1 1 0 0 21037][f 6 1 2 0 0 0]斡Y estamos en un callej吋n sin salida![n]斡夷Qu姻 vamos a hacer?![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 2 1 1][f 3 1 1 0 0 13023]La puerta que alterna entre abierta y[n]cerrada est茨 adelante...[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Destruyamos ese FOE.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Llevemos al FOE all胤.[f 2 7 1 20 2 32][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 12107]夷Qu姻, lo destruiremos con nuestros pu隠os?[n]En ese caso, d姻jamelo a m胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 4][f 3 1 1 0 0 0]Oye idiota, 斡no hay manera de que t雨 o[n]cualquiera de nosotros golpe a esa[n]cosa y viva para contarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 0 0 1][f 3 1 1 0 0 8001]U-Um...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No se abrir胤a la puerta si llevamos al[n]FOE que nos sigue hacia esa puerta?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28076]Ah, Es una gran idea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si el FOE nos sigue a trav姻s de la[n]puerta, la puerta cerrada se abrir茨...[n]夷Ese es el plan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23072][f 6 1 2 0 0 6]Definitivamente funcionaria. 斡Vamos a[n]intentarlo, Joker![n][f 1 3 65535][f 1 1][e]

