[msg MSG_000 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 99 1][f 3 1 6 0 0 500][f 3 1 1 0 0 14527][f 6 1 2 0 0 10]Lo siento, pero... No s姻 a d吋nde ir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quiero decir, hay un camino, pero tiene[n]una puerta cerrada, as胤 que no te har茨[n]ning雨n bien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 15106]Entonces, 夷decimar姻 este muro?[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Es todo tuyo.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Por favor, no.[f 2 7 1 20 6 32][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 22 10 0 1][f 3 1 1 0 0 22055]夷Eh? Espera, decim - 斡Para, para![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10][f 4 6 22 12 0 0]斡No, no, definitivamente no! Ser胤a muy[n]malo si este lugar explotara, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 22 12 0 1][f 3 1 1 0 0 22037][f 6 1 2 0 0 10]斡Lo escuchaste! Ser胤a muy malo si este[n]lugar explotara, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 4][f 3 1 1 0 0 35002]SER緯A ESPECIALMENTE PELIGROSO DESDE QUE[n]LOS DISCOS ELECTR遺NICOS SE DESPLOMAR緯AN.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 15 1 0 1][f 4 6 2 12 0 3][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]Aigis, go easy on them―they can't tell[n]you're kidding.[n][f 4 7 4 0 0][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 6 0 1][f 3 1 1 0 0 15010]S胤, parece que es el caso. Me disculpo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 0 3][f 3 1 1 0 0 26058][f 6 1 2 0 0 0]夷Tiene Joker? 斡Habla de ser de alta[n]definici吋n! Daaaamn...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26033][f 6 1 2 0 0 9]Pero, con toda honestidad... Mi sangre[n]se resfri吋 por un segundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 15 1 0 0][f 4 6 35 0 1 3][f 3 1 1 0 0 35022]A... 夷JOKE? UN ROBOT... ME HICE UN CHISTE.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_5 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35010][f 6 1 2 0 0 4]ERES MUY DIFERENTE DE LOS ROBOTS[n]N遺RDICOS, AIGIS-SAN... 夷POR QU畏?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷ES PORQUE NO FUISTE CRIADO EN ESTE[n]MUNDO, COMO YO?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15012]Actualmente s姻 muy poco sobre lo que[n]comprende un robot "normal"... Sin[n]embargo, no importa d吋nde est姻, soy yo mismo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Esto no te describe tambi姻n, Ribbon-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 8 0 3][f 3 1 1 0 0 35012]夷QU畏 TAL?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15063]Me dijeron que viniste con nosotros[n]porque quer胤as aprender sobre las emociones[n]que has alcanzado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ese sentimiento naci吋 de dentro de ti. Es tuyo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 2 1 3][f 3 1 1 0 0 35022]TEN緯A... MI PROPIA SENSACI遺N...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 1 6][f 3 1 1 0 0 13069]Bueno, vamos a terminar esta[n]conversaci吋n por ahora y reanudar nuestra exploraci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014_5 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 3][f 3 1 1 0 0 0]Aunque no haya un camino claro para[n]nosotros, debe haber un pasaje oculto en[n]alg雨n lugar. Intentemos buscar uno.[n][f 1 3 65535][f 1 1][e]

