[msg MSG_000 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 9056][f 6 1 2 0 0 0]Oh no, oh no, oh nooooo! 夷Es una cat茨strofe?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Obviamente no![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 0][f 3 1 1 0 0 0]夷Qu姻? Supongo que se ha detenido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1106]Teddie, no hay conocimiento de lo que podr胤a[n]suceder en este mundo. Aseg雨rate de no[n]tocar nada descuidadamente, 夷de acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 5 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Entiendo, el Maestro... pensar姻 en lo que he[n]hecho...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 16 10 0 1][f 3 1 1 0 0 16059][f 6 1 2 0 0 6]斡Pero mirad todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 1][f 3 1 1 0 0 28075]...[f 0 1 2]El agujero ha sido bloqueado[f 0 1 0][n]. Esta debe ser la causa de ese[n]terremoto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Esto me recuerda esas cosas que usan para[n]poner en juego. 夷C吋mo se llamaba... [f 0 1 2][n]stage lift[f 0 1 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 9058]夷Qu姻? Entonces, 夷es seguro decir que el[n]misterio fue resuelto completamente gracias[n]a m胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 21041][f 3 1 1 0 0 0]Amigo, 夷qu姻 pas吋 pensando en lo que hiciste?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Qu姻 es ese sonido?[n][f 1 3 65535][f 1 1][e]

