[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 22116][f 6 1 2 0 0 1]斡Hola! 斡Ahora hay viento soplando aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]Veo, as胤 que el interruptor del piso era para[n]controlar la pared que protege el viento[n]aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Ahora que el viento ha cambiado, usted debe[n]ser capaz de hacer m茨s progreso![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mantenga un ojo hacia fuera para m茨s de esos[n]escudos y interruptores mientras avanza![n][f 1 3 65535][f 1 1][e]

