[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 22118][f 6 1 2 0 0 6]斡Mira! 斡Un FOE![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 0]Yo, uh... no quiero que se acerque a[n]nosotros. 夷Podemos salir de aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 15 1 0 3][f 4 6 17 12 0 6][f 3 1 1 0 0 17001]斡Guau![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 0][f 3 1 1 0 0 0]No hay problema, Panther.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Koromaru dice: "[f 0 1 2]Es demasiado grande[n]para caber pasar. No hay necesidad de[n]preocuparse[f 0 1 0]".[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Ah, 斡qu姻 alivio! Me hab胤a asustado por[n]un segundo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 2 0 3][f 3 1 1 0 0 23052]No te preocupes, Panther. 斡Si algo viene[n]tras de ti, te proteger姻![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 1 0 1][f 3 1 1 0 0 0]Oh, no te preocupes. Gracias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 6][f 3 1 1 0 0 0]Whoa, ella lo hizo tan f茨cilmente...[n]Eso fue realmente impresionante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 8 1 0 1][f 3 1 1 0 0 8001]Ah, me preocupa algo sobre ese FOE...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Puede que avanzar no sea un problema[n]aqu胤, pero 夷no tendremos que esquivarlo[n]en alg雨n momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 15 1 0 3][f 4 6 17 12 0 6][f 3 1 1 0 0 0]斡Arf arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 0][f 3 1 1 0 0 15008]Koromaru dice: "[f 0 1 2]Debemos usar nuestro[n]terreno a nuestro favor[f 0 1 0]".[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 8069]Ya que Joker lleva el mapa, le dejaremos[n]la estrategia con ese FOE.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_5 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 8 12 0 1][f 3 1 1 0 0 0]夷Est茨s listo para seguir?[n][f 1 3 65535][f 1 1][e]

