[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]No necesito mantener mi personalidad[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 1][f 3 1 1 0 0 21040][f 6 1 2 0 0 6]斡Maldita sea! 斡No puedo sacar la canci吋n de[n]ese trailer de mi cabeza![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Y esas letras de mierda me est茨n volviendo[n]m茨s deprimida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 14 1 3][f 3 1 1 0 0 0]斡Luchemos contra ella y cantemos canciones[n]alegres y felices![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]斡Cu姻ntame! 斡Ir姻 primero![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 3][f 3 1 1 0 0 10081]No.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 0]夷No puedo cantar un poco?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]No a menos que quieras sangrar nuestros[n]o胤dos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11055][f 6 1 2 0 0 9]Amigo, 夷tienes que ser tan duro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 4][f 3 1 1 0 0 0]Entonces, 夷por qu姻 no hago un medley de mis[n]cosas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 3][f 3 1 1 0 0 4081]Obviamente preferir胤amos escuchar a Rise,[n]Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 26 2 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500][f 6 1 2 0 0 6]斡Eso ser胤a genial! 斡Me encantar胤a escuchar[n]a Risette cantar en vivo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Con qu姻 frecuencia escuchamos a un 胤dolo[n]cantar s吋lo para nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 3][f 3 1 1 0 0 6530][f 3 1 6 0 0 500]*Grecha* Si anima a todos, estar胤a feliz.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 0][f 3 1 1 0 0 0]Pero no podemos decepcionar a nuestra guardia[n]mientras exploramos, as胤 que tal vez[n]lo guardar姻 para cuando regresemos, 夷de[n]acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷En serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21043][f 6 1 2 0 0 1]斡Claro que s胤! 斡Estoy tan emocionada! 斡Vamos,[n]r茨pido![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 1 0 3][f 4 6 24 12 0 1][f 3 1 1 0 0 0]Skull est茨 completamente envuelto alrededor[n]de su dedo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Ese es nuestro Rise. Ella realmente sabe c吋mo[n]manejar sus fans.[n][f 1 3 65535][f 1 1][e]

