[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28131][f 6 1 2 0 0 4]Eso me recuerda, Joker. 夷El mapa viene bien?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Por supuesto.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Sinceramente, no estoy seguro...[f 2 7 1 20 8 32][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 22019]夷En serio? 夷Puedo ver?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0][f 4 6 28 6 1 1][f 3 1 1 0 0 28008]... Ser胤a un poco mejor si dibujaras algunos[n]detalles m茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una vez que delinees las paredes, creo que[n]ser茨 m茨s f茨cil identificar ambos extremos[n]muertos y lugares que todav胤a necesitamos[n]explorar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003_1 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]As胤, podemos buscar cada pulgada de la[n]pel胤cula... Incluso puede llevarnos a algunos[n]tesoros inesperados.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hikari era lo suficientemente amable para[n]darnos este cuaderno. 斡Hag茨moslo bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0][f 4 6 28 2 0 1][f 3 1 1 0 0 28047]Parece que hemos explorado mucho este lugar.[n]Dudo que pasemos por alto cualquier[n]art胤culo o pasajes ocultos en este punto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero tal vez ser胤a mejor si usted esboz吋 las[n]paredes tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 4][f 3 1 1 0 0 0]De hecho. Me imagino que eso nos ayudar茨 a[n]ver ambos extremos muertos y caminos que[n]a雨n no hemos viajado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006_1 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Tambi姻n puede permitir una exploraci吋n m茨s[n]suave, y habr茨 menos posibilidades de que[n]nosotros tambi姻n pasemos por alto[n]tesoros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Hikari era lo suficientemente amable para[n]darnos este cuaderno. 斡Hag茨moslo bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0][f 4 6 28 2 0 1][f 3 1 1 0 0 28048]Se ve bien. Las paredes est茨n delineadas, y[n]hemos explorado cada rinc吋n y cangrejo[n]hasta ahora...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tambi姻n podemos ver a d吋nde tenemos que ir,[n]as胤 que no parece haber ning雨n problema.[n]Muy impresionante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 4][f 3 1 1 0 0 0]Parece que tampoco hemos pasado por alto[n]ning雨n tesoro. 斡Est茨s haciendo un buen uso[n]de ese cuaderno![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Debemos agradecer a Hikari por d茨rnoslo![n][f 1 3 65535][f 1 1][e]

