[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Un callej吋n sin salida... Solo un montón de publicidad sobre pel胤culas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 10 1 1][f 3 1 1 0 0 61113][f 6 1 2 0 0 6]斡Oh, esa pel胤cula![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷La conoces, Hikari? ¿Es famosa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 61079]No realmente... Me recuerda a una pel胤cula que me encanta...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Ah s胤? ¿Qu姻 la hace tan buena?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 61142]Es dif胤cil de explicar, pero es una película en la que el director fue muy detallista.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La m雨sica y la direcci吋n art胤stica tambi姻n son excelentes. La película es realmente conmovedora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 0]No tiene famosos o efectos especiales caros...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 0]Pero esa pel胤cula me mostr吋 cómo no necesitas depender de esas cosas para tocar el corazón de la audiencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 3 1 1 0 0 19047][f 1 5][f 6 1 27 0 0 0]斡Vaya, debe ser muy buena! Quiero verla tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0]Las pel胤culas deben ser entretenidas, como esa que describi吋 Hikari…[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Pero todas estas pel胤culas son... realmente deprimentes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0]Quiero apresurarme y hacer que todos recuerden que las pel胤culas no deben ser como est茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tenemos que detener a Enlil antes de que sea tarde.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61172]Mmhm. S胤, s姻 que ver películas hace que sea m茨s fácil lidiar con la realidad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 2 1 0][f 3 1 1 0 0 0]Pero todas las personas deber胤an esforzarse por tratar de salir de aquí.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Incluy姻ndonos. 斡Vamos![n][f 1 3 65535][f 1 1][e]

