[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Es un callej吋n sin salida... S吋lo un[n]mont吋n de carteles de cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 10 1 1][f 3 1 1 0 0 61113][f 6 1 2 0 0 6]斡Oh, esta pel胤cula![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Lo reconoces, Hikari? 夷Es famoso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 61079]No realmente... Me recordaron esta[n]pel胤cula que amo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷S胤? 夷Qu姻 lo hace tan bueno?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 61142]Es dif胤cil de explicar, pero puedes[n]decir que est茨 lleno del cuidado del director.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La direcci吋n de m雨sica y arte tambi姻n[n]es maravillosa. La pel胤cula es muy alentadora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 0]No hay estrellas famosas o efectos[n]caros en ella...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 0]Pero esa pel胤cula me mostr吋 c吋mo no[n]necesitas confiar en esas cosas para tocar[n]el coraz吋n de la audiencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 3 1 1 0 0 19047][f 1 5][f 6 1 27 0 0 0]　斡Vaya, debe ser muy bueno! Quiero verlo tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0]Se supone que las pel胤culas son[n]bonitas, como c吋mo Hikari-chan describi吋 ese...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Pero los 雨nicos que juegan aqu胤 son[n]todos negativos... Es un bummer real.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0]Quiero apurarme y hacer que todos los[n]Cines recuerden que las pel胤culas no[n]deben ser como esas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tenemos que detener a Enlil antes de[n]que sea demasiado tarde.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61172]Mmhm. S姻 de primera mano que ver[n]pel胤culas es m茨s f茨cil que tratar con la realidad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 2 1 0][f 3 1 1 0 0 0]Pero cada persona todav胤a debe hacer un[n]esfuerzo para salir de aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Incluyendonos. 斡Vamos![n][f 1 3 65535][f 1 1][e]

