[msg MSG_000 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 6 0 1][f 3 1 1 0 0 55013]夷Qu姻 es esto? Siento un misterioso poder entre ustedes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]夷Huh? ¿Te refieres a esta carta brillante?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 10 0 0][f 3 1 1 0 0 0]夷Esta es... una Persona?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Lo obtuvimos de una Sombra. 夷Sabes qu姻 es?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 0][f 3 1 1 0 0 55043]No esperaba ver esto fuera de los l胤mites del cine... *risa* Que intrigante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Les importar胤a esperar un momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 12 0 0][f 3 1 1 0 0 0]Su paciencia es apreciada.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Parece que esta carta puede otorgar poder a una Persona.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 5018][f 6 1 2 0 0 4]Otorgar... 夷Poder?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 12 0 0][f 3 1 1 0 0 0][f 6 1 3 0 0 1]S胤. Dicho de otra forma, les permite extraer una habilidad de una Persona.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 75 6 0 0][f 3 1 1 0 0 0]...Sin embargo, ese poder es inestable. Ef胤mero, puede que solo dure un breve instante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 10]夷Tan corto? ¿Eso no nos servir茨 de mucho, verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 12 0 0][f 3 1 1 0 0 55069]No necesariamente. Si la usan en una fusi吋n de sacrificio, pueden transferir ese poder a otra Persona.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 8 2 0 0][f 3 1 1 0 0 0]Entiendo. Eso parece conveniente... siempre y cuando lo usemos correctamente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 2 0 0][f 3 1 1 0 0 55029][f 6 1 3 0 0 1]S胤, es un hallazgo fascinante. Pru姻balo... cuando tengan tiempo, por supuesto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]He hecho los preparativos, as胤 que pueden intentarlo cuando quieran. Vengan si se sienten inclinados a hacerlo.[n][f 1 3 65535][f 1 1][e]

