[msg MSG_000 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 79 1 0 4][f 4 6 78 0 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 6]斡Ah胤 est茨s, Recluso![n][f 1 3 65535][f 1 1][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 4 6 64 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 64 8 32 0][f 3 1 1 0 0 0]Marie no est茨...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 4]夷Est茨s buscando a Marie?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Parece que ha salido dejar otro recado de Margaret.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 4 6 64 5 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay otro pedazo de papel en el suelo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay algo escrito en 姻l con una letra muy seria...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 0][f 3 1 1 0 0 0]"Law"[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 0][f 3 1 1 0 0 0]Endorphin: a brain compound Sulforaphane: an antioxidant Inosine: allows muscle movement[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So, do you see it? The one law of the universe?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Everything comes down to chemicals... And their reactions...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1][f 4 6 64 5 1 3][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Es otro de los poemas de Marie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 4][f 6 1 3 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 6]斡Gyaaaaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 0 2 1][f 3 1 1 0 0 5][f 6 1 2 0 0 10]斡N-No es lo que piensas! Son... ¡Solo apuntes! ¡Para estudiar! T雨 estudias f胤sica, química y cosas así en la escuela, 夷¡verdad!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 14 1 0][f 3 1 1 0 0 6][f 6 1 2 0 0 6]斡No escrib胤 sulforaphane porque sea similar a Sandalphon ni nada por el estilo! ¡No suenan para nada parecido![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 85 5 1 0][f 3 1 1 0 0 7]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 0 2 0][f 3 1 1 0 0 8][f 6 1 2 0 0 6]斡Teodioest雨pidadopamina! ¡Te estoy lanzando una maldici吋n y ahora siempre sacar茨s malas calificaciones en ciencias![n][f 1 3 65535][f 1 1][e]

[msg MSG_009]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 3 1 1 0 0 0]Marie est茨 sonrojándose más que nunca...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Caroline]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 79 1 0 3][f 4 6 78 12 0 6][f 3 1 1 0 0 9]Ahora que lo mencionas, parece que hay una serie de habilidades que dependen de esas reacciones cient胤ficas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 0 0 0][f 3 1 1 0 0 10]Lo veo. Esto parece merecer m茨s experimentaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 14 1 0][f 3 1 1 0 0 11][f 6 1 2 0 0 6]斡Nadie necesita esos experimentos in雨tiles! ¡Espero que todos coman una Llamarada At吋mica![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Margaret]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 75 2 0 0][f 3 1 1 0 0 12]*risa* Quiz茨s deber胤as calmarte. Este es uno de tus trabajos menos embarazosos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 4 1 0][f 3 1 1 0 0 13][f 6 1 2 0 0 3]MENOS embarazoso... *suspiro* Lo puse en mi bolsillo. 夷C吋mo terminó all胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 10 0 0][f 3 1 1 0 0 14][f 6 1 2 0 0 4]*jadeo* 夷Podr胤a ser? ¿Es esta la ley del universo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 8 1 0][f 3 1 1 0 0 15]Falling...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16]"Fall in love"... "Fallen angel"...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 3 1 1 0 0 0]Marie volvi吋 a su lugar, notablemente inquieta...[n][f 1 3 65535][f 1 1][e]

