[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23001]夷Ad吋nde vas? Nagi dijo que la siguiera.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ella fue al puesto de concesi吋n. Vamos a ver[n]qu姻 tiene que decir.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23004]Podemos ir m茨s tarde. Por ahora, vamos a ver[n]a Nagi en el stand de concesi吋n.[n][f 1 3 65535][f 1 1][e]

