[msg MSG_001 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 79 1 0 4][f 4 6 78 4 1 1][f 3 1 1 0 0 58001][f 6 1 2 0 0 6]夷Aqu胤 de nuevo, Recluso? 斡Te dije que a雨n no estamos listas![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 0][f 6 1 2 0 0 4]夷Necesitas algo m茨s?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1]Solo quer胤a hablar un poco.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]H茨blame de las Personas Secundarias.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No, me voy.[f 2 7 1 64 6 32][e]

[msg MSG_004 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 12 0 0][f 3 1 1 0 0 58042]斡Hmph! Como si tuvieras tiempo para conversar, Recluso.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 78 4 0 0][f 6 1 2 0 0 6]Si crees que puedes relajarte solo porque no est茨s en tu celda, 斡estás equivocado![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 0]Nuestro deber es rehabilitarte.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Si es necesario, podemos adaptarnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 4 1 0][f 3 1 1 0 0 58118][f 6 1 2 0 0 6]斡Ser茨 mejor que est姻s agradecido, Recluso![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 12 0 0][f 3 1 1 0 0 58082][f 6 1 2 0 0 6]Sheesh, est茨s necesitado. Bien, escucha.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 0]Parece ser que la en que las cosas funcionan en este mundo es muy diferente del nuestro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]El poder del comod胤n que te permite cambiar de Persona en batalla, ya no est茨 disponible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 2 0 0][f 6 1 2 0 0 6]Aun as胤, parece que las cosas no son tan malas. 斡Así que animo![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 0 0 0][f 3 1 1 0 0 59024]Aqu胤, todo el mundo podr茨 equipar una [f 0 1 2]Persona adicional[f 0 1 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 4 0 0]No solo t雨, Recluso. Todos. 夷斡Entiendes!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 2 0 0][f 3 1 1 0 0 59012]Llamaremos a la Persona est茨ndar de cada uno su [f 0 1 2]"Persona principal"[f 0 1 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Y a las que obtengas en las pel胤culas, las llamaremos [f 0 1 2]"Secundarias"[f 0 1 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 12 0 0]En otras palabras, todos ustedes pueden llevar [f 0 1 2]dos Personas[f 0 1 0], una "Principal" y otra "Secundaria".[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 79 12 0 0][f 3 1 1 0 0 59059]No s姻 por qué ha cambiado el poder del Comod胤n. Sin embargo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Puede que haya otras cosas en las que podamos ayudar en lo que respecta a las Personas Secundarias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 4 1 0]斡Hasta entonces, sigue haciendo lo que tienes que hacer! 夷¡Entendido!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Justine]]
[f 0 5 65278][f 2 1][f 4 6 78 1 0 1][f 4 6 79 0 0 0][f 3 1 1 0 0 59047]夷Vas a volver?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Caroline]]
[f 0 5 65278][f 2 1][f 4 6 78 0 1 0]斡Tu misi吋n actual es escapar de este mundo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Esto es parte de su rehabilitaci吋n. 斡No lo olvides, Recluso![n][f 1 3 65535][f 1 1][e]

