[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 80 2 0 1][f 3 1 1 0 0 56028]夷Tienes algo que necesite aprecio?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Por favor, espera un momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Aqu胤 est茨. Por supuesto, t吋malo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Aqu胤 est茨. Por supuesto, toma..[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_1 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 10 0 0][f 3 1 1 0 0 56021]... Bueno, supongo que no puedes. No tienes[n]espacio.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 0][f 3 1 1 0 0 0]Mis disculpas, pero 夷podr胤as hacer algo de[n]espacio en tu bolsa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_2 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 1 0][f 3 1 1 0 0 56029]Estar姻 feliz de proporcionarlo tan pronto[n]como tengas el espacio para cargarlo. Solo[n]av胤same cuando est姻s listo.[n][f 1 3 65535][f 1 1][e]

