[msg JUNPEI_FOE_FOLLOW_START_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11300]Whoa, that's an FOE![n][f 1 6 65535][e]

[msg JUNPEI_FOE_FOLLOW_START__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11301]Yo, an FOE's after us![n][f 1 6 65535][e]

[msg JUNPEI_FOE_FOLLOW_START__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11302]Dude! An FOE's comin' this way![n][f 1 6 65535][e]

[msg JUNPEI_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11303]Crap, an FOE![n][f 1 6 65535][e]

[msg JUNPEI_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11304]Please don't notice us... Please don't[n]notice us...[n][f 1 6 65535][e]

[msg JUNPEI_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11305]Let's do this real quiet-like.[n][f 1 6 65535][e]

[msg JUNPEI_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11306]Aight, looks like we lost him.[n][f 1 6 65535][e]

[msg JUNPEI_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11307]Ha, like we're stupid enough to take[n]that thing head-on.[n][f 1 6 65535][e]

[msg JUNPEI_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11308]Junpei Iori lives to see another day![n][f 1 6 65535][e]

[msg JUNPEI_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11369]Shh! Watch your step.[n][f 1 6 65535][e]

[msg JUNPEI_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11370]Here comes ninja master Junpei![n][f 1 6 65535][e]

[msg JUNPEI_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11371]Yikes, this is makin' me nervous...[n][f 1 6 65535][e]

[msg JUNPEI_DENKISAKU_REACTIO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11372]Nope. No gettin' through that...[n][f 1 6 65535][e]

[msg JUNPEI_DENKISAKU_REACTIO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11373]Wonder if there's a switch to turn off[n]the power...[n][f 1 6 65535][e]

[msg JUNPEI_DENKISAKU_REACTIO_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11374]Is that some kinda new shock[n]therapy...? Uh, after you![n][f 1 6 65535][e]

[msg JUNPEI_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11375]I'm flying![n][f 1 6 65535][e]

[msg JUNPEI_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11376]Whoa!?[n][f 1 6 65535][e]

[msg JUNPEI_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11377]You serious!?[n][f 1 6 65535][e]

[msg JUNPEI_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11324]Oh? Are those the stairs I see?[n][f 1 6 65535][e]

[msg JUNPEI_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11325]Looks like we can move on to the next[n]area. You ready?[n][f 1 6 65535][e]

[msg JUNPEI_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11326]And if you turn your attention to the[n]front, you'll see a staircase.[n][f 1 6 65535][e]

[msg JUNPEI_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11327]Found a treasure chest![n][f 1 6 65535][e]

[msg JUNPEI_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11328]Hm? Is that a treasure chest?[n][f 1 6 65535][e]

[msg JUNPEI_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11329]Is that... treasure?[n][f 1 6 65535][e]

[msg JUNPEI_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11330]There's something fishy over there...[n][f 1 6 65535][e]

[msg JUNPEI_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11331]Yo, let's take a closer look.[n][f 1 6 65535][e]

[msg JUNPEI_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11332]Is there something over there? There[n]is, isn't there?[n][f 1 6 65535][e]

[msg JUNPEI_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11333]Ta da da da! Switch ahead![n][f 1 6 65535][e]

[msg JUNPEI_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11334]Spotted a switch![n][f 1 6 65535][e]

[msg JUNPEI_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11335]Hey, I see a switch![n][f 1 6 65535][e]

[msg JUNPEI_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11336]Hey, think I spotted a shortcut![n][f 1 6 65535][e]

[msg JUNPEI_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11337]Yo, that looks like a shortcut.[n][f 1 6 65535][e]

[msg JUNPEI_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11338]Hey, we can pass through there![n][f 1 6 65535][e]

[msg JUNPEI_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]【パーティの半分以上が死んでいる】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_FOE_WARNING_NEAR_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11309]Aw, geez, that FOE's still chasin' us![n][f 1 6 65535][e]

[msg JUNPEI_FOE_WARNING_NEAR__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11310]Damn that thing's stubborn! Girls[n]don't appreciate that, you know![n][f 1 6 65535][e]

[msg JUNPEI_FOE_WARNING_NEAR__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11311]Looks like it wants to be friends...[n]Uh, no thanks![n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_HP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11312]I can't keep goin'...[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11313]No health, no energy. Junpei's down[n]for the count![n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11314]Sorry, but I'm beat. Help me uuuuuup.[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_TP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_TP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_PARTY_TP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11315]My health's pretty much tapped out...[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11316]Help! I'm beggin' you![n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11317]My health's in the red... Can ya lend[n]me a hand?[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11318]Ergh... My energy's not lookin' so hot.[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11319]Aw, crap, I'm almost out of energy...[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11320]Sorry, I'm outta gas... Man, I'm beat...[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11321]Hmm. That was a pretty easy, huh?[n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11322]The good guys always win![n][f 1 6 65535][e]

[msg JUNPEI_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11323]Aw, yeah! Who's the man!?[n][f 1 6 65535][e]

[msg JUNPEI_BATTLE_CHANGE_DUN]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_BATTLE_CHANGE_DUN_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_BATTLE_CHANGE_DUN_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11360]Let's get the ball rollin'![n][f 1 6 65535][e]

[msg JUNPEI_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11361]Alright, let's go.[n][f 1 6 65535][e]

[msg JUNPEI_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11362]Aaand I'm off![n][f 1 6 65535][e]

[msg JUNPEI_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11363]Let's wrap this up quick.[n][f 1 6 65535][e]

[msg JUNPEI_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11364]This is a job for a hero![n][f 1 6 65535][e]

[msg JUNPEI_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11365]I can handle this all by myself![n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11352]Still got a long way to go. Watch your[n]health, yeah?[n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11353]Geez, we're still only this far...?[n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11354]Think we're about halfway there?[n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11355]Hey, this map's really fillin' up![n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11356]Dude, we've filled a ton![n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11357]Here's hoping the rest of those spaces[n]are safe![n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11358]Tada! The map's all finished! Nice one![n][f 1 6 65535][e]

[msg JUNPEI_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11359]Nice job on the mapping![n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_ALL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11342]Hey, good one![n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_ALL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11343]You've got a good memory.[n]Impressive.[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_KAID]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11344]Yeah, just like that![n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_KAID_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11345]Ding ding ding! We have a winner![n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_CHANGE_CO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11346]It's good to change things up.[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_CHANGE_CO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11347]Wow, you're pretty detailed, huh?[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_DEL_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11348]Watching you put the finishing[n]touches on that map... It's beautiful.[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_ICON_DEL__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11349]How could you throw that away!?[n]Just kidding.[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11350]Here, lemme sign my name... Huh?[n]Whaddya mean you don't need it?[n][f 1 6 65535][e]

[msg JUNPEI_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11351]Huh. That's convenient.[n][f 1 6 65535][e]

[msg JUNPEI_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11366]'Scuse me.[n][f 1 6 65535][e]

[msg JUNPEI_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11367]Let's go![n][f 1 6 65535][e]

[msg JUNPEI_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11368]All right! Let's do it![n][f 1 6 65535][e]

[msg JUNPEI_KARITORU_ENCOUNT_]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg JUNPEI_KARITORU_ENCOUNT__2]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg JUNPEI_KARITORU_ENCOUNT__3]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ３[n][f 1 6 65535][e]

