[msg AEGIS_FOE_FOLLOW_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15300]An FOE is now in pursuit![n][f 1 6 65535][e]

[msg AEGIS_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15301]An FOE has locked on to us.[n][f 1 6 65535][e]

[msg AEGIS_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15302]It seems we have been[n]spotted by an FOE.[n][f 1 6 65535][e]

[msg AEGIS_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15303]An FOE has been detected.[n][f 1 6 65535][e]

[msg AEGIS_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15304]Be wary of the nearby FOE.[n][f 1 6 65535][e]

[msg AEGIS_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15305]FOE detected. It's very close.[n][f 1 6 65535][e]

[msg AEGIS_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15306]It appears we managed to avoid[n]confrontation with the FOE.[n][f 1 6 65535][e]

[msg AEGIS_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15307]The FOE seems to have given up.[n][f 1 6 65535][e]

[msg AEGIS_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15308]It would appear we have escaped[n]from the FOE.[n][f 1 6 65535][e]

[msg AEGIS_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15369]Let us be careful to avoid detection.[n][f 1 6 65535][e]

[msg AEGIS_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15370]I believe "shhhh..." is the appropriate[n]exclamation.[n][f 1 6 65535][e]

[msg AEGIS_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15371]Careful... Careful...[n][f 1 6 65535][e]

[msg AEGIS_DENKISAKU_REACTION]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15372]We could be electrocuted by this...[n]Dreadful indeed.[n][f 1 6 65535][e]

[msg AEGIS_DENKISAKU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15373]Perhaps I can charge with this[n]electricity... No, never mind.[n][f 1 6 65535][e]

[msg AEGIS_DENKISAKU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15374]I advise we stop the electric current[n]before proceeding.[n][f 1 6 65535][e]

[msg AEGIS_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15375]There appears to be a[n]strong wind present![n][f 1 6 65535][e]

[msg AEGIS_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15376]Oh, how peculiar...[n][f 1 6 65535][e]

[msg AEGIS_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15377]I appear to be flying.[n][f 1 6 65535][e]

[msg AEGIS_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15324]Stairs located! It seems we can now[n]proceed.[n][f 1 6 65535][e]

[msg AEGIS_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15325]Stairs detected! Shall we use them?[n][f 1 6 65535][e]

[msg AEGIS_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15326]I suggest we move to a new area.[n][f 1 6 65535][e]

[msg AEGIS_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15327]I have confirmed there is a treasure[n]chest up ahead![n][f 1 6 65535][e]

[msg AEGIS_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15328]Treasure chest discovered. Perhaps we[n]will find "loot."[n][f 1 6 65535][e]

[msg AEGIS_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15329]A treasure chest... In other words,[n]booty![n][f 1 6 65535][e]

[msg AEGIS_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15330]I am detecting a curiosity up ahead.[n][f 1 6 65535][e]

[msg AEGIS_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15331]Irregularity detected ahead. I propose[n]we investigate.[n][f 1 6 65535][e]

[msg AEGIS_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15332]I propose that we investigate the area.[n][f 1 6 65535][e]

[msg AEGIS_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15333]Switch located![n][f 1 6 65535][e]

[msg AEGIS_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15334]Switch visual confirmed. What is our[n]course of action?[n][f 1 6 65535][e]

[msg AEGIS_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15335]A switch has been located. Do we[n]press it or destroy it?[n][f 1 6 65535][e]

[msg AEGIS_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15336]Potential shortcut located.[n][f 1 6 65535][e]

[msg AEGIS_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15337]I have located a potential pathway.[n][f 1 6 65535][e]

[msg AEGIS_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15338]I have uncovered a potential shortcut.[n][f 1 6 65535][e]

[msg AEGIS_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15387]【パーティの半分以上が死んでいる】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15388]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15389]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_FOE_WARNING_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15309]The FOE remains locked on![n][f 1 6 65535][e]

[msg AEGIS_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15310]The FOE is still in pursuit![n][f 1 6 65535][e]

[msg AEGIS_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15311]The enemy FOE is closing in![n][f 1 6 65535][e]

[msg AEGIS_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15315]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15316]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15317]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15321]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15322]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15323]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15312]I feel as if I will overheat...[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15313]I suggest we return.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15314]If this continues, I will be in danger of[n]shutting down.[n][f 1 6 65535][e]

[msg AEGIS_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15327]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15328]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15329]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15315]Reporting a decrease in health.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15316]There is a possibility of key functions[n]shutting down.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15317]Health is now at critical![n][f 1 6 65535][e]

[msg AEGIS_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15318]Reporting a decrease in stamina.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15319]My stamina has reached[n]its limits...[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15320]I detect a decrease in stamina. I[n]believe you call it being tired. [n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15390]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15391]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15392]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15321]That was a magnificent battle. It was[n]way past cool.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15322]That battle yielded excellent results.[n][f 1 6 65535][e]

[msg AEGIS_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15323]【パーティ誰かのＨＰが８０％以上】ランクトリプルＳの戦闘でした。[n][f 1 6 65535][e]

[msg AEGIS_BATTLE_CHANGE_DUNG]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15393]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_BATTLE_CHANGE_DUNG_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15393]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_BATTLE_CHANGE_DUNG_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15393]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15390]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15391]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15392]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15360]Let us steel our resolve for the task[n]ahead![n][f 1 6 65535][e]

[msg AEGIS_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15361]I believe the phrase is, "Let's go!"[n][f 1 6 65535][e]

[msg AEGIS_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15362]Let us strive for complete control of[n]this place![n][f 1 6 65535][e]

[msg AEGIS_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15363]Aigis, reporting![n][f 1 6 65535][e]

[msg AEGIS_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15364]Commencing mission.[n][f 1 6 65535][e]

[msg AEGIS_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15365]I propose that we resolve this quickly![n][f 1 6 65535][e]

[msg AEGIS_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15352]We still have quite a ways to go.[n][f 1 6 65535][e]

[msg AEGIS_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15353]I propose we take breaks throughout[n]our exploration.[n][f 1 6 65535][e]

[msg AEGIS_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15354]Our progress is at 50%![n][f 1 6 65535][e]

[msg AEGIS_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15355]Filling out our map will likely boost[n]exploration efficiency.[n][f 1 6 65535][e]

[msg AEGIS_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15356]"Not much further now," is a suitable[n]turn of phrase.[n][f 1 6 65535][e]

[msg AEGIS_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15357]It is my hope that we fill in the[n]remaining areas soon.[n][f 1 6 65535][e]

[msg AEGIS_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15358]This floor is now under our control...[n]Well done![n][f 1 6 65535][e]

[msg AEGIS_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15359]The map is complete. Well done.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_ALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15342]Not one millimeter off.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15343]Most impressive![n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_KAIDA]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15344]That would be correct.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_KAIDA_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15345]We can now traverse the floor[n]without getting lost.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_CHANGE_COL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15346]I see. This map now appears to[n]possess a special quality.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_CHANGE_COL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15347]Your artistic ability has revealed itself.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_DEL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15348]That which is not necessary shall be[n]deleted![n][f 1 6 65535][e]

[msg AEGIS_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15349]Clean and efficient as ever.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15350]If we do not take note, we will surely[n]forget.[n][f 1 6 65535][e]

[msg AEGIS_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15351]We need to take note of this so we do[n]not forget, yes?[n][f 1 6 65535][e]

[msg AEGIS_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15366]I've often heard people say,[n]"after you."[n][f 1 6 65535][e]

[msg AEGIS_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15367]This way![n][f 1 6 65535][e]

[msg AEGIS_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15368]Allow me to scout ahead![n][f 1 6 65535][e]

[msg AEGIS_KARITORU_ENCOUNT_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15384]【刈り取るものとエンカウントした】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg AEGIS_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15385]【刈り取るものとエンカウントした】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg AEGIS_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15386]【刈り取るものとエンカウントした】[n]ダミーメッセージ３[n][f 1 6 65535][e]

