[msg HARU_FOE_FOLLOW_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27300]Oh dear! We've been spotted![n][f 1 6 65535][e]

[msg HARU_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27301]We're being followed, guys![n][f 1 6 65535][e]

[msg HARU_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27302]FOE headed our way![n][f 1 6 65535][e]

[msg HARU_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27303]Shhh! It's right there...[n][f 1 6 65535][e]

[msg HARU_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27304]Take precautions, everyone.[n][f 1 6 65535][e]

[msg HARU_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27305]Please don't let it see us...[n][f 1 6 65535][e]

[msg HARU_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27306]*sigh* That was so close...[n][f 1 6 65535][e]

[msg HARU_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27307]We got away, we got away![n][f 1 6 65535][e]

[msg HARU_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27308]*giggle* Looks like we won in the end![n][f 1 6 65535][e]

[msg HARU_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27369]Let's keep a lookout, everyone![n][f 1 6 65535][e]

[msg HARU_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27370]Let's be on our tippy toes...[n][f 1 6 65535][e]

[msg HARU_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27371]I'm getting a tad nervous.[n][f 1 6 65535][e]

[msg HARU_DENKISAKU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27372]This... may be a bit excessive for[n]keeping crows away.[n][f 1 6 65535][e]

[msg HARU_DENKISAKU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27373]I wonder what the voltage is...[n][f 1 6 65535][e]

[msg HARU_DENKISAKU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27374]We have to turn the electricity off[n]first...[n][f 1 6 65535][e]

[msg HARU_KYOUHU_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27375]Whoa![n][f 1 6 65535][e]

[msg HARU_KYOUHU_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27376]Eek![n][f 1 6 65535][e]

[msg HARU_KYOUHU_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27377]Ahh![n][f 1 6 65535][e]

[msg HARU_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27324]Oh! It's the way to the next area![n][f 1 6 65535][e]

[msg HARU_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27325]Yay! We can go to the next floor![n][f 1 6 65535][e]

[msg HARU_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27326]Just imagine what the next area is like![n][f 1 6 65535][e]

[msg HARU_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27327]A treasure box![n][f 1 6 65535][e]

[msg HARU_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27328]It's a treasure box, let's check it out![n][f 1 6 65535][e]

[msg HARU_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27329]Is that treasure over there?[n][f 1 6 65535][e]

[msg HARU_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27330]Hmm... Something's fishy...[n][f 1 6 65535][e]

[msg HARU_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27331]Let's check out that area.[n][f 1 6 65535][e]

[msg HARU_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27332]Hey, what do you think that is...?[n][f 1 6 65535][e]

[msg HARU_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27333]Oh look, a switch.[n][f 1 6 65535][e]

[msg HARU_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27334]You thinking we ought to use[n]the switch?[n][f 1 6 65535][e]

[msg HARU_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27335]Oh hi, switch.[n][f 1 6 65535][e]

[msg HARU_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27336]We've got ourselves a shortcut![n][f 1 6 65535][e]

[msg HARU_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27337]A hidden passage, perhaps?[n][f 1 6 65535][e]

[msg HARU_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27338]Did we find a shortcut?[n][f 1 6 65535][e]

[msg HARU_PARTY_DEAD_1]
[f 0 5 65278][f 2 1]【パーティの半分以上が死んでいる】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_PARTY_DEAD_2]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_PARTY_DEAD_3]
[f 0 5 65278][f 2 1]【パーティーの半分以上が死んでいる】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_FOE_WARNING_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27309]It still hasn't given up!?[n][f 1 6 65535][e]

[msg HARU_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27310]Guys, it's still following us![n][f 1 6 65535][e]

[msg HARU_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27311]It doesn't give up easily, that's for sure.[n][f 1 6 65535][e]

[msg HARU_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_PARTY_HP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_PARTY_HP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_PARTY_HP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＨＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27312]Um, can I have someone heal me?[n][f 1 6 65535][e]

[msg HARU_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27313]Excuse me, but can we rest...?[n][f 1 6 65535][e]

[msg HARU_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27314]I'm sorry, I don't think I can keep up...[n][f 1 6 65535][e]

[msg HARU_PARTY_TP10_1]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_PARTY_TP10_2]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_PARTY_TP10_3]
[f 0 5 65278][f 2 1]【パーティ全体のＴＰが１０％以下】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27315]I need healing soon...[n][f 1 6 65535][e]

[msg HARU_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27316]This is pretty hard on me right now...[n][f 1 6 65535][e]

[msg HARU_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27317]I'm not in the best of shape...[n][f 1 6 65535][e]

[msg HARU_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27318]I'm trying but... I can hardly stay[n]awake.[n][f 1 6 65535][e]

[msg HARU_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27319]Just putting one foot in front of the[n]other is hard for me in my state...[n][f 1 6 65535][e]

[msg HARU_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27320]I might have pushed myself too hard...[n][f 1 6 65535][e]

[msg HARU_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（バトル後）】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27321]I'm good if you guys are good![n][f 1 6 65535][e]

[msg HARU_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27322]*giggle* I think I'm on a roll today![n][f 1 6 65535][e]

[msg HARU_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27323]Everyone's so energetic![n][f 1 6 65535][e]

[msg HARU_BATTLE_CHANGE_DUNGE]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_BATTLE_CHANGE_DUNGE_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_BATTLE_CHANGE_DUNGE_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg HARU_ITEM_90_DUNGEON_1]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_ITEM_90_DUNGEON_2]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_ITEM_90_DUNGEON_3]
[f 0 5 65278][f 2 1]【アイテム枠が９０％以上（ＤＧ出入り）】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27360]A fresh new investigation![n][f 1 6 65535][e]

[msg HARU_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27361]*giggle* This is starting to get fun.[n][f 1 6 65535][e]

[msg HARU_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27362]I'm excited to see what will happen.[n][f 1 6 65535][e]

[msg HARU_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27363]Everyone all set?[n][f 1 6 65535][e]

[msg HARU_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27364]I'm going to do my best![n][f 1 6 65535][e]

[msg HARU_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27365]Ready, set, go![n][f 1 6 65535][e]

[msg HARU_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27352]I'm so excited to see the final version![n][f 1 6 65535][e]

[msg HARU_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27353]It's starting to look like a map![n][f 1 6 65535][e]

[msg HARU_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27354]Halfway there![n][f 1 6 65535][e]

[msg HARU_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27355]Whew, halfway![n][f 1 6 65535][e]

[msg HARU_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27356]Are we almost done?[n][f 1 6 65535][e]

[msg HARU_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27357]Almost done, we've got this![n][f 1 6 65535][e]

[msg HARU_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27358]Hooray! We finished the map![n][f 1 6 65535][e]

[msg HARU_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27359]Look! It turned out a wonderful map![n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_ALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27342]Wow! That's really good![n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27343]You draw it so nicely.[n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_KAIDAN]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27344]That's an accurate representation.[n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_KAIDAN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27345]Mmhm that's how I remember it.[n][f 1 6 65535][e]

[msg HARU_MAPPING_CHANGE_COLO]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27346]*giggle* Adding a personal touch, are[n]we?[n][f 1 6 65535][e]

[msg HARU_MAPPING_CHANGE_COLO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27347]Oh, changing the color?[n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_DEL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27348]You're taking it out?[n][f 1 6 65535][e]

[msg HARU_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27349]Mmhm, let's get rid of it.[n][f 1 6 65535][e]

[msg HARU_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27350]So beautiful![n][f 1 6 65535][e]

[msg HARU_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27351]Excellent, we won't forget if we note it[n]down.[n][f 1 6 65535][e]

[msg HARU_DOOR_OPEN_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27366]This way![n][f 1 6 65535][e]

[msg HARU_DOOR_OPEN_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27367]Ready? Let's go.[n][f 1 6 65535][e]

[msg HARU_DOOR_OPEN_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27368]*giggle* Come on! Hurry![n][f 1 6 65535][e]

[msg HARU_KARITORU_ENCOUNT_1]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg HARU_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg HARU_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1]【刈り取るものとエンカウントした】[n]ダミーメッセージ３[n][f 1 6 65535][e]

