[msg CAROLIN_FOE_FOLLOW_START]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58300]You idiots, an FOE spotted you all![n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_START]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59300]It's the...[n][f 1 6 65535][e]

[msg CAROLIN_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58301]It's following you![n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59301]The FOE found you.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58302]Hey, the FOE noticed you![n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59302]It is now pursuing you.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58303]You better be careful![n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59303]The FOE is coming closer.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58304]Don't get close if you're not willing to[n]fight it![n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59304]Please be aware that the FOE[n]is nearby.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58305]An FOE's nearly on top of you![n][f 1 6 65535][e]

[msg JUSTINE_FOE_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59305]Please proceed with caution.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58306]Looks like the FOE gave up![n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59306]It looks like they can relax, Caroline.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58307]Good work, you got away![n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59307]The FOE stopped chasing you.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58308]Huh? What happened to it?[n][f 1 6 65535][e]

[msg JUSTINE_FOE_FOLLOW_END_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59308]It appears the FOE has ceased[n]chasing them, Caroline.[n][f 1 6 65535][e]

[msg CAROLIN_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58375]Avoid those lights, got it!?[n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59375]Proceed without allowing any light to[n]illuminate you.[n][f 1 6 65535][e]

[msg CAROLIN_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58376]Avoid them and you won't be seen![n]Got that?[n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59376]Until you turn the switch off, avoid[n]the spotlights.[n][f 1 6 65535][e]

[msg CAROLIN_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58377]If you can't turn the lights off, then at[n]least stay far away from them![n][f 1 6 65535][e]

[msg JUSTINE_KANSI_REACTION_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59377]Avoid them and you shan't be spotted.[n][f 1 6 65535][e]

[msg CAROLIN_DENKISAKU_REACTI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58378]If you don't want a nasty shock, look[n]for the switch![n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59378]Unless you impede the electricity, you[n]cannot proceed.[n][f 1 6 65535][e]

[msg CAROLIN_DENKISAKU_REACTI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58379]Look for the switch! It's gotta be[n]around there somewhere![n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59379]There is most likely a switch which you[n]can use to stop the electricity.[n][f 1 6 65535][e]

[msg CAROLIN_DENKISAKU_REACTI_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58380]*chuckle* It's like our executions![n][f 1 6 65535][e]

[msg JUSTINE_DENKISAKU_REACTI_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59380]If you locate the switch, you will be[n]able to proceed.[n][f 1 6 65535][e]

[msg CAROLIN_KYOUHU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58381]Fascinating... Try moving with the[n]wind.[n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59381]A mighty wind...![n][f 1 6 65535][e]

[msg CAROLIN_KYOUHU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58382]H-Hey!?[n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59382]Try using the wind to your advantage,[n]perhaps to augment your movement.[n][f 1 6 65535][e]

[msg CAROLIN_KYOUHU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58383]I see all of your minds have been[n]blown![n][f 1 6 65535][e]

[msg JUSTINE_KYOUHU_REACTION__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59383]Are any of you struggling...?[n][f 1 6 65535][e]

[msg CAROLIN_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58333]Hey, Justine, you think that's a[n]staircase?[n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59333]It appears to be one. Please confirm.[n][f 1 6 65535][e]

[msg CAROLIN_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58334]I found a staircase, Justine![n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59334]Excellent work, Caroline. I wouldn't[n]expect any less from you.[n][f 1 6 65535][e]

[msg CAROLIN_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58335]Hah, there we go! Now let's keep[n]going![n][f 1 6 65535][e]

[msg JUSTINE_STAIR_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59335]There appear to be stairs up ahead.[n][f 1 6 65535][e]

[msg CAROLIN_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58336]Ooh, a treasure box! Hurry up and[n]open it![n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59336]That must be a treasure box.[n][f 1 6 65535][e]

[msg CAROLIN_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58337]Hey, is that a treasure box?[n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59337]What luck. You've stumbled upon a[n]treasure box.[n][f 1 6 65535][e]

[msg CAROLIN_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58338]A treasure box! Aren't you gonna get[n]it!?[n][f 1 6 65535][e]

[msg JUSTINE_TREASURE_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59338]That must be what others call[n]treasure.[n][f 1 6 65535][e]

[msg CAROLIN_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58339]Hey, check that area! There's[n]something there.[n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59339]It is evident that there is something[n]interesting around there.[n][f 1 6 65535][e]

[msg CAROLIN_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58340]I sense there's something beneficial[n]to you around here![n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59340]I sense something in that area.[n][f 1 6 65535][e]

[msg CAROLIN_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58341]Get busy and search this area![n][f 1 6 65535][e]

[msg JUSTINE_CHECK_WALL_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59341]It may be wise to investigate the area.[n][f 1 6 65535][e]

[msg CAROLIN_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58342]Are you going to use that switch?[n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59342]That must be... some type of switch.[n][f 1 6 65535][e]

[msg CAROLIN_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58343]Hey! There's a switch over there![n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59343]Take note, there's a switch nearby.[n][f 1 6 65535][e]

[msg CAROLIN_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58344]I found a switch![n][f 1 6 65535][e]

[msg JUSTINE_SWITCH_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59344]Something may change in this[n]environment if you use the switch.[n][f 1 6 65535][e]

[msg CAROLIN_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58345]I'm sensing there's a wall you can go[n]through! Check around you![n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59345]There may be a way for you to pass[n]through the nearby wall.[n][f 1 6 65535][e]

[msg CAROLIN_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58346]You can probably go through that wall![n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59346]That wall is probably one you can walk[n]through.[n][f 1 6 65535][e]

[msg CAROLIN_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58347]You should check that wall. It's a[n]shortcut candidate![n][f 1 6 65535][e]

[msg JUSTINE_SHORTCUT_FIND_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59347]Please check the nearby walls.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58387]H-Hurry up and get back to the[n]theater![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59387]Caroline... Do you think they'll be[n]okay...?[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58388]Heal first! Then we'll talk![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59388]Just focus on healing.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58389]H-Hey! Are you guys all right!?[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_DEAD_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59389]Remember that returning is also an[n]option.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_WARNING_NEAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58309]That was an intense battle![n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59309]The FOE is still pursuing you. Stay alert,[n]Caroline.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58310]The FOE is still coming after you![n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59310]Continue to use caution.[n][f 1 6 65535][e]

[msg CAROLIN_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58311]Don't let your guard down! Justine,[n]stay on the lookout![n][f 1 6 65535][e]

[msg JUSTINE_FOE_WARNING_NEAR_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59311]The FOE is continuing to stalk you.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58315]Cancel the operation! Return to the[n]theater![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59315]I can see that everyone has exhausted[n]their energy reserves.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58316]Look at you lot! You're all barely[n]hanging on![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59316]We should abort the operation.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58317]Hey! Not one of you is looking good![n]Get back to the theater![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59317]It's obvious that everyone is fatigued.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58321]Hey, you all are flagging! Take a break![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59321]That's unusually compassionate of you[n]to notice, Caroline... And I do agree.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58322]Hurry up and heal![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59322]I'm seeing the party's health is on a[n]steady decline.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58323]You all need to patch yourselves up![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59323]It may be best to pause and heal.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58312]You need a breather! Heal yourselves![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59312]Aren't you overtaxing yourself?[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58313]Hurry up and heal![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59313]It looks like health and energy are[n]dangerously low.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58314]Looks like you've hit your limit.[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HPTP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59314]Please lend him a helping hand.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58327]Hey! Watch your energy levels![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59327]Caroline, we should let them rest.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58328]Tch! You're right; they need it! I order[n]you all to come back![n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59328]They're all worn out... Let's have them[n]come back and rest, Caroline.[n][f 1 6 65535][e]

[msg CAROLIN_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58329]What happened to your energy!?[n][f 1 6 65535][e]

[msg JUSTINE_PARTY_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59329]You may face increasing difficulty if[n]you continue to do battle in your state.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58318]Justine is right! Take a break![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59318]Inmate, your health is so low. Perhaps[n]a break is in order?[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58319]Hurry up and heal![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59319]The prisoner's health is getting very[n]low.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58320]Hey! Reminder: that searing pain[n]you feel is your health going down![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59320]Please heal immediately.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58324]You better be grateful for Justine's[n]compassion![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59324]All signs point to exhaustion...[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58325]You're out of energy!? Did you have[n]no plan at all!?[n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59325]Alas, they're running out of energy.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58326]Hey! Your energy's looking bad![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_TP10_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59326]They've been pushed to their limit.[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58390]Tsk, tsk, you greedy fool![n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59390]You have too many things.[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58391]You can't even organize your items!?[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59391]It would behoove you to be organized.[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58392]Have you lost track of how much you[n]have?[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_BATTLE_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59392]You have far too many things. I[n]recommend organizing them.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58330]Not a bad strategy. [n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59330]You're right, Caroline. It puts our[n]minds at ease, as well.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58331]Not bad, on to the next![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59331]That was a swell fight.[n][f 1 6 65535][e]

[msg CAROLIN_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58332]Hurry on to the next one![n][f 1 6 65535][e]

[msg JUSTINE_1PERSON_HP80_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59332]It looks like you've still got some fight[n]in you.[n][f 1 6 65535][e]

[msg CAROLIN_BATTLE_CHANGE_DU]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg CAROLIN_BATTLE_CHANGE_DU_2]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg CAROLIN_BATTLE_CHANGE_DU_3]
[f 0 5 65278][f 2 1]【バトルからダンジョン担当へナビ切り替え】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_DUNGEON_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58390]Tsk, tsk, you got greedy.[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON_]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59390]You have too many things.[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_DUNGEON__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58391]You can't even organize your items!?[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON__2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59391]It would behoove you to be organized.[n][f 1 6 65535][e]

[msg CAROLIN_ITEM_90_DUNGEON__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58392]Have you lost track of how much you[n]have?[n][f 1 6 65535][e]

[msg JUSTINE_ITEM_90_DUNGEON__3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59392]You have far too many things. I[n]recommend organizing them.[n][f 1 6 65535][e]

[msg CAROLIN_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58369]We'll give you the information you[n]need.[n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59369]So you are starting your exploration?[n][f 1 6 65535][e]

[msg CAROLIN_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58370]Time to get this investigation[n]underway![n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59370]Then we shall provide backup.[n][f 1 6 65535][e]

[msg CAROLIN_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58371]You didn't forget anything, did you?[n][f 1 6 65535][e]

[msg JUSTINE_DUNGEON_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59371]Now, let us begin.[n][f 1 6 65535][e]

[msg CAROLIN_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58372]All right! Let's blow this hatch![n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59372]Let's get this special screening[n]underway.[n][f 1 6 65535][e]

[msg CAROLIN_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58373]We will now raise curtains on the[n]special screening![n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59373]We'll provide assistance until the very[n]end.[n][f 1 6 65535][e]

[msg CAROLIN_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58374]Fine, I guess we'll help you out![n][f 1 6 65535][e]

[msg JUSTINE_QUEST_START_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59374]Well then, let's get this started.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58361]We still have a long ways to go![n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_25_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59361]This is only the beginning.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58362]We're not even halfway done! Don't[n]slack off![n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_25_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59362]It seems you've made real progress on[n]the map.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58363]Hey! We've only got half the map[n]drawn![n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_50_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59363]This must be about halfway...[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58364]Finally we're halfway done. Not bad.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_50_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59364]I'd say you've finally reached the[n]halfway point.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58365]We're almost done with the whole[n]area! No time to rest![n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_75_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59365]We only need to explore a bit further[n]to complete this floor.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58366]Just a little more, and then the floor of[n]this movie's a wrap![n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_75_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59366]Just a little more until we complete[n]this floor.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58367]Well, since you finished drawing this[n]floor, I guess you deserve some praise.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_100_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59367]We completed the entire map. That's[n]an accomplishment.[n][f 1 6 65535][e]

[msg CAROLIN_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58368]You know every nook and cranny now.[n][f 1 6 65535][e]

[msg JUSTINE_TOUHA_100_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59368]We've explored every area of this[n]floor.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_ALL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58351]Don't you have any sense of artistry?[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_ALL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59351]That's not bad.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58352]You're actually doing well with this[n]cartography business.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_ALL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59352]Not bad for a prisoner.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_KAI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58353]Not forgetting to draw the staircase. I[n]like that.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_KAI]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59353]Surely this excellent performance is a[n]result of our rehabilitative efforts.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_KAI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58354]Smart move, drawing it in. Just don't[n]go forgetting about it![n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_KAI_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59354]You're going to mark the staircase,[n]yes?[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_CHANGE_C]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58355]What kind of map are you drawing,[n]exactly!?[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_CHANGE_C]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59355]I am interested in the final product of[n]all this mapping.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_CHANGE_C_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58356]Well, it's certainly an interesting map.[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_CHANGE_C_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59356]So that's the color you use.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_DEL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58357]It's just like our rehabilitation of you![n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_DEL]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59357]Mistakes must be rectified.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58358]Why'd you draw it in the first place, if[n]you were just gonna erase it?[n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_ICON_DEL_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59358]Keeping the map clean is a good idea.[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58359]Hey! Don't forget about that memo![n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_MEMO_1]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59359]Taking notes? Ah, you've probably had[n]some hard lessons in the past...[n][f 1 6 65535][e]

[msg CAROLIN_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58360]You better write it neatly![n][f 1 6 65535][e]

[msg JUSTINE_MAPPING_MEMO_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59360]Now we won't have to rely on our[n]oh-too-fickle memories.[n][f 1 6 65535][e]

[msg CAROLIN_DOOR_OPEN_1]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ１[n][f 1 6 65535][e]

[msg CAROLIN_DOOR_OPEN_2]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ２[n][f 1 6 65535][e]

[msg CAROLIN_DOOR_OPEN_3]
[f 0 5 65278][f 2 1]【扉を進んだ】[n]ダミーメッセージ３[n][f 1 6 65535][e]

[msg CAROLIN_KARITORU_ENCOUNT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58384]The Reaper is near![n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59384]The Reaper approaches. Please be[n]careful.[n][f 1 6 65535][e]

[msg CAROLIN_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58385]Incoming Reaper![n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT_2]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59385]Please take care, for there's a Reaper[n]afoot.[n][f 1 6 65535][e]

[msg CAROLIN_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58386]I know this sound, it's the Reaper![n][f 1 6 65535][e]

[msg JUSTINE_KARITORU_ENCOUNT_3]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59386]It's the Reaper... your only chance is to[n]maintain focus.[n][f 1 6 65535][e]

