[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23039]夷Un callej吋n sin salida? Me estoy[n]cansando de ver a Kamoshidaman por todas partes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 3]No bromees, es que estoy fuera... 夷Ves[n]esas se隠ales en el camino?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todos lo estaban haciendo. Espeluznante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 1][f 3 1 1 0 0 22052]Sheesh, 夷por qu姻 tienes que[n]mencionarlo? He estado intentando no mirarlos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]夷Qu姻? Est茨n por toda la maldita[n]ciudad... No puedo evitar pensar en el palacio[n]de Kamoshida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Lo s姻. 夷Por qu姻 no los hacemos desaparecer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 0]夷C吋mo hacemos eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 1 0][f 3 1 1 0 0 22030]斡Quemamos a todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_006_1 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 1 4 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Baila, Carmen![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]斡Gran idea! 斡Ayuda![n][f 1 3 65535][f 1 1][e]

[msg MSG_007_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 1 5 0][f 3 1 1 0 0 21107]Ap茨rtese, Capit茨n..[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 2]斡Oye! 夷Qu姻 est茨s haciendo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]C茨lmate.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]D姻jame ayudar.[f 2 7 1 20 0 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 28 12 0 1][f 3 1 1 0 0 28068]Joker tiene raz吋n. No queremos llamar la atenci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 28 6 0 1][f 3 1 1 0 0 28092]夷T雨 tambi姻n, Joker...? Tranquilo. No[n]queremos llamar la atenci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 12 0 1][f 3 1 1 0 0 0]S姻 que pas吋 mucho entre Kamoshida y t雨...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y estoy seguro de que no es f茨cil[n]olvidar lo que hizo tampoco, pero el que aqu胤[n]no es real.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 4][f 3 1 1 0 0 22028][f 6 1 2 0 0 10]Lo siento... Pensar en ello me hace tan[n]irritado. Tengo que calmarme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]S胤, lo siento... Resolver la Queen y[n]Noir es m茨s importante ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500][f 6 1 2 0 0 1]斡As胤 es! 斡Vamos, vamos![n][f 1 3 65535][f 1 1][e]

