[msg MSG_000 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 23 1 0 6][f 4 6 85 2 0 1][f 3 1 1 0 0 65040]Eh... S胤, puedo sentir buenos patos en[n]eso. No est茨 mal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 6 1 2 0 0 7][f 3 1 1 0 0 0]Nyeheheh... Lo s姻, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1][f 3 1 1 0 0 65006][f 6 1 3 0 0 0]夷Quieres elegir un Sub-Persona para[n]adjuntar al P-Book?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 0]El [f 0 1 2]Sub-Persona que adjuntas no[n]desaparecer茨[f 0 1 0], as胤 que no lo estreses.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 1][f 3 1 1 0 0 0][f 6 1 3 0 0 0]Y puedes cambiarlo m茨s tarde de todos[n]modos, as胤 que elige uno por ahora.[n][f 1 3 65535][f 1 1][e]

