[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 1][f 3 1 6 0 0 500]That guy just now―don't tell me, was[n]that Hikari's...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2]Yeah. She had said that Doe was a being[n]created by the feelings she couldn't[n]get rid of.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 3]As for the movie we just saw, that[n]first segment was exactly the same[n]as what we'd seen earlier...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]However, the feelings expressed toward[n]Hikari-san were completely different[n]this time.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 12 0 3][f 3 1 1 0 0 5][f 6 1 2 0 0 10]Hey, hey! Forget all that for[n]now―how's Hikari-chan!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 15 1 2 1][f 3 1 1 0 0 6]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7][f 6 1 3 0 0 1]No issues with her pulse or blood[n]pressure. I believe she has only[n]lost consciousness temporarily.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 3 0 0][f 3 1 1 0 0 8]Thank goodness... She's okay then.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Doe]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 82 6 1 1][f 3 1 1 0 0 9]Ngh... Nngh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 10]Well then, what should we do with[n]him? There's still a danger of him[n]going berserk again.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]I suppose we could at least tie him up,[n]to be safe...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 6 6 1][f 3 1 1 0 0 12][f 6 1 2 0 0 3]Mm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 99 0][f 3 1 1 0 0 13][f 6 1 2 0 0 6][f 3 1 6 0 0 500]Oh! It looks like Hikari-chan's coming[n]around![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14][f 6 1 3 0 0 1]Doe's... not an enemy...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 15]...Ah. Do you remember now?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 16]I know that movie. It's been filming[n]for such a long time...[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]What movie?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Is that so?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Did you shoot it, Hikari?[f 2 7 1 20 0 32][e]

[msg MSG_015 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 6][f 3 1 1 0 0 17][f 6 1 2 0 0 4]Movie...? Do you mean that black-and-[n]white footage we keep seeing?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 18]Well, now that you mention it, it did[n]seem a lot like a home video...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 3 0 0 1]Mmhm... Ever since I was little...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20][f 6 1 3 0 0 1]No, just the opposite. I'm the one[n]who was always filmed.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 8 12 0 0][f 3 1 1 0 0 21][f 6 1 2 0 0 4]Then... does that mean the movie was[n]shot by your family?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 22]That's right... The one who's always[n]watched over me, standing right by[n]my side...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Doe]]
[f 0 5 65278][f 2 1][f 4 6 82 0 0 0][f 3 1 1 0 0 23]Hikari...[n][f 1 3 65535][f 1 1][e]

