[msg MSG_000 [Gloomy-looking student]]
[f 0 5 65278][f 2 1][f 4 6 57 1 0 1][f 3 1 1 0 0 0]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Innocent girl]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 3]Don't let it get to you. I'll help you[n]clean it off.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Gloomy-looking student]]
[f 0 5 65278][f 2 1][f 4 6 57 10 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 4]...Huh?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Ah―Thank you.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 0][f 3 1 1 0 0 5]Um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 4]I'm Hikari. You're Miyuki-chan, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7]Nice to meet you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 0][f 3 1 1 0 0 8]Hikari-chan... Um, it's nice to meet you[n]too...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 0][f 3 1 1 0 0 9]You really like movies, don't you,[n]Hikari-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 1 0][f 3 1 1 0 0 10]Mmhm! Even if I've seen it before,[n]I can watch it over and over.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]The one I saw the other day had[n]dinosaurs in it! Let's watch it together[n]sometime.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 2 1 0][f 3 1 1 0 0 12][f 6 1 2 0 0 6]Huh!? Are you sure? I'd love to![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 4]I know! Why don't we all go see it[n]together, then?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 0 1 1][f 3 1 1 0 0 14]Huh? Oh, I'll have to pass...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 1 1][f 3 1 1 0 0 15]I've got cram school to get to...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 0 1 1][f 3 1 1 0 0 16][f 6 1 2 0 0 6]Sorry about that! Maybe next time...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]I see. That's too bad... but, okay![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 57 0 1 3][f 3 1 1 0 0 18]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 3][f 3 1 1 0 0 19]What happened to my desk...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 1 0 1][f 3 1 1 0 0 20]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 21][f 6 1 2 0 0 4]Hey, do you know anything about this?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 1 1][f 3 1 1 0 0 22]Oh boy... It's your own fault, Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 16 1 0][f 3 1 1 0 0 23][f 6 1 2 0 0 4]Huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 4][f 3 1 1 0 0 24]Didn't you know the popular kids have[n]all started picking on Miyuki?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 0 0 1][f 3 1 1 0 0 25]Since you hang out with her, they're[n]after you too now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 4][f 3 1 1 0 0 26]Miyuki, could you just leave us alone?[n]We're gonna end up dragged into this[n]mess too.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 4 1 0][f 3 1 1 0 0 27]Wha―?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 1][f 3 1 1 0 0 28]If Miyuki goes away, I'm sure you won't[n]get hassled anymore, Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 2 1 0][f 3 1 1 0 0 29][f 6 1 2 0 0 1]But, that kind of thing doesn't bother[n]me. Let's all just stay friends![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 0][f 3 1 1 0 0 0]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30][f 6 1 2 0 0 4]Why do you have to be like that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 0][f 3 1 1 0 0 31]If you're gonna be like that, then why[n]don't you just take Miyuki's place?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 6 37 2 1 3][f 3 1 1 0 0 32][f 6 1 2 0 0 0]Wait, what!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 0 0 4][f 3 1 1 0 0 33]The popular girls just want someone[n]they can tease...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 34]If you stick around us, we'll get it too.[n]You're just gonna make trouble for us.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 0][f 3 1 1 0 0 35]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 56 0 0 1][f 3 1 1 0 0 36][f 6 1 2 0 0 6]Alright, everybody! Who thinks Hikari[n]should leave our group?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 2 1 0][f 3 1 1 0 0 37]Me![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 2 1 4][f 3 1 1 0 0 38]Me too...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Middle school Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 37 10 2 3][f 3 1 1 0 0 39][f 6 1 2 0 0 4]No... Why?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Nervous schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 55 0 1 1][f 3 1 1 0 0 40]I mean, it's what everyone else is saying,[n]so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Sulky schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 1][f 3 1 1 0 0 41][f 6 1 2 0 0 4]Yeah, everyone agrees. You do too, right,[n]Miyuki?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 6][f 3 1 1 0 0 42]I-I...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 6][f 3 1 1 0 0 43]......[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 44]Welp, in that case, Miyuki's the one[n]who's out.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 6 1 0][f 3 1 1 0 0 45][f 6 1 2 0 0 6]W-Wait![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 57 0 0 4][f 3 1 1 0 0 46]I-I... agree that Hikari-chan should go...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Loud schoolgirl]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 47]You see? Everyone agrees, so that's[n]the obvious decision.[n][f 1 3 65535][f 1 1][e]

