[msg MSG_000 [Yosuke]]
Alright! No more locks in our way!

[msg MSG_001 [P3 Fem Protag]]
We can go home now, right? That was a[n]long journey, but it's finally over.

[msg MSG_002 [Junpei]]
Hrmm... Now that we're done, I'm[n]starting to get hungry.

[msg MSG_003 [Chie]]
Me too! I can't wait to get back home[n]and eat as much as possible!

[msg MSG_004 [P4 Hero]]
Then you should come by my place. I'm[n]sure it'd make Nanako happy.

[msg MSG_005 [Rise]]
Yay! Let's go, let's go!

[msg MSG_006 [Junpei]]
We should have a celebration too! You[n]know, in the dorm lobby!

[msg MSG_007 [Mitsuru]]
We don't have the time to squander. Once[n]we've returned, we'll resume our mission[n]immediately.

[msg MSG_008 [Junpei]]
Whaaaat!? You're workin' us to death!

[msg MSG_009 [Akihiko]]
If you rest too much, your technique[n]will get sloppy.
Once we're at the dorm, it's right back[n]to training―got it, Shinji?

[msg MSG_010 [Shinjiro]]
Why the hell're you ropin' me into it!?

[msg MSG_011 [Morgana]]
Hey, gang! We need to continue with our[n]own operation when we get back, too.

[msg MSG_012 [Ryuji]]
I know, I know... By the way, where are[n]we gonna end up once we go through these[n]doors?

[msg MSG_013 [Haru]]
Maybe... Mementos?
But, aren't we all trying to return to[n]different places?

[msg MSG_014 [Ann]]
Hmm, I don't know... Maybe we'll just[n]end up in the right places once we[n]leave?

[msg MSG_015 [Makoto]]
Th-That's a rather large assumption...

[msg MSG_016 [Akechi]]
Still, this is our only exit. We have no[n]choice but to go this way.

[msg MSG_017 [P3 Fem Protag]]
Hikari-chan... I guess that makes this[n]our goodbye.

[msg MSG_018 [Hikari]]
Mm-hm...
-chan, thank you so much.

[msg MSG_019 [P3 Fem Protag]]
Huh?

[msg MSG_020 [Hikari]]
Even after you were separated from your[n]companions and stuck all alone here, you[n]stayed strong.
You were always cheerful, and tried your[n]best, like you refused to lose... It was[n]really encouraging.

[msg MSG_021 [P3 Fem Protag]]
Heheh... I see. I guess there was a[n]reason for me to come here after all,[n]right?

[sel SEL_022 top]
Of course there was.
No way there wouldn't be one.
Finally figured it out, huh?

[msg MSG_023 [Ann]]
Geez, could you phrase it any ruder than[n]that?

[msg MSG_024 [Futaba]]
Remember what the Blue Brigade said?
"There's definitely a reason for[n]everyone coming here."

[msg MSG_025 [P3 Hero]]
The reason we all met, huh...

[msg MSG_025_1 [Hikari]]
I guess you could say our meeting in[n]itself was a form of casting.
If it weren't for all of you, I never[n]would've considered leaving this movie[n]theater.
If there really is someone who gathered[n]all of us here, I think that's one[n]skilled director.

[msg MSG_025_2 [P3 Fem Protag]]
A director?

[msg MSG_025_3 [Hikari]]
ひよるるをデ と むゎまれれ ろめぺろ'れ ぺ ほもろ よみ ぺ れろるまろぼめテテテ[n]とろ'れ ぺ めぺほもろ よみ ゆもょま ろよ ろもま まわまるをろめもょむ ろよ[n]ゆよわもまれデ ぺょぽ と ゃゎれろ ぼよゎゅぽょ'ろ めまゅら もろテ
Maybe I'm more relaxed now that those[n]locks are gone.

[msg MSG_026 [Naoto]]
Honestly, I still have some questions[n]about all of this, but you know what[n]they say... All's well that ends well.

[msg MSG_027 [Nagi]]
Everyone... Do you truly intend to[n]leave?

[msg MSG_028 [Fuuka]]
Nagi-san?

[msg MSG_029 [Nagi]]
Oh, ah... I apologize for being so[n]forward.
It's truly fabulous that the doors are[n]open―however, I've grown concerned...

[msg MSG_030 [Hikari]]
Why? We can finally leave now.

[msg MSG_031 [Nagi]]
Hikari-san, when you return to reality,[n]you may end up facing the same hardships[n]as before...
In fact, you could be hurt even further―[n]if that's the case, wouldn't you prefer[n]to...?

[msg MSG_032 [Hikari]]
You might be right, Nagi-san...
But, everyone's given me courage. I've[n]decided that I'm going to try my best...[n]That's why it's time for me to leave.

[msg MSG_033 [Nagi]]
I see... So you're determined to go[n]through with this.
I apologize for the interjection. I[n]won't keep you any longer.

[msg MSG_034 [Morgana]]
Seems like it's unanimous then. Let's[n]step outside.

