[msg MSG_000 [Yusuke]]
Do you mind if I interject for a moment?[n]There's something I've been wondering.
The reason we were all trapped in a[n]movie theater in the first place―that[n]was tied to Hikari as well, correct?
Well, why would such a thing happen?

[msg MSG_001 [Morgana]]
Hmm, that's the part we just don't know[n]yet...

[msg MSG_002 [Ryuji]]
Anyways, we got the last key―let's head[n]back.

[msg MSG_003 [Hikari]]
Yeah, Nagi-san is waiting for us...[n]There's a lot I need to tell her, too.

[msg MSG_004 [Makoto]]
Well then, let's return to the theater.

