[msg MSG_000 [Haru]]
This is just... It's so horrible.

[msg MSG_001 [Koromaru]]
*growl* Bark, bark!

[msg MSG_002 [Aigis]]
Koromaru-san seems to dislike it as[n]well.
He said, "Hikari-san is Hikari-san. Why[n]is that fact being rejected?"

[msg MSG_003 [Mitsuru]]
Based on Hikari's appearance, this[n]incident appears to have occurred quite[n]recently.
To think she'd been on the receiving end[n]of such awful pressure from her[n]relatives...

[msg MSG_004 [High school Hikari]]
I'm different from all the other[n]girls... I'm strange... A no-good[n]abnormality...

[msg MSG_005 [Teddie]]
That doesn't matter! I'm just a little[n]bit different from what's normal...
But everyone's still accepted me as[n]their friend!

[msg MSG_006 [High school Hikari]]
Still, I'm... I'm just a living error,[n]causing trouble for everyone else...

[msg MSG_007 [Hikari]]
Th-That's not true! Individuality's not[n]some kind of error!

[msg MSG_008 [High school Hikari]]
Everyone says I'm weird... They say that[n]calling it "individuality" is just an[n]excuse...

[msg MSG_009 [Hikari]]
Huh?

[msg MSG_010 [High school Hikari]]
My lifelong dream will take me nowhere.[n]I can't even fix my own errors.
Deep down, though... I... I don't want[n]to suppress my real self!

[msg MSG_011 [Hikari]]
That's right... I was always under such[n]stress...
What does it mean to be normal? What am[n]I?
I started losing sight of what my[n]existence really ought to be...

[msg MSG_012 [P3 Fem Protag]]
You can't lose yourself like that!
The anxiety of feeling like the only one[n]who's different... I truly understand[n]that now.

[msg MSG_013 [P3 Fem Protag]]
To be honest... I've been scared the[n]whole time I've been here.
I'm the irregularity here―I'm the only[n]one different from everybody else!

[msg MSG_013_5 [P3 Fem Protag]]
The more I thought about why that is,[n]the more I started feeling like[n]everything about me is phony...

[msg MSG_014 [Shinjiro]]
...

[msg MSG_015 [P3 Fem Protag]]
But then, everyone I met accepted me,[n]just the way I am.

[msg MSG_016 [High school Hikari]]
......

[msg MSG_017 [P3 Fem Protag]]
Hikari-chan, that doesn't just apply to[n]me. The same goes for you too, right?

[sel SEL_018 top]
Just be yourself, Hikari.
We all like you as you are.

[msg MSG_019 [P3 Fem Protag]]
Mmhm. You are just you, Hikari-chan.[n]You're our precious friend.
That's why we came all this way to find[n]you.

[msg MSG_020 [High school Hikari]]
......!

[msg MSG_021 [Futaba]]
She's right, Hikari! Let's get outta[n]here and all go home together!

[msg MSG_022 [Hikari]]
That's right... There was something I[n]wanted to do!

[msg MSG_023 [Hikari's uncle]]
That's just you being selfish, Hikari.[n]Stop being such a bother to everyone!

[msg MSG_024 [Hikari's aunt]]
That's right―you're not normal. Keep[n]going with that attitude and you'll only[n]wind up miserable!

[msg MSG_025 [High school Hikari]]
My dream... The people I want to be[n]with...
I... I want to stay the person that I[n]know I am!
I don't want to discard my whole[n]identity just because of some ideas[n]you're trying to force on me!

[msg MSG_026 [Hikari's aunt]]
Are you still defying us!? Fine... We'll[n]set you straight.
You are an erroooooooooooor!

[msg MSG_027 [Hikari]]
N-Nooo!

[msg MSG_028 [Chie]]
No way we're letting this happen!

[msg MSG_029 [P3 Hero]]
Yeah, we've got to stop them―let's go!

