[msg MSG_000 [P4 Protag]]
You're... Doe!?

[msg MSG_001 [Ryuji]]
So you WERE the one behind all this! The[n]hell's your problem!?

[msg MSG_002 [Doe]]
......
......

[msg MSG_003 [Ryuji]]
Hey! I'm talkin' to you, spongebag!

[msg MSG_004 [Naoto]]
I'm not sure what it is, but something[n]seems different now...

[msg MSG_005 [Doe]]
Hi...kari...

[msg MSG_006 [Hikari]]
......!

[msg MSG_007 [Haru]]
H-He actually spoke!

[msg MSG_008 [Hikari]]
Ah―He said... my name...

[msg MSG_009 [Doe]]
......

[msg MSG_010 [Chie]]
Hey, wait up! Are you just gonna run off[n]like that!?

[msg MSG_011 [Futaba]]
Don't worry―I'm tracking his reading.[n]Looks like Doe's heading deeper into the[n]musical.

[msg MSG_012 [Mitsuru]]
...It almost seemed as if he was luring[n]us further inward.

[msg MSG_013 [Akihiko]]
You're right. It's quite possible that[n]he's leading us into a trap, but we[n]can't exactly turn tail, either.

[msg MSG_014 [Yusuke]]
What should we do? Do we pursue him,[n]Joker?

[sel SEL_015 top]
Of course.
We can't just let it end like this.

[msg MSG_016 [Yosuke]]
Yeah, let's take care of this the right[n]way.
We're countin' on you to guide us to[n]Doe, Navi-Gals!

[msg MSG_017 [Futaba]]
...Navi-Gals?

[msg MSG_018 [Rise]]
Yosuke-senpai sometimes talks like a[n]fuddy-duddy... Only sometimes, though.

[msg MSG_019 [Yosuke]]
Agh―That attempt to cover was even more[n]painful than the insult. Just cut it out[n]entirely!

[msg MSG_020 [Fuuka]]
Um... In any case, we'll do our best to[n]guide you. I'll keep a close eye on[n]Doe's reading!

