[msg MSG_000 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 12 3 1][f 3 1 1 0 0 34039][f 6 1 2 0 0 10]Escapamos del carn胤voro, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 0]Ah, finalmente te alcanzamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Oh, lo siento... Me olvid姻 completamente de ustedes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 25001][f 6 1 2 0 0 4]Realmente perdiste la compostura all胤, y fue muy repentino... 夷No fue un poco extremo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡De ninguna manera! ¡Mira eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 0]Hay muchos carn胤voros por aquí, por eso todos est茨n tan nerviosos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 22081][f 6 1 2 0 0 4]Aun as胤, 夷no es malo para tu salud entrar en p茨nico y huir así todo el tiempo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Han probado una t茨ctica diferente? Ya sabes, como pelear o algo as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No seas rid胤cula! ¡No hay manera de que podamos ganar, incluso si vamos todos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 6 0 0][f 3 1 1 0 0 0]Los que lo han intentado han sido comidos. A saber lo que nos pasar胤a a nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 6][f 3 1 1 0 0 0]Hrgh... Ahora eso es un pensamiento sombr胤o...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Me pregunto cu茨n fuertes son esos carn胤voros. 夷Sería imposible para nosotros, incluso con nuestras Personas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 3 0 0][f 4 6 20 1 0 0]夷Deber胤amos intentarlo?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No tentemos al destino.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Oh, ser胤a pan comido.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 8 6 0 1][f 3 1 1 0 0 8010][f 6 1 2 0 0 9]Sospecho que ser胤a demasiado peligroso... Como dice el dicho, los osos heridos son los m茨s peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 8 6 0 1][f 3 1 1 0 0 8071][f 6 1 2 0 0 9]Esa ser胤a la acci吋n m茨s sabia. Como dice el refrán, los osos heridos son los más peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 24 2 0 1][f 3 1 1 0 0 24047][f 6 1 2 0 0 4]Pareces muy confiado. 夷Vamos a buscar uno ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No creo que debamos tentar al destino, como dice el refr茨n, los osos heridos son los más peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷"Osos heridos"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Cuando un oso herido es acorralado, su desesperaci吋n lo hace especialmente aterrador. Lo mismo se dice de los jabal胤es.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9016][f 6 1 2 0 0 4]Entonces, 夷significa que ser胤a invencible si me meto en un aprieto?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Hraaaaaaaah! ¡Estoy listo! ¡Yosukeeeee! ¡Solo esp姻rame![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Idiota! ¡C茨llate! ¡Nos van a descubrir los carn胤voros![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Permanecer aqu胤 tambi姻n demasiado peligroso, deberíamos atravesar la zona r茨pido. Vamos.[n][f 1 3 65535][f 1 1][e]

