[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 1][f 3 1 1 0 0 1]Genial, otra pel胤cula que deja un mal[n]sabor de boca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 3]夷Verdad? Es igual que la de Kamoshidaman,[n]como si me dejara un vac胤o por[n]dentro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 4][f 3 1 1 0 0 3]Parece hablar sobre el poder de la[n]mayor胤a.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]La pel胤cula deja muy claro que la opini吋n[n]de la mayor胤a es la correcta, y[n]no existe otra opci吋n v茨lida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 5][f 6 1 2 0 0 3]Lo que la mayor胤a de la gente est茨 de[n]acuerdo, 夷eh? Esa no es nuestra clase[n]de cosas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]Quiero decir, usamos a la sociedad para[n]escoger nuestros objetivos bas茨ndonos[n]en su reputaci吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 71 6 0 1][f 3 1 1 0 0 7]Ryuji...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 8]Pero ahora, sabemos que es lo mejor.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9]Aplicamos nuestra justicia sin estar[n]influenciados por los caprichos de la[n]sociedad, as胤 los hacen los ladrones[n]fantasma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_05 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 68 0 0 3][f 3 1 1 0 0 10][f 6 1 2 0 0 4]Nuestros m姻todos a un lado... Hikari,[n]夷es esta pel胤cula la que necesitas ver?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 11]...No lo s姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 1 0 1][f 4 6 72 12 0 3][f 3 1 1 0 0 12][f 6 1 2 0 0 4]夷Y t雨, Nagi? 夷Conoces esta pel胤cula?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 6 0 0][f 3 1 1 0 0 13]No, en absoluto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 19 0 2 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 14]Mmm... Mmm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 1 2 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 16]Oh, bueno, no es tan importante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 8 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 17]Pero, las pel胤culas de dinosaurios no suelen ser m茨s tipo: 斡BLAAAAM! O algo así...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 14 1 1][f 3 1 1 0 0 18][f 6 1 2 0 0 6]斡S胤, s胤![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 8 1 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]Y todos son como, GRAAAAAARH! 斡y KA-BOOOM![n]夷Verdad?[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷GRAAAAAARH?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷KA-BOOOM?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]斡Tambi姻n ROOOOOOAAAAR![f 2 7 1 64 0 32][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 8 1 0][f 3 1 1 0 0 20][f 6 1 2 0 0 6]斡S胤! Y entonces todo es como,[n]斡BOOMBOOMBOOMBOOMBOOMBOOM![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 1][f 3 1 1 0 0 21]No dire nada, pero entiendo lo que[n]quieren decir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]Un dinosaurio que quiere salvar a su[n]manada, pero no puede hacerlo por la[n]opini吋n mayoritaria...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 1][f 3 1 1 0 0 23]Se supone que es una pel胤cula de[n]dinosaurios, pero es como ver los dolorosos[n]problemas de la vida humana.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 0 0 0][f 3 1 1 0 0 24]夷C吋mo alguien malo que se arruina la[n]paz y todo el mundo se preocupa[n]constantemente de c吋mo se sienten y piensan[n]los dem茨s?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 25][f 6 1 2 0 0 4]Lo mismo podr胤a decirse de la pel胤cula[n]de Kamoshidaman, 夷por qu姻 son las[n]historias as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 1][f 3 1 1 0 0 26]Esto no solo se aplica a las pel胤culas,[n]sino que los creadores incluyen un[n]mensaje en su pel胤cula.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27]En este caso, supongo que los cineastas[n]est茨n diciendo, "Deja de ser quien[n]eres y simplemente haz lo que hace[n]todo el mundo..."[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 28][f 6 1 2 0 0 6]夷Qu姻? 夷Decides qu姻 hacer por una mierda[n]como esa? 斡Eso no es diferente a[n]estar muerto![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 29]Estoy de acuerdo. No importa lo que me[n]digan los que me rodean, no tengo[n]ninguna intenci吋n de renunciar al arte.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 6 0 0][f 3 1 1 0 0 30]Por otro lado... puedo entender en cierta[n]medida la sensaci吋n de tener que[n]seguir la corriente de los dem茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 31]Si no los hubiera conocido, simplemente[n]habr胤a seguido lo que mi empresa y[n]los adultos exig胤an de m胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 0 1][f 3 1 1 0 0 32][f 6 1 2 0 0 4]夷Esa pel胤cula... fue tan extra隠a?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 33][f 6 1 2 0 0 4]夷Eh? 夷No te pareci吋 que hab胤a algo raro[n]en ella?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 34]Solo tengo curiosidad de por qu姻 est茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 35][f 6 1 2 0 0 4]夷Por qu姻 sientes tanta ira... o tristeza[n]por eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 36]En el fondo, ese dinosaurio quiere salvar[n]a su manada, pero nadie est茨[n]dispuesto a ayudar, as胤 que no puede...[n]Eso es realmente desalentador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 37]Pero sus compa隠eros se opusieron a la[n]idea. Si intentaran rescatarlos, todos[n]los dem茨s estar胤an en peligro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 38]Aun as胤, es posible rescatarlos...[n]Entonces todos estar胤an a salvo, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39][f 6 1 2 0 0 4]Creo que es una tonter胤a rendirse sin[n]intentar algo primero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 40]Eso es...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 84 12 0 0][f 3 1 1 0 0 41]Hikari, si crees que la pel胤cula debe[n]permanecer como es, entonces estoy[n]bien con ella tambi姻n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 42]Sin embargo, solo apoyo la decisi吋n si[n]realmente es lo que quieres. No quiero[n]que reprimas a la verdadera t雨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 43]夷Mi... verdadero yo? Esa pel胤cula...[n]Yo...[n][f 1 3 65535][f 1 1][e]

[sel SEL_030 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Est茨s bien con el resultado?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷No quieres un final diferente?[f 2 7 1 64 0 32][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 44]Al principio pens姻 que estaba bien...[n]Pero ahora...[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 45]夷Un final diferente? Ni siquiera hab胤a[n]pensado en eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 4]Bueno, entonces, por ejemplo... Si fueras[n]ese dinosaurio, 夷qu姻 querr胤as[n]hacer, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 47][f 6 1 2 0 0 4]夷Yo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 48]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 49]Pero... los otros dinosaurios...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 50][f 6 1 2 0 0 6]Si mientes sobre tus propios sentimientos...[n]斡Solo har茨 las cosas m茨s[n]dolorosas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 51][f 6 1 2 0 0 10]Ah... quiero decir... lo siento...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 52][f 6 1 2 0 0 4]夷Mentir...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 53][f 6 1 2 0 0 4]Viste c吋mo termin吋 Kamoshidaman y te[n]alegraste de lo que cambiamos, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 4 1 0][f 3 1 1 0 0 54][f 6 1 2 0 0 10]As胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 55]Si cambia de nuevo... Si hay un final[n]diferente a este...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 2 0][f 3 1 1 0 0 56]Creo que... Quiero ver...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 57][f 6 1 2 0 0 0]斡夷En serio?![n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 65 0 0 6][f 3 1 1 0 0 58]斡Muy bien! 斡Entonces d姻janos![n][f 1 3 65535][f 1 1][e]

[msg MSG_040_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 3 6][f 3 1 1 0 0 59][f 6 1 2 0 0 6][f 6 1 30 0 0 0]斡Cambiemos esta pel胤cula, igual que la[n]primera![n][f 1 3 65535][f 1 1][e]

[sel SEL_041 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]S胤.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Deber胤amos priorizar el escape.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]夷Qu姻 opini吋n los dem茨s?[f 2 7 1 64 0 32][e]

[msg MSG_042 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 60]Estoy de acuerdo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 61]Creo que cambiar estas pel胤culas nos[n]ayudara a escapar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 62]No s姻, creo que cambiar las pel胤culas[n]ser茨 la forma m茨s r茨pida de escapar[n]de aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 63]Bueno, yo estoy de acuerdo con eso.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 64]Creo que cambiar estas pel胤culas nos[n]ayudara a escapar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 0 0 1][f 3 1 1 0 0 65][f 6 1 2 0 0 4]Cuando la cambiamos, una llave sali吋 de[n]Doe... 夷Creen que ocurra lo mismo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 66]Ese patr吋n no ha sido confirmado todav胤a,[n]pero creo que es probable.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 67]A雨n m茨s, considerando que Doe es el que[n]reproduce estas extra隠as pel胤culas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 70 2 0 1][f 3 1 1 0 0 68][f 6 1 2 0 0 6]斡Entonces est茨 decidido! 斡Vamos a explorar[n]esa pel胤cula, [f 6 1 30 0 0 0]![n][f 1 3 65535][f 1 1][e]

