[msg MSG_000 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 1 1][f 3 1 1 0 0 1]Ngh... Nnh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Herb胤voro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 47 12 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 0]夷No puede ser... perdi吋 ante los humanos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Herb胤voro Enorme]]
[f 0 5 65278][f 2 1][f 4 6 48 0 0 6][f 3 1 1 0 0 3]Pero es mucho m茨s grande que ellos... Incre胤ble...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 4]Esto demuestra que no puedes definir a alguien solo por su apariencia, ni siquiera por sentido com雨n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 6 6 100 3][f 3 1 1 0 0 5][f 6 1 2 0 0 4][f 3 1 6 0 0 500]M茨s importante, 夷est茨s bien? 夷Est茨s herido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 1][f 3 1 1 0 0 6]Oh... No, estoy bien.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 12 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 4]...Fuiste suave conmigo, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 8]Preferimos llamarlo "contenernos". No beneficiar胤a a nadie hacerte da隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 10 1 0][f 3 1 1 0 0 9]Heheh, realmente no soy rival para ustedes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 10][f 6 1 2 0 0 4]Hice cosas terribles, pero aun as胤... 夷Por qu姻 a雨n quieren ayudarnos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]No hay raz吋n una en particular.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Parec胤a que lo necesitabas.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No s姻...[f 2 7 1 20 4 32][e]

[msg MSG_009 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 10 1 0][f 3 1 1 0 0 11]Heheh, y aun as胤 vinieron, y nos salvaron. En comparaci吋n ustedes, solo somos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 10 1 0][f 3 1 1 0 0 12]夷As胤 es como me ve胤a? Jaja... nunca me habr胤a dado cuenta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 4][f 3 1 1 0 0 13][f 6 1 2 0 0 6]斡Oh, genial! 斡Me ha dejado impresionado su actitud despreocupada![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 14]La forma en que se estaban forzando a creer en la regla de la mayor胤a... Todos parec胤an estar sufriendo, no sobreviviendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 15][f 6 1 2 0 0 4]夷No est茨bamos sobreviviendo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 16]Oh, parece que son los 雨nicos que no se hab胤an dado cuenta de esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 4]Han estado trabajando juntos todo este tiempo, 夷verdad? Todos buscando el mismo objetivo, 夷no es as胤?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18]Por supuesto, a veces van a chocar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]Pero, 夷ignorar por completo a algunas personas solo porque est茨n en la minor胤a? 夷No es triste?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 34 0 1 0][f 3 1 1 0 0 20]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 6][f 3 1 1 0 0 21][f 6 1 2 0 0 3]No entiendo nada...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 0][f 3 1 1 0 0 22][f 6 1 2 0 0 4]夷Qu姻 sentido tiene preocuparse de si eres igual o no todo el tiempo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23]Por supuesto que diferentes personas tienen opiniones diferentes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 24]As胤 es. Cuando se trata de amigos, las diferencias no importan; simplemente haces lo que puedes para ayudarlos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 25][f 6 1 2 0 0 7]夷Verdad, compa隠ero?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 26]S胤, compa隠ero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 34 0 1 1][f 3 1 1 0 0 27]No quer胤a ser abandonado, as胤 que simplemente segu胤 a los dem茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28]斡Pero finalmente he recuperado el juicio![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 12 1 1][f 3 1 1 0 0 29][f 6 1 2 0 0 6]斡No quiero pertenecer a un lugar donde tenga que mentir para encajar![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 30]S胤, simplemente sigue ese pensamiento.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 31]Y aseg雨rate de seguirlo con amigos que dependan de ti y en quienes tambi姻n puedas confiar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 32]Incluso yo me siento d姻bil si estoy solo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 33]Pero mis amigos me dan fuerza. Espero hacer lo mismo por ellos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Herb胤voro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 42 1 0 6][f 6 1 25 0 0 0][f 4 6 47 1 0 0][f 3 1 1 0 0 34]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 35]Entonces, chicos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Herb胤voro Malhumorado]]
[f 0 5 65278][f 2 1][f 4 6 42 0 0 0][f 3 1 1 0 0 36]Um... Nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 14 1 0][f 3 1 1 0 0 37][f 6 1 2 0 0 6]斡Tengo una idea![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 38]斡Dejemos de decidir las cosas por mayor胤a y discutamos las cosas a partir de ahora![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 12 0 0][f 3 1 1 0 0 39][f 6 1 2 0 0 4]斡No m茨s preocupaciones por lo que piensen los dem茨s! Quiero quedarme con ustedes, as胤 que... 夷Por qu姻 no hablamos las cosas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Herb胤voro T胤mido]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 90 0 1 0][f 3 1 1 0 0 40]Me di cuenta de que solo pensaba en m胤 mismo, porque tambi姻n ten胤a miedo de ser abandonado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 41]No pod胤a hablar, y siempre me odiaba por ser tan d姻bil.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 90 12 0 0][f 3 1 1 0 0 42]Lo siento por haberte abandonado... Aunque t雨 me hayas rescatado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Herb胤voro Malhumorado]]
[f 0 5 65278][f 2 1][f 4 6 42 0 0 0][f 3 1 1 0 0 43]Yo tambi姻n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 42 12 0 0][f 3 1 1 0 0 44]No quer胤a que me echaran, as胤 que todo lo que pensaba era quedarme con la mayor胤a.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 45]Creo que fui demasiado lejos con ustedes, humanos... Lo siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Herb胤voro Enorme]]
[f 0 5 65278][f 2 1][f 4 6 48 0 0 4][f 3 1 1 0 0 46]Entonces, todos... Todos sent胤amos lo mismo al respecto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Herb胤voro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 47 12 0 0][f 3 1 1 0 0 47]Ni siquiera intentamos hablar las cosas y simplemente nos asustamos tomando decisiones equivocadas... Fuimos realmente est雨pidos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 24 2 0 0][f 3 1 1 0 0 48]Ahora que ya no se esconden detr茨s de n雨meros, finalmente podemos escuchar los verdaderos sentimientos de todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 49]Creo que la regla de la mayor胤a puede ser una forma 雨til de tomar decisiones...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 14 1 0][f 3 1 1 0 0 50][f 6 1 2 0 0 4]Pero no hagamos que adherirse a ella sea nuestra principal prioridad. 夷Qu姻 les parece si buscamos otras formas de orientarnos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Herb胤voro T胤mido]]
[f 0 5 65278][f 2 1][f 4 6 90 12 0 0][f 3 1 1 0 0 51][f 6 1 2 0 0 6]...斡S胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 2 0 3][f 3 1 1 0 0 52][f 6 1 2 0 0 7]Heheh, 斡y eso es todo![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 53][f 6 1 2 0 0 4]夷Supongo que el caso est茨 cerrado ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 0 1 1][f 3 1 1 0 0 54][f 6 1 2 0 0 4]...夷Eh? Oigan, 夷escuchan algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 55]S胤... suena como algo que se acerca desde lejos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 6 10 100 1][f 3 1 1 0 0 56][f 6 1 2 0 0 6]斡Chicos, malas noticias! 斡Una presencia poderosa se acerca a gran velocidad![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57][f 6 1 2 0 0 1]Creo que es un carn胤voro... 斡Tengan cuidado![n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 58][f 6 1 2 0 0 4]Parece que finalmente nos encontr吋. 夷Deber胤amos plantarle cara?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 100 4][f 3 1 6 0 0 500][f 3 1 1 0 0 59][f 6 1 2 0 0 6]El verdadero problema es que los herbivores...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 60][f 6 1 2 0 0 10]Incluso si intent茨ramos sacarlos, 斡estar胤an atrapados en un callej吋n sin salida![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Herb胤voro T胤mido]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 90 0 0 3][f 3 1 1 0 0 61][f 6 1 2 0 0 0]夷斡Deber胤amos escondernos!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Herb胤voro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 47 12 0 1][f 3 1 1 0 0 62][f 6 1 2 0 0 6]斡T-Tenemos que huir![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Herb胤voro Enorme]]
[f 0 5 65278][f 2 1][f 4 6 48 0 1 4][f 3 1 1 0 0 63][f 6 1 2 0 0 0]Pero, 夷斡d吋nde!? 斡No tenemos una salida![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 4 1 0][f 3 1 1 0 0 64][f 6 1 2 0 0 6]斡Eh! 斡C茨lmense![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 26 10 100 1][f 3 1 1 0 0 65][f 6 1 2 0 0 10]斡No sirve de nada! 斡Viene hacia nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Gaudy Carnivore]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 92 0 1 1][f 3 1 1 0 0 66][f 6 1 1 0 0 1][f 6 1 2 0 0 6]斡GREEEEEEEEE![n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 12 1 6][f 3 1 1 0 0 67][f 6 1 2 0 0 0]Tch, est茨 aqu胤. 斡Joker! 夷斡Qu姻 hacemos!?[n][f 1 3 65535][f 1 1][e]

[sel SEL_048 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Tenemos que actuar... r茨pido.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Veamos c吋mo se desarrolla esto.[f 2 7 1 20 0 32][e]

[msg MSG_049 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 68]Muy bien, tomemos la l胤nea delantera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 69]No estoy seguro de eso... Pero no tenemos tiempo que perder.[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Gaudy Carnivore]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 70][f 6 1 3 0 0 1][f 6 1 2 0 0 6]斡GYAAAAAH![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 34 16 1 3][f 3 1 1 0 0 71][f 6 1 2 0 0 4]斡Espera! 夷Crees que podr胤as dejar que me encargue de esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 72][f 6 1 2 0 0 0]夷斡Eh!? 夷斡Sabes lo rid胤culo que suena eso!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 14 1 0][f 3 1 1 0 0 73]Heheh, todo lo que has visto hasta ahora es lo pat姻tico que he sido...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 74][f 6 1 2 0 0 6]斡D姻jame demostrar que tambi姻n tengo lo necesario![n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 4][f 3 1 1 0 0 75][f 6 1 2 0 0 0]E-Eh, 夷qu姻 vas a hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 1 0][f 3 1 1 0 0 76]Y-Yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 16 1 0][f 3 1 1 0 0 77][f 6 1 2 0 0 6]He tomado una decisi吋n: 斡Voy a ser honesto con mis sentimientos![n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [Herb胤voro Malhumorado]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 42 2 1 1][f 3 1 1 0 0 78][f 6 1 2 0 0 6]夷Q-Qu姻 est茨s pensando? 斡Si no nos vamos de aqu胤 r茨pido, todos seremos asesinados![n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 12 1 0][f 3 1 1 0 0 79][f 6 1 2 0 0 6]斡Yo tambi姻n soy un dinosaurio![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 80][f 6 1 2 0 0 1]斡Si lo intento con todas mis fuerzas, deber胤a poder ahuyentar a un solo carn胤voro![n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Herb胤voro T胤mido]]
[f 0 5 65278][f 2 1][f 4 6 90 12 0 4][f 3 1 1 0 0 81][f 6 1 2 0 0 10]斡Pero eso es imposible![n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 12 1 0][f 3 1 1 0 0 82][f 6 1 2 0 0 6]斡Despu姻s de todo, finalmente estamos siendo honestos entre nosotros![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 83][f 6 1 2 0 0 1]No hay manera de que abandone a mis compa隠eros ahora, 斡nunca m茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Herb胤voro Enorme]]
[f 0 5 65278][f 2 1][f 4 6 48 0 1 1][f 3 1 1 0 0 84][f 6 1 2 0 0 0]Espera, est茨s bromeando, 夷斡verdad!?[n][f 1 3 65535][f 1 1][e]

