[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 7][f 4 6 6 2 0 1][f 3 1 1 0 0 1]斡Genial! 斡Realmente era una llave para esta[n]puerta![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 1 0][f 3 1 1 0 0 2]斡Claro que s胤! Un paso m茨s cerca de salir de[n]aqu胤... 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 9][f 4 6 4 0 0 1][f 3 1 1 0 0 3]Yo... creo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 71 12 0 3][f 3 1 1 0 0 4]Hay una cosa que me da curiosidad: 夷No parec胤a[n]Doe mucho m茨s calmado que antes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]La primera vez que produjo una llave, parec胤a[n]tener mucho m茨s dolor que esta vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 1][f 3 1 1 0 0 6]Hm, ahora que lo mencionas... La diferencia[n]parece bastante leve.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 7]Veo lo que quieres decir... Quiz茨s nuestras[n]ediciones de las pel胤culas lo est茨n[n]afectando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 19 12 2 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 8]夷Te sientes mejor ahora, Hikari? Estabas[n]temblando mucho antes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 9]M-Mmhm... Lo siento, estoy bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 10]Hikari parece estar extremadamente nervioso[n]en la presencia de Doe.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 10][f 4 6 4 12 0 4][f 3 1 1 0 0 11]夷Hola? 斡Tiene sentido para m胤![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12]No ser胤a tan malo si eso fuera s吋lo un tipo[n]de traje como con Teddie, pero es[n]espeluznante, y tampoco nos hablar茨...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yukiko]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 5][f 4 6 5 0 0 0][f 3 1 1 0 0 13]Me pregunto... Si le arrancamos la cabeza,[n]夷c吋mo funciona Teddie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 11 0 4][f 3 1 1 0 0 14]Sent胤 que un tir吋n me rasg吋 la columna...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 15]*giggle*[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 7 13 0 0][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 16]Me alegra ver que est茨s empezando a entrar[n]en mejores esp胤ritus.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 6][f 3 1 1 0 0 17]斡Ayuda, no hay necesidad de temer! 斡Juramos[n]que te sacaremos de aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 18]S胤, lo que dijo, d姻janos esto. Averigua lo[n]que quieres hacer cuando vuelvas a casa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 81 0 0 0][f 3 1 1 0 0 19]夷Eh? 夷Qu姻 quiero hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 70 12 0 0][f 3 1 1 0 0 20]Mi recomendaci吋n es el juego de gr雨as[n]Featherman, 斡s吋lo se encuentra en Akiba![n][f 1 3 65535][f 1 1][e]

[msg MSG_017_5 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 18 1 0][f 3 1 1 0 0 21][f 6 1 2 0 0 6]La clave de la victoria est茨 con la fuerza[n]del brazo, pero tambi姻n tienes que comprobar[n]el ancho de las garras cuando est茨[n]abierta![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 4][f 3 1 1 0 0 22]Realmente te encanta ese juego, 夷verdad,[n]Futaba...? Bueno, si te saca de la casa, es[n]lo mejor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 12 0 0][f 3 1 1 0 0 23]Ah胤 est茨, tenemos una nueva pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Intercomunicaci吋n De Teatro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24][f 6 1 9 0 0 1]Tenemos un anuncio para nuestros clientes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 25][f 6 1 9 0 0 1]Una nueva pel胤cula comenzar茨 a aparecer en[n]el Cine 3 moment茨neamente. Repito...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 3][f 4 6 65 6 0 0][f 3 1 1 0 0 26]Genial, una nueva pel胤cula. Apuesto a que es[n]igual de mierda que los dos 雨ltimos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 27]Well, there's nothing else we can do to[n]get out of this place... Let's go,[n][f 6 1 30 0 0 0].[n][f 1 3 65535][f 1 1][e]

