[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28015]Esta isla parece ser bastante grande.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 0]Cierto... Puede haber sido necesario,[n]considerando cu茨n grandes son los dinosaurios[n]a menudo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 1][f 3 1 1 0 0 26518][f 6 1 2 0 0 4][f 3 1 6 0 0 500]... 夷Hm?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]夷Qu姻 pasa, Oracle? 夷Encontraste algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 0]Bueno... Estoy recibiendo lecturas de algo[n]aqu胤 que es mucho m茨s fuerte que las de[n]antes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Son FOEs?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 6][f 3 1 1 0 0 27055][f 6 1 2 0 0 0]Oh no, 夷podr胤an ser realmente los T-Rexes[n]que est茨bamos discutiendo hace un momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Mierda... S吋lo escuchar que podr胤a ser un[n]T-Rex es una cosa, pero ser FOEs es a雨n[n]m茨s loco.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es una locura.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Estaremos bien.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Vamos a correr.[f 2 7 1 20 8 32][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 21014]夷Verdad? Esos tipos son monstruos de pel胤culas[n]cl茨sicos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Como, un feroz T-Rex chompin' hacia abajo[n]cabeza sobre quien se escapa de ella ...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Sheesh, 夷est茨s muy asustado?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]Oh, pero tenemos un gato de aspecto sabroso[n]aqu胤, quiz茨s sea el primer curso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23036][f 6 1 2 0 0 6]N-Noooo - 斡Espera, quiero decir, no soy[n]sabroso! 斡O un gato![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 21084][f 6 1 2 0 0 4]Dices eso, pero esos tipos son monstruos[n]cl茨sicos de la pel胤cula.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Como, un feroz T-Rex chompin' hacia abajo[n]cabeza sobre quien se escapa de ella ...  [n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 es esto? 夷Te est茨s volviendo loco,[n]Skull?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]Oh, pero tenemos un gato de aspecto sabroso[n]aqu胤, quiz茨s sea el primer curso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23036][f 6 1 2 0 0 6]N-Noooo - 斡Espera, quiero decir, no soy[n]sabroso! 斡O un gato![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 21 10 0 0][f 3 1 1 0 0 21054][f 6 1 2 0 0 6]斡Espera un segundo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Si empiezas a correr de un T-Rex de inmediato,[n]斡s吋lo vas a terminar en m茨s peligro![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 3][f 3 1 1 0 0 0]Ah, el cl茨sico clich pel胤cula... El primero[n]en huir es el primero en ser comido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 19 2 3 1][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 0]Es verdad que los dinosaurios carn胤voros[n]son terribles... pero estoy seguro de que[n]estaremos bien si todos nos quedamos[n]juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 0]Mmhm! Si lo peor es peor, lo cortar姻 en la[n]mitad con mi hacha![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 6][f 3 1 1 0 0 22030][f 6 1 2 0 0 7]Ahaha, 斡entonces lo asar姻 vivo con mis llamas m茨s intensas![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 4 1 1][f 3 1 1 0 0 0]Me pregunto si sus ojos son un punto d姻bil.[n]Podr胤a intentar golpear all胤 para[n]probarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 21 1 0 1][f 4 6 23 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Siento que las chicas son m茨s valientes que[n]nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21123][f 6 1 2 0 0 6]No podemos dejar que nos muestren aqu胤...[n]Vamos a subir nuestro juego tambi姻n, Joker![n][f 1 3 65535][f 1 1][e]

