[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Hemos tra胤do la carne congelada y el[n]equipo de cocina mientras busc茨bamos[n]un buen lugar para cocinar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 24076]Mmm, si vamos a cocinar esta carne, 夷por[n]qu姻 no hacerlo aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Es un 茨rea abierta, hay una fuente de[n]agua cercana... Dir胤a que es un lugar[n]tan seguro para cocinar como podr胤amos[n]esperar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Quiz茨s solo encontramos una olla para[n]cocinar, pero deber胤amos estar bien[n]siempre y cuando tengamos una fuente[n]de calor para ella...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]La 雨nica cosa es que no tenemos una[n]receta para trabajar. 夷Eso ser茨 un[n]problema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 0]Naoto, siempre hay nuevos descubrimientos[n]esperando ser hechos en la cocina.[n]斡Solo necesitamos creer en nosotras[n]mismas![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 100 0][f 3 1 1 0 0 6573][f 3 1 6 0 0 500]斡Mm! Improvisar un plato sabroso con un[n]n雨mero m胤nimo de ingredientes tambi姻n[n]es una habilidad 雨til en la cocina.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Me estoy emocionando! 斡Es hora de que[n]nosotras, chicas, saquemos a relucir[n]nuestras habilidades culinarias![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Adelante![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1081]E-espera... Dado hay poca carne, 夷no deber胤amos conseguir un cocinero m茨s confiable... digo, menos experimental?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0]S-s胤, 斡lo que 姻l dijo! Nosotros nos[n]encargaremos de la parte de cocinar el[n]cebo, y t雨 puedes, eh...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡Ya s姻! 斡Puedes salir y buscar otros[n]ingredientes! 夷Por favor?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 7033][f 6 1 2 0 0 9]Te est茨s alterando un poco, Yosuke...[n]lo entiendo, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 2]斡Oye, qu姻 se supone que significa eso![n]夷Realmente te molesta que nosotras[n]cocinemos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es m茨s inquietante que molesto.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Contar姻 con ustedes, chicas.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Ser胤as la mejor para reunir ingredientes.[f 2 7 1 20 0 32][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 10 0 1][f 3 1 1 0 0 3057][f 6 1 2 0 0 0]S胤, es s雨per... Espera, 斡夷acabo de decir[n]eso en voz alta?![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 0 1 1][f 3 1 1 0 0 3054][f 6 1 2 0 0 0]夷Qu姻? Uh, quieres decir que... 夷Cuentas[n]con ellas para reunir un mont吋n de[n]ingredientes, verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 3071][f 6 1 2 0 0 10]S胤, 斡lo que 姻l dijo! Queremos que usen[n]sus... instintos femeninos, o lo que[n]sea, para encontrar los mejores[n]ingredientes para nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]No olviden que necesitamos encender fuego para cocinar la carne, Por eso nos sentimos m茨s adecuados para la parte de cocinar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 27 2 0 1][f 3 1 1 0 0 0]Buscar ingredientes suena divertido...[n]Siento que podemos encontrar nuevos[n]e interesantes aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 4][f 3 1 1 0 0 22030][f 6 1 2 0 0 4]斡Oh, tambi姻n creo eso! 夷Qu姻 te parece[n]si dejamos la cocina en sus manos y[n]nosotras, chicas, salimos a cazar un[n]poco?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 0]*risa* Haces que suene como una aventura...[n]Eso tambi姻n parece m茨s de mi[n]gusto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]En ese caso, 夷qu姻 tal si preparamos la[n]comida mientras ustedes buscan m茨s[n]ingredientes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 5 2 0 1][f 3 1 1 0 0 5077]Me parece bien. Dejaremos la cocina en[n]sus manos, al menos por esta vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]De acuerdo, 斡vamos en busca de nuevas[n]carnes![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Mm, ya tenemos la carne, as胤 que 夷por[n]qu姻 no buscamos... otros ingredientes,[n]para darle sabor, como algas marinas[n]y aletas de tibur吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]No me digas que vamos a caminar hasta[n]el oc姻ano para buscar... En cualquier[n]caso, deber胤amos irnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 18 4 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19122]斡S胤! ¡Vamos, chicas![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 3][f 4 6 9 12 0 1][f 3 1 1 0 0 9096]Uf, funcion吋... 斡Excelente trabajo,[n]Yosuke![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Si les hubi姻ramos dejado la cocina a[n]ellos, no terminar胤amos con cebo,[n]terminar胤amos con un arma qu胤mica...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 1][f 3 1 1 0 0 21011][f 6 1 2 0 0 4]Mm... 夷Las chicas de tu equipo son[n]realmente tan malas cocinando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Ni siquiera preguntes... Hay cosas que[n]es mejor no saber.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Pero no te preocupes! 斡Nuestro Maestro[n]es un cocinero maestro![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052]夷Oh? Apuesto a que las habilidades de Joker se comparan con las de[n][f 6 1 13 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Despu姻s de todo, 姻l vive en una cafeter胤a.[n]Cuando se trata de cocinar curry,[n]斡no tiene rival![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 1 2 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Eso es genial. Trabajemos juntos para asegurarnos de que todo salga bien.[n][f 1 3 65535][f 1 1][e]

[sel SEL_031 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Espero una cocina de primera.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Esto es tan pesado.[f 2 7 1 20 4 32][e]
[f 0 5 65278][f 2 1]斡Les robar姻 el apetito![f 2 7 1 20 0 32][e]

[msg MSG_032 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 1][f 3 1 1 0 0 3045][f 6 1 2 0 0 4]Oh, 夷ustedes est茨n fortaleciendo lazos[n]sobre la cocina?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0]斡Claro que s胤, parece que esto va a ser[n]todo un espect茨culo! No puedo esperar[n]para ver qu姻 preparan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 24016]Cocinar en un entorno desconocido puede[n]ser inc吋modo. La incomodidad por s胤[n]sola puede parecer imposible de[n]manejar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 0]Sin embargo, cualquier cosa puede ser[n]comestible una vez que ha sido cocinada,[n]eso es lo 雨nico de lo que estoy[n]seguro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No s姻 por qu姻, pero por la forma en la[n]que habla este chico... le creo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 9061][f 6 1 2 0 0 6]斡Ohhh, su orgullo como chef se ha[n]encendido como una hoguera![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]Parece que podemos esperar algo genial[n]de ellos. No puedo esperar a probar[n]lo que hacen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Mientras est茨s babeando, 夷puedo recordarles[n]que estamos haciendo todo esto[n]como cebo de dinosaurio, no comida[n]para Fox?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Despu姻s de limpiar la carne y terminar[n]las otras preparaciones...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 1][f 3 1 1 0 0 28031]Parece que estamos listos para cocinar[n]una vez que las chicas regresen.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 0]Joker y [f 6 1 12 0 0 0] manejaron todo con tanta[n]habilidad. Estoy impresionado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 2 0 0][f 3 1 1 0 0 0]Ya se ve delicioso y ni siquiera est茨[n]cocido a雨n... Estoy emocionado por[n]ver c吋mo resulta eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 26502][f 3 1 6 0 0 500]Chicos, parece que las chicas est茨n de[n]vuelta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 1 0 1][f 4 6 4 12 0 4][f 3 1 1 0 0 0]斡Perd吋n por la espera![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]Recogimos muchos ingredientes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Perfecto. Entonces, 夷qu姻 trajeron?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 2 0 1][f 3 1 1 0 0 8068]Esto es lo que encontr姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]...夷Es alg雨n tipo de hierba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 1][f 3 1 1 0 0 0]Parece ser alg雨n tipo de hierba.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No huele bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 23103][f 6 1 2 0 0 9]斡夷Meowww?! Eso es pasto para mi nariz...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 0]Es bastante... penetrante, pero las[n]hierbas pueden complementar bien el olor[n]de la carne, as胤 que podr胤an ser[n]雨tiles.[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4129][f 6 1 2 0 0 6]Okay, 斡siguiente! Echen un vistazo...[n]斡Taraaaan![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡Dios m胤o, es enorme! 夷Qu姻 tipo de huevo[n]es este?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0]No lo s姻. Lo vi en el suelo y lo recog胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3091][f 6 1 2 0 0 9]Ser茨 mejor que eso no termine eclosionando[n]frente a nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Tiene una forma agradable, pero un patr吋n[n]audaz y salvaje. Quiero llev茨rmelo[n]para estudiarlo m茨s a fondo en[n]lugar de romperlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 12 0 1][f 3 1 1 0 0 5129]Esto es lo que encontr姻, aqu胤 tienes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 10 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]夷Es eso... alg雨n tipo de planta carn胤vora que come insectos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 9056][f 6 1 2 0 0 10]Mis instintos animales... me dicen que[n]eso es peligroso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]夷No ser胤a lindo como un plato para[n]servir? Lo acabo de recoger, as胤 que est茨[n]fresco y bonito.[n][f 1 3 65535][f 1 1][e]

[sel SEL_060 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es una gran idea.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Esa cosa es espeluznante.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Deber胤amos cocinarlo.[f 2 7 1 20 0 32][e]

[msg MSG_061 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 1][f 3 1 1 0 0 21055][f 6 1 2 0 0 0]斡Amigo, 夷en serio?! 斡Si usamos eso como[n]un plato, se comer茨 la comida![n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 6][f 3 1 1 0 0 24018]Supongo que no apela al sentido de[n]belleza de todos. Sin embargo, a m胤 me[n]parece bastante magn胤fico.[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Verdad? 斡Tambi姻n creo que se ve realmente[n]genial![n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1037]No hay m茨s que pueda decir...[n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5074]Es realmente carnoso y fibroso, as胤 que[n]apuesto a que tiene una gran textura.[n]Tambi姻n parece que ser胤a bastante[n]saludable.[n][f 1 3 65535][f 1 1][e]

[msg MSG_066 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No es Amagi la pr吋xima heredera de una[n]posada hist吋rica?[n][f 1 3 65535][f 1 1][e]

[msg MSG_066_5 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]夷Escuch姻 mal? Por favor, dime que s胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_067 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1037]No, no lo hiciste... Pero entiendo a qu姻 te refieres...[n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 2 1 1][f 3 1 1 0 0 0]Oh... Todas las dem茨s pueden presumir[n]un mont吋n de cosas geniales, pero todo[n]lo que consegu胤 fueron estas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]夷Qu姻 es, qu姻 es? Vamos, 斡mu姻stranos![n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 23045][f 6 1 2 0 0 6]斡Ooooh, qu姻 aroma tan tentador! 夷Podr胤an[n]ser lo que estoy pensando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 1 0 1][f 4 6 27 12 0 4][f 3 1 1 0 0 0]斡Son setas matsutake silvestres![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 27 0 0 0] las vio, 斡y luego las Ladronas Fantasma[n]se llevaron todas![n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3049][f 6 1 2 0 0 6]斡Maldici吋n! Esas cosas son caras, 斡y[n]hay tantas![n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Pero, 夷por qu姻 est茨n creciendo setas[n]matsutake en la selva?[n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 12 0 1][f 3 1 1 0 0 8130]Sospecho que estuvieron involucradas en[n]experimentos de manipulaci吋n[n]gen姻tica.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Los investigadores podr胤an haberlas[n]desarrollado simult茨neamente con los[n]dinosaurios... Aunque es solo una[n]especulaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_075 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 2 3 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Entonces, el rendimiento total de las chicas incluye un mont吋n de hierbas, alg雨n tipo de huevo, una planta y muchas setas matsutake.[n][f 1 3 65535][f 1 1][e]

[msg MSG_076 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 3][f 4 6 25 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Esa planta es un poco... ya sabes, pero[n]las otras parecen utilizables,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_077 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24031]La olla se ha elevado a la temperatura[n]adecuada, y la carne tambi姻n est茨[n]lista para cocinar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 16 1 0][f 3 1 1 0 0 0]Joker, [f 6 1 12 0 0 0] dejamos el resto en sus[n]manos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_078 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 1 12 0 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Supongo que cocinaremos las setas primero. 夷Qu姻 deber胤amos hacer con ellas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_079 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Asarlas r茨pido sobre el fuego.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]P胤calas en trozos extremadamente finos.[f 2 7 1 20 0 32][e]

[msg MSG_080 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23045]Oooh, en el momento en que tocaron las[n]llamas, este agradable aroma me[n]lleg吋...[n][f 1 3 65535][f 1 1][e]

[msg MSG_081 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Mi apetito ha sido despertado. Puedo[n]sentir mi est吋mago gru隠endo como loco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_082 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 25 10 0 1][f 3 1 1 0 0 25058][f 6 1 2 0 0 10]夷Eh? Ese es un m姻todo... sorprendente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_083 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Vaya, simplemente siguen haci姻ndose m茨s[n]peque隠as y m茨s peque隠as, a una[n]velocidad incre胤ble... 斡Casi se siente[n]como un desperdicio![n][f 1 3 65535][f 1 1][e]

[msg MSG_084 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 1 0 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Bien, ahora le toca el turno a la carne. 夷C吋mo crees que deber胤amos cocinarla?[n][f 1 3 65535][f 1 1][e]

[sel SEL_085 top]
[f 0 5 65278][f 2 1]S姻llala r茨pidamente a fuego alto.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Coc胤nala a fuego lento.[f 2 7 1 20 0 32][e]

[msg MSG_086 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 21 4 3 6][f 3 1 1 0 0 21057]斡Oh, se ve taaaaan bien! 斡Tiene esas[n]quemaduras todo! Tengo hambre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_087 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hambriento? 斡Prueba un poco de esto,[n]entonces![n][f 1 3 65535][f 1 1][e]

[msg MSG_088 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21024]Ooh, no me importar胤a si yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ugh, esta es la planta que come insectos![n]Todav胤a se est茨 moviendo; no hay[n]forma de que vaya a comer esto...[n]斡Espera, 夷por qu姻 se est茨 MOVIENDO?![n][f 1 3 65535][f 1 1][e]

[msg MSG_089 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 1][f 3 1 1 0 0 4010][f 6 1 2 0 0 3]Asarla tan lentamente me est茨 poniendo[n]nerviosa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_090 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 4][f 3 1 1 0 0 0]Estoy de acuerdo. Preferir胤a tostarla[n]con una llama fuerte.[n][f 1 3 65535][f 1 1][e]

[msg MSG_091 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]Yukiko, por favor, no te acerques al[n]fuego...[n][f 1 3 65535][f 1 1][e]

[msg MSG_092 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 24 2 0 1][f 3 1 1 0 0 0]...Ah, esta carne est茨 maravillosamente[n]dorada. Creo que est茨 lista para[n]emplatar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_093 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 4][f 3 1 1 0 0 0]Ahora, deber胤amos decorarlo con las[n]setas que preparamos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_094 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 20 10 0 3][f 4 6 4 2 0 1][f 3 1 5 0 5 122][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Y ahora a隠adimos la salsa especial...[n]斡Listo, voilà![n][f 1 3 65535][f 1 1][e]

[msg MSG_095 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3034][f 6 1 2 0 0 0]斡夷Qu姻?! 斡Chie! 夷Qu姻 demonios acabas de[n]hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_096 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Es, eh... 夷Carne a la Pel胤cula con Salsa[n]de la Selva Recolectada?[n][f 1 3 65535][f 1 1][e]

[msg MSG_097 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Me refer胤a a 夷qu姻 HAY en la salsa? 夷Y[n]cu茨ndo hiciste esa cosa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_098 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 4][f 3 1 1 0 0 5032]Combinamos la clara de huevo, las hierbas[n]y un poco de l胤quido del interior[n]de la planta, luego lo hervimos todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_099 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 0]Um... Dijeron que no usar los ingredientes[n]ser胤a un desperdicio, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_099_5 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 8027][f 6 1 2 0 0 9]No pude detenerlas. Lo siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_100 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 0]Dios m胤o, este plato parece haber sido...[n]斡Cubierto de algo viscoso![n][f 1 3 65535][f 1 1][e]

[msg MSG_101 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Es, mm... 夷C吋mo lo llaman? 夷Org茨nico?[n]Adem茨s, es bonito y verde, 夷y no huele[n]como algo que comer胤a un dinosaurio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_102 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3036][f 6 1 2 0 0 6]斡Para nada! Simplemente apesta. 斡Huele[n]a... huevos de hierba![n][f 1 3 65535][f 1 1][e]

[msg MSG_103 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Qu姻 vamos a hacer con esto? Se ha[n]convertido en una especie de objeto[n]misterioso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_104 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 3][f 4 6 19 0 2 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]夷Deber胤amos... hacer una prueba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_105 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Eh? Pero qui姻n va a…[n][f 1 3 65535][f 1 1][e]

[msg MSG_106 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 3 0 2 0][f 4 6 9 0 4 1][f 3 1 1 0 0 0]斡Alley-oop! Directo a tu boca.[n][f 1 3 65535][f 1 2 60][f 1 1][e]

[msg MSG_107 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3104][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 3]斡夷Hrg?! 斡Bluh! 斡Ah, idiota! Y-yo no[n]quiero morir todav胤a... 斡Blech! 斡Blech![n][f 1 3 65535][f 1 1][e]

[msg MSG_108 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 4 1 3][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Yosuke... Por favor, sobrevive a esto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_109 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3124][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 3]*Tos* 斡Urgh![n][f 1 3 65535][f 1 1][e]

[msg MSG_110 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]夷Est茨s bien? 夷Deber胤amos intentar hacerte[n]vomitar o algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_111 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 1 0][f 3 1 1 0 0 3101][f 6 1 2 0 0 10]N-nnngh... 斡Hrrrrrghhhh![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]E-es... Es...[n][f 1 3 65535][f 1 1][e]

[msg MSG_112 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 16 1 0][f 3 1 1 0 0 3123][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Es... 斡斡斡delicioso!!![n][f 1 3 65535][f 1 1][e]

[msg MSG_113 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡夷En serio?![n][f 1 3 65535][f 1 1][e]

[msg MSG_114 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡En serio! 斡Es tan bueno que no tiene[n]sentido! 斡Pru姻benlo, chicos![n][f 1 3 65535][f 1 1][e]

[msg MSG_115 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 0 0 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 5 0 5 124]*Mordisco*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 3 1 1 0 0 19124][f 6 1 2 0 0 6]斡Wow, tiene raz吋n, esto es bueno! 斡Est茨[n]cremoso y lleno de sabor![n][f 1 3 65535][f 1 1][e]

[msg MSG_116 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 4][f 3 1 1 0 0 0]Mm, esto podr胤a volverse bastante[n]adictivo... La salsa a隠ade una riqueza a[n]la carne que complementa el sabor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_117 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 21064][f 6 1 2 0 0 0]No puedo creerlo, 夷esa babosidad funcion吋?[n]夷Tuvo alguna especie de reacci吋n[n]qu胤mica con la carne o algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_118 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 24 4 1 1][f 3 1 1 0 0 0]斡Qu姻 armon胤a 雨nica de sabor y aroma![n]Esta salsa es una colaboraci吋n[n]milagrosa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_119 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 1 0 3][f 4 6 4 4 1 1][f 3 1 1 0 0 4051][f 6 1 2 0 0 6]夷Escuchaste eso, Yosuke? 斡Nuestras[n]habilidades culinarias son imbatibles![n][f 1 3 65535][f 1 1][e]

[msg MSG_120 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No, esto fue un milagro combinado con[n]una coincidencia... Si no fuera por[n]la carne, esto ser胤a simplemente una[n]babosidad de huevo y hierba.[n][f 1 3 65535][f 1 1][e]

[msg MSG_121 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 0]En cualquier caso, creo que deber胤amos[n]poder atraer al carn胤voro con esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_122 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 4][f 3 1 1 0 0 8122]Vamos a colocar la carnada antes de que[n]se enfr胤e.[n][f 1 3 65535][f 1 1][e]

