[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 16 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 4]Whew... 斡Lo hicimos a salvo! 夷Todos[n]siguen con nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chica En姻rgica]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 6]Whoa, daaaamn! 斡Esto es realmente un cine![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chica Reservada]]
[f 0 5 65278][f 2 1][f 4 6 5 10 0 1][f 3 1 1 0 0 3][f 6 1 2 0 0 0]Esto es incre胤ble... 夷D吋nde fue el[n]bosque? 夷La isla? 夷Los ammonitas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chica En姻rgica]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4]Nadie se preocupa por los ammonitas.[n]Son espeluznantes. Tienen demasiadas piernas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 10 0 3][f 3 1 1 0 0 5]W-whoaaa... M茨s usuarios de Persona...[n]Nuestra l胤nea se est茨 expandiendo tan[n]r茨pido... Como algas secas en sopa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Un Chico Inteligente]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 65 1 0 3][f 4 6 8 10 0 1][f 3 1 1 0 0 6][f 6 1 2 0 0 0]Um... Mayo 夷Pregunto algo? 夷Cu茨ndo[n]cambiaste de ropa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Persona Con Traje De Oso]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 4][f 3 1 1 0 0 7][f 6 1 2 0 0 6]Whoaaaaa! 斡Eres como superduper[n]sorprendentes ilusionistas![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 8]Ohhh, esto... Es una larga historia.[n]Nos pondremos en eso m茨s tarde.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9][f 6 1 2 0 0 4]Tienes a alguien que est茨 muy enfermo, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 1 0 0 1][f 3 1 1 0 0 10]S胤. 夷Hay un lugar donde pueda descansar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 11][f 6 1 2 0 0 4]... 夷Est茨 bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 3 1 1 0 0 12]夷Y t雨 eres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 6][f 3 1 1 0 0 13]Ella es Hikari-chan.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Parece que ha estado atrapada en este[n]mundo como nosotros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15]Y esto es...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 2 2 6][f 3 1 1 0 0 16]Es bueno conocerte. Soy el comisario de[n]este cine. Por favor ll茨mame Nagi.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Hemos visto las circunstancias que[n]llevaron hasta ahora. Su socio requiere[n]tratamiento inmediato.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 84 16 2 6][f 4 6 81 14 2 0][f 3 1 1 0 0 18][f 6 1 2 0 0 4]Nagi-san, 夷hay alg雨n medicamento aqu胤?[n]Tambi姻n, una manta y un lugar para que[n]ella se acueste...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Persona Con Traje De Oso]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 1][f 3 1 1 0 0 19]*Sniffle* Eres tan amable, Hikarin...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Pero parece que los ant胤dotos normales[n]no funcionan en Rise-chan... 夷Qu姻 vamos a hacer?[n][f 1 3 65535][f 1 1][e]

[sel SEL_015 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]La salvaremos, no importa qu姻.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]No pierdas el coraz吋n.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Haremos lo que podamos.[f 2 7 1 64 0 32][e]

[msg MSG_016 [Un Chico Amenazador]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 4][f 3 1 1 0 0 21][f 6 1 2 0 0 6]T胤o, sois amables, aunque nos conocimos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Un Chico Inteligente]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 4][f 3 1 1 0 0 22]Gracias. Y no deber胤amos sacudirnos...[n]Tenemos que mantener la calma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 1 0 1][f 4 6 19 12 0 3][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 23]S吋lo conozco a todos por[n]un corto tiempo, pero todos son[n]personas muy confiables.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24]Adem茨s, es natural ayudarnos[n]mutuamente, especialmente en un momento como este.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 3 1 1 0 0 25]Gracias a todos. Es un gran alivio..[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Mujer Azul]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 75 0 0 1][f 3 1 1 0 0 26]Sin embargo, si ha sido afligida con[n]veneno, necesitar茨 un ant胤doto espec胤fico.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 75 12 0 0][f 3 1 1 0 0 27][f 6 1 2 0 0 4]Haremos todo lo que podamos para[n]ayudar. 夷No la llevar茨s aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Un Chico Amenazador]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 0][f 3 1 1 0 0 28]Eso ser胤a genial.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Un Chico Amenazador]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 29][f 6 1 2 0 0 0]Espera, 夷qu姻...? 夷Qui姻n eres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 3 1 1 0 0 30]T雨 tambi姻n est茨s aqu胤, Margaret...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Chica Con Traje De Punk]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 4][f 3 1 1 0 0 31]Yo tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Chica En姻rgica]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 32][f 6 1 2 0 0 0]夷Incluso t雨, Marie-chan? 夷Qu姻 haces aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chica Con Traje De Punk]]
[f 0 5 65278][f 2 1][f 4 6 85 6 0 0][f 3 1 1 0 0 33]No s姻... estaba con Margaret cuando termin姻 aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 66 10 0 1][f 3 1 1 0 0 34][f 6 1 2 0 0 0]斡De ninguna manera! 夷M茨s gente?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 35][f 6 1 2 0 0 4]I mean, who's that? Do you know her,[n][f 6 1 30 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_028 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Parece algo familiar.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]No tengo ni idea.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Est茨 locamente caliente.[f 2 7 1 64 0 32][e]

[msg MSG_029 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 1][f 3 1 1 0 0 36]夷En serio? Tienes un gran c胤rculo de conocidos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 6][f 3 1 1 0 0 37][f 6 1 2 0 0 4]... Aunque, 夷no se refiere a esa mujer[n]en azul que nos conocimos antes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 1][f 3 1 1 0 0 38][f 6 1 2 0 0 4]Pero, esa ropa azul... 夷Podr胤a estar[n]relacionada con los otros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 1][f 3 1 1 0 0 39]Hey, suficiente con la broma.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 40][f 4 6 23 2 0 1][f 6 1 2 0 0 6]Welp, hay un tipo para ti... Mis ojos[n]son s吋lo para Lady Ann, sin embargo![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Mujer Azul]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 75 0 0 1][f 3 1 1 0 0 41]El destino de alg雨n tipo debe habernos[n]convocado aqu胤... Despu姻s de todo, nada[n]innecesario sucede con nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 3][f 3 1 1 0 0 42][f 6 1 2 0 0 4]Entonces... 夷qui姻n eres t雨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Mujer Azul]]
[f 0 5 65278][f 2 1][f 4 6 75 12 0 0][f 3 1 1 0 0 43]Ah, por favor, disc雨lpeme.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 44]Es un placer conocerlos a todos. Me[n]llamo Margaret.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 1 0 3][f 3 1 1 0 0 45][f 6 1 3 0 0 1]Le doy ayuda a este joven caballero.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 46][f 6 1 3 0 0 1]Me complace conocerlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Chica Con Traje De Punk]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 4][f 3 1 1 0 0 47][f 6 1 2 0 0 4]... 夷Y yo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 0][f 3 1 1 0 0 48]Pres姻ntate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 4 0 0][f 3 1 1 0 0 49]Soy Marie.[n][f 1 3 65535][f 1 1][e]

[sel SEL_039 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Eso es todo lo que tienes?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Encantado.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Eres residente de Habitaci吋n Terciopelo?[f 2 7 1 64 0 32][e]

[msg MSG_040 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 4 0 0][f 3 1 1 0 0 50][f 6 1 2 0 0 10]夷Qu姻? 夷Qu姻 m茨s se supone que diga?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 51][f 6 1 2 0 0 6]Quiero decir, de repente me trajeron[n]aqu胤 tambi姻n. 斡Nada de esto tiene sentido para m胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 0 0][f 3 1 1 0 0 52][f 6 1 2 0 0 10]Oh... Lo mismo aqu胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 53]Quiero decir... Me trajeron aqu胤 de[n]repente, y nada de esto me tiene sentido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 54]No, me quedo ah胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55]Pero, de repente me trajeron aqu胤 y...[n]斡Esto no tiene sentido![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 0][f 3 1 1 0 0 56]En cualquier caso, neutralizar su[n]veneno es m茨s importante. Preparar姻 la[n]medicina para ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Un Chico Inteligente]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 7 13 0 0][f 4 6 8 12 0 0][f 3 1 1 0 0 57]夷En serio? Gracias, eso ser胤a muy 雨til.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 1][f 3 1 1 0 0 58]Por favor, d姻jenos el resto. Yo tambi姻n[n]dar姻 mi ayuda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 4][f 3 1 1 0 0 59]Yo tambi姻n ayudar姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 10 2 0][f 3 1 1 0 0 60]Gracias. Hikari-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_047_5 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 0 0 0][f 3 1 1 0 0 61]Estoy seguro de que est茨n exhaustos,[n]as胤 que por favor, descansa aqu胤 un rato.[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Margaret]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 1 1 0 3][f 4 6 75 12 0 1][f 3 1 1 0 0 62][f 6 1 2 0 0 4]De hecho, 夷por qu姻 no averiguar esta[n]situaci吋n en la que todos ustedes se han[n]encontrado durante este tiempo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 63]Volveremos una vez que se haya[n]preparado la medicina.[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 4][f 3 1 1 0 0 64]Yo tambi姻n voy...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 3 1 1 0 0 65]Muy bien. Esperaremos su regreso.[n][f 1 3 65535][f 1 1][e]

