[msg MSG_000]
[f 0 5 65278][f 2 1][f 0 6 255 255]En una remota isla en el mar distante...[n][f 1 2 93][f 1 1][e]

[msg MSG_000_1]
[f 0 5 65278][f 2 1][f 0 6 255 255]Existe un parque tem茨tico de dinosaurios[n]vivos, revivido a trav姻s de la manipulaci吋n[n]gen姻tica.[n][f 1 2 255][f 1 1][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Oh? Este tiene dinosaurios.[n][f 1 2 60][f 1 1][e]

[msg MSG_002]
[f 0 5 65278][f 2 1][f 0 6 255 255]Me siento mal por esto...[n][f 1 2 55][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 0 6 255 255]Cuando los humanos se fueron, la isla se[n]convirti吋 en un h茨bitat natural para las[n]criaturas perdidas.[n][f 1 2 180][f 1 1][e]

[msg MSG_003_1]
[f 0 5 65278][f 2 1][f 0 6 255 255]Era una tierra gobernada por los carn胤voros,[n]donde la ley de la selva prevalec胤a![n][f 1 2 180][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1][f 0 6 255 255]Mientras tanto, los herb胤voros lucharon por[n]sobrevivir en este duro mundo.[n][f 1 2 145][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 0 6 255 255]Desesperados e impotentes, formaron manadas[n]mientras luchaban por escapar de los[n]carn胤voros...[n][f 1 2 230][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1][f 0 6 255 255]En este momento, un mal surge de dentro de[n]las filas: 斡una que no puede tomar una[n]pista y caer en la l胤nea![n][f 1 2 190][f 1 1][e]

[msg MSG_007]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Nadie est茨 de acuerdo con ella, pero sigue[n]oponi姻ndose al reba隠o con sus opiniones![n][f 1 2 180][f 1 1][e]

[msg MSG_008]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Los n雨meros no mienten! 斡Las reglas de la[n]mayor胤a![n][f 1 2 110][f 1 1][e]

[msg MSG_008_1]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Una opini吋n in雨til expresada por un solitario[n]disidente no es m茨s que una molestia![n][f 1 2 150][f 1 1][e]

[msg MSG_009]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Podr茨 la mayor胤a justa silenciar a la minor胤a[n]malvada.[n][f 1 2 130][f 1 1][e]

[msg MSG_009_1]
[f 0 5 65278][f 2 1][f 0 6 255 255]...y finalmente encontrar paz y tranquilidad[n]dentro del "paradiso" de la antigua[n]leyenda!?[n][f 1 2 160][f 1 1][e]

[msg MSG_010]
[f 0 5 65278][f 2 1][f 0 6 255 255]La pel胤cula de dinosaurios m茨s grande y masiva[n]jam茨s llevada a pantalla:[n][f 1 2 150][f 1 1][e]

[msg MSG_010_1]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Tierra Junessic![n][f 1 2 60][f 1 1][e]

[msg MSG_011]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Ahora en cines![n][f 1 2 80][f 1 1][e]

[msg MSG_012]
[f 0 5 65278][f 2 1][f 0 6 255 255]　[n][f 1 2 30][f 1 1][e]

