[msg MSG_000 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 12 3 1][f 3 1 1 0 0 34039][f 6 1 2 0 0 10]Nos escapamos del carn胤voro, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 0]Ah, finalmente te hemos pillado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Oh, mi mal... Me olvid姻 totalmente de[n]ustedes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 25001][f 6 1 2 0 0 4]Realmente perdiste tu compostura all胤, y en[n]la gota de un sombrero, tambi姻n... 夷No[n]fue un poco extremo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡De ninguna manera! 斡Mira eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 0]Hay muchos carn胤voros por aqu胤... Es por eso[n]que todos han estado al borde.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 22081][f 6 1 2 0 0 4]A雨n as胤, 夷no es malo que tu salud sólo entre[n]en p茨nico y huya as胤 todo el tiempo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Has probado alguna vez una t茨ctica diferente?[n]Ya sabes, como pelear o algo as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No seas rid胤cula! 斡No hay manera de que[n]podamos ganar, incluso si les lanzamos a[n]todos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 6 0 0][f 3 1 1 0 0 0]Cualquiera que haya peleado se ha comido.[n]夷Qui姻n sabe cu茨ndo nos pasar茨 tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 6][f 3 1 1 0 0 0]Hrgh... Ahora hay un pensamiento sombr胤o...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Me pregunto cu茨n fuertes son estos carn胤voros.[n]夷Ser胤a imposible para nosotros, incluso[n]con nuestras Personas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 3 0 0][f 4 6 20 1 0 0]夷Deber胤amos intentarlo?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No tentemos al destino.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Ser胤a una brisa.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 8 6 0 1][f 3 1 1 0 0 8010][f 6 1 2 0 0 9]Sospecho que ser胤a demasiado peligroso...[n]Como dice el refr茨n, los osos heridos son[n]los m茨s peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 8 6 0 1][f 3 1 1 0 0 8071][f 6 1 2 0 0 9]Ese ser胤a el curso de acción m茨s sabio. Como[n]dice el refr茨n, los osos heridos son[n]los m茨s peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 24 2 0 1][f 3 1 1 0 0 24047][f 6 1 2 0 0 4]Pareces muy confiado. 夷Vamos a buscar uno[n]ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No creo que debamos tentar al destino, como[n]dice el dicho, los osos heridos son los[n]m茨s peligrosos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷"Osos heridos"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Cuando un oso herido es acorralado, su[n]desesperación lo hace especialmente aterrador.[n]Lo mismo se dice de los jabal胤es.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9016][f 6 1 2 0 0 4]Entonces, 夷significa que me convertir胤a en[n]invencible si me metiera en una pizca?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Hraaaaaah! 斡Ahora estoy lleno! 斡Yosukeeeee![n]斡Esp姻rame![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Idiota! 斡Nos ver茨 un carn胤voro![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 0]Permanecer aqu胤 es tambi姻n demasiado peligroso,[n]debemos pasar por esta zona r茨pidamente.[n]Vamos.[n][f 1 3 65535][f 1 1][e]

