[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 1 1][f 3 1 1 0 0 3096][f 6 1 2 0 0 10]斡Eso estuvo cerca![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Gracias por venir, chicos! Realmente nos[n]salvaste el culo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Yosukeeeee! 斡Eres humano despu姻s de todo![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3037][f 6 1 2 0 0 4]夷Eh? 夷Por qu姻 lloras?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ni siquiera sabes por lo que he pasado![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]夷Despertando en una jungla, llena de dinosaurios[n]hablando? Esto no tiene sentido...[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Me alegra que estuvieras a salvo.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]夷Est茨s herido?[f 2 7 1 20 0 32][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3033]S胤, pero no es grande..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡Espera! 夷Qui姻n eres?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 6][f 1 5][f 6 1 14 0 0 0]　　[n][f 3 1 1 0 0 0]Estos son nuestros compa隠eros que nos conocimos[n]aqu胤. Son Persona-usuarios, igual[n]que nosotros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 0]Nos chuparon en este mundo como t雨.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0]Ahora nos hemos unido para encontrar un camino[n]de regreso a nuestros propios mundos.[n]Encantado![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Igual que aqu胤... 夷Eres un gato disfrazado,[n]o una persona disfrazada de gato, como[n]con Teddie, o...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23036][f 6 1 2 0 0 1]Esc雨chame. No estoy en un disfraz, y no soy[n]un gato![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 14 0 0 0]　　[n][f 3 1 1 0 0 0]... De todos modos, me alegro de que est姻s[n]a salvo, Yosuke. Todos est茨bamos muy[n]preocupados por ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Gracias, chicos. Siento preocuparte...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Habr胤a logrado mejor si estuviera solo, pero[n]he estado tratando de proteger a este[n]dinosaurio que hablaba aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 7 2 0 0][f 3 1 1 0 0 7049][f 6 1 2 0 0 6]Luchaste hasta aqu胤... 夷todo por ti mismo?[n]斡Eso es malo, Yosuke-senpai![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Haha, estoy a toda velocidad... Supongo que[n]eso hace que estas heridas sean mis[n]medallas de honor?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Herbívoro Tímido]]
[f 0 5 65278][f 2 1][f 4 6 90 0 0 0][f 3 1 1 0 0 0]Um... Gracias...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3029][f 6 1 2 0 0 4]斡No te preocupes! Tenemos que ayudarnos unos[n]a otros cuando estamos en problemas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mira qui姻n ha vuelto. Supongo que tambi姻n[n]estaban preocupados por ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Herbívoro Tímido]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 90 0 1 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 93 0 1 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 21031][f 6 1 2 0 0 4]夷Ves? 斡La salvamos! 夷No te alegras?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Herbívoro Inquieto]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 47 1 1 4][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 0]斡S胤! 斡Un final tan bueno como podr胤amos[n]pedir![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 93 1 1 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 19020]夷No parecen estar reaccionando...[n]extra隠amente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 2 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces... 夷Deber胤amos hacer la cosa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Herbívoro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 47 0 1 0][f 3 1 1 0 0 0]S胤, supongo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 12 0 0][f 3 1 1 0 0 0]Es hora de someterlo a votaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 7034][f 6 1 2 0 0 0]Espera, 夷qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Todos aquellos que piensan que debemos[n]permitir que los humanos permanezcan en[n]nuestra manada, levanten la mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 90 1 1 3][f 6 1 25 0 0 0][f 4 6 34 16 3 4][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 7 4 0 0][f 4 6 22 10 0 0][f 3 1 1 0 0 22055][f 6 1 2 0 0 0]斡Oye! 夷Qu姻 demonios?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Herbívoro Tímido]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 90 0 1 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ahora, todos los que piensan que debemos[n]echarlos, levanten la mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 0 0 0][f 3 1 1 0 0 0]Sobre la base de un voto un茨nime, los humanos[n]son expulsados. D姻jalos aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 0][f 3 1 1 0 0 27061][f 6 1 2 0 0 0]Pero, 夷por qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 34 0 1 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 1 1 0][f 3 1 1 0 0 0]Todo es tu culpa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Santo, tiene mi cabeza! 夷Qu姻 demonios est茨[n]pasando aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ustedes ignoraron la regla de la mayor胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3019][f 6 1 2 0 0 4]夷Qu姻? 夷De qu姻 est茨s hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 3 1 1 0 0 0][f 6 1 9 0 0 1][f 6 1 2 0 0 6]Hemos terminado con ustedes. S吋lo... ve y[n]haz lo que quieras, pero d姻janos en paz![n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 1 3][f 3 1 1 0 0 0]Y ah胤 van...[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 3 6 0 6][f 3 1 1 0 0 3091][f 6 1 2 0 0 9]Amigo... 夷Qu姻 fue todo eso?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]夷Y por qu姻 ten胤a mi cabeza? No tengo idea de[n]lo que est茨 pasando, 斡y me estoy volviendo[n]loco![n][f 1 3 65535][f 1 1][e]

[sel SEL_040 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Es una larga historia.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Si te calmas, te lo dir姻.[f 2 7 1 20 0 32][e]

[msg MSG_041 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 1][f 3 1 1 0 0 5072]S胤, Yosuke tambi姻n parece agotado. Podr胤a[n]ser mejor si lo hablamos en un lugar[n]m茨s seguro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 8 1 0][f 3 1 1 0 0 3092]S胤... Tienes raz吋n. Adelante, ponlo sobre[n]m胤... Estoy escuchando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 1][f 3 1 1 0 0 0]Bueno, es una larga historia... podr胤a ser[n]mejor que hablemos de ello en un lugar[n]m茨s seguro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Yosuke parece agotado, tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0]Bueno, regresemos al cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3061][f 6 1 2 0 0 0]Espera, 夷dijiste un cine? 夷Tu base no es una[n]cueva o una tienda?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Bueno, supongo que deber胤amos explicar algunas[n]cosas en el camino. Vamos, s胤guenos.[n][f 1 3 65535][f 1 1][e]

