[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 1][f 3 1 1 0 0 3001][f 6 1 2 0 0 4]As胤 que, para cambiar esta pel胤cula,[n]tenemos que encontrar a... Yosukesaurio...[n]夷Verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Vamos, 夷alguien tiene alguna otra idea[n]de c吋mo llamarlo adem茨s de[n]Yosukesaurio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4033]夷C吋mo m茨s podr胤amos llamarlo? Es[n]exactamente igual a ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]夷Por qu姻 ten胤a que ser mi cabeza en un[n]dinosaurio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28015]Yosukesaurio probablemente es la clave[n]para cambiar esta pel胤cula.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La manada hab胤a dicho que se dirig胤an[n]a un "para胤so sin carn胤voros" en los[n]confines m茨s lejanos de la isla...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 4][f 3 1 1 0 0 0]En ese caso, estoy seguro de que[n]eventualmente nos reuniremos con ellos si[n]vamos en la direcci吋n de este para胤so.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3106][f 6 1 2 0 0 6]斡Genial! 斡Acabemos con esto lo m茨s r茨pido[n]posible![n][f 1 3 65535][f 1 1][e]

