[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 1][f 3 1 1 0 0 1][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Joker, espera! 斡Para, stoooop![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 25 4 1 0][f 3 1 1 0 0 2][f 6 1 2 0 0 0]夷Qu姻 pasa con el grito? 夷Es un enemigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 0][f 3 1 1 0 0 3][f 6 1 2 0 0 10]No lo s姻, pero algo se acerca a ustedes[n]locos r茨pido![n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]夷Es un dinosaurio?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Es un FOE?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Es Mona?[f 2 7 1 20 0 32][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 4][f 3 1 1 0 0 4][f 6 1 2 0 0 0]夷De ninguna manera? 夷Eso significa que[n]viene tras nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 4][f 3 1 1 0 0 5]S胤, me estoy acercando con mi supersoni..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 6]斡En serio! 斡He estado a tu lado todo este tiempo![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 1 0 0 7]Estos no son dinosaurios o FOEs...[n]Basado en esta velocidad de movimiento...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8][f 6 1 2 0 0 0]De ninguna manera... 夷Podr胤an ser humanos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 21 10 0 3][f 3 1 1 0 0 9][f 6 1 2 0 0 0]夷En serio? 夷Hay alguien m茨s aqu胤 adem茨s[n]de nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 1][f 3 1 1 0 0 10]Oh, tal vez esto es lo que Oracle hab胤a[n]mencionado cuando entramos en la pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]夷Sabes c吋mo hay m雨ltiples presencias[n]poderosas aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 8 2 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 12][f 6 1 2 0 6]Hey![n]斡Quiz茨s sean mis compa隠eros![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 13]Eso tiene sentido... Si son humanos con[n]poderes fuertes, podr胤a ser correcto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Sin embargo, normalmente, no deber胤a[n]haber humanos en esta pel胤cula.[n]Probablemente sea mejor permanecer cauteloso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0]Tienes raz吋n. Adem茨s, tengo curiosidad[n]por la parte de alta velocidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 2 99 1][f 3 1 1 0 0 16][f 6 1 2 0 0 6]Tu curiosidad est茨 a punto de estar[n]satisfecha... 斡Se est茨n acercando ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 24 0 0 4][f 3 1 1 0 0 17]Parece que no tenemos tiempo para[n]acabar con esto. Joker, 夷cu茨l es tu decisi吋n?[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1]Hagamos el primer movimiento.[f 2 7 1 20 0 1][e]
[f 0 5 65278][f 2 1]Veamos qu姻 pasa.[f 2 7 1 20 0 32][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 18]Muy bien, te lo dejaremos. Toma tu[n]arma, por el factor de miedo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19]Si estamos tratando con humanos, solo[n]mostr茨ndoles que deber胤a darte una ventaja.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 4][f 3 1 1 0 0 20]Espero que esto funcione a nuestro[n]favor... Permanezcamos en nuestros dedos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 26 2 99 0][f 3 1 1 0 0 21][f 6 1 2 0 0 6]Hey, entrando! 斡Prep茨rate![n][f 1 3 65535][f 1 1][e]

