[msg MSG_000 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 4106]斡Lo logramos! 斡Vamos, vamos a poner el cebo![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_3]
[f 0 5 65278][f 2 1][f 4 6 20 2 32 3][f 3 1 1 0 0 0]Colocamos el desv胤o del carn胤voro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 25008]Espero que el dinosaurio pueda olerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 4 3 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Hraaaah! 斡Que el olor de la carne[n]llegue a tus narices, poderosa bestia![n]*blow* *blow* *blow* *blow* *blow* *blow*[n]*blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow* *blow*[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Uh, s吋lo volar en el cebo con tu boca[n]no va a funcionar desde tan lejos..[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 6][f 3 1 1 0 0 23019][f 6 1 2 0 0 6]斡El dinosaurio est茨 oliendo el aire![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷En serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 6 0 99 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Mira! 斡Va por ello![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 22043][f 6 1 2 0 0 7]斡S胤! 斡Se est茨 comiendo el cebo! 斡Lo hicimos![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Deber胤amos aprovechar esta oportunidad[n]para pasar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 0][f 3 1 1 0 0 26633][f 3 1 6 0 0 500]Espera. Est茨 a punto de terminar el cebo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Ya? Todo ese esfuerzo, por nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3046][f 6 1 2 0 0 4]Espera, 夷qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]Podr胤a haber regresado a su nido ahora[n]que ha comido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0][f 6 1 2 0 4]Bueno, parece[n]que todo funcion吋 al final, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19042][f 6 1 2 0 6]Lo sabes! 斡Ese carn胤voro se ha ido![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 21 6 0 3][f 3 1 1 0 0 0]Dios, ahora parece que fue un[n]desperdicio dejar que ese dinosaurio comiera nuestra carne.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Estoy de acuerdo. La oportunidad de[n]festejar sobre un corte de carne que tama隠o[n]viene s吋lo una vez en la vida![n][f 1 3 65535][f 1 1][e]

[sel SEL_016 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Intentemos conseguir m茨s.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]夷Hay sobras?[f 2 7 1 20 0 32][e]

[msg MSG_017 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 27067]斡S胤! Fue muy divertido reunir[n]ingredientes y cocinar con todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Pero, reunir esos ingredientes de nuevo[n]podr胤a poner muy bien nuestras vidas en peligro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24089]Me imagino que queda al menos un poco[n]de jugo de carne. Ir姻 a ver..[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Oh no, no lo haces. Cuidado con tus modales.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Oh, todav胤a nos quedan toneladas de[n]esa salsa! Es saludable y sabroso,[n]夷deber胤amos traerlo de vuelta al Cine como regalo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 6][f 3 1 1 0 0 0]Me pregunto si podr胤amos servir esto en[n]nuestra posada... Podr胤a ser capaz de[n]hacer algo similar con ingredientes convencionales.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 3078][f 6 1 2 0 0 0]夷Olvidar胤as la salsa? 夷Qu姻 est茨s[n]tratando de hacer de todos modos, hacer una[n]versi吋n jungla de Mystery Food X!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0][f 6 1 2 0 4]夷Qu姻 es Mystery Food X?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 1][f 1 5][f 6 1 14 0 0 0]Es... No quieres saberlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 0 0 1][f 3 1 1 0 0 0]Siento interrumpir la conversaci吋n,[n]pero no sabemos cu茨ndo volver茨 ese carn胤voro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23123][f 6 1 2 0 0 6]Tiene raz吋n. 斡Vamos, mejor que pasemos[n]tan r茨pido como podamos![n][f 1 3 65535][f 1 1][e]

