[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 3 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19117]斡Mira, ah胤 est茨n![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0]斡Aha! 斡Por fin llegamos al reba隠o![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Herbivore Elegante]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 42 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oye, esos humanos han vuelto... 夷Nos siguieron?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷De ninguna manera? 斡Pens姻 que[n]bloqueamos el camino![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23052]斡Heheh! 斡Como si renunciara a un[n]obst茨culo tan peque隠o![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Herb胤voro Timid]]
[f 0 5 65278][f 2 1][f 4 6 90 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Pero... 夷por qu姻 nos sigues?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Herbivore Elegante]]
[f 0 5 65278][f 2 1][f 4 6 42 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, ya no tenemos nada que ver contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Nervous Herbivore]]
[f 0 5 65278][f 2 1][f 4 6 47 0 0 0][f 3 1 1 0 0 0]Vamos a ignorar a los humanos y seguir[n]movi姻ndose. 夷A qui姻n le importan?[n]Mientras podamos llegar a nuestro para胤so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7036][f 6 1 2 0 0 6]斡Hola! 斡Vuelve aqu胤, bastardos![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 1][f 6 1 25 0 0 0][f 4 6 34 1 0 3][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0]夷Est茨s bien con esto? Sigues[n]suprimiendo c吋mo te sientes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Est茨s realmente satisfecho con ser el[n]tipo de chico para abandonar a tus amigos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 34021][f 6 1 2 0 0 6]斡No puedo evitarlo! 斡Esto es lo que todos votaron![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 0 1 0][f 3 1 1 0 0 0]Es la regla de la manada... 斡Si voy en[n]contra, ser姻 el que sali吋 a patadas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡D姻jame en paz![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 3 3 2 0][f 4 6 5 6 0 4][f 3 1 1 0 0 0]Ah胤 van otra vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 6 1 3 0 0 1]斡Sheesh, esto otra vez! 斡Vamos tambi姻n![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 9 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Yosuke, 夷qu姻 es lo que te ha despedido tanto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3061][f 6 1 2 0 0 0]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Cierto, pareces especialmente invertido[n]cuando se trata de Yosukesaurus...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Cierto. Supongo que me estaba calentando con 姻l.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es como... Puedo entender c吋mo se siente.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]夷Porque te ves igual?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Por qu姻?[f 2 7 1 20 0 32][e]

[msg MSG_019 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3010][f 6 1 2 0 0 3]Bueno, supongo que eso podr胤a ser parte[n]de ello. Pero es m茨s porque me recuerda[n]c吋mo sol胤a ser...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3009]Bueno, no es tan interesante ni nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Creciendo, tuve que transferir mucho, y[n]los estudiantes de transferencia[n]tienden a sentirse aislados cuando llegan a su[n]nueva escuela.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0]S姻 lo que quieres decir. Hay todos[n]estos grupos de amigos establecidos y[n]camarillas, y luego apareces...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3011]Por eso me reir胤a o ir胤a con lo que los[n]otros dec胤an, as胤 que no me sentir胤a aislado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero, termin姻 escondiendo c吋mo me[n]sent胤a todo el tiempo. Incluso cuando no[n]estaba de acuerdo con lo que dijeron, me la chup姻.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si no hubiera hecho eso, ser胤a la extra隠a?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 99 0][f 3 1 1 0 0 0][f 3 1 6 0 0 500]S姻 lo dif胤cil que es sentirse solo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Podr胤a haber un mont吋n de gente a tu[n]alrededor, pero todav胤a sientes como si te[n]quedaras como un mal pulgar. Puede ser aterrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19010]Es dif胤cil estar solo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 5 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Cuando la familia de Yosuke-kun vino[n]por primera vez a Yasoinaba, se escrutaron[n]bastante por su negocio...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]S胤, no importa ad吋nde fui, siempre fue lo mismo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Siempre evaluar胤a las reacciones de la[n]gente para ver si les gustaba... Todas[n]mis relaciones se sent胤an tan falsas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Eso es, hasta que conoc胤 a estos tipos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]Yosuke-senpai...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3030]Cuando empec姻 a salir con ellos,[n]escondiendo mi personalidad alrededor de ellos[n]me hizo sentir como si fuera un idiota.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Espera, 夷realmente nos est茨s pagando un cumplido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Bueno, s胤. No importa lo que otros[n]dijeron, ustedes no me juzgaron[n]inmediatamente, 夷recuerdan?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Hablamos de nuestros verdaderos[n]sentimientos, y me detienes cuando estoy a[n]punto de hacer algo malo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Conocer gente as胤... Conocer amigos as胤[n]ha sido cambiar de vida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1029]Heh... Ese es el[n]mayor cumplido que podr胤a darnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 10 100 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Yosuke-senpai est茨 siendo real con nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Oh, vamos! 夷Qu姻 tiene de malo que me[n]derrame las tripas por una vez?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 9 6 0 0][f 3 1 1 0 0 9040]*Sniff* Me has movido tanto que apenas[n]puedo soportarlo, Yosuke...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Argh! 斡No m茨s de eso! 斡Estoy[n]avergonzada de repente![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 0][f 3 1 1 0 0 0]Gracias por compartir tus sentimientos[n]con nosotros, Yosuke-kun.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3003][f 6 1 2 0 0 6]U-Uhh... Bueno, de todos modos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Quiero darle a Yosukesaurus y a los[n]otros dinosaurios un pedazo de mi mente![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si todos son realmente compa隠eros,[n]necesitan dejar de preocuparse por las[n]reacciones de otros y ser honestos entre s胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]S胤, los encontraremos y les diremos[n]exactamente eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 27 2 0 1][f 3 1 1 0 0 27050]Todos comparten un v胤nculo tan[n]fuerte... Es maravilloso ser testigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ser茨 mejor que hagamos nuestro juego[n]tambi姻n... 夷Verdad, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_042 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Estamos tan apretados como ellos.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Vamos a trabajar juntos.[f 2 7 1 20 2 32][e]

[msg MSG_043 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 2 0 1][f 3 1 1 0 0 23067][f 6 1 2 0 0 6]As胤 es. 斡Nuestros lazos son fuertes como el acero![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21069][f 6 1 2 0 0 6]斡Claro que s胤! 斡Nada es imposible para[n]los Fantasmas![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 1 100 3][f 4 6 3 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Bueno, entonces, vamos a ir antes de[n]perder la pista de ellos![n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Haremos todo lo posible para navegar,[n]as胤 que ser茨 mejor que no te rindas![n][f 1 3 65535][f 1 1][e]

