[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 26062]斡Has vuelto![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Perd吋n por la prisa, pero ven conmigo a la[n]taquilla... La chica azul nos llama.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Pas吋 algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Supongo que tiene algo para nosotros tan[n]incre胤ble que... "Haz que nuestras mejillas[n]caigan al suelo."[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 0][f 3 1 1 0 0 9058]斡Haz que nuestras mejillas hagan lo que sea?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Qu姻 horrible! Me asegurar姻 de mantener tus[n]mejillas en su lugar, Futaba![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 1 0 1][f 4 6 70 10 0 3][f 3 1 1 0 0 26061][f 6 1 2 0 0 0]夷Wh-Whaaa?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 0]Sus patas son... suaves, pero caen al mismo[n]tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Incluso detecto un olor agradable de suavizador[n]de tela!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0]Sigo derramando helado sobre m胤, as胤 que[n]Yosuke siempre me da un buen lavado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 0][f 3 1 1 0 0 0]Yosuke-senpai es muy considerado, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 27003][f 6 1 2 0 0 4]夷C吋mo te lavas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0]Heheheh... 夷C吋mo crees que estoy limpia?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Vas a la lavadora.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]畏l te ahuyenta afuera.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]No tengo inter姻s en esto.[f 2 7 1 64 4 32][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 6][f 3 1 1 0 0 26017][f 6 1 2 0 0 4]Entonces, supongo que acaba de lanzarse all胤[n]con un detergente y el resto es[n]autom茨tico?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Mi piel es demasiado delicada para ese tipo[n]de tratamiento! 斡Un abrigo como este[n]solo puede ser lavado a mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 6][f 3 1 1 0 0 26047]夷Y luego lo corta con un cepillo? Suena como[n]un lavado de autos... o tal vez m茨s como[n]un Teddiewash.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Mi piel es demasiado delicada para ese tipo[n]de tratamiento! 斡Un abrigo como este[n]solo puede ser lavado a mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 6][f 3 1 1 0 0 26033]Whoa... Es tan desalentador que es macho, de[n]alguna manera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Qu姻 fr胤o! 斡Por favor, toma m茨s inter姻s en[n]m胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 1][f 3 1 1 0 0 0]Es un disfraz. Puede quit茨rsela.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 10 0 6][f 3 1 1 0 0 24036][f 6 1 2 0 0 4]夷Qu姻? 夷Tiene...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0]斡As胤 es! Solo voy as胤, aaaaa y... 斡Hup-hup,[n]y un abrazo![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 95 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ta-daaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 71 10 0 0][f 3 1 1 0 0 27057][f 6 1 2 0 0 0]夷Huhhh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 10 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Hab胤a alguien dentro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 8 0 1][f 3 1 1 0 0 0]Oh, 夷est茨s tan sorprendida por la repentina[n]aparici吋n de un chico tan bonito que[n]est茨s perdiendo palabras? Heehee...[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Vaya.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Y qu姻 hay dentro de eso?[f 2 7 1 64 0 32][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 12 0 0][f 3 1 1 0 0 9081][f 6 1 2 0 0 4]夷Qu姻? 夷Eso es todo? 夷No podr胤as, como, caerte[n]de rodillas en sorpresa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Lo siento... No val胤a la pena tanta reacci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 8 0 0][f 3 1 1 0 0 9135][f 6 1 2 0 0 4]夷Qu姻 es esto? 夷Quieres conocerme a雨n m茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]En realidad no...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Qu姻 mal![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, s胤, suficiente de esta estupidez. 夷No[n]deber胤a Yosuke ser m茨s importante para[n]nosotros ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 7013]Me pregunto d吋nde se ha ido...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Espero que est姻 bien... Quiero decir, estar茨[n]bien, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0]　　[n][f 3 1 1 0 0 0]S胤. Mi compa隠ero no es un tipo que cae tan[n]f茨cilmente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Tendremos que seguir haciendo lo que podamos[n]ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 10 0 1][f 3 1 1 0 0 5063][f 6 1 2 0 0 6]斡Oh! Eso me recuerda, 夷No nos est茨 esperando[n]Elizabeth? 斡Debemos irnos![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Heeeeeey! 斡No me dejes en paz![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Sheesh... Qu姻 mont吋n de remos. Vale, [f 6 1 30 0 0][n], vamos.[n][f 1 3 65535][f 1 1][e]

