[msg MSG_000 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 1][f 3 1 1 0 0 1]Ya veo... Es similar a como llegamos nosotros aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 2][f 6 1 2 0 0 10]Hay otros lugares que son como Mementos... Estoy sorprendida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 3]Bueno, espacios como esos nacen de los corazones de la gente, no ser胤a tan extra隠o si hubiera otros en otro lugar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 3][f 3 1 1 0 0 4]Un espacio nacido del coraz吋n de la gente, 夷eh?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]夷Por eso pueden conectarse a otros espacios similares?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 1][f 3 1 1 0 0 8]Probablemente, tal deducci吋n no se aplica 雨nicamente a los reinos dentro de las pel胤culas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9]Creo que el cine en el que estamos ahora es otro mundo que ha nacido por una raz吋n espec胤fica.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 10]Ya veo, eso explicar胤a por qu姻 he estado atrapado en esta forma también.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Persona Disfrazada De Oso]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 9 6 0 1][f 3 1 1 0 0 11][f 6 1 2 0 0 3]No entiendo lo que est茨s diciendo, pero debido a todo esto, Yosuke...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 1][f 6 1 1 0 0 1][f 4 6 72 2 1 3][f 4 6 9 0 1 1][f 3 1 1 0 0 12]斡Yosuke est茨 solo! ¡Waaaaaaaaaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13][f 6 1 3 0 0 3]夷Yosuke? ¿Es el amigo que mencionaste cuando nos conocimos? ¿El que se separ吋?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14][f 6 1 2 0 0 10][f 6 1 3 0 0 3]...Bien, mm, espera. Por favor, por favor, d姻jame ir... No puedo respirar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chica Reservada]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 4][f 3 1 1 0 0 15]Entiendo c吋mo te sientes, pero c茨lmate, Teddie.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16]Incluso si llevas a esa persona extrabrillante, Yosuke no saldr茨 de 姻l.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17][f 6 1 2 0 0 9][f 6 1 3 0 0 3]Je, je, je... 'Extra brillante'...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Persona Disfrazada De Oso]]
[f 0 5 65278][f 2 1][f 4 6 72 6 0 0][f 4 6 9 0 0 0][f 3 1 1 0 0 18]*Jadeo* Al principio ol胤 algo agradable en 姻l, 斡pero ella tiene raz吋n![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 8][f 3 1 1 0 0 19]Adem茨s, prefiero ir por esta hermosa dama...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 0 0][f 3 1 1 0 0 20]Aqu胤 tienes, este Megidolaon es para ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Persona Disfrazada De Oso]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 21][f 6 1 1 0 0 1][f 6 1 2 0 0 1]斡Gyaaaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 19 12 0 3][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 22]... Has sido separado de tu amigo llamado Yosuke, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23]Podr胤a seguir en la película. Me separ姻 de mis amigos y terminé en una película. Tal vez le paso lo mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chico Inteligente]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 1][f 3 1 1 0 0 24][f 6 1 2 0 0 3]Ya veo. Espero que Yosuke salga sano y salvo, como t雨...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Chica En姻rgica]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 25][f 6 1 2 0 0 6]De todos modos, 斡seamos positivos! ¡Entrar en p茨nico no ayudará en un momento como este![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26]斡Rise y Yosuke estar茨n bien! Despu姻s de todo, ¡también forman parte del Equipo de Investigaci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 3 1 1 0 0 27]Cierto. Yosuke nunca caer胤a tan f茨cilmente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28]Sin embargo, debe sentirse solo estando separado de nosotros. Tenemos que apresurarnos y rescatarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Persona Disfrazada De Oso]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 29]M-Maestro...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 30][f 6 1 2 0 0 7]斡Teddie ha vuelto y mejor que nunca! ¡Rescatar a Yosuke ser茨 lo 雨nico en mi mente![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 1 12 0 1][f 3 1 1 0 0 31]Lo siento, estamos un poco ruidosos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 32][f 6 1 3 0 0 1]S姻 que es un poco tarde, pero no nos hemos presentado. Me encantar胤a conocer m茨s sobre ustedes también.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 33]Oh, s胤, es verdad. Bueno, es hora de las presentaciones...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Chica En姻rgica]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 4 10 0 0][f 3 1 1 0 0 34][f 6 1 2 0 0 10]夷Eh? Entonces, ¿qu姻 deber胤amos hacer? ¿Quién va primero?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Persona Disfrazada De Oso]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 6][f 3 1 1 0 0 35]Obviamente, 斡deber胤a ser el Maestro! 夷Qui姻n podría ser mejor?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Chica Reservada]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 36]Es cierto, 姻l es nuestro l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chico Compuesto]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 3 1 1 0 0 37]Entendido. Mi nombre es...[n][f 1 3 65535][f 1 1][e]

