[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 1 1][f 3 1 1 0 0 22011][f 6 1 2 0 0 4]Entonces... incluso si encontramos a esos herb胤voros nuevamente, 夷nos servir茨 de algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]夷De verdad van a escuchar lo que tenemos que decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 1 0][f 3 1 1 0 0 0]S胤, parecían muy enojados con nosotros. Incluso nos echaron de su grupo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 8016]Creen que la regla de la mayor胤a los ha mantenido vivos en este mundo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003_5 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 0]Puedo entender por qu姻 no pudieron perdonarnos después de tomar sus métodos de supervivencia tan a la ligera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0]Pero, si vamos a cambiar esta pel胤cula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷No ser茨 imposible a menos que cambiemos ese pensamiento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 0][f 3 1 1 0 0 4104]夷C吋mo vamos a hacer eso? ¿Deber胤amos preparar unos ricos filetes para intentar convencerlos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Eso solo funcionar胤a contigo, Chie. 斡Esos tipos son herbívoros![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]No parec胤an f茨ciles de convencer. Necesitamos una manera de cambiar sus mentes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 24 4 1 3][f 3 1 1 0 0 24017][f 6 1 2 0 0 4]Esos dinosaurios son el misterio... 夷Por qu姻 est茨n tan negados a pensar en alguna alternativa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 1][f 3 1 1 0 0 0]...Creo que realmente est茨n asustados.[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]夷Asustados?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Creo que lo entiendo.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]夷A pesar de ser dinosaurios?[e]

[msg MSG_011 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 27011]Bueno, supongo que prefieren seguir la corriente. Tienen miedo de contradecir a los dem茨s y destacar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 27074]Bueno, supongo que prefieren seguir la corriente. Tienen miedo de contradecir a los dem茨s y destacar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 0][f 3 1 1 0 0 27011]Bueno, el tama隠o de sus cuerpos y la fuerza de sus corazones son cosas separadas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 0]Bueno, supongo que prefieren seguir la corriente. Tienen miedo de contradecir a los dem茨s y destacar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Es verdad, tener que seguir a la multitud, tener expectativas y etiquetas impuestas sobre ti...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Resistir ese tipo de cosas te agota mucho y realmente te golpea con el tiempo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 1][f 3 1 1 0 0 7012][f 6 1 2 0 0 3]Ohhh, te entiendo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Seguir la corriente es m茨s fácil, y no tienes que asumir la responsabilidad de ning雨n resultado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ese tambi姻n fue el enfoque a resolver en la pel胤cula anterior.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 0]Usar la regla de la mayor胤a para tomar decisiones no es necesariamente incorrecto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0]Pero, no poder expresar ni siquiera tu propia opini吋n solo porque est茨s en la minor胤a... eso es simplemente...[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es injusto.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Es asfixiante.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Es aburrido.[f 2 7 1 20 6 32][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 5069]Deben recibirse opiniones diferentes, independientemente de los n雨meros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 21091][f 6 1 2 0 0 3]夷Verdad? No decir tu opini吋n solo porque es diferente a la de los dem茨s, es lo peor...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Es normal que diferentes personas tengan diferentes opiniones![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 24067]De hecho. Si todos siguieran los mismos m姻todos y creencias, nada nuevo surgir胤a.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La diversidad debe ser m茨s valorada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 1 0 1 3][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]S胤, todos somos compa隠eros, pero cada uno tiene una manera diferente de pensar y sentir...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero, si todos lo discutimos, s姻 que podemos llegar a la mejor soluci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 1][f 3 1 1 0 0 0]Poder decir lo que piensas, aunque pueda resultar mal...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0]Supongo que eso es un tipo de valent胤a que esos dinosaurios no tienen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 4][f 3 1 1 0 0 9038]Yosukesaurio parec胤a tan molesto cuando la manada estaba votando...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Creo que, en el fondo, 姻l realmente no quer胤a echarnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]S胤, definitivamente estaba indeciso. Al final, parecía que tenía que convencerse a sí mismo de seguir la corriente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 0 1 1][f 3 1 1 0 0 0]As胤 que no tuvo el valor de dar ese peque隠o paso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 0][f 3 1 1 0 0 23103][f 6 1 2 0 0 0]夷斡Mrow-ow-ow!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Whoa, eso me asust吋... 夷斡Qu姻 FUE eso!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Son吋 como si algo grande cayera cerca. Deber胤amos investigar, Joker.[n][f 1 3 65535][f 1 1][e]

