[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 26062]斡Han vuelto![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Perd吋n por la prisa, pero vengan conmigo a la taquilla... La chica de azul nos llama.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Pas吋 algo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Supuestamente, ella tiene algo para nosotros tan incre胤ble que har茨 que... "Nuestras mejillas caigan al suelo".[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 1][f 3 1 1 0 0 0][f 3 1 1 0 0 9058]夷斡Hacer que nuestras mejillas hagan QU畏!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Qu姻 terrible! ¡Me aseguraré de mantener tus mejillas en su lugar, Futaba![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 1 0 1][f 4 6 70 10 0 3][f 3 1 1 0 0 26061][f 6 1 2 0 0 0]斡夷Q-Qu姻!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 0]Sus patas son... esponjosas, pero a la vez un poco regordetas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Acaso percibo un agradable aroma de suavizante de telas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0]Sigo derramando helado sobre m胤, así que Yosuke siempre me da un buen lavado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 0][f 3 1 1 0 0 0]Yosuke es realmente considerado, 夷verdad...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 27003][f 6 1 2 0 0 4]Quiero decir, Teddie: 夷c吋mo te ba隠as?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0]Je, je, je... 夷C吋mo crees que quedo relucientemente limpio?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Entras en la lavadora.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Te enjuaga con una manguera.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]No me interesa saberlo.[f 2 7 1 64 4 32][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 6][f 3 1 1 0 0 26017][f 6 1 2 0 0 4]Entonces, 夷supongo que simplemente lo arrojan all胤 con un poco de detergente y el resto es autom茨tico?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Mi pelaje es demasiado delicada para ese tipo de tratamiento! ¡Un abrigo como este solo se puede lavar a mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 6][f 3 1 1 0 0 26047]Y luego lo frota con un cepillo, 夷no? Suena como un lavado de autos... o quiz茨s más como un Teddiewash.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Mi pelaje es demasiado delicado para ese tipo de tratamiento. 斡Un abrigo como este solo puede lavarse a mano![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 6][f 3 1 1 0 0 26033]Vaya... Es tan distante que resulta un tanto masculino, de alguna manera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Qu姻 fr胤a! ¡Por favor, muestra m茨s interés en mí![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 4 12 0 1][f 3 1 1 0 0 0]Es un disfraz. Puede quit茨rselo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 10 0 6][f 3 1 1 0 0 24036][f 6 1 2 0 0 4]夷Qu姻? ¿畏l tiene...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 0]斡As胤 es! Solo hago esto, y... ¡Hup-hup, y un hup![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 95 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ta-daaaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 71 10 0 0][f 3 1 1 0 0 27057][f 6 1 2 0 0 0]*jadeo* 夷斡Huhhh!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 10 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷斡Hab胤a alguien adentro!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 8 0 1][f 3 1 1 0 0 0]Oh, 夷est茨s tan sorprendida por la repentina aparici吋n de un chico tan guapo que te has quedado sin palabras? Ji, ji, ji...[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Wow.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Y qu姻 hay dentro de ese?[f 2 7 1 64 0 32][e]

[msg MSG_024 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 12 0 0][f 3 1 1 0 0 9081][f 6 1 2 0 0 4]夷斡Qu姻!? ¿Eso es todo? ¿No podr胤as, como, ponerte de rodillas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Lo siento... No val胤a la pena tanta reacci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 8 0 0][f 3 1 1 0 0 9135][f 6 1 2 0 0 4]夷Qu姻 es esto? ¿Quieres conocerme a雨n m茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]En realidad no...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Qu姻 mal![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, sí, suficiente de esta estupidez. 夷No debería Yosuke ser m茨s importante ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 7013]Me pregunto d吋nde se ha ido...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Espero que est姻 bien... Quiero decir, estar茨 bien, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]S胤. Mi compa隠ero no es un tipo que cae tan f茨cilmente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Tendremos que seguir haciendo lo que podamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 10 0 1][f 3 1 1 0 0 5063][f 6 1 2 0 0 6]斡Oh! Eso me recuerda, 夷No nos est茨 esperando Elizabeth? ¡Debemos irnos![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Eeeeeh! ¡No me dejes atr茨aaaaas![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Vaya... Qu姻 grupo tan bullicioso. De acuerdo, [f 6 1 30 0 0 0], vamos.[n][f 1 3 65535][f 1 1][e]

