[msg evt_intro_DAMMY]
If this comes up, it's a bug. Please[n]report it.

[msg evt_intro_P4HERO]
A second-year at Yasogami-High. Leader[n]of the Investigation Team. ※紹介演出用メッセージ※

[msg evt_intro_P3HERO]
A second-year at Gekkoukan High. Leader[n]of the Shadow-fighting SEES.※紹介演出用メッセージ※

[msg evt_intro_YOSUKE]
A second-year at Yasogami High. Son of[n]the Junes store manager.※紹介演出用メッセージ※

[msg evt_intro_CHIE]
A second-year at Yasogami High. A girl[n]who loves kung fu and meat.※紹介演出用メッセージ※

[msg evt_intro_YUKIKO]
A second-year at Yasogami High. Prim,[n]but with an odd sense of[n]humor.※紹介演出用メッセージ※

[msg evt_intro_RISE]
A first-year at Yasogami High. A teen[n]idol on sabbatical from[n]showbiz.※紹介演出用メッセージ※

[msg evt_intro_KANZI]
A first-year at Yasogami High. An[n]impulsive but faithful young[n]man.※紹介演出用メッセージ※

[msg evt_intro_NAOTO]
A first-year at Yasogami High. The[n]"Detective Prince" who helps[n]police.※紹介演出用メッセージ※

[msg evt_intro_KUMA]
A mysterious creature from the TV world,[n]now living in Yosuke's[n]closet.※紹介演出用メッセージ※

[msg evt_intro_YUKARI]
A second-year at Gekkoukan High, who has[n]a strong will and archery[n]skills.※紹介演出用メッセージ※

[msg evt_intro_JUNPEI]
A second-year at Gekkoukan High. Easily[n]excited, but sets the tone.※紹介演出用メッセージ※

[msg evt_intro_SANADA]
A third-year at Gekkoukan High. The[n]popular captain of the boxing[n]team.※紹介演出用メッセージ※

[msg evt_intro_MITSURU]
A third-year at Gekkoukan High. Student[n]Council President and head of[n]SEES.※紹介演出用メッセージ※

[msg evt_intro_FUKA]
A second-year at Gekkoukan High. A[n]reserved girl with backup[n]abilities.※紹介演出用メッセージ※

[msg evt_intro_AEGIS]
A robotic weapon with Persona abilities[n]and also a second-year at[n]Gekkoukan.※紹介演出用メッセージ※

[msg evt_intro_AMADA]
A 5th-grader at Gekkoukan Elementary. He[n]lost his mother in an[n]accident.※紹介演出用メッセージ※

[msg evt_intro_KOROMARU]
A Shiba Inu with Persona abilities. His[n]owner died in an accident.※紹介演出用メッセージ※

[msg evt_intro_ARAGAKI]
A third-year at Gekkoukan High who is[n]taking time off. Friends with[n]Akihiko.※紹介演出用メッセージ※

[msg evt_intro_P3HERO2]
A second-year at Gekkoukan High. Leader[n]of the Shadow-fighting SEES.※紹介演出用メッセージ※

[msg evt_intro_P5HERO]
ぬを ぼよぽまょぺゆま もれ "どよやまるテ" と'ゆ ぺ れまぼよょぽ- をまぺる ぺろ[n]ひめゎゃもょ でもむめ ぺょぽ ろめま ゅまぺぽまる よみ ろめま はめぺょろよゆ[n]びめもまわまれテ と'ゆ ぼゎるるまょろゅを ゅもわもょむ ぺほよわま ぢぺみま[n]にまほゅぺょぼテ と'わま ほままょ らゎろ よょ らるよほぺろもよょ ぽゎま ろよ ぺ[n]みぺゅれま ぺぼぼゎれぺろもよょ ゅまわまゅまぽ ぺむぺもょれろ ゆまテ

[msg evt_intro_RYUJI]
ぢよぽまょぺゆまト ひやゎゅゅテ ひまぼよょぽ-をまぺる ぺょぽ みよるゆまる ろよら[n]るゎょょまる みよる ろめま ろるぺぼや ろまぺゆテ でよろ-ほゅよよぽまぽデ をまろ[n]ぼよゆらぺれれもよょぺろま ぺょぽ ぼぺるもょむテ のみろまょ るゎれめまれ もょろよ[n]ろめもょむれ ゐもろめよゎろ ろめもょやもょむ みもるれろテ

[msg evt_intro_ANN]
ぢよぽまょぺゆまト はぺょろめまるテ ひまぼよょぽ-をまぺる ぼゅぺれれゆぺろまデ[n]よょま-りゎぺるろまる だゆまるもぼぺょデ ぺょぽ らぺるろ-ろもゆま ゆぺむぺんもょま[n]ゆよぽまゅテ ちるもむめろ ぺょぽ ぼめままるみゎゅ; ぼぺるまれ ぽままらゅを みよる[n]めまる みるもまょぽれテ

[msg evt_intro_MONA]
ぢよぽまょぺゆまト ぬよょぺテ だょ よゎろれらよやまょデ ゆをれろまるもよゎれ ほまもょむ[n]ゐめよ ゐま ゆまろ ゐもろめもょ ろめま ぬまろぺわまるれまテ でま ぼぺょ ろぺやま[n]わぺるもよゎれ みよるゆれデ みるよゆ ぺょ よるぽもょぺるを ほゅぺぼや ぼぺろ ろよ ぺ[n]みゎゅゅ-れもんまぽデ ぽるもわぺほゅま わまめもぼゅまテ

[msg evt_intro_YUSUKE]
ぢよぽまょぺゆまト づよゑテ ひまぼよょぽ-をまぺる れろゎぽまょろ ぺろ なよれまも[n]でもむめ ゐもろめ ゆぺろゎるまデ ぽもれろもょぼろ ぺまれろめまろもぼ[n]れまょれもほもゅもろもまれ; めもれ みゎろゎるま ぺれ ぺょ ぺるろもれろ もれ[n]みよるまれままぺほゅま ろよ ぺゅゅ ゐめよ ゆままろ めもゆテ だ ゎょもりゎま[n]もょぽもわもぽゎぺゅテ

[msg evt_intro_MAKOTO]
ぢよぽまょぺゆまト ばゎままょテ びめもるぽ-をまぺる れまょらぺも ぺょぽ れろゎぽまょろ[n]ぼよゎょぼもゅ らるまれもぽまょろテ だぼぼよゆらゅもれめまぽ もょ ほよろめ[n]ゅもろまるぺるを ぺょぽ ゆぺるろもぺゅ ぺるろれテ ふまるを ゆよるぺゅ ぺょぽ[n]ゎられろぺょぽもょむデ ほゎろ ぺ ほもろ れよぼもぺゅゅを ぺゐやゐぺるぽテ

[msg evt_intro_FUTABA]
ぢよぽまょぺゆまト のるぺぼゅまテ づよれろまる ぽぺゎむめろまる よみ ろめま ちよれれ[n]ゐめよ もれ ぼゎるるまょろゅを らるよわもぽもょむ ゆを ゅよぽむもょむれテ でぺぼやまる[n]まゑろるぺよるぽもょぺもるま ぺょぽ みよるゆまる れめゎろ-もょテ ふまるを れめを[n]ぺるよゎょぽ れろるぺょむまるれテ

[msg evt_intro_HARU]
ぢよぽまょぺゆまト ねよもるテ びめもるぽ-をまぺる ぺろ ひめゎゃもょ でもむめ ぺょぽ[n]れまょらぺも ろよ ろめま るまれろ よみ ろめま むぺょむテ びめま よょゅを[n]ぽぺゎむめろまる よみ ろめま のやゎゆゎるぺ づよよぽれ ぼよるらよるぺろもよょ[n]らるまれもぽまょろテ

[msg evt_intro_AKECHI]
ぢよぽまょぺゆまト ぢるよゐテ だ ろめもるぽ-をまぺる めもむめ れぼめよよゅ[n]れろゎぽまょろ ゐめよ もれ よみろまょ るまみまるるまぽ ろよ ぺれ ろめま "ねまゑろ[n]っまろまぼろもわま はるもょぼま" ぽゎま ろよ めもれ れめぺるら ぽまぽゎぼろもよょれ[n]ぺょぽ みぺれろもぽもよゎれ ぺららまぺるぺょぼまテ

