[msg MSG_000 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 2 3][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 1]Ngh... 夷D吋nde estamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 2 1][f 3 1 1 0 0 2][f 6 1 2 0 0 0]斡Chicos! 斡夷Est茨n bien?![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 3][f 6 1 2 0 0 4]夷Yamagishi...? 夷Entonces estamos de[n]vuelta en el cine de Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 0 4][f 3 1 1 0 0 4]S胤. Parece que fueron arrastrados hasta[n]aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 1][f 3 1 1 0 0 5]El poder de Enlil est茨 fuera de nuestros[n]par茨metros...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 1][f 3 1 1 0 0 6]Pero el poder de esas personas en los[n]cines parece a雨n m茨s fuerte, pero se[n]niegan a escuchar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 6]斡Maldici吋n! 斡夷Por qu姻 diablos no pueden[n]entender su situaci吋n?![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 5 12 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]Pero, 夷esas personas... no parec胤an[n]estar un poco indecisas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 9]S胤. Hab胤a incluso algunas voces que[n]expresaban su deseo por la clase de[n]coraje que esperamos de ellos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 4][f 3 1 1 0 0 10]Pero al final... todos se rindieron y[n]se decidieron esconderse.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 12 1 1][f 3 1 1 0 0 11]Probablemente, est茨n pasando por el[n]mismo problema que yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 12][f 6 1 2 0 0 4]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 13]Ver pel胤culas vac胤as, pero que tus[n]propios recuerdos dolorosos te hacen[n]sentir como renunciar ser胤a m茨s f茨cil...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Eventualmente, incluso llegas al punto[n]donde piensas que perder tu individualidad[n]es la elecci吋n correcta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 6 0 0][f 3 1 1 0 0 15]Estas personas est茨n b茨sicamente sujetas[n]a un control mental... Incluso si[n]habl茨ramos con ellos, qui姻n sabe si[n]nos escuchar胤an.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 16]Pero, yo fui capaz de cambiar para mejor,[n]gracias a que cambiaron las[n]pel胤culas en mi Cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Me hicieron sentir que no deb胤a reprimirme[n]ni temer a mi futuro, y eso[n]deber胤an transmitir las pel胤culas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 1 0][f 3 1 1 0 0 18]Si todos ellos hubieran visto esas[n]pel胤culas, apuesto a que ahora estar胤an[n]pensando diferente.[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]斡ESO ES![f 2 7 1 64 4 0][e]
[f 0 5 65278][f 2 1]Entonces se las mostraremos.[f 2 7 1 64 0 32][e]

[msg MSG_015 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 10 0 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]斡Aah! 斡夷Por qu姻 gritas?![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 12 12 0 4][f 3 1 1 0 0 20]夷Tienes una idea?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 64 1 0 0][f 4 6 69 12 0 1][f 3 1 1 0 0 21]夷Te refieres a las pel胤culas de Hikari?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22][f 6 1 2 0 0 4]夷Quieres mostrarlas en los otros cines?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 4][f 3 1 1 0 0 23]Ah, ya veo, si funciona, las pel胤culas[n]editadas deber胤an cambiar c吋mo piensan,[n]as胤 como con Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 24]Bien, parece l吋gico...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 25][f 6 1 2 0 0 10]斡Espera, espera! Lo siento, pero... 夷De[n]qu姻 estaban hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 2 12 0 1][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 26]No vamos a convencerlos uno por uno, lo haremos a la vez, con la ayuda de las pel胤culas de Hikari.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27][f 6 1 2 0 0 4]夷Esa es la idea no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 4][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 28]S胤. Si ven esas películas y despiertan como Hikari, las puertas de sus cines se abrir茨n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Y entonces, todo querr茨n salir de los[n]cines.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 18 0 0 3][f 3 1 1 0 0 30][f 6 1 2 0 0 4]Pero, 夷c吋mo vamos a reproducir esas[n]pel胤culas en sus pantallas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 0][f 3 1 1 0 0 31][f 6 1 2 0 0 3]Mmm... Normalmente, los cines no muestran[n]la misma pel胤cula a la vez.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 32][f 6 1 2 0 0 4]Si quisi姻ramos reproducir el contenido[n]del cine de Hikari a todos, 夷c吋mo lo[n]har胤amos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_025 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Los proyectores...[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Intercambiaremos las pel胤culas.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Hikari pensar茨 en algo.[f 2 7 1 64 4 32][e]

[msg MSG_026 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 33]Correcto, confirm姻 la ubicaci吋n de cuatro[n]proyectores funcionando en lso[n]alrededores.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 34]Pero, 夷c吋mo los usamos? Los proyectores[n]son m茨quinas que muestran una[n]pel胤cula, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 35][f 6 1 2 0 0 4]夷Te refieres a la pel胤cula que avanza[n]por todo el suelo? 夷Quieres cambiar[n]esa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 36]Espera, 夷podr胤a esa pel胤cula tener algo[n]que ver con esos cuatro proyectores?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 1][f 3 1 1 0 0 37][f 6 1 2 0 0 0]斡Espera, espera! Puede ser aspirante a[n]directora y todo eso, pero 夷no es[n]pedir demasiado?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 38]Oh, tal vez... 夷Y si usamos los cuatro[n]proyectores que vimos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 4][f 3 1 1 0 0 39][f 6 1 2 0 0 4]Espera, 夷tienes una idea?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 2 0 1][f 3 1 1 0 0 40][f 6 1 2 0 0 6]斡Claro! 斡Solo necesitamos usar esos[n]cuatro proyectores para proyectar nuestras[n]propias pel胤culas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 41]Los caminos en el distrito del cine[n]parecen estar hechos de una tira de una[n]pel胤cula larga que va hacia todos[n]los cines.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 0][f 3 1 1 0 0 42]Esa pel胤cula estaba muy oscura. Y no me[n]refiero al balance de color...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 4][f 3 1 1 0 0 43][f 6 1 2 0 0 4]夷Podr胤a estar causando alg雨n efecto[n]negativo en todo los cines?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 44]Creo que la pel胤cula del piso est茨[n]compuesta por los recuerdos m茨s oscuros[n]de todos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 72 12 0 1][f 3 1 1 0 0 45]Es una mezcla de los recuerdos negativos[n]de la gente... Eso me recuerda a[n]los registros ak茨shicos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 4]夷Eh? 夷Qu姻 es eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 4][f 3 1 1 0 0 47]Supuestamente, son los eventos y emociones[n]de todo el mundo escritos...[n]suena similar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 48]Sin embargo, lo que se muestra aqu胤 est茨[n]demasiado sesgado para ser llamado[n]un verdadero registro de cualquier[n]cosa, y mucho menos de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 3][f 3 1 1 0 0 49]Es una mezcla de los recuerdos negativos[n]de la gente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 50]En efecto. Sin embargo, lo que se muestra[n]aqu胤 est茨 demasiado sesgado para[n]ser precisa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 51]Mmhm... Son recuerdos muy editados de[n]los recuerdos de todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 52]Todo lo divertido o alegre en sus vidas[n]fue cortado de la pel胤cula que est茨n[n]viendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 68 12 0 1][f 3 1 1 0 0 53]Mientras que la pel胤cula normalmente[n]partes positivas como negativas, todo[n]lo positivo fue cortado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 6][f 3 1 1 0 0 54]Cuando se trataba de las pel胤culas de[n]Hikari, las cambiamos una por una...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 55]Pero, para cambiar la opini吋n de todos,[n]necesitamos atacar de ra胤z, todas[n]a la vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 56]斡Ya veo! As胤 que todo lo que tenemos que hacer es cambiar la película de los proyectores con las películas de Hikari.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57]Si hacemos eso, seguro que todos...[n][f 1 3 65535][f 1 1][e]

[sel SEL_046 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Ganar茨n coraje.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Dejar茨n sus Cines.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Ellos... Bueno, no lo sabemos.[f 2 7 1 64 6 32][e]

[msg MSG_047 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 58][f 6 1 2 0 0 4]夷Se animar茨n como Hikarin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 4][f 3 1 1 0 0 59][f 6 1 2 0 0 6]斡Bien, tenemos que hacerlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 1][f 3 1 1 0 0 60][f 6 1 2 0 0 6]S胤. 斡Apuesto a que los ayudar茨 a todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 4][f 3 1 1 0 0 61]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 62]Cierto, no hay garant胤a de que cambien[n]reproduciendo las pel胤culas de Hikari.[n]Sin embargo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 63][f 6 1 2 0 0 4]No por eso vamos a dejar de intentarlo,[n]夷no es cierto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 4][f 3 1 1 0 0 64]Por supuesto. Vamos a mostrarles todas[n]las pel胤culas de Hikari, 夷de qu姻[n]servir茨 si no lo hacemos con la actitud[n]correcta?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 65]Entonces est茨 decidido, vamos a cambiar esas pel胤culas negativas con las de Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 4][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 66]Todo lo que tenemos que hacer es cambiar las pel胤culas de los proyectores de antes, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 0 0 1][f 3 1 1 0 0 67]En ese caso, necesitamos tomar las[n]pel胤culas de la vida de Hikari que[n]cambiamos y llevarlas a los proyectores.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 68][f 6 1 2 0 0 6]斡Vamos, a la sala de proyecci吋n![n][f 1 3 65535][f 1 1][e]

