[msg MSG_000 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 82 1 4 1][f 4 6 40 14 1 3][f 3 1 1 0 0 1]Intent姻 convencerme de que no ten胤a m茨s[n]opci吋n que ser quien todos quer胤an que fuera...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2]Y sigo viendo esas pel胤culas[n]distorsionadas para hacerme olvidar qui姻n soy[n]realmente dentro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_2 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 16 1 0][f 3 1 1 0 0 3][f 6 1 2 0 0 6]斡Pero ya no huir姻 de m胤 mismo! Voy a[n]cambiar esta pel胤cula y salir de aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 4 0 0][f 3 1 1 0 0 4]Pap茨... 斡Juro que alg雨n d胤a te enviar姻[n]esa invitaci吋n![n][f 1 3 65535][f 1 1][e]

