[msg MSG_000 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 1][f 6 1 2 0 0 4]Oye, venimos aqu胤 sin pensar, 夷no podríamos quedar atrapados aquí otra vez?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 2]Considerando lo que dijo Enlil, dudo que lo haga...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 3]Las cerraduras representaban el deseo de Hikari de quedarse.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Desde que Hikari decidi吋 irse, Enlil no ha mostrado ninguna intención de detenerla.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 5]Mm. Este lugar parece ser seguro, los cines restantes son el verdadero problema...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]Hasta que sus habitantes obtengan la voluntad de irse, sus puertas permanecer茨n cerradas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 6 0 6][f 3 1 1 0 0 7][f 6 1 2 0 0 10]Me pregunto qu姻 pasar茨 si se quedan aqu胤 para siempre...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Enlil dijo que estar胤an a salvo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 1][f 3 1 1 0 0 9]Pero no est茨n pensando por s胤 mismos. Solo es eso...[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Son totalmente ap茨ticos.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Son como desconexiones mentales...[f 2 7 1 64 0 32][e]

[msg MSG_006 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 2 1][f 3 1 1 0 0 10][f 6 1 2 0 0 6]Pi姻nsalo... 斡Esto no es muy diferente a estar muerto![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 11]Y qui姻n sabe cu茨nta gente está entrando en el distrito de cine mientras hablamos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 6 0 1][f 3 1 1 0 0 12]S胤. Han perdido la voluntad de vivir, como los de los casos de desconexiones mentales...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 4][f 3 1 1 0 0 13][f 6 1 2 0 0 0]夷斡Hay mucha gente aqu胤!? ¿¡Y sus n雨meros siguen creciendo!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 10 0 1][f 3 1 1 0 0 14][f 6 1 2 0 0 6]斡Noooo! ¡Esto una emergencia! Si esto sigue...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15][f 6 1 2 0 0 4]...夷Qu姻 va a pasar?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 16][f 6 1 2 0 0 10]夷Quieres calmarte? 斡Deber胤amos concentrarnos…[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_5 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]...en ordenar la informaci吋n que ya tenemos![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 4][f 3 1 1 0 0 18]T雨 eres el que necesita calmarse.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 1][f 3 1 1 0 0 19]Ese es nuestro Yosuke. Defendiendo su t胤tulo de Príncipe de la Decepci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 20][f 6 1 2 0 0 6]夷斡Podr胤an parar, por favor!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 75 1 0 1][f 4 6 1 12 0 3][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 21]...夷Sabes algo de esto, Margaret?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 6 0 0][f 3 1 1 0 0 22]Bueno, para empezar, las ramificaciones que tendr胤a en el mundo real no pueden pasarse por alto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 6][f 3 1 1 0 0 23]夷Qu姻 pasar胤a?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 24]Eventualmente, esos cines podr胤an invadir el tejido de sus realidades...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018_5 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 25]...O algo de esa naturaleza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 18 0 0 0][f 3 1 1 0 0 26][f 6 1 2 0 0 4]夷El mundo se va a llenar de estos Cines de mierda?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 6][f 3 1 1 0 0 27]Todo el mundo se volver茨 pesimista, muertos por dentro...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 28][f 6 1 2 0 0 3]Esto es un verdadero mont吋n de basura.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 18 2 1][f 3 1 1 0 0 29]No quiero que nadie m茨s pase por lo que pase aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 30]S胤, no lo permitiremos. Cuidaremos nuestro mundo de estos cines.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 6][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 31]Debemos prepararnos, esta podr胤a ser nuestra batalla final. Salgamos cuando estemos listos.[n][f 1 3 65535][f 1 1][e]

