[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 3][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19098]Whew...[n]Parece que todav胤a tenemos muchas[n]maneras de ir. 夷Est茨s bien, Hikari-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 1][f 3 1 1 0 0 0]Estoy bien, gracias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 0][f 3 1 1 0 0 0]Mientras m茨s caminamos en este piso de[n]pel胤cula, m茨s siento que est茨 drenando mi energ胤a.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Hmh... As胤 que esto es lo que Enlil[n]llama "salvaci吋n"[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 6][f 3 1 1 0 0 16086]Si la realidad es demasiado dolorosa[n]para alguien, ella les ofrece la opci吋n de[n]escapar. Supongo que es una especie de[n]salvaci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 6][f 3 1 1 0 0 0]Pero yo no tendr胤a nada que ver con[n]eso. Si s吋lo huyera de mis problemas,[n]ninguno de ellos ser胤a resuelto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 0]Ahora que he visto las versiones[n]editadas de las pel胤culas, estoy de acuerdo contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 12 0 3][f 3 1 1 0 0 11079]Pero hombre, pensar que Nagi-san[n]result吋 ser el malo que caus吋 todo esto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Parec胤a tan agradable, y cari隠osa, y[n]preciosa... 斡Totalmente el tipo m茨s viejo ideal![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ugh... Esa clase de charla me asquerosa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]斡Vamos, es el sue隠o de un hombre! Lo[n]entiendes, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 1][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2018]... 夷Huh? Lo siento, no[n]estaba escuchando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0]夷C吋mo pudiste volarme as胤? 斡No me[n]obligues a invocar la "Ordenanza de Have Pity"![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]夷Qu姻 es una[n]"Ordenanza de la Paz"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 11 1 0 0][f 4 6 15 0 0 4][f 3 1 1 0 0 15046]Puedo recordar a Junpei-san ense隠茨ndome[n]sobre esta ordenanza...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 0]Es un comando que proh胤be a cualquiera[n]tratar a Junpei-san m茨s bajo que un saltamontes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]夷畏l tambi姻n lo hace en este mundo? El[n]Junpei en mi mundo intenta sacar el mismo[n]movimiento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Haha, estoy impresionado con el otro yo![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 21082][f 6 1 2 0 0 9]夷Pero eso no significa que te traten[n]m茨s abajo que un saltamontes en cualquier realidad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 4][f 3 1 1 0 0 0]Creo que finalmente he deducido la[n]verdadera jerarqu胤a de SEES...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 12 0 1][f 3 1 1 0 0 0]Pasando de la charla de saltamontes, la[n]mujer que conoc胤amos como Nagi nos[n]mostr吋 gran bondad mientras estaba en el Cine...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Eso fue todo para enga隠arnos tambi姻n?[n]Parece muy contraintuitivo, considerando[n]la cantidad de apoyo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 0][f 3 1 1 0 0 14513][f 3 1 6 0 0 500]Incluso despu姻s de arruinar sus planes[n]para Hikari-chan, ella no ten胤a[n]exactamente ninguna mala voluntad hacia nosotros...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Para ser honesta, simplemente nos ech吋[n]y nos dej吋 ir en camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 1][f 3 1 1 0 0 0]Tengo la sensaci吋n de que tiene alguna[n]raz吋n para dejarnos ir...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 4][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Yo tambi姻n, no s吋lo eso,[n]creo que ella no estaba mintiendo sobre[n]intentar salvar a Hikari-chan, tampoco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 0][f 3 1 1 0 0 18113]Bueno, sea cual sea su trato, no cambia[n]lo que tenemos que hacer...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]Tenemos que romper esta mierda de[n]"salvaci吋n" que est茨 corriendo aqu胤, para siempre.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 2 2 0 1][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]En ese caso, sabemos[n]cu茨l es nuestra pr吋xima misi吋n...[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Pongamos fin al plan de Enlil.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Liberemos a esa gente.[f 2 7 1 20 2 32][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 21068][f 6 1 2 0 0 6]斡Claro que s胤! 斡Aqu胤 vienen los Ladrones Fantasma![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0]斡El Equipo de Investigaci吋n est茨 en el caso![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 17 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Arf, 斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 0]Koromaru-san dice, "SEES har茨 lo mejor tambi姻n."[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 0 0 1][f 3 1 1 0 0 61172]As胤 que... creo que finalmente entiendo[n]lo que realmente es un compa隠ero, ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 81 12 0 1]No es solo llevarse bien o divertirse[n]con otra persona.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todos tienen un final a su propia[n]historia que quieren ver, y se esfuerzan por[n]alcanzar con todo su coraz吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que cuando miras a tu lado, y hay[n]otros orgullosos luchando para llegar al[n]mismo final que t雨...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]A pesar de que usted podr胤a[n]malinterpretar o no estar de acuerdo con el otro a[n]veces, usted se apoya en el camino ...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 61165][f 4 6 81 2 0 1]Y eso es lo que hace que alguien sea tu compa隠ero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 18 2 4][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]Cierto - todos vamos a[n]luchar juntos, como compa隠eros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Estamos siguiendo nuestras propias[n]creencias hasta el final, igual que t雨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]As胤 es. 斡Espero que todos podamos hacer[n]todo lo posible juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 11032]斡Enfr姻ntalo, 姻ste est茨 en la bolsa![n]Tenemos al Equipo de Investigaci吋n, al[n]Ladrones Fantasma, e incluso SEES en el trabajo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Este grupo es m茨s que impresionante...[n]斡Es una locura! Quiero decir, 夷qu姻 es[n]esto, un espect茨culo de estrellas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]*giggle* Suena como una pel胤cula de crossover.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 4][f 3 1 1 0 0 15124]As胤 que estamos dentro de una pel胤cula[n]cruzada compuesta por compa隠eros[n]humanoides y un saltamontes... Entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Espera un segundo. 斡Aigis me est茨[n]clasificando como un saltamontes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 4][f 3 1 1 0 0 0]Cielos, 夷ya dejar胤as lo del[n]saltamontes? Vamos, salgamos sin este bicho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 11 1 0 0][f 4 6 5 6 0 4][f 3 1 1 0 0 0]No est姻s tan abajo, Grass..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Junpei-kun... 夷Por qu姻 no nos apuramos[n]para que no nos queden atr茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Ni siquiera t雨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 6 0 1][f 3 1 1 0 0 13092]Cielos. 夷Cu茨nto tiempo piensas[n]continuar con esta rutina de subpar?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hemos descansado aqu胤 por mucho tiempo.[n]Vamos a prepararnos y estar en camino![n][f 1 3 65535][f 1 1][e]

