[msg MSG_000 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 87 1 2 9][f 4 6 20 1 0 8][f 4 6 10 10 0 7][f 3 1 1 0 0 1][f 6 1 2 0 0 0]夷En serio? 斡夷Qu姻 hace ESO aqu胤?![n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Es de un rollo diferente.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Es una repetici吋n.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Tal vez se actualiz吋?[f 2 7 1 20 2 32][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 7][f 3 1 1 0 0 2]S胤, debe ser correcto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 7][f 3 1 1 0 0 3][f 6 1 2 0 0 3]Pero cambiamos esta pel胤cula. Incluso[n]si fuera una repetici吋n, no tiene[n]sentido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 7][f 3 1 1 0 0 4][f 6 1 2 0 0 0]Oh, 斡Vamos! 斡夷Despu姻s de todo lo que[n]pasamos?![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 7][f 3 1 1 0 0 5]Creo que esta es muy diferente a la[n]pel胤cula que arreglamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 8][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 6]Desde que cambiamos la conciencia de Hikari, esta pel胤cula debería estar corregida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 7][f 3 1 1 0 0 7]Pero la pel胤cula sigue distorsionada,[n]eh...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Si la dejamos as胤, todos ser茨n forzados[n]a seguir viendo la versi吋n de mierda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 8][f 3 1 1 0 0 9][f 6 1 2 0 0 6]Tenemos que hacer algo, 斡Vamos a arreglar[n]esta tambi姻n![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Madre Computadora]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 7 11 0 0][f 4 6 87 2 2 9][f 3 1 1 0 0 10]No entiendo. Esta pel胤cula representa[n]el paradigma de toda la sociedad[n]humana, y yo soy el paradigma de un[n]gobernante mundial.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Tu negaci吋n a esta popular pel胤cula los[n]convierte en un error en este mundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 7][f 3 1 1 0 0 12][f 6 1 2 0 0 6]No es como si estuvieran disfrutando la[n]pel胤cula. 斡Simplemente, no tienen[n]la opci吋n de ver algo mejor![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 4 0 8][f 3 1 1 0 0 13]Esta mierda no es diferente de lavarles[n]el cerebro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Madre Computadora]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14][f 6 1 3 0 0 2]Esto no es lavar cerebros... es simplemente[n]el sistema adecuado para el[n]mundo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15][f 6 1 3 0 0 2]Si todo el mundo elimina su individualidad[n]y siguen un modelo, las peleas[n]innecesarias dejar茨n de existir.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 4 0 7][f 3 1 1 0 0 16][f 6 1 2 0 0 2]No hagas que suene como si estuvieras[n]haciendo lo correcto. 斡Est茨s forzando[n]tus tonter胤as a los dem茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 4 0 8][f 3 1 1 0 0 17]Tiene raz吋n. A veces, la 雨nica manera[n]de entender algo es a trav姻s de una[n]forma de conflicto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 0 7][f 3 1 1 0 0 18][f 6 1 2 0 0 6]斡Lo que est茨s pidiendo abandonar nuestra[n]capacidad de pensar por nosotros[n]mismos![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Madre Computadora]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 3 0 0 2]Defender el individualismo y alteraci吋n[n]del orden mundial... Claramente son[n]unos herejes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20][f 6 1 3 0 0 2]Son herejes. Irregularidades. Errores.[n]Bugs.[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 7 11 0 0][f 4 6 20 1 0 8]Es nuestra decisi吋n, no la tuya.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Y qu姻 pasa con eso?[f 2 7 1 20 0 32][e]

[msg MSG_018 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 4 0 7][f 3 1 1 0 0 21]斡Es correcto! No importa lo que digas,[n]ser姻 yo misma...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22][f 6 1 2 0 0 6]斡Y eso no pondr茨s cambiarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 4 0 7][f 3 1 1 0 0 23]斡Guau![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Madre Computadora]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24][f 6 1 3 0 0 2]Han sido clasificados como errores[n]fatales... Cualquier otra comunicaci吋n[n]es innecesaria.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 4 100 7][f 3 1 1 0 0 25][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Cuidado! 斡Aqu胤 viene![n][f 1 3 65535][f 1 1][e]

