[msg MSG_000_5]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]＞ｅ５００＿３４５吋ット割り姻ベント フ斡ルムが見せる希望[n][f 1 3 65535][f 1 1][e]

[msg MSG_000 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 0 0][f 3 1 1 0 0 0]He sido... tan malo todo este tiempo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]He abusado de mi poder, creyendo que oprimir a mis ciudadanos beneficiar胤a a toda la sociedad...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Es este poder... no debo confundir el prop吋sito de mi autoridad![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 0 0][f 3 1 1 0 0 0]斡JA, JA, JA![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡El nuevo Kamoshidaman nunca maltratar茨 a un ciudadano de nuevo![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 0]夷A qui姻n le importa si pensamos diferente? Solo tenemos que hablarlo, de coraz吋n a corazón.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 0 0 0][f 3 1 1 0 0 0]Sheesh, todos hablan a la vez. Esta conversaci吋n llegar茨 a ninguna parte...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aunque, es bastante divertido decidir c吋mo hacer las cosas de esta forma.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es agradable tener compa隠eros con los que puedas ser sincero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 0]YO SOY... yo misma.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Soy Ribbon, amante de las flores y de todos en mi vida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 0]Creo que las flores son agradables... Creo que las flores son bonitas... Todo el mundo tiene su opini吋n sobre estas cosas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ser diferente no es un error. Intentar姻 ser soy yo misma...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari De Instituto]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 0]Trat姻 de convencerme de que no ten胤a otra opci吋n, que ser quien todos querían que fuera era lo correcto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y segu胤a viendo esas películas distorsionadas para hacerme olvidar qui姻n era realmente por dentro...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Pero ya no huir姻 de m胤 misma! ¡Voy a cambiar esta película y salir de aquí![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari De Instituto]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 0]Pap茨... 斡Juro que alg雨n d胤a te enviar姻 esa invitaci吋n![n][f 1 3 65535][f 1 1][e]

