[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 6]Maldici吋n... 斡No importa lo que le tiremos,[n]no vamos a ninguna parte![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 6 2 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2]*pant* *pant* Estamos en problemas reales si[n]esto sigue...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Enlil]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 39 2 0 1][f 3 1 1 0 0 3]Pensar que ser胤as tan firme en desafiar tu[n]derrota... Cualquier otra resistencia s吋lo[n]llevar茨 a sus muertes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 1 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 4]Ngh... 斡No hemos terminado todav胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 6 0 0][f 3 1 1 0 0 5]夷Por qu姻 no lo entiendes? Nadie necesita tu[n]ayuda...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]Todo lo que est茨s haciendo es imponer tus[n]propias creencias a mis directores de Cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 7][f 6 1 2 0 0 6]斡Eso no es verdad![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 8][f 6 1 2 0 0 4]夷Hikari-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 16 0][f 3 1 1 0 0 9][f 6 1 2 0 0 6]斡Todos! 斡Escucha![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 16 0][f 3 1 1 0 0 10]He estado negando qui姻n soy realmente durante[n]tanto tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Me asust姻 constantemente de lo que la gente[n]pensaba de m胤, por eso evit姻 desesperadamente[n]que me hirieran siguiendo a otros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 4 16 0][f 3 1 1 0 0 12]Sinceramente, me odiaba por ser as胤. Siempre[n]me sent胤 tan miserable, todo el[n]tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 16 0][f 3 1 1 0 0 13]Pero me dir胤a que no puedo hacer nada al[n]respecto porque soy d姻bil. Fue una excusa[n]que finalmente cre胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 14 16 0][f 3 1 1 0 0 14][f 6 1 2 0 0 4]夷No han hecho lo mismo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hombre Ins吋lito]]
[f 0 5 65278][f 2 1][f 4 6 60 0 0 1][f 3 1 1 0 0 15]Eso... Es como yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hombre L茨nguido]]
[f 0 5 65278][f 2 1][f 4 6 61 0 0 3][f 3 1 1 0 0 16]S胤, todo lo que pod胤a hacer era huir...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Despondent Woman]]
[f 0 5 65278][f 2 1][f 4 6 62 0 0 1][f 3 1 1 0 0 17]Pero... 夷Qu姻 importa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mujer Activa]]
[f 0 5 65278][f 2 1][f 4 6 63 0 0 3][f 3 1 1 0 0 18]No puedo hacer nada al respecto de todos[n]modos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Enlil]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 39 1 0 1][f 3 1 1 0 0 19]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 16 0][f 3 1 1 0 0 20][f 6 1 2 0 0 4]夷Est茨s bien con pel胤culas donde los protagonistas[n]se mantienen d姻biles? 夷D吋nde siguen[n]huyendo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 16 0][f 3 1 1 0 0 21][f 6 1 2 0 0 0]夷Puedes decir, desde lo m茨s profundo de tu[n]coraz吋n, que ver pel胤culas como esas[n]constantemente te hace feliz?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 16 0][f 3 1 1 0 0 22][f 6 1 2 0 0 6]Por favor... 斡Mira esta pel胤cula y recuerda![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 16 0][f 3 1 1 0 0 23][f 6 1 2 0 0 6]Recuerda el tipo de protagonista que quieres[n]estar en tu propia pel胤cula![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 16 0][f 3 1 1 0 0 24][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Nunca olvides, 斡tienes el papel principal en[n]tu propia vida![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hombre Ins吋lito]]
[f 0 5 65278][f 2 1][f 4 6 60 0 0 1][f 3 1 1 0 0 25]Mi vida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Hombre L茨nguido]]
[f 0 5 65278][f 2 1][f 4 6 61 0 0 3][f 3 1 1 0 0 26]Pero, todav胤a...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Mujer Activa]]
[f 0 5 65278][f 2 1][f 4 6 62 0 0 1][f 3 1 1 0 0 27]夷Qu姻 debo hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 1][f 3 1 1 0 0 28]Basta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 10 1 0][f 3 1 1 0 0 29][f 6 1 2 0 0 6]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 30]Los Cines son delicados y f茨cilmente confundidos.[n]No debes molestarlos[n]innecesariamente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 31]Si contin雨as esto, no mostrar姻 misericordia,[n]incluso a una persona impotente como t雨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 32]No soy impotente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 2 0 0][f 3 1 1 0 0 33][f 6 1 2 0 0 4]夷Oh? 夷C吋mo es eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 34][f 6 1 3 0 0 3]Conocer a todos aqu胤 y ver su fuerza guiarlos[n]hacia sus objetivos me dio coraje.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 35]Por eso me acord姻 de la verdadera raz吋n para[n]mi amor al cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 36]Las pel胤culas siempre me ense隠aron lo que[n]m茨s importa...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 2 0][f 3 1 1 0 0 37]Tomar acci吋n da coraje a los dem茨s, entonces[n]ese coraje mueve a雨n m茨s gente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 38][f 6 1 2 0 0 4]夷Y qu姻 importa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39][f 6 1 3 0 0 3]No importa lo peque隠o, incluso mi propio paso[n]adelante debe dar coraje a los dem茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 40]Tampoco es mi coraje. Todo el mundo tiene la[n]capacidad de ser una fuente de fuerza[n]para los dem茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 41][f 6 1 2 0 0 6]斡Por eso nadie es realmente indefenso, todos[n]tenemos el poder de cambiar![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 6][f 3 1 1 0 0 42][f 6 1 2 0 0 7]斡Dile![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 2 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 43]Hikari-chan ha crecido fuerte, y cada 雨ltima[n]persona en los Cines aqu胤 puede hacer[n]lo mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Enlil]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 4][f 4 6 39 10 0 0][f 3 1 1 0 0 44][f 6 1 2 0 0 0]...!?[n][f 1 3 65535][f 1 1][e]

