[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 32 1 3 9][f 4 6 20 1 0 8][f 4 6 22 10 0 7][f 3 1 1 0 0 1][f 6 1 2 0 0 0]夷斡Kamoshidaman!? ¿¡Qu姻 hace 畏l aqu胤!?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]畏l es de un rollo de pel胤cula diferente.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Es una repetici吋n.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Ese es su hermano gemelo.[f 2 7 1 20 2 32][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 7][f 3 1 1 0 0 2]Eso es lo m茨s probable. Es diferente al de la pel胤cula que cambiamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 7][f 3 1 1 0 0 3]No, estoy seguro de que corregimos esa pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 8][f 3 1 1 0 0 4]Es m茨s probable de una pel胤cula diferente a la que cambiamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 7][f 3 1 1 0 0 5][f 6 1 2 0 0 6]夷斡QU畏!? ¡Esto no es gracioso![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 8][f 3 1 1 0 0 6]No, este probablemente es de una pel胤cula diferente a la que cambiamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 12 0 7][f 3 1 1 0 0 7]La primera pel胤cula cambi吋 junto con la conciencia de Hikari...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Pero las personas que est茨n viendo esto ahora todav胤a están atrapadas con esa forma distorsionada forma de pensar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 8][f 3 1 1 0 0 9][f 6 1 2 0 0 3]Ahora, todos estar茨n atrapados viendo esa pel胤cula horrible...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 7][f 3 1 1 0 0 10][f 6 1 2 0 0 6]斡Entonces la cambiaremos las veces que haga falta![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 3 9][f 3 1 1 0 0 11]斡Soy el h姻roe de la justicia, Kamoshidaman![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12][f 6 1 2 0 0 6]斡Ustedes ser茨n castigados, criminales indeseables![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 21 5 0 7][f 4 6 25 6 0 8][f 3 1 1 0 0 13]Indeseables, 夷eh? Eso puede ser verdad en este momento...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 4 1 0][f 3 1 1 0 0 14]Pero sabemos que estamos haciendo lo correcto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 7][f 3 1 1 0 0 15]Estamos devolvi姻ndole la esperanza a los desesperados... Est茨 claro que estamos en lo correcto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 3 0][f 3 1 1 0 0 16]Obedecer a los l胤deres con poder absoluto es lo correcto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17][f 6 1 2 0 0 0]Todos est茨n de acuerdo con mi justicia. 夷斡No deber胤an estarlo tambi姻n!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18][f 6 1 2 0 0 6]斡Para encontrar la verdad, solo tienen que seguirme![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 22 4 0 7][f 3 1 1 0 0 19][f 6 1 2 0 0 4]Entonces, 夷el color negro ser胤a blanco si t雨 lo dijeras? ¿Qu姻 eres, estúpido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 8][f 3 1 1 0 0 20]Incluso un ni隠o sabr胤a que ese razonamiento est茨 completamente equivocado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 3 0][f 3 1 1 0 0 21]斡Nada cambiar茨, no importa lo que digas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]Yo soy el h姻roe del amor y la paz, temido por todos, en otras palabras, 斡yo decido que es correcto![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 32 0 3 0][f 3 1 1 0 0 23][f 6 1 2 0 0 6]Amor y paz: 斡Kamoshidaman! ¡JA, JA, JA, JA, JA, JA![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 0 0 7][f 3 1 1 0 0 24]斡Eh! No podr胤as estar m茨s equivocado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 8][f 3 1 1 0 0 25]De hecho. Los h姻roes deber胤an ayudar a los débiles a enfrentarse a los fuertes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 7][f 3 1 1 0 0 26][f 6 1 2 0 0 6]斡De hecho, es lo opuesto a ti![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 0 3 0][f 3 1 1 0 0 27][f 6 1 2 0 0 6]斡C茨llate! ¡No son más que una pandilla de indeseables rebelándose contra mi sociedad![n][f 1 3 65535][f 1 1][e]

[sel SEL_021 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 8]T雨 eres el indeseable aqu胤.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Ven a buscarnos.[f 2 7 1 20 0 1][e]

[msg MSG_022 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 6 32 2 3 0][f 3 1 1 0 0 28][f 6 1 1 0 0 1][f 6 1 2 0 0 6]Grrrr... 斡Es hora de que entiendas el verdadero poder de la justicia![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 99 7][f 3 1 1 0 0 29][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Aqu胤 viene! Prep茨rate...[n][f 1 3 65535][f 1 1][e]

