[msg MSG_000 [Voz Cansada De Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1][f 6 1 9 0 0 1]夷Qu姻 est茨 pasando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Voz De Mujer Desesperada]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2][f 6 1 9 0 0 1]La pel胤cula cambi吋...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Voz Cansada De Colegiala]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3][f 6 1 9 0 0 1]Vaya...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 4 1 1][f 3 1 1 0 0 4]夷Esto es...? ¿La pel胤cula de Hikari? Pero, ¿c吋mo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 5]Lo siento, cambiamos la pel胤cula en todos tus proyectores.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 6]夷Cu茨ndo...? Admito que me sorprende.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 1 6][f 3 1 1 0 0 7][f 6 1 2 0 0 6]Ya es hora de que te rindas, se隠orita.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 8]斡Estamos dejando salir a todos de los cines! ¡Tu plan fracaso![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 2 0 0][f 3 1 1 0 0 9]*risa* No digas, esas tonter胤as. Solo observen...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10]Aun con su intromisi吋n, no hay ni una sola alma que se est姻 poniendo de su lado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Voz De Mujer]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11][f 6 1 9 0 0 1]P-Pero... todav胤a estoy...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Voz De Estudiante Malhumorado]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12][f 6 1 9 0 0 1]Todav胤a tengo miedo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Voz Ap茨tica De Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13][f 6 1 9 0 0 1]No quiero que me hagan da隠o...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 39 1 0 1][f 4 6 81 6 1 3][f 3 1 1 0 0 14]Oh, no...[n][f 1 3 65535][f 1 1][e]

