[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 12 0 1][f 3 1 1 0 0 23072]Bien, repasemos el plan.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Las personas en los cines de Enlil est茨n[n]viendo pel胤culas superdepresivas,[n]o en otras palabras, "pel胤culas[n]negativas".[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Estas pel胤culas entristecen a las personas[n]con emociones negativas, de forma[n]que todos est茨n encerrados en sus[n]cines.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 4][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]Todos est茨n viendo algo diferente, pero parecen estar conectados de alguna manera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Podr胤amos ver la fuente de la pel胤cula[n]negativa como si fuera la ra胤z de un[n]茨rbol...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y los innumerables cines son las ramas[n]y hojas que se han extendido desde[n]la ra胤z.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 1][f 3 1 1 0 0 27074]Si las pel胤culas negativas son veneno[n]para sus mentes, entonces las pel胤culas[n]positivas deber胤an servir como[n]alimento.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cualquier veneno que fluya desde la ra胤z[n]se propagar胤a a trav姻s de las ramas[n]y hojas, igual que un alimento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Por eso vamos a cambiar estas pel胤culas[n]negativas por la pel胤cula de Hikari,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si hacemos eso, entonces esa gente de[n]en sus cines...[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Entrar茨n en raz吋n.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Ganar茨n coraje.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Saldr茨n de sus Cines.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 28 4 1 1][f 3 1 1 0 0 28068]S胤. Aunque, no hay garant胤a de que[n]suceda...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero supongo, que esta pel胤cula les dar茨[n]el impulso y coraje para cambiar[n]de opini吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 0][f 3 1 1 0 0 0]Todas estas pel胤culas est茨n compuestas[n]por fragmentos de recuerdos donde se[n]le negaba la individualidad a las[n]personas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Debe ser tan agotar, ver solo eso, tanto[n]f胤sica como mentalmente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 0]Aunque la vida puede estar llena de[n]dolor, no todos los recuerdos de una[n]persona son depresivos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 0][f 3 1 1 0 0 5021]Cuando has enfrentado demasiado trauma[n]y dolor, los recuerdos depresivos a[n]menudo cubrir茨n los felices.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Incluso si alguien quiere aferrarse a[n]esos recuerdos divertidos y alegres...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Es por eso que tenemos que apresurarnos[n]y cambiar estas pel胤culas de mierda[n]para hacer que todos despierten![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19077]斡Muy bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Ahora escuchen: hay un total de cuatro[n]proyectores.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Una vez que terminen de configurar toda[n]la pel胤cula, voy a cambiar el[n]interruptor y activarlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 1 1][f 3 1 1 0 0 23106]夷Con qu姻 proyector deber胤amos comenzar?[n]T雨 decides, Joker.[n][f 1 3 65535][f 1 1][e]

