[msg MSG_000]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 1][f 0 6 255 255]夷La individualidad? Esa es la clase de[n]cosa que acaba siendo un dolor para la gente...[n][f 6 1 19 0 0 65535][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 2][f 0 6 255 255]No es como si alguien me viera por[n]qui姻n soy realmente, de todos modos...[n][f 6 1 19 0 0 65535][e]

[msg MSG_002]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 3][f 0 6 255 255]As胤 es... No soy el 雨nico que piensa[n]que... Hay otros como yo...[n][f 6 1 19 0 0 65535][e]

[msg MSG_003]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 4][f 0 6 255 255]Estoy tan cansada de todo este dolor,[n]y... 夷La manera f茨cil de salir es tan mala?[n][f 6 1 19 0 0 65535][e]

[msg MSG_003_5]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 5][f 0 6 255 255]S姻 que no es lo correcto, pero... si no[n]hablo, no me lastimar姻.[n][f 6 1 19 0 0 65535][e]

[msg MSG_009]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 11][f 0 6 255 255]夷Ves? Todos los dem茨s est茨n de acuerdo...[n][f 6 1 19 0 0 65535][e]

[msg MSG_009_5]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 12][f 0 6 255 255]As胤 es como s姻... No estoy haciendo nada malo.[n][f 6 1 19 0 0 65535][e]

[msg MSG_015]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 18][f 0 6 255 255]S胤... Quien quiera salir y tratar puede[n]ir y hacer eso...[n][f 6 1 19 0 0 65535][e]

[msg MSG_015_5]
[f 0 5 65278][f 2 1][f 6 1 18 0 0 19][f 0 6 255 255]Pero yo... No quiero dejar este lugar.[n][f 6 1 19 0 0 65535][e]

