[msg MSG_000 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 10 0 3][f 3 1 1 0 0 1]No...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 6][f 3 1 1 0 0 2][f 6 1 2 0 0 3]夷Por qu姻 la gente del aqu胤 no nos cree?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 2 0 1][f 3 1 1 0 0 3][f 6 1 2 0 0 4]夷Realmente tienen la intenci吋n de liberar a cada una de las personas de este lugar?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Por favor, entiendan, eso es bastante pretencioso de su parte. Despu姻s de todo, esta gente quiere estar aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 12 4 0 0][f 3 1 1 0 0 5]Eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 3 0 0 1]夷No lo ven? Aqu胤 est茨n a salvo, sus acciones no tienen sentido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 39 12 0 0][f 3 1 1 0 0 7]Este mundo que les proveo es la 雨nica manera de salvarlos.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Eso no es verdad.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Seguiremos intent茨ndolo.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 6][f 3 1 1 0 0 8]S胤, decidimos salvarlos... 斡No intentes convencernos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9][f 6 1 2 0 0 6]斡Vamos a demostrarles a todos que tienen la fuerza para hacerlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 6][f 3 1 1 0 0 10]斡S胤! ¡No nos rendiremos tan f茨cilmente, estaríamos manchando nuestro nombre como Ladrones Fantasma![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11][f 6 1 2 0 0 6]斡Vamos a demostrarles a todos que tienen la fuerza para hacerlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 6 0 0][f 3 1 1 0 0 12]Parece que lo que diga solo caer茨 en o胤dos sordos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13]En ese caso, les mostrar姻 las veces que sean necesarias... que tan tontos son.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 0][f 3 1 1 0 0 14][f 6 1 2 0 0 0]夷斡Eek!?[n][f 1 2 40][f 1 1][e]

