[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 6]Maldici吋n... 斡No importa que le lancemos,[n]no logramos nada![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 6 2 0][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 2]*jadeo* *jadeo* Estaremos en problemas si esto sigue...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Enlil]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 39 2 0 1][f 3 1 1 0 0 3]Pensar que no aceptar胤an la derrota...[n]Cualquier resistencia solo llevar茨[n]a sus muertes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 1 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 4]Ngh... 斡A雨n no hemos terminado![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 6 0 0][f 3 1 1 0 0 5]夷Por qu姻 no lo entienden? Nadie necesita[n]tu ayuda...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]Todo lo que hacen es imponer su opini吋n[n]en mis cines.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 7][f 6 1 2 0 0 6]斡E-Eso no es verdad![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 8][f 6 1 2 0 0 4]夷Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 16 0][f 3 1 1 0 0 9][f 6 1 2 0 0 6]斡Escuchen![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 16 0][f 3 1 1 0 0 10]He negado qui姻n soy por tanto tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Siempre tuve miedo de lo que la gente[n]pensar胤a de m胤, por eso evitaba[n]desesperadamente ser lastimada siguiendo[n]a los dem茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 4 16 0][f 3 1 1 0 0 12]Me odiaba por ser as胤. Siempre me sent胤[n]tan miserable...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 16 0][f 3 1 1 0 0 13]Me dec胤a a m胤 misma que no pod胤a hacer[n]nada porque era d姻bil. Hasta que lo[n]cre胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 14 16 0][f 3 1 1 0 0 14][f 6 1 2 0 0 4]夷No han pasado por lo mismo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hombre Ap茨tico]]
[f 0 5 65278][f 2 1][f 4 6 60 0 0 1][f 3 1 1 0 0 15]Eso... Es lo que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hombre Cansado]]
[f 0 5 65278][f 2 1][f 4 6 61 0 0 3][f 3 1 1 0 0 16]S胤, todo lo que pod胤a hacer era huir...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mujer Desesperada]]
[f 0 5 65278][f 2 1][f 4 6 62 0 0 1][f 3 1 1 0 0 17]Pero... 夷Qu姻 importa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mujer Molesta]]
[f 0 5 65278][f 2 1][f 4 6 63 0 0 3][f 3 1 1 0 0 18]No puedo hacer nada al respecto de todos[n]modos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Enlil]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 39 1 0 1][f 3 1 1 0 0 19]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 16 0][f 3 1 1 0 0 20][f 6 1 2 0 0 4]夷Realmente est茨n bien con pel胤culas[n]donde los protagonistas son d姻biles?[n]夷D吋nde solo escapan de los problemas?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 16 0][f 3 1 1 0 0 21][f 6 1 2 0 0 0]夷Pueden aceptar, desde lo m茨s profundo[n]de su coraz吋n, que ver pel胤culas como[n]esas los hace felices?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 16 0][f 3 1 1 0 0 22][f 6 1 2 0 0 6]Por favor... 斡Miren esta pel胤cula y[n]recuerden![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 16 0][f 3 1 1 0 0 23][f 6 1 2 0 0 6]斡Recuerden el tipo de protagonista que[n]quien ser en su propia pel胤cula![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 16 0][f 3 1 1 0 0 24][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Nunca lo olviden, 斡tienen el papel[n]principal de su propia vida![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hombre Ap茨tico]]
[f 0 5 65278][f 2 1][f 4 6 60 0 0 1][f 3 1 1 0 0 25]Mi vida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Hombre Cansado]]
[f 0 5 65278][f 2 1][f 4 6 61 0 0 3][f 3 1 1 0 0 26]Pero, aun as胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Mujer Molesta]]
[f 0 5 65278][f 2 1][f 4 6 62 0 0 1][f 3 1 1 0 0 27]夷Qu姻 deber胤a hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 1][f 3 1 1 0 0 28]Basta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 81 10 1 0][f 3 1 1 0 0 29][f 6 1 2 0 0 6]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 30]Los hu姻spedes de mis cines son delicados[n]y se confunden con facilidad. No[n]los perturbes innecesariamente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 31]Si contin雨as, no mostrar姻 misericordia,[n]incluso con una persona tan indefensa[n]como t雨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 32]No soy indefensa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 2 0 0][f 3 1 1 0 0 33][f 6 1 2 0 0 4]夷Oh? 夷Qu姻 dices?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 34][f 6 1 3 0 0 3]Conocerlos a todos y ver c吋mo su fuerza[n]los gu胤a hacia sus objetivos me dio[n]coraje.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 35]Por eso recuerde la verdadera raz吋n por[n]la que amo el cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 36]Las pel胤culas me ense隠aron lo que m茨s[n]importa...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 2 0][f 3 1 1 0 0 37]Actuar da coraje a otros, ese coraje[n]motiva a las personas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 38][f 6 1 2 0 0 4]夷Y eso qu姻 importa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39][f 6 1 3 0 0 3]No importa que tan peque隠o, un solo paso[n]adelante puede darle coraje a los[n]dem茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 40]No es solo mi coraje, tampoco. Todos[n]tienen la capacidad de darle fuerza a[n]otros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026_5 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 41][f 6 1 2 0 0 6]斡Por eso nadie es indefenso, todos[n]tenemos el poder de cambiar![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 6][f 3 1 1 0 0 42][f 6 1 2 0 0 7]Je, je, je, 斡Ella lo tiene muy claro![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 2 6][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 43]斡Hikari se ha vuelto fuerte, y todas las personas aqu胤 pueden hacer lo mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Enlil]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 4][f 4 6 39 10 0 0][f 3 1 1 0 0 44][f 6 1 2 0 0 0]斡夷...?![n][f 1 3 65535][f 1 1][e]

