[msg MSG_000 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 42 0 0 4][f 4 6 48 0 0 1][f 4 6 34 12 0 3][f 3 1 1 0 0 1]夷A qui姻n le importa si todos tenemos opiniones[n]diferentes? Sólo tenemos que hablarlo,[n]corazón a corazón.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 6 0 0][f 3 1 1 0 0 2]Sheesh, todos hablan de una vez. Esta[n]conversación no va a ninguna parte...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 2 0 0][f 3 1 1 0 0 3]Entonces, de nuevo, es muy divertido decidir[n]cómo hacer las cosas de esta manera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_1 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 4 6 34 18 3 0][f 3 1 1 0 0 4]Realmente es agradable tener compañeros con[n]los que puedes estar abierto.[n][f 1 3 65535][f 1 1][e]

