[msg explain_01_quest_00]
[f 0 5 65278][f 2 1]クエスト００[n]説明文[n][e]

[msg explain_02_quest_00]
[f 0 5 65278][f 2 1]クエスト００[n]説明文[n][e]

[msg explain_03_quest_00]
[f 0 5 65278][f 2 1]クエスト００[n]説明文[n][e]

[msg explain_01_quest_01]
[f 0 5 65278][f 2 1]Derrota a los Basaltos.[n][e]

[msg explain_02_quest_01]
[f 0 5 65278][f 2 1][f 0 1 8]“クエスト１”[f 0 1 5]テストメッセージ2[n][e]

[msg explain_03_quest_01]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 2]completa[f 0 1 0].[n][e]

[msg explain_01_quest_02]
[f 0 5 65278][f 2 1]Alcanza el [f 0 1 8]Destino[f 0 1 5].[n][e]

[msg explain_02_quest_02]
[f 0 5 65278][f 2 1][f 0 1 8]“クエスト２”[f 0 1 5]テストメッセージ2[n][e]

[msg explain_03_quest_02]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 2]completa[f 0 1 0].[n][e]

[msg explain_01_quest_03]
[f 0 5 65278][f 2 1]Derrota a [f 0 1 8]Daring Gigas[f 0 1 5].[n][e]

[msg explain_02_quest_03]
[f 0 5 65278][f 2 1][f 0 1 5]Has completado la proyecci吋n especial.[n][f 0 1 5]Regresa ahora.[n][f 0 1 8]"Informe de proyecci吋n especial completada"[f 0 1 5]Ejecutar[n][e]

[msg explain_03_quest_03]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa[f 0 1 5].[n][e]

[msg explain_01_quest_04]
[f 0 5 65278][f 2 1]Ad姻ntrate m茨s en el [f 0 1 8]3er piso [f 0 1 5]mientras est茨s atento a las [f 0 1 8]c茨maras de vigilancia[f 0 1 5].[n][e]

[msg explain_02_quest_04]
[f 0 5 65278][f 2 1][f 0 1 5]Has completado la proyecci吋n especial.[n][f 0 1 5]Regresa ahora.[n][f 0 1 8]"Informe de proyecci吋n especial completada"[f 0 1 5]Ejecutar[n][e]

[msg explain_03_quest_04]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa[f 0 1 5].[n][e]

[msg explain_01_quest_05]
[f 0 5 65278][f 2 1]Encuentra una tienda con la letra K en su letrero.[n][e]

[msg explain_02_quest_05]
[f 0 5 65278][f 2 1][f 0 1 5]Has completado la proyecci吋n especial.[n][f 0 1 5]Regresa ahora.[n][f 0 1 8]"Informe de proyecci吋n especial completada"[f 0 1 5]Ejecutar[n][e]

[msg explain_03_quest_05]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa[f 0 1 5].[n][e]

[msg explain_01_quest_06]
[f 0 5 65278][f 2 1]Explora el bosque y encuentra la criatura antigua.[n][e]

[msg explain_02_quest_06]
[f 0 5 65278][f 2 1][f 0 1 5]Has completado la proyecci吋n especial.[n][f 0 1 5]Regresa ahora.[n][f 0 1 8]"Informe de proyecci吋n especial completada"[f 0 1 5]Ejecutar[n][e]

[msg explain_03_quest_06]
[f 0 5 65278][f 2 1][f 0 1 5]Esta proyecci吋n especial est茨 [f 0 1 8]completa[f 0 1 5].[n][e]

[msg explain_01_quest_07]
[f 0 5 65278][f 2 1]Derrota al Chico Pollo.[n][e]

[msg explain_02_quest_07]
[f 0 5 65278][f 2 1][f 0 1 5]Has completado la proyecci吋n especial.[n][f 0 1 5]Regresa ahora.[n][f 0 1 8]"Informe de proyecci吋n especial completada"[f 0 1 5]Ejecutar[n][e]

[msg explain_03_quest_07]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa[f 0 1 5].[n][e]

[msg explain_01_quest_08]
[f 0 5 65278][f 2 1]Encuentra al falso oficial de polic胤a en alg雨n lugar de la ciudad.[n][e]

[msg explain_02_quest_08]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_08]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_09]
[f 0 5 65278][f 2 1]Encuentra el grafiti que sea diferente al resto.[n][e]

[msg explain_02_quest_09]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_09]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_10]
[f 0 5 65278][f 2 1]Dir胤gete a un lugar donde puedas pescar.[n][e]

[msg explain_02_quest_10]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_10]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_11]
[f 0 5 65278][f 2 1]Obt姻n el tesoro oculto por el dinosaurio.[n][e]

[msg explain_02_quest_11]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_11]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_12]
[f 0 5 65278][f 2 1]Encuentra una fruta que parezca comestible.[n][e]

[msg explain_02_quest_12]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_12]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_13]
[f 0 5 65278][f 2 1]Re雨ne los ingredientes para hacer palomitas de ma胤z.[n][e]

[msg explain_02_quest_13]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_13]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_14]
[f 0 5 65278][f 2 1]Rescata al beb姻 dinosaurio.[n][e]

[msg explain_02_quest_14]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_14]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_15]
[f 0 5 65278][f 2 1]Descubre qu姻 est茨 da隠ando la jungla.[n][e]

[msg explain_02_quest_15]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_15]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_16]
[f 0 5 65278][f 2 1]Revisa los contenedores en la jungla.[n][e]

[msg explain_02_quest_16]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_16]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_17]
[f 0 5 65278][f 2 1]Pregunta a las personas y busca personal sospechoso.[n][e]

[msg explain_02_quest_17]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_17]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_18]
[f 0 5 65278][f 2 1]Derrota al objetivo.[n][e]

[msg explain_02_quest_18]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_18]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_19]
[f 0 5 65278][f 2 1]Encuentra la tienda grande.[n][e]

[msg explain_02_quest_19]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_19]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_20]
[f 0 5 65278][f 2 1]Captura al T-Rex para investigaci吋n cient胤fica.[n][e]

[msg explain_02_quest_20]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_20]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_01_quest_21]
[f 0 5 65278][f 2 1]Busca cosas que puedan ser comestibles.[n][e]

[msg explain_02_quest_21]
[f 0 5 65278][f 2 1]Busca cosas que puedan ser comestibles.[n][e]

[msg explain_03_quest_21]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_22]
[f 0 5 65278][f 2 1]Derrota al objetivo.[n][e]

[msg explain_02_quest_22]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_22]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_23]
[f 0 5 65278][f 2 1]Derrota a una Sombra con fines de entrenamiento.[n][e]

[msg explain_02_quest_23]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_23]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_24]
[f 0 5 65278][f 2 1]斡Avanza m茨s all茨 de la puerta transfigurada![n][e]

[msg explain_02_quest_24]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_24]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_25]
[f 0 5 65278][f 2 1]斡Derrota a la Sombra y demuestra el poder de los Ladrones Fantasma![n][e]

[msg explain_02_quest_25]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_25]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_26]
[f 0 5 65278][f 2 1]斡Dir胤gete a la pelea y ve qui姻n es la mascota m茨s fuerte![n][e]

[msg explain_02_quest_26]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_26]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_27]
[f 0 5 65278][f 2 1]Encuentra los materiales para la freidora.[n][e]

[msg explain_02_quest_27]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_27]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_28]
[f 0 5 65278][f 2 1]Repara al robot averiado.[n][e]

[msg explain_02_quest_28]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_28]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_29]
[f 0 5 65278][f 2 1]Derrota al FOE gigante.[n][e]

[msg explain_02_quest_29]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_29]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_30]
[f 0 5 65278][f 2 1]Descubre qu姻 hacer con la puerta transfigurada.[n][e]

[msg explain_02_quest_30]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_30]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_31]
[f 0 5 65278][f 2 1]Dir胤gete al bar.[n][e]

[msg explain_02_quest_31]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_31]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_32]
[f 0 5 65278][f 2 1]Deja que las hermosas damas avancen.[n][e]

[msg explain_02_quest_32]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_32]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_33]
[f 0 5 65278][f 2 1]Localiza los Puntos del Tesoro.[n][e]

[msg explain_02_quest_33]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_33]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_34]
[f 0 5 65278][f 2 1]カット予定[n][e]

[msg explain_02_quest_34]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_34]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_35]
[f 0 5 65278][f 2 1]Localiza el Huevo de Pascua.[n][e]

[msg explain_02_quest_35]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_35]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_36]
[f 0 5 65278][f 2 1]Re雨ne las piezas de comunicaci吋n.[n][e]

[msg explain_02_quest_36]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_36]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_37]
[f 0 5 65278][f 2 1]Prueba tu fuerza con el FOE.[n][e]

[msg explain_02_quest_37]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_37]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_38]
[f 0 5 65278][f 2 1]Derrota al FOE.[n][e]

[msg explain_02_quest_38]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_38]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_39]
[f 0 5 65278][f 2 1]Encuentra el objeto perdido de Hikari.[n][e]

[msg explain_02_quest_39]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_39]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_40]
[f 0 5 65278][f 2 1]Obt姻n canela.[n][e]

[msg explain_02_quest_40]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_40]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_41]
[f 0 5 65278][f 2 1]Cumple el deseo de Marie.[n][e]

[msg explain_02_quest_41]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_41]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_42]
[f 0 5 65278][f 2 1]斡Sigue a la mariposa![n][e]

[msg explain_02_quest_42]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_42]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_43]
[f 0 5 65278][f 2 1]Contin雨a adelante.[n][e]

[msg explain_02_quest_43]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_43]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_44]
[f 0 5 65278][f 2 1]カット予定[n][e]

[msg explain_02_quest_44]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_44]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_45]
[f 0 5 65278][f 2 1]Derrota al FOE.[n][e]

[msg explain_02_quest_45]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_45]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_46]
[f 0 5 65278][f 2 1]Lleva contigo lo que encuentres en el calabozo.[n][e]

[msg explain_02_quest_46]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_46]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_47]
[f 0 5 65278][f 2 1]Elimina la nueva amenaza que ha aparecido.[n][e]

[msg explain_02_quest_47]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_47]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_48]
[f 0 5 65278][f 2 1]Elimina la nueva amenaza que ha aparecido.[n][e]

[msg explain_02_quest_48]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_48]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 8]completa.[f 0 1 5][n][e]

[msg explain_01_quest_49]
[f 0 5 65278][f 2 1]Elimina la nueva amenaza que ha aparecido.[n][e]

[msg explain_02_quest_49]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_49]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 2]completa.[f 0 1 0][n][e]

[msg explain_01_quest_50]
[f 0 5 65278][f 2 1]Elimina la nueva amenaza que ha aparecido.[n][e]

[msg explain_02_quest_50]
[f 0 5 65278][f 2 1]Dummy[n][e]

[msg explain_03_quest_50]
[f 0 5 65278][f 2 1]Esta proyecci吋n especial est茨 [f 0 1 2]completa.[f 0 1 0][n][e]

