[msg addeffect_000]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_001]
[f 0 5 65278][f 2 1]St +1[n][e]

[msg addeffect_002]
[f 0 5 65278][f 2 1]St +2[n][e]

[msg addeffect_003]
[f 0 5 65278][f 2 1]St +3[n][e]

[msg addeffect_004]
[f 0 5 65278][f 2 1]St +4[n][e]

[msg addeffect_005]
[f 0 5 65278][f 2 1]St +5[n][e]

[msg addeffect_006]
[f 0 5 65278][f 2 1]En +1[n][e]

[msg addeffect_007]
[f 0 5 65278][f 2 1]En +2[n][e]

[msg addeffect_008]
[f 0 5 65278][f 2 1]En +3[n][e]

[msg addeffect_009]
[f 0 5 65278][f 2 1]En +4[n][e]

[msg addeffect_010]
[f 0 5 65278][f 2 1]En +5[n][e]

[msg addeffect_011]
[f 0 5 65278][f 2 1]Ma +1[n][e]

[msg addeffect_012]
[f 0 5 65278][f 2 1]Ma +2[n][e]

[msg addeffect_013]
[f 0 5 65278][f 2 1]Ma +3[n][e]

[msg addeffect_014]
[f 0 5 65278][f 2 1]Ma +4[n][e]

[msg addeffect_015]
[f 0 5 65278][f 2 1]Ma +5[n][e]

[msg addeffect_016]
[f 0 5 65278][f 2 1]Ag +1[n][e]

[msg addeffect_017]
[f 0 5 65278][f 2 1]Ag +2[n][e]

[msg addeffect_018]
[f 0 5 65278][f 2 1]Ag +3[n][e]

[msg addeffect_019]
[f 0 5 65278][f 2 1]Ag +4[n][e]

[msg addeffect_020]
[f 0 5 65278][f 2 1]Ag +5[n][e]

[msg addeffect_021]
[f 0 5 65278][f 2 1]Lu +1[n][e]

[msg addeffect_022]
[f 0 5 65278][f 2 1]Lu +2[n][e]

[msg addeffect_023]
[f 0 5 65278][f 2 1]Lu +3[n][e]

[msg addeffect_024]
[f 0 5 65278][f 2 1]Lu +4[n][e]

[msg addeffect_025]
[f 0 5 65278][f 2 1]Lu +5[n][e]

[msg addeffect_026]
[f 0 5 65278][f 2 1]+10 HP[n][e]

[msg addeffect_027]
[f 0 5 65278][f 2 1]+20 HP[n][e]

[msg addeffect_028]
[f 0 5 65278][f 2 1]+30 HP[n][e]

[msg addeffect_029]
[f 0 5 65278][f 2 1]+40 HP[n][e]

[msg addeffect_030]
[f 0 5 65278][f 2 1]+50 HP[n][e]

[msg addeffect_031]
[f 0 5 65278][f 2 1]+10 SP[n][e]

[msg addeffect_032]
[f 0 5 65278][f 2 1]+20 SP[n][e]

[msg addeffect_033]
[f 0 5 65278][f 2 1]+30 SP[n][e]

[msg addeffect_034]
[f 0 5 65278][f 2 1]+40 SP[n][e]

[msg addeffect_035]
[f 0 5 65278][f 2 1]+50 SP[n][e]

[msg addeffect_036]
[f 0 5 65278][f 2 1]Low chance of Confusion[n][e]

[msg addeffect_037]
[f 0 5 65278][f 2 1]Posibilidad media de Confusión[n][e]

[msg addeffect_038]
[f 0 5 65278][f 2 1]Alta probabilidad de Confusión[n][e]

[msg addeffect_039]
[f 0 5 65278][f 2 1]Low chance of Poison[n][e]

[msg addeffect_040]
[f 0 5 65278][f 2 1]Posibilidad media de veneno[n][e]

[msg addeffect_041]
[f 0 5 65278][f 2 1]Alta oportunidad de Poison[n][e]

[msg addeffect_042]
[f 0 5 65278][f 2 1]Baja probabilidad de miedo[n][e]

[msg addeffect_043]
[f 0 5 65278][f 2 1]Posibilidad media de Miedo[n][e]

[msg addeffect_044]
[f 0 5 65278][f 2 1]Alta oportunidad de Miedo[n][e]

[msg addeffect_045]
[f 0 5 65278][f 2 1]Baja probabilidad de Furia[n][e]

[msg addeffect_046]
[f 0 5 65278][f 2 1]Posibilidad media de Furia[n][e]

[msg addeffect_047]
[f 0 5 65278][f 2 1]Alta oportunidad de Fury[n][e]

[msg addeffect_048]
[f 0 5 65278][f 2 1]Baja oportunidad de Dizzy[n][e]

[msg addeffect_049]
[f 0 5 65278][f 2 1]Posibilidad media de Dizzy[n][e]

[msg addeffect_050]
[f 0 5 65278][f 2 1]Alta oportunidad de Dizzy[n][e]

[msg addeffect_051]
[f 0 5 65278][f 2 1]Low chance to Exhaust[n][e]

[msg addeffect_052]
[f 0 5 65278][f 2 1]Posibilidad media de agotar[n][e]

[msg addeffect_053]
[f 0 5 65278][f 2 1]Alta oportunidad de agotar[n][e]

[msg addeffect_054]
[f 0 5 65278][f 2 1]Low chance to Age[n][e]

[msg addeffect_055]
[f 0 5 65278][f 2 1]Posibilidad media a la Edad[n][e]

[msg addeffect_056]
[f 0 5 65278][f 2 1]High chance to Age[n][e]

[msg addeffect_057]
[f 0 5 65278][f 2 1]Low chance to Magic Bind[n][e]

[msg addeffect_058]
[f 0 5 65278][f 2 1]Posibilidad media de Magic Bind[n][e]

[msg addeffect_059]
[f 0 5 65278][f 2 1]High chance to Magic Bind[n][e]

[msg addeffect_060]
[f 0 5 65278][f 2 1]Tasa cr胤tica[n][e]

[msg addeffect_061]
[f 0 5 65278][f 2 1]Tasa cr胤tica+[n][e]

[msg addeffect_062]
[f 0 5 65278][f 2 1]Tasa cr胤tica++[n][e]

[msg addeffect_063]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +1[n][e]

[msg addeffect_064]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +2[n][e]

[msg addeffect_065]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +3[n][e]

[msg addeffect_066]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +4[n][e]

[msg addeffect_067]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +5[n][e]

[msg addeffect_068]
[f 0 5 65278][f 2 1]El poder de ataque de fuego aumentó un 25%[n][e]

[msg addeffect_069]
[f 0 5 65278][f 2 1]El poder de ataque de hielo aumentó un 25%[n][e]

[msg addeffect_070]
[f 0 5 65278][f 2 1]El poder de ataque de Elec aumentó un 25%[n][e]

[msg addeffect_071]
[f 0 5 65278][f 2 1]Energ胤a de ataque de viento aumentó un 25%[n][e]

[msg addeffect_072]
[f 0 5 65278][f 2 1]Chance to reflect Phys[n][e]

[msg addeffect_073]
[f 0 5 65278][f 2 1]Chance to reflect Phys+[n][e]

[msg addeffect_074]
[f 0 5 65278][f 2 1]Chance to reflect Phys++[n][e]

[msg addeffect_075]
[f 0 5 65278][f 2 1]Resistencia contra Confusión[n][e]

[msg addeffect_076]
[f 0 5 65278][f 2 1]Resistencia contra el veneno[n][e]

[msg addeffect_077]
[f 0 5 65278][f 2 1]Resistencia contra Miedo[n][e]

[msg addeffect_078]
[f 0 5 65278][f 2 1]Resistencia contra Furia[n][e]

[msg addeffect_079]
[f 0 5 65278][f 2 1]Resistencia contra Dizzy[n][e]

[msg addeffect_080]
[f 0 5 65278][f 2 1]Resistencia contra el agotamiento[n][e]

[msg addeffect_081]
[f 0 5 65278][f 2 1]Resistencia contra el envejecimiento[n][e]

[msg addeffect_082]
[f 0 5 65278][f 2 1]Resistencia contra Cadena m茨gica[n][e]

[msg addeffect_083]
[f 0 5 65278][f 2 1]+Auto-Tarukaja[n][e]

[msg addeffect_084]
[f 0 5 65278][f 2 1]+Auto-Rakukaja[n][e]

[msg addeffect_085]
[f 0 5 65278][f 2 1]+Auto-Sukukaja[n][e]

[msg addeffect_086]
[f 0 5 65278][f 2 1]St +10[n][e]

[msg addeffect_087]
[f 0 5 65278][f 2 1]En +10[n][e]

[msg addeffect_088]
[f 0 5 65278][f 2 1]Ma +10[n][e]

[msg addeffect_089]
[f 0 5 65278][f 2 1]Ag +10[n][e]

[msg addeffect_090]
[f 0 5 65278][f 2 1]Lu +10[n][e]

[msg addeffect_091]
[f 0 5 65278][f 2 1]+100 HP[n][e]

[msg addeffect_092]
[f 0 5 65278][f 2 1]Chance of inflicting all ailments[n][e]

[msg addeffect_093]
[f 0 5 65278][f 2 1]Chance of inflicting all ailments+[n][e]

[msg addeffect_094]
[f 0 5 65278][f 2 1]Chance of inflicting all ailments+[n][e]

[msg addeffect_095]
[f 0 5 65278][f 2 1]Daño f胤sico reducido en 10%[n][e]

[msg addeffect_096]
[f 0 5 65278][f 2 1]Daño f胤sico reducido en 20%[n][e]

[msg addeffect_097]
[f 0 5 65278][f 2 1]Daño f胤sico reducido en 30%[n][e]

[msg addeffect_098]
[f 0 5 65278][f 2 1]Daño al fuego reducido en 10%[n][e]

[msg addeffect_099]
[f 0 5 65278][f 2 1]Daño al fuego reducido en 20%[n][e]

[msg addeffect_100]
[f 0 5 65278][f 2 1]Daño al fuego reducido en un 30%[n][e]

[msg addeffect_101]
[f 0 5 65278][f 2 1]Daño al hielo reducido en un 10%[n][e]

[msg addeffect_102]
[f 0 5 65278][f 2 1]Daño por hielo reducido en 20%[n][e]

[msg addeffect_103]
[f 0 5 65278][f 2 1]Daño por hielo reducido en un 30%[n][e]

[msg addeffect_104]
[f 0 5 65278][f 2 1]Daño al viento reducido en 10%[n][e]

[msg addeffect_105]
[f 0 5 65278][f 2 1]Daño al viento reducido en 20%[n][e]

[msg addeffect_106]
[f 0 5 65278][f 2 1]Daño al viento reducido en 30%[n][e]

[msg addeffect_107]
[f 0 5 65278][f 2 1]Daño de Elec reducido en 10%[n][e]

[msg addeffect_108]
[f 0 5 65278][f 2 1]Daño de Elec reducido en 20%[n][e]

[msg addeffect_109]
[f 0 5 65278][f 2 1]Daño de Elec reducido en 30%[n][e]

[msg addeffect_110]
[f 0 5 65278][f 2 1]Daño m茨gico reducido en 10%[n][e]

[msg addeffect_111]
[f 0 5 65278][f 2 1]Daño m茨gico reducido en 20%[n][e]

[msg addeffect_112]
[f 0 5 65278][f 2 1]Daño m茨gico reducido en 30%[n][e]

[msg addeffect_113]
[f 0 5 65278][f 2 1]Reducir la posibilidad de tropezar[n][e]

[msg addeffect_114]
[f 0 5 65278][f 2 1]Reducir ligeramente la posibilidad de[n]tropezar[n][e]

[msg addeffect_115]
[f 0 5 65278][f 2 1]Gran reducción de la posibilidad de tropiezo[n][e]

[msg addeffect_116]
[f 0 5 65278][f 2 1]Phys dodge up+[n][e]

[msg addeffect_117]
[f 0 5 65278][f 2 1]Phys dodge up[n][e]

[msg addeffect_118]
[f 0 5 65278][f 2 1]Phys dodge up+[n][e]

[msg addeffect_119]
[f 0 5 65278][f 2 1]Dodge de fuego hasta +[n][e]

[msg addeffect_120]
[f 0 5 65278][f 2 1]Fuego dodge up[n][e]

[msg addeffect_121]
[f 0 5 65278][f 2 1]Dodge de fuego hasta ++[n][e]

[msg addeffect_122]
[f 0 5 65278][f 2 1]Hielo dodge up+[n][e]

[msg addeffect_123]
[f 0 5 65278][f 2 1]Ice dodge up[n][e]

[msg addeffect_124]
[f 0 5 65278][f 2 1]Hielo dodge up++[n][e]

[msg addeffect_125]
[f 0 5 65278][f 2 1]Dodge de viento arriba +[n][e]

[msg addeffect_126]
[f 0 5 65278][f 2 1]Viento dódge hacia arriba[n][e]

[msg addeffect_127]
[f 0 5 65278][f 2 1]Dodge de viento arriba ++[n][e]

[msg addeffect_128]
[f 0 5 65278][f 2 1]Elec dodge up+[n][e]

[msg addeffect_129]
[f 0 5 65278][f 2 1]Elec dodge up[n][e]

[msg addeffect_130]
[f 0 5 65278][f 2 1]Elec dodge up+[n][e]

[msg addeffect_131]
[f 0 5 65278][f 2 1]Dodge m茨gico sub+[n][e]

[msg addeffect_132]
[f 0 5 65278][f 2 1]Dodge m茨gico[n][e]

[msg addeffect_133]
[f 0 5 65278][f 2 1]Dodge m茨gico sub++[n][e]

[msg addeffect_134]
[f 0 5 65278][f 2 1]EXP +150%[n][e]

[msg addeffect_135]
[f 0 5 65278][f 2 1]SP a la mitad despu姻s de la batalla[n][e]

[msg addeffect_136]
[f 0 5 65278][f 2 1]Charisma[n][e]

[msg addeffect_137]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_138]
[f 0 5 65278][f 2 1]+100 SP[n][e]

[msg addeffect_139]
[f 0 5 65278][f 2 1]Todas las estad胤sticas +10[n][e]

[msg addeffect_140]
[f 0 5 65278][f 2 1]Gastos de SP triplicados[n][e]

[msg addeffect_141]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_142]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_143]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_144]
[f 0 5 65278][f 2 1]Fuego de Resistencia[n][e]

[msg addeffect_145]
[f 0 5 65278][f 2 1]Hielo resistente[n][e]

[msg addeffect_146]
[f 0 5 65278][f 2 1]Viento resistente[n][e]

[msg addeffect_147]
[f 0 5 65278][f 2 1]Resistir Elec[n][e]

[msg addeffect_148]
[f 0 5 65278][f 2 1]Refleja fuego[n][e]

[msg addeffect_149]
[f 0 5 65278][f 2 1]Reflect Ice[n][e]

[msg addeffect_150]
[f 0 5 65278][f 2 1]Viento reflectante[n][e]

[msg addeffect_151]
[f 0 5 65278][f 2 1]Reflect Elec[n][e]

[msg addeffect_152]
[f 0 5 65278][f 2 1]Fuego de drenaje[n][e]

[msg addeffect_153]
[f 0 5 65278][f 2 1]Dibujo de hielo[n][e]

[msg addeffect_154]
[f 0 5 65278][f 2 1]Viento de drenaje[n][e]

[msg addeffect_155]
[f 0 5 65278][f 2 1]Drain Elec[n][e]

[msg addeffect_156]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_157]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_158]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_159]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_160]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_161]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_162]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_163]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_164]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_165]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_166]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_167]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_168]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_169]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_170]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_171]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_172]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_173]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_174]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_175]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_176]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_177]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_178]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_179]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_180]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_181]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_182]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_183]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_184]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_185]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_186]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_187]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_188]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg addeffect_189]
[f 0 5 65278][f 2 1]Ataque de fuego[n][e]

[msg addeffect_190]
[f 0 5 65278][f 2 1]Ataque de hielo[n][e]

[msg addeffect_191]
[f 0 5 65278][f 2 1]Ataque de viento[n][e]

[msg addeffect_192]
[f 0 5 65278][f 2 1]Elec ataca[n][e]

[msg addeffect_193]
[f 0 5 65278][f 2 1]Daño al fuego[n][e]

[msg addeffect_194]
[f 0 5 65278][f 2 1]Daño por hielo[n][e]

[msg addeffect_195]
[f 0 5 65278][f 2 1]Daño al viento[n][e]

[msg addeffect_196]
[f 0 5 65278][f 2 1]Elec dañó[n][e]

