[msg quest_explain_000]
[f 0 5 65278][f 2 1]クエスト００の概要です。 ダミーメッセージです。[n][e]

[msg quest_explain_001]
[f 0 5 65278][f 2 1]斡Derrota a los Basaltos![n][e]

[msg quest_explain_002]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_003]
[f 0 5 65278][f 2 1]斡Derrota a los Gigas fanfarrones![n][e]

[msg quest_explain_004]
[f 0 5 65278][f 2 1]斡Evita los reflectores![n][e]

[msg quest_explain_005]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_006]
[f 0 5 65278][f 2 1]斡Investiga la misteriosa criatura[n]antigua![n][e]

[msg quest_explain_007]
[f 0 5 65278][f 2 1]Derrota al Chico Pollo[n][e]

[msg quest_explain_008]
[f 0 5 65278][f 2 1]斡Encuentra al falso oficial de polic胤a[n]y hazlo pagar![n][e]

[msg quest_explain_009]
[f 0 5 65278][f 2 1]斡Encuentra el graffiti que es diferente[n]al resto![n][e]

[msg quest_explain_010]
[f 0 5 65278][f 2 1]斡Dir胤gete al lugar de pesca y atrapa[n]uno grande![n][e]

[msg quest_explain_011]
[f 0 5 65278][f 2 1]斡Roba ese tesoro![n][e]

[msg quest_explain_012]
[f 0 5 65278][f 2 1]斡Recoge un helecho de canela![n][e]

[msg quest_explain_013]
[f 0 5 65278][f 2 1]斡Encuentra al culpable![n][e]

[msg quest_explain_014]
[f 0 5 65278][f 2 1]斡Rescata al beb姻 dinosaurio![n][e]

[msg quest_explain_015]
[f 0 5 65278][f 2 1]斡Descubre qu姻 est茨 causando estragos en[n]la jungla![n][e]

[msg quest_explain_016]
[f 0 5 65278][f 2 1]斡Localiza el objeto en cuesti吋n dentro[n]del contenedor![n][e]

[msg quest_explain_017]
[f 0 5 65278][f 2 1]斡Recopila informaci吋n y resuelve el caso![n][e]

[msg quest_explain_018]
[f 0 5 65278][f 2 1]斡Obt姻n tres materiales raros![n][e]

[msg quest_explain_019]
[f 0 5 65278][f 2 1]斡Derrota a Seidoptera![n][e]

[msg quest_explain_020]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_021]
[f 0 5 65278][f 2 1]斡Encuentra ingredientes comestibles en[n]la jungla![n][e]

[msg quest_explain_022]
[f 0 5 65278][f 2 1]斡Derrota a tres Sombras grandes![n][e]

[msg quest_explain_023]
[f 0 5 65278][f 2 1]斡Derrota a cuatro Rampage Drives![n][e]

[msg quest_explain_024]
[f 0 5 65278][f 2 1]斡Supera la tecnolog胤a de 雨ltima generaci吋n[n]de seguridad![n][e]

[msg quest_explain_025]
[f 0 5 65278][f 2 1]斡Destruye al KNS-1000![n][e]

[msg quest_explain_026]
[f 0 5 65278][f 2 1]斡Observa la batalla de las mascotas![n][e]

[msg quest_explain_027]
[f 0 5 65278][f 2 1]斡Encuentra piezas para el equipo de[n]cocina![n][e]

[msg quest_explain_028]
[f 0 5 65278][f 2 1]斡Repara el robot averiado![n][e]

[msg quest_explain_029]
[f 0 5 65278][f 2 1]斡Derrota a dos Tyranniqueens![n][e]

[msg quest_explain_030]
[f 0 5 65278][f 2 1]斡Resuelve el misterio de los dispositivos[n]de teletransporte![n][e]

[msg quest_explain_031]
[f 0 5 65278][f 2 1]斡Localiza el club nocturno![n][e]

[msg quest_explain_032]
[f 0 5 65278][f 2 1]斡Haz que las hermosas damas salven la[n]Kamociudad![n][e]

[msg quest_explain_033]
[f 0 5 65278][f 2 1]斡Busca los puntos del tesoro![n][e]

[msg quest_explain_034]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_035]
[f 0 5 65278][f 2 1]斡Encuentra el huevo de Pascua![n][e]

[msg quest_explain_036]
[f 0 5 65278][f 2 1]斡Re雨ne tres partes raras![n][e]

[msg quest_explain_037]
[f 0 5 65278][f 2 1]斡Dir胤gete al 茨rea de entrenamiento![n][e]

[msg quest_explain_038]
[f 0 5 65278][f 2 1]斡Derrota a SCM-8801![n][e]

[msg quest_explain_039]
[f 0 5 65278][f 2 1]斡Encuentra el objeto perdido de Hikari![n][e]

[msg quest_explain_040]
[f 0 5 65278][f 2 1]斡Obt姻n cuatro frutas![n][e]

[msg quest_explain_041]
[f 0 5 65278][f 2 1]斡Concede el deseo de Marie![n][e]

[msg quest_explain_042]
[f 0 5 65278][f 2 1]斡Persigue a la mariposa en el musical![n][e]

[msg quest_explain_043]
[f 0 5 65278][f 2 1]斡Responde las preguntas y contin雨a![n][e]

[msg quest_explain_044]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_045]
[f 0 5 65278][f 2 1]斡Termina la batalla de los osos![n][e]

[msg quest_explain_046]
[f 0 5 65278][f 2 1]斡Recupera la m雨sica de la pel胤cula![n][e]

[msg quest_explain_047]
[f 0 5 65278][f 2 1]斡Derrota la nueva Sombra en la[n]Kamociudad![n][e]

[msg quest_explain_048]
[f 0 5 65278][f 2 1]斡Derrota a la nueva Sombra en Junessic[n]Land![n][e]

[msg quest_explain_049]
[f 0 5 65278][f 2 1]斡Derrota la nueva Sombra en A.I.G.I.S![n][e]

[msg quest_explain_050]
[f 0 5 65278][f 2 1]斡Derrota la nueva Sombra en Hikari![n][e]

