[msg map_help_001_01]
[f 0 5 65278][f 2 1]Pulsa la herramienta l茨piz, y puedes dibujar[n]paredes en el mapa.[n][e]

[msg map_help_001_02]
[f 0 5 65278][f 2 1]La herramienta borrador elimina las paredes.[n][e]

[msg map_help_002_01]
[f 0 5 65278][f 2 1]Los colores de la herramienta del cepillo en[n]azulejos.[n][e]

[msg map_help_002_02]
[f 0 5 65278][f 2 1]La herramienta de polvo borra los suelos.[n][e]

[msg map_help_002_03]
[f 0 5 65278][f 2 1]Tapping el bot吋n de color y seleccionar un[n]color le permitir茨 cambiar el tinte.[n][e]

[msg map_help_003_01]
[f 0 5 65278][f 2 1]Coloque iconos como puertas en el mapa[n]arrastr茨ndolos.[n][e]

[msg map_help_003_02]
[f 0 5 65278][f 2 1]Para eliminar los iconos en el mapa, arrastrelos[n]a la basura con la herramienta[n]l茨piz.[n][e]

[msg map_help_004_01]
[f 0 5 65278][f 2 1]Pulsa el icono para cambiar el color.[n][e]

[msg map_help_005_01]
[f 0 5 65278][f 2 1]■ It1[n][e]

[msg map_help_006_01]
[f 0 5 65278][f 2 1]Toque el n雨mero de piso mientras que el mapa[n]entero se muestra, y s吋lo ese piso se[n]mostrar茨.[n][e]

[msg map_help_006_02]
[f 0 5 65278][f 2 1]Pulse el bot吋n laberinto para seleccionar el[n]laberinto y el suelo.[n][e]

[msg map_help_007_01]
[f 0 5 65278][f 2 1]Cuando toca la br雨jula en la parte superior[n]izquierda, puede mantener el icono del[n]jugador mirando hacia arriba mientras el[n]mapa cambia la direcci吋n.[n][e]

[msg map_help_007_02]
[f 0 5 65278][f 2 1]Devu姻lvelo a su configuraci吋n predeterminada,[n]tocando la br雨jula de nuevo.[n][e]

[msg map_help_008_01]
[f 0 5 65278][f 2 1]Si cometes un error, pulsa Undo para cancelar[n]la 雨ltima acci吋n.[n][e]

[msg map_help_009_01]
[f 0 5 65278][f 2 1]Utilice Auto Pilot para moverse[n]autom茨ticamente.[n][e]

[msg map_help_009_02]
[f 0 5 65278][f 2 1]Dibuja la ruta que te gustar胤a ir con el[n]bol胤grafo de ruta en el men雨 Auto Pilot.[n][e]

[msg map_help_009_03]
[f 0 5 65278][f 2 1]Viaja por la ruta que dibuj吋 y pulsa el bot吋n[n]de movimiento para comenzar a moverse[n]autom茨ticamente.[n][e]

[msg map_help_009_04]
[f 0 5 65278][f 2 1]Al tocar la l胤nea que fue dibujada por el[n]bol胤grafo de ruta se puede ir hacia atr茨s.[n][e]

[msg map_help_009_05]
[f 0 5 65278][f 2 1]Utilice el borrador de la ruta para eliminar[n]la l胤nea Piloto Auto. Borrarlo desde el[n]final de la l胤nea.[n][e]

[msg map_help_010_01]
[f 0 5 65278][f 2 1]Arrastre los iconos en la paleta gratis para[n]guardar sus iconos favoritos.[n][e]

[msg map_help_010_02]
[f 0 5 65278][f 2 1]Eliminar los iconos no deseados de la paleta[n]libre arrastrandolos a la basura.[n][e]

[msg map_help_011_01]
[f 0 5 65278][f 2 1]Durante ex茨menes especiales, tendr茨 una paleta[n]especial de detecci吋n. Tendr茨 iconos[n]que puedes colocar solo durante las[n]proyecciones.[n][e]

[msg map_help_011_02]
[f 0 5 65278][f 2 1]Sin embargo, no se pueden colocar iconos de[n]detecci吋n especiales encima de otros que[n]fueron colocados en un momento[n]diferente.[n][e]

