[msg quest_story_000]
[f 0 5 65278][f 2 1]Нельногольныеннные. неннныенныеннныенные[n][e]

[msg quest_story_001]
[f 0 5 65278][f 2 1]Sinopsis La ciudad de Kamo, liberada de[n]la regla de hierro de su tirano, sigue[n]luchando con una niebla del mal que todo[n]el mundo est茨 vigilando las mentes del pueblo. 斡Lloran por la verdadera paz![n][e]

[msg quest_story_002]
[f 0 5 65278][f 2 1][e]

[msg quest_story_003]
[f 0 5 65278][f 2 1]Sinopsis Una banda de hombres machos[n]est茨 aterrorizando a la gente de la 2a[n]Avenida de Kamo City. 夷Cu茨ndo vendr茨 un[n]hombre de verdad y pondr茨 una parada a tal machismo de cabeza huesca?[n][e]

[msg quest_story_004]
[f 0 5 65278][f 2 1]Sinopsis 斡Corre por la paz! 斡Corre por[n]amor! Corran por la ciudad mientras los[n]reflectores intentan mantenerse al d胤a[n]contigo. 斡En este r茨pido thriller de acci吋n nacer茨 una leyenda![n][e]

[msg quest_story_005]
[f 0 5 65278][f 2 1]005 ненный нельный[n][e]

[msg quest_story_006]
[f 0 5 65278][f 2 1]Sinopsis En una tierra donde los[n]dinosaurios han resucitado de nuevo, 夷hay[n]tambi姻n revuelos de vida en las aguas[n]profundas y oscuras? Esta es la Tierra Junesic, donde la historia est茨 escrita de nuevo...[n][e]

[msg quest_story_007]
[f 0 5 65278][f 2 1]Sinopsis El Ni隠o Chicken es el tutor[n]autoproclamado de Kamo City. Patrulla de[n]d胤a y de noche, pero es tan draconiano[n]que est茨 aplastando la misma paz en la que cree.[n][e]

[msg quest_story_008]
[f 0 5 65278][f 2 1]Sinopsis 夷Podr胤a ser el culpable un[n]polic胤a? 斡No puede ser! Pero Sombras se[n]esconden en la ciudad de Kamo, incluso[n]entre sus fuerzas de seguridad. 夷Se resolver茨 el caso?[n][e]

[msg quest_story_009]
[f 0 5 65278][f 2 1]Sinopsis Graffiti es el grito del alma.[n]夷Escuchas tu coraz吋n? 夷O te est茨s[n]mintiendo todos los d胤as? Encuentra tu[n]verdadera voz, deja que tu alma grite![n][e]

[msg quest_story_010]
[f 0 5 65278][f 2 1]Sinopsis Una onda en el agua, un[n]aliento del viento... 斡Y de repente, estall吋[n]una batalla 姻pica de vida y muerte! S胤,[n]este es el mundo dram茨tico de... la pesca![n][e]

[msg quest_story_011]
[f 0 5 65278][f 2 1]Sinopsis Dos tesoros legendarios,[n]pasados por generaciones, brillando en la[n]noche m茨s oscura. 夷Pueden ser robados bajo[n]los ojos vigilantes de dos Pterosaurios?[n][e]

[msg quest_story_012]
[f 0 5 65278][f 2 1]Sinopsis Cinnamon, el m茨s antiguo y el[n]m茨s fuerte de las especias. Se dice que[n]se deriva de una planta conocida como[n]Cinnamon Fern, que crece s吋lo en un bosque antiguo...[n][e]

[msg quest_story_013]
[f 0 5 65278][f 2 1]Sinopsis La tierra lleva mucho tiempo[n]atendida por dinosaurios gen姻ticamente[n]dise隠ados, pero de repente las plantas[n]mutantes han brotado en todas partes. 夷Qu姻 significa esto?[n][e]

[msg quest_story_014]
[f 0 5 65278][f 2 1]Sinopsis Incluso en una tierra[n]artificial, los beb姻s son algo natural. 斡Y[n]aunque sea un dinosaurio, un beb姻 separado de[n]sus padres es algo asustado![n][e]

[msg quest_story_015]
[f 0 5 65278][f 2 1]Synopsis Junessic Land es un lugar[n]gobernado por el principio de supervivencia[n]del m茨s apropiado. 夷Eres uno de los m茨s aptos?[n][e]

[msg quest_story_016]
[f 0 5 65278][f 2 1]Synopsis Humans left Junessic Land long[n]ago, but their abandoned technology[n]remains... 夷C吋mo pueden los dinosaurios[n]enfrentar lo que los humanos dejaron atr茨s?[n][e]

[msg quest_story_017]
[f 0 5 65278][f 2 1]Sinopsis Tiempo para que seas un[n]detective inteligente en Kamo City.[n]斡Entrevistar testigos! 斡Comb las escenas del[n]crimen! 斡Resolver el misterio en una dram茨tica revelaci吋n al final de la pel胤cula![n][e]

[msg quest_story_018]
[f 0 5 65278][f 2 1]Sinopsis 夷Tienes algo que sea precioso[n]para ti? Claro que s胤. 斡Pelea por ello![n]Y vea esta pel胤cula, donde todos hacen[n]lo mismo. 斡Las apuestas no podr胤an ser m茨s altas![n][e]

[msg quest_story_019]
[f 0 5 65278][f 2 1]Sinopsis Guerreros, ensamblad! En esta[n]isla antigua haz tu 雨ltimo estrado,[n]斡aunque grandes bestias torren sobre ti![n]Usted no debe falsificar (especialmente en una pel胤cula esta 姻pica).[n][e]

[msg quest_story_020]
[f 0 5 65278][f 2 1][e]

[msg quest_story_021]
[f 0 5 65278][f 2 1]Sinopsis 斡Busca ingredientes en la[n]selva y crea el plato perfecto! Los[n]programas normales de cocina no son nada[n]comparados con esto, un show de cocina en naturaleza imperdonable...[n][e]

[msg quest_story_022]
[f 0 5 65278][f 2 1]Sinopsis No te pierdas esta intensa[n]batalla con los amenazadores soldados de[n]oro de "A.I.G.I.S."! 斡Este espect茨culo de[n]una pel胤cula de acci吋n te golpear茨 el cerebro en la boca![n][e]

[msg quest_story_023]
[f 0 5 65278][f 2 1]Sinopsis La batalla final con los[n]habitantes de "A.I.G.I.S."! Hombre contra[n]m茨quina... 夷Qui姻n triunfar茨 sobre el otro?[n][e]

[msg quest_story_024]
[f 0 5 65278][f 2 1]Sinopsis "A.I.G.I.S." tiene nuevos[n]equipos de seguridad en esta proyecci吋n[n]especial. 夷Qui姻n ser茨 el primero en sabotearlo todo?[n][e]

[msg quest_story_025]
[f 0 5 65278][f 2 1]Sinopsis Solicitud de misi吋n de[n]emergencia! Localice el KNS-1000 dentro de[n]"A.I.G.I.S.", y pruebe su mettle![n][e]

[msg quest_story_026]
[f 0 5 65278][f 2 1]Sinopsis 斡La caza masiva de tesoros[n]est茨 ocurriendo en la selva! 斡Compite para[n]encontrar el bo吋n perfecto buscado por[n]un investigador! 夷Es el premio final una de las riquezas o del amor?[n][e]

[msg quest_story_027]
[f 0 5 65278][f 2 1]Sinopsis La basura de un hombre es el[n]tesoro de otro... como en esta pel胤cula,[n]que est茨 llena de piezas de m茨quina.[n]夷Qu姻 preciosa gema encontrar茨s entre los escombros?[n][e]

[msg quest_story_028]
[f 0 5 65278][f 2 1]Sinopsis 夷Listo para abordar una de las[n]mayores cuestiones de ciencia ficci吋n?[n]Entonces entra en esta prueba especial,[n]y preg雨ntate... si las m茨quinas pueden amar.[n][e]

[msg quest_story_029]
[f 0 5 65278][f 2 1]Sinopsis 斡Una prueba de fuerza contra[n]los carn胤voros m茨s fuertes, terminando en[n]una batalla final clim茨tica! Dile que[n]te quite sus patas apestosas.[n][e]

[msg quest_story_030]
[f 0 5 65278][f 2 1]Sinopsis Navegue una compleja red de[n]caminos para llegar a su destino! 夷Est茨s[n]preparado para un desaf胤o de l吋gica y[n]ingenios, o te perder茨s en un laberinto cinematogr茨fico?[n][e]

[msg quest_story_031]
[f 0 5 65278][f 2 1]Sinopsis Clubes nocturnos... Lugares[n]oscuros de sobrecarga sensorial que a雨n[n]requieren que interpretes un mont吋n de[n]cues sociales. No es f茨cil... 夷Crees que puedes hacerlo?[n][e]

[msg quest_story_032]
[f 0 5 65278][f 2 1]Sinopsis Kamo City ha perdido a su[n]h姻roe. 夷A qui姻n se convertir茨 su gente? Tal[n]vez a nadie m茨s que a USTED. Si te[n]demuestras un h姻roe, eso es. 斡Tiempo para tu papel protag吋nico![n][e]

[msg quest_story_033]
[f 0 5 65278][f 2 1]Sinopsis Treasure-hunters quer胤a. 夷Cu茨l[n]es la vieja rima? 夷Los interruptores[n]obtienen riquezas? 夷No? Bueno, eso es[n]exactamente lo que opera los interruptores en esta pel胤cula te conseguir茨![n][e]

[msg quest_story_034]
[f 0 5 65278][f 2 1][e]

[msg quest_story_035]
[f 0 5 65278][f 2 1]Sinopsis Una historia misteriosa donde[n]cazas huevos de Pascua s吋lo un verdadero[n]fan puede encontrar. No te preocupes,[n]esto no es una persecuci吋n de ganso salvaje... a menos que te refieres a la que pone huevos de oro![n][e]

[msg quest_story_036]
[f 0 5 65278][f 2 1]Sinopsis Una guerra se ha roto. 夷Y son[n]soldados de pie contra tanques? 夷C吋mo es[n]que esta infanter胤a de coraz吋n de le吋n[n]alguna vez vencer茨 las probabilidades... a menos que aparezca un h姻roe como t雨![n][e]

[msg quest_story_037]
[f 0 5 65278][f 2 1]Sinopsis El Sr. Bear le espera, en el[n]bosque. 斡Arriba tus nervios y enfrenta a[n]este gran enemigo! No lo pienses. 斡Si姻ntate![n][e]

[msg quest_story_038]
[f 0 5 65278][f 2 1]Sinopsis 斡Convierte a los verdugos[n]robot en chatarra! 夷No saben que no son m茨s[n]que jugadores en esta historia, s吋lo[n]corriendo en pedazos y bytes?[n][e]

[msg quest_story_039]
[f 0 5 65278][f 2 1]Sinopsis 斡La dee la da! 夷Listo para una[n]pel胤cula musical? 斡La da dee la! Ser茨[n]divertido. 斡La da- dum da! La vida es un[n]cabaret, viejo amigo.[n][e]

[msg quest_story_040]
[f 0 5 65278][f 2 1]斡Sinopsis Songs! 斡Comida! 斡Amor![n]夷Vendido en esta pel胤cula?[n][e]

[msg quest_story_041]
[f 0 5 65278][f 2 1]Sinopsis No hay necesidad de sentir[n]verguenza. Sigue y habla tu mente. Dispara.[n]Canta. Sigue tus pasiones. 斡Eso es lo[n]que hacen en esta pel胤cula, y t雨 tambi姻n puedes![n][e]

[msg quest_story_042]
[f 0 5 65278][f 2 1]Sinopsis 夷Conoces el secreto de las[n]mariposas? Te atraer茨n a dormir... con sus[n]colores, sus bailes y su gracia.[n]Cuidado... para que no detengan su magia.[n][e]

[msg quest_story_043]
[f 0 5 65278][f 2 1]Sinopsis La vida est茨 llena de[n]opciones, y esta pel胤cula refleja que al ser una[n]historia de aventura propia. Pero por[n]supuesto, 夷no est茨s viviendo uno de esos?[n][e]

[msg quest_story_044]
[f 0 5 65278][f 2 1][e]

[msg quest_story_045]
[f 0 5 65278][f 2 1]斡Estreno mundial de sinopsis! Es hora[n]de poner a desnudo qui姻n es el m茨s sabio[n]de todos ellos. Todos los a隠os de osos[n]han llevado a esto, la 雨nica batalla decisiva...[n][e]

[msg quest_story_046]
[f 0 5 65278][f 2 1]斡Ordenes de emergencia! 斡Traigan el[n]tesoro posthaste! Esta pel胤cula de acci吋n[n]clim茨tica, de alta velocidad, ladrona[n]fantasma te tendr茨 al borde de tu asiento![n][e]

[msg quest_story_047]
[f 0 5 65278][f 2 1]Sinopsis Prueba especial de emergencia![n]斡El terror agarra a Kamo City! 斡Derrota[n]la amenaza donde se ha apoderado, en la[n]plaza Kamoshida![n][e]

[msg quest_story_048]
[f 0 5 65278][f 2 1]Sinopsis Prueba especial de emergencia![n]El problema revuelva en la Tierra[n]Junessic. 斡Derrota la nueva amenaza que[n]acecha en la tierra de los dinosaurios![n][e]

[msg quest_story_049]
[f 0 5 65278][f 2 1]Sinopsis Prueba especial de emergencia![n]斡Un enemigo poderoso ha aparecido en[n]A.I.G.I.S. y tomado el control de la sala![n]斡Debes derrotarlo![n][e]

[msg quest_story_050]
[f 0 5 65278][f 2 1]Sinopsis Prueba especial de emergencia![n]斡Todo Hikari es ajeno, porque lo[n]impensable ha ocurrido! S胤, un enemigo ha[n]aparecido... 斡y se ha apoderado del foco del escenario central![n][e]

