[msg quest_story_000]
[f 0 5 65278][f 2 1]クエスト００のあらすじです。[n]ダミーメッセージです。[n]ダミーメッセージです。[n][e]

[msg quest_story_001]
[f 0 5 65278][f 2 1]Sinopsis[n]La Kamociudad, liberada del r姻gimen de su tirano, todav胤a lucha contra una niebla de maldad que est茨 corrompiendo las mentes de la gente en todo el pa胤s. 斡Gritan por una verdadera paz![n][e]

[msg quest_story_002]
[f 0 5 65278][f 2 1]【あらすじ】[n]　カット予定[n][e]

[msg quest_story_003]
[f 0 5 65278][f 2 1]Sinopsis[n]Una pandilla de hombres machos est茨 aterrorizando a la gente de la 2da Avenida de la Kamociudad. 夷Cu茨ndo vendr茨 un verdadero hombre a poner fin a semejante machismo obtuso?[n][e]

[msg quest_story_004]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Corre por la paz! 斡Corre por el amor! Corre por la ciudad mientras los reflectores ardientes intentan seguirte. 斡En este trepidante thriller de acci吋n, nacer茨 una leyenda![n][e]

[msg quest_story_005]
[f 0 5 65278][f 2 1]005 あらすじ[n]　カット予定[n][e]

[msg quest_story_006]
[f 0 5 65278][f 2 1]Sinopsis[n]En una tierra donde los dinosaurios han resurgido, 夷hay tambi姻n movimientos de vida en las aguas profundas y oscuras? Esto es Junessic Land, donde la historia se reescribe de nuevo...[n][e]

[msg quest_story_007]
[f 0 5 65278][f 2 1]Sinopsis[n]El Chico Pollo es el autoproclamado guardi茨n de la Kamociudad. Patrulla d胤a y noche, pero es tan draconiano que est茨 aplastando la misma paz en la que cree.[n][e]

[msg quest_story_008]
[f 0 5 65278][f 2 1]Sinopsis[n]夷Podr胤a el culpable ser un polic胤a? 斡No puede ser! Pero las Sombras acechan en todas partes en la Kamociudad, incluso entre sus fuerzas del orden. 夷Se resolver茨 el caso?[n][e]

[msg quest_story_009]
[f 0 5 65278][f 2 1]Sinopsis[n]El graffiti es el grito del alma. T雨, 夷escuchas a tu coraz吋n? 夷O te est茨s mintiendo a ti mismo todos los d胤as? Encuentra tu voz verdadera, 斡deja que tu alma grite![n][e]

[msg quest_story_010]
[f 0 5 65278][f 2 1]Sinopsis[n]Una onda en el agua, un suspiro del Viento... 斡Y de repente, estalla una 姻pica batalla entre la vida y la muerte! S胤, este es el mundo dram茨tico de... 斡la pesca![n][e]

[msg quest_story_011]
[f 0 5 65278][f 2 1]Sinopsis[n]Dos tesoros legendarios, transmitidos de generaci吋n en generaci吋n, brillando en la noche m茨s oscura. 夷Pueden ser robados bajo la atenta mirada de dos Pterosaurios?[n][e]

[msg quest_story_012]
[f 0 5 65278][f 2 1]Sinopsis[n]La canela, la especia m茨s antigua y real. Se dice que proviene de una planta conocida como helecho de canela, que crece solo en un bosque antiguo...[n][e]

[msg quest_story_013]
[f 0 5 65278][f 2 1]Sinopsis[n]La tierra ha sido cuidada durante mucho tiempo por dinosaurios gen姻ticamente modificados, pero de repente han brotado plantas mutantes en todas partes. 夷Qu姻 podr胤a significar esto?[n][e]

[msg quest_story_014]
[f 0 5 65278][f 2 1]Sinopsis[n]Incluso en una tierra artificial, los beb姻s son una cosa natural. 斡Y aunque sea un dinosaurio, un beb姻 separado de sus padres es una criatura asustada![n][e]

[msg quest_story_015]
[f 0 5 65278][f 2 1]Sinopsis[n]Junessic Land es un lugar gobernado por el principio de la supervivencia del m茨s apto. 夷Eres uno de los m茨s aptos?[n][e]

[msg quest_story_016]
[f 0 5 65278][f 2 1]Sinopsis[n]Los humanos abandonaron Junessic Land hace mucho tiempo, pero su tecnolog胤a abandonada permanece... 夷C吋mo pueden los dinosaurios enfrentar lo que los humanos dejaron atr茨s?[n][e]

[msg quest_story_017]
[f 0 5 65278][f 2 1]Sinopsis[n]Es hora de que seas un astuto detective en la Kamociudad. 斡Entrevista a los testigos! 斡Recorre las escenas del crimen! 斡Resuelve el misterio en un emocionante revelaci吋n al final de la pel胤cula![n][e]

[msg quest_story_018]
[f 0 5 65278][f 2 1]Sinopsis[n]夷Tienes algo que sea precioso para ti? Por supuesto que s胤. 斡As胤 que lucha por ello! Y mira esta pel胤cula, donde todos hacen lo mismo. 斡Las apuestas no podr胤an ser m茨s altas![n][e]

[msg quest_story_019]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Guerreros, re雨nanse! En esta isla antigua, hagan su 雨ltima defensa, 斡aunque las grandes bestias se eleven sobre ustedes! No deben titubear (especialmente en una pel胤cula tan 姻pica como esta).[n][e]

[msg quest_story_020]
[f 0 5 65278][f 2 1]【あらすじ】[n]　カット予定[n][e]

[msg quest_story_021]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Busca ingredientes en la jungla y crea el plato perfecto! Los programas de cocina normales no se comparan con esto, un programa de cocina en la naturaleza implacable...[n][e]

[msg quest_story_022]
[f 0 5 65278][f 2 1]Sinopsis[n]斡No te pierdas esta intensa batalla con los amenazadores soldados dorados de "A.I.G.I.S."! 斡Esta pel胤cula de acci吋n espectacular te dejar茨 el cerebro hecho papilla![n][e]

[msg quest_story_023]
[f 0 5 65278][f 2 1]Sinopsis[n]La batalla final con los habitantes de "A.I.G.I.S." 斡Hombre contra m茨quina... Qui姻n triunfar茨 finalmente sobre el otro?[n][e]

[msg quest_story_024]
[f 0 5 65278][f 2 1]Sinopsis[n]En esta proyecci吋n especial, "A.I.G.I.S." tiene nuevo equipo de seguridad. 夷Qui姻n ser茨 el primero en sabotearlo todo?[n][e]

[msg quest_story_025]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Solicitud de misi吋n de emergencia! 斡Localiza el KNS-1000 dentro de "A.I.G.I.S." y pon a prueba tu determinaci吋n![n][e]

[msg quest_story_026]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Una gran b雨squeda del tesoro est茨 ocurriendo en la jungla! 斡Compite para encontrar el bot胤n perfecto buscado por un investigador! 夷Es el premio final uno de riquezas o de amor?[n][e]

[msg quest_story_027]
[f 0 5 65278][f 2 1]Sinopsis[n]"La basura de uno es el tesoro de otro"... como en esta pel胤cula, que est茨 llena de piezas de m茨quina. 夷Qu姻 joya preciosa encontrar茨s entre los escombros?[n][e]

[msg quest_story_028]
[f 0 5 65278][f 2 1]Sinopsis[n]夷Listo para abordar una de las preguntas m茨s grandes de la ciencia ficci吋n de todos los tiempos? Luego, entra en esta proyecci吋n especial y preg雨ntate... si las m茨quinas pueden amar.[n][e]

[msg quest_story_029]
[f 0 5 65278][f 2 1]Sinopsis[n]Una prueba de fuerza contra el m茨s fuerte de los carn胤voros, 斡que termina en una batalla final clim茨tica! Dile que quite sus malditas garras de encima de ti.[n][e]

[msg quest_story_030]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Navega por una compleja red de caminos para llegar a tu destino! 夷Est茨s preparado para un desaf胤o de l吋gica y astucia, o te perder茨s en un laberinto cinematogr茨fico?[n][e]

[msg quest_story_031]
[f 0 5 65278][f 2 1]Sinopsis[n]Discotecas... Lugares oscuros de sobrecarga sensorial que a雨n requieren que interpretes un mont吋n de se隠ales sociales. No es f茨cil... 夷Crees que puedes hacerlo?[n][e]

[msg quest_story_032]
[f 0 5 65278][f 2 1]Sinopsis[n]La Kamociudad ha perdido a su h姻roe. 夷A qui姻n acudir茨n sus habitantes? Tal vez a nadie m茨s que a TI. Si demuestras ser un h姻roe, claro. 斡Es hora de tu papel protag吋nico![n][e]

[msg quest_story_033]
[f 0 5 65278][f 2 1]Sinopsis[n]Se buscan cazadores de tesoros. 夷Cu茨l es la vieja rima? 夷Interruptores obtienen riquezas? 夷No? Bueno, eso es exactamente lo que obtendr茨s al operar los interruptores en esta pel胤cula.[n][e]

[msg quest_story_034]
[f 0 5 65278][f 2 1]【あらすじ】[n]　カット予定[n][e]

[msg quest_story_035]
[f 0 5 65278][f 2 1]Sinopsis[n]Una historia de misterio en la que buscas huevos de Pascua que solo un verdadero fan puede encontrar. No te preocupes, esto no es una persecuci吋n absurda... a menos que te refieras a la que pone huevos de oro.[n][e]

[msg quest_story_036]
[f 0 5 65278][f 2 1]Sinopsis[n]Ha estallado una guerra. 夷Y son soldados de infanter胤a contra tanques? 夷C吋mo vencer茨 esta infanter胤a valiente las probabilidades... a menos que aparezca un h姻roe como t雨![n][e]

[msg quest_story_037]
[f 0 5 65278][f 2 1]Sinopsis[n]El Sr. Oso te est茨 esperando, en lo m茨s profundo del bosque. 斡Fortalece tus nervios y enfrenta a este gran enemigo! No pienses. 斡Siente![n][e]

[msg quest_story_038]
[f 0 5 65278][f 2 1]Sinopsis[n]Convierte a los verdugos robots en chatarra met茨lica. 夷No saben que son solo actores en esta historia, ejecut茨ndose en bits y bytes?[n][e]

[msg quest_story_039]
[f 0 5 65278][f 2 1]Sinopsis[n]斡La dee la da! 夷Listo para una pel胤cula musical? 斡La da dee la! Ser茨 muy divertido. 斡La da-dum da! La vida es un cabaret, amigo viejo.[n][e]

[msg quest_story_040]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Canciones![n]斡Comida![n]斡Amor![n]夷Ya est茨s vendido a esta pel胤cula?[n][e]

[msg quest_story_041]
[f 0 5 65278][f 2 1]Sinopsis[n]No necesitas sentir vergüenza. Sigue adelante y di lo que piensas. Grita. C茨ntalo. Sigue tus pasiones. Eso es lo que hacen en esta pel胤cula, 斡y t雨 tambi姻n puedes hacerlo![n][e]

[msg quest_story_042]
[f 0 5 65278][f 2 1]Sinopsis[n]夷Conoces el secreto de las mariposas? Te llevar茨n al sue隠o... con sus colores, sus danzas y su gracia. Cuidado... no vayan a obstruir tu magia.[n][e]

[msg quest_story_043]
[f 0 5 65278][f 2 1]Sinopsis[n]La vida est茨 llena de elecciones, y esta pel胤cula lo refleja siendo una historia de aventuras en la que t雨 eliges. Pero, por supuesto, 夷no est茨s ya viviendo una de esas?[n][e]

[msg quest_story_044]
[f 0 5 65278][f 2 1]【あらすじ】[n]　カット予定[n][e]

[msg quest_story_045]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Estreno mundial! Es hora de revelar qui姻n es el m茨s osuno de todos. Todos los a隠os de juegos de palabras con osos han llevado a esto, la batalla decisiva...[n][e]

[msg quest_story_046]
[f 0 5 65278][f 2 1]Sinopsis[n]斡遺rdenes de emergencia! 斡Devuelve el tesoro sin demora! 斡Esta pel胤cula de acci吋n de ladrones de guante blanco, llena de velocidad y emoci吋n, te mantendr茨 al borde tu asiento![n][e]

[msg quest_story_047]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Proyecci吋n especial de emergencia! 斡El terror se apodera de la Kamociudad! 斡Derrota la amenaza donde se ha establecido, en la Plaza Kamoshida![n][e]

[msg quest_story_048]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Proyecci吋n especial de emergencia! Problemas en Junessic Land. 斡Derrota la nueva amenaza que acecha en la tierra de los dinosaurios![n][e]

[msg quest_story_049]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Proyecci吋n especial de emergencia! 斡Un poderoso enemigo ha aparecido en A.I.G.I.S. y ha tomado el control de la sala de mando! 斡Debes derrotarlo![n][e]

[msg quest_story_050]
[f 0 5 65278][f 2 1]Sinopsis[n]斡Proyecci吋n especial de emergencia! 斡Todo Hikari est茨 consternado, porque lo impensable ha ocurrido! S胤, un enemigo ha aparecido... 斡y ha tomado el centro del escenario![n][e]

