[msg quest_explain_000]
[f 0 5 65278][f 2 1]クエスト００の概要です。[n]ダミーメッセージです。[n][e]

[msg quest_explain_001]
[f 0 5 65278][f 2 1]Defeat the Basalts! [n][e]

[msg quest_explain_002]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_003]
[f 0 5 65278][f 2 1]Defeat the swaggering Gigas![n][e]

[msg quest_explain_004]
[f 0 5 65278][f 2 1]Avoid the searchlights![n][e]

[msg quest_explain_005]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_006]
[f 0 5 65278][f 2 1]Investigate the mysterious ancient[n]creature![n][e]

[msg quest_explain_007]
[f 0 5 65278][f 2 1]Defeat the Chicken Kid![n][e]

[msg quest_explain_008]
[f 0 5 65278][f 2 1]Find the fake police officer and make[n]him pay![n][e]

[msg quest_explain_009]
[f 0 5 65278][f 2 1]Find graffiti that's different from the rest![n][e]

[msg quest_explain_010]
[f 0 5 65278][f 2 1]Head to the fishing spot and catch[n]yourself a big one![n][e]

[msg quest_explain_011]
[f 0 5 65278][f 2 1]Steal that treasure![n][e]

[msg quest_explain_012]
[f 0 5 65278][f 2 1]Collect a Cinnamon Fern![n][e]

[msg quest_explain_013]
[f 0 5 65278][f 2 1]Find the culprit![n][e]

[msg quest_explain_014]
[f 0 5 65278][f 2 1]Rescue the baby dinosaur![n][e]

[msg quest_explain_015]
[f 0 5 65278][f 2 1]Find out what's rampaging throughout[n]the jungle![n][e]

[msg quest_explain_016]
[f 0 5 65278][f 2 1]Locate the object in question from the[n]container![n][e]

[msg quest_explain_017]
[f 0 5 65278][f 2 1]Gather intel and solve the case![n][e]

[msg quest_explain_018]
[f 0 5 65278][f 2 1]Obtain three rare materials![n][e]

[msg quest_explain_019]
[f 0 5 65278][f 2 1]Defeat the Seidoptera![n][e]

[msg quest_explain_020]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_021]
[f 0 5 65278][f 2 1]Find edible ingredients in the jungle![n][e]

[msg quest_explain_022]
[f 0 5 65278][f 2 1]Defeat three large Shadows![n][e]

[msg quest_explain_023]
[f 0 5 65278][f 2 1]Defeat four Rampage Drives![n][e]

[msg quest_explain_024]
[f 0 5 65278][f 2 1]Get past security's next-generation tech![n][e]

[msg quest_explain_025]
[f 0 5 65278][f 2 1]Destroy KNS-1000![n][e]

[msg quest_explain_026]
[f 0 5 65278][f 2 1]Watch the battle of the mascots![n][e]

[msg quest_explain_027]
[f 0 5 65278][f 2 1]Find parts for the cooking equipment![n][e]

[msg quest_explain_028]
[f 0 5 65278][f 2 1]Fix the broken robot![n][e]

[msg quest_explain_029]
[f 0 5 65278][f 2 1]Defeat two Tyranniqueens![n][e]

[msg quest_explain_030]
[f 0 5 65278][f 2 1]Solve the mystery of the warp devices![n][e]

[msg quest_explain_031]
[f 0 5 65278][f 2 1]Locate the nightclub![n][e]

[msg quest_explain_032]
[f 0 5 65278][f 2 1]Have the beautiful ladies save Kamo City![n][e]

[msg quest_explain_033]
[f 0 5 65278][f 2 1]Search the Treasure Spots![n][e]

[msg quest_explain_034]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_035]
[f 0 5 65278][f 2 1]Locate the Easter Egg![n][e]

[msg quest_explain_036]
[f 0 5 65278][f 2 1]Collect three rare parts![n][e]

[msg quest_explain_037]
[f 0 5 65278][f 2 1]Head to the training area![n][e]

[msg quest_explain_038]
[f 0 5 65278][f 2 1]Defeat SCM-8801![n][e]

[msg quest_explain_039]
[f 0 5 65278][f 2 1]Find Hikari's lost item![n][e]

[msg quest_explain_040]
[f 0 5 65278][f 2 1]Obtain four fruits![n][e]

[msg quest_explain_041]
[f 0 5 65278][f 2 1]Grant Marie's wish![n][e]

[msg quest_explain_042]
[f 0 5 65278][f 2 1]Chase the butterfly in the musical![n][e]

[msg quest_explain_043]
[f 0 5 65278][f 2 1]Answer the questions and proceed![n][e]

[msg quest_explain_044]
[f 0 5 65278][f 2 1]※このクエストはカット[n][e]

[msg quest_explain_045]
[f 0 5 65278][f 2 1]Finish the battle of the bears![n][e]

[msg quest_explain_046]
[f 0 5 65278][f 2 1]Bring back music from the movie![n][e]

[msg quest_explain_047]
[f 0 5 65278][f 2 1]Defeat the new Shadow in Kamo City![n][e]

[msg quest_explain_048]
[f 0 5 65278][f 2 1]Defeat the new Shadow in Junessic Land![n][e]

[msg quest_explain_049]
[f 0 5 65278][f 2 1]Defeat the new Shadow in A.I.G.I.S.![n][e]

[msg quest_explain_050]
[f 0 5 65278][f 2 1]Defeat the new Shadow in Hikari![n][e]

