[msg chara_000]
[f 0 5 65278][f 2 1]Blank[n][e]

[msg chara_001]
[f 0 5 65278][f 2 1](Fila Frontal) Siempre listo para la batalla, [n]mejor con ataques de corte y el姻ctricos.[n][e]

[msg chara_002]
[f 0 5 65278][f 2 1](Fila Frontal) Un luchador vers茨til, h茨bil con todas las afinidades.[n][e]

[msg chara_003]
[f 0 5 65278][f 2 1](Fila Frontal) Un luchador 茨gil que se especializa en ataques de corte y viento.[n][e]

[msg chara_004]
[f 0 5 65278][f 2 1](Fila Frontal) Una chica experta en kung fu con alta[n]evasi吋n y ataques cr胤ticos.[n][e]

[msg chara_005]
[f 0 5 65278][f 2 1](Fila Trasera) Elegante, apropiada y mortal, 斡pero cuidado con su salud![n][e]

[msg chara_006]
[f 0 5 65278][f 2 1]Ninguno[n][e]

[msg chara_007]
[f 0 5 65278][f 2 1](Fila Frontal) Protege a sus compa隠eros con una alta[n]defensa y ofensa.[n][e]

[msg chara_008]
[f 0 5 65278][f 2 1](Fila Trasera) Un detective de tama隠o peque隠o, excelente con habilidades de enlace.[n][e]

[msg chara_009]
[f 0 5 65278][f 2 1](Fila Frontal) Una mascota autoproclamada que ayuda al grupo en combate.[n][e]

[msg chara_00A]
[f 0 5 65278][f 2 1](Fila Trasera) Una chica de humor variable que sobresale en habilidades de viento y recuperaci吋n.[n][e]

[msg chara_00B]
[f 0 5 65278][f 2 1](Fila Frontal) Un presumido con habilidades equilibradas en ataque, defensa y contraataque.[n][e]

[msg chara_00C]
[f 0 5 65278][f 2 1](Fila Frontal) Un boxeador sin rival que inflige un da隠o extremo.[n][e]

[msg chara_00D]
[f 0 5 65278][f 2 1](Front or Back) Sella las habilidades del enemigo y las remata con magia de hielo.[n][e]

[msg chara_00E]
[f 0 5 65278][f 2 1]None[n][e]

[msg chara_00F]
[f 0 5 65278][f 2 1](Front or Back) Arma anti-sombras que puede activar su[n]Modo Desenfreno.[n][e]

[msg chara_010]
[f 0 5 65278][f 2 1](Fila Trasera) Es genial con habilidades f胤sicas y de[n]Electricidad, 斡pero tiene poca salud![n][e]

[msg chara_011]
[f 0 5 65278][f 2 1](Fila Trasera) R茨pido y maneja magia de fuego y oscuridad, 斡pero no es resistente![n][e]

[msg chara_012]
[f 0 5 65278][f 2 1](Fila Frontal) El tipo m茨s resistente, pero extremadamente vulnerable a la magia.[n][e]

[msg chara_013]
[f 0 5 65278][f 2 1](Fila Trasera) Zen ataca, mientras que Rei cura. Ambos utilizan habilidades misteriosas...[n][e]

[msg chara_014]
[f 0 5 65278][f 2 1](Fila Trasera) Zen ha recuperado sus recuerdos y sus habilidades...[n][e]

