[msg item_500]
[f 0 5 65278][f 2 1]Blank[n][e]

[msg item_501]
[f 0 5 65278][f 2 1]消耗品　0x501　１行目 効果：[f 0 1 4]味方１人のＨＰ６０回復[f 0 1 0][n][n][e]

[msg item_502]
[f 0 5 65278][f 2 1]消耗品　0x502　１行目 効果：[f 0 1 4]味方１人のＨＰ１００回復[f 0 1 0][n][n][e]

[msg item_503]
[f 0 5 65278][f 2 1]消耗品　0x503　１行目 効果：[f 0 1 4]味方１人のＨＰ２００回復[f 0 1 0][n][n][e]

[msg item_504]
[f 0 5 65278][f 2 1]Una misteriosa cuenta que emite una luz[n]curativa. [f 0 1 4]Restaura todos los PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_505]
[f 0 5 65278][f 2 1]Dulces misteriosos que vigorizan el alma. [f 0 1 4][n]Restaura 30 PE[f 0 1 0]. (1[n]Aliado)[n][e]

[msg item_506]
[f 0 5 65278][f 2 1]Un regalo hecho de ingredientes estimulantes.[n][f 0 1 4]Restaura 60 PE[f 0 1 0]. (1[n]Aliado)[n][e]

[msg item_507]
[f 0 5 65278][f 2 1]Una goma misteriosa que enriquece el alma.[n][f 0 1 4]Restaura 100 PE[f 0 1 0]. (1[n]Aliado)[n][e]

[msg item_508]
[f 0 5 65278][f 2 1]消耗品　0x508　１行目 効果：[f 0 1 4]味方１人のＳＰ全回復[f 0 1 0][n][e]

[msg item_509]
[f 0 5 65278][f 2 1]Una gota del "bebido de los dioses". [f 0 1 4][n]Restaura 100 PS y 25 PE[f 0 1 0]. (1[n]Aliado)[n][e]

[msg item_50A]
[f 0 5 65278][f 2 1]Cristalizado "bebido de los dioses." [f 0 1 4][n]Restaura 200 PS y 50 PE[f 0 1 0]. (1[n]Aliado)[n][e]

[msg item_50B]
[f 0 5 65278][f 2 1]消耗品　0x50B　１行目 効果：[f 0 1 4]味方１人のＨＰ＆ＳＰ全回復[f 0 1 0][n][n][e]

[msg item_50C]
[f 0 5 65278][f 2 1]Una granada que puede recordar un alma ca胤da.[n][f 0 1 4]Revive y Restaura la mitad PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_50D]
[f 0 5 65278][f 2 1]Incienso que puede recordar un alma ca胤da.[n][f 0 1 4]Revive y Restaura todos los PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_50E]
[f 0 5 65278][f 2 1]消耗品　0x50E　１行目 効果：[f 0 1 4]味方１列のＨＰ１５０回復[f 0 1 0][n][n][e]

[msg item_50F]
[f 0 5 65278][f 2 1]消耗品　0x50F　１行目 効果：[f 0 1 4]味方１列のＨＰを３００回復[f 0 1 0][n][n][e]

[msg item_510]
[f 0 5 65278][f 2 1]Medicina para liberar la fuerza. [f 0 1 4]Elimina Restricciones[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_511]
[f 0 5 65278][f 2 1]消耗品　0x511　１行目 効果：[f 0 1 4]味方１人の状態異常を回復[f 0 1 0][n][n][e]

[msg item_512]
[f 0 5 65278][f 2 1]Agua de primavera consagrada en un ritual[n]santo. [f 0 1 4]Elimina Aumentos[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_513]
[f 0 5 65278][f 2 1]Sal gruesa consagrada en un ritual santo. [f 0 1 4][n]Elimina desventajas[f 0 1 0].[n](Grupo)[n][e]

[msg item_514]
[f 0 5 65278][f 2 1]Una sala con la bendici吋n divina de Rasetsu.[n][f 0 1 4]Aumentar el ataque por 3 turnos[f 0 1 0][n]. (1 fila)[n][e]

[msg item_515]
[f 0 5 65278][f 2 1]Una sala con la bendici吋n divina de los[n]Kongou. [f 0 1 4]Aumenta la defensa por 3 turnos[f 0 1 0][n]. (1 fila)[n][e]

[msg item_516]
[f 0 5 65278][f 2 1]Una sala con la bendici吋n de Idaten. [f 0 1 4][n]Aumenta[f 0 1 0] [f 0 1 4]la precisi吋nlevasi吋n por 3 turnos[f 0 1 0][n]. (1 fila)[n][e]

[msg item_517]
[f 0 5 65278][f 2 1]L胤quido estilo despu姻s de la bebida de los[n]dioses. [f 0 1 4]Elimina Estados Alterados y Restricciones[f 0 1 0][n]. (Grupo)[n][e]

[msg item_518]
[f 0 5 65278][f 2 1]消耗品　0x518　１行目 消耗品　0x518　２行目[n][e]

[msg item_519]
[f 0 5 65278][f 2 1]Conjura la niebla que ahoga las llamas. [f 0 1 4][n]Otorga resistencia al Fuego por 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51A]
[f 0 5 65278][f 2 1]Conjure la niebla que reduce el escalofr胤o.[n][f 0 1 4]Otorga resistencia al Hielo durante 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51B]
[f 0 5 65278][f 2 1]Conjura la niebla que humedece la electricidad.[n][f 0 1 4] Gran resistencia Elec por 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51C]
[f 0 5 65278][f 2 1]Conjura la niebla que disminuye el viento.[n][f 0 1 4] Gran resistencia al viento por 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51D]
[f 0 5 65278][f 2 1]Conjura la niebla que niega la energ胤a nuclear.[n][f 0 1 4]Gran resistencia nuclear por 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51E]
[f 0 5 65278][f 2 1]Conjura la niebla de los barrotes EPE. [f 0 1 4][n]Gran resistencia al Psy por 3 turnos[f 0 1 0][n]. (Grupo)[n][e]

[msg item_51F]
[f 0 5 65278][f 2 1]消耗品　0x51F　１行目 消耗品　0x51F　２行目[n][e]

[msg item_520]
[f 0 5 65278][f 2 1]消耗品　0x520　１行目 消耗品　0x520　２行目[n][e]

[msg item_521]
[f 0 5 65278][f 2 1]Bursts con una explosi吋n ardiente cuando se[n]lanza. [f 0 1 4]Da隠o de Fuego ligero[f 0 1 0][n]. (Todos los enemigos)[n][e]

[msg item_522]
[f 0 5 65278][f 2 1]Una bala que explota en llamas. [f 0 1 4]Da隠o de fuego medio[f 0 1 0][n]. (Todos los[n]enemigos)[n][e]

[msg item_523]
[f 0 5 65278][f 2 1]Bursts with crackling frost when thrown. [f 0 1 4][n]Da隠o de hielo ligero[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_524]
[f 0 5 65278][f 2 1]Una bala que explota en una tormenta. [f 0 1 4][n]Da隠o de hielo medio[f 0 1 0]. (Todos[n]los enemigos)[n][e]

[msg item_525]
[f 0 5 65278][f 2 1]Bursts con alta tensi吋n cuando se lanza. [f 0 1 4][n]Da隠o El姻ctrico leve[f 0 1 0]. (Todos[n]los enemigos)[n][e]

[msg item_526]
[f 0 5 65278][f 2 1]Una bala que explota en la electricidad. [f 0 1 4][n]Da隠o el姻ctrico medio[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_527]
[f 0 5 65278][f 2 1]Bursts with galeforce winds when thrown. [f 0 1 4][n]Da隠os de viento leve[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_528]
[f 0 5 65278][f 2 1]Una bala que explota en un torbellino. [f 0 1 4][n]Da隠o de viento medio[f 0 1 0]. (Todos[n]los enemigos)[n][e]

[msg item_529]
[f 0 5 65278][f 2 1]Bendito arroz que puede purificar un objetivo.[n][f 0 1 4]Ataque de Bendici吋n con muerte instant茨nea[f 0 1 0][n]. (1 Enemigo)[n][e]

[msg item_52A]
[f 0 5 65278][f 2 1]Un sutra prohibido usado como una maldici吋n[n]de muerte. [f 0 1 4]Ataque de Maldici吋n con muerte instant茨nea[f 0 1 0][n]. (1[n]Enemigo)[n][e]

[msg item_52B]
[f 0 5 65278][f 2 1]Bursts con poder cin姻tico cuando se lanza.[n][f 0 1 4]Da隠o Ps胤quico Ligero[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_52C]
[f 0 5 65278][f 2 1]Una bala que explota con poder telequin姻tico.[n][f 0 1 4]Da隠o Ps胤quico Medio[f 0 1 0].[n](Todos los enemigos)[n][e]

[msg item_52D]
[f 0 5 65278][f 2 1]Bursts with nuclear energy when thrown. [f 0 1 4][n]Da隠o Nuclear ligero[f 0 1 0]. (Todos[n]los enemigos)[n][e]

[msg item_52E]
[f 0 5 65278][f 2 1]Una bala que explota con energ胤a nuclear. [f 0 1 4][n]Da隠o Nuclear medio[f 0 1 0]. (Todos[n]los enemigos)[n][e]

[msg item_52F]
[f 0 5 65278][f 2 1]消耗品　0x52F　１行目 消耗品　0x52F　２行目[n][e]

[msg item_530]
[f 0 5 65278][f 2 1]消耗品　0x530　１行目 消耗品　0x530　２行目[n][e]

[msg item_531]
[f 0 5 65278][f 2 1]消耗品　0x531　１行目 効果：[f 0 1 4]使用ターン時の敵のドロップ率アップ[f 0 1 0][n][n][e]

[msg item_532]
[f 0 5 65278][f 2 1]Esta efigie extra隠amente se parece a su[n]portador. [f 0 1 4]Protege al usuario de 1 muerte instant茨nea por Bendici吋nlMaldici吋n[f 0 1 0][n][n].[n][e]

[msg item_533]
[f 0 5 65278][f 2 1]Tocando este tubo repele las sombras. [f 0 1 4][n]Reduce el 胤ndice de encuentro[f 0 1 0][n].[n][e]

[msg item_534]
[f 0 5 65278][f 2 1]Jugar esta tuber胤a atrae Sombras. [f 0 1 4]Aumentar la tasa de encuentros[f 0 1 0][n].[n][e]

[msg item_535]
[f 0 5 65278][f 2 1]Teleporta instant茨neamente al usuario a la[n]seguridad. [f 0 1 4]Escapa del laberinto actual[f 0 1 0][n].[n][e]

[msg item_536]
[f 0 5 65278][f 2 1]Al instante el usuario teletransporta a la[n]escalera. [f 0 1 4]Regresa a la entrada del piso[f 0 1 0][n].[n][e]

[msg item_537]
[f 0 5 65278][f 2 1]消耗品　0x537　１行目 消耗品　0x537　２行目[n][e]

[msg item_538]
[f 0 5 65278][f 2 1]Una herramienta que puede amplificar frecuencias[n]FOE. [f 0 1 4]Mostrar la ubicaci吋n de los FOE en la planta actual[f 0 1 0][n].[n][e]

[msg item_539]
[f 0 5 65278][f 2 1]Conocido como la bebida de los dioses. [f 0 1 4][n]Restaura todos los PS y PE[f 0 1 0].[n](Grupo)[n][e]

[msg item_53A]
[f 0 5 65278][f 2 1]Una cadena de cuentas con una luz curativa.[n][f 0 1 4]Restaura todos los PS[f 0 1 0].[n](Grupo)[n][e]

[msg item_53B]
[f 0 5 65278][f 2 1]Un misterioso Goho-M que no desaparece despu姻s[n]de su uso. [f 0 1 4]Escapa del laberinto actual[f 0 1 0][n].[n][e]

[msg item_53C]
[f 0 5 65278][f 2 1]Un misterioso Goba-K que no desaparece despu姻s[n]del uso. [f 0 1 4] Volver a la entrada del piso[f 0 1 0][n].[n][e]

[msg item_53D]
[f 0 5 65278][f 2 1]Sonar este cuerno atrae Sombras. [f 0 1 4]Aumenta considerablemente la tasa de encuentros[f 0 1 0][n][n].[n][e]

[msg item_53E]
[f 0 5 65278][f 2 1]Sonar este cuerno aleja las sombras. [f 0 1 4][n]Elimina encuentros aleatorios[f 0 1 0].[n][e]

[msg item_53F]
[f 0 5 65278][f 2 1]Explota la volatilidad del calabozo. [f 0 1 4][n]Actualizar los puntos del tesoro de la planta actual[f 0 1 0][n].[n][e]

[msg item_540]
[f 0 5 65278][f 2 1]消耗品　0x540　１行目 消耗品　0x540　２行目[n][e]

[msg item_541]
[f 0 5 65278][f 2 1]S吋lo usable en la batalla. No desaparece[n]despu姻s del uso. [f 0 1 4]Restaura 30 PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_542]
[f 0 5 65278][f 2 1]Una pelota que despliega una cortina de humo.[n][f 0 1 4]Escape garantizado (en batallas con escapatoria)[f 0 1 0][n].[n][e]

[msg item_543]
[f 0 5 65278][f 2 1]Un muslo picante y profundo de un f姻nix. [f 0 1 4][n]Revive y restaura 30% PS[f 0 1 0].[n](1 Aliado)[n][e]

[msg item_544]
[f 0 5 65278][f 2 1]Palomitas que se sazonan con sal. [f 0 1 4]Restaura 30 PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_545]
[f 0 5 65278][f 2 1]Frios hechos con patatas sanas. [f 0 1 4]Revive y restaura 10% PS[f 0 1 0][n]. (1[n]Aliado)[n][e]

[msg item_546]
[f 0 5 65278][f 2 1]消耗品　0x546　１行目 消耗品　0x546　２行目[n][e]

[msg item_547]
[f 0 5 65278][f 2 1]S吋lo usable en la batalla. No desaparece[n]despu姻s del uso. [f 0 1 4]Revive y restaura 10% PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_548]
[f 0 5 65278][f 2 1]消耗品　0x548　１行目 消耗品　0x548　２行目[n][e]

[msg item_549]
[f 0 5 65278][f 2 1]Dulces palomitas infundidas con miel. [f 0 1 4][n]Restaura 80 PS[f 0 1 0]. (1 Aliado)[n][e]

[msg item_54A]
[f 0 5 65278][f 2 1]Un perro caliente lo suficiente para alimentar[n]a tres. [f 0 1 4]Restaura 60 PS[f 0 1 0][n]. (1 fila)[n][e]

[msg item_54B]
[f 0 5 65278][f 2 1]Refrescante bebida que limpia impurezas. [f 0 1 4][n]Cura Estados Alterados[f 0 1 0].[n](1 Aliado)[n][e]

[msg item_54C]
[f 0 5 65278][f 2 1]Palomitas con sabor tropical. [f 0 1 4]Restaura 120 PS[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_54D]
[f 0 5 65278][f 2 1]Palomitas de ma胤z con jugos de sabor. [f 0 1 4][n]Restaura 180 PS[f 0 1 0]. (1 Aliado)[n][e]

[msg item_54E]
[f 0 5 65278][f 2 1]Misterios palomitas de siete sabores. [f 0 1 4][n]Restaura 250 PS[f 0 1 0]. (1 Aliado)[n][e]

[msg item_54F]
[f 0 5 65278][f 2 1]消耗品　0x54F　１行目 消耗品　0x54F　２行目[n][e]

[msg item_550]
[f 0 5 65278][f 2 1]El poder de Persona se puede copiar en esta[n]tarjeta. [f 0 1 4]Efecto especial en Sacrificio Fusi吋n[f 0 1 0][n].[n][e]

[msg item_551]
[f 0 5 65278][f 2 1]El poder de Persona se puede copiar en esta[n]tarjeta. [f 0 1 4]Efecto especial en Sacrificio Fusi吋n[f 0 1 0][n].[n][e]

[msg item_552]
[f 0 5 65278][f 2 1]Especialidad de un lugar de ramen en la[n]estaci吋n de Iwatodai. [f 0 1 4]Restaura 50% PS[f 0 1 0][n]. (Grupo)[n][e]

[msg item_553]
[f 0 5 65278][f 2 1]Especialidad de un restaurante chino en Inaba.[n][f 0 1 4] Restaura todos los PS[f 0 1 0][n]. (1 fila)[n][e]

[msg item_554]
[f 0 5 65278][f 2 1]Especialidad de un caf de callej吋n en Yongen-[n]Jaya. [f 0 1 4]Restaura 50% PE[f 0 1 0][n]. (Grupo)[n][e]

[msg item_555]
[f 0 5 65278][f 2 1]Incense que unifica la mente y la memoria.[n][f 0 1 4] Sube el nivel a Wild Level[f 0 1 0][n]. (1 Aliado)[n][e]

[msg item_556]
[f 0 5 65278][f 2 1]消耗品　0x556　１行目 消耗品　0x556　２行目[n][e]

[msg item_557]
[f 0 5 65278][f 2 1]Dos perros calientes largos combinados en[n]uno. [f 0 1 4]Restaura 120 PS[f 0 1 0]. (1[n]fila)[n][e]

[msg item_558]
[f 0 5 65278][f 2 1]Un perro caliente extra-long, extra-thick.[n][f 0 1 4]Restaura 180 PS[f 0 1 0]. (1[n]fila)[n][e]

[msg item_559]
[f 0 5 65278][f 2 1]Agua que purga impurezas corporales. [f 0 1 4][n]Cura Estados Alterados[f 0 1 0]. (1[n]fila)[n][e]

[msg item_55A]
[f 0 5 65278][f 2 1]Vatio de agua que purifica impurezas corporales.[n][f 0 1 4]Cura Estados Alterados[f 0 1 0][n]. (Grupo)[n][e]

[msg item_55B]
[f 0 5 65278][f 2 1]Una multi-paquete de medicina sin uni吋n. [f 0 1 4][n]Elimina Restricciones[f 0 1 0]. (1[n]fila)[n][e]

[msg item_55C]
[f 0 5 65278][f 2 1]Un paquete de jumbo de medicinas inconclusas.[n][f 0 1 4]Elimina Restricciones[f 0 1 0][n]. (Grupo)[n][e]

[msg item_55D]
[f 0 5 65278][f 2 1]Un largo arreglo de pasteles. Puede alimentar[n]hasta 3. [f 0 1 4]Restaura 30 PS[f 0 1 0][n]. (1 fila)[n][e]

[msg item_55E]
[f 0 5 65278][f 2 1]消耗品　0x55E　１行目 消耗品　0x55E　２行目[n][e]

[msg item_55F]
[f 0 5 65278][f 2 1]消耗品　0x55F　１行目 消耗品　0x55F　２行目[n][e]

[msg item_560]
[f 0 5 65278][f 2 1]消耗品　0x560　１行目 消耗品　0x560　２行目[n][e]

[msg item_561]
[f 0 5 65278][f 2 1]消耗品　0x561　１行目 消耗品　0x561　２行目[n][e]

[msg item_562]
[f 0 5 65278][f 2 1]消耗品　0x562　１行目 消耗品　0x562　２行目[n][e]

[msg item_563]
[f 0 5 65278][f 2 1]消耗品　0x563　１行目 消耗品　0x563　２行目[n][e]

[msg item_564]
[f 0 5 65278][f 2 1]消耗品　0x564　１行目 消耗品　0x564　２行目[n][e]

[msg item_565]
[f 0 5 65278][f 2 1]消耗品　0x565　１行目 消耗品　0x565　２行目[n][e]

[msg item_566]
[f 0 5 65278][f 2 1]消耗品　0x566　１行目 消耗品　0x566　２行目[n][e]

[msg item_567]
[f 0 5 65278][f 2 1]消耗品　0x567　１行目 消耗品　0x567　２行目[n][e]

[msg item_568]
[f 0 5 65278][f 2 1]消耗品　0x568　１行目 消耗品　0x568　２行目[n][e]

[msg item_569]
[f 0 5 65278][f 2 1]消耗品　0x569　１行目 消耗品　0x569　２行目[n][e]

[msg item_56A]
[f 0 5 65278][f 2 1]消耗品　0x56A　１行目 消耗品　0x56A　２行目[n][e]

[msg item_56B]
[f 0 5 65278][f 2 1]消耗品　0x56B　１行目 消耗品　0x56B　２行目[n][e]

[msg item_56C]
[f 0 5 65278][f 2 1]消耗品　0x56C　１行目 消耗品　0x56C　２行目[n][e]

[msg item_56D]
[f 0 5 65278][f 2 1]消耗品　0x56D　１行目 消耗品　0x56D　２行目[n][e]

[msg item_56E]
[f 0 5 65278][f 2 1]消耗品　0x56E　１行目 消耗品　0x56E　２行目[n][e]

[msg item_56F]
[f 0 5 65278][f 2 1]消耗品　0x56F　１行目 消耗品　0x56F　２行目[n][e]

[msg item_570]
[f 0 5 65278][f 2 1]消耗品　0x570　１行目 消耗品　0x570　２行目[n][e]

[msg item_571]
[f 0 5 65278][f 2 1]消耗品　0x571　１行目 消耗品　0x571　２行目[n][e]

[msg item_572]
[f 0 5 65278][f 2 1]消耗品　0x572　１行目 消耗品　0x572　２行目[n][e]

[msg item_573]
[f 0 5 65278][f 2 1]消耗品　0x573　１行目 消耗品　0x573　２行目[n][e]

[msg item_574]
[f 0 5 65278][f 2 1]消耗品　0x574　１行目 消耗品　0x574　２行目[n][e]

[msg item_575]
[f 0 5 65278][f 2 1]消耗品　0x575　１行目 消耗品　0x575　２行目[n][e]

[msg item_576]
[f 0 5 65278][f 2 1]消耗品　0x576　１行目 消耗品　0x576　２行目[n][e]

[msg item_577]
[f 0 5 65278][f 2 1]消耗品　0x577　１行目 消耗品　0x577　２行目[n][e]

[msg item_578]
[f 0 5 65278][f 2 1]消耗品　0x578　１行目 消耗品　0x578　２行目[n][e]

[msg item_579]
[f 0 5 65278][f 2 1]消耗品　0x579　１行目 消耗品　0x579　２行目[n][e]

[msg item_57A]
[f 0 5 65278][f 2 1]消耗品　0x57A　１行目 消耗品　0x57A　２行目[n][e]

[msg item_57B]
[f 0 5 65278][f 2 1]消耗品　0x57B　１行目 消耗品　0x57B　２行目[n][e]

[msg item_57C]
[f 0 5 65278][f 2 1]消耗品　0x57C　１行目 消耗品　0x57C　２行目[n][e]

[msg item_57D]
[f 0 5 65278][f 2 1]消耗品　0x57D　１行目 消耗品　0x57D　２行目[n][e]

[msg item_57E]
[f 0 5 65278][f 2 1]消耗品　0x57E　１行目 消耗品　0x57E　２行目[n][e]

[msg item_57F]
[f 0 5 65278][f 2 1]消耗品　0x57F　１行目 消耗品　0x57F　２行目[n][e]

[msg item_580]
[f 0 5 65278][f 2 1]消耗品　0x580　１行目 消耗品　0x580　２行目[n][e]

[msg item_581]
[f 0 5 65278][f 2 1]消耗品　0x581　１行目 消耗品　0x581　２行目[n][e]

[msg item_582]
[f 0 5 65278][f 2 1]消耗品　0x582　１行目 消耗品　0x582　２行目[n][e]

[msg item_583]
[f 0 5 65278][f 2 1]消耗品　0x583　１行目 消耗品　0x583　２行目[n][e]

[msg item_584]
[f 0 5 65278][f 2 1]消耗品　0x584　１行目 消耗品　0x584　２行目[n][e]

[msg item_585]
[f 0 5 65278][f 2 1]消耗品　0x585　１行目 消耗品　0x585　２行目[n][e]

[msg item_586]
[f 0 5 65278][f 2 1]消耗品　0x586　１行目 消耗品　0x586　２行目[n][e]

[msg item_587]
[f 0 5 65278][f 2 1]消耗品　0x587　１行目 消耗品　0x587　２行目[n][e]

[msg item_588]
[f 0 5 65278][f 2 1]消耗品　0x588　１行目 消耗品　0x588　２行目[n][e]

[msg item_589]
[f 0 5 65278][f 2 1]消耗品　0x589　１行目 消耗品　0x589　２行目[n][e]

[msg item_58A]
[f 0 5 65278][f 2 1]消耗品　0x58A　１行目 消耗品　0x58A　２行目[n][e]

[msg item_58B]
[f 0 5 65278][f 2 1]消耗品　0x58B　１行目 消耗品　0x58B　２行目[n][e]

[msg item_58C]
[f 0 5 65278][f 2 1]消耗品　0x58C　１行目 消耗品　0x58C　２行目[n][e]

[msg item_58D]
[f 0 5 65278][f 2 1]消耗品　0x58D　１行目 消耗品　0x58D　２行目[n][e]

[msg item_58E]
[f 0 5 65278][f 2 1]消耗品　0x58E　１行目 消耗品　0x58E　２行目[n][e]

[msg item_58F]
[f 0 5 65278][f 2 1]消耗品　0x58F　１行目 消耗品　0x58F　２行目[n][e]

[msg item_590]
[f 0 5 65278][f 2 1]消耗品　0x590　１行目 消耗品　0x590　２行目[n][e]

[msg item_591]
[f 0 5 65278][f 2 1]消耗品　0x591　１行目 消耗品　0x591　２行目[n][e]

[msg item_592]
[f 0 5 65278][f 2 1]消耗品　0x592　１行目 消耗品　0x592　２行目[n][e]

[msg item_593]
[f 0 5 65278][f 2 1]消耗品　0x593　１行目 消耗品　0x593　２行目[n][e]

[msg item_594]
[f 0 5 65278][f 2 1]消耗品　0x594　１行目 消耗品　0x594　２行目[n][e]

[msg item_595]
[f 0 5 65278][f 2 1]消耗品　0x595　１行目 消耗品　0x595　２行目[n][e]

[msg item_596]
[f 0 5 65278][f 2 1]消耗品　0x596　１行目 消耗品　0x596　２行目[n][e]

[msg item_597]
[f 0 5 65278][f 2 1]消耗品　0x597　１行目 消耗品　0x597　２行目[n][e]

[msg item_598]
[f 0 5 65278][f 2 1]消耗品　0x598　１行目 消耗品　0x598　２行目[n][e]

[msg item_599]
[f 0 5 65278][f 2 1]消耗品　0x599　１行目 消耗品　0x599　２行目[n][e]

[msg item_59A]
[f 0 5 65278][f 2 1]消耗品　0x59A　１行目 消耗品　0x59A　２行目[n][e]

[msg item_59B]
[f 0 5 65278][f 2 1]消耗品　0x59B　１行目 消耗品　0x59B　２行目[n][e]

[msg item_59C]
[f 0 5 65278][f 2 1]消耗品　0x59C　１行目 消耗品　0x59C　２行目[n][e]

[msg item_59D]
[f 0 5 65278][f 2 1]消耗品　0x59D　１行目 消耗品　0x59D　２行目[n][e]

[msg item_59E]
[f 0 5 65278][f 2 1]消耗品　0x59E　１行目 消耗品　0x59E　２行目[n][e]

[msg item_59F]
[f 0 5 65278][f 2 1]消耗品　0x59F　１行目 消耗品　0x59F　２行目[n][e]

[msg item_5A0]
[f 0 5 65278][f 2 1]消耗品　0x5A0　１行目 消耗品　0x5A0　２行目[n][e]

[msg item_5A1]
[f 0 5 65278][f 2 1]消耗品　0x5A1　１行目 消耗品　0x5A1　２行目[n][e]

[msg item_5A2]
[f 0 5 65278][f 2 1]消耗品　0x5A2　１行目 消耗品　0x5A2　２行目[n][e]

[msg item_5A3]
[f 0 5 65278][f 2 1]消耗品　0x5A3　１行目 消耗品　0x5A3　２行目[n][e]

[msg item_5A4]
[f 0 5 65278][f 2 1]消耗品　0x5A4　１行目 消耗品　0x5A4　２行目[n][e]

[msg item_5A5]
[f 0 5 65278][f 2 1]消耗品　0x5A5　１行目 消耗品　0x5A5　２行目[n][e]

[msg item_5A6]
[f 0 5 65278][f 2 1]消耗品　0x5A6　１行目 消耗品　0x5A6　２行目[n][e]

[msg item_5A7]
[f 0 5 65278][f 2 1]消耗品　0x5A7　１行目 消耗品　0x5A7　２行目[n][e]

[msg item_5A8]
[f 0 5 65278][f 2 1]消耗品　0x5A8　１行目 消耗品　0x5A8　２行目[n][e]

[msg item_5A9]
[f 0 5 65278][f 2 1]消耗品　0x5A9　１行目 消耗品　0x5A9　２行目[n][e]

[msg item_5AA]
[f 0 5 65278][f 2 1]消耗品　0x5AA　１行目 消耗品　0x5AA　２行目[n][e]

[msg item_5AB]
[f 0 5 65278][f 2 1]消耗品　0x5AB　１行目 消耗品　0x5AB　２行目[n][e]

[msg item_5AC]
[f 0 5 65278][f 2 1]消耗品　0x5AC　１行目 消耗品　0x5AC　２行目[n][e]

[msg item_5AD]
[f 0 5 65278][f 2 1]消耗品　0x5AD　１行目 消耗品　0x5AD　２行目[n][e]

[msg item_5AE]
[f 0 5 65278][f 2 1]消耗品　0x5AE　１行目 消耗品　0x5AE　２行目[n][e]

[msg item_5AF]
[f 0 5 65278][f 2 1]消耗品　0x5AF　１行目 消耗品　0x5AF　２行目[n][e]

[msg item_5B0]
[f 0 5 65278][f 2 1]消耗品　0x5B0　１行目 消耗品　0x5B0　２行目[n][e]

[msg item_5B1]
[f 0 5 65278][f 2 1]消耗品　0x5B1　１行目 消耗品　0x5B1　２行目[n][e]

[msg item_5B2]
[f 0 5 65278][f 2 1]消耗品　0x5B2　１行目 消耗品　0x5B2　２行目[n][e]

[msg item_5B3]
[f 0 5 65278][f 2 1]消耗品　0x5B3　１行目 消耗品　0x5B3　２行目[n][e]

[msg item_5B4]
[f 0 5 65278][f 2 1]消耗品　0x5B4　１行目 消耗品　0x5B4　２行目[n][e]

[msg item_5B5]
[f 0 5 65278][f 2 1]消耗品　0x5B5　１行目 消耗品　0x5B5　２行目[n][e]

[msg item_5B6]
[f 0 5 65278][f 2 1]消耗品　0x5B6　１行目 消耗品　0x5B6　２行目[n][e]

[msg item_5B7]
[f 0 5 65278][f 2 1]消耗品　0x5B7　１行目 消耗品　0x5B7　２行目[n][e]

[msg item_5B8]
[f 0 5 65278][f 2 1]消耗品　0x5B8　１行目 消耗品　0x5B8　２行目[n][e]

[msg item_5B9]
[f 0 5 65278][f 2 1]消耗品　0x5B9　１行目 消耗品　0x5B9　２行目[n][e]

[msg item_5BA]
[f 0 5 65278][f 2 1]消耗品　0x5BA　１行目 消耗品　0x5BA　２行目[n][e]

[msg item_5BB]
[f 0 5 65278][f 2 1]消耗品　0x5BB　１行目 消耗品　0x5BB　２行目[n][e]

[msg item_5BC]
[f 0 5 65278][f 2 1]消耗品　0x5BC　１行目 消耗品　0x5BC　２行目[n][e]

[msg item_5BD]
[f 0 5 65278][f 2 1]消耗品　0x5BD　１行目 消耗品　0x5BD　２行目[n][e]

[msg item_5BE]
[f 0 5 65278][f 2 1]消耗品　0x5BE　１行目 消耗品　0x5BE　２行目[n][e]

[msg item_5BF]
[f 0 5 65278][f 2 1]消耗品　0x5BF　１行目 消耗品　0x5BF　２行目[n][e]

[msg item_5C0]
[f 0 5 65278][f 2 1]消耗品　0x5C0　１行目 消耗品　0x5C0　２行目[n][e]

[msg item_5C1]
[f 0 5 65278][f 2 1]消耗品　0x5C1　１行目 消耗品　0x5C1　２行目[n][e]

[msg item_5C2]
[f 0 5 65278][f 2 1]消耗品　0x5C2　１行目 消耗品　0x5C2　２行目[n][e]

[msg item_5C3]
[f 0 5 65278][f 2 1]消耗品　0x5C3　１行目 消耗品　0x5C3　２行目[n][e]

[msg item_5C4]
[f 0 5 65278][f 2 1]消耗品　0x5C4　１行目 消耗品　0x5C4　２行目[n][e]

[msg item_5C5]
[f 0 5 65278][f 2 1]消耗品　0x5C5　１行目 消耗品　0x5C5　２行目[n][e]

[msg item_5C6]
[f 0 5 65278][f 2 1]消耗品　0x5C6　１行目 消耗品　0x5C6　２行目[n][e]

[msg item_5C7]
[f 0 5 65278][f 2 1]消耗品　0x5C7　１行目 消耗品　0x5C7　２行目[n][e]

[msg item_5C8]
[f 0 5 65278][f 2 1]消耗品　0x5C8　１行目 消耗品　0x5C8　２行目[n][e]

[msg item_5C9]
[f 0 5 65278][f 2 1]消耗品　0x5C9　１行目 消耗品　0x5C9　２行目[n][e]

[msg item_5CA]
[f 0 5 65278][f 2 1]消耗品　0x5CA　１行目 消耗品　0x5CA　２行目[n][e]

[msg item_5CB]
[f 0 5 65278][f 2 1]消耗品　0x5CB　１行目 消耗品　0x5CB　２行目[n][e]

[msg item_5CC]
[f 0 5 65278][f 2 1]消耗品　0x5CC　１行目 消耗品　0x5CC　２行目[n][e]

[msg item_5CD]
[f 0 5 65278][f 2 1]消耗品　0x5CD　１行目 消耗品　0x5CD　２行目[n][e]

[msg item_5CE]
[f 0 5 65278][f 2 1]消耗品　0x5CE　１行目 消耗品　0x5CE　２行目[n][e]

[msg item_5CF]
[f 0 5 65278][f 2 1]消耗品　0x5CF　１行目 消耗品　0x5CF　２行目[n][e]

[msg item_5D0]
[f 0 5 65278][f 2 1]消耗品　0x5D0　１行目 消耗品　0x5D0　２行目[n][e]

[msg item_5D1]
[f 0 5 65278][f 2 1]消耗品　0x5D1　１行目 消耗品　0x5D1　２行目[n][e]

[msg item_5D2]
[f 0 5 65278][f 2 1]消耗品　0x5D2　１行目 消耗品　0x5D2　２行目[n][e]

[msg item_5D3]
[f 0 5 65278][f 2 1]消耗品　0x5D3　１行目 消耗品　0x5D3　２行目[n][e]

[msg item_5D4]
[f 0 5 65278][f 2 1]消耗品　0x5D4　１行目 消耗品　0x5D4　２行目[n][e]

[msg item_5D5]
[f 0 5 65278][f 2 1]消耗品　0x5D5　１行目 消耗品　0x5D5　２行目[n][e]

[msg item_5D6]
[f 0 5 65278][f 2 1]消耗品　0x5D6　１行目 消耗品　0x5D6　２行目[n][e]

[msg item_5D7]
[f 0 5 65278][f 2 1]消耗品　0x5D7　１行目 消耗品　0x5D7　２行目[n][e]

[msg item_5D8]
[f 0 5 65278][f 2 1]消耗品　0x5D8　１行目 消耗品　0x5D8　２行目[n][e]

[msg item_5D9]
[f 0 5 65278][f 2 1]消耗品　0x5D9　１行目 消耗品　0x5D9　２行目[n][e]

[msg item_5DA]
[f 0 5 65278][f 2 1]消耗品　0x5DA　１行目 消耗品　0x5DA　２行目[n][e]

[msg item_5DB]
[f 0 5 65278][f 2 1]消耗品　0x5DB　１行目 消耗品　0x5DB　２行目[n][e]

[msg item_5DC]
[f 0 5 65278][f 2 1]消耗品　0x5DC　１行目 消耗品　0x5DC　２行目[n][e]

[msg item_5DD]
[f 0 5 65278][f 2 1]消耗品　0x5DD　１行目 消耗品　0x5DD　２行目[n][e]

[msg item_5DE]
[f 0 5 65278][f 2 1]消耗品　0x5DE　１行目 消耗品　0x5DE　２行目[n][e]

[msg item_5DF]
[f 0 5 65278][f 2 1]消耗品　0x5DF　１行目 消耗品　0x5DF　２行目[n][e]

[msg item_5E0]
[f 0 5 65278][f 2 1]消耗品　0x5E0　１行目 消耗品　0x5E0　２行目[n][e]

[msg item_5E1]
[f 0 5 65278][f 2 1]消耗品　0x5E1　１行目 消耗品　0x5E1　２行目[n][e]

[msg item_5E2]
[f 0 5 65278][f 2 1]消耗品　0x5E2　１行目 消耗品　0x5E2　２行目[n][e]

[msg item_5E3]
[f 0 5 65278][f 2 1]消耗品　0x5E3　１行目 消耗品　0x5E3　２行目[n][e]

[msg item_5E4]
[f 0 5 65278][f 2 1]消耗品　0x5E4　１行目 消耗品　0x5E4　２行目[n][e]

[msg item_5E5]
[f 0 5 65278][f 2 1]消耗品　0x5E5　１行目 消耗品　0x5E5　２行目[n][e]

[msg item_5E6]
[f 0 5 65278][f 2 1]消耗品　0x5E6　１行目 消耗品　0x5E6　２行目[n][e]

[msg item_5E7]
[f 0 5 65278][f 2 1]消耗品　0x5E7　１行目 消耗品　0x5E7　２行目[n][e]

[msg item_5E8]
[f 0 5 65278][f 2 1]消耗品　0x5E8　１行目 消耗品　0x5E8　２行目[n][e]

[msg item_5E9]
[f 0 5 65278][f 2 1]消耗品　0x5E9　１行目 消耗品　0x5E9　２行目[n][e]

[msg item_5EA]
[f 0 5 65278][f 2 1]消耗品　0x5EA　１行目 消耗品　0x5EA　２行目[n][e]

[msg item_5EB]
[f 0 5 65278][f 2 1]消耗品　0x5EB　１行目 消耗品　0x5EB　２行目[n][e]

[msg item_5EC]
[f 0 5 65278][f 2 1]消耗品　0x5EC　１行目 消耗品　0x5EC　２行目[n][e]

[msg item_5ED]
[f 0 5 65278][f 2 1]消耗品　0x5ED　１行目 消耗品　0x5ED　２行目[n][e]

[msg item_5EE]
[f 0 5 65278][f 2 1]消耗品　0x5EE　１行目 消耗品　0x5EE　２行目[n][e]

[msg item_5EF]
[f 0 5 65278][f 2 1]消耗品　0x5EF　１行目 消耗品　0x5EF　２行目[n][e]

[msg item_5F0]
[f 0 5 65278][f 2 1]消耗品　0x5F0　１行目 消耗品　0x5F0　２行目[n][e]

[msg item_5F1]
[f 0 5 65278][f 2 1]消耗品　0x5F1　１行目 消耗品　0x5F1　２行目[n][e]

[msg item_5F2]
[f 0 5 65278][f 2 1]消耗品　0x5F2　１行目 消耗品　0x5F2　２行目[n][e]

[msg item_5F3]
[f 0 5 65278][f 2 1]消耗品　0x5F3　１行目 消耗品　0x5F3　２行目[n][e]

[msg item_5F4]
[f 0 5 65278][f 2 1]消耗品　0x5F4　１行目 消耗品　0x5F4　２行目[n][e]

[msg item_5F5]
[f 0 5 65278][f 2 1]消耗品　0x5F5　１行目 消耗品　0x5F5　２行目[n][e]

[msg item_5F6]
[f 0 5 65278][f 2 1]消耗品　0x5F6　１行目 消耗品　0x5F6　２行目[n][e]

[msg item_5F7]
[f 0 5 65278][f 2 1]消耗品　0x5F7　１行目 消耗品　0x5F7　２行目[n][e]

[msg item_5F8]
[f 0 5 65278][f 2 1]消耗品　0x5F8　１行目 消耗品　0x5F8　２行目[n][e]

[msg item_5F9]
[f 0 5 65278][f 2 1]消耗品　0x5F9　１行目 消耗品　0x5F9　２行目[n][e]

[msg item_5FA]
[f 0 5 65278][f 2 1]消耗品　0x5FA　１行目 消耗品　0x5FA　２行目[n][e]

[msg item_5FB]
[f 0 5 65278][f 2 1]消耗品　0x5FB　１行目 消耗品　0x5FB　２行目[n][e]

[msg item_5FC]
[f 0 5 65278][f 2 1]消耗品　0x5FC　１行目 消耗品　0x5FC　２行目[n][e]

[msg item_5FD]
[f 0 5 65278][f 2 1]Especialidad de un lugar de ramen en la[n]estaci吋n de Iwatodai. [f 0 1 4]Restaura 50% PS[f 0 1 0][n]. (Grupo)[n][e]

[msg item_5FE]
[f 0 5 65278][f 2 1]Especialidad de un restaurante chino en Inaba.[n][f 0 1 4] Restaura todos los PS[f 0 1 0][n]. (1 fila)[n][e]

[msg item_5FF]
[f 0 5 65278][f 2 1]Especialidad de un caf de callej吋n en Yongen-[n]Jaya. [f 0 1 4]Restaura 50% PE[f 0 1 0][n]. (Grupo)[n][e]

