[msg S00_DG_GIMMICK_SWITCH_MS]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Gir姻 el interruptor.[n][f 1 1][e]

[msg S01_DG_GIMMICK_SWITCH_MS]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Has girado firmemente el interruptor a[n]su otra posici吋n.[n][f 1 1][e]

[msg S02_DG_GIMMICK_SWITCH_MS]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]El interruptor ha sido girado.[n][f 1 1][e]

[msg S03_DG_GIMMICK_SWITCH_MS]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]El interruptor ya ha sido girado firmemente[n]a su otra posici吋n.[n][f 1 1][e]

[msg S04_DG_GIMMICK_CHANGE_SW]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Gir吋 el interruptor a ENCENDIDO.[n][f 1 1][e]

[msg S05_DG_GIMMICK_CHANGE_SW]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Gir吋 el interruptor a APAGADO.[n][f 1 1][e]

[msg S06_DG_GIMMICK_CHANGE_SE]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Los reflectores han sido apagados.[n][f 1 1][e]

[msg S07_DG_GIMMICK_CHANGE_SE]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Los reflectores ya est茨n apagados.[n][f 1 1][e]

[msg S08_DG_GIMMICK_CHANGE_SE]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]El patr吋n de los reflectores ha cambiado.[n][f 1 1][e]

[msg S09_DG_GIMMICK_KAITENSAK]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Rot吋 la jaula.[n][f 1 1][e]

[msg S10_DG_GIMMICK_DENKISAKU]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]La puerta el姻ctrica ha sido apagada[n]temporalmente.[n][f 1 1][e]

[msg S11_DG_GIMMICK_DENKISAKU]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]El poder ya ha sido apagado.[n][f 1 1][e]

[msg S12_DG_GIMMICK_SERI_CHAN]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Los ascensores fueron utilizados.[n][f 1 1][e]

[msg S13_DG_GIMMICK_BOUHU_OPE]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]La direcci吋n del viento cambi吋.[n][f 1 1][e]

[msg S14_DG_GIMMICK_SERI_FIRS]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Los ascensores fueron utilizados.[n][f 1 1][e]

[msg S15_DG_GIMMICK_BOUHU_FIR]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 9]Se escucha el sonido de maquinaria...[n][f 1 1][e]

