[msg MSG_000 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 1][f 3 1 1 0 0 24063][f 6 1 2 0 0 0]斡Ah! 斡夷Qu姻 es esto?![n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Parece ser una c茨mara vieja... pero,[n]斡qu姻 dise隠o tan refinado![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]La alarma de arte de Fox ha vuelto a[n]sonar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 100 0][f 3 1 1 0 0 26592][f 3 1 6 0 0 500]斡Vamos! No hay tiempo para jugar, Estamos[n]a punto de salvar a Queen y Noir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Podr胤a llevarnos a una batalla, as胤 que[n]ser茨 mejor que tengas cuidado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]...夷Joker? 夷Pasa algo? Parec胤as[n]distra胤do.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pareces tener mucha curiosidad por esa[n]c茨mara...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1][f 4 6 20 8 32 0][f 3 1 1 0 0 0]Percibo un tipo de poder misterioso de[n]ella...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tengo la sensaci吋n de que podr胤amos[n]volver al cine con ella...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tal vez sea buena idea volver al cine[n]y reagruparnos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puedes guardar y salir del laberinto[n]aqu胤.[n][f 1 3 65535][f 1 1][e]

