[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 1][f 3 1 1 0 0 28019]...夷Es una escalera? Me pregunto hacia[n]donde conduce.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Est茨 bastante alto all胤 arriba...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 0]Tal vez puedas alcanzarlo, Skull, has[n]entrenado tus piernas con el equipo[n]de seguimiento...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Podrias saltar y alcanzarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 21082]斡De ninguna manera alcanzar胤a eso![n]Adem茨s... me especialic姻 en correr.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003_05 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷En serio?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Estaba ansioso por ver un gran salto...[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]Es imposible.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Intenta saltar por nosotros, Skull.[f 2 7 1 20 2 32][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 6][f 3 1 1 0 0 21091][f 6 1 2 0 0 9]夷Verdad? No hay manera de que alcance[n]algo as胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 8 1 6][f 3 1 1 0 0 21036][f 6 1 2 0 0 0]斡Ey, deja de pedirme cosas imposibles![n]斡夷Qu姻 crees que soy, un p茨jaro loco?![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 7 11 0 0][f 4 6 28 6 1 1][f 3 1 1 0 0 0]Tal vez sea el acceso hacia alg雨n lado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008_5 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Pero en este momento no sirve de nada[n]especular. Sigamos avanzando por ahora.[n][f 1 3 65535][f 1 1][e]

