[msg MSG_000 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 35 1 0 1][f 4 6 7 0 0 3][f 3 1 1 0 0 7010][f 6 1 2 0 0 4]Me preguntaba, ya sabes... 夷Puedes[n]pelear?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35009]NO. NO TENGO FUNCIONES DE COMBATE. POR[n]FAVOR RECU畏RDALO.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26031]斡No te preocupes! Todo lo que tienes[n]que hacer es seguirnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 6][f 3 1 1 0 0 10067][f 6 1 2 0 0 6]斡S胤, d姻janos las peleas![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]夷ME LLEVAN CON USTEDES, A PESAR DE QUE[n]NO PUEDO PELEAR? NO LES SOY DE[n]UTILIDAD. 夷POR QU畏?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Nos beneficias en algo.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Solo olv胤dalo y s胤gueme.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35014]CLARO, PUEDO SERVIR COMO ESCUDO...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 6][f 3 1 1 0 0 26135][f 6 1 2 0 0 6]斡S-sin escudos! 斡Nadie te pidi吋 que[n]hicieras eso! Solo s胤guenos, 夷est茨 bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35007]PERO...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 6][f 3 1 1 0 0 7107][f 6 1 2 0 0 6]No pienses en los detalles. 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 10 12 0 3][f 3 1 1 0 0 10018][f 6 1 2 0 0 4]Espera... nosotros podemos volver, 夷pero[n]qu姻 hay de ella?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 1][f 3 1 1 0 0 0]Ahora que lo dices, 夷ella puede dejar[n]esta pel胤cula?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 3][f 3 1 1 0 0 0]No tengo idea de si habr胤a o no alg雨n[n]efecto malo en ella...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 26009]La maquinaria es muy delicada. No debemos[n]acercarla a ning雨n escenario para[n]el que no est姻 dise隠ada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Deber胤amos tratar de esconderla en[n]alguna parte? 夷Y si la atrapan esos[n]robots de seguridad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 1][f 3 1 1 0 0 35008]SI ESTO LES PREOCUPA, CREO QUE TENGO[n]UNA SOLUCI遺N.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]NO DEBER緯A SER IDENTIFICABLE PARA LOS[n]ROBOTS DE SEGURIDAD =SI SUSPENDO MIS[n]OPERACIONES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Suspender sus operaciones? 夷Te refieres[n]a apagarte?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Robot Con Cinta]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35008]NO. TENGO UN MODO REPOSO. PUEDO SUSPENDER[n]TEMPORALMENTE MIS OPERACIONES.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 3][f 3 1 1 0 0 24047]夷Oh? Eso suena 雨til. Entonces, simplemente[n]presionar姻 aqu胤 y activar姻…[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Oye! 斡No vayas a su configuraci吋n sin[n]su permiso![n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 12 0 3][f 3 1 1 0 0 25009]Incluso si eres capaz de evitar sus[n]sensores, me preocupa dejarte aqu胤 al[n]descubierto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Por qu姻 no te escondes en alg雨n lugar[n]antes de activar tu modo reposo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1066]Estoy de acuerdo. Definitivamente ser胤a m茨s seguro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, nuestro pr吋ximo objetivo es[n]encontrar a los miembros restantes de[n]SEES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 3 1 1 0 0 0]斡Vamos![n][f 1 3 65535][f 1 1][e]

