[msg MSG_000]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 3 1 1 0 0 0]Distrito de Cine, Depths...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 3][f 3 1 1 0 0 1][f 6 1 2 0 0 1]Espero que est姻s listo, maldita sea[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 6]... 夷Qu姻 demonios? 斡Nadie est茨 aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 3][f 6 1 2 0 0 4]Aw hombre, 夷nos equivocamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 99 0][f 3 1 1 0 0 4][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Todos! 斡Mira ah胤 arriba![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 1][f 3 1 1 0 0 5]No puedes tener suficiente de tu[n]interferir aqu胤, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 1 3][f 3 1 1 0 0 6][f 6 1 2 0 0 6]斡Enlil![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 6 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 4]Es incomprensible para m胤, 夷por qu姻[n]est茨s poniendo tanto esfuerzo en luchar por[n]completos extra隠os?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8]Si hubieras escuchado mi palabra y[n]regresado a tus mundos, todas tus luchas[n]aqu胤 ser胤an terminadas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 9]Puedo entender la sensaci吋n de querer[n]huir, y no querer salir lastimado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 10][f 6 1 2 0 0 6]斡Pero por eso no puedo alejarme de lo[n]que est茨s haciendo![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 1 6][f 3 1 1 0 0 11][f 6 1 2 0 0 6]Si huyera de esto, no estar胤a actuando[n]en mis creencias, 斡y nunca har胤a algo as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 2 0 0][f 3 1 1 0 0 12][f 6 1 2 0 0 4]夷En serio? 夷Y...? 夷Qu姻 puedes hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 24 0 1 0][f 3 1 1 0 0 13][f 6 1 2 0 0 6]Ha llegado el momento: empuja nuestro[n]plan en su cara, Joker![n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3]斡Esta tarjeta de llamada es para ti![f 2 7 1 20 0 2][e]
[f 0 5 65278][f 2 1]斡Vamos a tomar tu pel胤cula![f 2 7 1 20 0 2][e]

[msg MSG_013 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 1 2 0][f 3 1 1 0 0 14]"Madame Enlil, comisario de los cines[n]de enga隠o..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15]"Desde que juegas pel胤culas que abogan[n]por la auto-abuso y enga隠an a los[n]miembros de la audiencia para confundir la[n]insensatez por la paz..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16]"Te robaremos esas pel胤culas[n]distorsionadas. Firmado, el Ladrones Fantasma."[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Enlil]]
[f 0 5 65278][f 2 1][f 4 6 39 0 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 4]夷Funciones distorsionadas? 夷Qu姻 est茨s[n]haciendo aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 18]A menos que cambiemos las creencias de[n]estos corredores de Cine, alejarlos[n]para siempre ser茨 imposible.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19]Por eso tuvimos que dise隠ar un plan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 14 1 6][f 3 1 1 0 0 20]S胤, encontramos una manera de cambiar[n]radicalmente los corazones de todos aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 12 1 3][f 3 1 1 0 0 21][f 6 1 2 0 0 0]斡Oracle! 夷Todo listo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 22][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡S胤! 斡Listo para seguir con este fin![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 1 1][f 4 6 21 6 1 3][f 3 1 1 0 0 23]斡Muy bien! D姻jalos, Hikari![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 24][f 6 1 2 0 0 6]Mmhm! 斡Hag茨moslo todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Enlil]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 39 10 0 1][f 3 1 1 0 0 25][f 6 1 2 0 0 0]...?[n][f 1 3 65535][f 1 1][e]

