[msg MSG_TUTORIAL_FOE_1]
[f 0 5 65278][f 2 1]Los movimientos FOE se pueden ver [f 0 1 2] en el mapa[f 0 1 0][n].[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Los FOEs seguir茨n movi姻ndose incluso [f 0 1 2][n]mientras est茨s en combate con otros enemigos[f 0 1 0][n].[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si un FOE te alcanza mientras luchas contra[n]otros enemigos, se unir茨 a la batalla [f 0 1 0][n]![n][f 1 1][e]

