[msg MSG_TUTORIAL_ENEMY_UI]
[f 0 5 65278][f 2 1]El [f 0 1 2]indicador de proximidad[f 0 1 0] muestra el [f 0 1 2]riesgo de que se produzca una batalla[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Gris significa que estás [f 0 1 2]seguro[f 0 1 0]. A medida que te mueves, se vuelve verde, luego amarillo y finalmente rojo.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Rojo significa que [f 0 1 2]una batalla es inminente[f 0 1 0], ¡así que no pierdas de vista este indicador![n][f 1 1][e]

