[msg MSG_SC_TUTORIAL_0]
[f 0 5 65278][f 2 1]Si tocas un 胤cono y lo arrastras mientras[n]la herramienta [f 0 1 2]l茨piz [f 0 1 0]est茨 seleccionada...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Entonces puedes colocar ese[f 0 1 2] 胤cono [f 0 1 0]en el mapa.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Por ejemplo, puedes marcar atajos con su propio [f 0 1 2][n]胤cono[f 0 1 0] designado.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Ese 胤cono mostrar茨 [f 0 1 2]autom茨ticamente[f 0 1 0] la[n]direcci吋n del atajo.[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_1]
[f 0 5 65278][f 2 1]Cualquier 胤cono colocado por error puede ser[n]eliminado arrastr茨ndolo hasta el [f 0 1 2]cubo de basura[f 0 1 0].[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_2]
[f 0 5 65278][f 2 1]Un error al dibujar paredes o pisos se corrige con[n]el bot吋n[f 0 1 2] DESHACER[f 0 1 0].[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_3]
[f 0 5 65278][f 2 1][n]Tu mapa tiene muchas otras funciones[n]tambi姻n. Los detalles se pueden encontrar en la secci吋n[n][f 0 1 2]AYUDA[f 0 1 0] en la esquina inferior derecha del mapa.[n]斡No olvides completarlo mientras exploras; te lo agradecer茨s m茨s adelante![n][f 1 1][e]

