[msg MSG_TUTORIAL_QUEST_MAP_0]
[f 0 5 65278][f 2 1][n]Si ingresas a una pel胤cula a trav姻s de una proyecci吋n[n]especial, el [f 0 1 2]laberinto cambiar茨[f 0 1 0]... Algunas puertas y atajos[n]estar茨n sellados Algunas 茨reas ser茨n inaccesibles,[n]como si nunca hubieran existido.[n][n]斡[f 0 1 2]Nuevos Lugares de Tesoro, cofres y FOEs estar茨n en[n]el laberinto[f 0 1 0]![n][f 1 1][e]

[msg MSG_TUTORIAL_QUEST_MAP_1]
[f 0 5 65278][f 2 1]Las 茨reas inaccesibles se colorear茨n [f 0 1 2]de rojo[f 0 1 0][n]y estar茨n [f 0 1 2]marcadas con un 胤cono especial[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]斡Aseg雨rate de mirar la pantalla inferior cuando[n]explores una proyecci吋n especial![n][f 1 1][e]

[msg MSG_TUTORIAL_QUEST_MAP_2]
[f 0 5 65278][f 2 1]Tambi姻n ver茨s una [f 0 1 2]paleta de proyecci吋n especial[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Los 胤conos de esta paleta [f 0 1 2]solo se pueden colocar[n]durante proyecciones especiales[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Deber胤as usar estos para indicar cualquier [f 0 1 2]cambio[n]causado por la proyecci吋n especial[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sin embargo, una advertencia:[n][f 1 1][e]
[f 0 5 65278][f 2 1]Estos 胤conos de la paleta no se pueden colocar[n]encima de ning雨n 胤cono colocado previamente.[n][f 1 1][e]
[f 0 5 65278][f 2 1]斡Aseg雨rate de aprovechar la paleta al m茨ximo para[n]sacar el mayor provecho de las proyecciones[n]especiales![n][f 1 1][e]

