[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]En los laberintos, es posible que te encuentres con[n][f 0 1 2]Sombras doradas especiales[f 0 1 0].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1][n]Cuando los derrotes, podr胤as recibir [f 0 1 2]recompensas[n]mayores de las que obtendr胤as de Sombras normales[f 0 1 0].[n][n]Adem茨s, las Sombras doradas pueden tener habilidades[n]y resistencias especiales, as胤 que recuerda Analizarlas[n]mientras peleas.[n][f 1 1][e]

