[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]　[n]In addition to their [f 0 1 2]main Persona[f 0 1 2], each[n]teammate can have an additional one: a[n]freely interchangeable [f 0 1 2]Sub-Persona[f 0 1 0].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes04]
[f 0 5 65278][f 2 1]Open the menu with the [f 0 1 2]X Button[f 0 1 0] and[n]select [f 0 1 2]PERSONA[f 0 1 0] to assign Sub-Personas.[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1]This lets each teammate have the skills of[n]two Personas: the main and the sub.[n][f 1 1][e]

[msg BTL_TUTORIAL_mes03]
[f 0 5 65278][f 2 1]A Sub-Persona's HP and SP are added to[n]that of the party member as [f 0 1 2]a bonus[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Bonus HP and SP will be [f 0 1 2]automatically[n]replenished at the start of any battle[f 0 1 0]![n][f 1 1][e]

[msg BTL_TUTORIAL_mes05]
[f 0 5 65278][f 2 1]　[n]Assigning a Sub-Persona whose [f 0 1 2]level is[n]very low[f 0 1 0] compared to the main Persona[n]will [f 0 1 2]reduce the power of some attack skills[f 0 1 0].[n]　[n]Always try to give your teammates a Sub-[n]Persona with a level close to that of their[n]main Persona.[n][f 1 1][e]
[f 0 5 65278][f 2 1]　[n]You can assign Sub-Personas at [f 0 1 2]any time[n]while you're not in battle[f 0 1 0]. But once you[n]are in battle, you can't use any Sub-[n]Personas that weren't assigned to someone.[n][f 1 1][e]

