[msg MSG_BTL_TUTORIAL_001]
[f 0 5 65278][f 2 1]　Recupere de sus heridas de batalla a trav姻s[n]de varias opciones en el men雨 [f 0 1 2]Bot吋n X[f 0 1 0][n].[n][f 1 1][e]
[f 0 5 65278][f 2 1]　　Utilice [f 0 1 2] elementos de curaci吋n[f 0 1 0][n], que se enumeran en la secci吋n ITEM[n]acertadamente llamada. Recuerden, estos[n]ser茨n consumidos cuando los usen.[n][f 1 1][e]
[f 0 5 65278][f 2 1]　　Bajo SKILL, usted puede utilizar las habilidades[n]de curaci吋n [f 0 1 0] de sus compa隠eros[n]de equipo. Hacer esto consumir茨[n]algunos de sus SP.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cuando la HP de los aliados golpea 0, ellos[n]son [f 0 1 2] inconsciente[f 0 1 0], y permanecer茨 as胤 hasta que se utilice un elemento de reactivaci吋n o habilidad, o hasta que salga del laberinto. Cuando todos los miembros del partido pierden conciencia, es [f 0 1 2][n][n][n][n][n]Game Over[f 0 1 0],[n]as胤 que ten cuidado![n][f 1 1][e]

