[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]Los compa隠eros de equipo en reserva pueden unirse[n]a la batalla mediante los [f 0 1 2]ataques de seguimiento[f 0 1 0].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1][n]Los ataques de seguimiento pueden ocurrir despu姻s de[n]que un miembro del grupo realiza un golpe cr胤tico,[n]o si el ataque tuvo afinidad con la debilidad del enemigo.[n][n]Los ataques de seguimiento tienen una alta probabilidad[n]de derribar a las Sombras[f 0 1 0].[n][f 1 1][e]

