[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]Algunas Sombras tienen una barrera especial[n]conocida como el [f 0 1 2]Afinity Barrier[f 0 1 0][n].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1]　Cuando su Barrera de Afinidad est茨 levantada,[n]una Sombra es resistente a las afinidades de sus ataques. Sin embargo, si usted [f 0 1 2][n][n]deal suficiente da隠o[f 0 1 0][n]o [f 0 1 2] recuerda algunas otras condiciones[f 0 1 0][n], la barrera se desactivar茨,[n]y la resistencia de la Sombra[n]cambiar茨.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cuando el Affinity Barrier se desactiva, el[n][f 0 1 2]Shadow cambiar茨 visiblemente[f 0 1 0][n]. Esto tambi姻n se reflejar茨 en los[n]datos de la Sombra si lo analiza.[n][f 1 1][e]

