[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]Algunas habilidades pueden infligir [f 0 1 2]estados alterados[f 0 1 0], que son[n]efectos negativos en los[n]personajes.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Los estados alterados pueden evitar que alguien[n]act雨e, o incluso infligir da隠o.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si los aliados est茨n afectados por estados[n]alterados, 斡intenta curarlos lo antes posible![n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1][n]Adem茨s, ten en cuenta que no solo tu[n]grupo es vulnerable a los estados alterados;[n]斡tambi姻n puedes infligirlos a las Sombras! Busca[n]entre los miembros de tu grupo ataques o habilidades[n]que tengan la posibilidad de causar un estado alterado, y 雨salas en tu beneficio.[n][f 1 1][e]

