[msg EVE_FLAG_QUEST_TUTO_TXT_]
[f 0 5 65278][f 2 1]Al seleccionar [f 0 1 2]Issue Ticket[f 0 1 0][n], puede asistir a una proyección especial. Como el nombre implica, es diferente de una pel胤cula normal! Recibir estas misiones especiales seleccionando [f 0 1 2][n][n][n][n]Ticket[f 0 1 0] en el men雨 [f 0 1 2]Cine[f 0 1 0][n].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Adem茨s, [f 0 1 2] todos los que se introducen en las proyecciones especiales ser茨n motivados[f 0 1 0][n][n], por lo que es una[n]oportunidad para experimentar con su maquillaje[n]de fiesta.[n][f 1 1][e]

