[msg BTL_TUTORIAL_mes01]
[f 0 5 65278][f 2 1]En proyecciones especiales, a medida[n]que crece el v胤nculo de sus aliados,[n]pueden adquirir [f 0 1 2] Habilidades de[n]un胤sono[f 0 1 0].[n][f 1 1][e]

[msg BTL_TUTORIAL_mes02]
[f 0 5 65278][f 2 1]　Un Unison Skill es como un ataque de[n]seguimiento, pero realizado por algunos[n]miembros del partido en lugar de miembros[n]de respaldo. Las Habilidades de Envenenamiento pueden tener resultados dram茨ticos como [f 0 1 2] da隠o pesado[f 0 1 0] o [f 0 1 2] una alta probabilidad de golpes enemigos[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cuanto m茨s Unison Skills tu equipo[n]adquiere a trav姻s de bonos aliados, mayor es[n]la posibilidad de poder usar uno.[n]Adquire Unison Skills al asumir el desaf胤o de [f 0 1 2] proyecciones especiales[f 0 1 0]![n][f 1 1][e]

