[msg msg000_MSG]
[f 0 5 65278][f 2 1][n]Puedes realizar una [f 0 1 2]Fusi吋n de Personas[f 0 1 0], donde fusionas[n]varias Personas para invocar una nueva.[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]Perder茨s las Personas originales[f 0 1 0], pero la resultante[n]heredar茨 algunas de sus habilidades y su nivel podr胤a[n]ser m茨s alto[f 0 1 2](aunque no pueden superar tu nivel)[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]Tu propio nivel se llama [f 0 1 2]Nivel de Comod胤n[f 0 1 0], y es el m茨s[n]alto en el grupo.[n][f 1 1][e]

[msg msg001_MSG]
[f 0 5 65278][f 2 1][n]Tambi姻n puedes evitar perder una Persona en la fusi吋n[n]haciendo una copia de ella antes.[n][n]En el men雨 de Fusi吋n de 2 Capas, presiona el [f 0 1 2]Bot吋n X[f 0 1 0][n]mientras la Persona est姻 seleccionada, y luego[n]puedes activar o desactivar la opci吋n de [f 0 1 2]copia[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]Si no haces una copia de ninguna de las Personas,[n]entonces la fusi吋n no tendr茨 costo.[n][n]Simplemente se perder茨n.[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]Si decides hacer una copia de una Persona, entonces[n]tendr茨s que [f 0 1 2]pagar yenes para fusionarla[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]El precio ser茨 el mismo que cuando invocas una[n]Persona desde el "Persona Film".[n][n]斡Prueba diferentes combinaciones para fortalecer[n]tu grupo![n][f 1 1][e]

