[msg EVE_FLAG_QUEST_TUTO_TXT_]
[f 0 5 65278][f 2 1][n]En la [f 0 1 2]taquilla[f 0 1 0], puedes aceptar una solicitud de proyecci吋n especial. Se te asignar茨 una misi吋n y, si logras completarla, recibir茨s una [f 0 1 2]recompensa[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1][n]La proyecci吋n especial terminar茨 cuando completes la misi吋n, y las proyecciones especiales que han terminado no pueden volver a ser accedidas. Por eso, vale la pena buscar cada rinc吋n del laberinto antes de cumplir la misi吋n. Por supuesto, tambi姻n puedes desbloquear m茨s proyecciones especiales al continuar tu viaje o al [f 0 1 2]cumplir ciertos requisitos[f 0 1 0].[n][f 1 1][e]

