[msg msg001_MSG]
[f 0 5 65278][f 2 1]Solo los accesorios tienen efectos de afinidad. Aumentan la evasi吋n a los ataques de afinidad.[n][f 1 1][e]

[msg msg002_MSG]
[f 0 5 65278][f 2 1]Las armas con un bono de estado alterado a隠adir茨n ese efecto a tu ataque, lo que podr胤a causar que los enemigos se vean afectados por el estado alterado.[n][f 1 1][e]

[msg msg003_MSG]
[f 0 5 65278][f 2 1]Si la armadura tiene un bono de estado alterado, aumenta tu resistencia a ese estado alterado.[n][f 1 1][e]

[msg msg004_MSG]
[f 0 5 65278][f 2 1]Los efectos de "aumento de estado" aumentan tus estad胤sticas, ya sea que provengan de armas o armaduras.[n][f 1 1][e]

[msg msg005_MSG]
[f 0 5 65278][f 2 1]Las armas con efectos de perforaci吋n o salpicadura [n]pueden golpear a m雨ltiples objetivos.[n][f 1 1][e]

[msg msg006_MSG]
[f 0 5 65278][f 2 1]Hay otros efectos que no funcionan [n]durante las batallas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Estos efectos otorgan bonificaciones a [n]los resultados posteriores a la batalla.[n][f 1 1][e]

