[msg msg001_MSG]
[f 0 5 65278][f 2 1]S吋lo los accesorios tienen efectos de[n]afinidad. Aumentan la evasi吋n a los[n]ataques de afinidad.[n][f 1 1][e]

[msg msg002_MSG]
[f 0 5 65278][f 2 1]Las armas con un bono de la enfermedad[n]del estado a隠adir茨n eso a su ataque,[n]para que los enemigos puedan verse[n]afectados con el malestar.[n][f 1 1][e]

[msg msg003_MSG]
[f 0 5 65278][f 2 1]Si la armadura tiene una bonificaci吋n[n]de la enfermedad de estado, aumenta su[n]resistencia a esa dolencia.[n][f 1 1][e]

[msg msg004_MSG]
[f 0 5 65278][f 2 1]Los efectos de aumento del estado[n]elevan sus estad胤sticas, ya sean de armas o armaduras.[n][f 1 1][e]

[msg msg005_MSG]
[f 0 5 65278][f 2 1]Las armas con efectos de perforaci吋n o[n]salpicadura pueden alcanzar m雨ltiples objetivos.[n][f 1 1][e]

[msg msg006_MSG]
[f 0 5 65278][f 2 1]Hay otros efectos que no funcionan[n]durante las batallas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Estos efectos otorgan primas a los[n]resultados post-battle.[n][f 1 1][e]

