[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 741][f 6 1 3 0 0 2]Bueno entonces. Parece que ha terminado[n]el momento de la conversaci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 742][f 6 1 3 0 0 2]Ahora, solo puedes enfocarte en doblar[n]tu poder en su mayor medida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 743][f 6 1 3 0 0 2]Te lo advierto, no soy extra隠o en este[n]tipo de agitaci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 744][f 6 1 3 0 0 2]夷Esto? No, no es nada.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 745][f 6 1 3 0 0 2]No te preocupes por m胤... Te aconsejo[n]que vengas conmigo como si quisieras matar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 746][f 6 1 2 0 0 7][f 6 1 3 0 0 2]Esto va magn胤ficamente. 斡Me atrevo a[n]decir que me estoy llevando un poco![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 747][f 6 1 3 0 0 2]*chuckle* Parece que ten胤a raz吋n. Tu[n]esp胤ritu es notable.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 748][f 6 1 3 0 0 2]Sin embargo, recuerde que juzgar mal[n]una batalla, especialmente esta tarde,[n]ser胤a un desleal a su poder.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 749][f 6 1 3 0 0 2]Bien hecho. Tu poder es muy excelente.[n][f 1 3 65535][f 1 1][e]

