[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 6 1 2 0 0 7][f 3 1 1 0 0 1]斡Otra brillante victoria, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 1 0][f 3 1 1 0 0 2]Mementos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3]Entonces, 夷este lugar fue formado por el[n]inconsciente colectivo de la sociedad? Un[n]palacio de toda la poblaci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Esto parece ser otra forma diferente del[n]mundo cognitivo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 1][f 3 1 1 0 0 5]夷Qui姻n sabe lo que hay en sus profundidades?[n]Golpea el coraz吋n de mi curiosidad[n]intelectual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 0][f 3 1 1 0 0 6]Por otro lado, es bastante aterrador...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 3][f 4 6 22 12 0 1][f 3 1 1 0 0 7]Todav胤a recuerdo que odiaba este lugar cuando[n]empezamos a venir aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 1 1 1][f 4 6 26 0 0 3][f 3 1 1 0 0 8]Si seguimos perdiendo el tiempo as胤, vamos[n]a acabar encontr茨ndonos con algunos[n]enemigos. Mona, transformate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 23 1 1 0][f 3 1 1 0 0 9]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 0][f 3 1 1 0 0 10]夷Monaaa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 27 0 0 6][f 3 1 1 0 0 11]夷Qu姻 pasa, Mona?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 1 0][f 3 1 1 0 0 12]斡Oh! Lo siento. Es s吋lo que Mementos se[n]siente... diferente de lo habitual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 4 6 25 0 0 0][f 3 1 1 0 0 13]夷En qu姻 sentido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 0 0 3][f 4 6 21 12 0 1][f 3 1 1 0 0 14]...夷No es siempre as胤? Oye, Joker, 夷qu姻 te[n]parece?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1]Es el Mementos de siempre.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Parece diferente.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Ni idea.[f 2 7 1 20 6 32][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 15]Yo tambi姻n lo creo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 3][f 4 6 24 6 0 1][f 3 1 1 0 0 16]夷Eh? Parece que me falta la experiencia[n]necesaria para percibirlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 17]Me parece lo mismo de siempre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 18]Yo tampoco tengo ni idea.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 2 0 0 3][f 4 6 23 6 0 1][f 3 1 1 0 0 19]Mmm... supongo que es s吋lo mi imaginaci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 1][f 3 1 1 0 0 20]De todos modos, 斡es la hora de transformarse![n]斡Atr茨s, todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 0 0][f 3 1 1 0 0 21]No puedo creer que este gato se convierta en[n]un coche... Qu姻 mundo tan fascinante es[n]este.  [n][f 1 3 65535][f 1 1][e]

