[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 6]斡Realmente PODEMOS usar[n]nuestras Personas aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 4]Ya que todav胤a estamos con atuendo de[n]ladr案n fantasma, 夷significa eso que este[n]lugar est茨 dentro de Mementos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 1][f 3 1 1 0 0 3]Excepto que no pod胤amos usar[n]nuestras armas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 4]Correcto, se convirtieron en [n]modelos de armas ordinarias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 1][f 3 1 1 0 0 5]夷En serio? Tal vez s案lo seas t位.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 3 0 0 1][f 6 1 2 0 0 0]Espera, 夷qu姻, la m胤a tambi姻n?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7]夷As胤 que podemos usar nuestras[n]Personas, pero no nuestras armas?[n]夷Qu姻 demonios pasa con este lugar?[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]夷No hay ning位n efecto cognitivo aqu?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Todav胤a estamos en Mementos.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No estoy seguro...[f 2 7 1 20 6 32][e]

[msg MSG_007 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]Eso parece ser el caso, pero si es as胤,[n]夷a d案nde hemos ido exactamente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 9][f 6 1 2 0 0 4]Pero, ya que nuestras armas no funcionan,[n]夷Eso no significa que no estamos[n]en Mementos?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 10]夷Podr胤a este lugar no estar afectado[n]por la cognicin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 0 1 1][f 3 1 1 0 0 11][f 6 1 2 0 0 6]斡Oye, estoy sintiendo otra Sombra![n]斡Viene hacia aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 1 0][f 3 1 1 0 0 12]夷Hay m茨s aqu?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13][f 6 1 2 0 0 10][f 6 1 3 0 0 1]Eso no es todo, este es muy diferente[n]de esos matorrales... Parece mucho m茨s[n]peligroso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 1 6][f 3 1 1 0 0 14][f 6 1 2 0 0 0]夷Qu姻 est茨 pasando aqu?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 15]No s姻, pero deber胤amos evitar[n]el contacto con 姻l.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16][f 6 1 2 0 0 6]斡Intentar姻 navegar hacia donde no[n]hay sombras![n][f 1 3 65535][f 1 1][e]

