[msg MSG_000 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 3][f 3 1 1 0 0 1][f 6 1 2 0 0 3]Esto es s吋lo... Es tan horrible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 4 0 1][f 3 1 1 0 0 2][f 6 1 2 0 0 2]*Growl* 斡Barco, corteza![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 3]Koromaru-san parece no gustarle tambi姻n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Dijo: "Hikari-san es Hikari-san. 夷Por qu姻 se[n]rechaza ese hecho?"[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 5]Basado en la apariencia de Hikari, este[n]incidente parece haber ocurrido[n]recientemente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6][f 6 1 2 0 0 3]Pensar que hab胤a estado en el extremo receptor[n]de tanta presi吋n de sus parientes...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 40 14 1 3][f 3 1 1 0 0 7]Soy diferente de todas las otras chicas...[n]Soy extra隠o... Una anormalidad no buena...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 1 1][f 3 1 1 0 0 8][f 6 1 2 0 0 6]斡Eso no importa! Soy un poco diferente de lo[n]normal...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9]斡Pero todos todav胤a me han aceptado como su[n]amigo![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 15 1 0][f 3 1 1 0 0 10]A雨n as胤, yo... Soy un error vivo, causando[n]problemas para todos los dem茨s...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 2 1][f 3 1 1 0 0 11][f 6 1 2 0 0 10]斡Eso no es verdad! 斡La individualidad no es[n]un error![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 0 0 0][f 3 1 1 0 0 12]Todos dicen que soy raro... Dicen que llamarlo[n]"individualidad" es s吋lo una excusa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 1 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 4]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 16 1 0][f 3 1 1 0 0 14]Mi sue隠o de por vida me llevar茨 a ninguna[n]parte. Ni siquiera puedo corregir mis[n]propios errores.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 40 12 1 0][f 3 1 1 0 0 15][f 6 1 2 0 0 6]En el fondo, sin embargo... Yo... 斡No quiero[n]suprimir mi verdadero yo![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 16]As胤 es... Siempre estaba bajo tal estr姻s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]夷Qu姻 significa ser normal? 夷Qu姻 soy?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 18]Empec姻 a perder de vista lo que mi existencia[n]realmente debe ser...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 4 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19]斡No puedes perderte as胤![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20]La ansiedad de sentirse como la 雨nica que es[n]diferente... Realmente lo entiendo[n]ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 21]Para ser honesto... He estado asustado todo[n]el tiempo que he estado aqu胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]Soy la irregularidad aqu胤... 斡Soy el 雨nico[n]diferente de todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_013_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 23]Cuanto m茨s pens姻 en por qu姻 es eso, m茨s[n]empec姻 a sentirme como todo sobre m胤 es[n]falso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 4][f 3 1 1 0 0 24][f 6 1 27 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 25]Pero entonces, todos los que conoc胤 me[n]aceptaron como soy.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 40 1 0 4][f 3 1 1 0 0 26]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 27]Hikari-chan, que no s吋lo se aplica a m胤. Lo[n]mismo va para ti, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Solo s姻 t雨 mismo, Hikari.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Todos nos gustas como t雨.[f 2 7 1 20 2 32][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 28]Mmhm. S吋lo eres t雨, Hikari-chan. Eres nuestro[n]precioso amigo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Por eso vinimos hasta aqu胤 para encontrarte.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 40 18 1 0][f 3 1 1 0 0 30][f 6 1 2 0 0 1]...![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 0][f 3 1 6 0 0 500][f 3 1 1 0 0 31][f 6 1 2 0 0 6]斡Tiene raz吋n, Hikari! 斡Salgamos de aqu胤 y[n]todos vayan juntos a casa![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 19 1 0][f 4 6 81 16 2 0][f 3 1 1 0 0 32][f 6 1 2 0 0 6]As胤 es... 斡Quer胤a hacer algo![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [El T胤o De Hikari]]
[f 0 5 65278][f 2 1][f 4 6 59 0 0 0][f 3 1 1 0 0 33][f 6 1 2 0 0 2]Eres ego胤sta, Hikari. 斡Deja de molestar a[n]todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [La T胤a De Hikari]]
[f 0 5 65278][f 2 1][f 4 6 58 0 1 0][f 3 1 1 0 0 34][f 6 1 2 0 0 6]As胤 es, no eres normal. 斡Sigue con esa actitud[n]y solo terminar茨s miserable![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Escuela Secundaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 40 15 1 0][f 3 1 1 0 0 35]Mi sue隠o... La gente con la que quiero[n]estar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 40 16 1 0][f 3 1 1 0 0 36][f 6 1 2 0 0 6]Yo... 斡Quiero quedarme con la persona que s姻[n]que soy![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 37][f 6 1 2 0 0 6]斡No quiero descartar toda mi identidad s吋lo[n]por algunas ideas que intentas forzarme![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [La T胤a De Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 38][f 6 1 3 0 0 3][f 6 1 2 0 0 2]夷Todav胤a nos est茨s desafiando? Bien... Te[n]pondremos derecho.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 58 2 1 0][f 3 1 1 0 0 39][f 6 1 1 0 0 1][f 6 1 2 0 0 1]斡Eres un erroooooooooooooor![n][f 1 3 65535][f 1 2 100][f 1 1][e]

[msg MSG_027 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 0 0][f 3 1 1 0 0 40][f 6 1 2 0 0 6]斡N-Nooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 4 4 0 1][f 3 1 1 0 0 41]斡De ninguna manera vamos a dejar que esto[n]suceda![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 4 4][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 42]S胤, tenemos que detenerlos, 斡vamos![n][f 1 3 65535][f 1 1][e]

