[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 14 1 1][f 3 1 1 0 0 21108][f 6 1 2 0 0 6]斡Excelente! Eso encajo muy bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 0]Fue como sospech茨bamos, pero...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]"Junessic Land" tambi姻n estaba basada en una versi吋n distorsionada de los recuerdos de Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 1][f 3 1 1 0 0 61066]S胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3010]Por eso los dinosaurios de esa pel胤cula eran todas chicas, bueno, la mayoría. Pero de todos modos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Esa manada de herb胤voros estaba basada en los compa隠eros de clase de Hikari...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y los carn胤voros eran los chicos populares que iban tras el grupo de Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 6][f 3 1 1 0 0 8071]Parece que una de las amigas de Hikari se convirti吋 en el blanco de ellos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 6][f 3 1 1 0 0 0]Los otros compa隠eros tem胤an pasar por lo mismo, así que trataron de echarla de su grupo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin embargo, Hikari se opuso, lo que caus吋 la discordia del grupo que hizo que la expulsaran.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 7 12 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]As胤 que de ahí viene toda esa mierda de la "regla de la mayoría" en la película, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 7 2 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 6 0 3][f 3 1 1 0 0 0]Dijeron que el voto de la mayor胤a es lo correcto, y cualquier opini吋n diferente es directamente descartada...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Nunca intentaron resolver sus problemas. Decid胤an qu姻 hacer bas茨ndose en n雨meros arbitrarios.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 1][f 3 1 1 0 0 4087][f 6 1 2 0 0 4]Pero, 夷por qu姻 Yosukesaurio ten胤a la cabeza de Yosuke?[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Sus personalidades eran similares.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Es una buena mezcla?[f 2 7 1 20 4 32][e]
[f 0 5 65278][f 2 1]Solo fue coincidencia, supongo.[f 2 7 1 20 0 32][e]

[msg MSG_011 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 6][f 3 1 1 0 0 5069]Eso yo tambi姻n lo creo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso Yosuke dijo que el dinosaurio le record吋 a s胤 mismo, cuando acababa de llegar a Inaba.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1046]...Oh, claro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Por qu姻 nos comparas? 斡No hay nada de m胤 en ese dinosaurio, solo tenía mi cabeza en su cuerpo![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 6][f 3 1 1 0 0 0]Creo que porque era similar a Yosuke, cuando se lleg吋 a Inaba.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 1][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1049]Hay un viejo dicho que dice que, en alg雨n lugar, hay otras tres personas en el mundo que se parecen exactamente a ti...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Vamos, 夷cu茨les son las probabilidades de que uno de esos sea un dinosaurio humanoide?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 6][f 3 1 1 0 0 0]Creo que es porque era similar a Yosuke, cuando llego a Inaba.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 3 1 0 3][f 4 6 8 0 0 1][f 3 1 1 0 0 0]Esforzarte para siempre estar de acuerdo con los dem茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Eso ten胤an en com雨n, así que a Yosuke lo pusieron en al papel de Yosukesaurio.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 6][f 3 1 1 0 0 25067]Es la raz吋n por la que Kamoshida se convirtió en la autoridad m茨xima en "Kamoshidaman"[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]B茨sicamente, 斡Yosuke fue elegido como la mejor persona para ese papel! ¡Felicidades![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]Eso no fue un cumplido...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Bueno, entender a los dem茨s no es malo, el problema surge cuando se lleva ese enfoque demasiado lejos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cualquier lugar donde opriman tus opiniones est茨 completamente mal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 1][f 3 1 1 0 0 13070]Estoy de acuerdo. El trato que le dieron a Hikari no fue m茨s que un juicio encubierto bajo la pretensi吋n de la regla de la mayor胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 81 12 0 1][f 3 1 1 0 0 0]Todo lo que quer胤a era quedarme con Miyuki...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Eso estuvo mal? ¿Realmente le estaba causando problemas a los dem茨s?[n][f 1 3 65535][f 1 1][e]

[sel SEL_025 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]No digas tonter胤as.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]No hiciste nada malo.[f 2 7 1 20 0 32][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 61018][f 6 1 2 0 0 4]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 0][f 3 1 1 0 0 0]Si hubiera estado en tu situaci吋n, creo que habr胤a hecho lo mismo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 0][f 3 1 1 0 0 0]Tu deseo de ayudar a tu amiga, resulto en algo tan terrible... Es tan triste.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 6][f 3 1 1 0 0 0]Obsesionarse con sus reacciones y ocultar tus verdaderos sentimientos, o insistir y ser excluido...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]De cualquier manera, a雨n tienes que soportar mucho dolor...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 24068]En efecto, es lo mismo que matar tu propio coraz吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0]Pero la Hikari de ahora deber胤a ser capaz de...[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61042]S胤, tengo que seguir adelante. Tengo que ver lo que me espera adelante.[n][f 1 3 65535][f 1 1][e]

