[msg MSG_000 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 8 3 1][f 3 1 1 0 0 1]*chuckle*[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 2 0 3][f 3 1 1 0 0 2][f 6 1 2 0 0 7]斡Ta-dah da-daah! Edici吋n de pel胤culas,[n]completa![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 1][f 3 1 1 0 0 3]Cielos... C茨lmate un poco, 夷de acuerdo? Al[n]menos intenta mantener un poco de compostura[n]ahora que estamos al final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 4]Ah胤 est茨. Mit-chan...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 2 1 0][f 3 1 1 0 0 5][f 6 1 2 0 0 8]S姻 que te est茨s poniendo triste porque tendr茨s[n]que despedirte de m胤, 斡pero deber胤as[n]soportarlo sin ponerte tan testioso![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷Y de qu姻 est茨s hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 11]斡Mi encanto se fue sobre su cabeza?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Rise]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 6 2 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 7]斡Bienvenidos a todos! 斡Esa pel胤cula fue[n]genial![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 2 4][f 3 1 1 0 0 9]No pude evitar llorar. Me alegro mucho por[n]ti, Hikari-chan...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 10]Todos... Siento haberos preocupado a todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 16 2 0][f 3 1 1 0 0 11]Dejemos este Cine juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 84 8 3 1][f 3 1 1 0 0 12]S胤, de hecho.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13]Has adquirido la llave final, despu姻s de[n]todo. Escapar ahora es totalmente posible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 4][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 14]S胤, deber胤amos cuidar de esa 雨ltima cerradura[n]ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 15]Mmhm! Todos... vamos.[n][f 1 3 65535][f 1 1][e]

