[msg MSG_000 [Estudiante De Aspecto Sombr胤o]]
[f 0 5 65278][f 2 1][f 4 6 57 1 0 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 3]No dejes que te afecte. Te ayudar姻 a limpiarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Estudiante De Aspecto Sombr胤o]]
[f 0 5 65278][f 2 1][f 4 6 57 10 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 4]...夷Eh?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4]Ah... Gracias.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 0][f 3 1 1 0 0 5]Um...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 4]Soy Hikari. 夷T雨 eres Miyuki-chan, verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7]Encantada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 0][f 3 1 1 0 0 8]Hikari... Um, es un placer conocerte tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 0][f 3 1 1 0 0 9]Te gustan las pel胤culas, 夷verdad, Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 1 0][f 3 1 1 0 0 10]斡Mmhm! Incluso si la he visto antes, puedo volver a verla una y otra vez.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]斡La que vi el otro d胤a tenía dinosaurios! Vamos a verla juntos alg雨n día.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 2 1 0][f 3 1 1 0 0 12][f 6 1 2 0 0 6]夷斡Eh!? ¿Est茨s segura? ¡Me encantar胤a![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 4]斡S胤! 夷Por qu姻 no vamos a verla juntos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 0 1 1][f 3 1 1 0 0 14]夷Eh? Oh, tendr姻 que pasar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 1 1][f 3 1 1 0 0 15]Tengo que ir a mis asesor胤as...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 0 1 1][f 3 1 1 0 0 16][f 6 1 2 0 0 6]斡Lo siento! Tal vez la pr吋xima...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]Ya veo. Es una l茨stima... pero, 斡está bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 57 0 1 3][f 3 1 1 0 0 18]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 3][f 3 1 1 0 0 19]夷Qu姻 pas吋 con mi escritorio...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 1 0 1][f 3 1 1 0 0 20]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 0 0 0][f 3 1 1 0 0 21][f 6 1 2 0 0 4]Oye, 夷sabes algo sobre esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 1 1][f 3 1 1 0 0 22]Oh... Es tu culpa, Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 16 1 0][f 3 1 1 0 0 23][f 6 1 2 0 0 4]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 4][f 3 1 1 0 0 24]夷No sab胤as que los ni隠os populares empezaron a meterse con Miyuki?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 0 0 1][f 3 1 1 0 0 25]Si sales con ella, ellos tambi姻n te buscar茨n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 4][f 3 1 1 0 0 26]Miyuki, 夷podr胤as dejarnos en paz? Vamos a terminar siendo arrastrados a contigo tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 4 1 0][f 3 1 1 0 0 27]夷Qu姻...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 1][f 3 1 1 0 0 28]Si Miyuki se va, estoy seguro de que ya no te molestar茨n, Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 2 1 0][f 3 1 1 0 0 29][f 6 1 2 0 0 1]Pero, ese tipo de cosas no me molestan. 斡Sigamos siendo amigos![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 0][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30][f 6 1 2 0 0 4]夷Por qu姻 tienes que ser as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 0][f 3 1 1 0 0 31]Si vas a ser as胤, 夷por qu姻 no tomas el lugar de Miyuki?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 6 37 2 1 3][f 3 1 1 0 0 32][f 6 1 2 0 0 0]夷斡Espera, qu姻!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 0 0 4][f 3 1 1 0 0 33]Las chicas populares solo quieren alguien a quien puedan molestar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 34]Si te quedas con nosotros, nosotros tambi姻n la llevaremos. Solo vas a causarnos problemas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 0][f 3 1 1 0 0 35]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 56 0 0 1][f 3 1 1 0 0 36][f 6 1 2 0 0 6]斡Muy bien! 夷Qui姻n piensa que Hikari deber胤a quedar fuera de nuestro grupo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 2 1 0][f 3 1 1 0 0 37]斡Yo![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 2 1 4][f 3 1 1 0 0 38]Yo tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari De Secundaria]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 37 10 2 3][f 3 1 1 0 0 39][f 6 1 2 0 0 4]No... 夷Por qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Estudiante Nerviosa]]
[f 0 5 65278][f 2 1][f 4 6 55 0 1 1][f 3 1 1 0 0 40]Es lo que todos votaron, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Estudiante Malhumorada]]
[f 0 5 65278][f 2 1][f 4 6 54 0 0 1][f 3 1 1 0 0 41][f 6 1 2 0 0 4]S胤, todos est茨n de acuerdo. T雨 tambi姻n, 夷verdad, Miyuki?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 0 0 6][f 3 1 1 0 0 42]Y-Yo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 57 0 1 6][f 3 1 1 0 0 43]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 44]Bien, en ese caso, Miyuki es la que est茨 fuera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Miyuki]]
[f 0 5 65278][f 2 1][f 4 6 57 6 1 0][f 3 1 1 0 0 45][f 6 1 2 0 0 6]斡E-Espera![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 57 0 0 4][f 3 1 1 0 0 46]Y-Yo... estoy de acuerdo con que Hikari deber胤a irse...[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Estudiante Ruidosa]]
[f 0 5 65278][f 2 1][f 4 6 56 0 0 1][f 3 1 1 0 0 47]夷Lo ves? Todos est茨n de acuerdo, as胤 que la decisi吋n es obvia.[n][f 1 3 65535][f 1 1][e]

