[msg MSG_000 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 1][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 1]Entonces, ese es el tr茨iler de la pr吋xima pel胤cula... No bromeaban. Realmente me dejó un mal sabor de boca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 2]夷Entonces vamos a entrar en un musical?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 2 0][f 3 1 1 0 0 3][f 6 1 2 0 0 10]Adem茨s, 夷斡no era Hikari la que estaba cantando en el tráiler!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 1][f 3 1 1 0 0 4]No hay duda de que era id姻ntica...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]Sin embargo, podr胤a ser alguien completamente diferente que solo se parece a Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 6][f 6 1 2 0 0 3]夷Y el t胤tulo de la película? Era completamente ilegible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 6][f 3 1 1 0 0 7][f 6 1 2 0 0 4]夷Parec胤a que las letras estaban borradas? ¿En las otras películas tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 0 0 1][f 3 1 1 0 0 8]No, los t胤tulos eran legibles.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 1][f 3 1 1 0 0 9][f 6 1 2 0 0 4]夷Pero qu姻 podr胤a haber afectado al título de esta película?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 4 1 1][f 3 1 1 0 0 10][f 6 1 2 0 0 6]Eso no es lo importante ahora. 斡Tenemos que encontrar a Hikari![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11]Ella debe estar en esta pel胤cula porque estaba en el tr茨iler, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 1 0][f 3 1 1 0 0 12][f 6 1 2 0 0 6]S胤, puedo sentir su se隠al. Hikari est茨 ahí, 斡no hay duda![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 1][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 13]Bueno, ahora que sabemos d吋nde est茨, vamos a buscarla.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Nagi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 84 6 3 1][f 3 1 1 0 0 14]La seguridad de Hikari est茨 en sus manos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15]斡Por favor, s茨lvenla![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 16]斡Claro! Prometemos encontrarla.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]斡Y volveremos todos juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 5 12 0 1][f 3 1 1 0 0 18]No es necesario que te preocupes, Nagi. 夷Verdad, [f 6 1 30 0 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1]Por supuesto.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Hag茨moslo.[f 2 7 1 64 2 32][e]

[msg MSG_013 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 1][f 1 5][f 6 1 17 0 0 0][n][f 3 1 1 0 0 19]*Risa* Qu姻 tranquilizador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 4][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 20]斡Bien, entremos a esa pel胤cula![n][f 1 3 65535][f 1 1][e]

