[msg MSG_000 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1][f 6 1 3 0 0 2]Est茨s filmando de nuevo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2][f 6 1 2 0 0 4][f 6 1 3 0 0 2]夷Por qu姻 tienes que seguir film茨ndome?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 3][f 6 1 9 0 0 1]Bueno, cada momento tuyo que filmo es una[n]parte preciosa del historial de tu vida.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 4][f 6 1 9 0 0 1]Escucha, 夷de acuerdo? Tienes el papel principal[n]en tu propia vida, Hikari.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5][f 6 1 9 0 0 1]Por eso, bueno... uno podr胤a llamarte la[n]actriz estrella de tu propia pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 8 5 9][f 3 1 1 0 0 6][f 6 1 2 0 0 4]夷Yo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 7][f 6 1 9 0 0 1]As胤 es. Entonces, ven ahora. Sonr胤e para la[n]c茨mara, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 3][f 4 6 37 10 5 9][f 3 1 1 0 0 8]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 37 12 5 9][f 3 1 1 0 0 9][f 6 1 2 0 0 10]No puedo. Es embarazoso... Puedes seguir[n]adelante y dejar de filmarme ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 14 5 9][f 3 1 1 0 0 10][f 6 1 2 0 0 4]夷Soy... diferente de otras personas? 夷Soy...[n]raro? 夷Me equivoco para ser as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11][f 6 1 9 0 0 1]夷Qu姻 te hace pensar eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12][f 6 1 3 0 0 2]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13][f 6 1 9 0 0 1]Bueno... ciertamente no eres normal, Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 16 5 9][f 3 1 1 0 0 14][f 6 1 2 0 0 0]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15][f 6 1 9 0 0 1]Para m胤, no eres normal... Eres especial.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16][f 6 1 9 0 0 1]Eres un encanto, un alma sensible, y un poco[n]de preocupaci吋n, adem茨s, tu sonrisa me[n]recuerda a tu madre...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17][f 6 1 9 0 0 1]Hikari, est茨 totalmente bien ser quien eres.[n]No deber胤as pensar que est茨 mal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 8 5 9][f 3 1 1 0 0 18][f 6 1 2 0 0 4]夷En serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 9 0 0 1]Mira, es natural que seas diferente de otras[n]personas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 20][f 6 1 9 0 0 1]Tienes tu propia individualidad especial. Me[n]har胤a feliz si pudieras ver el valor en[n]eso tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 18 5 9][f 3 1 1 0 0 21]Cielos..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22][f 6 1 2 0 0 4]Pap茨... 夷Recuerdas c吋mo te dije que quiero[n]hacer pel胤culas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23][f 6 1 9 0 0 1]Claro que s胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 12 4 9][f 3 1 1 0 0 24]Si lo que me dijiste es verdad... Si eres el[n]l胤der en tu propia vida...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 25]Entonces realmente quiero convertirme en[n]director de cine. Quiero grabar toda clase[n]de vidas de la gente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26]Cada persona tiene su propia historia que[n]contar. Todos viven y piensan de diferentes[n]maneras...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27]Ya sea ficci吋n o no ficci吋n, quiero filmar[n]esas historias diferentes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 37 8 5 9][f 3 1 1 0 0 28]Y si la gente que mira esas pel胤culas lo pasa[n]bien o se siente feliz viendolas,[n]entonces eso me har胤a feliz.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Eso es lo que hicieron las pel胤culas para[n]m胤... Como me mostraste, pap茨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Calma La Voz Del Hombre]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 30][f 6 1 9 0 0 1]Es un sue隠o maravilloso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chica Inocente]]
[f 0 5 65278][f 2 1][f 4 6 37 18 5 9][f 3 1 1 0 0 31]斡S胤, y me asegurar姻 de que sea verdad![n][f 1 3 65535][f 1 1][e]

