[msg MSG_000 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 1][f 3 1 1 0 0 16002]...Este piso tambi姻n tiene un ambiente[n]musical.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Flores y notas musicales... Este lugar[n]tiene un ambiente similar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Sabes, nunca he visto un musical.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]La gente ah胤 solo comienza a cantar de[n]la nada, 夷verdad? Eso es demasiado[n]irreal para m胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 1][f 3 1 1 0 0 61055][f 6 1 2 0 0 6]斡Eso no es verdad![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Las pel胤culas sonoras existen desde la[n]d姻cada de 1920, cuando las pel胤culas[n]habladas superpuestas con m雨sica[n]fueron...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 11 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]O-oh, 夷Est茨s bien...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 6 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Oh... lo siento. No quer胤a levantar la[n]voz de esa manera...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 0][f 3 1 1 0 0 0]No, est茨 bien. No s姻 nada de eso, as胤[n]que si姻ntete libre de cont茨rmelo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 61152]*risa* Gracias. Me alegra escucharlo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ahora que lo pienso, no puedo evitar[n]hablar mucho cuando se trata de[n]pel胤culas... La gente se suele molestar[n]conmigo por eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24036]"夷Molestar"? 斡Pero, la pasi吋n que la[n]gente muestra al hablar de lo que le[n]gusta es tan alentadora![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 6][f 3 1 1 0 0 0]Adem茨s, a veces escuchar sobre lo que[n]les gusta a otros puede hacer que te[n]intereses en ellos tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 22031][f 6 1 2 0 0 6]斡Me encantan los musicales![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puede que no haya sido una pel胤cula,[n]斡pero cuando vi una obra en vivo en[n]Broadway, se me eriz吋 la piel![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 6][f 3 1 1 0 0 0]Estoy de acuerdo. Cuando escuchas las[n]voces de un gran grupo y ves c吋mo se[n]unen sus movimientos, es muy[n]conmovedor.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es cierto que la gente no estalla en[n]canciones en la vida real... pero creo[n]que hay algunos momentos en los que[n]tu coraz吋n se convierte en canci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 61162][f 6 1 2 0 0 0]斡Exacto! 斡Entiendes! 斡Hay momentos en[n]la vida real en los que tus emociones[n]se vuelven tan fuertes que sientes[n]ganas de cantar![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero yo no soy mucho de cantar, as胤 que[n]experimento eso a trav姻s de los[n]personajes en los musicales.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 0]斡S胤! La tristeza, la felicidad e incluso[n]la ira se expresan de manera tan[n]v胤vida con canciones y bailes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]S胤. Los actores expresan todo tipo de[n]emociones y estados de 茨nimo con su[n]cuerpo, en todo tipo de g姻neros[n]musicales.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]La capacidad de un musical para expresar[n]directamente las emociones humanas[n]es lo que me atrae.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todav胤a recuerdo cuando descubr胤 que[n]los di茨logos no son la 雨nica forma de[n]comunicar un mensaje.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5032]*risa* Parece que amas los musicales,[n]Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]*jadeo* 斡Lo siento! Ah胤 voy otra vez,[n]divagando...[n][f 1 3 65535][f 1 1][e]

[sel SEL_016 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Es bastante sorprendente, en realidad.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Eres muy apasionada.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Eres toda una entusiasta.[f 2 7 1 20 2 32][e]

[msg MSG_017 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 6][f 3 1 1 0 0 21067]夷Verdad? No pens姻 que pudieras emocionarte[n]tanto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 es, los musicales te permiten expresar[n]emociones intensas a trav姻s del[n]canto y el baile, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 6][f 3 1 1 0 0 25068]Ella debe amar los musicales porque es[n]as胤 en el fondo, y los musicales a[n]menudo expresan directamente esa[n]emoci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 6][f 3 1 1 0 0 26542][f 3 1 6 0 0 500]Mweheheh... Una entusiasta no se detendr茨[n]una vez que comience a hablar de[n]su tema. 斡Estoy muy feliz de ver a[n]Hikari tan emocionada![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 81 1 0 0][f 4 6 5 2 0 0][f 3 1 1 0 0 5032]Admito que estoy un poco celosa de que[n]tengas algo por lo que est姻s tan[n]apasionada...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Espero poder encontrar algo que me[n]fascine de la misma manera, ya sabes,[n]como Chie con su kung fu y la carne.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 1 6][f 3 1 1 0 0 0]Vamos, 斡no creo que la carne cuente![n]Quiero decir, s胤, me encanta y todo,[n]pero...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Oh, pero estoy FASCINADA con el kung[n]fu! 夷Quieres ver "El Juicio del Drag吋n"[n]conmigo alguna vez, Yukiko?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 0][f 3 1 1 0 0 61168][f 6 1 2 0 0 6]斡Esa es esa famosa pel胤cula de kung fu![n]Tambi姻n la vi, 斡incluso me hizo[n]hervir la sangre![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 14 1 0][f 3 1 1 0 0 4066][f 6 1 2 0 0 6]斡S胤, de eso estoy hablando! 斡Me emociono[n]tanto que no puedo evitar gritar[n]"斡Hwa-taaaa!"![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Vaya, sabes mucho, Hikari. 斡Pensar que[n]entiendes lo genial que es esa[n]pel胤cula![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]U-um... 夷Alguien m茨s tiene una pel胤cula[n]favorita?[n][f 1 3 65535][f 1 1][e]

[sel SEL_025 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]El Caballero de la Tarta Asciende.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Posibilidad Amorosa.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Se隠or Miserable.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No se me ocurre ninguna.[f 2 7 1 20 6 32][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 1][f 3 1 1 0 0 23073]Ah, s胤. Pens姻 que ser胤a una pel胤cula de[n]h姻roes clich姻, pero fue sorprendentemente[n]provocadora en cuanto a la[n]conciencia social.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 6][f 3 1 1 0 0 22032]斡Yo tambi姻n la vi! No pude contener las[n]l茨grimas con esa pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 1][f 3 1 1 0 0 23116]S胤, esa tambi姻n fue un musical.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 18 1 1][f 3 1 1 0 0 0]Sent胤 que aprend胤 sobre la bondad humana[n]por su naturaleza despiadada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 1][f 3 1 1 0 0 23098]夷En serio? Cuando volvamos, vamos a ver[n]algo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 2 0 3][f 3 1 1 0 0 0]Creo que "Like A Dragon" ser胤a la m胤a.[n]Fue bastante emocionante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 8 16 1][f 3 1 1 0 0 0]斡夷Esa es la pel胤cula de Yakuza, verdad?![n]Recuerdo se me eriz吋 la piel por[n]lo intensa que era.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 2 0 0][f 3 1 1 0 0 25048]Realmente sabes mucho, 夷no, Hikari?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Me sorprende que conozcas tantos tipos[n]de pel胤culas y no solo las musicales.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hay alguna raz吋n por la que te enamoraste[n]de las pel胤culas, Hikarin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Eh...? 夷Una raz吋n?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61013]Mi... raz吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 0 0 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]夷Hikari?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]夷Cm? Oh... Probablemente, sea porque he[n]visto pel胤culas desde que tengo[n]memoria.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Pero... no puedo recordar nada m茨s ahora[n]mismo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10032]Ya veo. Bueno, podr胤amos aprender m茨s[n]si seguimos viendo esta pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 0]Mmhm... Quiero asegurarme de verla toda.[n]Sigamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 23 12 0 4][f 3 1 1 0 0 23072]Aseg雨rense de estar alerta.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Esta pel胤cula puede parecer alegre, pero[n]no olviden que... 斡Est茨 llena de[n]Sombras![n][f 1 3 65535][f 1 1][e]

