[msg MSG_000 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 6 1][f 3 1 1 0 0 61005]Ah... Eso fue...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 1 0 3][f 4 6 10 10 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 fue eso? 夷Era parte de los recuerdos de[n]Hikari tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 0][f 3 1 1 0 0 28067]S胤, eso tambi姻n fue de su 姻poca en la escuela[n]primaria. El orador la llam吋 "Hikari"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 0]Y como ella lo llam吋 "Pap茨", eso[n]significar胤a...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 12 2 1][f 3 1 1 0 0 61012]Mi... Nngh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10][f 3 1 6 0 0 500]夷Est茨s bien, Hikari? Si es demasiado para[n]ti, c茨lmate. No te empujes demasiado duro[n]aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Lo siento. Estoy tan confundido...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28015]Dado que esta pel胤cula se basa en sus propios[n]recuerdos, los recuerdos podr胤an ser[n]enfurecidos o inexactos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puede ser mejor evitar obligarla a recordar[n]cosas, y dejar que suceda naturalmente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Est茨 bien tomarlo un poco a la vez, Hikari.[n]Retraceremos el pasado a su propio[n]ritmo, 夷de acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]Gracias... Me alegro de irme ahora.[n][f 1 3 65535][f 1 1][e]

