[msg MSG_000 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 0 1][f 3 1 1 0 0 0]夷Qu姻 fue eso ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 0][f 3 1 1 0 0 28012]夷Podr胤a haber sido la memoria de Hikari?[n]Eso fue mucho m茨s grave que el remolque[n]que vimos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 10 100 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 3 1 6 0 0 500]夷D吋nde fue esa maestra y sus estudiantes?[n]夷El Hikari del pasado tambi姻n[n]desapareci吋?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]斡Arf arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 18 6 1][f 3 1 1 0 0 61005]Ah... Eso fue...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 0]Hikari![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 1 6][f 3 1 1 0 0 22098]斡Hikari! 斡Qu姻 alivio, est茨s bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Est茨s herido en alguna parte, Hikarin?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 0]No... estoy bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 13 12 0 0][f 3 1 1 0 0 13004]Siento interrumpir, pero 夷d吋nde fue Doe? Te[n]secuestr吋 y te trajo aqu胤, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Oh... Ah, no es eso...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 61052]Yo... Vine sola.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 10 100 0][f 3 1 1 0 0 26559][f 6 1 2 0 0 0][f 3 1 6 0 0 500]夷Qu姻? 夷Doe no lo hizo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]Mientras ve胤a las pel胤culas que todos cambiaron,[n]empec姻 a recordar, poco a poco...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todas las cosas que hab胤a renunciado, y las[n]cosas que hab胤a olvidado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Todo empez吋 a salir bien por dentro, y despu姻s[n]de recordar esas cosas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 61012]... Tambi姻n sent胤 que necesitaba cambiar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷As胤 que decidi吋 entrar en la pel胤cula de su[n]propio acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]... Doe me dijo que lo hiciera.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 1]Dijo que no puedo seguir siendo parte del[n]p雨blico para siempre... Que necesito superar[n]esto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 10 6 0][f 3 1 1 0 0 0]Cuando me dijo eso, mi deseo de venir aqu胤[n]s吋lo se puso m茨s fuerte... As胤 que...[n][f 1 3 65535][f 1 1][e]

[sel SEL_015 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]No seas tan imprudente la pr吋xima vez.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Seguro que no est茨s herido?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Nos alegra que est姻s bien.[f 2 7 1 20 2 32][e]

[msg MSG_016 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61028]Lo siento... Pero sent胤 que ten胤a que venir[n]aqu胤, sin importar qu姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Est茨s herido? 夷Te han atacado mientras has[n]estado aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 0]No, he estado bien, pero no estoy seguro por[n]qu姻...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]No he estado en peligro desde que llegu姻[n]aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]Ah... Afortunadamente, no he encontrado ning雨n[n]peligro desde que llegu姻 aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 6][f 3 1 1 0 0 0]Ya veo. Bueno, estoy aliviado de que no[n]estuvieras herido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 26 12 100 0][f 3 1 1 0 0 0]Estoy tan contenta de que est姻s bien, Hikari...[n]斡Siento que me afeitaron m茨s de unos[n]a隠os de mi vida![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 0]Futaba, siento haberte preocupado... Y[n]todos los dem茨s tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1001]Entonces, sobre ese musical que vimos, 夷podr胤a[n]haber sido tu...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 0]Mmhm... La historia se bas吋 en mis propios[n]recuerdos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Fue dicho como un musical, pero lo que pas吋...[n]fue casi exactamente igual que mi[n]pasado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]As胤 que lo que vimos fue, de hecho,[n]biogr茨fico...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 21022][f 6 1 2 0 0 2]夷Qu姻 demonios pasa con esa ense隠anza? Eso[n]fue peor que la mierda, 斡deber胤a estar[n]enlatada por eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 6][f 3 1 1 0 0 0]Cierto, eso fue imperdonable, pero al menos[n]siento como si la imagen estuviera[n]reuni姻ndose ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 8 0 0 6][f 3 1 1 0 0 0]Conceptos como "hero" y "teacher"... "Autoridad[n]absoluta" ser胤a otra. La 雨ltima[n]palabra clave ser胤a...[n][f 1 3 65535][f 1 1][e]

[sel SEL_030 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Regla de la mayor胤a[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]"Rabbit"[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]"Robot"[f 2 7 1 20 2 32][e]

[msg MSG_031 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 6][f 3 1 1 0 0 28078]Es de una pel胤cula diferente. La pieza final[n]del rompecabezas de ese n雨mero musical[n]es "rabbit"[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 0][f 3 1 1 0 0 28067]Precisamente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Espera... 夷est茨n hablando de Kamoshidaman?[n]夷Y c吋mo se transform吋 en un conejo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 26 0 100 0][f 3 1 1 0 0 0]S胤, lo clavaron. Kamoshidaman estaba formado[n]por los recuerdos de Hikari.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 6][f 3 1 1 0 0 24076]Esa maestra de primaria era la "autoridad[n]absoluta" de su clase.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esto describe perfectamente a Kamoshidaman[n]tambi姻n. Nadie debe haber podido desafiarla,[n]incluso cuando estaba equivocada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 0]En el ordeal del conejo, Hikari fue[n]injustamente rega隠ada por un maestro, alguien[n]con autoridad absoluta.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Y el conejo, el s胤mbolo del trauma de[n]Hikari, tambi姻n apareci吋 en la pel胤cula...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 6 1 25 0 0 0][f 4 6 81 6 2 1][f 3 1 1 0 0 61004]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 12 0 1][f 3 1 1 0 0 0]Ahora que pienso que los ciudadanos que[n]siguieron a Kamoshidaman... Deben haber sido[n]los estudiantes que no..[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No, quien no pudo hablar con la maestra por[n]su autoridad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Una pel胤cula de mierda nacida de recuerdos[n]de mierda, 夷eh? No me extra隠a que fuera[n]tan asqueroso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 6][f 3 1 1 0 0 27011][f 6 1 2 0 0 4]Esto es s吋lo un pensamiento, pero esta l吋gica[n]se aplica a m茨s pel胤culas adem茨s de[n]Kamoshidaman, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 1][f 3 1 1 0 0 25068]Tienes raz吋n... Lo mismo podr胤a decirse acerca[n]de A.I.G.I.S. o Junesic Land...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Creo que todos han estado conectados a los[n]recuerdos de Hikari, en alguna forma[n]o forma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 18 0 0 0][f 3 1 1 0 0 0]Eso significa que esta pel胤cula con el t胤tulo[n]irreparable tambi姻n est茨 relacionada[n]con sus recuerdos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 6][f 3 1 1 0 0 0]Siento que estamos empezando a ver lo que[n]conduce este mundo de la pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 8 12 0 0][f 3 1 1 0 0 8080][f 6 1 2 0 0 4]夷Por qu姻 naci吋 este mundo para empezar?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Un individuo que tiene un pasado doloroso no[n]s吋lo explica la raz吋n detr茨s de todo[n]este mundo tangible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 13 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Hikari, 夷hay algo que venga a la mente de tu[n]parte?[n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61039][f 6 1 2 0 0 3]Lo siento. No puedo pensar en nada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_047 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 0 1 1][f 3 1 1 0 0 23015]Un mundo que refleja el coraz吋n de una[n]persona... Suena como algo con lo que tenemos[n]experiencia.[n][f 1 3 65535][f 1 1][e]

[sel SEL_048 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]夷Qu姻 quieres decir?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]El mundo cognitivo...[f 2 7 1 20 2 32][e]

[msg MSG_049 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 0][f 3 1 1 0 0 23130][f 6 1 2 0 0 0]斡Vamos! 斡Estoy hablando del mundo cognitivo![n]夷Realmente lo olvidaste todo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0]Bueno, no podemos usar el navegante Metaverse[n]aqu胤, as胤 que esto no parece ser[n]exactamente lo mismo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23069]Cierto. Pero no podemos usar el navegador[n]Metaverse aqu胤, as胤 que esto no parece ser[n]exactamente lo mismo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 7 1 0 1][f 4 6 3 0 0 3][f 3 1 1 0 0 3013]No estoy totalmente seguro de por qu姻, pero[n]este lugar se siente bastante similar al[n]mundo de la televisi吋n con el que nuestro[n]equipo trata.[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 0]Oh s胤, ahora que lo mencionas, se siente[n]igual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 5013][f 6 1 2 0 0 4]As胤 que, en esencia, las pel胤culas se han[n]basado en las experiencias emocionalmente[n]traumatizantes de Hikari, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Entonces necesitamos reconsiderar el objetivo[n]de Doe, aunque todav胤a es un completo[n]misterio para nosotros...[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Doe dijo a Hikari, "Necesitas superar[n]esto", 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0]Considerando eso, est茨 empezando a sentir[n]que no es realmente el malo despu姻s de[n]todo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 11020][f 6 1 2 0 0 4]夷Est茨s bien, Hikari? 夷Te sientes bajo[n]el clima?[n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 61054]No es eso. Yo s吋lo... Sigo pensando en por[n]qu姻 siempre soy as胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Es mi problema, as胤 que deber胤a ser el que[n]lo resuelva...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 61080]Pero al final, he causado tantos problemas[n]para todos... Si ese es el caso, entonces[n]tal vez deber胤a...[n][f 1 3 65535][f 1 1][e]

[sel SEL_058 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Te preocupas demasiado.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]As胤 no vemos las cosas.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No seas tan duro contigo mismo.[f 2 7 1 20 6 32][e]

[msg MSG_059 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 6][f 3 1 1 0 0 3030][f 6 1 2 0 0 4]S胤, lo que dijo. Ninguno de nosotros se[n]preocupa por eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]El pensamiento de que usted es un problema[n]para nosotros nunca cruz吋 nuestras mentes.[n]Todos vinimos aqu胤 porque quer胤amos[n]ayudar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Espero que puedas creernos cuando digamos[n]que nos sentimos as胤 por ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 23069]Cierto, el Fantasma Los ladrones est茨n[n]destinados a salvar a la gente en problemas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]Los miembros de SEES vinieron aqu胤 porque[n]quer胤amos rescatarte, lo mismo va para el[n]Equipo de Investigaci吋n, tambi姻n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Espero que puedas creernos cuando digamos[n]que nos sentimos as胤 por ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 6][f 3 1 1 0 0 12067]S胤, no hay necesidad de superar esto. A nadie[n]le importa lanzar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]El pensamiento de que usted es un problema[n]para nosotros nunca cruz吋 nuestras mentes.[n]Todos vinimos aqu胤 porque quer胤amos[n]ayudar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Espero que puedas creernos cuando digamos[n]que nos sentimos as胤 por ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 19 1 0 3][f 4 6 81 0 0 0][f 3 1 1 0 0 61133]Todos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_066 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　　[n][f 3 1 1 0 0 0]Plus, s吋lo hemos llegado tan lejos trabajando[n]juntos, 夷no crees que deber胤amos ver[n]esto tambi姻n como un equipo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_067 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 6][f 3 1 1 0 0 27009]Todos podemos decir que quieres cambiar,[n]Hikari...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 6][f 3 1 1 0 0 0]Por eso quiero darte mi fuerza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]Muchas gracias...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 61002]Si no es demasiado... 夷Podr胤an prestarme su[n]fuerza aqu胤?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Para que cambie, y para que todos salgamos[n]de este lugar... 斡Quiero ver esta pel胤cula[n]al final![n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 9 2 0 0][f 3 1 1 0 0 9067][f 6 1 2 0 0 4]斡Total y seguro! Todos sienten lo mismo,[n]夷verdad, Yosuke?[n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 7]夷Por qu姻 me preguntas, idiota? 斡No soy todo[n]el mundo! 斡Pero, por supuesto que estoy[n]dentro![n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 13 2 0 0][f 3 1 1 0 0 13031]Hm, eres toda una gente confiable...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Escapar este mundo sigue siendo importante,[n]pero hemos llegado tan lejos, lo veremos[n]juntos, hasta el final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 6][f 3 1 1 0 0 0]斡Welp, est茨 decidido! 斡Adentro en esta pel胤cula[n]y cambiemos la mierda![n][f 1 3 65535][f 1 1][e]

