[msg MSG_000 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 81 1 0 1][f 4 6 10 12 0 3][f 3 1 1 0 0 10003][f 6 1 2 0 0 4]Hey, Hikari-chan. Te gustan las[n]pel胤culas, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 0 0][f 3 1 1 0 0 0]S胤, los amo. 夷Por qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0]Bueno, me preguntaba por qu姻 estabas[n]atrapado en un cine en primer lugar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 4][f 3 1 1 0 0 9015][f 6 1 2 0 0 4]Hrmmm... Si Doe es el que encarcel吋 a[n]Hikarin, 夷quiz茨s le agrada su jaula?[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Qu姻 amable de su parte.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Es m茨s sobre lo que le gusta a Doe.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Es un anfitri吋n cort姻s.[f 2 7 1 20 0 32][e]

[msg MSG_005 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 11 4 0 1][f 3 1 1 0 0 11083][f 6 1 2 0 0 6]Si es tan amable, 夷por qu姻 la atrap吋 aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 4][f 3 1 1 0 0 0]S胤. No importa cu茨nto le gusten las[n]pel胤culas, atraparla y obligarla a ver a[n]estos horribles no tiene sentido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 22 10 1 6][f 3 1 1 0 0 22075]Claro. Desde Doe es un proyectista, no[n]es dif胤cil imaginar que elija un lugar[n]que se adapte a sus propios intereses tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 24 4 1 1][f 3 1 1 0 0 24075]Ya veo. Si est茨 teniendo su estancia[n]durante mucho tiempo, tambi姻n puede[n]hacerlo c吋modo para ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 0]斡La atrap吋 aqu胤! 夷Qu姻 clase de anfitri吋n es ese?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 24022][f 6 1 2 0 0 4]No tendr胤a ning雨n problema estar[n]atrapado en la residencia de Joker, aunque...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]Es un lugar c吋modo, y hay curry all胤.[n]Si tuviera suministros de arte conmigo,[n]podr胤a pasar semanas en su casa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 3094][f 6 1 2 0 0 9]Me golpe吋 con el sentido m茨s fuerte de[n]dejar vu, como si tuviera mi propio oso[n]para cruzar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 22 1 0 6][f 4 6 81 12 0 1][f 3 1 1 0 0 61001]Um... Para ser honesto, me gust吋 ese[n]cine al principio...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tengo que ver pel胤culas durante todo el[n]tiempo que quisiera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 22058]夷En serio? Pero, 夷no era s吋lo la misma[n]pel胤cula en bucle hasta que aparecimos?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 4][f 3 1 1 0 0 0]Adem茨s, fue ese horrible golpe de[n]Kamoshidaman... S姻 que te encantan las[n]pel胤culas y todo, pero 夷no se envejecer胤a?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Fue repetitivo, pero no me importaba...[n]En realidad, nada me molest吋 mientras[n]estaba viendo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 5 6 0 0][f 3 1 1 0 0 5125]S姻 lo que quieres decir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ha habido momentos en los que no quer胤a[n]pensar en nada y huir de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]Mmhm... Creo que estaba intentando[n]escapar de la realidad en ese cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 0]Pero, definitivamente puedo decir que[n]ya no es el caso. Esos no son los tipos[n]de pel胤culas que quiero ver ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]No tener que pensar mientras estuvieras[n]viendo la pel胤cula... Es casi como si[n]te estuvieras alejando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 10 0 4][f 3 1 1 0 0 16018][f 6 1 2 0 0 4]夷Eh? 夷Qu姻 quieres decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 0][f 3 1 1 0 0 0]Cuando lleg吋 por primera vez,[n]Hikari-san no ten胤a intenciones de salir del cine...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero, mientras ve胤a las pel胤culas,[n]tanto las tramas de las pel胤culas como sus[n]propios sentimientos comenzaron a[n]cambiar, y Doe escupi吋 las llaves.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 28 6 1 6][f 3 1 1 0 0 0]Es como si sus acciones estuvieran[n]vinculadas a los cambios de coraz吋n de[n]Hikari-san y su deseo de salir de este lugar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 61018][f 6 1 2 0 0 4]夷Mi coraz吋n estaba relacionado con todo esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 8068]Cuando lleg吋 por primera vez,[n]Hikari-san no ten胤a intenciones de salir del cine...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero, mientras ve胤a las pel胤culas,[n]tanto las tramas de las pel胤culas como sus[n]propios sentimientos comenzaron a cambiar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0]A雨n no podemos estar seguros de nada,[n]pero debe haber alguna conexi吋n entre el[n]Cine y Hikari-san.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si fuera a postular qui姻n podr胤a[n]manejar un Cine lleno de pel胤culas que[n]reflejan el coraz吋n de Hikari-san, ser胤a...[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]Doe.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Nagi.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]La brigada azul.[f 2 7 1 20 0 32][e]

[msg MSG_024 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 21013]S胤, tiene sentido para m胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 4][f 3 1 1 0 0 0]Es un buen punto... Doe ha estado[n]sirviendo de proyectoionista todo este tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 3]A雨n as胤, algo me parece.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4059][f 6 1 2 0 0 0]夷Hablas en serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Uhh... 夷Nagi-san no se despert吋 aqu胤 en[n]el Cine con Hikari?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Eso no significa que se haya[n]arrastrado a este desastre como nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 21 12 0 1][f 3 1 1 0 0 21013][f 6 1 2 0 0 4]Cuando se trata de eso, 夷no es Doe el[n]雨nico que podr胤a sacar algo de esto rid胤culo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 4][f 3 1 1 0 0 0]Es un buen punto... Doe ha estado[n]sirviendo de proyectoionista todo este tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 3]A雨n as胤, algo me parece.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 1][f 3 1 1 0 0 25089]Hmm... Esa gente en todo el azul podr胤a[n]muy bien saber algo, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 1][f 3 1 1 0 0 0]Hay alguien m茨s sospechoso que ellos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 4][f 3 1 1 0 0 13013]Quieres decir Doe... 畏l ha estado[n]sirviendo como el proyectoionista todo este tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 3]A雨n as胤, algo me parece.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28073]Debo decir, estoy de acuerdo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin embargo, no tenemos idea de cu茨les[n]son los motivos de Doe, as胤 que nada[n]puede decirse con certeza en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 12 0 0 1][f 3 1 1 0 0 0]Supongo que todo lo que podemos hacer[n]es encontrarlo y presionarlo para que[n]responda. 夷Qui姻n sabe si eso nos har茨 bien.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 0]Hikari y Doe entraron en esta pel胤cula,[n]夷verdad? Tiene que haber una raz吋n por[n]la que finalmente hizo un movimiento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 0 1][f 4 6 18 12 0 3][f 3 1 1 0 0 18068][f 6 1 2 0 0 4]Aki tiene raz吋n. Entonces, 夷d吋nde diablos est茨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 2 0][f 3 1 1 0 0 0]Creo que est茨 al final de esta[n]pel胤cula... en el punto m茨s profundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0][f 6 1 2 0 4]Puedes decir d吋nde est茨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 61066][f 6 1 2 0 0 10]Es solo una sensaci吋n que estoy[n]recibiendo... Siento no estar m茨s seguro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]En absoluto, este lugar est茨[n]胤ntimamente conectado a tu coraz吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 0]As胤 que seguirlo deber胤a ser la manera[n]m茨s r茨pida de resolver nuestro problema.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 0 0][f 1 5][f 6 1 17 0 0 0][f 3 1 1 0 0 2066] Correcto. Te[n]seguiremos por el camino en el que crees.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 3 1 1 0 0 0]Vamos, sigamos.[n][f 1 3 65535][f 1 1][e]

