[msg MSG_000 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 1][f 3 1 1 0 0 1]Comenzaremos ahora la asamblea de[n]clases discutiendo el problema de c吋mo[n]nuestro conejo de mascotas se enferm吋.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 2]Todos los que estaban a cargo de[n]cuidarlo, por favor, qu姻dense aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chica Perdida]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 38 0 1 0][f 3 1 1 0 0 3]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 4]Ustedes tres fueron responsables de[n]cuidar al conejo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5][f 6 1 2 0 0 4]夷Por qu姻 sucedi吋 algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Maldito]]
[f 0 5 65278][f 2 1][f 4 6 52 0 1 6][f 3 1 1 0 0 6]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Chica Timida]]
[f 0 5 65278][f 2 1][f 4 6 51 0 1 0][f 3 1 1 0 0 7]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 8]Si hubieras cumplido todos tus deberes[n]como se dijo, el conejo no se habr胤a enfermado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 9]Lo que ha pasado me pone muy triste.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Chica Timida]]
[f 0 5 65278][f 2 1][f 4 6 51 2 1 0][f 3 1 1 0 0 10]Lo siento, Maestro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Maldito]]
[f 0 5 65278][f 2 1][f 4 6 52 2 1 0][f 3 1 1 0 0 11]Lo siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chica Perdida]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 38 1 1 0][f 3 1 1 0 0 12]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 13][f 6 1 2 0 0 4]Hikari-chan, 夷por qu姻 est茨s callado?[n]夷No eras uno de los cuidadores del conejo[n]en ese momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 14][f 6 1 2 0 0 4]Shiratori-san, 夷por qu姻 est茨s callado?[n]夷No eras uno de los cuidadores del[n]conejo en ese momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Escuela Primaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 38 2 1 0][f 3 1 1 0 0 15]Hab胤a una hortaliza en la comida del[n]conejo que nos diste que es mala para ellos...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16]Eso es lo que... Les dije a los otros[n]dos, tambi姻n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]Dije: "No podemos darle ese vegetal..."[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 18]斡No quiero excusas![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 0 0][f 3 1 1 0 0 19][f 6 1 2 0 0 4]Todos los dem茨s se han disculpado...[n]夷Por qu姻 no puedes hacer lo mismo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Escuela Primaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 38 2 1 0][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Pero... 斡es la verdad![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Profesor De Escuela Primaria]]
[f 0 5 65278][f 2 1][f 4 6 53 0 1 0][f 3 1 1 0 0 21][f 6 1 2 0 0 6]斡Eso no importa! 斡Disculpe primero![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22]Te niegas a escuchar a tu profesor...[n]Tienes que interrumpir el orden del aula...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 23][f 6 1 2 0 0 4]Sinceramente, 夷por qu姻 tienes que ser as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Escuela Primaria Hikari]]
[f 0 5 65278][f 2 1][f 4 6 38 0 1 0][f 3 1 1 0 0 24]YO...[n][f 1 3 65535][f 1 1][e]

