[msg BTLMSGID_DUMMY0]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DUMMY1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_SINGLE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_S_MANY]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_D_MANY]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_E_SUP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_E_SUP_STOP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_S_SUP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_D_SUP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADDENEMY_OPEN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADDENEMY_FOE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_ADDENEMY_FOEDEA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_CMD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_CMD_NO]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_CMD_NO_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_STONE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_SLEEP]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BLTMSGID_CONFUSE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_PARA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_TERROR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_STUN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_F_SEAL_HEAD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_F_SEAL_ARM]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_F_SEAL_LEG]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CRITICALHIT_P]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CRITICALHIT_E]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ATTACK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DAMAGE_P_E]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DAMAGE_P_E_C]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DAMAGE_E_P_HP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DAMAGE_E_P_TP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_USE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HPHEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HPHEAL_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TPHEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TPHEAL_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DISCHARGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_MANY]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ITEMUSE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEFENCE]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_SUMMON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_DEAD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_STONE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_SLEEP]
[f 0 5 65278][f 2 1][f 2 4 1]{dialog}[n][e]

[msg BLTMSGID_BST_CONFUSE]
[f 0 5 65278][f 2 1][f 2 4 1]{dialog}[n][e]

[msg BLTMSGID_BST_POINSON_EX]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_POISON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_BLIND]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_CURSE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_PARA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_STUN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_SEAL_MA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_SEAL_RIKI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_BST_SEAL_SOKU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BLTMSGID_RIVIVE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_STONE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_SLEEP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_CONFUSION]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_STINK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_POISON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_BLIND]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_CURSE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_PARALYSIS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_HEAD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_ARM]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BSTH_LEG]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ESCAPE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NOT_ESCAPE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NO_ESCAPE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NOTSELECTESCAPE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NOT_ESCAPE_LEG]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UNITDEAD_E]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UNITDEAD_P]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PARTYDEAD_E_S]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PARTYDEAD_E_D]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PARTYDEAD_P]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KUISHIBARI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LIMITSUMMON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MEGAN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SUMMON_SACRIFIC]
[f 0 5 65278][f 2 1][f 2 4 1]{dialog}[n][e]

[msg BTLMSGID_SUMMON_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_POISONDAMAGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SACRIFICE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHANGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MOVE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RANGEOUT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AVOID]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_STOPACTION]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFUP_CRITICAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFUP_HEALEFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS3_UROKOCHASE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_URI_MESSAGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DSUMMON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFDOWN_CRITICA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ANDROSTOP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KUITIGIRI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LIMITON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ARIMISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MIRROR_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MIRROR_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_6BOSS_BURSTMISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHANGE_ACTOR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHANGE_TARGET]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOOT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BLOCK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEAD_P]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ONESTOP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ANALYZE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MAXHP_DAMAGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MITIBIKI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PORATA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEASTMISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MISS_H]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MISSCOUNTER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NOTCHANGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SEPARATE_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PORATA_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_5BOSS_AR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_GUARD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_CHARGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_CHASE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_DOLL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_ACTCUT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEASTOFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_ON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ROCKETJUMP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PROTECT_FRONT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PROTECT_REAR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COVER_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MIGAWARI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REPEAT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OVERWRITE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFUPCLEAR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFDOWNCLEAR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UPOFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DOWNOFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_UPC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_UPC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_SPEED_UPC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_HITRATIO_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_AVOID_UPC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_DOW]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_SPEED_DOWNC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_HITRATIO_DO]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_AVOID_DOWNC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_SPEED_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_HITRATIO_UP_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_AVOID_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_DOWN_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_DOW_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_SPEED_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_HITRATIO_DO_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_AVOID_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP_]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP__2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP__3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_H_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_H_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_STNONE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_HP_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEV_GUARD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_OVERGUARD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRNS_WAIT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRNS_CMNDSELECT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRNS_CMNDWAIT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_ACT_COUNTER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_THROW]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_PATIENCE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_PATIENCE_ACT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEADACTION]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEADACTION_18E]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RARE_DASH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ATTRUP_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ATTRUP_3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ATTRUP_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_CHANGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ABSORB_HP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEADACTION_18B]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FANNEL_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FANNEL_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FANNEL_3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UNITDEAD_FNL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_K_FANNEL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOOT_F]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SNIPER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SNIPER_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEASTCOUNTER_0]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_A4_0]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_A5_0]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_KAISH_BOOT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_A1_0]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_A1_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAST_A1_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_6BOSS_AR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRANS_ERROR_END]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEADSTONE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_STOPBST]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_STOPSEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_WEAKDAMAGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MURAMASA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ROCKETJUMPMISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SARUTOBI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOSS_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS1_SPWATSTAN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS1_STANMSG]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AP_5LASTBOSS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_5LASTBOS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_6LASTBOS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_H_KUISHIBARI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OOMIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NONBST]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NONSEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DENGUN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DEADACTION_F18B]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_MEGAZA_HEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_KAISHAKU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_DEADSUMMON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_SUMMON_MSG_00]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_E_SUMMON_MSG_01]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_E_SUMMON_MSG_02]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS_LASTBOSS_ARM]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS_LASTBOSS_ARM_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_TAMAGO_MSG_00]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_UP_ALL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAITAISHINSHO]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_SHOMO]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_KYOMU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS_CHANGE_ATK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BS_CHANGE_DEF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LBS_MES_00]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NONCOST]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FRONT_DEAD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_KEKKAI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_KITOU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_ACT_CCOUNTER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SUMMON_CHICK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LIMITMISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_180_END]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_LBS_CHANGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UROBORO_SHIELD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DISCHARGE_BH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PARTYDEAD_E_BR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PARTYDEAD_E_GK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ES_CHANGE_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_MOVE_S]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_MOVE_D]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_E_MOVE_A]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOOT_V]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOOT_WIDE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RARE_ENCOUNT_D]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RARE_ENCOUNT_S]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_CHARGE_BOSS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ST_BODYCHANGE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ST_BODYCHANGE_E]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KIJIN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KIJIN_OFF]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_KUISHIBARI2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TPCUT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HOUJIN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HOUJIN_EFT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRANSPARENT_ON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TRANSPARENT_OFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ICEACTSTOP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACTSTOPTURN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LMT_103]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_3BS_URK_TAKEOFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_3BS_URK_ON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_3BS_URK_DEATH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FROG_JUMP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OVERHEATON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OVERHEATOFF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MSGWAIT1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MSGWAIT2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MSGWAIT3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MSGWAIT4]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_MSGWAIT5]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_BALLOON]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_CHARGE_BOSS_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ACT_LION_SLEEP]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_UP2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_UP2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_UP3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_UP3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_DOWN_3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_DOW_3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTACK_DOWN_4]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DEFENCE_DOW_4]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_COUNTER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_COUNTER_BOO]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_FIRE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_ICE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_THUN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_BUTS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_SHOC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_THRU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_FI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_IC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_TH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_BU]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_SH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_TH_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_COUNT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_CHASE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_LINEC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_HEAL]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_ATK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_DEF]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_DANCE_EN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_LINK]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_GUARD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_CONC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_AREA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_WEAKENED]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MASCOT]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_BUNNY]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFOFF_P_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFOFF_P_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFOFF_UP]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REFOFF_DOWN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAIMA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HOUJIN_CANCEL_M]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OATH_END]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COUNTER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHASE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP__4]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP__5]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTR_WEPUP__6]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_WIND]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_HIKA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_YAMI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_WI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_HI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_YA]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HPNONCOST]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KEIKAI]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_RARE_1]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_RARE_2]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_RARE_3]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_HAMA_OMEN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MUDO_OMEN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_NIYANIYA]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_JIBAKU_MISS]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHICKEN]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_ROBOT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TOWER]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TOWER3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TOWER5]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KING]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_KING_ESCAPE]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_BIBIRI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TORIMAKI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PUNISH]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_1]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_2]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_3]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_EYE_HEAD]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_EYE_RIGHT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_EYE_LEFT]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ENLIL_RETAKE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ENLIL_HIKARI]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MUTEKI_KAMO_WAR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MOTHER_COM]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MOTHER_COM_CURE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAMO_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SKAM_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_YOUS_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_IKUT_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MCOM_ERROR]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DO_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ENL1_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ENL2_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TREX_MIE]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BUF_OMEN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_JIO_OMEN]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KHRONOS_ANNOUNC]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PASTOR_OATH_ATT [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3843]{dialog}[n][f 1 1][e]

[msg BTLMSGID_PASTOR_OATH_SKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3844]{dialog}[n][f 1 1][e]

[msg BTLMSGID_PASTOR_OATH_LEA [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3846]{dialog}[n][f 1 1][e]

[msg BTLMSGID_PASTOR_OATH_ITE [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3845]{dialog}[n][f 1 1][e]

[msg BTLMSGID_PASTOR_OATH_TWO [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3847]{dialog}[n][f 1 1][e]

[msg BTLMSGID_PASTOR_JUDGEMEN [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 3848]{dialog}[n][f 1 1][e]

[msg BTLMSGID_HOQ_CAST_SKILL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HOQ_INTERRUPT_S [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_P4HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_P3HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_YOUSUKE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_CHIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_YUKIKO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_RISE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_KANJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_NAOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_KUMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_YUKARI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_JUNPEI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_SANADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_MITURU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_FUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_AEGIS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_AMADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_KOROMAR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_ARAGAKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_P3_HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_P5HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_RYUJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_ANN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_MONA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_YUSUKE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_MAKOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_FUTABA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_HARU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ADD_ATK_AKECI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_P4HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_P3HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_YOUSUKE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_CHIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_YUKIKO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_RISE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_KANJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_NAOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_KUMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_YUKARI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_JUNPEI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_SANADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_MITURU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_FUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_AEGIS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_AMADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_KOROMAR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_ARAGAKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_P3_HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_P5HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_RYUJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_ANN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_MONA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_YUSUKE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_MAKOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_FUTABA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_HARU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL_ATK_AKECI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_P4HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_P3HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_YOUSUK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_CHIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_YUKIKO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_RISE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_KANJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_NAOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_KUMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_YUKARI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_JUNPEI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_SANADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_MITURU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_FUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_AEGIS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_AMADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_KOROMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_ARAGAK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_P3_HER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_P5HERO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_RYUJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_ANN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_MONA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_YUSUKE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_MAKOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_FUTABA [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 26070]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_HARU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALL2_ATK_AKECI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_P4HER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_P3HER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_YOUSU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_CHIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_YUKIK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_RISE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_KANJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_NAOTO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_KUMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_YUKAR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_JUNPE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_SANAD [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_MITUR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_FUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_AEGIS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_AMADA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_KOROM [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_ARAGA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_P3_HE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_P5HER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_RYUJI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_ANN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_MONA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_YUSUK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_MAKOT [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_FUTAB [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_HARU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI_ATK_AKECI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_P4HE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_P3HE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_YOUS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_CHIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_YUKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_RISE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_KANJ [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_NAOT [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_KUMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_YUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_JUNP [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_SANA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_MITU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_FUKA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_AEGI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_AMAD [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_KORO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_ARAG [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_P3_H [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_P5HE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_RYUJ [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_ANN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_MONA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_YUSU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_MAKO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_FUTA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_HARU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COMBI2_ATK_AKEC [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_VELVET_THEODORE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_VELVET_ELIZABET [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_VELVET_MARGARET [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_USAGI_OOGOE [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_VELVET_SRICAM [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_GK_COUNT3 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_GK_COUNT2 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_GK_COUNT1 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ESCAPE_ALL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OVERWRITE_ALL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HPHEAL_ALL_MEMB [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_EXP_GIFT [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOUHEKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_GOURIKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAISOKU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COVERAL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DENKOH [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ORACLE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MESSIAH [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ESHOWER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FULLGET [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COST_CUT [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TIYUDAI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TIYUSOK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HOMUNCU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_OWNDOLL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KIAIBRACE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAMINONIE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DLCATK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_UZUUZU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MANZOK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_THINK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KETSUDAN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_MAHASUKU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RANDAMA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HEATRA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SASTAIN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_HIDE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_RISKY_GAMEOVER [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_JIBAKU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_EIKOHNO [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ALLBSTHEAL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KOUKA_NASHI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_AMRITA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_LPATRA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_COUNT_UP [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ONEBSTHEAL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_ONESEALHEAL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CHARGE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_CONCENTRATE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_KAKUSEI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_SUMMON_TRUMP [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DOLL_SMILE [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_MOTIVATION [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOAST [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_RELAX [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_CREEP [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 0]{dialog}[n][e]

[msg BTLMSGID_TURNENDHEAL [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DARKMIST [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_TARGET_DEAD_ALR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DROP_MONEY [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_COUNTER_ATT [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_SKILL_LOCK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAR_TENSION_L2 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAR_TENSION_L3 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BEAR_TENSION_L3_2 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_NEND [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRUP_KAKU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_NE [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_REF_ATTRDOWN_KA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_DOUBLE_ATTACK [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_BOOT2 [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FULL_ANALYZE_SU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_FULL_SNALYZE_FA [Merciful Clergyman]]
[f 0 5 65278][f 2 1][f 2 4 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_SONIC_RUSH [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_RUSH_STEP [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_GOWAN [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_GAISHU [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_UTIOTOSI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_GEIGEKI [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_ORGIA [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_COSTC [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_COSTR [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

[msg BTLMSGID_PQ2_ZEROS [Merciful Clergyman]]
[f 0 5 65278][f 2 1]{dialog}[n][e]

