[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54125]Esta prueba especial le exigir茨 cazar un[n]n雨mero espec胤fico de objetivos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aunque tambi姻n podr胤as recurrir a eliminar[n]cualquier cosa y todo lo que viene a tu[n]manera...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 54039][f 6 1 2 0 0 6]Sea cual sea su decisi吋n, debe demostrar una[n]experiencia emocionante, escalofriante[n]y completa. 斡Por favor, int姻ntalo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]... Ah胤 lo tienes, un candidato seguro para[n]la buena pel胤cula del a隠o.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]Sus objetivos esta vez son los Rampage Drives[n]encontrados en "A.I.G.I.S."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54013]Quiero que derrotes cuatro de ellos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 0]Suena bien. 斡Tengo ganas de pelear![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 3 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19129]斡Muy bien! 斡Se trata de hacer el primer[n]movimiento![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 12043][f 6 1 2 0 0 6]Me gusta tu actitud, [f 6 1 27 0 0 0]! 斡Vamos[n]a golpearlos muertos![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ser茨 mejor que no vayan a esto sin un plan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54099]Marcar姻 las ubicaciones de estas Sombras en[n]tu mapa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Buena suerte, todos.[n][f 1 3 65535][f 1 1][e]

