[msg MSG_BTL_TUTORIAL_844_ENC]
Reserved

[msg MSG_BTL_TUTORIAL_844_101]
"ばゎもぼや ぢよょわまるろ" ぶめまょ ろめま はぺるろを ぬまろまる もれ みもゅゅまぽ[n]ろよ ぺ ぼまるろぺもょ らよもょろデ をよゎ ぼぺょ らまるみよるゆ ぺ [f 0 1 2]ばゎもぼや[n]ぢよょわまるろ[f 0 1 0] ほを らるまれれもょむ ろめま へ ちゎろろよょ ぽゎるもょむ ろめま[n]ぺぼろもよょ よみ まもろめまる ぺょ まょまゆを よる ぺょ ぺゅゅをテ

[msg MSG_BTL_TUTORIAL_844_102]
A Quick Convert will automatically[n]switch out your team at the end of the[n]turn.

[msg MSG_BTL_TUTORIAL_844_103]
By the way, all of the team members that[n]come into battle via Quick Convert will[n]be feeling in top form, eager to fight!

[msg MSG_BTL_TUTORIAL_844_104]
Compared to an ordinary Team Convert,[n]Quick Convert makes it easier to knock[n]down Shadows.

[msg MSG_BTL_TUTORIAL_844_HP_]
Reserved

[msg MSG_BTL_TUTORIAL_844_HP__2]
Reserved

[msg MSG_BTL_TUTORIAL_844_HP__3]
Reserved

[msg MSG_BTL_TUTORIAL_844_BTL]
Reserve

