[msg MSG_000 [Kamoshidaman]]
You petty criminals are upsetting the[n]world's order and sowing anxiety!

[msg MSG_000_5 [Kamoshidaman]]
It's time for you to perish! Face me,[n]for I am your justice!

[msg MSG_001 [Makoto]]
Blind justice is nothing more than[n]egocentric rubbish.

[msg MSG_002 [Haru]]
You're a phony hero who stands for[n]nothing... You need to come to your[n]senses!

[msg MSG_003 [Kamoshidaman]]
YOU are the ones who must come to YOUR[n]senses! HAHAHA!

