[msg MSG_000 [Kamoshidaman]]
HAHAHA!

[msg MSG_000_5 [Kamoshidaman]]
The pinnacle of absolute justice is[n]here! You'd better be prepared,[n]criminals!

[msg MSG_001 [Ryuji]]
Heh! We'll show you the power of the[n]Phantom Thieves!

[msg MSG_003 [Kamoshidaman]]
HAHAHA!

[msg MSG_004 [Ryuji]]
Our attacks aren't doin' shit!?

[msg MSG_005 [Yusuke]]
They seem to be hitting him, but...

[msg MSG_007 [Kamoshidaman]]
See? It's exactly as I said.

[msg MSG_007_5 [Kamoshidaman]]
This is the power of absolute justice...[n]My power as the unquestionable ruler!

[msg MSG_011 [P3 Fem Protag]]
Are we really powerless to him!?

[msg MSG_006 [Ann]]
It's like my body's gotten so tired all[n]of a sudden...

[msg MSG_012 [Akechi]]
Ngh, I can't move like I want to... It's[n]like I truly can't defy his will...

[msg MSG_013 [Morgana]]
Grrr... We're gonna be in real trouble[n]here!

