[msg MSG_000 [Mother Computer]]
Why are you incapable of functioning[n]like those around you?
Why do you insist on maintaining[n]individuality?

[msg MSG_000_5 [Mother Computer]]
UIY-2249! You shall be erased along with[n]these other irregularities!

[msg MSG_001 [Mitsuru]]
It healed itself!?

[msg MSG_002 [Fuuka]]
It seems to automatically heal itself[n]when its health decreases enough!

[msg MSG_003 [Yukiko]]
What!? Does that mean we can't finish[n]this?

[msg MSG_004 [Ribbon]]
ORACLE―I HAVE A SUGGESTION.

[msg MSG_005 [Futaba]]
Huh? What's up, Ribbon?

[msg MSG_006 [Ribbon]]
...IF THE PLAN SUCCEEDS.

[msg MSG_007 [Futaba]]
Ohhh, I see!
Sweet! Just leave it to me, then!

[msg MSG_008 [Makoto]]
Oracle, what're you planning!?

[msg MSG_009 [Futaba]]
Mweheheh... Imma hack it!
Ribbon's circuits are connected to the[n]Mother Computer―that's the ticket!
Ribbon and I are gonna team up and try[n]to disable that auto-recovery function!
In the meantime, I need you guys to keep[n]that thing's attention.
I'll issue the attack order when ready!

[msg MSG_010 [P3 Fem Protag]]
Gotcha―leave it to us!

[msg MSG_011 [Morgana]]
I see... You got this, Oracle!

[msg MSG_014 [Mother Computer]]
Irregularities must... must...[n]eliminate... Irre...gu... Irr... re...

[msg MSG_016 [Futaba]]
What!? Again!?
Welp, we'll just keep at it! C'mon,[n]Ribbon!

[msg MSG_015 [Mother Computer]]
Irrerererererererererrrreeeerrrroooo...[n]TU9H5AY8OU[f 0 1 3]$%＆*******************

[msg MSG_012 [Mother Computer]]
WARNING! WARNING! CEASE RESISTANCE, OR[n]COUNTERMEASURES WILL BE TAKEN!

[msg MSG_013 [Mother Computer]]
DAMAGE CRITICAL... DANGER... DANGER OF A[n]WORLD WITHOUT INDIVIDUALITY ENDING...

[msg MSG_BTL_25_1 [Mother Computer]]
リボン 「解析率２５％！」 ※仮演出

[msg MSG_BTL_50_1 [Mother Computer]]
リボン 「解析率５０％！」 ※仮演出

[msg MSG_BTL_75_1 [Mother Computer]]
リボン 「解析率７５％！あと少し！」 ※仮演出

[msg MSG_BTL_100_1 [Mother Computer]]
リボン 「解析率１００％！ 自動回復機構を５０％まで低下！」 ※仮演出

[msg MSG_BTL_25_2 [Mother Computer]]
リボン 「解析率２５％！」 ※仮演出

[msg MSG_BTL_50_2 [Mother Computer]]
リボン 「解析率５０％！」 ※仮演出

[msg MSG_BTL_75_2 [Mother Computer]]
リボン 「解析率７５％！あと少し！」 ※仮演出

[msg MSG_BTL_100_2 [Mother Computer]]
リボン 「解析率１００％！ 自動回復機構を２５％まで低下！」 ※仮演出

[msg MSG_BTL_25_3 [Mother Computer]]
リボン 「解析率２５％！」 ※仮演出

[msg MSG_BTL_50_3 [Mother Computer]]
リボン 「解析率５０％！」 ※仮演出

[msg MSG_BTL_75_3 [Mother Computer]]
リボン 「解析率７５％！あと少し！」 ※仮演出

[msg MSG_BTL_100_3 [Mother Computer]]
リボン 「解析率１００％！ 自動回復機構をシャットダウン！」 ※仮演出

