[msg MSG_000 [Yosuke]]
You guys! You found me!

[msg MSG_001 [Morgana]]
Is he with that herbivore we were trying[n]to find!?

[msg MSG_002 [Gaudy carnivore]]
GRRRROOOOOOOAR!

[msg MSG_003 [Teddie]]
Aaaaaah! Yosuke's gonna be swallowed[n]whole if we don't do something!

[msg MSG_004 [Kanji]]
Senpai! We're comin' for ya!
Hey―meat-eating chicken! Come and get[n]us, dammit!

[msg MSG_005 [Morgana]]
Wait! That carnivore's insanely strong!

[msg MSG_006 [Kanji]]
Then what're we supposed to do!?[n]Senpai's gonna get eaten!

[msg MSG_007 [P4 Hero]]
If only we could lure that carnivore[n]away from them...

[msg MSG_008 [P3 Fem Protag]]
Oh, I know! Couldn't we use that thing?
You know, the thing we found on our way[n]here... It ought to take care of that[n]carnivore!

[sel SEL_009 top]
You mean the gate?
You mean the rope?
You mean the trap?

[msg MSG_010 [Makoto]]
That's right! We saw one that was left[n]open!

[msg MSG_011 [Ryuji]]
What are you, a dino wrangler!? We ain't[n]got any rope!

[msg MSG_012 [Yukiko]]
Hmm, a dino wrangler...
Oh―maybe she meant that we could lead[n]the carnivore to that electric gate?

[msg MSG_013 [Makoto]]
That's right! We saw one that was left[n]open!

[msg MSG_014 [Ann]]
Trap? I don't remember a trap...

[msg MSG_015 [Akechi]]
I believe [f 6 1 26 0 0 0]-san was referring to[n]that electric gate.

[msg MSG_016 [Makoto]]
Oh, that's right! We saw one that was[n]left open!

[msg MSG_017 [Ryuji]]
So, all we gotta do is go there and trap[n]it!

[sel SEL_018 top]
Let's go with that plan.
How do we do that, though?
You've got this, Skull.

[msg MSG_019 [Haru]]
But how are we going to drive the[n]carnivore beyond the gate?

[msg MSG_020 [Chie]]
How? Well, we'll just... How ARE we[n]gonna trap it!?

[msg MSG_021 [Ryuji]]
Yeah, I'll just―wait, don'tcha think[n]that's a bit out of my league!?

[msg MSG_022 [Teddie]]
Leave this to me! I've got a nice-sized[n]rock right here, so I'll just take aim,[n]and...
Hey―eat THIS!

[msg MSG_023 [Ann]]
Wahhh! Did he just whip a rock at a[n]carnivore!?

[msg MSG_024 [Teddie]]
And that's a perfect pitch! Did you all[n]see my flawless technique!?

[msg MSG_025 [Gaudy carnivore]]
GWOOOOOOOOO!

[msg MSG_026 [Chie]]
Aah! Didn't that just make it angrier!?

[msg MSG_027 [Teddie]]
I ticked it off on purpose so it'll come[n]after us!

[msg MSG_028 [Yukiko]]
Ah, so we're going with a decoy[n]strategy.

[msg MSG_029 [Rise]]
Everyone, head back the way you just[n]came! Run as fast as you can―past that[n]gate!

[msg MSG_030 [P4 Hero]]
Looks like our mission's begun. Let's[n]keep going until we rescue Yosuke!

[msg MSG_031 [Chie]]
Gotcha! We have more important things to[n]do than heading back to the movie[n]theater, anyway!

[msg MSG_032 [Futaba]]
Right―but you don't have much time! You[n]have to run for it!

