[msg MSG_000 [P4 Protag]]
. I'm a second-year at Yasogami High. I[n]hope we get along.

[msg MSG_001 [Makoto]]
A second-year... I didn't think you were[n]younger than me. You're quite mature for[n]your age.

[msg MSG_002 [Akechi]]
He squared off with [f 6 1 30 0 0 0]― I doubt he's[n]anyone ordinary.

[sel SEL_003 top]
It's a pleasure.
I'll take you down next time.
Nice to me-heet you, ho!

[msg MSG_004 [P4 Hero]]
Likewise. It's reassuring to have new[n]companions.

[msg MSG_005 [P4 Hero]]
Yeah, bring it on!

[msg MSG_006 [P4 Hero]]
ME EAT YOU WHOLE...

[msg MSG_007 [P3 Fem Protag]]
I am in your care...

[msg MSG_008 [Intelligent-looking boy]]
Umm... Are you all using some sort of[n]code?

[msg MSG_009 [Ryuji]]
Oh, are y'all already on the same[n]wavelength?
Cuz, man, there's somethin' real similar[n]between you three... I guess it's just[n]the sort of vibe you got?

[msg MSG_010 [Ann]]
That reminds me, you already knew some[n]of the blue folks, too.
Like, [f 6 1 27 0 0 0]-chan knew Theodore too...

[msg MSG_011 [P3 Fem Protag]]
Yeah, I have the power of the wild card,[n]so I can take on different Personas.
Looks like the same goes for-kun and[n][f 6 1 30 0 0 0]-kun too.

[msg MSG_011_5 [P3 Fem Protag]]
Really, I'm just blown away to learn[n]that there are other people with the[n]same power as me!

[msg MSG_012 [P4 Hero]]
Yeah, I'm surprised myself. This has to[n]be fate of some kind that brought us[n]together.

[msg MSG_013 [Energetic girl]]
Uh, so, I guess I'll go next?

[msg MSG_014 [Chie]]
I'm Chie Satonaka, second-year at[n]Yasogami High. I love kung fu and meat!

[msg MSG_015 [Haru]]
Wait, kung fu and... meat?

[msg MSG_016 [Chie]]
Ah... And, I love... sweets, heh! Ooh,[n]I'm also super-interested in fashion!

[msg MSG_017 [Morgana]]
Ohhh man... That was even more awkward[n]than Lady Ann's acting...

[msg MSG_018 [Menacing-looking boy]]
Senpai, they already figured you out...

[msg MSG_019 [Yukiko]]
It seems I'm next... I'm Yukiko Amagi.[n]It's nice to meet you all.

[msg MSG_020 [Chie]]
Yukiko's family runs a historic inn, and[n]she's next in line to take it over.

[msg MSG_021 [Haru]]
Ah, so that explains the air about her.[n]It's like she has all the qualities of a[n]traditional Japanese lady.

[msg MSG_022 [P3 Fem Protag]]
That's so cool that you're the next[n]manager of an inn. I bet you're great at[n]housekeeping―and cooking, too!

[msg MSG_023 [P4 Hero]]
Don't... mention cooking again.

[msg MSG_024 [Futaba]]
I sense great tragedy in that comment...

[msg MSG_025 [Kanji]]
'Kay, I'll go next. I'm Kanji Tatsumi,[n]first-year at Yasogami High.

[msg MSG_026 [Morgana]]
Another bottle blond like Ryuji, eh?[n]Maybe you two'll get along well.

[msg MSG_027 [Kanji]]
......

[msg MSG_028 [Morgana]]
...Wh-What!?

[msg MSG_029 [Kanji]]
......

[msg MSG_030 [Ryuji]]
Whoa, whoa, what're you givin' Morgana[n]that look for?

[msg MSG_031 [Kanji]]
Uh... Huh!? I―I'm not giving a look!

[msg MSG_032 [Person in bear costume]]
Geez, how could you be such a cheat,[n]Kanji? Don't tell me my fur isn't cuddly[n]enough for you anym―

[msg MSG_033 [Kanji]]
Waaaaaaah! Hey, why're you rattin' me[n]out!?
J-Just drop it! Next! You, Naoto!

[msg MSG_034 [Naoto]]
Oh, yes. I'm Naoto Shirogane, and the[n]same first-year as Kanji-kun.

[msg MSG_035 [Makoto]]
That name sounds familiar. Where have I[n]heard it...?

[msg MSG_036 [Akechi]]
Naoto Shirogane: The original "Detective[n]Prince."
I've seen many of your successes[n]broadcast on the news.
...I never thought I'd meet the[n]original, let alone somewhere like this.

[msg MSG_037 [Naoto]]
The original, you say?

[msg MSG_038 [Akechi]]
Yes. Despite my lack of experience as[n]compared to yourself, I'm called the[n]next "Detective Prince" by our media...

[msg MSG_039 [Naoto]]
Ah, I see. Also, there's no need for[n]such formality.
It seems I'm younger than you in this[n]world.

[msg MSG_040 [Akechi]]
Are you sure? Then, don't mind if I[n]do...

[msg MSG_041 [Chie]]
So that means we've got two Detective[n]Princes then!? That's super reassuring!

[msg MSG_042 [Akechi]]
Haha, I'll do my best to try and live up[n]to those expectations.

[msg MSG_043 [Person in bear costume]]
Ooh, me me me! Lemme go next!

[msg MSG_044 [Teddie]]
Nice to meet you! I'm the one and only[n]Teddie―obviously!

[msg MSG_045 [Ann]]
Uh, what's so obvious about that!?

[msg MSG_046 [Teddie]]
Oh my! Don't you know of my renowned[n]charms, madam?

[msg MSG_046_5 [Teddie]]
Lo and behold... within this bear suit[n]is an incredible, awesome pretty boy!

[msg MSG_047 [Chie]]
Yeah, yeah―quit trying to strip all the[n]time.

[msg MSG_047_5 [Chie]]
Just to make it clear, it's probably for[n]the best not to think too hard about[n]him...
Something might pop out of him from time[n]to time, but just think of it as a part[n]of him and you'll get along fine!

[msg MSG_048 [Ann]]
Alright, could this get any more[n]confusing!?

[msg MSG_049 [Yukiko]]
Let's see... The only ones who aren't[n]here are Rise-chan and Yosuke-kun.

[msg MSG_050 [Ryuji]]
We know who Risette is, though. She's,[n]like, a star idol!

[msg MSG_051 [P4 Hero]]
All right, then. Let's have her provide[n]a more detailed introduction later.

[msg MSG_052 [Naoto]]
The same can go for Yosuke-senpai as[n]well.
It'd be faster to hear about him from[n]his own mouth once we safely regroup[n]with him.

[msg MSG_053 [P4 Hero]]
Yeah. All right, that does it for our[n]end.

[msg MSG_054 [Haru]]
Well, that makes it our turn. So...
Should we begin with Futaba-chan?

[msg MSG_055 [Futaba]]
WHAT!? Th-Th-That's way too much[n]pressure to put on me!

[msg MSG_055_5 [Futaba]]
, [f 6 1 30 0 0 0]! Shouldn't we start with you[n]since you're our leader!?

