[msg MSG_000 [Margaret]]
I've been waiting for you.

[msg MSG_001 [P4 Hero]]
What's going on?

[msg MSG_002 [Margaret]]
Since I've also been summoned here, I[n]wished to aid you all in some way...
And what came to mind is "Persona[n]sacrificing"―it's a means of[n]strengthening your Personas.

[sel SEL_003 top]
Strengthening?
Sacrificing?

[msg MSG_004 [Yusuke]]
You can strengthen our Personas?

[msg MSG_005 [Margaret]]
Yes. By merging Personas together, your[n]Persona will be able to grow.

[msg MSG_006 [Yusuke]]
That has a rather ominous ring to it.

[msg MSG_007 [Margaret]]
*chuckle* I won't ask you to offer one[n]of your own as a sacrifice or anything,[n]so please take solace in that.
This involves merging Personas together[n]to strengthen your Persona.

[msg MSG_008 [Ryuji]]
Is that different from Persona fusion?

[msg MSG_009 [Margaret]]
Persona fusion is the means of creating[n]a new Persona from multiple Personas.
A sacrifice is performed on a single[n]Persona, wherein other Personas are[n]merged with it to assist in its growth.
The original Persona will grow, and[n]those merged will disappear.

[msg MSG_010 [Makoto]]
One becomes stronger, while the others[n]are lost... That would definitely be[n]considered a sacrifice.

[msg MSG_011 [Akechi]]
Can that be done with both Main and[n]Sub-Personas?

[msg MSG_012 [Margaret]]
Yes. It's possible to help both of them[n]grow...
Although, naturally, you will be unable[n]to sacrifice your main Persona.

[msg MSG_013 [Teddie]]
But wait―isn't there more? Like, at a[n]really high cost?

[msg MSG_014 [Margaret]]
Of course, I will ask for compensation―[n]a reasonable amount. However, since this[n]is for my own research as well...
If the Persona to disappear is being[n]sacrificed for the first time, it shall[n]be free of charge.
When that Persona is sacrificed again,[n]though, I will ask to be compensated.

[msg MSG_015 [Haru]]
So, essentially, all Personas can be[n]sacrificed for free the first time?

[msg MSG_016 [Margaret]]
That is correct.

[msg MSG_017 [Chie]]
Ooh... This is an awesome way for us to[n]grow stronger!

[msg MSG_018 [P4 Hero]]
Thanks, Margaret. I appreciate your[n]cooperation.

[msg MSG_019 [Margaret]]
...No, my part here is destiny's doing[n]as well.
With your coming, a change has occurred[n]within the movies―the distorted programs[n]are being corrected.
You all may have been cast into roles as[n]Persona-users to accomplish this.

[msg MSG_019_1 [P4 Hero]]
We were cast into such roles?

[msg MSG_019_2 [Margaret]]
Yes, and I believe we were called here[n]to watch over this... So, Marie?

[msg MSG_020 [Marie]]
Ugh... Do I really have to?

[msg MSG_021 [Margaret]]
You'll have plenty of time to write your[n]poems, so don't concern yourself with[n]that.

[msg MSG_022 [Marie]]
Th-That's not―They're not just my poems,[n]they're my pathos!
StupidterribleMargaretyou'retheworst![n]Just drop it, alright!?

