[msg MSG_000 [Chie]]
Hey, are you two alright!? I mean... You[n]guys just did something totally insane!

[msg MSG_001 [Futaba]]
There was, like, a kinda clashing of[n]powers, and some fusion thing... It was[n]so intense!

[msg MSG_002 [Kanji]]
Senpai and Joker were both amazin' out[n]there!

[msg MSG_003 [Akechi]]
Hold on! As impressive as it was, we[n]need to get this turned on!

[msg MSG_004 [Naoto]]
He's right; the carnivore is barely[n]being held back right now.
If we don't hurry, their efforts will[n]have been for nothing.

[msg MSG_005 [Yusuke]]
...Hm? There's a panel with a button on[n]the opposite side of the panel.

[msg MSG_006 [Naoto]]
It's hard to imagine that's a pointless[n]feature. It's likely worth trying out!

[msg MSG_007 [Makoto]]
There's no time for discussion―let's[n]press it.

[msg MSG_008 [Haru]]
Yes! The power's on!

[msg MSG_008_05 [Gaudy carnivore]]
GYAAAAAAAH!

[msg MSG_009 [Teddie]]
Roar all you want―the ball's in our[n]court now!

[msg MSG_010 [Morgana]]
Joker, flip the switch! It better work[n]this time...

[msg MSG_011 [Ann]]
I-It worked...?

[msg MSG_012 [Futaba]]
Mission complete, you guys! The target[n]has been captured.

[msg MSG_013 [Chie]]
Whew... What a relief!

[msg MSG_014 [Yukiko]]
*sigh* We did it, everyone. I was really[n]concerned for a moment that it wouldn't[n]work.

[msg MSG_015 [Naoto]]
Looks like this was the emergency power[n]supply after all.
I believe we'll be safe for the time[n]being.

[msg MSG_016 [Teddie]]
Let's hurry back to Yosuke!

[msg MSG_017 [P4 Hero]]
Teddie's right―let's go!

