[msg MSG_000 [Yosuke]]
So, to change this movie, we've got to[n]find that... Yosukesaurus... right?

[msg MSG_000_5 [Yosuke]]
I'm sorry, does anybody have any other[n]ideas for what to call him besides[n]Yosukesaurus!?

[msg MSG_001 [Chie]]
What else would we call him? He looks[n]exactly like you.

[msg MSG_002 [Yosuke]]
Agh, why did it have to be my head on[n]the dinosaur?

[msg MSG_003 [Akechi]]
Yosukesaurus is the one who most likely[n]holds the key to changing this movie.
The herd had said they were headed to a[n]"paradise with no carnivores" at the[n]island's furthest reaches...

[msg MSG_004 [Yusuke]]
In that case, I'm sure we'll eventually[n]reunite with them if we head in the[n]direction of this paradise.

[msg MSG_005 [Yosuke]]
Great! Let's just get this over with as[n]fast as possible!

