[msg MSG_000 [Carnivore]]
GRRRROOOOOOOAR!

[msg MSG_001 [Ryuji]]
AAAAAAAH! Whatdowedo!?

[msg MSG_002 [Yosuke]]
Crap! Retreat!

[msg MSG_003 [Ann]]
Well, NOW what do we do? We can't go any[n]further without passing through there...

[msg MSG_004 [Yusuke]]
I haven't seen any gates in the[n]vicinity. I doubt we can trap it[n]somewhere.

[msg MSG_005 [Chie]]
Ooh, I know! Why don't we use somebody[n]as bait and sneak past it while it's[n]distracted?

[msg MSG_006 [Yukiko]]
Oh, are you volunteering, Chie?

[msg MSG_007 [Chie]]
Huh? M-Me!?
C-C'mon, shouldn't it be someone who,[n]uh... looks more delicious than me?

[msg MSG_008 [Teddie]]
Chie-chan!? Why are you looking at me!?
Don't tell me... You're not all going to[n]gang up on me, are you?

[sel SEL_009 top]
We'll never forget you...
Sorry, Ted...

[msg MSG_010 [Yukiko]]
Mmhm, I agree that we should feed the[n]dinosaur.

[msg MSG_011 [Teddie]]
Nooooo... Don't you have any mercy!?

[msg MSG_012 [P4 Hero]]
Isn't that a... bit too cruel?

[msg MSG_013 [Yukiko]]
Oh no, I didn't mean Teddie! I meant[n]that we should use some kind of actual[n]food.

[msg MSG_014 [Naoto]]
I see... a plan to bait it with an[n]appropriate meal.

[msg MSG_015 [P3 Fem Protag]]
Carnivores eat meat, so... Where around[n]here could we get some?

[sel SEL_016 top]
Let's harvest some Shadow meat.
Maybe from a storage unit?
Let's hunt an herbivore.

[msg MSG_017 [Yosuke]]
That seems kinda messed up, man. How[n]would you even know what parts are[n]edible?

[msg MSG_018 [Haru]]
Although, I must say, I'm a bit curious[n]as to what it's like.

[msg MSG_019 [Yukiko]]
I know exactly what you mean.

[msg MSG_020 [Yosuke]]
Um, let's just pretend that we didn't[n]hear any of that...
If only we could find some meat just[n]lying around somewhere...

[msg MSG_021 [Ryuji]]
Do you really think somethin' like that[n]in this jungle would have anything in it[n]that ain't spoiled?

[msg MSG_022 [Chie]]
Huh?
W-We're not gonna go that far, are we?[n]Eheheh...

[msg MSG_023 [Makoto]]
Um, please don't take him seriously,[n]okay? I'm sure Joker is just... joking.

[msg MSG_024 [Yosuke]]
If only we could find meat just lying[n]around somewhere...

[msg MSG_025 [Akechi]]
ぶまゅゅデ れもょぼま ろめよれま まゅまぼろるもぼ むぺろまれ ぺるま れろもゅゅ[n]みゎょぼろもよょぺゅデ らまるめぺられ ろめま みよよぽ れろよるぺむま ゎょもろれ ぺるま[n]るゎょょもょむ らるよらまるゅを ぺれ ゐまゅゅ?

[msg MSG_026 [Yosuke]]
...Oh, you mean that freezer container[n]we saw earlier! Yeah, we could rustle up[n]something useful in there.

[msg MSG_027 [Haru]]
Our company freezes plenty of meats and[n]they turn out just fine, so I imagine[n]those containers work the same way.

[msg MSG_028 [P3 Fem Protag]]
That's such a great idea! Wasn't that[n]container pretty close to here?

[msg MSG_029 [Ann]]
Leave it to the Phantom Thieves to check[n]it out! We'll go right now!

[msg MSG_030 [Morgana]]
All right, let's go swipe some frozen[n]meat!

