[msg MSG_000 [Makoto]]
Everyone, look over there!

[msg MSG_001 [Ann]]
Whoa, it's huge! Is... that a bird?

[msg MSG_002 [Yusuke]]
Those wings have quite the interesting[n]profile... I'd love to do a sketch of[n]it.

[msg MSG_003 [Makoto]]
Isn't that more of a flying reptile than[n]it is a bird? The Pteranodon is a pretty[n]well- known specimen from that family.

[msg MSG_004 [Futaba]]
Hey, wait a sec―be careful! That's an[n]FOE!

[msg MSG_005 [Morgana]]
What!? Well, looks like we can't just[n]kick back and gawk at it.

[msg MSG_006 [Yusuke]]
So it's not a bird... Still, it's[n]definitely worth observing. I really[n]should sketch it―

[msg MSG_007 [Ryuji]]
Weren't you listening? IT'S AN ENEMY![n]And an FOE at that!

[msg MSG_008 [Haru]]
I suspect we'd be critically injured if[n]we were to get attacked by such massive[n]wings... We should be careful.

[msg MSG_009 [Ryuji]]
...Y'know, all this talk about birds is[n]startin' to make me hungry.
What if there was a chicken that size?[n]Couldn't we make a shit-ton of fried[n]chicken out of it?
Oh man, how many servings would that[n]even be...

[msg MSG_012 [Yusuke]]
My stomach just growled.

[msg MSG_013 [Haru]]
I wonder if fried FOEs would taste good.[n]I feel like they'd give me an upset[n]stomach... but I'm still curious.

[msg MSG_014 [Futaba]]
Wanna try catching one for a taste test?
...On second thought, we could end up[n]being the meal. Make sure you don't get[n]chased down while you pass it by.

