[msg MSG_000 [Futaba]]
Joker, wait! Stop, stoooop!

[msg MSG_001 [Makoto]]
What's with the yelling? Is it an[n]enemy!?

[msg MSG_002 [Futaba]]
I dunno, but something's approaching you[n]guys crazy fast!

[sel SEL_003 top]
Is it a dinosaur?
Is it an FOE?
Is it Mona?

[msg MSG_004 [Ann]]
No way!? Does that mean it's coming[n]after us?

[msg MSG_005 [Morgana]]
Yeah, I'm closing in with my supersoni―
Get real! I've been right next to you[n]this whole time!

[msg MSG_006 [Futaba]]
These aren't dinosaurs or FOEs... Based[n]on this movement speed...
No way... Could they be human!?

[msg MSG_007 [Ryuji]]
For real? There's someone else here[n]besides us!?

[msg MSG_008 [Haru]]
Oh, maybe this is what Oracle had[n]mentioned when we first entered the[n]movie...
You know, about how there are multiple[n]powerful presences here?

[msg MSG_009 [P3 Fem Protag]]
Hey! Maybe they're my companions!

[msg MSG_010 [Akechi]]
That makes sense... If they're humans[n]with strong powers, you could be[n]correct.
However, normally, there should be no[n]humans in this movie. It's probably best[n]to remain cautious.

[msg MSG_011 [P3 Fem Protag]]
You're right. Plus, I'm curious about[n]the high-speed part.

[msg MSG_012 [Futaba]]
Your curiosity's about to be[n]satisfied... They're closing in right[n]now!

[msg MSG_013 [Yusuke]]
It seems we have no time to mull this[n]over. Joker, what's your call?

[sel SEL_014 top]
Let's make the first move.
Let's see what happens.

[msg MSG_015 [Morgana]]
All right, we'll leave it to you. Take[n]your gun, for the scare factor...
If we're dealing with humans, just[n]showing 'em that should give you an[n]advantage.

[msg MSG_016 [Makoto]]
I hope this works out in our favor...[n]Let's stay on our toes, though.

[msg MSG_017 [Futaba]]
Hey, incoming! Get ready!

