[msg MSG_000 [Yosuke]]
Whew, that was close!
Thanks for coming, guys! You really[n]saved our asses.

[msg MSG_001 [Teddie]]
Yosukeeeee! You're human after aaaall!

[msg MSG_002 [Yosuke]]
Huh? What are you crying about?
You don't even know what I've been[n]through!
Waking up in some jungle―full of talking[n]dinosaurs!? This makes no sense...

[sel SEL_003 top]
I'm glad you were safe.
Are you hurt?

[msg MSG_004 [Yosuke]]
Uh, yeah, but it's no big―
W-Wait! Who are you!?

[msg MSG_005 [P4 Hero]]
These are our companions that we met[n]here. They're Persona-users, just like[n]us.

[msg MSG_006 [Morgana]]
We got sucked into this world just like[n]you did.
Now we've teamed up to find a way back[n]to our own worlds. Pleased to meet you!

[msg MSG_007 [Yosuke]]
Same here... So, uh, are you a cat in a[n]costume, or a person in a cat costume,[n]like with Teddie, or...?

[msg MSG_008 [Morgana]]
Listen to me. I am NOT in a costume, and[n]I am NOT a cat!

[msg MSG_009 [P4 Hero]]
...Anyway, I'm glad you're safe, Yosuke.[n]We were all really worried about you.

[msg MSG_010 [Yosuke]]
Aw, thanks, guys. Sorry for worrying[n]you...
I would've managed better if I were[n]alone, but I've been trying to protect[n]this talking dinosaur I met here...

[msg MSG_011 [Kanji]]
You fought your way here... all by[n]yourself? That's badass, Yosuke-senpai!

[msg MSG_012 [Yosuke]]
Haha, I'm all beat up though... I guess[n]that makes these wounds my medals of[n]honor?

[msg MSG_013 [Timid herbivore]]
Um... Thank you...

[msg MSG_014 [Yosuke]]
Aw, don't worry about it! We gotta help[n]each other out when we're in trouble,[n]y'know.
...Hey, look who's back. I guess they[n]were worried about you too.

[msg MSG_015 [Timid herbivore]]
......

[msg MSG_016 [Stubborn herbivore]]
......

[msg MSG_017 [Ryuji]]
See? We saved her! Aren't you glad?

[msg MSG_018 [Nervous herbivore]]
......

[msg MSG_019 [Chie]]
Oh yeah! As good an ending as we could[n]ask for!

[msg MSG_020 [Stubborn herbivore]]
......

[msg MSG_021 [P3 Fem Protag]]
Don't they seem to be reacting kinda...[n]strangely?

[msg MSG_022 [Stubborn herbivore]]
So... Should we do the thing?

[msg MSG_023 [Nervous herbivore]]
...Y-Yeah, I guess so.

[msg MSG_024 [Stubborn herbivore]]
Time to put it to a vote.

[msg MSG_025 [Kanji]]
Wait―what!?

[msg MSG_026 [Stubborn herbivore]]
All those who think we should allow the[n]humans to remain in our herd, raise your[n]hand!

[msg MSG_027 [Yosukesaurus]]
......

[msg MSG_028 [Ann]]
Hey! What the hell!?

[msg MSG_029 [Timid herbivore]]
......

[msg MSG_030 [Stubborn herbivore]]
Now, all those who think we should kick[n]them out, raise your hand!

[msg MSG_031 [Stubborn herbivore]]
Based on a unanimous vote, the humans[n]are hereby kicked out. Leave them here.

[msg MSG_032 [Haru]]
But, why?

[msg MSG_033 [Yosukesaurus]]
......
*sigh* It's all your fault...

[msg MSG_034 [Yosuke]]
Holy―He has my head!!! What the hell is[n]happening here!?

[msg MSG_035 [Yosukesaurus]]
You guys ignored the majority rule!

[msg MSG_036 [Yosuke]]
Wha... What are you even talking about?

[msg MSG_037 [Yosukesaurus]]
We're done with you guys. Just... go and[n]do whatever you want, but leave us[n]alone!

[msg MSG_038 [Makoto]]
And there they go...

[msg MSG_039 [Yosuke]]
Dude... What was all that about?
And WHY did he have MY HEAD!? I have no[n]idea what's happening, and I'm getting[n]really freaked out!

[sel SEL_040 top]
It's a long story.
If you calm down, I'll tell you.

[msg MSG_041 [Yukiko]]
Yeah―Yosuke-kun seems exhausted, too. It[n]might be better if we talked about it in[n]a safer place.

[msg MSG_042 [Yosuke]]
Yeah... You're right. Go ahead and lay[n]it on me―I'm listening.

[msg MSG_043 [Yukiko]]
Well, it's a long story... it might be[n]better if we talked about it in a safer[n]place.
Yosuke-kun seems exhausted, too...

[msg MSG_044 [Yusuke]]
Well then, let's return to the movie[n]theater.

[msg MSG_045 [Yosuke]]
Wait―did you say a movie theater? Your[n]base isn't some cave or tent!?

[msg MSG_046 [Morgana]]
Okay, I guess we should explain SOME[n]things along the way. C'mon, follow us.

