[msg MSG_000 [Ryuji]]
Hell yeah! That dumbass dino followed us[n]here!

[msg MSG_001 [Futaba]]
The activation switch should be nearby―[n]Electrify the gate!

[msg MSG_002 [Kanji]]
Alright, let's do this!

[msg MSG_003 [Kanji]]
Huh!? It ain't workin'!?

[msg MSG_004 [P3 Fem Protag]]
Let me try!

[msg MSG_005 [P3 Fem Protag]]
Huh...? Is it broken!?

[msg MSG_006 [Akechi]]
It's not lit up... The power seems to be[n]off.
That explains why the gate was left wide[n]open.

[msg MSG_007 [Ann]]
Oh, no! How do we turn it on!?

[msg MSG_008 [Naoto]]
Perhaps there's a backup power supply[n]somewhere?

[msg MSG_009 [Ryuji]]
Backup power supply! Right! Let's get to[n]searching!

[msg MSG_010 [Gaudy carnivore]]
GRRRROOOOOOOAR!

[msg MSG_011 [Yusuke]]
This is bad! It's about to get past the[n]gate!

[msg MSG_012 [P4 Hero]]
Then... I'll stall it.

[msg MSG_013 [Teddie]]
Sensei!? Y-You can't...!

[sel SEL_014 top]
I'm coming too!
Wait!

[msg MSG_015 [Ann]]
It's no use, he can't hear us! He's[n]already nearly there!

[msg MSG_016]
I can't leave [f 6 1 12 0 0 0] to deal with that[n]carnivore alone...!

[msg MSG_017 [Chie]]
Wha―You too, Joker!?

