[msg MSG_000 [Kamoshidaman]]
ムUstedes, criminales insignificantes, estホn perturbando el orden de este mundo!

[msg MSG_000_5 [Kamoshidaman]]
ムEs hora de que perezcan! ムMボrenme, YO soy la justicia!

[msg MSG_001 [Makoto]]
Tu justicia ciega no es mホs que basura egoc〒ntrica.

[msg MSG_002 [Haru]]
ムEres un falso h〒roe que no representa nada... debes entrar en razポn!

[msg MSG_003 [Kamoshidaman]]
ムUSTEDES son las que deben entrar en razポn! ムJA, JA, JA!

