[msg MSG_000 [Kamoshidaman]]
ムJA, JA, JA!

[msg MSG_000_5 [Kamoshidaman]]
ムLa justicia absoluta estホ aquボ! ムMホs les vale estar preparados, criminales!

[msg MSG_001 [Ryuji]]
ムJe, je! ムTe mostraremos el poder de los Ladrones Fantasma!

[msg MSG_003 [Kamoshidaman]]
ムJA, JA, JA!

[msg MSG_004 [Ryuji]]
ムメNuestros ataques no estホn funcionando?!

[msg MSG_005 [Yusuke]]
Lo estamos golpeando, pero...

[msg MSG_007 [Kamoshidaman]]
メVen? Es exactamente como dije.

[msg MSG_007_5 [Kamoshidaman]]
Este es el poder de la justicia absoluta... ムMi poder como gobernante incuestionable!

[msg MSG_011 [P3 Fem Protag]]
ムメRealmente no podemos derrotarlo?!

[msg MSG_006 [Ann]]
Es como si mi cuerpo se debilitara...

[msg MSG_012 [Akechi]]
Argh, apenas puedo moverme... Es como si realmente no pudiera desafiar su voluntad...

[msg MSG_013 [Morgana]]
ムEstamos en problemas!

