[msg MSG_000 [Caroline]]
ムJa, ja, ja! ムNo necesitamos ayuda para derrotar a los prisioneros!

[msg MSG_001 [Justine]]
Deberボas sentirte honrado, Recluso.

[msg MSG_010 [Caroline]]
Mmm. Supongo que fuimos demasiado suaves con ellos.

[msg MSG_011 [Justine]]
...Se acabポ la diversiポn.

[msg MSG_020 [Caroline]]
Argh... ムTodavボa no hemos terminado contigo!

[msg MSG_021 [Margaret]]
Ah, no puedo seguir viendo esto.

[msg MSG_022 [Justine]]
...メQu〒 haces? Todavボa podemos pelear.

[msg MSG_023 [Margaret]]
*risita* No me malinterpretes. Pero hay una manera adecuada de librar estas batallas.
ムLes dar〒 un ejemplo!

[msg MSG_030 [Margaret]]
メRealmente tienes tanto poder...? No me lo esperaba...
Mmm... Bien. ムYa no tengo que contenerme!

[msg MSG_031 [Caroline]]
ムメEh?!

[msg MSG_032 [Caroline]]
...メムQu〒 pasa con esa mirada, Reclusos!? ムNo es como si estuviera asustada o algo asボ!

[msg MSG_033 [Justine]]
ムCaroline, concentrate!

[msg MSG_040 [Margaret]]
※マーロレ7:が先L倒sた会話

[msg MSG_050 [Margaret]]
*risita* Hacボa tiempo que no tenボa un desafボo asボ, esto es maravilloso.

[msg MSG_051 [Theodore]]
Bien, yo me encargo.

[msg MSG_052 [Caroline]]
ムメEh...?! ムNo te metas en nuestra pelea!

[msg MSG_053 [Theodore]]
Vamos, メrealmente lucharホn en esa condiciポn?

[msg MSG_054 [Justine]]
...Quizホs serボa mejor calmarnos y aceptar su ayuda...

[msg MSG_060 [Theodore]]
Argh... gah...

[msg MSG_061 [Caroline]]
Ja, uf... メQu〒 pasa, Theodore? ムEstabas tan ansioso por intervenir!

[msg MSG_062 [Justine]]
Caroline, mira. Los prisioneros estホn acabando con Theodore.
Si bajamos la guardia, seremos las siguientes en caer.

[msg MSG_063 [Caroline]]
ムLo s〒!

[msg MSG_070 [Theodore]]
※.ヰ(ミが双子oq先L倒sた

[msg MSG_080 [Theodore]]
Incluso juntos, no podemos ganar... Impresionante.
...Dejo el resto en tus manos, Hermana.

[msg MSG_081 [Elizabeth]]
Mi momento ha llegado. Yo, Elizabeth, ser〒 tu oponente.
...Aunque hubiera preferido ser la primera.
Oh, メlucharホn conmigo?

[msg MSG_082 [Caroline]]
ムPor supuesto!

[msg MSG_083 [Elizabeth]]
ムEse es el espボritu! ムVamos!

[msg MSG_090 [Caroline]]
ムJa! メQu〒 pasa, Elizabeth? メEstホs cansada?

[msg MSG_091 [Elizabeth]]
Caroline, resolveremos esto despu〒s de clase. Trae tu dinero del almuerzo.

[msg MSG_092 [Justine]]
...Al menos ustedes parecen tener energボa de sobra...

[msg MSG_093 [Elizabeth]]
*risita* Bueno, rara vez podemos disfrutar de una pelea de este nivel.
Cr〒eme, ムnecesitas mantener la compostura para disfrutarlo!

[msg MSG_100 [Elizabeth]]
Bien hecho.

[msg MSG_110 [Justine]]
Qu〒 sensaciポn tan curiosa... Asボ que esto es "diversiポn", メverdad...?

[msg MSG_111 [Caroline]]
ムNos hicieron pasar un buen rato, Reclusos!

[msg MSG_112 [Elizabeth]]
Una victoria perfecta... Les ofrezco mis mayores elogios, desde lo mホs profundo de mi corazポn.

