[msg MSG_000 [Yusuke]]
Nuevos enemigos... Tienen una forma[n]interesante.

[msg MSG_001 [Ryuji]]
Bien, estoy seguro de que ser茨 pan[n]comido si descubrimos sus debilidades,[n]夷verdad?

[msg MSG_002 [Futaba]]
En realidad... son m茨s agresivas que las[n]de antes. 斡Tengan cuidado!

[msg MSG_BTL_605_003 [Futaba]]
Siempre estoy registrando los datos[n]cuando golpean a una Sombra.
Av胤senme si quieren echar un vistazo.

