[msg MSG_000 [Elizabeth]]
Bien. Parece que el tiempo de hablar termino.
Ahora, solo conc〒ntrate en utilizar tu poder al mホximo.

[msg MSG_010 [Elizabeth]]
Deberボa advertirte que no soy ajena a este tipo de batallas...
Ah, メesto...? No, no es nada.
No te preocupes por mボ... Te aconsejo que intentes matarme.

[msg MSG_020 [Elizabeth]]
Esto es magnボfico. ムCreo que me estoy dejando llevar un poco!

[msg MSG_030 [Elizabeth]]
*risita* Parece que tenボa razポn. Tu espボritu es admirable.
Sin embargo, recuerda que juzgar mal a tu rival, especialmente a estas alturas, serボa perjudicial para tu poder.

[msg MSG_040 [Elizabeth]]
Buen trabajo. Tu poder es realmente impresionante...

