[msg MSG_BTL_TUTORIAL_842_ENC]
Reservado

[msg MSG_BTL_TUTORIAL_842_101]
ぢよょ "にもょや ちよよれろ" ゅよれ ぼよゆらぺォまるよれ らゎまぽまょ[n]らるよらよるぼもよょぺる ぺれもれろまょぼもぺ ぺ ろるぺわイれ ぽま ゎょ [f 0 1 2]にもょや[n]ちよよれろ[f 0 1 0]デ りゎま れま ぺぼろもわぺ ぼゎぺょぽよ ぺゅむゎもまょ むよゅらまぺ ぺ[n]ゎょ まょまゆもむよテ

[msg MSG_BTL_TUTORIAL_842_102]
El Link Boost hace que el pr吋ximo[n]miembro del grupo que act雨e obtenga dos[n]efectos.

[msg MSG_BTL_TUTORIAL_842_103]
ぢよょろもょグぺ ぺろぺぼぺょぽよ ゅぺれ ぽまほもゅもぽぺぽまれ ぽまゅ まょまゆもむよ[n]まょ まゅ ゆもれゆよ ろゎるょよデ ィを よほろまょぽるァれ ぼぺぽぺ わまん ゆァれ[n]まみまぼろよれ ぽま にもょや ちよよれろ らぺるぺ まゅまむもる!

[msg MSG_BTL_TUTORIAL_842_104]
Aprovecha este ataque encadenado para[n]obtener ventaja en la batalla.

[msg MSG_BTL_TUTORIAL_842_HP_]
Reservado

[msg MSG_BTL_TUTORIAL_842_HP__2]
Reservado

[msg MSG_BTL_TUTORIAL_842_HP__3]
Reservado

[msg MSG_BTL_TUTORIAL_842_BTL]
Reserva

