[msg MSG_000 [Kamoshidaman]]
斡Ustedes, criminales insignificantes, est茨n perturbando el orden de este mundo!

[msg MSG_000_5 [Kamoshidaman]]
斡Es hora de que perezcan! 斡M胤renme, YO soy la justicia!

[msg MSG_001 [Makoto]]
Tu justicia ciega no es m茨s que basura egoc姻ntrica.

[msg MSG_002 [Haru]]
斡Eres un falso h姻roe que no representa nada... debes entrar en raz吋n!

[msg MSG_003 [Kamoshidaman]]
斡USTEDES son las que deben entrar en raz吋n! 斡JA, JA, JA!

