[msg MSG_000 [Doe]]
Continuar〒 proyectando pelボculas para los d〒biles...
メDe qu〒 te servirホ enfrentar la realidad despu〒s de tanto tiempo?

[msg MSG_001 [P3 Fem Protag]]
Las personas solo pueden aprender del dolor experimentホndolo.
Es por el dolor que estホn dispuestas a ayudar a otras que sufren.

[msg MSG_002 [P4 Hero]]
Si te caes en tu camino, estホ bien detenerte; todo lo que necesitas es mirar a tu alrededor.

[msg MSG_003 [P3 Hero]]
Seguro encontrarホs personas que te ofrecerホn ayuda.
Una vez te ayuden a encontrar tu camino y levantarte, puedes seguir intentホndolo.

[msg MSG_004 [Hikari]]
Yo... No, nosotros...
ムCaminaremos juntos por ese camino hasta el final!

