[msg MSG_000 [Yusuke]]
Nuevos enemigos... Tienen una forma interesante.

[msg MSG_001 [Ryuji]]
Bien, seguro de que ser茨 pan comido si descubrimos sus debilidades, 夷verdad?

[msg MSG_002 [Futaba]]
En realidad... son m茨s agresivas que las de antes. 斡Tengan cuidado!

[msg MSG_BTL_605_003 [Futaba]]
Siempre registro los datos cuando atacan a una Sombra.
Av胤senme si quieren echar un vistazo.

