[msg MSG_000 [Yosukesaurio]]
メPor qu〒 luchan por alguien mホs? ムQu〒 molestos…!

[msg MSG_000_5 [Yosukesaurio]]
ムTomen la indirecta y mueran de una vez!

[msg MSG_001 [Naoto]]
Saber cuホndo retirarse es importante. Pero...

[msg MSG_002 [Yosuke]]
ムDe ninguna manera abandonarボamos a nuestros amigos aquボ!

[msg MSG_003 [Chie]]
ムSi no hiciera lo que considero correcto, me arrepentirボa!

[msg MSG_004 [Teddie]]
ムAsボ es! No importa lo que digan los demホs...

[msg MSG_005 [P4 Hero]]
ムSeguiremos el camino en el que creemos!

