[msg MSG_BTL_TUTORIAL_840_ENC]
Reserved

[msg MSG_BTL_TUTORIAL_840_101]
"Afinidades y Debilidades" Todos los ataques tienen una [f 0 1 2]afinidad[f 0 1 0], como el Fuego, y los enemigos pueden ser d姻biles[f 0 1 0] a ellos.

[msg MSG_BTL_TUTORIAL_840_102]
Ataca teniendo en cuenta la debilidad del enemigo y causar茨s un da隠o masivo, adem茨s de forzar a tu desafortunado oponente a entrar en estado de Derribo[f 0 1 0].

[msg MSG_BTL_TUTORIAL_840_103]
"Enemigos Derribados y Ataques Combinados" Los enemigos derribados tomar茨n su turno al final en cada ronda. Si todos son derribados, tendr茨s la oportunidad de realizar un [f 0 1 2]Ataque Combinado,[f 0 1 0] 斡que es la oportunidad perfecta para infligir un da隠o extremo!

[msg MSG_BTL_TUTORIAL_840_104]
"Informaci吋n del Objetivo" Mientras cambias entre los enemigos, aparecer茨 informaci吋n 雨til sobre ellos: Se mostrar茨 el icono [f 0 1 2]D畏BIL[f 0 1 0] si la afinidad de tu ataque ha sido efectiva en batallas anteriores contra ese enemigo. Por otro lado, si la afinidad de tu ataque nunca se ha utilizado contra ese enemigo, se mostrar茨 un icono [f 0 1 2]sin datos[f 0 1 0].

[msg MSG_BTL_TUTORIAL_840_105]
Para facilitarlo, el tipo de ataque elegido por cada compa隠ero se mostrar茨 sobre el cursor del objetivo.

[msg MSG_BTL_TUTORIAL_840_106]
斡Prueba ataques con afinidades diferentes con cada nuevo enemigo para aprender sus debilidades!

[msg MSG_BTL_TUTORIAL_840_107]
"Analizar" Puedes ver informaci吋n adicional sobre las Sombras enemigas presionando el [f 0 1 2]Bot吋n L[f 0 1 0].

[msg MSG_BTL_TUTORIAL_840_201]
Reservado

[msg MSG_BTL_TUTORIAL_840_HP_]
Reservado

[msg MSG_BTL_TUTORIAL_840_HP__2]
Reservado

[msg MSG_BTL_TUTORIAL_840_HP__3]
Reservado

[msg MSG_BTL_TUTORIAL_840_BTL]
Reservado

