[msg MSG_000 [Kamoshidaman]]
斡Ustedes, criminales insignificantes,[n]est茨n perturbando el orden del mundo!

[msg MSG_000_5 [Kamoshidaman]]
斡Es hora de que perezcan! 斡M胤renme, soy[n]la justicia!

[msg MSG_001 [Makoto]]
La justicia ciega no es m茨s que basura[n]egoc姻ntrica.

[msg MSG_002 [Haru]]
斡Eres un falso h姻roe que no representa[n]nada... debes entrar en raz吋n!

[msg MSG_003 [Kamoshidaman]]
斡USTEDES son las que deben entrar en[n]raz吋n! 斡JA, JA, JA!

