[msg MSG_0000 [Ryuji]]
ムEh! ムメQu〒 demonios?!

[msg MSG_0001 [Ann]]
ムN-no puede ser!

[msg MSG_0002 [P3 Fem Protag]]
ムメCポmo le crecieron las orejas asボ?!

[msg MSG_0003 [Futaba]]
ムMierda! ムSe transformポ!

[msg MSG_0004 [メKamoshidaman?]]
ムJA, JA, JA! ムVoy a mostrarles mi verdadero poder!

[msg MSG_000 [Ann]]
ムメQU※ es eso?! Es espeluznante... ムN-no puede ser!

[msg MSG_001 [Akechi]]
Es desagradable... pero, メpor qu〒 un conejo?

[msg MSG_002 [Yusuke]]
Lo discutiremos despu〒s. ムAquボ viene!

[msg MSG_003 [メKamoshidaman?]]
ムMalhechores corruptos! ムEntreguen sus armas y rボndanse!

[msg MSG_004 [メKamoshidaman?]]
La justicia... ムLa justicia siempre gana!

[msg MSG_005 [メKamoshidaman?]]
ムImposible...! ムメCポmo es que yo, la justicia encarnada, es derrotada?!

[msg MSG_006 [メKamoshidaman?]]
ムメPor qu〒?! メCポmo...? Mi justicia...

