[msg MSG_000 [P3 Fem Protag]]
ムChicos, メestホn bien?!

[msg MSG_001 [Yosuke]]
ムNosotros nos encargamos!

[msg MSG_002 [Chico Agresivo]]
ムメQui〒n eres?!

[msg MSG_003 [Perro]]
ムGuau, guau!

[msg MSG_004 [Makoto]]
ムRetrocedan y pポnganse a salvo!

[msg MSG_005 [Chica Espボrita]]
ムメEh...?! メQu〒 pasa con ese ej〒rcito de enmascarados?

[msg MSG_006 [Chico Con Gorra De B〒isbol]]
ムメPor qu〒 lo sabrボamos?!

[msg MSG_007 [P3 Fem Protag]]
No se preocupen, ムtambi〒n son usuarios de Persona! ムEstホn de nuestro lado!

[msg MSG_008 [Niワo Sombrボo]]
メEh...?

[msg MSG_009 [Chica Bien Vestida]]
ムメPersona?!

