[msg addeffect_000]
Nada

[msg addeffect_001]
Fuerza +1.

[msg addeffect_002]
Fuerza +2.

[msg addeffect_003]
Fuerza +3.

[msg addeffect_004]
Fuerza +4.

[msg addeffect_005]
Fuerza +5.

[msg addeffect_006]
Defensa +1.

[msg addeffect_007]
Defensa +2.

[msg addeffect_008]
Defensa +3.

[msg addeffect_009]
Defensa +4.

[msg addeffect_010]
Defensa +5.

[msg addeffect_011]
Magia +1.

[msg addeffect_012]
Magia +2.

[msg addeffect_013]
Magia +3.

[msg addeffect_014]
Magia +4.

[msg addeffect_015]
Magia +5.

[msg addeffect_016]
Agilidad +1.

[msg addeffect_017]
Agilidad +2.

[msg addeffect_018]
Agilidad +3.

[msg addeffect_019]
Agilidad +4.

[msg addeffect_020]
Agilidad +5.

[msg addeffect_021]
Suerte +1.

[msg addeffect_022]
Suerte +2.

[msg addeffect_023]
Suerte +3.

[msg addeffect_024]
Suerte +4.

[msg addeffect_025]
Suerte +5.

[msg addeffect_026]
M茨x PS +10.

[msg addeffect_027]
M茨x PS +20.

[msg addeffect_028]
M茨x PS +30.

[msg addeffect_029]
M茨x PS +40.

[msg addeffect_030]
M茨x PS +50.

[msg addeffect_031]
M茨x PE +10.

[msg addeffect_032]
M茨x PE +20.

[msg addeffect_033]
M茨x PE +30.

[msg addeffect_034]
M茨x PE +40.

[msg addeffect_035]
M茨x PE +50.

[msg addeffect_036]
Baja probabilidad de provocar P茨nico.

[msg addeffect_037]
Media probabilidad de provocar P茨nico.

[msg addeffect_038]
Alta probabilidad de provocar P茨nico.

[msg addeffect_039]
Baja probabilidad de Envenenar.

[msg addeffect_040]
Media probabilidad de Envenenar.

[msg addeffect_041]
Alta probabilidad de Envenenar.

[msg addeffect_042]
Baja probabilidad de Asustar.

[msg addeffect_043]
Media probabilidad de Asustar.

[msg addeffect_044]
Alta probabilidad de Asustar.

[msg addeffect_045]
Baja probabilidad de Enfurecer.

[msg addeffect_046]
Media probabilidad de Enfurecer.

[msg addeffect_047]
Alta probabilidad de Enfurecer.

[msg addeffect_048]
Baja probabilidad de Marear.

[msg addeffect_049]
Media probabilidad de Marear.

[msg addeffect_050]
Alta probabilidad de Marear.

[msg addeffect_051]
Baja probabilidad de Agotar.

[msg addeffect_052]
Media probabilidad de Agotar.

[msg addeffect_053]
Alta probabilidad de Agotar.

[msg addeffect_054]
Baja probabilidad de Envejecer.

[msg addeffect_055]
Media probabilidad de Envejecer.

[msg addeffect_056]
Alta probabilidad de Envejecer.

[msg addeffect_057]
Baja probabilidad de sellar Magia.

[msg addeffect_058]
Media probabilidad de sellar Magia.

[msg addeffect_059]
Alta probabilidad de sellar Magia.

[msg addeffect_060]
Bajo aumento en la probabilidad de[n]cr胤ticos.

[msg addeffect_061]
Medio aumento en la probabilidad de[n]cr胤ticos.

[msg addeffect_062]
Alto aumento en la probabilidad de[n]cr胤ticos.

[msg addeffect_063]
+1 todos los stats.

[msg addeffect_064]
+2 todos los stats.

[msg addeffect_065]
+3 todos los stats.

[msg addeffect_066]
+4 todos los stats.

[msg addeffect_067]
+5 todos los stats.

[msg addeffect_068]
Fortalece ataques de Fuego un 25%.

[msg addeffect_069]
Fortalece ataques de Hielo un 25%.

[msg addeffect_070]
Fortalece ataques El姻ctricos un 25%.

[msg addeffect_071]
Fortalece ataques de Viento un 25%.

[msg addeffect_072]
Baja probabilidad de reflejar ataques[n]f胤sicos.

[msg addeffect_073]
Media probabilidad de reflejar ataques[n]f胤sicos.

[msg addeffect_074]
Alta probabilidad de reflejar ataques[n]f胤sicos.

[msg addeffect_075]
Resistencia contra el P茨nico.

[msg addeffect_076]
Resistencia contra el Veneno.

[msg addeffect_077]
Resistencia contra el Miedo.

[msg addeffect_078]
Resistencia contra la Ira.

[msg addeffect_079]
Resistencia contra el Mareo.

[msg addeffect_080]
Resistencia contra el Cansancio.

[msg addeffect_081]
Resistencia contra el Envejecimiento.

[msg addeffect_082]
Resistencia contra sellos de Magia.

[msg addeffect_083]
Activa Tarukaja al inicio del combate.

[msg addeffect_084]
Activa Rakukaja al inicio del combate.

[msg addeffect_085]
Activa Sukukaja al inicio del combate.

[msg addeffect_086]
Fuerza +10.

[msg addeffect_087]
Defensa +10.

[msg addeffect_088]
Magia +10.

[msg addeffect_089]
Agilidad +10.

[msg addeffect_090]
Suerte +10.

[msg addeffect_091]
M茨x PS +100.

[msg addeffect_092]
Baja probabilidad de infligir estados de[n]padecimiento.

[msg addeffect_093]
Media probabilidad de infligir estados[n]de padecimiento.

[msg addeffect_094]
Alta probabilidad de infligir estados de[n]padecimiento.

[msg addeffect_095]
Reduce da隠o f胤sico recibido un 10%.

[msg addeffect_096]
Reduce da隠o f胤sico recibido un 20%.

[msg addeffect_097]
Reduce da隠o f胤sico recibido un 30%.

[msg addeffect_098]
Reduce da隠o de Fuego recibido un 10%.

[msg addeffect_099]
Reduce da隠o de Fuego recibido un 20%.

[msg addeffect_100]
Reduce da隠o de Fuego recibido un 30%.

[msg addeffect_101]
Reduce da隠o de Hielo recibido un 10%.

[msg addeffect_102]
Reduce da隠o de Hielo recibido un 20%.

[msg addeffect_103]
Reduce da隠o de Hielo recibido un 30%.

[msg addeffect_104]
Reduce da隠o de Viento recibido un 10%.

[msg addeffect_105]
Reduce da隠o de Viento recibido un 20%.

[msg addeffect_106]
Reduce da隠o de Viento recibido un 30%.

[msg addeffect_107]
Reduce da隠o El姻ctrico recibido un 10%.

[msg addeffect_108]
Reduce da隠o El姻ctrico recibido un 20%.

[msg addeffect_109]
Reduce da隠o El姻ctrico recibido un 30%.

[msg addeffect_110]
Reduce da隠o elemental recibido un 10%.

[msg addeffect_111]
Reduce da隠o elemental recibido un 20%.

[msg addeffect_112]
Reduce da隠o elemental recibido un 30%.

[msg addeffect_113]
Reduce probabilidad de tropezar.

[msg addeffect_114]
Reduce un poco la probabilidad de[n]tropezar.

[msg addeffect_115]
Reduce mucho la probabilidad de[n]tropezar.

[msg addeffect_116]
Aumenta probabilidad de esquivar ataques[n]f胤sicos.

[msg addeffect_117]
Aumenta un poco la probabilidad de[n]esquivar ataques f胤sicos.

[msg addeffect_118]
Aumenta mucho la probabilidad de[n]esquivar ataques f胤sicos.

[msg addeffect_119]
Aumenta probabilidad de esquivar ataques[n]de Fuego.

[msg addeffect_120]
Aumenta un poco la probabilidad de[n]esquivar ataques de Fuego.

[msg addeffect_121]
Aumenta mucho la probabilidad de[n]esquivar ataques de Fuego.

[msg addeffect_122]
Aumenta probabilidad de esquivar ataques[n]de Hielo.

[msg addeffect_123]
Aumenta un poco la probabilidad de[n]esquivar ataques de Hielo.

[msg addeffect_124]
Aumenta mucho la probabilidad de[n]esquivar ataques de Hielo.

[msg addeffect_125]
Aumenta probabilidad de esquivar ataques[n]de Viento.

[msg addeffect_126]
Aumenta un poco la probabilidad de[n]esquivar ataques de Viento.

[msg addeffect_127]
Aumenta mucho la probabilidad de[n]esquivar ataques de Viento.

[msg addeffect_128]
Aumenta probabilidad de esquivar ataques[n]El姻ctricos.

[msg addeffect_129]
Aumenta un poco la probabilidad de[n]esquivar ataques El姻ctricos.

[msg addeffect_130]
Aumenta mucho la probabilidad de[n]esquivar ataques El姻ctricos.

[msg addeffect_131]
Aumenta la probabilidad de esquivar[n]ataques elementales.

[msg addeffect_132]
Aumenta un poco la probabilidad de[n]esquivar ataques elementales.

[msg addeffect_133]
Aumenta mucho la probabilidad de[n]esquivar ataques elementales.

[msg addeffect_134]
EXP +150%

[msg addeffect_135]
Reduce PE a la mitad al final de un[n]combate.

[msg addeffect_136]
Carisma

[msg addeffect_137]
Ninguno

[msg addeffect_138]
M茨x PE +100.

[msg addeffect_139]
+10 todos los stats.

[msg addeffect_140]
Costo de PE triplicado.

[msg addeffect_141]
Ninguno

[msg addeffect_142]
Ninguno

[msg addeffect_143]
Ninguno

[msg addeffect_144]
Resistencia al Fuego.

[msg addeffect_145]
Resistencia al Hielo.

[msg addeffect_146]
Resistencia al Viento.

[msg addeffect_147]
Resistencia El姻ctrica.

[msg addeffect_148]
Refleja el Fuego.

[msg addeffect_149]
Refleja el Hielo.

[msg addeffect_150]
Refleja el Viento.

[msg addeffect_151]
Refleja la Electricidad.

[msg addeffect_152]
Absorve el Fuego.

[msg addeffect_153]
Absorbe Hielo

[msg addeffect_154]
Absorbe Viento

[msg addeffect_155]
Absorve la Electricidad.

[msg addeffect_156]
Ninguno

[msg addeffect_157]
Ninguno

[msg addeffect_158]
Ninguno

[msg addeffect_159]
Ninguno

[msg addeffect_160]
Ninguno

[msg addeffect_161]
Ninguno

[msg addeffect_162]
Ninguno

[msg addeffect_163]
Ninguno

[msg addeffect_164]
Ninguno

[msg addeffect_165]
Ninguno

[msg addeffect_166]
Ninguno

[msg addeffect_167]
Ninguno

[msg addeffect_168]
Ninguno

[msg addeffect_169]
Ninguno

[msg addeffect_170]
Ninguno

[msg addeffect_171]
Ninguno

[msg addeffect_172]
Ninguno

[msg addeffect_173]
Ninguno

[msg addeffect_174]
Ninguno

[msg addeffect_175]
Ninguno

[msg addeffect_176]
Ninguno

[msg addeffect_177]
Ninguno

[msg addeffect_178]
Ninguno

[msg addeffect_179]
Ninguno

[msg addeffect_180]
Ninguno

[msg addeffect_181]
Ninguno

[msg addeffect_182]
Ninguno

[msg addeffect_183]
Ninguno

[msg addeffect_184]
Ninguno

[msg addeffect_185]
Ninguno

[msg addeffect_186]
Ninguno

[msg addeffect_187]
Ninguno

[msg addeffect_188]
Ninguno

[msg addeffect_189]
Fortalece ataques de Fuego.

[msg addeffect_190]
Fortalece ataques de Hielo.

[msg addeffect_191]
Fortalece ataques de Viento.

[msg addeffect_192]
Fortalece ataques de Electricidad.

[msg addeffect_193]
Debilita ataques de Fuego.

[msg addeffect_194]
Debilita ataques de Hielo.

[msg addeffect_195]
Debilita ataques de Viento.

[msg addeffect_196]
Debilita ataques de Electricidad.

