[msg addeffect_000]
Nada

[msg addeffect_001]
Fr +1

[msg addeffect_002]
Fr +2

[msg addeffect_003]
Fr +3

[msg addeffect_004]
Fr +4

[msg addeffect_005]
Fr +5

[msg addeffect_006]
Rs +1

[msg addeffect_007]
Rs +2

[msg addeffect_008]
Rs +3

[msg addeffect_009]
Rs +4

[msg addeffect_010]
Rs +5

[msg addeffect_011]
Ma +1

[msg addeffect_012]
Ma +2

[msg addeffect_013]
Ma +3

[msg addeffect_014]
Ma +4

[msg addeffect_015]
Ma +5

[msg addeffect_016]
Ag +1

[msg addeffect_017]
Ag +2

[msg addeffect_018]
Ag +3

[msg addeffect_019]
Ag +4

[msg addeffect_020]
Ag +5

[msg addeffect_021]
Su +1

[msg addeffect_022]
Su +2

[msg addeffect_023]
Su +3

[msg addeffect_024]
Su +4

[msg addeffect_025]
Su +5

[msg addeffect_026]
PS +10

[msg addeffect_027]
PS +20

[msg addeffect_028]
PS +30

[msg addeffect_029]
PS +40

[msg addeffect_030]
PS +50

[msg addeffect_031]
PE +10

[msg addeffect_032]
PE +20

[msg addeffect_033]
PE +30

[msg addeffect_034]
PE +40

[msg addeffect_035]
PE +50

[msg addeffect_036]
Baja probabilidad de provocar Pホnico

[msg addeffect_037]
Media probabilidad de provocar Pホnico

[msg addeffect_038]
Alta probabilidad de provocar Pホnico

[msg addeffect_039]
Baja probabilidad de Envenenar

[msg addeffect_040]
Media probabilidad de Envenenar

[msg addeffect_041]
Alta probabilidad de Envenenar

[msg addeffect_042]
Baja probabilidad de Asustar

[msg addeffect_043]
Media probabilidad de Asustar

[msg addeffect_044]
Alta probabilidad de Asustar

[msg addeffect_045]
Baja probabilidad de Enfurecer

[msg addeffect_046]
Media probabilidad de Enfurecer

[msg addeffect_047]
Alta probabilidad de Enfurecer

[msg addeffect_048]
Baja probabilidad de Marear

[msg addeffect_049]
Media probabilidad de Marear

[msg addeffect_050]
Alta probabilidad de Marear

[msg addeffect_051]
Baja probabilidad de Agotar

[msg addeffect_052]
Media probabilidad de Agotar

[msg addeffect_053]
Alta probabilidad de Agotar

[msg addeffect_054]
Baja probabilidad de Envejecer

[msg addeffect_055]
Media probabilidad de Envejecer

[msg addeffect_056]
Alta probabilidad de Envejecer

[msg addeffect_057]
Baja probabilidad de atar Magia

[msg addeffect_058]
Media probabilidad de atar Magia

[msg addeffect_059]
Alta probabilidad de atar Magia

[msg addeffect_060]
Probabilidad crボtica aumentada

[msg addeffect_061]
Probabilidad crボtica aumentada+

[msg addeffect_062]
Probabilidad crボtica aumentada++

[msg addeffect_063]
Todos los stats. +1

[msg addeffect_064]
Todos los stats. +2

[msg addeffect_065]
Todos los stats. +3

[msg addeffect_066]
Todos los stats. +4

[msg addeffect_067]
Todos los stats. +5

[msg addeffect_068]
Fortalece ataques de Fuego un 25%.

[msg addeffect_069]
Fortalece ataques de Hielo un 25%.

[msg addeffect_070]
Fortalece ataques El〒ctricos un 25%.

[msg addeffect_071]
Fortalece ataques de Viento un 25%.

[msg addeffect_072]
Probabilidad de reflejar fボsicos

[msg addeffect_073]
Probabilidad de reflejar fボsicos+

[msg addeffect_074]
Probabilidad de reflejar fボsicos++

[msg addeffect_075]
Resistir Pホnico

[msg addeffect_076]
Resistir Veneno

[msg addeffect_077]
Resistir Miedo

[msg addeffect_078]
Resistir Ira

[msg addeffect_079]
Resistir Mareo

[msg addeffect_080]
Resistir Cansancio

[msg addeffect_081]
Resistir Envejecimiento

[msg addeffect_082]
Resistir ataduras de Magia.

[msg addeffect_083]
+Auto-Tarukaja

[msg addeffect_084]
+Auto-Rakukaja

[msg addeffect_085]
+Auto-Sukukaja

[msg addeffect_086]
Fr +10.

[msg addeffect_087]
Rs +10.

[msg addeffect_088]
Ma +10.

[msg addeffect_089]
Ag +10.

[msg addeffect_090]
Su +10.

[msg addeffect_091]
PS +100.

[msg addeffect_092]
Probabilidad de infligir estados alterados

[msg addeffect_093]
Probabilidad de infligir estados alterados+

[msg addeffect_094]
Probabilidad de infligir estados alterados++

[msg addeffect_095]
Reduce daワo fボsico un 10%

[msg addeffect_096]
Reduce daワo fボsico un 20%

[msg addeffect_097]
Reduce daワo fボsico un 30%

[msg addeffect_098]
Reduce daワo de Fuego un 10%

[msg addeffect_099]
Reduce daワo de Fuego un 20%

[msg addeffect_100]
Reduce daワo de Fuego un 30%

[msg addeffect_101]
Reduce daワo de Hielo un 10%

[msg addeffect_102]
Reduce daワo de Hielo un 20%

[msg addeffect_103]
Reduce daワo de Hielo un 30%

[msg addeffect_104]
Reduce daワo de Viento un 10%

[msg addeffect_105]
Reduce daワo de Viento un 20%

[msg addeffect_106]
Reduce daワo de Viento un 30%

[msg addeffect_107]
Reduce daワo El〒ctrico un 10%

[msg addeffect_108]
Reduce daワo El〒ctrico un 20%

[msg addeffect_109]
Reduce daワo El〒ctrico un 30%

[msg addeffect_110]
Reduce daワo Mホgico un 10%

[msg addeffect_111]
Reduce daワo Mホgico un 20%

[msg addeffect_112]
Reduce daワo Mホgico un 30%

[msg addeffect_113]
Reduce probabilidad de tropezar

[msg addeffect_114]
Reduce un poco la probabilidad de tropezar

[msg addeffect_115]
Reduce mucho la probabilidad de tropezar

[msg addeffect_116]
Esquivar fボsicos+

[msg addeffect_117]
Esquivar fボsicos

[msg addeffect_118]
Esquivar fボsicos++

[msg addeffect_119]
Esquivar fuego+

[msg addeffect_120]
Esquivar fuego

[msg addeffect_121]
Esquivar fuego++

[msg addeffect_122]
Esquivar hielo+

[msg addeffect_123]
Esquivar hielo

[msg addeffect_124]
Esquivar hielo++

[msg addeffect_125]
Esquivar viento+

[msg addeffect_126]
Esquivar viento

[msg addeffect_127]
Esquivar viento++

[msg addeffect_128]
Esquivar Elec+

[msg addeffect_129]
Esquivar Elec

[msg addeffect_130]
Esquivar Elec++

[msg addeffect_131]
Esquivar Magia+

[msg addeffect_132]
Esquivar Magia

[msg addeffect_133]
Esquivar Magia++

[msg addeffect_134]
Exp. +150%

[msg addeffect_135]
PE a la mitad despu〒s del combate

[msg addeffect_136]
Carisma

[msg addeffect_137]
Ninguno

[msg addeffect_138]
PE +100.

[msg addeffect_139]
Todos los stats. +10

[msg addeffect_140]
Costo PE triplicado

[msg addeffect_141]
Ninguno

[msg addeffect_142]
Ninguno

[msg addeffect_143]
Ninguno

[msg addeffect_144]
Resistencia al Fuego

[msg addeffect_145]
Resistencia al Hielo

[msg addeffect_146]
Resistencia al Viento

[msg addeffect_147]
Resistencia El〒ctrica

[msg addeffect_148]
Refleja el Fuego

[msg addeffect_149]
Refleja el Hielo

[msg addeffect_150]
Refleja el Viento

[msg addeffect_151]
Refleja la Electricidad

[msg addeffect_152]
Absorbe el Fuego

[msg addeffect_153]
Absorbe Hielo

[msg addeffect_154]
Absorbe Viento

[msg addeffect_155]
Absorbe Electricidad

[msg addeffect_156]
Ninguno

[msg addeffect_157]
Ninguno

[msg addeffect_158]
Ninguno

[msg addeffect_159]
Ninguno

[msg addeffect_160]
Ninguno

[msg addeffect_161]
Ninguno

[msg addeffect_162]
Ninguno

[msg addeffect_163]
Ninguno

[msg addeffect_164]
Ninguno

[msg addeffect_165]
Ninguno

[msg addeffect_166]
Ninguno

[msg addeffect_167]
Ninguno

[msg addeffect_168]
Ninguno

[msg addeffect_169]
Ninguno

[msg addeffect_170]
Ninguno

[msg addeffect_171]
Ninguno

[msg addeffect_172]
Ninguno

[msg addeffect_173]
Ninguno

[msg addeffect_174]
Ninguno

[msg addeffect_175]
Ninguno

[msg addeffect_176]
Ninguno

[msg addeffect_177]
Ninguno

[msg addeffect_178]
Ninguno

[msg addeffect_179]
Ninguno

[msg addeffect_180]
Ninguno

[msg addeffect_181]
Ninguno

[msg addeffect_182]
Ninguno

[msg addeffect_183]
Ninguno

[msg addeffect_184]
Ninguno

[msg addeffect_185]
Ninguno

[msg addeffect_186]
Ninguno

[msg addeffect_187]
Ninguno

[msg addeffect_188]
Ninguno

[msg addeffect_189]
Fortalece ataques de Fuego

[msg addeffect_190]
Fortalece ataques de Hielo

[msg addeffect_191]
Fortalece ataques de Viento

[msg addeffect_192]
Fortalece ataques El〒ctricos

[msg addeffect_193]
Debilita ataques de Fuego

[msg addeffect_194]
Debilita ataques de Hielo

[msg addeffect_195]
Debilita ataques de Viento

[msg addeffect_196]
Debilita ataques El〒ctricos

