[msg chara_000]
Blank

[msg chara_001]
(Fila Frontal) Siempre listo para la[n]batalla, mejor con ataques de corte y[n]el姻ctricos.

[msg chara_002]
(Fila Frontal) Un luchador vers茨til,[n]h茨bil con todas las afinidades.

[msg chara_003]
(Fila Frontal) Un luchador 茨gil que se[n]especializa en ataques de corte y[n]Viento.

[msg chara_004]
(Fila Frontal) Una chica experta en kung[n]fu con alta evasi吋n y ataques cr胤ticos.

[msg chara_005]
(Fila Trasera) Elegante, apropiada y[n]mortal, 斡pero cuidado con su salud!

[msg chara_006]
Ninguno

[msg chara_007]
(Fila Frontal) Protege a sus compa隠eros[n]con una alta defensa y ofensa.

[msg chara_008]
(Fila Trasera) Un detective de tama隠o[n]peque隠o, excelente con habilidades de[n]enlace.

[msg chara_009]
(Fila Frontal) Una mascota[n]autoproclamada que ayuda al grupo en[n]combate.

[msg chara_00A]
(Fila Trasera) Una chica de humor[n]variable que sobresale en habilidades de[n]Viento y recuperaci吋n.

[msg chara_00B]
(Fila Frontal) Un presumido con[n]habilidades equilibradas en ataque,[n]defensa y contraataque.

[msg chara_00C]
(Fila Frontal) Un boxeador sin rival que[n]inflige un da隠o extremo.

[msg chara_00D]
(Front or Back) Sella las habilidades[n]del enemigo y las remata con magia de[n]Hielo.

[msg chara_00E]
None

[msg chara_00F]
(Front or Back) Arma anti-sombras que[n]puede activar su Modo Desenfreno.

[msg chara_010]
(Fila Trasera) Es genial con habilidades[n]F胤sicas y de Electricidad, 斡pero tiene[n]poca salud!

[msg chara_011]
(Fila Trasera) R茨pido y maneja magia de[n]Fuego y oscuridad, 斡pero no es[n]resistente!

[msg chara_012]
(Fila Frontal) El tipo m茨s resistente,[n]pero extremadamente vulnerable a la[n]magia.

[msg chara_013]
(Fila Trasera) Zen ataca, mientras que[n]Rei cura. Ambos utilizan habilidades[n]misteriosas...

[msg chara_014]
(Fila Trasera) Zen ha recuperado sus[n]recuerdos y sus habilidades...

