[msg MSG_BTL_TUTORIAL_844_ENC]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_101]
[f 0 5 65278][f 2 1]"Conversi吋n R茨pida"[n]Cuando el Medidor de Grupo se llena hasta cierto punto, puedes realizar una [f 0 1 2]Conversi吋n R茨pida[f 0 1 0] presionando el bot吋n Y durante la acci吋n de un enemigo o un aliado.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_102]
[f 0 5 65278][f 2 1]Una Conversi吋n R茨pida cambiar茨 autom茨ticamente[n]tu equipo al final del turno.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_103]
[f 0 5 65278][f 2 1]Por cierto, todos los miembros del equipo que[n]entren en batalla mediante una Conversi吋n R茨pida[n]se sentir茨n en plena forma y ansiosos por luchar.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_104]
[f 0 5 65278][f 2 1]En comparaci吋n con una Conversi吋n de Equipo ordinaria,[n]la Conversi吋n R茨pida facilita derribar a las Sombras.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP_]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP__2]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP__3]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_BTL]
[f 0 5 65278][f 2 1]Reserva[n][f 1 1][e]

