[msg MSG_000_3 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 201][f 6 1 1 0 0 1][f 6 1 2 0 0 6][f 6 1 3 0 0 2]GRUUUUUUUAAAAH...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_5 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 8][f 3 1 3 0 0 202]夷Se transform吋? 夷En serio puede hacer eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_7 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 1 7][f 1 5][f 6 1 13 0 0 0]　　[n][f 3 1 3 0 0 203]Ngh... Parece que terminamos de hablar de[n]esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 8][f 3 1 3 0 0 204]Has renunciado a tu libertad...[n]夷Es as胤 como quieres vivir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 205][f 6 1 3 0 0 2]斡C茨llate, c茨llate! Si no hago esto... Yo...[n]yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 206][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 6 1 3 0 0 2]斡No tengo m茨s remedio... que eliminarte![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 8][f 3 1 3 0 0 207][f 6 1 2 0 0 6]斡Maldita sea, se ha vuelto completamente loco! 斡Despierta![n][f 1 3 65535][f 1 1][e]

[msg MSG_002_5 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 1 7][f 1 5][f 6 1 13 0 0 0]　　[n][f 3 1 3 0 0 208]斡Todos, listos![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 209][f 6 1 3 0 0 2]N-Nngh... N-No... No puedo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Herbivore Elegante]]
[f 0 5 65278][f 2 1][f 4 6 42 2 1 1][f 3 1 3 0 0 210]夷Qu姻? No puedes echarte atr茨s ahora...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enorme Herb胤voro]]
[f 0 5 65278][f 2 1][f 4 6 48 0 1 0][f 3 1 3 0 0 211]La mayor胤a ha hablado, 夷o prefieres ser expulsado de la manada?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 212][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 6 1 3 0 0 2]No... 斡No quiero que me echen![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 213][f 6 1 2 0 0 10][f 6 1 3 0 0 2]Hey, uh... 夷No es esto suficiente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Nervous Herbivore]]
[f 0 5 65278][f 2 1][f 4 6 47 0 1 3][f 3 1 3 0 0 214]No puedes parar ahora. Esto es por lo que[n]todos votamos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Herbivore Elegante]]
[f 0 5 65278][f 2 1][f 4 6 42 2 1 1][f 3 1 3 0 0 215]As胤 es. No hay manera de que un voto un茨nime[n]sea incorrecto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 216][f 6 1 3 0 0 2]C-Claro... 夷No hay nada que pueda hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Herb胤voro Timid]]
[f 0 5 65278][f 2 1][f 4 6 90 0 1 3][f 3 1 3 0 0 217][f 6 1 2 0 0 10]Eh, hey... Si 姻l sigue as胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Enorme Herb胤voro]]
[f 0 5 65278][f 2 1][f 4 6 48 0 1 1][f 3 1 3 0 0 218][f 6 1 2 0 0 6]夷Quieres quedarte con la manada, verdad? Entonces, 斡m茨s te vale demostrarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 219][f 6 1 2 0 0 0][f 6 1 3 0 0 2]斡Aaaaargh! 斡Bien! Lo har姻... 夷斡Eso es lo que[n]quieres, verdad!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 220][f 6 1 1 0 0 1][f 6 1 2 0 0 1][f 6 1 3 0 0 2]GRRRUUUUUUHHHHHHH...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 24 0 1 7][f 3 1 3 0 0 221][f 6 1 2 0 0 0]Que es... 斡Algo no est茨 bien aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 222][f 6 1 3 0 0 2][f 6 1 2 0 0 1]斡GYAAAAAAH![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Enorme Herb胤voro]]
[f 0 5 65278][f 2 1][f 4 6 48 0 1 1][f 3 1 3 0 0 226]斡Vamos! 斡At茨calos![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Herbivore Elegante]]
[f 0 5 65278][f 2 1][f 4 6 42 2 1 3][f 3 1 3 0 0 227]斡D姻jate de tonter胤as![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Nervous Herbivore]]
[f 0 5 65278][f 2 1][f 4 6 47 0 1 1][f 3 1 3 0 0 228]...斡Hazlo de una vez![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 10 0 7][f 3 1 1 0 0 27051][f 3 1 1 0 0 0]Parece que s吋lo est茨 luchando por los[n]dinosaurios detr茨s de 姻l...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 8][f 3 1 1 0 0 0]斡Maldita sea, esto es terrible! 夷Qu姻 vamos[n]a hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 1 7][f 1 5][f 6 1 13 0 0 0]　　[n][f 3 1 1 0 0 1036]Parece que tendremos que callar a esos dinosaurios...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Vamos, todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_016_5 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 8][f 3 1 3 0 0 3040]斡Muy bien! 斡Lo hicimos![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosukesaurus]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 223][f 6 1 3 0 0 2]E-En serio? Jajaja... Ustedes... realmente son fuertes...[n][f 1 3 65535][f 1 1][e]

