[msg MSG_000 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 121][f 6 1 2 0 0 6][f 6 1 3 0 0 2]斡Perm胤tanme enseñarles el trabajo de la[n]justicia y la paz![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 1 7][f 3 1 3 0 0 122]No me importa aprender algo tan presuntuoso[n]como eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 123][f 6 1 3 0 0 2]Malditos insolente... 斡Sin embargo, Kamoshidaman[n]no perder茨![n][f 1 3 65535][f 1 1][e]

[msg MSG_002_5 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 124][f 6 1 3 0 0 2]斡No perdono a nadie que interrumpa la paz de[n]la ciudad de Kamo![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 125][f 6 1 2 0 0 10][f 6 1 3 0 0 2]斡Imposible![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 126][f 6 1 3 0 0 2]斡Soy justicia absoluta! 夷Cómo podr胤a ser[n]derrocado por tales canallas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 127][f 6 1 3 0 0 2]斡Idiotas! 夷Por qu姻 no lo entiendes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 128][f 6 1 3 0 0 2]斡Soy el 茨rbitro de la justicia! 斡Todo lo que[n]tienes que hacer es callarte y[n]obedecerme![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 129][f 6 1 2 0 0 6][f 6 1 3 0 0 2]斡Pensar que me atrapar胤as as胤! Malditos[n]malvados, curando la ciudad de Kamo![n][f 1 3 65535][f 1 1][e]

