[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 701][f 6 1 3 0 0 2]Bueno, todos... Yo, Theodore, ser姻 tu oponente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 702][f 6 1 3 0 0 2]Perm胤tanme presenciar su fuerza de primera mano.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 703][f 6 1 3 0 0 2]Ya veo. Me fascinas tanto como palomitas de ma胤z.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 704][f 6 1 3 0 0 2]Pero esto no est茨 cerca del alcance de[n]tu poder, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 705][f 6 1 3 0 0 2]Me siento orgulloso de mi fuerza. Y ese[n]orgullo no me permitir茨 vacilar tan pronto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 706][f 6 1 3 0 0 2]Impresionante... Pero los cumplidos[n]pueden esperar hasta que el polvo se haya instalado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 707][f 6 1 3 0 0 2]Ahora, perm胤tanme presenciar el alcance[n]completo de su poder.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Theodore]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 708][f 6 1 3 0 0 2]Magn胤fico... As胤 que este es tu poder...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 709][f 6 1 3 0 0 2]Lo he presenciado por m胤 mismo.[n][f 1 3 65535][f 1 1][e]

