[msg MSG_BTL_TUTORIAL_845_ENC]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_101]
[f 0 5 65278][f 2 1]"Sombras Raras"[n]A veces, en los calabozos aparecer茨n enemigos especiales conocidos como [f 0 1 2]Sombras Raras[f 0 1 0].[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_102]
[f 0 5 65278][f 2 1]Las Sombras Raras pueden parecerse a las Sombras[n]ordinarias, 斡pero hay una diferencia![n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_103]
[f 0 5 65278][f 2 1]Si los atacas y son resistentes a la afinidad[n]del ataque, 斡realizar茨n un contraataque poderoso contra ti![n]Pero si puedes encontrar una debilidad y aprovecharla,[n]tendr茨s muchas m茨s posibilidades de 姻xito.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_104]
[f 0 5 65278][f 2 1]En comparaci吋n con una Conversi吋n de Equipo ordinaria, la Conversi吋n R茨pida hace que sea m茨s f茨cil derribar a las Sombras.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP_]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP__2]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP__3]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_BTL]
[f 0 5 65278][f 2 1]Reserva[n][f 1 1][e]

