[msg MSG_BTL_TUTORIAL_844_ENC]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_101]
[f 0 5 65278][f 2 1]"Quick Convert" Cuando el Medidor de[n]Grupo se llene hasta cierto punto,[n]podr茨s usar [f 0 1 2]Quick Convert[f 0 1 0] presionando[n]el bot吋n Y durante la acci吋n de un[n]enemigo o un aliado.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_102]
[f 0 5 65278][f 2 1]Usar Quick Convert cambiar茨 autom茨ticamente[n]tu equipo al final del turno.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_103]
[f 0 5 65278][f 2 1]Por cierto, todos los miembros del equipo[n]que entren en batalla mediante[n]una Quick Convert se sentir茨n en plena[n]forma y ansiosos por luchar.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_104]
[f 0 5 65278][f 2 1]En diferencia de Team Convert, Quick[n]Convert facilita derribar a las Sombras.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP_]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP__2]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_HP__3]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_844_BTL]
[f 0 5 65278][f 2 1]Reserva[n][f 1 1][e]

