[msg MSG_0000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 1][f 3 1 3 0 0 141][f 6 1 2 0 0 0]斡Whoa! 斡夷Qu姻 demonios?![n][f 1 3 65535][f 1 1][e]

[msg MSG_0001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 3 0 0 142][f 6 1 2 0 0 10]斡N-no puede ser![n][f 1 3 65535][f 1 1][e]

[msg MSG_0002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 4][f 1 5][f 6 1 27 0 0 0][n][f 3 1 3 0 0 143]夷斡C吋mo le crecieron las orejas as胤!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_0003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 26 10 100 1][f 3 1 3 0 0 144][f 6 1 2 0 0 0]斡Mierda! 斡Se transform吋![n][f 1 3 65535][f 1 1][e]

[msg MSG_0004 [夷Kamoshidaman?]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 145][f 6 1 2 0 0 6][f 6 1 3 0 0 2]斡JA, JA, JA! 斡Te mostrar姻 mi verdadero[n]poder![n][f 1 3 65535][f 1 1][e]

[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 8][f 3 1 3 0 0 131][f 6 1 2 0 0 0]Ugh, 斡夷QU畏 es eso?! Es tan espeluznante...[n]斡No! 斡Nuh-uh! 斡De ninguna manera![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 7][f 3 1 3 0 0 132]Es bastante desagradable... pero, 夷por[n]qu姻 un conejo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 1 8][f 3 1 3 0 0 133][f 6 1 2 0 0 6]Nos preocuparemos por eso despu姻s. 斡Aqu胤[n]viene![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [夷Kamoshidaman?]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 134][f 6 1 2 0 0 6][f 6 1 3 0 0 2]Grr... 斡Malhechores corruptos! 斡Entreguen[n]sus armas y som姻tanse![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [夷Kamoshidaman?]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 135][f 6 1 2 0 0 6][f 6 1 3 0 0 2]斡Grr...! La justicia... 斡La justicia[n]siempre gana![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [夷Kamoshidaman?]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 136][f 6 1 2 0 0 0][f 6 1 3 0 0 2]斡Imposible...! 斡夷C吋mo es posible que[n]yo, la justicia encarnada, sea[n]derrotado?![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [夷Kamoshidaman?]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 138][f 6 1 3 0 0 2]斡夷Por qu姻?! 夷C吋mo puede...? Mi[n]justicia...[n][f 1 3 65535][f 1 1][e]

