[msg MSG_BTL_TUTORIAL_845_ENC]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_101]
[f 0 5 65278][f 2 1]"Sombras Raras" A veces, en los calabozos aparecer茨n enemigos especiales conocidos como [f 0 1 2]Sombras Raras[f 0 1 0].[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_102]
[f 0 5 65278][f 2 1]Las Sombras Raras pueden parecerse a las Sombras normales, 斡pero hay una diferencia![n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_103]
[f 0 5 65278][f 2 1]Si las atacas y son resistentes a una afinidad, 斡realizar茨n un contraataque poderoso contra ti! Pero si puedes encontrar una debilidad y aprovecharla, tendrás muchas más posibilidades de derrotarla.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_104]
[f 0 5 65278][f 2 1]A diferencia de Team Convert, Quick Convert hace que sea m茨s fácil derribar a las Sombras.[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP_]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP__2]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_HP__3]
[f 0 5 65278][f 2 1]Reservado[n][f 1 1][e]

[msg MSG_BTL_TUTORIAL_845_BTL]
[f 0 5 65278][f 2 1]Reserva[n][f 1 1][e]

