[msg MSG_000 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 501][f 6 1 3 0 0 2]Mi presencia es necesaria para aquellos[n]que quieren escapar de su realidad.[n]Desafiarme es tan tonto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 502][f 6 1 3 0 0 2]Son solo unos ni隠os insignificantes y[n]lamentables para m胤. R胤ndanse ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 99 1][f 3 1 3 0 0 503][f 6 1 2 0 0 6]斡Aguanten! 斡Tenemos que seguir reproduciendo[n]la pel胤cula![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 99 0][f 3 1 3 0 0 504]Necesitamos que su forma de pensar[n]cambie. 斡Por favor![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 4][f 3 1 3 0 0 505][f 6 1 2 0 0 1]斡Vamos, tienes que aguantar! 斡Nosotras[n]tambi姻n haremos nuestro mejor[n]esfuerzo![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Enlil]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 506][f 6 1 3 0 0 2]Han venido innumerables humanos, ansiosos[n]de encontrar seguridad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 507][f 6 1 3 0 0 2]Tu resistencia a mi salvaci吋n no es m茨s[n]que una perdida de tiempo.[n][f 1 3 65535][f 1 1][e]

