[msg MSG_000 [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 711][f 6 1 3 0 0 2]Aqu胤 y ahora, te veo como un oponente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 712][f 6 1 2 0 0 4][f 6 1 3 0 0 2]Me pregunto cu茨nto puedo esperar de ti..?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 713][f 6 1 3 0 0 2]夷Eso es todo...? No, no lo pens姻.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 714][f 6 1 3 0 0 2]S吋lo tu expresi吋n hace que eso sea claro.[n]Vamos a continuar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 715][f 6 1 2 0 0 4][f 6 1 3 0 0 2]夷Qu姻 te parece? 夷Puedes seguir luchando?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 716][f 6 1 2 0 0 6][f 6 1 3 0 0 2]Entonces otra vez... Ya sea que puedas o no,[n]斡no puedo retenerme![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 717][f 6 1 3 0 0 2]Exhilarante... No pares ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 718][f 6 1 3 0 0 2]Perm胤tanme presenciar todo lo que sus batallas[n]le han hecho... hasta el final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 3 0 0 719][f 6 1 3 0 0 2]Hmhm... Realmente maravilloso.[n][f 1 3 65535][f 1 1][e]

