[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 1 1][f 3 1 1 0 0 21037][f 6 1 2 0 0 6]斡Tch, est茨n aqu胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 0]Es como pens姻. Parecen diferentes de los que[n]encontramos en los Palacios.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Sin embargo, siguen siendo nuestro enemigo.[n]斡Si se interponen en nuestro camino,[n]deben ser derrotados![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 0 99 0][f 3 1 1 0 0 26567]Inari tiene razón.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No parecen demasiado fuertes, as胤 que vamos[n]a cargar como siempre![n][f 1 3 65535][f 1 1][e]

