[msg BTL_MES_003_000]
Dummy

[msg BTL_MES_003_001]
斡Je! Lo siento, pero voy a darlo todo. 斡Te derrotaremos!

[msg BTL_MES_003_002]
＜声Of＞kDGktうぜ！ ぜDGー負けNえ！

[msg BTL_MES_003_003]
斡夷Qu姻?! 斡Un FOE! 斡Ah, vamos...!

[msg BTL_MES_003_004]
＜声Of＞了解DI！ 退散退散！

[msg BTL_MES_003_005]
夷A qui姻n le importa si es un FOE? 斡No vamos a retroceder!

[msg BTL_MES_003_006]
斡Eh, una rara! 斡Qu姻 suerte!

[msg BTL_MES_003_007]
＜声Of＞eかせIけDG！ ぜDGー逃がさNーぞ！

[msg BTL_MES_003_008]
＜声Of＞さzきlーK、)ビ！

[msg BTL_MES_003_009]
＜声Of＞qnーかい！ qせ、さzきlーK！

[msg BTL_MES_003_010]
＜声Of＞KrbJK！ hDBj助かrぜ、山岸さz！

[msg BTL_MES_003_011]
斡Esta es fuerte! 斡夷C吋mo salimos de esta?!

[msg BTL_MES_003_012]
＜声Of＞えDI…ここP次O機会L！ EーこILしNぇ？

[msg BTL_MES_003_013]
No la hemos visto antes. 斡Busquemos sus debilidades!

[msg BTL_MES_003_014]
＜声Of＞うDし、いtいtkDGfoうぜ！

[msg BTL_MES_003_015]
斡Oye! 斡Podr胤amos ganar esta!

[msg BTL_MES_003_016]
＜声Of＞oDし！ 俺LeかせKさい！

[msg BTL_MES_003_017]
斡Muy f茨cil! 斡Podemos con esto!

[msg BTL_MES_003_018]
＜声Of＞お？krか？ kDBeうOか？

[msg BTL_MES_003_019]
斡Ah! 夷La Sombra cambi吋?

[msg BTL_MES_003_020]
＜声Of＞おいおい！ ヤベーDG！

[msg BTL_MES_003_021]
＜声Of＞くそ…！ 呼zHNーDEO！

[msg BTL_MES_003_022]
斡夷Qu姻 hacemos?!

[msg BTL_MES_003_023]
＜声Of＞BnD、マジ！？ 立G直さNーIkZーAt。

[msg BTL_MES_003_024]
＜声Of＞大丈夫かo、相棒！？ KzIかしNーIK…

[msg BTL_MES_003_025]
＜声Of＞うおD、大丈夫かo！？ 治さNぇIkZーK

[msg BTL_MES_003_026]
＜声Of＞4ミー

[msg BTL_MES_003_027]
＜声Of＞里中、平気かo！？ すぐLKzIかしNーI！

[msg BTL_MES_003_028]
＜声Of＞天城O事、KzIかしNーIK…

[msg BTL_MES_003_029]
＜声Of＞4ミー

[msg BTL_MES_003_030]
＜声Of＞完二、しDかqしt！ くそ、フ隠ローしNーIK…

[msg BTL_MES_003_031]
＜声Of＞マジかo、直斗… KzIかしNーIK…

[msg BTL_MES_003_032]
＜声Of＞クマ、しDかqしtDG！ くそ、フ隠ローしNーIK…

[msg BTL_MES_003_033]
＜声Of＞岳羽さz、大丈夫か？ 助けNーI…！

[msg BTL_MES_003_034]
＜声Of＞伊織、大丈夫かo！？ 早くKzIかしNーI

[msg BTL_MES_003_035]
＜声Of＞真田さz、大丈夫かo！？ kZえ、手うたNーI

[msg BTL_MES_003_036]
＜声Of＞桐条さz、ヤバくNーか！？ 何IかしNぇI！

[msg BTL_MES_003_037]
＜声Of＞4ミー

[msg BTL_MES_003_038]
＜声Of＞威姻Bjz、大変KこILKDGzぞ！？ 何IかしNーIkZぇ

[msg BTL_MES_003_039]
＜声Of＞天田がヤベ緯！ 放DGおけNーぞ！？

[msg BTL_MES_003_040]
＜声Of＞コロマル、KzIかしNーIK… こOeeじjマズ姻DG

[msg BTL_MES_003_041]
＜声Of＞荒垣さz、大丈夫… じjKいDすoN

[msg BTL_MES_003_042]
＜声Of＞おいおい、マジか？ bDIくIヤベーzじjNーO？

[msg BTL_MES_003_043]
＜声Of＞ジョー吋ー、しDかqしtDG！ 何IかしNーI…

[msg BTL_MES_003_044]
＜声Of＞ス吋ル、しDかqしt！ くそ、フ隠ローしNーIK…

[msg BTL_MES_003_045]
＜声Of＞パンサーがkZぇ！ フ隠ローしNーI！

[msg BTL_MES_003_046]
＜声Of＞モ)がピン5LKDGzぞ！ JうLかしNーI！

[msg BTL_MES_003_047]
＜声Of＞フ隠7クス、しDかqしtDG！ すぐフ隠ローしNぇI！

[msg BTL_MES_003_048]
＜声Of＞ク姻ーン、大丈夫かo… こOeeじjマズ姻DG！

[msg BTL_MES_003_049]
＜声Of＞4ミー

[msg BTL_MES_003_050]
＜声Of＞ノワール、マジかo！ 大丈夫…じjNぇoK！？

[msg BTL_MES_003_051]
＜声Of＞しDかqしtDG、クロ胤！ すぐLフ隠ローしNぇI…！

[msg BTL_MES_003_052]
＜声Of＞おDし、狙い撃BしGkrぜ！

[msg BTL_MES_003_053]
斡Estamos en racha!

[msg BTL_MES_003_054]
＜声Of＞謂7ケー！ kDGktうぜD！

[msg BTL_MES_003_055]
Si quieres atacar su debilidad, 斡c茨mbiame!

[msg BTL_MES_003_056]
斡Bien! 夷Hora de un Relevo?

[msg BTL_MES_003_057]
斡Oh! 斡Parece que es mi momento de brillar!

[msg BTL_MES_003_058]
＜声Of＞さDすが、相棒！ 頼zAぜ！

[msg BTL_MES_003_059]
＜声Of＞ああ、任せrぜ。 kDBeDGくs！

[msg BTL_MES_003_060]
＜声Of＞4ミー

[msg BTL_MES_003_061]
＜声Of＞うおD、里中Okr気がス郁ーK

[msg BTL_MES_003_062]
＜声Of＞えDI…天城？ 俺たBeH燃kすKo…？

[msg BTL_MES_003_063]
＜声Of＞4ミー

[msg BTL_MES_003_064]
＜声Of＞完二！ WBかeしGkso！

[msg BTL_MES_003_065]
＜声Of＞oDしj！ kDBeえ、直斗！

[msg BTL_MES_003_066]
＜声Of＞いいぞ、クマ！ いDけええええ！

[msg BTL_MES_003_067]
＜声Of＞おおD。岳羽さz、燃えGrK！

[msg BTL_MES_003_068]
＜声Of＞おDしjー！ 伊織、頼zAぜ！

[msg BTL_MES_003_069]
＜声Of＞真田さzO気迫、kZぇ…！

[msg BTL_MES_003_070]
＜声Of＞桐条さz、超クールAぜ！

[msg BTL_MES_003_071]
＜声Of＞4ミー

[msg BTL_MES_003_072]
＜声Of＞威姻Bjz！ WBかeしGks！

[msg BTL_MES_003_073]
＜声Of＞おDし、天田！ 頑張so！

[msg BTL_MES_003_074]
＜声Of＞コロマル！ お前L任せた！

[msg BTL_MES_003_075]
＜声Of＞荒垣さz、 kr気充分じjKいDすか！

[msg BTL_MES_003_076]
＜声Of＞おう、期待しGDかpK！

[msg BTL_MES_003_077]
＜声Of＞決hGくsoK、ジョー吋ー！

[msg BTL_MES_003_078]
＜声Of＞ス吋ル、WBかeしGkso！

[msg BTL_MES_003_079]
＜声Of＞パンサー、 kDBeDGくs！

[msg BTL_MES_003_080]
＜声Of＞モ)ー！ 頼zAぞー！

[msg BTL_MES_003_081]
＜声Of＞おうo。任せrぜフ隠7クス！

[msg BTL_MES_003_082]
＜声Of＞ク姻ーンOkr気、ス郁ーぜ…！

[msg BTL_MES_003_083]
＜声Of＞4ミー

[msg BTL_MES_003_084]
＜声Of＞kDBeえ、ノワール！

[msg BTL_MES_003_085]
＜声Of＞クロ胤！ 蹴散pしGkso！

[msg BTL_MES_003_086]
斡Muy bien! 斡Listo para rockear!

