[msg BTL_MES_004_000]
Dummy

[msg BTL_MES_004_001]
No perder〒, ムporque no podemos perder ahora!

[msg BTL_MES_004_002]
＜声Of＞oぉーし！ kDGkrかzN！

[msg BTL_MES_004_003]
ムAh! ムUn FOE! ムYo digo que escapemos!

[msg BTL_MES_004_004]
＜声Of＞Sえ…！ ささDI撤退しo！

[msg BTL_MES_004_005]
ムGANAREMOS! ムD〒mosles una paliza!

[msg BTL_MES_004_006]
ムCarne rara! Quiero decir... ムSombra rara!

[msg BTL_MES_004_007]
＜声Of＞待G待G待Gー！ 逃がさーz！

[msg BTL_MES_004_008]
＜声Of＞)ビ、あzがIN！ 了解したぞo！

[msg BTL_MES_004_009]
＜声Of＞さzきlー、qせBjz！ 了解したぞo！

[msg BTL_MES_004_010]
＜声Of＞あqがI、風花Bjz！ 了解したぞo！

[msg BTL_MES_004_011]
ムEeep! ムEste va a ser difボcil!

[msg BTL_MES_004_012]
＜声Of＞Jーz、IWD飛QしBjう？ DG、調子LOrIヤバいかi…

[msg BTL_MES_004_013]
ムOh! Nunca habボamos visto esa antes. メDeberボamos buscar su debilidad?

[msg BTL_MES_004_014]
＜声Of＞おDけー！ kDGkt！

[msg BTL_MES_004_015]
ムLo tenemos! ムSボ!

[msg BTL_MES_004_016]
＜声Of＞qnーかい！ いDくぞー！

[msg BTL_MES_004_017]
Esto no serホ problema. Apuesto a que ni siquiera sudaremos.

[msg BTL_MES_004_018]
＜声Of＞ミ5ョー！ミ5ャ5ャ5ャ5ャ！

[msg BTL_MES_004_019]
ムメQu〒...?! メLa Sombra cambiポ...?

[msg BTL_MES_004_020]
＜声Of＞えええええ！？ マジDすか！？

[msg BTL_MES_004_021]
＜声Of＞BnD、こpーD！ KL来GzADEO！

[msg BTL_MES_004_022]
Oh... ムEsto no es bueno!

[msg BTL_MES_004_023]
＜声Of＞こs…かKqヤバ〒気がすr…

[msg BTL_MES_004_024]
＜声Of＞BnDIBnDI！ KzIかしKいI！

[msg BTL_MES_004_025]
＜声Of＞こs、回復しKいIヤバくKい？

[msg BTL_MES_004_026]
＜声Of＞ヤ7バ！ BnDI花村、しDかq！

[msg BTL_MES_004_027]
＜声Of＞4ミー

[msg BTL_MES_004_028]
＜声Of＞雪子が危Kい！ 回復しKいI！

[msg BTL_MES_004_029]
＜声Of＞4ミー

[msg BTL_MES_004_030]
＜声Of＞うv、マジ！？ 完二くz、しDかq！

[msg BTL_MES_004_031]
＜声Of＞直斗くzが危Kい…！ 回復しKいI！

[msg BTL_MES_004_032]
＜声Of＞BnDIBnDI！ クマくz、しDかq！

[msg BTL_MES_004_033]
＜声Of＞mかqBjzが危Kいo！ 回復しKきj！

[msg BTL_MES_004_034]
＜声Of＞Bn、ヤバD！ 伊織くz、しDかq！

[msg BTL_MES_004_035]
＜声Of＞真田さzがピン5！ 回復しKいI！

[msg BTL_MES_004_036]
＜声Of＞美鶴さzがkQい！ 回復しKいI！

[msg BTL_MES_004_037]
＜声Of＞4ミー

[msg BTL_MES_004_038]
＜声Of＞ミ〒/スがピン5Ddい！ フワローしKきj！

[msg BTL_MES_004_039]
＜声Of＞Jうしoう、乾くzが！ 回復しKきjAo！

[msg BTL_MES_004_040]
＜声Of＞Bn、kQD！ コロBjz、しDかqしtー！

[msg BTL_MES_004_041]
＜声Of＞大丈夫Hすか、荒垣さz！？ KzIかしKくBj！

[msg BTL_MES_004_042]
＜声Of＞うvD、たいYz！ KzIか治療しGあげKいI…

[msg BTL_MES_004_043]
＜声Of＞ジョーポーがピン5Ao！ 回復しKくBj！

[msg BTL_MES_004_044]
＜声Of＞うv、kQD！ スポル、しDかq！

[msg BTL_MES_004_045]
＜声Of＞パンサー、しDかq！ 早くKzIかしKいI…！

[msg BTL_MES_004_046]
＜声Of＞おvD、モ)が…！ KおしGあげKいI！

[msg BTL_MES_004_047]
＜声Of＞ヤ7バ！ フワ7クス、しDかq！

[msg BTL_MES_004_048]
＜声Of＞ああD、ク〒ーンが！ 回復が必要そうAo！

[msg BTL_MES_004_049]
＜声Of＞4ミー

[msg BTL_MES_004_050]
＜声Of＞kQD、ノワールが！ KzIかしKいI！

[msg BTL_MES_004_051]
＜声Of＞うDそ！ クロボ、しDかqしGー！

[msg BTL_MES_004_052]
＜声Of＞ぜーzW、eIhG WDIQしBjうかpN！

[msg BTL_MES_004_053]
ムHwataaa! ムLos patear〒 a todos en la cara!

[msg BTL_MES_004_054]
＜声Of＞VDVDV！ (ン(ンこいDGO！

[msg BTL_MES_004_055]
ムUsemos su debilidad en su contra, chicos!

[msg BTL_MES_004_056]
ムメDeberボamos usar relevo?!

[msg BTL_MES_004_057]
ムOh, yo, yo! ムChie Satonaka, lista!

[msg BTL_MES_004_058]
＜声Of＞そO漢気、見せGfo！

[msg BTL_MES_004_059]
＜声Of＞お願い、一気LkDBjDG！

[msg BTL_MES_004_060]
＜声Of＞花村、eかせたかzN！

[msg BTL_MES_004_061]
＜声Of＞4ミー

[msg BTL_MES_004_062]
＜声Of＞おお、雪子張q切DGrKー

[msg BTL_MES_004_063]
＜声Of＞4ミー

[msg BTL_MES_004_064]
＜声Of＞完二くz、頼qLKrN！

[msg BTL_MES_004_065]
＜声Of＞直斗くz、kDBjえkDBjえ！

[msg BTL_MES_004_066]
＜声Of＞おおー！クマくzOkr気、すごすぎr！

[msg BTL_MES_004_067]
＜声Of＞mかqBjz、すご…！

[msg BTL_MES_004_068]
＜声Of＞伊織くzDGQ絶好調じjz！

[msg BTL_MES_004_069]
＜声Of＞真田さzが、メラメラI燃えGいr…！

[msg BTL_MES_004_070]
＜声Of＞bあー… 美鶴さz、すごい迫力…！

[msg BTL_MES_004_071]
＜声Of＞4ミー

[msg BTL_MES_004_072]
＜声Of＞ミ〒/ス いDけえええ！

[msg BTL_MES_004_073]
＜声Of＞乾くzL任せrD！

[msg BTL_MES_004_074]
＜声Of＞コロすけ、頼gN！

[msg BTL_MES_004_075]
＜声Of＞荒垣さz、頼iしすぎeすD！

[msg BTL_MES_004_076]
＜声Of＞おおD、kr気fたいAN！ いけいけゴー！

[msg BTL_MES_004_077]
＜声Of＞頼zAo、ジョーポー！

[msg BTL_MES_004_078]
＜声Of＞いいN！ スポル、いDBjえー！

[msg BTL_MES_004_079]
＜声Of＞パンサー、任せたD！

[msg BTL_MES_004_080]
＜声Of＞モー)ー！ WD飛Qせー！

[msg BTL_MES_004_081]
＜声Of＞頼iしいぞー！フワ7クスー！

[msg BTL_MES_004_082]
＜声Of＞ク〒ーン！お願いND！

[msg BTL_MES_004_083]
＜声Of＞4ミー

[msg BTL_MES_004_084]
＜声Of＞ノワール！ (ーンIいDBjえ！

[msg BTL_MES_004_085]
＜声Of＞いいぞー！ クロボ、kDBjえー！

[msg BTL_MES_004_086]
ムHwa-cha! ムNo soy la misma Chie de antes! ムMボrame ahora!

