[msg BTL_MES_006_000]
Dummy

[msg BTL_MES_006_001]
Esa parece dura... 斡Cuidado, chicos!

[msg BTL_MES_006_002]
斡Mant姻nganse alerta!

[msg BTL_MES_006_003]
Oh no, 斡夷un FOE...?! 斡Debemos[n]retroceder!

[msg BTL_MES_006_004]
斡Hay un FOE! 斡No luches contra 姻l!

[msg BTL_MES_006_005]
S胤, esto es muuuy arriesgado.[n]斡V茨monos de aqu胤!

[msg BTL_MES_006_006]
斡Retirada! 斡Y vigila que no te[n]persiga!

[msg BTL_MES_006_007]
ねまぼまれもろぺゆよれ ゎょ らゅぺょ らぺるぺ ぺろるぺわまれぺる れゎ[n]ぽまみまょれぺテ ィぱまぼよょよんぼよ ゎょぺ らもまゅ むるゎまれぺ ぼゎぺょぽよ[n]ゅぺ わまよ!

[msg BTL_MES_006_008]
斡Ese tiene ataques muy poderosos! 斡No[n]te arriesgues!

[msg BTL_MES_006_009]
斡Cuidado, ese FOE tiene ataques[n]f胤sicos s雨per fuertes!

[msg BTL_MES_006_010]
斡Cuidado, los ataques m茨gicos de ese[n]FOE no son una broma!

[msg BTL_MES_006_011]
ひま らよょま ゆァれ みゎまるろま ぺ ゆまぽもぽぺ りゎま れゎ れぺゅゎぽ[n]ほぺゃぺテ ぴょぺ わまん りゎま まゆらもまぼまれデ ィぽまほまれ ゆぺろぺるゅよ[n]ゅよ ぺょろまれ らよれもほゅま!

[msg BTL_MES_006_012]
斡Una sombra rara! 斡No dejes que[n]escape!

[msg BTL_MES_006_013]
斡Hay una Sombra rara! 斡Derr胤bala[n]r茨pido!

[msg BTL_MES_006_014]
斡S胤! 斡No dejen que se escape,[n]夷entendido?!

[msg BTL_MES_006_015]
斡No perdamos a esa rara!

[msg BTL_MES_006_016]
つれま らゎまぽま むよゅらまぺる ぺ ろよぽよ まゅ むるゎらよ ぺ ゅぺ わまんテ[n]びるぺろぺ ぽま ぽまみまょぽまるろま れも ゅよ わまれ わまょもるテ

[msg BTL_MES_006_017]
ぴょ まょまゆもむよ りゎま ゎれぺ ぺろぺりゎまれ まょ ろよぽぺ ゅぺ[n]んよょぺテテテ ィぴれぺ ろゎれ めぺほもゅもぽぺぽまれ ぽまみまょれもわぺれ!

[msg BTL_MES_006_018]
ぴょ まょまゆもむよ りゎま らゎまぽま ゎれぺる ゆゎまるろま[n]もょれろぺょろァょまぺテ ィへよ ぽもむよ りゎま ゅよ まゅもゆもょまれ[n]らるもゆまるよ!

[msg BTL_MES_006_019]
Los ataques m茨gicos no funcionar茨n.[n]斡Usa otra cosa!

[msg BTL_MES_006_020]
斡Cuidado! 斡El pr吋ximo ataque es muy[n]poderoso!

[msg BTL_MES_006_021]
Sip, ese es intimidante... 斡Cuidado!

[msg BTL_MES_006_022]
Oh-oh... Parece que nos tomaron por[n]sorpresa...

[msg BTL_MES_006_023]
斡Podr胤amos ganar si lo damos todo![n]夷Qu姻 hacemos...?

[msg BTL_MES_006_024]
ィねよ れまぺれ もゆらるゎぽまょろま! ィひも れま わま ぽまゆぺれもぺぽよ[n]ぽゎるよデ ろゎ ゆまゃよる よらぼもカょ まれ ぼよるるまる!

[msg BTL_MES_006_025]
斡No tenemos datos sobre esa Sombra![n]Deber胤amos encontrar sus debilidades.

[msg BTL_MES_006_026]
斡Un nuevo tipo enemigo, no conocemos[n]sus debilidades!

[msg BTL_MES_006_027]
斡Ve por ellos, Senpai!

[msg BTL_MES_006_028]
斡Puedes hacerlo! 斡S姻 que puedes!

[msg BTL_MES_006_029]
斡Ten cuidado, Yosuke!

[msg BTL_MES_006_030]
斡Vamos, Chie!

[msg BTL_MES_006_031]
斡No te detengas, Yukiko!

[msg BTL_MES_006_032]
Dummy

[msg BTL_MES_006_033]
斡Dales una paliza, Kanji!

[msg BTL_MES_006_034]
斡Lo tienes, Naoto!

[msg BTL_MES_006_035]
斡Vamos Teddie!

[msg BTL_MES_006_036]
斡Puedes hacerlo, Yukari!

[msg BTL_MES_006_037]
斡Junpei, mantengamos la calma y[n]encontremos sus debilidades!

[msg BTL_MES_006_038]
夷A-akihiko? Vamos c茨lmate, 夷de[n]acuerdo?

[msg BTL_MES_006_039]
Mitsuru se ve tan genial...

[msg BTL_MES_006_040]
Dummy

[msg BTL_MES_006_041]
斡Hazlo, Aigis!

[msg BTL_MES_006_042]
斡C茨lmate, Ken! 斡Te estamos animando!

[msg BTL_MES_006_043]
斡Ve por ellos, Koro!

[msg BTL_MES_006_044]
斡Contamos contigo, Shinjiro!

[msg BTL_MES_006_045]
斡Adelante! 斡Tenemos cubriremos la[n]espalda!

[msg BTL_MES_006_046]
斡Eso es, Joker!

[msg BTL_MES_006_047]
斡Buena suerte, Skull!

[msg BTL_MES_006_048]
斡Sigue, Panther!

[msg BTL_MES_006_049]
斡Buena idea, Mona!

[msg BTL_MES_006_050]
斡Vamos, Fox!

[msg BTL_MES_006_051]
斡Vamos, Queen! 斡Te apoyar姻!

[msg BTL_MES_006_052]
Dummy

[msg BTL_MES_006_053]
斡Suena bien, Noir! 斡Adelante!

[msg BTL_MES_006_054]
斡Puedes hacerlo, Crow!

[msg BTL_MES_006_055]
斡Nada que no puedas manejar, solo[n]mant姻n el enfoque!

[msg BTL_MES_006_056]
斡No bajes la guardia!

[msg BTL_MES_006_057]
Esto parece bastante f茨cil, pero no[n]te conf胤es.

[msg BTL_MES_006_058]
No hay problema. 斡Hag茨moslo r茨pido!

[msg BTL_MES_006_059]
斡Acabemos con esto, chicos!

[msg BTL_MES_006_060]
斡Derr吋talos a todos!

[msg BTL_MES_006_061]
No lo olvides, 斡puedes golpear la[n]debilidad del enemigo!

[msg BTL_MES_006_062]
斡Es tu oportunidad! 斡Ve por su punto[n]d姻bil!

[msg BTL_MES_006_063]
Oh no, 夷qu姻 hacemos...? 斡No podemos[n]escapar!

[msg BTL_MES_006_064]
斡El intento de escape fall吋![n]斡Cuidado!

[msg BTL_MES_006_065]
N-no puede ser... 斡Apareci吋 un FOE!

[msg BTL_MES_006_066]
はまょれイ りゎま ろよぽよれ れぺほウぺょ りゎま まれ ぽま ゆぺゅぺ[n]まぽゎぼぺぼもカょ もょわぺぽもる まゅ まれらぺぼもよ らまるれよょぺゅテ[n]ィはぺるまぼま りゎま ねの!

[msg BTL_MES_006_067]
斡Ah! 斡Senpai, est茨s grave! 斡夷Estaras[n]bien?!

[msg BTL_MES_006_068]
斡Cuidado, alguien est茨 en estado[n]cr胤tico!

[msg BTL_MES_006_069]
斡Yosuke est茨 en peligro! 斡Cuidado!

[msg BTL_MES_006_070]
斡Chie est茨 en problemas!

[msg BTL_MES_006_071]
斡Yukiko necesita ayuda!

[msg BTL_MES_006_072]
Dummy

[msg BTL_MES_006_073]
斡Kanji est茨 en aprietos! 斡Cuidalo!

[msg BTL_MES_006_074]
斡Naoto est茨 en peligro!

[msg BTL_MES_006_075]
斡Teddie est茨 en apuros!

[msg BTL_MES_006_076]
斡Yukari no se encuentra muy bien!

[msg BTL_MES_006_077]
斡No se ve bien para Junpei!

[msg BTL_MES_006_078]
斡Akihiko est茨 en mal estado!

[msg BTL_MES_006_079]
斡Mitsuru no se ve tan genial!

[msg BTL_MES_006_080]
Dummy

[msg BTL_MES_006_081]
斡Aigis est茨 en peligro!

[msg BTL_MES_006_082]
斡Ken est茨 en problemas!

[msg BTL_MES_006_083]
斡Pobre Koro est茨 herido!

[msg BTL_MES_006_084]
斡Shinjiro est茨 en una mala situaci吋n[n]en este momento!

[msg BTL_MES_006_085]
斡Cuidado! 斡No falta mucho para que te[n]derriben!

[msg BTL_MES_006_086]
斡Joker podr胤a necesitar algo de[n]ayuda!

[msg BTL_MES_006_087]
斡Cuidado, Skull! 斡Est茨s en mal[n]estado!

[msg BTL_MES_006_088]
斡Panther realmente necesita ayuda, la[n]que sea!

[msg BTL_MES_006_089]
斡Mona est茨 en problemas!

[msg BTL_MES_006_090]
斡Cuidado! 斡Fox est茨 en aprietos!

[msg BTL_MES_006_091]
斡Queen parece que est茨 en un aprieto[n]real!

[msg BTL_MES_006_092]
Dummy

[msg BTL_MES_006_093]
斡La situaci吋n de Noir se ve terrible!

[msg BTL_MES_006_094]
斡Cuidado! 斡Crow est茨 por quedar[n]inconsciente!

[msg BTL_MES_006_095]
Esto no se ve bien... 夷Tal vez[n]deber胤amos regresar?

[msg BTL_MES_006_096]
斡夷Est茨s bien?! 斡R茨pido, tienes que[n]sanar!

[msg BTL_MES_006_097]
斡Oh no! 斡Alguien ha sido petrificado!

[msg BTL_MES_006_098]
斡Cuidado! 斡Cuando atacas, tambi姻n te[n]haces da隠o a ti mismo!

[msg BTL_MES_006_099]
斡Tienes que quitarte ese veneno,[n]r茨pido!

[msg BTL_MES_006_100]
斡Alguien est茨 dormido! 斡Despierta!

[msg BTL_MES_006_101]
斡Alguien est茨 confundido! 夷C吋mo[n]logramos que vengan a sus sentidos?

[msg BTL_MES_006_102]
斡夷Qu-?! 斡Alguien ha sido paralizado!

[msg BTL_MES_006_103]
夷Est茨s bien? 斡Aguanta!

[msg BTL_MES_006_104]
斡Oh no! 斡Tu Persona ha sido atada!

[msg BTL_MES_006_105]
斡No puedes usar ataques f胤sicos!

[msg BTL_MES_006_106]
斡Tu movimiento se ha ralentizado![n]斡Cuidado con los ataques que vienen!

[msg BTL_MES_006_107]
斡Es d姻bil contra los ataques f胤sicos![n]斡Derr吋talo a golpes!

[msg BTL_MES_006_108]
Es d姻bil contra el Fuego. 斡Quemenlo!

[msg BTL_MES_006_109]
Es d姻bil contra el hielo. 斡Congela a[n]esa Sombra!

[msg BTL_MES_006_110]
斡Usa ataques de viento! 斡Sorpr姻ndelo!

[msg BTL_MES_006_111]
Su debilidad es la Electricidad. 斡Haz[n]algo que lo deje impactado!

[msg BTL_MES_006_112]
ィつれ ぽイほもゅ ぼよょろるぺ ゅよれ ぺろぺりゎまれ ょゎぼゅまぺるまれ![n]ィふぺゆよれ ぺ ぽまゆよれろるぺる りゎま れよゆよれ ゅぺ ほよゆほぺ!

[msg BTL_MES_006_113]
Es d姻bil contra la Psicokinesis.[n]斡Pensemos en eso!

[msg BTL_MES_006_114]
つれ ぽイほもゅ ぼよょろるぺ ゅぺれ めぺほもゅもぽぺぽまれ ぽま[n]ちまょぽもぼもカょテ ィでぺむぺゆよれ りゎま るゎまむゎま らよる れゎ[n]みもょぺゅ!

[msg BTL_MES_006_115]
斡Es d姻bil contra las habilidades de[n]Maldici吋n!

[msg BTL_MES_006_116]
斡Usa ataques f胤sicos contra ese!

[msg BTL_MES_006_117]
斡El fuego es efectivo! 斡Quemenlos a[n]todos!

[msg BTL_MES_006_118]
斡Odia el fr胤o! 夷Qui姻n no? 斡Intenta[n]atacar con hielo!

[msg BTL_MES_006_119]
斡Es d姻bil contra el viento! 夷Puedes[n]golpearlo?

[msg BTL_MES_006_120]
斡La electricidad es efectiva![n]斡Explota esa debilidad!

[msg BTL_MES_006_121]
Usar ataques nucleares es nuestra[n]mejor opci吋n. 斡Esa es su debilidad!

[msg BTL_MES_006_122]
にぺ はれもぼよやもょまれもれ まれ まみまぼろもわぺテ ィっまるるカろぺゅよ[n]ぺょろまれ ぽま りゎま れま わゎまゅわぺ られもぼカらぺろぺ ぼよょ[n]ねのひのびぱのひ!

[msg BTL_MES_006_123]
ィねよろもぼもぺれ ぼまゅまれろもぺゅまれ! ィだろぺりゎまれ ぽま[n]ちまょぽもぼもカょ れよょ ほぺれろぺょろま まみもぼぺぼまれ ぼよょろるぺ まれま!

[msg BTL_MES_006_124]
斡Los ataques de maldici吋n son buenos[n]contra ese!

[msg BTL_MES_006_125]
斡Lo est茨s haciendo genial!

[msg BTL_MES_006_126]
斡Vamos, vamos, vamos! 斡Derr胤benlos a[n]todos!

[msg BTL_MES_006_127]
斡S胤! 斡Pueden hacerlo, chicos!

[msg BTL_MES_006_128]
Solo lo dir姻... 斡Ustedes son[n]eh-CRE胤bles!

[msg BTL_MES_006_129]
斡Ahora puedes usar Relevo!

[msg BTL_MES_006_130]
斡Podr胤as hacer un gran da隠o con un[n]Relevo!

[msg BTL_MES_006_131]
斡Estoy lista para apoyar en cualquier[n]momento!

[msg BTL_MES_006_132]
斡Av胤same si hay algo que pueda hacer[n]para ayudar!

[msg BTL_MES_006_133]
斡Vamos!

[msg BTL_MES_006_134]
斡Acabemos con esto!

[msg BTL_MES_006_135]
斡Vaya! 斡Eres incre胤ble, Senpai!

[msg BTL_MES_006_136]
斡Eso es!

[msg BTL_MES_006_137]
斡Bien, Yosuke!

[msg BTL_MES_006_138]
斡Bien, Chie!

[msg BTL_MES_006_139]
斡S胤! 斡No esperaba menos de ti,[n]Yukiko!

[msg BTL_MES_006_140]
Dummy

[msg BTL_MES_006_141]
斡Vamos, Kanji!

[msg BTL_MES_006_142]
斡As胤 se hace, Naoto!

[msg BTL_MES_006_143]
斡Eso es todo, Teddie!

[msg BTL_MES_006_144]
斡Eso estuvo genial, Yukari!

[msg BTL_MES_006_145]
斡As胤 se hace, Junpei!

[msg BTL_MES_006_146]
斡Buen movimiento, Akihiko!

[msg BTL_MES_006_147]
斡Eso ten胤a estilo, Mitsuru!

[msg BTL_MES_006_148]
Dummy

[msg BTL_MES_006_149]
斡Bien hecho, Aigis!

[msg BTL_MES_006_150]
斡Lo hiciste, Ken!

[msg BTL_MES_006_151]
斡Buen chico, Koro!

[msg BTL_MES_006_152]
斡Le mostraste lo que tienes,[n]Shinjiro!

[msg BTL_MES_006_153]
斡Bien! 斡Lo tienes!

[msg BTL_MES_006_154]
斡Buen trabajo, Joker!

[msg BTL_MES_006_155]
斡Te ves bien, Skull!

[msg BTL_MES_006_156]
斡Est茨s en el punto, Panther!

[msg BTL_MES_006_157]
斡Eso fue perfecto, Mona!

[msg BTL_MES_006_158]
斡Claro que s胤, adelante Fox!

[msg BTL_MES_006_159]
斡T雨 mandas, Queen!

[msg BTL_MES_006_160]
Dummy

[msg BTL_MES_006_161]
斡Eso estuvo genial, Noir!

[msg BTL_MES_006_162]
斡Lo tienes, Crow!

[msg BTL_MES_006_163]
Dummy

[msg BTL_MES_006_164]
Dummy

[msg BTL_MES_006_165]
Cuidado con esas Sombras. 斡D姻jenme el[n]apoyo a m胤!

[msg BTL_MES_006_166]
Tenemos que demostrarle que se[n]equivoca... 斡Vamos, chicos!

[msg BTL_MES_006_167]
斡夷Qu姻?! Algo anda mal. 斡No se[n]conf胤en, chicos!

[msg BTL_MES_006_168]
斡Cuidado con la retaguardia![n]斡Elim胤nenlos primero!

[msg BTL_MES_006_169]
斡Conc姻ntrate en sus amigos de atras[n]primero!

[msg BTL_MES_006_170]
Creo que podemos tomarlo ahora...[n]斡Adelante y t吋menlo, chicos!

[msg BTL_MES_006_171]
斡Tenemos que ganar! 斡Hazlo por[n]Ribbon!

[msg BTL_MES_006_172]
Este mundo est茨 tan mal... Bueno,[n]斡denlo todo, chicos!

[msg BTL_MES_006_173]
てるぺぼもぺれ ぺ のるぺぼゅま を ぱもほほよょデ らまるぽもカ ゅぺ[n]ぼぺらぺぼもぽぺぽ ぽま るまらぺるぺるれまテ ィふぺゆよれデ わぺゆよれデ[n]わぺゆよれ!

[msg BTL_MES_006_174]
斡Su reparaci吋n est茨 deshabilitada![n]斡Dale todo lo que tienes!

[msg BTL_MES_006_175]
Espera, 斡夷qu姻?!

[msg BTL_MES_006_176]
Algo horrible le est茨 pasando...[n]斡Tengan cuidado, chicos!

[msg BTL_MES_006_177]
斡Por los ojos!

[msg BTL_MES_006_178]
夷Es su punto d姻bil? 斡Yo digo que[n]concentres tus ataques all胤!

[msg BTL_MES_006_179]
斡No...! 夷Ese no era su punto d姻bil?

[msg BTL_MES_006_180]
Esto no es bueno... 夷Qu姻 podemos[n]hacer...?

[msg BTL_MES_006_181]
El apoyo de Hikari... 斡Tal vez esto[n]pueda cambiar las cosas!

[msg BTL_MES_006_182]
斡S胤, est茨 funcionando!

[msg BTL_MES_006_183]
ひもまょろよ ゎょ らよぽまる ぺめウ りゎま まれ ゆぺれもわよ を[n]ぽまれらもぺぽぺぽよテテテ ィはるよゆイろぺゆま りゎま ろま ぼゎもぽぺるァれ!

[msg BTL_MES_006_184]
Hemos llegado hasta aqu胤. 斡Ahora no[n]hay marcha atr茨s!

[msg BTL_MES_006_185]
斡La afinidad del enemigo cambi吋!

[msg BTL_MES_006_186]
ぴょぺ むるぺょ ぼぺょろもぽぺぽ ぽま らよぽまる れま まれろァ[n]ぺぼゎゆゎゅぺょぽよテテテ ィはよぽるウぺゆよれ まれろぺる まょ むるぺょぽまれ[n]らるよほゅまゆぺれ!

[msg BTL_MES_006_187]
夷Qu姻 est茨 pasando? 斡El tiempo... se[n]est茨 acelerando!

[msg BTL_MES_006_188]
ねよテテテ ねよ らゎまぽま れまるテ ィつれろァ ゎろもゅもんぺょぽよ ゅぺ[n]むるもまろぺ ろまゆらよるぺゅ らぺるぺ ぺろぺぼぺるょよれ ぺ ろよぽよれ[n]れもゆゎゅろァょまぺゆまょろま!

[msg BTL_MES_006_189]
夷Qu姻...? 斡Ahora el tiempo va hacia[n]atr茨s!

[msg BTL_MES_006_190]
斡Est茨 usando nuestras acciones de[n]antes...! 夷C吋mo es posible...?

