[msg BTL_MES_008_000]
Dummy

[msg BTL_MES_008_001]
No podemos escapar. 斡La 雨nica opci吋n es ganar!

[msg BTL_MES_008_002]
＜声Of＞ええ、絶対L負けpseせz 油断P禁物Hす。

[msg BTL_MES_008_003]
El FOE... Deber胤amos alejarnos en sigilo.

[msg BTL_MES_008_004]
＜声Of＞たしかL ここP退くZきHすN。

[msg BTL_MES_008_005]
Un FOE... 斡Pero tal vez tengamos la fuerza para derrotarlo!

[msg BTL_MES_008_006]
Ah, una Sombra rara... Esto es una oportunidad para nosotros.

[msg BTL_MES_008_007]
＜声Of＞ええ ここH逃がす手PあqeせzN！

[msg BTL_MES_008_008]
＜声Of＞助かqeす、)ビ！

[msg BTL_MES_008_009]
＜声Of＞久慈川さz、了解Hす

[msg BTL_MES_008_010]
＜声Of＞了解しeした、山岸さz！

[msg BTL_MES_008_011]
Parecen m茨s fuertes que nosotros...

[msg BTL_MES_008_012]
＜声Of＞戦略的撤退i視野L入seしnう。

[msg BTL_MES_008_013]
Nunca hab胤amos visto a este enemigo. Analicemos su debilidad.

[msg BTL_MES_008_014]
＜声Of＞いtzK攻撃y試しGfeしnう

[msg BTL_MES_008_015]
Ni siquiera vale la pena luchar contra esa.

[msg BTL_MES_008_016]
＜声Of＞ええ、vかDGいeす

[msg BTL_MES_008_017]
Tenemos muchas posibilidades de ganar.

[msg BTL_MES_008_018]
＜声Of＞手加減PしKい主義KzHす

[msg BTL_MES_008_019]
La Sombra ha... 夷Cambiado...?

[msg BTL_MES_008_020]
＜声Of＞ク7！ マズ姻HすN…

[msg BTL_MES_008_021]
＜声Of＞Jうkp 囲esたoうHすN…

[msg BTL_MES_008_022]
Estamos en peligro...

[msg BTL_MES_008_023]
＜声Of＞立G直しが必要HすN…

[msg BTL_MES_008_024]
＜声Of＞先輩…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_025]
＜声Of＞危KいHすN… 治療y優先しeしnう！

[msg BTL_MES_008_026]
＜声Of＞花村先輩…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_027]
＜声Of＞里中先輩…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_028]
＜声Of＞天城先輩…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_029]
＜声Of＞4ミー

[msg BTL_MES_008_030]
＜声Of＞大丈夫Hすか、巽くz？ 治療y優先しeしnう！

[msg BTL_MES_008_031]
＜声Of＞4ミー

[msg BTL_MES_008_032]
＜声Of＞大丈夫Hすか、クマくz？ 治療y優先しeしnう！

[msg BTL_MES_008_033]
＜声Of＞岳羽さz…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_034]
＜声Of＞伊織さz…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_035]
＜声Of＞真田さz…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_036]
＜声Of＞桐条さz…！ KzIかフ隠ローしKいI！

[msg BTL_MES_008_037]
＜声Of＞4ミー

[msg BTL_MES_008_038]
＜声Of＞大丈夫Hすか、威姻/スさz？ 治療y優先しeしnう！

[msg BTL_MES_008_039]
＜声Of＞大丈夫Hすか、天田くz？ 治療y優先しeしnう！

[msg BTL_MES_008_040]
＜声Of＞大丈夫Hすか、コロマルさz？ 治療y優先しeしnう！

[msg BTL_MES_008_041]
＜声Of＞大丈夫Hすか、荒垣さz？ 治療y優先しeしnう！

[msg BTL_MES_008_042]
＜声Of＞こOeeHP危険Hす。 フ隠ローy！

[msg BTL_MES_008_043]
＜声Of＞ジョー吋ーが危険Hす！ フ隠ローy！

[msg BTL_MES_008_044]
＜声Of＞ス吋ルが危険Hす！ フ隠ローy！

[msg BTL_MES_008_045]
＜声Of＞パンサーが危険Hす！ フ隠ローy！

[msg BTL_MES_008_046]
＜声Of＞モ)が危険Hす！ フ隠ローy！

[msg BTL_MES_008_047]
＜声Of＞フ隠7クスが危険Hす！ フ隠ローy！

[msg BTL_MES_008_048]
＜声Of＞大丈夫Hすか、ク姻ーン？ 治療y優先しeしnう！

[msg BTL_MES_008_049]
＜声Of＞4ミー

[msg BTL_MES_008_050]
＜声Of＞大丈夫Hすか、ノワール？ 治療y優先しeしnう！

[msg BTL_MES_008_051]
＜声Of＞クロ胤が危険Hす！ フ隠ローy！

[msg BTL_MES_008_052]
＜声Of＞ここP、効率oくいきeしnう

[msg BTL_MES_008_053]
斡Es nuestra oportunidad! 斡La aprovechar姻!

[msg BTL_MES_008_054]
＜声Of＞そうHすN 気y抜かずいきeしnう

[msg BTL_MES_008_055]
Puedo atacar su debilidad con precisi吋n...

[msg BTL_MES_008_056]
Siempre podemos usar relevo.

[msg BTL_MES_008_057]
Parece que me toca.

[msg BTL_MES_008_058]
＜声Of＞先輩、otしくお願いしeす！

[msg BTL_MES_008_059]
＜声Of＞HP、対処お願いしeす！

[msg BTL_MES_008_060]
＜声Of＞花村先輩Okr気が凄いHすN

[msg BTL_MES_008_061]
＜声Of＞里中先輩、任せeす！

[msg BTL_MES_008_062]
＜声Of＞天城先輩… kq過ぎKい程度Lお願いしeす！

[msg BTL_MES_008_063]
＜声Of＞4ミー

[msg BTL_MES_008_064]
＜声Of＞巽くzが kr気L満BGいeすN

[msg BTL_MES_008_065]
＜声Of＞4ミー

[msg BTL_MES_008_066]
＜声Of＞クマくz！ キミO本気、見せGくAさい！

[msg BTL_MES_008_067]
＜声Of＞岳羽さz、そOee お願いしeす！

[msg BTL_MES_008_068]
＜声Of＞伊織さzL お任せしeすN。

[msg BTL_MES_008_069]
＜声Of＞真田さzが kr気HすN…！

[msg BTL_MES_008_070]
＜声Of＞桐条さzP 容赦がKさそうHす。

[msg BTL_MES_008_071]
＜声Of＞4ミー

[msg BTL_MES_008_072]
＜声Of＞威姻/スさz！ 作戦y開始しGくAさい！

[msg BTL_MES_008_073]
＜声Of＞天田くzがkr気HすN！

[msg BTL_MES_008_074]
＜声Of＞コロマルさz！ 頑張DGくAさい！

[msg BTL_MES_008_075]
＜声Of＞蹴散pしGくAさい！ 荒垣さz！

[msg BTL_MES_008_076]
＜声Of＞ここP威)3Lお任せしeす！

[msg BTL_MES_008_077]
＜声Of＞さすがHすN！ ジョー吋ー！

[msg BTL_MES_008_078]
＜声Of＞期待しGいeす！ ス吋ル！

[msg BTL_MES_008_079]
＜声Of＞パンサーL 続きeしnう！

[msg BTL_MES_008_080]
＜声Of＞モ)！ キミL託しeす！

[msg BTL_MES_008_081]
＜声Of＞フ隠7クスKp 華麗L決hGくsrPず！

[msg BTL_MES_008_082]
＜声Of＞こO勢いL乗qeしnう！ ク姻ーン！

[msg BTL_MES_008_083]
＜声Of＞4ミー

[msg BTL_MES_008_084]
＜声Of＞ノワールi kr気充分HすN！

[msg BTL_MES_008_085]
＜声Of＞クロ胤！ お願いしeすN！

[msg BTL_MES_008_086]
斡Es momento de demostrarles que puedo hacer!

