[msg BTL_MES_013_000]
Dummy

[msg BTL_MES_013_001]
Lo siento, pero no podemos retroceder. 斡La victoria ser茨 nuestra!

[msg BTL_MES_013_002]
＜声Of＞負けrvけLPいかKい。 すeKいが、ここP退いGipうぞ！

[msg BTL_MES_013_003]
Un FOE... Retirarse ser胤a la mejor opci吋n.

[msg BTL_MES_013_004]
＜声Of＞ああ、こBpi 無茶yすr道理PKい

[msg BTL_MES_013_005]
Un FOE... Pero este parece estar a nuestro alcance.

[msg BTL_MES_013_006]
斡Una Sombra rara...! 斡No dejes que escape!

[msg BTL_MES_013_007]
＜声Of＞KrbJ… 優先的L狙うIしoう

[msg BTL_MES_013_008]
＜声Of＞了解した、)ビ

[msg BTL_MES_013_009]
＜声Of＞了解A、久慈川

[msg BTL_MES_013_010]
＜声Of＞承知した、山岸

[msg BTL_MES_013_011]
Esta parece poderosa... 夷Qu姻 hacemos?

[msg BTL_MES_013_012]
＜声Of＞退くか、進gか。 采配P任せr

[msg BTL_MES_013_013]
Un nuevo enemigo. Mantengan la calma y 斡encuentren su punto d姻bil!

[msg BTL_MES_013_014]
＜声Of＞戦闘,ー3O収集が必要AK krぞ！

[msg BTL_MES_013_015]
Esto no deber胤a ser un problema.

[msg BTL_MES_013_016]
＜声Of＞戦力P五分五分OoうAK。 いくぞ！

[msg BTL_MES_013_017]
斡Los derrotaremos aqu胤 y ahora!

[msg BTL_MES_013_018]
＜声Of＞格下AかpIいDG 決しG侮rKo！

[msg BTL_MES_013_019]
夷Qu姻...? 夷La Sombra cambi吋?

[msg BTL_MES_013_020]
＜声Of＞逃走失敗か… さG、Jうすr！？

[msg BTL_MES_013_021]
＜声Of＞退くOi作戦Aぞ！

[msg BTL_MES_013_022]
斡Estamos en crisis! 斡Necesitamos un plan!

[msg BTL_MES_013_023]
＜声Of＞今P、回復y最優先H 進hrZきAtう

[msg BTL_MES_013_024]
＜声Of＞こOeeHPマズいK… 援護y優先すrぞ！

[msg BTL_MES_013_025]
＜声Of＞大丈夫か？ ここP回復y考えKけsQ…

[msg BTL_MES_013_026]
＜声Of＞大丈夫か、花村！ 対処y考えNQ…

[msg BTL_MES_013_027]
＜声Of＞無理yすrK、里中！ こBpHi援護yすr！

[msg BTL_MES_013_028]
＜声Of＞しDかqしt、天城！ すぐL援護すr！

[msg BTL_MES_013_029]
＜声Of＞4ミー

[msg BTL_MES_013_030]
＜声Of＞大丈夫か、巽！ こOeeHPマズいK…

[msg BTL_MES_013_031]
＜声Of＞しDかqしt、白鐘！ JうLか回復yしKけsQ…

[msg BTL_MES_013_032]
＜声Of＞おいクマ、しDかqしt！ こOee放DGおけKいK…

[msg BTL_MES_013_033]
＜声Of＞岳羽がkpsGrぞ！ くD…回復が必要AK

[msg BTL_MES_013_034]
＜声Of＞無理yすrK伊織！ 待DGいt、援護すr！

[msg BTL_MES_013_035]
＜声Of＞しDかqしt、明彦！ 今、援護yすr！

[msg BTL_MES_013_036]
＜声Of＞4ミー

[msg BTL_MES_013_037]
＜声Of＞4ミー

[msg BTL_MES_013_038]
＜声Of＞くD…威姻/ス！ こBpiフ隠ローL努hr！

[msg BTL_MES_013_039]
＜声Of＞天田、しDかqしGくs！ すぐ援護すr！

[msg BTL_MES_013_040]
＜声Of＞おいD、コロマル！ くD…回復が必要そうAK

[msg BTL_MES_013_041]
＜声Of＞しDかqしt、荒垣！ 早く回復yしGkpKいI…

[msg BTL_MES_013_042]
＜声Of＞おい、大丈夫か！？ すぐLフ隠ローLあたr！

[msg BTL_MES_013_043]
＜声Of＞ジョー吋ー、しDかqしt！ 早く手当GしKけsQ…！

[msg BTL_MES_013_044]
＜声Of＞こOeeHPス吋ルが危険A！ 早急L対処が必要Aぞ！

[msg BTL_MES_013_045]
＜声Of＞くD…パンサーが…！ こBpi、すぐ援護すr！

[msg BTL_MES_013_046]
＜声Of＞Jうした、モ)！？ こOeeHP危険Aぞ！

[msg BTL_MES_013_047]
＜声Of＞大丈夫か、フ隠7クス！ くD…すぐL回復しKけsQ！

[msg BTL_MES_013_048]
＜声Of＞ク姻ーンがkpsGrぞ！ すぐL回復Lあたs！

[msg BTL_MES_013_049]
＜声Of＞4ミー

[msg BTL_MES_013_050]
＜声Of＞ノワール、しDかqしt！ こBpiフ隠ローすr！

[msg BTL_MES_013_051]
＜声Of＞クロ胤がkpsGいrぞ！ 早急K回復y！

[msg BTL_MES_013_052]
＜声Of＞了解した。 すぐL楽LしGktう

[msg BTL_MES_013_053]
斡Ahora es mi turno! 斡Prep茨rate!

[msg BTL_MES_013_054]
＜声Of＞フ7… eAeA、いけそうAK

[msg BTL_MES_013_055]
Perm胤teme exponer su debilidad.

[msg BTL_MES_013_056]
Un Relevo podr胤a sernos 雨til.

[msg BTL_MES_013_057]
Supongo que ser茨 un desaf胤o de fuerza.

[msg BTL_MES_013_058]
＜声Of＞ああ、期待L応えGくs！

[msg BTL_MES_013_059]
＜声Of＞フ7…頼iしい限qAK 任せrぞ！

[msg BTL_MES_013_060]
＜声Of＞花村、目LiOy見せGks！

[msg BTL_MES_013_061]
＜声Of＞頼gぞ、里中！

[msg BTL_MES_013_062]
＜声Of＞天城、思う存分L 力y奮DGくs！

[msg BTL_MES_013_063]
＜声Of＞4ミー

[msg BTL_MES_013_064]
＜声Of＞気合P充分O様AK、巽！

[msg BTL_MES_013_065]
＜声Of＞白鐘！ 君O力y信じGいr！

[msg BTL_MES_013_066]
＜声Of＞クマ、君O本領y 発揮しGくs！

[msg BTL_MES_013_067]
＜声Of＞頼zAぞ、岳羽！ そOee敵y殲滅しt！

[msg BTL_MES_013_068]
＜声Of＞フ7、伊織… 存分LkDGfせt！

[msg BTL_MES_013_069]
＜声Of＞明彦！ 全力H行け！

[msg BTL_MES_013_070]
＜声Of＞4ミー

[msg BTL_MES_013_071]
＜声Of＞4ミー

[msg BTL_MES_013_072]
＜声Of＞威姻/ス！ 敵O殲滅y開始しt！

[msg BTL_MES_013_073]
＜声Of＞天田、実力y見せEけGks！

[msg BTL_MES_013_074]
＜声Of＞いいぞ、コロマル。 お前Kpksr！

[msg BTL_MES_013_075]
＜声Of＞気合が入DGいrK、荒垣。 後P頼zAぞ。

[msg BTL_MES_013_076]
＜声Of＞フ7…いい気合いA、期待しGrぞ！

[msg BTL_MES_013_077]
＜声Of＞お前O力、見せGくsジョー吋ー！

[msg BTL_MES_013_078]
＜声Of＞bう…ずいWzI 頼iしいじjKいか、ス吋ル！

[msg BTL_MES_013_079]
＜声Of＞パンサー！ 君O力、期待しGいrぞ！

[msg BTL_MES_013_080]
＜声Of＞KpQ、モ)！ 遠慮KくkDGfせt！

[msg BTL_MES_013_081]
＜声Of＞Jうkp、フ隠7クスL eかせた方がoさそうAK

[msg BTL_MES_013_082]
＜声Of＞頼zAぞ、ク姻ーン。 君KpkDGくsrI信じGr

[msg BTL_MES_013_083]
＜声Of＞4ミー

[msg BTL_MES_013_084]
＜声Of＞ノワール、君O出番A。 フルパワーHいDGくs！

[msg BTL_MES_013_085]
＜声Of＞フ7、クロ胤Kp 完璧LキメGくsそうA

[msg BTL_MES_013_086]
Supongo que es hora de mostrar de lo que soy capaz.

