[msg BTL_MES_026_000]
Dummy

[msg BTL_MES_026_001]
斡Este es duro! 斡Ten cuidado!

[msg BTL_MES_026_002]
斡Hm! 斡Prep茨rate para lo que sea!

[msg BTL_MES_026_003]
斡Ugh, un FOE! 斡No creo que podamos[n]con 姻l!

[msg BTL_MES_026_004]
斡Un FOE! 斡Corre!

[msg BTL_MES_026_005]
No pasa nada si huimos. 斡Mejor[n]prevenir que lamentar!

[msg BTL_MES_026_006]
Probablemente deber胤amos correr...[n]斡Corran!

[msg BTL_MES_026_007]
Esa es fuerte. 斡Tendr茨s que ser[n]creativo!

[msg BTL_MES_026_008]
斡Esa es fuerte! 斡Mant姻n la calma!

[msg BTL_MES_026_009]
斡Este FOE es fuerte en ataques[n]f胤sicos! 斡No dejes que te toque!

[msg BTL_MES_026_010]
Ese enemigo es astuto, 斡cuidado con[n]sus ataques m茨gicos!

[msg BTL_MES_026_011]
斡Esa se volver茨 loco si se debilita![n]斡Elim胤nala r茨pido!

[msg BTL_MES_026_012]
斡Genial! 斡Una sombra rara! 斡No dejes[n]que se escape!

[msg BTL_MES_026_013]
斡Mierda, una rara! 斡Derr胤bala!

[msg BTL_MES_026_014]
斡Bien! 斡Atr茨pala antes de que se[n]escape...!

[msg BTL_MES_026_015]
斡Apunten y no la dejen escapar!

[msg BTL_MES_026_016]
Ese puede golpear a todos a la vez.[n]斡Atentos a sus movimientos!

[msg BTL_MES_026_017]
斡Esa Sombra puede golpear a m雨ltiples[n]objetivos! 斡Mantente en guardia!

[msg BTL_MES_026_018]
斡Esa puede matar instant茨neamente![n]斡Elim胤nala primero!

[msg BTL_MES_026_019]
斡Los ataques m茨gicos no funcionar茨n![n]斡Prueba otra cosa!

[msg BTL_MES_026_020]
斡Se aproxima un ataque poderoso![n]斡Cuidado!

[msg BTL_MES_026_021]
斡Esa es fuerte! 斡Ten cuidado!

[msg BTL_MES_026_022]
Esos tipos son m茨s fuertes que[n]nosotros. 斡Cuidado!

[msg BTL_MES_026_023]
Es luchar o correr, 斡decide!

[msg BTL_MES_026_024]
夷Qu姻 va a ser? 夷Pelea o corre?

[msg BTL_MES_026_025]
Ese enemigo es nuevo... 斡No dejes que[n]te supere!

[msg BTL_MES_026_026]
No hay datos sobre este... 斡Ten[n]cuidado!

[msg BTL_MES_026_027]
斡Ohhh! 斡Buen trabajo, chicos!

[msg BTL_MES_026_028]
Tranquilo. 斡Me gusta eso!

[msg BTL_MES_026_029]
斡No retrocedas, Yosuke!

[msg BTL_MES_026_030]
斡Buena idea, Chie!

[msg BTL_MES_026_031]
斡No te arriesgues, Yukiko!

[msg BTL_MES_026_032]
Dummy

[msg BTL_MES_026_033]
斡Mant姻n la concentraci吋n, Kanji!

[msg BTL_MES_026_034]
斡Incre胤ble, Naoto!

[msg BTL_MES_026_035]
斡Ah胤 vas, Teddie!

[msg BTL_MES_026_036]
Ten cuidado, Yukari.

[msg BTL_MES_026_037]
斡Junpei! 斡Busca su debilidad!

[msg BTL_MES_026_038]
Vamos, Hikohiko... Esto no es un[n]boxeo.

[msg BTL_MES_026_039]
斡Vas en racha, Mitsuru!

[msg BTL_MES_026_040]
Dummy

[msg BTL_MES_026_041]
斡Hazlo, Aigis!

[msg BTL_MES_026_042]
Ken-no-suke, 斡fresco! 斡Me gusta!

[msg BTL_MES_026_043]
斡Vamos, Koromaru!

[msg BTL_MES_026_044]
斡Hm! 斡Lo tienes, Shinjiro!

[msg BTL_MES_026_045]
斡Correcto! 斡Mant姻n los ojos bien[n]abiertos!

[msg BTL_MES_026_046]
斡Puedes hacerlo, Joker!

[msg BTL_MES_026_047]
夷Seguro que puedes hacerlo, Skull?

[msg BTL_MES_026_048]
斡Tranquila, Panther!

[msg BTL_MES_026_049]
斡Buena idea, Mona!

[msg BTL_MES_026_050]
斡Vamos, Fox!

[msg BTL_MES_026_051]
斡Incre胤ble, Queen!

[msg BTL_MES_026_052]
Dummy

[msg BTL_MES_026_053]
斡Ten cuidado, Noir!

[msg BTL_MES_026_054]
Crow tiene raz吋n.

[msg BTL_MES_026_055]
No deber胤a ser un problema, 斡pero no[n]te conf胤es...!

[msg BTL_MES_026_056]
斡Oye, no te conf胤es!

[msg BTL_MES_026_057]
Jeje, 斡solo son unos pececillos![n]Ustedes pueden con esto.

[msg BTL_MES_026_058]
Este ya est茨 en el saco.

[msg BTL_MES_026_059]
Esto ser茨 r茨pido.

[msg BTL_MES_026_060]
斡No pueden hacer nada contra[n]nosotros! 斡Acabemos con ellos!

[msg BTL_MES_026_061]
斡Es nuestra oportunidad! 斡Apunten a[n]su debilidad!

[msg BTL_MES_026_062]
斡Podemos golpear su debilidad! 斡Dale[n]con todo!

[msg BTL_MES_026_063]
Maldici吋n... No hay salida...

[msg BTL_MES_026_064]
Hrngg... No hay oportunidad...

[msg BTL_MES_026_065]
斡Maldici吋n! 斡Un FOE...!

[msg BTL_MES_026_066]
斡No puede ser! 斡夷Un FOE?!

[msg BTL_MES_026_067]
夷Est茨n bien, chicos? 斡Esto parece[n]dif胤cil!

[msg BTL_MES_026_068]
Tu salud es baja. 斡Ten cuidado!

[msg BTL_MES_026_069]
斡Yosuke est茨 en mal estado!

[msg BTL_MES_026_070]
斡Chie est茨 en problemas! 斡Haz algo!

[msg BTL_MES_026_071]
斡Yukiko est茨 en peligro!

[msg BTL_MES_026_072]
Dummy

[msg BTL_MES_026_073]
斡Kanji est茨 en problemas!

[msg BTL_MES_026_074]
斡Naoto podr胤a necesitar ayuda!

[msg BTL_MES_026_075]
斡Teddie se nos va, si no hacemos[n]algo!

[msg BTL_MES_026_076]
Yukari necesita ayuda lo antes[n]posible!

[msg BTL_MES_026_077]
斡Junpei est茨 herido! 斡Tienes que[n]ayudarlo!

[msg BTL_MES_026_078]
斡Hikohiko est茨 buscando que lo[n]noqueen si no lo ayudamos!

[msg BTL_MES_026_079]
斡Mitsuru se est茨 debilitando[n]r茨pidamente! 斡Ay雨dala!

[msg BTL_MES_026_080]
Dummy

[msg BTL_MES_026_081]
斡No dejes que Aigis se apague![n]斡Necesita ayuda!

[msg BTL_MES_026_082]
斡Ayuda! 斡Ken-no-suke podr胤a no[n]lograrlo!

[msg BTL_MES_026_083]
斡No dejes que lastimen a Puppy!

[msg BTL_MES_026_084]
斡Que alguien ayude a Shinjiro!

[msg BTL_MES_026_085]
斡Cuidado! 斡No te arriesgues!

[msg BTL_MES_026_086]
斡Joker no hace tanto calor!

[msg BTL_MES_026_087]
斡Skull est茨 jodido si no recibe[n]ayuda!

[msg BTL_MES_026_088]
Panther va a necesitar ayuda pronto!

[msg BTL_MES_026_089]
Mona est茨 mal herido, chicos!

[msg BTL_MES_026_090]
Fox est茨 herido! 斡Haz algo!

[msg BTL_MES_026_091]
斡No mueras por nosotros, Queen!

[msg BTL_MES_026_092]
Dummy

[msg BTL_MES_026_093]
斡Noir necesita ayuda! 斡Deprisa!

[msg BTL_MES_026_094]
斡Crow es carne muerta si no hacemos[n]algo r茨pido!

[msg BTL_MES_026_095]
斡Oye! 夷Est茨n todos bien?

[msg BTL_MES_026_096]
斡Siempre podemos correr...!

[msg BTL_MES_026_097]
斡Est茨n petrificados! 斡No podr茨n[n]moverse!

[msg BTL_MES_026_098]
斡Est茨n malditos! 斡Conc姻ntrate en[n]curar!

[msg BTL_MES_026_099]
斡No es bueno! 斡Est茨n envenenados!

[msg BTL_MES_026_100]
斡Oye! 斡Deja de dormir y despierta!

[msg BTL_MES_026_101]
斡Recup姻rate!

[msg BTL_MES_026_102]
La par茨lisis los est茨 retrasando...

[msg BTL_MES_026_103]
斡Heeey! 斡Sal de ah胤!

[msg BTL_MES_026_104]
斡Cuidado! 斡No podr茨s usar tu Persona!

[msg BTL_MES_026_105]
斡Cuidado! 斡No puedes usar ning雨n[n]ataque f胤sico!

[msg BTL_MES_026_106]
Grr... No pueden hacer mucho en este[n]estado...

[msg BTL_MES_026_107]
斡Es d姻bil para los ataques f胤sicos![n]斡Dale todo lo que tienes!

[msg BTL_MES_026_108]
斡Es d姻bil contra el fuego![n]斡Enciendelo!

[msg BTL_MES_026_109]
斡Este es d姻bil contra el hielo! 斡Hora[n]de refrescarlo!

[msg BTL_MES_026_110]
斡Es d姻bil al viento! 斡S吋plale!

[msg BTL_MES_026_111]
La electricidad deber胤a funcionar...[n]夷Crees que puedes manejarlo?

[msg BTL_MES_026_112]
斡Poder nuclear! 斡Elim胤nalo de un solo[n]golpe!

[msg BTL_MES_026_113]
夷Psicokinesis? Bien, 斡hag茨moslo!

[msg BTL_MES_026_114]
La bendici吋n es su debilidad. 斡Hora[n]de ser juzgado!

[msg BTL_MES_026_115]
La maldici吋n deber胤a funcionar.[n]斡Demu姻strale qui姻n manda!

[msg BTL_MES_026_116]
斡Usa ataques f胤sicos para derribarlo!

[msg BTL_MES_026_117]
Usa fuego. 斡Quema, beb姻, quema!

[msg BTL_MES_026_118]
夷Oh? 斡Parece que es d姻bil contra el[n]hielo! 斡Cong姻lalo!

[msg BTL_MES_026_119]
Debilidad contra el viento, 夷eh? 夷Lo[n]tienes?

[msg BTL_MES_026_120]
Es d姻bil a la electricidad. 斡Dale una[n]buena sacudida!

[msg BTL_MES_026_121]
斡Es d姻bil a los ataques nucleares![n]斡Dale todo lo que tienes!

[msg BTL_MES_026_122]
斡Psicokinesis! 斡Listo, apunta, fuego!

[msg BTL_MES_026_123]
斡Oh! Es d姻bil ante la bendici吋n.[n]斡Mu姻strales la luz!

[msg BTL_MES_026_124]
斡Usa la maldici吋n para eliminarlos!

[msg BTL_MES_026_125]
斡Bien! 斡Vamos a por ello!

[msg BTL_MES_026_126]
斡Lo est茨n haciendo genial, chicos![n]斡Buen trabajo!

[msg BTL_MES_026_127]
斡Todo est茨 bien! 斡Ustedes estar茨n[n]bien!

[msg BTL_MES_026_128]
斡S胤! 斡Ah胤! 斡Atr茨palos!

[msg BTL_MES_026_129]
斡Podr胤a ser un buen momento para un[n]Relevo!

[msg BTL_MES_026_130]
斡Ohh! 斡Es el momento perfecto para un[n]Relevo!

[msg BTL_MES_026_131]
Bien, estoy listo. 斡Conf胤en en m胤!

[msg BTL_MES_026_132]
斡Hey! 斡Lista y esperando!

[msg BTL_MES_026_133]
斡Muy bien! 斡A por ellos!

[msg BTL_MES_026_134]
斡S胤! 斡Vamos, vamos!

[msg BTL_MES_026_135]
斡Se ven bien!

[msg BTL_MES_026_136]
斡Se ven bien!

[msg BTL_MES_026_137]
斡Buen trabajo, Yosuke!

[msg BTL_MES_026_138]
斡Rock 'n' roll, Chie!

[msg BTL_MES_026_139]
斡Incre胤ble, Yukiko!

[msg BTL_MES_026_140]
Dummy

[msg BTL_MES_026_141]
斡Oh s胤, Kanji, sigue as胤!

[msg BTL_MES_026_142]
斡Bien, Naoto!

[msg BTL_MES_026_143]
斡Te ves bien, Teddie!

[msg BTL_MES_026_144]
斡Yukari, eso fue incre胤ble!

[msg BTL_MES_026_145]
斡Sigue, Junpei!

[msg BTL_MES_026_146]
斡Bien, Hikohiko!

[msg BTL_MES_026_147]
斡Impresionante, Mitsuru!

[msg BTL_MES_026_148]
Dummy

[msg BTL_MES_026_149]
斡Movimientos suaves, Aigis!

[msg BTL_MES_026_150]
斡Nada mal, Ken-no-suke!

[msg BTL_MES_026_151]
斡Aww, qui姻n es un buen chico!

[msg BTL_MES_026_152]
斡Buen d胤a, Shinjiro!

[msg BTL_MES_026_153]
斡Se ven bien!

[msg BTL_MES_026_154]
斡Destrezas locas, Joker!

[msg BTL_MES_026_155]
斡Muy bien, Skull! 斡Eso fue genial!

[msg BTL_MES_026_156]
斡Panther a por la victoria!

[msg BTL_MES_026_157]
斡Maldita sea, Mona!

[msg BTL_MES_026_158]
斡Eso estuvo genial, Fox!

[msg BTL_MES_026_159]
斡Esa es nuestra Queen!

[msg BTL_MES_026_160]
Dummy

[msg BTL_MES_026_161]
Noir, eso fue genial!

[msg BTL_MES_026_162]
斡Est茨s en racha, Crow!

[msg BTL_MES_026_163]
Dummy

[msg BTL_MES_026_164]
Dummy

[msg BTL_MES_026_165]
Supongo que tenemos que pelear.[n]斡Estoy a tu lado!

[msg BTL_MES_026_166]
Podemos con estos tipos. 斡Usa esas[n]Personas!

[msg BTL_MES_026_167]
斡Hag茨moslo! Prueba diferentes ataques[n]para encontrar su debilidad!

[msg BTL_MES_026_168]
斡Usa la habilidad de "protegerse" si[n]quieres defender a tus amigos!

[msg BTL_MES_026_169]
Ese debe ser raro. 斡No dejes que[n]escape, Joker!

[msg BTL_MES_026_170]
斡Derriba a todas las Sombras para un[n]ataque combinado!

[msg BTL_MES_026_171]
斡Activa el Boost con un Relevo![n]斡Ense隠ales c吋mo se hace!

[msg BTL_MES_026_172]
夷Pidieron refuerzos? Estos son[n]nuevos... 斡Mantente alerta!

[msg BTL_MES_026_173]
斡El estado de la sombra cambi吋![n]斡Quiz茨s encontremos una debilidad!

[msg BTL_MES_026_174]
斡H姻roe, vaya tonter胤a! 斡Le vamos a[n]ense隠ar!

[msg BTL_MES_026_175]
斡夷Qu姻 est茨 pasando?! 夷Est茨n bien?

[msg BTL_MES_026_176]
斡Esto no es bueno! 斡Sal de ah胤[n]r茨pido!

[msg BTL_MES_026_177]
Vamos, vamos a callar a este tipo.

[msg BTL_MES_026_178]
斡Ahora no tiene nada! 斡Es hora de[n]vengarse!

[msg BTL_MES_026_179]
斡S胤! 斡Vamos! 斡Patea a ese aspirante a[n]h姻roe!

[msg BTL_MES_026_180]
Bien... Aun as胤, 斡ahora es m茨s[n]fuerte! 斡Ten cuidado!

[msg BTL_MES_026_181]
Esas zanahorias est茨n en el camino.[n]斡Quiz茨s podamos romperlas!

[msg BTL_MES_026_182]
斡Genial! 斡Ya no puede usar esas[n]zanahorias!

[msg BTL_MES_026_183]
No hay marcha atr茨s... 斡Ataquen sin[n]piedad!

[msg BTL_MES_026_184]
夷Los otros se unen? 斡Mant姻n tu[n]guardia en alto!

[msg BTL_MES_026_185]
No es bueno... 斡Cu胤date de los de[n]atr茨s primero!

[msg BTL_MES_026_186]
斡Vigila a los de atr茨s!

[msg BTL_MES_026_187]
斡Deber胤amos poder derribarlo ahora![n]斡Vamos!

[msg BTL_MES_026_188]
斡Esto es para Ribbon! 斡No podemos[n]perder!

[msg BTL_MES_026_189]
斡Un mundo como este est茨 mal![n]斡Tenemos que detenerlo!

[msg BTL_MES_026_190]
Ribbon deshabilit吋 la autocuraci吋n.[n]斡Es nuestra oportunidad!

[msg BTL_MES_026_191]
Ya no deber胤a poder curarse.[n]斡Ac茨balo!

[msg BTL_MES_026_192]
斡夷Eso est茨 permitido siquiera?!

[msg BTL_MES_026_193]
Est茨 fuera de control... 斡Atenci吋n[n]chicos!

[msg BTL_MES_026_194]
斡Ve a por los ojos!

[msg BTL_MES_026_195]
夷Ese es su punto d姻bil? 斡Concentra[n]tus ataques!

[msg BTL_MES_026_196]
斡夷Qu姻?! 夷Ese no es su punto d姻bil?

[msg BTL_MES_026_197]
No... si esto sigue...

[msg BTL_MES_026_198]
El apoyo de Hikari... 斡Tal vez[n]podamos hacerlo!

[msg BTL_MES_026_199]
斡S胤! 斡Est茨 funcionando!

[msg BTL_MES_026_200]
Su presencia es incre胤ble... 斡Tengan[n]cuidado, chicos!

[msg BTL_MES_026_201]
Hemos llegado hasta aqu胤. 斡Terminemos[n]esto!

[msg BTL_MES_026_202]
斡La afinidad del enemigo cambi吋![n]斡Cuidado!

[msg BTL_MES_026_203]
Ha acumulado mucha energ胤a. 斡Si[n]ataca, estamos perdidos!

[msg BTL_MES_026_204]
斡夷Qu姻 demo...?! 夷El tiempo est茨[n]saltando hacia adelante?

[msg BTL_MES_026_205]
夷C吋mo puede atacarnos mientras salta[n]a trav姻s del tiempo...?

[msg BTL_MES_026_206]
斡夷Eh?! 斡夷Qu姻 pas吋?! 夷Volvimos en el[n]tiempo?

[msg BTL_MES_026_207]
斡夷Recuerda lo que hicimos antes de[n]retroceder?! No puede ser...

