[msg BTL_MES_026_000]
DUMMY

[msg BTL_MES_026_001]
Mm... vale la pena pelear contra esa.

[msg BTL_MES_026_002]
斡Lo tienes! Ahora, 斡enc茨rgate!

[msg BTL_MES_026_003]
斡A-ah! 斡Ese tipo est茨 muy por encima de tu liga!

[msg BTL_MES_026_004]
斡Retrocedan! 斡Retirada! 斡Vete!

[msg BTL_MES_026_005]
Mm... Puede que seas lo suficientemente fuerte...

[msg BTL_MES_026_006]
Esa es dura. Necesitar茨s un enfoque diferente.

[msg BTL_MES_026_007]
Esa tiene un ataque fuerte. No dejes que te tome por sorpresa.

[msg BTL_MES_026_008]
Los ataques f胤sicos de esa son fastidios. No lo olvides.

[msg BTL_MES_026_009]
Cuidado con sus ataques m茨gicos. 斡Mantente alerta!

[msg BTL_MES_026_010]
Se vuelve violenta cuando se debilita. 斡Eliminala r茨pido!

[msg BTL_MES_026_011]
Vaya... La forma en la que brilla...

[msg BTL_MES_026_012]
斡No dejes que escape!

[msg BTL_MES_026_013]
Mm... 斡Esa tiene un ataque que los golpear茨 a todos a la vez!

[msg BTL_MES_026_014]
斡Cuida tus aliados! 夷Est茨n bien?

[msg BTL_MES_026_015]
斡Esa tiene un ataque que golpea m雨ltiples objetivos!

[msg BTL_MES_026_016]
斡No te olvides de protegerte!

[msg BTL_MES_026_017]
Esta... 斡Tiene un ataque de muerte instant茨nea!

[msg BTL_MES_026_018]
斡Oye! 斡Pon atenci吋n!

[msg BTL_MES_026_019]
斡No uses ataques de afinidad ahora!

[msg BTL_MES_026_020]
斡Usa ataques f胤sicos!

[msg BTL_MES_026_021]
斡Cuidado! 斡Viene un gran golpe!

[msg BTL_MES_026_022]
斡Prep茨rense para el impacto!

[msg BTL_MES_026_023]
Esa parece dura.

[msg BTL_MES_026_024]
斡Oye, no te arriesgues demasiado! 斡No podemos dejar que mueras aqu胤!

[msg BTL_MES_026_025]
夷Mm? Nunca hab胤amos visto esa antes...

[msg BTL_MES_026_026]
Primero, lo primero: 斡prueba habilidades diferentes!

[msg BTL_MES_026_027]
斡Esa Sombra es perfecta para ti!

[msg BTL_MES_026_028]
斡En otras palabras, es presa f茨cil! 斡Elim胤nala!

[msg BTL_MES_026_029]
Eh, solo un pececillo.

[msg BTL_MES_026_030]
斡Je! 斡Entonces no deber胤a tardar mucho!

[msg BTL_MES_026_031]
夷Mm? 斡Las afinidades de esa Sombra cambiaron!

[msg BTL_MES_026_032]
斡Es tu oportunidad! 斡Explota su debilidad!

[msg BTL_MES_026_033]
Tss... 斡Nada bueno!

[msg BTL_MES_026_034]
En otras palabras, 斡no logramos escapar! 斡Sobrevivan!

[msg BTL_MES_026_035]
夷Qu姻? 斡夷Ahora?!

[msg BTL_MES_026_036]
斡Es un FOE! 斡Esto NO es bueno!

[msg BTL_MES_026_037]
斡Cuidado! 斡Casi tenemos un abatido!

[msg BTL_MES_026_038]
Oye, 斡夷est茨 bien su salud?!

[msg BTL_MES_026_039]
Oye, 夷Yosuke est茨 bien?

[msg BTL_MES_026_040]
斡夷Chie estar茨 bien?!

[msg BTL_MES_026_041]
O-oye, 斡Perderemos a Yukiko a este paso!

[msg BTL_MES_026_042]
Dummy

[msg BTL_MES_026_043]
夷Vas a dejar a Kanji as胤?

[msg BTL_MES_026_044]
Naoto est茨 al l胤mite.

[msg BTL_MES_026_045]
斡Oye! 斡Alguien proteja a Teddie!

[msg BTL_MES_026_046]
斡Eh! 斡Yukari est茨 en peligro!

[msg BTL_MES_026_047]
斡Oye! 斡Junpei no est茨 muy bien!

[msg BTL_MES_026_048]
夷Vamos a dejar Akihiko as胤?

[msg BTL_MES_026_049]
斡Oye! 斡Alguien proteja a Mitsuru!

[msg BTL_MES_026_050]
Dummy

[msg BTL_MES_026_051]
斡Mira la salud de Aigis!

[msg BTL_MES_026_052]
Ken parece estar acabado.

[msg BTL_MES_026_053]
斡Oye! 斡Alguien proteja a Koromaru!

[msg BTL_MES_026_054]
斡Shinjiro no va a lograrlo!

[msg BTL_MES_026_055]
斡Alguien va a morir a este paso!

[msg BTL_MES_026_056]
斡Oye! 斡夷Vas a sobrevivir, Joker?!

[msg BTL_MES_026_057]
斡Skull est茨 en peligro!

[msg BTL_MES_026_058]
夷Mm? 夷Panther estar茨 bien?

[msg BTL_MES_026_059]
Mm... 斡Mona podr胤a caer pronto!

[msg BTL_MES_026_060]
斡Oye! 斡Alguien, ayude a Fox!

[msg BTL_MES_026_061]
夷Queen recibir茨 ayuda pronto?

[msg BTL_MES_026_062]
Dummy

[msg BTL_MES_026_063]
La salud de Noir est茨 al l胤mite...

[msg BTL_MES_026_064]
Crow no va a contarlo...

[msg BTL_MES_026_065]
斡Deprisa, c雨rense ya!

[msg BTL_MES_026_066]
Tss... 斡Petrificaci吋n!

[msg BTL_MES_026_067]
Oye, 斡un aliado ha sido Maldecido!

[msg BTL_MES_026_068]
斡Cuidado con el veneno! Espera, 夷斡ya est茨s envenenado!?

[msg BTL_MES_026_069]
斡Despierten esa cabeza dormilona!

[msg BTL_MES_026_070]
Maldita sea, est茨n confundidos...

[msg BTL_MES_026_071]
斡Un aliado ha sido paralizado!

[msg BTL_MES_026_072]
斡Maldici吋n! Est茨n aturdidos...

[msg BTL_MES_026_073]
Sus ataques m茨gicos est茨n sellados. Va a ser un problema...

[msg BTL_MES_026_074]
Cuidado, tu fuerza est茨 sellada.

[msg BTL_MES_026_075]
Maldici吋n, su agilidad est茨 sellada...

[msg BTL_MES_026_076]
斡Sup姻ralo y luego, a por ellos!

[msg BTL_MES_026_077]
斡Puedes usar ataques f胤sicos para golpear sus puntos d姻biles!

[msg BTL_MES_026_078]
斡Esa es d姻bil contra el Fuego!

[msg BTL_MES_026_079]
斡El hielo es una buena opci吋n para esa!

[msg BTL_MES_026_080]
Esa Sombra es d姻bil al viento...

[msg BTL_MES_026_081]
斡La electricidad es su debilidad!

[msg BTL_MES_026_082]
斡Una Sombra d姻bil a lo nuclear!

[msg BTL_MES_026_083]
La psicoquinesis es lo que necesitamos...

[msg BTL_MES_026_084]
斡La Bendici吋n es lo que necesitamos!

[msg BTL_MES_026_085]
斡Usa la maldici吋n para atacar su debilidad!

[msg BTL_MES_026_086]
斡Oye! 斡Intenta golpearlas con un ataque f胤sico!

[msg BTL_MES_026_087]
Una Sombra d姻bil al Fuego... 斡Hora de verla arder!

[msg BTL_MES_026_088]
斡Congela las Sombras y derribarlas!

[msg BTL_MES_026_089]
斡Si quieres aprovechar su debilidad, usa Viento!

[msg BTL_MES_026_090]
D姻bil a la electricidad, eh... 斡Hora de la silla el姻ctrica!

[msg BTL_MES_026_091]
斡Con ataques nucleares, podr胤as abusar de su debilidad!

[msg BTL_MES_026_092]
Hay una Sombra d姻bil contra la Psicoquinesis.

[msg BTL_MES_026_093]
斡Puedes golpear su debilidad con ataques de bendici吋n!

[msg BTL_MES_026_094]
Son d姻biles contra la Maldici吋n. 斡Mald胤celos con un castigo eterno!

[msg BTL_MES_026_095]
夷Sabes qu姻 hacer?

[msg BTL_MES_026_096]
斡No hay raz吋n para NO usarlo! 夷Me oyes?

[msg BTL_MES_026_097]
斡Yosuke, no nos decepciones!

[msg BTL_MES_026_098]
斡Hazlo, Chie!

[msg BTL_MES_026_099]
Yukiko puede con esto.

[msg BTL_MES_026_100]
Dummy

[msg BTL_MES_026_101]
斡Kanji! 斡Intenta ser 雨til por una vez!

[msg BTL_MES_026_102]
Naoto, 斡Es tu oportunidad de brillar!

[msg BTL_MES_026_103]
斡Teddie, mu姻strales que no eres un osito de peluche!

[msg BTL_MES_026_104]
Yukari, 夷sabes qu姻 hacer?

[msg BTL_MES_026_105]
斡Vamos, Junpei!

[msg BTL_MES_026_106]
斡Akihiko, usa cada c姻lula en tu cuerpo!

[msg BTL_MES_026_107]
斡Mitsuru, te toca!

[msg BTL_MES_026_108]
Dummy

[msg BTL_MES_026_109]
Aigis, esto te va como anillo al dedo, 夷no?

[msg BTL_MES_026_110]
夷Qu姻 te parece, Ken? 斡Aqu胤 puedes lucirte!

[msg BTL_MES_026_111]
斡Vamos, Koromaru!

[msg BTL_MES_026_112]
斡Ac茨balo, Shinjiro!

[msg BTL_MES_026_113]
斡Bien! 斡Ve por ellos!

[msg BTL_MES_026_114]
斡Joker! 斡Depende de ti!

[msg BTL_MES_026_115]
斡Skull, t雨 puedes!

[msg BTL_MES_026_116]
Panther, 斡haz algo bueno por nosotros!

[msg BTL_MES_026_117]
斡Vamos, Mona! 斡Acaba con ellos!

[msg BTL_MES_026_118]
斡Date prisa y ac茨balo, Fox!

[msg BTL_MES_026_119]
斡Esto deber胤a ser f茨cil para ti, Queen!

[msg BTL_MES_026_120]
Dummy

[msg BTL_MES_026_121]
斡Ahora, Noir!

[msg BTL_MES_026_122]
Crow, 夷crees poder con esto?

[msg BTL_MES_026_123]
Bien, adelante.

[msg BTL_MES_026_124]
Ahora... 夷Qu姻 sigue?

[msg BTL_MES_026_125]
T吋mate tu tiempo, pero no demasiado.

[msg BTL_MES_026_126]
Esto me est茨 dando ganas de unirme a la batalla.

[msg BTL_MES_026_127]
Oye, 夷qu姻 tal si usas Relevo?

[msg BTL_MES_026_128]
斡Usa Relevo!

[msg BTL_MES_026_129]
夷Eh? 斡Hay alguien que est茨 en Boost!

[msg BTL_MES_026_130]
Bien, bien, 斡est茨 en Boost!

[msg BTL_MES_026_131]
Mira, 斡Yosuke est茨 en Boost!

[msg BTL_MES_026_132]
斡Chie ha sido Boosteada!

[msg BTL_MES_026_133]
斡Oye, Yukiko est茨 en Boost!

[msg BTL_MES_026_134]
Dummy

[msg BTL_MES_026_135]
斡Oh! 斡Kanji est茨 Boosteado!

[msg BTL_MES_026_136]
斡Naoto est茨 Boosteada!

[msg BTL_MES_026_137]
斡Teddie tiene un buen Boost!

[msg BTL_MES_026_138]
斡Buen Boost, Yukari!

[msg BTL_MES_026_139]
夷Eh? 斡Junpei est茨 Boosteado!

[msg BTL_MES_026_140]
Parece que Akihiko ha sido Boosteado.

[msg BTL_MES_026_141]
斡Mira a Mitsuru! 斡Ella est茨 en Boost!

[msg BTL_MES_026_142]
Dummy

[msg BTL_MES_026_143]
Bien. 斡Aigis est茨 en modo Boost!

[msg BTL_MES_026_144]
斡Ken tiene un Boost!

[msg BTL_MES_026_145]
斡Koromaru est茨 Boosteado!

[msg BTL_MES_026_146]
Shinjiro est茨 en Boost.

[msg BTL_MES_026_147]
Alguien en el grupo ha sido Boosteado.

[msg BTL_MES_026_148]
斡Ah! 斡Buen Boost, Joker!

[msg BTL_MES_026_149]
Skull ha sido Boosteado.

[msg BTL_MES_026_150]
斡Bien, Panther ha sido Boosteada!

[msg BTL_MES_026_151]
Mira... 斡Mona ha sido Boosteado!

[msg BTL_MES_026_152]
斡Mira a Fox! 斡Lo han Boosteado!

[msg BTL_MES_026_153]
斡Queen, buen Boost!

[msg BTL_MES_026_154]
Dummy

[msg BTL_MES_026_155]
Noir ha sido Boosteada.

[msg BTL_MES_026_156]
斡Crow ha sido boosteado!

[msg BTL_MES_026_157]
斡Puedes golpear su debilidad! ... 斡Aseg雨rate de matarla!

[msg BTL_MES_026_158]
斡Y tienes una afinidad con esa Sombra! 斡Es nuestra oportunidad!

[msg BTL_MES_026_159]
El apoyo est茨 listo en cualquier momento.

[msg BTL_MES_026_160]
Apoyo listo. 斡郁salo cuando puedas!

[msg BTL_MES_026_161]
Parece que estamos frente a un enemigo fuerte.

[msg BTL_MES_026_162]
Cuidado.

[msg BTL_MES_026_163]
Esto... no es bueno.

[msg BTL_MES_026_164]
Estoy de acuerdo. Recomiendo escapar de inmediato.

[msg BTL_MES_026_165]
Tal vez con tu habilidad, puedas derrotarlo.

[msg BTL_MES_026_166]
Pero parece que ser茨 dif胤cil romper su defensa. Debemos encontrar una manera.

[msg BTL_MES_026_167]
Est茨 preparando un ataque masivo. Ten cuidado.

[msg BTL_MES_026_168]
Sus ataques f胤sicos pueden causarte problemas... Ten cuidado.

[msg BTL_MES_026_169]
La fuerza de esa est茨 en sus ataques m茨gicos. No lo olvides.

[msg BTL_MES_026_170]
Este enemigo gana fuerza a medida que se debilita. Ser胤a mejor eliminarlo r茨pido.

[msg BTL_MES_026_171]
Debe ser... una Sombra rara.

[msg BTL_MES_026_172]
Parece ser una Sombra rara, no la dejes escapar.

[msg BTL_MES_026_173]
Ten cuidado con sus ataques. Los golpear茨 a todos.

[msg BTL_MES_026_174]
Vigila tu salud.

[msg BTL_MES_026_175]
Esta Sombra usa un ataque que golpea m雨ltiples objetivos.

[msg BTL_MES_026_176]
No olvides protegerte.

[msg BTL_MES_026_177]
Esa usa habilidades de muerte instant茨nea... Ten cuidado.

[msg BTL_MES_026_178]
No bajes la guardia.

[msg BTL_MES_026_179]
Es in雨til intentar ataques de debilidad ahora mismo.

[msg BTL_MES_026_180]
Probablemente, lo mejor ser茨 usar ataques f胤sicos.

[msg BTL_MES_026_181]
Se aproxima un ataque enorme...

[msg BTL_MES_026_182]
No olvides protegerte.

[msg BTL_MES_026_183]
Este oponente es demasiado fuerte para ti.

[msg BTL_MES_026_184]
Si est茨s en peligro, te recomiendo escapar.

[msg BTL_MES_026_185]
No tenemos datos de ese enemigo...

[msg BTL_MES_026_186]
Podr胤amos querer averiguar su naturaleza primero.

[msg BTL_MES_026_187]
No son fuertes ni d姻biles...

[msg BTL_MES_026_188]
Derr吋tala r茨pido y con experiencia.

[msg BTL_MES_026_189]
Este enemigo ni siquiera vale tu tiempo.

[msg BTL_MES_026_190]
Ahora, date prisa y deshazte de ellos.

[msg BTL_MES_026_191]
Parece que la afinidad del enemigo cambi吋.

[msg BTL_MES_026_192]
Es tu oportunidad de golpear su debilidad.

[msg BTL_MES_026_193]
No encontr姻 una salida...

[msg BTL_MES_026_194]
No veo una salida.

[msg BTL_MES_026_195]
Nos alcanz吋...

[msg BTL_MES_026_196]
Es un FOE, ten cuidado.

[msg BTL_MES_026_197]
Cuida a tus aliados.

[msg BTL_MES_026_198]
Parece que necesitan ayuda.

[msg BTL_MES_026_199]
夷Vas a ignorar a Yosuke?

[msg BTL_MES_026_200]
Chie no est茨 bien.

[msg BTL_MES_026_201]
Yukiko podr胤a terminar mal.

[msg BTL_MES_026_202]
Dummy

[msg BTL_MES_026_203]
Me pregunto si Kanji lo lograra.

[msg BTL_MES_026_204]
夷Naoto est茨 bien?

[msg BTL_MES_026_205]
Teddie no parece estar bien.

[msg BTL_MES_026_206]
Vigila la salud de Yukari.

[msg BTL_MES_026_207]
夷Van a dejar a Junpei as胤?

[msg BTL_MES_026_208]
Parece que Akihiko est茨 en peligro.

[msg BTL_MES_026_209]
Quiz茨s quieras vigilar la salud de Mitsuru.

[msg BTL_MES_026_210]
Dummy

[msg BTL_MES_026_211]
夷Aigis va a estar bien?

[msg BTL_MES_026_212]
Ken est茨 en su l胤mite.

[msg BTL_MES_026_213]
Ten cuidado con Koromaru.

[msg BTL_MES_026_214]
夷Vamos a dejar a Shinjiro atr茨s?

[msg BTL_MES_026_215]
Un miembro del grupo podr胤a desmayarse pronto...

[msg BTL_MES_026_216]
Joker, 夷quieres morir aqu胤?

[msg BTL_MES_026_217]
La salud de Skull est茨 bajando.

[msg BTL_MES_026_218]
夷Vas a dejar que Panther muera?

[msg BTL_MES_026_219]
Mira la salud de Mona.

[msg BTL_MES_026_220]
Si nadie hace nada por Fox, podr胤a morir.

[msg BTL_MES_026_221]
夷Vas a dejar a Queen as胤?

[msg BTL_MES_026_222]
Dummy

[msg BTL_MES_026_223]
Noir podr胤a desmayarse pronto.

[msg BTL_MES_026_224]
夷Vas a dejar a Crow en ese estado?

[msg BTL_MES_026_225]
Recomiendo priorizar la curaci吋n.

[msg BTL_MES_026_226]
Alguien se ha petrificado.

[msg BTL_MES_026_227]
Parece que alguien est茨 maldito.

[msg BTL_MES_026_228]
Alguien est茨 envenenado.

[msg BTL_MES_026_229]
Alguien est茨 durmiendo.

[msg BTL_MES_026_230]
Parece que est茨n confundidos...

[msg BTL_MES_026_231]
Parece que alguien est茨 paralizado.

[msg BTL_MES_026_232]
Parecen mareados...

[msg BTL_MES_026_233]
Su magia est茨 atada.

[msg BTL_MES_026_234]
Parece que tu fuerza est茨 atada.

[msg BTL_MES_026_235]
Parece que tu agilidad est茨 atada... De todos modos, voy a darte 吋rdenes.

[msg BTL_MES_026_236]
夷No deber胤as encargarte de eso ahora?

[msg BTL_MES_026_237]
Un ataque f胤sico resolver茨 el problema.

[msg BTL_MES_026_238]
Un enemigo d姻bil contra el Fuego. Qu姻malo hasta que quede carbonizado.

[msg BTL_MES_026_239]
Si quieres apuntar a su debilidad, utiliza Hielo.

[msg BTL_MES_026_240]
Hay una Sombra d姻bil contra el Viento.

[msg BTL_MES_026_241]
Esa es d姻bil contra la Electricidad.

[msg BTL_MES_026_242]
La afinidad Nuclear ser胤a 雨til aqu胤.

[msg BTL_MES_026_243]
Estas Sombras son d姻biles contra la Psicoquinesis.

[msg BTL_MES_026_244]
Ese enemigo debe ser d姻bil contra la Bendici吋n.

[msg BTL_MES_026_245]
Si quieres golpear su debilidad, intenta usar maldici吋n.

[msg BTL_MES_026_246]
D姻bil contra ataques f胤sicos... Qu姻 Sombra tan cobarde.

[msg BTL_MES_026_247]
Hay una Sombra d姻bil para Fuego.

[msg BTL_MES_026_248]
Esa Sombra es d姻bil al Hielo.

[msg BTL_MES_026_249]
Podr胤as golpear su debilidad con el Viento.

[msg BTL_MES_026_250]
La Electricidad podr胤a ser lo que necesitas.

[msg BTL_MES_026_251]
La Sombra es d姻bil contra lo nuclear.

[msg BTL_MES_026_252]
Con la Psicoquinesis, podr茨s golpear su debilidad.

[msg BTL_MES_026_253]
Bendice a esa Sombra y ser茨 su fin.

[msg BTL_MES_026_254]
Usa la afinidad de Maldici吋n para golepar su debilidad.

[msg BTL_MES_026_255]
No hay por qu姻 contenerse.

[msg BTL_MES_026_256]
Lo entiendes, 夷no?

[msg BTL_MES_026_257]
Yosuke, espero que cumplas nuestras expectativas.

[msg BTL_MES_026_258]
Chie, tu turno.

[msg BTL_MES_026_259]
Estoy segura de que lo har茨s bien, Yukiko.

[msg BTL_MES_026_260]
Dummy

[msg BTL_MES_026_261]
Kanji, mu姻stranos c吋mo debe ser un hombre.

[msg BTL_MES_026_262]
Naoto, todo depende de ti.

[msg BTL_MES_026_263]
Lo tienes, Teddie, 夷verdad?

[msg BTL_MES_026_264]
Yukari, supongo que puedes encargarte de esto, 夷verdad?

[msg BTL_MES_026_265]
Junpei, 夷quieres ser m茨s 雨til?

[msg BTL_MES_026_266]
Mm... Akihiko, espero que puedas con esto.

[msg BTL_MES_026_267]
Mitsuru, deber胤as ser capaz de asestar el golpe.

[msg BTL_MES_026_268]
Dummy

[msg BTL_MES_026_269]
Vamos, Aigis.

[msg BTL_MES_026_270]
Ken, tal vez es tu momento brillar.

[msg BTL_MES_026_271]
Vamos, Koromaru.

[msg BTL_MES_026_272]
Tal vez este sea el momento de Shinjiro.

[msg BTL_MES_026_273]
夷No hay alguien que pueda encargarse de esta tarea?

[msg BTL_MES_026_274]
Joker, esto parece un trabajo para ti.

[msg BTL_MES_026_275]
Ahora, Skull, ve y s姻 雨til.

[msg BTL_MES_026_276]
Tal vez esto dependa de ti, Panther.

[msg BTL_MES_026_277]
Mona, 夷no es este tu territorio?

[msg BTL_MES_026_278]
Fox, 夷te encargar胤as de esto?

[msg BTL_MES_026_279]
Queen, aqu胤 es donde puedes lucirte.

[msg BTL_MES_026_280]
Dummy

[msg BTL_MES_026_281]
Ve y mu姻strales c吋mo se usa un hacha, Noir.

[msg BTL_MES_026_282]
Acaba con ellos, Crow.

[msg BTL_MES_026_283]
夷Cu茨l es nuestro pr吋ximo movimiento?

[msg BTL_MES_026_284]
Poder pelear as胤 es bastante refrescante.

[msg BTL_MES_026_285]
Ten cuidado.

[msg BTL_MES_026_286]
Mantente tranquilo y elige tus acciones sabiamente.

[msg BTL_MES_026_287]
Podr胤as golpear una debilidad si cambian lugares.

[msg BTL_MES_026_288]
Esa podr胤a ser la mejor soluci吋n si quieres golpear la debilidad.

[msg BTL_MES_026_289]
Parece que est茨 Boosteado.

[msg BTL_MES_026_290]
Alguien en el grupo est茨 en Boost.

[msg BTL_MES_026_291]
Yosuke est茨 Boosteado.

[msg BTL_MES_026_292]
Mira, Chie est茨 Boosteada.

[msg BTL_MES_026_293]
Parece que Yukiko acaba de Boostearse.

[msg BTL_MES_026_294]
Dummy

[msg BTL_MES_026_295]
Kanji est茨 en Boost.

[msg BTL_MES_026_296]
Naoto est茨 en Boost.

[msg BTL_MES_026_297]
Parece que Teddie est茨 Boosteado.

[msg BTL_MES_026_298]
Yukari est茨 en Boost.

[msg BTL_MES_026_299]
Junpei est茨 en Boost.

[msg BTL_MES_026_300]
Akihiko parece estar en Boost.

[msg BTL_MES_026_301]
Mitsuru est茨 Boosteada.

[msg BTL_MES_026_302]
Dummy

[msg BTL_MES_026_303]
Aigis ha entrado en modo Boost.

[msg BTL_MES_026_304]
Ken ha sido Boosteado.

[msg BTL_MES_026_305]
Koromaru est茨 en modo Boost.

[msg BTL_MES_026_306]
Shinjiro ha sido Boosteado.

[msg BTL_MES_026_307]
Alguien en el grupo est茨 en Boost.

[msg BTL_MES_026_308]
Parece que est茨s Boosteado, Joker.

[msg BTL_MES_026_309]
Skull est茨 en Boost.

[msg BTL_MES_026_310]
Panther se ha Boosteado.

[msg BTL_MES_026_311]
Parece que Mona ha sido Boosteado.

[msg BTL_MES_026_312]
Fox est茨 en Boost.

[msg BTL_MES_026_313]
Queen est茨 en Boost.

[msg BTL_MES_026_314]
Dummy

[msg BTL_MES_026_315]
Parece que Noir est茨 en Boost.

[msg BTL_MES_026_316]
Crow est茨 en Boost.

[msg BTL_MES_026_317]
Puedes atacar su debilidad... Esta es tu oportunidad.

[msg BTL_MES_026_318]
Abusar de su debilidad ser胤a su mejor apuesta.

[msg BTL_MES_026_319]
Parece que ahora puedes pedir nuestro apoyo.

[msg BTL_MES_026_320]
Tal vez puedas incluir nuestro apoyo en tu estrategia.

