[msg MSG_000 [Ryuji]]
Espera, メhacia dポnde corremos?

[sel SEL_001 top]
ムOracle!
Vamos a averiguarlo.

[msg MSG_002 [Futaba]]
ムEspera! Veamos, ruta de escape, ruta de escape...

[msg MSG_003 [Makoto]]
ムNo tenemos tiempo para esto! Tenemos que alejarnos de aquボ antes de que lleguen refuerzos...
ムOracle! ムメHay algマn lugar seguro?!

[msg MSG_003_05 [Futaba]]
ムDame un segundo! Estoy buscando...

[msg MSG_004 [Futaba]]
ムJoker, ve por ahボ! ムDeberボa estar libre en esa direcciポn!

[msg MSG_005 [Morgana]]
ムMuy bien! ムVamos!

