[msg MSG_000 [Akechi]]
...メUna escalera? Me pregunto hacia donde conduce.

[msg MSG_001 [Ryuji]]
Estホ bastante alto allボ arriba...

[msg MSG_002 [Ann]]
Tal vez puedas alcanzarla, Skull, has entrenado tus piernas con el Equipo de Atletismo...
Podrボas saltar y alcanzarla.

[msg MSG_003 [Ryuji]]
ムDe ninguna manera alcanzarボa eso! Ademホs... me especialic〒 en correr.

[msg MSG_003_05 [Yusuke]]
メEn serio?
Estaba ansioso por ver un gran salto...

[sel SEL_004 top]
Es imposible.
Intenta saltar por nosotros, Skull.

[msg MSG_005 [Ryuji]]
メVerdad? No hay manera de que alcance algo asボ...

[msg MSG_006 [Ryuji]]
ムOye, deja de pedirme cosas imposibles! ムメQu〒 crees que soy, un pホjaro loco?!

[msg MSG_008 [Akechi]]
Tal vez sea el acceso hacia algマn lado...

[msg MSG_008_5 [Akechi]]
Pero en este momento no sirve de nada especular. Sigamos avanzando por ahora.

