[msg MSG_000 [Futaba]]
Nuestro destino estホ adelante.
Hay muchas mホs luces de bマsqueda en[n]comparaciポn con las zonas anteriores... E[n]incluso, estoy obteniendo seワales de FOEs[n]adelante.

[msg MSG_001 [Ryuji]]
Asボ que tenemos que evitar esos enormes[n]FOEs, mientras esquivamos las luces...
Bueno, creo que deberボamos dejホrselo a[n]Joker, como siempre... Confiamos en ti.

[msg MSG_002 [Morgana]]
No podemos arruinar esto. Procedamos con[n]mホxima precauciポn.

