[msg MSG_000 [Yusuke]]
メMm? メQu〒 es eso?

[msg MSG_001 [Ann]]
Oh, parece que estホ brillando...

[msg MSG_002 [Yusuke]]
Es un brillo bastante hermoso... Me gustarボa observarlo mホs de cerca.

[msg MSG_003 [Ann]]
Espera, メes seguro? ムPodrボa ser una trampa!

[msg MSG_004 [Yusuke]]
Cuanto mホs lo miro, mホs misterioso se vuelve su brillo. メPodrボa esta aura... ser replicada con pintura?

[msg MSG_005 [Ryuji]]
ムNo estホ escuchando!

[msg MSG_006 [Futaba]]
Es inマtil intentar detener a Fox cuando se pone asボ. Solo ignora lo que dice.
Pero... ムMホs importante! Parece que hay algo raro.

[msg MSG_007 [Yusuke]]
*suspiro* Debボ haber traボdo mis suministros de arte...
ムメCポmo se me pudo pasar?!

[msg MSG_008 [Ryuji]]
Bien, ya basta, ムvamos!

