[msg MSG_000 [Ann]]
夷Qu姻 podr胤a ser?

[msg MSG_001 [Futaba]]
Mm... No tengo buena se隠al desde aqu胤.[n]斡Ni idea! Es un misterio.

[msg MSG_002 [Ryuji]]
Oye, el olfato animal deber胤a ser 雨til[n]para este tipo de cosas... Mona, 夷qu姻[n]est茨s oli姻ndolo?

[msg MSG_003 [Morgana]]
斡YO-SOY-UN-HUMANO! 斡No un... perro[n]polic胤a!
...Aunque, tiene un buen brillo. Me[n]recuerda a un Tesoro.

[msg MSG_004 [Akechi]]
Un Tesoro, 夷eh? Entonces, 夷por qu姻 no lo[n]llamamos a este "Punto del Tesoro"?
Es posible que contenga objetos bastante[n]雨tiles.

[msg MSG_005 [Ryuji]]
Me parece bien. Eso ser茨 m茨s f茨cil de[n]recordar.

[msg MSG_006 [Yusuke]]
As胤 que el brillo desaparece cuando[n]recoges los objetos...
Es una transici吋n agradable.

[msg MSG_007 [Ann]]
っま ろよぽよれ ゆよぽよれデ ぽまほまるウぺゆよれ るまわもれぺる ゅよれ ゅゎむぺるまれ[n]りゎま ろもまょまょ ぼよょ まれろぺ ゅゎん ほるもゅゅぺょろまテ ィぬぺょろイょ ゅよれ[n]よゃよれ ぺほもまるろよれデ どよやまる!

