[msg MSG_000 [Ann]]
斡Al fin!... Espera, 夷No es aqu胤 por[n]donde entramos?
斡No puedo creer que nos haya llevado tan[n]lejos, podr胤a ser muy 雨til!

[msg MSG_001 [Ryuji]]
S胤, podr胤amos saltarnos parte del[n]camino...
Es como... 夷C吋mo se dice? Ya sabes...

[msg MSG_002 [Akechi]]
Mm, 夷Creo que te refieres a un "atajo"?
Usar esto har茨 nuestra exploraci吋n mucho[n]m茨s f茨cil.
Deber胤amos buscar m茨s como esta.

[msg MSG_003 [Yusuke]]
Adem茨s, ser胤a 雨til marcarla en el mapa[n]para la pr吋xima.

