[msg MSG_000 [Ryuji]]
ムメEh?! Oye, メNo es la escalera de antes?

[msg MSG_001 [Akechi]]
Ya veo, asボ que lleva hacia aquボ...
Podrボamos usarla si la bajamos...
メPor qu〒 no la revisamos?

[msg MSG_002 [Akechi]]
...メUna escalera? Me pregunto dポnde[n]lleva.

[msg MSG_003 [Yusuke]]
No s〒, メcポmo se ve en el mapa?

[msg MSG_004 [Futaba]]
Parece que conecta al otro lado... donde[n]estホbamos antes.

[msg MSG_005 [Ryuji]]
メEn serio? ムOye, vamos a comprobarlo![n]ムPodrボa ser un camino secreto!

