[msg MSG_000 [Futaba]]
ムJoker! ムDetecto enemigos tras esas escaleras!
Si vas a bajar, probablemente sea mejor que est〒s lo mホs preparado posible.

[msg MSG_001 [Ryuji]]
メQu〒 hacemos, Joker? メBajamos?

[msg MSG_002 [Ryuji]]
ムOh, bien, enemigos! メEstamos listos, Joker?

[sel SEL_003 top]
Bajemos.
Dame un minuto.

[msg MSG_004 [Ryuji]]
ムBien! Es hora de darles una paliza.

[msg MSG_005 [Ryuji]]
Entendido, tマ decides. Supongo que deberボa estirarme...

