[msg MSG_000 [P3 Fem Protag]]
Saben, hay algo en estos ciudadanos...[n]Son un poco extra隠os.

[msg MSG_001 [Ann]]
Oh, 夷t雨 tambi姻n lo crees,?

[msg MSG_002 [P3 Fem Protag]]
Todos intentan autoconvencerse de que el[n]h姻roe siempre tiene raz吋n y no est茨[n]haciendo nada malo...

[msg MSG_002_5 [P3 Fem Protag]]
Pero es como si se negaran a pensar en[n]lo que realmente importa: la verdadera[n]justicia...
Es como si simplemente siguieran la[n]corriente, su justicia es lo correcto,[n]solo porque 姻l lo dice.

[msg MSG_003 [Ryuji]]
S胤, ninguno de ellos est茨 pensando por[n]s胤 mismo...
斡Kamoshidaman est茨 equivocado, pero esta[n]gente no piensa!

[msg MSG_004 [Ann]]
Este lugar es igual de desagradable que[n]Kamoshida antes de que lo cambi茨ramos.

[msg MSG_005 [Morgana]]
Bueno, esa es una raz吋n m茨s para no[n]perder el tiempo, sigamos.
Apresuremos la operaci吋n de rescate.

