[msg MSG_000 [Ann]]
ムAl fin!... Espera, メNo es aquボ por donde entramos?
ムNo puedo creer que nos haya llevado tan lejos, podrボa ser muy マtil!

[msg MSG_001 [Ryuji]]
Sボ, podrボamos saltarnos parte del camino...
Es como... メCポmo se dice? Ya sabes...

[msg MSG_002 [Akechi]]
Mm, メCreo que te refieres a un "atajo"?
Usar esto harホ nuestra exploraciポn mucho mホs fホcil.
Deberボamos buscar mホs como esta.

[msg MSG_003 [Yusuke]]
Ademホs, serボa マtil marcarla en el mapa para la prポxima.

