[msg MSG_000 [Rise]]
斡Chicos! 斡Estoy recibiendo la se隠al de[n]una manada de herb胤voros tras esa[n]puerta!
Pero hay algo extra隠o en ellos... Me[n]pregunto si les pasara algo.

[msg MSG_001 [Yosuke]]
Mm... Ser茨 mejor que tengamos cuidado.
Joker, 夷estamos listos?

[msg MSG_002 [Yosuke]]
Las cosas pueden ponerse peligrosas.[n]夷Crees que estamos listos?

[sel SEL_003 top]
Vamos.
Necesito un momento.

[msg MSG_004 [Yosuke]]
Bien, 斡hag茨moslo!

[msg MSG_005 [Yosuke]]
Entiendo. No perdemos nada con[n]prepararnos.

