[msg MSG_000 [Rise]]
ムChicos, un segundo! Estoy sintiendo una[n]presencia tras esa puerta... Es diferente a[n]todo lo que nos hemos encontrado hasta ahora.
Solo para estar seguros, tal vez quieras[n]comprobar si estホs preparado...

[msg MSG_001 [Chie]]
メHay una presencia misteriosa tras esa[n]puerta? Eso es tan aterrador... メDe[n]verdad tenemos que ir por ahボ?

[sel SEL_002 top]
Vamos.
...

[msg MSG_003 [Chie]]
B-bien, entonces... ムTe seguimos, Joker![n]Despu〒s de ti, je, je, je...

[msg MSG_004 [Akechi]]
メEscuchaste eso, Joker? Te han asignado[n]una tarea.
No decepcionarホs a la dama, メverdad?[n]Estaremos detrホs de ti.

[msg MSG_005 [Akechi]]
La precauciポn es una t〒cnica vital para[n]sobrevivir. Si no estホs seguro de[n]lograrlo, prepホrate antes de entrar.

