[msg MSG_000 [Ann]]
ムLo hicimos! ムBien, hora de la cacerボa!

[msg MSG_001 [Chie]]
Whoa, ムMira esta carne! ムムムEs... la carne de todas las carnes!!!

[msg MSG_002 [Yosuke]]
Chie, メestホs babeando?

[msg MSG_003 [Chie]]
Je, je, je... No puedo evitarlo cuando algo tan delicioso estホ justo delante.

[msg MSG_004 [Kanji]]
Bueno, si a Chie le gusta, apuesto a que atraerホ ese carnボvoro fホcilmente.

[msg MSG_005 [Makoto]]
Intentemos colocarla a una distancia segura del dinosaurio y esperemos que eso lo aleje del camino.

[msg MSG_006 [Ann]]
Pero, esa carne sigue congelada... メEstホ bien asボ?

[msg MSG_007 [Naoto]]
Recuerdo haber oボdo que los carnボvoros tienen sus sentidos bien desarrollados para oler a su presa...
Creo que nuestra probabilidad de 〒xito serホ mayor si aumentamos el olor, creo que deberボamos descongelarla.

[sel SEL_008 top]
Vamos a descongelarla.
Vamos a cocinarla.
Agregu〒mosle a Teddie.

[msg MSG_009 [Haru]]
Si lo hici〒ramos aumentarボa... pero es muy grande, descongelarla llevarホ mucho tiempo.

[msg MSG_010 [Akechi]]
Si reacciona al olor, メpor qu〒 no cocinamos la carne?

[msg MSG_011 [Yukiko]]
Sボ... ムEso es!

[msg MSG_012 [Teddie]]
ムNoooo! ムメNo hay piedad para un oso en este mundo?!

[msg MSG_013 [Akechi]]
Si reacciona al olor, メpor qu〒 no cocinamos la carne?

[msg MSG_014 [P3 Fem Protag]]
ムSボ! ムEstoy segura de que ese dinosaurio vendrホ saltando hacia ese delicioso y carnoso aroma!

[msg MSG_015 [Makoto]]
Habボa utensilios de cocina en el congelador, quizホ deberボamos usarlos.

[msg MSG_016 [Ryuji]]
Por cierto, メdポnde vamos a cocinarla? No he visto una cocina en esta selva.

[msg MSG_017 [Ann]]
Um... メEn el cine?

[msg MSG_018 [Yosuke]]
ムNo! Si les dejamos cocinar en un espacio cerrado, ムtodos terminaremos muertos!

[msg MSG_019 [Chie]]
ムOye! ムメQu〒 quieres decir con eso, Yosuke?!

[msg MSG_020 [Yosuke]]
*jadeo* Bueno, ya sabes... U-uhhhh...

[sel SEL_021 top]
Cocinar en interiores es peligroso.
El cine tampoco tiene cocina.

[msg MSG_022 [P4 Hero]]
Joker tiene un buen punto...
Considerando lo grande que es este corte, serボa difボcil cocinarla en una cocina normal.

[msg MSG_023 [Yosuke]]
ムSボ, eso! ムEs demasiado peligroso cocinar en interiores! Cocinarla fuera serホ mucho mホs fホcil, y seguro...
ムSerホ mホs fホcil huir! Tambi〒n...

[msg MSG_024 [Akechi]]
Joker tiene razポn. No habボa nada de eso en el cine...

[msg MSG_025 [Yosuke]]
ムSボ, sボ! Ni siquiera podemos hacer nada allホ de todos modos, asボ que メpor qu〒 no la cocinamos al aire libre?
ムSerホ mホs fホcil huir! Tambi〒n...

[msg MSG_026 [Yusuke]]
Sin embargo, cocinar al aire libre es peligroso, podrボamos iniciar un incendio forestal...

[msg MSG_027 [Makoto]]
En ese caso, tal vez deberボamos hacerlo cerca de un rボo, para poder apagar el fuego rホpido si algo pasa.
Busquemos un lugar donde haya agua cerca para cocinar.

