[msg MSG_000 [Yusuke]]
Mm...

[msg MSG_001 [Ann]]
メQu〒 pasa, Fox?

[msg MSG_002 [Yusuke]]
Bueno, estaba pensando que podrボa ser buena idea ponerle una marca especボfica a las jaulas...

[msg MSG_003 [Akechi]]
Sボ, es una buena idea.
Creo que tener una marca especial para esas jaulas serボa マtil para distinguirlas en el mapa.

[sel SEL_004 top]
Tambi〒n lo creo.
メEs realmente necesario?

[msg MSG_005 [Yusuke]]
Muy bien, メqu〒 tal algo asボ?

[msg MSG_006 [Yusuke]]
Mmm... Permボteme darte un ejemplo.
メQu〒 tal algo asボ?

[msg MSG_007 [Akechi]]
Bueno, el mapa serホ mホs fホcil de leer. メPor qu〒 no la usas?

[msg MSG_ICON_KAITEN_KABE_OPE]
Se ha aワadido un icono [f 0 1 2]Jaula giratoria[f 0 1 0] al mapa de la pantalla inferior.
Si deseas comprobar cポmo utilizar este icono...
Presiona [f 0 1 2]AYUDA[f 0 1 0] en la parte inferior derecha del mapa y presiona [f 0 1 2]Tipos de Iconos[f 0 1 0].

