[msg MSG_000 [Yosukesaurio]]
ムMierda, mierda, mierda, estホ aquボ![n]ムSerホ mejor que corramos!

[msg MSG_001 [Chie]]
ムメQ-qu〒 es eso?! ムEs enoorme!
ムNo duraremos ni un minuto si esa cosa[n]nos atrapa!

[msg MSG_002 [Morgana]]
Um, t-tranquilos... Hay cierta distancia[n]entre 〒l y nosotros, deberボamos estar[n]bien... por ahora.
Ademホs, uhh... ムMiren qu〒 brazos y[n]piernas tiene! Apuesto a que es muy[n]lento, solo miren.

[msg MSG_003 [Teddie]]
Oh, estホ bien entonces...
Estaba pensando en hacerme el muerto,[n]pero tal vez podamos escapar.

[msg MSG_004 [Ryuji]]
ムImpresionante! Supongo que hay que[n]preguntarle a un animal sobre[n]estrategias contra otros animales, メeh?

[msg MSG_005 [Morgana]]
ムNo empieces! Mira dポnde estamos, o[n]dejamos de quejarnos o nos comerホn.

[msg MSG_006 [P4 Hero]]
Si nos atrapara un FOE como ese,[n]seriamos comida de dinosaurio.
Parece que deberボamos continuar con mホs[n]cuidado que antes.

[msg MSG_007 [Akechi]]
Intentemos evitar entrar en pホnico.[n]Tomar decisiones racionales es vital en[n]este momento.
Joker, vamos a [f 0 1 2]continuar para que el FOE[n]no pueda alcanzarnos[f 0 1 0].

