[msg MSG_000 [Ann]]
斡Lo hicimos! 斡Bien, hora de la cacer胤a!

[msg MSG_001 [Chie]]
Whoa, 斡Mira esta carne! 斡斡斡Es... la[n]carne de todas las carnes!!!

[msg MSG_002 [Yosuke]]
Chie, 夷est茨s babeando?

[msg MSG_003 [Chie]]
Je, je, je... No puedo evitarlo cuando[n]algo tan delicioso est茨 justo delante.

[msg MSG_004 [Kanji]]
Bueno, si a Chie le gusta, apuesto a que[n]atraer茨 ese carn胤voro f茨cilmente.

[msg MSG_005 [Makoto]]
Intentemos colocarla a una distancia[n]segura, de dinosaurio y esperemos que[n]eso lo aleje del camino.

[msg MSG_006 [Ann]]
Pero, esa carne sigue congelada... 夷Est茨[n]bien as胤?

[msg MSG_007 [Naoto]]
Recuerdo haber o胤do que los carn胤voros[n]tienen sus sentidos bien desarrollados[n]para oler a su presa...
Creo que nuestra probabilidad de 姻xito[n]ser茨 mayor si aumentamos el olor, creo[n]que deber胤amos descongelarla.

[sel SEL_008 top]
Vamos a descongelarla.
Vamos a cocinarla.
Agregu姻mosle a Teddie.

[msg MSG_009 [Haru]]
Si lo hici姻ramos aumentar胤a... pero es[n]muy grande, descongelarla llevar茨 mucho[n]tiempo.

[msg MSG_010 [Akechi]]
Si reacciona al olor, 夷por qu姻 no[n]cocinamos la carne?

[msg MSG_011 [Yukiko]]
S胤... 斡Eso es!

[msg MSG_012 [Teddie]]
斡Noooo! 斡夷No hay piedad para un oso en[n]este mundo?!

[msg MSG_013 [Akechi]]
Si reacciona al olor, 夷por qu姻 no[n]cocinamos la carne?

[msg MSG_014 [P3 Fem Protag]]
斡S胤! 斡Estoy segura de que ese dinosaurio[n]vendr茨 saltando hacia ese delicioso y[n]carnoso aroma!

[msg MSG_015 [Makoto]]
Hab胤a utensilios de cocina en el[n]congelador, quiz茨 deber胤amos usarlos.

[msg MSG_016 [Ryuji]]
Por cierto, 夷d吋nde vamos a cocinarla? No[n]he visto una cocina en esta selva.

[msg MSG_017 [Ann]]
Um... 夷En el cine?

[msg MSG_018 [Yosuke]]
斡No! Si les dejamos cocinar en un[n]espacio cerrado, 斡todos terminaremos[n]muertos!

[msg MSG_019 [Chie]]
斡Oye! 斡夷Qu姻 quieres decir con eso,[n]Yosuke?!

[msg MSG_020 [Yosuke]]
*jadeo* Bueno, ya sabes... U-uhhhh...

[sel SEL_021 top]
Cocinar en interiores es peligroso.
El Cine tampoco tiene cocina.

[msg MSG_022 [P4 Hero]]
Joker tiene un buen punto...
Considerando lo grande que es este[n]corte, ser胤a dif胤cil cocinarla en una[n]cocina normal.

[msg MSG_023 [Yosuke]]
斡S胤, eso! 斡Es demasiado peligroso[n]cocinar en interiores! Cocinarla fuera[n]ser茨 mucho m茨s f茨cil, y seguro...
斡Ser茨 m茨s f茨cil huir! Tambi姻n...

[msg MSG_024 [Akechi]]
Joker tiene raz吋n. No hab胤a nada de eso[n]en el cine...

[msg MSG_025 [Yosuke]]
斡S胤, s胤! Ni siquiera podemos hacer nada[n]all茨 de todos modos, as胤 que 夷por qu姻 no[n]la cocinamos al aire libre?
斡Ser茨 m茨s f茨cil huir! Tambi姻n...

[msg MSG_026 [Yusuke]]
Sin embargo, cocinar al aire libre es[n]peligroso, podr胤amos iniciar un incendio[n]forestal...

[msg MSG_027 [Makoto]]
En ese caso, tal vez deber胤amos hacerlo[n]cerca de un r胤o, para poder apagar el[n]fuego r茨pido si algo pasa.
Busquemos un lugar donde haya agua cerca[n]para cocinar.

