[msg MSG_000 [Yukiko]]
Eh, メQu〒 crees que sea eso?

[msg MSG_001 [Chie]]
Parece una mホquina, pero... No tengo ni idea.

[msg MSG_002 [Futaba]]
Mmm... No puedo verla desde aquボ.

[msg MSG_003 [Yukari]]
Podrボamos acercarnos mホs si encontramos otro camino. メPor qu〒 no buscamos uno?

[msg MSG_004 [Futaba]]
ムBuena idea, Yukari! Podrボa haber algo interesante en esa cosa... Hrghhh... ムMi curiosidad estホ aumentando!

