[msg MSG_000 [Rise]]
斡Esperen, chicos! 斡Estoy recibiendo[n]m雨ltiples lecturas fuertes tras esa[n]puerta!

[msg MSG_001 [Chie]]
斡夷Eh?! 夷Qu姻 tan fuertes? 斡夷Qu姻 hacemos?!

[msg MSG_002 [Futaba]]
...
Son parecidas a cuando nos encontramos[n]con [f 6 1 27 0 0 0], o el equipo de [f 6 1 12 0 0 0]...

[msg MSG_003 [Kanji]]
夷Los compa隠eros de [f 6 1 27 0 0 0] est茨n all胤?

[msg MSG_004 [Rise]]
No estoy segura, tambi姻n recibo otras[n]lecturas...

[msg MSG_005 [Morgana]]
Bueno, eso es preocupante...
Joker, 夷qu姻 hacemos? Reagruparnos antes[n]siempre es una opci吋n.

[msg MSG_006 [Morgana]]
No sabemos qu姻 hay adelante... 夷Estamos[n]listos?

[sel SEL_007 top]
Vamos.
Debemos reagruparnos.

[msg MSG_008 [Morgana]]
斡Bien, vamos a prepararnos y a entrar!

[msg MSG_009 [Morgana]]
Ah, buena decisi吋n.

