[msg MSG_000 [Yukari]]
Parece que llegamos a una nueva zona... ムY es enorme!
Tambi〒n hay robots por todas partes. Me pregunto cポmo mantienen esto...

[msg MSG_001 [Junpei]]
Bueno, son mホquinas que siguen ポrdenes, asボ que メdebe ser fホcil mantener esto limpio?

[msg MSG_002 [Yukari]]
ムYa lo s〒! Pero hay algo en general que me molesta...

[msg MSG_003 [Akechi]]
メTe preguntas por qu〒 se supone que es "normal" en este mundo, Takeba?

[msg MSG_004 [Yukari]]
ムSボ, eso! Quiero saber qui〒n programポ este estilo de vida para las mホquinas.

[msg MSG_005 [Ken]]
メQuizホs los humanos que hicieron a los robots?

[msg MSG_006 [Naoto]]
En las pelボculas de ciencia ficciポn, hay una especie de computadora madre que controla a la sociedad robポtica...

[msg MSG_007 [Ann]]
ムCreo que he oボdo hablar de eso! Normalmente, son el jefe final que el h〒roe debe derrotar.
Si recuerdo bien, estホn conectadas a todos los robots... O algo asボ.

[msg MSG_008 [Yosuke]]
Asボ que dices que hay una especie de lボder electrポnico... メEso no describe al Supervisor?

[msg MSG_009 [Chie]]
En ese caso, メno arreglarボamos la pelボcula si lo derrotホramos?
ムUn lボder que obliga a todo el mundo a ser igual estホ definitivamente equivocado!

[msg MSG_010 [Morgana]]
Suena como un plan. Estホ decidido, vamos a buscar al Supervisor.

[msg MSG_011]
Veo a Crow parado mientras los demホs avanzan...

[msg MSG_012 [Akechi]]
メUn mundo que sacrifica a unos pocos por la mayorボa, eh? Un enfoque autoritario, sin duda.

[msg MSG_013 [Akechi]]
...Joker, メquerボas decirme algo?
Nadie puede escucharnos, asボ que si quieres decirme algo, adelante.

[sel SEL_014 top]
Estホs actuando raro.
Esa es mi lボnea. メPasa algo?

[msg MSG_015 [Akechi]]
メEh? メTマ crees? No me di cuenta...
Puede que me est〒 poniendo algo nervioso este entorno sin darme cuenta.

[msg MSG_016 [Akechi]]
メEh? Nada en particular...
Puede que me est〒 poniendo algo nervioso este entorno sin darme cuenta.

[msg MSG_017 [Akechi]]
Bueno, supongo que esto significa que tengo mi propia opiniポn sobre este mundo. Es emocionante y lleno de misterio...
Mientras estamos aquボ, incluso podrボa…
No, no importa. Me asegurar〒 de mantenerme fuerte de ahora en adelante.

[sel SEL_018 top]
Sigue asボ.
Solo hazlo.

[msg MSG_019 [Akechi]]
...Supongo que deberボa agradecerte. Aprovechar〒 tus amables palabras ahora.

[msg MSG_020 [Akechi]]
Sigue asボ, メeh?...

[msg MSG_021 [Akechi]]
Lo siento. Gracias.

[msg MSG_022 [Yukari]]
ムOigan, ustedes dos! ムSi no vienen, se quedarホn atrホs!

[msg MSG_023 [Akechi]]
Bueno, ya la escuchaste. Debemos irnos, Joker.

