[msg MSG_000 [Fuuka]]
斡Oh! 斡Estoy recibiendo una se隠al enemiga[n]cerca! 斡Tengan cuidado!

[msg MSG_001 [P4 Hero]]
En ese caso, podr胤amos volver al Cine y[n]reagruparnos si es necesario.
夷Qu姻 hacemos? 夷Estamos listos?

[msg MSG_002 [Fuuka]]
Estoy recibiendo una se隠al enemiga.[n]夷Est茨s listo?

[sel SEL_003 top]
Estamos listos.
Volvamos.

[msg MSG_004 [Junpei]]
斡S胤, se隠or! 斡Lleg吋 la hora!

[msg MSG_005 [Ken]]
Cierto, qui姻n sabe que nos espera.[n]Deber胤amos tener cuidado, por si acaso.

