[msg MSG_000 [Fuuka]]
斡Estoy sintiendo una presencia poderosa[n]adelante! Por favor, tengan cuidado...

[msg MSG_001 [P3 Hero]]
Esa debe ser el 茨rea central donde[n]controlan a los robots, la sala de[n]comandos de la computadora madre.

[msg MSG_002 [Aigis]]
Creo que la probabilidad de una batalla[n]es extremadamente alta.
夷Entramos inmediatamente?

[msg MSG_003 [Aigis]]
Creo que tendremos una batalla. 夷Estamos[n]preparados?

[sel SEL_004 top]
斡Es hora del espect茨culo!
A雨n no.

[msg MSG_005 [Aigis]]
Entendido. 斡Vamos!

[msg MSG_006 [Aigis]]
Entendido. Estar姻 a la espera.

