[msg MSG_000 [Yosuke]]
斡Ack! 斡Otro robot!

[msg MSG_001 [Ryuji]]
斡Y estamos en un callej吋n sin salida![n]斡夷Qu姻 vamos a hacer?!

[msg MSG_002 [Mitsuru]]
La puerta que alterna entre abierta y[n]cerrada est茨 adelante...

[sel SEL_003 top]
Destruyamos ese FOE.
Llevemos al FOE all胤.

[msg MSG_004 [Akihiko]]
夷Qu姻, lo destruiremos con nuestros[n]pu隠os? En ese caso, d姻jamelo a m胤.

[msg MSG_005 [Shinjiro]]
Oye idiota, 斡no hay manera de que t雨 o[n]cualquiera de nosotros golpe a esa cosa[n]y viva para contarlo!

[msg MSG_006 [Naoto]]
U-um...
夷No se abrir胤a la puerta si llevamos al[n]FOE que nos sigue hacia esa puerta?

[msg MSG_007 [Akechi]]
Ah, Es una gran idea.
Si el FOE nos sigue a trav姻s de la[n]puerta, la puerta cerrada se abrir茨...[n]夷Ese es el plan?

[msg MSG_008 [Morgana]]
Definitivamente funcionaria. 斡Vamos a[n]intentarlo, Joker!

