[msg MSG_000 [Chie]]
ムメQu〒〒〒?!

[msg MSG_001 [Yukari]]
Oh, la puerta se abriポ.
...Espera, メPor qu〒 te asustas?

[msg MSG_002 [Chie]]
ムNo es eso! ムLa puerta detrホs de[n]nosotros, [f 0 1 2] s〒 cerro de repente[f 0 1 0]!

[msg MSG_003 [Yukari]]
Tienes razポn. Probablemente, hay algマn[n]tipo de patrポn en esto.

[msg MSG_004 [Ken]]
Tマ tambi〒n lo pensaste, メeh?[n]Probablemente, deberボamos seguir[n]movi〒ndonos por ahora.

