[msg MSG_000 [Rise]]
ムEsperen, chicos! ムEstoy recibiendo[n]mマltiples lecturas fuertes tras esa[n]puerta!

[msg MSG_001 [Chie]]
ムメEh?! メQu〒 tan fuertes? ムメQu〒 hacemos?!

[msg MSG_002 [Futaba]]
...
Son parecidas a cuando nos encontramos[n]con [f 6 1 27 0 0 0], o el equipo de [f 6 1 12 0 0 0]...

[msg MSG_003 [Kanji]]
メLos compaワeros de [f 6 1 27 0 0 0] estホn allボ?

[msg MSG_004 [Rise]]
No estoy segura, tambi〒n recibo otras[n]lecturas...

[msg MSG_005 [Morgana]]
Bueno, eso es preocupante...
Joker, メqu〒 hacemos? Reagruparnos antes[n]siempre es una opciポn.

[msg MSG_006 [Morgana]]
No sabemos qu〒 hay adelante... メEstamos[n]listos?

[sel SEL_007 top]
Vamos.
Debemos reagruparnos.

[msg MSG_008 [Morgana]]
ムBien, vamos a prepararnos y a entrar!

[msg MSG_009 [Morgana]]
Ah, buena decisiポn.

