[msg MSG_000 [Shinjiro]]
Oye, mira eso... Esa es un hacha bastante impresionante.

[msg MSG_001 [Yukiko]]
Sボ, y qu〒 cara tan aterradora tiene... メEstarホ molesto por algo?
Tenemos a Hikari con nosotros, asボ que serボa mejor tratar de evitar a los enemigos que puedan causarnos problemas.

[msg MSG_002 [Morgana]]
Entonces, メqu〒 hacemos ahora?

[sel SEL_003 top]
Usemos un cebo para alejarlo.
Pregunt〒mosle a Noir.

[msg MSG_004 [Yukiko]]
Sボ, funcionポ una vez, asボ que deberボamos intentarlo de nuevo.

[msg MSG_005 [P4 Hero]]
ムN-no! ...Deberボamos tener un plan mホs sポlido esta vez.
メPor qu〒 no le preguntamos a Noir, nuestra experta en hachas?

[msg MSG_006 [P4 Hero]]
Exacto. Ella usa un hacha, podrボa ser de ayuda con esto.

[msg MSG_007 [Haru]]
Bueno... las hachas tienen un alcance de ataque bastante corto, asボ que es mejor no acercarse demasiado.
Ademホs, un hacha tan grande seria extremadamente pesada, asボ que dudo que pueda balancearla, probablemente solo puede dar un golpe a la vez.

[msg MSG_008 [Yusuke]]
Entiendo... "No te acerques" y "Calcula bien su momento si te acercas" parecen ser las mejores tホcticas aquボ.

[msg MSG_009 [Yukiko]]
Su expresiポn[f 0 1 0] tambi〒n puede ser una pista マtil para saber cuando va a realizar un ataque.
メNo serホ mホs peligroso cuando estホ mホs enfadado?

[msg MSG_010 [Yusuke]]
Eso tendrボa sentido. Dejaremos que tマ decidas cuホndo esquivar, Joker.

