[msg MSG_000 [Yusuke]]
メHm? He visto un oso.

[msg MSG_001 [Teddie]]
ムHola! メMe llamaste?

[msg MSG_002 [Yusuke]]
Qu〒 increボble velocidad...

[msg MSG_003 [Teddie]]
ムJe, je, je! ムComo un oso inteligente,[n]soy capaz de responder rホpido!

[msg MSG_004 [Junpei]]
メHolaaaa, Teddie? Mira eso.

[msg MSG_005 [Teddie]]
メHrmm? ムメQu〒 es...?!

[msg MSG_006 [Teddie]]
Espera, ムメqu〒 es...?! ムメE-es un oso?!

[msg MSG_007 [Teddie]]
ムメY es increボblemente rホpido?!

[msg MSG_008 [Akihiko]]
Tiene el cuerpo de un peso pesado, pero[n]la agilidad de un peso pluma... ムQu〒[n]impresionante oponente!

[msg MSG_009 [Mitsuru]]
No importa lo rホpido que sea, [f 0 1 2]debe tener[n]algマn tipo de patrポn como los otros FOE[f 0 1 0].
Si observamos cuidadosamente su movimiento, no[n]deberボa suponer una amenaza para nosotros...[n]Buena suerte, Joker.

