[msg MSG_000 [Ken]]
Um... メPuedo decir algo?

[msg MSG_001 [Akihiko]]
メHm? メQu〒 pasa?

[msg MSG_002 [Ken]]
Bueno, ah... este, piso...
Si pulsamos el interruptor mientras[n]estamos en el ascensor, [f 0 1 2]メno nos llevarボa[n]a la planta de abajo[f 0 1 0]?

[sel SEL_003 top]
Es una gran idea.
メCrees que sea seguro?

[msg MSG_004 [Akechi]]
Cierto, podrボamos usarlo como las[n]escaleras. Creo que vale la pena[n]intentarlo.
Aunque, SI se detiene en el piso de[n]abajo. Podrボamos acabar descendiendo[n]para siempre...

[msg MSG_005 [Akechi]]
Es cierto que serボa estupendo si se conectara[n]con la siguiente planta, pero puede que[n]acabemos descendiendo para siempre...

[msg MSG_006 [Ken]]
ムメQ-qu〒?! ムNooo!

[msg MSG_007 [Akechi]]
...Ja, ja, solo bromeo. Si parece[n]sospechoso, deberボamos preguntarle a[n]nuestras navegadoras.

[msg MSG_008 [Rise]]
ムTenボa la sensaciポn de que dirボas eso, ya lo[n]hemos comprobado! ムNo te preocupes, se detiene[n]en el siguiente piso!

[msg MSG_009 [Ken]]
メEn serio? ムGracias a Dios!

[msg MSG_010 [Yosuke]]
Bueno, entonces, saltamos y…

[msg MSG_011 [Futaba]]
ムEspera! Serホ mejor marcar esto en su[n]mapa antes de girar las narices de los[n]ホrboles.
Moverse arriba y abajo probablemente[n]complicarホ el mapeo.

[msg MSG_012 [Yusuke]]
En ese caso, serボa mejor si tuvi〒ramos[n]un sボmbolo especボfico para esto.[n]Permボtanme diseワar uno...

[msg MSG_013 [Yosuke]]
ムGracias! ムEstホ hecho, vamos a probarlo,[n]Joker!

[msg MSG_ICON_SERI_OPEN]
Se ha aワadido un icono [f 0 1 2]Stage Lift[f 0 1 0] al[n]mapa de la pantalla inferior.
Si deseas comprobar cポmo utilizar este[n]icono...
Presiona [f 0 1 2]AYUDA[f 0 1 0] en la parte inferior[n]derecha del mapa y presiona [f 0 1 2]Tipos de[n]Iconos[f 0 1 0].

