[msg MSG_000 [Koromaru]]
ムBark! ムBark bark!

[msg MSG_001 [Ryuji]]
Qu〒 pasa, Koromaru…
ムメEh, qu〒 dem...?!

[msg MSG_002 [Chie]]
Hay un FOE...
ムBien hecho, Koro! Eres un buen chico.

[msg MSG_003 [Koromaru]]
ムGuau!

[msg MSG_004 [Ken]]
メMm? Pero si el FOE estホ aquボ,[n]メpodrボamos...?

[msg MSG_005 [Teddie]]
ムHeehee! [f 0 1 2]ムSi usamos el interruptor[n]correcto, serボa un adiポs para ese tipo[f 0 1 0]!
ムVamos! ムTengo ganas de encontrar ese[n]interruptor!

