[msg MSG_000 [Shinjiro]]
Oye, mira eso... Esa es un hacha[n]bastante impresionante.

[msg MSG_001 [Yukiko]]
Sボ, y qu〒 cara tan aterradora tiene...[n]メEstarホ molesto por algo?
Tenemos a Hikari con nosotros, asボ que[n]serボa mejor tratar de evitar a los[n]enemigos que puedan causarnos problemas.

[msg MSG_002 [Morgana]]
Entonces, メqu〒 hacemos ahora?

[sel SEL_003 top]
Usemos un cebo para alejarlo.
Pregunt〒mosle a Noir.

[msg MSG_004 [Yukiko]]
Sボ, funcionポ una vez, asボ que deberボamos[n]intentarlo de nuevo.

[msg MSG_005 [P4 Hero]]
ムN-no! ...Deberボamos tener un plan mホs[n]sポlido esta vez.
メPor qu〒 no le preguntamos a Noir,[n]nuestra experta en hachas?

[msg MSG_006 [P4 Hero]]
Exacto. Ella usa un hacha, podrボa ser de[n]ayuda con esto.

[msg MSG_007 [Haru]]
Bueno... las hachas tienen un alcance de[n]ataque bastante corto, asボ que es mejor[n]no acercarse demasiado.
Ademホs, un hacha tan grande seria[n]extremadamente pesada, asボ que dudo que pueda[n]balancearla, probablemente solo puede dar un[n]golpe a la vez.

[msg MSG_008 [Yusuke]]
Entiendo... "No te acerques si es posible" y[n]"Calcula bien el momento si es necesario[n]acercarte" parecen ser las mejores tホcticas[n]aquボ.

[msg MSG_009 [Yukiko]]
Su expresiポn[f 0 1 0] tambi〒n puede ser una pista[n]マtil para saber cuando va a realizar un[n]ataque.
メNo serホ mホs peligroso cuando estホ mホs[n]enfadado?

[msg MSG_010 [Yusuke]]
Eso tendrボa sentido. Dejaremos que tマ[n]decidas cuホndo esquivar, Joker.

