[msg MSG_000 [Yosuke]]
ムAh! メQu〒 es... este agujero?

[msg MSG_001 [Junpei]]
ムAmigo! メEse tronco... es una cara?!

[msg MSG_002 [Teddie]]
Y encima... メEs un Teddie?

[msg MSG_003 [Ryuji]]
ムNo tienes nada que ver con esto!

[msg MSG_004 [Naoto]]
No tengo ni idea para qu〒 es ese tronco,[n]pero podrボa ser algマn tipo de mecanismo[n]dentro de esta pelボcula...
Quizホs [f 0 1 2]esa nariz sea una especie de[n]interruptor[f 0 1 0].

[msg MSG_005 [P3 Hero]]
メNariz?

[msg MSG_006 [P4 Hero]]
メNariz?

[msg MSG_007 [P3 Fem Protag]]
メNariz? Es como...

[sel SEL_008 top]
Sボ.
Esa nariz larga.

[msg MSG_009 [Ryuji]]
ムメQu〒 demonios les pasa?! ムToda esta[n]charla sobre una nariz me estホ[n]asustando!

[msg MSG_010 [Naoto]]
Solo es una teorボa. Echemos un vistazo a[n]ese tronco, pero tengan cuidado con el[n]agujero.

