[msg MSG_000 [Ann]]
ムMira, enanos! ムSon tan lindos!

[msg MSG_001 [Fuuka]]
ムEspera, Panther! ムNo te acerques a ellos!

[msg MSG_002 [Ann]]
メEh?
ムAaaah!

[msg MSG_003 [Morgana]]
ムCuidado!

[msg MSG_004 [Morgana]]
ムAh! Eso estuvo cerca. メEstホs bien, Panther?

[msg MSG_005 [Ann]]
S-sボ... Gracias, Mona. Me salvaste el pellejo.

[msg MSG_006 [Morgana]]
ムメMiau?! ムE-e-eso fue nya-cosa!
Por ti, Panther, desafiarボa el fuego y el hielo... Viento y olas... ムEnanos con armas!

[msg MSG_007 [Yukari]]
ムBravo, Mona! Me sorprende que pudieras moverte tan rホpido. メSupongo que es gracias al poder del amor?
Debe haber sido aterrador acabar en el punto de mira tan de repente.

[msg MSG_008 [Akechi]]
Parecen [f 0 1 2]apuntar con sus armas a todo lo que se les ponga delante[f 0 1 0].
No podremos evitar una pelea si nos ven... Ten cuidado con esos tipos, Joker.

