[msg MSG_000 [Ann]]
ムMira, enanos! ムSon tan lindos!

[msg MSG_001 [Fuuka]]
ムEspera, Panther! ムNo te acerques a[n]ellos!

[msg MSG_002 [Ann]]
メEh?
ムAaaah!

[msg MSG_003 [Morgana]]
ムCuidado!

[msg MSG_004 [Morgana]]
ムAh! Eso estuvo cerca. メEstホs bien,[n]Panther?

[msg MSG_005 [Ann]]
S-sボ... Gracias, Mona. Me salvaste el[n]pellejo.

[msg MSG_006 [Morgana]]
ムメMiau?! ムE-e-eso fue nya-cosa!
Por ti, Panther, desafiarボa el fuego y[n]el hielo... Viento y olas... ムEnanos con[n]armas!

[msg MSG_007 [Yukari]]
ムBravo, Mona! Me sorprende que pudieras[n]moverte tan rホpido. メSupongo que es[n]gracias al poder del amor?
Debe haber sido aterrador acabar en el[n]punto de mira tan de repente.

[msg MSG_008 [Akechi]]
Parecen [f 0 1 2]apuntar con sus armas a todo lo[n]que se les ponga delante[f 0 1 0].
No podremos evitar una pelea si nos[n]ven... Ten cuidado con esos tipos,[n]Joker.

