[msg MSG_000 [Junpei]]
斡夷Ah?! 斡夷Qu姻 fue ese ruido?!

[msg MSG_001 [Akechi]]
夷Quiz茨s ese FOE [f 0 1 2]destruy吋 los escombros[f 0 1 0][n]de antes?

[msg MSG_002 [Fuuka]]
Lo comprobar姻. Veamos...

[msg MSG_003 [Fuuka]]
斡Incre胤ble! 斡Todos esos escombros[n]salieron volando!

[msg MSG_004 [Yosuke]]
Esa cosa es demasiado fuerte. Si nos[n]atrapa, estamos acabados...

[msg MSG_005 [Akechi]]
No te preocupes. Solo tenemos que[n]asegurarnos de mantenernos alerta.
Adem茨s, ahora sabemos que los [f 0 1 2]caminos[n]bloqueados pueden abrirse si hacemos uso[n]de ese FOE[f 0 1 0].
Cuando encontremos un camino obstruido[n]con escombros, podemos deshacernos de[n]ellos de la misma forma.

[msg MSG_006 [Morgana]]
Cierto. 斡Cuando llegue el momento,[n]aseg雨rate de atraer el FOE hacia los[n]escombros, Joker!

