[msg MSG_000 [Akechi]]
Joker, mira. Esta parte del suelo parece[n]tener alguna funciポn especial...
メCrees que... que deberボamos pisarlo?

[sel SEL_001 top]
Vamos a averiguarlo.
No lo s〒.

[msg MSG_002 [Akihiko]]
ムSボ, vamos!

[msg MSG_003 [Mitsuru]]
Detente, Akihiko.
No te metas con cosas que no entendemos.

[msg MSG_004 [Mitsuru]]
Parece sensato. No hay necesidad de[n]meterse con algo que tiene efectos[n]desconocidos.

[msg MSG_005 [Yukiko]]
Hmm... Pero aun asボ tengo curiosidad.[n]Tal vez tiene algo que ver con ese[n]dispositivo que vimos antes.

[msg MSG_005_5 [Yukiko]]
Oye, Chie, メpor qu〒 no intentamos saltar[n]sobre esto?

[msg MSG_006 [Chie]]
ムメEh?! Uhhhh... メNo crees que es una[n]mala idea?

[msg MSG_007 [Kanji]]
ムメY no nos acababan de decir que no[n]hici〒ramos eso?!

[msg MSG_008 [Yukiko]]
Sボ, pero... メNo te dan mホs ganas de[n]hacerlo? メO soy solo yo?

[msg MSG_009 [Akechi]]
Bueno... Si no encontramos otro camino,[n]supongo que podrボamos intentarlo.

[msg MSG_010 [Mitsuru]]
Es un buen punto. Joker, te dejaremos[n]las pruebas.

