[msg MSG_000 [Morgana]]
ムメMeow?! メS-se moviポ?

[msg MSG_001 [Futaba]]
ムEh, chicos!
ムEsa cosa estホ [f 0 1 2]copiando sus movimientos[f 0 1 0]!

[msg MSG_002 [Ryuji]]
ムメEh?! メQu〒 quieres decir con "copiar"?[n]ムEstホ haciendo lo contrario a nosotros!

[msg MSG_003 [Akechi]]
Bueno, en realidad, no es verdad.
Se ha invertido el punto de vista, no la[n]direcciポn. Por ejemplo, si nos ve y nos[n]movemos a la derecha...

[msg MSG_004 [Teddie]]
ムOhhh, ya veo, parecerホ que se moviポ a[n]la izquierda!

[msg MSG_005 [Ryuji]]
メEh? ムメNos estホ copiando?!
Entonces, メavanzamos y esa cosa hizo lo[n]mismo?

[msg MSG_006 [Akechi]]
Asボ parece. Creo que si nos dirigimos a[n]la derecha, se moverボa a su derecha,[n]y...

[msg MSG_007 [Teddie]]
ムDesde nuestro punto de vista, parecerホ[n]que se moviポ a la izquierda! Ya veo, ya[n]veo...

[msg MSG_008 [Chie]]
Uhhh...

[msg MSG_008_5 [Chie]]
No entiendo todo eso de "derecha significa[n]izquierda", pero mientras tengamos cuidado,[n]estaremos bien… ムメVerdad?!

[msg MSG_009 [Mitsuru]]
De hecho. Todo lo que debemos hacer es[n]observar sus movimientos a medida que[n]avanzamos. Te seguimos, Joker.

