[msg MSG_000 [Chie]]
メQu〒 es esto? Hay un montポn de basura[n]aquボ.

[msg MSG_001 [Naoto]]
メEs... todo basura? Esto es demasiado.

[msg MSG_001_1 [Kanji]]
Ugh, メQui〒n demonios deja toda esta[n]basura en medio de la carretera?

[msg MSG_001_2 [Makoto]]
Cruzar parece demasiado arriesgado. メHay[n]alguna forma de evitarlo?

[msg MSG_002 [Akihiko]]
メDeberボamos quitarla toda de en medio?[n]Podrボamos verlo como entrenamiento...

[msg MSG_003 [Shinjiro]]
Ahボ va el idiota de cerebro muscular de[n]nuevo... No te metas en esto. Estamos[n]tratando de llegar a una soluciポn real.

[msg MSG_004 [Aigis]]
Entonces, メla destruiremos?

[msg MSG_005 [Shinjiro]]
*jadeo* メTマ tambi〒n?

[msg MSG_006 [Naoto]]
Quizホ no sea la peor idea.
Serボa difボcil, incluso con nuestra[n]fuerza combinada, mover tantos[n]escombros...

[msg MSG_007 [Akechi]]
Tienes razポn, necesitarボamos algマn tipo[n]de maquinaria pesada. メHay algo cerca[n]que podamos usar?

[msg MSG_008 [Mitsuru]]
...No veo nada parecido por aquボ. Bueno,[n]busquemos en la zona e intentemos[n]encontrar otro m〒todo.
Ah, y serボa mejor anotar esto en el mapa[n]para mホs tarde, por si acaso.

[msg MSG_009 [Yusuke]]
Entonces diseワar〒 un sボmbolo especial[n]para ello. ムEste montポn de basura me ha[n]inspirado!

[msg MSG_ICON_CLASH_BLOCK_OPE]
Se ha aワadido un icono [f 0 1 2]Escombros[f 0 1 0] al mapa[n]en la pantalla inferior.
Si deseas comprobar cポmo utilizar este[n]icono...
Presiona [f 0 1 2]AYUDA[f 0 1 0] en la parte inferior[n]derecha del mapa y presiona [f 0 1 2]Tipos de[n]Iconos[f 0 1 0].

