[msg MSG_000 [Akechi]]
Joker, mira. Esta parte del suelo parece[n]tener alguna funci吋n especial...
夷Crees que... que deber胤amos pisarlo?

[sel SEL_001 top]
Vamos a averiguarlo.
No lo s姻.

[msg MSG_002 [Akihiko]]
斡S胤, vamos!

[msg MSG_003 [Mitsuru]]
Detente, Akihiko.
No te metas con cosas que no entendemos.

[msg MSG_004 [Mitsuru]]
Parece sensato. No hay necesidad de[n]meterse con algo que tiene efectos[n]desconocidos.

[msg MSG_005 [Yukiko]]
Hmm... Pero aun as胤 tengo curiosidad.[n]Tal vez tiene algo que ver con ese[n]dispositivo que vimos antes.

[msg MSG_005_5 [Yukiko]]
Oye, Chie, 夷por qu姻 no intentamos saltar[n]sobre esto?

[msg MSG_006 [Chie]]
斡夷Eh?! Uhhhh... 夷No crees que es una[n]mala idea?

[msg MSG_007 [Kanji]]
斡夷Y no nos acababan de decir que no[n]hici姻ramos eso?!

[msg MSG_008 [Yukiko]]
S胤, pero... 夷No te dan m茨s ganas de[n]hacerlo? 夷O soy solo yo?

[msg MSG_009 [Akechi]]
Bueno... Si no encontramos otro camino,[n]supongo que podr胤amos intentarlo.

[msg MSG_010 [Mitsuru]]
Es un buen punto. Joker, te dejaremos[n]las pruebas.

