[msg MSG_000 [Ann]]
斡Mira! 斡Un FOE!

[msg MSG_000_1 [Ann]]
Yo, uh... no quiero que se acerque a[n]nosotros. 夷Podemos salir de aqu胤?

[msg MSG_001 [Koromaru]]
斡Guau!

[msg MSG_002 [Aigis]]
No hay problema, Panther.
Koromaru dice: "[f 0 1 2]Es demasiado grande para[n]caber pasar. No hay necesidad de[n]preocuparse[f 0 1 0]".

[msg MSG_003 [Ann]]
Ah, 斡qu姻 alivio! Me hab胤a asustado por[n]un segundo...

[msg MSG_004 [Morgana]]
No te preocupes, Panther. 斡Si algo viene[n]tras de ti, te proteger姻!

[msg MSG_005 [Ann]]
Oh, no te preocupes. Gracias.

[msg MSG_006 [Yosuke]]
Whoa, ella lo hizo tan f茨cilmente... Eso[n]fue realmente impresionante.

[msg MSG_007 [Naoto]]
Ah, me preocupa algo sobre ese FOE...
Puede que avanzar no sea un problema[n]aqu胤, pero 夷no tendremos que esquivarlo[n]en alg雨n momento?

[msg MSG_008 [Koromaru]]
斡Arf arf!

[msg MSG_009 [Aigis]]
Koromaru dice: "[f 0 1 2]Debemos usar nuestro[n]terreno a nuestro favor[f 0 1 0]".

[msg MSG_010 [Naoto]]
Ya que Joker lleva el mapa, le dejaremos[n]la estrategia con ese FOE.

[msg MSG_010_5 [Naoto]]
夷Est茨s listo para seguir?

