[msg MSG_000 [Ann]]
Entonces... メPasポ algo?

[msg MSG_001 [Akihiko]]
Bueno, no parece que haya cambiado nada...

[sel SEL_002 top]
Pregunt〒mosle a Oracle.
El aire se siente diferente...

[msg MSG_003 [Futaba]]
OK, Un segundo. Mmm... Fuuka, Rise, メqu〒 opinan de esto?

[msg MSG_004 [Fuuka]]
Um... メCreo que el aire ha cambiado un poco?

[msg MSG_005 [Rise]]
Mmhm, yo tambi〒n lo siento. メQuizホs un [f 0 1 2]cambio en la direcciポn del viento[f 0 1 0]?

[msg MSG_006 [Akihiko]]
Bueno, メqu〒 hacemos ahora?

[msg MSG_007 [Akechi]]
...メPodrボa tener algo que ver con ese escudo de viento que vimos antes?

[msg MSG_007_1 [Akechi]]
Joker, メpor qu〒 no vamos a revisar eso de nuevo?

