[msg MSG_000 [Rise]]
メHm? Espera un segundo...
No sopla el viento en tu ubicaciポn, pero las lecturas me dicen que sボ. Qu〒 extraワo.

[msg MSG_001 [P3 Hero]]
メEs posible que esta pelボcula lo est〒 bloqueando?

[msg MSG_002 [Fuuka]]
Creo que tienes razポn. Esa pelボcula estホ actuando como un paraviento ahora mismo.
Eso significarボa que estarボas siendo jalado por el viento si no fuera por esa barrera...

[msg MSG_003 [Akechi]]
La pelボcula nos protege del viento, メeh? Podrボa ser mejor para nosotros dibujar esto en el mapa, por si acaso.

[msg MSG_004 [Yusuke]]
Entonces crear〒 un sボmbolo. Algo como...

[msg MSG_ICON_BLOCKWALL_OPEN]
Se ha aワadido un icono [f 0 1 2]Paraviento[f 0 1 0] al mapa de la pantalla inferior.
Si deseas comprobar cポmo utilizar este icono...
Presiona [f 0 1 2]AYUDA[f 0 1 0] en la parte inferior derecha del mapa y presiona [f 0 1 2]Tipos de Icono[f 0 1 0].

