[msg MSG_000 [Rise]]
斡Chicos, Enlil est茨 adelante! La se隠al[n]que recibo de ella es como si fuera el[n]centro de una tormenta...

[msg MSG_001 [P3 Hero]]
Bien... Lo logramos. 夷Listo, Joker?

[msg MSG_002 [P3 Hero]]
Enlil espera adelante. 夷Listo?

[sel SEL_003 top]
Vamos.
A雨n no.

[msg MSG_004 [P4 Hero]]
Bien. Prep茨rense...

[msg MSG_005 [P3 Fem Protag]]
斡S胤! 斡Tenemos que detener a Enlil!

[msg MSG_006 [P4 Hero]]
No hay problema. Ser茨 mejor que nos[n]preparemos tanto como podamos.

[msg MSG_007 [P3 Fem Protag]]
斡S胤! 斡No podemos perder, no importa qu姻!

