[msg MSG_000 [Yukari]]
メEh? Parece un callejポn sin salida.[n]Supongo que tendremos que encontrar otro[n]camino.

[msg MSG_001 [Ann]]
Qu〒 molestia, pero メqu〒 otra opciポn[n]tenemos?
*suspiro* Podrボa caminar eternamente si[n]estuviera de compras.

[msg MSG_002 [Yukari]]
Eso me recuerda, Panther. Trabajas como[n]modelo, メverdad?

[msg MSG_003 [Ann]]
Mhm, es solo un trabajo a tiempo[n]parcial. Siempre me ha encantado la[n]moda.
Hay algunas tiendas aquボ, asボ que ech〒[n]un vistazo rホpido cuando llegamos...
Pero toda la ropa de aquボ es, bueno...[n]demasiado para mボ.
Kamoshidaman estホ impreso en toda la[n]ropa. De ninguna manera me pondrボa eso.

[msg MSG_004 [Yukari]]
Ohh, Kamoshidaman es ese tipo con esa[n]gran sonrisa, メverdad?
Sボ, esa sonrisa es demasiado... Tampoco[n]creo que la usarボa.

[sel SEL_005 top]
Sボ, es aburrido.
Creo que es elegante.
Quiero una.

[msg MSG_006 [Ann]]
メVerdad? ムメTマ tambi〒n lo crees, Joker?!

[msg MSG_007 [Ann]]
Espera, ムメhablas en serio?!
Tal vez es popular aquボ, pero... メRopa[n]de Kamoshidaman?
ムUgh, no! ムSolo lo imagin〒, pero no[n]podrボa hacerlo! ムNo quiero esa cara en[n]mi cuerpo de ninguna manera!

[msg MSG_008 [Ann]]
ムメQu〒?! メHablas en serio?

[msg MSG_009 [Yukari]]
Bueno, todos tienen sus gustos... pero[n]si tuviera que usarla, tendrボa que ser[n]algマn tipo de reto.

[msg MSG_010 [P3 Fem Protag]]
メPero, quizホ es tan aburrida que en[n]realidad es genial?

[msg MSG_011 [Ann]]
No. Ninguna cantidad de aburrimiento va[n]a hacer que algo asボ est〒 bien.

[msg MSG_012 [Morgana]]
ムNo te preocupes, Panther!
ムEstoy seguro de que te verボas hermosa[n]incluso con ropa de Kamoshidaman!

[msg MSG_013 [Ann]]
Uh, no me refiero a eso. No me importa[n]si se me verボa bien o no.

[msg MSG_014 [Morgana]]
ムメMew?!

[msg MSG_015 [Yukari]]
Bueno, tendremos que dejar las compras[n]para despu〒s.
ムVamos, sigamos!

