[msg MSG_000 [Yosuke]]
Vaya, qu姻 vistas... Hay robots en todas[n]partes.

[msg MSG_001 [Junpei]]
Oh, eso me recuerda. Todos aqu胤 somos de[n]tiempos diferentes, 夷verdad?
Entonces, 夷significa que existe la[n]posibilidad de que el Jap吋n del futuro[n]se parezca a esto?

[sel SEL_002 top]
No.
Bastante la verdad.

[msg MSG_003 [Junpei]]
Espera, 斡夷en serio?!

[msg MSG_004 [Makoto]]
Claro que no.

[msg MSG_005 [P4 Hero]]
Considerando que saben qui姻n es Rise,[n]夷no significa que no son tan del futuro?

[msg MSG_006 [Junpei]]
Figuras...
*suspiro* Sab胤a que ser胤a as胤... Es un[n]poco decepcionante. Esperaba algo con un[n]poco m茨s misterioso.

[msg MSG_007 [Yukari]]
Bueno, si lo que quieres es misterio,[n]creo que la existencia de Aigis es[n]bastante interesante.

[msg MSG_008 [Junpei]]
S胤, pero estoy hablando de una ciudad[n]futurista.
Quiero un mundo de ciencia ficci吋n que[n]me haga sentir un ni隠o otra vez.

[msg MSG_009 [Ken]]
斡S姻 lo que quieres decir!

[msg MSG_009_1 [Ken]]
Oh, um... Quiero decir... me interesa la[n]雨ltima tecnolog胤a, no lo de ser un ni隠o[n]peque隠o.
斡Me refiero a cosas como robots gigantes[n]y robots!

[msg MSG_010 [Naoto]]
Oh, tambi姻n lo entiendo. Estoy...[n]bueno... algo interesada en la[n]maquinaria...

[msg MSG_011 [Futaba]]
Los intereses de todos pueden diferir un[n]poco, pero suena como si tuvieras[n]bastante inter姻s.

[msg MSG_011_1 [Futaba]]
だらゎまれろよ ぺ りゎま れまるウぺ ぽもわまるろもぽよ れも ろよぽよれ ゅよれ[n]ゎれゎぺるもよれ ぽま はまるれよょぺ ぺみもぼもよょぺぽよれ ぺ ゅぺ ぼもまょぼもぺ[n]みもぼぼもカょ めもぼもまるぺょ ゎょぺ らまりゎまォぺ るまゎょもカょテ

[msg MSG_012 [Makoto]]
Me parece que ser胤a muy intensa. No creo[n]que fuera capaz de seguir la[n]conversaci吋n...
M茨s importante, esto parece un callej吋n[n]sin salida. Probemos otro camino.

[msg MSG_0000 [Yosuke]]
Vaya, qu姻 vistas... Hay robots en todas[n]partes.

[msg MSG_0001 [Junpei]]
Oh, eso me recuerda. Todos aqu胤 somos de[n]tiempos diferentes, 夷verdad?
Entonces, 夷significa que existe la[n]posibilidad de que el Jap吋n del futuro[n]se parezca a esto?

[sel SEL_0002 top]
No.
Bastante la verdad.

[msg MSG_0003 [Junpei]]
Espera, 斡夷en serio?!

[msg MSG_0004 [Makoto]]
Claro que no.

[msg MSG_0005 [P4 Hero]]
Considerando que saben qui姻n es Rise,[n]夷no significar胤a que nuestros tiempos no[n]son tan distantes?

[msg MSG_0006 [Junpei]]
Figuras...
*jadeo* Supuse que ser胤a as胤... Un poco[n]decepcionante. Esperaba algo un poco m茨s[n]misterioso.

[msg MSG_0007 [Yukari]]
Bueno, si quieres misterio, creo que la[n]existencia de Aigis es bastante[n]misteriosa.

[msg MSG_0008 [Junpei]]
S胤, pero estoy hablando m茨s de una[n]ciudad futurista.
Quiero un mundo de ciencia ficci吋n que[n]me haga sentir como un ni隠o.

[msg MSG_0009 [Ken]]
斡Entiendo a lo que te refieres!

[msg MSG_0009_1 [Ken]]
Oh, um... Quiero decir... me interesa la[n]雨ltima tecnolog胤a, no lo de ser un ni隠o[n]peque隠o.
斡Me refiero a cosas como robots gigantes[n]y robots!

[msg MSG_0010 [Naoto]]
Oh, tambi姻n lo entiendo. Estoy...[n]bueno... algo interesada en la[n]maquinaria...

[msg MSG_0011 [Futaba]]
Los intereses de todos pueden diferir un[n]poco, pero suena como si tuvieras[n]bastante inter姻s.

[msg MSG_0011_1 [Futaba]]
だらゎまれろよ ぺ りゎま れまるウぺ ぽもわまるろもぽよ れも ろよぽよれ ゅよれ[n]ゎれゎぺるもよれ ぽま はまるれよょぺ ぺみもぼもよょぺぽよれ ぺ ゅぺ ぼもまょぼもぺ[n]みもぼぼもカょ めもぼもまるぺょ ゎょぺ らまりゎまォぺ るまゎょもカょテ

[msg MSG_0012 [Makoto]]
Me parece que ser胤a muy intensa. No creo[n]que fuera capaz de seguir la[n]conversaci吋n...
M茨s importante, esto parece un callej吋n[n]sin salida. Probemos otro camino.

