[msg MSG_000 [Chie]]
Ah, ムメOtro callejポn sin salida?!
メPor qu〒 este lugar es tan complicado?[n]ムTodos estos cines me hacen sentir[n]perdida!

[msg MSG_001 [Yusuke]]
Y mientras hablamos, estos cines estホn[n]llenos de personas viendo estas[n]pelボculas negativas...

[msg MSG_002 [Chie]]
Hay algo que me he estado preguntando[n]desde qu〒 llegamos a este distrito del[n]cine...

[msg MSG_003 [Ryuji]]
メQu〒?

[msg MSG_004 [Chie]]
Considerando cuホntos cines hay... メCrees[n]que en alguno de ellos est〒n mostrando[n]una pelボcula sobre kung-fu?
ムY si entrara en esa pelボcula, メpodrボa[n]realizar acrobacias impresionantes?!

[msg MSG_005 [P4 Hero]]
Oh... Me preguntaba lo mismo.

[msg MSG_006 [Ann]]
ムメTマ tambi〒n?!

[msg MSG_007 [Kanji]]
Entonces, メcrees que hay otra pelボcula[n]que tenga un montポn de... cosas[n]adorables y lindas?

[msg MSG_008 [Shinjiro]]
ムOoh! Bueno, yo me preguntaba...

[msg MSG_009 [Junpei]]
ムJa, te atrap〒! ムNo puedo creer que ESA[n]sea la pelボcula a la que quieres entrar!
En mi caso, ムquiero entrar en una pelボcula[n]deportiva! ムSerボa un jugador de la liga[n]superguapo y podrボa mostrar mis habilidades!

[msg MSG_010 [Yusuke]]
En ese caso, deseo entrar en una[n]pelボcula rebosante de obras de arte y[n]comida deliciosa.

[msg MSG_011 [Akechi]]
ムJa, ja, todos son tan abiertos con sus[n]deseos!
Pero, considerando cポmo funcionan las[n]pelボculas aquボ, incluso si logrホramos[n]encontrarlas, dudo que vi〒ramos lo que[n]queremos.

[msg MSG_012 [P3 Hero]]
メEn qu〒 clase de pelボcula te gustarボa[n]entrar, Crow?

[msg MSG_013 [Akechi]]
Creo que me gustarボa entrar en una de[n]misterio.
Como Prボncipe Detective, estoy interesado en[n]resolver casos difボciles, incluso en una[n]pelボcula... メNo te gustarボa, Shirogane?

[msg MSG_014 [Naoto]]
Sボ, tengo curiosidad sobre los[n]artilugios y planes que solo podrボa[n]haber en una pelボcula.

[msg MSG_015 [Yosuke]]
Serボas la estrella, Naoto. Una detective[n]disfrazada de hombre es perfecta para[n]una historia de detective.
Y luego, te enamoras de un amor[n]prohibido: ムun forajido con un pasado[n]impactante! メQu〒 te parece?

[msg MSG_016 [Naoto]]
ムYo... yo nunca me enamorarボa de alguien[n]asボ! ムArrestarボa a todos y cada uno de[n]esos forajidos!

[msg MSG_017 [Hikari]]
*risa* Serボa divertido ver todas esas[n]pelボculas.
Creo que convertir la vida cotidiana en[n]una pelボcula tambi〒n serボa interesante.
Solo ver a la gente vivir su vida al[n]mホximo puede ser alentador.

[msg MSG_018 [Junpei]]
ムOh, le diste en el clavo, Hikari!
ムRealmente tengo que llevar mi juego a un[n]nivel mホs alto para conquistar el corazポn de[n]Hikari como un jugador de las grandes ligas!

[msg MSG_019 [Futaba]]
ムVamos, mantengamos esa energボa mientras[n]avanzamos!

[msg MSG_020 [Hikari]]
ムSボ!

