[msg MSG_000 [Chie]]
Ah, 斡夷Otro callej吋n sin salida?!
夷Por qu姻 este lugar es tan complicado?[n]斡Todos estos cines me hacen sentir[n]perdida!

[msg MSG_001 [Yusuke]]
Y mientras hablamos, estos cines est茨n[n]llenos de personas viendo estas[n]pel胤culas negativas...

[msg MSG_002 [Chie]]
Hay algo que me he estado preguntando[n]desde qu姻 llegamos a este distrito del[n]cine...

[msg MSG_003 [Ryuji]]
夷Qu姻?

[msg MSG_004 [Chie]]
Considerando cu茨ntos cines hay... 夷Crees[n]que en alguno de ellos est姻n mostrando[n]una pel胤cula sobre kung-fu?
斡Y si entrara en esa pel胤cula, 夷podr胤a[n]realizar acrobacias impresionantes?!

[msg MSG_005 [P4 Hero]]
Oh... Me preguntaba lo mismo.

[msg MSG_006 [Ann]]
斡夷T雨 tambi姻n?!

[msg MSG_007 [Kanji]]
Entonces, 夷crees que hay otra pel胤cula[n]que tenga un mont吋n de... cosas[n]adorables y lindas?

[msg MSG_008 [Shinjiro]]
斡Ooh! Bueno, yo me preguntaba...

[msg MSG_009 [Junpei]]
斡Ja, te atrap姻! 斡No puedo creer que ESA[n]sea la pel胤cula a la que quieres entrar!
En mi caso, 斡quiero entrar en una pel胤cula[n]deportiva! 斡Ser胤a un jugador de la liga[n]superguapo y podr胤a mostrar mis habilidades!

[msg MSG_010 [Yusuke]]
En ese caso, deseo entrar en una[n]pel胤cula rebosante de obras de arte y[n]comida deliciosa.

[msg MSG_011 [Akechi]]
斡Ja, ja, todos son tan abiertos con sus[n]deseos!
Pero, considerando c吋mo funcionan las[n]pel胤culas aqu胤, incluso si logr茨ramos[n]encontrarlas, dudo que vi姻ramos lo que[n]queremos.

[msg MSG_012 [P3 Hero]]
夷En qu姻 clase de pel胤cula te gustar胤a[n]entrar, Crow?

[msg MSG_013 [Akechi]]
Creo que me gustar胤a entrar en una de[n]misterio.
Como Pr胤ncipe Detective, estoy interesado en[n]resolver casos dif胤ciles, incluso en una[n]pel胤cula... 夷No te gustar胤a, Shirogane?

[msg MSG_014 [Naoto]]
S胤, tengo curiosidad sobre los[n]artilugios y planes que solo podr胤a[n]haber en una pel胤cula.

[msg MSG_015 [Yosuke]]
Ser胤as la estrella, Naoto. Una detective[n]disfrazada de hombre es perfecta para[n]una historia de detective.
Y luego, te enamoras de un amor[n]prohibido: 斡un forajido con un pasado[n]impactante! 夷Qu姻 te parece?

[msg MSG_016 [Naoto]]
斡Yo... yo nunca me enamorar胤a de alguien[n]as胤! 斡Arrestar胤a a todos y cada uno de[n]esos forajidos!

[msg MSG_017 [Hikari]]
*risa* Ser胤a divertido ver todas esas[n]pel胤culas.
Creo que convertir la vida cotidiana en[n]una pel胤cula tambi姻n ser胤a interesante.
Solo ver a la gente vivir su vida al[n]m茨ximo puede ser alentador.

[msg MSG_018 [Junpei]]
斡Oh, le diste en el clavo, Hikari!
斡Realmente tengo que llevar mi juego a un[n]nivel m茨s alto para conquistar el coraz吋n de[n]Hikari como un jugador de las grandes ligas!

[msg MSG_019 [Futaba]]
斡Vamos, mantengamos esa energ胤a mientras[n]avanzamos!

[msg MSG_020 [Hikari]]
斡S胤!

