[msg MSG_000 [Ryuji]]
Supongo que no podemos ir por aquボ.
Hay dibujos en todas las paredes. メCポmo se llama a eso?

[msg MSG_001 [Akechi]]
Creo que la palabra que buscas es "graffiti". A menudo se relaciona con la disminuciポn de la seguridad pマblica.

[msg MSG_001_1 [Akechi]]
Sin embargo, マltimamente, algunos los han reconocido como arte. He oボdo que incluso se han realizado exposiciones.
Supuestamente, cuando un artista encuentra obras de arte que consideran peores que las suyas, pintan sobre ella.

[msg MSG_002 [Morgana]]
Entonces, メesto tambi〒n es arte? No lo entiendo...

[msg MSG_003 [Yusuke]]
Independientemente de cポmo sea el arte de cada uno, pintar sobre la obra de otro sin su permiso me parece una falta de respeto...
Pero tal vez sea asボ como se enfrentan...

[msg MSG_004 [Akechi]]
Ah, sボ, supongo que es una forma de verlo. Imagino que es una regla entre esos artistas.

[msg MSG_005 [Yusuke]]
Eso sin duda harボa que otros estuvieran ansiosos por demostrar sus habilidades. Entonces, tal vez yo tambi〒n deberボa...

[sel SEL_006 top]
No lo hagas.
Vamos.

[msg MSG_007 [Futaba]]
Tiene razポn, Inari. No tenemos tiempo, asボ que contrポlate.

[msg MSG_008 [Yusuke]]
Argh...

[msg MSG_009 [Yusuke]]
Muy bien, entonces... Supongo que tendr〒 que dejarlo para otra ocasiポn.

