[msg MSG_000 [Morgana]]
Un callej吋n sin salida... Solo un mont吋n[n]de publicidad sobre pel胤culas.

[msg MSG_001 [Hikari]]
斡Oh, esa pel胤cula!

[msg MSG_002 [Ann]]
夷La conoces, Hikari? 夷Es famosa?

[msg MSG_003 [Hikari]]
No realmente... Me recuerda a una[n]pel胤cula que me encanta...

[msg MSG_004 [Ryuji]]
夷Ah s胤? 夷Qu姻 la hace tan buena?

[msg MSG_005 [Hikari]]
Es dif胤cil de explicar, pero es una[n]pel胤cula en la que el director fue muy[n]detallista.
La m雨sica y la direcci吋n art胤stica[n]tambi姻n son excelentes. La pel胤cula es[n]realmente conmovedora.
No tiene famosos o efectos especiales[n]caros...
Pero esa pel胤cula me mostr吋 c吋mo no[n]necesitas depender de esas cosas para[n]tocar el coraz吋n de la audiencia.

[msg MSG_006 [P3 Fem Protag]]
斡Vaya, debe ser muy buena! Quiero verla[n]tambi姻n.

[msg MSG_007 [Yosuke]]
Las pel胤culas deben ser entretenidas,[n]como esa que describi吋 Hikari…
Pero todas estas pel胤culas son...[n]realmente deprimentes.

[msg MSG_008 [Ann]]
Quiero apresurarme y hacer que todos[n]recuerden que las pel胤culas no deben ser[n]como est茨s.
Tenemos que detener a Enlil antes de que[n]sea tarde.

[msg MSG_009 [Hikari]]
Mmhm. S胤, s姻 que ver pel胤culas hace que[n]sea m茨s f茨cil lidiar con la realidad...
Pero todas las personas deber胤an[n]esforzarse por tratar de salir de aqu胤.

[msg MSG_010 [Morgana]]
Incluy姻ndonos. 斡Vamos!

