[msg MSG_000 [Naoto]]
Parece un callejポn sin salida.[n]Deberボamos regresar.

[msg MSG_001 [Teddie]]
Un paso mホs, y mi espalda estarホ[n]hecha... hora de un descanso.

[msg MSG_002 [Yosuke]]
Si te cansas tan rホpido, tu salario[n]nunca va a subir.

[msg MSG_003 [Teddie]]
ムEstoy cansado de trabajar, estoy cansado de[n]ir al gimnasio, y esto es algo que[n]definitivamente no puedo manejar!

[msg MSG_004 [Yosuke]]
Sheesh... Serボa bueno que encontraras[n]otro trabajo a tiempo parcial que puedas[n]manejar.
Hay muchos robots aquボ. Quizホs Junes[n]podrボa contratar a uno...

[msg MSG_005 [Teddie]]
ムE-espera, Yosuke! Tマ no... No vas a[n]abandonarme aquボ, メverdad?

[msg MSG_005_1 [Teddie]]
Ohhh, qu〒 cruel... メHas estado jugado[n]conmigo todo este tiempo y ahora[n]simplemente me abandonas...?

[msg MSG_006 [Yosuke]]
ムNo lo digas asボ!

[msg MSG_007 [Fuuka]]
*risa* Tambi〒n tengo curiosidad por[n]estos robots.
Las tareas tan detalladas que hacen[n]requerirボan una tecnologボa muy avanzada.[n]Me pregunto como es su IA...

[msg MSG_008 [Futaba]]
メT-te gustan ese tipo de cosas?

[msg MSG_009 [Fuuka]]
Mm, bueno me gusta jugar con las[n]mホquinas y eso...

[msg MSG_010 [Futaba]]
Ooh, ムEres especialista en hardware! Yo[n]soy mホs de una chica de software...
ムApuesto que, si trabajホramos juntas,[n]podrボamos crear un Robot Featherman de[n]tamaワo real!

[msg MSG_011 [Fuuka]]
ムSuena divertido! Estoy segura de que[n]podrボamos agregar un montポn de[n]funciones...

[msg MSG_012 [Futaba]]
Mmm... ムPrimero deberボamos aspirar a[n]100.000 caballos de fuerza! ムPodrボamos[n]aワadir una funciポn de transformaciポn!

[msg MSG_013 [Makoto]]
Parece que se llevan bien.

[msg MSG_014 [Ryuji]]
Si las dejamos, van a hablar para[n]siempre. Deberボamos detenerlas y seguir[n]avanzando.

[msg MSG_0000 [Naoto]]
Parece un callejポn sin salida.[n]Deberボamos regresar.

[msg MSG_0001 [Teddie]]
Un paso mホs, y mi espalda estarホ[n]hecha... hora de un descanso.

[msg MSG_0002 [Yosuke]]
Si te cansas tan rホpido, tu salario[n]nunca va a subir.

[msg MSG_0003 [Teddie]]
ムEstoy cansado de trabajar, estoy cansado de[n]ir al gimnasio, y esto es algo que[n]definitivamente no puedo manejar!

[msg MSG_0004 [Yosuke]]
Sheesh... Serボa bueno que encontraras[n]otro trabajo a tiempo parcial que puedas[n]manejar.
Hay muchos robots aquボ. Quizホs Junes[n]podrボa contratar a uno...

[msg MSG_0005 [Teddie]]
ムE-espera, Yosuke! Tマ no... No vas a[n]abandonarme aquボ, メverdad?

[msg MSG_0005_1 [Teddie]]
Ohhh, qu〒 cruel... メHas estado jugado[n]conmigo todo este tiempo y ahora[n]simplemente me abandonas...?

[msg MSG_0006 [Yosuke]]
ムNo lo digas asボ!

[msg MSG_0007 [Fuuka]]
*risa* Tambi〒n tengo curiosidad por[n]estos robots.
Las tareas tan detalladas que hacen[n]requerirボan una tecnologボa muy avanzada.[n]Me pregunto como es su IA...

[msg MSG_0008 [Futaba]]
メT-te gustan ese tipo de cosas?

[msg MSG_0009 [Fuuka]]
Mm, bueno me gusta jugar con las[n]mホquinas y eso...

[msg MSG_0010 [Futaba]]
Ooh, ムEres especialista en hardware! Yo[n]soy mホs de una chica de software...
ムApuesto que, si trabajホramos juntas,[n]podrボamos crear un Robot Featherman de[n]tamaワo real!

[msg MSG_0011 [Fuuka]]
ムSuena divertido! Estoy segura de que[n]podrボamos agregar un montポn de[n]funciones...

[msg MSG_0012 [Futaba]]
Mmm... ムPrimero deberボamos aspirar a[n]100.000 caballos de fuerza! ムPodrボamos[n]aワadir una funciポn de transformaciポn!

[msg MSG_0013 [Makoto]]
Parece que se llevan bien.

[msg MSG_0014 [Ryuji]]
Si las dejamos, van a hablar para[n]siempre. Deberボamos detenerlas y seguir[n]avanzando.

