[msg MSG_000 [Yusuke]]
...夷Un callej吋n sin salida? Bueno, quiz茨[n]podamos tomar un descanso, tengo hambre.

[msg MSG_001 [Ryuji]]
Oh, matar胤a por algo de ramen ahora[n]mismo...

[msg MSG_002 [Chie]]
Hrgh... Pensar en eso tan de repente me[n]dio hambre...

[msg MSG_003 [Junpei]]
つゅ るぺゆまょ まれ ゎょ らゅぺぼまる ぼゎゅらよれよデ まょ るまぺゅもぽぺぽテ つれ[n]ぽま まれよれ ぺゅもゆまょろよれ ぽもぺほカゅもぼよれ りゎま ぽま るまらまょろま[n]ぺょめまゅぺれ ぽま ゅぺ ょぺぽぺテテテ
とゆぺむもょぺ まれよれ みもぽまよれ ゆまんぼゅァょぽよれま ぼよょ まゅ ぺぼまもろま[n]ぽま ぺゃよ ゅもむまるぺゆまょろま ろよれろぺぽよ を まゅ ぼぺゅぽよ ゆもまょろるぺれ[n]ゅよ れよるほまれ ろよぽよテテテ ィっまゅもぼもよれよ!

[msg MSG_004 [Yusuke]]
Ahora estoy a雨n m茨s hambriento. Ser茨[n]mejor que te hagas responsable de eso.

[msg MSG_005 [Junpei]]
Bieen. Te invitar姻 un taz吋n cuando[n]salgamos de aqu胤.

[msg MSG_006 [Yusuke]]
斡夷Una invitaci吋n...?! 斡Ir姻 incluso si[n]tengo que arrastrarme, as胤 que esp姻rame!

[msg MSG_007 [Yosuke]]
Oh, est茨 desesperado...
Pero, ir a comer ramen con ustedes suena[n]genial. Iremos juntos cuando esto[n]termine, 夷de acuerdo?

[msg MSG_008 [Ryuji]]
Bueno, ahora que tenemos algo que[n]esperar, 斡Vamos!

