[msg MSG_000 [Rise]]
Es un callej吋n sin salida. 斡Parece un[n]buen momento para descansar!

[msg MSG_001 [Ryuji]]
Awright...
Sabes, he estado pensando, pero 夷no es[n]una locura que estemos hablando con[n]Risette?

[sel SEL_002 top]
Es una locura.
夷T雨 crees?
Ya me acostumbre.

[msg MSG_003 [Ryuji]]
夷Verdad? Incluso tiene una persona...

[msg MSG_004 [Ryuji]]
夷Qu姻 quieres decir con "t雨 crees"?[n]斡Estamos hablando de la idol Risette!

[msg MSG_005 [Ryuji]]
斡Como si eso importara! 斡Estamos[n]hablando de la idol Risette!

[msg MSG_006 [Kanji]]
夷No est茨s demasiado emocionado? No es[n]nada fuera de lo com雨n.

[msg MSG_007 [Ryuji]]
斡No hay nada de com雨n en esto! 夷C吋mo[n]puedes pensar eso?

[msg MSG_008 [Futaba]]
Entiendo c吋mo te sientes, Skull, pero tu[n]fanatismo est茨 empezando a ser molesto.

[msg MSG_009 [Ryuji]]
斡Vamos! 斡Al menos d姻jame disfrutar de[n]esto!

[msg MSG_010 [Morgana]]
斡Oye, Skull! 斡Ya tenemos la Panther la[n]supermodelo en nuestro equipo! No te has[n]olvidado de ella, 夷verdad?

[msg MSG_011 [Ryuji]]
Uh, no es como si lo hubiera olvidado.[n]Solo que la conozco desde la secundaria,[n]as胤 que no es lo mismo...

[msg MSG_012 [Yosuke]]
斡Ohh, te entiendo! 斡Es importante[n]mantenerlo fresco!

[msg MSG_013 [Ann]]
Oye, Skull. Creo que t雨 y yo necesitamos[n]hablar.

[msg MSG_014 [Rise]]
Lo mismo va para ti, Yosuke.

[msg MSG_015 [Ryuji]]
斡夷Eh?! 斡S-solo bromeaba...!

[msg MSG_016 [Yosuke]]
S-s胤, no lo dec胤amos de esa forma... Ja,[n]ja, ja...

[msg MSG_017 [Morgana]]
Mm... Estos dos no tienen esperanza.

