[msg MSG_000 [Fuuka]]
Parece un callej吋n sin salida. 夷Por qu姻[n]no tomamos un descanso?

[msg MSG_001 [P3 Fem Protag]]
斡S胤!
Mientras caminaba estaba mirando todos[n]estos carteles de pel胤culas, mi cuello[n]me est茨 empezando a doler.

[msg MSG_002 [Haru]]
A m胤 tambi姻n. Es dif胤cil no mirarlos[n]cuando hay tantos.

[msg MSG_003 [Hikari]]
夷Qu姻 clase de pel胤culas ves? 夷Has visto[n]alguna recientemente?

[msg MSG_004 [Yosuke]]
Mi compa隠ero y yo vimos esta pel胤cula[n]llamada "Loan of the Ring" que era[n]bastante divertida.
La trama era una locura. Se trataba de[n]unos tipos arriesgando sus vidas para[n]poder pagar sus anillos de compromiso.

[msg MSG_005 [P4 Hero]]
Estuvo bien. Incluso me inspir吋 a ser[n]m茨s valiente.

[msg MSG_006 [Mitsuru]]
Veamos... La pel胤cula rom茨ntica que vi[n]recientemente fue bastante interesante.

[msg MSG_007 [Shinjiro]]
...夷T雨? 夷Una pel胤cula rom茨ntica?

[msg MSG_008 [Mitsuru]]
斡夷Qu姻?! 夷Qu姻 tiene raro eso?
No es raro que yo vea algo rom茨ntico,[n]夷verdad?

[msg MSG_009 [Akihiko]]
No es extra隠o, pero dif胤cil de imaginar.[n]No estabas interesada en esas cosas[n]antes.

[msg MSG_010 [Mitsuru]]
夷En serio? Son sorprendentemente[n]entretenidas.
Las personas esclavas del amor a menudo[n]dejan que sus emociones las dominen y[n]toman decisiones irracionales.
Hay mucho que no entiendo... Pero ver[n]personas con las que no me identifico es[n]bastante divertido.

[msg MSG_011 [Yosuke]]
Es una forma de verlas...

[msg MSG_012 [Hikari]]
*るもれぺ* ぢるまよ りゎま まゅ めまぼめよ ぽま りゎま ぺゅむゎもまょ らゎまぽぺ[n]ぽもれみるゎろぺる ぽま まゅゅぺれ ぽま まれぺ ゆぺょまるぺ まれ らぺるろま ぽま[n]ゅよ りゎま ゅぺれ めぺぼま ろぺょ むまょもぺゅまれテ
Las pel胤culas te permiten experimentar[n]cosas que normalmente no puedes y ver[n]los valores de otra persona.
Dependiendo de c吋mo la veas, hay muchas[n]formas de disfrutar una pel胤cula.

[msg MSG_013 [Akihiko]]
Entiendo. Es verdad que es importante[n]aprender sobre valores y mundos[n]diferentes al nuestro.

[msg MSG_014 [P3 Fem Protag]]
Bueno, 夷te gustar胤a ver una conmigo,[n]Akihiko? 斡Conozco la pel胤cula rom茨ntica[n]perfecta!

[msg MSG_015 [Shinjiro]]
...Nah, eso ser胤a imposible para Aki.[n]Apuesto a que se quedar胤a dormido.

[msg MSG_016 [Akihiko]]
夷Qu姻? Eso no es...
...Bueno, tal vez tengas raz吋n.

[msg MSG_017 [Mitsuru]]
Lo imaginaba.
...Bueno, terminemos esta peque隠a[n]charla. Tenemos que seguir avanzando.

