[msg MSG_000 [Morgana]]
Un callej吋n sin salida, 夷eh? *suspiro*[n]Me estoy cansando de ver a Kamoshidaman[n]por todas partes...

[msg MSG_001 [Ryuji]]
No es broma, tambi姻n me est茨[n]molestando... 夷Viste esas se隠ales en el[n]camino?
Todas lo elogiaban. Qu姻 espeluznante...

[msg MSG_002 [Ann]]
Sheesh, 夷por qu姻 tuviste que sacar ese[n]tema? He estado tratando de no mirarlos.

[msg MSG_003 [Ryuji]]
斡夷Eh?! Est茨n por toda la maldita[n]ciudad... No puedo evitar pensar en el[n]Palacio de Kamoshida.

[msg MSG_004 [Ann]]
Lo s姻. 夷Por qu姻 no los hacemos[n]desaparecer?

[msg MSG_005 [Morgana]]
夷C吋mo hacemos eso?

[msg MSG_006 [Ann]]
斡Los quemamos todos!

[msg MSG_006_1 [Ann]]
斡Vamos, Carmen!

[msg MSG_007 [Ryuji]]
Ooh, 斡gran idea! 斡D姻jame ayudar!

[msg MSG_007_1 [Ryuji]]
Vamos, Capit茨n…

[msg MSG_008 [Morgana]]
斡Oye! 斡夷Qu姻 crees que est茨s haciendo?!

[sel SEL_009 top]
C茨lmate.
D姻jame ayudar.

[msg MSG_010 [Akechi]]
Joker tiene raz吋n. No queremos llamar la[n]atenci吋n.

[msg MSG_011 [Akechi]]
夷T雨 tambi姻n, Joker...? Tranquilo. No[n]queremos llamar la atenci吋n.

[msg MSG_012 [Morgana]]
S姻 qu姻 pas吋 mucho entre Kamoshida y[n]t雨...
Y estoy seguro de que no es f茨cil[n]olvidar lo que hizo tampoco, pero[n]Kamoshidaman no es real.

[msg MSG_013 [Ann]]
Mm, lo siento... Pensar en ello me[n]irrita. Tengo que calmarme.

[msg MSG_014 [Ryuji]]
S胤, lo siento... Rescatar a Queen y Noir[n]es m茨s importante ahora.

[msg MSG_015 [Futaba]]
斡As胤 es! 斡Vamos, sigamos!

