[msg MSG_000 [Akechi]]
Eso me recuerda, Joker. メVa bien el[n]mapa?

[sel SEL_001 top]
Por supuesto.
Sinceramente, no estoy seguro...

[msg MSG_002 [Ann]]
メEn serio? メPuedo verlo?

[msg MSG_003 [Akechi]]
...Serボa mejor si dibujaras algunos[n]detalles mホs.
Una vez delineadas las paredes, creo que serホ[n]mホs fホcil identificar tanto los callejones sin[n]salida como los lugares que aマn debemos[n]explorar.

[msg MSG_003_1 [Akechi]]
De esa forma, podemos buscar en cada[n]centボmetro de la pelボcula... Puede que incluso[n]nos lleve a algunos tesoros inesperados.

[msg MSG_004 [Morgana]]
Hikari ha tenido la amabilidad de[n]regalarnos este cuaderno. ムHagamos buen[n]uso de 〒l!

[msg MSG_005 [Akechi]]
Parece que hemos explorado gran parte de este[n]lugar. Dudo que pasemos por alto algマn objeto[n]o pasadizo oculto a estas alturas...
Pero, メquizホ serボa mejor que tambi〒n[n]perfilaras las paredes?

[msg MSG_006 [Yusuke]]
En efecto. Imagino que eso nos ayudarホ a[n]ver tanto los callejones sin salida como[n]los caminos que aマn no hemos recorrido.

[msg MSG_006_1 [Yusuke]]
Tambi〒n puede permitir una exploraciポn[n]mホs fluida y habrホ menos posibilidades[n]de que pasemos por alto los tesoros.

[msg MSG_007 [Morgana]]
Hikari ha tenido la amabilidad de[n]regalarnos este cuaderno. ムHagamos buen[n]uso de 〒l!

[msg MSG_008 [Akechi]]
Hmm, se ve bien. Las paredes estホn[n]delineadas, y hemos explorado cada[n]rincポn y grieta hasta ahora...
Tambi〒n podemos ver por dポnde tenemos[n]que ir, asボ que no parece haber ningマn[n]problema. Impresionante.

[msg MSG_009 [Morgana]]
Parece que tampoco hemos pasado por alto[n]ningマn tesoro. ムEstホs aprovechando muy[n]bien ese cuaderno!
ムDeberボamos agradecerle a Hikari por el[n]cuaderno!

