[msg MSG_001 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1607]!
ムHaremos que puedas invocar a [f 0 1 2]Gemori[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_002 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1608]!
ムHaremos que puedas invocar a [f 0 1 2]Ammut[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_003 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1609]!
ムHaremos que puedas invocar a [f 0 1 2]Hare of[n]Inaba[f 0 1 0] a trav〒s de una fusiポn especial!

[msg MSG_004 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1610]!
ムHaremos que puedas invocar a [f 0 1 2]Mayahuel[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_005 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1611]!
ムHaremos que puedas invocar a [f 0 1 2]Vivian[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_006 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1612]!
ムHaremos que puedas invocar a [f 0 1 2]Dzelarhons[f 0 1 0][n]a trav〒s de una fusiポn especial!

[msg MSG_007 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1613]!
ムHaremos que puedas invocar a [f 0 1 2]Fenrir[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_008 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1614]!
ムHaremos que puedas invocar a [f 0 1 2]Hathor[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_009 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1615]!
ムHaremos que puedas invocar a [f 0 1 2]Longinus[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_010 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1616]!
ムHaremos que puedas invocar a [f 0 1 2]Jeanne[n]d'Arc[f 0 1 0] a trav〒s de una fusiポn especial!

[msg MSG_011 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1617]!
ムHaremos que puedas invocar a [f 0 1 2]Vouivre[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_012 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1618]!
ムHaremos que puedas invocar a [f 0 1 2]Kudlak[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_013 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1619]!
ムHaremos que puedas invocar a [f 0 1 2]Kresnik[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_014 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1620]!
ムHaremos que puedas invocar a [f 0 1 2]Seraph[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_015 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1621]!
ムHaremos que puedas invocar a [f 0 1 2]Huang Di[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_016 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1622]!
ムHaremos que puedas invocar a [f 0 1 2]Black[n]Frost[f 0 1 0] a trav〒s de una fusiポn especial!

[msg MSG_017 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1623]!
ムHaremos que puedas invocar a [f 0 1 2]Alice[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_018 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1624]!
ムHaremos que puedas invocar a [f 0 1 2]Michael[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_019 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1625]!
ムHaremos que puedas invocar a [f 0 1 2]Norn[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_020 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1626]!
ムHaremos que puedas invocar a [f 0 1 2]Pale Rider[f 0 1 0][n]a trav〒s de una fusiポn especial!

[msg MSG_021 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1627]!
ムHaremos que puedas invocar a [f 0 1 2]Shiva[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_022 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1628]!
ムHaremos que puedas invocar a [f 0 1 2]Beelzebub[f 0 1 0][n]a trav〒s de una fusiポn especial!

[msg MSG_023 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1629]!
ムHaremos que puedas invocar a [f 0 1 2]Lucifer[f 0 1 0] a[n]trav〒s de una fusiポn especial!

[msg MSG_024 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1630]!
ムHaremos que puedas invocar a [f 0 1 2]Persona[n]Especial 24[f 0 1 0] a trav〒s de una fusiポn[n]especial!

[msg MSG_025 [Caroline]]
ムOye! ムEse es [f 4 4 3 0 1631]!
ムHaremos que puedas invocar a [f 0 1 2]Persona[n]Especial 25[f 0 1 0] a trav〒s de una fusiポn[n]especial!

[msg MSG_090 [Justine]]
メMm...?

[msg MSG_091 [Justine]]
Caroline... メSientes algo en el[n]prisionero?

[msg MSG_092 [Justine]]
Espera, Recluso.

