[msg MSG_000 [Margaret]]
Bienvenido a la Habitaciポn Terciopelo...
Intrigante. Has obtenido una vasija con[n]un poder aマn mayor.

[sel SEL_000 top]
メUna vasija?
メQu〒 poder?

[msg MSG_001 [Margaret]]
Hablo del "Comodボn" que [f 6 1 30 0 0 0] tiene...
Esa carta contiene un poder aマn mayor[n]que las Cartas en Blanco.
Con esa, puedes impartir fuerza a tu[n]Persona principal mediante la fusiポn de[n]sacrificio.

[msg MSG_002 [Ryuji]]
Ya me perdiste. メEsto es importante?

[msg MSG_003 [Margaret]]
En efecto. Se podrボa decir que es un[n]vistazo al potencial crudo del comodボn.
Har〒 los preparativos necesarios para[n]realizar ese ritual.
Si alguna vez quieres intentarlo, estar〒[n]aquボ para ayudarte.

