[msg MSG_000 [Theodore]]
ムBienvenidos! ムLos he estado esperando![n]Por favor, por aquボ.

[msg MSG_001 [Theodore]]
ムEscuche que encontraste algo muy[n]interesante en el mundo de esa pelボcula!
Si no te importa, メpuedo verlo por mボ[n]mismo?

[msg MSG_002]
Le mostr〒 〒l [f 0 1 2]artボculo no identificado[f 0 1 0] a[n]Theodore...

[msg MSG_003 [Theodore]]
ムVaya, estホ hecho a mano...! Como la[n]マltima obra maestra de un artesano...
ムQu〒 elegancia en su simplicidad...![n]Ciertamente, es una obra de arte.

[msg MSG_003_1 [Theodore]]
Ahora, curiosidades como estas suelen[n]contener un poder oculto, pero... esta[n]siente extraワamente vacボa.

[sel SEL_004 top]
メPuedes sentirlo?
メPuedes arreglarla?

[msg MSG_005 [Theodore]]
Sボ. Normalmente, puedo percibir un[n]vestigio de su energボa restante...

[msg MSG_006 [Theodore]]
Una obra de este estilo, bueno... temo[n]que no puedo crear una igual por mi[n]cuenta...
Pero al menos, creo que podrボa despertar[n]el poder que se encuentra dentro.

[msg MSG_006_1 [Theodore]]
Si encuentras mホs, メpodrボas traerlas[n]aquボ?
Si me permites, puedo revelar su valor y[n][f 0 1 2]sacar todo su poder[f 0 1 0].

[msg MSG_002_05]
Le cont〒 que tiramos el resto, sin saber[n]su valor...

[msg MSG_002_06 [Theodore]]
メQu〒...? メCポmo pudiste hacer algo tan[n]terrible...?

[msg MSG_002_06_1 [Theodore]]
Por lo que s〒, todas estホn elaboradas[n]con mucha habilidad y cuidado.[n]ムVerdaderas obras maestras!
Son elegantes, pero simples...[n]ciertamente son obras de arte.
He escuchado que a menudo son vasijas de[n]un poder oculto, aunque pueda[n]desaparecer en algunas...

[sel SEL_002_07 top]
メPuedes sentirlo?
メPuedes arreglarlas?

[msg MSG_002_08 [Theodore]]
Sボ. Normalmente, puedo percibir un[n]vestigio de su energボa restante...

[msg MSG_002_09 [Theodore]]
Una obra de este estilo, bueno... temo[n]que no puedo crear una igual por mi[n]cuenta...
Pero al menos, creo que podrボa despertar[n]el poder dentro de una.

[msg MSG_002_09_1 [Theodore]]
Si encuentras mホs, メpodrボas traerlas[n]aquボ?
Si me permites, puedo revelar su valor y[n][f 0 1 2]sacar todo su poder[f 0 1 0].

[msg MSG_007]
Ahora puedes [f 0 1 2]Valorar[f 0 1 0] objetos no[n]identificados y restaurar su poder[n]original.

[msg MSG_008 [Theodore]]
Estoy a tu servicio.

