[msg MSG_000 [Caroline]]
斡Parece que nos trajiste algo 雨til por[n]una vez, Recluso!
斡D姻jame ver!

[msg MSG_001]
Le entregu姻 [f 4 4 3 0 1602]...

[msg MSG_002 [Justine]]
Hmm... Qu姻 intrigante...
Esto puede ayudarnos a mejorar la[n]Habitaci吋n Terciopelo.

[msg MSG_003 [Caroline]]
斡Espera aqu胤, Recluso!

[msg MSG_004]
Minutos m茨s tarde...

[msg MSG_005 [Justine]]
*jadeo* Fue complicado, pero esto[n]deber胤a ser 雨til para tu rehabilitaci吋n.

[msg MSG_006]
Ahora puedes usar 斡[f 0 1 2]Fusi吋n de 3 capas[f 0 1 0]![n]Esta requerir茨 tres Personas para[n]funcionar.

[msg MSG_007 [Caroline]]
斡No desaproveches nuestra ayuda,[n]Recluso!

