[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 0 1 0 3][f 4 6 33 0 0 1][f 3 1 1 0 0 4167]Thus concludes the preparations of[n]your very own P-Book.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 33 12 0 0][f 3 1 1 0 0 0]Feel free to make changes to it[n]whenever the mood strikes you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]To begin using StreetPass, select[n][f 0 1 2]StreetPass Setting[f 0 1 0] from the menu.[n][f 1 3 65535][f 1 1][e]

