[msg MSG_000 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 85 12 0 1][f 3 1 1 0 0 65009]Okay, so lemme explain about how to[n][f 0 1 2]communicate with other worlds[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The deal is, there are apparently a ton[n]of worlds besides this one out there.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So, like, in those other worlds, there[n]are other "you"s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]And they're all trying to communicate[n]with your world from theirs.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 65001]So if you want to contact this other[n]you, you use the [f 0 1 2]P-Book[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]The P-Book can hold your[n]team's info and one Sub-Persona.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]When you exchange a Book with another[n]you, you'll both be able to summon the[n]Sub-Personas within the Books.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Obviously it'll still cost some money,[n]but you might end up with a really[n]strong Persona.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_2 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 0][f 3 1 1 0 0 0]But first we'll need a name. So the[n]other yous can tell you apart,[n]and stuff.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_3 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 1 1][f 3 1 1 0 0 65013]Hmm... Well, it's a name that goes[n]in the P-Book, so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_4 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Let's call it your [f 0 1 2]P-Book Name[f 0 1 0]![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]You can change it whenever, so just[n]give me something to write down.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 0]A P-Book Name, huh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23115][f 6 1 2 0 0 5]Why don't we use our Phantom Thieves[n]team name?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 3 0 0 0]Uh, your what?[n][f 1 3 65535][f 1 1][e]

