[msg MSG_000]
[f 0 5 65278][f 2 1]Where will you start from?[n]*This debug is for mission confirmation.[n][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1]From the beginning[e]
[f 0 5 65278][f 2 1]From Ch.1[e]
[f 0 5 65278][f 2 1]From Ch.2[e]
[f 0 5 65278][f 2 1]From Ch.3[e]
[f 0 5 65278][f 2 1]From Ch.4[e]
[f 0 5 65278][f 2 1]From Ch.5[e]

[msg MSG_002]
[f 0 5 65278][f 2 1]Starting gameplay.[n][f 1 1][e]

[msg MSG_003]
[f 0 5 65278][f 2 1]Skipping the prologue and starting[n]from Ch.1.[n][f 1 1][e]

[msg MSG_004]
[f 0 5 65278][f 2 1]Starting gameplay from Ch.2.[n][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1]Starting gameplay from Ch.3.[n][f 1 1][e]

[msg MSG_006]
[f 0 5 65278][f 2 1]Starting gameplay from Ch.4.[n][f 1 1][e]

[msg MSG_007]
[f 0 5 65278][f 2 1]Starting gameplay from Ch.5.[n][f 1 1][e]

