[msg MSG_000 [Elizabeth]]
The special screening this time is...
A story about a passionate battle[n]between men... A violent clash that[n]could split the very earth in two!
The rules are simple: Defeat the large,[n]muscular Shadows. That is all.

[msg MSG_001 [Kanji]]
Heh! Sounds like fun! I'm gettin' pumped[n]just thinkin' about it!
Hell yeah! Bring 'em on! It's Kanji[n]time!

[sel SEL_002 top]
You've got this.
Settle down.

[msg MSG_003 [Morgana]]
Yeah, looks like you're all set. We're[n]counting on you, Kanji.

[msg MSG_004 [Morgana]]
Haha, let him be. He's just excited.

[msg MSG_005 [Kanji]]
......!
......

[msg MSG_006 [Morgana]]
Wh-What?

[msg MSG_007 [Kanji]]
...Tch.

[msg MSG_008 [Ryuji]]
Hey, wait a sec.
Weren't you glaring at Morgana earlier[n]too?
If you got somethin' to say, just say[n]it!

[msg MSG_009 [Kanji]]
......

[msg MSG_010 [Ann]]
Hey, Ryuji, cut it out! Kanji-kun, you[n]too!

[msg MSG_011 [Kanji]]
...I got nothin' to say.

[msg MSG_012 [Ryuji]]
The hell's his problem?

[msg MSG_012_1 [Ryuji]]
Whatever, let's get goin'. I'm itchin'[n]to break somethin'.
Those Shadows won't know what hit 'em.[n]Where to?

[msg MSG_013 [Elizabeth]]
The target enemies' locations are[n]displayed on the ticket.
According to this, you'll find them in[n]three separate areas.
You may want to mark them on your map.

[msg MSG_014]
The enemies' locations have been added[n]to the map.

[msg MSG_015 [Morgana]]
All right, we should be okay now. Let's[n]head out once we're ready!

