[msg MSG_000 [Futaba]]
Whew... We defeated the new challenger![n]I'm pretty sure that's all of them.

[msg MSG_001 [Ryuji]]
Hey, Kanji! You aight?

[msg MSG_002 [Kanji]]
No problem here! I'm pretty good at[n]takin' a hit.
Still, I gotta say, I'm sorry for[n]shovin' you guys like that.

[msg MSG_003 [Ryuji]]
Heh, don't worry about it. We would've[n]been toast if you didn't.
That was one hell of a punch. You got[n]some real power.

[msg MSG_004 [Kanji]]
Th-Thanks!

[msg MSG_005 [Kanji]]
By the way, lemme also just say... I'm[n]sorry!

[msg MSG_006 [Ryuji]]
Wh-Wha―?

[msg MSG_007 [Kanji]]
I guess I didn't understand you, Skull.
I thought you were just some thug from[n]the city who didn't know how to[n]listen...

[msg MSG_008 [Futaba]]
That pretty much sums it up.

[msg MSG_009 [Ann]]
Sounds about right.

[msg MSG_010 [Ryuji]]
Shut up!

[msg MSG_011 [Kanji]]
You apologized to me after I tried to[n]pick a fight with you, and...
You called me your friend.

[msg MSG_012 [Ryuji]]
W-Well, yeah. We were fightin' a[n]Shadow... Pretty embarrassing now that I[n]think about it...
I'm sorry too. I thought you were like[n]everyone else... Judgin' me 'n' stuff.
Those eyes of yours just kinda set me[n]off.

[msg MSG_013 [Naoto]]
Understandable. It's the truth.

[msg MSG_014 [Rise]]
Yeah, not much we can do there. Kanji's[n]not exactly the most inviting person in[n]the world.

[msg MSG_015 [Kanji]]
Hey, shut it!

[sel SEL_016 top]
You two make a good team.
You two are a lot alike.

[msg MSG_017 [Ryuji]]
Heheh, maybe we are. We definitely got[n]spirit, that's for sure!

[msg MSG_018 [Kanji]]
Hell yeah! No one's got more spirit than[n]us!

[msg MSG_019 [Futaba]]
And thus, a passionate bromance was born[n]between two men.
Happily ever after. Now, c'mon back!

[msg MSG_020 [Kanji]]
Hey...
You're pretty different from how you[n]look, you know that?

[msg MSG_021 [Ryuji]]
Haha, look who's talkin'.

[msg MSG_022 [Kanji]]
Maybe I'm just stupid, but I guess you[n]really can't judge a book by its cover.

[msg MSG_023 [Ryuji]]
Guess so.
Joker might seem quiet all the time, but[n]he's super reliable when it comes down[n]to it.
...He's taught an outcast like me a[n]whole lot.
I'm really grateful for the Phantom[n]Thieves. Every one of them.

[msg MSG_024 [Kanji]]
It's basically the same for me.
My team accepted everything about me,[n]even my weaknesses.
So, I'm tryna give back, or at least[n]help out, you know?

[msg MSG_025 [Ryuji]]
Yeah. It's not like we got the smarts or[n]the support skills, but...
What can I say? I KNOW we're good for[n]somethin'!

[msg MSG_026 [Kanji]]
Hell yeah! You're one passionate dude,[n]Skull!

[msg MSG_027 [Ryuji]]
Heh, all this talk's makin' me feel even[n]more embarrassed...
Don't tell anyone about all this, yeah?

[msg MSG_028 [Kanji]]
Yeah, no way. S-Same goes for you.

[msg MSG_029 [Futaba]]
Hey, you guys're gonna get left behind![n]Why're you two all red?
Oh hoh... Did you two confess your love[n]for each other?

[msg MSG_030 [Ryuji]]
H-Hell no! We're comin'!

