[msg MSG_000 [Elizabeth]]
For this special screening, all of you[n]will be required to complete a certain[n]mission.

[msg MSG_001 [Yosuke]]
Mission?

[msg MSG_002 [Elizabeth]]
I would like you to reach the location[n]that I specify.

[msg MSG_003 [Chie]]
...Huh? That's all? That sounds easy!

[msg MSG_004 [Elizabeth]]
Perhaps, but things rarely go as[n]planned. Such is the way of the world.

[sel SEL_005 top]
Say what!?
Saw that coming...
Not a problem.

[msg MSG_006 [Morgana]]
Come on, you should've seen that coming.

[msg MSG_007 [Ryuji]]
Dude, does anything faze you? Even just[n]a little?

[msg MSG_008 [Yosuke]]
Wow... Always playin' it cool.

[msg MSG_009 [Elizabeth]]
That said, it seems the syndicate has[n]recently become aware of our plans...
As a result, security has been raised to[n]the maximum level.
Guard detail and searchlight activity[n]will be megatons heavier than usual.

[msg MSG_010 [Ryuji]]
Ugh... This is a pain just hearin' about[n]it...

[msg MSG_011 [Ann]]
That's...

[msg MSG_012 [Chie]]
Yeah, it's perfect!
Slipping past searchlights is totally[n]something a phantom thief would do!

[msg MSG_013 [Ryuji]]
What's got those two so worked up?[n]Somethin' happen?

[sel SEL_014 top]
They're motivated.
They're good friends.
We can't let them show us up.

[msg MSG_015 [Ryuji]]
Well, that's cool, I guess...
Honestly, though, it's a pretty weird[n]pairing, now that I think about it.

[msg MSG_016 [Ryuji]]
Well, that's cool, I guess... Still,[n]they weren't always that close, were[n]they?

[msg MSG_017 [Ryuji]]
What is this, a competition!?
I'm just sayin', it's kind of a weird[n]pairing, don't you think?

[msg MSG_018 [Yosuke]]
Well, they are different from each[n]other. They don't look like they'd have[n]anything in common...

[msg MSG_019 [Teddie]]
A sweet-toothed girl from the city and a[n]meat-lover from the country...
Both so different yet so pretty! I can't[n]bear to choose between them!

[msg MSG_020 [Ann]]
Hey. What're you guys mumbling about[n]over there?

[msg MSG_021 [Chie]]
You're gonna get left behind!

[msg MSG_022 [Kanji]]
They really are worked up... Guess we[n]should get movin' too.

