[msg MSG_000 [Ryuji]]
So we're gonna look for ammonites,[n]but... where the hell do we start?

[sel SEL_001 top]
The dirt.
The forest.
The ocean.

[msg MSG_002 [Ann]]
You wanna look around here? That seems[n]like it'd be kinda tough, don't you[n]think?

[msg MSG_003 [Haru]]
That's an idea. Ammonites are sea[n]creatures, after all.
But there's no ocean anywhere nearby, is[n]there...?

[msg MSG_004 [Akechi]]
If we're searching for ammonites, I[n]imagine it's best to look near the[n]water.
Fossils are often found in rivers, even[n]today.

[msg MSG_005 [Naoto]]
I believe the closest body of water is[n]just east of here.

[msg MSG_006 [Yusuke]]
Thank you all...
Mark my words, I WILL obtain that[n]ammonite for Amagi-san! I WILL see her[n]passion in full bloom!

[msg MSG_007 [Yukiko]]
I appreciate it, but... it's a little[n]embarrassing hearing you scream it out[n]like that.

[msg MSG_008 [Makoto]]
Sorry... It's just his way of showing[n]you that he cares.
Either way, let's make our way east.

