[msg MSG_000 [Elizabeth]]
For this next task, you will be required[n]to find what are known as "ammonites."
It has been rumored that these[n]long-extinct creatures have recently[n]been spotted somewhere in Junessic Land.
I would very much like to have a playful[n]rendezvous with this "ammonite" and its[n]superbly tentacle-like legs.

[msg MSG_001 [Chie]]
Where's Elizabeth learn about this kinda[n]stuff...?

[msg MSG_002 [Elizabeth]]
*giggle* I have a gift for sensing these[n]sorts of things!
It is somewhat of a cure for boredo― I[n]mean... I'm just naturally talented.

[msg MSG_003 [Ryuji]]
...We can hear you, you know.

[msg MSG_004 [Naoto]]
Well, we do seem to benefit from[n]completing these requests.

[msg MSG_005 [Yusuke]]
Ammonites...

[msg MSG_006 [Futaba]]
Hm? What's up Inari?

[msg MSG_007 [Yusuke]]
, I want to accept this quest! Is that[n]fine?

[sel SEL_008 top]
Not a problem.
I'll leave it to you.
Why's that?

[msg MSG_009 [Yusuke]]
Thank you.

[msg MSG_010 [Ryuji]]
What's got you so excited?

[msg MSG_011 [Yusuke]]
I wish to move Amagi-san's heart.

[msg MSG_012 [Teddie]]
By giving her an ammonite!? That's[n]nonsense!
Girls want things that are shiny and[n]expensive!

[msg MSG_013 [Chie]]
That's not how you do it, but, uh...[n]Since when were you two a thing?

[msg MSG_014 [Yukiko]]
It's not like that. Yusuke-kun's[n]teaching me how to draw.
He wants to help me find something I'll[n]like, something I can be passionate[n]about.

[msg MSG_015 [Yusuke]]
Amagi-san has no idea of the incredible[n]artistic potential she possesses.
I must find this ammonite in order to[n]see what she's truly capable of!

[msg MSG_016 [Morgana]]
Yusuke's getting all worked up. We'd[n]better get this done quick.

[msg MSG_017 [Chie]]
...Yukiko's art wasn't that special, was[n]it? I feel like I've seen the same sort[n]of stuff in art class...

