[msg MSG_000 [Yosuke]]
Yeah! We did it!

[msg MSG_001 [Chie]]
Woohoo! Meat! Meat! Meat!

[msg MSG_002 [Naoto]]
Might we be forgetting the real reason[n]we came here...? It was to defeat the[n]FOE.

[msg MSG_003 [Chie]]
No use sweatin' the details, Naoto-kun![n]All's well that ends well!

[msg MSG_004 [Yusuke]]
Now, without further ado, let us begin[n]the feast...

[msg MSG_005 [Yusuke]]
Hm? What's this!?

[msg MSG_006 [Yosuke]]
It's hard as a rock... Whatever it is,[n]it's definitely not meat.

[msg MSG_007 [Chie]]
Whaaat!? What do you mean!?

[msg MSG_008 [Naoto]]
It appears to be a realistic imitation.
Though it may look like meat on the[n]outside, it's actually made of wood.

[msg MSG_009 [Makoto]]
Well... I had a feeling that might be[n]the case seeing as how the FOE was using[n]it as a weapon.

[msg MSG_010 [Chie]]
So we can't eat it? Then, where did that[n]amazing meat smell come from!?

[msg MSG_011 [Akechi]]
I get the feeling it probably came from[n]that nearby hamburger place.

[msg MSG_012 [Chie]]
S-Seriously...?

[msg MSG_013 [Yusuke]]
Ngh... Once again, I was prepared for a[n]feast, and once again, you tell me I[n]can't eat? How terribly disappointing.
Still... it wasn't all for nothing!
びめま ぼよょれろるゎぼろもよょデ ろめま ぼよゅよるもょむ ろまぼめょもりゎまテテテ[n]とろ'れ ほぺるまゅを ぽもれろもょむゎもれめぺほゅま みるよゆ ろめま るまぺゅ[n]ろめもょむ! と ゆゎれろょ'ろ みよるむまろ ろめもれ!

[msg MSG_014 [Ann]]
Oh... There he goes again...

[msg MSG_015 [Morgana]]
Well, if we can't eat it, we can't eat[n]it.
I'd say we're done here. Let's head back[n]to the theater for now.

