[msg MSG_000 [Haru]]
So that one's the fake? I wonder if[n]he'll admit it.

[sel SEL_001 top]
Let's bring him down.
Let's hear what he has to say.

[msg MSG_002 [Naoto]]
Hold on, we should double check.
I'll go make sure. Please let me handle[n]this.

[msg MSG_003 [Naoto]]
Right. Let's make sure.
I have an idea. Please wait here.

[msg MSG_004 [Serious Policeman]]
What? You again? We're on duty, stop[n]pestering us.

[msg MSG_005 [Naoto]]
So you're the fake!
Reveal yourself! Your charade ends now!

[msg MSG_006 [Futaba]]
Whoa! There's a drastic turn of events!

[msg MSG_007 [Serious Policeman]]
Wh-What're you talking about!? Who are[n]you!?

[msg MSG_008 [Naoto]]
Here's what you told me earlier.
"The officer by car number 11-10 seems[n]suspicious to me."
Say your suspicions were correct. That[n]would mean the officer with the car[n]numbered 11-10 is a liar and a fake...
However, officer 11-10 stated officer[n]77-55 is real.
If officer 11-10 is lying about officer[n]77-55, then there's more than one liar.
Therefore, you are the liar!

[msg MSG_009 [Serious Policeman]]
Damn it! You're one crazy kid. I'm gonna[n]need some backup...
......!?
......
...OOOOOOHN!

[msg MSG_010 [Chie]]
Whoa geez! It transformed!

[msg MSG_011 [Futaba]]
Looks like our hypothesis was correct![n]Here it comes!

