[msg MSG_000]
It says "COOL KAMOSHIDAMAN" on the[n]wall...

[msg MSG_001 [Yusuke]]
This doesn't look unfinished.

[msg MSG_002 [Ryuji]]
Cool... Kamoshidaman?
You think he was too hot in that spandex[n]or somethin'? And maybe people wanted to[n]help cool him down?

[msg MSG_003 [Ann]]
No, dummy. Obviously it means, like,[n]"awesome" here!

[msg MSG_004 [Ryuji]]
Ugh, so this is actually PRAISING[n]Kamoshidaman!? You gotta be kiddin' me.

[msg MSG_005 [Akechi]]
The people of this city did once see him[n]as a hero. It's probably left over from[n]then.
Then again, they may be having second[n]thoughts.

[msg MSG_006 [Morgana]]
You're probably right. Either way, let's[n]keep looking for the graffiti that was[n]changed.

[msg MSG_007]
It says "COOL KAMOSHIDAMAN" on the[n]wall...

[msg MSG_008 [Yusuke]]
Hmm... This doesn't look like the[n]drawing we're after. We want the one[n]that's different from the others.

