[msg MSG_000 [Yusuke]]
......

[sel SEL_001 top]
What's wrong?
Are you hungry or something?

[msg MSG_002 [Yusuke]]
Oh... Sorry, I was just looking at this[n]graffiti.

[msg MSG_003 [Yusuke]]
Well, I certainly could eat, but I'm far[n]from starving.
I was just looking at this graffiti.

[msg MSG_004 [Yusuke]]
Look here. It's unfinished.

[msg MSG_005 [Ryuji]]
Oh yeah, it ain't like the others. Maybe[n]they got bored halfway through?

[msg MSG_006 [Yusuke]]
No, that's unlikely.
I can feel the artist's hesitation here,[n]their suffering...
Their hands were forced to stop painting[n]against their will. Right here.

[msg MSG_007 [P3 Fem Protag]]
Wow, Fox. How did you figure all of that[n]out?

[msg MSG_008 [Yusuke]]
Graffiti is a crime, but there's an[n]artistic quality to it that can't be[n]dismissed.
だょぽ と ぽよょ'ろ ゃゎれろ ゆまぺょ ろめま ろまぼめょもりゎまテ と ゆまぺょ[n]ろめま ぼるまぺろよる'れ みままゅもょむれ ぺょぽ ろめま ゆまれれぺむま ろめまを[n]ろるを ろよ ぼよょわまを ろよ れよぼもまろをテテテ!
Yes, it's coming to me! This well of[n]inspiration simply won't stop flowing!
Ahh, perhaps I'll fill in the blanks and[n]finish it for them...!
Urgh! No... Be still, my hand...!

[msg MSG_009 [Ryuji]]
Welp, he's at it again.

[msg MSG_010 [Morgana]]
Hmm, I've never really cared much for[n]graffiti.
But it's a crime, right? If Queen found[n]out, you'd be tasting the iron fist of[n]justice for sure.

[msg MSG_011 [Ann]]
Hey, how long are you guys gonna stand[n]there? Queen and Noir are waiting for[n]us! Let's go!

[msg MSG_012 [Yusuke]]
My apologies, I was distracted... Right.[n]They're our top priority.
Now then, let's be off. We must dethrone[n]that false hero!

[msg MSG_013]
There's some unfinished graffiti here on[n]the wall...

