[msg MSG_000]
It says "FOOL KAMOSHIDAMAN" on the[n]wall...

[msg MSG_001 [Ryuji]]
Whoa! Hey, check it out! Isn't this one[n]different from the others?

[msg MSG_002 [P3 Fem Protag]]
Yeah, the others say "COOL," but this[n]one says "FOOL."

[msg MSG_003 [Yusuke]]
"FOOL"...

[msg MSG_004 [Akechi]]
"COOL" and "FOOL." It's only a one[n]letter difference, yet they carry almost[n]opposite meanings.
So a graffiti drawing that once praised[n]Kamoshidaman has now been changed to[n]deny him.

[msg MSG_005 [Yusuke]]
What do you make of this, Joker?

[sel SEL_006 top]
The people's opinion changed.
It's a pretty big turnaround.
Nothing really.

[msg MSG_007 [Yusuke]]
Yes, I'd say so too.
とろ ゆぺを ゅよよや ゅもやま ょよろめもょむ ゆよるま ろめぺょ ゆよぼやまるをデ[n]ほゎろ と ほまゅもまわま もろ れめよゐれ ろめぺろ ろめま らまよらゅま ぺるま[n]れろぺるろもょむ ろよ ろめもょや ぽもみみまるまょろゅをテ

[msg MSG_008 [Yusuke]]
Hmm... I suppose that's one way to look[n]at it.
But I believe this is proof that the[n]people are starting to think[n]differently.

[msg MSG_009 [Yusuke]]
I see... If it was just ordinary street[n]art, I may have said the same.
But I believe this is proof that the[n]people are starting to think[n]differently.

[msg MSG_010 [Ann]]
Starting to think differently?

[msg MSG_011 [Yusuke]]
Notice how wet the paint is. This was[n]written not too long ago.
This is a testament to the fall of[n]Kamoshidaman's power. It tells us the[n]people have come to their senses.
Slowly but surely, they are beginning to[n]change, just as the movie did.
I've no doubt that this street art is[n]just one of those changes.

[msg MSG_012 [Makoto]]
Even if they don't speak out, they have[n]other ways to express their feelings.

[msg MSG_013 [Yusuke]]
Art is far more than just something to[n]look at.
A person can assert their existence[n]through art―shout with the voice deep[n]inside their soul.

[msg MSG_014 [Ryuji]]
と ろめよゎむめろ もろ ゐぺれ ゃゎれろ れよゆま ぺょょよをもょむ れぼるもほほゅまれ[n]ぺろ みもるれろデ ほゎろ もろ'れ らるまろろを ぼよよゅ もみ ろめぺろ'れ ろめま[n]ゆまれれぺむま もろ'れ ろるをもょむ ろよ れまょぽテ
It means they're not letting themselves[n]get pushed around anymore.

[msg MSG_015 [Ann]]
Yeah, things didn't just end with us[n]beating Kamoshidaman.
The people actually started thinking for[n]themselves afterwards.

[msg MSG_016 [Futaba]]
Wow... If Fox hadn't explained all that[n]about the graffiti, I never would've[n]realized what it really meant.
So, in a way, Fox, I guess I'm thankful[n]that you're a weirdo just this once.

[msg MSG_017 [Yusuke]]
What do you mean, "weirdo"!?

[msg MSG_018 [P3 Fem Protag]]
Uhh, well... I guess this means we've[n]fulfilled the request, right?

[msg MSG_019 [Haru]]
Mhm, I think so. Let's head back to the[n]theater.

