[msg MSG_000 [Kanji]]
Awesome. They really were hidin' under[n]the leaves.

[msg MSG_001 [Haru]]
*giggle* Pretty surprising, actually.[n]I've never seen ones this big before.

[msg MSG_002 [Teddie]]
Ahh! Don't bring it any closer with that[n]pretty smile on your face!

[msg MSG_003 [Kanji]]
The hell, Teddie? You can't handle a[n]little worm?
Wait a sec, what's wrong with you guys?[n]Yer all so far away...

[msg MSG_004 [Chie]]
Ahaha... I'm not the biggest fan of[n]those things...

[msg MSG_005 [Ann]]
Y'know, there are others here who'd be[n]better for this...

[msg MSG_006 [Morgana]]
I get it. They are kind of gross when[n]you see them up close.

[sel SEL_007 top]
I'm on it.
I don't like bugs either...
Want a bite, Mona?

[msg MSG_008 [Morgana]]
Nice, Joker. You didn't hesitate one[n]bit.

[msg MSG_009 [Ann]]
You can depend on someone who's quick to[n]act like that.

[msg MSG_010 [Morgana]]
But you still put your hand in that pile[n]of leaves. That was pretty brave...

[msg MSG_011 [Yusuke]]
Of course. He is the leader of the[n]Phantom Thieves, after all.

[msg MSG_012 [Morgana]]
No way! Don't treat me like some stray![n]Hey, get that thing away from me!

[msg MSG_013 [P4 Hero]]
Always the first to act... I'd expect[n]nothing less.

[msg MSG_014 [Yosuke]]
Hm? What's up, partner?

[msg MSG_015 [P4 Hero]]
Nothing... Well, it looks like we found[n]some, but is this enough?

[msg MSG_016 [Haru]]
Hmm... It looks like less than what we[n]hoped for.

[msg MSG_017 [Kanji]]
No problem! Senpai could catch a fish[n]using nothin' but his will if he really[n]wanted to!

[sel SEL_018 top]
Really?
They're counting on you.
So can I!

[msg MSG_019 [P4 Hero]]
I appreciate the vote of confidence, but[n]I don't think it's possible.

[msg MSG_020 [P4 Hero]]
I'm glad to hear that, but I don't think[n]it's possible.

[msg MSG_021 [Yusuke]]
What...? To think they've both become[n]such incredible fishermen...

[msg MSG_022 [P4 Hero]]
I appreciate the sentiment, but I don't[n]think it's possible.

[msg MSG_023 [Haru]]
Well then, perhaps we can continue the[n]search somewhere else.
I'm sure there are other places with[n]leaves like this.

[msg MSG_024 [Morgana]]
Right, then let's keep looking.
We'll find more leaves at the other[n]Treasure Spots. Let's go!

