[msg MSG_000 [Ryuji]]
Where do you think that fish is at?

[msg MSG_001 [Yosuke]]
What about that spot where we cooked up[n]that meat?

[msg MSG_002 [Kanji]]
All right! Then, let's head over that[n]way!

[msg MSG_003 [P4 Hero]]
...Hold on. Before we head out, aren't[n]we forgetting something important?

[sel SEL_004 top]
Something important?
Bait.
Bread crumbs.

[msg MSG_005 [Yukiko]]
Oh! I know! Bait for the fish!

[msg MSG_006 [Kanji]]
Bread crumbs? Why, in case we get[n]hungry?

[msg MSG_007 [Yukiko]]
Oh! I know! Bait for the fish!

[msg MSG_008 [P4 Hero]]
Right. If we're going fishing, we'll[n]need some bait. Bread crumbs would've[n]been perfect...
I guess we'll have to find something[n]there.

[msg MSG_009 [Yosuke]]
Bait for the fish? You mean, like,[n]worms...? Where we gonna get those?

[msg MSG_010 [Haru]]
Oh, I've heard that worms tend to hide[n]beneath piles of damp leaves...

[msg MSG_011 [Chie]]
Eeek!

[msg MSG_012 [Ann]]
Y-You just had to go there...

[msg MSG_013 [P4 Hero]]
Hm... Damp leaves...?
All right, let's find some and gather up[n]some bait.

