[msg MSG_000 [Kanji]]
This is the spot.

[msg MSG_001 [Yosuke]]
But we can't start fishing without any[n]bait.

[msg MSG_002 [Haru]]
We'll need some bugs.
I'm sure we'll find more than enough if[n]we look among the leaves. Let's go see.

[msg MSG_003 [Rise]]
This is it! I can sense them!

[msg MSG_004 [Kanji]]
Well, we got our bait. Let's find that[n]fish!
You got this, Senpai!

[msg MSG_005 [Ryuji]]
Bet Joker catches it first!

[msg MSG_006 [Kanji]]
What's that!?

[msg MSG_007 [Ryuji]]
Fine, then, it's a duel! Show 'em what[n]you got, Joker!

[sel SEL_008 top]
Leave it to me.
Time to finish what we started.
Don't drag me into this.

[msg MSG_009 [P4 Hero]]
Hm. Let's do it.

[msg MSG_010 [P4 Hero]]
C'mon, it'll be fun.

[msg MSG_011 [Teddie]]
You can do it, Sensei!

[msg MSG_012 [Yusuke]]
Go, Joker! Show us your brilliance!

[msg MSG_013 [Makoto]]
I knew this would happen.

[msg MSG_014 [Yosuke]]
All right. Ready... Go!

[msg MSG_015 [P4 Hero]]
Hm!

[msg MSG_016 [Ryuji]]
Guess we'll have to wait. It usually[n]takes a while from this point...

[msg MSG_017 [P4 Hero]]
...I've got a bite!

[msg MSG_018 [Ryuji]]
Are you kidding me!?

[msg MSG_019 [Morgana]]
The way the line's pulling, it's gonna[n]be a big one!

[msg MSG_020 [P4 Hero]]
Ugh... This thing's about to take me[n]down with it...

[sel SEL_021 top]
I've got your back.
We'll do it together.

[msg MSG_022 [P4 Hero]]
Joker... Right!
Ready? One... Two...

[sel SEL_023 top]
Three!
Got you!

[msg MSG_024 [Kanji]]
Whoa! That's hella huge...

[msg MSG_025 [Makoto]]
Judging by the size, I'm sure this is[n]the fish we're looking for.

[msg MSG_026 [P4 Hero]]
Whew... Thanks. It was supposed to be a[n]duel, but you still stepped in to help[n]me.

[sel SEL_027 top]
I did what any leader would do.
We're a team.

[msg MSG_028 [P4 Hero]]
Our leader...
You're right. I would've done the same[n]thing.

[msg MSG_029 [P4 Hero]]
A team... Yeah, you're right!

[msg MSG_030 [Futaba]]
There was like, a clashing of powers,[n]and a fusion thing that was so intense!

[msg MSG_031 [Haru]]
You two were able to catch the fish[n]because you worked together.

[msg MSG_032 [Yusuke]]
Yes, it was quite the battle.
Well now, I'd say we're done here. Let's[n]head back.

