[msg MSG_000 [Elizabeth]]
Well done, everyone. I received the[n]Cinnamon Fern you brought me.
I tried feeding one to Theo, but he[n]complained and said things like, "It's[n]bitter," and, "It's not ripe yet."

[msg MSG_001 [Akechi]]
O-Oh... He ate this raw... I must admit,[n]I feel sorry for him.

[msg MSG_002 [Elizabeth]]
To think we had to dry it then grind it[n]into a fine powder...
It appears I had the wrong idea.[n]Whoopsie-daisy.

[msg MSG_003 [Futaba]]
That's all you have to say...?

[msg MSG_004 [Elizabeth]]
Now then, once everyone's ready, we can[n]finally start making these "churros."
Furthermore, I believe we've enough[n]ingredients to start selling them from[n]this point on.

[msg MSG_005 [Ann]]
That means we'll be able to eat them[n]whenever we want! I'm glad we did all[n]that work!

[sel SEL_006 top]
That's exciting.
Don't eat too many.

[msg MSG_007 [Ann]]
Yeah! Let's all eat some together! It'll[n]help us relax when we're tired.

[msg MSG_008 [P3 Fem Protag]]
We'll have so much time to talk, Theo[n]will need to work extra hard.

[msg MSG_009 [Ann]]
Haha, I know, I know. Cut me some slack.
I'll just have to fight as hard as I can[n]and burn off some of those calories!

[msg MSG_010 [P3 Fem Protag]]
Hehe, don't forget our chatting time.[n]Theo will need to work extra hard to[n]keep up.

[msg MSG_011 [Rise]]
Oh, I'm so excited! We have so much to[n]talk about!

[msg MSG_012 [Ryuji]]
Dude, girls become friends so friggin'[n]fast...

[msg MSG_013 [Yusuke]]
They often talk a lot in order to get to[n]know each other. It's one area in which[n]I could never hope to outdo them.

[msg MSG_014 [P4 Hero]]
Well, we've all been fortunate enough to[n]meet here, so we should do our best to[n]strengthen these new friendships.

