[msg MSG_000 [Elizabeth]]
For this special screening, you will be[n]tasked with gathering the specified[n]ingredients.
If I recall, these Tingly Kernels were[n]used in the latest popcorn recipe...
Would you be so kind as to bring some to[n]my foolish younger brother?

[msg MSG_001 [Theodore]]
That would be most appreciated...
I believe you can find Tingly Kernels[n]near damp places like ponds or rivers.
A place as rife with vegetation as[n]Junessic Land should be perfect.

[msg MSG_001_5 [Morgana]]
Okay then, I say we give him a hand. He[n]is always helping us, after all.
Plus, we'll get some more of that new[n]popcorn. Two birds, one stone. Make sure[n]you're ready, and we'll get going.

[msg MSG_002 [Distant scream]]
Aaaaaaaaaaaaah!

[msg MSG_003 [Theodore]]
Wh-What was that...!?

[msg MSG_004 [Morgana]]
Come on, let's go check it out!

