[msg MSG_000]
We planted the popcorn in the lobby then[n]hid out of sight...

[msg MSG_001 [Teddie]]
Oho, this must be one of those take-out[n]steaks I've heard so much about!

[msg MSG_002 [Naoto]]
Um... Are you perhaps referring to a[n]stakeout?

[msg MSG_003 [Akechi]]
Shh... Someone's coming.

[msg MSG_003_2 [Teddie?]]
......

[msg MSG_003_4 [Naoto]]
It's just as we thought... and now we've[n]caught them in the act.

[msg MSG_004 [Teddie]]
Hey, hey, hey! Whaddya think you're[n]doing with my bear suit!?
I refuse to overlook your evildoings any[n]longer!

[msg MSG_005 [Teddie?]]
......!?

[msg MSG_006 [Naoto]]
We've finally caught you.

[msg MSG_007 [Akechi]]
Given the situation, there's only one[n]answer. Take off that suit...

[msg MSG_008 [Akechi ＆ Naoto]]
Caroline and Justine!

[msg MSG_010 [Caroline]]
Rrrgh...! How did you know it was us!?

[msg MSG_011 [Naoto]]
We may have only had circumstantial[n]evidence...
But after process of elimination, you[n]two were the only remaining suspects.

[msg MSG_012 [Akechi]]
Let's start with Elizabeth and[n]Theodore...
The two of them were with when Haru[n]found the bear suit, so that clears[n]them.

[msg MSG_013 [Naoto]]
Next, we know that Margaret was in the[n]screening room at the time of the[n]incident.
Marie-san also had a run-in with the[n]bear suit, so it clearly wasn't her.

[msg MSG_014 [Akechi]]
So you see, that only left the two of[n]you.

[msg MSG_015 [Naoto]]
And if you're wondering how we knew it[n]was both of you, the bear suit gave us a[n]hint.
The two of you are far too small for one[n]of you to have worn it alone.
Therefore, the reason you were stumbling[n]around was because one of you was[n]sitting on the other's shoulders.

[msg MSG_015_2 [Teddie]]
I never would've imagined two people[n]could fit in my bear suit...
No fair! Look at all the fun you were[n]having in there! Why wasn't I invited!?

[msg MSG_016 [Justine]]
I don't believe we'll be able to talk[n]our way out of this, Caroline.

[msg MSG_017 [Caroline]]
Urrrgh...

[msg MSG_018 [Naoto]]
Why did you do it?

[msg MSG_019 [Justine]]
When Caroline heard about the popcorn,[n]she said she just had to try it...

[msg MSG_020 [Caroline]]
You were as curious as me, Justine!
B-Besides, Theodore was going on about[n]how he made his greatest creation yet...

[msg MSG_021 [Justine]]
But then we learned he had run out of[n]ingredients for his new popcorn and that[n]he couldn't make much as is.
However, the more we realized we[n]couldn't have any, the more we wanted[n]it...
...Or so Caroline said.

[msg MSG_021_2 [Caroline]]
Hey! Quit trying to pin this all on me!

[msg MSG_021_4 [Justine]]
Then, as we wallowed in despair, we came[n]across the empty bear suit.

[sel SEL_022 top]
So it was spur of the moment.
If the suit hadn't been there...

[msg MSG_023 [Justine]]
Yes, the suit was practically begging to[n]be worn.

[msg MSG_024 [Akechi]]
In a way, you two were also victims in[n]that you were manipulated by the suit...

[msg MSG_025 [Teddie]]
Wh-Wha―? It's my fault!?

[msg MSG_026 [Caroline]]
Urgh... We didn't mean to blow things so[n]out of proportion.
I'm sorry I couldn't control the suit[n]better...

[msg MSG_027 [Justine]]
Yes, we apologize for the commotion...

[msg MSG_028 [Teddie]]
It's okay. I know that it's hard to be[n]honest sometimes!
...So here you go! Ta-da!
Theodore made it for us!

[msg MSG_028_2 [Justine]]
B-But that's...!

[msg MSG_028_4 [Caroline]]
You're giving it to us!?

[msg MSG_028_6 [Teddie]]
Presents for you! Everyone's happier[n]when we share!

[msg MSG_029 [Caroline]]
*chomp* *chomp* *snarf* ...Mmph!
Th-This flavor... It's... shocking!

[msg MSG_030 [Justine]]
Yes, very... I can't... *munch* ...I[n]can't stop eating.

[msg MSG_031 [Teddie]]
Let's go say sorry and share our new[n]popcorn with everyone! I'm sure they'll[n]forgive you!

[msg MSG_032 [Caroline]]
Urgh... Well, uh... Thanks.

[msg MSG_032_2 [Justine]]
Allow me to express my gratitude as[n]well... Thank you very much.

[msg MSG_033 [Akechi]]
*chuckle* Well, case closed... I think.

[msg MSG_034 [Naoto]]
Yes, well done. Now then, we should[n]report to the box office.

