[msg MSG_000]
We hurried over to the theater lobby...

[msg MSG_001 [Akechi]]
What's this...?

[msg MSG_002 [Naoto]]
Theodore's new popcorn has been[n]scattered all over the floor...

[msg MSG_003 [Rise]]
We were all eating some of Theodore's[n]popcorn when Teddie suddenly showed[n]up...

[msg MSG_004 [Yukiko]]
He rammed into the table and sent[n]popcorn flying everywhere...

[msg MSG_005 [Naoto]]
And where did he go after that?

[msg MSG_006 [Ann]]
I think he stumbled over to the test[n]screening room...

[msg MSG_007 [Naoto]]
Stumbled?
Just to confirm... Was Teddie wearing[n]his bear suit at the time?

[msg MSG_008 [Ann]]
Yeah, he was.

[msg MSG_009 [Akechi]]
I see... This is turning into quite the[n]case.

[sel SEL_010 top]
This is a job for the detective duo.
Who's the real culprit?

[msg MSG_011 [Naoto]]
I'm honored that you would turn to me[n]for this.

[msg MSG_012 [Akechi]]
と ぼぺょ'ろ わまるを ゐまゅゅ まゆほぺるるぺれれ ゆをれまゅみ もょ みるよょろ よみ[n]ろめま みもるれろ むまょまるぺろもよょ っまろまぼろもわま はるもょぼまテ と'ゅゅ ぽよ[n]ぺゅゅ と ぼぺょ ろよ れよゅわま ろめもれ ぼぺれまテ

[msg MSG_013 [Naoto]]
We'll need to uncover the full story[n]beforehand.

[msg MSG_014 [Akechi]]
Indeed. We still haven't confirmed[n]whether Teddie was the perpetrator or[n]just another victim.

[msg MSG_015 [Chie]]
Whoa, those two really know their[n]stuff... We'd better just let them[n]handle this.

[msg MSG_016 [Naoto]]
Teddie's sudden attack and the discarded[n]bear suit... The only thing connecting[n]these events is...

[msg MSG_017 [Akechi]]
Yes... Theodore's popcorn.
The popcorn in Teddie's costume was the[n]same as what we found here.

[msg MSG_018 [Naoto]]
Correct. It seems we'll have to pay a[n]visit to Theodore's shop next.

[msg MSG_019 [Akechi]]
Agreed. Let's take a look.

