[msg MSG_000 [Teddie]]
Woo! A vine-covered door!

[msg MSG_001 [Haru]]
I suppose I'm up. I'll take a look.

[msg MSG_002 [Haru]]
There! I found one!

[msg MSG_003 [Morgana]]
Nice! How much more do we need...?

[msg MSG_004 [Haru]]
This should be enough.
Now we just need to grind these and[n]apply them to the dinosaur's wound, and[n]it should be okay.

[msg MSG_005 [Yukiko]]
I'm so glad to hear that. What do you[n]say we head back?

