[msg MSG_000 [Elizabeth]]
Oh my, it seems this next special[n]screening is a crime thriller...
There has been a series of suspicious[n]incidents in Kamo City... Your task is[n]to get to the bottom of the mystery.

[msg MSG_001 [Makoto]]
It sounds like we should step in.

[msg MSG_002 [Mitsuru]]
What sort of incidents have occurred?

[msg MSG_003 [Elizabeth]]
I only have an outline of the[n]circumstances... Frankly, I've no idea.

[msg MSG_004 [Shinjiro]]
You can't seriously be that clueless...

[msg MSG_005 [Elizabeth]]
The bulk of your task will be to uncover[n]the details of said incidents. 'Tis not[n]my job.

[msg MSG_006 [Junpei]]
Dude, if you don't even know what[n]happened, then what the heck're we[n]supposed to do...?

[sel SEL_007 top]
It's a mystery.
You tell her, Ace Detective.

[msg MSG_008 [Elizabeth]]
But of course. It is a crime thriller,[n]after all.

[msg MSG_009 [Junpei]]
I mean, she's not wrong...

[msg MSG_010 [Junpei]]
Hey, this guy's got it! Yeah, not even[n]Junpei, Ace Detective could solve this[n]one!

[msg MSG_011 [Mitsuru]]
All right, enough fooling around...

[msg MSG_011_1 [Mitsuru]]
We barely have anything to go by. What[n]should we do...?

[msg MSG_012 [Makoto]]
Well, one of the first steps in any[n]investigation is to examine the crime[n]scene.

[msg MSG_012_1 [Makoto]]
I think it'd be best if we just went out[n]and looked for clues.

[msg MSG_013 [Mitsuru]]
I see...

[msg MSG_014 [Futaba]]
Just what I'd expect from the daughter[n]of a cop. Glad we can count on you.

[msg MSG_015 [Elizabeth]]
Indeed! Examining the crime scenes will[n]surely prove useful.

[msg MSG_015_1 [Elizabeth]]
As such, I have taken the liberty of[n]marking the locations where these[n]incidents have occurred.

[msg MSG_016 [Ryuji]]
That's strangely convenient...

[msg MSG_017 [Makoto]]
I wouldn't worry about it. Let's give it[n]a try.

[msg MSG_018 [Elizabeth]]
Now then, I am greatly looking forward[n]to seeing this detective story unfold.

