[msg MSG_000 [Junpei]]
Ugh, I'm beat.

[msg MSG_000_1 [Junpei]]
It's a dead end, so we can take a little[n]break before heading back, right?

[sel SEL_001 top]
Sure, let's take a break.
If you must.
Start running.

[msg MSG_002 [Junpei]]
Aw yeah, you feel me!

[msg MSG_002_1 [Junpei]]
と ほまろ れよゆまよょま ぺれ やもょぽめまぺるろまぽ ぺれ をよゎ'れ ぺ るまぺゅ[n]めもろ ゐもろめ ろめま ゅぺぽもまれテ のる ゆぺをほま をよゎ'るま ぺゅるまぺぽを[n]むよもょ' れろまぺぽを ゐもろめ れよゆまよょまテテテ

[msg MSG_003 [Junpei]]
You're a slavedriver, man! That won't[n]get you popular with the ladies!

[msg MSG_003_1 [Junpei]]
Speaking of which, how 'bout I give you[n]some pointers...?

[msg MSG_004 [Mitsuru]]
Iori!

[msg MSG_005 [Junpei]]
Y-Yes!?

[msg MSG_006 [Mitsuru]]
If you've got time to chatter, then[n]you've clearly got energy to spare.

[msg MSG_006_1 [Mitsuru]]
So less talking, more walking! Let's go!

[msg MSG_007 [Junpei]]
Yes, ma'am...

[msg MSG_008 [Mitsuru]]
Honestly...

[msg MSG_009 [Makoto]]
Are you okay?

[msg MSG_010 [Mitsuru]]
Oh, my apologies for the outburst; it's[n]just my negligence as a leader.

[msg MSG_010_1 [Mitsuru]]
He's not a bad person at heart, but he's[n]too carefree. Or maybe he just doesn't[n]know when to get serious...

[msg MSG_011 [Makoto]]
The troubles never seem to end for us[n]older group members.

[msg MSG_012 [Mitsuru]]
Ah, right, you're a third-year as well.[n]I'd love to chat with you at some[n]point...

[msg MSG_012_1 [Mitsuru]]
But I don't want to be a hypocrite. We[n]should get going for now.

[msg MSG_013]
A new special screening: "Those Who[n]Stand at the Top" has been added to the[n]box office.

