[msg MSG_000 [P3 Fem Protag]]
Nice going, guys! That's one down!

[msg MSG_001 [Akihiko]]
Who was the winner that time? Tell us,.

[msg MSG_002 [P3 Fem Protag]]
Hmm... It's too early to say. It is best[n]of four, after all.

[msg MSG_003 [Shinjiro]]
On to the next one. Let's get this over[n]with.

[msg MSG_004 [Akihiko]]
Remember, Shinji―if I win, you're doing[n]special training with me.

[msg MSG_005 [Shinjiro]]
Hah! And if I win, you have to shut up[n]about it!

[msg MSG_006 [Mitsuru]]
My goodness... Their stupidity is beyond[n]me...
However, at this rate, I imagine we'll[n]get through this screening without too[n]much trouble. Let's keep it up.

[msg MSG_007 [P3 Fem Protag]]
Right!

