[msg MSG_000 [Elizabeth]]
Thank you for bringing the parts in.[n]Here is your reward.

[msg MSG_001 [Elizabeth]]
As promised, you may also eat all the[n]donuts you desire...
and [f 6 1 13 0 0 0], I hereby grant you the[n]privilege of joining the eating[n]competition!

[msg MSG_002 [P3 Hero]]
Doesn't look like we have the[n]"privilege" of refusing.

[msg MSG_003 [P4 Hero]]
Yeah. I'm steeling my stomach...

[msg MSG_004 [Theodore]]
Now, I will prepare the fryer. Please[n]give me a moment.

[msg MSG_005 [Theodore]]
Thank you for waiting.
The fryer is fixed, and it is now ready[n]to produce donuts aplenty.

[msg MSG_006 [Shinjiro]]
How did I get stuck on the cooking[n]crew...?

[msg MSG_007 [Theodore]]
My apologies, but I'm afraid it would[n]have been a bit much for me alone...

[msg MSG_008 [Margaret]]
Allow me to review the rules. Your[n]objective is simple...
Whoever can eat more donuts than his[n]opponent within the time limit shall be[n]declared the winner.
Are you two ready?

[msg MSG_009 [P4 Hero]]
I've come this far. There's no backing[n]out now.
...And if we're doing this, I want to[n]face you at your best.

[msg MSG_010 [P3 Hero]]
...Hopefully I'll survive it.

[msg MSG_011 [Elizabeth]]
Now... let the Wildcard challenge begin!

[msg MSG_012 [Kanji]]
I believe in you, Senpai!

[msg MSG_013 [Aigis]]
-san, I know you can do it!

[msg MSG_014 [Ann]]
Good luck, you two!

[msg MSG_015 [Elizabeth]]
One more plate of donuts here, please.

[msg MSG_016 [Margaret]]
One over here, too. Be quick about it.

[msg MSG_017 [Haru]]
The donuts are vanishing so swiftly...

[msg MSG_018 [Shinjiro]]
There ya go! Hurry up!

[msg MSG_019 [Kanji]]
Senpai! It's hot and fresh! Lemme blow[n]on it so it'll cool down!

[msg MSG_020 [Aigis]]
Then I shall use an air-conditioner[n]fan...!

[msg MSG_021 [P4 Hero]]
...Hngh...

[msg MSG_022 [P3 Hero]]
...Gh...

[msg MSG_023 [Makoto]]
They're both eating so much, but it[n]looks like it's getting tough.

[sel SEL_024 top]
Maybe some water?
Maybe change the flavor?

[msg MSG_025 [Ryuji]]
Yeah, eating nothin' but donuts would[n]get your mouth all dry...

[msg MSG_026 [Akihiko]]
No. If they drink water now, it'll all[n]expand in their stomach.
That's why they're fighting against the[n]urge to take a drink.

[msg MSG_027 [Makoto]]
True... They must be tired of eating the[n]one flavor by now...

[msg MSG_028 [Rise]]
If they want to boost their hunger,[n]maybe try something spicy! Senpai, I[n]have some superhot sauce!

[msg MSG_029 [Fuuka]]
Some sort of acid would help settle[n]their stomach, right? How about some[n]vinegar?

[msg MSG_030 [Yosuke]]
Are you trying to kill them!?

[msg MSG_031 [Margaret]]
No matter what happens, their time is[n]running out...

[msg MSG_032 [Elizabeth]]
3, 2, 1... Time's up!
Let us start the tally.

[msg MSG_033 [Junpei]]
Wh-Who won...?

[msg MSG_034 [Yosuke]]
You can't tell just by looking at the[n]plates...

[msg MSG_035 [Theodore]]
Now, I shall declare the verdict...
They appear to have eaten exactly the[n]same amount of donuts. This battle[n]concludes as a decisive draw.

[msg MSG_036 [P4 Hero]]
......

[msg MSG_037 [P3 Hero]]
......

[msg MSG_038 [Kanji]]
L-Looks like they used up all their[n]energy...

[msg MSG_039 [Margaret]]
An even match...? Well, I expected as[n]much.

[msg MSG_040 [Elizabeth]]
Yes. I daresay I'm quite satisfied.

[msg MSG_041 [Ryuji]]
If you knew it'd be a tie, then why'd[n]you make 'em go at it?

[sel SEL_042 top]
An experiment?
They just got bored.

[msg MSG_043 [Margaret]]
Indeed! We wished to test the true[n]potential of the Wildcards.

[msg MSG_044 [Margaret]]
There's no need for slander. We merely[n]aimed to test the Wildcards' potential.

[msg MSG_045 [Elizabeth]]
Yes. We now know the truth.

[msg MSG_046 [Junpei]]
That's all you wanted? Guys, I think[n]you're allowed to complain now...

[msg MSG_047 [P4 Hero]]
...Not bad, [f 6 1 16 0 0].

[msg MSG_048 [P3 Hero]]
Same goes for you, [f 6 1 13 0 0 0].

[msg MSG_049 [Junpei]]
What the―Look at them now! They ended up[n]with some weird donut connection!

[msg MSG_050 [P3 Hero]]
I kind of figured a big eating[n]competition was going to be a drag...[n]but it was fun.
I think I got to know you a little[n]better from this.

[msg MSG_051 [P4 Hero]]
Same here. I'm looking forward to[n]working together with you from now on.

[msg MSG_052 [Elizabeth]]
And so they are content to share first[n]place! Allow me to reward your efforts[n]with this trophy.

[msg MSG_053 [Yosuke]]
When did you even make this...?

[msg MSG_054 [Ann]]
Well at least we got to see them[n]compete. Now it's our turn, so bring on[n]the donuts!

[msg MSG_055 [Shinjiro]]
Uh, about that.

[msg MSG_056 [Theodore]]
We worked the machine rather hard. It[n]appears the fryer is broken again.
And this time, I fear a simple parts[n]replacement will not be enough.

[msg MSG_057 [Yusuke]]
What...? My donuts...

[msg MSG_058 [Shinjiro]]
...Relax. I'll make a couple batches of[n]donuts when we get home.

[msg MSG_059 [Teddie]]
Then let's have a donut party when we[n]get back, too!

[msg MSG_060 [P3 Hero]]
I think I'll pass on donuts for a[n]while...

[msg MSG_061 [P4 Hero]]
What a coincidence. Me too...

