[msg MSG_000 [Futaba]]
Nice! That's all of 'em! We got all the[n]parts we need!

[msg MSG_001 [P4 Hero]]
Now we just need to get it back safely.[n]We'll be there soon.

[msg MSG_002 [Fuuka]]
*giggle* I'm getting excited just[n]thinking about building it!
I haven't been able to tinker with any[n]of these mechs, so it's kind of a[n]thrill...

[msg MSG_003 [Futaba]]
Mweheheh... One step closer to evolving[n]into our new forms.

[msg MSG_004 [Fuuka]]
You know, something occurred to me when[n]we were talking about the turret's[n]tech...

[msg MSG_005 [Futaba]]
Oh, whatcha got? Lay it on me!

[msg MSG_006 [Junpei]]
Those two are real techies, huh? Sounds[n]like they even do this stuff in their[n]free time.
I figured girls usually liked, y'know...[n]shopping, and desserts, and popular[n]stuff.

[msg MSG_007 [Yosuke]]
I dunno. Chie's not really into that.

[msg MSG_008 [Chie]]
Wha―H-Hey, I do that stuff!
I've gone out to shop for steak, and[n]check out popular new fighting styles,[n]and practice them down by the river!

[msg MSG_009 [Yosuke]]
Uhh... I shouldn't have said anything.

[msg MSG_010 [Futaba]]
Okay, we can save the chatting for[n]later. Let's get you back to the[n]theater.
Wait... Oh, crap!

[msg MSG_011 [Yusuke]]
What's going on, Oracle? Is there a[n]problem?

[msg MSG_012 [Lab security]]
UNAUTHORIZED PRESENCE DETECTED.[n]UNAUTHORIZED PRESENCE DETECTED.
ALL UNITS, CONVERGE ON INTRUDERS. I[n]REPEAT, UNAUTHORIZED PRESENCE DETECTED.

[msg MSG_013 [Rise]]
Guys, this is bad! We're reading a huge[n]spike in Shadow presence! You're[n]surrounded!

[msg MSG_014 [Chie]]
Wait, seriously!? We're in some deep[n]trouble!

[msg MSG_015 [Fuuka]]
Try to stay calm. I'll analyze the[n]situation.
Rise-chan, please search for a safe[n]route.

[msg MSG_016 [Rise]]
Roger that!

[msg MSG_017 [Futaba]]
I'll check for other Shadows around the[n]area.
Guys, just stay put for a second or two.[n]We'll help guide you!
Just hang in there a little longer!

[msg MSG_018 [Mitsuru]]
Tsk. I suppose a fight is unavoidable.

[msg MSG_019 [Akihiko]]
Hmph. I'll just knock them out. I was[n]just thinking I wanted to punch[n]something!

[msg MSG_020 [Fuuka]]
The enemy's coming! Be careful!

