[msg MSG_000 [Rise]]
Good job, guys! That's the second one!
Just one more to go! You've got this!

[msg MSG_001 [P3 Fem Protag]]
You know now that I think about it, the[n]navigators are amazing.
It's not just about scanning enemies.[n]They have to keep track of all our[n]health, our positions, our powers...

[msg MSG_002 [Yosuke]]
Yeah. Without the navigation, we'd be[n]screwed... Guess we'd better be[n]thankful.

[msg MSG_003 [P3 Fem Protag]]
Y'know, I kinda want to try navigating.
I could totally shout advice. Like, "The[n]enemy's coming from behind! Never give[n]up! Trust your instincts!"

[msg MSG_004 [Naoto]]
Is that... navigating? I feel like[n]advice should be more...

[sel SEL_005 top]
Precise?
Fun?
Passionate?

[msg MSG_006 [Naoto]]
Right. It's about quick thinking,[n]analysis, AND communication.
They might not have combat abilities,[n]but they need a lot of techniques.

[msg MSG_007 [Naoto]]
Well, yes... But just focusing on having[n]fun isn't going to help a field team.
What's important is quick thinking,[n]analysis, AND communication.
They might not have combat abilities,[n]but they need a lot of techniques.

[msg MSG_008 [Naoto]]
Well, yes... But just focusing on being[n]passionate isn't going to help a field[n]team.
What's important is quick thinking,[n]analysis, AND communication.
They might not have combat abilities,[n]but they need a lot of techniques.

[msg MSG_009 [Teddie]]
That's not all! Like Sensei said,[n]they're all special in their own way!
Fuu-chan is so kind and polite! It makes[n]my bear heart go all fluttery...
But Oracle is always pumped up! I'm[n]always hyped when she's around.

[msg MSG_010 [Junpei]]
Yeah, I know what you mean... Still, out[n]of all of them, Risette's probably the[n]biggest surprise.

[msg MSG_011 [Ryuji]]
Yeah. We've got an idol backing us up![n]We're totally like VIPs over here!

[msg MSG_012 [Futaba]]
Oh yeah? Well as long as you two have[n]your idols, I guess you don't need my[n]help, huh?

[msg MSG_013 [Junpei]]
Uh―just kidding, Ms. Oracle! Sir! Uh,[n]ma'am! We're counting on you!

[msg MSG_014 [Akihiko]]
It's thanks to our navigators that we[n]can fight as hard as we do.
As long as we keep moving forward, we[n]should remember that we couldn't do[n]without them.

[msg MSG_015 [Fuuka]]
Oh no, I-I think that's a little much...

[msg MSG_016 [Rise]]
But when I hear that from you guys, it[n]makes me glad I've been trying my best[n]for you.
I mean, we want you guys to do your best[n]in battles!

[msg MSG_017 [Junpei]]
You're definitely motivating us! Keep up[n]the good work, ladies!

[msg MSG_018 [Rise]]
You got it! We'll back you up with all[n]we've got!

[msg MSG_019 [Futaba]]
Okay, enough with the lovefest here.[n]Chop chop! You guys got a part to find!

