[msg MSG_000 [Theodore]]
Eff, eff, FOE. Now that it's crushed,[n]ex-FOE...

[msg MSG_001 [Elizabeth]]
...I'm terribly sorry. It appears my[n]brother is overcome with delirium.

[msg MSG_002 [Theodore]]
You're the one who told me to do this!

[msg MSG_003 [Elizabeth]]
You have successfully executed the[n]executioner! Scrapped it to scrap metal!
It appears you can take on any obstacle[n]the enemy throws at you...
Hm...?

[msg MSG_004 [Junpei]]
Grrrraah! Junpei Iori's not outta the[n]game yet!

[msg MSG_005 [Kanji]]
Ngaaahhh! I ain't gonna lose!

[msg MSG_006 [Junpei]]
Whoa!

[msg MSG_007 [Kanji]]
Wh-Whoa!

[msg MSG_008 [Morgana]]
Yikes, that was a pretty bad fall...[n]Rest in peace, guys.

[msg MSG_009 [Akihiko]]
Hah! Careful there. Even when you're at[n]your limits, you gotta stay focused.

[msg MSG_010 [Kanji]]
Guh, hah... Not bad... Junpei-san.
Thought you... dropped out...?

[msg MSG_011 [Junpei]]
Phew... I, uh... I'm not sure, but...
I've got... someone... I gotta protect.
So... I still... gotta get stronger.

[msg MSG_012 [Kanji]]
Man, Junpei-san...
Maybe I was wrong about you. You got[n]some real grit after all.

[msg MSG_013 [Junpei]]
Huh...? Maybe that was too serious...
Bah, nevermind! I better get back to the[n]jokes. Can't just be Junpei, the[n]Straight-faced Detective!

[msg MSG_014 [Kanji]]
Man, don't get embarrassed by that! You[n]got something you wanna protect, right?
Then let's get even stronger![n]Akihiko-san can help us!

[msg MSG_015 [Junpei]]
Uh, well... Maybe that can wait until[n]next time...

[msg MSG_016 [Akihiko]]
I heard it all!
Already made you a training regimen.[n]I've got it covered!

[msg MSG_017 [Junpei]]
I said next time! Didn't you hear THAT[n]part!?

[msg MSG_018 [Kanji]]
Junpei-san... You got this! I'm cheerin'[n]for ya!

[msg MSG_019 [Akihiko]]
Don't worry, Kanji. I've made you a[n]training regimen too!

[msg MSG_020 [Kanji]]
...What?

[msg MSG_021 [Akihiko]]
Now, let's start with warmups!
One thousand squats! Go!

[msg MSG_022 [Junpei]]
Noooo!

[msg MSG_023 [Kanji]]
Wh-Why meeee!?

[msg MSG_024 [Yukiko]]
They're having so much fun. I guess this[n]is what they call "teen spirit"?

[msg MSG_025 [P3 Hero]]
And off they go into the sunset.

[msg MSG_026 [Morgana]]
I'm not sure being a teenager usually[n]involves this much screaming...

