[msg MSG_000 [Relaxed flower]]
Hehehehehe. The "black thing" was taken[n]away.

[msg MSG_001 [Cheerful Flower]]
And taken down below.

[msg MSG_002 [Relaxed Flower]]
They wanted it all to themselves.

[msg MSG_003 [Ryuji]]
と れろもゅゅ ぽゎょょよ ゐめぺろ ろめま めまゅゅ ろめまを'るま ろぺゅやもょむ[n]ぺほよゎろデ ほゎろ ろめもれ "ほゅぺぼや ろめもょむ" めぺれ むよろろぺ ほま[n]れよゆまゐめまるま ぽよゐょ ほまゅよゐデ るもむめろ?
Let's just look around that spot Hikari[n]marked on the map.

