[msg MSG_000 [Singing flower]]
Sweet passion! Like the burst of juice[n]at the first bite of fruit...
Let it drown your heart...

[msg MSG_001 [Marie]]
Beating wildly... with swirls of love,[n]with kisses of sugar, with sighs of[n]longing...

[msg MSG_002 [Junpei]]
What's next, "with eye of newt"? She[n]sounds like she's chanting a curse...

[msg MSG_003 [Marie]]
...No. This isn't right. It needs an air[n]of the forbidden!

[sel SEL_004 top]
The forbidden?
Sounds saucy!

[msg MSG_005 [Marie]]
Yes, saucy. A dark sauce that bubbles[n]forth and sweetly washes you away...
*むぺれら* づ-づよるむまろ ゐめぺろ と ゃゎれろ れぺもぽテ と ぽよょ'ろ まわまょ[n]やょよゐ ゐめぺろ れぺゎぼを ゆまぺょれテテテ まゑぼまらろデ ゅもやまデ もょ[n]みよよぽ! と ゐぺれ ろぺゅやもょむ ぺほよゎろ みよよぽ!

[msg MSG_006 [P4 Hero]]
All right, then. Let's go check out the[n]other flower.

