[msg MSG_000 [Morgana]]
Now, let's get started.

[msg MSG_001 [Yukiko]]
Ah! Oh no!

[msg MSG_002 [Morgana]]
What happened? Are we under attack!?

[msg MSG_003 [Yukiko]]
I forgot to bring our lunch... I worked[n]so hard on it...

[msg MSG_004 [P4 Hero]]
...That's very good news.

[msg MSG_005 [Yosuke]]
...Yeah. We're off to a good start.

[msg MSG_006 [Hikari]]
Elizabeth said she wanted a lunker,[n]so... a big one?

[msg MSG_007 [Yukari]]
Yeah. I guess we'll have to take a look[n]around.

