[msg MSG_000 [Ann]]
Whoa, what's that!?

[msg MSG_001 [Yusuke]]
Shh, quiet! Something's happening.

[msg MSG_002 [Sonorous voice]]
Hmhm... Hello, and welcome.
Today, I have a little diversion[n]prepared for you.
That said, it's nothing too difficult.[n]The rules are quite simple.
Up ahead, you will see two signs. Each[n]has a question printed on them.
Please answer the questions, then[n]proceed in accordance with your answers.
*chuckle* I wonder what you will think,[n]once you see where your answers will[n]lead you?

[msg MSG_003 [Ken]]
Is it gone...?

[msg MSG_004 [Ryuji]]
Who was that? An enemy?

[msg MSG_005 [Fuuka]]
Hm. I didn't sense any hostility from[n]them... It seemed like they were just[n]explaining the rules.

[msg MSG_006 [Akihiko]]
So all we have to do is answer questions[n]on signs? We'll have to see the[n]questions first...

[msg MSG_007 [Morgana]]
All right, first order of business is to[n]find those signs. Let's go, Joker.

