[msg MSG_000 [Ryuji]]
Oh, this's gotta be one of the signs!

[msg MSG_001 [Chie]]
The voice said there'd be a question on[n]it, right? Let's see...

[msg MSG_002 [Naoto]]
"You stand beside a railroad track."
"You see a speeding cart on the track.[n]Its brakes are failing."
"Ahead of the cart, you see five[n]workers. If the cart isn't stopped,[n]their lives will be in danger."
"Straight ahead, you see a lever that[n]can change the cart's course to another[n]track."
"If you change its course, you can save[n]the five workers, but there is one[n]worker on the other track."
"In this situation, would you pull the[n]lever? If yes, turn right. If no, turn[n]left."

[msg MSG_003 [Teddie]]
Cart? Track? I don't see any of those[n]around here...

[msg MSG_004 [Akechi]]
No, the sign proposes a thought[n]experiment. A classic one, at that. We[n]just need to provide an answer.

[msg MSG_005 [Mitsuru]]
Either we do nothing, and endanger five[n]people by our inaction, or kill one to[n]save the five...
Hm... The parameters are simple enough,[n]but the answer is less so.

[msg MSG_006 [Makoto]]
Yeah, there's no clear-cut right answer[n]here. We're just being asked what we[n]would do.
If we pull the lever, we go right, but[n]if we don't do anything, we go left...
It's up to you, Joker. We'll go[n]whichever way you go.

[msg MSG_007]
There's a question written on the[n]sign...
"You stand beside a railroad track."
"You see a speeding cart on the track.[n]Its brakes are failing."
"Ahead of the cart, you see five[n]workers. If the cart isn't stopped,[n]their lives will be in danger."
"Straight ahead, you see a lever that[n]can change the cart's course to another[n]track."
"If you change its course, you can save[n]the five workers, but there is one[n]worker on the other track."
"In this situation, would you pull the[n]lever? If yes, turn right. If no, turn[n]left."

