[msg MSG_000 [Caroline]]
Come on, Inmate. You'd better not hold[n]anything back!
We're practically bending the rules to[n]have this bout with you. How do you like[n]that special treatment?

[msg MSG_001 [Justine]]
I've never seen you so high in spirits,[n]Caroline.
I suppose you can be as enthusiastic as[n]you like, as long as you don't trip us[n]up.

[msg MSG_002 [Caroline]]
Wha―!? I'm not "enthusiastic"!
And look at you! You've been talking a[n]lot more than usual around him!

[msg MSG_003 [Justine]]
......
I can't imagine what you mean.

[sel SEL_004 top]
Are you two done yet?
This is adorable.

[msg MSG_005 [Caroline]]
Sh-Shut up! This is all your fault[n]anyway!

[msg MSG_006 [Justine]]
That's correct. Your very presence is...[n]disconcerting.

[msg MSG_007 [Akechi]]
Well, well. Sounds like a fixation to[n]me, Joker.

[msg MSG_008 [Caroline]]
A-Adora―whuh, I―what's that supposed to[n]mean!?

[msg MSG_009 [Justine]]
H-Hrmph. Don't bother placating us. We[n]have no mercy for you.

[msg MSG_010 [Caroline]]
Y-Yeah, th-th-that's right!

[msg MSG_011 [Akechi]]
The stuttering and blushing isn't[n]exactly helping their case.

[msg MSG_012 [Elizabeth]]
Well! This introduction is running a tad[n]long.

[msg MSG_012_1 [Elizabeth]]
I appreciate that the tsundere schtick[n]is a bit of a "slow burn," but may I ask[n]that you begin soon?

[msg MSG_013 [Justine]]
You don't have to tell us twice.
Come, Caroline. Our hot dogs await.

[msg MSG_014 [Caroline]]
Heh heh... Understood. It's time we[n]taught you a lesson, Inmate!

[msg MSG_015 [Caroline]]
Heh... Well, Inmate, you seem pretty[n]confident this time. But no matter how[n]many times you try, you'll still lose.

[msg MSG_016 [Justine]]
At least try and put up a struggle. Now,[n]let us commence.

