[msg PARTY_EDIT_SCR_MSG]
[f 0 5 65278][f 2 1]Welcome.[n][f 1 1][e]

[msg PARTY_EDIT_TUTORIAL_TOP]
[f 0 5 65278][f 2 1]This is the tutorial message on the TOP screen for "Change Party Members."[n][f 1 1][e]

[msg MSG_TUTORIAL_NAVI_OPEN_S]
[f 0 5 65278][f 2 1]Navigators have [f 0 1 2]combat-only[f 0 1 0] skills and[n][f 0 1 2]exploration-only skills[f 0 1 0]. If you separate[n]the combat and exploration navigators,[n]they can [f 0 1 2]only use the skills that[n]correspond with how you've sorted them[f 0 1 0].[n][f 1 1][e]

