[msg MSG_000 [Futaba]]
Well done in returning, my minions!

[msg MSG_001 [Ryuji]]
Well, that stuff you mentioned about the[n]door got us all curious.

[msg MSG_002 [Hikari]]
I'm so glad you're safe...

[msg MSG_003 [Ann]]
Oh, you were worried about us! Thank[n]you.

[msg MSG_004 [Hikari]]
Huh? Um...

[msg MSG_005 [Ann]]
Oh... Sorry, was it something I said?

[msg MSG_006 [Nagi]]
I'm sure that's not the case...[n]Hikari-san must not be used to all of[n]this yet, that's all.

[msg MSG_007 [Futaba]]
Hikari...

[msg MSG_008 [Hikari]]
......

[msg MSG_009 [Yusuke]]
By the way, Futaba―what's the situation[n]with the powerful unknown presence you[n]mentioned earlier?

[msg MSG_010 [Futaba]]
Yeah, about that―I'm sensing a[n]mysterious power in the test screening[n]room here.
It's an odd presence I've never felt[n]before, and I'm picking up some weird[n]noises, too.

[msg MSG_011 [Ryuji]]
Is it something dangerous, like the[n]FOEs?

[msg MSG_012 [Futaba]]
I'm pretty sure... it's different.

[msg MSG_013 [Akechi]]
You haven't any idea either, Nagi-san?

[msg MSG_014 [Nagi]]
Correct―while she claims that something[n]is in there, I have no clue what it[n]could be.

[msg MSG_015 [Yusuke]]
This is rather peculiar. We should look[n]into it ourselves.

[msg MSG_016 [Akechi]]
Who knows what we'll find on the other[n]side, though―we should be cautious.

[msg MSG_017 [Akechi]]
You two should remain here for your own[n]safety. We'll investigate this and[n]report back.

[msg MSG_018 [Nagi]]
Very well. Please don't endanger[n]yourselves.

[msg MSG_019 [Hikari]]
......

[msg MSG_020 [Ryuji]]
Okay, let's get going.

