[msg MSG_000 [Ryuji]]
Wha―"punishment exhibition"!? What the[n]hell did we do!?

[msg MSG_001 [Yusuke]]
Now I'm even more concerned for Queen[n]and Noir...
Though their capture does explain why[n]they never responded to Oracle's hails.

[msg MSG_002 [Ann]]
We don't have any idea what's going to[n]happen to those two! We have to find[n]them as soon as possible!

[msg MSG_003 [Yusuke]]
From what we just heard, they seem to be[n]held somewhere called "Kamoshida[n]Square"...

[msg MSG_004 [Akechi]]
Hold on―it's possible that we're being[n]lured into a trap.
What say you, Joker?

[sel SEL_005 top]
We're going there anyway.
Let's advance with caution.

[msg MSG_006 [Akechi]]
I have a feeling there wasn't any point[n]in asking...

[msg MSG_007 [Ann]]
Oracle, can you tell where this square[n]is?

[msg MSG_008 [Futaba]]
Hmm, I don't think I can... Looks like[n]you'll just have to keep up the[n]progress.

[msg MSG_009 [Morgana]]
There are also those wanted posters we[n]saw... That means we're already being[n]targeted.
We'll need to proceed with even more[n]caution from here on. Lead the way,[n]Joker!

[sel SEL_010 top]
You got it.
Leave it to me.
I don't feel so good...

[msg MSG_011 [Morgana]]
Excellent! We're counting on you.

[msg MSG_012 [Morgana]]
Ooh, so confident!

[msg MSG_013 [Morgana]]
Why're you getting cold feet now!? Queen[n]and Noir are counting on us!

[msg MSG_014 [Yusuke]]
Don't worry. We've got your back.

[msg MSG_015 [Ann]]
Yeah, I'm positive we can do this. Let's[n]go save those two!

[msg MSG_016 [Morgana]]
All right―Phantom Thieves, move out!

