[msg MSG_000 [Yusuke]]
It seems that we can use our Personas[n]here without any issues after all.

[msg MSG_001 [Ryuji]]
Yeah, but somethin' still feels off...[n]It's like I'm not as strong or as fast[n]as I used to be.

[msg MSG_002 [Akechi]]
Well, we are in a different world now―[n]perhaps we have to start over here.

[msg MSG_003 [Ann]]
By the way, what should we do with this[n]stuff? They're some shards of those[n]Shadows we defeated...

[msg MSG_004 [Yusuke]]
Hm, I haven't the faintest idea of their[n]worth. If only we could somehow use[n]them...

[msg MSG_005 [Futaba]]
Uh, Nagi says she'll buy them at the[n]concession stand when you guys get back[n]here.

[msg MSG_006 [Ann]]
For real? Then we'll be able to afford[n]all sorts of things at the stand! Let's[n]keep taking down Shadows!

[msg MSG_007]
Perhaps I should sell these shards next[n]time I'm at the concession stand...

