[msg MSG_000]
Citizens of Kamo City!

[msg MSG_000_1]
I have finally arrived!

[msg MSG_000_2]
There have been some delays due to[n]dealing with those accursed thieves...

[msg MSG_000_3]
But, the time for the punishment[n]exhibition has come!

[msg MSG_001]
No...

[msg MSG_002]
I won't give up just yet...

[msg MSG_003]
Now, let's start the countdown!

[msg MSG_003_1]
Those who threaten our peace are to be[n]punished by my own hand!

[msg MSG_004]
FIVE!

[msg MSG_006]
FOUR!

[msg MSG_008]
This is bad...

[msg MSG_009]
We're running out of time...

[msg MSG_010]
THREE―

[msg MSG_011]
Hm!? What's all this!?

[msg MSG_012]
A blackout?

[msg MSG_013]
Is this part of the show?

[msg MSG_014]
Turn on the backup power! Hop to it!

[msg MSG_015]
Wha―!?

[msg MSG_016]
You scoundrels disturbing Kamo City...[n]So you've come to be punished!

[msg MSG_016_1]
As you well know, my justice makes me[n]invincible!

[msg MSG_016_2]
HAHAHAHA!

[msg MSG_017]
Kamoshidaman―there's a piece of paper on[n]your back!

[msg MSG_017_1]
It says it's... a calling card!

[msg MSG_018]
A calling card!?

[msg MSG_019]
"We will take the Kamoshidaman[n]statue...!?"

[msg MSG_020]
Wha―!?

[msg MSG_020_1]
Whaaaaaaaat!?

[msg MSG_021]


