[msg MSG_000 [Ryuji]]
*gasp* *pant* We should be fine... Now[n]that we're back...

[msg MSG_001 [Futaba]]
Good job on the escape, guys! Your moves[n]were especially awesome,!

[msg MSG_002 [P3 Fem Protag]]
*pant* *pant* I... I was barely able to[n]keep up.

[msg MSG_002_5 [P3 Fem Protag]]
I'm amazed with everyone's speed... I[n]was like, "So THIS is what the Phantom[n]Thieves can do!"

[msg MSG_003 [Morgana]]
Heh, that's nothing to be surprised[n]over. Our real power comes from―

[msg MSG_004 [Ryuji]]
Gah, that Kamoshidaman bastard! His[n]powers are such bullshit!

[msg MSG_005 [Morgana]]
Hey, I was talking!

[msg MSG_006 [Ann]]
Man, he just froze us in our tracks...[n]That was all thanks to the statue,[n]right?

[msg MSG_007 [Futaba]]
Yeah, he really flipped his wig when[n]Makoto and Haru called him out―that's[n]definitely it!

[msg MSG_008 [Yusuke]]
He's finally revealed his true colors...[n]We need to find a way to counter or[n]disable the statue's ability.

[msg MSG_009 [Futaba]]
Kamoshidaman's guarding it, though.[n]First we have to figure out how to get[n]past him.

[msg MSG_010 [Ryuji]]
Should we try blowing it up?

[msg MSG_011 [Yusuke]]
Where would we get a bomb? That would[n]probably also harm any citizens in the[n]vicinity.

[msg MSG_012 [Morgana]]
Hmm... How do you think we should disarm[n]the statue, [f 6 1 30 0 0 0]?

[sel SEL_013 top]
Ram it with a truck.
Have Queen and Noir do it.
Let's steal the thing.

[msg MSG_014 [Ryuji]]
What kind of crazy plan is that!? Are[n]you a Wild Max driver too, now!?

[msg MSG_015 [Yusuke]]
That approach isn't at all artful...

[msg MSG_016 [Morgana]]
Right. We're the Phantom Thieves,! We[n]need to be more stylish than that―
Hm... Wait a second... Why don't we do[n]what we Phantom Thieves do best and[n]steal it?

[msg MSG_017 [P3 Fem Protag]]
Well, they're tied up right now, so[n]wouldn't that plan be kind of...[n]impossible?

[msg MSG_018 [Ryuji]]
If we can't destroy the statue, then[n]could we charge in with a truck and drag[n]it off?

[msg MSG_019 [Ann]]
Will you stop resorting to force so[n]quickly!?

[msg MSG_020 [Morgana]]
Then... Why don't we do what we Phantom[n]Thieves do best and steal it?

[msg MSG_021 [Morgana]]
Ooh―I was just thinking that!

[msg MSG_022 [Ryuji]]
Steal it, huh? Kickass! So, what's the[n]scheme?

[msg MSG_023 [Morgana]]
Obviously, we still have to come up with[n]that part.

[msg MSG_024 [Ann]]
Even if we get near the statue, it's[n]gotta be awfully heavy... Will we even[n]be able to steal it?

[msg MSG_025 [Akechi]]
Ah, I don't think we need to worry about[n]its weight. Do you remember its peculiar[n]behavior?

[msg MSG_027 [Yusuke]]
Yes―despite its size, it swayed back and[n]forth.

[msg MSG_028 [Ryuji]]
Oh yeah, you're right! I mean, ain't it[n]weird for such a massive thing to move[n]like that?

[msg MSG_029 [Yusuke]]
びめま れろぺろゎま ぼよゎゅぽ ほま ぽまれもむょまぽ ろよ ぺららまぺる ぺれ もみ[n]もろ'れ ゆぺぽま よみ れろよょまデ ゐめまょ もろ'れ るまぺゅゅを ぼよゆらるもれまぽ[n]よみ みよぺゆ よる れよゆまろめもょむ れもゆもゅぺるテ
We may have been deceived by its[n]appearance―that statue could very well[n]be quite light.

[msg MSG_030 [Akechi]]
In fact, it moved quite a bit during our[n]battle, and that was just from the wind[n]passing by.

[msg MSG_031 [Ryuji]]
So it's a fake!? Talk about a fitting[n]power source for such a fake hero!
Like, what's even the point of lighting[n]up a phony-ass statue!?

[msg MSG_032 [Yusuke]]
The citizens must gain some peace of[n]mind through its reverence―no matter how[n]false it may be.

[msg MSG_033 [P3 Fem Protag]]
That's a good point. Everyone in the[n]movie blindly follows Kamoshidaman.

[msg MSG_034 [Morgana]]
Now, onto how to steal it...

[msg MSG_035 [Ann]]
It's all lit up in the center of the[n]square... Just getting near it will draw[n]too much attention to us.

[msg MSG_036 [P3 Fem Protag]]
Does that mean it'd be easier to steal[n]if we turned those lights off?

[msg MSG_037 [Morgana]]
Well, that's obvious...
But then the question is, where's the[n]light switch?

[sel SEL_038 top]
Is it in Kamoshida Square?
Down the FOE-infested path.
Let's just blow all of it up.

[msg MSG_039 [Ann]]
Hmm, did we spot anything like that when[n]we were there?

[msg MSG_040 [Yusuke]]
No, it's not at the square. I do have an[n]idea of where it may be, though...

[msg MSG_040_5 [Yusuke]]
There was that path earlier, the one[n]that led to an area infested with FOEs.

[msg MSG_041 [Ryuji]]
Oh, you mean the one from Yusuke's[n]little chant?

[msg MSG_042 [Yusuke]]
A path leading to an area infested with[n]FOEs. I find that rather suspicious,[n]too.

[msg MSG_043 [Ryuji]]
Ooh! That sure would make things[n]easy―Wait, just how violent are you!?
It's obviously way easier to just switch[n]it off!

[msg MSG_044 [Yusuke]]
I have an idea about the location of[n]that switch...
Remember the path leading to an area[n]infested with FOEs?

[msg MSG_045 [P3 Fem Protag]]
Oh right, the policemen passing by there[n]said something about lighting...

[msg MSG_046 [Akechi]]
They were discussing how the lighting[n]needed to be flashier for the[n]exhibition.
Due to the importance of the lighting,[n]one can imagine its security being[n]extremely tight.

[msg MSG_047 [Ryuji]]
So, we'll find the lighting controls[n]somewhere past that crowd of FOEs!

[msg MSG_048 [Yusuke]]
That seems likely... So, there is indeed[n]something worthwhile beyond the thorny[n]path.

[msg MSG_049 [Morgana]]
Okay, let me recap...
In order to rob Kamoshidaman of his[n]powers, we need to steal that statue...
But, to approach it, we have to power[n]down its lighting first.
The lights' power source is most likely[n]beyond that swarm of FOEs... Does that[n]cover it?

[msg MSG_050 [Akechi]]
It'll probably be quite dangerous, but[n]we don't have any time to spare―we'll[n]just have to get it done.

[msg MSG_051 [Futaba]]
Okay, then you guys head back to that[n]crossroad...
And I'll keep up the navigation for[n]you,!

