[msg MSG_000 [Futaba]]
Chicos, 夷c吋mo est茨n? 夷Se est茨n cansados?
Vamooos... Respondaaaan, Ladrones[n]Fantasmaaa...

[msg MSG_001 [Yusuke]]
No nos subestimes. Esto es…

[msg MSG_002 [Yusuke]]
...Mm. Creo que tengo hambre.

[msg MSG_003 [Morgana]]
Vamos... No te desmalles antes de[n]ocuparnos de Enlil, 夷entendido?

[msg MSG_004 [Haru]]
斡Yo no estoy cansada! 夷Y ustedes?

[msg MSG_005 [Ann]]
Estoy bien... Esto no es nada para un[n]ladr吋n fantasma. 夷Y t雨, Hikari?

[msg MSG_006 [Hikari]]
Yo tambi姻n estoy bien. Sol胤a caminar[n]mucho mientras cargaba una c茨mara[n]bastante pesada.

[msg MSG_007 [Ryuji]]
Mm... Sabes, Hikari, est茨s mucho m茨s[n]animada 雨ltimamente.

[msg MSG_008 [Hikari]]
夷Eh? 夷A-a qu姻 te refieres?

[msg MSG_009 [Ryuji]]
夷Recuerdas cuando nos contaste qu姻 tipo[n]de pel胤culas te gustan?
Desde que dijiste que te gustan las pel胤culas[n]que le dan esperanza a la gente, pareces una[n]persona completamente diferente.

[msg MSG_010 [Hikari]]
Bueno, es que... Finalmente, record姻 el[n]sue隠o que quiero alcanzar, solo ten胤a[n]que decirlo.

[msg MSG_011 [Ryuji]]
夷Cu茨l es tu sue隠o?

[sel SEL_012 top]
夷Ser directora?
夷Ser curadora?

[msg MSG_013 [Haru]]
As胤 es. Hikari dijo que quer胤a hacer[n]peliculas desde que era joven.

[msg MSG_014 [Hikari]]
Eso ser胤a bastante agradable, ya que estar胤a[n]rodeada de pel胤culas todo el tiempo, pero lo[n]que realmente quiere es hacerlas.

[msg MSG_015 [Haru]]
Tu sue隠o es convertirte en directora,[n]夷no? Mencionaste que quer胤as hacer[n]pel胤culas desde que eras joven.

[msg MSG_016 [Hikari]]
He estado filmando pel胤culas por mi[n]cuenta desde que era ni隠a porque quer胤a[n]convertirme en directora...

[msg MSG_017 [Ann]]
Whoa, 斡Eso es incre胤ble! 夷Grabas tus[n]propias pel胤culas?

[msg MSG_018 [Hikari]]
No es nada impresionante... Aprend胤[n]viendo a otros hacerlo.

[msg MSG_019 [Makoto]]
No hay por qu姻 ser modesta.
Todo el mundo tiene un sue隠o, pero,[n]intentar cumplirlo, no es algo que todo[n]el mundo se atreve.

[msg MSG_020 [Yusuke]]
Mm... 夷Qu姻 tipo de pel胤culas hac胤as?

[msg MSG_021 [Hikari]]
N-no he filmado nada recientemente.
Perd胤 de vista... lo que quer胤a[n]mostrarle a todos... e incluso de qui姻n[n]soy.

[msg MSG_022 [Futaba]]
Hikari...

[msg MSG_023 [Hikari]]
Pero ahora lo recuerdo, gracias a que[n]los conoc胤. Las pel胤culas que amaba...
Y las pel胤culas que realmente quer胤a[n]hacer... 斡Por eso estoy pensando en[n]volver a filmar!

[sel SEL_024 top]
Me encantar胤a echarte una mano.
Suena genial.
D姻jame ser la estrella de tu primera[n]pel胤cula.

[msg MSG_025 [Ryuji]]
斡Yo tambi姻n! 斡Vamos a hacer realidad el[n]sue隠o de Hikari!

[msg MSG_026 [Morgana]]
斡S胤! 斡Estoy seguro de que puedes hacer[n]realidad ese sue隠o ahora, Hikari!

[msg MSG_027 [Morgana]]
斡Oye, no te robes el protagonismo! 斡Yo[n]voy a ser la estrella!

[msg MSG_028 [Ryuji]]
夷Un gato actuando? Eso ser胤a bastante[n]raro.

[msg MSG_029 [Morgana]]
斡No ser胤a un gato actuando! 斡Lo har胤a[n]despu姻s de convertirme en humano!

[msg MSG_030 [Makoto]]
Oh... No empecemos con tonter胤as.
Volviendo al tema, creo que est茨s lista[n]para salir al mundo y hacerlo, Hikari.[n]Sigue tu sue隠o.

[msg MSG_031 [Hikari]]
Gracias.
Tambi姻n... Cuando termine mi primera[n]pel胤cula, quiero que mi padre la vea.

[msg MSG_031_5 [Hikari]]
Definitivamente, quiero darle esta[n]invitaci吋n pronto... Esta vez ser茨 en[n]serio.

[msg MSG_032 [Haru]]
Ya veo... Estoy segura de que lo har茨s.

[msg MSG_033 [Ryuji]]
Oye, 夷esa invitaci吋n solo aplica para tu[n]padre?

[msg MSG_034 [Hikari]]
夷Eh?

[msg MSG_035 [Ryuji]]
Bueno, nos gustar胤a ver tu pelicula[n]tambi姻n, 夷verdad?

[sel SEL_036 top]
Por supuesto.
Tambi姻n estoy interesado.
夷Podemos verla tambi姻n?

[msg MSG_037 [Ann]]
Oh, por favor 夷O es pedir demasiado?

[msg MSG_038 [Hikari]]
斡Oh, no! 斡No lo es! 斡Me encantar胤a que[n]ustedes la vieran!
夷D-de verdad ir胤an a ver mi pel胤cula?

[msg MSG_039 [Ryuji]]
斡Por supuesto! 斡Estoy convencido!

[msg MSG_040 [Futaba]]
No solo Skull, todos los Ladrones...[n]斡Los ladrones estar茨n all胤!

[msg MSG_041 [Hikari]]
斡Prometo que terminar姻 la pel胤cula, no[n]importa que haga falta!

[msg MSG_042 [Makoto]]
*risa* Bueno, para que eso suceda,[n]tenemos que acabar con este lugar[n]primero.

[msg MSG_043 [Ryuji]]
斡Cierto! 斡Vamos a ocuparnos de nuestros[n]asuntos aqu胤, as胤 Hikari podr茨 filmar de[n]vuelta a casa!

