[msg MSG_000 [Yukari]]
夷En serio? 斡夷Qu姻 hace ESO aqu胤?!

[sel SEL_001 top]
Es de un rollo diferente.
Es una repetici吋n.
夷Tal vez se actualiz吋?

[msg MSG_002 [Aigis]]
S胤, debe ser correcto.

[msg MSG_003 [Akihiko]]
Pero cambiamos esta pel胤cula. Incluso si[n]fuera una repetici吋n, no tiene sentido.

[msg MSG_004 [Junpei]]
Oh, 斡Vamos! 斡夷Despu姻s de todo lo que[n]pasamos?!

[msg MSG_005 [Aigis]]
Creo que esta es muy diferente a la[n]pel胤cula que arreglamos.

[msg MSG_006 [P3 Hero]]
Desde que cambiamos la conciencia de[n]Hikari, esta pel胤cula deber胤a estar[n]corregida...

[msg MSG_007 [Akihiko]]
Pero la pel胤cula sigue distorsionada,[n]eh...
Si la dejamos as胤, todos ser茨n forzados[n]a seguir viendo la versi吋n de mierda.

[msg MSG_008 [Junpei]]
Tenemos que hacer algo, 斡Vamos a[n]arreglar esta tambi姻n!

[msg MSG_009 [Madre Computadora]]
ねよ まょろもまょぽよテ つれろぺ らまゅウぼゎゅぺ るまらるまれまょろぺ まゅ[n]らぺるぺぽもむゆぺ ぽま ろよぽぺ ゅぺ れよぼもまぽぺぽ めゎゆぺょぺデ を をよ れよを[n]まゅ らぺるぺぽもむゆぺ ぽま ゎょ むよほまるょぺょろま ゆゎょぽもぺゅテ
Tu negaci吋n a esta popular pel胤cula los[n]convierte en un error en este mundo.

[msg MSG_010 [Ken]]
No es como si estuvieran disfrutando la[n]pel胤cula. 斡Simplemente, no tienen la[n]opci吋n de ver algo mejor!

[msg MSG_011 [Shinjiro]]
Esta mierda no es diferente de lavarles[n]el cerebro.

[msg MSG_012 [Madre Computadora]]
Esto no es lavar cerebros... es[n]simplemente el sistema adecuado para el[n]mundo.
Si todo el mundo elimina su[n]individualidad y siguen un modelo, las[n]peleas innecesarias dejar茨n de existir.

[msg MSG_013 [Yukari]]
No hagas que suene como si estuvieras[n]haciendo lo correcto. 斡Est茨s forzando[n]tus tonter胤as a los dem茨s!

[msg MSG_014 [Akihiko]]
Tiene raz吋n. A veces, la 雨nica manera de[n]entender algo es a trav姻s de una forma[n]de conflicto.

[msg MSG_015 [Mitsuru]]
斡Lo que est茨s pidiendo abandonar nuestra[n]capacidad de pensar por nosotros mismos!

[msg MSG_016 [Madre Computadora]]
Defender el individualismo y alteraci吋n[n]del orden mundial... Claramente son unos[n]herejes.
Son herejes. Irregularidades. Errores.[n]Bugs.

[sel SEL_017 top]
Es nuestra decisi吋n, no la tuya.
夷Y qu姻 pasa con eso?

[msg MSG_018 [Aigis]]
斡Es correcto! No importa lo que digas,[n]ser姻 yo misma...
斡Y eso no pondr茨s cambiarlo!

[msg MSG_019 [Koromaru]]
斡Guau!

[msg MSG_020 [Madre Computadora]]
Han sido clasificados como errores[n]fatales... Cualquier otra comunicaci吋n[n]es innecesaria.

[msg MSG_021 [Fuuka]]
斡Cuidado! 斡Aqu胤 viene!

