[msg MSG_000_5]
＞ｅ５００＿３４５ポ7:割q〒ベン: フムルムが見せr希望

[msg MSG_000 [Kamoshidaman]]
He sido... tan malo todo este tiempo.
He abusado de mi poder, creyendo que[n]oprimir a mis ciudadanos beneficiarボa a[n]toda la sociedad...
ムEs este poder... no debo confundir el[n]propポsito de mi autoridad!

[msg MSG_001 [Kamoshidaman]]
ムJA, JA, JA!
ムEl nuevo Kamoshidaman nunca maltratarホ[n]a un ciudadano de nuevo!

[msg MSG_002 [Yosukesaurio]]
メA qui〒n le importa si pensamos[n]diferente? Solo tenemos que hablarlo, de[n]corazポn a corazポn.

[msg MSG_003 [Yosukesaurio]]
Sheesh, todos hablan a la vez. Esta[n]conversaciポn llegarホ a ninguna parte...
Aunque, es bastante divertido decidir[n]cポmo hacer las cosas de esta forma.
Es agradable tener compaワeros con los[n]que puedas ser sincero.

[msg MSG_004 [Ribbon]]
YO SOY... yo misma.
Soy Ribbon, amante de las flores y de[n]todos en mi vida...

[msg MSG_005 [Ribbon]]
Creo que las flores son agradables... Creo que[n]las flores son bonitas... Todo el mundo tiene[n]su opiniポn sobre estas cosas...
Ser diferente no es un error. Intentar〒[n]ser soy yo misma...

[msg MSG_006 [Hikari De Instituto]]
Trat〒 de convencerme de que no tenボa[n]otra opciポn, que ser quien todos querボan[n]que fuera era lo correcto...
Y seguボa viendo esas pelボculas[n]distorsionadas para hacerme olvidar[n]qui〒n era realmente por dentro...
ムPero ya no huir〒 de mボ misma! ムVoy a[n]cambiar esta pelボcula y salir de aquボ!

[msg MSG_007 [Hikari De Instituto]]
Papホ... ムJuro que algマn dボa te enviar〒[n]esa invitaciポn!

