[msg MSG_000 [Hikari De Instituto]]
Trat姻 de convencerme de que no ten胤a[n]otra opci吋n, que ser quien todos quer胤an[n]que fuera era lo correcto...
Y segu胤a viendo esas pel胤culas[n]distorsionadas para hacerme olvidar[n]qui姻n era realmente por dentro...

[msg MSG_000_2 [Hikari De Instituto]]
斡Pero ya no huir姻 de m胤 misma! 斡Voy a[n]cambiar esta pel胤cula y salir de aqu胤!

[msg MSG_001 [Hikari De Instituto]]
Pap茨... 斡Juro que alg雨n d胤a te enviar姻[n]esa invitaci吋n!

