[msg MSG_000 [Rise]]
斡Bien, las cuatro pel胤culas cambiadas!

[msg MSG_001 [Naoto]]
Todo lo que queda es reproducir la[n]nuestra en esos cines.

[msg MSG_002 [Kanji]]
Entonces, 夷terminamos una vez que Oracle[n]active el interruptor?

[msg MSG_003 [Morgana]]
Deber胤a, s胤...

[msg MSG_004 [Hikari]]
Todav胤a hay algo que necesito hacer.

[msg MSG_005 [Akechi]]
夷Qu姻? 夷Olvidamos algo?

[msg MSG_006 [Hikari]]
Todav胤a quiero hablar con Nagi... con[n]Enlil.

[msg MSG_007 [Ann]]
斡夷QU畏?!

[msg MSG_008 [Hikari]]
La gente que est茨 atrapada ahora podr茨[n]salir...
Pero creo que m茨s gente seguir asiendo[n]arrastrada por ella.

[msg MSG_009 [Yukari]]
Bueno, estamos hablando de las[n]reacciones de las personas al dolor.[n]Estos problemas nunca van a desaparecer.

[msg MSG_010 [Hikari]]
Al final, despu姻s de cambiar a los que est茨n[n]ahora... Enlil seguir胤a mostr茨ndoles las[n]pel胤culas que ella quiera a los nuevos.
Entonces, esto ser茨 in雨til, as胤 que...[n]Quiero decirle a Enlil lo que siento[n]antes de irnos.

[msg MSG_010_5 [Hikari]]
Quiero que sepa que puede hacer lo[n]correcto, y darles esa verdadera[n]"salvaci吋n".

[sel SEL_011 top]
Deber胤amos hacerlo.
Puede que no te escuche...
Haz lo que quieras.

[msg MSG_012 [Hikari]]
Mmm... Definitivamente quiero[n]intentarlo.
Despu姻s de todo, ustedes me ense隠aron a[n]no rendirme.

[msg MSG_013 [Akechi]]
Cierto. Es probable que terminemos[n]luchando contra ella.

[msg MSG_014 [Hikari]]
Aun as胤... No quiero arrepentirme, de no[n]haberlo intentado.

[msg MSG_015 [Morgana]]
Parece firme con tus decisiones, Hikari.[n]斡Nada mal!

[msg MSG_016 [Hikari]]
Bueno, ustedes me ense隠aron a no[n]rendirme.

[msg MSG_017 [Akechi]]
夷Te escuchar茨? Es probable que[n]encontrarnos con ella resulte en otra[n]pelea.

[msg MSG_018 [Hikari]]
Aun as胤... No quiero arrepentirme, de no[n]haberlo intentado.

[msg MSG_019 [Morgana]]
Parece firme con tus decisiones, Hikari.[n]斡Nada mal!

[msg MSG_020 [Hikari]]
Bueno, ustedes me ense隠aron a no[n]rendirme.

[msg MSG_021 [P3 Fem Protag]]
斡Ja, ja, ja! 斡Eso es verdad!

[msg MSG_022 [Ryuji]]
Bueno, ese plan suena bien. Vamos a[n]mostrarle a Enlil lo que pasa.

[msg MSG_023 [Akihiko]]
S胤, ella ya no me asusta.

[msg MSG_024 [Teddie]]
斡Yo tambi姻n, yo tambi姻n! 斡Me quedar姻[n]hasta el final!

[msg MSG_025 [Shinjiro]]
No llegamos tan lejos para dejar las[n]cosas a medias...
No hay manera de que nos vallamos sin[n]mostrarle que vamos en serio.

[msg MSG_026 [Hikari]]
Chicos...

[sel SEL_027 top]
Hag茨moslo.
Discutamos los detalles de ese plan.

[msg MSG_028 [P3 Hero]]
Tantas esperanzas en juego... Los[n]futuros de tantas personas.

[msg MSG_029 [P4 Hero]]
夷Est茨n todos listos?

[msg MSG_030 [Yosuke]]
斡S胤, como siempre!

[msg MSG_031 [Junpei]]
斡Yo tambi姻n! Si me rindiera ahora, me[n]sentir胤a menos hombre.

[msg MSG_032 [Mitsuru]]
Todos parecen estar preparados.

[msg MSG_033 [Koromaru]]
斡Guau!

[msg MSG_034 [Fuuka]]
Adelante y prep茨rate lo mejor que[n]puedas, estaremos aqu胤 para brindarte[n]apoyo.

[msg MSG_035 [Futaba]]
Escuchen: vamos a enfrentarnos a Enlil.[n]Aseg雨rense de estar completamente[n]preparados, 夷de acuerdo?
Cuando creas estar listo, encontraremos[n]a Enlil y Hikari le dir茨 lo que piensa.

