[msg MSG_000 [P4 Protag]]
メQu〒 es este cuarto?

[msg MSG_001 [Ken]]
Mira una mホquina enorme... メEs un[n]proyector?

[msg MSG_002 [Aigis]]
Eso parece. Confirmado cuatro de ellos[n]dentro de mi rango de visiポn.

[msg MSG_003 [Kanji]]
メNo hay algo raro en la luz que emite de[n]ese proyector?
Los colores parecen... mal. メLa pelボcula[n]estホ daワada?

[msg MSG_004 [Akechi]]
Parece que estホn proyectando los[n]negativos de la pelボcula.

[msg MSG_005 [Hikari]]
Asボ es. La razポn por la que los negativos[n]hacen que la gente se sienta mal es la[n]inversiポn de colores que cambia la luz y la[n]oscuridad...
La pelボcula se desinvierte durante la[n]impresiポn, al final, los colores salen[n]como los ves normalmente en la pantalla.

[sel SEL_006 top]
Oh, Entiendo...
メQu〒 mホs sabes de esto?
*Ronquido*

[msg MSG_007 [Futaba]]
No puede evitarlo, es una entusiasta.[n]Solo s〒 amable, sonrボe, asiente... Ahボ[n]lo tienes.

[msg MSG_008 [Futaba]]
ムOye, no te duermas! Tienes que[n]escucharla hasta que termine.

[msg MSG_009 [Hikari]]
Dado que cualquier pelボcula invertida se[n]llama "negativa", las que se invierten[n]de nuevo son "positivas".
Tambi〒n existe algo llamado "pelボcula de[n]inversiポn" que graba imホgenes positivas de[n]inmediato, en lugar de imホgenes negativas...
Pero las pelボculas tienden a ser filmadas en[n]negativo porque las correcciones y la[n]duplicaciポn son mホs fホciles de esa forma.

[msg MSG_010 [Ryuji]]
B-bien. No entendボ nada de eso.

[msg MSG_011 [Hikari]]
Oh...

[msg MSG_012 [Naoto]]
Pareces ser una experta en esto, Hikari.

[msg MSG_013 [Hikari]]
メEh? Oh, mm... supongo que me pongo muy[n]nerviosa cuando hablo de pelボculas...

[msg MSG_014 [Shinjiro]]
Estホ bien. Hablar sobre algo que te[n]gusta es normal.

[msg MSG_015 [Morgana]]
Imホgenes negativas y positivas... メNo te[n]recuerdan algo, Joker?

[sel SEL_016 top]
Las emociones negativas.
Emociones positivas.
No s〒 a qu〒 te refieres.

[msg MSG_017 [Morgana]]
ムExactamente... eso!

[msg MSG_018 [Akechi]]
Basホndonos en nuestra experiencia,[n]ciertamente parecen conceptos[n]anホlogos...

[msg MSG_019 [Akechi]]
Creo que se refiere a emociones humanas[n]positivas y negativas. Ciertamente[n]parecen conceptos anホlogos...

[msg MSG_020 [Chie]]
S-sボ, "conceptos anホlogos"... Asボ como,[n]eh... carrillera de cerdo y trasero de[n]cerdo, メverdad?

[msg MSG_021 [Yosuke]]
メSabes siquiera de que estホ hablando? メY[n]la carne es realmente la マnica cosa en[n]tu mente?

[msg MSG_022 [Haru]]
Bueno, por ejemplo, la gente alegre se[n]llamarボa "positiva", mientras que la gente[n]sombrボa se conocerボa como "negativa"...

[msg MSG_023 [Yosuke]]
Entiendo. Esto estホ empezando a tener[n]sentido ahora.

[msg MSG_024 [Yusuke]]
Lo que realmente necesitamos determinar[n]es dポnde estホn proyectando estos[n]negativos.

[msg MSG_025 [Rise]]
Mmm... メCrees que tiene algo que ver con[n]la pelボcula en la que estホs caminando?

[msg MSG_026 [Yukari]]
Oh, buen punto. メEsta pelボcula del piso[n]no es mホs de las negativas?

[msg MSG_027 [Fuuka]]
Parece venir de todo tipo de[n]direcciones. Seguiremos investigando.
Si averiguamos algo, les avisaremos[n]enseguida.

[msg MSG_028 [Mitsuru]]
Por favor, hホganlo.
Parece que deberボamos dejarle esto a[n]nuestras navegadoras. Tenemos nuestras[n]propias tareas aquボ.

[msg MSG_029 [Ken]]
ムSボ, vamos a movernos!

