[msg MSG_000 [Yusuke]]
Este lugar parece estar quedado intacto.

[msg MSG_001 [Naoto]]
Sボ, aunque, sospecho que es solo[n]cuestiポn de tiempo.

[msg MSG_002 [Elizabeth]]
Felicitaciones.
Mis palabras, ese fue un final realmente[n]impresionante. ムBravo!

[msg MSG_003 [Morgana]]
メS-seワorita Elizabeth? メSu ropa volviポ a[n]la normalidad?

[msg MSG_004 [Theodore]]
Nuestro papel aquボ ha terminado.
Mホs importante aマn, debo compartir lo[n]impresionado que estoy con ustedes. Han[n]llevado este festival de cines a su final.

[msg MSG_005 [Caroline]]
Bien... Finalmente, podemos volver a[n]nuestras tareas habituales.

[msg MSG_006 [Justine]]
Asボ que, debemos compensar el tiempo[n]perdido...
Pero por ahora, har〒 una excepciポn マnica[n]y te felicitar〒 Recluso, buen trabajo.

[sel SEL_007 top]
No fue nada especial.
Supongo que las sorprendボ.
Mホs alabanzas, por favor.

[msg MSG_008 [Caroline]]
Hmph, una respuesta respetable...[n]ムMant〒n esa actitud mientras te enfocas[n]en tu rehabilitaciポn, Recluso!

[msg MSG_009 [Caroline]]
ムHmph, no te pongas arrogante! ムConoce[n]tu lugar, Recluso!

[msg MSG_010 [Caroline]]
ムNo te confボes, Recluso! ムIncluso un[n]cerdo puede volar si se calienta lo[n]suficiente!

[msg MSG_011 [Junpei]]
メ"I-incluso un cerdo puede volar"? メSe[n]supone que eso es una amenaza?

[msg MSG_012 [Akihiko]]
La carne de cerdo estホ llena de vitamina[n]B1. メNo significa que en realidad lo[n]estホ elogiando?

[msg MSG_013 [Justine]]
Caroline, メno es "Incluso un cerdo puede[n]trepar un ホrbol si lo intenta lo[n]suficiente"?

[msg MSG_014 [Caroline]]
ムC-cホllate! ムSabes a qu〒 me refiero!

[msg MSG_015 [Yukari]]
Entonces, メrealmente podemos ir a casa[n]esta vez?

[msg MSG_016 [Shinjiro]]
メCポmo lo hacemos? No hay ninguna salida.

[msg MSG_017 [Theodore]]
No hay motivo para preocuparse, por[n]favor.

