[msg MSG_001 [Junpei]]
En serio vamos a meternos con esos[n]proyectores, 夷eh? Supongo que estaremos[n]en problemas si Enlil nos descubre...

[msg MSG_002 [Rise]]
Ella no es alguien que nos escuchar胤a.[n]Si nos atrapa en el acto, realmente nos[n]la pondr茨 dif胤cil esta vez...

[msg MSG_003 [Teddie]]
斡Vamos, es hora de ser un ladr吋n fantasma![n]斡Nos deslizaremos por las sombras y[n]capturaremos r茨pidamente a nuestro objetivo!

[msg MSG_004 [Akihiko]]
No est茨 en mi naturaleza escabullirme.
Adem茨s, nunca he realizado ning雨n robo[n]fantasma antes. Tendr茨s que mostrarnos[n]c吋mo se hace.

[sel SEL_005 top]
Solo d姻jate llevar.
Nuestro estilo no es dif胤cil de imitar.
C茨llate y s胤guenos pista.

[msg MSG_006 [Mitsuru]]
夷A-as胤 es como hacen las cosas?

[msg MSG_007 [Morgana]]
斡Claro que no! 斡Nuestro enfoque es mucho[n]m茨s estrat姻gico que eso!
Les mostraremos las verdaderas[n]habilidades de los Ladrones Fantasma,[n]斡solo s胤ganos de cerca!

[msg MSG_008 [Teddie]]
斡Oh, 斡夷en serio?! 斡El Estilo Teddie es[n]"llenarse de snacks tres veces al d胤a"!

[msg MSG_009 [P4 Hero]]
Creo que no se refiere a eso...

[msg MSG_010 [Morgana]]
El estilo no es algo en lo que se da con[n]lecciones, 斡solo tienen que sentirlo!
De todos modos, les mostraremos las[n]verdaderas habilidades de los Ladrones[n]Fantasma, 斡solo s胤ganos de cerca!

[msg MSG_011 [Mitsuru]]
Oh... 斡Qu姻 directo!
Supongo que seguiremos su ejemplo[n]mientras avanzamos en la misi吋n.

[msg MSG_012 [Morgana]]
斡S胤, les mostraremos las verdaderas[n]habilidades de los Ladrones Fantasma!

[msg MSG_013 [Yukiko]]
*risa* 斡Es como si todos nosotros nos[n]hubi姻ramos unido a su equipo!

[msg MSG_014 [Chie]]
斡Eso suena genial! 斡Podemos estar en el[n]equipo de investigaci吋n y en el de[n]Ladrones Fantasma!

[msg MSG_015 [Naoto]]
Los que persiguen y los que son[n]perseguidos, normalmente, tales partes[n]nunca se relacionar胤an...
Tal vez tiene que ver con este mundo[n]extra隠o, que nos permite unir fuerzas.

[msg MSG_016 [Mitsuru]]
Siento lo mismo, nosotros en SEES[n]tambi姻n seremos Ladrones Fantasma en[n]esta misi吋n.

[msg MSG_017 [Ken]]
Je, je, 夷Ser un ladr吋n fantasma, eh?

[msg MSG_018 [Junpei]]
Est茨s en la edad en la que sue隠as con[n]esa clase de cosas. Parece que eres un[n]chico normal despu姻s de todo, Ken.

[msg MSG_019 [Ken]]
斡Eso no es en lo que estaba pensando![n]D姻jame en paz...

[msg MSG_020 [Koromaru]]
斡Guau!

[msg MSG_021 [Aigis]]
Koromaru tambi姻n quiere unirse. Dice:[n]"Quiero registrarme tambi姻n".

[msg MSG_023 [Futaba]]
斡S胤! Hikari, eres parte de los Ladrones[n]Fantasma tambi姻n ahora, 夷de acuerdo?

[msg MSG_024 [Hikari]]
夷Eh? 夷Realmente est茨n de acuerdo...?

[msg MSG_025 [Haru]]
斡Por supuesto! Vamos a lograrlo juntos[n]con nuestro esfuerzo.

[msg MSG_026 [Hikari]]
Mm... 斡Gracias!

[msg MSG_027 [Ann]]
斡Ja, ja, ja, nuestro equipo acaba de[n]convertirse en un ej姻rcito! Pens姻 que se[n]supon胤a que 姻ramos "Fantasmas".

[sel SEL_028 top]
Esto va a ser divertido.
Esto va a ser complicado...

[msg MSG_029 [Fuuka]]
斡Vaya, qu姻 confianza!
Igual que nuestro l胤der, pero el suyo es[n]tan confiable... 斡Estoy impresionada!

[msg MSG_030 [Rise]]
夷Verdad? Todos son tan confiables,[n]斡incluso [f 6 1 27 0 0 0] tiene agallas!

[msg MSG_031 [Yusuke]]
S胤, podr胤a ser todo un desaf胤o coordinar[n]a tantas personas de forma excepcional.

[msg MSG_032 [Futaba]]
Oh, 斡t雨 serias el indicado para eso,[n]Inari!

[msg MSG_033 [Ryuji]]
S胤, 斡夷Lo mismo para ti, sabes?!

[msg MSG_034 [P3 Hero]]
S姻 que puede ser extra隠o que diga[n]esto... pero honestamente, creo que[n]estoy emocionado.

[msg MSG_035 [P4 Hero]]
En realidad, no es tan extra隠o... Creo[n]que me siento igual.
Normalmente, nunca nos hubi姻ramos[n]conocido, pero nos hemos reunido por un[n]prop吋sito.
Justo aqu胤, en este momento, solo queda[n]una cosa por hacer, y es algo que[n]podemos hacer.

[msg MSG_036 [P3 Fem Protag]]
As胤 es. 斡Estoy segura de que nuestro[n]encuentro significa algo!

[msg MSG_037 [Morgana]]
Entonces, 斡comencemos con la misi吋n inaugural[n]de los reci姻n llegados Ladrones Fantasma![n]Comencemos con los detalles de...

[msg MSG_038 [Ryuji]]
斡OH, MIERDA! 斡Lo olvid姻 completamente,[n]el aviso!

[msg MSG_039 [Morgana]]
夷Qu姻? 夷El aviso?

[msg MSG_040 [Ryuji]]
斡No podemos empezar la misi吋n sin uno![n]Yusuke, 夷puedes dibujar uno?

[msg MSG_041 [Makoto]]
Pero esto no es un palacio. No sirve de[n]nada enviar uno...

[msg MSG_042 [P3 Fem Protag]]
Oh, 夷Un aviso es esencial para las[n]operaciones de los Ladrones Fantasma?[n]斡Hagamos uno, hagamos uno!

[msg MSG_043 [Ken]]
斡Tambi姻n creo que deber胤a hacerlo! E-eso[n]nos animar胤a a todos...

[msg MSG_044 [Yusuke]]
As胤 que crees en la belleza de nuestra[n]tradici吋n... Como quieras. Voy a[n]preparar uno.

[msg MSG_045 [Ryuji]]
斡Bien, lo 雨nico que falta es nuestra[n]frase! 斡Di lo tuyo, [f 6 1 30 0 0 0]!

[sel SEL_046 top]
斡Es hora del espect茨culo!
斡Vamos a robar la pel胤cula de Enlil!
No s姻 de qu姻 hablas...

[msg MSG_047 [Ryuji]]
夷Qu姻姻姻...? 夷AHORA te quedas callado?

[msg MSG_048 [Morgana]]
Supongo que no tenemos opci吋n. Perm胤teme[n]comenzar esto de la forma correcta...

[msg MSG_049 [Morgana]]
斡Ladrones Fantasma, comencemos la[n]operaci吋n!

[msg MSG_050 [Ann]]
斡S胤!

[msg MSG_051 [Ryuji]]
斡S胤!

[msg MSG_052 [Yusuke]]
斡S胤!

[msg MSG_053 [Makoto]]
斡S胤!

[msg MSG_054 [Morgana]]
斡S胤!

[msg MSG_055 [Haru]]
斡S胤!

[msg MSG_056 [Futaba]]
斡S胤!

[msg MSG_057 [Akechi]]
斡S胤!

[msg MSG_058 [P4 Protag]]
斡S胤!

[msg MSG_059 [Chie]]
斡S胤!

[msg MSG_060 [Yukiko]]
斡S胤!

[msg MSG_061 [Yosuke]]
斡S胤!

[msg MSG_062 [Kanji]]
斡S胤!

[msg MSG_063 [Naoto]]
斡S胤!

[msg MSG_064 [Rise]]
斡S胤!

[msg MSG_065 [Teddie]]
斡S胤!

[msg MSG_066 [Yukari]]
斡S胤!

[msg MSG_067 [Junpei]]
斡S胤!

[msg MSG_068 [Fuuka]]
斡S胤!

[msg MSG_069 [Akihiko]]
斡S胤!

[msg MSG_070 [Shinjiro]]
S胤...

[msg MSG_071 [Mitsuru]]
斡S胤!

[msg MSG_072 [Ken]]
斡S胤!

[msg MSG_073 [Koromaru]]
斡Awoooo!

[msg MSG_074 [Aigis]]
斡S胤!

[msg MSG_075 [P3 Protag]]
斡S胤!

[msg MSG_076 [P3 Fem Protag]]
斡S胤!

[msg MSG_077 [Hikari]]
斡S胤!

