[msg MSG_000 [P3 Hero]]
Ngh... 夷D吋nde estamos?

[msg MSG_001 [Fuuka]]
斡Chicos! 斡夷Est茨n bien?!

[msg MSG_002 [Mitsuru]]
夷Yamagishi...? 夷Entonces estamos de[n]vuelta en el cine de Hikari?

[msg MSG_003 [Rise]]
S胤. Parece que fueron arrastrados hasta[n]aqu胤.

[msg MSG_004 [Futaba]]
El poder de Enlil est茨 fuera de nuestros[n]par茨metros...
Pero el poder de esas personas en los[n]cines parece a雨n m茨s fuerte, pero se[n]niegan a escuchar.

[msg MSG_005 [Ryuji]]
斡Maldici吋n! 斡夷Por qu姻 diablos no pueden[n]entender su situaci吋n?!

[msg MSG_006 [Yukiko]]
Pero, 夷esas personas... no parec胤an[n]estar un poco indecisas?

[msg MSG_007 [Yusuke]]
S胤. Hab胤a incluso algunas voces que[n]expresaban su deseo por la clase de[n]coraje que esperamos de ellos...

[msg MSG_008 [Yukari]]
Pero al final... todos se rindieron y se[n]decidieron esconderse.

[msg MSG_009 [Hikari]]
Probablemente, est茨n pasando por el[n]mismo problema que yo...

[msg MSG_010 [Chie]]
夷Qu姻?

[msg MSG_011 [Hikari]]
Ver pel胤culas vac胤as, pero que tus[n]propios recuerdos dolorosos te hacen[n]sentir como renunciar ser胤a m茨s f茨cil...
Eventualmente, incluso llegas al punto[n]donde piensas que perder tu[n]individualidad es la elecci吋n correcta.

[msg MSG_012 [Akechi]]
つれろぺれ らまるれよょぺれ まれろァょ ほァれもぼぺゆまょろま れゎゃまろぺれ ぺ ゎょ[n]ぼよょろるよゅ ゆまょろぺゅテテテ とょぼゅゎれよ れも めぺほゅァるぺゆよれ ぼよょ[n]まゅゅよれデ りゎもイょ れぺほま れも ょよれ まれぼゎぼめぺるウぺょテ

[msg MSG_013 [Hikari]]
Pero, yo fui capaz de cambiar para[n]mejor, gracias a que cambiaron las[n]pel胤culas en mi Cine.
Me hicieron sentir que no deb胤a[n]reprimirme ni temer a mi futuro, y eso[n]deber胤an transmitir las pel胤culas.
Si todos ellos hubieran visto esas[n]pel胤culas, apuesto a que ahora estar胤an[n]pensando diferente.

[sel SEL_014 top]
斡ESO ES!
Entonces se las mostraremos.

[msg MSG_015 [Haru]]
斡Aah! 斡夷Por qu姻 gritas?!

[msg MSG_016 [Akihiko]]
夷Tienes una idea?

[msg MSG_017 [Makoto]]
夷Te refieres a las pel胤culas de Hikari?
夷Quieres mostrarlas en los otros cines?

[msg MSG_018 [Yosuke]]
Ah, ya veo, si funciona, las pel胤culas[n]editadas deber胤an cambiar c吋mo piensan,[n]as胤 como con Hikari.

[msg MSG_019 [Naoto]]
Bien, parece l吋gico...

[msg MSG_020 [Chie]]
斡Espera, espera! Lo siento, pero... 夷De[n]qu姻 estaban hablando?

[msg MSG_021 [P3 Hero]]
No vamos a convencerlos uno por uno, lo[n]haremos a la vez, con la ayuda de las[n]pel胤culas de Hikari.
夷Esa es la idea no?

[msg MSG_022 [P4 Hero]]
S胤. Si ven esas pel胤culas y despiertan[n]como Hikari, las puertas de sus cines se[n]abrir茨n...
Y entonces, todo querr茨n salir de los[n]cines.

[msg MSG_023 [Shinjiro]]
Pero, 夷c吋mo vamos a reproducir esas[n]pel胤culas en sus pantallas?

[msg MSG_024 [Fuuka]]
Mmm... Normalmente, los cines no[n]muestran la misma pel胤cula a la vez.
Si quisi姻ramos reproducir el contenido[n]del cine de Hikari a todos, 夷c吋mo lo[n]har胤amos?

[sel SEL_025 top]
Los proyectores...
Intercambiaremos las pel胤culas.
Hikari pensar茨 en algo.

[msg MSG_026 [Aigis]]
Correcto, confirm姻 la ubicaci吋n de[n]cuatro proyectores funcionando en lso[n]alrededores.

[msg MSG_027 [Ken]]
Pero, 夷c吋mo los usamos? Los proyectores[n]son m茨quinas que muestran una pel胤cula,[n]夷verdad?

[msg MSG_028 [Chie]]
夷Te refieres a la pel胤cula que avanza[n]por todo el suelo? 夷Quieres cambiar esa?

[msg MSG_029 [Yukiko]]
Espera, 夷podr胤a esa pel胤cula tener algo[n]que ver con esos cuatro proyectores?

[msg MSG_030 [Junpei]]
斡Espera, espera! Puede ser aspirante a[n]directora y todo eso, pero 夷no es pedir[n]demasiado?

[msg MSG_031 [Hikari]]
Oh, tal vez... 夷Y si usamos los cuatro[n]proyectores que vimos?

[msg MSG_032 [Yukari]]
Espera, 夷tienes una idea?

[msg MSG_033 [Futaba]]
斡Claro! 斡Solo necesitamos usar esos[n]cuatro proyectores para proyectar[n]nuestras propias pel胤culas!
によれ ぼぺゆもょよれ まょ まゅ ぽもれろるもろよ ぽまゅ ぼもょま らぺるまぼまょ[n]まれろぺる めまぼめよれ ぽま ゎょぺ ろもるぺ ぽま ゎょぺ らまゅウぼゎゅぺ ゅぺるむぺ[n]りゎま わぺ めぺぼもぺ ろよぽよれ ゅよれ ぼもょまれテ

[msg MSG_034 [Haru]]
Esa pel胤cula estaba muy oscura. Y no me[n]refiero al balance de color...

[msg MSG_035 [Fuuka]]
夷Podr胤a estar causando alg雨n efecto[n]negativo en todo los cines?

[msg MSG_036 [Hikari]]
Creo que la pel胤cula del piso est茨[n]compuesta por los recuerdos m茨s oscuros[n]de todos...

[msg MSG_037 [Akechi]]
Es una mezcla de los recuerdos negativos[n]de la gente... Eso me recuerda a los[n]registros ak茨shicos.

[msg MSG_038 [Kanji]]
夷Eh? 夷Qu姻 es eso?

[msg MSG_039 [Naoto]]
Supuestamente, son los eventos y[n]emociones de todo el mundo escritos...[n]suena similar...
ひもょ まゆほぺるむよデ ゅよ りゎま れま ゆゎまれろるぺ ぺりゎウ まれろァ[n]ぽまゆぺれもぺぽよ れまれむぺぽよ らぺるぺ れまる ゅゅぺゆぺぽよ ゎょ[n]わまるぽぺぽまるよ るまむもれろるよ ぽま ぼゎぺゅりゎもまる ぼよれぺデ を ゆゎぼめよ[n]ゆまょよれ ぽま ろよぽよテ

[msg MSG_040 [Akechi]]
Es una mezcla de los recuerdos negativos[n]de la gente...

[msg MSG_041 [Naoto]]
En efecto. Sin embargo, lo que se[n]muestra aqu胤 est茨 demasiado sesgado para[n]ser precisa.

[msg MSG_042 [Hikari]]
Mmhm... Son recuerdos muy editados de[n]los recuerdos de todos.
Todo lo divertido o alegre en sus vidas[n]fue cortado de la pel胤cula que est茨n[n]viendo.

[msg MSG_043 [Yusuke]]
Mientras que la pel胤cula normalmente[n]partes positivas como negativas, todo lo[n]positivo fue cortado...

[msg MSG_044 [Makoto]]
Cuando se trataba de las pel胤culas de[n]Hikari, las cambiamos una por una...
Pero, para cambiar la opini吋n de todos,[n]necesitamos atacar de ra胤z, todas a la[n]vez.

[msg MSG_045 [P3 Fem Protag]]
斡Ya veo! As胤 que todo lo que tenemos que[n]hacer es cambiar la pel胤cula de los[n]proyectores con las pel胤culas de Hikari.
Si hacemos eso, seguro que todos...

[sel SEL_046 top]
Ganar茨n coraje.
Dejar茨n sus Cines.
Ellos... Bueno, no lo sabemos.

[msg MSG_047 [Teddie]]
夷Se animar茨n como Hikarin?

[msg MSG_048 [Kanji]]
斡Bien, tenemos que hacerlo!

[msg MSG_049 [Ann]]
S胤. 斡Apuesto a que los ayudar茨 a todos!

[msg MSG_050 [Koromaru]]
斡Arf!

[msg MSG_051 [Mitsuru]]
Cierto, no hay garant胤a de que cambien[n]reproduciendo las pel胤culas de Hikari.[n]Sin embargo...
No por eso vamos a dejar de intentarlo,[n]夷no es cierto?

[msg MSG_052 [Akihiko]]
はよる れゎらゎまれろよテ ふぺゆよれ ぺ ゆよれろるぺるゅまれ ろよぽぺれ ゅぺれ[n]らまゅウぼゎゅぺれ ぽま でもやぺるもデ エぽま りゎイ れまるわもるァ れも ょよ ゅよ[n]めぺぼまゆよれ ぼよょ ゅぺ ぺぼろもろゎぽ ぼよるるまぼろぺ?

[msg MSG_053 [P4 Hero]]
Entonces est茨 decidido, vamos a cambiar[n]esas pel胤culas negativas con las de[n]Hikari.

[msg MSG_054 [P3 Hero]]
Todo lo que tenemos que hacer es cambiar[n]las pel胤culas de los proyectores de[n]antes, 夷verdad?

[msg MSG_055 [Morgana]]
En ese caso, necesitamos tomar las[n]pel胤culas de la vida de Hikari que[n]cambiamos y llevarlas a los proyectores.
斡Vamos, a la sala de proyecci吋n!

