[msg MSG_000 [Yukiko]]
Oye, venimos aquボ sin pensar, メno[n]podrボamos quedar atrapados aquボ otra[n]vez?

[msg MSG_001 [Yusuke]]
Considerando lo que dijo Enlil, dudo que[n]lo haga...

[msg MSG_001_5 [Yusuke]]
Las cerraduras representaban el deseo de[n]Hikari de quedarse.
Desde que Hikari decidiポ irse, Enlil no[n]ha mostrado ninguna intenciポn de[n]detenerla.

[msg MSG_002 [Mitsuru]]
Mm. Este lugar parece ser seguro, los[n]cines restantes son el verdadero[n]problema...
Hasta que sus habitantes obtengan la[n]voluntad de irse, sus puertas[n]permanecerホn cerradas.

[msg MSG_003 [Haru]]
Me pregunto qu〒 pasarホ si se quedan aquボ[n]para siempre...
Enlil dijo que estarボan a salvo...

[msg MSG_004 [Ken]]
Pero no estホn pensando por sボ mismos.[n]Solo es eso...

[sel SEL_005 top]
Son totalmente apホticos.
Son como desconexiones mentales...

[msg MSG_006 [Yukari]]
Pi〒nsalo... ムEsto no es muy diferente a[n]estar muerto!

[msg MSG_007 [Mitsuru]]
Y qui〒n sabe cuホnta gente estホ entrando[n]en el distrito de cine mientras[n]hablamos...

[msg MSG_008 [Makoto]]
Sボ. Han perdido la voluntad de vivir,[n]como los de los casos de desconexiones[n]mentales...

[msg MSG_009 [Ann]]
ムメHay mucha gente aquボ?! ムメY sus nマmeros[n]siguen creciendo?!

[msg MSG_010 [Teddie]]
ムNoooo! ムEsto una emergencia! Si esto[n]sigue...
...メQu〒 va a pasar?

[msg MSG_011 [Yosuke]]
メQuieres calmarte? ムDeberボamos[n]concentrarnos…

[msg MSG_011_5 [Yosuke]]
...en ordenar la informaciポn que ya[n]tenemos!

[msg MSG_012 [Chie]]
Tマ eres el que necesita calmarse.

[msg MSG_013 [Yukiko]]
Ese es nuestro Yosuke. Defendiendo su[n]tボtulo de Prボncipe de la Decepciポn.

[msg MSG_014 [Yosuke]]
ムメPodrボan parar, por favor?!

[msg MSG_015 [P4 Hero]]
...メSabes algo de esto, Margaret?

[msg MSG_016 [Margaret]]
Bueno, para empezar, las ramificaciones[n]que tendrボa en el mundo real no pueden[n]pasarse por alto.

[msg MSG_017 [Naoto]]
メQu〒 pasarボa?

[msg MSG_018 [Elizabeth]]
Eventualmente, esos cines podrボan[n]invadir el tejido de sus realidades...

[msg MSG_018_5 [Elizabeth]]
...O algo de esa naturaleza.

[msg MSG_019 [Shinjiro]]
メEl mundo se va a llenar de estos Cines[n]de mierda?

[msg MSG_020 [Akihiko]]
Todo el mundo se volverホ pesimista,[n]muertos por dentro...
Esto es un verdadero montポn de basura.

[msg MSG_021 [Hikari]]
No quiero que nadie mホs pase por lo que[n]pase aquボ...

[msg MSG_022 [P3 Fem Protag]]
Sボ, no lo permitiremos. Cuidaremos[n]nuestro mundo de estos cines.

[msg MSG_023 [P4 Hero]]
Debemos prepararnos, esta podrボa ser[n]nuestra batalla final. Salgamos cuando[n]estemos listos.

