[msg MSG_000 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 85 12 0 1][f 3 1 1 0 0 65009]Vale, entonces lemme explicar acerca de[n]c吋mo [f 0 1 2] comunicarse con otros[n]mundos[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El trato es, aparentemente hay una[n]tonelada de mundos adem茨s de este de ah胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que, en esos otros mundos, hay otros...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y todos est茨n tratando de comunicarse[n]con su mundo desde el suyo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 65001]As胤 que si quieres contactar con este[n]otro, utilizas el [f 0 1 2]P-Book[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El P-Book puede contener la informaci吋n[n]de su equipo y una Sub-Persona.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cuando intercambias un Libro con otro,[n]ambos podr茨s convocar a las Sub-Personas[n]dentro de los Libros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Obviamente todav胤a costar茨 algo de[n]dinero, pero podr胤as terminar con una[n]Persona muy fuerte.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_2 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 0][f 3 1 1 0 0 0]Pero primero necesitamos un nombre. As胤[n]que el otro puede dec胤rtelo, y esas cosas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_3 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 1 1][f 3 1 1 0 0 65013]Hmm... Bueno, es un nombre que va en el[n]P-Book, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_4 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Vamos a llamarlo su [f 0 1 2]P-Book Name[f 0 1 0]![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puedes cambiarlo cuando quieras, as胤[n]que dame algo para escribir.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 0]Un nombre de P-Book, eh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_5 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23115][f 6 1 2 0 0 5]夷Por qu姻 no usamos nuestro nombre de[n]equipo Ladrones Fantasma?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4][f 6 1 3 0 0 0]夷Tu qu姻?[n][f 1 3 65535][f 1 1][e]

