[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 0 1 0 3][f 4 6 33 0 0 1][f 3 1 1 0 0 4167]As胤 concluye los preparativos de su propio P-Book.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 33 12 0 0][f 3 1 1 0 0 0]Si姻ntete libre de hacer cambios en ella[n]cuando el estado de 茨nimo te golpee.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Para comenzar a utilizar StreetPass,[n]seleccione [f 0 1 2] Ajuste de Pasos[f 0 1 0] del men雨.[n][f 1 3 65535][f 1 1][e]

