[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 0 1 0 3][f 4 6 33 12 0 1][f 3 1 1 0 0 0]Después, debes elegir una Persona Secundaria para adjuntar al P-Book.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Descuida, [f 0 1 2]seguirás conservando tu Persona Secundaria[f 0 1 0] después de adjuntarla.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso puedes cambiar tu selección más adelante, así que adjunta una sin preocuparte.[n][f 1 3 65535][f 1 1][e]

