[msg MSG_000 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 23 1 0 6][f 4 6 85 2 0 1][f 3 1 1 0 0 65040]Eh... S胤, puedo sentir buenos patos en eso.[n]No est茨 mal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 6 1 2 0 0 7][f 3 1 1 0 0 0]Nyeheheh... Lo s姻, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1][f 3 1 1 0 0 65006][f 6 1 3 0 0 0]夷Quieres elegir un Sub-Persona para adjuntar[n]al P-Book?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 3 0 0 0]El [f 0 1 2]Sub-Persona que adjuntas no desaparecer茨[f 0 1 0][n], as胤 que no lo[n]estreses.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 2 0 1][f 3 1 1 0 0 0][f 6 1 3 0 0 0]Y puedes cambiarlo m茨s tarde de todos modos,[n]as胤 que elige uno por ahora.[n][f 1 3 65535][f 1 1][e]

