[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 1][f 3 1 1 0 0 21061][f 6 1 2 0 0 0]斡夷Q-qu姻 demonios es este enorme tallo?![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 0][f 3 1 6 0 0 500][f 3 1 1 0 0 0]No es un tallo ordinario...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Parece que tiene algo que ver con ese[n]tronco que vimos antes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3013][f 6 1 2 0 0 4]夷Un tronco? Oh, 夷entonces esta es una[n]especie de plataforma elevadora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 100 0][f 3 1 6 0 0 500][f 3 1 1 0 0 0]Mmhm, se est茨 levantado en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 7 1 1][f 3 1 1 0 0 8075]En ese caso, si giramos la nariz de este[n]tronco, deber胤a suceder algo con[n]este tallo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 6 0 0 500][f 3 1 1 0 0 26502]Si quieres usar esa plataforma elevadora,[n]tendr茨s que girar el interruptor[n]de la nariz de ese tronco.[n][f 1 3 65535][f 1 1][e]

