[msg MSG_000]
Within Theater 3...

[msg MSG_001 [Mitsuru]]
So, in order to leave this place, you[n]believe we need to revise the contents[n]of the movies shown in these theaters...
Do I understand your explanation[n]correctly?

[msg MSG_002 [Makoto]]
Yes, that's what we think so far.
Based on the contents of the movie and[n]its trailer, I believe its aim is to[n]paint individuality in a negative light.

[msg MSG_003 [Shinjiro]]
So what you're sayin' is that we just[n]hafta destroy their shitty way of[n]thinking, right?

[msg MSG_004 [Ken]]
Also, we need to find our leader and[n]Aigis-san.

[msg MSG_005 [Akihiko]]
と ぽよょ'ろ むまろ ぺゅゅ ろめもれ "むよもょむ もょれもぽま ゆよわもまれ" ぺょぽ[n]ゐめぺろょよろデ ほゎろ もろ ゅよよやれ ゅもやま ゐま ぽよょ'ろ めぺわま ぺょを[n]ろもゆま ろよ ゐぺれろま ぽもれぼゎれれもょむ もろテテテ
I'm really worried about our companions,[n]too. I'm ready to let my fists lead the[n]way!

[msg MSG_006 [Shinjiro]]
*sigh* Look at this guy, grinning like a[n]kid... I better not see you go rushin'[n]in by yourself!

[msg MSG_007 [Futaba]]
Uh, um...

[msg MSG_008 [Haru]]
What's the matter, Futaba-chan?

[msg MSG_009 [Futaba]]
Um... I have a favor to ask!
I wanna join you guys on the mission!

[msg MSG_010 [Ryuji]]
What? You wanna come into the movie with[n]us!?

[msg MSG_011 [Futaba]]
Yeah, can I? Please?

[sel SEL_012 top]
That could be really helpful.
It'll be dangerous...

[msg MSG_013 [Yosuke]]
Yeah, I get that... but isn't it kinda[n]dangerous for your navigator to do[n]something like that?

[msg MSG_014 [Futaba]]
No no no, don't worry! I've infiltrated[n]Palaces and Mementos with the Phantom[n]Thieves in the past...
Plus, my hacking skills would be super-[n]handy in a sci-fi world! I'll do more[n]good in there than out here!

[msg MSG_015 [Futaba]]
But―but―I've infiltrated Palaces and[n]Mementos with you guys in the past...
Plus, my hacking skills would be super-[n]handy in a sci-fi world! I'll do more[n]good in there than out here!

[msg MSG_016 [Yusuke]]
I see. She makes a valid point.
Since this movie's world is controlled[n]with electronics, having Futaba with us[n]would be especially helpful.

[msg MSG_017 [Morgana]]
What's your call? Personally, I think[n]she'd be fine, but it's up to you.

[sel SEL_018 top]
Let's all go together.
Come with us.
Hope you've got the guts for it.

[msg MSG_019 [Futaba]]
Yes! Thank you so much―you won't regret[n]it!

[msg MSG_020 [Futaba]]
Awesome! Lead the way, fellow party[n]members!

[msg MSG_021 [Futaba]]
That's... well, I'll be fine―it'll be[n]fine! I swear I won't cause any trouble![n]Okay?

[msg MSG_022 [Hikari]]
...You really want to go in there,[n]Futaba-chan?

[msg MSG_023 [Futaba]]
I think that movie is wrong. I wanna be[n]the one to change it, no matter what it[n]takes.

[msg MSG_024 [Hikari]]
I... I don't understand.

[msg MSG_025 [Futaba]]
That's fine―for now, just watch the[n]movie for me, okay? All the way to the[n]end.

[msg MSG_026 [Hikari]]
Mmhm, I'll be watching... Please, come[n]back safe...

[msg MSG_027 [Futaba]]
Roger that!

[msg MSG_028 [Mitsuru]]
Well, we should be on our way. I'm[n]growing more worried about our[n]companions.

[msg MSG_029 [Nagi]]
Be careful, everyone. Please don't do[n]anything reckless...

[msg MSG_030 [Ryuji]]
No prob! We'll just keep on kickin' ass!

[msg MSG_031 [Nagi]]
Those Persona-users... They seem to be[n]very dependable.

[msg MSG_032 [Hikari]]
Mmhm... They're so strong.

[msg MSG_033 [Nagi]]
Not to say that I don't believe in them,[n]but I can't help myself from[n]wondering...
Will we ever truly be able to leave this[n]place?

[msg MSG_034 [Hikari]]
Do you mean... we could be stuck in this[n]movie theater forever?

[msg MSG_035 [Nagi]]
I'm merely proposing a hypothetical[n]situation:
If it turned out that we must remain[n]here forever... what would you do,[n]Hikari-san?

[msg MSG_036 [Hikari]]
...I don't know.
I might not be able to do anything about[n]it, but...

[msg MSG_037 [Nagi]]
Hikari-san...

[msg MSG_038 [Doe]]
......

[msg MSG_039 [Nagi]]
Doe...

[msg MSG_040 [Hikari]]
......!?

[msg MSG_041 [Doe]]
......

[msg MSG_042 [Hikari]]
What are you even...?

[msg MSG_043 [Nagi]]
It's all right, Hikari-san―I'm right[n]here with you...

