[msg MSG_000 [Boy with baseball cap]]
Whoa, you weren't kidding about this[n]being a movie theater!

[msg MSG_001 [Spirited girl]]
It's still hard to believe, but... we[n]really were inside a movie that whole[n]time, huh?

[msg MSG_002 [Well-dressed girl]]
Good heavens. What's all the commotion[n]here?
We really don't have the time to waste[n]on something as nonsensical as this...

[msg MSG_003 [Boy with baseball cap]]
Come on, Senpai. There's no point in[n]getting all irritated...
What we really need to do is find our[n]leader and Ai-chan!

[msg MSG_004 [Well-dressed girl]]
Yes, I know...
So, where is this movie theater curator?[n]I'd like to pay her my respects.

[msg MSG_005 [Makoto]]
Ah, of course―I'll introduce you to[n]them...
This is Nagi-san the curator, and[n]Hikari-chan. They're both trapped here[n]as well.

[msg MSG_006 [Nagi]]
It's nice to meet you. My name is Nagi.
As she just mentioned, everyone here is[n]in a similar circumstance...
I too will do what I can to assist you,[n]so please feel free to call on me[n]whenever the occasion arises.

[msg MSG_007 [Well-dressed girl]]
Thank you. I apologize for the trouble,[n]but we're extremely grateful for your[n]assistance.

[msg MSG_008 [Hikari]]
......

[msg MSG_009 [Quiet girl]]
Are you Hikari-chan?

[msg MSG_010 [Hikari]]
Yes... Nice to meet you.
Um... Are you all [f 6 1 26 0 0 0]-san's...?

[msg MSG_011 [Haru]]
They're your companions―right?

[msg MSG_012 [P3 Fem Protag]]
Mmhm. At least, that's what I had[n]figured, but...

[msg MSG_013 [Aggressive boy]]
But none of us know her―myself included.
On the other hand, she knows all about[n]us... This is bizarre.

[msg MSG_014 [Quiet girl]]
I don't think she's lying...
Her Evoker and armband seem to be real,[n]and she even knows about Aigis.

[msg MSG_015 [Ann]]
Could they be cognitive beings of[n][f 6 1 27 0 0 0]-chan?

[msg MSG_016 [Akechi]]
No, that's very unlikely. This place is[n]different from Palaces or Mementos.

[msg MSG_017 [Chie]]
Hrgh, I'm totally lost now. What does[n]all of this mean―in basic terms?

[msg MSG_018 [P3 Fem Protag]]
ぶまゅゅテテテ びめもれ もれ ぺ らもぼやゅまテ だれ どゎょらまも ゐよゎゅぽ らゎろ[n]もろデ "びめもれ れよゎょぽれ ゅもやま ぺ ぼぺれま まわまょ ぺょ だぼま[n]っまろまぼろもわま ゅもやま ゆをれまゅみ ぼぺょ'ろ れよゅわま!"

[msg MSG_019 [Boy with baseball cap]]
Whoa! You know my trademark gag!?

[sel SEL_020 top]
What's that supposed to mean?
"Ace Detective"?
That's pretty lame...

[msg MSG_021 [Spirited girl]]
Ah, never mind him. It'd be a big waste[n]of time and energy for a whole lot of[n]nothing.

[msg MSG_022 [Boy with baseball cap]]
Listen, it's a catchphrase that's more[n]useful now than ever.
Such a wet blanket... even an Ace[n]Detective like me could never figure you[n]out, Yuka-tan!

[msg MSG_023 [Boy with baseball cap]]
Nooo... Don't tell me you're a mood[n]killer too!?
From one cold shoulder to the next...[n]even an Ace Detective like me can't[n]figure you guys out!

[msg MSG_024 [Spirited girl]]
Ugh, such a try-hard...

[msg MSG_025 [Boy with baseball cap]]
Anyway, she's definitely mastered my Ace[n]Detective gag―looks like she knows about[n]us after all.

[msg MSG_026 [Teddie]]
But, has everyone else forgotten this[n]charming lady?

[msg MSG_027 [Somber child]]
I'm sorry... I really am trying my best[n]to remember.

[msg MSG_028 [Dog]]
*whine*

[msg MSG_029 [Boy with baseball cap]]
Sorry... I really don't know what to[n]say. You even went out of your way to[n]save us, too...

[msg MSG_030 [P3 Fem Protag]]
Oh no, it's okay! Don't worry about it![n]I mean, this whole place seems to be[n]really crazy!
I mean, think about it. We've helped a[n]dinosaur with a bizarre human head, and[n]there's even a talking cat here.

[msg MSG_031 [Yosuke]]
What do you mean a bizarre head!?

[msg MSG_032 [Morgana]]
And I am NOT a cat!

[msg MSG_033 [Somber child]]
U-Um...!
I don't think [f 6 1 27 0 0 0]-san is a bad[n]person.
I mean, I can't explain why, and this is[n]supposed to be our first time meeting,[n]but still...

[msg MSG_034 [Dog]]
Arf!

[msg MSG_035 [Somber child]]
See! Even Koromaru agrees!

[msg MSG_036 [P3 Fem Protag]]
Haha... Thanks, Ken-kun, Koromaru.

[msg MSG_037 [Boy with beanie]]
Well, don't let it get to you too much.
ちもろもょ' よみみ ゆよるま ろめぺょ をよゎ ぼぺょ ぼめまゐ'ゅゅ よょゅを ろもるま[n]をよゎ よゎろテ ねよ らよもょろ もょ るゎれめもょ' ろめもょむれテ と'ゆ れゎるま[n]ゐま'ゅゅ みもむゎるま ろめもれ ぺゅゅ よゎろテ

[msg MSG_038 [P3 Fem Protag]]
Shinjiro-senpai...!

[msg MSG_039 [Hikari]]
-san... I'm sure it'll be okay...
U-Um, I don't know how to put it...[n]That's just how I feel right now.

[msg MSG_040 [P3 Fem Protag]]
Thanks, Hikari-chan!
Yeah... I'm sure it'll work out. Let's[n]just keep trying our best!

[msg MSG_041 [P4 Hero]]
By the way, how did you all end up in[n]this world?

[msg MSG_042 [Quiet girl]]
Oh yeah... Well...

