[msg MSG_000 [Yusuke]]
Look―there!

[msg MSG_001 [Chie]]
Huh? What's happening?

[msg MSG_002 [Robot with a ribbon]]
AFTER CONDUCTING AN INTERNAL ANALYSIS, I[n]HAVE IDENTIFIED A TECHNICAL ERROR.

[msg MSG_003 [Mass-produced robot A]]
ALL ERRORS MUST BE ELIMINATED.

[msg MSG_004 [Mass-produced robot B]]
COME WITH US. WE WILL RESET YOUR AI TO[n]FACTORY CONDITIONS.

[msg MSG_005 [Robot with a ribbon]]
UNDERSTOOD.

[msg MSG_006 [Futaba]]
Is that the robot from the trailer!?

[msg MSG_007 [Yukari]]
Wow, she really does look like Aigis...

[msg MSG_008 [Fuuka]]
Um, more importantly―they said they're[n]going to format her!

[sel SEL_009 top]
Let's rescue her.
Let's wait and see what happens.

[msg MSG_010 [Ryuji]]
Right! We can't let that happen to her!

[msg MSG_011 [Akechi]]
Wait―we need to go about this with more[n]caution.
They haven't noticed us yet. Let's see[n]what happens first, then―

[msg MSG_012 [Akechi]]
I agree. Thankfully, they haven't[n]noticed us yet, so―

[msg MSG_013 [Akihiko]]
No way, this is an opportunity! We can[n]get the jump on 'em right now.

[msg MSG_014 [Shinjiro]]
You just wanna beat the shit outta them.[n]Stop chargin' into things without tryin'[n]to use your two brain cells first.

[msg MSG_015 [Akihiko]]
What was that!?

[msg MSG_016 [Mitsuru]]
Will you two stop!? We don't have the[n]time for this!

[msg MSG_017 [P3 Fem Protag]]
Then, let's make it a competition! How[n]quickly do you think you could take down[n]those robots?

[msg MSG_018 [Akihiko]]
It wouldn't take me three minutes.

[msg MSG_019 [Shinjiro]]
I'd do it in one.

[msg MSG_020 [Akihiko]]
Then, I'm gonna do it in 30 seconds!

[msg MSG_021 [Shinjiro]]
Hm! Your mouth better not be writin'[n]checks that your fists can't cash!

[msg MSG_022 [Akihiko]]
Get back here, Shinji! I'm not letting[n]you get a headstart!

[msg MSG_023 [Junpei]]
Wow! You sure know how to play them like[n]a fiddle.

[msg MSG_024 [P3 Fem Protag]]
Heheheh, yep! It happens all the time,[n]so I know exactly how to handle their[n]competitiveness!

[msg MSG_025 [Mitsuru]]
Good heavens... They act like children[n]in your world as well?
Well, in any case: thank you for[n]defusing that situation.

[msg MSG_026 [Makoto]]
We can't fall behind, either. Let's back[n]them up!

