[msg MSG_000 [Overseer]]
...Oh dear, so you've progressed this[n]far.
You seem to be wreaking havoc all over[n]my fair society however you please.

[msg MSG_001 [Futaba]]
So, you're the Overseer, r-right!?

[msg MSG_002 [Overseer]]
Indeed. I am the Overseer that guides[n]the robots of this world to their[n]rightful form.

[msg MSG_003 [Junpei]]
Gah, that face... I know he's not the[n]real one, but it's still givin' me the[n]heebie- jeebies...

[msg MSG_004 [Overseer]]
UIY-2249: you have disobeyed your[n]commands and acted upon your personal[n]whim.
I do not recall giving you such orders.[n]Why did you defy your commands?

[msg MSG_005 [Ribbon]]
......

[msg MSG_006 [Overseer]]
Since you cannot function as you are[n]programmed, you seem to be defective[n]after all.

[sel SEL_007 top]
Defective, huh?
That's not true.

[msg MSG_008 [Overseer]]
That is correct. Having unnecessary[n]thoughts, not performing as[n]programmed...
Such a unit disturbs the world's[n]harmony, and obviously must be[n]eliminated.

[msg MSG_009 [Overseer]]
What an odd statement. UIY-2249 is a[n]robot.
If a robot cannot perform as programmed,[n]clearly they are defective.
Such a unit disturbs the world's[n]harmony, and obviously must be[n]eliminated.

[msg MSG_010 [Futaba]]
Ribbon's already got a will of her own![n]Don't go forcing your own expectations[n]on her!

[msg MSG_011 [Overseer]]
My expectations? No, this is simply the[n]set of standards, and proper order, of[n]this world.
Here, everyone obeys these standards and[n]basks in the serenity they afford.

[msg MSG_012 [Ann]]
Serenity? Don't make me laugh![n]Ribbon-chan's suffering sure doesn't[n]look like serenity to me!

[msg MSG_013 [Overseer]]
That is solely due to the fact that this[n]unit is an error.
This unit, that cannot accept our[n]world's standards, and cannot function[n]as programmed...

[msg MSG_014 [Ribbon]]
......

[msg MSG_015 [Overseer]]
UIY-2249, you are, without a doubt, an[n]error that must be eliminated.

[msg MSG_016 [Futaba]]
Ribbon!

[msg MSG_017 [Chie]]
What... How could you!?

[msg MSG_018 [Ribbon]]
I AM... ALL RIGHT... EVERYONE, PLEASE[n]FLEE...

[msg MSG_019 [Futaba]]
Don't be stupid! We can't leave you here[n]like this!

[msg MSG_020 [Overseer]]
You continue to defend such an error?[n]Are you all rebelling against this[n]world's standards as well?

[sel SEL_021 top]
To hell with your standards.
She is not an error.

[msg MSG_022 [Ryuji]]
Yeah! Worryin' about how others might[n]see you ain't always the right thing to[n]do!
All we're doing is savin' our companion,[n]of our own free will.

[msg MSG_023 [P3 Fem Protag]]
It's true that some rules are needed for[n]a society...
But they're not for chaining others down[n]and making them do everything you say!
I'll never agree that everyone has to be[n]the same for life to be at its best!

[msg MSG_024 [Overseer]]
If you disregard our standards, then you[n]are contaminants to our society...[n]Irregularities must be eliminated.
Before disposing of that flawed unit, I[n]shall dispose of you first.

[msg MSG_025 [P3 Hero]]
Here he comes, you guys!

[msg MSG_026 [Ryuji]]
Bring it on. We're gonna grind you into[n]computer paste!

