[msg MSG_000 [Shinjiro]]
You must be the thing in charge of this[n]screwed-up place.

[msg MSG_001 [Junpei]]
How could you do such terrible things to[n]Ribbon-chan? Is it really so wrong to be[n]different!?

[msg MSG_002 [Mother Computer]]
All I have done is take the appropriate[n]measures based on standard operating[n]procedure.
Your continued defiance of our[n]procedures proves the foolishness and[n]impropriety of your stance.

[msg MSG_003 [Junpei]]
Dude! Why is Ikutsuki-san back again!?

[msg MSG_004 [Mitsuru]]
Technically, it's an "Ikutsuki Robot."[n]We've been led to believe it has nothing[n]to do with the real person.

[msg MSG_005 [Chie]]
Uh, but why is it here at all!?

[msg MSG_006 [Mother Computer]]
I manifested because the robots have[n]yearned for my existence.
They craved a unified society with no[n]individuality. Thus, a being was created[n]to establish and uphold this society.
That being is me.
I am connected to the circuits of every[n]robot...
ひめよゎゅぽ ぺょ もるるまむゎゅぺるもろを ぺるもれまデ と ぼぺょ ぽまろまぼろ もろ[n]もゆゆまぽもぺろまゅをテ と ぺゆ ぺゅれよ ぼぺらぺほゅま よみ まるぺぽもぼぺろもょむ[n]ろめまれま もるるまむゎゅぺるもろもまれ まぺれもゅをテ
In other words, I am the guardian of the[n]robots.

[msg MSG_007 [Kanji]]
Huh? What the hell are you goin' on[n]about!? You're talkin' nonsense!

[msg MSG_008 [Makoto]]
Anyone here with individuality disrupts[n]society's harmony, so they are deemed[n]unnecessary in this world...
Because of that, you're the one making[n]all of these robots purge themselves for[n]being so-called "errors"?

[msg MSG_009 [Mother Computer]]
If you understand so well, then treat[n]yourselves like the errors you are and[n]follow the procedure as the others have.
Existences that deviate from the norm[n]are nothing but a shame to be corrected.

[msg MSG_010 [Yosuke]]
You're the one who needs correcting!

[msg MSG_011 [Yusuke]]
Don't push your own values onto us.

[msg MSG_012 [Mother Computer]]
These are not my values. It is the law[n]of this world.
UIY-2249's individuality is a defect[n]that defies our society's harmony... The[n]unit must be treated as such.

[msg MSG_013 [Ribbon]]
MY INDIVIDUALITY IS... A DEFECT...

[msg MSG_014 [Futaba]]
Ribbon! Don't let that stupid glowy[n]thing get to you!

[msg MSG_015 [Mother Computer]]
Cease this. Defects that are incapable[n]of adhering to the norms of this world[n]have been deemed unnecessary.

[msg MSG_016 [Ryuji]]
Just who the hell do you think you are!?

[msg MSG_017 [Mother Computer]]
I am the voice given to this world's[n]laws.
Those who cannot understand my words[n]need to be disposed of as social[n]misfits.
UIY-2249...
Disappear along with the other[n]irregularities of TK, YS, and IW.

[sel SEL_018 top]
Enough of this nonsense.
Shut up.

[msg MSG_019 [P3 Hero]]
You're the one who's going to disappear!

[msg MSG_020 [P4 Hero]]
Right! We refuse to accept your laws!

[msg MSG_021 [Mother Computer]]
What is preventing you from[n]understanding?
Obey my words, and you will be happy.
If you refuse to obey me, then you must[n]be eliminated.

[msg MSG_022 [P3 Fem Protag]]
Guys―here it comes!

