[msg MSG_000 [Akechi]]
*sigh* There are enemies everywhere[n]here. This is putting a real damper on[n]our progress.

[msg MSG_001 [Shinjiro]]
Hmph, what a pain in the ass. We don’t[n]even get the time to rest up.

[msg MSG_002 [Teddie]]
Ooh, ooh―that reminds me! Are you all[n]better now, Ai-chan?

[msg MSG_003 [Aigis]]
Yes, I've fully recovered. I apologize[n]for worrying everyone.

[msg MSG_004 [Makoto]]
Um, about your... Orgia Mode, was it?[n]That was quite the surprise.

[sel SEL_005 top]
What’s Orgia Mode?
It was super-cool.
I want to see you do that again.

[msg MSG_006 [Aigis]]
That is a special function loaded in my[n]system especially for offensive combat.

[msg MSG_007 [Ryuji]]
Damn, it must feel super-badass to just[n]mow down enemies like that!

[msg MSG_008 [P3 Fem Protag]]
ぬゆデ もろ ぽよまれ めぺわま もろれ ぽるぺゐほぺぼやれデ ろめよゎむめテ のょぼま[n]れめま ゎれまれ もろデ ぺゅゅ よみ めまる みゎょぼろもよょれ ぺるま[n]ろまゆらよるぺるもゅを ぽもれぺほゅまぽ ゎょろもゅ れめま るまぼよわまるれテ

[msg MSG_009 [Futaba]]
Hear hear! Being able to shift gears and[n]transform like that is a mech-lover's[n]dream!

[msg MSG_010 [Aigis]]
That is a special function loaded in my[n]system especially for offensive combat.

[msg MSG_011 [Ryuji]]
Damn, it must feel super-badass to just[n]mow down enemies like that!

[msg MSG_012 [P3 Fem Protag]]
ぬゆデ もろ ぽよまれ めぺわま もろれ ぽるぺゐほぺぼやれデ ろめよゎむめテ のょぼま[n]れめま ゎれまれ もろデ ぺゅゅ よみ めまる みゎょぼろもよょれ ぺるま[n]ろまゆらよるぺるもゅを ぽもれぺほゅまぽ ゎょろもゅ れめま るまぼよわまるれテ

[msg MSG_013 [P3 Fem Protag]]
だめぺめぺデ ろめぺろ ゆもむめろ ほま ぺ ほもろ ぽもみみもぼゎゅろ るもむめろ[n]ょよゐ―ぺみろまる ゎれもょむ もろデ めまる みゎょぼろもよょれ ぺるま[n]ろまゆらよるぺるもゅを ぽもれぺほゅまぽ ゎょろもゅ れめま るまぼよわまるれテ

[msg MSG_014 [Aigis]]
That is a special function loaded in my[n]system especially for offensive combat.

[msg MSG_015 [Yusuke]]
So, it’s a risky attack―a double-edged[n]sword, if you will.

[msg MSG_016 [Ryuji]]
Not bein' able to move for a while, huh?[n]That sounds like Oracle's battery.

[msg MSG_017 [Yukiko]]
Eh? Oracle's powered by a battery!?

[msg MSG_018 [Yosuke]]
Oh come on, there's no way he's being[n]serious!
...Right?

[msg MSG_019 [Futaba]]
He’s not talking about a real battery.[n]It’s more like I just collapse when I[n]get too tired.

[msg MSG_020 [Ribbon]]
IS THERE A POSSIBILITY THAT I ALSO HAVE[n]AN ORGIA MODE?

[msg MSG_021 [Naoto]]
I’m not sure... Based on your model's[n]appearance, that doesn’t seem like a[n]standard function...

[msg MSG_022 [Ribbon]]
I SEE... THAT IS SOMEWHAT DISAPPOINTING.

[msg MSG_023 [Yukari]]
Wait, it’s disappointing to you? Do you[n]mean you want to use Orgia Mode too,[n]Ribbon?

[msg MSG_024 [Ribbon]]
IT DOES NOT MAKE ME WANT TO PROACTIVELY[n]ACQUIRE IT, BUT SINCE I HAVE NO BATTLE[n]FUNCTIONS...
I WOULD AT LEAST BE OF USE TO YOU AT[n]THAT POINT, IF I COULD USE IT― THAT IS[n]WHAT I HAD THOUGHT.

[msg MSG_025 [P3 Fem Protag]]
Ribbon-chan... I didn’t realize you were[n]thinking such things.

[msg MSG_026 [Ken]]
But, if Ribbon-san had her own Orgia[n]Mode, what do you think it would be?

[sel SEL_027 top]
She fires a rocket punch.
She shoots lasers from her eyes.
Her entire body starts glowing.

[msg MSG_028 [Kanji]]
That sounds pretty clich〒.

[msg MSG_029 [Junpei]]
Oh no, it’s way more thrilling than it[n]is clich〒! Rocket Punches are what boys[n]dream of!

[msg MSG_030 [Yukiko]]
But don’t you think just a punch would[n]be kind of... lacking?
I think it’d be better if she also[n]projected lights, blasted music, and[n]started dancing crazy, too!

[msg MSG_031 [Ryuji]]
Oh yeah, that’s standard robot stuff,[n]but... aren’t lasers a bit too "kiddie"?

[msg MSG_032 [Akechi]]
You think so? I think that equipment[n]would be very practical in combat.

[msg MSG_033 [Yukiko]]
Hmm... But doesn’t it feel like it's[n]just not enough?
I think it’d be better if she also[n]projected lights, blasted music, and[n]started dancing crazy, too!

[msg MSG_034 [Yukiko]]
Oh, I think that’s great.
But it’d be even better if she also[n]blasted music and started dancing crazy!

[msg MSG_035 [Yosuke]]
Why would she need to dance!? What’re[n]you trying to get her to do, lead a[n]parade!?

[msg MSG_036 [Teddie]]
If it’s a parade, then I wanna join too![n]Obviously, I’d be the official beauty,[n]blowing kisses and waving to my fans!

[msg MSG_037 [Yusuke]]
Hm... Then you can leave the float's[n]design to me.

[msg MSG_038 [Yukiko]]
Oh, if you need a float, I can help with[n]that. I'll make one with a seafood base[n]and shrimp ice cream on top!

[msg MSG_039 [Yosuke]]
That’s not the kind of float he’s[n]talkin' about! I mean―We don’t need[n]either of those!

[msg MSG_040 [Mitsuru]]
Oh dear, it seems this is starting to[n]really get out of hand... We should get[n]going.

[msg MSG_041 [Ribbon]]
YES, I UNDERSTAND. LET US PROCEED[n]ONWARD.

