[msg MSG_000 [Mother Computer]]
Your actions are useless. You are[n]incapable of defeating me.

[msg MSG_001 [Futaba]]
No! Its processing speed is too fast...[n]It keeps immediately rewriting its[n]coding!
We're so close, too!

[msg MSG_002 [Ribbon]]
ERROR. ERROR.
MEMORY REWRITE DETECTED...

[msg MSG_003 [Akihiko]]
Hey, something's up. What's happening to[n]her!?

[msg MSG_004 [Futaba]]
Don't tell me―is Ribbon getting hacked[n]back!?

[msg MSG_005 [Ribbon]]
NNH, AAH... AH...
ERROR. ERROR.
MY MEMORY IS... AH... NO... I... I...[n]NNNH...

[msg MSG_006 [Mother Computer]]
How do you feel now, UIY-2249?
All of your suffering is due to your[n]individuality.
Discard this irregularity.
All you must do is stop thinking,[n]emulate the others around you, and[n]continue working for all eternity!

[msg MSG_007 [Ribbon]]
......

[msg MSG_008 [Futaba]]
Shut up! Th-That violates the Labor[n]Standards Act!
Ribbon! Don't listen to that thing!

[msg MSG_009 [Mother Computer]]
Why are you incapable of thinking like[n]the other robots?
Working robots must live like working[n]robots. That is your happiness to be[n]had.

[msg MSG_010 [Ribbon]]
MY... HAPPINESS?

[msg MSG_011 [Mother Computer]]
That is correct. You must teach this to[n]those irregularities as well.
Discarding individuality is attaining[n]happiness―that is the norm of society.

[msg MSG_012 [Ribbon]]
NNNH...

[msg MSG_013 [Mitsuru]]
Hang in there, Ribbon!

[msg MSG_014 [Teddie]]
Noooo! You need to stay strong!

[msg MSG_015 [Futaba]]
Please, Ribbon!

[msg MSG_016 [Ribbon]]
I... I... I AM... I...?

[msg MSG_017 [Mother Computer]]
Now, come along―there is no need to[n]suffer any longer.
I will provide you with the peace you[n]seek. There is nothing to fear...

[msg MSG_018 [Morgana]]
Ribbon, don't listen to it! Your[n]feelings aren't an error!

[msg MSG_019 [Makoto]]
He's right! That's just how you feel...[n]It's your own heart!
The Ribbon that loved flowers and[n]petting Koromaru―that's who you really[n]are!

[msg MSG_020 [Ribbon]]
F-FLOWERS... PRETTY...
KOROMARU-SAN... SO SOFT... IT MADE ME[n]HAPPY...
I... I...

[msg MSG_021 [Futaba]]
...R-Ribbon! L-Listen!

[msg MSG_022 [Ann]]
Oracle!?

[msg MSG_023 [Futaba]]
I-I... I like how you are now, Ribbon.[n]That's why you should stay that way!

[msg MSG_024 [Ribbon]]
HOW I AM... NOW?

[msg MSG_025 [Futaba]]
Yeah, that's right...! I-I... I like the[n]real you...
That's why... I don't... I don't want[n]you to disappear!

[msg MSG_026 [Ribbon]]
I... I AM...

[sel SEL_027 top]
Leave the rest to us.
Don't lose to that thing.
Remember your own name.

[msg MSG_028 [Futaba]]
R-Right! We'll... change this world!

[msg MSG_029 [Futaba]]
We're gonna change this world for you,[n]Ribbon! Just try your hardest to fight[n]that thing!

[msg MSG_030 [Ribbon]]
ORA...CLE...

[msg MSG_031 [Ribbon]]
I AM... RIB... RIBBON...

[msg MSG_032 [Futaba]]
I'll protect you, Ribbon!
So you can live as yourself... I'll[n]destroy every BS standard and norm in[n]this place!

[msg MSG_033 [Morgana]]
All right, you tell 'em!

[msg MSG_034 [Mother Computer]]
Thought processes and actions that defy[n]the standards... I will never accept[n]them.
Shifting priorities... Now eliminating[n]the irregularities attempting to[n]maliciously influence our society.

[msg MSG_035 [Ribbon]]
NO...

[msg MSG_035_5 [Ribbon]]
NOOOOOOOOO!

[msg MSG_036 [Mother Computer]]
What is happening!?

[msg MSG_037 [Futaba]]
Ribbon!

[msg MSG_038 [Ribbon]]
THAT'S... right. I am Ribbon. It's the[n]name that everyone has given me!

[msg MSG_039 [Aigis]]
Is this Orgia Mode!?

[msg MSG_040 [Yukari]]
B-But why!? She can really do that?

[msg MSG_041 [Futaba]]
I'll explain later! Ribbon―let's get[n]back to the hack!

[msg MSG_042 [Ribbon]]
I will defy the norms of this world!
Flowers are pretty... and I don't want[n]to ever forget that feeling...
I don't want to forget the person...[n]that everyone's accepted!

[msg MSG_043 [Mother Computer]]
To think that you could surpass my[n]processing speed...
I will not accept any defiance of the[n]world's standards!

[msg MSG_044 [Ribbon]]
I... I... won't lose!
Won't―Won't lo... sssseeee...

[msg MSG_045 [Haru]]
Ribbon-chan!?

[msg MSG_046 [Aigis]]
No! She is overheating!

[msg MSG_047 [Futaba]]
Wh-What!?
You can't keep going like this, Ribbon!

[msg MSG_048 [Ribbon]]
Gggg... Even if... ggggg... I break...[n]through this... gggg...
I will be satisfied... ggg... This is...[n]how I... truly am!

[msg MSG_049 [Mother Computer]]
Nghhh... Ggg... This... My recovery...[n]function's...
How dare you... YOU'RE NOTHING BUT AN[n]IRREGULARITY!

[msg MSG_050 [Ribbon]]
Gggg...gg...

[msg MSG_051 [Futaba]]
Ribbon!

[msg MSG_052 [P3 Hero]]
We'll definitely help create the world[n]that Ribbon wants!

[msg MSG_053 [Futaba]]
Ribbon!
Sorry, everyone... You guys go deal with[n]the Mother Computer!

[msg MSG_054 [P3 Hero]]
Yeah, leave the rest to us.
We'll definitely help create the world[n]that Ribbon wants!

[msg MSG_055 [Rise]]
Ribbon-chan stopped the Mother[n]Computer's auto-recovery function! Now's[n]your chance!

[msg MSG_056 [Fuuka]]
Everyone, get ready!

[msg MSG_057 [Mother Computer]]
GGGGGG... ELIMINATE CRITICAL ERRORS![n]ELIMINAAATE!

