[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 3][f 3 1 1 0 0 22011][f 6 1 2 0 0 6]斡Ch-Chie-chan![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4058]Whoa! Me asustaste...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 1][f 3 1 1 0 0 4011][f 6 1 2 0 0 4]夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 1 0][f 3 1 1 0 0 22012][f 6 1 2 0 0 10]Eh... Esto podr胤a sonar un poco raro,[n]preguntando esto de la nada, pero...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Puedes ense隠arme kung fu?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 4062][f 6 1 2 0 0 6]夷Kung fu? Supongo que podr胤a... 斡Espera![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Ann-chan, 夷tambi姻n eres un fan茨tico de[n]la pel胤cula kung fu?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Oh, oh, oh! 夷Cu茨l es tu prueba favorita[n]del Drag吋n? Es dif胤cil de elegir,[n]pero... Creo que el m胤o es el primero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 1 0][f 3 1 1 0 0 22057]夷Trial del Drag吋n? Lo siento, realmente[n]no s姻 qu姻 es eso.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Te estaba viendo pelear, y pens姻 que te[n]ve胤as muy bien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4066][f 6 1 2 0 0 0]夷C-Cool? 夷Yo?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡De ninguna manera! Eres m茨s genial que[n]yo, Ann-chan. 夷C吋mo consigo un cuerpo[n]como el tuyo? 夷Es tu dieta?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Come carne? Por favor dime que comes[n]carne y no s吋lo un mont吋n de hojas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 0][f 3 1 1 0 0 22018]夷Se va?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 0]Bueno, supongo que la dieta es[n]importante, pero tambi姻n me gustan las cosas con[n]crema batida...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 5 1 0][f 3 1 1 0 0 4087][f 6 1 2 0 0 4]夷Entonces trabajas?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Lo entiendo! S胤, Fantasma. 斡Los[n]ladrones siempre andan como locos![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 0][f 3 1 1 0 0 0]S胤, es verdad. Supongo que me desgasto[n]bastante de eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 4031]斡Lo sab胤a![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Vale, 夷qu姻 tal si me ense隠as a moverme como t雨?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 10 0 0][f 3 1 1 0 0 22019][f 6 1 2 0 0 0]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 0]Y, a cambio, te ense隠ar姻 kung fu.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]As胤, ambos aprenderemos los secretos[n]del otro a ser geniales. 夷Qu姻 piensas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Suena divertido.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Es un trato.[f 2 7 1 64 0 32][e]

[msg MSG_013 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 4058][f 6 1 2 0 0 0][f 6 1 30 0 0 0]- 夷kun? 夷Cu茨ndo llegaste aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ha estado aqu胤 todo el tiempo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]De todos modos, si eso es todo lo que[n]quieres saber, entonces estar胤a feliz de ense隠arte![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 0][f 3 1 1 0 0 4045]Ooh, eso suena tan fantasma ladr吋n-y...[n]Tan guay...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0]Hehe. Parece que ambos estamos[n]recibiendo lo que queremos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Si eso es todo lo que quieres saber,[n]entonces estar胤a feliz de ense隠arte![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 8 0 0][f 3 1 1 0 0 4033]Muy bien, a cambio de que te ense隠e kung fu...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 3 0 0][f 3 1 1 0 0 22072][f 6 1 2 0 0 6]Te ense隠ar姻 a moverse como un ladr吋n[n]fantasma. 斡Es un trato![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0]Vale, 夷d吋nde deber胤amos practicar? La[n]雨nica manera real de aprender esto es[n]salir y hacerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 66 1 0 0][f 4 6 3 0 0 6][f 3 1 1 0 0 3005]Heyyy! Elizabeth dice que tiene una[n]nueva proyecci吋n especial.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Lo tengo! 斡Ya vamos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Podemos averiguar el resto m茨s tarde, 夷de acuerdo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "斡Kung[n]Fu Catwalk!" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

