[msg MSG_000 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 68 1 0 1][f 4 6 5 12 0 3][f 3 1 1 0 0 5110]Yusuke-kun, estudias arte, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si no te importa, 夷crees que podr胤as darme[n]algunos consejos de dibujo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 24047]夷Tambi姻n te interesa el arte, Amagi-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Estaba pensando que podr胤a ponerlo en exhibición[n]en nuestra posada... 夷Qu姻 piensas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Buena idea.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Podr胤a dibujar en clientes.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Por qu姻 no la ayudas?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 24075]Hm. Algo dibujado por el propio gerente podr胤a[n]ayudar a la posada a crecer m茨s[n]popular.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]Muy bien. Todav胤a estoy entrenando, pero si[n]est茨 bien contigo, entonces acepto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5024][f 6 1 2 0 0 6]斡Gracias![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]... 夷Qu姻 hacemos ahora?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 24114]Primero, me gustar胤a saber qu姻 tipo de imagen[n]desea dibujar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puedes usar lo que quieras como un motivo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Lo tengo![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 5088]夷Qu姻 piensas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Se ve bien.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Parece lo suficientemente bueno para comer.[f 2 7 1 64 0 32][e]

[msg MSG_010 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 24067]No es nada malo, y...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]Encapsula perfectamente la belleza natural[n]de su forma curvada. Tienes buen ojo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 24073][f 6 1 2 0 0 3]Tienes razón. Debo admitir que est茨 empezando[n]a tener hambre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5032]Los camarones son geniales, 夷no? 斡Son[n]deliciosos, y son divertidos de mirar![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puedes hacer que cualquier parfait se vea[n]hermosa sólo colocando unos cuantos camarones[n]encima.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24054]夷Un parfait de camarones? Supongo que todav胤a[n]hay muchos platos que todav胤a tengo[n]que aprender sobre...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]En cuanto a tu dibujo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Amagi-san... 夷Podr胤as estar reteni姻ndote?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukiko]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 1][f 4 6 5 10 0 0][f 3 1 1 0 0 5018][f 6 1 2 0 0 0]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 5 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]No es una mala imagen, pero este camarón[n]parece algo restringido...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 0][f 3 1 1 0 0 0]夷Restricto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 0][f 3 1 1 0 0 24073]斡Libera tu interior! 斡Deja que tu l茨piz te[n]gu胤e![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ahora, mira al camarón otra vez! 夷Qu姻[n]significa para ti?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 5017][f 6 1 2 0 0 4]夷Eh? 夷Enfrente a los camarones? 夷Qu姻 significa[n]para m胤...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 7 1 0][f 3 1 1 0 0 0]Sh-Shrimp... Camarones...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Camarones, camarones... 斡SHRIMP![n][f 1 3 65535][f 1 1][e]

[msg MSG_019_02 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 5 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]S胤... 斡Ese es el aspecto! 斡Esa es la sensación![n]斡Pon todo sobre el lienzo![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 5 0 0][f 3 1 1 0 0 5069][f 6 1 2 0 0 6]斡Correcto! 斡Lo intentar姻![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 10 0 0][f 3 1 1 0 0 24095][f 6 1 2 0 0 6]斡Esto es...![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 0][f 3 1 1 0 0 0]Wh-夷Qu姻 piensas? I feel like I was really[n]able to capture the essence of the[n]shrimp...[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Eso es un camarón?[f 2 7 1 64 8 32][e]
[f 0 5 65278][f 2 1]Tienes mucho talento para esto.[f 2 7 1 64 8 32][e]
[f 0 5 65278][f 2 1]No sigo...[f 2 7 1 64 6 32][e]

[msg MSG_024 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 24099][f 6 1 2 0 0 6]夷Cómo podr胤a ser... 斡Para pensar que me llam姻[n]artista![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]夷Eh? 夷Es malo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 0][f 3 1 1 0 0 24085][f 6 1 2 0 0 6]夷Malo? 斡Todo lo contrario! 斡Puedo sentir tu[n]pasión! 斡Este camarón desafia todas las[n]expectativas![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Quiero ver m茨s de tu arte, Amagi-san![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 0][f 3 1 1 0 0 5017]Es amable de tu parte decir, pero no s姻 qu姻[n]m茨s dibujar...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ya veo... 夷Necesitas un motivo que sea tan[n]emocionante como el camarón?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Eh? S胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 0][f 3 1 1 0 0 24108][f 6 1 2 0 0 6]Entonces, lo encontrar姻 para ti. 斡Cuando lo[n]haga, quiero que vuelvas a dibujar para[n]m胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 6][f 3 1 1 0 0 26005]斡Heeey! He o胤do que hay un billete nuevo[n]disponible.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷Hm? 夷Qu姻 est茨s mirando, Inari? 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_032]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyección especial: "Inspiración[n]Investigación!" se ha añadido a la[n]taquilla.[n][f 1 3 65535][f 1 1][e]

