[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 6 12 100 1][f 3 1 1 0 0 6503][f 6 1 2 0 0 6][f 3 1 6 0 0 500]斡Oh! Estoy viendo un poco de agua cerca. 斡Ya[n]casi est茨n ah胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷De verdad vamos a encontrar una de esas[n]cosas amonestadas aqu胤? Viv胤an en el oc姻ano,[n]夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 0 0 0][f 3 1 1 0 0 25009]As胤 es. Supuestamente, los ammonitas viv胤an[n]en el fondo del oc姻ano.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Se ha dicho que se han encontrado fósiles en[n]r胤os y lagos que fueron una vez parte[n]del oc姻ano.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Ahh. Podremos cavar el mundo antiguo con[n]nuestras propias manos... 斡Esto seguramente[n]despertar茨 mi creatividad![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Chie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 4 0 0 1][f 3 1 1 0 0 4009][f 6 1 2 0 0 4]夷Es Fox siempre as胤?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Bastante.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Est茨 m茨s tranquilo de lo habitual.[f 2 7 1 20 6 32][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 6][f 3 1 1 0 0 26569][f 3 1 6 0 0 500]En realidad, no es tan malo ahora mismo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quiero decir, el otro d胤a que quer胤a esconder[n]al Monte Fuji para poder pintar el[n]amanecer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 4066][f 6 1 2 0 0 0]夷En serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 6][f 3 1 1 0 0 0][f 3 1 6 0 0 500]S胤, mucho.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quiero decir, el otro d胤a quer胤a ir al monte[n]Fuji para poder pintar el amanecer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 0 0][f 3 1 1 0 0 27074]S胤... Al menos pudimos evitar que subiera[n]con su uniforme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 0][f 3 1 1 0 0 0]Normalmente, lo juega bien, pero cuando se[n]pone as胤, no hay nada que decir lo que[n]podr胤a hacer...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El t胤o es un tonto para el arte. No sabe cómo[n]retenerse.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 1][f 3 1 1 0 0 24036]夷Un tonto? Te har姻 saber, tengo mejores[n]calificaciones que t雨...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Eso no es lo que digo! 斡No me disculpes as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 4 1 0 1][f 4 6 5 6 0 3][f 3 1 1 0 0 5125]No sabe cómo retenerse, 夷eh? Sinceramente,[n]estoy un poco celosa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0]Yukiko...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 0][f 3 1 1 0 0 5009]Siempre he intentado actuar correctamente y[n]cumplir con las expectativas de todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tal vez tambi姻n aparece en mis fotos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 24073]As胤 que eso fue... No te preocupes,[n]Amagi-san.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]La pasión que tienes en tu corazón es real.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Te ayudar姻 a desnudarlo todo! 斡Ahora, vamos![n]斡Exponerte al mundo![n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Vamos a parar aqu胤.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Tal vez te retengas.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]斡Ayuda! 斡Polic胤a![f 2 7 1 20 0 32][e]

[msg MSG_018 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 25 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Fox... 夷Puedo hablar contigo un momento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Sólo intento enseñarle a Amagi-san las[n]maravillas del arte...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 16 1 4][f 3 1 1 0 0 4093]S胤, s胤, d胤selo al juez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 26 12 100 1][f 3 1 1 0 0 26592][f 6 1 2 0 0 6]Olvidando el raro por ahora, estamos casi[n]all胤! 斡Sigue![n][f 1 3 65535][f 1 1][e]

