[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 3][f 3 1 1 0 0 3043][f 6 1 2 0 0 1]斡S胤! 斡Lo hicimos![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4134][f 6 1 2 0 0 7]Woohoo! 斡Carne! 斡Carne! 斡Carne![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 0][f 3 1 1 0 0 0]夷Podr胤amos olvidar la verdadera raz吋n por la[n]que vinimos aqu胤? Fue para derrotar al[n]FOE.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No vale la pena sudar los detalles, Naoto-kun![n]斡Todo est茨 bien que termina bien![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 4][f 3 1 1 0 0 0]Ahora, sin m茨s pre茨mbulos, comencemos la[n]fiesta...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 24095][f 6 1 2 0 0 0]夷Hm? 夷Qu姻 es esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Es duro como una roca... Sea lo que sea,[n]definitivamente no es carne.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 4059][f 6 1 2 0 0 0]夷Qu姻? 夷Qu姻 quieres decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 1 0][f 3 1 1 0 0 0]Parece ser una imitaci吋n realista.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aunque parezca carne en el exterior, est茨[n]hecha de madera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 0]Bueno... Ten胤a la sensaci吋n de que podr胤a[n]ser el caso viendo como el FOE lo estaba[n]usando como arma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 0][f 4 6 4 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Entonces no podemos comerlo? Entonces, 夷de[n]d吋nde vino ese olor incre胤ble de carne?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28014]Tengo la sensaci吋n de que probablemente vino[n]de ese lugar de la hamburguesa cercana.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Seriously...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 0][f 3 1 1 0 0 24099]Ngh... Una vez m茨s, estaba preparado para[n]una fiesta, y una vez m茨s, 夷me dices que[n]no puedo comer? Qu姻 terrible decepci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]A雨n as胤... 斡no fue todo por nada![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]La construcci吋n, la t姻cnica de color... 斡Es[n]apenas diferenciable de lo real! 斡No debo[n]olvidarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 0][f 3 1 1 0 0 22091][f 6 1 2 0 0 9]Oh... Ah胤 va otra vez...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 0 0 1][f 3 1 1 0 0 0]Bueno, si no podemos comerlo, no podemos[n]comerlo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Dir胤a que hemos terminado aqu胤. Volvamos al[n]Cine por ahora.[n][f 1 3 65535][f 1 1][e]

