[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 3][f 3 1 1 0 0 3039][f 6 1 2 0 0 9]Hombre, no importa lo lejos que[n]vayamos, es lo mismo una y otra vez.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Plantas y insectos gigantes hasta donde[n]puede ver el ojo. 夷Y los dinosaurios[n]tambi姻n? Este lugar es una locura...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0]Naturalmente, los caminos tampoco est茨n[n]pavimentados, lo que hace dif胤cil moverse...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 0 0 0][f 3 1 1 0 0 0]Bueno, el menos uno de nosotros est茨 bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 0 1][f 3 1 1 0 0 24063][f 6 1 2 0 0 6]斡Qu姻 exquisita vida vegetal! 斡Una[n]monta隠a de cuadernos no ser胤a suficiente para[n]capturar toda esta belleza![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]S胤, no te preocupes por 姻l.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 24 1 0 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]Sheesh, est茨 realmente metido en[n]esto... No va a vagar y ser comido, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 6][f 3 1 1 0 0 0]Sinceramente, Fox es m茨s probable que[n]coma uno de los dinosaurios...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Qu姻 demonios? 斡Es algo que esperar胤a de Chie![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 1][f 3 1 1 0 0 4036][f 6 1 2 0 0 6]斡Oye! 斡Incluso mi apetito no me har胤a[n]coger un dinosaurio y empezar a ahogarme![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No es que me opongo a probar[n]dinosaurios o nada. 斡No hay carne mala![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Hmm... carne[n]de dinosaurio a un lado, me pregunto[n]cu茨ndo podremos comer carne de nuevo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_010 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Hay perros calientes en el Cine.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Siento que vi algo antes...[f 2 7 1 20 8 32][e]
[f 0 5 65278][f 2 1]S吋lo tienes que hacer algo con el agua.[f 2 7 1 20 6 32][e]

[msg MSG_011 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 1][f 3 1 1 0 0 4010]Quiero decir, los perros calientes son[n]geniales y todo, pero la carne de[n]dinosaurio tiene m茨s... BAM, 夷sabes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Quiero comer en un pedazo de carne tan[n]grande, me sentir姻 como si nunca fuera[n]capaz de terminarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 1][f 3 1 1 0 0 4066][f 6 1 2 0 0 0]Espera, 夷en serio? 夷D吋nde?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]S胤, creo que yo tambi姻n. 夷D吋nde estaba?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 1][f 3 1 1 0 0 4125][f 6 1 2 0 0 9]Agua...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]S姻 que me quejo, pero el agua no lo[n]hace por m胤, no por nada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, 夷d吋nde encontramos este[n]pedazo de carne enorme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]Eso es lo que decimos. No est茨 aqu胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Espera, espera! 夷De d吋nde diablos has venido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 24031]O胤 que alguien mencion吋 carne. Mi[n]est吋mago est茨 listo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Este tipo es tan raro como Chie...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Mira, lamento decepcionarte, pero[n]probablemente no vamos a comer carne por un tiempo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 0][f 3 1 1 0 0 0]Entonces... 夷no hay... carne?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 24 6 1 0][f 3 1 1 0 0 0]Y aqu胤 estaba listo para festejar...[n]Ahora soy a雨n m茨s colgador...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 4][f 3 1 1 0 0 4013][f 6 1 2 0 0 9]S胤, toda esta charla sobre la carne me[n]ha hecho tener hambre tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 6 0 1][f 3 1 1 0 0 0]Un par de carn胤voros, estos dos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]La pr吋xima vez que tengamos una[n]oportunidad, Joker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "Meat &[n]the Art of Friendship" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

