[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 3][f 3 1 1 0 0 26044]斡Muy bien! 斡Le ganamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Fue muy r茨pido para revelarse. Pens姻[n]que intentar胤a jugar tonto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8067]Normalmente, eso es lo que har胤an. Sin[n]embargo, esta es una proyecci吋n especial.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es esencialmente una pel胤cula, as胤 que[n]imagin姻 que la Sombra seguir胤a alg雨n[n]tipo de regla para c吋mo funciona el final.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Supuse que si encontramos el correcto,[n]ser胤a forzado a revelar su verdadero yo.[n]Pens姻 que val胤a la pena intentarlo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Brillante.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Eso fue incre胤ble, detective.[f 2 7 1 20 0 32][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 8 0 1][f 3 1 1 0 0 8053]Por favor, no era s吋lo yo. Lo resolvimos juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 4][f 3 1 1 0 0 0]斡S胤, Oracle tambi姻n fue incre胤ble! 斡Se[n]acord吋 de todos esos testimonios![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 3][f 3 1 1 0 0 26032]Heheh. Tengo un buen recuerdo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Un gran detective necesita un gran[n]asistente! Ll茨mame Watson.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]夷Oh? Oracle, 夷lees novelas de detectives?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 3][f 3 1 1 0 0 26052]He le胤do los cl茨sicos hasta algunos de[n]los m茨s nuevos y populares al menos una vez.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Incre胤ble cu茨ntas historias puedes[n]contar sobre antiguas casas y islas desiertas![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 8029]Me gustar胤a investigar una escena del[n]crimen en un lugar como ese un d胤a.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]Aunque es raro encontrar una escena del[n]crimen como las que se encuentran en novelas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Con qu姻 frecuencia escuchas que un[n]detective acaba de pasar en una escena del[n]crimen? No funciona as胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 8033]Tampoco ves que la gente vaga por su[n]cuenta sabiendo que hay un asesino suelto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]A diferencia del mundo de la ficci吋n,[n]el trabajo de un detective es bastante directo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 3][f 6 1 2 0 0 6][f 3 1 1 0 0 26032]斡Totalmente! Esas personas que se[n]escapan por su cuenta...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Tendr胤as que ser un tonto para hacer algo as胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8032]Haha. Eso es lo que la gente espera de[n]novelas detective, supongo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin cosas como esas, los cr胤menes no[n]ocurrir胤an, y los detectives no tendr胤an[n]nada con qu姻 trabajar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 3][f 3 1 1 0 0 26068]S胤. Esas historias no ser胤an muy[n]divertidas si fuera que "la polic胤a vino por la ma隠ana"[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 0]Exactamente. El detective estar胤a fuera[n]del trabajo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hablando de lo que se espera, not姻 algo[n]interesante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 6][f 3 1 1 0 0 23002]Heeey, no quiero arruinar la diversi吋n, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 4][f 6 1 2 0 0 3][f 3 1 1 0 0 0]夷De qu姻 diablos est茨n hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 1][f 3 1 1 0 0 0]Mis disculpas. Supongo que me atraparon[n]en la conversaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 3][f 3 1 1 0 0 26045]Oye, fue una charla divertida. 斡Vamos a[n]hablar m茨s pronto![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8032]Claro, si quieres.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ahora, regresemos. Deber胤amos compartir[n]nuestros resultados con Elizabeth.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 5 1 1][f 3 1 1 0 0 28032]...Hmm. Fue un espect茨culo, detective[n]Prince. Muy entretenido.[n][f 1 3 65535][f 1 1][e]

