[msg MSG_000 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8130]Aqu胤 est茨 la terminal de b雨squeda.[n]Oracle, por favor?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 4][f 3 1 1 0 0 26088]Veamos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 4][f 3 1 1 0 0 0]Lo siento, no esperaba esto, pero no[n]est茨 conectado a la red...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso si hubiera hackeado aqu胤,[n]todav胤a no ser胤a capaz de encontrar esos coches.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 0]Eso es un problema. Supongo que[n]tendremos que encontrarlos solos.[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Tenemos que hacer algo.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]夷Hay otra manera?[f 2 7 1 20 0 32][e]

[msg MSG_005 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 4][f 3 1 1 0 0 26116]夷Hm? Espera un segundo... Hab胤a otra[n]terminal, 夷no?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tal vez pueda acceder a esa. S胤, vamos[n]a intentarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 8069]Entonces, para encontrar los coches de[n]la polic胤a, tendremos que encontrar el[n]otro terminal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Eso o cambiamos a buscar los coches por[n]nuestra cuenta. Dejaremos la decisi吋n, Joker.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 12 0 1][f 3 1 1 0 0 0]Esta terminal no va a cortarla.[n]Tendremos que hackear el otro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 26 12 0 1][f 3 1 1 0 0 0]Parece que ya no necesitamos esto. Ya[n]sabemos d吋nde est茨n los coches.[n][f 1 3 65535][f 1 1][e]

