[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54115]Buen trabajo, todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Vi todo desde la pantalla grande.[n]Encontraste el graffiti en cuesti吋n sin ning雨n problema.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]En medio de esa obra de arte era una[n]peque隠a mirada de cambio... Qu姻[n]terriblemente fascinante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1]Parecer胤a que las palabras no son la[n]雨nica forma de expresarse. Estoy[n]impresionado por esta revelaci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1]Gracias por permitirme disfrutar de una[n]maravillosa proyecci吋n. Perm胤tanme[n]preparar su recompensa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Se lo dar姻 a su debido tiempo. Por[n]favor, haz buen uso de ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 68 4 1 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 0][f 3 1 1 0 0 26110][f 6 1 2 0 0 4]夷Qu姻 pasa, Inari? 夷Tu mano se sale de[n]control otra vez?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 0]No. Es s吋lo que esta 雨ltima prueba[n]especial ha dado mucho que pensar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19047]夷En serio? 斡Pens姻 que lo hab胤as descubierto[n]todo, Yusuke-kun![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]Cre胤a que derrotar a Kamoshidaman[n]tendr胤a alg雨n tipo de efecto en el[n]pensamiento de la gente, pero...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tambi姻n hab胤a cre胤do que la pel胤cula[n]s吋lo continuar胤a mientras la cambiamos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Despu姻s de que nos fuimos, asum胤 que el[n]tiempo parar胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 23017]En realidad, estaba pensando lo mismo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una vez terminado, no pens姻 que habr胤a m茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 24079]Pero despu姻s de ver ese graffiti, me di[n]cuenta de que no era el caso.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Incluso sin nuestra influencia, la[n]pel胤cula seguir茨 cambiando.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esas personas se han convertido en[n]independientes, y ahora han empezado a[n]actuar de su propia voluntad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]No es una pel胤cula ordinaria. Es una[n]entidad viviente... 夷No estar胤as de acuerdo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Te siento.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Est茨s exagerando.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Mi mano, tembla...[f 2 7 1 64 8 32][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 25075]夷Una entidad viviente? Eso es una toma diferente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Nunca imagin姻 que un simple graffiti[n]ampliar胤a mis puntos de vista.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 0][f 3 1 1 0 0 25076]S胤, es un poco dif胤cil imaginar que la[n]pel胤cula est茨 viva.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 0]A雨n as胤, parece apropiado...[n]Definitivamente veo las cosas de forma diferente ahora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Nunca imagin姻 que un simple graffiti[n]ampliar胤a mis puntos de vista.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24031]Hah... 夷T雨 tambi姻n? Habiendo tocado el[n]arte de otro, mi mano se niega a establecerse.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Erk... 斡No! Ahora que estoy pensando en[n]ello, estoy perdiendo el control de nuevo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Anhelo dar forma a estos sentimientos[n]que brotan dentro de m胤...! 斡Si tuviera[n]un pincel y un lienzo ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 4][f 3 1 1 0 0 0]Oye, 夷te importa no disparar a Inari[n]as胤? Ahora vamos a tener que esperar a que se calme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 65 2 0 1][f 3 1 1 0 0 21031]Tienes raz吋n. Ser茨 muy interesante ver[n]c吋mo cambia esta pel胤cula de aqu胤 en adelante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]No voy a decir que[n]estamos sirviendo justicia o nada... pero[n]estoy feliz si le hemos dado a esa gente la[n]oportunidad de cambiar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 4 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Qu姻 emocionante! 斡Creo que mi mano[n]est茨 empezando a sacudirse tambi姻n![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 6 0 1][f 3 1 1 0 0 22093]Muy bien, suficiente de esa broma, o[n]vamos a empezar a actuar como Yusuke.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 66 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Esperemos que todas las otras pel胤culas[n]cambien mejor como esta![n][f 1 3 65535][f 1 1][e]

