[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 1 1 0 6][f 4 6 74 0 100 1][f 3 1 1 0 0 54115]Este es definitivamente el pescado que ped胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Debo decir que tus t姻cnicas de pesca[n]eran realmente una vista para contemplar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Supongo que deber胤a haber esperado[n]tanto de aquellos con el poder de la tarjeta salvaje.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 7 12 0 1][f 3 1 1 0 0 7052]Ustedes dos fueron incre胤bles...[n]Supongo que nos ense隠aste de qu姻 se trata ser un l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 0]斡S胤, el l胤der de tu grupo era tan[n]genial como el nuestro![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 0]Ambos tienen el tipo de carisma que[n]re雨ne a la gente... Supongo que por eso son[n]tan similares.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 1][f 3 1 1 0 0 5069]Mhm, tienes la sensaci吋n de que todo va[n]a estar bien cuando est茨s con tu l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡S胤! Me siento a gusto sabiendo que[n]tiene mi espalda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1064]Agreed. I felt the same from[n][f 6 1 30 0 0 0] during the special[n]screening.[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Charisma?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷El poder de la tarjeta salvaje?[f 2 7 1 64 0 32][e]

[msg MSG_008 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1029]No, nada de eso.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 3 1 1 0 0 0]Sent胤 que realmente har胤as algo[n]imprudente si fuera por tus amigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Por qu姻 m茨s desafiar胤as a un[n]espadach胤n con nada m茨s que un arma modelo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Tuve que hacer algo.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Perd吋n por los sentimientos.[f 2 7 1 64 4 32][e]

[msg MSG_010 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1066]S胤. Todo lo que pod胤a pensar era[n]proteger a mis amigos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Es lo mismo para ti, 夷no?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quieres proteger a los que dependen de[n]ti... Puedo sentirlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1048]No, yo tambi姻n lo siento.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 3 1 1 0 0 0]Estaba desesperada por proteger a mis[n]amigos. Estoy seguro de que fue lo mismo para ti.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quieres proteger a los que dependen de[n]ti... Puedo sentirlo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Tienes raz吋n.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Supongo que somos muy parecidos.[f 2 7 1 64 2 32][e]

[msg MSG_013 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 10 1 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Veo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 3 1 1 0 0 0]Me alegro de poder conocer a alguien[n]que siente lo mismo que yo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 3 1 1 0 0 0]Vamos a trabajar juntos desde aqu胤. Como amigos.[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Claro.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Por supuesto.[f 2 7 1 64 2 32][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 1 1 0 0][f 4 6 70 2 0 6][f 3 1 1 0 0 26058][f 6 1 2 0 0 6]夷Oh? 斡Es como si los dos hubieran[n]entrado en el modo de super amistad![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Kanji]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 7 10 0 4][f 3 1 1 0 0 0]No bromees... Los dos juntos son, como,[n]Nivel 99 o alguna mierda...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1074]No... Son 530.000.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷De qu姻 diablos est茨n hablando?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 4][f 3 1 1 0 0 0]Bueno, de cualquier manera... Si[n]ustedes dos trabajan juntos, no tienen nada que temer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 23 2 0 6][f 3 1 1 0 0 23126][f 6 1 2 0 0 6]斡Apuesto a que ustedes dos ser茨n a雨n[n]m茨s fuertes ahora![n][f 1 3 65535][f 1 1][e]

