[msg MSG_000 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4044]斡El tesoro es nuestro! 斡Eso hace dos![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 0]Un trabajo bien hecho. Ahora tenemos que[n]entregarlos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 9041]Ohoho! 斡Un 姻xito rotundo para el Vengador[n]Teddie![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 3][f 3 1 1 0 0 23104]夷Qu姻? 斡No tan alto![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 3][f 3 1 1 0 0 0]Mira, a雨n no hemos terminado. Un ladrón[n]fantasma no est茨 terminado hasta que vuelvan[n]a su escondite.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 1][f 3 1 1 0 0 0]Vaya, suena como un viaje de campo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 3][f 3 1 1 0 0 0]Un viaje de campo donde podr胤amos ser comidos[n]por los dinosaurios...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 3][f 3 1 1 0 0 0]Bueno, me alegro de que todo haya ido bien.[n]No est茨 mal para algunos ladrones fantasmas[n]de primera vez, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 26628]斡Buen trabajo, chicos! 斡Vuelve![n][f 1 3 65535][f 1 1][e]

