[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54010]Ahora bien, el objetivo de esta proyecci吋n[n]especial es...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Robar el tesoro del Seidoptera![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 8 0 3][f 3 1 1 0 0 23045]夷Treasure?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 6][f 3 1 1 0 0 0]No creo que sea el tipo de tesoro que[n]conocemos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Cierto. Esto no es un palacio, as胤 que tal[n]vez sea algo como oro o plata?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 54009]Seg雨n el billete, el objetivo es un par de[n]coronas de oro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 7]斡S胤! 斡Eso suena como un tesoro![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]S胤. Por favor, roba los tesoros ocultos de[n]los dinosaurios voladores, y tr茨elos aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3085]Espera, esas cosas son FOEs, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si tratamos de tomarlos de cabeza, probablemente[n]acabaremos como comida de dinosaurios.[n]夷C吋mo se supone que tenemos el[n]tesoro?[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]No necesitamos pelear.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]Entrenamos hasta que podamos vencerlos.[f 2 7 1 64 0 32][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4019][f 6 1 2 0 0 4]夷Eh? 夷C吋mo conseguimos el tesoro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 23030]Nyahaha... Somos los Ladrones Fantasma.[n]Tenemos que hacer cosas de estilo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4049][f 6 1 2 0 0 7]Ohh, entrenamiento, 夷eh? 斡Bien, har姻 lo mejor[n]que pueda![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 5][f 3 1 1 0 0 0]Oye, vamos, podemos hacerlo mejor que eso.[n]Somos los Ladrones Fantasma, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 3][f 3 1 1 0 0 25068]Es verdad. Los Seidopteras podr胤an no llevar[n]sus tesoros con ellos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si podemos averiguar d吋nde est茨n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 6][f 3 1 1 0 0 0]斡Entonces, entramos y los llevamos! 斡Los[n]negocios como siempre![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Vaya, realmente suenas como ladrones fantasma![n]斡Esto es tan emocionante![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 70 1 0 6][f 4 6 74 12 100 1][f 3 1 1 0 0 54100]Por favor, usa esto para llevar el tesoro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es una bolsa que Theo se prepar吋.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 3][f 3 1 1 0 0 0]Whoa, 夷Theodore hizo esto? Es tan talentoso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54059]S胤. Vino a m胤 con l茨grimas en los ojos y me[n]rog吋 que lo usara.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 1 3][f 3 1 1 0 0 0]Es obvio que est茨s mintiendo cuando sonr胤es[n]as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Eso me recuerda...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Donde hay ladrones fantasma, hay tesoro, y[n]viceversa. Estos dos est茨n profundamente[n]unidos e inseparablemente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Estoy deseando finalmente ver al Ladrones[n]Fantasma mostrar sus verdaderas[n]habilidades.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54029][f 6 1 2 0 0 6]斡Bailando por el aire, atravesando el suelo![n]斡En todas partes y en ninguna parte al[n]mismo tiempo![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 71 6 0 3][f 3 1 1 0 0 27054]No s姻 si podemos hacer todo eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 1][f 3 1 1 0 0 54071]No debes renunciar. "斡Creo que puedo! 斡Creo[n]que puedo!"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Creo en todos ustedes! 斡Ahora, vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 10 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Realmente est茨s presionando... En este punto,[n]es dif胤cil decir que no podemos[n]hacerlo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Definitivamente deber胤amos decir, "creemos[n]que no podemos"[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 2 0 1][f 3 1 1 0 0 23031]La Srta. Elizabeth tom吋 prestadas esas palabras[n]de alg雨n otro lugar, 斡pero creo que[n]est茨 funcionando! 斡Estoy despedido![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Es natural que un ladr吋n fantasma sea atra胤do[n]al tesoro, despu姻s de todo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 8 0 1][f 3 1 1 0 0 23042][f 6 1 2 0 0 7]斡Nya-hoo! Treasuure![n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 3][f 3 1 1 0 0 0]Oho! 斡Morgana est茨 motivada![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 6][f 3 1 1 0 0 0]Es como si alguien le diera un poco de[n]catnip...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 1][f 3 1 1 0 0 23036][f 6 1 2 0 0 2]Lo estoy. No. 斡A. CAT! 斡N-O-T! 夷Lo tienes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 5 12 0 3][f 3 1 1 0 0 0]S胤. T雨. Lo son. 斡C-A-T![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Noooooo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 3][f 3 1 1 0 0 21031]Haha, est茨s muy emocionada.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, no estoy a nivel de Morgana, pero[n]estoy un poco hip吋crita, 夷sabes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Eh? 夷En serio, Ryuji? 夷Tambi姻n te est茨s[n]poniendo feo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 21054]斡No soy un gato! 夷De verdad dije eso?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 0]Oye, 夷recuerdas c吋mo, antes, dec胤a que no[n]hemos hecho ning雨n trabajo de ladr吋n fantasma[n]en un tiempo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0]斡Ah, s胤! 斡Pero ahora podemos hacer eso![n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21032]Esto no es un escenario t胤pico como un banco[n]o un museo, sin embargo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]A雨n as胤, creo que esta pel胤cula ser茨 el lugar[n]perfecto para que hagamos lo nuestro.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 18 1 0][f 3 1 1 0 0 0]Y luego peleas con Seidopteras en el aire y[n]atacas el tesoro, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4067][f 6 1 2 0 0 7]斡S胤! 斡Suena bonito y ladr吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 9]... Dudo que seamos capaces de eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 6][f 3 1 1 0 0 0]Espera, 夷est茨n planeando luchar contra los[n]Seidopteras? Sabes que son FOEs, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54079]Las cosas est茨n realmente calentando ahora.[n]Estar姻 aqu胤, mirando con el aliento[n]batido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 0]斡Vamos, Ladrones Fantasma! 斡Ve por ese[n]tesoro![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]... Y ah胤 lo tienes.[n][f 1 3 65535][f 1 1][e]

[sel SEL_040 top]
[f 0 5 65278][f 2 1]Empecemos.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]斡Ese tesoro es nuestro![f 2 7 1 64 0 32][e]

[msg MSG_041 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 1][f 3 1 1 0 0 21045]Oh, te ves muy hinchada tambi姻n, [f 6 1 30 0 0 0][n]. Debo decir que es la primera vez[n]que me siento as胤 en un rato.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Yo tambi姻n! 斡Le mostrar姻 a todos el Teddie-way[n]del fantasma ladrones![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 0]Muy bien, salgamos. Aseg雨rate de que estemos[n]listos.[n][f 1 3 65535][f 1 1][e]

