[msg MSG_000 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 1][f 3 1 1 0 0 5109]Phew, sent胤 que mi coraz吋n estaba a punto de[n]parar. Qu姻 emoci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 3][f 3 1 1 0 0 0]Realmente estaba escondido en el Treasure[n]Spot, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0]夷As胤 que esto es una corona de oro? Ciertamente[n]tiene un brillo deslumbrante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Pero qu姻 querr胤a un dinosaurio con algo as胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 28013]Hmm... 夷Tal vez Seidopteras est茨n atra胤dos[n]al brillo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]He o胤do que los Crows tienden a recoger[n]objetos brillantes, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 3][f 3 1 1 0 0 3091]夷Me est茨s diciendo que la cosa cuenta como[n]un p茨jaro...? Es demasiado grande.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 0]Bueno, eso es uno abajo. As胤 que ahora tenemos[n]una m茨s que ir, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 0]El otro FOE probablemente escondi吋 su corona[n]de la misma manera.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4067]Impresionante, vamos a comprobarlo! 斡Lo[n]hicimos una vez, podemos hacerlo de nuevo![n][f 1 3 65535][f 1 1][e]

