[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54097]Disculpe, [f 6 1 30 0 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Sabes de esta cosa que es popular[n]entre los j吋venes y la cadera llamados "churros"?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 6][f 1 5][f 6 1 28 0 0 0]夷Te refieres a "churros", como el aperitivo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]No.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]He o胤do hablar de ellos.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Los amo..[e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 1 6][f 3 1 1 0 0 6059]夷Eh? 夷En serio?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Son como donas largas y finas[n]cubiertas de canela y az雨car![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 1 6][f 3 1 1 0 0 6023]夷As胤 que nunca has tenido uno antes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Son como donas largas y finas[n]cubiertas de canela y az雨car![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 4 6][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19031]*chuckle* [f 6 1 30 0 0]-kun 夷eres un gran fan de los dulces?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 3][f 3 1 1 0 0 0]Es crujiente en el exterior, s雨per[n]suave en el interior, y lleno de dulce y dulce bondad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 6][f 3 1 1 0 0 0]Son tan buenos, y son muy convenientes[n]tambi姻n. Es la merienda perfecta para[n]llevar al cine.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54016]Ah... As胤 es como dicen los rumores:[n]mejora la experiencia de cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Me gustar胤a mucho probar estos "churros"![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Habiendo pensado en esto, he ordenado[n]Theo para hacerme un poco o dibujar un[n]cuchillo a trav姻s de su est吋mago como tributo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 3][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19033]Ahahaha... Es una[n]orden... 夷Tenemos los ingredientes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Lo hice recoger los ingredientes, pero[n]ha estado lloriqueando por haber "una[n]cosa desaparecida"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Seg雨n 姻l, necesitamos algo llamado[n]"Si-na-mom", que es conocido por su olor apasionante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 6][f 3 1 1 0 0 6075]Cierto, los churros tienen ese olor a[n]canela, 夷no? Sin ella, sentir胤as que falta algo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54100]... Eso dijo, si por favor le ofrece a[n]esta mujer lamentable su ayuda.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]He o胤do que una planta conocida como el[n]"Cinnamon Fern" puede encontrarse en[n]alg雨n lugar de la pel胤cula de dinosaurios.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si no te importar胤a recoger algo para[n]m胤... No gratis, por supuesto.[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Lo tengo.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Suena como un arrastre...[f 2 7 1 64 0 32][e]

[msg MSG_014 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 6][f 3 1 1 0 0 22043]Yay, est茨 arreglado, entonces! Busquemos canela![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0]*chuckle* Suenas tan[n]emocionada. Apuesto a que vas por los churros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 6][f 3 1 1 0 0 22050]Hehe, me tienes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 6][f 3 1 1 0 0 0]斡Los churros son tan buenos ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 3][f 3 1 1 0 0 0]斡Estoy con ustedes en este! 斡Ser姻 el[n]mejor navegante que pueda ser![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 2 6][f 3 1 1 0 0 22090]Vamos, Elizabeth nos necesita. Vamos a ayudarla.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Adem茨s, probablemente comeremos unos[n]churros una vez que hayamos terminado, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0]*chuckle* 夷Es eso lo que buscas, Ann?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 6][f 3 1 1 0 0 22050]Hehe, me tienes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 6][f 3 1 1 0 0 0]斡Los churros son tan buenos ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 1 6][f 3 1 1 0 0 0]Oh, por favor di que s胤, [f 6 1 30 0 0]-san! 斡Te prometo que ser姻 el mejor[n]navegante que pueda ser![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 6 1 0 0][f 4 6 74 12 100 1][f 3 1 1 0 0 54024]Aprecio la bondad de todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esto puede ser ego胤sta de m胤, pero he[n]avanzado y preparado esto como una[n]proyecci吋n especial.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 10 0 0][f 3 1 1 0 0 0]斡Eso fue r茨pido![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Y lo que es m茨s, ya se han determinado[n]los lugares de los Ferns de Canela. Qu姻[n]incre胤blemente fortuito.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54127]Puede ser mejor si los escribes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 3 1 1 0 0 0]Las ubicaciones de Cinnamon Ferns se[n]han a隠adido al mapa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 2 6][f 3 1 1 0 0 22067]Esto es perfecto. 斡Vamos![n][f 1 3 65535][f 1 1][e]

