[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19044]斡Ah胤 est茨, el Cinnamon Fern![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 3][f 3 1 1 0 0 9131]*sniff sniff*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Qu姻 dulce olor... Es irresistible...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 1][f 3 1 1 0 0 0]Pero esto es, como, s吋lo hierba 'n'[n]mierda ... 夷C吋mo diablos lo usaremos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 28015]T胤picamente, la canela se hace mediante[n]el procesamiento de la corteza de canela seca.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aunque no estoy seguro si as胤 es como[n]funciona aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0]De cualquier manera, llevemos esto con[n]nosotros y d茨moslo a Theodore.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 3][f 3 1 1 0 0 6614]斡Bien, dos a la izquierda, vamos a por[n]ellos! 斡Cuidado con esas FOEs![n][f 1 3 65535][f 1 1][e]

