[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 1][f 3 1 1 0 0 56098]Phew... Gracias por esperar, todos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El palomita est茨 listo ahora. Por favor,[n]ay雨dense.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 28026]Gracias.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Adem茨s, si no es demasiado pedir, lo[n]apreciar胤amos si mantuvieras este nuevo lote un[n]secreto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 0][f 3 1 1 0 0 56068]Por supuesto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0][f 3 1 1 0 0 0]Juro por las palomitas, no le dir姻 a nadie.[n]Tienes mi palabra.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 72 1 0 6][f 4 6 8 2 0 1][f 3 1 1 0 0 0]Ahora, todo lo que tenemos que hacer es dejar[n]el disfraz de Teddie delante de la sala[n]de proyecci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 28067]Cierto. Pongamos nuestro plan en acci吋n.[n][f 1 3 65535][f 1 1][e]

