[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 6 2 1][f 3 1 1 0 0 54036]Parece que esos dos causaron un revuelo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]Esto fue claramente negligencia por parte de[n]Theo. No temas. Le dar姻 una estricta[n]conversaci吋n despu姻s de esto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Aqu胤 est茨 su recompensa por este tiempo. Por[n]favor, ac姻ptalo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54115]Excelente trabajo, todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 8 1 0 1][f 4 6 72 2 0 3][f 3 1 1 0 0 28031]Este caso ciertamente fue interesante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 0]S胤, estoy de acuerdo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ver a los dos me record吋 un poco de mi viejo[n]yo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Tu viejo yo?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Estuviste as胤?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 8012]Bueno, quiero decir que entiendo lo que se[n]siente cuando no puedes ser honesto contigo[n]mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 0]Eso es inesperado. Dir胤a que pareces mucho[n]m茨s maduro que esos dos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 8136]Hubo una vez cuando intent姻 suprimir qui姻n[n]era realmente para convertirme en mi ser[n]ideal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es gracias a mis amigos que pude aceptar mi[n]verdadero yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 1 0][f 3 1 1 0 0 0]Tu verdadero yo, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Akechi?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 0][f 3 1 1 0 0 28078]Estaba pensando que tienes amigos maravillosos.[n]Los detectives suelen trabajar solo,[n]夷sabes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Me alegro de poder trabajar contigo esta vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8031]*chuckle* Tambi姻n fue emocionante para m胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Otro detective Prince... Siento que trabajar[n]contigo me ayudar茨 a mejorar mis[n]habilidades deductivas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 28068]De hecho. Sigamos trabajando juntos para ver[n]que todos llegamos a casa con seguridad.[n][f 1 3 65535][f 1 1][e]

