[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54125]Ahora, para esta proyecci吋n especial...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Vas a ir a la Tierra de Junessic y[n]terminar con la tiran胤a sin control de la[n]Bestia Ravenosa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 3][f 3 1 1 0 0 6016]Carn胤voro... Espera, 夷no es una de esas FOEs?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54059]Correcto... Es una amenaza mucho m茨s[n]maliciosa que cualquier dinosaurio com雨n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Devorando todo a la vista, es la[n]definici吋n de B-E-A-S-T.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Actualmente se est茨 volviendo loco,[n]haciendo lo que quiera, donde quiera que quiera...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54080]Si algo no se hace pronto, es seguro[n]que te precipite tarde o temprano... o as胤 me temo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 3][f 3 1 1 0 0 0]La mierda que dices que no coincide con[n]tu expresi吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 6][f 3 1 1 0 0 12030]Eso suena como un oponente aterrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 10 1 3][f 3 1 1 0 0 18133]Igual que t雨...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 1 0 0][f 3 1 1 0 0 18112]Entonces, 夷c吋mo encontramos esta cosa?[n]夷Pueden los navegantes verlo por nosotros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 12 1 0 0][f 4 6 6 6 0 1][f 3 1 1 0 0 6009]Se est茨 moviendo tanto, no creo que[n]podamos determinar su ubicaci吋n exacta...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 1][f 3 1 1 0 0 0]Si tan solo tuvi姻ramos alguna pista de[n]d吋nde podr胤a ser...[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Busquemos huesos.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Cerca de su presa.[f 2 7 1 64 0 32][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 28075]Buena idea. Todo lo que tenemos que[n]hacer es buscar las pistas que quedan por[n]detr茨s por esta Bestia Ravenosa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si est茨 atacando y comiendo todo lo que[n]pone los ojos, entonces podemos seguir[n]su rastro de alimentaci吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 3][f 3 1 1 0 0 18091]Y eventualmente nos enfrentaremos con[n]el bastardo, 夷eh? Bastante horrible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 0]As胤 que tendremos que encontrar rastros[n]de su 雨ltima comida... En otras[n]palabras, huesos de dinosaurios frescos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Suena bien, [f 6 1 30 0 0]?[n][f 1 3 65535][f 1 1][e]

[sel SEL_011 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Te lo dejar姻.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Lo que quieras.[f 2 7 1 64 4 32][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 10 0 1][f 3 1 1 0 0 28019]夷Yo...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 1][f 3 1 1 0 0 0]Haha, muy bien. Supongo que deber胤a[n]sacar algo de peso de vez en cuando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 1][f 3 1 1 0 0 28033]Haha, 夷est茨s diciendo que quieres que[n]me encargue de esto?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Muy bien, entonces. Ten胤a curiosidad[n]sobre esta Bestia Ravenosa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 3][f 3 1 1 0 0 12071]Sea lo que sea, definitivamente es[n]dif胤cil. No puedo esperar a conocerlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 1][f 3 1 1 0 0 0]Me alegro de poder contar contigo.[n]Intentar姻 satisfacer las expectativas tambi姻n.[n][f 1 3 65535][f 1 1][e]

