[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 1][f 3 1 1 0 0 56001]Hola a todos. 夷C吋mo est茨s?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 100 3][f 3 1 1 0 0 54095]斡Villain![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 3][f 3 1 1 0 0 0]Ese atuendo sospechoso... 斡Alto ah胤! 斡Te[n]cortar姻 donde est茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 10 0 1][f 3 1 1 0 0 56052]S-Sister, por favor. Soy yo, Theodore.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 3][f 3 1 1 0 0 54023]夷Hm?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Parece que he saltado el arma. Ahora que te[n]miro m茨s de cerca, veo que eres mi[n]hermano.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19110]夷Teo? 夷Qu姻 haces aqu胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 1][f 3 1 1 0 0 0]Sobre eso... Vine aqu胤 porque tengo una[n]petici吋n.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]夷Una petici吋n?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Pasa algo?[f 2 7 1 64 0 32][e]

[msg MSG_007 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 1][f 3 1 1 0 0 56070]Bueno, si eres capaz...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay algo que me gustar胤a ponerme las manos[n]encima.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 4 0 1][f 3 1 1 0 0 56028]斡Lo llaman "Futurista Gizmo"![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 3][f 3 1 1 0 0 8018]夷Futurista Gizmo...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 3][f 4 6 80 12 0 1][f 3 1 1 0 0 56062]S胤. La pel胤cula "Tierra Ju茨tica" que pasaste[n]por...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aparentemente, es el hogar de una multitud[n]de tecnolog胤a de pr吋xima generaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 6][f 3 1 1 0 0 25115]Ahora que lo mencionas, esa pel胤cula tiene[n]lugar en el futuro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Las personas all胤 fueron capaces de revivir[n]los dinosaurios con su tecnolog胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 3][f 3 1 1 0 0 11020]Pero si estamos hablando del futuro, 夷no[n]ser胤a mejor "A.I.G.I.S".?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay m茨s tecnolog胤a all胤, 夷sabes?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 8010]Sobre eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 1][f 3 1 1 0 0 14003]La tecnolog胤a utilizada en "Tierra Ju茨tica"[n]es un poco diferente de la tecnolog胤a[n]que vimos en "A.I.G.I.S."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Lo que se encuentra en "A.I.G.I.S." se deriva[n]de la f胤sica ficticia...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 3][f 3 1 1 0 0 8116]斡S胤, eso es exactamente![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 0]Y la tecnolog胤a encontrada en "Tierra Ju茨tica"[n]se derivaba de la f胤sica del mundo[n]real.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Por lo tanto, incluso si ambas pel胤culas[n]contienen el mismo tipo de dispositivo,[n]pueden estar hechas de materiales completamente[n]diferentes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 21093]R-Right... Entonces... 夷 f胤sica?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 0]Hmm... Est茨n sintonizando a los normies para[n]que puedan hablar geek unos con otros.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 1][f 3 1 1 0 0 56043]Ustedes dos saben mucho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 6][f 3 1 1 0 0 8126][f 6 1 30 0 0 0], 夷est茨 bien contigo si buscamos este[n]"Futurista Gizmo"?[n][f 1 3 65535][f 1 1][e]

[sel SEL_019 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Vale.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Bien por m胤.[f 2 7 1 64 0 32][e]

[msg MSG_020 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 1][f 3 1 1 0 0 56041]Much appreciated, [f 6 1 30 0 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y si lo consideramos una proyecci吋n especial,[n]podr姻 presentarte con una recompensa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Con eso, hermana, 夷podr胤as crear un...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 3][f 3 1 1 0 0 54014]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 1][f 3 1 1 0 0 0]夷Sister?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 10 100 3][f 3 1 1 0 0 54095]夷De d吋nde viene este misterioso y[n]disfrazado...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 6 0 1][f 3 1 1 0 0 56037]*suspira*[n][f 1 3 65535][f 1 1][e]

[msg MSG_025]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "Long-lost[n]Tech" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

