[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 54142]Bravo, bravo. Mi sombrero est茨 fuera de[n]tus habilidades de investigaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 74 1 100 0][f 4 6 11 12 1 3][f 3 1 1 0 0 11092]Realmente nos diste un mal momento, ya[n]sabes. Fue dif胤cil imaginarlo todo con[n]cerca de ninguna informaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]Pero la gente de Kamo City puede dormir[n]bien esta noche, gracias a m胤...[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Junpei, Ace Detective?[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]...[f 2 7 1 64 4 32][e]

[msg MSG_003 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 1 1][f 3 1 1 0 0 13053]J-Junpei, Ace Detective...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 3][f 3 1 1 0 0 11019][f 6 1 2 0 0 1]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 0 6][f 3 1 1 0 0 10060][f 6 1 2 0 0 0]夷Qu姻...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13033]... Ten胤a la sensaci吋n de que ibas a decir eso.[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Eso es pensar como Junpei.[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]夷Te sientes bien?[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]Eso fue hermoso...[f 2 7 1 64 12 0][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 8 0 0][f 3 1 1 0 0 13058][f 6 1 2 0 0 3]夷Puedes dejar de hablar de eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 8 0 0][f 3 1 1 0 0 13040][f 6 1 2 0 0 3]Dijiste que deb胤a intentarlo, as胤 que...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 8 0 0][f 3 1 1 0 0 13052][f 6 1 2 0 0 10]No act雨es como si fuera tan conmovedor...![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 65 8 1 3][f 3 1 1 0 0 21031]Bueno, s吋lo resolvimos el caso por toda[n]la informaci吋n que obtuvimos de la[n]gente de la ciudad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 1][f 3 1 1 0 0 0]No creo que hubieran hecho algo as胤[n]antes. Realmente han cambiado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 3][f 3 1 1 0 0 11029]Supongo que lo m茨s importante es el[n]tipo al mando. Ese es el camino del mundo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 10 2 6][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Porque sabes mucho sobre eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 74 0 100 1][f 3 1 1 0 0 54115]Ahora bien, aqu胤 est茨 tu recompensa.[n]Por favor, ac姻ptalo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 13129]Perd吋name, pero me gustar胤a que tuvieras esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 3][f 3 1 1 0 0 25088][f 6 1 2 0 0 4]夷Gloves?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 0]Son guantes de moto. Quer胤a darte las[n]gracias por todo lo que hiciste por m胤 esta vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 8 0 0][f 3 1 1 0 0 25040][f 6 1 2 0 0 10]No necesitas agradecerme... Adem茨s, a雨n[n]no tengo mi licencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 10 0 0][f 3 1 1 0 0 13093]夷En serio? Despu姻s de ver a tu Persona, asum胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 25015]Creo que es s吋lo una representaci吋n de[n]c吋mo me siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 0]Responsabilidad, regulaciones... S吋lo[n]quiero tirar todas esas cosas a toda velocidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 1 0][f 3 1 1 0 0 13033]Parece que ambos cargamos una carga[n]similar despu姻s de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 1 0][f 3 1 1 0 0 0]Siento el mismo sentido de la libertad[n]cuando estoy montando mi moto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022_2 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 0]No te obligar姻 a aceptar estos guantes, pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022_3 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 13069]Al ver como soportas la misma carga que[n]yo, quiero que sepas ese sentimiento[n]del viento en tu cara alg雨n d胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 0][f 3 1 1 0 0 0]Kirijo-san...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 25024][f 6 1 2 0 0 7]Gracias. 夷Qu姻 dices si ambos sacamos[n]nuestras bicicletas en alg雨n lugar, una[n]vez que consiga mi licencia?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 1 0][f 3 1 1 0 0 13070]Por supuesto. Una vez que volvamos al[n]mundo real...[n][f 1 3 65535][f 1 1][e]

[msg MSG_024_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13032][f 6 1 2 0 0 6]斡Vamos juntos, trineo![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 25072][f 6 1 2 0 0 6]斡S胤, es una promesa![n][f 1 3 65535][f 1 1][e]

