[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 8 1 1][f 3 1 1 0 0 11097][f 6 1 2 0 0 9]Estoy vencido.[n][f 1 3 65535][f 1 1][e]

[msg MSG_000_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]Es un callejón sin salida, as胤 que podemos[n]tomar un pequeño descanso antes de regresar,[n]夷verdad?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]Claro, tomemos un descanso.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Si es necesario.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Empieza a correr.[f 2 7 1 20 6 32][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11042][f 6 1 2 0 0 7]斡S胤, me sientes![n][f 1 3 65535][f 1 1][e]

[msg MSG_002_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]Apuesto a que alguien tan amable como t雨 es[n]un verdadero 姻xito con las damas. O tal[n]vez ya est姻s estable con alguien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 4 0 0][f 3 1 1 0 0 11058][f 6 1 2 0 0 10]斡Eres un esclavista! 斡Eso no te har茨 popular[n]con las damas![n][f 1 3 65535][f 1 1][e]

[msg MSG_003_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0]Hablando de eso, 夷qu姻 tal si te doy algunos[n]punteros?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 3][f 3 1 1 0 0 13034]斡Iori![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 1][f 3 1 1 0 0 11062][f 6 1 2 0 0 0]夷S胤?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13092]Si tienes tiempo para charlar, entonces[n]claramente tienes energ胤a que ahorrar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 0 0][f 3 1 1 0 0 13107][f 6 1 2 0 0 1]斡As胤 que menos hablando, m茨s caminando![n]斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 11097]S胤, señora...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 4 1 3][f 3 1 1 0 0 13040]Sinceramente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 25003][f 6 1 2 0 0 4]夷Est茨s bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 1 0][f 3 1 1 0 0 13009]Mis disculpas por el desembolso; es sólo mi[n]negligencia como l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 0][f 3 1 1 0 0 0]No es una mala persona en el corazón, pero[n]es demasiado descuidado. O tal vez no sabe[n]cu茨ndo ponerse serio...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 6 0 0][f 3 1 1 0 0 25076]Los problemas nunca parecen terminar para[n]nosotros los miembros del grupo mayor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13070]Ah, cierto, t雨 tambi姻n eres un tercer año.[n]Me encantar胤a charlar contigo en alg雨n[n]momento...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 25 1 0 0][f 4 6 13 12 0 0][f 3 1 1 0 0 0]Pero no quiero ser hipócrita. Deber胤amos[n]irnos por ahora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Se ha añadido a la taquilla una nueva selección[n]especial: "Aquellos que est茨n en la[n]parte superior".[n][f 1 3 65535][f 1 1][e]

