[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54125]El objetivo de esta pr吋xima prueba especial[n]es recoger tres tipos de materiales.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 1][f 3 1 1 0 0 54005][f 6 1 2 0 0 6]Ahora, si nuestro especialista en materiales[n]describir胤a los materiales en detalle...[n]斡Theo! Theo, 夷d吋nde est茨s?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Theo, sal de aqu胤, o as胤 que ay雨dame, llenar姻[n]tu m茨quina de palomitas con polvo de[n]soja y..[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 10]斡Estoy aqu胤! 夷C吋mo puedo ayudarte, hermana?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]Describa a ellos los materiales necesarios.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 56062]Por supuesto. El Mago Fantasma dejar茨 el Oso[n]Teddy.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La arena flotante caer茨 el Kaleidoscopio...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y la Figura de Arcilla se puede obtener de[n]la Unidad de Rampage.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 54101]Estas son todas partes raras de una Sombra...[n]Nos gustar胤a que los extraigas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Materiales raros? Qu姻 arrastre...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 74 1 100 0][f 4 6 80 4 0 0][f 3 1 1 0 0 56050][f 6 1 2 0 0 6]斡Por favor, no digas esas cosas y acepta esta[n]proyecci吋n![n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Eres muy entusiasta.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Qu姻 pasa?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No.[f 2 7 1 64 6 32][e]

[msg MSG_008 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19068]S胤, 夷qu姻 est茨 pasando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19019]Mmhm, pareces estresado. 夷Todo bien?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 10 0 0][f 3 1 1 0 0 56052][f 6 1 2 0 0 6]斡Ten un coraz吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19090]Hang on. Estoy seguro de que hay una buena[n]raz吋n por la que act雨a as胤. Cierto. 夷Theo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0][f 3 1 1 0 0 56062]S胤... Si recogemos los materiales enumerados,[n]podremos crear nuevos equipos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cada material es bastante robusto. Nos[n]permitir茨n fabricar equipos m茨s grandes,[n]mejores y m茨s voluminosos.[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Son tan fuertes?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Eso es emocionante.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Bulky, 夷eh?[f 2 7 1 64 0 32][e]

[msg MSG_014 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0][f 3 1 1 0 0 56097]S胤. Por mi honor, te har姻 algo valioso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11029][f 6 1 2 0 0 7]斡El equipo duro ser胤a un sue隠o![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0][f 3 1 1 0 0 56097]S胤. Por mi honor, te har姻 algo valioso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 10013][f 6 1 2 0 0 3]No s姻 c吋mo me siento sobre la voluminosa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 0]Me refiero a la fuerza del equipo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tengan la seguridad, les garantizo que estar茨n[n]felices tanto con su eficacia como[n]con su dise隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 100 0][f 3 1 1 0 0 54081]Dios, 夷c吋mo te atreves a pensar que puedes[n]usar la prueba especial para tu propia[n]ganancia.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 0][f 3 1 1 0 0 54095]Tengo la mitad de la mente para decirte que[n]te impales donde est茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Parece que mi hermano sin valor est茨 decidido[n]a cortarle la cabeza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 1 0][f 3 1 1 0 0 56051][f 6 1 2 0 0 0]夷Mi cabeza?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 0 0 0][f 3 1 1 0 0 56070]Bien. Si est茨s dispuesto a arriesgar tus[n]vidas por el bien de estos materiales...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 80 0 1 0][f 3 1 1 0 0 0]Entonces har姻 lo mismo. Por favor, prestame[n]tu ayuda.[n][f 1 3 65535][f 1 1][e]

