[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 12 100 1][f 3 1 1 0 0 54081]No estoy satisfecho con tus resultados.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]Tu objetivo era "recoger" los[n]ingredientes, pero parece que fuiste adelante y[n]los cocinaste...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Gracias a tu ego胤smo, me sent姻 aqu胤[n]medio hambriento.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 1][f 3 1 1 0 0 54095][f 6 1 2 0 0 2]斡Ahora mi hambre es tan intensa, estoy[n]llena de un impulso cada vez mayor para[n]DESTROY TODO![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 0]Tenemos ingredientes sobrantes. Shinji[n]probablemente pueda hacer algo para ti.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 6][f 3 1 1 0 0 18050]夷Qu姻 demonios? No me ofrezcas as胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 54041]Supongo que se puede arreglar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Muy bien. 斡Esperar姻 a esta fiesta hasta[n]el final de los d胤as si es necesario![n][f 1 3 65535][f 1 1][e]

[msg MSG_003_05 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Sheesh... Esto no va a ser f茨cil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 1][f 3 1 1 0 0 24112]Es bastante peculiar, pero me siento[n]mucho m茨s poderoso despu姻s de comer la[n]cocina de Aragaki-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 0 0 0][f 3 1 1 0 0 0]Probablemente es porque est茨s lleno.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]De hecho. Lleno de inspiraci吋n! 斡Qu姻[n]sensaci吋n estimulante![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 12031]Sabes lo que dicen: no puedes luchar[n]con el est吋mago vac胤o.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]La 雨nica manera de asumir a los[n]oponentes realmente duros es con entrenamiento[n]y una dieta adecuada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Lo dije una vez, lo dir姻 dos veces:[n]夷puede con la prote胤na?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12030]Darnos prote胤nas es como dar alas a un[n]tigre. Es una coincidencia hecha en el cielo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 7 1 0][f 3 1 1 0 0 18036][f 6 1 2 0 0 6]Peque隠o... 夷Qu姻 acabo de decir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Tiene raz吋n. Esa comida era perfecci吋n absoluta![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]Tal vez pueda canalizar este[n]sentimiento en mi rutina de combate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12130][f 6 1 2 0 0 6]斡S胤! 斡Tomaremos prote胤nas junto a la[n]comida de Shinji y entraremos para matar![n]斡Ser茨 genial![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 18097][f 6 1 2 0 0 9]Estos dos son algo m茨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, si tienen hambre, no me importa[n]cocinar para ustedes otra vez...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Pero si te pillo poniendo esa mierda de[n]prote胤na en todo, habr茨 un infierno que[n]pagar, 夷entendido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 18 1 0 0][f 4 6 68 4 0 0][f 3 1 1 0 0 24067][f 6 1 2 0 0 4]Entendido... Tendremos que comerlo en[n]nuestro tiempo. 斡Muy bien, entonces![n]Buena comida y prote胤na es![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12043][f 6 1 2 0 0 4]斡Suena como un plan![n][f 1 3 65535][f 1 1][e]

