[msg MSG_000 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 1][f 3 1 1 0 0 16013]Fantasmas ladrones, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hm? 夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 16078]Nada. Es s吋lo... cambiar en un disfraz[n]y luchar contra el mal suena como algo[n]que ver胤as en un c吋mic.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces... 夷por qu姻 se convirtieron en[n]ladrones fantasma?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Nos equivocamos.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Simplemente sucedi吋.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Porque est茨 bien.[f 2 7 1 20 0 32][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 16039][f 6 1 2 0 0 4]夷Error?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 0][f 3 1 1 0 0 0]Adultos de mierda Buncha... Todos vimos[n]de primera mano lo desordenados que pueden ser.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 0][f 3 1 1 0 0 21033]Bueno, s胤, empez吋 as胤...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 0]Pero entonces hicimos nuestra meta de[n]detener a todos esos idiotas que pensaban[n]que pod胤an hacer lo que quisieran.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23032]Bueno, supongo que es verdad.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Suena bastante bien para herir el mal[n]en nombre de la justicia, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 6][f 3 1 1 0 0 22017]Est茨bamos planeando que fuera una cosa[n]de una sola vez...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 6][f 3 1 1 0 0 0]Pero entonces nos dimos cuenta de que[n]no 姻ramos los 雨nicos adultos aprovechando.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que seguimos adelante, esperando[n]que podamos hacer una diferencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052][f 6 1 2 0 0 6]Y as胤 nacieron los Fantasmas,[n]protegiendo a los d姻biles y cambiando los[n]corazones de los imp胤os![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 1 0][f 3 1 1 0 0 16039]Cambiar los corazones de los malvados...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Est茨s bien, Ken?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 16037][f 6 1 2 0 0 6]Estoy bien. 斡Gracias por compartir![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]... 夷Qu姻 pasa con Ken-kun?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 1 3][f 3 1 1 0 0 21033]Bueno, 姻l es esa edad, 夷sabes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cada tipo tiene un tiempo cuando quiere[n]ser un superh姻roe.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 1 0][f 3 1 1 0 0 22013][f 6 1 2 0 0 4]夷En serio?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "Una[n]Lecci吋n en Justicia" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

