[msg MSG_000 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 1][f 4 6 13 2 0 3][f 3 1 1 0 0 13005][f 6 1 26 0 0 0]Parece que est茨s muy bien con todos aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19030]*chuckle* Casi[n]siento que estoy de vuelta a casa.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]No es dif胤cil llevarse bien con todos[n]cuando act雨an como siempre lo hacen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 12031]夷Oh? 夷No hay mucha diferencia entre[n]nosotros aqu胤 y nosotros en tu mundo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19129]斡As胤 es![n]Mitsuru-senpai es siempre super madura y confiable.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Shinjiro-senpai es siempre muy amable y[n]a menudo se escapa a la mascota[n]Koromaru y le hace comer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 10 0 6][f 3 1 1 0 0 18053][f 6 1 2 0 0 10]夷Eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Y cada vez que intento[n]salir con Akihiko-senpai, siempre se[n]convierte en alg雨n tipo de rutina de entrenamiento...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]As胤 que termino jodiendo de vuelta al[n]dormitorio, empapado en sudor.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 18097][f 6 1 2 0 0 9]Maldici吋n. Aki, eres un dolor en el[n]culo en ese mundo tambi姻n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 0]夷A qui姻n llamas dolor en el culo? Es[n]importante que entrenes diariamente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm sure the other me is only doing it[n]because he cares about you,[n][f 6 1 27 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 10 2 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19018]Huh? Claro...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 0 0 0][f 3 1 1 0 0 0]Si puedes seguir con mi rutina,[n]entonces est茨s en buena forma.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 0][f 3 1 1 0 0 0]De acuerdo, entonces, tal vez[n]deber胤amos ir a trabajar m茨s tarde. Nos vamos a[n]debilitar si nos largamos demasiado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 0][f 3 1 1 0 0 18092][f 6 1 2 0 0 4]De esto estoy hablando. No necesitas[n]escuchar lo que dice Aki si no quieres.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]斡Oh, no! 斡No es que no quiera![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Estaba sintiendo el impulso de moverse![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 1 0][f 3 1 1 0 0 12030][f 6 1 2 0 0 7]夷Ves? 夷Escuchaste eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Tch... Si dejas la rutina a Aki, qui姻n[n]sabe lo que acabar茨s haciendo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 0][f 3 1 1 0 0 0]- Hola. Si planeas entrenar, av胤same.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12045]夷Por fin vas a trabajar conmigo, Shinji?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Est茨 bien... 斡Parecer姻 una rutina incre胤ble![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 1 0][f 3 1 1 0 0 18097]Eso no es lo que digo, tonto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 1][f 3 1 1 0 0 13092]Francamente, me preocupar胤a mucho dejar[n]solo a los dos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Ser茨 mejor que controlen sus[n]temperamentos. 夷Entendido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial:[n]"Confianza Transcendental" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

