[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 3][f 3 1 1 0 0 11009]Buenas noches, y bienvenido a "Junpei lo[n]cree, o no"...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hay muchas cosas extraéšas en este mundo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11016]Sucediå despuå§»s de la puesta del sol, en un[n]pequeéšo lugar aislado como el que estamos[n]ahora...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Como una chica solitaria se apresurå a casa,[n]de repente se dio la extraéša sensaciå‹n[n]de que alguien la estaba viendo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11013][f 6 1 2 0 0 6]Por curiosidad, se dio la vuelta... y vio a[n]un tèƒ¤tere sin vida y desgastado mirèŒ¨ndola[n]tan de cerca.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 1][f 3 1 1 0 0 25103][f 6 1 2 0 0 0]*jadeo*[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 0]Trastornada por la vista, la chica se marchå,[n]pero no importa adå‹nde fue, ella todavèƒ¤a[n]podèƒ¤a sentir esos ojos mirèŒ¨ndola...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Algo estaba mal, penså, asèƒ¤ que se dio la[n]vuelta una vez mèŒ¨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 11103][f 6 1 2 0 0 6]æ–¡Så‹lo para ver el tèƒ¤tere de antes![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4105][f 6 1 2 0 0 6]æ–¡Noooooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 0][f 3 1 1 0 0 0]El tèƒ¤tere empezå a arrastrarse hacia ella...[n]Creeeeeeak... Creciå mèŒ¨s cerca y mèŒ¨s...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]De repente, sacå un cuchillo, y con un gemido[n]aterrador, dijo:[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 4 0 6][f 3 1 1 0 0 5030][f 6 1 1 0 0 1][f 6 1 2 0 0 1]"æ–¡Dale a la carne un montå‹n de calor para un[n]buen borde sellado!"[n][f 1 3 65535][f 1 1][e]

