[msg MSG_000 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 1][f 4 6 4 0 0 4][f 4 6 5 12 0 3][f 3 1 1 0 0 5125]Buenas noches, y bienvenido a "Yukiko[n]lo cree, o no"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tal vez era s吋lo yo... pero 夷alguien[n]sinti吋 una presencia extra隠a durante la[n]investigaci吋n?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 0]夷Alguien oy吋 el sonido d姻bil de los[n]pasos desde atr茨s mientras caminamos por el[n]centro de investigaci吋n...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 1][f 3 1 1 0 0 4054][f 6 1 2 0 0 0]夷Qu姻? 夷Yukiko?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 0]Me preguntaba qu姻 era. Me dije que[n]deb胤a estar pensando sobre cosas...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 5 6 0 3]Sin embargo, no pude sacudir la[n]sensaci吋n. Quer胤a dar la vuelta, pero sent胤[n]que, si lo hiciera, pasar胤a algo terrible...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 25 6 0 1][f 3 1 1 0 0 25099][f 6 1 2 0 0 9]Espera, para...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 6][f 3 1 1 0 0 11009]Yo tambi姻n no pude resistir... As胤 que[n]me di la vuelta.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cuando lo hice, me encontraron con la[n]silueta de un hombre extra隠o que parec胤a[n]estar mir茨ndome.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 6][f 3 1 1 0 0 11010]Su cara estaba p茨lida y sin ning雨n[n]rastro de vida. Sus ojos estaban abiertos y[n]sangrientos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El sudor fr胤o corri吋 por la espalda de[n]mi cuello. Me pens姻: "Esto es malo..."[n]Entonces, de repente..[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 1][f 3 1 1 0 0 25103][f 6 1 2 0 0 1]斡Noooooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 5030][f 6 1 2 0 0 1]El hombre se acerc吋 a nosotros, y de su[n]boca torcida grit吋: "斡Tengo mucha[n]hambre! 夷Puedes ahorrar algo de comida?"[n][f 1 3 65535][f 1 1][e]

