[msg MSG_000 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 1 1][f 3 1 1 0 0 15039][f 6 1 2 0 0 1]Objetivo eliminado. 斡Bien hecho, todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 3][f 3 1 1 0 0 0]斡Eso no fue nada! Era b茨sicamente una etapa[n]de bonificación.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 6][f 3 1 1 0 0 0][f 3 1 6 0 0 500]Bueno, tenemos a la Srta. Robot aqu胤! 斡Todos[n]saben que los mejores mechs tienen la[n]cosa blanca, roja y amarilla![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15124]夷As胤 funcionan las cosas en tu mundo, Oracle?[n]Entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 17 0 0 0]Buen trabajo, todos. Volvamos y reportemos.[n][f 1 3 65535][f 1 1][e]

