[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 3][f 3 1 1 0 0 54125]El objetivo de esta pr吋xima prueba[n]especial es bastante simple.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Debes derrotar a uno de los KNS-1000[n]encontrados en "A.I.G.I.S."[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 1][f 3 1 1 0 0 0]Lo entiendo, por "KNS-1000", se refiere[n]al tipo de vigilancia FOE, 夷correcto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15071]Ya veo. Un oponente problem茨tico. Sin[n]embargo, tengo algunos datos sobre dicho enemigo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esta es una oportunidad perfecta para[n]calibrar mis niveles de energ胤a.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 3][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]Aigis,[n]夷todav胤a necesitas tiempo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15074]Tonter胤as. Todos los sistemas funcionan[n]correctamente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin embargo, no estaba dise隠ado para[n]luchar en estas pel胤culas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Para ver que realizamos nuestras[n]misiones, debo adquirir alguna experiencia de combate.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]夷Est茨s bien?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No te empujes.[f 2 7 1 64 0 32][e]

[msg MSG_006 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 15023]I appreciate the sentiment,[n][f 6 1 30 0 0 0]-san.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Sin embargo, soy un arma anti-Shadow.[n]Mi deber es proteger a todos ustedes.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Las batallas m茨s dif胤ciles seguramente[n]est茨n por delante, y si soy para[n]protegerte, tendr姻 que estar preparado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 6][f 3 1 1 0 0 22047]Eso es... bastante genial.[n][f 1 3 65535][f 1 1][e]

[sel SEL_008 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Trabajaremos juntos.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]No lo soportas solo.[f 2 7 1 64 0 32][e]

[msg MSG_009 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 10 0 1][f 3 1 1 0 0 15017][f 6 1 2 0 0 4]夷Trabajar juntos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]tiene[n]raz吋n, Aigis. Somos un equipo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]No hay necesidad de que lo soportas[n]todo por ti mismo. Trabajaremos juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 1][f 3 1 1 0 0 15069]斡Entendido! 斡Entonces vamos todos a la[n]proyecci吋n especial juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 6 0 1][f 3 1 1 0 0 0]夷Eso es un no? Esperaba prestar asistencia...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]tiene[n]raz吋n, Aigis. No tienes que soportarlo todo[n]para ti mismo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Somos un equipo. Todos deber胤amos trabajar juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 1][f 3 1 1 0 0 15030]Gracias a ambos. 斡Hagamos todo lo posible![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 6][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2006]Vale, [f 6 1 30 0 0 0], salgamos cuando estemos listos.[n][f 1 3 65535][f 1 1][e]

