[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54010]Esta pr吋xima prueba especial promete[n]ser una aventura bastante llena de acci吋n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Es una b雨squeda de tesoros. 斡Tu tarea[n]ser茨 localizar el tesoro escondido dentro[n]de la selva![n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]夷Qu姻 m茨s es nuevo?[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Eso es lo nuestro.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Tesoro oculto?[f 2 7 1 64 0 32][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23069]S胤. Encontrar tesoro es la especialidad[n]de Ladrones Fantasma.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 clase de tesoro es?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 54016]Parece ser una especie de artefacto[n]preciado un investigador destinado a[n]ofrecer a su amante...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esperando hacerlo cuando su[n]investigaci吋n estaba completa, lo escondi吋 para su custodia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 0 0][f 3 1 1 0 0 0]... Lo que le pas吋 al investigador..[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54023]Aqu胤 hay un mapa de la ubicaci吋n del[n]tesoro... 夷Oh? Parece que hay algo en la espalda...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 0]"Una vez que termine este trabajo,[n]finalmente se lo propongo"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]"Esta obra es la pura encarnaci吋n de la[n]belleza y el alusi吋n. A ella le encanta..."[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 0][f 3 1 1 0 0 26096]Supongo que tent吋 el destino...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 0]夷As胤 que fue un regalo para su[n]novia...? Tengo curiosidad por lo que era.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Dijo que era la encarnaci吋n de la[n]belleza. 夷Quiz茨 sea una joya?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6030][f 6 1 2 0 0 6]斡Qu姻 rom茨ntico![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 11 10 0 1][f 3 1 1 0 0 0]Las chicas est茨n emocionadas por esto...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 9 10 0 1][f 3 1 1 0 0 9062][f 6 1 2 0 0 1]Ooh! 斡Esto es![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Eh? 夷De qu姻 est茨s hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 9029][f 6 1 2 0 0 6]Quien encuentre el tesoro primero ser茨[n]coronado la mascota n雨mero uno![n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]夷Una mascota n雨mero uno?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Por qu姻?[f 2 7 1 64 0 32][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9012]El deber de una mascota es hacer feliz[n]a las damas y proporcionar consuelo[n]cuando lo necesiten...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]Naturalmente, si encontrar el tesoro[n]hace feliz a todos, entonces es justo que[n]el que lo encuentra consigue el t胤tulo![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 6 0 0][f 3 1 1 0 0 17004]Woof...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 6][f 3 1 1 0 0 0]Koromaru-san dice que no tiene idea de[n]lo que est茨s hablando.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 6 0 0][f 3 1 1 0 0 23092][f 6 1 2 0 0 9]Lo dijiste. A nadie le importa tu tonto[n]concurso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 1 0][f 3 1 1 0 0 9016][f 6 1 2 0 0 4]夷Oho...? Bueno, si no hay competencia,[n]entonces supongo que gan姻 por defecto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 8 0 0][f 3 1 1 0 0 0]Y luego me pongo bonita Ann-chan todo[n]para m胤 mismo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23064][f 6 1 2 0 0 6]斡Arrrgh! 夷D吋nde te vas?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 9135][f 6 1 2 0 0 6]斡Si no te gusta, intenta quitarme el t胤tulo![n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 5 0 0][f 3 1 1 0 0 23099][f 6 1 2 0 0 6]Maldici吋n... 斡Bien, lo har姻! Pero vamos[n]a tener una cosa clara...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡No me importa tu est雨pido t胤tulo! S吋lo[n]estoy haciendo esto para hacer feliz a Lady Ann![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 0 0 1][f 3 1 1 0 0 10003][f 6 1 2 0 0 4]Se est茨 calentando bastante all胤. 夷Est茨n bien?[n][f 1 3 65535][f 1 1][e]

[sel SEL_024 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]Est茨n bien.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]En realidad es conveniente.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Morgana va a ganar.[f 2 7 1 64 0 32][e]

[msg MSG_025 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 6][f 3 1 1 0 0 26114]Bueno, es una b雨squeda de tesoros. Es[n]bueno que todos est姻n motivados.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23015][f 6 1 30 0 0 0]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Cierto. 斡No hay forma de perder a un[n]oso pervertido![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 17 1 0 3][f 4 6 71 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Y t雨, Koro-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]斡斡Arf! Arf, 斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 6][f 3 1 1 0 0 0]"El concurso es de poco inter姻s para[n]m胤, pero con gusto ayudar姻 a buscar el tesoro..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]... As胤 dice Koromaru-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9068][f 6 1 2 0 0 6]斡Entonces eso lo resuelve! 斡Que empiece[n]el primer Mascot Match-up![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 1][f 3 1 1 0 0 9107][f 6 1 2 0 0 6]斡Que los hombres m茨s valientes, vengan![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 6][f 3 1 1 0 0 23108][f 6 1 2 0 0 6]斡S胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 0][f 3 1 1 0 0 17001][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

