[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 100 3][f 3 1 1 0 0 6509][f 3 1 6 0 0 500][f 6 1 2 0 0 3]Hmm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 pasa?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 7 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Parece que el camino se divide por delante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Un camino contin雨a hacia el este y hace[n]un gran bucle hacia el norte...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 100 6][f 3 1 1 0 0 14503][f 3 1 6 0 0 500]Y el otro camino conduce hacia el norte[n]y hace un bucle m茨s peque隠o.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Basado en nuestra posici吋n, ese ser胤a[n]el m茨s corto de los dos caminos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9016][f 6 1 2 0 0 6]斡M茨s corto es! 斡Todos s胤ganme![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 12 1 0][f 3 1 1 0 0 23082]Espera. El camino m茨s corto no es[n]siempre la mejor opci吋n.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 0][f 3 1 1 0 0 0]Si la experiencia me ha ense隠ado algo,[n]es que el camino f茨cil tiende a ser una trampa...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 9090]Conferencia, conferencia,[n]conferencia... Si esto fuera un concurso de quejas,[n]ganar胤as las manos abajo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 23034][f 6 1 2 0 0 2]夷Qui姻n se queja?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Bueno, creo que t雨 tambi姻n podr胤as[n]hacer un caso. 夷Qu姻 camino crees que[n]deber胤amos tomar, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_009 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]El camino m茨s corto.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]El camino m茨s largo.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Necesitamos m茨s informaci吋n.[f 2 7 1 20 0 32][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9029][f 6 1 2 0 0 6]夷Ves? 夷Qu姻 te dije?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23029][f 6 1 2 0 0 6]斡Sab胤a que lo entender胤as, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 22013]S胤, ser胤a agradable si conoci姻ramos un[n]poco m茨s sobre lo que nos espera por cada camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 17 12 0 1][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]斡Barco, corteza![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Hm? 夷Qu姻 pasa, Koromaru?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 4][f 3 1 1 0 0 0]Parece estar diciendo que puede oler[n]algo por cada camino.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 4019]夷En serio? No huelo nada.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Y estoy bastante seguro de poder[n]recoger el olor de la carne desde cualquier[n]parte dentro de una milla y media de este lugar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 3 6 0 1][f 3 1 1 0 0 3094][f 6 1 2 0 0 9]Ah胤 va el monstruo de la carne... Como[n]si fuera algo de lo que estar orgulloso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 0]Koromaru tiene un olor mucho mejor que[n]nosotros, as胤 que podr胤a estar en algo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 6][f 3 1 1 0 0 26517][f 3 1 6 0 0 500]No hay forma de saberlo desde aqu胤.[n]Tendremos que acercarnos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tendr茨s tanta informaci吋n como puedas[n]antes de tomar una decisi吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 1][f 3 1 1 0 0 9067]斡Yo digo que revisemos el camino m茨s[n]corto primero![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Vamos![n][f 1 3 65535][f 1 1][e]

