[msg MSG_000 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 1 1 0 4][f 4 6 2 6 0 1][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2104]No parece que haya[n]mucho por aqu胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]S胤, tampoco aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 0][f 3 1 1 0 0 27009]Disculpe, pero me preguntaba...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 12 0 0][f 3 1 1 0 0 0]夷Son ustedes dos muy grandes comedores?[n]Nunca habr胤a adivinado...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 10 1 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]S胤, no lo s姻. Nunca he pensado en m胤[n]mismo como uno.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Whoa, whoa, man. Cualquiera que pueda[n]terminar el Mega Beef Bowl de Aiya es sin[n]duda alguna clase de monstruo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esa cosa est茨 cargada con cinco veces[n]la carne, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 5017]The only ones who can finish it are[n][f 6 1 13 0 0 0]-kun, or maybe Chie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Ahora que era una batalla...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2046]Huh. Suena impresionante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]斡Mira qui姻n habla! Comes como un caballo, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Fideos extra en tu ramen, r茨pido[n]comiendo takoyaki... Creo que tienes una[n]reputaci吋n en el centro comercial Paulownia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15030]Su ingesta supera la capacidad estimada[n]de su cuerpo, pero sus vitales y[n]expresi吋n no indican dificultad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 21 0 0 1][f 3 1 1 0 0 0]Esos dos son realmente incre胤bles... No[n]me extra隠a que la tripulaci吋n azul est姻[n]sobre ellos.[n][f 1 3 65535][f 1 1][e]

[sel SEL_012 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Son inmejorables.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Estoy en su nivel.[f 2 7 1 20 2 32][e]

[msg MSG_013 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 1 0][f 3 1 1 0 0 21018][f 6 1 2 0 0 4]夷Eh? Pero realmente ganaste el Big Bang[n]Challenge, 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 1][f 3 1 1 0 0 3066][f 6 1 2 0 0 6]斡Espera, t雨 tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Ahora que lo pienso, t雨 ganaste el Big[n]Bang Challenge...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 0]Dir胤a que se necesita un poco de coraje[n]para terminar eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 0][f 3 1 1 0 0 7048]Huh. 夷Entonces tu l胤der es igual?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Supongo que si quieres ser el jefe,[n]夷tienes que comer toneladas de comida?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Vamos, de ninguna manera... Comer es lo[n]grande que es tu est吋mago, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[sel SEL_019 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]Se trata de agallas.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Es sobre el conocimiento.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Se trata de competencia.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Se trata de bondad.[f 2 7 1 20 0 32][e]

[msg MSG_020 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 1][f 4 6 1 0 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 1064]Correcto. Para comer[n]bien, necesitas entender tus l胤mites,[n]conocimiento para controlar tu ritmo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El coraje para enfrentar una marea[n]incansable de comida, y la diligencia para[n]perseverar contra un desaf胤o colosal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 0]Esas son precisamente las habilidades[n]necesarias para ser un l胤der.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 1][f 3 1 1 0 0 3092][f 6 1 2 0 0 10]Vale. Lo siento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 0][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]No te preocupes. Busquemos las partes[n]que necesitamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 1][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 2066]S胤. Sigamos movi姻ndonos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 2 1 1][f 3 1 1 0 0 13047]夷As胤 que un apetito terrible es la[n]clave de la verdadera direcci吋n? Fascinante...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No s姻 si quieres usar a estos tipos[n]como referencia para eso...[n][f 1 3 65535][f 1 1][e]

