[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 74 0 2 1][f 3 1 1 0 0 54115]Bien hecho.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esta proyecci吋n se neg吋 a permanecer como[n]una caza de tesoros fascinante.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 100 1][f 3 1 1 0 0 0]Cuando el robot se despert吋, fue como si mis[n]sentimientos fueran, 夷c吋mo deber胤a[n]ponerlo, "hit by a truck"? Romp胤 en l茨grimas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 1][f 3 1 1 0 0 0]Tienes mi m茨s profunda gratitud por haberme[n]llevado a trav姻s de una historia tan[n]conmovedora.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54139]Por favor acepte esto como su recompensa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 19 1 0 3][f 4 6 17 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 4][f 3 1 1 0 0 0]Koromaru says he enjoyed[n]spending time with you,[n][f 6 1 27 0 0 0].[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 0][f 3 1 1 0 0 16115]Eso me recuerda, Aigis... Dijiste que[n]Koromaru y t雨 sent胤an algo en [f 6 1 27 0 0 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Qu姻 fue exactamente?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Arf...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 6 0 0][f 3 1 1 0 0 15026]Lo siento. Ninguno de nosotros pudo responder[n]con claridad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 0]Ahaha, raro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19079][f 6 1 2 0 0 6]Bueno, no tiene sentido preocuparse por eso,[n]夷verdad? Quiero decir, el hecho de que[n]todos estamos aqu胤 en primer lugar es[n]raro tambi姻n![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Me alegra estar aqu胤 con todos. 夷Est茨 bien?[n]夷O es raro?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 0][f 3 1 1 0 0 0][f 6 1 27 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17002][f 6 1 2 0 0 6]斡Arf, Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 0]Koromaru dice, tambi姻n, que es mejor[n]vivir en el presente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Debo estar de acuerdo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 4][f 3 1 1 0 0 16069][f 6 1 2 0 0 6]*chuckle* Tienes raz吋n. 斡Creo que las cosas[n]est茨n bien como est茨n ahora![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todav胤a tenemos una manera de ir, pero lo[n]superaremos si trabajamos juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 0][f 3 1 1 0 0 17014][f 6 1 2 0 0 6]斡Awooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 3 0 0][f 3 1 1 0 0 0]Koromaru tambi姻n parece motivado. Por supuesto,[n]yo tampoco planeo sentarme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19031]*giggle* 斡Todos estamos contando con ustedes[n]dos! 斡Hag茨moslo, equipo![n][f 1 3 65535][f 1 1][e]

