[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 1][f 3 1 1 0 0 11033]Aqu胤 vamos. 夷Todos listos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 3][f 3 1 1 0 0 0]Tu voz est茨 rompiendo mucho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 6][f 3 1 1 0 0 0]Ahora que lo miro mejor, esa cosa es[n]enorme...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 1][f 3 1 1 0 0 9040]斡S胤! 夷C吋mo voy a impresionar a las damas si[n]esa gran bestia saca un bocado de este[n]hermoso mandio de mi...?[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]Estaremos bien.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]No tengas miedo.[f 2 7 1 20 0 32][e]

[msg MSG_005 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 1][f 3 1 1 0 0 16067]Cierto. S吋lo perdemos si renunciamos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 6][f 3 1 1 0 0 0]No est茨 mal, Ken. Tienes raz吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 8 0 0][f 3 1 1 0 0 0]Heheh... Es algo que escuch姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 4][f 3 1 1 0 0 26561][f 6 1 2 0 0 1][f 3 1 6 0 0 500]斡Es de Featherman! "斡Los h姻roes nunca se[n]retiran, suplican o se rinden!"[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Adelante, Joker! 斡Es hora de derrotar al[n]Tyranniqueen![n][f 1 3 65535][f 1 1][e]

