[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 26628][f 3 1 6 0 0 500][f 6 1 2 0 0 1]斡Has derrotado al poderoso Tyranniqueen![n]斡Buen trabajo, guerreros![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Heh! 斡Toma eso, cabrón! 斡No quiero ver tu[n]cara fea aqu胤 nunca m茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 1][f 3 1 1 0 0 16081]No puedes decirlo as胤, Kanji-san. Los h姻roes[n]no maldicen as胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 16 12 0 1]Trate de tener una multa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 3][f 3 1 1 0 0 7012][f 6 1 2 0 0 9]夷S胤? Muy bien entonces...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 7 2 0 0]斡S胤! 夷Te gusta eso? 斡Somos los Rangers F姻nix![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 1][f 3 1 1 0 0 16029][f 6 1 2 0 0 7]斡S胤, eso es! 斡Bien, mi turno![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 16 4 0 1]斡Los Villanos no tienen ninguna oportunidad[n]mientras los Phoenix Rangers est姻n cerca![n]斡Featherman para siempre![n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Bien.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Eso fue genial.[f 2 7 1 20 2 32][e]

[msg MSG_006 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16024][f 6 1 2 0 0 7]斡Gracias! Lo hicimos trabajando juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 8 0 0][f 3 1 1 0 0 16031]Heheh, bastante heroico, 夷verdad? Este es un[n]sueño hecho realidad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 4][f 3 1 1 0 0 0]El gran tirano fue vencido, y por lo tanto,[n]la paz fue restaurada en la Tierra de[n]Junessic.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 4 6 26 10 100 4]斡La próxima vez en Phoenix Ranger Featherman,[n]los h姻roes vuelven a la base![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 0]No estoy seguro de lo que est茨 pasando, pero[n]parece que hemos terminado aqu胤.[n]Volvamos.[n][f 1 3 65535][f 1 1][e]

