[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 2 100 1][f 3 1 1 0 0 54016]Las cosas resultaron bastante diferentes de[n]lo que hab胤a imaginado... Sin embargo,[n]veo que has cumplido tu objetivo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]Debo decir, sin embargo... Tengo un inter姻s[n]leve en que esta chica hable yo mismo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Alg雨n d胤a, me gustar胤a acoger a una chica[n]hablar entre los residentes de la Sala[n]Velvet.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Cuando llegue ese momento, Theo ser茨 incluido[n]como Theoko... o tal vez Theobeth.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 0][f 3 1 1 0 0 27033][f 6 1 2 0 0 4]Ahaha... 夷Teodoro terminar茨 como Teddie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Nuh-uh-uh. No puedes imitar tan f茨cilmente[n]esa belleza.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, 夷por qu姻 exactamente quieres unirte[n]a la charla de chicas tanto, Teddie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 0 0 0][f 3 1 1 0 0 9012]Bueno... Todo el mundo siempre parece que se[n]est茨n divirtiendo tanto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pens姻, si me uniera, ser胤a capaz de aprender[n]m茨s sobre ustedes. Y no sólo eso...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 73 12 0 0][f 3 1 1 0 0 0]Pero pens姻 que podr胤amos ser mejores amigos[n]tambi姻n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 0]Teddie...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 0][f 3 1 1 0 0 0]Deber胤as haberlo dicho.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 0][f 3 1 1 0 0 27069][f 6 1 2 0 0 4]S胤. Si ese es el caso, entonces no tiene que[n]ser sólo nosotras chicas. Todos podr胤amos[n]charlar juntos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷En serio? 夷Me vas a dejar unir?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Puedo entrar en el para胤so de tu chica[n]secreta y hablar de esto y eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0]Claro que puedes. Pero si tienes alguna idea[n]divertida, te asar姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 73 10 0 0][f 3 1 1 0 0 9102][f 6 1 2 0 0 10]Eek... Pero entonces el para胤so se asar茨[n]conmigo...![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 73 12 0 0][f 3 1 1 0 0 0]斡No importa! Como miembro de la brigada de[n]belleza, voy a seguir d茨ndole todo lo que[n]tengo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 73 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Ai-chan, Rise-chan, Haru-chan! 斡Robamos los[n]corazones de todos juntos![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 0][f 3 1 1 0 0 27032][f 6 1 2 0 0 6]斡S胤, vamos a hacerlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]斡Lo tienes! 斡No pienses que voy a dejar que[n]me golpees en lo que respecta a la[n]dulzura![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 3 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Seguir姻 tu ejemplo y perforar姻 el corazón de[n]todos, Teddie![n][f 1 3 65535][f 1 1][e]

