[msg MSG_000 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 71 1 0 3][f 4 6 6 2 0 1][f 3 1 1 0 0 6003][f 6 1 2 0 0 7]... As胤 que esa bebida enzim茨tica es[n]muy popular en la industria. 斡Dicen que[n]hace que tu piel est姻 suave![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 0][f 3 1 1 0 0 0]Vaya. Me preocupo por mi piel todo el tiempo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 0 0][f 3 1 1 0 0 0]Tambi姻n he estado buscando ayunar.[n]夷D吋nde vas un per胤odo de tiempo sin comer nada?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Escuch姻 que muchos modelos y actrices[n]lo hacen en el extranjero, as胤 que me[n]gustar胤a probarlo cuando sea un poco mayor![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 6 0 0][f 3 1 1 0 0 4066][f 6 1 2 0 0 9]夷F-Fasting? S吋lo pensar en ello me hace[n]sentir... Nunca podr胤a hacer eso...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si es piel suave que quieres, siempre[n]puedes usar los manantiales calientes en[n]la posada de mi familia. Eso funciona muy bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 0]Tienes una piel muy hermosa, Yukiko-senpai.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ojal茨 mi familia tuviera una posada de[n]primavera. Podr胤a desintoxicarme todos los d胤as.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 4][f 3 1 1 0 0 15002]Tengo una pregunta: 夷Los robots tambi姻n[n]se benefician de los efectos de las[n]aguas termales?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]No creo que sea una buena idea...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 6 0 0][f 3 1 1 0 0 0]Ya veo. Eso es desafortunado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 4][f 3 1 1 0 0 9002][f 6 1 2 0 0 4]斡Hola, se隠oritas! 夷De qu姻 estamos hablando?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 8 1 1][f 3 1 1 0 0 0]夷Eh? 斡No me digas! Es una charla de[n]chicas... S吋lo bromeaba.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 6 1 0 0][f 4 6 9 10 0 0][f 3 1 1 0 0 9058][f 6 1 2 0 0 6]夷Hablar con chicas? 斡Escuch姻 sobre esto de Yosuke![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Dijo que es un refugio secreto donde[n]las chicas comparten sus pensamientos[n]sobre el amor, la infatuaci吋n y el romance![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 0][f 3 1 1 0 0 0]Eso es b茨sicamente lo mismo. 夷Qu姻[n]demonios te ha dicho Yosuke?[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Quiero hablar como una chica! 斡D姻jame entrar![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 1 0][f 3 1 1 0 0 5018][f 6 1 2 0 0 4]夷Eh? 夷No eres un macho alfa, Teddie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]夷Est茨s diciendo que soy un animal?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 0]Bueno, definitivamente no eres una[n]chica, 夷verdad? Siempre te llamas "chico[n]solitario" o lo que sea.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 5 1 0][f 3 1 1 0 0 9040][f 6 1 2 0 0 3]斡Erk! As胤 es...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Pero no soy tan bonita como una chica?[n]Eso deber胤a ser suficiente... 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 8 1 1][f 3 1 1 0 0 0]斡Eso no es lo mismo! S吋lo las chicas[n]pueden hablar con chicas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, supongo que puedes unirte esta[n]vez. Est茨bamos hablando de belleza y[n]cuidado de la piel.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 1]斡Eso no es hablar de chicas! 斡Quiero[n]hablar con GIRL![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 6 1 0 0][f 4 6 71 6 0 0][f 3 1 1 0 0 27058][f 6 1 2 0 0 9]夷Qu姻? Pero...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Entrar姻 en este reino secreto de la[n]dama, aunque me mate![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Entonces, 夷qu姻 tal esto? Si puedo ser[n]m茨s bonita que el resto de ustedes, puedo[n]unirme a ustedes para una charla de chicas REAL.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 27032][f 6 1 2 0 0 4]W-Wow, est茨s determinado. 夷Quieres unirte a eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 0 0][f 3 1 1 0 0 0]Tambi姻n me interesa esta charla de[n]chicas. Voy a registrar datos para futuras referencias.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 8 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Como miembro del mundo del 胤dolo, no[n]voy a dejar que me muestres tan f茨cilmente.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Muy bien, Teddie, est茨s en. 斡Veamos lo[n]bonito que puedes ser![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 9107][f 6 1 2 0 0 6]Rrrrraaahh, desaf胤o aceptado! 斡Te[n]mostrar姻 mi poder femenino![n][f 1 3 65535][f 1 1][e]

[msg MSG_026]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una nueva proyecci吋n especial: "El[n]Secreto a la Belleza" se ha a隠adido a la taquilla.[n][f 1 3 65535][f 1 1][e]

