[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 1][f 3 1 1 0 0 26549][f 3 1 6 0 0 500][f 6 1 2 0 0 6]斡Mierda! 斡No bromeaba con esos Treasure[n]Spots![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 0]斡Mee-YOW! 斡Mira todo el tesoro![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Vamos, Joker! 斡Puedo o胤rlo llamando mi[n]nombre![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 1][f 3 1 1 0 0 27031]*giggle* C茨lmate, Mona-chan.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 27 0 0 1][f 3 1 1 0 0 0]No podemos cargar. Echemos un vistazo al mapa[n]y mu姻vanse con cuidado.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 4][f 3 1 1 0 0 0]Como dijo Zabby, tambi姻n hay m茨s puntos warp[n]por aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 1][f 3 1 1 0 0 0]Mencionó que los Treasure Spots estaban m茨s[n]all茨 de los nuevos warps... si recuerdo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 0][f 3 1 1 0 0 0]Entonces supongo que tendremos que encontrar[n]nuevas formas alrededor de los puntos[n]warp y las puertas posteriores.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 7 4 0 0][f 4 6 20 1 0 0]Estoy en ello.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Suena como un dolor.[f 2 7 1 20 4 32][e]

[msg MSG_006 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13127]En otras palabras, nuestro enfoque habitual.[n]No muy exigente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13032]*chuckle* 夷Renunciar antes de empezar? Al[n]menos intentarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 6 1 4][f 3 1 1 0 0 0]Hab胤a tres lugares, 夷correcto? Entonces[n]encontremos el primero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 100 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Muy bien! 斡Entonces vamos a buscar esos[n]Treasure Spots! Mantengan los ojos fuera,[n]chicos![n][f 1 3 65535][f 1 1][e]

