[msg MSG_000 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 11 2 0 1][f 3 1 1 0 0 11043][f 6 1 2 0 0 6]斡La segunda baja![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Y? S姻 que solo estoy reuniendo cosas, pero[n]夷no me parece una estrella?[n][f 1 3 65535][f 1 1][e]

[sel SEL_001 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Y "el mejor actor" va a...[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]En realidad no.[f 2 7 1 20 6 32][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11030][f 6 1 2 0 0 7]斡Hahah! Mira, hay un tipo que sabe la calidad[n]cuando lo ve. Buen trabajo, Junpei.[n]Gracias. 斡Junpei![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0]Y se quejaba mucho antes... Seguro que[n]rebot吋.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 0][f 3 1 1 0 0 11020][f 6 1 2 0 0 4]夷Oh? 夷Ahora me estoy volviendo demasiado[n]predecible? 夷Quieres que pruebe un poco de[n]ropa interior?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 0][f 3 1 1 0 0 0]No, no creo que necesites. Ese tipo de sonidos[n]como tu vida ya.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 2 0 0][f 3 1 1 0 0 0]*Grecha* 斡Me alegro de que te est姻s divirtiendo[n]ahora! S吋lo hay un lugar m茨s para[n]buscar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 1][f 3 1 1 0 0 0]斡Heh! Tenemos a Joker dirigiendo el camino.[n]Esto deber胤a ser f茨cil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 13080]Sin embargo, aseg雨rate de mantenerte concentrado.[n]Sea cual sea nuestra ventaja,[n]todav胤a hay m茨s complicaciones en su lugar.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Por el momento, tendremos que lanzar una red[n]amplia para encontrar el premio final.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 1][f 3 1 1 0 0 0]Aha... Est茨s muy mareado, Mitsuru. Estaba a[n]punto de decir lo mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 21 0 3 4][f 3 1 1 0 0 21091]Heh. Dice el tipo que estaba babeando sobre[n]su precioso tesoro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Bueno, los ladrones no podemos perdernos en[n]un lugar como este. Cuento contigo,[n]Joker![n][f 1 3 65535][f 1 1][e]

