[msg MSG_000 [Flor Shrill]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 6 1 9 0 0 1][f 3 1 1 0 0 0]Oh yo, oh, miren a todos ustedes.[n]Buscas la "cosa negra", 夷no?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Flor Sonriente]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]A lo largo de una senda oscura,[n]bloqueada, una casa se encuentra a la sombra en[n]la ira. Vio a trav姻s de una puerta,[n]infundida con el mal hace mucho tiempo ignorada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Shrill Flower]]
[f 0 5 65278][f 2 1][f 6 1 9 0 0 1][f 3 1 1 0 0 0]... Oh, pero debes cuidarte, gran[n]cuidado. Porque est茨n esperando en esa casa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 1][f 3 1 1 0 0 3016]Acabo de pensar en algo. Cuando dicen[n]"carreo bloqueado", 夷significan un[n]callej吋n sin salida?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una casa situada en un callej吋n sin[n]salida... dulce, lo descubr胤! Y est茨 al[n]otro lado de una puerta...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oye, hab胤a una puerta justo donde[n]bajamos, 夷verdad? 夷No era al oeste de aqu胤?[n]斡Estoy en un rollo![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 4][f 3 1 1 0 0 11122][f 6 1 2 0 0 6]Amigo, lo eres! 斡Vamos por all茨![n][f 1 3 65535][f 1 1][e]

