[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 2 100 1][f 3 1 1 0 0 54030]Ambling alrededor de un mundo de cuento[n]de hadas cosechando fruta...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Dios, fue como un sue隠o en la pantalla.[n]Me sent胤 tan relajada que estaba[n]durmiendo... 夷Dije eso en voz alta?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Eso fue una exageraci吋n juguetona. Lo[n]que quer胤a decir era que disfrut姻 de una[n]experiencia tan calmante y agradable.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 3][f 3 1 1 0 0 3108]Estaba durmiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 6 0 6][f 3 1 1 0 0 0]Definitivamente.[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Fue una misi吋n divertida.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Fue un arrastre.[f 2 7 1 64 6 32][e]

[msg MSG_004 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19069]Quiero decir, todo[n]lo que hicimos fue caminar alrededor,[n]pero lo pas姻 muy bien todo lo mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 3][f 3 1 1 0 0 0]Y proporcion吋 tiempo de calidad para[n]hablar con compa隠eros, algo importante que[n]se olvida en un grupo de este tama隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 6][f 1 5][f 6 1 28 0 0 0]　[n][f 3 1 1 0 0 19031]*giggle* Fue un[n]largo paseo donde no pas吋 mucho.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero tenemos que relajarnos un poco. Y[n]tengo que hablar con todos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Entonces supongo que no fue[n]muy malo. Parece que la moral de todos[n]subi吋, al menos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 3][f 3 1 1 0 0 0]As胤 que gracias, Elizabeth.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54031]*chuckle* ...No hay necesidad de agradecerme.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mi propia recompensa fue el momento de[n]descansar, aumentar la moral, y por supuesto...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 8 100 1][f 3 1 1 0 0 0]斡Un mont吋n de fruta reci姻n reunida![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 0]Voy a comer todo esto justo aqu胤, y[n]entonces la b雨squeda ser茨 completa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 6 0 6][f 1 5][f 6 1 17 0 0 0]　[n][f 3 1 1 0 0 0]Esa es Elizabeth, tan[n]astuto como siempre...[n][f 1 3 65535][f 1 1][e]

