[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54115]Bien hecho, todos. Trajiste la[n]proyecci吋n a un final agradable. Muy los auteurs[n]del cine, todos ustedes lo son.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aqu胤 est茨 tu recompensa.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 2 0 1][f 3 1 1 0 0 0]Me gustar胤a agradecerle personalmente[n]tambi姻n. Fue amable de tu parte cumplir[n]con la petici吋n de Marie.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Marie? 夷No tienes algo que darles?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 6 0 4][f 3 1 1 0 0 0]Bueno... Hay esto...[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]夷Qu姻 pasa?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Nos est茨s dando algo?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 0 4][f 3 1 1 0 0 65047]斡N-N-N-Nada! 斡No es nada![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Definitivamente no es como si te[n]estuviera agradeciendo o algo as胤, por dejarme[n]entrar contigo en la pel胤cula.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 0 4][f 3 1 1 0 0 65047]夷Eh? Bueno... ya sabes...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Quiero decir, no es como si me[n]estuviera sintiendo feliz que me dejaras[n]acompa隠ar dentro de la pel胤cula o algo as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 8 0 4][f 3 1 1 0 0 0]El punto es... Gracias. Quiero que tengas esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 3][f 3 1 1 0 0 0]Todav胤a siguiendo el cl茨sico gui吋n de[n]Tsundere a la carta... Un pr胤sculo[n]exterior esconde un interior suave y rom茨ntico...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 1 1][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0 1109] Por cierto, Marie,[n]夷Terminaste tu poema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 0 0 4][f 3 1 1 0 0 0]S胤, creo que est茨 casi hecho...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 10 0 4][f 3 1 1 0 0 0]斡No! 斡No es un poema! Es m茨s como...[n]una expresi吋n de patos...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 3][f 3 1 1 0 0 28033]夷No es b茨sicamente un poema?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Marie]]
[f 0 5 65278][f 2 1][f 4 6 85 4 0 4][f 3 1 1 0 0 0]斡No, no es as胤! 斡Tienes miedo de que seas el peor![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 1 2 0 1][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0]Sin embargo, nos[n]encantar胤a ver el producto terminado en alg雨n momento.[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]S胤, esperando.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]夷Aunque la tortura?[f 2 7 1 64 0 32][e]

[msg MSG_014 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 14 0 0 0]斡Por supuesto![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 1][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0 1031]... Tienes raz吋n.[n][f 1 3 65535][f 1 1][e]

