[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54035]斡Un carrito fuera del control se[n]preocupa hacia los trabajadores condenados![n]Pero en el 雨ltimo momento, [f 6 1 30 0 0] decide su destino![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]... Tal vez s吋lo fueron dos preguntas,[n]pero pueden haber mostrado una gran[n]comprensi吋n de sus corazones.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Mientras esto era un poco de salida de[n]las proyecciones especiales habituales,[n]disfrut姻 sin embargo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 0 3][f 3 1 1 0 0 26013]夷Pero qui姻n hizo esas se隠ales en primer[n]lugar? 夷Y qu姻 hay de la espeluznante[n]mujer que anuncia?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11113]En realidad, ahora que lo pienso, esa[n]voz sexy era un poco familiar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]夷Te suenan las campanas?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Ni idea.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Elizabeth?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Era familiar...[f 2 7 1 64 0 32][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 8 0 1][f 3 1 1 0 0 11030]斡Pero mi Babe Radar se est茨 volviendo salvaje![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Alguien muy sexy, muy maduro, con ese[n]tipo de aura sofisticada para ella...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54067]Desafortunadamente, no fui yo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es m茨s probable que me encuentren en mi[n]asiento durante las proyecciones,[n]devorando palomitas y perros calientes con[n]abandono salvaje.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Me alegra que haya[n]disfrutado del espect茨culo, como siempre.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11013]No, tengo la sensaci吋n de que es[n]alguien mayor y m茨s maduro que Elizabeth...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11050]Lo s姻, 夷verdad? Y sent胤 que era alguien[n]s雨per reciente, como justo despu姻s de[n]llegar a este Cine.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 8 0 1][f 3 1 1 0 0 0]Alguien muy sexy, muy maduro, con ese[n]tipo de aura sofisticada para ella...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Quiz茨 nunca sepamos la verdad. Pero en[n]cuanto a mi especulaci吋n sobre los[n]motivos del orquestador...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Creo que ella estaba intrigada por ti,[n]y fue impulsada por un deseo de[n]comprender mejor a todos ustedes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 3][f 1 5][f 6 1 14 0 0 0]　[n][f 3 1 1 0 0 0]Bueno, s吋lo puedo esperar[n]que tenga lo que quer胤a fuera de ella.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54031]夷Qui姻n puede decir?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Espero que siga observando tus haza隠as[n]en los juicios por venir.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54113]En cualquier caso, fue un espect茨culo[n]muy entretenido. Por favor, contin雨e con[n]el buen trabajo.[n][f 1 3 65535][f 1 1][e]

