[msg MSG_000 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28075]Ya veo. 夷As胤 que sacaste la palanca, Joker?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El carrito perder茨 a los cinco trabajadores,[n]y en cambio matar茨 al trabajador soltero[n]en la otra pista...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 3][f 3 1 1 0 0 0]Sacrificando a uno para salvar a cinco, 夷eh?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Bueno, salva la mayor parte de las vidas.[n]Supongo que es una especie de "correcto"[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 0]斡H-Hang en un segundo![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 1][f 3 1 1 0 0 0]夷As胤 que ese inocente acaba de huir? Hombre,[n]no s姻 si salvar a esos tipos lo hace[n]bien...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 3][f 3 1 1 0 0 24068]Estoy de acuerdo. No puedes medir el valor[n]de la vida humana solo en n雨meros.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Supongo que eso hace que este problema sea[n]tan dif胤cil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 0]S胤. Queen lo resumi吋 mejor... No hay[n]respuesta objetivamente correcta.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todo lo que podemos hacer es tener en cuenta[n]todo lo que hemos considerado, y luego[n]avanzar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28075]Ya veo. 夷As胤 que elegiste no tirar de la[n]palanca, Joker?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]El carro continuar茨 en su camino, y golpear[n]a esas cinco personas... Pero la otra[n]persona ser茨 perdonada.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 3][f 3 1 1 0 0 0]夷Est茨 bien? Quiero decir, 夷no ser胤a mejor[n]salvar a cinco personas en vez de solo[n]una...?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 3][f 3 1 1 0 0 0]斡Arrgh, no lo entiendo! Tampoco podemos matar[n]a ese otro tipo![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 0]Si no hacemos un sacrificio, entonces no[n]podemos salvar a otro...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Una condici吋n de extraordinaria crueldad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 100 3][f 3 1 1 0 0 6509][f 3 1 6 0 0 500]No s姻 qu姻 har胤a si estuviera en esa[n]situaci吋n...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Bueno, como dije, no hay una respuesta que[n]sea objetivamente "correcta" aqu胤.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todo lo que podemos hacer es tener en cuenta[n]todo lo que hemos considerado, y luego[n]avanzar.[n][f 1 3 65535][f 1 1][e]

