[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 54002]Ahora, el objetivo de esta proyecci吋n especial...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Debes llegar al 茨rea designada en la[n]pel胤cula de Hikari. Un objetivo muy simple.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54023][f 6 1 2 0 0 4]...Oh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 3][f 3 1 1 0 0 18018]夷Qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 1][f 3 1 1 0 0 0]Bueno, hay una nota aqu胤 que dice[n]"puedes tomar cualquier camino"[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]夷Qu姻 significa eso?[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]夷Qu姻 pasa con la nota?[f 2 7 1 64 0 32][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54014]No puedo decir... No s姻 nada sobre la[n]proyecci吋n m茨s all茨 de lo documentado aqu胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 3][f 3 1 1 0 0 0]夷Eso significa que hay m雨ltiples[n]caminos a este objetivo...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 0]Tal vez nos env胤an al infierno o al[n]purgatorio, y depende de nosotros escoger.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 6][f 3 1 1 0 0 3101]Amigo, esto es bastante raro sin estas[n]ideas locas...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 12 0 3][f 3 1 1 0 0 0]Bueno, no puedes estar aqu胤 pensando en[n]ello. Ser茨 mejor que echemos un vistazo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 1][f 3 1 1 0 0 17001]斡Arf![n][f 1 3 65535][f 1 1][e]

