[sel Y_FCLSHOP_YESNO top]
Normal: Yes
Normal: No

[sel Y_FCLSHOP_YESNO_BUY_NUM top]
Buy
Cancel

[sel Y_FCLSHOP_YESNO_BUY top]
Buy
Cancel

[sel Y_FCLSHOP_YESNO_BUY_EQUI top]
Equip
Not now

[sel Y_FCLSHOP_YESNO_BUY_TRAD top]
Buy out
Cancel

[sel Y_FCLSHOP_YESNO_SELL_ALL top]
Sell
Cancel

[sel Y_FCLSHOP_YESNO_SELL top]
Sell
Cancel

[sel Y_FCLSHOP_YESNO_SELL_NUM top]
個数選択売却確認はい★未使用
個数選択売却確認いいえ★未使用

[sel Y_FCLSHOP_YESNO_COSTODY_ top]
Store
Cancel

[sel Y_FCLSHOP_YESNO_COSTODY__2 top]
Store
Cancel

[sel Y_FCLSHOP_YESNO_COSTODY__3 top]
Withdraw
Cancel

[sel Y_FCLSHOP_YESNO_COSTODY__4 top]
Withdraw
Cancel

[sel Y_FCLSHOP_YESNO_COSTODY__5 top]
Withdraw
Cancel

[sel Y_FCLSHOP_YESNO_UNKNOWN_ top]
全て鑑定するはい★未使用
全て鑑定するいいえ★未使用

[msg Y_FCLSHOP_BUY_MSG [Theodore]]
is yen[f 0 1 0]. Will that be all right?

[msg Y_FCLSHOP_USE_BUY_MSG [Theodore]]
of those will be yen[f 0 1 0]. Will that do?

[msg Y_FCLSHOP_SELL_MSG [Theodore]]
You'd like to sell x[f 2 4 1]?

[msg Y_FCLSHOP_SELL_MULUTI_MS [Theodore]]
Selling [f 2 4 0] of those will[n]total to yen[f 0 1 0]. Will that do?

[msg Y_FCLSHOP_FAV_NG]
You cannot sell an item registered as a[n]favorite.

[msg Y_FCLSHOP_DLC_NG]
DLC items cannot be sold.

[msg Y_FCLSHOP_ADD_LIST [Theodore]]
was added to the merchandise!

[msg Y_FCLSHOP_EQUIP [Theodore]]
Would you like to equip the right away?

[msg Y_FCLSHOP_TRADE [Theodore]]
Would you like to sell the you had[n]equipped for yen[f 0 1 0]?

[msg Y_FCLSHOP_ALLSELL [Theodore]]
Selling all the materials you have will[n]total yen[f 0 1 0]. Will that do?

[msg Y_FCLSHOP_HELP []]
Not used

[msg WSHOP_ADDNEW]
Not used

[msg WSHOP_HELLO_MARGARET [Margaret]]
Not used

[msg WSHOP_HELLO_THEODORE [Theodore]]
Not used

[msg WSHOP_HELLO_RAIN [Theodore]]
Not used

[msg Y_FCLSHOP_ADD_MES [Theodore]]
Y_FCLSHOP_ADD_MES ★未使用！

[msg Y_FCLSHOP_ADD_MES_RARE [Theodore]]
Y_FCLSHOP_ADD_MES_RARE ★未使用！

[msg Y_FCLSHOP_ADD_MES2 []]
Y_FCLSHOP_ADD_MES2 ★未使用！

[msg Y_FCLSHOP_ADD_MES3 [Theodore]]
Y_FCLSHOP_ADD_MES3 ★未使用！

[msg Y_FCLSHOP_ADD_MES4 [Theodore]]
Y_FCLSHOP_ADD_MES4 ★未使用！

[msg Y_FCLSHOP_ADD_MES_MARGAR [Margaret]]
Y_FCLSHOP_ADD_MES_MARGARET ★未使用！

[msg Y_FCLSHOP_SELL_MES_NORMA [Theodore]]
My, what an interesting material![n]Already, I can envision the finished[n]work in my head!
Now, I'll be just a moment...

[msg Y_FCLSHOP_SELL_MES_NORMA_2 [Theodore]]
My my... I cannot wait to see what will[n]be born from this material.
Perhaps it's my imagination, but I[n]daresay even the popcorn machine is[n]trembling with anticipation!

[msg Y_FCLSHOP_SELL_MES_RARE1 [Theodore]]
An intriguing material indeed. I wonder,[n]what will result...?
Regardless, I shall try processing it.[n]Please wait a moment.

[msg Y_FCLSHOP_SELL_MES_RARE2 [Theodore]]
My... What a splendid shine...
It seems to be a high-quality[n]material... A rarity indeed! I cannot[n]wait to craft something with it!

[msg Y_FCLSHOP_SELL_MES_HIGH_ [Theodore]]
Ah, how amazing!
I, the humble Theodore, shall do my[n]utmost to fashion something worthy from[n]this!

[msg Y_FCLSHOP_ADD_MES_NORMAL [Theodore]]
Thank you for waiting. Please, make good[n]use of this.

[msg Y_FCLSHOP_ADD_MES_NORMAL_2 [Theodore]]
What do you think? I believe it has been[n]reborn into a splendid new form!

[msg Y_FCLSHOP_ADD_MES_RARE1 [Theodore]]
Phew... How's this?

[msg Y_FCLSHOP_ADD_MES_RARE2 [Theodore]]
Phew... Thank you for waiting.
I believe I have created something truly[n]worthy of such fine material...!

[msg Y_FCLSHOP_ADD_MES_HIGH_R [Theodore]]
What do you think of my handiwork? I[n]believe it has been reborn into a[n]splendid new shape!
Many things are, in their own ways,[n]diamonds in the rough. With a keen eye,[n]you can―
W-Wait! I wasn't finished!

[msg WSHOP_NO_MAKE [Theodore]]
Not used

[msg WSHOP_NO_MATERIAL [Theodore]]
Not used

[msg WSHOP_KEEP_MATERIAL [Theodore]]
Just a few more materials, and I believe[n]I can create something like this.

[msg WSHOP_EXIT_CONF]
★未使用！

[msg CSHOP_DEP_CONF [Theodore]]
Would you like me to store of your[n]belongings?

[msg CSHOP_DEP_CONF_OK [Theodore]]
Very well, I will store of your[n]belongings.

[msg CSHOP_PUL_CONF [Theodore]]
Would you like to take [f 2 4 0][n]of your stored belongings?

[msg CSHOP_PUL_CONF_OK [Theodore]]
Here are [f 2 4 0] of your[n]belongings. Please, take them.

[msg CSHOP_COMMON_NG_1 [Theodore]]
...Ah, I do apologize... It seems you[n]have a great many of these already. I[n]cannot store any more of them.

[msg CSHOP_COMMON_NG_2 [Theodore]]
I believe we are out of space. I do[n]apologize, but I cannot store any more[n]of your items than this.

[msg CSHOP_COMMON_NG_3 [Theodore]]
It seems your inventory is full. I do[n]apologize, but I cannot return a portion[n]of your items.

[msg WSHOP_MULUTI_ADD_ITEM]


[msg WSHOP_MULUTI_ADD_ITEM_LA]
Available now for purchase.

[msg WSHOP_EXP_NEW_ITEM_M [Nagi]]
★未使用！

[msg WSHOP_EXP_RARE_MATERIAL_ [Nagi]]
★未使用！

[msg WSHOP_EXP_EFFECT_M [Nagi]]
★未使用！

[msg WSHOP_EXP_KANTEI [Theodore]]
In your exploration efforts, I believe[n]you will acquire some once-mighty items[n]that have lost their power.
If you bring them to me, I can appraise[n]these items and reawaken their original[n]properties.
Such an appraisal will require a fee,[n]I'm afraid, but you may find it's very[n]much worth the price.
Please use this service as much as you[n]want, and together we shall reveal the[n]true worth of your finds.

[msg WSHOP_EXP_ITEM_MAX_T [Theodore]]
The maximum number of items you can[n]carry is 60.
and [f 4 4 3 0 1333] are extremely useful[n]items...
But if you take in too many, you may end[n]up having to discard what you acquire in[n]the labyrinth.
I believe it'd be best to only carry 10[n]to 20 items into the labyrinths.

[msg WSHOP_EXP_ITEM_MAX_M [Nagi]]
It seems the maximum number of items you[n]can carry is 60.
It's true that [f 4 4 3 0 1348] and are[n]extremely useful...
But if you carry too many, you may find[n]you have no room to pick up treasures[n]you find along the way.
Perhaps it'd be best to bring about 10[n]to 20 items when departing on your[n]journey?

[msg WSHOP_EXP_CLOAKROOM_T [Theodore]]
Have you been carrying any items or[n]valuable equipment that you find you're[n]not using?
I have prepared 99 spaces where you can[n]store your belongings at this shop.
For each space, you can store up to 99[n]of any one item.
Why not leave any belongings you don't[n]immediately need here?
There is no fee for this service, so use[n]it all you like.
However, there is one point of caution I[n]should note...
Multiple accessories cannot be stored in[n]the same space.
Please, keep that in mind.

[msg WSHOP_EXP_CLOAKROOM_M [Nagi]]
Are you carrying any items or valuable[n]equipment that you don't expect to use[n]for a while?
I have prepared 99 spaces where you can[n]store your belongings with me.
For each space, you will be able to[n]store up to 99 of a given item.
If you have any vital belongings not[n]immediately relevant to your travels,[n]why not leave them here?
This service is free of charge, so[n]please use it at your leisure.
However, there is one matter I'd like[n]you to be cautious about.
Multiple accessories cannot be stored in[n]the same space.
Please keep that in mind.

[msg WSHOP_MATERIAL_HELP_NONE]
No information.

[msg Y_FCLSHOP_BUY_MSG_Ex [Nagi]]
is yen[f 0 1 0]. Will that be all right?

[msg Y_FCLSHOP_USE_BUY_MSG_Ex [Nagi]]
of those will be yen[f 0 1 0]. Will that be all[n]right?

[msg Y_FCLSHOP_SELL_MSG_Ex [Nagi]]
You'd like to sell x[f 2 4 1]?

[msg Y_FCLSHOP_SELL_MULUTI_MS_2 [Nagi]]
Selling [f 2 4 0] of those will[n]total to yen[f 0 1 0]. Will that do?

[msg Y_FCLSHOP_ADD_LIST_Ex [Nagi]]
was added to the merchandise!

[msg Y_FCLSHOP_EQUIP_Ex [Nagi]]
Would you like to equip the at once?

[msg Y_FCLSHOP_TRADE_Ex [Nagi]]
Would you like to sell the you had[n]equipped for yen[f 0 1 0]?

[msg Y_FCLSHOP_ALLSELL_Ex [Nagi]]
Selling all the materials you have will[n]total yen[f 0 1 0]. Will that do?

[msg CSHOP_DEP_CONF_Ex [Nagi]]
Would you like to store [f 2 4 0][n]of your belongings?

[msg CSHOP_DEP_CONF_OK_Ex [Nagi]]
Very well, I will store [f 2 4 0][n]of your belongings.

[msg CSHOP_PUL_CONF_Ex [Nagi]]
Would you like to take [f 2 4 0][n]of your stored belongings?

[msg CSHOP_PUL_CONF_OK_Ex [Nagi]]
Here are [f 2 4 0] of your[n]belongings. Please take them.

[msg CSHOP_COMMON_NG_1_Ex [Nagi]]
Ah, I'm afraid my storage space is full.[n]I can't take any more from you...[n]Terribly sorry.

[msg CSHOP_COMMON_NG_2_Ex [Nagi]]
I'm afraid I'm already storing as many[n]of those as I can.

[msg CSHOP_COMMON_NG_3_Ex [Nagi]]
I cannot return this to you with your[n]inventory so full. Please come back[n]after you've made room in your bag.

[msg Y_FCLSHOP_HAVE_MAX_T_MSG [Theodore]]
Pardon me, but I believe your inventory[n]is full.

[msg Y_FCLSHOP_HAVE_MAX_M_MSG [Nagi]]
I'm sorry... It seems your inventory is[n]full.

[msg Y_FCLSHOP_SELL_RARE_MAT_ [Theodore]]
Thank you for selling that rare[n]material.

[msg Y_FCLSHOP_SELL_RARE_MAT__2 [Nagi]]
Ah, you've sold a rare material! I[n]appreciate it.

[msg CSHOP_COMMON_NG_4 [Theodore]]
I'm sorry, but our space is limited, and[n]I couldn't store a portion of the[n]belongings you chose...

[msg CSHOP_COMMON_NG_4_Ex [Nagi]]
I'm afraid some of your belongings[n]couldn't be stored since our space is[n]limited.

[msg CSHOP_COMMON_NG_5 [Theodore]]
It seems your inventory is full. I do[n]apologize, but I cannot return a portion[n]of your items.

[msg CSHOP_COMMON_NG_5_Ex [Nagi]]
I couldn't return some of your items[n]with your inventory full. Please come[n]back after you've freed up your bag.

[msg WSHOP_UNKNOWN_JUDGE_ONE_ [Theodore]]
Shall I appraise this?

[msg WSHOP_UNKNOWN_JUDGE_ALL_ [Theodore]]
★未使用！

[msg WSHOP_MULUTI_ADD_UNKNOWN]
Obtained [f 0 7 0 65535].

[msg WSHOP_UNKNOWN_JUDGE_RESU [Theodore]]
Not used

[msg WSHOP_UNKNOWN_JUDGE_RESU_2 [Theodore]]
Not used

[msg WSHOP_UNKNOWN_JUDGE_RESU_3 [Theodore]]
★未使用！

[msg WSHOP_TALK000 [だいだら．のオヤジ]]
…しっくりくるモンが欲しけりゃ、 素材もってこい。
言っとくが…ワシって、 ありきたりのモンは好かんっ！
うろたえるような珍品、 持ってきナ。
…そしたら、もっと伊達なもん、 作ってやってもいいゼ。
作るものによっちゃ、 素材の種類や数はそれぞれだ。
こっちに素材がある程度貯まったら、 ワシのひらめきで、アートにしてやる。
但し、何を作るかは、ワシの勝手だ。 なんたって、アートだからな。
絶賛、期待してるからな！

[msg WSHOP_TALK001 [だいだら．のオヤジ]]
…っらっしゃい！！ 今日は、どんな“アート”したいんだ？
…重くないやつ？ 制服の下に隠すだぁ？
…オメェ…意外に変な趣味してんナ。
…ま、好きならしかたねぇ。 色々試してきナ。

[msg WSHOP_TALK002 [だいだら．のオヤジ]]
旅館の一人娘が塞ぎ込んじまったとか、 …商店街中、コソコソとうるせぇこった。
まぁ…あの旅館は、娘の評判で もってるとこがあるからなぁ。
家出かもしれねぇってんだから、 親不孝が祟んなきゃ良いが…
何不自由ないお嬢さんの考えなんザ、 ワシにはわからんがね。

[msg WSHOP_TALK003 [だいだら．のオヤジ]]
オメェ…都会から来たのか？ あの荒んだ、悪意の街からねぇ…
ワシも、尻の青い頃は あっちにも詳しかったが…
ここは空気も水も、米も旨いし… …全部忘れたがな。

[msg WSHOP_TALK004 [だいだら．のオヤジ]]
…っらっしゃい！！ 活きの良いヤツ、持ってきたか？
むうっ？…完二だぁ？ あのヒヨっコが何かしたか？？
そいや、アイツ…お笑い系の 変なテレビ番組に出てただろ？
まさか…スカウトされて上京か！ …間違いねェ…だろ？

[msg WSHOP_TALK005 [だいだら．のオヤジ]]
そういや最近、巽屋の完二見ねぇな。
あの童子…悪ぶっとるようだが、 豪胆の極みにしか見えん…
突然、族と一戦交えるとかって、 自慢の盾、強奪してきおってな…
子供の喧嘩に使うなんざ。 “アート”に対する侮辱だぜ…

[msg WSHOP_TALK006 [だいだら．のオヤジ]]
完二のヤロウ、 ひょっこり帰ってきたらしいな。
理由を聞いても、答えねぇって… 親不孝なヤロウぅだぜ…
ま…尻の青い頃は、 言いたくない事もあらぁな。

[msg WSHOP_TALK007 [だいだら．のオヤジ]]
…らっしゃい！ オメェ…完二と仲良いらしいな。
あの暴れ馬を舎弟にしたって… スゲェじゃねぇか。
ぬっ？舎弟じゃねぇだ？ …照れんなよ。

[msg WSHOP_TALK008 [だいだら．のオヤジ]]
…ぁんだ？オメェ… なんかウキウキしてやがって。
林間学校？…まさか！ 着替えに持ってくんじゃネェだろうな！
ナ二って…ワシの“アート”だろっ！ ダッハハハハハハ！
あ？…違うのか。

[msg WSHOP_TALK009 [だいだら．のオヤジ]]
…オメェ、林間学校どうだったんだ？ …ゲンナリしてるな？
飯で死にかけた？ …なんだぁそりゃあ？
ま、今しか楽しめねぇこたぁ やっとくべきだぜ。

[msg WSHOP_TALK010 [だいだら．のオヤジ]]
最近、ジメジメして 精神統一に時間がかかりやがる…
湿気ってのは、“アート”達にとって天敵だ。
時々なぁ…こいつら全部 好き放題させてやりたいって思うんだ。
…ま、あぶねぇがな。

[msg WSHOP_TALK011 [だいだら．のオヤジ]]
マル久のりせちゃん、こっちに 帰って来たらしいな… …ワシ、見てないけど。
…なんでって、ずっとここに居るし。 割とシャイなのね、ワシって。
…ファンなのか、だと？ …なんで答えにゃならん。
…どうでもエエ！ “アート”に集中させんかいっ！

[msg WSHOP_TALK012 [だいだら．のオヤジ]]
マル久のりせちゃん、帰って来たらしいな…
実はワシと、四六さんとマル久さんは、 結構仲良くやってんだ。
りせちゃんは、ワシの孫みたいな もんなんだな…
マル久のばあさんにも、世話になってるし… 人情ってのは良いねぇ。

[msg WSHOP_TALK013 [だいだら．のオヤジ]]
オメェ…諸岡って教師知ってるか？ 殺されたらしいな…
昔、ここにも来たが、 ＰＴＡだの、精神衛生がどうのって…
犬っコロみてぇに、騒ぎやがって… 厄介なヤロウだったぜ…まったく。
精神衛生上どうのって… アイツの方が、どうかしてたぜ。

[msg WSHOP_TALK014 [だいだら．のオヤジ]]
…ぬっ。なんだか、最近… オメェから覇気を感じるな。
邪気じゃねぇが… 戦国武将みてぇな、なんかだ。
くだらねぇ喧嘩に、“アート”を 使ったら許さんからな！

[msg WSHOP_TALK015 [だいだら．のオヤジ]]
破顔一笑…か？ オメェ…やけに清清しいな。
心の汚泥…悪意を払いのけた 良い顔してやがる…
ワシの“アート”を理解してるのが、 オメェで嬉しいぜ…

[msg WSHOP_TALK016 [だいだら．のオヤジ]]
祭りだなんだって浮かれてると、 すぐに夏休みなんざ、終わっちまうぜ。
鉄は熱いうちに打て！って言うだろう。
オメェらもアツくなれるうちに やっとくのが、イイゼ。

[msg WSHOP_TALK017 [だいだら．のオヤジ]]
オメェの覇気に、華ぁ咲いてるぜ？ なんか、良いことあったのかぃ？
ぬうっ！！旅行だと…？
…ワシは、壬生せんべえでいいぞ。
…なに、行くのは京都じゃない？ ま、期待はしてなかったが…

[msg WSHOP_TALK018 [だいだら．のオヤジ]]
…オメェ、修学旅行だったんだよな？
も…もしかして、お土産とか… い…いや、期待してねぇぞ！！
…ま、事故とかなくって 良かったじゃねぇか。

[msg WSHOP_TALK019 [だいだら．のオヤジ]]
ぬっ？…なんだ？ “探偵王子”だ？
…気に食わんな…ワシ、“王子”より “武将”の方が好きでな…
…で、ワシの“アート”と なにか関係があるのか？
…ないの？ …マジメに聞いて損したわっ！

[msg WSHOP_TALK020 [だいだら．のオヤジ]]
秋深し…鉄の匂いも、紅葉色… どうだ？なかなか良い句だろ？
ぬ…大して意味がないだと… ぬぅぅ…ワシの日常を詠ったのに…
まあいい… さっさと、素材、出さんかい…
…今のは句じゃないぞ。

[msg WSHOP_TALK021 [だいだら．のオヤジ]]
もう秋か…オメェと知り合って 半年以上経っちまったナ？
…ぬっ？ ワシの顔の刀傷はなんだと？
詳しいことは、男同士、聞いてくれるな…
…コレもまた…ワシの“アート”だと 言っておこうか…

[msg WSHOP_TALK022 [だいだら．のオヤジ]]
なんだ…顔青いじゃねぇか？ …ま、男同士、なんも聞かねぇゾ。
守りたいものを守る… オメェ、漢の瞳…してるゼ。

[msg WSHOP_TALK023 [だいだら．のオヤジ]]
…なんだか辛そうな顔してやがる。
男ってのは、真顔で 耐えなきゃなんねぇ時もあるがな…
…ま、あんまり心にため過ぎるな。

[msg WSHOP_TALK024 [だいだら．のオヤジ]]
おかしな霧が、ワシの工房の種火を 消そうと…むうっ…許せんっ！
この種火のおかげで、 ワシの冷え性も治ってたのに…
こんな真冬に、閉鎖になったら ワシ、どうやって生きていけば…！

[msg WSHOP_TALK025 [だいだら．のオヤジ]]
いつの世にも悪は絶えない… 確かにそうだなぁ…
…覚えとけ。 悪は粛清され、善は勝ち誇る。
これが世の道理ってもんだ。 …今は逆転してるがな。
オメェには、真っ直ぐな瞳で 何が悪いか見極めて欲しいぜ…

[msg WSHOP_TALK026 [だいだら．のオヤジ]]
バイトだぁ？
ワシの“アート”を理解できなきゃ、 バイトなんぞさせないぜ。
今までに、ワシの“アート”を真に理解できる ヤツがこの世にいたとしたら…
オメェさんぐらいだな！ ダッハハハハハハ！
まぁ、そもそもバイトなんざ 募集した事ねぇけどな。

[msg WSHOP_TALK027 [だいだら．のオヤジ]]
例のおかしな霧、すっかり消えちまったなぁ。 まるで最初からなかったみてぇだぜ。
何だぁ？誇らしげな顔しやがって。 まさかこの一件、オメェが絡んでんのか？
ダッハハハハハハハ！気に入った！ オメェって奴ぁ、アートしてるぜ！

[msg WSHOP_TALK028 [だいだら．のオヤジ]]
おう、よく来たな！ あけましておめでとうさん。
正月くれぇ休むかと思ったが… オメェのツラ見たら、どうにもうずいてきやがった。
いっちょ気合い入れて アート初めと行くかぁ！

[msg WSHOP_TALK029 [だいだら．のオヤジ]]
いやあ、外は毎日クソ寒いな！ だが、ここは暑いぜ？
ワシの燃え上がるアートなハートが、 ハードでキュートなビートを刻んどるからな！
何？種火のせいだろってそりゃオメェ… まあ、１０００度近けぇからなぁ…

[msg WSHOP_TALK030 [だいだら．のオヤジ]]
オメェらが気楽に出入りしてるせいか、 前より見に来る客も増えてなぁ。
弟子にしてくれ、なんてのもいるが、 アートってな、教わるもんじゃねぇ。
心の声に耳を澄まし、魂を燃やし尽くす！ それでこそアートってもんよ！

[msg WSHOP_TALK031 [だいだら．のオヤジ]]
おう、どうした。 都会に帰るんじゃなかったのか？
…ふーむ、その顔はどうも 何かやり残した事があるってぇツラだな。
ま、野暮は言いっこナシだ。 オメェとワシの仲だろ？存分に見ていきな！

[msg WSHOP_TALKCMM001 [だいだら．のオヤジ]]
むぅ…旦那が亡くなった家の、 蔵の中身、買い取ったんだがなぁ…
意味深な手紙が出てきやがってよぉ… 恋文だぜ…厄介だろ？
捨てるってのも、薄情だし… 返しに行くってのもなぁ…
＞ひさ乃が言っていた手紙のことだろうか…
＞手紙を預かることにした。
＞[f 2 5 3 65535 0]を手に入れた。

[msg WSHOP_TALKCMM002 [だいだら．のオヤジ]]
むぅっ！オメェ、良い所に来た！
この間の手紙なんだがぁ… また出てきやがってよ。
良かったら、また預かってくれねぇか…
＞手紙を預かることにした。
＞[f 2 5 3 65535 0]を手に入れた。

