[sel PARTY_EDIT_YESNO top]
Yes
No

[sel PARTY_EDIT_YESNO_CALL top]
Yes
No

[sel PARTY_EDIT_YESNO_CALL_DE top]
Yes
No

[sel PARTY_EDIT_YESNO_REGIST_ top]
Yes
No

[msg MSG_ORGIA000]
Orgia Mode explainer. Although it's not[n]complicated...
Agreed! Looking forward to it!

[msg PARTY_EDIT_MSG_CALL_COMF]
Use this registered party?

[msg PARTY_EDIT_MSG_SET_COMFI]
Register [f 2 4 0]?

[msg PARTY_EDIT_MSG_DEL_COMFI]
Delete [f 2 4 0]?

[msg PARTY_EDIT_MSG_CANCEL_CR]
Leave without registering the party?

[msg PARTY_EDIT_MSG_NAME_ENTR]
Enter a name for this party using the[n]Touch Screen.

[msg PARTY_EDIT_MSG_CANCEL_ED]
Do you want to leave without changing[n]the party formation?

[msg PARTY_EDIT_MSG_PARTY_ALL]
There's no one in your party who's[n]actually in condition to fight.

[msg PARTY_EDIT_MSG_LEADER_NO]
The team leader hasn't been chosen. Make[n]sure you have one.

[msg PARTY_EDIT_MSG_NO_MEMBER]
Select allies to add to the party.

[msg PARTY_EDIT_MSG_LEADER_NO_2]
Choose a party leader, someone with the[n]power of the wild card.

[msg PARTY_EDIT_MSG_FIRST_NAV]
A navigator hasn't been chosen. You need[n]one!

[msg PARTY_EDIT_MSG_DUNGEON_N]
You forgot to choose a field navigator.

[msg PARTY_EDIT_RISKY_INVALID]
When your difficulty is set to Risky,[n]you must include [f 6 1 30 0 0 0] in the party.

