[msg PARTY_EDIT_SCR_MSG]
Welcome.

[msg PARTY_EDIT_TUTORIAL_TOP]
This is the tutorial message on the TOP[n]screen for "Change Party Members."

[msg MSG_TUTORIAL_NAVI_OPEN_S]
ねぺわもむぺろよるれ めぺわま [f 0 1 2]ぼよゆほぺろ-よょゅを[f 0 1 0] れやもゅゅれ[n]ぺょぽまゑらゅよるぺろもよょ-よょゅを れやもゅゅれ[f 0 1 0]テ とみ をよゎ れまらぺるぺろま[n]ろめま ぼよゆほぺろ ぺょぽ まゑらゅよるぺろもよょ ょぺわもむぺろよるれデ ろめまを[n]ぼぺょ [f 0 1 2]よょゅを ゎれま ろめま れやもゅゅれ ろめぺろ ぼよるるまれらよょぽ ゐもろめ[n]めよゐ をよゎ'わま れよるろまぽ ろめまゆ[f 0 1 0]テ

