[msg MSG_000 [Morgana]]
Otra vez... 夷Fue otro de los recuerdos[n]de Hikari?

[msg MSG_001 [P3 Hero]]
Ciertamente, encaja en el patr吋n.
La Hikari de ese clip era la misma del[n]musical.

[msg MSG_002 [Yukari]]
Pero eso no era como un musical… Es m茨s[n]bien algo as胤 como la historia de su[n]vida.

[msg MSG_003 [Hikari]]
Se sienten como mis recuerdos... Muy[n]preciados...
Pero, no puedo recordar...

[msg MSG_004 [Haru]]
Hikari...

[msg MSG_005 [Hikari]]
夷Por qu姻? Son mis recuerdos... Quiero[n]recordarlos, pero...

[msg MSG_005_5 [Hikari]]
Es casi como... Si me negara a recordar,[n]en el fondo...

[sel SEL_006 top]
No exageres.
Lo recordar茨s eventualmente.

[msg MSG_007 [Hikari]]
Gracias... Prometo que lo lograr姻...

[msg MSG_008 [P4 Hero]]
Cierto, nos tienes de tu lado tambi姻n.[n]Vamos.

