[msg MSG_000 [Voz De Hombre Tranquila]]
Hikari, 夷no vas a salir?

[msg MSG_001 [Chica Con La Mirada Perdida]]
...

[msg MSG_002 [Voz De Hombre Tranquila]]
Te compr姻 el cuaderno que quer胤as.

[msg MSG_003 [Chica Con La Mirada Perdida]]
...

[msg MSG_004 [Voz De Hombre Tranquila]]
Hikari, 夷por qu姻 no sales?

[msg MSG_005 [Voz De Hombre Tranquila]]
*Suspira*
夷Por qu姻 tienes que ser as胤?

