[msg MSG_000 [Ann]]
Eso... 夷Le pas吋 a Hikari?

[msg MSG_001 [Akechi]]
S胤, escuch姻 "asamblea de clase", as胤 que[n]debe ser de cuando estaba en la[n]primaria.

[msg MSG_002 [Yukiko]]
夷Qu姻 es lo correcto y qu姻 es lo[n]incorrecto, eh?

[msg MSG_003 [Naoto]]
Es realmente dif胤cil juzgar lo que es[n]correcto o incorrecto cuando no hay unas[n]reglas definidas...
Pero esa situaci吋n... No era diferente[n]de una dictadura.

[msg MSG_004 [Ryuji]]
Lo que dice la profesora es lo correcto,[n]夷eh? 斡De ninguna forma estar姻 de acuerdo[n]con ESO!

[msg MSG_004_5 [Ryuji]]
斡Todo lo que hizo fue imponer sus[n]decisiones ego胤stas a los dem茨s, solo[n]porque era parte de la mayor胤a!

[msg MSG_005 [Hikari De Primaria]]
Los profesores no son aliados de los[n]d姻biles. No existen los h姻roes...

[msg MSG_006 [Ken]]
Oh, 夷Es la Hikari del pasado?

[msg MSG_007 [Hikari De Primaria]]
El poder de hacer que la gente haga lo[n]que se les ordena... Mi profesora me[n]oblig吋 a disculparme usando ese poder...

[msg MSG_008 [夷Hikari?]]
...S胤. Mi profesora no era una hero胤na.

[msg MSG_009 [Junpei]]
Espera, qu姻... 夷Otra Hikari? 夷Es la[n]verdadera?

[msg MSG_010 [Futaba]]
斡No hay duda de que es la real!

[msg MSG_011 [Teddie]]
Hikarin, 斡est茨s a salvo! 斡Voy a[n]rescatarte ahora mismo!

[msg MSG_012 [Yukari]]
Espera un segundo. Ambas est茨n actuando[n]raro...

[msg MSG_013 [Hikari]]
夷Por qu姻 desafiaste a la profesora?[n]Sab胤as que solo te meter胤as en m茨s[n]problemas...

[msg MSG_014 [Hikari De Primaria]]
Bueno... Es como todos los h姻roes que he[n]visto en las pel胤culas...
Eran fuertes, 斡e hicieron lo correcto![n]斡Ayudaron a los d姻biles!
Pero, dije que lo sent胤a... Todo porque[n]mi profesora decidi吋 que estaba[n]equivocada.

[msg MSG_015 [Hikari]]
Las palabras que quer胤a decir no eran[n]"lo siento"...
La verdad es que... lo que realmente[n]quer胤a decirle era…

[msg MSG_016 [Profesora De Primaria]]
斡夷Hikari... a雨n me est茨s desafiando?!

[msg MSG_017 [Profesora De Primaria]]
斡夷Shiratori... a雨n me est茨s desafiando?!

[msg MSG_018 [Hikari De Primaria]]
Te negaste a escucharme...
Ni siquiera intentaste entender. Puedes[n]ser una maestra, 斡pero est茨s equivocada!

[msg MSG_019 [Profesora De Primaria]]
Contest茨ndole a un maestro...

[msg MSG_020 [Profesora De Primaria]]
...斡Iiiiiinaaaaaaceptabllllle.

[msg MSG_021 [Hikari]]
斡Noooo!

[msg MSG_022 [P3 Fem Protag]]
斡Hikari! 斡Cuidado!

[msg MSG_023 [Shinjiro]]
Tch, 斡Tenemos que salvarla!

