[msg MSG_000 [Estudiante De Aspecto Sombrボo]]
...

[msg MSG_001 [Chica Inocente]]
No dejes que te afecte. Te ayudar〒 a[n]limpiarlo.

[msg MSG_002 [Estudiante De Aspecto Sombrボo]]
...メEh?
Ah... Gracias.
Um...

[msg MSG_003 [Hikari De Secundaria]]
Soy Hikari. メTマ eres Miyuki, verdad?
Encantada.

[msg MSG_004 [Miyuki]]
Hikari... Um, es un placer conocerte[n]tambi〒n...

[msg MSG_005 [Miyuki]]
Te gustan las pelボculas, メverdad,[n]Hikari?

[msg MSG_006 [Hikari De Secundaria]]
ムMmhm! Incluso si la he visto antes,[n]puedo volver a verla una y otra vez.
ムLa que vi el otro dボa tenボa[n]dinosaurios! Vamos a verla juntos algマn[n]dボa.

[msg MSG_007 [Miyuki]]
ムメEh?! メEstホs segura? ムMe encantarボa!

[msg MSG_008 [Hikari De Secundaria]]
ムSボ! メPor qu〒 no vamos a verla juntos?

[msg MSG_009 [Estudiante Nerviosa]]
メEh? Oh, tendr〒 que pasar...

[msg MSG_010 [Estudiante Ruidosa]]
Tengo que ir a mis asesorボas...

[msg MSG_011 [Estudiante Malhumorada]]
ムLo siento! Tal vez la prポxima...

[msg MSG_012 [Hikari De Secundaria]]
Ya veo. Es una lホstima... pero, ムestホ[n]bien!

[msg MSG_013 [Miyuki]]
...

[msg MSG_014 [Hikari De Secundaria]]
メQu〒 pasポ con mi escritorio...?

[msg MSG_015 [Estudiante Nerviosa]]
...

[msg MSG_016 [Hikari De Secundaria]]
Oye, メsabes algo sobre esto?

[msg MSG_017 [Estudiante Ruidosa]]
Oh... Es tu culpa, Hikari.

[msg MSG_018 [Hikari De Secundaria]]
メEh?

[msg MSG_019 [Estudiante Malhumorada]]
メNo sabボas que los niワos populares[n]empezaron a meterse con Miyuki?

[msg MSG_020 [Estudiante Nerviosa]]
Si sales con ella, ellos tambi〒n te[n]buscarホn.

[msg MSG_021 [Estudiante Ruidosa]]
Miyuki, メpodrボas dejarnos en paz? Vamos[n]a terminar siendo arrastrados a contigo[n]tambi〒n.

[msg MSG_022 [Miyuki]]
メQu〒...?

[msg MSG_023 [Estudiante Malhumorada]]
Si Miyuki se va, estoy seguro de que ya[n]no te molestarホn, Hikari.

[msg MSG_024 [Hikari De Secundaria]]
Pero, ese tipo de cosas no me molestan.[n]ムSigamos siendo amigos!

[msg MSG_025 [Estudiante Ruidosa]]
...
メPor qu〒 tienes que ser asボ?

[msg MSG_026 [Estudiante Malhumorada]]
Si vas a ser asボ, メpor qu〒 no tomas el[n]lugar de Miyuki?

[msg MSG_027 [Hikari De Secundaria]]
ムメEspera, qu〒?!

[msg MSG_028 [Estudiante Nerviosa]]
Las chicas populares solo quieren[n]alguien a quien puedan molestar...

[msg MSG_029 [Estudiante Ruidosa]]
Si te quedas con nosotros, nosotros[n]tambi〒n la llevaremos. Solo vas a[n]causarnos problemas.

[msg MSG_030 [Miyuki]]
...

[msg MSG_031 [Estudiante Ruidosa]]
ムMuy bien! メQui〒n piensa que Hikari[n]deberボa quedar fuera de nuestro grupo?

[msg MSG_032 [Estudiante Malhumorada]]
ムYo!

[msg MSG_033 [Estudiante Nerviosa]]
Yo tambi〒n...

[msg MSG_034 [Hikari De Secundaria]]
No... メPor qu〒?

[msg MSG_035 [Estudiante Nerviosa]]
Es lo que todos votaron, asボ que...

[msg MSG_036 [Estudiante Malhumorada]]
Sボ, todos estホn de acuerdo. Tマ tambi〒n,[n]メverdad, Miyuki?

[msg MSG_037 [Miyuki]]
Y-yo...
...

[msg MSG_038 [Estudiante Ruidosa]]
Bien, en ese caso, Miyuki es la que estホ[n]fuera.

[msg MSG_039 [Miyuki]]
ムE-espera!
Y-yo... estoy de acuerdo con que Hikari[n]deberボa irse...

[msg MSG_040 [Estudiante Ruidosa]]
メLo ves? Todos estホn de acuerdo, asボ que[n]la decisiポn es obvia.

