[msg MSG_000 [Yusuke]]
夷Les importa si interrumpo? Hay algo que[n]he estado pregunt茨ndome.
La raz吋n por la que todos est茨bamos[n]atrapados en un cine, en primer lugar,[n]est茨 relacionado con Hikari, 夷verdad?
Bien, 夷por qu姻 nosotros?

[msg MSG_001 [Morgana]]
Esa es la parte que a雨n no sabemos...

[msg MSG_002 [Ryuji]]
De todas formas, tenemos la 雨ltima[n]llave. Volvamos.

[msg MSG_003 [Hikari]]
S胤, Nagi nos est茨 esperando... Tambi姻n[n]tengo que cont茨rselo.

[msg MSG_004 [Makoto]]
Bien, regresemos al Cine.

