[msg MSG_MOVIE_000]
メPor qu〒 tienes que ser asボ?

[msg MSG_MOVIE_001]
メPor qu〒 tienes que ser asボ?

[msg MSG_MOVIE_002]
メPor qu〒 tienes que ser asボ?

[msg MSG_MOVIE_003]
No... ムPara!

[msg MSG_MOVIE_004]
Hikari...

[msg MSG_MOVIE_005]
A-ah... Ahh...

[msg MSG_MOVIE_006]
メPor qu〒 tienes que ser asボ?

[msg MSG_MOVIE_007]
メPor qu〒?...

[msg MSG_MOVIE_008]
メPor qu〒?...

[msg MSG_MOVIE_009]
メPor qu〒?...

[msg MSG_MOVIE_010]
メPor qu〒?...

[msg MSG_MOVIE_011]
メPor qu〒?...

[msg MSG_MOVIE_012]
メPor qu〒?...

[msg MSG_MOVIE_013]
メPor qu〒 tienes que ser asボ?

[msg MSG_MOVIE_014]
ムNoooooo!

