[msg MSG_000 [Yukari]]
...Oye, Hikari. Te gustan las pel胤culas,[n]夷verdad?

[msg MSG_001 [Hikari]]
S胤, los amo. 夷Por qu姻?

[msg MSG_002 [Yukari]]
Bueno, me preguntaba por qu姻 estabas[n]atrapada en un cine en primer lugar.

[msg MSG_003 [Teddie]]
Hrmmm... Si Doe es el que encerr吋 a[n]Hikarin, 夷quiz茨s adapto su jaula?

[sel SEL_004 top]
Qu姻 amable de su parte.
Quiz茨 es lo que le gusta a Doe.
Es un anfitri吋n cort姻s.

[msg MSG_005 [Junpei]]
Uh, si es tan amable, 斡夷por qu姻 la[n]atrap吋 para empezar?!

[msg MSG_006 [Yosuke]]
S胤. No importa cu茨nto le gusten las pel胤culas,[n]atraparla y obligarla a ver a esas horribles[n]versiones no tiene sentido.

[msg MSG_007 [Ann]]
Claro. Dado que Doe es el que las proyecta, no[n]es dif胤cil imaginar que elija un lugar que se[n]adapte a sus planes tambi姻n.

[msg MSG_008 [Yusuke]]
Ya veo. Si va a estar tanto tiempo,[n]tambi姻n pudo hacerlo c吋modo para ella.

[msg MSG_009 [Yosuke]]
斡La encarcelo! 斡夷Qu姻 clase de anfitri吋n[n]es ese?!

[msg MSG_010 [Yusuke]]
Aunque, tendr胤a ning雨n problema estar[n]atrapado en la residencia de Joker...
Es un lugar c吋modo, y hay curry. Si tuviera[n]suministros para crear arte conmigo, podr胤a[n]pasar semanas en su casa.

[msg MSG_011 [Yosuke]]
Acabo de experimentar un d姻jà vu...

[msg MSG_012 [Hikari]]
Um... Para ser honesta, me gust吋 ese[n]cine al principio...
Pod胤a ver pel胤culas todo el tiempo que[n]quisiera.

[msg MSG_013 [Ann]]
夷En serio? Pero, 夷no era la misma[n]pel胤cula en bucle hasta que llegamos?
Adem茨s, fue esa horrible pel胤cula de[n]Kamoshidaman... S姻 que te encantan las[n]pel胤culas y todo, pero 夷pero no se volver胤a[n]aburrido?

[msg MSG_014 [Hikari]]
Fue repetitivo, pero no me importaba...[n]En realidad, no me molestaba lo que[n]estaba viendo...

[msg MSG_015 [Yukiko]]
S姻 lo que quieres decir.
Ha habido momentos en los que no quer胤a[n]pensar en nada y huir de todo.

[msg MSG_016 [Hikari]]
Mmhm... Creo que estaba intentando[n]escapar de la realidad en ese cine.
Pero, ya no es el caso. Esos ya no son[n]los tipos de pel胤culas que quiero ver.

[msg MSG_017 [Naoto]]
No tener que pensar mientras vez la[n]pel胤cula... Es casi como si te[n]estuvieras aislando.

[msg MSG_018 [Ken]]
夷Eh? 夷Qu姻 quieres decir?

[msg MSG_019 [Naoto]]
Cuando lleg吋, Hikari no ten胤a[n]intenciones de salir del cine...
Pero, mientras ve胤a las pel胤culas, tanto las[n]pel胤culas como sus sentimientos empezaron a[n]cambiar, y Doe escup胤a las llaves.

[msg MSG_020 [Akechi]]
Es como si sus acciones estuvieran[n]relacionadas con los cambios del coraz吋n[n]de Hikari y su deseo de salir.

[msg MSG_021 [Hikari]]
夷Mi coraz吋n est茨 relacionado con todo[n]esto...?

[msg MSG_022 [Naoto]]
Cuando lleg吋, Hikari no ten胤a[n]intenciones de salir del cine...
Pero, mientras ve胤a las pel胤culas, tanto[n]las pel胤culas como sus sentimientos[n]empezaron a cambiar...
No podemos asegurar nada, pero debe[n]haber alguna conexi吋n entre el Cine y[n]Hikari.
Si tuviera que apostar qui姻n podr胤a cambiar un[n]cine para que est姻 lleno de pel胤culas que[n]reflejen el coraz吋n de Hikari, ser胤a...

[sel SEL_023 top]
Doe.
Nagi.
La brigada azul.

[msg MSG_024 [Ryuji]]
S胤, tiene sentido para m胤.

[msg MSG_025 [Mitsuru]]
Es un buen punto... Doe ha estado[n]proyectando esas pel胤culas todo este[n]tiempo...
Aun as胤, no estoy segura.

[msg MSG_026 [Chie]]
斡夷Qu姻... Hablas en serio?!

[msg MSG_027 [Kanji]]
Uhh... 夷Nagi no despert吋 aqu胤 en el cine[n]con Hikari?
夷Eso no significa que fue arrastrada a[n]este desastre como nosotros?

[msg MSG_028 [Ryuji]]
Entonces, 夷no es Doe el 雨nico que podr胤a[n]lograr algo tan rid胤culo?

[msg MSG_029 [Mitsuru]]
Es un buen punto... Doe ha estado[n]proyectando esas pel胤culas todo este[n]tiempo...
Pero aun as胤, algo no me convence.

[msg MSG_030 [Makoto]]
Mmm... Esa gente de azul podr胤a saber[n]algo, pero...

[msg MSG_031 [Ryuji]]
Hay alguien m茨s sospechoso que ellos.

[msg MSG_032 [Mitsuru]]
Quieres decir Doe... 姻l ha estado[n]proyectando esas pel胤culas todo este[n]tiempo...
Pero aun as胤, algo no me convence.

[msg MSG_033 [Akechi]]
Debo decir que estoy de acuerdo...
Sin embargo, no tenemos idea de cu茨les[n]son las intenciones de Doe, as胤 que no[n]podemos decir nada con certeza a雨n.

[msg MSG_034 [Akihiko]]
Supongo que todo lo que podemos hacer es[n]encontrarlo y hacer que responda. Qui姻n sabe[n]si eso realmente nos servir茨 de algo...
Hikari y Doe entraron en esta pel胤cula,[n]夷verdad? Tiene que haber una raz吋n por[n]la que hizo ese movimiento.

[msg MSG_035 [Shinjiro]]
Aki tiene raz吋n. 夷D吋nde diablos est茨?

[msg MSG_036 [Hikari]]
Creo que est茨 al final de esta[n]pel胤cula... en el punto m茨s profundo.

[msg MSG_037 [P4 Hero]]
夷Puedes decirnos d吋nde est茨?

[msg MSG_038 [Hikari]]
Es solo un presentimiento... Pero no[n]estoy segura.

[msg MSG_039 [Naoto]]
Para nada, este lugar est茨 probablemente[n]胤ntimamente conectado con tu coraz吋n...
As胤 que seguirlo deber胤a ser la manera[n]m茨s r茨pida de resolver el problema.

[msg MSG_040 [P3 Hero]]
Entendido. Te seguiremos.
Vamos, sigamos.

