[msg MSG_000 [Yukari]]
メQ-qu〒 fue eso?

[msg MSG_001 [Akechi]]
メPodrボa haber sido un recuerdo de[n]Hikari? Fue mucho mホs sombrボo que el[n]trホiler...

[msg MSG_002 [Rise]]
メAdポnde fueron esa profesora y sus[n]alumnos? メLa Hikari del pasado tambi〒n[n]desapareciポ?

[msg MSG_003 [Koromaru]]
ムArf arf!

[msg MSG_004 [Hikari]]
Ah... Eso...

[msg MSG_005 [P3 Fem Protag]]
ムHikari!

[msg MSG_006 [Ann]]
ムHikari! ムQu〒 alivio, estホs bien!

[msg MSG_007 [Teddie]]
メEstホs herida, Hikarin?

[msg MSG_008 [Hikari]]
No... estoy bien.

[msg MSG_009 [Mitsuru]]
Siento interrumpir, pero メa dポnde fue[n]Doe? Te secuestrポ y te trajo aquボ,[n]メverdad?

[msg MSG_010 [Hikari]]
Oh... Ah, eso no es...
Yo... Yo vine sola.

[msg MSG_011 [Futaba]]
ムメQ-qu〒?! メNo fue Doe?

[msg MSG_012 [Hikari]]
Mientras veボa las pelボculas que[n]cambiaron, empec〒 a recordar, poco a[n]poco...
Todas las cosas que habボa reprimido y[n]olvidado...
Todo empezポ a salir dentro de mボ, y[n]despu〒s de recordar esas cosas...
...Sentボ que necesitaba cambiar.

[msg MSG_013 [Naoto]]
メEntonces decidiste entrar en la[n]pelボcula por ti misma?

[msg MSG_014 [Hikari]]
...Doe me dijo que lo hiciera.
Dijo que no puedo seguir siendo parte[n]del pマblico para siempre... Que necesito[n]superar esto...
Cuando me dijo eso, mi deseo de venir[n]aquボ solo se hizo mホs fuerte... Asボ[n]que...

[sel SEL_015 top]
No seas tan imprudente la prポxima vez.
メSeguro que no estホs herida?
Nos alegra que est〒s bien.

[msg MSG_016 [Hikari]]
Lo siento... Pero sentボ que tenボa que[n]venir aquボ...

[msg MSG_017 [Yukiko]]
メEstホs herida? メTe han atacado mientras[n]estabas aquボ?

[msg MSG_018 [Hikari]]
No, estoy bien... Pero no estoy segura[n]de por qu〒...

[msg MSG_019 [Hikari]]
Mmhm, No he estado en peligro desde que[n]llegu〒 aquボ...

[msg MSG_020 [Hikari]]
Ah... Afortunadamente, no he encontrado[n]ningマn peligro desde que llegu〒 aquボ...

[msg MSG_021 [Yukiko]]
Ya veo. Estoy aliviado de que no est〒s[n]herida.

[msg MSG_022 [Futaba]]
Oh, estoy tan contenta de que est〒s[n]bien, Hikari... ムSiento que eso me quitポ[n]unos aワos de vida!

[msg MSG_023 [Hikari]]
Futaba, siento haberte preocupado... Y[n]los demホs tambi〒n.

[msg MSG_024 [P4 Hero]]
Entonces, ese musical que vimos, メeras[n]tマ...?

[msg MSG_025 [Hikari]]
Mmhm... La historia estホ basada en mis[n]recuerdos.
Fue en forma de musical, pero es lo que[n]pasポ... fue casi exactamente igual a mi[n]pasado.

[msg MSG_026 [Yusuke]]
Asボ que lo que vimos fue, biogrホfico...

[msg MSG_027 [Ryuji]]
ムメQu〒 demonios pasaba con esa maestra?![n]ムEso fue peor que malo! ムDeberボan[n]haberla despedido por eso!

[msg MSG_028 [Akechi]]
Es verdad, eso fue imperdonable, pero al[n]menos siento como si las piezas del[n]rompecabezas encajaran ahora.

[msg MSG_029 [Naoto]]
Conceptos como "h〒roe" y "profesor"...[n]"Autoridad absoluta". La マltima palabra[n]clave serボa...

[sel SEL_030 top]
Regla de la mayorボa.
"Conejo".
"Robot".

[msg MSG_031 [Akechi]]
Eso es de una pelボcula diferente. La[n]pieza final para ese rompecabezas es[n]"conejo".

[msg MSG_032 [Akechi]]
Exacto.

[msg MSG_033 [Ann]]
Espera... メEstホn hablando de[n]Kamoshidaman? メY cuホndo se transformポ en[n]un conejo?

[msg MSG_034 [Futaba]]
Sボ. Kamoshidaman fue creado a partir de[n]los recuerdos de Hikari.

[msg MSG_035 [Yusuke]]
Esa maestra de primaria era la[n]"autoridad absoluta" de su clase.
Esto describe perfectamente a Kamoshidaman[n]tambi〒n. Nadie debe haber podido desafiarlo,[n]incluso cuando estaba equivocado.

[msg MSG_036 [Makoto]]
Con el incidente del conejo, Hikari fue[n]injustamente regaワada por una maestra,[n]alguien con autoridad absoluta.
Y el conejo, el sボmbolo del trauma de[n]Hikari, tambi〒n apareciポ en la[n]pelボcula...

[msg MSG_037 [Hikari]]
...

[msg MSG_038 [Ann]]
Ahora que lo pienso, esos ciudadanos que[n]admiraban a Kamoshidaman... Deben haber[n]sido los estudiantes que no...
No, quienes no pudieron hablarle a la[n]maestra por su autoridad.

[msg MSG_039 [Ryuji]]
Una pelボcula de mierda nacida de[n]recuerdos de mierda, メeh? No me extraワa[n]que fuera tan asqueroso.

[msg MSG_040 [Haru]]
Entonces, pero esta lポgica se aplica a[n]mホs pelボculas, ademホs de la de[n]Kamoshidaman, メno?

[msg MSG_041 [Makoto]]
Tienes razポn... Lo mismo podrボa decirse[n]acerca de A.I.G.I.S. o Junesic Land...
Creo que todas han estado conectadas a[n]los recuerdos de Hikari, de alguna forma[n]u otra.

[msg MSG_042 [Shinjiro]]
Eso significa que esta pelボcula con[n]tボtulo ilegible tambi〒n estホ relacionada[n]con sus recuerdos.

[msg MSG_043 [Akihiko]]
Mm... Siento que poco a poco estamos[n]empezando a ver el porqu〒 de este mundo[n]de pelボculas.

[msg MSG_044 [Naoto]]
メPor qu〒 naciポ este mundo para empezar?
El pasado doloroso de alguien no explica[n]la razポn detrホs de todo este mundo.

[msg MSG_045 [Mitsuru]]
Hikari, se te ocurre algo?

[msg MSG_046 [Hikari]]
Lo siento. No puedo pensar en nada...

[msg MSG_047 [Morgana]]
Un mundo que refleja el corazポn de una[n]persona... Suena como algo con lo que[n]tenemos experiencia.

[sel SEL_048 top]
メQu〒 quieres decir?
Un mundo cognitivo...

[msg MSG_049 [Morgana]]
ムOh, vamos! ムEstoy hablando del mundo[n]cognitivo! メRealmente olvidaste todo[n]eso?
Bueno, no podemos usar el Navegador[n]aquボ, asボ que esto no serホ exactamente[n]lo mismo...

[msg MSG_050 [Morgana]]
Cierto. Pero no podemos usar el[n]navegador Metaverse aquボ, asボ que esto[n]no parece ser exactamente lo mismo...

[msg MSG_051 [Yosuke]]
No estoy seguro de por qu〒, pero este lugar se[n]siente bastante similar al mundo de la[n]televisiポn en el que peleamos.

[msg MSG_052 [Kanji]]
Oh, sボ, ahora que lo mencionas, se[n]siente igual.

[msg MSG_053 [Yukiko]]
Asボ que, en esencia, las pelボculas se[n]basan en las experiencias traumatizantes[n]de Hikari, メverdad?
Entonces necesitamos reconsiderar el[n]objetivo de Doe, aunque 〒l sigue siendo[n]un completo misterio para nosotros...

[msg MSG_054 [Yukari]]
Doe le dijo a Hikari: "Necesitas superar[n]esto", メverdad?
Considerando eso, estoy empezando a[n]pensar que 〒l no es realmente el malo[n]despu〒s de todo...

[msg MSG_055 [Hikari]]
...

[msg MSG_056 [Junpei]]
メEstホs bien, Hikari? メTe sientes mal?

[msg MSG_057 [Hikari]]
No es eso. Yo solo... Sigo pensando en[n]por qu〒 siempre soy asボ...
Es mi problema, asボ que deberボa ser la[n]que lo resuelva...
Pero al final, causo tantos problemas[n]para todos... Si soy el problema,[n]entonces tal vez deberボa...

[sel SEL_058 top]
Te estホs preocupando demasiado.
No vemos las cosas asボ.
No seas tan dura contigo misma.

[msg MSG_059 [Yosuke]]
Sボ, lo que 〒l dijo. Ninguno de nosotros[n]estホ molesto por eso.

[msg MSG_060 [P3 Hero]]
La idea de que seas un problema para nosotros[n]ni siquiera cruzポ por mi mente. Todos vinimos[n]aquボ porque querボamos ayudar.
Espero que nos creas cuando decimos que[n]no pensamos eso de ti.

[msg MSG_061 [Morgana]]
Cierto, los Ladrones Fantasma estamos[n]destinados a salvar a la gente en[n]problemas.

[msg MSG_062 [P3 Hero]]
Los miembros de SEES vinieron aquボ[n]porque querボamos rescatarte, lo mismo[n]para el Equipo de Investigaciポn.
Espero que nos creas cuando decimos que[n]no pensamos eso de ti.

[msg MSG_063 [Akihiko]]
Sボ, no hay necesidad de culparte por[n]esto. Nadie aquボ tiene problema en[n]ayudar.

[msg MSG_064 [P3 Hero]]
La idea de que seas un problema para nosotros[n]ni siquiera cruzポ por mi mente. Todos vinimos[n]aquボ porque querボamos ayudar.
Espero que nos creas cuando decimos que[n]no pensamos eso de ti.

[msg MSG_065 [Hikari]]
Ustedes...

[msg MSG_066 [P3 Fem Protag]]
Ademホs, solo hemos llegado tan lejos por[n]qu〒 trabajamos juntos, メno crees que[n]somos un equipo?

[msg MSG_067 [Haru]]
Todos podemos ver realmente que quieres[n]cambiar, Hikari...
Por eso quiero darte mi fuerza.

[msg MSG_068 [Hikari]]
Muchas gracias...
Si no mucho pedir―No... メPodrボan[n]prestarme su fuerza, por favor?
Para cambiar, y para que todos salgamos[n]de este lugar... ムQuiero ver el final de[n]esta pelボcula!

[msg MSG_069 [Teddie]]
ムTotalmente y seguro! Todos opinamos lo[n]mismo, メverdad, Yosuke?

[msg MSG_070 [Yosuke]]
メPor qu〒 me preguntas, idiota? ムNo soy[n]todos! ムPero, por supuesto, que estoy[n]dentro!

[msg MSG_071 [Mitsuru]]
Mm, todos ustedes son personas tan[n]confiables...
Escapar de este mundo sigue siendo importante,[n]pero hemos llegado hasta aquボ, vamos a ver[n]esto juntos, hasta el final.

[msg MSG_072 [Ryuji]]
ムBien, estホ decidido! ムVamos a[n]adentrarnos en esta pelボcula y cambiarla[n]completamente!

