[msg MSG_000 [Hikari]]
N-no... ムEsto no estホ bien, esto no estホ[n]bien!
※l... ※l no me dijo eso.

[msg MSG_001 [Hombre Con Gafas]]
メDe qu〒 estホs hablando? メNo soy el "yo"[n]que conoces?

[msg MSG_002 [Hikari]]
ムNo! En realidad... ムno sucediポ asボ!
Todo estホ en mi... mi...

[msg MSG_003 [Hombre Con Gafas]]
Hikari... メPor qu〒?…

[msg MSG_004 [P3 Fem Protag]]
ムHikari, cuidado!

[msg MSG_005 [Hombre Con Gafas]]
ムメPor qu〒 tienes que ser asボボボボボボボボボ?!

[msg MSG_006 [Hikari]]
ムNoooooo!

[msg MSG_007 [Futaba]]
ムAquボ viene! ムProtejan a Hikari!

[msg MSG_008 [Ryuji]]
ムNo tienes que decirlo dos veces![n]ムHagホmoslo!

