[msg MSG_MOVIE_000]
斡Hikari es una chica mala!

[msg MSG_MOVIE_001]
斡Hikari es una chica mala!

[msg MSG_MOVIE_002]
斡Ella nunca escucha!

[msg MSG_MOVIE_003]
斡Qu姻 chica mala!

[msg MSG_MOVIE_004]
斡Yo no hice nada malo!

[msg MSG_MOVIE_005]
No interrumpas la armon胤a de la clase...[n]斡Es lo que siempre te digo!

[msg MSG_MOVIE_005_5]
斡Todos tienen que hacer lo que digo!

[msg MSG_MOVIE_006]
夷Por qu姻? 夷No se supone que los maestros[n]deben estar de acuerdo con quien tenga[n]raz吋n?

[msg MSG_MOVIE_007]
Con una chica tan mala...

[msg MSG_MOVIE_008]
斡El conejo acabar茨 muriendo!

[msg MSG_MOVIE_009]
Es culpa de Hikari...

[msg MSG_MOVIE_010]
斡Ella es la raz吋n por la que morir茨!

[msg MSG_MOVIE_011]
斡No! 斡Eso no es verdad!

[msg MSG_MOVIE_012]
斡Disc雨lpate!

[msg MSG_MOVIE_013]
斡Eso no est茨 bien!

[msg MSG_MOVIE_014]
斡Lo que dice la profesora siempre es lo[n]correcto!

[msg MSG_MOVIE_015]
斡Por favor, esc雨chame!

[msg MSG_MOVIE_016]
斡斡斡Pide disculpas!!!

[msg MSG_MOVIE_017]
Yo... Lo siento...

[msg MSG_MOVIE_018]
Ahora eres una buena chica.

