[msg MSG_MOVIE_000]
斡Hikari ser茨 expulsada!

[msg MSG_MOVIE_001]
斡La expulsamos porque piensa diferente!

[msg MSG_MOVIE_002]
夷No podemos ser amigos solo porque[n]pensamos diferente?

[msg MSG_MOVIE_003]
Vamos, 夷por qu姻 no?

[msg MSG_MOVIE_004]
斡S胤, as胤 es!

[msg MSG_MOVIE_005]
斡S胤, as胤 es!

[msg MSG_MOVIE_006]
斡S胤, as胤 es!

[msg MSG_MOVIE_007]
斡S胤, as胤 es!

[msg MSG_MOVIE_008]
斡Hikari ser茨 expulsada!

[msg MSG_MOVIE_009]
斡Lo que la mayor胤a piensa es lo[n]correcto!

[msg MSG_MOVIE_010]
夷Y qu姻 pasa con las otras opiniones?

[msg MSG_MOVIE_011]
斡Solo est茨n siendo ego胤stas!

[msg MSG_MOVIE_012]
斡S胤, as胤 es!

[msg MSG_MOVIE_013]
斡S胤, as胤 es!

[msg MSG_MOVIE_014]
斡S胤, as胤 es!

[msg MSG_MOVIE_015]
斡S胤, as胤 es!

[msg MSG_MOVIE_016]
T雨 eres la que est茨 equivocada,[n]Hikari...

[msg MSG_MOVIE_017]
斡As胤 es, Miyuki! 斡T雨 eres nuestra amiga!

[msg MSG_MOVIE_018]
Pero Hikari es diferente...

[msg MSG_MOVIE_019]
Es la 雨nica que es diferente...

[msg MSG_MOVIE_020]
斡Por eso no es nuestra amiga!

[msg MSG_MOVIE_021]
斡No nuestro amigo!

[msg MSG_MOVIE_022]
夷Por qu姻 solo yo...?

[msg MSG_MOVIE_023]
Es tu culpa, Hikari. Debes pensar igual[n]el grupo.

