[msg MSG_BTL_001]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Ni隠os traviesos, cuidado![n][f 1 1][e]

[msg MSG_BTL_002]
[f 0 5 65278][f 2 1][f 0 6 255 255]Nosotros, la Liga de la Belleza...[n][f 1 1][e]

[msg MSG_BTL_003]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Tambi姻n conocidas como, las chicas[n]bonitas![n][f 1 1][e]

[msg MSG_BTL_004]
[f 0 5 65278][f 2 1][f 0 6 255 255]...斡nos apoderaremos de sus corazones![n][f 1 1][e]

[msg MSG_BTL_005]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Aqu胤 vamos![n][f 1 1][e]

