[msg MSG_000 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 1 1][f 3 1 1 0 0 24022][f 6 1 2 0 0 4]Hm? What's that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 0]Oh, it looks like something's shining...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 0][f 3 1 1 0 0 0]That's a rather beautiful glimmer...[n]I wish to observe it closer.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 0][f 3 1 1 0 0 22061][f 6 1 2 0 0 10]Wait, is it safe? It could be a trap![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 0][f 3 1 1 0 0 0]Hmm, the more I look at it, the more[n]mysterious its shine becomes. Could[n]such an aura... be replicated with paint?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]He ain't listenin' at all![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 26 12 100 1][f 3 1 6 0 0 500][f 3 1 1 0 0 26591]Fox is useless once he gets like[n]this. Just ignore what he says.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 26 8 99 1][f 3 1 1 0 0 0]But―more importantly! It looks like[n]there's something unusual there.[n]Check it out, Joker![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 0 0 0][f 3 1 1 0 0 0]*sigh* I should've brought my art[n]supplies...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Grr... How careless could I be!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 0 0 0][f 3 1 1 0 0 21091]Okay, bud, that's enough―let's go![n][f 1 3 65535][f 1 1][e]

