[msg MSG_000 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26643]Looks like that Kamoshida Square is[n]on the other side of these gates.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm getting readings of Queen and Noir...[n]and Kamoshidaman, too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Be careful, everyone![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 1 1][f 3 1 1 0 0 23069]Yeah, I doubt he'd just pleasantly hand[n]those two over to us...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]He'll most likely be a tough opponent,[n]so we could potentially benefit from[n]heading back and regrouping first.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]We'll leave that decision to you, Joker―[n]what should we do?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 6 0 0 500][f 4 6 20 1 0 3][f 4 6 26 2 99 1][f 3 1 1 0 0 26502]Beyond these gates is Kamoshida Square.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm getting readings of Queen and Noir...[n]and Kamoshidaman, too.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Are you really ready to do this?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Let's go.[f 2 7 1 20 6 32][e]
[f 0 5 65278][f 2 1]Not yet.[f 2 7 1 20 6 32][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23072][f 6 1 2 0 0 6]Okay, then―everyone, follow Joker's[n]lead![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23070]We can't be too cautious, after all. Let's[n]make sure we charge in fully prepared.[n][f 1 3 65535][f 1 1][e]

