[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 2 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19012]You know, there's something about[n]the citizens here... They're sort of eerie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oh, you got that feeling too,[n][f 6 1 27 0 0 0]-chan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 0]Everyone's trying to convince[n]themselves that a hero of justice is[n]always right and can do no wrong...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002_5 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19080][f 6 1 2 0 0 3]But it's like they refuse to think about[n]what really matters: figuring out what[n]justice actually is...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It's like they're just going with the flow―[n]the justice here is absolute, all because[n]they're told it is.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 6 0 6][f 3 1 1 0 0 0]Yeah, none of 'em are even tryin' to[n]think for themselves...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Kamoshidaman ain't right in the first[n]place, but these people don't make[n]any sense, either![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 1 0][f 3 1 1 0 0 22091]If anything goes in the name of justice,[n]this place is nastier than Kamoshida[n]before his heart was changed.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 23 12 1 1][f 3 1 1 0 0 0]Well, that's even more of a reason for us[n]to not dally around here, then.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Let's hurry up with the rescue operation.[n][f 1 3 65535][f 1 1][e]

