[msg MSG_000 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 35 1 0 1][f 4 6 7 0 0 3][f 3 1 1 0 0 7010][f 6 1 2 0 0 4]Y'know, I've been wonderin'...[n]Can you fight?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35009]NO. I HAVE NO BATTLE FUNCTIONS.[n]PLEASE REMEMBER THIS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 0 0][f 3 1 1 0 0 26031]Don't worry! All you gotta do is[n]follow us.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 6][f 3 1 1 0 0 10067][f 6 1 2 0 0 6]Yeah, leave the fighting to us![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 0][f 3 1 1 0 0 35012][f 6 1 2 0 0 4]YOU ARE BRINGING ME ALONG, EVEN[n]THOUGH I CANNOT FIGHT? YOU DO[n]NOT BENEFIT FROM THIS. SO, WHY?[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]There is a benefit.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Just drop it and follow me.[f 2 7 1 20 0 32][e]

[msg MSG_006 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35014]TRUE, I CAN AT LEAST SERVE AS[n]A SHIELD...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 6 1 6][f 3 1 1 0 0 26135][f 6 1 2 0 0 6]N-No living shields! Nobody asked you[n]to do that! Just follow us, okay?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 1 0][f 3 1 1 0 0 35007]BUT...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 6][f 3 1 1 0 0 7107][f 6 1 2 0 0 6]Don't sweat all the details. C'mon,[n]let's go![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Yukari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 10 12 0 3][f 3 1 1 0 0 10018][f 6 1 2 0 0 4]Wait―going back to the movie theater[n]is fine for us, but what about her?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 6 0 1][f 3 1 1 0 0 0]Now that you mention it―can[n]she leave this movie?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 3][f 3 1 1 0 0 0]I have no idea whether or not there[n]would be any ill effects for her...[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 12 0 1][f 3 1 1 0 0 26009]Precision machinery is very delicate.[n]We shouldn't bring her around any[n]setting that she's not designed for.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]So should we try to hide her[n]somewhere? Oh, but what if she[n]got caught by those security robots?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 12 0 1][f 3 1 1 0 0 35008]IF THIS CONCERNS YOU, I BELIEVE[n]THERE IS A SOLUTION.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I SHOULD NOT BE IDENTIFIABLE TO[n]THE SECURITY ROBOTS' SENSORS[n]IF I SUSPEND MY OPERATIONS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Suspend your operations? Do you mean[n]power down?[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Robot with a ribbon]]
[f 0 5 65278][f 2 1][f 4 6 35 0 0 0][f 3 1 1 0 0 35008]NO. I HAVE A SLEEP MODE. I AM ABLE[n]TO TEMPORARILY AND HARMLESSLY[n]SUSPEND OPERATIONS.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 2 0 3][f 3 1 1 0 0 24047]Oh? That sounds useful. Then, I shall[n]go ahead and activate―[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hey! Don't go fiddling with her settings[n]without her permission![n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 25 12 0 3][f 3 1 1 0 0 25009]Even if you're able to avoid their sensors,[n]I'm concerned about just leaving you[n]here in the open.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Why don't you take cover somewhere[n]before engaging sleep mode?[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1066]I agree. That definitely sounds like it[n]would be safer.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Well, our next goal is to find the[n]remaining members of SEES.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 3 1 1 0 0 0]Let's go![n][f 1 3 65535][f 1 1][e]

