[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 1][f 3 1 1 0 0 3124][f 6 1 2 0 0 10]Ack! Another robot![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 3 11 0 1][f 4 6 21 12 1 3][f 3 1 1 0 0 21037][f 6 1 2 0 0 0]And we're at a dead end! What're we[n]gonna do!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 13 2 1 1][f 3 1 1 0 0 13023]The gate that alternates between open[n]and closed states is just up ahead...[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Let's destroy the FOE.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Let's lead the FOE there.[f 2 7 1 20 2 32][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 1][f 3 1 1 0 0 12107]What, we're destroying it with our fists?[n]In that case, leave it to me.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 8 1 4][f 3 1 1 0 0 0]Hey moron, there's no way you or[n]anybody is punching that thing[n]and living to talk about it![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Naoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 8 0 0 1][f 3 1 1 0 0 8001]U-Um...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Wouldn't the closed door open up if we[n]led the pursuing FOE through the gate?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 1][f 3 1 1 0 0 28076]Ah, that's a great idea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]If we have the pursuing FOE go through[n]the gate, the currently closed door will[n]open for us... Is that your plan?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23072][f 6 1 2 0 0 6]I can definitely see that working. Let's[n]give it a try, Joker![n][f 1 3 65535][f 1 1][e]

