[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 1][f 3 1 1 0 0 22116]Oh, look―dwarves! They're kinda cute![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 99 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 3 1 6 0 0 500]Wait―Panther! Don't go near them![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Eh?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 10 0 1][f 3 1 1 0 0 22059][f 6 1 2 0 0 10]...Aaaah![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 1 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Look out![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 22 1 0 1][f 4 6 23 6 0 3][f 3 1 1 0 0 23109][f 6 1 2 0 0 4]Whew! That was close. Are you all right,[n]Panther?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Y-Yeah... Thanks, Mona. You saved[n]my butt back there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 0][f 3 1 1 0 0 0][f 6 1 1 0 0 1][f 6 1 2 0 0 0]Meow!? Th-Th-That was nya-thing![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 8 0 0][f 3 1 1 0 0 23032]For you, Panther, I'd brave fire and ice...[n]Wind and waves... Dwarves with guns![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 1][f 3 1 1 0 0 10047]Ooh, bravo, Mona! I'm surprised you[n]could move that fast. I guess it's thanks[n]to the power of love?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It must've been scary to end up in[n]the crosshairs so suddenly.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 28 0 0 1][f 3 1 1 0 0 28075]From what we've witnessed, they seem[n]to [f 0 1 2]point their guns at anything standing[n]before them[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]We won't be able to avoid a fight if they[n]lock onto us... Be careful around those[n]guys, Joker.[n][f 1 3 65535][f 1 1][e]

