[msg MSG_000 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 18002][f 6 1 2 0 0 4]Hey―ain't that glowing part of the floor[n]one of those switches?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 3][f 3 1 1 0 0 0]Hmm. That should mean there's a wind[n]generator nearby...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]But there doesn't seem to be anything[n]we can do about it from here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 4 1 1][f 3 1 1 0 0 0]Actually, I think there might be a way:[n]look just beyond it.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23075][f 6 1 2 0 0 4]One of those copyca―mimicking FOEs,[n]huh? I see... Get what he means, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3]...Nope.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]We'll get that thing to activate it.[f 2 7 1 20 2 32][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 23009]We want to get over there, but we can't,[n]because there's no wind blowing―right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23049]Nice―quick on the take, as always.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Uh, I kinda don't get it at all, eheheh...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]We want to get over there, but we can't,[n]because there's no wind blowing―right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ken]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 16 6 0 3][f 3 1 1 0 0 16068][f 6 1 2 0 0 3]Yeah. We don't have a way to reach[n]the switch that we need to activate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]And that's why we're going to have[n]the FOE activate it for us. It copies[n]our movement, right?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]So why not take advantage of its[n]behavior and [f 0 1 2]have the FOE move[n]onto that switch[f 0 1 0]?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Oh, I get it! Then the wind that we need[n]will start blowing![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3][f 4 6 8 2 0 1][f 3 1 1 0 0 8076]If this works as we've planned, we[n]should be able to ride the wind to[n]the other side.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]There doesn't seem to be any alternative[n]solution, so let's give this a try.[n][f 1 3 65535][f 1 1][e]

