[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 1][f 3 1 1 0 0 54039]斡Ha llegado el momento![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 10 0 0][f 3 1 1 0 0 0]夷Para qu姻?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 0][f 3 1 1 0 0 0]Desde que llegaste a este mundo, has[n]enfrentado una lucha ardua tras otra...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Con lo lejos que has llegado, creo que[n]ahora puedes ser lo suficientemente[n]fuerte para superar este nuevo desaf胤o...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 100 0][f 3 1 1 0 0 0]斡No hablo de ninguna otra que la[n]pr吋xima proyecci吋n especial![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Esta vez, se le encargar茨 de entrar en[n]la ciudad de Kamo y derrotar al pollo FOE![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 1 0][f 3 1 1 0 0 22019][f 6 1 2 0 0 4]夷Te refieres a ese cretino sosteniendo[n]la pierna de pollo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 0]Eso es correcto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 0 0 0][f 3 1 1 0 0 0]Hah. Esto deber胤a ser f茨cil. 斡Ya hemos[n]ganado a su tipo antes![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ser茨 un negocio como siempre, pero con[n]una recompensa mayor. Eso me suena muy bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 68 1 0 1][f 4 6 23 0 3 6][f 3 1 1 0 0 23004]Al principio, no ten胤amos otra opci吋n[n]que huir... pero hemos crecido mucho m茨s[n]fuerte desde entonces.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Probablemente podemos manejarlo ahora,[n]夷no crees? Vamos a intentarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 0][f 3 1 1 0 0 0]Tambi姻n quisiera participar en esta[n]prueba especial.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]He estado interesado en su arma por un[n]tiempo. Una forma tan intrigante... Es[n]casi como una losa de carne.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 65 10 0 0][f 3 1 1 0 0 21116][f 6 1 2 0 0 6]斡Acabo de recordar![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Sab胤a que hab胤a visto un enorme trozo[n]de carne en alg雨n lugar! As胤 que ah胤 es[n]donde estaba...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 1 4][f 3 1 1 0 0 4045]夷Un mont吋n de carne?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Muy bien, vamos a sacarlos! 斡Ese pollo es m胤o![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 0]Arte comestible, 夷eh? Lo espero.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0]... Parece que 姻l y Chie[n]planean comerlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]S胤... Ciertamente parecer胤a as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 68 1 0 0][f 4 6 72 12 0 0][f 3 1 1 0 0 28110]Espera un minuto. Puede parecer carne a[n]primera vista, pero no hay garant胤a de[n]que sea comestible...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Comer es creer! 斡Nunca lo sabremos a[n]menos que lo intentemos![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 1 0][f 3 1 1 0 0 0]De acuerdo. No puedo suprimir mi pasi吋n[n]por el arte ni mi pasi吋n por la comida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 7 13 0 0][f 4 6 64 1 0 3][f 4 6 23 6 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Vaya, parece que est茨n muertos comiendo[n]esa cosa... Quiz茨s deber胤as decir algo.[n][f 1 3 65535][f 1 1][e]

[sel SEL_017 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]Derrotar el FOE viene primero.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]斡Es un buffet de carne![f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Golp姻ense.[f 2 7 1 64 0 32][e]

[msg MSG_018 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 4074][f 6 1 2 0 0 6]斡Bien, bien, bien! 斡Y luego tenemos la carne![n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 14 1 0][f 3 1 1 0 0 23035][f 6 1 2 0 0 0]夷Qu姻? 夷Tambi姻n est茨s en esto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Un buffet! 斡Me gusta el sonido de eso![n]斡Apres雨rense y ag茨rrenlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 6 0 0][f 4 6 68 2 0 0][f 3 1 1 0 0 24067]Muy bien, haremos lo que nos plazca.[n]Sugiero que traigamos algunos contenedores[n]para la carne.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Oh! 斡Yo tambi姻n![n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 3 6 0 3][f 3 1 1 0 0 0]T胤o, realmente est茨n listos para hacer esto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 3][f 3 1 1 0 0 0]Bueno, si es carne FOE que quieres,[n]supongo que deber胤a echar una mano.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 0 1][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0][f 6 1 2 0 4]Yosuke...[n]夷Tienes hambre tambi姻n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 3133]斡No lo comer姻![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]Es que... Bueno... Siento que es hora[n]de empezar a sacar mi propio peso de nuevo, 夷sabes?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Estuve separado de todos durante todo[n]ese tiempo, as胤 que no he tenido la[n]oportunidad de mostrar mis cosas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [P4 Hero]]
[f 0 5 65278][f 2 1][f 6 1 25 0 0 0][f 4 6 1 6 0 0][f 1 5][f 6 1 14 0 0 0][f 3 1 1 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 74 2 100 1][f 3 1 1 0 0 54031]*chuckle* apetitos monstruosos,[n]curiosidad persistente y otras motivaciones[n]complejas tambi姻n...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Aunque sus razones pueden diferir,[n]todos ustedes est茨n unidos en su[n]determinaci吋n de ver esto a trav姻s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Sin embargo, recuerde que se enfrentar茨[n]a un FOE... Le pido que permanezca[n]vigilante hasta el final.[n][f 1 3 65535][f 1 1][e]

