[msg MSG_000 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 1][f 3 1 1 0 0 3002]Tenemos dos puntos m茨s de warp aqu胤. 夷Qu姻 tomamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 6 1 2 0 0 5][f 3 1 1 0 0 0]斡Lo tengo! 斡Es el de la izquierda![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Pareces seguro, Panther. 夷Has averiguado la pista?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 3 1 1 0 0 22032]斡No! Tengo una corazonada, eso es todo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]En realidad, acabo de recordar que vi[n]en la televisi吋n que Escorpio era la[n]se隠al m茨s afortunada para hoy.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 2 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Y el color de Scorpio era azul. As胤 que[n]el punto de warp azul es[n]definitivamente la manera de ir![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 3][f 3 1 1 0 0 22057][f 3 1 1 0 0 0]O no.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 3][f 3 1 1 0 0 0]Eheh... Supongo que es un poco d姻bil.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]夷Cu茨l crees que es correcto, Aragaki-kun?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 3][f 3 1 1 0 0 18019]夷Eh? 夷C吋mo diablos deber胤a saberlo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 0]Haha... No hay raz吋n en particular.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Joker hace la 雨ltima llamada de todos[n]modos. Supongo que solo quer胤a tu opini吋n[n]para referencia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 3][f 3 1 1 0 0 18096]...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 3][f 3 1 1 0 0 0]Ni idea.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Por todo lo que sabemos, ambos est茨n equivocados.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 1][f 3 1 1 0 0 28068]Hahaha, lo suficiente...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si nos equivocamos, espero que tengamos[n]la oportunidad de volver y tomar la[n]decisi吋n correcta.[n][f 1 3 65535][f 1 1][e]

