[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 74 0 5 1][f 3 1 1 0 0 54099]La proyecci吋n especial esta vez es una[n]exploraci吋n de A.I.G.I.S.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Esta vez, el suelo designado es[n]absolutamente lleno de tesoros![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 0][f 3 1 1 0 0 0]Y as胤, tu gloriosa misi吋n esta vez es[n]reunir todo el rid胤culo que puedas encontrar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Hehehehehe... Tesoro, 夷eh? 斡Tienes mi atenci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 0 0 0][f 3 1 1 0 0 0]No te emociones demasiado, maldito[n]gato. Tenemos que atacar a Treasure Spots, 夷verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54073]Por desgracia, no ser茨 tan f茨cil.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 0]Junto con estos nuevos Puntos de[n]Tesoro, tambi姻n hay nuevos puntos de Warping.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 6 2 1][f 3 1 1 0 0 0]Encontrar茨s el tesoro pasado estas[n]nuevas zonas warp.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]夷Las zonas de Warp nos van a tirar por[n]todas partes? Eso va a arruinar mi[n]Perspectiva Ace...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 3]斡Maldita sea! Ser胤a mucho m茨s sencillo[n]si pudi姻ramos golpear a un monstruo duro[n]y conseguir los bienes.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006 top]
[f 0 5 65278][f 2 1][f 4 7 3 0 0][f 4 6 64 1 0 0]Deja de quejarte.[f 2 7 1 64 6 32][e]
[f 0 5 65278][f 2 1]No bromees.[f 2 7 1 64 2 32][e]

[msg MSG_007 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 65 1 0 0][f 4 6 71 2 0 1][f 3 1 1 0 0 27031]Debo decir que estoy de acuerdo. Estas[n]proyecciones tambi姻n tienen su propio encanto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ciertamente, las pel胤culas de acci吋n[n]llamativas son emocionantes, pero no[n]cuando todos son un p雨blico pueden ver.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 65 1 0 0][f 4 6 71 12 0 1][f 3 1 1 0 0 27004]夷Oh? 夷No es tu tipo de pel胤cula? Creo[n]que estos tienen cierto encanto.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ciertamente, las pel胤culas de acci吋n[n]llamativas son emocionantes, pero no[n]cuando todos son un p雨blico pueden ver.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 8 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]夷Eh? Espera, 夷qu姻 p雨blico?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 65 1 0 0][f 4 6 13 2 0 1][f 3 1 1 0 0 13071]Hah. Un punto justo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cualquier pel胤cula puede ser[n]magn胤fica... Todos los actores de primera clase[n]saben que esto es verdad.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 0][f 3 1 1 0 0 0]夷Eh? Bueno, yo soy un actor de primera[n]clase. 斡Podr胤a haberte dicho eso![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Entonces vamos a intentarlo! 斡Las[n]estrellas no pueden elegir sus trabajos![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 0][f 3 1 1 0 0 21092]De acuerdo, de acuerdo, vamos a[n]conseguir este show en el camino.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Tiene que haber Sombras ah胤 fuera, as胤[n]que vamos a patear sus culos, conseguir[n]el bot胤n, y hacernos nuevas armas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 11 1 0 0][f 4 6 65 1 0 0][f 4 6 71 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]斡Sab胤a que vendr胤as! 斡Vamos a usar esta[n]oportunidad para hacernos m茨s poderosos![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 0]Tener protectores como t雨 hace mucho[n]para aliviar nuestras mentes. Ahora[n]podemos reunir tesoros en paz.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 0]Contamos con ustedes dos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11067][f 6 1 2 0 0 6]斡Lo tienes![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 0][f 3 1 1 0 0 0]Haha... Bueno, nos hizo bien. Supongo[n]que no podemos ganar, 夷eh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 18 2 0 1][f 3 1 1 0 0 18133]Dios. Es como si estuvieran lavados de[n]cerebro. A雨n as胤, admiro que...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Heh. Bueno, si vas a ser un l胤der, tal[n]vez puedas aprender una o dos cosas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 71 1 0 4][f 4 6 13 12 0 1][f 3 1 1 0 0 0]El dise隠o del piso probablemente va a[n]cambiar... Tendremos que investigar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 0][f 3 1 1 0 0 27122]Entonces una vez que estemos listos,[n]vamos a empezar. 斡Con suerte encontraremos[n]algo que valga la pena![n][f 1 3 65535][f 1 1][e]

