[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3][f 4 6 19 1 0 6][f 4 6 74 0 100 1][f 3 1 1 0 0 0]Incluso Sombras de tremendo poder no[n]son m茨s que juego de ni隠os para ti.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54026]Todos ustedes han crecido[n]admirablemente desde su llegada aqu胤. Tu nuevo poder[n]es realmente notable.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 1][f 3 1 1 0 0 0]Eres incre胤ble...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Te he estado observando, as胤 que puedo[n]decirlo. Todos ustedes se han vuelto m茨s[n]fuertes y m茨s fuertes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 6][f 1 5][f 6 1 28 0 0 0]斡S胤, me sorprend胤![n][f 1 3 65535][f 1 1][e]

[msg MSG_002_1 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 28 0 0 0][f 3 1 1 0 0 19030]Pero todav胤a...[n]Estoy luchando por todos, no solo por m胤[n]mismo. Creo que es la 雨nica raz吋n por la[n]que llegu姻 tan lejos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 0]Cada uno de ustedes trabaja para[n]perfeccionar su capacidad, y las reuniones[n]fat胤dicas dan a luz m茨s poder.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Siento que he aprendido algo vitalmente[n]importante al ver tus haza隠as en la[n]pantalla de plata...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 2 0][f 3 1 1 0 0 0]Aunque no sea mi lugar, me gustar胤a[n]darle las gracias una vez m茨s.[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 3]Es tu turno despu姻s.[f 2 7 1 64 12 0][e]
[f 0 5 65278][f 2 1]A雨n no hemos terminado.[f 2 7 1 64 12 0][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 54059]S胤, lo entiendo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]Las posibilidades ilimitadas est茨n[n]ocultas dentro de esa pel胤cula oscura...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Siento que la hora se acerca. Pronto[n]veremos todos sus secretos desnudos.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 0 100 0][f 3 1 1 0 0 0]Pero por ahora... no hay nada m茨s que pueda decir.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_2 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]En cualquier caso, por favor venga a[n]hablar conmigo una vez que est姻 preparado.[n][f 1 3 65535][f 1 1][e]

