[msg MSG_000 [Ann]]
What could this be?

[msg MSG_001 [Futaba]]
Hmm... I can't get a good reading from[n]where I am. Ergo, no idea! It's a[n]mystery.

[msg MSG_002 [Ryuji]]
Hey, animal noses are useful for this[n]kind of stuff―Mona, can't you tell what[n]it is by smelling it?

[msg MSG_003 [Morgana]]
I―AM―A―HUMAN! Not some... police dog!
...Even still, it does have a pretty[n]shine to it. It reminds me of a[n]Treasure.

[msg MSG_004 [Akechi]]
A Treasure, hm...? Then, for our own[n]convenience, why don't we call this a[n]"Treasure Spot"?
It's possible that they provide highly[n]lucrative goods.

[msg MSG_005 [Ryuji]]
Sounds good to me. That'll make it easy[n]to understand, for all of us.

[msg MSG_006 [Yusuke]]
So, that shine disappears once you[n]gather things from it...
Such transience has a pleasing quality[n]to it.

[msg MSG_007 [Ann]]
...Anyway, we should check places that[n]have a shining light. Keep your eyes[n]peeled, Joker!

