[msg MSG_000 [Ann]]
*sigh* That was exhausting! How much[n]surveillance do they really need!?

[msg MSG_001 [Yusuke]]
You have a point―they should be[n]conserving electricity. Such utility[n]costs should never be taken lightly.
In fact, the fear I felt when I saw last[n]month's electric bill... Ngh!

[msg MSG_002 [Morgana]]
Uh, that has nothing to do with this...

[msg MSG_003 [Yusuke]]
Then again, evading the searchlights was[n]indeed fun. It's one of the pleasures of[n]being a phantom thief.

[msg MSG_004 [Morgana]]
It worked out since we managed to slip[n]past them, but who knows what could have[n]happened if we got busted...

[msg MSG_005 [Futaba]]
Well, good job, folks.
By the way, I took a look around and it[n]seems there aren't any more[n]searchlights!
...In this area, at least.

[msg MSG_006 [Ryuji]]
Ack... That means there's more in the[n]next area...

[msg MSG_007 [Futaba]]
This is for Queen and Noir's sakes,[n]Skull! Show some guts!

[msg MSG_008 [Ryuji]]
Okay, okay! C'mon then, let's get[n]ourselves psyched up and keep on moving!

