[msg MSG_000 [Ryuji]]
Whoa―the hell is that!? It's huge!

[msg MSG_001 [Akechi]]
It seems to be a type of FOE, different[n]from what we've previously seen...
It doesn't seem to be on any sort of[n]patrol, but that doesn't mean it's not[n]dangerous.

[msg MSG_002 [Morgana]]
It even has more searchlights around[n]it...

[msg MSG_002_5 [Morgana]]
We'd better take extra care around that[n]thing―make sure you proceed carefully,[n]Joker!

