[msg MSG_000 [Akechi]]
Hold on―it seems our inventory is full[n]at the moment.
Even if we were to find something, we[n]wouldn't be able to carry it. Ought we[n]sort through what we have first?

[msg MSG_001 [Morgana]]
Hmm... There's no mistake that[n]something's here, though.
Let's head back to the theater and go[n]through our belongings, or check here[n]again when we have space to spare.

