[msg MSG_000 [Futaba]]
Joker! I'm sensing enemies down those[n]stairs.
If you're gonna head down, it's probably[n]best if you do it when you're as[n]prepared as possible.

[msg MSG_001 [Ryuji]]
So what's your call, Joker? Are we doing[n]this?

[msg MSG_002 [Ryuji]]
Oh, right―there are enemies past here![n]Are we good to go now, Joker?

[sel SEL_003 top]
Let's head on down.
Give me a minute to get ready.

[msg MSG_004 [Ryuji]]
Yes! Time to give 'em hell.

[msg MSG_005 [Ryuji]]
Gotcha, we'll leave when to go up to[n]you. I guess I should stretch again,[n]too...

