[msg MSG_000 [Futaba]]
Our target destination is up ahead.
There are tons more searchlights[n]compared to the previous areas... And,[n]I'm even sensing FOEs further in.

[msg MSG_001 [Ryuji]]
So we gotta avoid those huge FOEs, all[n]while dodgin' the searchlights...
Well, I think we should leave the orders[n]up to Joker, as usual... We're relying[n]on you to get us through this.

[msg MSG_002 [Morgana]]
We can't afford to mess this up. Let's[n]proceed even more cautiously through[n]here.

