[msg MSG_000 [Ryuji]]
Ooh, what's this?

[msg MSG_001 [Akechi]]
It appears to be a switch of some[n]sort...
What say you, Joker? Should we try[n]pressing it?

[sel SEL_002 top]
Let's go for it.
Let's not.
Do what you want.

[msg MSG_003 [Ryuji]]
Alright! Don't mind if I do...

[msg MSG_004 [Ann]]
H-Hey! Are you sure that's safe? What if[n]it turns out to be a trap?

[msg MSG_005 [Yusuke]]
True. Why not have Oracle look into it?

[msg MSG_006 [Ann]]
Yeah―it'd be bad if we learned the hard[n]way that this is a trap...

[msg MSG_007 [Yusuke]]
If anything, we should have Oracle look[n]into it first.

[msg MSG_008 [Ryuji]]
For real!? Then, let's try pressin' it!

[msg MSG_009 [Ann]]
H-Hey! What if it turns out to be a[n]trap?

[msg MSG_010 [Yusuke]]
True. Why not have Oracle look into it?

[msg MSG_011 [Futaba]]
Yep yep, leave it to me...

[msg MSG_012 [Futaba]]
Hm―what's this?
Hey, guys! That switch is connected to[n]the searchlights!
If you turn off the power, we'll be good[n]to go. Joker, try it!

[msg MSG_013 [Ryuji]]
Aha! We did it―the searchlights are off!

[msg MSG_014 [Akechi]]
Well that was a useful function. If we[n]find another one of these, we'll likely[n]want to check it out.

[msg MSG_015 [Futaba]]
Hm―what's this?
Hey, guys! That switch is connected to[n]the searchlights!

[msg MSG_016 [Ryuji]]
For real!? Lucky us!

[msg MSG_017 [Futaba]]
If you turn off the power, we'll be good[n]to go. Make sure you try any others that[n]we find later.

