[msg MSG_000 [Futaba]]
Joker! I'm getting a Shadow reading from[n]beyond that door.
I think you'll probably have to fight[n]it... Are you ready for that?

[sel SEL_001 top]
We're good to go.
I need a moment.

[msg MSG_002 [Ryuji]]
Alright! Let's roll!

[msg MSG_003 [Yusuke]]
Mm, returning to the movie theater and[n]regrouping is also a wise tactic.
Let's proceed onward once we're ready to[n]go.

