[msg MSG_000 [Haru]]
Queen, about that battle a moment ago...

[msg MSG_001 [Makoto]]
......

[msg MSG_002 [Haru]]
Queen?

[msg MSG_003 [Makoto]]
Huh? Oh, Noir―what is it?

[msg MSG_004 [Haru]]
Oh no, it's nothing serious.

[msg MSG_004_5 [Haru]]
Is something on your mind?

[msg MSG_005 [Makoto]]
Well, I was just recalling when we were[n]both captured.
It's times like these that I really need[n]to get my act together...

[msg MSG_006 [Haru]]
I see. You sure are responsible, Queen.

[msg MSG_007 [Makoto]]
No, this isn't responsibility―it's only[n]because I'm ashamed of myself for[n]getting captured like that.
Oh―Sorry, that sounded harsh. I don't[n]feel the same about your capture, I'm[n]just, um...

[msg MSG_008 [Haru]]
Don't worry, I understand―plus, I feel[n]the same way.
So, don't try taking on all of these[n]burdens yourself, okay? We're friends,[n]so we help each other with problems.

[msg MSG_009 [Makoto]]
Yes, thank you.
It's time for us to push ourselves to[n]even greater heights so we can redeem[n]ourselves!

[msg MSG_010 [Haru]]
Yeah! If only we could figure out[n]something in particular we could do...

[msg MSG_011 [Futaba]]
Heeey, guys! I've got some pipin' hot[n]intel for ya!

[msg MSG_012 [Morgana]]
What's up?

[msg MSG_013 [Futaba]]
I don't know the whole story, but[n]apparently, the ticket machine in the[n]theater suddenly lit up!
Looks like Zabby wants to give us a[n]spiel about it.
Stop by the box office when you guys get[n]back―don't forget, now!

