[msg MSG_000 [Yosukesaurus]]
Ah, here―this is it! See? There's a[n]thing sticking out of the box here...
All you've gotta do is pull that.

[msg MSG_001 [Ann]]
Nice! Well, why don't we give it a shot?

[msg MSG_002 [Ann]]
We just need to pull this switch, right?[n]What's your call, Joker? Should we try[n]it?

[sel SEL_003 top]
Why not?
Let's not.

[msg MSG_004 [Kanji]]
Huh? Nothin's happening.

[msg MSG_005 [Morgana]]
Well, duh. We need to go back to that[n]gate―
Hm? A number...
Wha―It's a countdown!?

[msg MSG_006 [Kanji]]
Shit!? I-I-Is it gonna explode!?

[msg MSG_007 [Chie]]
What!? Nobody told me anything about an[n]explosion!

[msg MSG_008 [Naoto]]
Please, calm down. Take a look at the[n]display...
This most likely shows us the amount of[n]time remaining before the electric[n]current in the gate is reactivated.

[msg MSG_009 [Akechi]]
Basically, we need to get past the gate[n]before the countdown hits zero.

[msg MSG_010 [Kanji]]
Oh, what the―You scared the shit outta[n]me!

[msg MSG_011 [Naoto]]
This is likely where the humans here[n]would lure the carnivores...
If so, they would have designed the[n]device to be used repeatedly.

[msg MSG_012 [Akechi]]
That's a good point. If the timer runs[n]out on us, we can simply reactivate it[n]with this control box.
There's no need to worry. Everything[n]will go smoothly if we keep our wits[n]about us.

[msg MSG_013 [Ryuji]]
Ah, you wanna poke around a little more,[n]then?

