[msg MSG_000 [P4 Protag]]
Hey, is it me, or is Teddie missing?

[sel SEL_001 top]
Did he get lost?
Did he run away?

[msg MSG_002 [Chie]]
Haha, are you trying to pull our leg or[n]something? There's no way―
Wait, you're right. Where is he!?

[msg MSG_003 [Haru]]
I noticed that it had grown rather quiet[n]earlier... Teddie being missing would[n]explain that.

[msg MSG_004 [Yosuke]]
Sheesh, that idiot! Where'd he―

[msg MSG_005 [Yosuke]]
There he is!
What're you doing over there!? You had[n]us all worried!

[msg MSG_006 [Teddie]]
Hrm? Why are you yelling, Yosuke? Is[n]something wrong?

[msg MSG_007 [Yosuke]]
...Uhhh, why are you rubbing up against[n]that container like that?

[msg MSG_008 [Teddie]]
This world is so hot... I felt like I[n]was about to start melting away!
Just then, I found this refreshingly[n]chilly and comfortable box. Ahhh, this[n]is truly heaven...

[msg MSG_009 [Akechi]]
Is that some sort of freezer storage[n]unit that Teddie is... sprawled upon?

[msg MSG_010 [P4 Hero]]
I never would've imagined we'd find[n]something like this out here.

[msg MSG_011 [Akechi]]
The cool air seeping out must feel nice.[n]I can only imagine how tough it is[n]wearing a costume in this heat...

[msg MSG_012 [Teddie]]
That long nose of yours looks pretty[n]heated to me, Crow. Wanna hop up here[n]next to me?

[msg MSG_013 [Akechi]]
U-Um... My outfit has better ventilation[n]than it appears. I'll pass this time.

[msg MSG_014 [Yukiko]]
If you're so hot, how about I incinerate[n]you, Teddie?
You know how the old saying goes...[n]Clear your mind of all mundane thoughts[n]and you'll find even fire cool.

[msg MSG_015 [Teddie]]
Nooooo! Please don't make any roast[n]bear!

[msg MSG_016 [Chie]]
Oh, would you stop!? We need to keep[n]moving here!

