[msg MSG_000 [Rise]]
Guys, just a sec! I'm sensing a presence[n]beyond that door... It's different from[n]anything we've encountered so far.
どゎれろ ろよ ほま れゎるま をよゎ'るま るまぺぽを みよる ぺょをろめもょむ ろめぺろ[n]ぼよゎゅぽ めぺららまょデ をよゎ ゆもむめろ ゐぺょろ ろよ ぼめまぼや もみ[n]をよゎ'るま みゎゅゅを らるまらぺるまぽテテテ

[msg MSG_001 [Chie]]
So there's a mystery presence past that[n]door? That's so scary... Do we really[n]have to go that way?

[sel SEL_002 top]
Let's go.
......

[msg MSG_003 [Chie]]
F-Fine, then, uh... You can lead the[n]way, Joker! After you, eheheh...

[msg MSG_004 [Akechi]]
Did you hear that, Joker? You've been[n]called upon for the task.
You won't let the lady down, will you?[n]We'll all be right behind you.

[msg MSG_005 [Akechi]]
Caution is a vital survival skill. If[n]you're uncertain of our success, let's[n]prepare ourselves before entering.

