[msg MSG_000 [Ryuji]]
Hey, shouldn't we use a different symbol[n]for the electric gates instead of just[n]reusing the one for the rotating cages?

[sel SEL_001 top]
That's a good point.
Let's ask Fox to design one for us.

[msg MSG_002 [Yusuke]]
Hm, in that case... How about something[n]like this?

[msg MSG_003 [Haru]]
That's fantastic! It ought to make our[n]map even easier to read!

[msg MSG_ICON_DENKISAKU_OPEN]
An [f 0 1 2]Electric Gate[f 0 1 0] icon has been added to[n]the map on the bottom screen.
If you wish to review how to use this[n]icon again...
Press [f 0 1 2]HELP[f 0 1 0] at the bottom right of the[n]map and check the [f 0 1 2]Icon Types[f 0 1 0].

