[msg MSG_000 [Fuuka]]
I-I'm sorry, but... I don't know where[n]to go next.
I mean, there is a path, but it has a[n]locked door, so it won't do you any[n]good...

[msg MSG_001 [Aigis]]
Then, shall I decimate this wall?

[sel SEL_002 top]
It's all yours.
Please―don't.

[msg MSG_003 [Ann]]
Huh? Wait, decim―Stop, stop!
No, no, definitely no! It'd be super bad[n]if this place exploded, right!?

[msg MSG_004 [Ann]]
You heard him! It'd be super bad if this[n]place exploded, right!?

[msg MSG_005 [Ribbon]]
IT WOULD BE ESPECIALLY DANGEROUS SINCE[n]ELECTRICAL CONDUITS RUN THROUGH THESE[n]WALLS.

[msg MSG_006 [P3 Hero]]
Aigis, go easy on them―they can't tell[n]you're kidding.

[msg MSG_007 [Aigis]]
Yes, it seems that is the case. I[n]apologize...

[msg MSG_008 [Futaba]]
Wh-Whoa, she's got jokes!? Talk about[n]being high-specced! Daaaamn...
But, in all honesty... My blood totally[n]ran cold for a second there.

[msg MSG_009 [Ribbon]]
A... JOKE? A ROBOT... MADE A JOKE.

[msg MSG_009_5 [Ribbon]]
YOU ARE VERY DIFFERENT FROM NORMAL[n]ROBOTS, AIGIS-SAN... WHY IS THAT?
IS IT BECAUSE YOU WERE NOT CREATED IN[n]THIS WORLD, AS I WAS?

[msg MSG_010 [Aigis]]
I currently know very little about what[n]comprises a "normal" robot... However,[n]no matter where I am, I am myself.
Does this not describe yourself as well,[n]Ribbon-san?

[msg MSG_011 [Ribbon]]
HOW SO?

[msg MSG_012 [Aigis]]
I was told that you came with us because[n]you wanted to learn about the emotions[n]you have attained.
That feeling was born from within you.[n]It is your own.

[msg MSG_013 [Ribbon]]
I HAD... MY OWN FEELING...

[msg MSG_014 [Mitsuru]]
Well, let's wrap this conversation up[n]for now and resume our exploration.

[msg MSG_014_5 [Mitsuru]]
While there may be no clear path for us[n]to take, there must be a hidden passage[n]somewhere. Let's try looking for one.

