[msg MSG_000 [Yukiko]]
Hey, what do you think that is?

[msg MSG_001 [Chie]]
It looks like some kind of machine,[n]but... Uhh, I have no idea.

[msg MSG_002 [Futaba]]
Hrmmm... I can't really tell from here.

[msg MSG_003 [Yukari]]
We might be able to get closer to it if[n]we find a different path. Why don't we[n]try to find one?

[msg MSG_004 [Futaba]]
Good idea, Yukari! I swear there's[n]something to that thing... Hrghhh... My[n]curiosity's reached its level cap!

