[msg MSG_000 [Fuuka]]
I'm sensing a powerful presence ahead![n]Everyone, please be careful...

[msg MSG_001 [P3 Hero]]
That should be the central area where[n]the robots are controlled―the command[n]room of the Mother Computer.

[msg MSG_002 [Aigis]]
I believe the probability of engaging in[n]battle is extremely high.
Shall we enter immediately?

[msg MSG_003 [Aigis]]
I believe we will engage in a fierce[n]battle through here. Are we prepared to[n]go?

[sel SEL_004 top]
It's showtime!
Not yet.

[msg MSG_005 [Aigis]]
Understood. In we go!

[msg MSG_006 [Aigis]]
Understood. I shall be on standby.

