[msg MSG_000 [Teddie]]
Oh no, oh no, oh nooooo! I-Is this a[n]catastrophe!?

[msg MSG_001 [Ryuji]]
Obviously not!
...Hm? Guess it's stopped.

[msg MSG_002 [P4 Hero]]
Teddie, there's no knowing what might[n]happen in this world. Make sure you[n]don't touch anything carelessly, okay?

[msg MSG_003 [Teddie]]
I understand, Sensei... I'll think about[n]what I've done...

[msg MSG_004 [Ken]]
Oh―but look, everyone!

[msg MSG_005 [Akechi]]
...[f 0 1 2]The hole's been blocked[f 0 1 0]. This must be[n]the cause of that earthquake.

[msg MSG_006 [Shinjiro]]
This reminds me of those things they use[n]for puttin' on plays. What was it[n]called... [f 0 1 2]stage lift[f 0 1 0]?

[msg MSG_007 [Teddie]]
Whaaa―!? So, it's safe to say the[n]mystery was solved entirely thanks to[n]me?

[msg MSG_008 [Ryuji]]
Dude, what happened to thinkin' on what[n]you did?

[msg MSG_018 [Naoto]]
...Wait, what's that sound!?

