[msg MSG_000 [Morgana]]
Agh! This wind... It's too strong... I'm[n]gonna―
Mrowww!?

[msg MSG_001 [Teddie]]
Whaaaaaa!? Nooooooo! Heeeeelp!

[msg MSG_002 [Akechi]]
Huh!? Wait, wha―!

[msg MSG_003 [Rise]]
Oh no! Are you guys okay!?

[msg MSG_004 [Futaba]]
Whoa, the wind's so strong that they're[n]actually floating! Awww, Mona looks like[n]a tiny balloon...

[msg MSG_005 [Morgana]]
Don't call me a balloon! Sheesh... That[n]was not fun.

[msg MSG_006 [Yukiko]]
Looks like everyone's all right―wait,[n]where's Teddie?

[msg MSG_007 [Teddie]]
Phew-wee! What a close call! I'm glad I[n]clung onto Crow like this.

[sel SEL_008 top]
He's fine with it.
You two get along so well.
I'm getting jealous.

[msg MSG_009 [Akechi]]
Can you really... call this... "fine"!?

[msg MSG_010 [Akechi]]
O-Oh, you... really... think so!?

[msg MSG_011 [Akechi]]
Then... would you mind... trading[n]places!?

[msg MSG_012 [Mitsuru]]
To think the wind could be so strong as[n]to make us float... I suppose we're[n]lucky we didn't fall into that hole.
It seems we'll need to proceed with even[n]more caution from here on out.

[msg MSG_013 [Yosuke]]
Yeah, we're in Enlil's world―who knows[n]what's waiting for us ahead.
Stay on guard, everyone!

[msg MSG_014 [Morgana]]
Agh! Why's this wind... so... strong!?

[msg MSG_015 [Teddie]]
Whaaaaa!? My fur... My pride and joy is[n]getting all mussed!

[msg MSG_015_5 [Teddie]]
...Hrmm? I'm floating! But, how!?

[msg MSG_016 [Mitsuru]]
To think the wind could be so strong as[n]to make us float... I suppose we're[n]lucky we didn't fall into that hole.
It seems we'll need to proceed with even[n]more caution from here on out.

[msg MSG_017 [Yosuke]]
Yeah, we're in Enlil's world―who knows[n]what's waiting for us ahead.
Stay on guard, everyone!

