[msg MSG_000 [Rise]]
Hm? Hold on a sec...
There's not any wind blowing where you[n]are, but the reading I'm getting tells[n]me that there is. I wonder why?

[msg MSG_001 [P3 Hero]]
Is it possible that this film's blocking[n]it?

[msg MSG_002 [Fuuka]]
I think you're right. That film's acting[n]as a windbreaker right now.
That would mean you could end up blasted[n]away by the wind here if not for that[n]barrier...

[msg MSG_003 [Akechi]]
Film that shields us from the wind, eh?[n]It may be best for us to draw this on[n]the map, just in case.

[msg MSG_004 [Yusuke]]
Then I'll come up with a symbol for it.[n]Something along the lines of...

[msg MSG_ICON_BLOCKWALL_OPEN]
A [f 0 1 2]Wind Shield[f 0 1 0] icon has been added to the[n]map on the bottom screen.
If you wish to check how to use this[n]icon once more...
Press [f 0 1 2]HELP[f 0 1 0] at the bottom right of the[n]map and check the [f 0 1 2]Icon Types[f 0 1 0].

