[msg MSG_000 [Morgana]]
Meow!? I-It moved!?

[msg MSG_001 [Futaba]]
Whoa there, folks!
That thing's [f 0 1 2]copying your movement[f 0 1 0]!

[msg MSG_002 [Ryuji]]
Huh!? Whaddaya mean, "copy"? It's doin'[n]the opposite of us!

[msg MSG_003 [Akechi]]
Well actually, that's not true.
The point-of-view has been reversed, not[n]the direction. For example, if it faces[n]us, and we move to the right...

[msg MSG_004 [Teddie]]
Ohhh, I see―it'll look like it moved[n]left!

[msg MSG_005 [Ryuji]]
Huh? It's copying us!?
So, because we moved forward, that thing[n]did the same thing?

[msg MSG_006 [Akechi]]
So it seems. I believe if we were to[n]head right, it would also move to its[n]right, so...

[msg MSG_007 [Teddie]]
From our point of view, it'll look like[n]it moved left! I see, I see...

[msg MSG_008 [Chie]]
Uhhh...

[msg MSG_008_5 [Chie]]
I don't get all this "right means left"[n]stuff, but as long as we're careful,[n]we'll be fine... Right!?

[msg MSG_009 [Mitsuru]]
Indeed. All we must do is consider its[n]movement as we proceed onward. You have[n]the lead, Joker.

