[msg MSG_000 [Chie]]
Yikes, what's that? There's a big heap[n]of junk over there.

[msg MSG_001 [Naoto]]
Is that... all rubbish? That's quite a[n]lot.

[msg MSG_001_1 [Kanji]]
Ugh, who the hell left all this trash in[n]the middle of the road?

[msg MSG_001_2 [Makoto]]
Getting through that seems too risky. Is[n]there any way to get around it?

[msg MSG_002 [Akihiko]]
Should we just haul it all out of the[n]way? We could think of it as strength[n]training...

[msg MSG_003 [Shinjiro]]
There goes the muscle-brained idiot[n]again... Stay outta this. We're trying[n]to come up with a real solution here.

[msg MSG_004 [Aigis]]
Then, shall we destroy it?

[msg MSG_005 [Shinjiro]]
*sigh* You too?

[msg MSG_006 [Naoto]]
However, that may not be the worst idea.
It would be difficult with even our[n]combined strength to move this much[n]debris...

[msg MSG_007 [Akechi]]
You're right, we'd need some kind of[n]heavy machinery. Is there anything[n]nearby we can use?

[msg MSG_008 [Mitsuru]]
...I see nothing of the sort around[n]here. Oh well, let's search the area and[n]try to find another method.
Ah―and it'd be best to note this down on[n]the map for later, just in case.

[msg MSG_009 [Yusuke]]
Then I'll design a special symbol for[n]it. This heap of trash has inspired me!

[msg MSG_ICON_CLASH_BLOCK_OPE]
A [f 0 1 2]Debris[f 0 1 0] icon has been added to the map[n]on the bottom screen.
If you wish to check how to use this[n]icon once more...
Press [f 0 1 2]HELP[f 0 1 0] at the bottom right of the[n]map and check the [f 0 1 2]Icon Types[f 0 1 0].

