[msg MSG_000 [Mitsuru]]
It would seem we can't go any further.[n]We'll have to turn back.

[msg MSG_001 [Haru]]
Um... I've been wondering, but you're[n]the heiress to the Kirijo Group,[n]correct?

[msg MSG_002 [Mitsuru]]
Hm...? Yes, that may be the case in the[n]near future.
Although, I'm not sure how some of the[n]adults around me feel about the[n]matter...

[msg MSG_003 [Haru]]
About that... Does it ever weigh you[n]down? All of that business with the[n]company, I mean...

[msg MSG_004 [Mitsuru]]
That's right―you mentioned you're the[n]successor to a mega corporation as well.

[msg MSG_005 [Haru]]
Mhm. Lately, I can't help but think[n]about everything with my own company and[n]things of that nature...
And I began to wonder how you handle all[n]of it... I'm sorry to bring it up so[n]suddenly.

[msg MSG_006 [Mitsuru]]
No, it's all right.
Well, when it comes to my family... To[n]be honest, it does feel like a heavy[n]burden at times.
Especially when I think about the Kirijo[n]Group's future and the responsibilities[n]I hold as its sole heiress.

[msg MSG_007 [Haru]]
I thought so...

[msg MSG_008 [Mitsuru]]
However, recently, I've felt as though[n]my companions have helped me lift that[n]weight off my shoulders.

[msg MSG_009 [Haru]]
Your companions?

[msg MSG_010 [Mitsuru]]
When I'm with them, I realize there is[n]still much I've yet to learn.
Be it for better or worse, I've been[n]learning something new each day.
Not only is it a painful reminder of how[n]narrow sighted I had been...
But it's also helped me see that it's[n]important to be diverse in my thinking.[n]They've taught me a lot.

[msg MSG_011 [Haru]]
I think I can relate...
Had it not been for the Phantom Thieves,[n]I would've stayed a subservient puppet[n]forever...

[msg MSG_012 [Mitsuru]]
I see. Then, wouldn't you say you've[n]already found your answer?

[msg MSG_013 [Haru]]
Hm?

[msg MSG_014 [Mitsuru]]
If you feel you can't carry the burden[n]any longer, you can always try talking[n]with your companions.
I understand it's difficult to open up[n]on such matters...
But if you feel that you trust them with[n]all of your heart, then there's nothing[n]to fear.

[msg MSG_015 [Haru]]
*giggle* That's probably true. I'm sure[n]they'll say things I would have never[n]imagined.

[msg MSG_016 [Mitsuru]]
You should know, there's no need to find[n]a perfect answer.
Just go little by little, and do your[n]best to add to your accomplishments.
...I feel I've spoken too much. Did that[n]answer suffice?

[msg MSG_017 [Haru]]
Yes, it was very helpful! Thank you!
Oh, I know. I'm not sure if it'd be a[n]good way to thank you... but would you[n]allow me to treat you to coffee one day?

[msg MSG_018 [Mitsuru]]
Coffee? I do drink tea from time to[n]time, but I don't have much experience[n]with coffee.
I've heard there's much to learn. I'd be[n]honored to take you up on your offer.

[msg MSG_019 [Haru]]
Leave it to me! I have some delicious[n]coffee beans that were harvested after[n]being fermented in elephant dung!

[msg MSG_020 [Mitsuru]]
Wh-What...?
...No, it wouldn't do well to go in with[n]a prejudiced opinion. I'll be looking[n]forward to it.

