[msg MSG_000 [Chie]]
Aw, a dead end!?
Why's this place so complicated? All[n]these movie theaters are making me feel[n]like we're lost!

[msg MSG_001 [Yusuke]]
Even as we speak, those theaters are[n]filled with people watching negative[n]films...

[msg MSG_002 [Chie]]
Y'know, there's something I've been[n]wondering since we ended up in this[n]theater district...

[msg MSG_003 [Ryuji]]
What's that?

[msg MSG_004 [Chie]]
Considering how many theaters there[n]are... Do you think one of 'em could be[n]showing a kung fu flick?
And, if I went in that movie, would I be[n]able to pull off some kickass stunts!?

[msg MSG_005 [P4 Hero]]
Oh... I've actually wondered the same[n]thing.

[msg MSG_006 [Ann]]
You too!?

[msg MSG_007 [Kanji]]
So, do you think there's another movie[n]out there that's got a bunch of, uh...[n]fluffy, cute shit?

[msg MSG_008 [Shinjiro]]
Ooh―Uh, I mean, hmm, I wonder...

[msg MSG_009 [Junpei]]
Haha, busted! I can't believe THAT'S the[n]movie you wanna go inside!
とょ ゆを ぼぺれまデ と ゐぺょょぺ むよ もょ ぺ れらよるろれ ゆよわもま! と'ぽ[n]らゅぺを ろめま れゎらまる-むよよぽ-ゅよよやもょむ ゆぺゃよる ゅまぺむゎまる れよ と[n]ぼよゎゅぽ れめよゐ よみみ ゆを れやもゅゅれ!

[msg MSG_010 [Yusuke]]
In that case, I wish to enter a movie[n]overflowing with beautiful artwork and[n]delicious food.

[msg MSG_011 [Akechi]]
Haha, you're all so open with your[n]desires...
But, considering how the films work[n]here, even if we managed to find them, I[n]doubt we'd get what we want.

[msg MSG_012 [P3 Hero]]
While we're on the subject, what kind of[n]movie would you want to go inside, Crow?

[msg MSG_013 [Akechi]]
I think I'd want to go into a mystery.
As a Detective Prince, I'm interested in[n]solving difficult cases, even in a[n]movie... Don't you agree, Shirogane-san?

[msg MSG_014 [Naoto]]
Yes―I'm curious about the ruses and[n]schemes that could only occur in a film.

[msg MSG_015 [Yosuke]]
You'd be perfect as the star, Naoto. A[n]lady detective disguised as a man is[n]perfect for a story like that.
And then, you fall for a forbidden love―[n]the outlaw with a shocking past! How's[n]that float your boat?

[msg MSG_016 [Naoto]]
I... I'd never fall for someone like[n]that! I would arrest any and all[n]outlaws!

[msg MSG_017 [Hikari]]
*giggle* It'd be so fun to watch the[n]movies you all want to be in.
Even if it's not made into a wild genre[n]flick, I think turning everyday life[n]into a movie would be interesting too.
Just watching people live their lives to[n]the fullest can be really encouraging.

[msg MSG_018 [Junpei]]
Oh man, you hit the nail on the head,[n]Hikari-chan!
I've really gotta step my game up even[n]further to strike Hikari-chan's heart as[n]a major leaguer!

[msg MSG_019 [Futaba]]
C'mon, everybody―let's keep this energy[n]up as we get moving!

[msg MSG_020 [Hikari]]
Yeah!

