[msg MSG_000 [Ryuji]]
I don't need to keep my personality[f 0 1 1]
Ugh, dammit! I can't get that trailer's[n]song outta my head!
And those shitty-ass lyrics are makin'[n]me even more depressed...

[msg MSG_001 [Teddie]]
Then, let's fight against it and sing[n]lots of cheerful, happy songs!

[msg MSG_002 [Junpei]]
Count me in! I'll go first!

[msg MSG_003 [Yukari]]
No.

[msg MSG_004 [Junpei]]
Aw, can't I sing just a little!?

[msg MSG_005 [Yukari]]
Not unless you want to make our ears[n]bleed.

[msg MSG_006 [Junpei]]
Dude, do you have to be so harsh!?

[msg MSG_007 [Yosuke]]
Well then, why don't I do a medley of my[n]stuff?

[msg MSG_008 [Chie]]
Uh, we'd obviously rather hear[n]Rise-chan, Yosuke.

[msg MSG_009 [Futaba]]
Ooh, that'd be great! I'd love to hear[n]Risette sing live!
How often do we get to hear an idol sing[n]for just us!?

[msg MSG_010 [Rise]]
*giggle* If it'll cheer everyone up, I'd[n]be happy to.

[msg MSG_010_1 [Rise]]
But we can't let our guard down while[n]exploring, so maybe I'll save it for[n]when we all get back, okay?

[msg MSG_011 [Ryuji]]
For real!?

[msg MSG_011_1 [Ryuji]]
Hell yeah! I'm so stoked! C'mon, let's[n]hurry!

[msg MSG_012 [Yusuke]]
Skull's completely wrapped around her[n]finger.

[msg MSG_013 [P4 Hero]]
That's our Rise. She really knows how to[n]handle her fans.

