[msg MSG_000 [Morgana]]
A dead end, hm? *sigh* I'm getting tired[n]of seeing Kamoshidaman everywhere...

[msg MSG_001 [Ryuji]]
No kidding, it's bummin' me out... You[n]see those signs on the way here?
All of 'em were praisin' him. Creepy as[n]hell...

[msg MSG_002 [Ann]]
Sheesh, why'd you have to bring that up?[n]I've been trying not to look at them.

[msg MSG_003 [Ryuji]]
What!? They're all over the friggin'[n]city... Can't help but think of[n]Kamoshida's Palace.

[msg MSG_004 [Ann]]
I know. Why don't we make 'em disappear?

[msg MSG_005 [Morgana]]
How do we do that?

[msg MSG_006 [Ann]]
We burn every last one of 'em!

[msg MSG_006_1 [Ann]]
Dance, Carmen!

[msg MSG_007 [Ryuji]]
Ooh, great idea! Lemme help!

[msg MSG_007_1 [Ryuji]]
Blast away, Captain―

[msg MSG_008 [Morgana]]
Hey! What are you doing!?

[sel SEL_009 top]
Settle down.
Let me help out too.

[msg MSG_010 [Akechi]]
Joker's right. We don't want to draw any[n]attention to ourselves.

[msg MSG_011 [Akechi]]
You too, Joker...? Easy now. We don't[n]want to draw any attention to ourselves.

[msg MSG_012 [Morgana]]
I know that a lot happened between you[n]and Kamoshida...
And I'm sure it's not easy to forget[n]what he did either, but the one here[n]isn't real.

[msg MSG_013 [Ann]]
Mm, I'm sorry... Thinking about it just[n]makes me so irritated. I gotta calm[n]down.

[msg MSG_014 [Ryuji]]
Yeah, sorry... Rescuin' Queen and Noir's[n]more important right now.

[msg MSG_015 [Futaba]]
That's right! C'mon, let's keep going!

