[msg MSG_000 [Caroline]]
Looks like you actually brought us[n]something useful for once, Inmate!
Hand it over!

[msg MSG_001]
Handed over [f 4 4 3 0 1602]...

[msg MSG_002 [Justine]]
Hmm... How intriguing...
This may help us to improve the[n]functionality of the Velvet Room.

[msg MSG_003 [Caroline]]
Wait here, Inmate!

[msg MSG_004]
A few minutes later...

[msg MSG_005 [Justine]]
*sigh* It was somewhat difficult, but[n]this should prove useful to your[n]rehabilitation.

[msg MSG_006]
You can now use [f 0 1 2]3-Layer Fusion[f 0 1 0]! This[n]will require three Personas to initiate.

[msg MSG_007 [Caroline]]
Don't take our help for granted, Inmate!

