[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 4 1 1][f 3 1 1 0 0 22074]We've never seen that Shadow before,[n]but let's hurry up and kick its butt―[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 16 1 0][f 3 1 1 0 0 22058][f 6 1 2 0 0 10]Wait... Wh-What the...? My body feels[n]weird...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 27 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Oh... I can't gather up my strength[n]like usual either...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 10 0 6][f 3 1 1 0 0 0]You too!? So it's not just me...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 1][f 3 1 1 0 0 23121][f 6 1 2 0 0 6]We'll have to figure it out later! Here it[n]comes![n][f 1 3 65535][f 1 1][e]

