[msg MSG_000 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 23106]Tenemos la ubicaci吋n de Kamoshidaman...[n]Una vez que entremos, no podemos[n]regresar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 0][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 0]Hemos llegado hasta aqu胤, as胤 que todo lo que queda es poner nuestro plan en acci吋n. 斡Hagamos bien, con confianza y precauci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 3][f 4 6 23 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Joker, 夷est茨s listo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Vamos a salvar a nuestras amigas.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]A雨n no.[f 2 7 1 20 6 32][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23076][f 6 1 2 0 0 6]Ya veo... 斡Av胤sanos cuando est姻s listo![n][f 1 3 65535][f 1 1][e]

