[msg MSG_000 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 0 1 1][f 3 1 1 0 0 56002]Ah, bienvenido.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Me gustar胤a mostrarles un nuevo art胤culo[n]que estar姻 ofreciendo. 夷Me prestan[n]su atenci吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 3]斡Claro! 斡Vamos a ver![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 56103]Presentando el [f 4 4 4 0 1333].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]En teor胤a, te ser茨 muy 雨til. Usar uno[n]te permitira [f 0 1 2]escapar instant茨neamente[n]de los laberintos[f 0 1 0].[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Espero sinceramente que esto ayude a[n]sus esfuerzos de exploraci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 2 0 0]Tal vez le gustar胤a una muestra. El[n]primero es, como se suele decir, un[n]regalo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 80 1 0 1][f 4 6 66 0 1 3][f 3 1 1 0 0 22021][f 6 1 2 0 0 0]斡夷Qu姻?! 夷Quieres decir que si usamos[n]esto... podemos volver directo al cine?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 12 0 6]Deber胤amos comprar algunos m茨s. Un plan[n]de escape es vital para cualquier[n]operaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 80 12 0 0][f 3 1 1 0 0 56113]Si les parecen 雨tiles, por favor, vuelvan[n]a comprar algunos m茨s tarde.[n][f 1 3 65535][f 1 1][e]

