[msg chara_000]
[f 0 5 65278][f 2 1]Blank[n][e]

[msg chara_001]
[f 0 5 65278][f 2 1][Front Row]Siempre listo para una pelea, es mejor con ataques de Corte y El姻ctricos.[n][e]

[msg chara_002]
[f 0 5 65278][f 2 1][Front Row]Un luchador vers茨til, h茨bil en todas las afinidades.[n][e]

[msg chara_003]
[f 0 5 65278][f 2 1][Front Row]Un luchador 茨gil que se especializa en ataques de Corte y Viento.[n][e]

[msg chara_004]
[f 0 5 65278][f 2 1][Front Row]Una chica experta en kung fu con alta evasi吋n y ataques cr胤ticos.[n][e]

[msg chara_005]
[f 0 5 65278][f 2 1][Back Row]Correcta, apropiada y mortal, 斡pero cuidado con su salud![n][e]

[msg chara_006]
[f 0 5 65278][f 2 1]None[n][e]

[msg chara_007]
[f 0 5 65278][f 2 1][Front Row]Protege a sus compa隠eros con una alta defensa y ofensa.[n][e]

[msg chara_008]
[f 0 5 65278][f 2 1][Back Row]Un detective de peque隠o, excelente en habilidades de enlace.[n][e]

[msg chara_009]
[f 0 5 65278][f 2 1][Front Row]Una autodenominada mascota que ayuda al grupo en combate.[n][e]

[msg chara_00A]
[f 0 5 65278][f 2 1][Back Row]Una chica de mal humor que sobresale en habilidades de Viento y recuperaci吋n.[n][e]

[msg chara_00B]
[f 0 5 65278][f 2 1][Front Row]Un presumido con habilidades equilibradas de ataque, defensa y contraataque.[n][e]

[msg chara_00C]
[f 0 5 65278][f 2 1][Front Row]Un boxeador incomparable que inflige un da隠o extremo.[n][e]

[msg chara_00D]
[f 0 5 65278][f 2 1][Front or Back]Sella las habilidades de los enemigos y los derrota con magia de Hielo.[n][e]

[msg chara_00E]
[f 0 5 65278][f 2 1]None[n][e]

[msg chara_00F]
[f 0 5 65278][f 2 1][Front or Back]Arma anti-sombras[n]que puede activar su Modo Desenfreno.[n][e]

[msg chara_010]
[f 0 5 65278][f 2 1][Back Row]Es genial con habilidades f胤sicas y de Electricidad, 斡pero tiene poca salud![n][e]

[msg chara_011]
[f 0 5 65278][f 2 1][Back Row]R茨pido y maneja magia de Fuego y Oscuridad, 斡pero no es duradero![n][e]

[msg chara_012]
[f 0 5 65278][f 2 1][Front Row]El tipo m茨s duro del lugar, pero extremadamente vulnerable a la magia.[n][e]

[msg chara_013]
[f 0 5 65278][f 2 1][Back Row]Zen ataca, mientras que Rei cura. Ambos utilizan habilidades misteriosas...[n][e]

[msg chara_014]
[f 0 5 65278][f 2 1][Back Row]Zen ha recuperado sus recuerdos y sus habilidades...[n][e]

