[msg BR_RISE_GETSKILL_TRDEYE]
[f 0 5 65278][f 2 1]Cuando seleccionas un objetivo, puedes[n]verificar si el ataque ser茨 efectivo[n]o no.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_ENMY_S]
[f 0 5 65278][f 2 1]Podr茨s ver a los enemigos en el mapa,[n]incluso en lugares que a雨n no has[n]explorado.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_TRSR_S]
[f 0 5 65278][f 2 1]Los cofres del tesoro ser茨n visibles en[n]el mapa, incluso en lugares que a雨n[n]no has explorado.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_W_SACH]
[f 0 5 65278][f 2 1]Te dir茨n las debilidades del enemigo al[n]comienzo de la batalla.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_HP]
[f 0 5 65278][f 2 1]Se recuperar茨 una peque隠a cantidad de[n]PS al final de la batalla.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_Z_ESCP]
[f 0 5 65278][f 2 1]Podr茨s escapar con 姻xito de casi todas[n]las batallas.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_SP]
[f 0 5 65278][f 2 1]Se recuperar茨 una peque隠a cantidad de[n]PE al final de la batalla.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_HPSONG]
[f 0 5 65278][f 2 1]El efecto de recuperaci吋n de PS al final[n]de la batalla se ha vuelto m茨s[n]fuerte.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_SPSONG]
[f 0 5 65278][f 2 1]El efecto de recuperaci吋n de PE al final[n]de la batalla se ha vuelto m茨s[n]fuerte.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_H_ANYZ]
[f 0 5 65278][f 2 1]Junto con las afinidades a las que has[n]atacado en el pasado, ahora tambi姻n[n]puedes aprender qu姻 habilidades posee[n]el enemigo.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_F_ANYZ]
[f 0 5 65278][f 2 1]Junto con las habilidades que tiene el[n]enemigo, ahora tambi姻n puedes descubrir[n]las afinidades a las que no has[n]atacado en el pasado.[n][f 1 1][e]

