[msg BR_RISE_GETSKILL_TRDEYE]
[f 0 5 65278][f 2 1]When selecting a target, you can[n]check to see whether the attack will[n]be effective or not.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_ENMY_S]
[f 0 5 65278][f 2 1]You will be able to see enemies on[n]the map, even where you haven't[n]explored yet.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_TRSR_S]
[f 0 5 65278][f 2 1]Treasure chests will be visible on[n]the map, even where you haven't[n]explored yet.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_W_SACH]
[f 0 5 65278][f 2 1]You will be told the enemy weaknesses[n]at the beginning of battle.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_HP]
[f 0 5 65278][f 2 1]A small amount of HP will be recovered[n]at the end of battle.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_Z_ESCP]
[f 0 5 65278][f 2 1]You will be able to successfully[n]escape from almost all battles.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_IYA_SP]
[f 0 5 65278][f 2 1]A small amount of SP will be recovered[n]at the end of battle.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_HPSONG]
[f 0 5 65278][f 2 1]The HP recovery effect at the end[n]of battle has become stronger.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_SPSONG]
[f 0 5 65278][f 2 1]The SP recovery effect at the end[n]of battle has become stronger.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_H_ANYZ]
[f 0 5 65278][f 2 1]Along with the affinities you've[n]attacked in the past, you can now learn[n]what skills the enemy possesses as well.[n][f 1 1][e]

[msg BR_RISE_GETSKILL_F_ANYZ]
[f 0 5 65278][f 2 1]Along with the skills the enemy has,[n]you can now find out about the affinities[n]you haven't attacked in the past as well.[n][f 1 1][e]

