[sel noffice_yesno top]
[f 0 5 65278][f 2 1]S胤[e]
[f 0 5 65278][f 2 1]No[e]

[sel noffice_yesno_accept_che top]
[f 0 5 65278][f 2 1]Aceptar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[sel noffice_yesno_accept_ove top]
[f 0 5 65278][f 2 1]Aceptar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[sel noffice_yesno_accept_jum top]
[f 0 5 65278][f 2 1]受領後ダンジョンジャンプ確認　はい★未使用[e]
[f 0 5 65278][f 2 1]受領後ダンジョンジャンプ確認　いいえ★未使用[e]

[sel noffice_yesno_cancel_che top]
[f 0 5 65278][f 2 1]Descartar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[msg cure_check]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg cure_check_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg cure_check_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg cure_not_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg cure_not_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg cure_ng_E [Elizabeth]]
[f 0 5 65278][f 2 1]Disculpa, pero parece que te faltan[n]fondos.[n][f 1 1][e]

[msg cure_ng_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg not_accept_E [Elizabeth]]
[f 0 5 65278][f 2 1]En este momento, no hay entradas que[n]emitir.[n][f 1 1][e]

[msg full_accept_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg not_report_E [Elizabeth]]
[f 0 5 65278][f 2 1]※PQ2では使用しない ご報告頂ける依頼はございません。[n][f 1 1][e]

[msg not_cancel_E [Elizabeth]]
[f 0 5 65278][f 2 1]Parece que no tienes una entrada en[n]curso en este momento.[n][f 1 1][e]

[msg accept_check_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54206]夷Esta es la entrada que te gustar胤a[n]emitir?[n][f 1 1][e]

[msg accept_overwrite_check_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54207]夷Te gustar胤a cancelar tu entrada actual[n]y aceptar est茨 en su lugar?[n][f 1 1][e]

[msg cancel_check_E [Elizabeth]]
[f 0 5 65278][f 2 1]夷Te gustar胤a cancelar esta entrada?[n][f 1 1][e]

[msg cancel_refuse_check_E [Elizabeth]]
[f 0 5 65278][f 2 1]Esta entrada no puede ser cancelada.[n][f 1 1][e]

[msg cancel_end_E [Elizabeth]]
[f 0 5 65278][f 2 1]La entrada ha sido cancelada.[n][f 1 1][e]

[msg NHELP001_CURE_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg NHELP001_CURE_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg NHELP001_CURE_E_BLUE [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg NHELP001_QUEST_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54013]Las "proyecciones especiales" son[n]manifestaciones de eventos curiosos que[n]descubres en las pel胤culas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Las proyecciones especiales tienden a[n]divergir considerablemente de la[n]pel胤cula en la que se basan.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Puedes descubrir nuevos giros que no[n]aparecer胤an en una exploraci吋n normal.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Pru姻balos si te cansas de lo habitual[n]o te encuentras atascado de otra[n]manera.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54029]Si completas una proyecci吋n especial,[n]tambi姻n obtendr茨s excelentes[n]recompensas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Te aseguro que valen mucho la pena el[n]esfuerzo.[n][f 1 1][e]

[msg NHELP003_QUEST_REWARD_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54125]Cuando completes una proyecci吋n especial,[n]recibir茨s la recompensa que te[n]corresponde...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sin embargo, ese no es el 雨nico[n]beneficio.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 2 100 1][f 3 1 1 0 0 54029]Tambi姻n obtendr茨s una buena cantidad de[n]puntos de experiencia para fortalecerte[n]a雨n m茨s.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Independientemente de la composici吋n de[n]tu grupo, la experiencia fortalecer茨[n]a todos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Ganar茨s experiencia y recompensas, y yo[n]podr姻 ver todo en la gran pantalla.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54113]Yo dir胤a que ambos salimos ganando.[n]Prueba una si te apetece.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Ah, pero una vez que terminas una[n]proyecci吋n especial, no puedes volver a[n]visitarla.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Por ello, te aconsejo que las explores[n]a fondo antes de finalizarlas.[n][f 1 1][e]

[msg NHELP004_QUEST_TIMELIMIT [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg NHELP005_QUEST_CANCEL_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54103]Incluso despu姻s de aceptar una entrada,[n]es posible cancelarla.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si tienes dificultades o deseas una[n]proyecci吋n diferente, cancela la entrada.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Tambi姻n puedes volver a aceptar libremente[n]entradas  que hayas cancelado[n]anteriormente.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hasta que se complete la proyecci吋n[n]especial, puedes aceptar la entrada[n]todas las veces que desees.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 4 2 1][f 3 1 1 0 0 54039][f 6 1 2 0 0 6]斡Pero espera, hay m茨s! 斡Aceptar y cancelar[n]entradas es completamente[n]gratuito![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1]Por favor, haz uso de estas ofertas si[n]te sientes inclinado.[n][f 1 1][e]

[msg accept_jump_dg]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg quest_find]
[f 0 5 65278][f 2 1]Hay una nueva proyecci吋n especial[n]disponible. La entrada se puede aceptar[n]aqu胤.[n][f 1 1][e]

[msg talk_dammy [ダミー]]
[f 0 5 65278][f 2 1]会話ダミー[n][f 1 1][e]

