[sel combine_sel top]
[f 0 5 65278][f 2 1]S胤[e]
[f 0 5 65278][f 2 1]No[e]

[msg combine_check_zyusu [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59205]夷Esta persona?[n][f 1 1][e]

[msg combine_check_karo [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58205]夷Est茨s seguro de que quieres esta[n]persona?[n][f 1 1][e]

[msg combine_not_level [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58203]斡No me hagas re胤r. No eres lo suficientemente[n]fuerte como para manejar esta[n]Persona![n][f 1 1][e]

[msg combine_possession [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58203]斡Ya tienes esta Persona![n][f 1 1][e]

[msg combine_not_has_sorce_pe [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58203]斡No tienes la Persona adecuada para esto![n][f 1 1][e]

[msg combine_stock_over [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58203]斡No puedes tener m茨s Personas! 斡No seas[n]codicioso, Recluso![n][f 1 1][e]

[msg combine_free_ticket_chec [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59204]Tienes [f 4 4 3 0 1350] x[f 2 4 0].[n]夷Deber胤amos usar esto para fusionar[n]de forma gratuita?[n][f 1 1][e]

[msg combine_money [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Parece que te faltan fondos.[n][f 1 1][e]

[msg combine_money_conf [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59204]Tomaremos [f 0 1 2][f 2 4 0] yenes[f 0 1 0] para[n]invocar esta Persona. 夷Est茨s seguro?[n][f 1 1][e]

[msg combine_succession [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59206]Elige las habilidades que deseas[n]transferir.[n][f 1 1][e]

[msg combine_burst [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_check_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_not_level_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_possession_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_stock_over_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_money_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_money_conf_Ex [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg combine_succession_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg combine_burst_Ex [Elizabeth]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_comu_bonus]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_get_comu_bonus]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg combine_008]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_no_comu_bonus]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_get_card]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 0 6 255 255]斡La Persona [f 0 1 1][f 2 4 0][f 0 1 0] ha surgido[n]del mar de tu alma![n][f 1 1][e]

[msg combine_accident [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58206]Eso no estaba exactamente en el plan...[n]B-bueno, 斡no es nuestro problema![n][f 1 2 133][f 1 1][e]

[msg combine_fool_accident [Margaret]]
[f 0 5 65278][f 2 1]Bien, bien... Esto es un "Comod胤n".[n][f 1 1][e]

[msg combine_accident_Ex [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58206]Eso no estaba exactamente en el plan...[n]B-bueno, 斡no es nuestro problema![n][f 1 2 149][f 1 1][e]

[msg combine_fool_accident_Ex [Elizabeth]]
[f 0 5 65278][f 2 1]Vaya... Esto es un "Comod胤n".[n][f 1 1][e]

[msg combine_drink_conf [Elizabeth]]
[f 0 5 65278][f 2 1]ジュース使用前確認MSG（仮）[n][f 1 1][e]

[msg combine_accident_up [Elizabeth]]
[f 0 5 65278][f 2 1]事故率ＵＰ時のメッセージ（仮）[n][f 1 1][e]

[msg weather_bonus_omen]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg weather_bonus_omen_add]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_get_skill]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_noget_skil]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_no_skill]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_powerup]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_get_comubo]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_get_change]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_bonus_changeskil]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_news_greeting [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg weather_news_wait [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg zensyo_menu [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg zensyo_summons [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58204]Costar茨 [f 0 1 2][f 2 4 0] yenes[f 0 1 0] invocar[n]a esta Persona. 夷Est茨s seguro?[n][f 1 1][e]

[msg zensyo_not_summons [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]No tienes suficiente dinero. Por favor,[n]no malgastes nuestro tiempo.[n][f 1 1][e]

[msg zensyo_get_summons]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 0 6 255 255]La Persona [f 0 1 1][f 2 4 0][f 0 1 0] ha sido[n]invocada.[n][f 1 1][e]

[msg zensyo_not2_summons [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]Parece que ya tienes esta Persona. 夷No[n]pensaste en verificarlo?[n][f 1 1][e]

[msg zensyo_not3_summons [Margaret]]
[f 0 5 65278][f 2 1]Parece que tu nivel no es lo suficientemente[n]alto para invocar a esta[n]Persona...[n][f 1 1][e]

[msg zensyo_not4_summons [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]No puedes tener m茨s Personas. La avaricia[n]no es buena.[n][f 1 1][e]

[msg zensyo_regist [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡La Persona Film ha sido sobrescrita![n][f 1 1][e]

[msg zensyo_add_check [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58208]夷Quieres registrar tu [f 0 1 1][f 2 4 0][f 0 1 0][n]en la Persona Film, 夷verdad?[n][f 1 1][e]

[msg zensyo_all_add_check [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58208]Puedo registrar todas las Personas que[n]tengas en Persona Film, 夷verdad?[n][f 1 1][e]

[msg zensyo_mark_add_check [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58208]夷Quieres que registre las Personas que[n]seleccionaste en Persona Film, verdad?[n][f 1 1][e]

[msg zensyo_no_regist [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]Parece que no tienes Personas que pueda[n]registrar en el compendio. Francamente,[n]es decepcionante.[n][f 1 1][e]

[msg powerup_message [Margaret]]
[f 0 5 65278][f 2 1]このペルソナを強化しますか？[n][f 1 1][e]

[msg powerup_cancel [Margaret]]
[f 0 5 65278][f 2 1]あなたが現在身に着けている ペルソナに関しては、お預かり出来ません…[n][f 1 1][e]

[msg powerup_non [Margaret]]
[f 0 5 65278][f 2 1]強化素材となるペルソナを お持ちで無いご様子…[n][f 1 1][e]

[msg powerup_receive [Margaret]]
[f 0 5 65278][f 2 1]このペルソナの強化を中止し、 引き取りますか？[n][f 1 1][e]

[msg powerup_receive1 [Margaret]]
[f 0 5 65278][f 2 1]現在お預かりしているペルソナは、 ご覧の状態です。[n][f 1 1][e]

[msg powerup_receive2 [Margaret]]
[f 0 5 65278][f 2 1]現在お預かりしているペルソナは、 ご覧の状態です。[n][f 1 1][e]

[msg powerup_receive3 [Margaret]]
[f 0 5 65278][f 2 1]現在お預かりしているペルソナは、 ご覧の状態です。[n][f 1 1][e]

[msg powerup_failed [Margaret]]
[f 0 5 65278][f 2 1]残念な事になってしまいました…[n][f 1 1][e]

[msg powerup_no_receive [Margaret]]
[f 0 5 65278][f 2 1]これ以上ペルソナを所持出来ないご様子… 夷きを作ってから引き取りにいらして下さい。[n][f 1 1][e]

[msg skill_powerup [Margaret]]
[f 0 5 65278][f 2 1]ペルソナのスキルが強化しそうです。[n][f 1 1][e]
[f 0 5 65278][f 2 1]『[f 0 1 1][f 2 4 0][f 0 1 0]』を強化しますか？[n][f 1 1][e]

[msg cmb_comu_achieve_get_ite]
[f 0 5 65278][f 2 1][f 0 6 255 255]Recibiste [f 2 5 3 65535 0].[n][f 1 1][e]

[msg comu_achieve_rank_A [Margaret]]
[f 0 5 65278][f 2 1]私の忠告など、 必要ありませんでしたね。[n][f 1 1][e]

[msg comu_achieve_rank_B [Margaret]]
[f 0 5 65278][f 2 1]素晴らしいペースです。[n][f 1 1][e]
[f 0 5 65278][f 2 1]コミュニテ斡こそがあなたの“世界”を作る… どうぞお忘れなきよう…[n][f 1 1][e]

[msg comu_achieve_rank_C [Margaret]]
[f 0 5 65278][f 2 1]なかなかのペースですね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]コミュニテ斡こそがあなたの“世界”を作る… どうぞお忘れなきよう…[n][f 1 1][e]

[msg comu_achieve_rank_D [Margaret]]
[f 0 5 65278][f 2 1]もっと絆を大事になさった方がいいかと。[n][f 1 1][e]
[f 0 5 65024][f 2 1]コミュニテ斡こそがあなたの“世界”を作る… どうぞお忘れなきよう…[n][f 1 1][e]

[msg comu_achieve_rank_E [Margaret]]
[f 0 5 65278][f 2 1]もっと絆を大事になさい。 貴方の傍に、きっと見つかるはずなのだから。[n][f 1 1][e]
[f 0 5 65024][f 2 1]コミュニテ斡こそがあなたの“世界”を作る… どうぞお忘れなきよう…[n][f 1 1][e]

[msg cmb_comu_achieve [Margaret]]
[f 0 5 65278][f 2 1]あら…？[n][f 1 1][e]
[f 0 5 65278][f 2 1]どうやら、貴方のコミュニテ斡達成率が、 ５０％を越えた様子…[n][f 1 1][e]
[f 0 5 65278][f 2 1]素晴らしいわ。 なら…これを受け取ってちょうだい。[n][f 1 1][e]
[f 0 5 65278][f 2 1]コミュの充実こそが、 あなたの“世界”の充実になる…[n][f 1 1][e]
[f 0 5 65278][f 2 1]私、あなたの“世界”を 楽しみにしているわ。[n][f 1 1][e]

[msg cmb_comu_achieve_100 [Margaret]]
[f 0 5 65278][f 2 1]素晴らしいわ…[n][f 1 1][e]
[f 0 5 65278][f 2 1]貴方はとうとう、全てのコミュニテ斡を 真の絆へと育んだのね…[n][f 1 1][e]
[f 0 5 65024][f 2 1]誰にでも出来ることじゃないわ…[n][f 1 1][e]
[f 0 5 65024][f 2 1]やはり貴方は…私の思ったとおりの人。[n][f 1 1][e]
[f 0 5 65024][f 2 1]貴方の“世界”とは… どんなものなのかしら。[n][f 1 1][e]
[f 0 5 65024][f 2 1]出来るなら、その“世界”に 私も連れて行って欲しいわね…[n][f 1 1][e]
[f 0 5 65024][f 2 1]…では、これを。 私が長い時をかけて作ったものよ。[n][f 1 1][e]
[f 0 5 65024][f 2 1]きっと、貴方を守るわ。 この私の代わりにね…[n][f 1 1][e]

[msg book_bonus001 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]Not used[n][f 1 1][e]

[msg book_bonus002 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]Not used[n][f 1 1][e]

[msg book_bonus003 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]Not used[n][f 1 1][e]

[msg book_bonus004 [Margaret]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]★未使用！[n][f 1 1][e]

[msg combine_before_comu_none [Igor]]
[f 0 5 65278][f 2 1]“[f 2 4 0]”コミュはまだお持ちでないご様子。[n]もっとも、“[f 2 4 0]”コミュを築かれるのは、[n]まだ先のようですが…[n][f 1 1][e]
[f 0 5 65278][f 2 1]新たな力を授かる事はございませんが、 このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_before_comu_none_2 [Igor]]
[f 0 5 65278][f 2 1]“[f 2 4 0]”コミュはまだお持ちでないご様子。[n]そろそろ現れる頃かと存じますが…[n][f 1 1][e]
[f 0 5 65278][f 2 1]新たな力を授かる事はございませんが、 このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_before_comu_none_3 [Igor]]
[f 0 5 65278][f 2 1]“[f 2 4 0]”コミュはまだお持ちでないご様子。[n][f 1 1][e]
[f 0 5 65278][f 2 1]新たな力を授かる事はございませんが、 このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_00 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”をお持ちでないご様子… 新たな力を授かる事はございませんな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_01 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは１… さて…力をどれほど授かるでしょうな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_02 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは２… 幾らかは力を授かって生まれるでしょうな…[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_03 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは３… 幾らかは力を授かって生まれるでしょうな…[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_04 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは４… なかなかの力を授かって生まれそうですな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_05 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは５… なかなかの力を授かって生まれそうですな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_06 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは６… かなりの力を授かって生まれそうですな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_07 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは７… かなりの力を授かって生まれそうですな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_08 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは８… 大きな力を授かって生まれて参りますな…[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_09 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは９… 大きな力を授かって生まれて参りますな…[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_rank_10 [Igor]]
[f 0 5 65278][f 2 1]対応する“コミュ”のランクは１０…[n][f 1 1][e]
[f 0 5 65278][f 2 1]ほう…これは間違いなく、 強大な力を授かって生まれて参りますな。[n][f 1 1][e]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_comu_world [Igor]]
[f 0 5 65278][f 2 1]このペルソナで宜しいですかな？[n][f 1 1][e]

[msg combine_tutorial_mes_igo [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_tutorial_mes_igo_2 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_yohou_tutorial_m [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg book_tutorial_mes [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg combine_powerup_tutorial [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_tutorial_mes_igo_3 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_tutorial_mes_igo_4 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP000_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP001 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP002_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP003 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP004_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP005_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP006_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP007 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP008 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP009 [Igor]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP010_M [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 75 0 0 1]★未使用！[n][f 1 1][e]

[msg msg_combine_MHELP001_M [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 1 0 4][f 4 6 78 12 0 1]Las Personas que registres en "Persona[n]Film" se pueden ver siempre que[n]quieras.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Adem茨s, podemos invocar una Persona[n]desde la pel胤cula si est茨s dispuesto a[n]pagar su precio.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Solo hay un peque隠o detalle: cuanto m茨s[n]fuerte sea la Persona, m茨s te va a[n]costar. Obviamente.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si registras muchas Personas, tal vez[n]consideremos darte un descuento. 斡Mejor[n]trabaja duro para conseguirlo![n][f 1 1][e]

[msg msg_combine_MHELP002_M [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 12 0 4][f 4 6 78 1 0 1]Cuando adquieras una Persona por primera[n]vez, su estado base y original se[n]registrar茨 en Persona Films.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Pero a medida que las fortalezcas, puedes[n]sobrescribir su pel胤cula con tu[n]versi吋n m茨s poderosa de ellos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Este es un servicio gratuito, pero[n]tendr茨s que indicarnos espec胤ficamente[n]si deseas sobrescribir una entrada.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si lo deseas, simplemente ind胤canos que[n]deseas "Sobrescribir Persona Film".[n]夷Entendido?[n][f 1 1][e]

[msg msg_combine_MHELP003 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S0HELP001 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S0HELP002 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S0HELP003 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S1HELP001 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S1HELP002 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S1HELP003 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S2HELP001 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S2HELP002 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_S2HELP003 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U0HELP001 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U0HELP002 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U0HELP003 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U1HELP001 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U1HELP002 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U1HELP003 [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U2HELP001 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U2HELP002 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_U2HELP003 [Marie]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg cmm_please_000 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_001 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_002 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_003 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_004 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_005 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_006 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_007 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_008 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_009 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_010 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_0320 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmm_please_flg_wait [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg cmb_cmm_bonus_rank10 [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 4][e]

[msg msg_combine_MESSAGE000 [1]]
[f 0 5 65278][f 2 1]斡SOY UN TONTO![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE001 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Abre tus ojos... 斡Te levantar茨s...![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE002 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Nuestros cuerpos[n]pueden ser diferentes,[n]pero yo soy tú. Me pongo a tu cuidado.[f 1 1][e]

[msg msg_combine_MESSAGE003 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Eres t雨 quien me llam吋...?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Te ves fuerte... Muy bien. Estoy de[n]acuerdo en acompa隠arte.[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Estoy bajo tu[n]cuidado...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE004 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Te prestar姻 el[n]poder que puedo ofrecer.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE005 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Soy uno de los[n]muchos que residen en el mar de tu[n]alma...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE006 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡Te proteger姻[n]con todo mi poder![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE007 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... No me olvidar茨s[n]pronto...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE008 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Mi nombre es [f 0 1 1][f 2 4 1][f 0 1 0]... Juntos[n]caminaremos por este largo y arduo[n]camino...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE009 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Tu escudo, tu[n]espada, tu amigo...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE010 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Soy uno contigo...[n]Por favor recuerde eso.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE011 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Te proteger姻 y[n]curar姻 tus heridas...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE012 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Soy [f 0 1 1][f 2 4 1][f 0 1 0]! 斡Atestiguar茨s[n]mi poder con tus propios ojos![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE013 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Esta espada[n]ser茨 usada en tu nombre...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE014 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Har姻 todo lo[n]posible para darte apoyo.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE015 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡Rel茨jate y dejale[n]todo a tu gran hermana![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE016 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Har姻 todo lo[n]posible, as胤 que por favor d姻jame[n]quedarme.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE017 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Veamos la[n]verdadera fuerza de tu determinaci吋n.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE018 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Mu姻strame qu姻[n]poderes tienes...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE019 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Soy [f 0 1 1][f 2 4 1][f 0 1 0]! 斡Nuestra victoria[n]est茨 en tus manos![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE020 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Siempre estar姻[n]a tu lado...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE021 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Ir姻 contigo a[n]construir un futuro m茨s brillante...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE022 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Muy bien,[n]tendr茨s mi fuerza a tu disposici吋n.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE023 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡Estoy contigo[n]en el camino de la gloria![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE024 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡La misi吋n de mi[n]vida ser茨 mantenerte a salvo![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE025 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... He venido a[n]ti, cuyo coraz吋n desea poder...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE026 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Yo [f 0 1 1][f 2 4 1][f 0 1 0]. Te invito todo.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE027 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Nac胤 de ti, y[n]por eso volver姻 a ti...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE028 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡Puedes contar[n]conmigo! Me asegurar姻 de que ganemos...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE029 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Y-yo soy [f 0 1 1][f 2 4 1][f 0 1 0]! 斡Yo sOy uNo[n]COnTiGo![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE030 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]YO SOY [f 0 1 1][f 2 4 1][f 0 1 0]. Es un placer[n]conocerte...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE031 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 0 1 1][f 2 4 1][f 0 1 0]... Sube. Estamos en un viaje de ida al[n]infierno...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE032 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Antes de estar [f 0 1 1][f 2 4 1][f 0 1 0]... Soy[n]el invicto que te jura lealtad...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE033 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Hola. Soy [f 0 1 1][f 2 4 1][f 0 1 0]. Te acompa隠ar姻[n]en tu viaje.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE034 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Supongo que te[n]cuidar姻 por un tiempo...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE035 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Soy [f 0 1 1][f 2 4 1][f 0 1 0], ho! Encantado[n]de conocerte, hee ho![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE036 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 0 1 1][f 2 4 1][f 0 1 0]... 夷Jugar茨s conmigo por y para siempre?[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE037 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Soy [f 0 1 1][f 2 4 1][f 0 1 0]. 斡Ser姻 el salvaje[n]harbinger de tu victoria absoluta![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE038 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Soy [f 0 1 1][f 2 4 1][f 0 1 0], hee hoooo! 斡No[n]me subestimes, hee hee ho![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE039 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n se atreve a llamarme?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Tienes la fuerza para penetrar esta[n]oscuridad atormentada... Tienes mi[n]inter姻s, chico...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Te prestar姻 mi[n]poder por ahora...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE040 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n se atreve a llamarme...?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Eres un ni隠o noble, para tener una luz[n]tan fuerte. Te dar姻 mi protecci吋n...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Intentar姻 estar[n]a la altura de la fuerza de tu[n]coraz吋n...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE041 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]T雨 eres yo... Y yo soy t雨... Desde el[n]mar de tu alma, vengo...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Desde el mismo momento de mi emergencia,[n]he sido una luz gu胤a para iluminar[n]tu camino...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy el dios original...[n][f 0 1 1][f 2 4 1][f 0 1 0]...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE042 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n me llama...?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Tu coraz吋n brillante brilla incluso en[n]la noche m茨s oscura... Ser姻 tu[n]fuerza...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Que tu luz[n]nunca se apague...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE043 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n me llama?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Uno que brilla en la inimaginable[n]oscuridad... 夷Incluso dibujar茨s en tu ser[n]hueco por tu fuerza?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Yo marcar姻 el[n]camino que tomes...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_NETWORK_STOC [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 65200]Esto no va a funcionar. No tienes ninguna[n]Persona Secundaria.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Necesitas al menos una Persona Secundaria,[n]as胤 que ve a buscar una primero.[n][f 1 1][e]

[msg msg_combine_NETWORK_STOC_2 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 65200]Esto no va a funcionar. No tienes ninguna[n]Persona Secundaria.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Necesitas al menos una Persona Secundaria,[n]as胤 que ve a buscar una primero.[n][f 1 1][e]

[msg msg_combine_NETWORK_dumm [0]]
[f 0 5 65278][f 2 1]Dummy[n][f 1 1][e]

[msg msg_combine_sacrifice_co [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 58204]夷Es esta la Persona que quieres mejorar[n]con el poder del sacrificio?[n][f 1 1][e]

[msg msg_combine_sacrifice_bo]
[f 0 5 65278][f 2 1][f 0 6 255 255]El poder de las Personas sacrificadas[n]se vierte en [f 0 1 1][f 2 4 0][f 0 1 0]...[n][f 1 1][e]

[msg msg_combine_sacrifice_it]
[f 0 5 65278][f 2 1][f 0 6 255 255]La habilidad de la Persona sacrificada[n]habita en su interior...[n][f 0 1 1][f 2 4 0][f 0 1 0][n][f 1 1][e]

[msg msg_combine_sacrifice_it_2]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Obtuviste[n][f 0 7 0 65535][f 2 5 3 65535 0][f 0 7 150 65535][f 2 5 3 65535 1]　[n][f 0 7 0 65535][f 2 5 3 65535 2][f 0 7 150 65535][f 2 5 3 65535 3]![n][f 1 1][e]

[msg msg_combine_sacrifice_it_3]
[f 0 5 65278][f 2 1]Todas las ranuras de habilidades est茨n[n]llenas. Por favor, selecciona una[n]habilidad para olvidar.[n][f 1 1][e]

[msg msg_combine_skcard_sel [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_skcard_check [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_skcard_get]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_skcard_del]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_skcard_money [Margaret]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55200]Parece que no tienes suficiente dinero...[n][f 1 1][e]

[msg msg_combine_skcard_same_ [Caroline]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_skcard_item]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP011_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP012_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP013_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP014_M [Margaret]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP000_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP002_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP004_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP005_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP006_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP010_E [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][f 1 1][e]

[msg msg_combine_HELP011_E [Elizabeth]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg msg_combine_HELP_ACCIDEN [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 12 0 4][f 4 6 78 1 0 1]"Fusi吋n de Personas" es un proceso muy[n]delicado.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Aunque es muy raro, nos equivocamos[n]ocasionalmente... y en tales casos,[n]puede ocurrir un "accidente".[n][f 1 1][e]
[f 0 5 65278][f 2 1]Los accidentes en la fusi吋n alteran el[n]resultado del ritual. Espec胤ficamente,[n]invocando a un Persona diferente[n]a la prevista.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Incluso no podemos saber lo que surgir茨[n]de tal error.[n][f 1 1][e]

[msg msg_combine_HELP_KENSAKU [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 1 0 4][f 4 6 78 0 1 1]Con "B雨squeda de Fusi吋n", 斡Puedes ver[n]todas las Personas que pueden ser[n]invocadas![n][f 1 1][e]
[f 0 5 65278][f 2 1]Puedes usar esto para buscar las Personas[n]de m茨s alto nivel que puedas[n]invocar...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Y si est茨s buscando a Personas que a雨n[n]no tienes en Persona Films, tambi姻n[n]te puede ser 雨til.[n][f 1 1][e]

[msg msg_combine_HELP_3SIN [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 12 0 4][f 4 6 78 1 0 1]"Fusi吋n de 3 capas" es un ritual en el[n]que tres Personas se fusionan para[n]hacer una Persona de un nivel alto.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Los tres ser茨n consumidos, pero el[n]resultado final ser茨 notablemente fuerte.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si quieres m茨s poder, entonces sugiero[n]usar este ritual sabiamente.[n][f 1 1][e]

[msg msg_combine_HELP_TOKUSYU [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 79 1 0 4][f 4 6 78 12 0 1]"Fusi吋n especial" es una manera de[n]invocar a una Persona espec胤fica, usando[n]Personas espec胤ficas en el proceso.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Esta es la 雨nica manera de conseguir[n]algunas Personas que no puedes invocar[n]con fusiones normales.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Puede que no sea f茨cil, pero todas son[n]Personas muy poderosas, definitivamente[n]valen el esfuerzo extra.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Podr胤as intentarlo, al menos. 斡Usa todas[n]las ventajas que puedes conseguir![n][f 1 1][e]

[msg msg_combine_HELP_SACRIFI [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 7 1 0 0][f 4 7 4 0 0][f 4 6 75 12 0 1]Estoy a cargo de esto.[n][f 1 1][e]
[f 0 5 65278][f 2 1]La "Fusi吋n de Sacrificio" es un arte[n]secreto en el que una Persona es[n]sacrificada para ayudar a otra Persona a[n]mejorar.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cuanto m茨s altos sean los niveles de la[n]Persona Sacrificada, m茨s mejoras[n]obtendr茨s.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Normalmente, este arte secreto requiere[n]un pago apropiado...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Pero en nombre de otras investigaciones,[n]existe una condici吋n especial.[n][f 1 1][e]
[f 0 5 65278][f 2 1]La primera vez que sacrifiques a cualquier[n]Persona individual, realizar姻 el[n]ritual de forma gratuita.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Puedes mejorar tu Persona principal de[n]esta manera, tambi姻n. Puede ser una[n]buena manera de fortalecerse.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cuando obtienes una Persona nueva, 夷por[n]qu姻 no usas la Fusi吋n de Sacrificio[n]al menos una vez?[n][f 1 1][e]

[msg msg_combine_HELP_ACCESSO [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg msg_combine_MHELP001_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 80 0 0 1]Not used[n][f 1 1][e]

[msg msg_combine_MHELP002_E [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 80 0 0 1]★未使用！[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Bien, as胤 que explicar姻 c吋mo funciona[n]esto de P-Book.[n][f 1 1][e]
[f 0 5 65278][f 2 1]La cosa es que, aparentemente hay una[n]tonelada de mundos adem茨s de este,[n]lleno de versiones alternativas de ti.[n][f 1 1][e]
[f 0 5 65278][f 2 1]El P-Book es lo que se utiliza para[n]comunicarse con otros mundos adem茨s de[n]姻ste.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]As胤 que puedes contactar con uno de[n]estos otros, para cambiar una Persona[n]con ellos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Tienes que poner la informaci吋n de tu[n]equipo en el P-Book, adem茨s de lo que[n]quieras.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Pero la Persona debe ser una de tus[n]Personas Secundarias.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Una vez que consigas un P-Book de alguien,[n]puedes llamar a cualquier Persona[n]que tengan.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si lo usas bien, puedes ver a alguna de[n]las personas fuertes que pasan por[n]ah胤.[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_2 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Bien, as胤 que explicar姻 c吋mo funciona[n]esto de P-Book.[n][f 1 1][e]
[f 0 5 65278][f 2 1]La cosa es que, aparentemente hay una[n]tonelada de mundos adem茨s de este,[n]lleno de versiones alternativas de ti..[n][f 1 1][e]
[f 0 5 65278][f 2 1]El P-Book es lo que se utiliza para[n]comunicarse con otros mundos adem茨s de[n]姻ste.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]As胤 que puedes contactar con uno de[n]estos otros, para cambiar una Persona[n]con ellos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Tienes que poner la informaci吋n de tu[n]equipo en el P-Book, adem茨s de lo que[n]quieras.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Pero la Persona debe ser una de tus[n]Personas Secundarias.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Una vez que consigas un P-Book de alguien,[n]puedes llamar a cualquier Persona[n]que tengan.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si lo usas bien, puedes ver a alguna de[n]las personas fuertes que pasan por[n]ah胤.[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_3 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Guardar姻 a los P-Books que intercambies,[n]as胤 que av胤same cuando quieras[n]verlos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, y te avisar姻 cuando tengas nuevos[n]P-Books.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 6 0 1]Solo ten en cuenta que, no puedes[n]conservar cada P-Book que obtengas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]S吋lo puedes tener 100, as胤 que si hay[n]alguno que realmente quieras conservar,[n]deber胤as "Proteger" sus datos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Porque una vez que este lleno, empezar茨n[n]a desaparecer, empezando por el[n]m茨s viejo. A menos que est茨n protegidos.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]Y puedes proteger un m茨ximo de 80 libros.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Y si quieres invocar una persona de un[n]P-Book, h茨zmelo saber.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Te costar茨, pero esas peque隠as gemelas[n]pueden invocarla. Seg雨n Margaret, de[n]todos modos.[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_4 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Guardar姻 a los P-Books que intercambies,[n]as胤 que av胤same cuando quieras[n]verlos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, y te avisar姻 cuando tengas nuevos[n]P-Books.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 6 0 1]Solo ten en cuenta que, no puedes[n]conservar cada P-Book que obtengas.[n][f 1 1][e]
[f 0 5 65278][f 2 1]S吋lo puedes tener 100, as胤 que si hay[n]alguno que realmente quieras conservar,[n]deber胤as "Proteger" sus datos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Porque una vez que este lleno, empezar茨n[n]a desaparecer, empezando por el[n]m茨s viejo. A menos que est茨n protegidos.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]Y puedes proteger un m茨ximo de 80 libros.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Y si quieres invocar una persona de un[n]P-Book, h茨zmelo saber.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Te costar茨, pero esas peque隠as gemelas[n]pueden invocarla. Seg雨n Margaret, de[n]todos modos.[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_5 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Puedes cambiar los detalles de tu P-Book[n]cuando quieras.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cosas como las Personas Secundarias que[n]agregaste, tu nombre de P-Book,[n]mensajes personales...[n][f 1 1][e]
[f 0 5 65278][f 2 1]As胤 que si quieres cambiar algo, todo[n]lo que tienes que hacer es pedirlo.[f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]No escribas un nombre o detalles que[n]pueda incomodar al otro.[n][f 1 1][e]
[f 0 5 65278][f 2 1]No hagas cosas raras. Despu姻s de todo,[n]quieres que se alegren de tener tu[n]libro, 夷verdad?[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_6 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Puedes cambiar los detalles de tu P-Book[n]cuando quieras.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Cosas como las Personas Secundarias que[n]agregaste, tu nombre de P-Book,[n]mensajes personales...[n][f 1 1][e]
[f 0 5 65278][f 2 1]As胤 que si quieres cambiar algo, todo[n]lo que tienes que hacer es pedirlo.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]No escribas un nombre o detalles que[n]pueda incomodar al otro.[n][f 1 1][e]
[f 0 5 65278][f 2 1]No hagas cosas raras. Despu姻s de todo,[n]quieres que se alegren de tener tu[n]libro, 夷verdad?[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_7 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Por lo tanto, su P-Book se puede[n]intercambiar en una cosa llamada "C吋digo QR"[n][f 1 1][e]
[f 0 5 65278][f 2 1]夷Supongo que puede facilitar el intercambio[n]de los P-Books?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si no puedes conectarte con ellos[n]directamente, entonces siempre puedes[n]intercambiar los c吋digos QR.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Podr胤as crear el tuyo propio, o si la[n]otra persona ha creado la suya, podr胤as[n]leerla.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]Bueno, podr胤as conseguir cosas 雨tiles[n]en esos P-Book. As胤 que intercambia[n]todos los c吋digos QR que puedas.[n][f 1 1][e]

[msg msg_combine_NETWORK_HELP_8 [Marie]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 4 6 85 12 0 1]Por lo tanto, su P-Book se puede[n]intercambiar en una cosa llamada "C吋digo QR"[n][f 1 1][e]
[f 0 5 65278][f 2 1]夷Supongo que puede facilitar el intercambio[n]de los P-Books?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Si no puedes conectarte con ellos[n]directamente, entonces siempre puedes[n]intercambiar los c吋digos QR.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Podr胤as crear el tuyo propio, o si la[n]otra persona ha creado la suya, podr胤as[n]leerla.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 85 12 0 1]Bueno, podr胤as conseguir cosas 雨tiles[n]en esos P-Book. As胤 que intercambia[n]todos los c吋digos QR que puedas.[n][f 1 1][e]

[msg book_bonus001_ex [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][e]

[msg book_bonus002_ex [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][e]

[msg book_bonus003_ex [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][e]

[msg book_bonus004_ex [Elizabeth]]
[f 0 5 65278][f 2 1]Not used[n][e]

[msg zensyo_summons_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_not_summons_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_not2_summons_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_not4_summons_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_regist_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_add_check_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_all_add_check_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_mark_add_check_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Not used[n][f 1 1][e]

[msg zensyo_no_regist_Ex [Elizabeth]]
[f 0 5 65278][f 2 1][f 0 6 255 255]★未使用！[n][f 1 1][e]

[msg msg_combine_MESSAGE044 [1]]
[f 0 5 65278][f 2 1]夷Qui姻n me llama...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Me conocer茨s como [f 0 1 1]Zeus[f 0 1 0]... He sido[n]llamado desde el m茨s all茨...[n][f 1 1][e]
[f 0 5 65278][f 2 1]T雨, cuyos lazos llegan a tierras[n]desconocidas... Averiguar姻 tu resoluci吋n.[n][f 1 1][e]

[msg msg_combine_MESSAGE045 [1]]
[f 0 5 65278][f 2 1]Yo soy t雨, t雨 eres yo...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Uno que recurre libremente a la fuerza[n]de los lazos... 夷Deseas m茨s[n]libertad...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Entonces, vayamos juntos a la lejana[n]tierra de la libertad...[n][f 1 1][e]

[msg msg_combine_MESSAGE046 [1]]
[f 0 5 65278][f 2 1]Yo soy t雨... T雨 eres yo... Del mar de[n]tu alma, surge...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Yo soy [f 0 1 1]Orpheus[f 0 1 0], maestro de las[n]cuerdas...[n][f 1 1][e]

[msg msg_combine_MESSAGE047 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Yo soy [f 0 1 1][f 2 4 1][f 0 1 0]... El que nace[n]de ti y camina a tu lado...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE048 [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255]★未使用！[n][f 1 1][e]

[msg msg_combine_MESSAGE049 [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255]★未使用！[n][f 1 1][e]

[msg combine_regist_NG [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]Has protegido esta Persona, por lo que[n]no puede ser registrada.[n][f 1 1][e]

[msg combine_regist_NG_Ex [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 59203]Has protegido esta Persona, por lo que[n]no puede ser registrada.[n][f 1 1][e]

[msg msg_combine_scr_error [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]La fuerza de esta Persona no puede ser[n]llevada m茨s lejos.[n][f 1 1][e]

[msg msg_combine_skcard_yet [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Esta Persona a雨n no ha aprendido ninguna[n]habilidad que se pueda extraer de[n]ella.[n][f 1 1][e]

[msg msg_combine_skcard_lost [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Esta Persona ha perdido la habilidad[n]que puede extraerse de ella.[n][f 1 1][e]

[msg msg_combine_NETWORK_STOC_3 [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]Oh... Esa Persona Secundaria no puede[n]ser usada para comunicarse con otros[n]mundos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Tendr茨s que elegir una diferente.[n][f 1 1][e]

[msg msg_combine_NETWORK_STOC_4 [Marie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 65200]Oh... Esa Persona Secundaria no puede[n]ser usada para comunicarse con otros[n]mundos.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Tendr茨s que elegir una diferente.[n][f 1 1][e]

[msg msg_combine_TOP_ACCESSOR [Margaret]]
[f 0 5 65278][f 2 1]★未使用！[n][f 1 1][e]

[msg combine_stock_lack]
[f 0 5 65278][f 2 1]No hay Personas suficientes en tu[n]inventario.[n][f 1 1][e]

[msg msg_combine_ZENSYO_TEST [Justine]]
[f 0 5 65278][f 2 1][f 0 6 255 255]★未使用！[n][f 1 1][e]

[msg msg_combine_skcard_skill [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]★未使用！[n][f 1 1][e]

[sel combine_sel_TICKET top]
[f 0 5 65278][f 2 1]Pagar fusi吋n[e]
[f 0 5 65278][f 2 1]Cancelar fusi吋n[e]
[f 0 5 65278][f 2 1]Utilizar un ticket[e]

[msg msg_combine_sac_skill_ch [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Tienes [f 0 1 3][f 2 4 0][f 0 1 0] x[f 0 1 3][f 2 4 2][f 0 1 0]. 夷Le[n]gustar胤a utilizarlo para transmitir[n][f 0 1 1][f 2 4 1][f 0 1 0]?[n][f 1 1][e]

[msg msg_combine_sac_skill_ge]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 0 1 1][f 2 4 0][f 0 1 0]ha aprendido[n][f 0 1 1][f 2 4 1][f 0 1 0]![n][f 1 1][e]

[msg msg_combine_sac_skill_ha]
[f 0 5 65278][f 2 1][f 0 6 255 255]Ya tienes [f 2 4 0].[n][f 1 1][e]

[msg msg_combine_stock_over_s [Justine]]
[f 0 5 65278][f 2 1]Se necesitan [f 0 6 255 255][f 3 1 1 0 0 59203][f 2 4 0] ranura(s)[n]adicional(es) para retirarse del inventario[n]de Personas.[n][f 1 1][e]

[msg msg_combine_sac_cost_fre [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255][f 3 1 1 0 0 55204]Dado que es la primera vez que veo esta[n]resonancia de poder, no habr茨 ning雨n[n]costo. 夷Est茨 seguro?[n][f 1 1][e]

[msg msg_combine_sac_cost_che [Margaret]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Necesito [f 0 1 2][f 2 4 0] yenes[f 0 1 0] para[n]esta Fusi吋n de Sacrificio. 夷Puedo[n]proceder?[n][f 1 1][e]

[msg combine_money_caro [Caroline]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡No tienes suficiente dinero! 斡Qu姻[n]verguenza![n][f 1 1][e]

[sel combine_book_summon_sel top]
[f 0 5 65278][f 2 1]Invocar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[sel combine_book_reg_all_sel top]
[f 0 5 65278][f 2 1]Registrar todo.[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[sel combine_book_reg_sel top]
[f 0 5 65278][f 2 1]Registrar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[sel combine_cmb_sel top]
[f 0 5 65278][f 2 1]Continuar[e]
[f 0 5 65278][f 2 1]No importa[e]

[sel combine_cmb_sac_free_sel top]
[f 0 5 65278][f 2 1]Continuar[e]
[f 0 5 65278][f 2 1]No importa[e]

[sel combine_cmb_sac_sel top]
[f 0 5 65278][f 2 1]Continuar[e]
[f 0 5 65278][f 2 1]No importa[e]

[sel combine_cmb_cpy_sel top]
[f 0 5 65278][f 2 1]Continuar[e]
[f 0 5 65278][f 2 1]No importa[e]

[sel combine_wcard_sel top]
[f 0 5 65278][f 2 1]Aceptar[e]
[f 0 5 65278][f 2 1]Cancelar[e]

[msg msg_combine_MESSAGE__048 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Debo ayudar a un Embaucador, 夷eh? Que[n]as胤 sea. Te ayudar姻 a limpiar tu[n]nombre.[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__049 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]De ahora en adelante, Embaucador, acepto[n]existir a tu lado y ayudar a tu[n]causa...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__050 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Nac胤 de ti, y contigo caminar姻 por esta[n]tierra... como c吋mplice voluntario[n]del Embaucador...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__051 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Abre los ojos... 斡Despierta, Embaucador![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__052 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n se atreve a llamarme...?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]El que hace brillar la luz sobre las[n]tinieblas... 夷Te atreves a hacer de la[n]nada tu objeto?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Yo determinar姻[n]el camino que tomes...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__053 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Qui姻n se atreve a llamarme...?[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Oh coraz吋n radiante que brilla en la[n]noche... Me convertir姻 en tu fuerza,[n]Embaucador...[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0]... Que tu luz[n]nunca se apague...[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__054 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Con una diosa como yo a tu lado,[n]conocer茨s la verdadera victoria![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__055 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Sigue luchando, Embaucador! 斡Seguir姻[n]tu camino y ser姻 tu fuerza![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__056 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Locura en mi mano derecha, tenacidad en[n]la izquierda... Ahora bien, 夷a qui姻n[n]destrozar姻 primero?[n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__057 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]Soy [f 0 1 1][f 2 4 1][f 0 1 0].[n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]Voy a ayudar al Embaucador...? No importa.[n]斡Traer姻 el dolor como siempre lo[n]hago![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__058 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Ja, ja, ja! Yo soy [f 0 1 1][f 2 4 1][f 0 1 0]![n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷Quieres mi fuerza...? Heh... Bien. Pero[n]no bajes la guardia, 斡o te aplastar姻[n]yo mismo![n][f 1 2 60][f 1 1][e]

[msg msg_combine_MESSAGE__059 [1]]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Ja, ja, ja! Yo soy [f 0 1 1][f 2 4 1][f 0 1 0]![n][f 1 2 60][f 1 1][e]
[f 0 5 65278][f 2 1][f 0 6 255 255]夷As胤 que un Embaucador quiere mi ayuda?[n]Me parece bien... 斡Aplastar姻 a[n]cualquiera que se te cruce![n][f 1 2 60][f 1 1][e]

[msg cmb_cmm_quest02 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]マハンマ[f 0 1 0]”を持った“[f 0 1 1]マタドール[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest03 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]暴れまくり[f 0 1 0]”を持った“[f 0 1 1]ド畏ン[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest04 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]ブフーラ[f 0 1 0]”を持った“[f 0 1 1]ネコショ胤雨ン[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest05 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]素早さの心得[f 0 1 0]”を持った“[f 0 1 1]ジャ威クフロスト[f 0 1 0]”…[n]貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest06 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]メギド[f 0 1 0]”を持った“[f 0 1 1]ヤタ遺ラス[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest07 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]メデ斡ラマ[f 0 1 0]”を持った“[f 0 1 1]ヤツフサ[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest08 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]テトラ吋ーン[f 0 1 0]”を持った“[f 0 1 1]遺ネーシャ[f 0 1 0]”… 貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest09 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]では次は…[n][f 1 1][e]
[f 0 5 65278][f 2 1]“[f 0 1 1]コンセントレ姻ト[f 0 1 0]”を持った“[f 0 1 1]トランペッター[f 0 1 0]”…[n]貴方なら見せてくださるわね。[n][f 1 1][e]
[f 0 5 65278][f 2 1]楽しみに、お待ちしております。[n][f 1 1][e]

[msg cmb_cmm_quest10 [マー遺レ7:]]
[f 0 5 65278][f 2 1][f 4 6 75 0 0 1]これ以上、貴方の心を見せてくれなくていいわ。 もう充分、分かっているから…[n][f 1 1][e]
[f 0 5 65278][f 2 1]…ありがとう。[n][f 1 1][e]
[f 0 5 65278][f 2 1]やはり貴方は、私が思った通りの人…[n][f 1 1][e]
[f 0 5 65278][f 2 1]時が来たら…私に答えをくれる人だわ…[n][f 1 1][e]
[f 0 5 65278][f 2 1]ふふっ… その時が楽しみね…[n][f 1 1][e]

