[msg MSG_BEST_1_1 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1074]Me siento preparado. 夷Te importa si me uno a la pelea?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_1_2 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1001]夷Te importa si me uno a la acci吋n? Estoy en forma en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_2_1 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2001]夷Crees que podr胤a unirme a ti? Siento que lo har姻 mejor de lo habitual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_2_2 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2031]Siento que estoy en forma. 夷Te importa si vengo contigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3001]Oye, 夷te importar胤a llevarme contigo? 斡Estoy en racha![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_3_2 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3030]Jeje, me siento imparable. 斡Ll姻vame contigo y no te decepcionar姻![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_4_1 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4051]Estoy llena de energ胤a y lista para traer el 斡"BAM"![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_4_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4130]斡Hiiiyah! 斡Mi indicador de energ胤a est茨 lleno! 斡D姻jame enfrentarlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_5_1 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5002]Oye, d姻jame pelear tambi姻n. Siento que estoy en plena forma en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_5_2 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 4 0 0][f 3 1 1 0 0 5073]Siento algo ardiendo por dentro. 斡Siento que puedo hacer cualquier cosa![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_6_1 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6134]斡S胤, mi voz est茨 en excelente forma ahora mismo! 斡D姻jame encargarme de la navegaci吋n![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_6_2 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6070]斡Los niveles de energ胤a est茨n al 100%! Deber胤a estar listo para empezar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_7_1 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 7107]斡Ponme ah胤! 斡Puedo con ellos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_7_2 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 7108]斡S胤, me siento genial! 斡Los enfrentar姻 a todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_8_1 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8126]夷Crees que pueda unirme? Estoy en excelente forma en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_8_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8106]Estoy bien de salud y energ胤a. Listo para pelear.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_9_1 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 9029]斡Oh, yo! 斡El胤geme a m胤! 斡Me siento muy confiado![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_9_2 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 9037]斡Hrrrrraaah! 斡Poder de Teddie al m茨ximo! 斡D姻jame encargarme de esto![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_10_1 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10069]S胤, me siento bien. Puedo resistir un golpe si lo necesitas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_10_2 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10031]Parece que estoy en buena forma en este momento. 夷Te importar胤a llevarme contigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_11_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11106]Jeje, 斡me siento emocionado! 斡La leyenda de Junpei Iori comienza justo despu姻s de esto![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_11_2 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11108]斡Oh, s胤, estoy en la zona! Debes llevarme contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_12_1 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031]Jeje, estos pu隠os est茨n listos para pelear. Col吋came en primera fila.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_12_2 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12108]Me siento m茨s afilado de lo habitual. 斡D姻jame salir y demostrarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_13_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13127]Parece que estoy en plena forma. 夷Te importar胤a llevarme contigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_13_2 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 0 0][f 3 1 1 0 0 13130]Estoy en perfectas condiciones. 斡Nuestros enemigos no tienen ninguna oportunidad![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_14_1 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 14001]Um... me siento bastante bien en este momento. 斡Creo que puedo ayudar![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_14_2 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 14126]夷Puedo intentar navegar? Me siento bastante segura en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_15_1 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 1 0][f 3 1 1 0 0 15102]Salida al m茨ximo. 斡Perm胤teme poner a prueba mi habilidad![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_15_2 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15101]斡Estoy en 吋ptima condici吋n! 斡Permiso para desplegar![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_16_1 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16030]斡Me siento genial! 斡D姻jame unirme a la pelea![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_16_2 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 0][f 3 1 1 0 0 16001]Um... 夷Podr胤as dejarme pelear? 斡Te prometo que no te arrepentir茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_17_1 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 0][f 3 1 1 0 0 17002]斡Guau, guau![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_17_2 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 0][f 3 1 1 0 0 17014]斡Guau! 斡Auuuu![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_18_1 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 2 0 0][f 3 1 1 0 0 18008]Oye, 夷te importa si me uno? No te arrepentir茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_18_2 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 2 0 0][f 3 1 1 0 0 18016]Huh, no me siento nada mal en este momento. Perm胤teme hacerles algo de da隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_19_1 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19001]Oye, 夷te importa si voy contigo? 斡Prometo darlo todo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_19_2 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 4 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19107]斡Siento que podr胤a enfrentar al mundo entero! 斡Vamos a por ello![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_64_1 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 1][f 3 1 1 0 0 23048]Oh, est茨s en sinton胤a. 斡Mu姻stranos de qu姻 est茨s hecho![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_64_2 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 1][f 3 1 1 0 0 23045]Oye, te ves bien. 斡Sal ah胤 y derrota a algunas Sombras![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_65_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21004]Oye, 夷te importa si me uno? Siento que quiero soltarme un poco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_65_2 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 1][f 3 1 1 0 0 21032]Amigo, estoy s雨per emocionado. Perm胤teme encargarme de esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_66_1 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 22001]Oye, 夷puedo ir? 斡Estoy lista![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_66_2 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 1][f 3 1 1 0 0 22106]斡S胤! 斡Estoy en llamas! 斡Lista para la pelea![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_67_1 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23001]斡Llevame ah胤 afuera! Puedo sentir que voy a hacerlo genial.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_67_2 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052]Nyahaha... Estoy en plena forma. Este es mi momento para brillar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_68_1 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24097]Por favor, perm胤teme unirme. Conf胤o en que cumplir姻 tus expectativas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_68_2 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 1][f 3 1 1 0 0 24108]斡Estoy lleno de inspiraci吋n! 斡Este es mi momento![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_69_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 25001]夷Puedo ir? Siento que estoy en buena forma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_69_2 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 4 0 1][f 3 1 1 0 0 25071]Estoy rebosante de energ胤a. Perm胤teme ayudar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_70_1 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26107]斡Me siento 3 veces m茨s poderosa! 斡Vamos all茨![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_70_2 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 1][f 3 1 1 0 0 26029]斡Estoy lista! 斡Siento que podr胤a navegar con los ojos cerrados![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_71_1 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 0 0][f 3 1 1 0 0 27126]夷Est茨 bien si me encargo de esto? Te prometo que me las arreglar姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_71_2 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 1][f 3 1 1 0 0 27031]*risa* Me siento genial. Creo que podr姻 ser de gran ayuda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_72_1 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 28001]Siento que podr胤a ayudar. 夷Me dejas unirme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_72_2 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 1][f 3 1 1 0 0 28137]夷Estar胤a bien si me encargo de esto? Me siento inusualmente capaz en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_0 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6003]夷Te diriges a la proyecci吋n especial?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Tengo la navegaci吋n. 斡Aseg雨rate de que Aigis y Haru est姻n en el grupo![n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_1 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15007]夷Vas a la proyecci吋n especial, verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Por favor, comprueba que Haru y yo estemos en el grupo, y que Rise nos navega.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_2 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 27031]夷Vas a la proyecci吋n especial?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Aseg雨rate de que Aigis y yo estemos en el grupo, y que Rise sea la navegadora.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_47 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 0][f 3 1 1 0 0 23072]Si vas a la proyecci吋n especial, aseg雨rate de llevarme en el grupo principal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_48 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 1068]Si te diriges a la proyecci吋n especial, aseg雨rate de llevarme contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_49 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 2117]Si vas a la proyecci吋n especial, necesito estar en el grupo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_50 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 19127]Si vas a la proyecci吋n especial, aseg雨rate de incluirme en el grupo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_EX_BEST_00]
[f 0 5 65278][f 2 1]※Force quest targets to enter Great[n]Condition.[n][f 1 3 65535][f 1 1][e]

