[msg MSG_BEST_1_1 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0]　[n][f 3 1 1 0 0 1074]Estoy a la altura de la tarea. 夷Te importa[n]si me uno a la pelea?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_1_2 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 13 0 0 0]　[n][f 3 1 1 0 0 1001]Mind if I get in the action? Estoy en buena[n]forma ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_2_1 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0]　[n][f 3 1 1 0 0 2001]夷Crees que podr胤a acompa隠arte? Siento que[n]lo har姻 mejor de lo habitual.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_2_2 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0]　[n][f 3 1 1 0 0 2031]Siento que estoy en buena forma. 夷Te importa[n]si vengo contigo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3001]Oye, 夷te importa llevarme? 斡Estoy en un rollo[n]ahora mismo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_3_2 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3030]斡Me siento imparable! Tr茨eme y no te[n]decepcionar茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_4_1 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4051]斡Estoy listo para traer el "BAM"![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_4_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 4130]斡Hiiiyah! 斡Mi man吋metro est茨 lleno! 斡D姻jenme![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_5_1 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 2 0 0][f 3 1 1 0 0 5002]Oye, d姻jame pelear tambi姻n. Siento que estoy[n]en forma superior ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_5_2 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 4 0 0][f 3 1 1 0 0 5073]Hay algo que se quema dentro. 斡Siento que[n]puedo hacer cualquier cosa![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_6_1 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6134]斡S胤, mi voz est茨 en buena forma ahora mismo![n]斡Dejadme navegar![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_6_2 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6070]斡Oye! 斡Los niveles de energ胤a est茨n al 100%![n]斡Deber胤a ser bueno ir![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_7_1 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 7107]斡S茨quenme! 斡Puedo tomarlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_7_2 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 0][f 3 1 1 0 0 7108]斡S胤, me siento genial! 斡Los llevar姻 a todos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_8_1 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8126]夷Crees que podr胤a venir? Estoy en excelente[n]forma ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_8_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 0][f 3 1 1 0 0 8106]Soy bueno en salud y energ胤a. Listo para[n]luchar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_9_1 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 0][f 3 1 1 0 0 9029]斡Yo! 斡Escogeme! 斡Me siento confiado![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_9_2 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 4 0 0][f 3 1 1 0 0 9037]斡Hrrrrraaah! 斡El poder de Teddie al m茨ximo![n]斡D姻jame esto![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_10_1 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10069]S胤, me siento bien. 斡Puedo dar un golpe si[n]me necesitas![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_10_2 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 2 0 0][f 3 1 1 0 0 10031]Parece que estoy en buena forma ahora mismo.[n]夷Te importa llevarme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_11_1 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11106]斡Lo siento! La leyenda de Junpei Iori comienza,[n]justo despu姻s de esto![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_11_2 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 0 0][f 3 1 1 0 0 11108]斡S胤, estoy en la zona! Tienes que llevarme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_12_1 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12031]Estos pu隠os est茨n listos para una pelea.[n]Ponme en el frente.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_12_2 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 0][f 3 1 1 0 0 12108]Me siento m茨s fuerte de lo habitual. 斡D姻jame[n]salir y probarlo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_13_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 0][f 3 1 1 0 0 13127]Parece que estoy en primera forma. 夷Te[n]importar胤a llevarme?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_13_2 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 0 0][f 3 1 1 0 0 13130]Estoy en perfectas condiciones. 斡Nuestros[n]enemigos no tienen ninguna oportunidad![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_14_1 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 14001]Um... Me siento bastante bien ahora. 斡Creo[n]que puedo ayudar![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_14_2 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 0][f 3 1 1 0 0 14126]夷Puedo probar mi mano para navegar? Me siento[n]muy confiado en este momento.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_15_1 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 0 1 0][f 3 1 1 0 0 15102]Salida al m茨ximo. 斡Perm胤tanme probar mi[n]calmante![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_15_2 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15101]斡Estoy en condiciones de m茨xima! 斡Permiso[n]para desplegar![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_16_1 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 16030]斡Me siento genial! 斡D姻jame unirme a la pelea![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_16_2 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 0][f 3 1 1 0 0 16001]Um... 夷Podr胤as dejarme pelear? 斡Te prometo[n]que no te arrepentir茨s![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_17_1 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 0][f 3 1 1 0 0 17002]斡Barco, corteza![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_17_2 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 2 0 0][f 3 1 1 0 0 17014]斡Arf! Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_18_1 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 2 0 0][f 3 1 1 0 0 18008]Oye, 夷te importa si vengo? No te[n]arrepentir茨s.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_18_2 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 2 0 0][f 3 1 1 0 0 18016]No me siento mal por ahora. Dame un poco de[n]da隠o.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_19_1 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 19001]夷Te importa si vengo contigo? 斡Prometo darle[n]todo![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_19_2 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 18 4 0][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 19107]斡Siento que podr胤a tomar el mundo! 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_64_1 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 1][f 3 1 1 0 0 23048]Est茨s en punto. 斡Mu姻stranos de qu姻 est茨s[n]hecho![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_64_2 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 1][f 3 1 1 0 0 23045]Hey, estoy bien. 斡Sal de ah胤 y derriba algunas[n]Sombras![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_65_1 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 0][f 3 1 1 0 0 21004]夷Te importa si vengo? Me siento como soltar[n]un poco.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_65_2 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 2 0 1][f 3 1 1 0 0 21032]Amigo, soy una maldita bomba. Lemme cuide de[n]esto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_66_1 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 0][f 3 1 1 0 0 22001]夷Puedo ir? 斡Estoy listo para irme![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_66_2 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 1][f 3 1 1 0 0 22106]斡S胤! 斡Estoy ardiendo! 斡Listo para una pelea![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_67_1 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23001]斡S茨quenme! 斡Puedo decir que lo har姻 genial![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_67_2 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 23052]Nyahaha... Estoy en la forma superior. Este[n]es mi momento de brillar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_68_1 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 24097]Por favor, perm胤tanme venir. Conf胤o en que[n]cumplir姻 tus expectativas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_68_2 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 4 0 1][f 3 1 1 0 0 24108]斡Estoy rebosando de inspiraci吋n! 斡Este es mi[n]momento![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_69_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 25001]夷Puedo ir? Siento que estoy en buena forma.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_69_2 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 4 0 1][f 3 1 1 0 0 25071]Estoy lleno de energ胤a. Perm胤tame ayudar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_70_1 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 0][f 3 1 1 0 0 26107]斡Soy 3 veces el poder! 斡Vamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_70_2 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 1][f 3 1 1 0 0 26029]斡Voy a ir! 斡Siento que podr胤a navegar con[n]los ojos cerrados![n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_71_1 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 0 0][f 3 1 1 0 0 27126]夷Estar胤a bien si manejara esto? Prometo que[n]me quedar姻.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_71_2 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 1][f 3 1 1 0 0 27031]Me siento genial. Creo que ser姻 una gran[n]ayuda.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_72_1 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 0][f 3 1 1 0 0 28001]Siento como si pudiera ayudar ahora mismo.[n]夷Puedo ir?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BEST_72_2 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 2 0 1][f 3 1 1 0 0 28137]夷Estar胤a bien si me encargara de esto? Me[n]siento inusualmente capaz ahora mismo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_0 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 0][f 3 1 1 0 0 6003]夷Se dirige a la proyecci吋n especial?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Tengo la navegaci吋n. 斡Aseg雨rese de que Aigis[n]y Haru-san est姻n en el grupo![n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_1 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 2 0 0][f 3 1 1 0 0 15007]Vas a la proyecci吋n especial, 夷verdad?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Por favor, confirme que Haru-san y yo estamos[n]en la fiesta, y que Rise-san es el[n]navegante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_32_2 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 12 0 0][f 3 1 1 0 0 27031]夷Vas a la proyecci吋n especial?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1]Aseg雨rese de que Aigis-san y yo estamos en[n]la fiesta, y que Rise-chan es el[n]navegante.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_47 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 64 4 32 3][f 4 6 23 2 0 0][f 3 1 1 0 0 23072]Si est茨s tomando la prueba especial, aseg雨rate[n]de estar en la fiesta principal.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_48 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 13 0 0 0]　[n][f 3 1 1 0 0 1068]Si te diriges a la proyecci吋n especial,[n]aseg雨rate de llevarme.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_49 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 2 0 0][f 1 5][f 6 1 16 0 0 0]　[n][f 3 1 1 0 0 2117]Si vas a la proyecci吋n especial, tendr姻 que[n]estar en la fiesta.[n][f 1 3 65535][f 1 1][e]

[msg MSG_QUEST_50 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 1][f 1 5][f 6 1 27 0 0 0]　[n][f 3 1 1 0 0 19127]Si haces la prueba especial, aseg雨rate de[n]incluirme en el grupo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_EX_BEST_00]
[f 0 5 65278][f 2 1]※Objetivos de b雨squeda para entrar en Gran[n]Condici吋n.[n][f 1 3 65535][f 1 1][e]

