[msg PARTY_EDIT_SCR_MSG]
[f 0 5 65278][f 2 1]Bienvenido.[n][f 1 1][e]

[msg PARTY_EDIT_TUTORIAL_TOP]
[f 0 5 65278][f 2 1]Este es el mensaje tutorial en la pantalla superior para "Cambiar miembros del grupo".[n][f 1 1][e]

[msg MSG_TUTORIAL_NAVI_OPEN_S]
[f 0 5 65278][f 2 1]Los navegadores tienen habilidades [f 0 1 2]solo de combate[f 0 1 0] y[n][f 0 1 2]solo de exploraci吋n[f 0 1 0]. Si separas a los navegadores de combate y exploraci吋n,[n]solo podr茨n [f 0 1 2]usar las habilidades que correspondan a c吋mo los hayas clasificado[f 0 1 0].[n][f 1 1][e]

