[msg PARTY_EDIT_SCR_MSG]
[f 0 5 65278][f 2 1]Bienvenido.[n][f 1 1][e]

[msg PARTY_EDIT_TUTORIAL_TOP]
[f 0 5 65278][f 2 1]Este es el mensaje tutorial en la[n]pantalla TOP para "Los Miembros del Partido Cambio"[n][f 1 1][e]

[msg MSG_TUTORIAL_NAVI_OPEN_S]
[f 0 5 65278][f 2 1]Los navegantes tienen habilidades [f 0 1 2]combat-only[f 0 1 0] y [f 0 1 2] habilidades de explotaci吋n-雨nicamente[f 0 1 0]. Si separas a los navegantes de[n]combate y exploraci吋n, ellos pueden [f 0 1 2] usar solamente las habilidades que[n]corresponden con c吋mo las has clasificado[f 0 1 0].[n][f 1 1][e]

