[msg start_01]
[f 0 5 65278][f 2 1]Entrada[n][e]

[msg start_02]
[f 0 5 65278][f 2 1]磁軸[n][e]

[msg quest_01]
[f 0 5 65278][f 2 1]Pantalla de cine[n][e]

[msg quest_02]
[f 0 5 65278][f 2 1]※吋ット０２[n][e]

[msg quest_03]
[f 0 5 65278][f 2 1]Escaleras hacia la 1ra Avenida[n][e]

[msg quest_04]
[f 0 5 65278][f 2 1]Escaleras hacia la Plaza Kamoshida[n][e]

[msg quest_05]
[f 0 5 65278][f 2 1]※吋ット０５[n][e]

[msg quest_06]
[f 0 5 65278][f 2 1]Escaleras hacia el 威rea 1[n][e]

[msg quest_07]
[f 0 5 65278][f 2 1]Escaleras hacia la 1ra Avenida[n][e]

[msg quest_08]
[f 0 5 65278][f 2 1]Escaleras hacia la Plaza Kamoshida[n][e]

[msg quest_09]
[f 0 5 65278][f 2 1]Escaleras hacia la Plaza Kamoshida[n][e]

[msg quest_10]
[f 0 5 65278][f 2 1]Escaleras hacia el Fin de la Isla[n][e]

[msg quest_11]
[f 0 5 65278][f 2 1]Pantalla de cine[n][e]

[msg quest_12]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_13]
[f 0 5 65278][f 2 1]Escaleras hacia el 威rea 2[n][e]

[msg quest_14]
[f 0 5 65278][f 2 1]Escaleras hacia el 威rea 1[n][e]

[msg quest_15]
[f 0 5 65278][f 2 1]Escaleras hacia el 威rea 3[n][e]

[msg quest_16]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_17]
[f 0 5 65278][f 2 1]Escaleras hacia la 3ra Avenida[n][e]

[msg quest_18]
[f 0 5 65278][f 2 1]Escaleras hacia la Zona 2[n][e]

[msg quest_19]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_20]
[f 0 5 65278][f 2 1]※吋ット２０[n][e]

[msg quest_21]
[f 0 5 65278][f 2 1]Escaleras hacia el Fin de la Isla[n][e]

[msg quest_22]
[f 0 5 65278][f 2 1]Escaleras hacia la Zona 2[n][e]

[msg quest_23]
[f 0 5 65278][f 2 1]Escaleras al Piso 1 del Laboratorio[n][e]

[msg quest_24]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_25]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_26]
[f 0 5 65278][f 2 1]Escaleras hacia la Zona 3[n][e]

[msg quest_27]
[f 0 5 65278][f 2 1]Pantalla de cine[n][e]

[msg quest_28]
[f 0 5 65278][f 2 1]Escaleras hacia la Zona 3[n][e]

[msg quest_29]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_30]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_31]
[f 0 5 65278][f 2 1]Escaleras hacia la Plaza Kamoshida[n][e]

[msg quest_32]
[f 0 5 65278][f 2 1]Escaleras hacia la 2da Avenida[n][e]

[msg quest_33]
[f 0 5 65278][f 2 1]Escaleras al Piso 2 del Laboratorio[n][e]

[msg quest_34]
[f 0 5 65278][f 2 1]※吋ット３４[n][e]

[msg quest_35]
[f 0 5 65278][f 2 1]Pantalla de cine[n][e]

[msg quest_36]
[f 0 5 65278][f 2 1]Escaleras al Piso 1 del Laboratorio[n][e]

[msg quest_37]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_38]
[f 0 5 65278][f 2 1]Escaleras al Piso 1 del Laboratorio.[n][e]

[msg quest_39]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_40]
[f 0 5 65278][f 2 1]Escaleras hacia el Acto 6[n][e]

[msg quest_41]
[f 0 5 65278][f 2 1]Pantalla de cine[n][e]

[msg quest_42]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_43]
[f 0 5 65278][f 2 1]Entrada a la proyecci吋n especial[n][e]

[msg quest_44]
[f 0 5 65278][f 2 1]※吋ット４４[n][e]

[msg quest_45]
[f 0 5 65278][f 2 1]Escaleras hacia el Acto 2[n][e]

[msg quest_46]
[f 0 5 65278][f 2 1]Escaleras hacia el Acto 4[n][e]

[msg quest_47]
[f 0 5 65278][f 2 1]Escaleras hacia la 3ra Avenida[n][e]

[msg quest_48]
[f 0 5 65278][f 2 1]Escaleras hacia el 威rea 4[n][e]

[msg quest_49]
[f 0 5 65278][f 2 1]Escaleras al Piso 2 del Laboratorio[n][e]

[msg quest_50]
[f 0 5 65278][f 2 1]Escaleras hacia el Acto 7[n][e]

