[msg MSG_BTL_001]
[f 0 5 65278][f 2 1][f 0 6 255 255]Now, Fox![n][f 1 1][e]

[msg MSG_BTL_002]
[f 0 5 65278][f 2 1][f 0 6 255 255]Let's do it![n][f 1 1][e]

[msg MSG_BTL_003]
[f 0 5 65278][f 2 1][f 0 6 255 255]Except... I've grown famished...[n][f 1 1][e]

[msg MSG_BTL_004]
[f 0 5 65278][f 2 1][f 0 6 255 255]Fine... Eat this.[n][f 1 1][e]

[msg MSG_BTL_005]
[f 0 5 65278][f 2 1][f 0 6 255 255]I've got protein, too! Here![n][f 1 1][e]

