[msg MSG_000 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 54123]Oh Dios, parece que esta pr吋xima prueba[n]especial es un thriller de crimen...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Ha habido una serie de incidentes sospechosos[n]en Kamo City... Su tarea es llegar al[n]fondo del misterio.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 3][f 3 1 1 0 0 0]Parece que deber胤amos entrar.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 6][f 3 1 1 0 0 13013][f 6 1 2 0 0 4]夷Qu姻 tipo de incidentes han ocurrido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 74 0 100 0][f 3 1 1 0 0 54030]S吋lo tengo un esbozo de las circunstancias...[n]Francamente, no tengo ni idea.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 3][f 3 1 1 0 0 18133][f 6 1 2 0 0 9]No puedes ser tan insensato...[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 0]La mayor parte de su tarea ser茨 descubrir[n]los detalles de dichos incidentes. No es[n]mi trabajo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 0 0 6][f 3 1 1 0 0 11078]Amigo, si ni siquiera sabes lo que pas吋,[n]夷entonces qu姻 diablos se supone que hagamos?[n][f 1 3 65535][f 1 1][e]

[sel SEL_007 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 3]Es un misterio.[f 2 7 1 64 8 32][e]
[f 0 5 65278][f 2 1]D胤selo, detective Ace.[f 2 7 1 64 6 32][e]

[msg MSG_008 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 0][f 3 1 1 0 0 54029]Pero por supuesto. Es un thriller de crimen,[n]despu姻s de todo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 6][f 3 1 1 0 0 0]Quiero decir, ella no est茨 equivocada...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 2 1 0][f 3 1 1 0 0 11131][f 6 1 2 0 0 6]Hey, este tipo lo tiene! S胤, ni siquiera[n]Junpei, Ace Detective podr胤a resolver este![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 13 6 0 3][f 3 1 1 0 0 13091]Muy bien, basta de tonter胤as...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_1 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 4 1 0][f 3 1 1 0 0 13081][f 6 1 2 0 0 3]Apenas tenemos nada que pasar. 夷Qu姻 deber胤amos[n]hacer?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 6][f 3 1 1 0 0 25089]Bueno, uno de los primeros pasos en cualquier[n]investigaci吋n es examinar la escena[n]del crimen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012_1 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 0][f 3 1 1 0 0 0]Creo que ser胤a mejor que sali姻ramos a buscar[n]pistas.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 1 0][f 3 1 1 0 0 13075]Ya veo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Justo lo que esperaba de la hija de un polic胤a.[n]Me alegra poder contar contigo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 12 100 1][f 3 1 1 0 0 54058]斡De hecho! Examinar las escenas del crimen[n]seguramente ser茨 雨til.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015_1 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 5 1][f 3 1 1 0 0 0]Como tal, me he tomado la libertad de marcar[n]los lugares donde se han producido estos[n]incidentes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 65 8 1 3][f 3 1 1 0 0 0]Eso es extra隠amente conveniente...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 6][f 3 1 1 0 0 25114]No me preocupar胤a. Vamos a intentarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 0 2 0][f 3 1 1 0 0 54113]Ahora bien, estoy muy ansioso por ver esta[n]historia de detectives.[n][f 1 3 65535][f 1 1][e]

