[msg MSG_000 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9008][f 6 1 2 0 0 4]斡Hay dos puntos warp aqu胤! 夷Cu茨l tomamos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 0]Mmm... Este es el primer tenedor real en la[n]carretera que hemos encontrado.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si adivinamos mal aqu胤, podr胤a reducir[n]significativamente nuestros esfuerzos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 11008]夷Qu姻 hay de ese papelback? 夷Qu姻 dijo?[n][f 1 3 65535][f 1 1][e]

[sel SEL_003 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 3]GROWL.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]GROW.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]CROW.[f 2 7 1 20 0 32][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 22080]No, era "GROW". Estoy bastante seguro de que[n]no hab胤a ning雨n L extra all胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 3][f 3 1 1 0 0 0]Pero un L lo har胤a sombr胤o...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 22111]Crece si quieres, pero estoy bastante[n]acostumbrado a corregir a la gente en L's y[n]R's...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 10 0 3][f 3 1 1 0 0 0]斡Grrr... Rrrrgh... Grrrawr![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡GrrAWK![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 9 6 0 3][f 3 1 1 0 0 0]Owie... me escup胤 la lengua...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 6][f 3 1 1 0 0 3022]夷De verdad tienes una lengua ah胤? Son noticias[n]para m胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 25068]As胤 es, fue "GROW". Como una planta creciendo[n]m茨s grande. O una persona madurando,[n]supongo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 3][f 3 1 1 0 0 0]夷As胤 lo dices? Pens姻 que rimaba con "chow"[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 1][f 3 1 1 0 0 0]Deber胤as prestar m茨s atenci吋n en ingl姻s...[n]Si escuchaste al profesor, sabr胤as la[n]pronunciaci吋n.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 12 0 3][f 3 1 1 0 0 21041]S胤, s胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 22080]No, era "GROW". Era un "G", no un "C"[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 3][f 3 1 1 0 0 0]"CROW". Como en el p茨jaro de caza furtiva,[n]supongo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 12 100 6][f 3 1 1 0 0 6616][f 3 1 6 0 0 500]Crow, 夷eh? 夷No era el nombre de c吋digo de[n]Akechi?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 0]Crow es estudiante y detective, 夷eh? Espero[n]que no se quede con el estr姻s.[n]夷Entendido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 3][f 3 1 1 0 0 10091]*Suspira* Se necesita coraje para entregar[n]un juego tan malo con ese tipo de[n]entusiasmo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 0]夷No vas a unirte a la conversaci吋n?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]Bueno, bueno, una charla con Aragaki![n]Esto es raro.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Todav胤a soy bastante nuevo para el grupo, y[n]no soy bueno con las multitudes, as胤 que[n]prefiero mantener mi distancia.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 18133]夷S胤? Bueno, te sientas bien.[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 0]夷Y t雨?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Siempre te veo caminando unos pasos detr茨s[n]del resto del grupo. 夷Hay alguna raz吋n[n]para eso?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 0]Tch... no tengo una buena raz吋n. Es algo que[n]hago.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 2 0 3][f 3 1 1 0 0 28033]No quise ofenderme. No tienes que decirme si[n]no quieres.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 3][f 3 1 1 0 0 0]Realmente se llevan bien, 夷no?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Cuando estoy en medio de eso, es casi demasiado[n]para m胤...[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 6 0 1][f 3 1 1 0 0 18096]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 6 1 3][f 3 1 1 0 0 0]Bueno, supongo que estoy m茨s c吋modo as胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 1][f 3 1 1 0 0 0]... Ahora eres t雨.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 3][f 3 1 1 0 0 28112]斡Bien! Parece que nos estamos moviendo de[n]nuevo.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]"GROW", 夷verdad? Me pregunto cu茨l es el camino[n]correcto...[n][f 1 3 65535][f 1 1][e]

