[msg YUKIKO_FOE_FOLLOW_START_]
It looks like the FOE's after us!

[msg YUKIKO_FOE_FOLLOW_START__2]
It's an FOE! Look out!

[msg YUKIKO_FOE_FOLLOW_START__3]
An FOE's heading our way!

[msg YUKIKO_FOE_NEAR_1]
It's an FOE! Be careful, everyone!

[msg YUKIKO_FOE_NEAR_2]
An FOE's close. We should be careful!

[msg YUKIKO_FOE_NEAR_3]
Isn't that an FOE?

[msg YUKIKO_FOE_FOLLOW_END_1]
Looks like it gave up on us.

[msg YUKIKO_FOE_FOLLOW_END_2]
Thank goodness we got away.

[msg YUKIKO_FOE_FOLLOW_END_3]
Phew... It went away.

[msg YUKIKO_KANSI_REACTION_1]
Quietly... Quietly...

[msg YUKIKO_KANSI_REACTION_2]
This is pretty nerve-racking.

[msg YUKIKO_KANSI_REACTION_3]
We should be careful not to get[n]caught.

[msg YUKIKO_DENKISAKU_REACTIO]
This trap's proving to be quite an[n]obstacle.

[msg YUKIKO_DENKISAKU_REACTIO_2]
Couldn't we just destroy this gate?

[msg YUKIKO_DENKISAKU_REACTIO_3]
It would be a lot easier if I could[n]just burn this down...

[msg YUKIKO_KYOUHU_REACTION_1]
Ahahahaha!

[msg YUKIKO_KYOUHU_REACTION_2]
Huh!?

[msg YUKIKO_KYOUHU_REACTION_3]
Whoa!

[msg YUKIKO_STAIR_FIND_1]
Do you think we can go on from here?

[msg YUKIKO_STAIR_FIND_2]
Looks like we can go on to the next[n]floor.

[msg YUKIKO_STAIR_FIND_3]
I think we can keep going. Why don't[n]we check it out?

[msg YUKIKO_TREASURE_FIND_1]
Look, it's a treasure chest!

[msg YUKIKO_TREASURE_FIND_2]
It's a treasure chest. Should we open[n]it?

[msg YUKIKO_TREASURE_FIND_3]
I wonder what's inside.

[msg YUKIKO_CHECK_WALL_1]
Oh, look over there!

[msg YUKIKO_CHECK_WALL_2]
Hmm... I feel like there's something[n]here.

[msg YUKIKO_CHECK_WALL_3]
Why don't we take a look around here?

[msg YUKIKO_SWITCH_FIND_1]
Oh, a switch.

[msg YUKIKO_SWITCH_FIND_2]
Ooh, we're going to have to press the[n]switch, aren't we?

[msg YUKIKO_SWITCH_FIND_3]
Doesn't that look like a switch?

[msg YUKIKO_SHORTCUT_FIND_1]
I think we can pass through there.

[msg YUKIKO_SHORTCUT_FIND_2]
Do you think we can use that as a[n]shortcut?

[msg YUKIKO_SHORTCUT_FIND_3]
Hey, I think we can go through there.

[msg YUKIKO_PARTY_DEAD_1]
【パーティの半分以上が死んでいる】 ダミーメッセージ１

[msg YUKIKO_PARTY_DEAD_2]
【パーティーの半分以上が死んでいる】 ダミーメッセージ２

[msg YUKIKO_PARTY_DEAD_3]
【パーティーの半分以上が死んでいる】 ダミーメッセージ３

[msg YUKIKO_FOE_WARNING_NEAR_]
The FOE's still coming!

[msg YUKIKO_FOE_WARNING_NEAR__2]
We're being followed. Let's be[n]careful.

[msg YUKIKO_FOE_WARNING_NEAR__3]
The FOE's still chasing us!

[msg YUKIKO_PARTY_HPTP10_1]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ１

[msg YUKIKO_PARTY_HPTP10_2]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ２

[msg YUKIKO_PARTY_HPTP10_3]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ３

[msg YUKIKO_PARTY_HP10_1]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ１

[msg YUKIKO_PARTY_HP10_2]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ２

[msg YUKIKO_PARTY_HP10_3]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ３

[msg YUKIKO_1PERSON_HPTP10_1]
I'm sorry, I can't go on...

[msg YUKIKO_1PERSON_HPTP10_2]
This isn't good. I think I'm at my[n]limits...

[msg YUKIKO_1PERSON_HPTP10_3]
Do you think we could take a[n]break...?

[msg YUKIKO_PARTY_TP10_1]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ１

[msg YUKIKO_PARTY_TP10_2]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ２

[msg YUKIKO_PARTY_TP10_3]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ３

[msg YUKIKO_1PERSON_HP10_1]
Someone, please heal me...

[msg YUKIKO_1PERSON_HP10_2]
My health's getting too low...

[msg YUKIKO_1PERSON_HP10_3]
Please, someone heal me...

[msg YUKIKO_1PERSON_TP10_1]
Nnh... I don't think I have any more[n]energy...

[msg YUKIKO_1PERSON_TP10_2]
*sigh* I'm getting tired...

[msg YUKIKO_1PERSON_TP10_3]
It's no good... I don't think I can[n]move another inch...

[msg YUKIKO_ITEM_90_BATTLE_1]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ１

[msg YUKIKO_ITEM_90_BATTLE_2]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ２

[msg YUKIKO_ITEM_90_BATTLE_3]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ３

[msg YUKIKO_1PERSON_HP80_1]
Hehe! This is nothing for us!

[msg YUKIKO_1PERSON_HP80_2]
I can keep going. Just leave it to[n]me.

[msg YUKIKO_1PERSON_HP80_3]
I think we can keep going at this[n]rate.

[msg YUKIKO_BATTLE_CHANGE_DUN]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ１

[msg YUKIKO_BATTLE_CHANGE_DUN_2]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ２

[msg YUKIKO_BATTLE_CHANGE_DUN_3]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ３

[msg YUKIKO_ITEM_90_DUNGEON_1]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ１

[msg YUKIKO_ITEM_90_DUNGEON_2]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg YUKIKO_ITEM_90_DUNGEON_3]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg YUKIKO_DUNGEON_START_1]
Don't push yourselves too hard,[n]everyone.

[msg YUKIKO_DUNGEON_START_2]
We didn't forget anything, did we?

[msg YUKIKO_DUNGEON_START_3]
We should be prepared for anything.

[msg YUKIKO_QUEST_START_1]
Let's do our best to succeed.

[msg YUKIKO_QUEST_START_2]
Let's go about this carefully!

[msg YUKIKO_QUEST_START_3]
Don't worry, I'm sure we can do it.

[msg YUKIKO_TOUHA_25_1]
I feel like we still have a lot more[n]exploring to do...

[msg YUKIKO_TOUHA_25_2]
We still have a way to go, but let's[n]keep doing our best.

[msg YUKIKO_TOUHA_50_1]
I think we're about halfway there.

[msg YUKIKO_TOUHA_50_2]
Mm, we're on a roll. Let's keep it[n]up!

[msg YUKIKO_TOUHA_75_1]
Phew... We've walked quite a long[n]way.

[msg YUKIKO_TOUHA_75_2]
Just a little more and this floor's[n]all done.

[msg YUKIKO_TOUHA_100_1]
We've walked every inch of this[n]floor. Well done.

[msg YUKIKO_TOUHA_100_2]
We've walked every last inch of this[n]floor!

[msg YUKIKO_MAPPING_ICON_ALL_]
The map's looking really nice, thanks[n]to you.

[msg YUKIKO_MAPPING_ICON_ALL__2]
Wow, this map's really precise!

[msg YUKIKO_MAPPING_ICON_KAID]
I'm sure it will help if we know[n]where the stairs are.

[msg YUKIKO_MAPPING_ICON_KAID_2]
It's good to mark down points of[n]interest.

[msg YUKIKO_MAPPING_CHANGE_CO]
Ah, you're using that color!?

[msg YUKIKO_MAPPING_CHANGE_CO_2]
You have a keen eye for art. Maybe[n]I'll try it too.

[msg YUKIKO_MAPPING_ICON_DEL_]
It's best to throw away things we[n]don't need.

[msg YUKIKO_MAPPING_ICON_DEL__2]
Mmhm, much cleaner now.

[msg YUKIKO_MAPPING_MEMO_1]
It's important to take notes.

[msg YUKIKO_MAPPING_MEMO_2]
Make sure you write it down so you[n]don't forget.

[msg YUKIKO_DOOR_OPEN_1]
I guess we're going this way.

[msg YUKIKO_DOOR_OPEN_2]
Let's keep going.

[msg YUKIKO_DOOR_OPEN_3]
What do you think is on the other[n]side?

[msg YUKIKO_KARITORU_ENCOUNT_]
【刈り取るものとエンカウントした】 ダミーメッセージ１

[msg YUKIKO_KARITORU_ENCOUNT__2]
【刈り取るものとエンカウントした】 ダミーメッセージ２

[msg YUKIKO_KARITORU_ENCOUNT__3]
【刈り取るものとエンカウントした】 ダミーメッセージ３

