[msg MITURU_FOE_FOLLOW_START_]
We've been detected by an FOE!

[msg MITURU_FOE_FOLLOW_START__2]
Tsk... An FOE has locked onto us!

[msg MITURU_FOE_FOLLOW_START__3]
We're being tracked by an FOE!

[msg MITURU_FOE_NEAR_1]
There's an FOE close by...

[msg MITURU_FOE_NEAR_2]
An FOE. So they're here, as well.

[msg MITURU_FOE_NEAR_3]
That's an FOE. Stay alert!

[msg MITURU_FOE_FOLLOW_END_1]
It appears we've eluded that FOE.

[msg MITURU_FOE_FOLLOW_END_2]
Good... It seems it's given up.

[msg MITURU_FOE_FOLLOW_END_3]
Our escape is secured...

[msg MITURU_KANSI_REACTION_1]
Exercise caution here.

[msg MITURU_KANSI_REACTION_2]
What an inconvenient trap.

[msg MITURU_KANSI_REACTION_3]
Make sure to prioritize stealth...

[msg MITURU_DENKISAKU_REACTIO]
I advise not touching that.

[msg MITURU_DENKISAKU_REACTIO_2]
We can proceed after we shut off the[n]power.

[msg MITURU_DENKISAKU_REACTIO_3]
Shutting off the electricity would be[n]the prudent course.

[msg MITURU_KYOUHU_REACTION_1]
Ngh...!

[msg MITURU_KYOUHU_REACTION_2]
What!?

[msg MITURU_KYOUHU_REACTION_3]
Ugh, the wind!?

[msg MITURU_STAIR_FIND_1]
We can proceed onward. Any[n]objections?

[msg MITURU_STAIR_FIND_2]
There's a stairway over there.

[msg MITURU_STAIR_FIND_3]
Stairs... The next floor lies ahead.

[msg MITURU_TREASURE_FIND_1]
A treasure box... Shall we?

[msg MITURU_TREASURE_FIND_2]
Hm. There's a treasure box.

[msg MITURU_TREASURE_FIND_3]
There's treasure ahead.

[msg MITURU_CHECK_WALL_1]
Hm...? What's that?

[msg MITURU_CHECK_WALL_2]
...Something's bothering me. Do you[n]mind if we investigate?

[msg MITURU_CHECK_WALL_3]
What is that...? Let's take a closer[n]look.

[msg MITURU_SWITCH_FIND_1]
Hm? Is this... a switch?

[msg MITURU_SWITCH_FIND_2]
Look. There's a switch.

[msg MITURU_SWITCH_FIND_3]
A switch...? What's our move?

[msg MITURU_SHORTCUT_FIND_1]
Hm? It appears we can pass through[n]there.

[msg MITURU_SHORTCUT_FIND_2]
Good. This should make a fine[n]shortcut.

[msg MITURU_SHORTCUT_FIND_3]
Look. That should serve as a[n]shortcut.

[msg MITURU_PARTY_DEAD_1]
【パーティの半分以上が死んでいる】 ダミーメッセージ１

[msg MITURU_PARTY_DEAD_2]
【パーティーの半分以上が死んでいる】 ダミーメッセージ２

[msg MITURU_PARTY_DEAD_3]
【パーティーの半分以上が死んでいる】 ダミーメッセージ３

[msg MITURU_FOE_WARNING_NEAR_]
Don't relax yet! The FOE is nearly[n]upon us!

[msg MITURU_FOE_WARNING_NEAR__2]
That FOE is still in pursuit...

[msg MITURU_FOE_WARNING_NEAR__3]
Stay sharp! That FOE is still here!

[msg MITURU_PARTY_HPTP10_1]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ１

[msg MITURU_PARTY_HPTP10_2]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ２

[msg MITURU_PARTY_HPTP10_3]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ３

[msg MITURU_PARTY_HP10_1]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ１

[msg MITURU_PARTY_HP10_2]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ２

[msg MITURU_PARTY_HP10_3]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ３

[msg MITURU_1PERSON_HPTP10_1]
Ngh... I'm fine... I can keep...[n]going...

[msg MITURU_1PERSON_HPTP10_2]
How did this happen...? I was too[n]careless...

[msg MITURU_1PERSON_HPTP10_3]
I don't want to become a liability,[n]but...

[msg MITURU_PARTY_TP10_1]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ１

[msg MITURU_PARTY_TP10_2]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ２

[msg MITURU_PARTY_TP10_3]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ３

[msg MITURU_1PERSON_HP10_1]
Ngh... Sorry, but could I trouble you[n]for some healing...?

[msg MITURU_1PERSON_HP10_2]
Ngh... I'm rather low on health...

[msg MITURU_1PERSON_HP10_3]
Apologies, but I'm near my limit...

[msg MITURU_1PERSON_TP10_1]
I'm having difficulty keeping up...[n]Apologies...

[msg MITURU_1PERSON_TP10_2]
The strain is getting to me...

[msg MITURU_1PERSON_TP10_3]
Sorry... Can we rest a moment?

[msg MITURU_ITEM_90_BATTLE_1]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ１

[msg MITURU_ITEM_90_BATTLE_2]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ２

[msg MITURU_ITEM_90_BATTLE_3]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ３

[msg MITURU_1PERSON_HP80_1]
We'll preserve this momentum, I hope?

[msg MITURU_1PERSON_HP80_2]
Another testament to our growth.

[msg MITURU_1PERSON_HP80_3]
C'est magnifique! Well fought.

[msg MITURU_BATTLE_CHANGE_DUN]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ１

[msg MITURU_BATTLE_CHANGE_DUN_2]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ２

[msg MITURU_BATTLE_CHANGE_DUN_3]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ３

[msg MITURU_ITEM_90_DUNGEON_1]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ１

[msg MITURU_ITEM_90_DUNGEON_2]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg MITURU_ITEM_90_DUNGEON_3]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg MITURU_DUNGEON_START_1]
We'll leave the decision-making to[n]you.

[msg MITURU_DUNGEON_START_2]
Let's go!

[msg MITURU_DUNGEON_START_3]
Let our exploration commence!

[msg MITURU_QUEST_START_1]
Let's move.

[msg MITURU_QUEST_START_2]
Now, to the mission!

[msg MITURU_QUEST_START_3]
Let's get started, everyone.

[msg MITURU_TOUHA_25_1]
We've only just begun.

[msg MITURU_TOUHA_25_2]
Let's proceed slowly, but surely.

[msg MITURU_TOUHA_50_1]
I hope the responsibilities aren't a[n]burden. Are you tired?

[msg MITURU_TOUHA_50_2]
We've covered a good portion of this[n]floor.

[msg MITURU_TOUHA_75_1]
We've walked quite a distance. How is[n]everyone's health?

[msg MITURU_TOUHA_75_2]
I'm starting to see the full[n]picture...

[msg MITURU_TOUHA_100_1]
I daresay we won't be getting lost on[n]this floor again.

[msg MITURU_TOUHA_100_2]
I see we were right to put you in[n]charge.

[msg MITURU_MAPPING_ICON_ALL_]
Yes, that all looks familiar.

[msg MITURU_MAPPING_ICON_ALL__2]
Ah, yes... I do remember that.

[msg MITURU_MAPPING_ICON_KAID]
Now we'll always know the way to the[n]stairs.

[msg MITURU_MAPPING_ICON_KAID_2]
So this leads to the next floor, does[n]it?

[msg MITURU_MAPPING_CHANGE_CO]
Oh...? You've a good sense for this.

[msg MITURU_MAPPING_CHANGE_CO_2]
A novel idea indeed.

[msg MITURU_MAPPING_ICON_DEL_]
Almost refreshing.

[msg MITURU_MAPPING_ICON_DEL__2]
An exemplary feat of cartography.

[msg MITURU_MAPPING_MEMO_1]
Good. Now you won't forget.

[msg MITURU_MAPPING_MEMO_2]
That should prove useful.

[msg MITURU_DOOR_OPEN_1]
Let's proceed.

[msg MITURU_DOOR_OPEN_2]
Now, forward.

[msg MITURU_DOOR_OPEN_3]
Come.

[msg MITURU_KARITORU_ENCOUNT_]
【刈り取るものとエンカウントした】 ダミーメッセージ１

[msg MITURU_KARITORU_ENCOUNT__2]
【刈り取るものとエンカウントした】 ダミーメッセージ２

[msg MITURU_KARITORU_ENCOUNT__3]
【刈り取るものとエンカウントした】 ダミーメッセージ３

