[msg ARAGAKI_FOE_FOLLOW_START]
Tch, it's comin' after us...

[msg ARAGAKI_FOE_FOLLOW_START_2]
Looks like the FOE's spotted us.

[msg ARAGAKI_FOE_FOLLOW_START_3]
Be careful. An FOE's tailing us.

[msg ARAGAKI_FOE_NEAR_1]
There's an FOE right by us...

[msg ARAGAKI_FOE_NEAR_2]
Well well, looks like an FOE's shown[n]up.

[msg ARAGAKI_FOE_NEAR_3]
An FOE... Be careful not to get[n]spotted.

[msg ARAGAKI_FOE_FOLLOW_END_1]
Looks like it finally gave up.

[msg ARAGAKI_FOE_FOLLOW_END_2]
Looks like it went the other way.

[msg ARAGAKI_FOE_FOLLOW_END_3]
We left that FOE in the dust.

[msg ARAGAKI_KANSI_REACTION_1]
Tch, this is going to make movin' a[n]pain.

[msg ARAGAKI_KANSI_REACTION_2]
Be careful. It'll suck if we get[n]caught.

[msg ARAGAKI_KANSI_REACTION_3]
What a pain-in-the-ass trap.

[msg ARAGAKI_DENKISAKU_REACTI]
An electric gate, huh... This sucks,[n]but let's take the longer route.

[msg ARAGAKI_DENKISAKU_REACTI_2]
Better look for the switch to turn[n]the current off...

[msg ARAGAKI_DENKISAKU_REACTI_3]
Looks like we'd better focus on[n]getting rid of the electricity.

[msg ARAGAKI_KYOUHU_REACTION_]
Whoa!?

[msg ARAGAKI_KYOUHU_REACTION__2]
Seriously...!?

[msg ARAGAKI_KYOUHU_REACTION__3]
Tch...!

[msg ARAGAKI_STAIR_FIND_1]
Hey, some stairs...

[msg ARAGAKI_STAIR_FIND_2]
Looks like we can keep going. Should[n]we?

[msg ARAGAKI_STAIR_FIND_3]
There's more to go, huh. What's your[n]call here?

[msg ARAGAKI_TREASURE_FIND_1]
There's a treasure box... Wanna open[n]it?

[msg ARAGAKI_TREASURE_FIND_2]
A treasure box, huh... Hope there's[n]somethin' good in it.

[msg ARAGAKI_TREASURE_FIND_3]
Hey, there's a treasure box.

[msg ARAGAKI_CHECK_WALL_1]
I'm sensing somethin' suspicious...[n]Should we open it?

[msg ARAGAKI_CHECK_WALL_2]
Hey, what's that?

[msg ARAGAKI_CHECK_WALL_3]
There's somethin' over there.

[msg ARAGAKI_SWITCH_FIND_1]
A switch, huh... Should we use it?

[msg ARAGAKI_SWITCH_FIND_2]
Hey, that over there―ain't that a[n]switch?

[msg ARAGAKI_SWITCH_FIND_3]
A switch, huh... What do you wanna[n]do?

[msg ARAGAKI_SHORTCUT_FIND_1]
Can't we go through there?

[msg ARAGAKI_SHORTCUT_FIND_2]
Look, we might be able to use that as[n]a shortcut.

[msg ARAGAKI_SHORTCUT_FIND_3]
Wouldn't that work as a shortcut?

[msg ARAGAKI_PARTY_DEAD_1]
【パーティの半分以上が死んでいる】 ダミーメッセージ１

[msg ARAGAKI_PARTY_DEAD_2]
【パーティーの半分以上が死んでいる】 ダミーメッセージ２

[msg ARAGAKI_PARTY_DEAD_3]
【パーティーの半分以上が死んでいる】 ダミーメッセージ３

[msg ARAGAKI_FOE_WARNING_NEAR]
Looks like that one's still tailin'[n]us.

[msg ARAGAKI_FOE_WARNING_NEAR_2]
I had a feeling it wasn't lettin' us[n]go that easily...

[msg ARAGAKI_FOE_WARNING_NEAR_3]
Looks like this ain't over yet.

[msg ARAGAKI_PARTY_HPTP10_1]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ１

[msg ARAGAKI_PARTY_HPTP10_2]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ２

[msg ARAGAKI_PARTY_HPTP10_3]
【パーティ全体のＨＰＴＰが１０％以下】 ダミーメッセージ３

[msg ARAGAKI_PARTY_HP10_1]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ１

[msg ARAGAKI_PARTY_HP10_2]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ２

[msg ARAGAKI_PARTY_HP10_3]
【パーティ全体のＨＰが１０％以下】 ダミーメッセージ３

[msg ARAGAKI_1PERSON_HPTP10_1]
Tch, I'm reaching my limit...

[msg ARAGAKI_1PERSON_HPTP10_2]
Hey, why don't we start headin' back?

[msg ARAGAKI_1PERSON_HPTP10_3]
I feel like I'm gonna fall flat on my[n]face...

[msg ARAGAKI_PARTY_TP10_1]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ１

[msg ARAGAKI_PARTY_TP10_2]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ２

[msg ARAGAKI_PARTY_TP10_3]
【パーティ全体のＴＰが１０％以下】 ダミーメッセージ３

[msg ARAGAKI_1PERSON_HP10_1]
Tch, I'm gettin' dizzy...

[msg ARAGAKI_1PERSON_HP10_2]
Sorry, but I need healing.

[msg ARAGAKI_1PERSON_HP10_3]
My health's low...

[msg ARAGAKI_1PERSON_TP10_1]
I'm runnin' low on energy here...

[msg ARAGAKI_1PERSON_TP10_2]
My energy's starting to run low.

[msg ARAGAKI_1PERSON_TP10_3]
Out of energy, huh... Tch, what a[n]shame.

[msg ARAGAKI_ITEM_90_BATTLE_1]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ１

[msg ARAGAKI_ITEM_90_BATTLE_2]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ２

[msg ARAGAKI_ITEM_90_BATTLE_3]
【アイテム枠が９０％以上（バトル後）】 ダミーメッセージ３

[msg ARAGAKI_1PERSON_HP80_1]
Not bad.

[msg ARAGAKI_1PERSON_HP80_2]
Some solid moves there.

[msg ARAGAKI_1PERSON_HP80_3]
Let's hope the next one goes like[n]that too.

[msg ARAGAKI_BATTLE_CHANGE_DU]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ１

[msg ARAGAKI_BATTLE_CHANGE_DU_2]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ２

[msg ARAGAKI_BATTLE_CHANGE_DU_3]
【バトルからダンジョン担当へナビ切り替え】 ダミーメッセージ３

[msg ARAGAKI_ITEM_90_DUNGEON_]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ１

[msg ARAGAKI_ITEM_90_DUNGEON__2]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg ARAGAKI_ITEM_90_DUNGEON__3]
【アイテム枠が９０％以上（ＤＧ出入り）】 ダミーメッセージ２

[msg ARAGAKI_DUNGEON_START_1]
Let's hurry up and finish this.

[msg ARAGAKI_DUNGEON_START_2]
Alright, let's go.

[msg ARAGAKI_DUNGEON_START_3]
Better give it your all.

[msg ARAGAKI_QUEST_START_1]
...Let's finish this quick.

[msg ARAGAKI_QUEST_START_2]
Don't slack off, alright?

[msg ARAGAKI_QUEST_START_3]
Well, let's get it started.

[msg ARAGAKI_TOUHA_25_1]
This place looks pretty spread-out.

[msg ARAGAKI_TOUHA_25_2]
No point worryin' over this. Let's[n]just go about it calmly.

[msg ARAGAKI_TOUHA_50_1]
Halfway, huh... Looks like we've[n]still got a ways to go.

[msg ARAGAKI_TOUHA_50_2]
I felt like we were closin' in on our[n]goal...

[msg ARAGAKI_TOUHA_75_1]
This map's startin' to come together.

[msg ARAGAKI_TOUHA_75_2]
We're goin' at a pretty good pace,[n]yeah?

[msg ARAGAKI_TOUHA_100_1]
So, the map's all filled in. Good[n]job.

[msg ARAGAKI_TOUHA_100_2]
You really got that finished... I'm[n]impressed.

[msg ARAGAKI_MAPPING_ICON_ALL]
You're really keepin' at it there.

[msg ARAGAKI_MAPPING_ICON_ALL_2]
Yeah, it was around there.

[msg ARAGAKI_MAPPING_ICON_KAI]
I think that's right.

[msg ARAGAKI_MAPPING_ICON_KAI_2]
I'd say knowing where our entrance is[n]is a pretty big deal.

[msg ARAGAKI_MAPPING_CHANGE_C]
You changed colors, huh? Not bad.

[msg ARAGAKI_MAPPING_CHANGE_C_2]
Huh, lookin' pretty good.

[msg ARAGAKI_MAPPING_ICON_DEL]
I coulda sworn Aki said somethin'[n]about losing weight and whatnot...

[msg ARAGAKI_MAPPING_ICON_DEL_2]
Keepin' things in order can make a[n]real difference―especially out here.

[msg ARAGAKI_MAPPING_MEMO_1]
Taking notes is important.

[msg ARAGAKI_MAPPING_MEMO_2]
Oh? Well, I'm impressed.

[msg ARAGAKI_DOOR_OPEN_1]
Let's hurry up and go.

[msg ARAGAKI_DOOR_OPEN_2]
C'mon, over here...

[msg ARAGAKI_DOOR_OPEN_3]
Be careful out there.

[msg ARAGAKI_KARITORU_ENCOUNT]
【刈り取るものとエンカウントした】 ダミーメッセージ１

[msg ARAGAKI_KARITORU_ENCOUNT_2]
【刈り取るものとエンカウントした】 ダミーメッセージ２

[msg ARAGAKI_KARITORU_ENCOUNT_3]
【刈り取るものとエンカウントした】 ダミーメッセージ３

