[msg MSG_SC_TUTORIAL_0]
[f 0 5 65278][f 2 1]If you tap an icon and drag it along[n][f 0 1 2]while the pencil tool is selected[f 0 1 0]...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Then you can [f 0 1 2]place that icon on the map[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]For example, you can mark shortcuts with[n]their own designated [f 0 1 2]icon[f 0 1 0].[n][f 1 1][e]
[f 0 5 65278][f 2 1]That icon will [f 0 1 2]automatically display[f 0 1 0][n]the travel direction of the shortcut.[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_1]
[f 0 5 65278][f 2 1]Any icons placed by mistake can be[n]deleted by [f 0 1 2]dragging them to the trash can[f 0 1 0].[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_2]
[f 0 5 65278][f 2 1]A mistake in drawing walls or floors is[n]fixed with the [f 0 1 2]UNDO button[f 0 1 0].[n][f 1 1][e]

[msg MSG_SC_TUTORIAL_3]
[f 0 5 65278][f 2 1][n]Your map has many other functions[n]as well. Details can be found under[n][f 0 1 2]HELP[f 0 1 0] at the map's bottom right.[n]Don't forget to fill it in as you[n]explore; you'll thank yourself later![n][f 1 1][e]

