[msg MSG_TUTORIAL_TREASURE_MA]
[f 0 5 65278][f 2 1]You might find [f 0 1 2]treasure maps[f 0 1 0] inside[n]the treasure chests.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Looking at a [f 0 1 2]treasure map[f 0 1 0] drops an icon[n]like the one above onto your own map.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Reach the spot indicated by the icon[n]and you'll net some fabulous items![n][f 1 1][e]
[f 0 5 65278][f 2 1]So don't forget to look at any and all[n][f 0 1 2]treasure maps[f 0 1 0] that fall into your hands![n][f 1 1][e]

