[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Kanji]]
Oye, podemos conseguir algunos objetos.[n]夷Quieres parar un segundo?

[msg MSG_001 [Kanji]]
斡Entendido!

[msg MSG_002 [Kanji]]
斡Yo me encargo!

[msg MSG_003 [Kanji]]
夷Oh, no vamos a por ello?

[msg MSG_004 [Kanji]]
Deber胤a hacerlo.

[msg MSG_005]
Nos llevaremos eso.

[msg MSG_006]
斡S胤!

[msg MSG_007]
斡Claro que s胤!

[msg MSG_008 [Kanji]]
Eso estuvo cerca. Supongo que[n]conseguimos todo lo que pudimos.

[msg MSG_009]
斡Genial!

[msg MSG_010]
斡Vaya!

[msg MSG_011]
斡Oye, una rara!

[msg MSG_012 [Kanji]]
Parece un atajo. 夷Quieres tomarlo?

[msg MSG_013 [Kanji]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Kanji]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Kanji]]
S胤, eso no va a suceder. Nadie va a[n]pasar por ah胤.

[msg MSG_016 [Kanji]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Kanji]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Kanji]]
Hombre, este lugar... Algo se siente[n]extra隠o.

[msg MSG_019 [Kanji]]
斡Muy bien! 斡Demos todo lo que tenemos!

[msg MSG_020 [Kanji]]
S胤, probablemente m茨s seguro.

[msg MSG_021 [Kanji]]
Sali吋 de la nada... Eso fue realmente[n]una locura...

[msg MSG_022 [Kanji]]
Se siente bastante "sombr胤o" por aqu胤.[n]夷Qu姻 opinas?

[msg MSG_023 [Kanji]]
斡Entendido!

[msg MSG_024 [Kanji]]
S胤, probablemente m茨s seguro.

[msg MSG_025 [Kanji]]
夷Eso es todo?

[msg MSG_026 [Kanji]]
Esto deber胤a llevar al cine. 夷Quieres[n]volver?

[msg MSG_027]
斡Cuidado!

