[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Ann]]
ムOye! ムParece que podemos recolectar[n]cosas aquボ! メCuホl es el plan?

[msg MSG_001 [Ann]]
ムDe acuerdo! ムMantengamos nuestros ojos[n]abiertos para cualquier Sombra!

[msg MSG_002 [Ann]]
ムSuena bien! ムEnfoqu〒monos en[n]recolectar!

[msg MSG_003 [Ann]]
Parece arriesgado. Tal vez deberボamos[n]volver mホs tarde.

[msg MSG_004 [Ann]]
Parece que eso es todo.

[msg MSG_005]
ムEsto es nuestro!

[msg MSG_006]
ムMuy bien!

[msg MSG_007]
ムYay!

[msg MSG_008 [Ann]]
E-eso fue espeluznante. Vamos a parar[n]aquボ.

[msg MSG_009]
ムBastante genial, メverdad?!

[msg MSG_010]
ムLa situaciポn se estホ poniendo intensa!

[msg MSG_011]
ムBien!

[msg MSG_012 [Ann]]
ムOh! ムVeo un atajo! メDeberボamos pasar[n]por aquボ?

[msg MSG_013 [Ann]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_014 [Ann]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_015 [Ann]]
Parece que no podemos pasar por aquボ.

[msg MSG_016 [Ann]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_017 [Ann]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_018 [Ann]]
O-oye, tengo un mal presentimiento sobre[n]este lugar.

[msg MSG_019 [Ann]]
B-bien... Entendido.

[msg MSG_020 [Ann]]
Sボ, probablemente deberボamos hacerlo[n]ahora.

[msg MSG_021 [Ann]]
Uf... Pens〒 que eso era todo para[n]nosotros.

[msg MSG_022 [Ann]]
メNo hay como un montポn de Sombras aquボ?[n]メQu〒 deberボamos hacer?

[msg MSG_023 [Ann]]
ムDe acuerdo! ムSeamos cuidadosos!

[msg MSG_024 [Ann]]
Sボ, probablemente deberボamos hacerlo.

[msg MSG_025 [Ann]]
Uf... Eso estuvo cerca.

[msg MSG_026 [Ann]]
Este camino nos lleva de vuelta al cine,[n]メno? メNos vamos?

[msg MSG_027]
ムCuidado!

