[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Yosuke]]
斡Oye, es un punto del tesoro! 夷Quieres[n]echar un vistazo?

[msg MSG_001 [Yosuke]]
斡Entendido! 斡Estemos atentos!

[msg MSG_002 [Yosuke]]
夷Solo saquear el lugar, eh? 斡No hay[n]problema!

[msg MSG_003 [Yosuke]]
Oh, 夷lo dejamos as胤?

[msg MSG_004 [Yosuke]]
De acuerdo... eso deber胤a ser todo.

[msg MSG_005]
斡No me importa si lo hago!

[msg MSG_006]
斡Genial!

[msg MSG_007]
斡Entendido!

[msg MSG_008 [Yosuke]]
斡Dios m胤o, estuvo cerca! 夷Qu姻 te parece[n]si lo dejamos aqu胤?

[msg MSG_009]
斡Muy bien!

[msg MSG_010]
斡Un objeto raro!

[msg MSG_011]
斡Muy bien!

[msg MSG_012 [Yosuke]]
斡Vaya, eso es un atajo! 夷Vamos a[n]tomarlo?

[msg MSG_013 [Yosuke]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_014 [Yosuke]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Yosuke]]
Vaya, parece que ese camino no es[n]viable, 夷verdad?

[msg MSG_016 [Yosuke]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Yosuke]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Yosuke]]
Oye... Hay algo extra隠o. 夷Sientes eso?[n]夷Qu姻 hacemos?

[msg MSG_019 [Yosuke]]
S-s胤... Mientras seamos cuidadosos.

[msg MSG_020 [Yosuke]]
S胤. Qui姻n sabe lo que podr胤a aparecer.

[msg MSG_021 [Yosuke]]
斡Qu姻 demonios fue eso! Estoy feliz de[n]que hayamos sobrevivido...

[msg MSG_022 [Yosuke]]
夷Eh? Hay Sombras por aqu胤... 夷Cu茨l es el[n]plan?

[msg MSG_023 [Yosuke]]
斡Genial! 斡Eliminemos a esas Sombras!

[msg MSG_024 [Yosuke]]
De acuerdo, t雨 eres el jefe.

[msg MSG_025 [Yosuke]]
Uf... 夷Eso es todo?

[msg MSG_026 [Yosuke]]
Esto deber胤a llevar de vuelta al cine.[n]夷Quieres tomar un descanso?

[msg MSG_027]
斡Cuidado!

