[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Rise]]
斡Un punto del tesoro! 夷Quieres[n]revisarlo?

[msg MSG_001 [Rise]]
斡S胤! Mejor prevenir que lamentar.

[msg MSG_002 [Rise]]
斡S胤, llevemos todo lo que podamos[n]cargar!

[msg MSG_003 [Rise]]
Retrocediendo, 斡entendido!

[msg MSG_004 [Rise]]
斡Eso es todo!

[msg MSG_005]
斡Hemos conseguido algo!

[msg MSG_006]
斡Genial!

[msg MSG_007]
斡Yay!

[msg MSG_008 [Rise]]
Esa Sombra no supo lo que la golpe吋.[n]Espero que haya sido la 雨ltima...

[msg MSG_009]
斡Oooh, una rara!

[msg MSG_010]
斡Ese est茨 bien!

[msg MSG_011]
斡Ah胤 vamos!

[msg MSG_012 [Rise]]
He visto un atajo. 夷Vamos a usarlo?

[msg MSG_013 [Rise]]
He visto un atajo. 夷Vamos a usarlo?

[msg MSG_014 [Rise]]
ショートカットがあるみたいだけど どうする？[n](ショートカット選択メッセージ（仮）)

[msg MSG_015 [Rise]]
No podemos pasar por aqu胤. 斡Pero revisa[n]el otro lado!

[msg MSG_016 [Rise]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_017 [Rise]]
こちらからは通れないようだ… (ショートカット未開通メッセージ（仮）)

[msg MSG_018 [Rise]]
斡Espera! Ten cuidado, hay algo realmente[n]peligroso all胤.

[msg MSG_019 [Rise]]
De acuerdo. Har姻 todo lo que pueda para[n]brindar apoyo.

[msg MSG_020 [Rise]]
Muy bien, entonces, retrocedamos...

[msg MSG_021 [Rise]]
夷Est茨n bien? Esa fue una Sombra muy[n]fuerte. 斡Pero lo hicieron bien!

[msg MSG_022 [Rise]]
Estoy detectando m雨ltiples Sombras aqu胤.[n]Si insisten en buscar, 斡mant姻nganse[n]alerta!

[msg MSG_023 [Rise]]
De acuerdo, 斡pero por favor, ten[n]cuidado!

[msg MSG_024 [Rise]]
斡Entendido!

[msg MSG_025 [Rise]]
斡Buen trabajo, chicos!

[msg MSG_026 [Rise]]
Eso lleva de vuelta al cine. 夷Quieres[n]regresar?

[msg MSG_027]
斡Cuidado!

