[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Shinjiro]]
Parece que podemos conseguir cosas aqu胤.[n]夷Qu姻 hacemos?

[msg MSG_001 [Shinjiro]]
Entendido. Mant姻n los ojos bien[n]abiertos.

[msg MSG_002 [Shinjiro]]
S胤, estamos fuera de peligro. Echemos un[n]vistazo.

[msg MSG_003 [Shinjiro]]
Entendido...

[msg MSG_004 [Shinjiro]]
Parece que esos son todos.

[msg MSG_005]
Eh...

[msg MSG_006]
No est茨 mal.

[msg MSG_007]
Nos llevamos eso.

[msg MSG_008 [Shinjiro]]
Hemos terminado.

[msg MSG_009]
Impresionante.

[msg MSG_010]
Bien por ti.

[msg MSG_011]
Oye, eso es raro, 夷no?

[msg MSG_012 [Shinjiro]]
Un atajo, 夷eh...? 夷Qu姻 hacemos?

[msg MSG_013 [Shinjiro]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_014 [Shinjiro]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_015 [Shinjiro]]
Tch... No podemos ir por aqu胤.

[msg MSG_016 [Shinjiro]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_017 [Shinjiro]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_018 [Shinjiro]]
Tengo un mal presentimiento sobre este[n]lugar... 夷Qu姻 opinas?

[msg MSG_019 [Shinjiro]]
De acuerdo. Hag茨moslo.

[msg MSG_020 [Shinjiro]]
Buena elecci吋n.

[msg MSG_021 [Shinjiro]]
Eso fue dif胤cil. Menos mal que[n]termin吋...

[msg MSG_022 [Shinjiro]]
Siento sombras cerca. 夷Cu茨l es el plan?

[msg MSG_023 [Shinjiro]]
De acuerdo, vamos a investigar.

[msg MSG_024 [Shinjiro]]
S胤, seguro.

[msg MSG_025 [Shinjiro]]
Vaya, ten胤a la sensaci吋n de que[n]aparecer胤an.

[msg MSG_026 [Shinjiro]]
夷Regresamos al Cine?

[msg MSG_027]
斡Cuidado!

