[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Chie]]
斡Vaya, mira esto! 斡Un Punto del Tesoro![n]夷Qu姻 vamos a hacer?

[msg MSG_001 [Chie]]
斡Correcto! 斡Mantengan los ojos bien[n]abiertos, chicos!

[msg MSG_002 [Chie]]
斡Entendido! 斡Hag茨moslo correctamente!

[msg MSG_003 [Chie]]
S胤, de todas formas parece un poco[n]sospechoso.

[msg MSG_004 [Chie]]
Bien... 夷Es eso todo?

[msg MSG_005]
斡Quien lo encuentra, se lo queda!

[msg MSG_006]
斡Es todo nuestro!

[msg MSG_007]
斡No est茨 nada mal en absoluto!

[msg MSG_008 [Chie]]
斡Vaya, eso estuvo cerca! Mejor dejarlo[n]aqu胤 antes de que empeore.

[msg MSG_009]
斡Genial!

[msg MSG_010]
斡Oye, ese es raro!

[msg MSG_011]
Vaya...

[msg MSG_012 [Chie]]
Oye, creo que eso es un atajo. 夷Qu姻[n]opinas?

[msg MSG_013 [Chie]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_014 [Chie]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_015 [Chie]]
Bueno, no podemos ir por ese camino...[n]Es un fastidio, pero en fin.

[msg MSG_016 [Chie]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_017 [Chie]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_018 [Chie]]
E-eh, algo que no est茨 bien... 夷Lo[n]sientes tambi姻n, verdad?

[msg MSG_019 [Chie]]
夷E-est茨s seguro...? Bueno, est茨 bien,[n]supongo...

[msg MSG_020 [Chie]]
斡S胤! 斡S胤, buena idea!

[msg MSG_021 [Chie]]
Esa cosa era fuerte... Vaya. Hablamos de[n]un monstruo.

[msg MSG_022 [Chie]]
Hmm... Parece que hay muchas Sombras por[n]aqu胤.

[msg MSG_023 [Chie]]
De acuerdo, siempre y cuando seamos[n]cuidadosos.

[msg MSG_024 [Chie]]
夷Eh? 夷No lo crees?

[msg MSG_025 [Chie]]
Uf... Eso fue tan repentino...

[msg MSG_026 [Chie]]
夷Oh, volvemos?

[msg MSG_027]
斡Cuidado!

