[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Fuuka]]
Parece que podr胤a haber un tesoro en ese[n]lugar. 夷Quieres comprobarlo?

[msg MSG_001 [Fuuka]]
斡Correcto! 斡Mantengan los ojos bien[n]abiertos!

[msg MSG_002 [Fuuka]]
斡Entendido! 斡Vamos a centrarnos al[n]m茨ximo en buscar objetos!

[msg MSG_003 [Fuuka]]
De acuerdo, entiendo. Vamos a tomar un[n]riesgo calculado.

[msg MSG_004 [Fuuka]]
斡Eso es! Buen trabajo a todos.

[msg MSG_005]
斡Vaya!

[msg MSG_006]
夷Era un buen bot胤n?

[msg MSG_007]
斡Interesante!

[msg MSG_008 [Fuuka]]
Buen trabajo. Parece que hemos[n]terminado.

[msg MSG_009]
斡Esa es uno raro!

[msg MSG_010]
斡Lo lograste!

[msg MSG_011]
斡Ahora hay algo especial!

[msg MSG_012 [Fuuka]]
斡Es un atajo! 夷Deber胤amos abrirlo?

[msg MSG_013 [Fuuka]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_014 [Fuuka]]
ショー:吋7:があrfたいAけJ Jうすr？[n](ショー:吋7:選択メ7セージ（仮）)

[msg MSG_015 [Fuuka]]
No podemos pasar por aqu胤. 斡Vamos a[n]revisar el otro lado!

[msg MSG_016 [Fuuka]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_017 [Fuuka]]
こBpかpP通sKいoうA… (ショー:吋7:未開通メ7セージ（仮）)

[msg MSG_018 [Fuuka]]
斡Espera, espera! Estoy detectando la[n]se隠al de algo realmente peligroso all胤[n]dentro.

[msg MSG_019 [Fuuka]]
De acuerdo... 斡Mantente a salvo!

[msg MSG_020 [Fuuka]]
Entendido.

[msg MSG_021 [Fuuka]]
E-eso estuvo cerca... 夷Est茨 todo el[n]mundo bien?

[msg MSG_022 [Fuuka]]
斡Estoy detectando Sombras en la zona![n]斡Mantente alerta!

[msg MSG_023 [Fuuka]]
斡De acuerdo! 斡Puedes contar conmigo!

[msg MSG_024 [Fuuka]]
Entendido.

[msg MSG_025 [Fuuka]]
斡Excelente trabajo a todos!

[msg MSG_026 [Fuuka]]
Eso lleva de vuelta al cine. 夷Volvemos?

[msg MSG_027]
斡Cuidado!

