[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Rise]]
ムUn punto del tesoro! メQuieres[n]revisarlo?

[msg MSG_001 [Rise]]
ムSボ! Mejor prevenir que lamentar.

[msg MSG_002 [Rise]]
ムSボ, llevemos todo lo que podamos[n]cargar!

[msg MSG_003 [Rise]]
Retrocediendo, ムentendido!

[msg MSG_004 [Rise]]
ムEso es todo!

[msg MSG_005]
ムHemos conseguido algo!

[msg MSG_006]
ムGenial!

[msg MSG_007]
ムYay!

[msg MSG_008 [Rise]]
Esa Sombra no supo lo que la golpeポ.[n]Espero que haya sido la マltima...

[msg MSG_009]
ムOooh, una rara!

[msg MSG_010]
ムEse estホ bien!

[msg MSG_011]
ムAhボ vamos!

[msg MSG_012 [Rise]]
He visto un atajo. メVamos a usarlo?

[msg MSG_013 [Rise]]
He visto un atajo. メVamos a usarlo?

[msg MSG_014 [Rise]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_015 [Rise]]
No podemos pasar por aquボ. ムPero revisa[n]el otro lado!

[msg MSG_016 [Rise]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_017 [Rise]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_018 [Rise]]
ムEspera! Ten cuidado, hay algo realmente[n]peligroso allボ.

[msg MSG_019 [Rise]]
De acuerdo. Har〒 todo lo que pueda para[n]brindar apoyo.

[msg MSG_020 [Rise]]
Muy bien, entonces, retrocedamos...

[msg MSG_021 [Rise]]
メEstホn bien? Esa fue una Sombra muy[n]fuerte. ムPero lo hicieron bien!

[msg MSG_022 [Rise]]
Estoy detectando mマltiples Sombras aquボ.[n]Si insisten en buscar, ムmant〒nganse[n]alerta!

[msg MSG_023 [Rise]]
De acuerdo, ムpero por favor, ten[n]cuidado!

[msg MSG_024 [Rise]]
ムEntendido!

[msg MSG_025 [Rise]]
ムBuen trabajo, chicos!

[msg MSG_026 [Rise]]
Eso lleva de vuelta al cine. メQuieres[n]regresar?

[msg MSG_027]
ムCuidado!

