[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Fuuka]]
Parece que podrボa haber un tesoro en ese[n]lugar. メQuieres comprobarlo?

[msg MSG_001 [Fuuka]]
ムCorrecto! ムMantengan los ojos bien[n]abiertos!

[msg MSG_002 [Fuuka]]
ムEntendido! ムVamos a centrarnos al[n]mホximo en buscar objetos!

[msg MSG_003 [Fuuka]]
De acuerdo, entiendo. Vamos a tomar un[n]riesgo calculado.

[msg MSG_004 [Fuuka]]
ムEso es! Buen trabajo a todos.

[msg MSG_005]
ムVaya!

[msg MSG_006]
メEra un buen botボn?

[msg MSG_007]
ムInteresante!

[msg MSG_008 [Fuuka]]
Buen trabajo. Parece que hemos[n]terminado.

[msg MSG_009]
ムEsa es uno raro!

[msg MSG_010]
ムLo lograste!

[msg MSG_011]
ムAhora hay algo especial!

[msg MSG_012 [Fuuka]]
ムEs un atajo! メDeberボamos abrirlo?

[msg MSG_013 [Fuuka]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_014 [Fuuka]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_015 [Fuuka]]
No podemos pasar por aquボ. ムVamos a[n]revisar el otro lado!

[msg MSG_016 [Fuuka]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_017 [Fuuka]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_018 [Fuuka]]
ムEspera, espera! Estoy detectando la[n]seワal de algo realmente peligroso allボ[n]dentro.

[msg MSG_019 [Fuuka]]
De acuerdo... ムMantente a salvo!

[msg MSG_020 [Fuuka]]
Entendido.

[msg MSG_021 [Fuuka]]
E-eso estuvo cerca... メEstホ todo el[n]mundo bien?

[msg MSG_022 [Fuuka]]
ムEstoy detectando Sombras en la zona![n]ムMantente alerta!

[msg MSG_023 [Fuuka]]
ムDe acuerdo! ムPuedes contar conmigo!

[msg MSG_024 [Fuuka]]
Entendido.

[msg MSG_025 [Fuuka]]
ムExcelente trabajo a todos!

[msg MSG_026 [Fuuka]]
Eso lleva de vuelta al cine. メVolvemos?

[msg MSG_027]
ムCuidado!

