[sel ITEM_POINT_SEL top]
Buscar con cautela
Buscar minuciosamente
Cancelar

[sel ITEM_POINT_FORCE_BTL_SEL top]
Buscar
Cancelar

[sel SHORTCUT_SEL top]
Usar
No usar

[sel ENTRANCE_SEL top]
Volver
Cancelar

[msg MSG_000 [Chie]]
ムVaya, mira esto! ムUn Punto del Tesoro![n]メQu〒 vamos a hacer?

[msg MSG_001 [Chie]]
ムCorrecto! ムMantengan los ojos bien[n]abiertos, chicos!

[msg MSG_002 [Chie]]
ムEntendido! ムHagホmoslo correctamente!

[msg MSG_003 [Chie]]
Sボ, de todas formas parece un poco[n]sospechoso.

[msg MSG_004 [Chie]]
Bien... メEs eso todo?

[msg MSG_005]
ムQuien lo encuentra, se lo queda!

[msg MSG_006]
ムEs todo nuestro!

[msg MSG_007]
ムNo estホ nada mal en absoluto!

[msg MSG_008 [Chie]]
ムVaya, eso estuvo cerca! Mejor dejarlo[n]aquボ antes de que empeore.

[msg MSG_009]
ムGenial!

[msg MSG_010]
ムOye, ese es raro!

[msg MSG_011]
Vaya...

[msg MSG_012 [Chie]]
Oye, creo que eso es un atajo. メQu〒[n]opinas?

[msg MSG_013 [Chie]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_014 [Chie]]
ショー:ポ7:があrfたいAけJ Jうすr？[n](ショー:ポ7:選択メ7セージ（仮）)

[msg MSG_015 [Chie]]
Bueno, no podemos ir por ese camino...[n]Es un fastidio, pero en fin.

[msg MSG_016 [Chie]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_017 [Chie]]
こBpかpP通sKいoうA… (ショー:ポ7:未開通メ7セージ（仮）)

[msg MSG_018 [Chie]]
E-eh, algo que no estホ bien... メLo[n]sientes tambi〒n, verdad?

[msg MSG_019 [Chie]]
メE-estホs seguro...? Bueno, estホ bien,[n]supongo...

[msg MSG_020 [Chie]]
ムSボ! ムSボ, buena idea!

[msg MSG_021 [Chie]]
Esa cosa era fuerte... Vaya. Hablamos de[n]un monstruo.

[msg MSG_022 [Chie]]
Hmm... Parece que hay muchas Sombras por[n]aquボ.

[msg MSG_023 [Chie]]
De acuerdo, siempre y cuando seamos[n]cuidadosos.

[msg MSG_024 [Chie]]
メEh? メNo lo crees?

[msg MSG_025 [Chie]]
Uf... Eso fue tan repentino...

[msg MSG_026 [Chie]]
メOh, volvemos?

[msg MSG_027]
ムCuidado!

