[msg MSG_BTL_001]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Ahora, Fox![n][f 1 1][e]

[msg MSG_BTL_002]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Hag茨moslo![n][f 1 1][e]

[msg MSG_BTL_003]
[f 0 5 65278][f 2 1][f 0 6 255 255]Excepto que he crecido de hambre...[n][f 1 1][e]

[msg MSG_BTL_004]
[f 0 5 65278][f 2 1][f 0 6 255 255]Bien... come esto.[n][f 1 1][e]

[msg MSG_BTL_005]
[f 0 5 65278][f 2 1][f 0 6 255 255]斡Yo tambi姻n tengo prote胤nas! 斡Aqu胤![n][f 1 1][e]

