[sel YESNO_SEL top]
Yes
No

[msg GET_ITEM_MES]
I obtained [f 2 5 3 65535 0].

[msg GET_MONEY_MES]
I obtained [f 2 4 0] yen.

[msg TBOX_ENEMY_APPEAR]
Look out!

[msg NOT_OPEN_SHORTCUT]
We can't go through...

[msg OPENED_BOX]
There's nothing else here...

[msg EXIT_DUNGEON_SEL]
Should I drop out of this movie?

[msg SHORTCUT_ASK]
There's a hidden passage...

[sel SEL_SHORTCUT_ASK top]
Use
Don't use

[msg ONEWAY_ASK]
びめもれ れめよるろぼゎろ ゅよよやれ ゅもやま もろ よょゅを むよまれ よょま ゐぺを;[n]と ぼぺょ むよ ろめるよゎむめデ [f 0 1 2]ほゎろ と ゐよょ'ろ ほま ぺほゅま ろよ ぼよゆま[n]ほぺぼや みるよゆ ろめま よろめまる れもぽまテテテ

[sel SEL_ONEWAY_ASK top]
Use
Don't use

[msg BAG_FULL]
It looks like my bag is full...

[msg GATHER_SUSPENSE]
I searched the Treasure Spot...
...?

[sel JIJIKU_SEL top]
Save
Leave the labyrinth
Cancel

[msg JIJIKU_ASK]
What should I do?

[msg FIND_QUEST_TEST]
Perhaps we should return to the theater[n]and check the status of the quest...

[sel SEL_QUEST_ESCAPE_TEST top]
Return to the theater
Proceed forward

[msg ALERT_MSG]
This leads outside of the special[n]screening. What should I do?

[sel SEL_ALERT_MSG top]
Return to the theater
Continue exploring

[msg MAPPING_FAILED_MSG]
The treasure chest map is emitting a[n]mysterious glow!
It seems to be indicating locations that[n]haven't been visited...

[sel POWER_SPOT_SEL top]
Search cautiously
Search thoroughly
Cancel

[msg USE_AUTO_RECOVER_ASK]
Should I use auto-recovery?

[sel AUTO_RECOVER_SEL top]
Use
Do not use

[msg AUTO_RECOVER_NOT_USE_MSG]
Maybe not.

[msg AUTO_RECOVER_NOT_USE_MSG_2]
Nobody needs healing.

[msg AUTO_RECOVER_NOT_USE_MSG_3]
There's not enough SP to use the[n]recovery skill.

[msg AUTO_RECOVER_NOT_USE_MSG_4]
Nobody in the party can use a recovery[n]skill.

[msg MSG_TUTORIAL_OTAKARA_GET]
> Treasure Spot event

[msg MSG_TUTORIAL_POWERSPOT_1]
"Treasure Spots" are where you may[n]obtain [f 0 1 2]various items[f 0 1 0].

[msg MSG_TUTORIAL_POWERSPOT_2]
If you choose to [f 0 1 2]Search thoroughly[f 0 1 0]...
Then you may find [f 0 1 2]up to 5[f 0 1 0] items, with a[n]greater chance they'll be rare.
However, you also have a greater chance[n]of triggering a battle.

[msg MSG_TUTORIAL_POWERSPOT_3]
If you choose to [f 0 1 2]Search cautiously[f 0 1 0]...
Then you may find [f 0 1 2]up to 3[f 0 1 0] items, while[n]enjoying a low risk of battle.

[msg MSG_TUTORIAL_POWERSPOT_4]
びめまるま'れ ぺ ゅもゆもろまぽ ょゎゆほまる よみ もろまゆれ もょ まぺぼめ[n]びるまぺれゎるま ひらよろデ ほゎろ もみ をよゎ [f 0 1 2]ゅまぺわま ろめま ゅぺほをるもょろめ[f 0 1 0]デ[n]ぼまるろぺもょ れらよろれ ゐもゅゅ ほま るまらゅまょもれめまぽデ ぺょぽ をよゎ ぼぺょ[n]れまぺるぼめ ろめまゆ ぺむぺもょテ びぺやま ぺぽわぺょろぺむま よみ ろめもれデ ぺょぽ[n]をよゎ'ゅゅ まょぽ ゎら るもぼめまる ろめぺょ ぺ やもょむ!

[msg MSG_TUTORIAL_OTAKARA_GET_2]
> Got goods! event
> But let's be careful of the enemy[n]event

[msg MSG_TUTORIAL_OTAKARA_BAG]
> Inventory full event

[msg MSG_TUTORIAL_QUEST_MAP_0]
とみ をよゎ まょろまる ぺ ゅぺほをるもょろめ ぽゎるもょむ ぺ れらまぼもぺゅ[n]れぼるままょもょむデ [f 0 1 2]れよゆま らぺろめれ ゐもゅゅ ほま もょぺぼぼまれれもほゅま[f 0 1 0]テ[n]びめまるま ゆもむめろ ほま よろめまる ぼめぺょむまれ ぺれ ゐまゅゅテ
The map may show some differences in the[n]floor's layout.[f 0 1 0].

[msg MSG_TUTORIAL_QUEST_MAP_1]
Inaccessible areas will be [f 0 1 2]colored red[f 0 1 0][n]and [f 0 1 2]marked with a special iconon the[n]lower screen.
Keep an eye on the lower screen and stay[n]alert when exploring labyrinths during[n]special screenings.

[msg MSG_TUTORIAL_QUEST_MAP_2]
Also, a [f 0 1 2]special screening palettewill[n]appear on the lower screen.
Icons from this palette [f 0 1 2]can only be[n]placed during a special screening[f 0 1 0].
Use these to mark events that only occur[n]during special screenings.
Make use of the palette and strive to[n]complete the quest.

[msg MSG_TUTORIAL_QUEST_TREAS]
Special screenings have their[n]owntreasure chests not found elsewhere[f 0 1 0].
These contain items that will come in[n]handy, so don't miss them!

[msg MSG_FUTABA_IP_BTL_MSG_1]
It's the Reaper... This one's gonna be[n]tough!

[msg MSG_FUTABA_IP_BTL_MSG_2]
I know this feeling... It's the Reaper!

[msg MSG_FUTABA_IP_BTL_MSG_3]
Tough one on the way! Get ready!

[msg MSG_FUKA_IP_BTL_MSG_1]
I'm picking up a signal... Look out,[n]it's the Reaper!

[msg MSG_FUKA_IP_BTL_MSG_2]
The Reaper is closing in on you! Please,[n]stay on your guard!

[msg MSG_FUKA_IP_BTL_MSG_3]
Hm, according to my readings... ...Oh[n]no! There's a Reaper!

[msg MSG_RISE_IP_BTL_MSG_1]
Uh oh, I'm picking up a Reaper nearby![n]Watch out!

[msg MSG_RISE_IP_BTL_MSG_2]
I sense The Reaper! Stay on your guard!

[msg MSG_RISE_IP_BTL_MSG_3]
Picking up a signal from the Reaper![n]It's coming this way!

[msg MSG_JUSTINE_IP_BTL_MSG_1]
The Reaper approaches. Please be[n]careful.

[msg MSG_JUSTINE_IP_BTL_MSG_2]
Please take care, for there's a Reaper[n]afoot.

[msg MSG_JUSTINE_IP_BTL_MSG_3]
It's the Reaper... Your only chance is[n]to maintain focus.

[msg MSG_CAROLIN_IP_BTL_MSG_1]
The Reaper is near!

[msg MSG_CAROLIN_IP_BTL_MSG_2]
Incoming Reaper!

[msg MSG_CAROLIN_IP_BTL_MSG_3]
I know this sound, it's the Reaper!

[msg MSG_ELIZABETH_IP_BTL_MSG]
A Reaper makes its grand entrance!

[msg MSG_ELIZABETH_IP_BTL_MSG_2]
With my incredible ears, I can hear the[n]Reaper calling.

[msg MSG_ELIZABETH_IP_BTL_MSG_3]
That sound... It can only be a Reaper.

[msg MSG_THEODOR_IP_BTL_MSG_1]
I wish this wasn't true, but there's a[n]Reaper coming!

[msg MSG_THEODOR_IP_BTL_MSG_2]
Incoming Reaper. Please take care!

[msg MSG_THEODOR_IP_BTL_MSG_3]
I'm sensing something, and it's most[n]certainly a Reaper!

[msg MSG_MARGARET_IP_BTL_MSG_]
The Reaper is here! Stay on guard!

[msg MSG_MARGARET_IP_BTL_MSG__2]
Remain alert. A powerful enemy is[n]approaching.

[msg MSG_MARGARET_IP_BTL_MSG__3]
The Reaper is close. Stay vigilant.

[msg MSG_NANAKO_IP_BTL_MSG_1]
The Reaper! That's what it is!

[msg MSG_NANAKO_IP_BTL_MSG_2]
A Reaper is coming!

[msg MSG_NANAKO_IP_BTL_MSG_3]
No! The Reaper is coming fast!

[msg MSG_foe_exist_move_short [Futaba]]
H-Hey! There's an FOE on the other side[n]of that shortcut!
Don't go through there!

[msg MSG_foe_exist_move_short_2 [Futaba]]
H-Hey! There's an FOE on the other side[n]of that shortcut!
Don't go through there!

[msg MSG_foe_exist_move_short_3 [Rise]]
Wait! There's an FOE on the other side!
I wouldn't go through there just now!

[msg MSG_foe_exist_move_short_4 [Fuuka]]
Hold on, please! There's an FOE through[n]there!
Let's wait until it leaves before going[n]further.

[msg MSG_GET_TRESURE_MAP]
The [f 0 1 2]location of the treasure[f 0 1 0] hidden in[n]this movie has been marked on the map.

