[msg MSG_000 [Languid man]]
Can we really... be like the characters[n]in that movie?
If I'm actually not powerless... If I[n]can change...
Then, I want to change!

[msg MSG_001 [Despondent woman]]
M-Me too... Honestly... I wanted to live[n]and laugh like them...
Can I still change? If I can redo it[n]all, then I... I don't want to give up!

[msg MSG_002 [Listless man]]
I was so scared... All I thought about[n]was running from my problems...
But, I don't really want to be like[n]this... I want to move on!

