[msg MSG_001 [Junpei]]
Man, we're really gonna mess with those[n]projectors, huh? I guess we'll be in[n]some real trouble if Enlil busts us...

[msg MSG_002 [Rise]]
ひめま'れ ょよろ れよゆまよょま ゐめよ'ゅゅ めまぺる ゐめぺろ ゐま めぺわま ろよ[n]れぺをテ とみ ゐま むまろ ぼぺゎむめろ もょ ろめま ぺぼろデ れめま'ゅゅ[n]るまぺゅゅを ゅまろ ゎれ めぺわま もろ ろめもれ ろもゆまテテテ

[msg MSG_003 [Teddie]]
Hooray, it's phantom thief time! We'll[n]slink through the shadows and swiftly[n]seize our target!

[msg MSG_004 [Akihiko]]
It's not in my nature to sneak around.
On top of that, I've never done any[n]phantom thieving before. You'll have to[n]show us the ropes here.

[sel SEL_005 top]
We just go with the flow.
Our style isn't hard to pick up.
Just shut up and follow our lead.

[msg MSG_006 [Mitsuru]]
I-Is that how you do things?

[msg MSG_007 [Morgana]]
No way! Our approach is way more[n]strategic than that!
We'll show you the true skills of the[n]Phantom Thieves―just follow our lead!

[msg MSG_008 [Teddie]]
Oho, is that so? By the way, Teddie[n]Style is "stuffing yourself with snacks[n]three times a day"!

[msg MSG_009 [P4 Hero]]
I don't think that's what he means...

[msg MSG_010 [Morgana]]
Style's not something you give lessons[n]on―you just have to feel it!
Anyway, we'll show you the true skills[n]of the Phantom Thieves―just follow our[n]lead!

[msg MSG_011 [Mitsuru]]
Ha... How straightforward.
Then we'll follow your example as we[n]advance through the mission.

[msg MSG_012 [Morgana]]
Yeah, we'll show you the true skills of[n]the Phantom Thieves!

[msg MSG_013 [Yukiko]]
*giggle* It's like all of us have joined[n]the troupe!

[msg MSG_014 [Chie]]
Ooh, that sounds awesome! We get to be[n]in both the Investigation Team AND the[n]Phantom Thieves!

[msg MSG_015 [Naoto]]
Those who pursue and those being[n]pursued―normally, such parties would[n]never fraternize...
Perhaps it's something about this[n]strange world that allows us to join our[n]efforts.

[msg MSG_016 [Mitsuru]]
In the same regard, we of SEES will also[n]contribute to the Phantom Thieves for[n]this mission.

[msg MSG_017 [Ken]]
Heheh, a phantom thief, huh?

[msg MSG_018 [Junpei]]
Ah, you're at the age where you dream of[n]that kinda thing. Seems like you're an[n]elementary kid after all, Ken.

[msg MSG_019 [Ken]]
Th-That's not what I was thinking! Leave[n]me alone...

[msg MSG_020 [Koromaru]]
Arf!

[msg MSG_021 [Aigis]]
Koromaru-san is enthusiastic as well. He[n]said, "Sign me up too."

[msg MSG_023 [Futaba]]
Oh yeah! Hikari, you're part of the[n]Phantom Thieves too now, okay?

[msg MSG_024 [Hikari]]
Huh? It's really all right for me to...?

[msg MSG_025 [Haru]]
Of course! Let's go try our hardest[n]together.

[msg MSG_026 [Hikari]]
Mmhm... Thank you!

[msg MSG_027 [Ann]]
Haha, our crew's just ballooned into an[n]army! I thought we were supposed to be[n]the "Phantom" Thieves.

[sel SEL_028 top]
This is going to be fun.
This is going to be a handful...

[msg MSG_029 [Fuuka]]
Wow, what confidence!
The same goes for our own leader, but[n]yours is so trustworthy... I'm[n]impressed!

[msg MSG_030 [Rise]]
Right? They're all so[n]dependable―even-san's got guts!

[msg MSG_031 [Yusuke]]
Excellent point―it's going to be quite[n]the challenge keeping such unusually[n]unique individuals in line.

[msg MSG_032 [Futaba]]
Oh, you're one to talk, Inari!

[msg MSG_033 [Ryuji]]
Yeah―same for you, ya know!?

[msg MSG_034 [P3 Hero]]
I know it may sound strange saying[n]something like this... but honestly, I'm[n]getting a bit excited.

[msg MSG_035 [P4 Hero]]
Actually, it's not so strange―I feel the[n]same way.
Normally, we never would've met, yet[n]we've all come together for a purpose.
Right here, right now, there's only one[n]thing for us to do―in fact, it's[n]something only we can do as well.

[msg MSG_036 [P3 Fem Protag]]
That's right. I'm sure there's a meaning[n]for all of us meeting!

[msg MSG_037 [Morgana]]
ぶまゅゅ ろめまょデ ゅまろ'れ やもぼや よみみ ろめま もょぺゎむゎるぺゅ[n]ゆもれれもよょ よみ ろめま ょまゐゅを-まゑらぺょぽまぽ はめぺょろよゆ びめもまわまれ![n]にまろ'れ れろぺるろ ゐもろめ ろめま ぽまろぺもゅれ よみ―

[msg MSG_038 [Ryuji]]
OH, SHIT! We totally forgot―the calling[n]card!

[msg MSG_039 [Morgana]]
What? The calling card?

[msg MSG_040 [Ryuji]]
We can't start without one! Yusuke― can[n]you whip one up for us?

[msg MSG_041 [Makoto]]
But, this isn't a Palace. There's not[n]really any use for us to send one...

[msg MSG_042 [P3 Fem Protag]]
Oh, a calling card's a must for Phantom[n]Thieves operations! Let's make one,[n]let's make one!

[msg MSG_043 [Ken]]
I think we should do it too! I-If[n]this'll raise everyone's morale...

[msg MSG_044 [Yusuke]]
Ha, so you believe in the beauty of[n]tradition as well... As you wish. I'll[n]prepare one now.

[msg MSG_045 [Ryuji]]
Welp, all that's left is our usual[n]cheer! Take it away, [f 6 1 30 0 0 0]!

[sel SEL_046 top]
It's showtime!
Let's steal Enlil's movie!
I can't think one up offhand...

[msg MSG_047 [Ryuji]]
Whaaaat...? NOW'S when you clam up on[n]us!?

[msg MSG_048 [Morgana]]
*sigh* I guess we've got no other[n]choice. Allow me to get this started the[n]right way...

[msg MSG_049 [Morgana]]
Grand Phantom Thieves, let's begin the[n]operation!

[msg MSG_050 [Ann]]
Yeah!

[msg MSG_051 [Ryuji]]
Yeah!

[msg MSG_052 [Yusuke]]
Yeah!

[msg MSG_053 [Makoto]]
Yeah!

[msg MSG_054 [Morgana]]
Yeah!

[msg MSG_055 [Haru]]
Yeah!

[msg MSG_056 [Futaba]]
Yeah!

[msg MSG_057 [Akechi]]
Yeah!

[msg MSG_058 [P4 Protag]]
Yeah!

[msg MSG_059 [Chie]]
Yeah!

[msg MSG_060 [Yukiko]]
Yeah!

[msg MSG_061 [Yosuke]]
Yeah!

[msg MSG_062 [Kanji]]
Yeah!

[msg MSG_063 [Naoto]]
Yeah!

[msg MSG_064 [Rise]]
Yeah!

[msg MSG_065 [Teddie]]
Yeah!

[msg MSG_066 [Yukari]]
Yeah!

[msg MSG_067 [Junpei]]
Yeah!

[msg MSG_068 [Fuuka]]
Yeah!

[msg MSG_069 [Akihiko]]
Yeah!

[msg MSG_070 [Shinjiro]]
Yeah...

[msg MSG_071 [Mitsuru]]
Yeah!

[msg MSG_072 [Ken]]
Yeah!

[msg MSG_073 [Koromaru]]
Awoooo!

[msg MSG_074 [Aigis]]
Yes!

[msg MSG_075 [P3 Protag]]
Yeah!

[msg MSG_076 [P3 Fem Protag]]
Yeah!

[msg MSG_077 [Hikari]]
Yeah!

