[msg MSG_000 [Hikari]]
Ah...

[msg MSG_001 [Enlil]]
If this truly is the will of mankind,[n]then I ask that you prove it to be so.

[msg MSG_002 [Enlil]]
Moreover, you must not forget...
I appeared in this form solely due to[n]the desires of humans.
As long as humans yearn for me, I shall[n]appear as many times as necessary.

[msg MSG_003 [P3 Fem Protag]]
It's really, finally over for sure this[n]time.

[msg MSG_004 [Hikari]]
Mm-hm...

[msg MSG_005 [Hikari]]
Ah! That sound...

