[msg MSG_000 [Yosuke]]
...The hell was that?

[msg MSG_001 [Teddie]]
The theater people seem like they're in[n]so much pain...

[msg MSG_002 [Enlil]]
Now do you understand?
へよゎ ゐまるま ぼぺらぺほゅま よみ まゑもろもょむ ろめま ろめまぺろまる[n]ほまぼぺゎれま よみ をよゎる れろるまょむろめデ ぼよるるまぼろ? ぶまゅゅデ ろめぺろ[n]もれょ'ろ らよれれまれれまぽ ほを まわまるを れよゎゅ めまるまテテテ
For them, this is instead a place where[n]they can gain a sense of peace they've[n]never found in their own realities.

[msg MSG_003 [Futaba]]
Th-That... can't be...

[msg MSG_004 [Enlil]]
Can you truly say that isn't the case?

[msg MSG_005 [Fuuka]]
It's...

[msg MSG_006 [Enlil]]
*chuckle* Well then, everyone―thank you[n]for attending the theater.

[msg MSG_007 [Kanji]]
Agh―dammit! Get your ass back here!

[msg MSG_008 [Mitsuru]]
She vanished...

[msg MSG_009 [Yusuke]]
...Can we truly return home now?

[msg MSG_010 [Rise]]
Yeah... It seems like it. But...

[msg MSG_011 [Hikari]]
I...

[msg MSG_012 [P3 Fem Protag]]
Don't worry, Hikari-chan! It's alright,[n]we'll make sure you get back to your―

[msg MSG_013 [Hikari]]
That's not it―I'm not worried about[n]myself...
I'm remembering how those people are[n]feeling right now... So much that it[n]hurts.

[msg MSG_013_5 [Hikari]]
I ran away from all sorts of things in[n]my life, just because I didn't want to[n]get hurt...
I even tried to get rid of everything[n]that I ever cared about...

[msg MSG_014 [Teddie]]
Hikarin...

[msg MSG_015 [Hikari]]
But, then you all saved me... You made[n]me realize I want to be myself again.
と'ゆ れゎるま ゐま ぼぺょ ぽよ ろめま れぺゆま ろめもょむ みよる ろめま[n]よろめまるれ めまるまテ だゅゅ ろめまを ょままぽ もれ ろめま ぼめぺょぼま ろよ[n]れまま ゐめぺろ ゅもみま れめよゎゅぽ ほま ゅもやまテテテ

[msg MSG_015_5 [Hikari]]
テテテだょぽ ろめまを'ゅゅ めぺわま ゐめぺろ ろめまを ょままぽ ろよ れまま ろめま[n]わぺゅゎま よみ もょぽもわもぽゎぺゅもろをテ ひよデ と ぼぺょ'ろ ゃゎれろ[n]ぺほぺょぽよょ ぺゅゅ ろめま らまよらゅま めまるま ゅもやま ろめもれ!

[sel SEL_016 top]
Well said.
I agree.
Aw, here it goes...

[msg MSG_017 [P3 Fem Protag]]
Yeah! You've got the right idea! Let's[n]go save them!

[msg MSG_018 [P4 Hero]]
Right―I think we should save everyone[n]here too.

[msg MSG_019 [P3 Hero]]
You say that like you think it's a[n]bother, but the look on your face says[n]otherwise.

[msg MSG_020 [Fuuka]]
Based on what we've seen so far, I don't[n]think those people really want to be[n]here...

[msg MSG_021 [Naoto]]
It was like they were trying to convince[n]themselves to stay here by claiming that[n]everyone held the same opinion...
That's our clue that they don't truly[n]feel that way. We need to help them snap[n]out of it.

[msg MSG_022 [Morgana]]
Looks like this'll be our last big job[n]here.

[msg MSG_023 [Ryuji]]
Whoa, when did my clothes change!?

[msg MSG_024 [Yusuke]]
It must be because we've demonstrated[n]our will to confront Enlil here...

[msg MSG_025 [Ann]]
Makes sense. Now that we know what we're[n]doing here, let's go chase after her!

[msg MSG_026 [Mitsuru]]
Wait―there's no knowing what awaits us[n]ahead. We should prepare for our mission[n]first.

[msg MSG_027 [Akechi]]
That's true... I do feel a bit uneasy[n]charging onward in our current state.

[msg MSG_028 [Aigis]]
Understood. Everyone, let us return[n]inside the theater.

