[msg MSG_000 [P3 Fem Protag]]
Whew... It looks like we've still got[n]quite a ways to go. Are you holding up[n]all right, Hikari-chan?

[msg MSG_001 [Hikari]]
I'm okay, thanks.

[msg MSG_002 [Akihiko]]
The more we walk on this film floor, the[n]more I feel like it's draining my[n]energy.
Hmh... So this is what Enlil calls[n]"salvation."

[msg MSG_003 [Ken]]
If reality's too painful for someone,[n]she offers them the option to escape it.[n]I suppose that's a kind of salvation...
ちゎろ と ゐよゎゅぽょ'ろ めぺわま ぺょをろめもょむ ろよ ぽよ ゐもろめ もろデ[n]ゆをれまゅみテ とみ と よょゅを るぺょ みるよゆ ゆを らるよほゅまゆれデ ょよょま[n]よみ ろめまゆ ゐよゎゅぽ まわまる ほま れよゅわまぽテ

[msg MSG_004 [Hikari]]
Now that I've seen the edited versions[n]of the movies, I agree with you.

[msg MSG_005 [Koromaru]]
Arf!

[msg MSG_006 [Junpei]]
But man, to think Nagi-san turned out to[n]be the baddie causing all of this...
She seemed so nice, and caring, and[n]gorgeous... Totally the ideal[n]older-sister type!

[msg MSG_007 [Yukari]]
Ugh... That kind of talk totally grosses[n]me out.

[msg MSG_008 [Junpei]]
Aw c'mon, it's a man's dream! You get[n]it, right [f 6 1 16 0 0]?

[msg MSG_009 [P3 Hero]]
...Huh? Sorry, I wasn't listening.

[msg MSG_010 [Junpei]]
How could you blow me off like that!?[n]Don't make me invoke the "Have Pity[n]Ordinance"!

[msg MSG_011 [P3 Hero]]
What's a "Have Pity Ordinance"?

[msg MSG_012 [Aigis]]
I am able to recall Junpei-san teaching[n]me about this ordinance previously...
It is a command forbidding anyone from[n]treating Junpei-san lower than a[n]grasshopper.

[msg MSG_013 [P3 Fem Protag]]
Oh, he does that in this world too? The[n]Junpei in my world tries to pull the[n]same move.

[msg MSG_014 [Junpei]]
Haha, I'm impressed with the other me!

[msg MSG_015 [Ryuji]]
Uh, but doesn't that mean you get[n]treated lower than a grasshopper in any[n]reality?

[msg MSG_016 [Akechi]]
I think I've finally deduced the true[n]hierarchy of SEES...

[msg MSG_017 [Mitsuru]]
Moving on from grasshopper talk―the[n]woman we knew as Nagi showed us great[n]kindness while in the theater...
Was that all to deceive us as well? It[n]seems awfully counterintuitive,[n]considering the amount of support.

[msg MSG_018 [Fuuka]]
Even after ruining her plans for[n]Hikari-chan, she didn't exactly bear any[n]ill will towards us...
To be honest, she sort of just brushed[n]us off and let us go on our way.

[msg MSG_019 [Hikari]]
I have a feeling she's got some reason[n]for letting us go...

[msg MSG_020 [P3 Fem Protag]]
Me too―not only that, I think she wasn't[n]actually lying about trying to save[n]Hikari-chan, either.

[msg MSG_021 [Shinjiro]]
Well, whatever her deal is, it doesn't[n]change what we've gotta do...
We've gotta bust up this bullshit[n]"salvation" she's runnin' here― for[n]good.

[msg MSG_022 [P3 Hero]]
In that case, we know what our next[n]mission is...

[sel SEL_023 top]
Let's put a stop to Enlil's scheme.
Let's set those people free.

[msg MSG_024 [Ryuji]]
Hell yeah! Here come the Phantom[n]Thieves!

[msg MSG_025 [Teddie]]
The Investigation Team is on the case!

[msg MSG_026 [Koromaru]]
Arf, arf!

[msg MSG_027 [Aigis]]
Koromaru-san says, "SEES will do its[n]best as well."

[msg MSG_028 [Hikari]]
So... I think I finally understand what[n]a companion really is, now.
It's not just getting along or having[n]fun with another person.
Everyone has an ending to their own[n]story that they want to see, and they[n]strive to reach with all their heart...
So when you look beside you, and there[n]are others proudly fighting to reach the[n]same ending as you...
Even though you might misunderstand or[n]disagree with each other sometimes, you[n]support each other along the way...
And that is what makes someone your[n]companion.

[msg MSG_029 [P3 Hero]]
Right―we're all going to fight back[n]together, as companions.
We're following our own beliefs to the[n]end, just like you are.

[msg MSG_030 [Ken]]
That's right. I hope we can all do our[n]best together!

[msg MSG_031 [Junpei]]
Face it―this one's in the bag! We've got[n]the Investigation Team, the Phantom[n]Thieves, and even SEES on the job.
This group is more than impressive―it's[n]downright insane! I mean, what is this,[n]some kinda all-star show?

[msg MSG_032 [Hikari]]
*giggle* That sounds like a crossover[n]movie.

[msg MSG_033 [Aigis]]
So, we are within a crossover movie[n]comprised of humanoid companions and a[n]grasshopper... I comprehend.

[msg MSG_034 [Junpei]]
Wait a sec―even Aigis is classifying me[n]as some kinda grasshopper now!?

[msg MSG_035 [Yukari]]
Geez, would you drop the grasshopper[n]thing already? C'mon, let's bug off[n]without this bug.

[msg MSG_036 [Yukiko]]
Don't be so down, Grass―
―Junpei-kun... Ah, why don't we hurry[n]along so we don't get left behind?

[msg MSG_037 [Junpei]]
Oh no―even YOU!?

[msg MSG_038 [Mitsuru]]
Good heavens. How long do you intend to[n]continue this subpar routine?
We've rested here for long enough. Let's[n]prepare ourselves and be on our way!

