[msg MSG_000]
Now do you understand?

[msg MSG_000_5]
Your attempted interference here is[n]utterly asinine and ineffectual.

[msg MSG_001]
A society protected by peace and[n]order...

[msg MSG_001_3]
That is the world mankind desires.

[msg MSG_001_5]
As its sovereign, I cannot overlook you[n]thieves disturbing this world.

[msg MSG_002]
If you cannot accept simple direction...

[msg MSG_002_5]
Then I will cut you down myself.

