[msg MSG_000 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 0 2 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 1][f 6 1 2 0 0 3]Ngh... Where are we?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 0 2 1][f 3 1 1 0 0 2][f 6 1 2 0 0 0]Everyone! Are you all right!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 0][f 3 1 1 0 0 3][f 6 1 2 0 0 4]Yamagishi...? So, we're back in Hikari's[n]movie theater?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 0 0 4][f 3 1 1 0 0 4]Yeah. Looks like you were knocked[n]all the way back here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 0 0 1][f 3 1 1 0 0 5]Enlil's power is off the charts...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 70 6 0 1][f 3 1 1 0 0 6]But the power of those folks in the[n]theaters who refuse to listen to us[n]seems even stronger.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 4 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 6]Dammit! Why the hell can't they get[n]with the program already!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 5 12 0 1][f 3 1 1 0 0 8][f 6 1 2 0 0 4]But, those people―didn't they seem like[n]they were actually a bit hesitant?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 0][f 3 1 1 0 0 9]Yes. There were even some voices[n]expressing their desire for the sort of[n]courage we hoped for them to show...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 6 0 4][f 3 1 1 0 0 10]But in the end... they all gave up and[n]just stuck to hiding away.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Hikari]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 12 1 1][f 3 1 1 0 0 11]I think they're probably dealing with[n]the same problem I was...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 0 0 0][f 3 1 1 0 0 12][f 6 1 2 0 0 4]What's that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 18 2 0][f 3 1 1 0 0 13]Watching movies based on nothing but[n]your own painful memories makes you[n]feel like giving up would be easier...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 14]Eventually, you even get to the point[n]where you think getting rid of your[n]individuality really is the right choice.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 6 0 0][f 3 1 1 0 0 15]These people are basically subject to[n]mind control... Even if we were to speak[n]to them, who knows if they'd hear us.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 1 0][f 3 1 1 0 0 16]But, I was able to change for the better,[n]thanks to your editing the movies in[n]my theater.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 17]They made me feel like I shouldn't[n]repress myself or fear the future―[n]and that's how movies ought to be.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 81 6 1 0][f 3 1 1 0 0 18]If all those poor people had been[n]watching those movies instead, I bet[n]they'd all be thinking differently now.[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]That's it![f 2 7 1 64 4 0][e]
[f 0 5 65278][f 2 1]Then we'll screen those for them.[f 2 7 1 64 0 32][e]

[msg MSG_015 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 10 0 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4]Aah! What's the shouting about!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0][f 4 6 12 12 0 4][f 3 1 1 0 0 20]Did you come up with something?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Makoto]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 64 1 0 0][f 4 6 69 12 0 1][f 3 1 1 0 0 21]You mean Hikari-chan's movies that[n]we changed?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 22][f 6 1 2 0 0 4]Are you thinking about showing those[n]to the others in the theaters?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 4][f 3 1 1 0 0 23]Ah, I see―if it goes as planned, the edited[n]movies should change how the theater[n]people think, like with Hikari-chan.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 24]Well, it does seem to follow logically...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 10 0 0][f 3 1 1 0 0 25][f 6 1 2 0 0 10]Hold on, hold on! Sorry, but, uh...[n]what are you all talking about?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 2 12 0 1][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 26]We're not going to convince the[n]theatergoers at a time, but all at once,[n]with the help of Hikari-san's movies.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 27][f 6 1 2 0 0 4]Does that about cover it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 4][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 28]Yeah. If they watch those movies and[n]gain the courage to be themselves,[n]their theater doors should unlock...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 29]Then everyone ought to want to leave[n]their theaters.[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 18 0 0 3][f 3 1 1 0 0 30][f 6 1 2 0 0 4]So, how're we gonna get these movies[n]on their screens?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 6 0 0][f 3 1 1 0 0 31][f 6 1 2 0 0 3]Hmm... Normally, movie theaters don't[n]all show the same thing at once.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 32][f 6 1 2 0 0 4]If we hope to play Hikari-chan's movies[n]to everyone simultaneously, how would[n]we go about that?[n][f 1 3 65535][f 1 1][e]

[sel SEL_025 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]There were those projectors...[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]We'll change the floor film.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Hikari can figure that part out.[f 2 7 1 64 4 32][e]

[msg MSG_026 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 1][f 3 1 1 0 0 33]Correct―I did confirm four running[n]projectors in the vicinity.[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 0 0 0][f 3 1 1 0 0 34]But, how do we use them? Projectors[n]are machines that display film, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 12 0 1][f 3 1 1 0 0 35][f 6 1 2 0 0 4]You mean the film that's flowing all over[n]the ground? You wanna change that?[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 0 0 0][f 3 1 1 0 0 36]Wait, could that film have something to[n]do with those four projectors we saw?[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 10 0 1][f 3 1 1 0 0 37][f 6 1 2 0 0 0]Whoa, whoa! She may be an aspiring[n]movie director and all, but isn't that[n]asking a bit too much!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 38]Oh, but maybe―What if we used those[n]four projectors we saw?[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Yukari]]
[f 0 5 65278][f 2 1][f 4 6 10 12 0 4][f 3 1 1 0 0 39][f 6 1 2 0 0 4]Wait, you really came up with[n]something?[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 70 2 0 1][f 3 1 1 0 0 40][f 6 1 2 0 0 6]I get it! We just need to use those four[n]projectors to screen our own films![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 41]The paths in the movie theater district[n]seem to be made of one long filmstrip[n]that reaches all the theaters there.[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 4 1 0][f 3 1 1 0 0 42]That film was really dark, too. And I[n]don't just mean the color balance...[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 12 0 4][f 3 1 1 0 0 43][f 6 1 2 0 0 4]Could that be causing some negative[n]effect in the other theatergoers?[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 1 0][f 3 1 1 0 0 44]I think the floor film is made up of[n]everyone's darkest memories...[n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 72 12 0 1][f 3 1 1 0 0 45]So, it's a composite of people's[n]memories... That reminds me[n]of the Akashic records.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 6 0 0][f 3 1 1 0 0 46][f 6 1 2 0 0 4]Huh? What are those?[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 4][f 3 1 1 0 0 47]They're supposedly the events and[n]emotions of the entire world written[n]down―indeed, that does ring similar...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 48]However, what's being shown here is[n]far too biased to be called a true record[n]of anything, let alone everything.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 3][f 3 1 1 0 0 49]So, it's a composite of people's[n]memories...[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 50]Indeed. However, what's being shown[n]here is far too biased to be accurate.[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 51]Mmhm... This is a heavily edited version[n]of everyone's memories.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 52]Everything fun or joyful in their lives[n]was cut from the film they're watching.[n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 68 12 0 1][f 3 1 1 0 0 53]While film normally has both positives[n]and negatives, to think that all positive[n]portions have been excised from this...[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 0 0 6][f 3 1 1 0 0 54]When it came to Hikari-chan's movies[n]being screened, we changed them[n]one at a time...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 69 2 0 0][f 3 1 1 0 0 55]But, to change the consciousnesses of[n]the theatergoers, we need to strike at[n]the root cause, all at once.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 12 0 1][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 56]I see! So all we have to do is change the[n]film in the projectors to Hikari-chan's[n]movies.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57]If we do that, I'm sure everyone...[n][f 1 3 65535][f 1 1][e]

[sel SEL_046 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]They'll gain courage.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]They'll leave their theaters.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]They'll... Well, we don't know.[f 2 7 1 64 6 32][e]

[msg MSG_047 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 2 0 1][f 3 1 1 0 0 58][f 6 1 2 0 0 4]Will everyone get cheered up like[n]Hikarin did?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 2 0 4][f 3 1 1 0 0 59][f 6 1 2 0 0 6]Then, we gotta do this![n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 2 0 1][f 3 1 1 0 0 60][f 6 1 2 0 0 6]Yeah. I bet it'll help everybody![n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 12 0 4][f 3 1 1 0 0 61]Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 0 0 1][f 3 1 1 0 0 62]True, there's no guarantee that they'll[n]change if we play Hikari's movies for[n]them. However...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 1][f 3 1 1 0 0 63][f 6 1 2 0 0 4]We aren't the type of people to give up[n]without trying―am I correct?[n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 2 0 4][f 3 1 1 0 0 64]Sure are. If we're gonna show 'em all[n]Hikari's movies, what good will it do if[n]we don't do this with the right attitude?[n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 1 0 1 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 65]Then it's decided―let's swap that[n]negative movie with Hikari's.[n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 4][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 66][f 6 1 2 0 0 4]All we need to do is swap out the film[n]in those projectors we found earlier,[n]right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 0 0 1][f 3 1 1 0 0 67]In that case, we need to grab the movies[n]about Hikari's life that we changed and[n]take 'em back to the projectors.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 68][f 6 1 2 0 0 6]C'mon, let's get to the projection room![n][f 1 3 65535][f 1 1][e]

