[msg MSG_001 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 6 1 3][f 3 1 1 0 0 1]Man, we're really gonna mess with those[n]projectors, huh? I guess we'll be in some[n]real trouble if Enlil busts us...[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 6 0 1][f 3 1 1 0 0 2][f 6 1 2 0 0 9]She's not someone who'll hear what we[n]have to say. If we get caught in the act,[n]she'll really let us have it this time...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 0][f 3 1 1 0 0 3][f 6 1 2 0 0 6]Hooray, it's phantom thief time! We'll[n]slink through the shadows and swiftly[n]seize our target![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akihiko]]
[f 0 5 65278][f 2 1][f 4 6 12 6 0 1][f 3 1 1 0 0 4]It's not in my nature to sneak around.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 12 12 0 1][f 3 1 1 0 0 5]On top of that, I've never done any[n]phantom thieving before. You'll[n]have to show us the ropes here.[n][f 1 3 65535][f 1 1][e]

[sel SEL_005 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]We just go with the flow.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Our style isn't hard to pick up.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Just shut up and follow our lead.[f 2 7 1 64 2 32][e]

[msg MSG_006 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 6 0 4][f 3 1 1 0 0 6][f 6 1 2 0 0 9]I-Is that how you do things?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 0 0][f 3 1 1 0 0 7][f 6 1 2 0 0 6]No way! Our approach is way more[n]strategic than that![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 8]We'll show you the true skills of the[n]Phantom Thieves―just follow our lead![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 65278][f 2 1][f 4 6 9 12 0 1][f 3 1 1 0 0 9][f 6 1 2 0 0 6]Oho, is that so? By the way, Teddie Style[n]is "stuffing yourself with snacks three[n]times a day"![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 6][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 10][f 6 1 2 0 0 9]I don't think that's what he means...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 23 12 0 0][f 3 1 1 0 0 11][f 6 1 2 0 0 6]Style's not something you give lessons[n]on―you just have to feel it![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 12]Anyway, we'll show you the true skills[n]of the Phantom Thieves―just follow[n]our lead![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 6 13 2 0 4][f 3 1 1 0 0 13]Ha... How straightforward.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 13 12 0 4][f 3 1 1 0 0 14]Then we'll follow your example as[n]we advance through the mission.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 0][f 3 1 1 0 0 15][f 6 1 2 0 0 6]Yeah, we'll show you the true skills[n]of the Phantom Thieves![n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 5 2 0 1][f 3 1 1 0 0 16][f 6 1 2 0 0 7]*giggle* It's like all of us have joined[n]the troupe![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 2 0 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]Ooh, that sounds awesome! We get to[n]be in both the Investigation Team AND[n]the Phantom Thieves![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 1][f 3 1 1 0 0 18]Those who pursue and those being[n]pursued―normally, such parties[n]would never fraternize...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 19]Perhaps it's something about this[n]strange world that allows us to[n]join our efforts.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Mitsuru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 13 12 0 1][f 3 1 1 0 0 20]In the same regard, we of SEES will also[n]contribute to the Phantom Thieves for[n]this mission.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 8 0 0][f 3 1 1 0 0 21]Heheh, a phantom thief, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Junpei]]
[f 0 5 65278][f 2 1][f 4 6 11 12 0 1][f 3 1 1 0 0 22]Ah, you're at the age where you dream[n]of that kinda thing. Seems like you're[n]an elementary kid after all, Ken.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 4 0 0][f 3 1 1 0 0 23][f 6 1 2 0 0 6]Th-That's not what I was thinking![n]Leave me alone...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 15 1 0 1][f 4 6 17 0 0 3][f 3 1 1 0 0 24][f 6 1 2 0 0 6]Arf![n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Aigis]]
[f 0 5 65278][f 2 1][f 4 6 15 12 0 0][f 3 1 1 0 0 25]Koromaru-san is enthusiastic as well.[n]He said, "Sign me up too."[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Futaba]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 81 1 1 1][f 4 6 70 2 0 3][f 3 1 1 0 0 26]Oh yeah! Hikari, you're part of the[n]Phantom Thieves too now, okay?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 10 1 0][f 3 1 1 0 0 27][f 6 1 2 0 0 4]Huh? It's really all right for me to...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Haru]]
[f 0 5 65278][f 2 1][f 4 6 71 2 0 6][f 3 1 1 0 0 28]Of course! Let's go try our hardest[n]together.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 2 1 0][f 3 1 1 0 0 29][f 6 1 2 0 0 6]Mmhm... Thank you![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 66 2 0 1][f 3 1 1 0 0 30]Haha, our crew's just ballooned into[n]an army! I thought we were supposed[n]to be the "Phantom" Thieves.[n][f 1 3 65535][f 1 1][e]

[sel SEL_028 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]This is going to be fun.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]This is going to be a handful...[f 2 7 1 64 8 32][e]

[msg MSG_029 [Fuuka]]
[f 0 5 65278][f 2 1][f 4 6 14 10 0 1][f 3 1 1 0 0 31]Wow, what confidence![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 14 2 0 1][f 3 1 1 0 0 32][f 6 1 2 0 0 6]The same goes for our own leader, but[n]yours is so trustworthy... I'm impressed![n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 2 0 4][f 3 1 1 0 0 33]Right? They're all so dependable―even[n][f 6 1 27 0 0 0]-san's got guts![n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 6 0 1][f 3 1 1 0 0 34]Excellent point―it's going to be quite[n]the challenge keeping such unusually[n]unique individuals in line.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 0][f 3 1 1 0 0 35][f 6 1 2 0 0 6]Oh, you're one to talk, Inari![n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 1 4][f 3 1 1 0 0 36][f 6 1 2 0 0 0]Yeah―same for you, ya know!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 2 2 0 3][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 37]I know it may sound strange saying[n]something like this... but honestly,[n]I'm getting a bit excited.[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 1][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 38]Actually, it's not so strange―I feel[n]the same way.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 39]Normally, we never would've met, yet[n]we've all come together for a purpose.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 1 12 0 1][f 3 1 1 0 0 40]Right here, right now, there's only one[n]thing for us to do―in fact, it's something[n]only we can do as well.[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 0 0][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 41]That's right. I'm sure there's a meaning[n]for all of us meeting![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 42]Well then, let's kick off the inaugural[n]mission of the newly-expanded Phantom[n]Thieves! Let's start with the details of―[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 43][f 6 1 2 0 0 1]OH, SHIT! We totally forgot―the calling[n]card![n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 10 0 0][f 3 1 1 0 0 44][f 6 1 2 0 0 4]What? The calling card?[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 68 1 0 1][f 4 6 65 12 0 0][f 3 1 1 0 0 45]We can't start without one! Yusuke―[n]can you whip one up for us?  [n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 69 12 0 6][f 3 1 1 0 0 46]But, this isn't a Palace. There's not[n]really any use for us to send one...[n][f 1 3 65535][f 1 1][e]

[msg MSG_042 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 2 3 6][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 47][f 6 1 2 0 0 7]Oh, a calling card's a must for Phantom[n]Thieves operations! Let's make one, let's[n]make one![n][f 1 3 65535][f 1 1][e]

[msg MSG_043 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 2 0 0][f 3 1 1 0 0 48]I think we should do it too! I-If this'll[n]raise everyone's morale...[n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 2 0 0][f 3 1 1 0 0 49]Ha, so you believe in the beauty of[n]tradition as well... As you wish.[n]I'll prepare one now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 65 2 0 1][f 3 1 1 0 0 50][f 6 1 2 0 0 6]Welp, all that's left is our usual cheer![n]Take it away, [f 6 1 30 0 0 0]![n][f 1 3 65535][f 1 1][e]

[sel SEL_046 top]
[f 0 5 65278][f 2 1][f 4 6 64 1 0 0]It's showtime![f 2 7 1 64 8 1][e]
[f 0 5 65278][f 2 1]Let's steal Enlil's movie![f 2 7 1 64 8 1][e]
[f 0 5 65278][f 2 1]I can't think one up offhand...[f 2 7 1 64 4 32][e]

[msg MSG_047 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 10 0 0][f 3 1 1 0 0 51][f 6 1 2 0 0 0]Whaaaat...? NOW'S when you clam up[n]on us!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_048 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 52]*sigh* I guess we've got no other choice.[n]Allow me to get this started the right[n]way...[n][f 1 3 65535][f 1 1][e]

[msg MSG_049 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 4 3 1][f 3 1 1 0 0 53][f 6 1 2 0 0 1]Grand Phantom Thieves, let's begin the[n]operation![n][f 1 3 65535][f 1 1][e]

[msg MSG_050 [Ann]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 54]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_051 [Ryuji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 55]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_052 [Yusuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 56]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_053 [Makoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 57]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_054 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 58]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_055 [Haru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 59]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_056 [Futaba]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 70]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_057 [Akechi]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 71]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_058 [P4 Protag]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 72]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_059 [Chie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 73]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_060 [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 74]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_061 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 75]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_062 [Kanji]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 76]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_063 [Naoto]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 77]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_064 [Rise]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 78]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_065 [Teddie]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 79]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_066 [Yukari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 80]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_067 [Junpei]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 81]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_068 [Fuuka]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 82]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_069 [Akihiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 83]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_070 [Shinjiro]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 84]Yeah...[n][f 1 3 65535][f 1 1][e]

[msg MSG_071 [Mitsuru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 85]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_072 [Ken]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 86]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_073 [Koromaru]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 87]Awoooo![n][f 1 3 65535][f 1 1][e]

[msg MSG_074 [Aigis]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 88]Yes![n][f 1 3 65535][f 1 1][e]

[msg MSG_075 [P3 Protag]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 89]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_076 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 90]Yeah![n][f 1 3 65535][f 1 1][e]

[msg MSG_077 [Hikari]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 91]Yeah![n][f 1 3 65535][f 1 1][e]

