[msg MSG_000 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 88 0 0 9][f 4 6 81 10 1 8][f 3 1 1 0 0 1][f 6 1 2 0 0 0]No... This again!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 10 0 7][f 3 1 1 0 0 2][f 6 1 2 0 0 4]I thought he had disappeared...[n][f 1 3 65535][f 1 1][e]

[sel SEL_002 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 8]Is that really Doe?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]That's a phony.[f 2 7 1 20 6 32][e]

[msg MSG_003 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 0 0 7][f 3 1 1 0 0 3]He's most likely from a different film[n]than the one we edited.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 7][f 3 1 1 0 0 4]Right. At the very least, he's not the[n]same one that we know.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [P3 Hero]]
[f 0 5 65278][f 2 1][f 4 6 2 12 0 8][f 1 5][f 6 1 16 0 0 0][n][f 3 1 1 0 0 5]I think you're right. Doe was born from[n]Hikari-san's distorted cognition...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 6]But her consciousness has changed[n]already.[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Koromaru]]
[f 0 5 65278][f 2 1][f 4 6 17 4 0 7][f 3 1 1 0 0 7][f 6 1 2 0 0 6]Grrrrr...[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Shinjiro]]
[f 0 5 65278][f 2 1][f 4 6 18 12 0 8][f 3 1 1 0 0 8]So what we're seein' here's the distorted[n]version of the film, huh?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 6 0 7][f 1 5][f 6 1 13 0 0 0][n][f 3 1 1 0 0 9][f 6 1 2 0 0 3]That would mean the consciousness[n]of the people in the theaters is still[n]distorted...[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Ken]]
[f 0 5 65278][f 2 1][f 4 6 16 12 0 8][f 3 1 1 0 0 10][f 6 1 2 0 0 4]If we leave this as it is, everyone will be[n]forced to keep watching that distorted[n]movie, right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 4 0 7][f 1 5][f 6 1 27 0 0 0][n][f 3 1 1 0 0 11][f 6 1 2 0 0 6]Then we need to change it. We'll change[n]it as many times as we have to![n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Doe]]
[f 0 5 65278][f 2 1][f 4 6 88 0 0 9][f 3 1 1 0 0 12]As long as you live, you will face suffering[n]and strife. Oppose others and you will[n]be hurt.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 13]If you don't want to be hurt, discard[n]everything and surrender yourself[n]to this movie.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 8][f 4 6 81 12 1 7][f 3 1 1 0 0 14]You're wrong! Nobody wants to see[n]a movie like that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 15]The protagonists in the movies I want[n]to see always get back on their feet,[n]no matter how hurt they end up.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Doe]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 16][f 6 1 3 0 0 2]Isn't this what you wished for? More[n]than anyone else? Just look away and[n]you'll soon be at ease.[n][f 1 3 65535][f 1 1][e]

[sel SEL_014 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]That's just avoiding reality.[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]Yeah, it's easy, but not fun at all.[f 2 7 1 20 6 32][e]

[msg MSG_015 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 14 6 0][f 3 1 1 0 0 17][f 6 1 2 0 0 6]I'll watch the movies that I want to see![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Doe]]
[f 0 5 65278][f 2 1][f 4 6 88 2 0 9][f 3 1 1 0 0 18][f 6 1 1 0 0 1]Ngh... Nngh... Gggghhhh...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 1 0 0 1]If only... you all weren't here...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 1 7][f 3 1 1 0 0 20][f 6 1 2 0 0 6]Get ready! Here he comes![n][f 1 3 65535][f 1 1][e]

