[msg MSG_000 [Upset woman]]
[f 0 5 65278][f 2 1][f 4 6 63 0 1 1][f 3 1 1 0 0 1]Ah... I remember now...[n]What I really wanted...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Languid man]]
[f 0 5 65278][f 2 1][f 4 6 61 0 1 3][f 3 1 1 0 0 2]That's right... Deep down,[n]I didn't want to give up![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Despondent woman]]
[f 0 5 65278][f 2 1][f 4 6 62 0 1 1][f 3 1 1 0 0 3]I won't give up yet either. I'm going[n]to stick it out just a bit longer![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Listless man]]
[f 0 5 65278][f 2 1][f 4 6 60 0 1 3][f 3 1 1 0 0 4]Haha... Guess all we needed[n]was a bit of courage...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5]Thank you...[n][f 1 3 65535][f 1 1][e]

