name: Spanish Mod

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  process_and_compile_files_job:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: SET N
      run: python MsgEditorLT/setn_folder.py

    - name: IMPORT TO PARAMS
      run: python MsgEditorLT/import_msg_params.py

    - name: COMPILE
      run: python MsgEditorLT/compiler.py

    - name: Upload compiled artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: MsgEditorLT/compiled/
        if-no-files-found: warn
