name: Spanish Mod

on:
  push:
    branches:
      - master
    paths:
      - 'MsgEditorLT/Data/**'
  pull_request:
    branches:
      - master
    paths:
      - 'MsgEditorLT/Data/**'

jobs:
  process_and_compile_files:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      # Check out the repository code
      uses: actions/checkout@v4

    - name: Set up Python
      # Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: SET N
      # Run setn_folder.py script
      run: python MsgEditorLT/setn_folder.py

    - name: IMPORT TO PARAMS
      # Run import_msg_params.py script
      run: python MsgEditorLT/import_msg_params.py

    - name: COMPILE
      # Compile using compiler.py script
      run: python MsgEditorLT/compiler.py

    - name: Upload compiled artifact
      # Upload the compiled files as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: spanish-mod-dev
        path: MsgEditorLT/compiled/
        if-no-files-found: warn

  create_release:
    needs: process_and_compile_files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Check out the repository code
      uses: actions/checkout@v4

    - name: Download artifact
      # Download the compiled files artifact
      uses: actions/download-artifact@v4
      with:
        name: spanish-mod-dev
        path: ./compiled

    - name: Create Pre-Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./compiled
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.0-$(date +%s)  # Unique tag name using current timestamp
        name: Spanish Mod Pre-release
        body: |
          Pre-release.
        draft: false
        prerelease: true