[msg MSG_000 [P3 Fem Protag]]
夷Encontramos la Plaza Kamoshida?

[msg MSG_001 [Ann]]
Apuesto a que lo hicimos...

[msg MSG_002 [Ann]]
Solo grita, "aqu胤 es"... lo m茨s alto[n]posible.

[msg MSG_003 [Ryuji]]
El palacio de Kamoshida era asqueroso,[n]pero esto no est茨 muy alejado...

[msg MSG_004 [Yusuke]]
斡Blugh...!

[msg MSG_005 [Futaba]]
斡夷Qu姻 pasa?!

[msg MSG_006 [Yusuke]]
Es horrible... 斡Esa estatua es[n]completamente repugnante!
No, m茨s que eso, 斡es una profanaci吋n a[n]la belleza!

[sel SEL_007 top]
En serio...
Es basura.

[msg MSG_008 [夷Voz Heroica]]
斡USTEDES son los repugnantes!

[msg MSG_009 [Morgana]]
斡夷Qu姻?!

[msg MSG_010 [Kamoshidaman]]
斡JA JA JA JA! 斡Buen trabajo llegando tan[n]lejos, villanos de mi ciudad!

[msg MSG_011 [Ann]]
斡Queen! 斡Noir!

[msg MSG_012 [Haru]]
斡Chicos!

[msg MSG_013 [Kamoshidaman]]
斡Ahora castigar姻 a la basura de la[n]sociedad ante ustedes!

[msg MSG_014 [P3 Fem Protag]]
斡夷"Basura de la sociedad"?!

[msg MSG_015 [Kamoshidaman]]
斡JA JA JA JA! 斡As胤 es!

[msg MSG_015_5 [Kamoshidaman]]
No solo me desobedecen a m胤, el[n]protector de esta ciudad...
Tambi姻n siembran discordia entre los[n]ciudadanos y solo traen caos a nuestra[n]pac胤fica sociedad.
夷C吋mo deber胤a referirme a tal basura?

[msg MSG_016 [Ryuji]]
Hijo de... 斡No acepto nada de esta[n]mierda egoc姻ntrica!

[msg MSG_017 [Kamoshidaman]]
夷Egoc姻ntrica? Yo estoy muy lejos de[n]eso...

[msg MSG_018 [Hombre Descarado]]
Esos son los criminales, 夷verdad?

[msg MSG_019 [Mujer Cansada]]
Si Kamoshidaman lo dice, entonces deben[n]serlo...

[msg MSG_020 [Hombre Agitado]]
斡Dijo que son los criminales!

[msg MSG_021 [Ann]]
La gente lo apoya...

[msg MSG_022 [Kamoshidaman]]
斡JA JA JA JA! 斡As胤 es!
Pueden ser criminales, pero aun as胤,[n]debo felicitarlos por no abandonar a sus[n]compa隠eras como cobardes.

[msg MSG_022_5 [Kamoshidaman]]
Sin embargo, 斡me han desafiado! 斡No son[n]m茨s que basura, contaminando toda mi[n]sociedad!
斡Estos rebeldes ser茨n castigados por mi[n]juicio!

[msg MSG_023 [Ryuji]]
斡夷Qu姻?! 斡Un bastardo hambriento de poder[n]como t雨 no tiene derecho a juzgarnos!

[msg MSG_024 [Yusuke]]
Todo lo que haces es aprovecharte de los[n]ciudadanos con tu autoridad... Es[n]pat姻tico.

[msg MSG_025 [Ann]]
斡Y lo mismo ocurre con toda la gente de[n]esta ciudad que te sigue ciegamente!

[msg MSG_026 [Kamoshidaman]]
Mmm, parece que esta basura ni siquiera[n]tienen las neuronas necesarias para[n]admitir sus errores.

[msg MSG_027 [Akechi]]
No creo que discutir con 姻l nos lleve a[n]alg雨n lado. 夷Qu姻 hacemos?

[sel SEL_028 top]
Usar la fuerza bruta.
Derrotar a los ciudadanos.
Salvar a Queen y a Noir.

[msg MSG_029 [Yusuke]]
No perdamos tiempo con ese plan.[n]Seguramente utilizara a los ciudadanos.

[msg MSG_030 [Ann]]
斡S胤, vamos a darle una lecci吋n y[n]rescatarlas!

[msg MSG_031 [Ryuji]]
Parece que tenemos que hacerlo[n]reaccionar como lo hicimos con[n]Kamoshida...
Estoy seguro de que eso har茨 que la[n]gente reaccione tambi姻n.

[msg MSG_032 [Ann]]
斡S胤! 斡Vamos a derrotarlo y salvar a esas[n]dos!

[msg MSG_033 [Ryuji]]
Bien, esto no va a ning雨n lado.[n]斡Tendremos que derribarlo!

[msg MSG_034 [Yusuke]]
Eso tambi姻n deber胤a despertar a los[n]ciudadanos.

[msg MSG_035 [Kamoshidaman]]
斡JA JA JA JA! 斡Soy invencible! 斡Soy la[n]justicia! 斡Simples ni隠os no pueden[n]derrotarme!

