[msg MSG_000 [Voz De Hombre]]
Umm...

[msg MSG_001 [Caroline]]
ムEscuchen, serホ mejor que se aseguren de[n]mantener cerca a nuestro recluso!

[msg MSG_002 [Ryuji]]
Sボ, sボ...

[msg MSG_003 [Caroline]]
ムQu〒 insolencia! ムメQuieres ser ejecutado[n]tambi〒n?!

[msg MSG_004 [Futaba]]
Es tan dura... メUna niワa pequeワa y[n]militarista? ムSiento que estoy[n]descubriendo una nueva obsesiポn!

[msg MSG_005 [Voz De Hombre]]
Perdポname...

[msg MSG_006 [Ann]]
Yusuke, メhas dicho algo?

[msg MSG_007 [Yusuke]]
No, yo no.

[msg MSG_008 [Ann]]
Pens〒 que habボa oボdo la voz de[n]alguien... メTal vez estoy imaginando[n]cosas?

[msg MSG_009 [Voz De Hombre]]
Mm, solo un momento de tu tiempo...

[msg MSG_010 [Yusuke]]
Ann, detrホs de ti, メqui〒n es?

[msg MSG_011 [Ann]]
メEh?

[msg MSG_012 [Hombre De Azul]]
Ah, finalmente, alguien se dio cuenta…

[msg MSG_013 [Ann]]
ムAaaaaaaaah!

[msg MSG_014 [Hombre De Azul]]
ムメWaaaaaaaaah?!

[msg MSG_015 [Ryuji]]
ムメPor qu〒 tambi〒n te sorprendes?! Y, lo[n]mホs importante, ムメQUI※N eres?!

[msg MSG_016 [Mujer De Azul]]
Puedo oボr que me llaman...

[msg MSG_017 [Futaba]]
ムO-o-OTRA MミS?!

[msg MSG_018 [Caroline]]
Oye, Justine...

[msg MSG_019 [Justine]]
Esos dos...

[msg MSG_020 [Mujer De Azul]]
Nos complace mucho conocerlos.

[msg MSG_021 [Ryuji]]
メQui〒n demonios son ustedes? ムメY por qu〒[n]todos son azules?!

[msg MSG_022 [Mujer De Azul]]
Soy Elizabeth. Este es mi hermano menor,[n]Theodore.

[msg MSG_023 [Theodore]]
Encantado de conocerlos, me llamo[n]Theodore.

[msg MSG_024 [Akechi]]
メCuホnto tiempo llevan ahボ?

[msg MSG_025 [Elizabeth]]
*risa* Siempre estamos a su lado, en[n]cualquier momento, en cualquier lugar.

[msg MSG_026 [Ryuji]]
Oh, genial, mホs mierda mental...

[msg MSG_037 [Morgana]]
No entiendo lo que estホ pasando aquボ...[n]Todo esto es raro.

[msg MSG_038 [Yusuke]]
Este mundo estホ lleno de misterios. No[n]puedo entenderlo tampoco.

[msg MSG_039 [Ann]]
Bueno, llevan ropa similar a esas[n]gemelas. メPodrボan ser compaワeros de[n]trabajo?

[msg MSG_040 [Theodore]]
Bien... quizホs sea mejor decir que todos[n]somos "Asistentes de la Habitaciポn[n]Terciopelo".

[msg MSG_041 [Elizabeth]]
En efecto, sin embargo, omitamos los[n]detalles por ahora y vayamos directo al[n]grano.

[msg MSG_042 [Theodore]]
A-ah, ムsボ!
Al llegar a este mundo, me separ〒 de mi[n]invitada...
La busqu〒 por todas partes en este cine,[n]pero no hay rastro de ella.

[msg MSG_043 [Ryuji]]
メTu invitada? メTambi〒n es toda azul?

[msg MSG_044 [Theodore]]
No. Es una chica de instituto, con[n]auriculares...

[msg MSG_045 [Yusuke]]
メAuriculares?

[msg MSG_046 [Futaba]]
Tengo auriculares, pero no estoy en el[n]instituto.

[msg MSG_047 [Ann]]
No lo s〒... No hemos visto a nadie asボ,[n]メverdad [f 6 1 30 0 0 0]?

[sel SEL_048 top]
No.
Entonces, ella tambi〒n estホ perdida...

[msg MSG_049 [Nagi]]
No tengo ni idea tampoco...

[msg MSG_049_5 [Nagi]]
メY tマ, Hikari?

[msg MSG_050 [Hikari]]
No, no...

[msg MSG_051 [Theodore]]
Ya veo. Eso es preocupante...

[msg MSG_052 [Yusuke]]
メPodrボa estar dentro de la pelボcula,[n]como nuestras amigas?

[msg MSG_053 [Theodore]]
メDentro de la pelボcula? メA qu〒 te...?

[msg MSG_054 [Elizabeth]]
Theo, no hagas preguntas tan frボvolas.[n]Simplemente, debes percibir su[n]significado.

[msg MSG_055 [Theodore]]
Ah, discマlpame...

[msg MSG_056 [Ryuji]]
Theodore... Supongo que si encontramos a[n]esa chica, la traeremos de vuelta.

[msg MSG_057 [Theodore]]
ムOh, muchas gracias! Eso serボa de gran[n]ayuda.

[msg MSG_058 [Elizabeth]]
Theo, se necesitan mホs que palabras para[n]expresar gratitud.

[msg MSG_059 [Theodore]]
Mホs que palabras, メquieres decir... que[n]tambi〒n debo inclinarme?

[msg MSG_060 [Elizabeth]]
Para nada. Segマn mi intuiciポn...

[msg MSG_061 [Elizabeth]]
Creo que estas personas han caボdo en[n]este mundo y ahora estホn atrapadas aquボ.
Y tal vez, su マnica salida est〒[n]asegurada con numerosas cerraduras[n]intimidantes...

[msg MSG_062 [Ryuji]]
ムメCポmo sabes todo eso?!

[msg MSG_063 [Theodore]]
Mucho sucede en el curso de la vida.[n]Nosotros hemos experimentado bastante.

[msg MSG_064 [Elizabeth]]
Nuestra llegada aquボ tambi〒n fue[n]inevitable... Hemos sido llevados aquボ[n]por el destino.

[msg MSG_064_5 [Elizabeth]]
Es por eso que mi tonto hermano menor[n]Theodore les proporcionarホ toda la ayuda[n]que necesiten.

[msg MSG_065 [Theodore]]
メEh? ムメH-hermana?!

[msg MSG_066 [Elizabeth]]
"Buena compaワボa en el camino es el atajo[n]mホs corto hacia la tumba", creo que es[n]el dicho.
En cualquier caso, debemos mantener el[n]espボritu de ayudar a aquellos que lo[n]necesitan.

[sel SEL_067 top]
Eso serボa genial.
Esto es demasiado extraワo.
メQu〒 clase de ayuda, exactamente?

[msg MSG_068 [Ann]]
Todavボa no lo entiendo, pero no parecen[n]ser enemigos...
Cuanto mホs gente nos ayude, mejor,[n]メcierto?

[msg MSG_069 [Akechi]]
Entonces, メcポmo nos ayudarボan[n]especボficamente?

[msg MSG_070 [Ryuji]]
Sボ, メverdad? Primero pensamos que[n]estaban con esas gemelas, pero parece[n]que no.

[msg MSG_071 [Ann]]
Pero no parecen enemigos. メTal vez[n]debemos confiar en ellos?

[msg MSG_072 [Akechi]]
Entonces, メcポmo nos ayudarボan[n]especボficamente?

[msg MSG_073 [Elizabeth]]
Bueno, メhay algマn lugar cercano donde[n]podamos establecer nuestro negocio y[n]aprovecharnos?
...Quiero decir, complacerlos con[n]nuestras finas mercancボas, メquizホs?

[msg MSG_074 [Futaba]]
Ella definitivamente acaba de decir[n]"aprovecharnos".

[msg MSG_075 [Elizabeth]]
No escuch〒 eso, laaalaalaaa...

[msg MSG_076 [Futaba]]
ムMi puntuaciポn ha bajado!

[msg MSG_077 [Ryuji]]
Hay un puesto de comida en el vestボbulo.[n]メQu〒 tal allボ?

[msg MSG_078 [Nagi]]
Si eso les sirve, con gusto les mostrar〒[n]el camino...

[msg MSG_027 [Theodore]]
...メMm? Hermana, esas dos de allボ...

[msg MSG_028 [Elizabeth]]
Oh, vaya, メqu〒 tenemos aquボ...?

[msg MSG_029 [Caroline]]
Hmp...

[msg MSG_030 [Justine]]
...

[msg MSG_031 [Elizabeth]]
Mm, entiendo...

[msg MSG_031_5 [Elizabeth]]
Escucha, Theo: Serボa poco educado[n]entrometerse en asuntos mホs allホ de lo[n]necesario.

[msg MSG_032 [Theodore]]
Pero, Hermana...

[msg MSG_033 [Elizabeth]]
Nada pasa sin motivo. Debe haber una[n]razポn para que nos llamaran a este[n]lugar...
Y buscar esa razポn puede ser otra[n]necesidad.

[msg MSG_034 [Caroline]]
Justine, メqui〒nes crees que son?

[msg MSG_035 [Justine]]
Siento como si... estuvieran[n]relacionados con nuestra existencia.
Quien sabe que dirホ nuestro amo sobre[n]esto... No profundicemos mホs por ahora.

[msg MSG_036 [Caroline]]
Hmp, tienes razポn... mientras no[n]interfieran con la rehabilitaciポn del[n]recluso.

[msg MSG_079 [Caroline]]
ムAhora escucha, Recluso! Hasta que[n]escapemos de este cine, te permitiremos[n]moverte libremente.

[msg MSG_080 [Justine]]
En otras palabras, estホs en libertad[n]condicional. Pero no olvides tu[n]rehabilitaciポn.

[msg MSG_081 [Elizabeth]]
Bien, entonces, vayamos de prisa al[n]puesto de comida...

