[msg MSG_000]
Cine, taquilla...
Akechi estホ hablando con Elizabeth...

[msg MSG_001 [Akechi]]
Ah, has venido.

[sel SEL_002 top]
Espero no interrumpir.
Hay algo raro en el ambiente.

[msg MSG_003 [Akechi]]
No es nada serio.
Algo me dio curiosidad antes, asボ que[n]querボa preguntar.

[msg MSG_004 [Elizabeth]]
Aja, asボ que esto debe ser lo que llaman[n]"interrogaciポn"... Estoy bastante[n]emocionada de experimentarlo en persona.

[sel SEL_005 top]
メLa estホs interrogando?
メEsto te emociona?

[msg MSG_006 [Akechi]]
Como dije, no es nada serio, solo una[n]simple pregunta.

[msg MSG_007 [Elizabeth]]
Bueno, eso es lamentable. Estaba[n]esperando experimentarlo con una porciポn[n]de "Katsu Dune"...

[msg MSG_008 [Akechi]]
Ja, ja, ja, メte refieres a las series[n]policボacas donde ofrecen comida a los[n]sospechosos cuando los interrogan? Eso es[n]puramente ficticio.
Esto es simplemente para satisfacer mi[n]curiosidad personal.

[msg MSG_009 [Akechi]]
Mencionaste anteriormente que nada sin[n]sentido ocurre en la Habitaciポn[n]Terciopelo...
Entonces, メcポmo explicarボas la presencia[n]de [f 6 1 26 0 0 0]?

[sel SEL_010 top]
メQu〒 quieres decir?
ムメElla... es la responsable de todo[n]esto?!

[msg MSG_011 [Elizabeth]]
*risa* Pensar que llegarボas a esa[n]conclusiポn... Estホs bien adaptado a las[n]tareas de detective.

[msg MSG_012 [Akechi]]
Si la memoria no me falla, [f 6 1 26 0 0 0] vino[n]aquボ a trav〒s de la Habitaciポn[n]Terciopelo...
Lo que quiero preguntar es si eso tiene[n]algマn significado.

[msg MSG_013 [Elizabeth]]
Sボ, creo que su llegada no es una simple[n]coincidencia...
Sin embargo, eso no solo se aplica a[n]ella.

[msg MSG_014 [Akechi]]
メQu〒 quieres decir?

[msg MSG_015 [Elizabeth]]
Dado que tambi〒n te has encontrado con[n]asistentes de la Habitaciポn[n]Terciopelo...
Tu presencia aquボ tambi〒n era inevitable[n]y tiene algマn significado...

[msg MSG_016 [Akechi]]
Un significado, メeh...? Pero ese[n]significado no te involucra[n]directamente, メverdad?
Asボ que todas nuestras respuestas estホn[n]mホs allホ del final de la pelボcula...

[sel SEL_017 top]
Tengo curiosidad por ver cポmo terminarホ.
Vamos a trabajar en el plan.

[msg MSG_018 [Elizabeth]]
Si alcanzan o no ese final depende de[n]ustedes...
Todos parecen estar tramando algo...[n]Solo con presenciarlos, mi corazポn se[n]acelera.

[msg MSG_019 [Akechi]]
Nuestro plan debe tener 〒xito si[n]queremos descubrirlo.

[msg MSG_020 [Elizabeth]]
Sボ, creo que esa serボa una sabia[n]decisiポn.
Si alcanzan o no el final de la pelボcula[n]depende completamente de todos ustedes.

[msg MSG_021 [Akechi]]
Sボ, y para lograrlo, necesitamos[n]asegurarnos de que este plan tenga[n]〒xito.

[msg MSG_022]
Parece que las cosas van bien por aquボ.[n]Deberボa volver por ahora...

[msg MSG_023]
Parece que las cosas van bien por aquボ.[n]Tal vez deberボa ver a los demホs...

[sel SEL_024 top]
y Yusuke
Ann y Ryuji
Morgana y Futaba

