[msg MSG_000 [Futaba]]
ムJoker! ムEspera! ムPara, paaraaaa!

[msg MSG_001 [Ann]]
Ah-ムメQu〒 pasa?!

[msg MSG_002 [Yusuke]]
メHay una trampa?

[msg MSG_003 [Futaba]]
ムNo, es sobre el cine!
メRecuerdas esa puerta que decボa "Solo[n]personal autorizado"?

[msg MSG_004 [Ryuji]]
Oh, メTe refieres a la que estaba[n]cerrada? メQu〒 pasa con ella?

[msg MSG_005 [Futaba]]
De repente intercept〒 una seワal muy[n]fuerte de esa puerta.

[msg MSG_006 [Ann]]
メUna seワal? メTe refieres a un enemigo?

[msg MSG_007 [Futaba]]
No, es muy extraワa, una presencia[n]extraワa, e incluso Nagi no sabe que[n]podrボa ser...
Es muy poco probable que sean Queen y[n]Noir, pero aun asボ creo que deberボamos[n]revisar.

[msg MSG_008 [Akechi]]
Si es asボ, entonces tenemos que volver[n]al cine... Joker.

[sel SEL_009 top]
Volvamos.
Vamos a revisar.

[msg MSG_010 [Futaba]]
Bien, ムRegresen lo antes posible, los[n]estar〒 esperando!

[msg MSG_011 [Yusuke]]
Una presencia misteriosa, メeh? Me[n]pregunto que podrボa ser...

