[msg MSG_000 [Chica De Cabello Casta隠o]]
Uf, me salvaron... 斡Gracias!

[msg MSG_000_5 [Chica De Cabello Casta隠o]]
Mm, ustedes son... 夷Usuarios de Persona[n]tambi姻n?

[msg MSG_001 [Ryuji]]
S胤, parece que t雨 tambi姻n.

[msg MSG_002 [Yusuke]]
Pensar que hay otros usuarios de Persona[n]aqu胤... Siento un misterioso destino que[n]nos une.

[msg MSG_003 [Chica De Cabello Casta隠o]]
Tambi姻n estoy sorprendida... 斡Tienen[n]m茨scaras tan elaboradas que pens姻 que[n]eran m茨s enemigos!

[msg MSG_004 [Ann]]
Ja, ja... S胤, supongo que se ven raras[n]desde las perspectivas de otros...

[sel SEL_005 top]
No son raras.
Son elegantes.
No somos tus enemigos.

[msg MSG_006 [Chica De Cabello Casta隠o]]
Oh... Em, lo siento.

[msg MSG_006_5 [Chica De Cabello Casta隠o]]
No quise decir que estaban mal, 斡Creo[n]que tienen mucha personalidad!

[msg MSG_007 [Chica De Cabello Casta隠o]]
S胤, estoy de acuerdo. Creo que est茨n[n]llenas de personalidad.

[msg MSG_008 [Chica De Cabello Casta隠o]]
斡S胤, despu姻s de todo, me salvaron porque[n]vieron que estaba en problemas!

[msg MSG_009 [Chica De Cabello Casta隠o]]
斡S胤! Dijiste algo hace un momento,[n]斡夷conoces a Theo?!

[msg MSG_010 [Akechi]]
S胤, aunque lo conocimos recientemente.

[msg MSG_011 [Chica De Cabello Casta隠o]]
Oh… Me alegra que Theo este a salvo. Nos[n]separamos de repente, as胤 que estaba[n]preocupada por 姻l.

[msg MSG_012 [Akechi]]
Parec胤a estar preocupado por ti. Espero[n]que te re雨nas pronto con 姻l.

[msg MSG_013 [Chica De Cabello Casta隠o]]
斡Gracias!
Oh, a雨n no me he presentado. Mi nombre[n]es...

