[msg MSG_000 [Morgana]]
ムFinalmente, es el momento, chicos!
ムSi esa estatua es la debilidad de Kamoshidaman, esto deberボa interferir con sus poderes!

[msg MSG_001 [Akechi]]
Bien, entonces, a nuestras posiciones.

[msg MSG_002 [Ryuji]]
ムVamos, Panther!

[msg MSG_003 [Ann]]
ムCポmo lo planeamos, Skull!

[msg MSG_003_5 [Ann]]
Solo aguanten, chicas... ムVamos por ustedes!

[msg MSG_004 [P3 Fem Protag]]
Deja el panel de interruptores en mis manos. Har〒 mi parte cuando sea el momento.

[msg MSG_005 [Yusuke]]
Puedo preparar mi accesorio de inmediato. Te avisar〒 cuando est〒 listo.

[msg MSG_006 [Morgana]]
Entonces, ムtodo lo que tenemos que hacer es esperar el momento adecuado!

[msg MSG_007 [Portavoz]]
Ciudadanos de Ciudad Kamo, esto es un anuncio pマblico...
La exhibiciポn de castigo en la Plaza Kamoshida estホ a punto de comenzar.
Repito...

[msg MSG_008 [Hombre Emocionado]]
Parece que las personas que desafiaron a Kamoshidaman finalmente serホn castigadas.

[msg MSG_009 [Mujer Joven]]
Si Kamoshidaman dice que son malvadas, ムentonces debe pasar!

[msg MSG_010 [Kamoshidaman]]
ムJA, JA, JA! Como todos saben, soy la justicia absoluta de esta ciudad.

[msg MSG_011 [Hombre Fanホtico]]
ムSボ!

[msg MSG_012 [Hombre De Mediana Edad]]
ムSi simplemente seguimos a Kamoshidaman, nuestra ciudad estarホ en paz!

[msg MSG_013 [Kamoshidaman]]
ムEn efecto! ムSolo a trav〒s de mi existencia existe la paz en la ciudad!
Sin embargo, han aparecido violadores de esa paz. ムCualquiera que se oponga a mボ es malvado y un criminal!
ムY castigar〒 este mal que perturba nuestra paz con mi propia justicia!

[msg MSG_014 [Mujer Suplicante]]
ムTe lo suplicamos, prot〒genos de los criminales, por nuestro bien!

[msg MSG_015 [Jovencito]]
Kamoshidaman es la justicia, メverdad? Es lo que todos dicen...

[msg MSG_016 [Viejo]]
ムCreemos en ti, Kamoshidaman!

[msg MSG_017 [Ryuji]]
ム"Mi propia justicia"! ムVaya mierda egoボsta!

[msg MSG_018 [Ann]]
ム※l puede hacer que suene tan bien como quiera, pero lo マnico que estホ haciendo es reprimir a todos con su poder!

[msg MSG_019 [Yusuke]]
Mis disculpas por el retraso; todo estホ listo.

[msg MSG_020 [Ryuji]]
ムEstamos listos tambi〒n!

[msg MSG_021 [P3 Fem Protag]]
Estoy tan nerviosa que estoy sudando...
Espera, メo deberボan ser balas? ムDe todos modos, no tenemos otra opciポn!

[msg MSG_022 [Futaba]]
Parece que todos estホn en posiciポn...
Entonces, ムiniciemos este atraco! Joker, haz los honores.

[sel SEL_023 top]
ムVamos!
ムRobemos esa estatua!

[msg MSG_024 [Morgana]]
ムEsta vez lo venceremos y rescataremos a Queen y Noir!

