[msg MSG_000]
Cine, taquilla...
Akechi est茨 hablando con Elizabeth...

[msg MSG_001 [Akechi]]
Ah, has venido.

[sel SEL_002 top]
Espero no interrumpir.
Hay algo raro en el ambiente.

[msg MSG_003 [Akechi]]
No es nada serio.
Algo me dio curiosidad antes, as胤 que[n]quer胤a preguntar.

[msg MSG_004 [Elizabeth]]
Aja, as胤 que esto debe ser lo que llaman[n]"interrogaci吋n"... Estoy bastante[n]emocionada de experimentarlo en persona.

[sel SEL_005 top]
夷La est茨s interrogando?
夷Esto te emociona?

[msg MSG_006 [Akechi]]
Como dije, no es nada serio, solo una[n]simple pregunta.

[msg MSG_007 [Elizabeth]]
Bueno, eso es lamentable. Estaba[n]esperando experimentarlo con una porci吋n[n]de "Katsu Dune"...

[msg MSG_008 [Akechi]]
Ja, ja, ja, 夷te refieres a las series[n]polic胤acas donde ofrecen comida a los[n]sospechosos cuando los interrogan? Eso es[n]puramente ficticio.
Esto es simplemente para satisfacer mi[n]curiosidad personal.

[msg MSG_009 [Akechi]]
Mencionaste anteriormente que nada sin[n]sentido ocurre en la Habitaci吋n[n]Terciopelo...
Entonces, 夷c吋mo explicar胤as la presencia[n]de [f 6 1 26 0 0 0]?

[sel SEL_010 top]
夷Qu姻 quieres decir?
斡夷Ella... es la responsable de todo[n]esto?!

[msg MSG_011 [Elizabeth]]
*risa* Pensar que llegar胤as a esa[n]conclusi吋n... Est茨s bien adaptado a las[n]tareas de detective.

[msg MSG_012 [Akechi]]
Si la memoria no me falla, [f 6 1 26 0 0 0] vino[n]aqu胤 a trav姻s de la Habitaci吋n[n]Terciopelo...
Lo que quiero preguntar es si eso tiene[n]alg雨n significado.

[msg MSG_013 [Elizabeth]]
S胤, creo que su llegada no es una simple[n]coincidencia...
Sin embargo, eso no solo se aplica a[n]ella.

[msg MSG_014 [Akechi]]
夷Qu姻 quieres decir?

[msg MSG_015 [Elizabeth]]
Dado que tambi姻n te has encontrado con[n]asistentes de la Habitaci吋n[n]Terciopelo...
Tu presencia aqu胤 tambi姻n era inevitable[n]y tiene alg雨n significado...

[msg MSG_016 [Akechi]]
Un significado, 夷eh...? Pero ese[n]significado no te involucra[n]directamente, 夷verdad?
As胤 que todas nuestras respuestas est茨n[n]m茨s all茨 del final de la pel胤cula...

[sel SEL_017 top]
Tengo curiosidad por ver c吋mo terminar茨.
Vamos a trabajar en el plan.

[msg MSG_018 [Elizabeth]]
Si alcanzan o no ese final depende de[n]ustedes...
Todos parecen estar tramando algo...[n]Solo con presenciarlos, mi coraz吋n se[n]acelera.

[msg MSG_019 [Akechi]]
Nuestro plan debe tener 姻xito si[n]queremos descubrirlo.

[msg MSG_020 [Elizabeth]]
S胤, creo que esa ser胤a una sabia[n]decisi吋n.
Si alcanzan o no el final de la pel胤cula[n]depende completamente de todos ustedes.

[msg MSG_021 [Akechi]]
S胤, y para lograrlo, necesitamos[n]asegurarnos de que este plan tenga[n]姻xito.

[msg MSG_022]
Parece que las cosas van bien por aqu胤.[n]Deber胤a volver por ahora...

[msg MSG_023]
Parece que las cosas van bien por aqu胤.[n]Tal vez deber胤a ver a los dem茨s...

[sel SEL_024 top]
y Yusuke
Ann y Ryuji
Morgana y Futaba

