[msg MSG_000]
夷Esta es... la Habitaci吋n de Terciopelo?

[msg MSG_001 [Yusuke]]
Qu姻 curiosa habitaci吋n azul... Tiene un[n]cierto aire acogedor.

[msg MSG_003 [Akechi]]
夷Podr胤a atribuirse tambi姻n la apariencia[n]de esta habitaci吋n a la anomal胤a?

[msg MSG_004 [Ann]]
Oye, [f 6 1 30 0 0 0], pres姻ntanoslas.

[msg MSG_005 [Justine]]
S胤, y cu姻ntanos algo sobre este cine en[n]el que estamos atrapadas.

[msg MSG_006]
Deber胤a decirles lo que s姻 hasta[n]ahora...

[msg MSG_008 [Caroline]]
Ya veo... No nos est茨s mintiendo,[n]夷verdad?

[msg MSG_009 [Ryuji]]
Bien, ahora entendemos lo de la[n]Habitaci吋n Terciopelo, y esas gemelas...

[msg MSG_010 [Justine]]
Recluso, 夷nos est茨s diciendo que no hay[n]forma de salir de aqu胤?

[sel SEL_011 top]
As胤 es.
Desafortunadamente...

[msg MSG_012 [Justine]]
Y pensar que nos har胤an prisioneras...

[msg MSG_013 [Caroline]]
Justine, no tiene sentido que nos[n]obsesionemos con esto. Ve茨moslo como[n]parte de su rehabilitaci吋n.

[msg MSG_014 [Justine]]
De hecho, ser胤a mejor aceptar la[n]situaci吋n por ahora.
Afortunadamente, esta es una Habitaci吋n[n]Terciopelo...

[msg MSG_015 [Justine]]
Gracias. Recluso: asumiremos la tarea de[n]fusionar a Personas aqu胤.

[sel SEL_016 top]
Eso ser胤a genial.
斡Wow! 夷Pueden hacerlo?

[msg MSG_017 [Caroline]]
Ser茨 mejor que est姻s agradecido.

[msg MSG_018 [Justine]]
Qu姻 tonter胤a...

[msg MSG_019 [Caroline]]
斡Sigue con esa insolencia y te[n]ejecutaremos!

[msg MSG_020 [Justine]]
Aun as胤, tendr茨s que esperar un tiempo,[n]hasta que nuestros preparativos est姻n[n]listos.
Parece que necesitaremos algo de tiempo.

[msg MSG_021 [Caroline]]
Has sido capaz de manejar a innumerables[n]Personas, 夷no, recluso?

[msg MSG_022 [Justine]]
Nos referimos a esa habilidad del[n]"Comod胤n".
Sin embargo, ese poder parece haber sido[n]alterado aqu胤...

[sel SEL_023 top]
夷Qu姻 quieres decir?
Quieres decir que...

[msg MSG_024 [Caroline]]
En pocas palabras, no podr茨s cambiar a[n]"Arsene".

[msg MSG_025]
Parece que no puedo cambiar de[n]Persona...

[msg MSG_025_5 [Nagi]]
Est茨n a salvo…

[msg MSG_026 [Nagi]]
斡Oh! Recuerdo que esta habitaci吋n era la[n]sala de pruebas...

[msg MSG_027 [Caroline]]
夷Qui姻nes son?

[msg MSG_028 [Nagi]]
Por favor, disc雨lpennos. Hemos estado[n]demasiado preocupadas por ustedes...

[msg MSG_029 [Hikari]]
...夷Gemelas?

[msg MSG_030 [Justine]]
Nos informaron de ustedes dos antes. No[n]hay necesidad de molestarse con[n]nosotras.

[msg MSG_031 [Nagi]]
U-umm...

[msg MSG_032 [Ann]]
Mmm. Parece que vamos a tener que hacer[n]m茨s presentaciones y ponernos manos a la[n]obra…

[msg MSG_033 [Nagi]]
Ya veo... Est茨 pasando, todo tan r茨pido.
Si sirve de ayuda, utilicen esta[n]instalaci吋n como consideren necesario.

[msg MSG_034 [Hikari]]
夷Son... tus amigas tambi姻n?

[msg MSG_035 [Justine]]
La palabra "amiga" es totalmente[n]inadecuada para nosotras.

[msg MSG_036 [Caroline]]
Estamos a cargo de su rehabilitaci吋n.

[msg MSG_037 [Hikari]]
夷...?

[msg MSG_038 [Justine]]
Bueno, entonces, Recluso, sigue[n]dedic茨ndote a tu rehabilitaci吋n aqu胤.
Esta incapacidad para manifestar tu[n]habilidad de Comod胤n debe considerarse[n]una prueba.

[msg MSG_039 [Ann]]
As胤 que no puedes cambiar de Persona...[n]Es un problema, pero creo que tendremos[n]que lidiar con eso.

[sel SEL_040 top]
Estoy seguro de que nos las[n]arreglaremos.
Voy a confiar en todos ustedes.
Esto es preocupante...

[msg MSG_041 [Morgana]]
As胤 es, no hay necesidad de[n]preocuparse... 斡T雨 tambi姻n puedes contar[n]con todos nosotros!

[msg MSG_042 [Yusuke]]
As胤 es como deber胤a ser.

[msg MSG_043 [Ryuji]]
斡No te preocupes! 斡Lo arreglaremos de[n]alguna manera!

[msg MSG_044 [Caroline]]
夷Mmm? Espera, Recluso, 夷qu姻 tienes ah胤?

[msg MSG_045 [Justine]]
Entrega ese objeto brillante dentro de[n]tu bolsillo.

[msg MSG_046 [Yusuke]]
夷Objeto brillante? 夷Tal vez se refieren[n]a ese pedazo de pel胤cula que[n]encontraste?

[msg MSG_047]
Entrego la pel胤cula brillante...

[msg MSG_048 [Justine]]
Esto...

[msg MSG_049 [Ann]]
Acabamos de encontrarla. 夷Saben que es?

[msg MSG_050 [Caroline]]
Esta pel胤cula brillante tiene infinitas[n]posibilidades dentro...

[msg MSG_051 [Justine]]
Esas infinitas posibilidades existen[n]dentro del coraz吋n, en otras palabras,[n]Personas.
Con esto, deber胤as poder tomar una[n]Persona adicional adem茨s de Arsene...

[msg MSG_052 [Futaba]]
夷En serio, una segunda Persona? 夷Eso[n]significa doblar el poder de fuego? 斡Eso[n]es tan OP!

[msg MSG_053 [Justine]]
No, el segundo Persona que se puede[n]tomar no tendr茨 la misma fuerza que la[n]original.
Si Arsene es la Persona principal, las[n]dem茨s son consideradas Personas[n]Secundarias...
Pi姻nsalo simplemente como una ayuda para[n]la original.

[msg MSG_054 [Akechi]]
Aun as胤, 夷dos al mismo tiempo? Bastante[n]impresionante, [f 6 1 30 0 0 0].

[msg MSG_055 [Justine]]
Recluso, mira esto.

[msg MSG_056]
Observo la pel胤cula brillar...

[msg MSG_056_05]
斡Una "Pixie" surgi吋 de la pel胤cula!

[msg MSG_057]
La pel胤cula brillante se transform吋 y[n]obtuve la Persona "Pixie".

[msg MSG_057_05 [Ryuji]]
No lo entiendo, 斡pero maldici吋n! 斡Eso[n]del Comod胤n es incre胤ble!
Tienes suerte. Desear胤a poder usar dos[n]Personas tambi姻n.

[msg MSG_058 [Justine]]
...Caroline.

[msg MSG_059 [Caroline]]
S胤... As胤 que parece, Justine.

[msg MSG_060 [Ryuji]]
夷Qu姻 pasa?

[msg MSG_061 [Caroline]]
El resto de ustedes tambi姻n son capaces[n]de tomar una segunda Persona.

[msg MSG_062 [Ryuji]]
斡夷En serio?! 斡夷No solo [f 6 1 30 0 0 0]?!

[msg MSG_063 [Justine]]
Obviamente, ese ser胤a el caso en un[n]escenario normal...
Pero aqu胤, pueden pedir prestada y[n]utilizar las Personas que toman forma en[n]el coraz吋n del Recluso.
夷Por qu姻?... 夷Podr胤a ser porque el poder[n]del Comod胤n cambi吋?

[sel SEL_064 top]
夷T雨 tampoco lo sabes?
夷C吋mo podr胤a cambiar?

[msg MSG_065 [Caroline]]
斡Cuida tus palabras, Recluso!
Todo lo que debes hacer es usar ese[n]poder… 斡SIN PREGUNTAR!

[msg MSG_066 [Justine]]
S胤, eso es correcto.
Sin embargo, esta sensaci吋n que tengo...[n]Es como si otro con el poder del Comod胤n[n]estuviera aqu胤.

[msg MSG_067 [Justine]]
Sin embargo, esta sensaci吋n que tengo...[n]Es como si otro con el poder del Comod胤n[n]estuviera aqu胤.

[msg MSG_068 [Caroline]]
斡Escucha! 斡No necesitas saber qu姻 est茨[n]pasando!
Todo lo que necesitas hacer es hacer uso[n]de ese poder, 斡y mantener la boca[n]cerrada!

[msg MSG_069 [Yusuke]]
As胤 que lo que est茨s diciendo es que[n]ahora podemos llamar a otra Persona[n]adem茨s de la habitual.

[msg MSG_070 [Futaba]]
Oh, 斡Estoy tan emocionada!

[msg MSG_071 [Ann]]
Principal y Secundaria, eh... 夷Ser姻[n]capaz de manejarme usando ambas?

[msg MSG_072 [Morgana]]
Bueno, tenemos a [f 6 1 30 0 0 0] para ayudar con[n]eso...
Al fin y al cabo, es nuestro[n]especialista en utilizar varias[n]personas.
En todo caso, esto ampliar茨 nuestras[n]estrategias, as胤 que habr茨 menos que[n]temer, 夷no?

[msg MSG_073 [Justine]]
Incluso en esta situaci吋n inusual,[n]sigues siendo un Recluso. No descuides[n]tu rehabilitaci吋n...

