[msg MSG_000 [Caroline]]
ムHola, Recluso!
Te ves bastante mal. メCポmo van las[n]cosas?

[sel SEL_001 top]
Todo bien hasta ahora.
No va muy bien.
...

[msg MSG_002 [Justine]]
Oボr eso hace que todos nuestros[n]preparativos valgan la pena...

[msg MSG_003 [Caroline]]
Hmph. Tenemos buenas noticias: estamos[n]listas para realizar fusiones.
ムAhora, ven a la Habitaciポn Terciopelo!

[msg MSG_004 [Caroline]]
ムメQu〒?! En serio, eres un desastre.

[msg MSG_005 [Justine]]
Tenemos buenas noticias: nuestros[n]preparativos para las fusiones estホn[n]completos.
Vamos a la Habitaciポn Terciopelo.

[msg MSG_006 [Caroline]]
ムNo tienes derecho a permanecer en[n]silencio! ムResponde la pregunta!

[msg MSG_007 [Justine]]
O, メquizホs estホs en tan mal que te[n]sientes incapaz de darnos una respuesta?
Tenemos buenas noticias: nuestros[n]preparativos para las fusiones estホn[n]completos.

[msg MSG_008 [Caroline]]
ムAhora, ven a la Habitaciポn Terciopelo!

[msg MSG_009 [Ryuji]]
Y se van.

[msg MSG_010 [Ann]]
Bueno, supongo que deberボamos[n]seguirlas...

