[msg MSG_003 [Cr胤ptico Objeto Negro]]
...

[msg MSG_004 [Futaba]]
夷Qu姻―Whoooaaah! 斡夷Qu姻 es eso?!

[msg MSG_005 [Akechi]]
斡夷Es una Sombra?!

[msg MSG_006 [Cr胤ptico Objeto Negro]]
...

[msg MSG_007 [Ann]]
Es sospechoso, pero... 夷No parece ser un[n]enemigo? 斡夷Qu姻 es esta cosa?!

[sel SEL_008 top]
Lo tocar姻.
Intentemos hablar con 姻l.

[msg MSG_009 [Morgana]]
Espero que no te ataque... Ten cuidado,[n][f 6 1 30 0 0 0].

[msg MSG_010]
夷...?
Se siente muy raro...

[msg MSG_011 [Futaba]]
夷Est茨s bien? 夷No te paso nada? 夷Solo[n]hace "boing-boing" cuando lo tocas?
Bien... Alguien tiene que intentar[n]hablar con 姻l.

[msg MSG_012 [Ann]]
夷H-holaaa? 夷Puedes o胤rme?

[msg MSG_013 [Cr胤ptico Objeto Negro]]
...

[msg MSG_014 [Futaba]]
No responde. Es solo un objeto aburrido.

[msg MSG_015 [Morgana]]
Bueno, en ese caso... 夷D吋nde est茨n sus[n]o胤dos?

[msg MSG_016 [Ann]]
Si hablamos alto, 夷no escuchar茨 lo que[n]estamos diciendo?

[msg MSG_016_5 [Ann]]
夷H-holaaa? 夷Puedes o胤rme?

[msg MSG_017 [Cr胤ptico Objeto Negro]]
...

[msg MSG_018 [Futaba]]
No reacciona... 夷Quiz茨 no puede o胤rnos?
Solo queda intentar tocarlo... 斡Ryuji!

[msg MSG_019 [Ryuji]]
斡夷Por qu姻 yo?!
Ugh, bien... 夷Est茨n seguros?

[msg MSG_020 [Ryuji]]
斡Whoa! 斡Es superesponjoso!

[msg MSG_021 [Akechi]]
Bien, hemos aprendido que es el茨stico,[n]pero parece que no habla.

[msg MSG_022 [Yusuke]]
No habla, ni se mueve, ni reacciona a[n]nosotros en absoluto...
夷Quiz茨s esto sea alg雨n tipo de mu隠eco?

[msg MSG_023 [Futaba]]
E-espera... Es solo un mu隠eco, 夷eh? Pero[n]es demasiado grande. Al menos deber胤a[n]ser escala 1:7.

[msg MSG_024 [Morgana]]
Bueno, ellas no est茨n aqu胤, as胤 que[n]sigamos buscando.

