[msg MSG_000]
La mano de Ryuji atraves吋 la pantalla...

[msg MSG_001 [Ryuji]]
斡夷M-mi mano?!
斡Mi mano entr吋 EN la pantalla!
Esto acaba de pasar... 斡夷Verdad?!

[msg MSG_002 [Akechi]]
Es absolutamente incre胤ble...

[msg MSG_003 [Ann]]
Espera un segundo. Si Makoto y Haru[n]estaban con nosotros dentro de la[n]pel胤cula...
夷Eso significa que las dejamos atr茨s en[n]la ciudad al otro lado de la pantalla?

[msg MSG_004 [Nagi]]
Me temo que ese parece ser el caso...

[msg MSG_005 [Yusuke]]
B茨sicamente, si quisi姻ramos rescatarlas,[n]nuestra 雨nica opci吋n es volver dentro de[n]la pel胤cula.

[msg MSG_006 [Ryuji]]
斡Tenemos que ir a salvarlas!, 夷no[n][f 6 1 30 0 0 0]?

[sel SEL_007 top]
Claro que s胤.
Vamos, r茨pido.

[msg MSG_008 [Morgana]]
Muy bien, entonces vamos a... Espera,[n]夷se supone que debemos... saltar?

[msg MSG_009 [Hikari]]
Oh... Nagi...

[msg MSG_010 [Nagi]]
夷Qu姻 pasa?

[msg MSG_011]
Ella est茨 susurr茨ndole a Nagi otra[n]vez...

[msg MSG_012 [Nagi]]
Hikari est茨 muy preocupada por su[n]seguridad.
Ya que es peligroso dentro de la[n]pel胤cula, ella cree que puede ser m茨s[n]seguro que se queden aqu胤.

[msg MSG_013 [Ryuji]]
Gracias por la advertencia, pero ese[n]peligro solo nos hace preocuparnos m茨s[n]por ellas.

[msg MSG_014 [Ann]]
斡S胤! 斡Tenemos que entrar all胤 lo antes[n]posible por nuestras amigas!

[msg MSG_015 [Hikari]]
夷Eh?

[msg MSG_016 [Hikari]]
夷Por sus amigas?
...
Pero, los amigos son...

[msg MSG_017 [Futaba]]
...夷Hikari?

[msg MSG_018 [Ryuji]]
斡Est茨 bien! 斡Todo el mundo, prep茨rense![n]3, 2, 1...

[msg MSG_019 [Hikari]]
斡E-espera!

[msg MSG_020 [Ryuji]]
斡Whoa! 斡夷Qu姻 pasa ahora?!

[msg MSG_021 [Hikari]]
...

[msg MSG_022 [Ryuji]]
Uhh...

[msg MSG_023 [Hikari]]
Em... por favor, un segundo...

[msg MSG_024]
Hikari est茨 pregunt茨ndole a Nagi sobre[n]algo...

[msg MSG_025 [Hikari]]
...夷Est茨 bien?

[msg MSG_026 [Nagi]]
S胤, entiendo...

[msg MSG_027 [Nagi]]
Hikari sigue preocupada por ustedes...
As胤 que me pidi吋 que les prestara mi[n]ayuda.

[msg MSG_028 [Yusuke]]
夷Tienes algo en mente?

[msg MSG_029 [Nagi]]
Efectivamente, hay algo que puedo[n]ofrecerles. 夷S胤ganme, por favor?

[msg MSG_030]
Nagi se dirige hacia el puesto de[n]comida...

[msg MSG_031 [Morgana]]
Si nos va a ayudar, veamos de que se[n]trata antes de volver a la pel胤cula.

