[msg MSG_000 [Yusuke]]
Parece que podemos usar nuestras[n]Personas aquボ despu〒s de todo.

[msg MSG_001 [Ryuji]]
Sボ, pero algo todavボa se siente raro...[n]Es como si no fuera tan fuerte o tan[n]rホpido como antes.

[msg MSG_002 [Akechi]]
Bueno, ahora estamos en un mundo[n]diferente, tal vez tengamos que empezar[n]de cero.

[msg MSG_003 [Ann]]
Por cierto, メqu〒 debemos hacer con esto?[n]Parecen fragmentos de esas sombras...

[msg MSG_004 [Yusuke]]
No tengo la menor idea de su valor. Si[n]pudi〒ramos utilizarlos de alguna[n]manera...

[msg MSG_005 [Futaba]]
Uh, Nagi dice que los comprarホ en el[n]puesto de comida cuando regresen.

[msg MSG_006 [Ann]]
メEn serio? ムEntonces podremos comprar[n]todo tipo de cosas en el puesto![n]ムAcabemos con las sombras!

[msg MSG_007]
Quizホs deberボa vender estos fragmentos[n]la prポxima vez que pase por el puesto de[n]comida...

