[msg MSG_000]
Todos se reunieron en el vestボbulo despu〒s de terminar sus preparativos...

[msg MSG_001 [Morgana]]
メEstホn todos listos?

[msg MSG_002 [Ryuji]]
ムSボ, completamente!

[msg MSG_003 [P3 Fem Protag]]
ムTodo listo de nuestro lado, tambi〒n!

[msg MSG_004 [Morgana]]
, メY tus preparativos?
Una vez que salgamos, no podremos regresar aquボ por un tiempo. Si necesitas ocuparte de algo, este es el momento.

[sel SEL_005 top]
Necesito tiempo para prepararme.
Empecemos la misiポn.

[msg MSG_006 [Morgana]]
Sボ, es mejor estar completamente preparado. ムMホs vale prevenir que lamentar!

[msg MSG_007 [Akechi]]
Cuando estemos listos, vayamos a la plaza de Kamoshida.

[msg MSG_008 [P3 Fem Protag]]
Esta misiポn tiene que tener 〒xito, ムsin importar qu〒!

[msg MSG_009 [Morgana]]
ムSボ, hora de robar la estatua de Kamoshidaman y rescatar a nuestras compaワeras!

[msg MSG_010 [Akechi]]
Bueno, comencemos dirigi〒ndonos a la Plaza Kamoshida.

[msg MSG_011 [P3 Fem Protag]]
ムEsta misiポn tiene que ser un 〒xito, pase lo que pase! ムVamos!

