[msg MSG_000 [Makoto]]
夷Est茨s bien, Noir?

[msg MSG_001 [Haru]]
Mmm... 夷Y t雨, Queen?

[msg MSG_002 [Makoto]]
Estoy sobrellev茨ndolo...

[msg MSG_003 [Haru]]
夷D吋nde estamos? 夷Esto es Mementos? O,[n]夷Un Palacio?

[msg MSG_004 [Makoto]]
No estoy segura... Nuestra informaci吋n[n]es muy limitada, tanto sobre[n]Kamoshidaman como de este lugar.
La pr吋xima vez que aparezca, necesito[n]intentar obtener informaci吋n.

[msg MSG_005 [Kamoshidaman]]
斡JA JA JA JA!
夷De qu姻 est茨n hablando? 夷Han decidido[n]confesar sus delitos?

[msg MSG_006 [Makoto]]
Hablando del diablo... Voy a preguntar[n]una vez m茨s: 夷d吋nde estamos? 夷Qui姻n[n]eres?

[msg MSG_007 [Kamoshidaman]]
夷Todav胤a est茨s atontada por tu peque隠a[n]siesta? 斡No me hagas decir lo obvio!
Esta es mi ciudad, Ciudad Kamo, y yo soy[n]el h姻roe de la justicia absoluta:[n]斡Kamoshidaman!

[msg MSG_008 [Makoto]]
夷Kamoshidaman? 夷No es Suguru Kamoshida,[n]antiguo profesor del Instituto Shujin?

[msg MSG_009 [Kamoshidaman]]
夷Instituto Shujin? 夷Ex profesor? 夷De qu姻[n]est茨s hablando?

[msg MSG_010 [Haru]]
Considerabas la escuela tu propio[n]castillo y hac胤as lo que quer胤as...

[msg MSG_011 [Kamoshidaman]]
夷Un castillo? Miren a estas dos,[n]diciendo a雨n m茨s tonter胤as. 斡Ya he[n]tenido suficiente de este disparate!

[msg MSG_012 [Makoto]]
Justo como pensaba, parece Kamoshida,[n]pero es alguien completamente[n]diferente...

[msg MSG_013 [Kamoshidaman]]
Tengo noticias para ustedes: los[n]detalles de su castigo han sido[n]decididos.
Ser茨n ejecutadas como enemigas de la[n]ciudad y miserables oponentes de mi[n]persona.

[msg MSG_014 [Haru]]
夷E-ejecutadas?

[msg MSG_015 [Kamoshidaman]]
As胤 es. El juicio debe ser aplicado[n]sobre el mal...
斡Y ser茨 realizado por mi mano, la mano[n]absolutamente justa de Kamoshidaman!

[msg MSG_016 [Makoto]]
No acepto esto. 斡No hemos hecho nada[n]malo!

[msg MSG_017 [Kamoshidaman]]
ィどだ どだ どだ! ぬぺゅわぺぽよ よ ゃゎれろよデ れよを をよ りゎもまょ ろよゆぺ[n]ゅぺ ぽまぼもれもカょテ つれぺ まれ ゆも るまれらよょれぺほもゅもぽぺぽ ぼよゆよ まゅ[n]ゅウぽまる ぽま ぢもゎぽぺぽ なぺゆよテ
Si no gu胤o a los ciudadanos, esta ciudad[n]se hundir茨 en el caos.
夷No las escuchas... las voces de la[n]gente anhelando la paz?

[msg MSG_018 [Mujer Curiosa]]
夷Esas dos... son las malvadas que[n]amenazan Ciudad Kamo?

[msg MSG_019 [Hombre Descarado]]
斡Eso es lo que dijo Kamoshidaman, as胤[n]que tiene que ser verdad!

[msg MSG_020 [Mujer Cansada]]
S胤... Todo lo que tenemos que hacer es[n]escuchar a Kamoshidaman.

[msg MSG_021 [Hombre Agitado]]
斡Cualquiera que desaf胤e a Kamoshidaman[n]es malvado!

[msg MSG_022 [Kamoshidaman]]
斡JA JA JA! 夷Ahora lo entienden?
Lo 雨nico que estoy haciendo es cumplir[n]con mi deber como el poderoso gobernante[n]de estos d姻biles ciudadanos.

[msg MSG_023 [Makoto]]
La gente en esta ciudad est茨 siendo[n]controlada por ti, no creen en lo que[n]dices.

[msg MSG_024 [Kamoshidaman]]
斡Quien tiene el poder, decide las[n]reglas! 斡Desafiar mi poder es una[n]tonter胤a!

[msg MSG_024_5 [Kamoshidaman]]
斡Deber胤an sentirse honradas de ser[n]castigadas por m胤, el h姻roe de la[n]justicia absoluta! 斡JA JA JA!

[msg MSG_025 [Haru]]
Entonces eres quien decide lo que es[n]bueno y malo, solo porque tienes el[n]poder. 斡Eso no es correcto!

[msg MSG_026 [Makoto]]
斡No te dejaremos hacer lo que quieras[n]con nosotras! Estoy segura de que Joker[n]y los dem茨s...

[msg MSG_027 [Kamoshidaman]]
Ni siquiera una disculpa, 夷eh? Parece[n]que a雨n no est茨s arrepentida.

[msg MSG_028 [Kamoshidaman]]
Entonces, arrod胤llate y s雨plica ante[n]todos los ciudadanos y tal vez te[n]perdone.

[msg MSG_029 [Haru]]
斡Nunca har胤a tal cosa!

[msg MSG_030 [Kamoshidaman]]
Qu姻 tonto es desafiar a los fuertes, y[n]lo justo que es obedecer al[n]gobernante...
Ser茨s una excelente oportunidad para[n]recordarles a los ciudadanos estos[n]hechos.
Retrasemos la ejecuci吋n un poco m茨s.[n]斡Reflexiona sobre tus acciones hasta[n]entonces! 斡JA JA JA!

[msg MSG_031 [Kamoshidaman]]
Vigila bien a estas dos. 斡Est茨n[n]empe隠adas en destruir la paz de mi[n]ciudad!

[msg MSG_032 [Polic胤a Gordo]]
斡S胤, se隠or!

[msg MSG_033 [Makoto]]
Qu姻 lamentable justicia. No puedo creer[n]que todos simplemente le obedezcan...

[msg MSG_034 [Polic胤a Gordo]]
斡Cuidado! Kamoshidaman es a quien todos[n]aspiran a ser.
Incluso la persona que te captur吋 era un[n]colega nuestro que aspira a ser como[n]nuestro h姻roe.

[msg MSG_035 [Haru]]
Espera... 夷Te refieres a la cosa que nos[n]atac吋?

[msg MSG_036 [Makoto]]
Ahora que lo mencionas, ese disfraz...[n]Era como una versi吋n m茨s tosca del traje[n]de Kamoshidaman.

[msg MSG_037 [Polic胤a Gordo]]
Mmm. No importa cu茨nto resistas, nunca[n]le ganar茨s a Kamoshidaman.
斡Mientras todav胤a tengamos "eso" aqu胤,[n]Kamoshidaman es invencible!

[msg MSG_038 [Haru]]
...夷"Eso"?

[msg MSG_039 [Polic胤a Gordo]]
Pero nuevamente, Kamoshidaman te ha[n]juzgado como malvada, as胤 que no hay[n]escapatoria de tu castigo...

[msg MSG_039_5 [Polic胤a Gordo]]
No importa cu茨nto supliques, todo lo que[n]puedes hacer es sentarte y esperar la[n]muerte. 斡Ja, ja, ja!

[msg MSG_040 [Haru]]
Si es invencible mientras tenga "eso"...

[msg MSG_041 [Makoto]]
Entonces deber胤a ser cierto: puede ser[n]da隠ado una vez que "eso" desaparezca.[n]Pero, 夷qu姻 podr茨 ser?

