[msg MSG_000]
La sala de proyecciポn...

[msg MSG_001 [Ryuji]]
Nunca he estado en una sala de[n]proyecciポn. メEse proyector no es enorme?

[msg MSG_002 [Futaba]]
Oye, ムNo toques eso! Los dispositivos[n]complejos como los proyectores son[n]delicados.

[msg MSG_003 [Crボptico Objeto Negro]]
...

[msg MSG_004 [Futaba]]
メQu〒―Whoooaaah! ムメQu〒 es eso?!

[msg MSG_005 [Akechi]]
ムメEs una Sombra?!

[msg MSG_006 [Crボptico Objeto Negro]]
...

[msg MSG_007 [Ann]]
Es sospechoso, pero... メNo parece ser un[n]enemigo? ムメQu〒 es esta cosa?!

[sel SEL_008 top]
Lo tocar〒.
Intentemos hablar con 〒l.

[msg MSG_009 [Morgana]]
Espero que no te ataque... Ten cuidado,[n][f 6 1 30 0 0 0].

[msg MSG_010]
メ...?
Se siente muy raro...

[msg MSG_011 [Futaba]]
メEstホs bien? メNo te paso nada? メSolo[n]hace "boing-boing" cuando lo tocas?
Bien... Alguien tiene que intentar[n]hablar con 〒l.

[msg MSG_012 [Ann]]
メH-holaaa? メPuedes oボrme?

[msg MSG_013 [Crボptico Objeto Negro]]
...

[msg MSG_014 [Futaba]]
No responde. Es solo un objeto aburrido.

[msg MSG_015 [Morgana]]
Bueno, en ese caso... メDポnde estホn sus[n]oボdos?

[msg MSG_016 [Ann]]
Si hablamos alto, メno escucharホ lo que[n]estamos diciendo?

[msg MSG_016_5 [Ann]]
メH-holaaa? メPuedes oボrme?

[msg MSG_017 [Crボptico Objeto Negro]]
...

[msg MSG_018 [Futaba]]
No reacciona... メQuizホ no puede oボrnos?
Solo queda intentar tocarlo... ムRyuji!

[msg MSG_019 [Ryuji]]
ムメPor qu〒 yo?!
Ugh, bien... メEstホn seguros?

[msg MSG_020 [Ryuji]]
ムWhoa! ムEs superesponjoso!

[msg MSG_021 [Akechi]]
Bien, hemos aprendido que es elホstico,[n]pero parece que no habla.

[msg MSG_022 [Yusuke]]
No habla, ni se mueve, ni reacciona a[n]nosotros en absoluto...
メQuizホs es algマn tipo de muワeco?

[msg MSG_023 [Futaba]]
E-espera... Es solo un muワeco, メeh? Pero[n]es demasiado grande. Al menos deberボa[n]ser escala 1:7.

[msg MSG_024 [Morgana]]
Bueno, ellas no estホn aquボ, asボ que[n]sigamos buscando.

