[msg MSG_000 [Morgana]]
斡Finalmente, es el momento, chicos!
斡Si esa estatua es la debilidad de[n]Kamoshidaman, esto deber胤a interferir[n]con sus poderes!

[msg MSG_001 [Akechi]]
Bien, entonces, a nuestras posiciones.

[msg MSG_002 [Ryuji]]
斡Vamos, Panther!

[msg MSG_003 [Ann]]
斡C吋mo lo planeamos, Skull!

[msg MSG_003_5 [Ann]]
Solo aguanten, chicas... 斡Vamos por[n]ustedes!

[msg MSG_004 [P3 Fem Protag]]
Deja el panel de interruptores en mis[n]manos. Har姻 mi parte cuando sea el[n]momento.

[msg MSG_005 [Yusuke]]
Puedo preparar mi accesorio de[n]inmediato. Te avisar姻 cuando est姻 listo.

[msg MSG_006 [Morgana]]
Entonces, 斡todo lo que tenemos que hacer[n]es esperar el momento adecuado!

[msg MSG_007 [Portavoz]]
Ciudadanos de Ciudad Kamo, esto es un[n]anuncio p雨blico...
La exhibici吋n de castigo en la Plaza[n]Kamoshida est茨 a punto de comenzar.
Repito...

[msg MSG_008 [Hombre Emocionado]]
Parece que las personas que desafiaron a[n]Kamoshidaman finalmente ser茨n[n]castigadas.

[msg MSG_009 [Mujer Joven]]
Si Kamoshidaman dice que son malvadas,[n]斡entonces debe pasar!

[msg MSG_010 [Kamoshidaman]]
斡JA, JA, JA! Como todos saben, soy la[n]justicia absoluta de esta ciudad.

[msg MSG_011 [Hombre Fan茨tico]]
斡S胤!

[msg MSG_012 [Hombre De Mediana Edad]]
斡Si simplemente seguimos a Kamoshidaman,[n]nuestra ciudad estar茨 en paz!

[msg MSG_013 [Kamoshidaman]]
斡En efecto! 斡Solo a trav姻s de mi[n]existencia existe la paz en la ciudad!
Sin embargo, han aparecido violadores de[n]esa paz. 斡Cualquiera que se oponga a m胤[n]es malvado y un criminal!
斡Y castigar姻 este mal que perturba[n]nuestra paz con mi propia justicia!

[msg MSG_014 [Mujer Suplicante]]
斡Te lo suplicamos, prot姻genos de los[n]criminales, por nuestro bien!

[msg MSG_015 [Jovencito]]
Kamoshidaman es la justicia, 夷verdad? Es[n]lo que todos dicen...

[msg MSG_016 [Viejo]]
斡Creemos en ti, Kamoshidaman!

[msg MSG_017 [Ryuji]]
斡"Mi propia justicia"! 斡Vaya mierda[n]ego胤sta!

[msg MSG_018 [Ann]]
斡畏l puede hacer que suene tan bien como[n]quiera, pero lo 雨nico que est茨 haciendo[n]es reprimir a todos con su poder!

[msg MSG_019 [Yusuke]]
Mis disculpas por el retraso; la[n]configuraci吋n est茨 completa.

[msg MSG_020 [Ryuji]]
斡Estamos listos tambi姻n!

[msg MSG_021 [P3 Fem Protag]]
Estoy tan nerviosa que estoy sudando...
Espera, 夷o deber胤an ser balas? 斡De todos[n]modos, no tenemos otra opci吋n!

[msg MSG_022 [Futaba]]
Parece que todos est茨n en posici吋n...
Entonces, 斡iniciemos este atraco! Joker,[n]haz los honores.

[sel SEL_023 top]
斡Vamos!
斡Robemos esa estatua!

[msg MSG_024 [Morgana]]
斡Esta vez lo venceremos y rescataremos a[n]Queen y Noir!

