[msg MSG_000 [Ryuji]]
Bueno, ahora que desciframos ese extraワo misterio, vamos a buscar a Makoto y a Haru.

[msg MSG_001 [Yusuke]]
Antes de eso... Morgana, hay algo que me gustarボa preguntarte...
Despu〒s de entrar en la pelボcula, メpudiste vernos en la pantalla?

[msg MSG_002 [Morgana]]
Sボ, definitivamente estaban en la pantalla. Era como si fueran actores de la pelボcula.

[msg MSG_003 [Akechi]]
メOh? Eso es interesante. Me gustarボa verlo por mボ mismo.

[msg MSG_004 [Morgana]]
Pero, habボa algo raro...
A menos que progresaran en la pelボcula, se repetボa la misma escena en bucle.

[msg MSG_005 [Ann]]
メEh?

[msg MSG_006 [Futaba]]
Parecボa que la pelボcula se repetボa. Cuando avanzaban, la pelボcula continuaba.

[msg MSG_007 [Yusuke]]
Esencialmente, estamos desarrollando la trama como si fu〒ramos los actores dentro de ella.
Esta es una actividad creativa sin precedentes.

[msg MSG_008 [Ann]]
Oye, Morgana, メencontraste alguna pista aquボ en el cine?

[msg MSG_009 [Morgana]]
No... busqu〒 por todas partes, pero no hay ni rastro de Makoto y Haru aquボ.
Si vamos a buscarlas, serボa mejor hacerlo dentro de la pelボcula...
ムAsボ que, de ahora en adelante, voy a darlo todo!

[msg MSG_010 [Ann]]
Me tranquiliza oボr eso, pero... メDe verdad estホ bien dejar a Futaba aquボ sola?

[sel SEL_011 top]
Esa idea me preocupa.
Ella puede manejarlo.
No estoy convencido...

[msg MSG_012 [Futaba]]
ムメQ-qu〒?! メEs una confesiポn de confianza hacia mボ?

[msg MSG_013 [Futaba]]
メPor qu〒? ムメSolo porque soy devastadoramente tボmida con extraワos?!

[msg MSG_014 [Morgana]]
ムNo, para nada!
Espera... en realidad, es eso.

[msg MSG_015 [Morgana]]
Oye, [f 6 1 30 0 0 0]...

[msg MSG_016]
Morgana me susurra...

[msg MSG_017 [Morgana]]
...Cuando estaba vigilando a Hikari y Nagi, no hicieron nada sospechoso.
No creo que haya problemas en dejar a Futaba con ellas.

[msg MSG_018 [Futaba]]
No se preocupen por mボ... Me quedar〒 aquボ con nuestros nuevos amigos azules.
Ademホs, si ocurre algo malo, メno serボa malo que no hubiera nadie para informar?
Me centrar〒 en la navegaciポn y ser〒 su contacto de este lado. メAlguna objeciポn?

[msg MSG_019 [Yusuke]]
Tu ayuda serホ muy apreciada. Todos confiamos en ti.

[msg MSG_020 [Morgana]]
ムEstホ decidido!

[msg MSG_021 [Hikari]]
...メTマ tambi〒n vas Morgana?

[msg MSG_022 [Morgana]]
Claro que sボ. Tengo habilidades, メsabes?

[msg MSG_023 [Hikari]]
Puedes ser capaz de luchar... pero...

[msg MSG_024 [Morgana]]
ムJa, ja! Solo si〒ntate y mira.
メVerdad, [f 6 1 30 0 0 0]? ムHemos estado juntos en las buenas y en las malas!

[sel SEL_025 top]
No te preocupes por nosotros.
No dejaremos a nuestras amigas.

[msg MSG_026 [Hikari]]
...

[msg MSG_027 [Morgana]]
ムSボ, lo que dijo! ムMuy bien, vホmonos, chicos!

[msg MSG_028 [Futaba]]
Bueno, serホ mejor que decidas qui〒n lucharホ primero.
Si van todos juntos, serホn mホs vulnerables a los enemigos.

[msg MSG_029 [Morgana]]
Es cierto, tambi〒n hay que tener en cuenta la formaciポn del grupo, con posiciones Frontales y Traseras.
Los miembros de la lボnea Trasera reciben menos daワo que los de la lボnea Frontal.

[msg MSG_099]
/ルロ)が加入しeした！ ※仲間加入ＷＮＤ用画像くreHO仮。 TEMP

