[msg MSG_000 [Ryuji]]
Whoa... 斡夷Esto es real?! En serio[n]entramos en la pel胤cula...

[msg MSG_001 [Yusuke]]
夷C吋mo deber胤amos proceder? Ser胤a[n]prudente pasear sin rumbo...

[msg MSG_002 [Ann]]
夷Qu姻 es ese ruido?

[msg MSG_003 [Voz Con Cordones Estaticos]]
...ch... 斡Chicos!

[msg MSG_004 [Yusuke]]
夷Mm? 夷Es... Oracle?

[msg MSG_005 [Ann]]
斡Oracle! 夷Puedes o胤rnos?

[msg MSG_006 [Futaba]]
斡Ah! Me alegra escucharlos. 斡Parece que[n]est茨n bien!

[msg MSG_007 [Ann]]
Espera, 斡夷por qu姻 tienes puesto tu traje[n]ladr吋n fantasma tambi姻n?!

[msg MSG_007_1 [Futaba]]
Mm... Todo lo que s姻 es que mi ropa[n]cambi吋 cuando entraron en la pel胤cula.
夷C吋mo funciona toda esta locura?

[sel SEL_007_2 top]
Es solo el Metaverso.
No lo s姻.

[msg MSG_007_3 [Futaba]]
Bueno, no tiene sentido pensar en ello,[n]todav胤a hay mucho que no sabemos.
De todos modos, todo est茨 bien por aqu胤,[n]as胤 que los ayudar姻, 斡no hay problema!

[msg MSG_007_4 [Yusuke]]
En ese caso, lamento pedir algo tan[n]r茨pido, pero...
夷Podr胤as echar un vistazo a la pel胤cula[n]con tu Persona?

[msg MSG_008 [Futaba]]
No. Ya lo intent姻.
Puedo ver d吋nde est茨n, pero eso es[n]todo...
Tampoco puedo ver d吋nde est茨n Queen o[n]Noir. Lo siento...

[msg MSG_009 [Ryuji]]
Muy bien, tendremos que buscarlas.

[msg MSG_010 [Futaba]]
Aun as胤, parece que puedo ayudarlos en[n]batalla como siempre.
斡No se preocupen por eso!

[msg MSG_011 [Ann]]
斡Bien, y puedes contar con nosotros para[n]encontrar a esas dos!

[msg MSG_012 [Futaba]]
Muy bien, 斡aseg雨rate de dibujar tu mapa[n]mientras te mueves para que no[n]terminemos perdidos m茨s tarde!
夷Alg雨n problema con el cuaderno?

[msg MSG_013 [Yusuke]]
Todo parece estar en orden. 夷Empezamos?

