[msg MSG_000 [P3 Fem Protag]]
夷Esto es... un puesto de comida?

[msg MSG_001 [Elizabeth]]
Bienvenidos.
でま まれろぺぽよ まれらまるぺょぽよ れゎ ゅゅまむぺぽぺ ぼよょ ろぺょろよ[n]みまるわよる りゎま ゆもれ よゃよれ ぼよゆまょんぺるよょ ぺ れよほるまれぺゅもる ぽま[n]ゆも ぼるァょまよデ ぼよゆよ ゅよれ ぽま ょゎまれろるよ ゆぺまれろるよテ

[msg MSG_002 [Theodore]]
Sin embargo, no parecen estar[n]sobresaliendo m茨s de lo habitual...

[msg MSG_003 [Theodore]]
Hermana: por favor saluda a mi invitada[n]primero.

[msg MSG_004 [Elizabeth]]
Ah, grosero de mi parte.
Me llamo Elizabeth. Soy la hermana mayor[n]de Theodore.
Theo me ha dicho m茨s que elogios de ti,[n][f 6 1 27 0 0 0].

[msg MSG_005 [P3 Fem Protag]]
Es un placer conocerte tambi姻n. Me han[n]hablado mucho de ti.
Aun as胤, me sorprende saber que tienes[n]una hermana mayor, Theo.

[msg MSG_006 [Theodore]]
Mi hermana Elizabeth es un poco... no,[n]bastante ingenua en ciertos aspectos.
Sospecho que podr胤a causarte problemas,[n]pero espero que logres llevarte bien con[n]ella.

[msg MSG_007 [Elizabeth]]
Mi lema es hacer lo que me plazca, vaya[n]a donde vaya el viento.

[msg MSG_008 [P3 Fem Protag]]
夷Tambi姻n viniste aqu胤 con Theo,[n]Elizabeth?

[msg MSG_009 [P3 Fem Protag]]
斡Elizabeth!

[msg MSG_010 [Elizabeth]]
Oh, [f 6 1 27 0 0 0], me alegra ver que est茨s a[n]salvo.

[msg MSG_011 [P3 Fem Protag]]
Escuche la situaci吋n de los dem茨s,[n]pero... pensar que tambi姻n te trajeron[n]aqu胤...

[msg MSG_012 [Elizabeth]]
S胤, todo sucedi吋 en un abrir y cerrar de[n]ojos. Cuando llegu姻, Theo y yo est茨bamos[n]aqu胤...

[msg MSG_013 [Theodore]]
Nuestro maestro no estaba, pero[n]ciertamente est茨bamos dentro de la[n]Habitaci吋n Terciopelo.
A pesar de eso, de repente, se conect吋[n]con este cine e incluso cambi吋 su[n]forma...

[msg MSG_014 [Elizabeth]]
La Habitaci吋n Terciopelo es un lugar[n]inseparable de los destinos de nuestros[n]hu姻spedes.
Existe una regla estricta "nada sin[n]sentido sucede dentro".

[msg MSG_015 [P3 Fem Protag]]
En otras palabras, 夷hay una raz吋n por la[n]cual llegamos aqu胤?

[sel SEL_016 top]
夷Y ese significado es?
S茨canos de aqu胤.

[msg MSG_017 [Elizabeth]]
Esa respuesta tendr茨n que descubrirla[n]ustedes mismos.

[msg MSG_018 [Elizabeth]]
Fuimos tra胤dos aqu胤 de la misma manera[n]que ustedes... No hay nada que podamos[n]hacer al respecto tampoco.

[msg MSG_019 [Elizabeth]]
Sin embargo, no tenemos la intenci吋n de[n]simplemente sentarnos y observar.
Para ayudarlos a todos en su viaje, he[n]obligado a Theo a preparar una tienda[n]para ustedes.

[msg MSG_020 [Ryuji]]
斡Oh! No importa...

[msg MSG_021 [Elizabeth]]
Un momento, por favor. Hay algunos[n]toques finales que deben hacerse[n]primero...

[msg MSG_022 [Theodore]]
夷Hermana? Creo que los preparativos[n]est茨n completos...

[msg MSG_023 [Elizabeth]]
Todo esto es un tanto insulso para la[n]gran inauguraci吋n de una tienda.
Un ritual de inauguraci吋n adecuado[n]deber胤a ser emocionante, con estallidos[n]y explosiones.

[msg MSG_024 [Theodore]]
Ah...
斡Y-ya lo sab胤a!
斡Debemos animar nuestros esp胤ritus con[n]estruendos y comenzar el comercio con[n]explosiones!

[msg MSG_025 [Elizabeth]]
S胤, y para eso, debemos a隠adir el toque[n]final... Theo, ven conmigo un momento.

[msg MSG_026]
Elizabeth arrastr吋 a Theodore tom茨ndolo[n]de la mano...

[msg MSG_027 [P3 Fem Protag]]
Elizabeth estaba tan emocionada que no[n]pude decir ni una palabra... Espero que[n]Theo est姻 bien.

[msg MSG_028 [Ann]]
Oh, parece que han vuelto.

[msg MSG_029 [Theodore]]
Nos disculpamos por el retraso...

[msg MSG_030 [P3 Fem Protag]]
斡夷Th-Theo?!

[msg MSG_031 [Theodore]]
Hermana... 夷Este atuendo es realmente[n]necesario para una gran apertura?

[msg MSG_032 [Elizabeth]]
Theo, 夷puedes sentirlo? La curiosa[n]euforia que se mezcla con tu profunda y[n]rica vergüenza.

[msg MSG_032_5 [Elizabeth]]
斡Ese sentimiento es crucial para el gran[n]ritual de apertura! 斡Este traje es para[n]expresar tu hospitalidad!

[msg MSG_033 [Theodore]]
Eh, ahora que lo mencionas, siento como[n]si mi coraz吋n estuviera elev茨ndose...
...斡Oh, cielos! 斡Incluso mi brazo me[n]invita a los cielos!

[msg MSG_034 [Elizabeth]]
No debes olvidar ponerte este atuendo al[n]proporcionar servicios a nuestros[n]invitados, 夷entendido?

[msg MSG_035 [Ann]]
...夷Deber胤a decirles qu姻 se equivocan?

[msg MSG_036 [Ryuji]]
Olv胤dalo. Si empiezas ahora, no[n]terminar茨n nunca.

[msg MSG_037 [Futaba]]
Una despistada y su hermano explotado...[n]Este sketch c吋mico necesita urgentemente[n]a alguien serio.

[msg MSG_038 [Theodore]]
Bien, entonces: actuar姻 como su vendedor[n]aqu胤 en este puesto de comida.
A隠adir姻 nuevos productos con el tiempo.

[msg MSG_039 [Yusuke]]
夷Nuevos productos? 夷C吋mo recibir茨s[n]env胤os en nuestra situaci吋n?

[msg MSG_040 [Theodore]]
Procesar姻 los materiales que obtengan[n]dentro de la pel胤cula para crear nuevos[n]productos...
斡Y lo har姻 usando esta m茨quina de[n]palomitas!

[msg MSG_041 [Ann]]
Eh, 斡夷qu姻?!

[msg MSG_042 [Theodore]]
Perm胤tanme mostrarles, para esta[n]ocasi吋n, ya he preparado los materiales[n]necesarios.
Simplemente, los colocar姻 en la m茨quina[n]de palomitas y luego encender姻 el[n]interruptor.

[msg MSG_043 [Theodore]]
Ah胤 lo tienen: un arma completamente[n]nueva. 夷Ven? 夷No fue f茨cil?

[msg MSG_044 [Ryuji]]
Pero, 斡夷c吋mo?! 斡Ni siquiera s姻 por d吋nde[n]empezar a preguntar!

[msg MSG_045 [Haru]]
Probablemente, sea lo 雨ltimo que deber胤a[n]salir de una m茨quina de palomitas...

[msg MSG_046 [Theodore]]
Las palomitas se hacen calentando los[n]granos de ma胤z y haciendo que su[n]contenido interno se expanda...
En otras palabras, es la manifestaci吋n[n]de la posibilidad oculta del ma胤z.
As胤, esta milagrosa metamorfosis solo es[n]posible a trav姻s de una m茨quina de[n]palomitas de ma胤z.

[msg MSG_047 [Ann]]
斡De alguna manera lo hizo funcionar!

[msg MSG_048 [Makoto]]
Muy bien, dej姻moslo as胤...

[msg MSG_049 [Theodore]]
Si falta alg雨n material, lo notificar姻.
Sin embargo, tambi姻n les avisar姻 de lo[n]que te falta basado en los materiales[n]que consigan.
Espero que lo entiendan.

[msg MSG_050 [Akechi]]
As胤 que si queremos saber que[n]necesitamos, necesitamos tener al menos[n]uno de los materiales...

[msg MSG_051 [Yusuke]]
Mencionaste que los est茨s vendiendo,[n]夷verdad? A pesar de afirmar que nos[n]est茨s ayudando...

[msg MSG_052 [Elizabeth]]
Todo tiene un precio: as胤 es como[n]funciona el mundo, y es algo que no[n]puedo cambiar.
Por favor, recu姻rdenlo.

[msg MSG_053 [Theodore]]
He asumido las responsabilidades de la[n]Srta. Nagi, as胤 que por favor, contin雨en[n]siendo clientes de este puesto.
Si vendieron materiales aqu胤 antes,[n]crear姻 nuevos productos a partir de[n]ellos.

[msg MSG_054 [Ryuji]]
Ahora tenemos una tienda y algunos[n]compa隠eros m茨s. Parece que es hora de[n]ponernos manos a la obra.

[msg MSG_055 [Morgana]]
Una vez nos preparemos, volvamos a[n]entrar a la pel胤cula...
Estoy preocupado por Makoto y Haru.

