[msg MSG_000 [Ann]]
メEh? ムメNiワas?! メEstホn perdidas?

[msg MSG_001 [Akechi]]
No estoy tan seguro, parecen mホs que[n]simplemente niワas perdidas.

[msg MSG_002 [Caroline]]
メQu〒...?

[msg MSG_003 [Justine]]
メDポnde estホ nuestro maestro?

[msg MSG_004 [Caroline]]
ムJustine! ムMira!

[msg MSG_005 [Justine]]
Tマ tambi〒n estホs aquボ, Recluso.

[msg MSG_006 [Caroline]]
Oye, recluso, ムメdポnde estamos?! ムメQu〒[n]haces aquボ?!

[sel SEL_007 top]
Ni idea.
Esa es mi lボnea.
Adivina.

[msg MSG_008 [Caroline]]
Esa expresiポn en tu cara... Parece no[n]tienes ni idea.

[msg MSG_009 [Caroline]]
ムメCポmo te atreves?!

[msg MSG_010 [Justine]]
Espera, Caroline.
Esa expresiポn en su cara... Parece no[n]tiene ni idea.

[msg MSG_011 [Caroline]]
ムメQu〒 crees que estホs haciendo?!

[msg MSG_012 [Justine]]
Espera, Caroline. Dudo que el recluso[n]sea capaz de algo asボ.
Probablemente, no tenga ni idea de lo[n]que estホ pasando.

[msg MSG_013 [Caroline]]
Entonces... メQu〒 estホ pasando aquボ?

[msg MSG_014 [Justine]]
No lo s〒.

[msg MSG_015 [Futaba]]
Ooooh, ムSon tan pequeeeワas! メY son[n]GEMELAS?

[msg MSG_016 [Ryuji]]
, メConoces a estas Rugrats?

[msg MSG_017 [Caroline]]
ムメRugrats?!

[msg MSG_018 [Justine]]
Esa basura...

[msg MSG_019 [Morgana]]
ムSボ! ムDeja de ser tan grosero y[n]muestrales respeto!

[sel SEL_020 top]
メLas conoces tambi〒n?
Hablando de traiciポn...

[msg MSG_021 [Morgana]]
No, no es eso, pero... メM-me siento[n]bien?

[msg MSG_022 [Justine]]
En cualquier caso, cu〒ntanos tu[n]situaciポn aquボ, recluso.

[msg MSG_023 [Caroline]]
Vamos a escuchar lo que tienes que decir[n]en esa habitaciポn… ムEh, tマ! ムGato!

[msg MSG_024 [Morgana]]
ムメS-sボ?!

[msg MSG_025 [Caroline]]
Escolta al prisionero a la habitaciポn,[n]ムy hazlo rホpido!

[msg MSG_026 [Morgana]]
メP-por qu〒 yo?

[msg MSG_027 [Justine]]
...

[msg MSG_028 [Morgana]]
L-lo har〒... ムClaro! ムCon mucho gusto!

[msg MSG_029 [Caroline]]
Hmph, no te olvides del resto de esa[n]gente tambi〒n.

[msg MSG_030 [Akechi]]
Supongo que somos "el resto de esa[n]gente"...

[msg MSG_031 [Ryuji]]
En serio, メqui〒nes son?
Y Morgana, メpor qu〒 obedeces sus[n]ポrdenes?

[sel SEL_032 top]
Apuesto a que se ha enamorado.
Es como su gato mascota.

[msg MSG_033 [Ryuji]]
メDe verdad? メDe qui〒n?

[msg MSG_034 [Morgana]]
ムNo seas ridボculo! ムMi amor es solo para[n]la Seワorita Ann!

[msg MSG_035 [Morgana]]
ムTe dije que no soy un gato!
*jadeo* メYa estホs contento? Estoy[n]empezando a cansarme de ese par…

[msg MSG_036 [Ryuji]]
ムPero eso es, como, tu marca ahora!

[msg MSG_037 [Morgana]]
...Esas dos tienen algo "especial"[n]dentro de ellas.
Cuando me miran con esos ojos, siento[n]que tengo que escucharlas.

[sel SEL_038 top]
メComo una especie de hipnosis?
メTe estホs perdiendo?

[msg MSG_039 [Morgana]]
No, nada de eso. Es mホs como si hubiera[n]algo en mボ...
Algo que grita "ムTengo que hacer lo que[n]dicen!"…

[msg MSG_040 [Ryuji]]
No me gusta nada de esto...

[msg MSG_041 [Morgana]]
Bueno, ムlo hice sin pensar! Y, no tengo[n]ni idea de por qu〒...

[msg MSG_042 [Yusuke]]
Si son conocidas de [f 6 1 30 0 0 0], creo que[n]podemos confiar en ellas.

[msg MSG_043 [Morgana]]
Estar〒 bien. Vamos, no podemos hacerlas[n]esperar.

