[msg MSG_000]
El puesto de comida...
Ann y Ryuji le estホn explicando el plan a Theodore...

[msg MSG_001 [Ann]]
...Y por eso necesitamos tantos. メPodrボas prepararlos para nosotros?

[msg MSG_002 [Theodore]]
Oh, este es realmente un gran pedido...
Pero tambi〒n es un plan muy emocionante. Los preparar〒 para de inmediato.

[msg MSG_003 [Ryuji]]
ムGracias, Theodore!
...Oh, no te habボa visto [f 6 1 30 0 0 0]. メViniste a ver cポmo vamos?

[msg MSG_004 [Ann]]
*risita* Parece que nuestra parte va a funcionar. Aunque es un pedido bastante grande.

[msg MSG_005 [Theodore]]
Por favor, no te preocupes, llenar〒 este pedido inmediatamente.

[msg MSG_006 [Ryuji]]
Tenemos que sorprender a este falso h〒roe, ムasボ que mejor que esto se vea bien!

[msg MSG_007 [Ann]]
ムExacto! Quiero decir, s〒 que es otra persona, pero aマn tiene la cara de ese bastardo... Eso solo me enoja mホs.

[msg MSG_008 [Ryuji]]
Eh... Entonces, メcポmo habrボas reaccionado si Kamoshidaman fuera superatractivo?

[sel SEL_009 top]
El mal es malo, sin importar cuホn atractivo sea.
Entonces le darボa un respiro...
Lo odiarボa aマn mホs.

[msg MSG_010 [Ryuji]]
Sボ, estoy de acuerdo. No importa qu〒 cara tenga, lo que estホ haciendo es imperdonable.

[msg MSG_011 [Ann]]
Ha tratado tan mal a Makoto y Haru... No vamos a dejar que se salga con la suya con lo que ha hecho.

[msg MSG_012 [Ryuji]]
ムメEn serio?!

[msg MSG_013 [Ann]]
Bueno, si odio a Kamoshida un 100%, puede que baje a un 99%...
Pero ha tratado tan mal a Makoto y Haru... ムDefinitivamente es imperdonable!

[msg MSG_014 [Ryuji]]
B-bien... Aunque no te estaba preguntando a ti...

[msg MSG_015 [Ann]]
Ha tratado tan mal a Makoto y Haru... ムDefinitivamente es imperdonable!

[msg MSG_016 [Ryuji]]
De todos modos, parece que hemos asegurado las cosas de nuestro lado...
Si aマn no has revisado a los demホs, ve y hazlo.

[msg MSG_017]
Parece que las cosas van bien aquボ. Deberボa regresar...

[msg MSG_018]
Parece que las cosas van bien aquボ. Tal vez deberボa ir a ver a los demホs...

[sel SEL_019 top]
Akechi y Elizabeth
y Yusuke
Morgana y Futaba

