[msg MSG_000 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 0 3 1][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19117][f 6 1 2 0 0 6]斡Mira, ah胤 est茨n![n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0]斡Aj茨! 斡Finalmente, alcanzamos a la[n]manada![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Herb胤voro Malhumorado]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 42 12 0 3][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Oye, esos humanos han vuelto... 夷Nos[n]siguieron?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Herb胤voro Testarudo]]
[f 0 5 65278][f 2 1][f 4 6 93 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]夷En serio? 斡Pens姻 que hab胤amos bloqueado[n]el camino![n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 2 0 1][f 3 1 1 0 0 23052]斡Je, je, je! 斡Como si fu姻ramos a rendirnos[n]por un obst茨culo tan peque隠o![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Herb胤voro T胤mido]]
[f 0 5 65278][f 2 1][f 4 6 90 12 0 6][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Pero... 夷Por qu姻 nos est茨n siguiendo?[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Herb胤voro Malhumorado]]
[f 0 5 65278][f 2 1][f 4 6 42 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]S胤, ya no tenemos nada que ver ustedes.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Herb胤voro Inquieto]]
[f 0 5 65278][f 2 1][f 4 6 47 0 0 0][f 3 1 1 0 0 0]Ignoremos a los humanos y sigamos[n]adelante. 夷A qui姻n les importan? Mientras[n]podamos llegar al para胤so...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 7 4 0 1][f 3 1 1 0 0 7036][f 6 1 2 0 0 6]斡Eh, vuelvan aqu胤, desgraciados![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 3 1 0 1][f 6 1 25 0 0 0][f 4 6 34 1 0 3][f 3 1 1 0 0 0]...[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0]夷Est茨s bien con esto? Sigues reprimiendo[n]c吋mo te sientes realmente...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]夷Realmente est茨s satisfecho siendo el[n]tipo de persona que abandona a sus[n]amigos?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Yosukesaurio]]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 34021][f 6 1 2 0 0 6]斡N-no puedo evitarlo! 斡Esto es lo que[n]todos votaron![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 0 1 0][f 3 1 1 0 0 0]Es la ley de la manada... 斡Si me opongo,[n]ser姻 el siguiente en ser expulsado![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 34 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Solo... 斡D姻jenme en paz![n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 3 3 2 0][f 4 6 5 6 0 4][f 3 1 1 0 0 0]Ah胤 van otra vez.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 6 1 3 0 0 1]斡夷Otra vez?! 斡Ser茨 mejor que los sigamos![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 4 0 0][f 4 6 9 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Yosuke, 夷qu姻 te ha emocionado tanto?[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 10 0 0][f 3 1 1 0 0 3061][f 6 1 2 0 0 0]斡夷Eh?![n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Makoto]]
[f 0 5 65278][f 2 1][f 4 6 25 12 0 0][f 3 1 1 0 0 0]Cierto, parece que te involucras demasiado[n]cuando se trata de Yosukesaurio...[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Uh... Cierto. Supongo que me estaba[n]enfadando un poco con 姻l all茨 atr茨s.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Es como si... pudiera entender c吋mo se[n]siente.[n][f 1 3 65535][f 1 1][e]

[sel SEL_018 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 20 1 0 0]夷Porque te pareces a 姻l?[f 2 7 1 20 0 32][e]
[f 0 5 65278][f 2 1]斡夷Por qu姻?![f 2 7 1 20 0 32][e]

[msg MSG_019 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3010][f 6 1 2 0 0 3]Bueno, supongo que as胤 puede ser parte[n]de ellos. Me recuerda a c吋mo sol胤a[n]ser yo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3009]Bueno, no es algo demasiado interesante[n]ni nada por el estilo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Al crecer, tuve que mudarme mucho, y[n]los estudiantes nuevos suelen sentirse[n]aislados cuando llegan a una nueva[n]escuela.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0]Entiendo a lo que te refieres. Todos[n]los grupos de amigos establecidos, y[n]luego simplemente apareces t雨...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 4 2 0][f 3 1 1 0 0 3011]Por eso simplemente me re胤a o iba con[n]lo que los dem茨s dec胤an, todo para no[n]sentirme aislado...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Pero termin姻 ocultando c吋mo me sent胤a[n]realmente. Incluso cuando no estaba[n]de acuerdo con lo que dec胤an, simplemente[n]me lo guardaba.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Si no hubiera hecho eso, 夷ser胤a el raro,[n]verdad?[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 4 99 0][f 3 1 1 0 0 0][f 3 1 6 0 0 500]S姻 lo dif胤cil que es sentirse solo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Puede haber un mont吋n de personas a tu[n]alrededor, pero aun as胤 sientes que[n]destacas como un pulgar dolorido.[n]Puede ser aterrador.[n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [P3 Fem Protag]]
[f 0 5 65278][f 2 1][f 4 6 19 6 3 6][f 1 5][f 6 1 28 0 0 0][n][f 3 1 1 0 0 19010]Es dif胤cil estar solo...[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 5 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Cuando la familia de Yosuke lleg吋 por[n]primera vez a Yasoinaba, fueron juzgados[n]debido a su negocio...[n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0]S胤, no importaba a d吋nde fuera, siempre[n]era lo mismo...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Constantemente evaluaba las reacciones[n]de las personas para ver si les ca胤a[n]bien... Todas mis relaciones se[n]sent胤an falsas.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Eso fue hasta que los conoc胤.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 8 0 0 0][f 3 1 1 0 0 0]Yosuke...[n][f 1 3 65535][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 2 0 0][f 3 1 1 0 0 3030]Cuando empec姻 a pasar tiempo con ellos,[n]ocultar mi personalidad a su alrededor[n]me hac胤a sentir como si estuviera[n]actuando como un tonto.[n][f 1 3 65535][f 1 1][e]

[msg MSG_030 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 4 4 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 0]Espera, 夷realmente nos est茨s dando un[n]cumplido?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Bueno, s胤. No importa lo que dijeran[n]los dem茨s, ustedes no me juzgaron,[n]夷recuerdan?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 0]Hablamos sobre nuestros verdaderos[n]sentimientos, y me detienen cuando estoy[n]a punto de hacer algo mal.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Conocer a personas as胤, tener amigos[n]as胤, me ha cambiado la vida.[n][f 1 3 65535][f 1 1][e]

[msg MSG_032 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 2 0 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 1029]Je... Ese es el mayor cumplido que podr胤a darnos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_033 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 6 10 100 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6][f 3 1 6 0 0 500]No puede ser... 斡Yosuke realmente est茨[n]siendo sincero con nosotros![n][f 1 3 65535][f 1 1][e]

[msg MSG_034 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 0 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Oh, vamos! 夷Qu姻 tiene de malo que por[n]una vez me abra y diga lo que siento?[n][f 1 3 65535][f 1 1][e]

[msg MSG_035 [Teddie]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 9 6 0 0][f 3 1 1 0 0 9040]Me has conmovido tanto que apenas puedo[n]soportarlo, Yosuke...[n][f 1 3 65535][f 1 1][e]

[msg MSG_036 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]斡Argh! 斡Ok, suficiente! 斡Me estoy[n]avergonzado demasiado![n][f 1 3 65535][f 1 1][e]

[msg MSG_037 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 5 12 0 0][f 3 1 1 0 0 0]Gracias por compartir tus sentimientos[n]con nosotros, Yosuke.[n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 3 12 0 0][f 3 1 1 0 0 3003][f 6 1 2 0 0 6]U-uhh... 斡Bueno, de todos modos![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]斡Quiero decirle a Yosukesaurio y a los[n]dem茨s dinosaurios lo que pienso![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Si realmente son compa隠eros, necesitan[n]dejar de preocuparse por las reacciones[n]de los dem茨s y ser honestos entre[n]ellos.[n][f 1 3 65535][f 1 1][e]

[msg MSG_039 [P4 Hero]]
[f 0 5 65278][f 2 1][f 4 6 1 0 1 0][f 1 5][f 6 1 14 0 0 0][n][f 3 1 1 0 0 0]S胤, los encontraremos y les diremos exactamente eso.[n][f 1 3 65535][f 1 1][e]

[msg MSG_040 [Haru]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 27 2 0 1][f 3 1 1 0 0 27050]Todos comparten un v胤nculo tan fuerte...[n]Es maravilloso presenciarlo.[n][f 1 3 65535][f 1 1][e]

[msg MSG_041 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 4][f 3 1 1 0 0 0][f 6 1 2 0 0 4]M茨s nos vale mejorar tambi姻n, 夷verdad,[n]Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_042 top]
[f 0 5 65278][f 2 1][f 4 6 20 1 0 0]Somos tan cercanos como ellos.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]Vamos a trabajar juntos.[f 2 7 1 20 2 32][e]

[msg MSG_043 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 2 0 1][f 3 1 1 0 0 23067][f 6 1 2 0 0 6]As胤 es. 斡Nuestros lazos son fuertes como[n]el acero![n][f 1 3 65535][f 1 1][e]

[msg MSG_044 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 21069][f 6 1 2 0 0 6]斡Claro que s胤! 斡Nada es imposible para[n]los Ladrones Fantasma![n][f 1 3 65535][f 1 1][e]

[msg MSG_045 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 26 1 100 3][f 4 6 3 2 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Bueno, entonces, 斡pong茨monos en marcha[n]antes de perderlos![n][f 1 3 65535][f 1 1][e]

[msg MSG_046 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 26 2 100 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Haremos nuestro mejor esfuerzo para[n]guiarlos, 斡as胤 que no se rindan![n][f 1 3 65535][f 1 1][e]

