[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 8 1 1][f 3 1 1 0 0 1][f 6 1 2 0 0 4]Hey, did that statue just wobble?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 2]Yes, I saw it too. That's odd, though...[n]How could such a gentle breeze move[n]a statue of that size?[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kamoshidaman]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 32 4 1 1][f 3 1 1 0 0 3][f 6 1 2 0 0 6]What are you muttering about? I hope[n]you're prepared for your penance,[n]criminals![n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 20 0 1 3][f 4 6 23 12 1 6][f 3 1 1 0 0 4][f 6 1 2 0 0 6]Here he comes, Joker![n][f 1 3 65535][f 1 1][e]

