[msg MSG_000 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 1][f 3 1 1 0 0 22109]Whew... Looks like we're managing[n]to make some progress.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Don't go lookin' down on the Phantom[n]Thieves! I don't wear out THAT easily![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 6 0 4][f 3 1 1 0 0 24094][f 6 1 2 0 0 9]Please, dial back the testosterone...[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 3]Just looking at him's starting to tire me[n]out...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 1 4][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Are you all right, Panther? Sheesh, why'd[n]you have to go and upset her like that!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 10 0 0][f 3 1 1 0 0 21054][f 6 1 2 0 0 0]Wha―!? That's such bullshit![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 2 1 1][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Shh! Someone's coming.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Let's hide until they pass by.[n][f 1 3 65535][f 1 1][e]

[msg MSG_007]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 8 32 3][f 3 1 1 0 0 0]I can hear the voices of nearby[n]citizens...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Brazen man's voice]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Did you hear? Seems like yet another[n]criminal's slipped into the city, besides[n]those thieves.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Weary woman's voice]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]That's so scary... What kind of criminal?[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Brazen man's voice]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]I don't know the details...[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Weary woman's voice]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]Well, if they're defying Kamoshidaman,[n]they've gotta be criminals... right?[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Brazen man's voice]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]That's what Kamoshidaman's saying,[n]so I guess they have to be.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]I mean, even if I said I didn't think so,[n]that'd just be painting a target on[n]my own back.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Weary woman's voice]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 9 0 0 1]True―I'm pretty sure everyone else[n]feels the same, anyway...[n][f 1 3 65535][f 1 1][e]

[msg MSG_014]
[f 0 5 65278][f 2 1][f 4 6 20 2 32 3][f 3 1 1 0 0 0]The chatting voices grow fainter[n]and trail off...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Akechi]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 28 0 0 1][f 3 1 1 0 0 0]They're gone...[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 0 0][f 3 1 1 0 0 21022][f 6 1 2 0 0 2]Dude, what the hell!? You can get[n]called a criminal just cuz Kamoshidaman[n]said so!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]They were all behind this punishment[n]thing, but they're not even thinkin' for[n]themselves!  [n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0]"What Kamoshidaman is saying..."[n]"Everyone else feels the same..."[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It seems as if they're just going along[n]with whatever those around them[n]are doing.[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 22 12 0 0][f 3 1 1 0 0 22112]More importantly, it's clearer that[n]Kamoshidaman's not like the real[n]Kamoshida.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]It didn't seem like those two people[n]were exactly superfans of his, either.[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 1][f 3 1 1 0 0 0]Yeah, it seems to me like they're just[n]supporting him because he's in[n]a position of power...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Some kind of hero HE is! Might as well[n]be that emperor who paraded around[n]in his "new" clothes![n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 28 12 0 0][f 3 1 1 0 0 28015]They mentioned something else that[n]I found curious...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Do you remember how they said[n]someone else slipped into the city[n]besides ourselves?  [n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0][f 6 1 2 0 0 4]Who could that be?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 4 1 1][f 3 1 1 0 0 0]They didn't seem to be talking about[n]Queen or Noir...[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 20 1 0 3][f 4 6 21 12 0 1][f 3 1 1 0 0 0]Well, whoever they are, we just gotta[n]keep moving for now. Right, Joker?[n][f 1 3 65535][f 1 1][e]

[sel SEL_023 top]
[f 0 5 65278][f 2 1]Let's get going.[f 2 7 1 20 2 32][e]
[f 0 5 65278][f 2 1]I'm curious about who it is too.[f 2 7 1 20 8 32][e]

[msg MSG_024 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 23069]Yeah, I'm really worried about those[n]two. Let's hurry up and find them![n][f 1 3 65535][f 1 1][e]

[msg MSG_025 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 4][f 3 1 1 0 0 23078]I can understand how you feel, but we[n]need to prioritize rescuing Queen and[n]Noir first.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 21 4 1 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]Hell yeah! Let's blast our way through![n][f 1 3 65535][f 1 1][e]

[msg MSG_027 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 22 4 0 3][f 3 1 1 0 0 22035]Hey, don't go rushing ahead by[n]yourself![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 22 0 0 0][f 3 1 1 0 0 0]...Then again, I guess all his energy[n]is doing the heavy lifting for us.[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 24 12 0 1][f 3 1 1 0 0 0][f 6 1 2 0 0 7]Ha―we oughtn't fall behind him, then.[n]Let's move out.[n][f 1 3 65535][f 1 1][e]

