[msg MSG_000 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 23 1 0 1][f 4 6 65 12 1 3][f 3 1 1 0 0 1][f 6 1 2 0 0 0]What is it, Morgana!? You find some[n]kinda clue?[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 6 0 0][f 3 1 1 0 0 2][f 6 1 2 0 0 3]Take a look at this door.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 0 0 6][f 3 1 1 0 0 3][f 6 1 2 0 0 4]What about it?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Morgana]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 3][f 4 6 66 1 0 3][f 4 6 23 6 0 1][f 3 1 1 0 0 4]This door...[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 5]So it's no use?[n][f 1 3 65535][f 1 1][e]

[msg MSG_005]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]This appears to be the exit, but there are[n]multiple thick chains on the door...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 6 1 3 0 0 2][f 3 1 1 0 0 0]The chains are held on with four[n]different padlocks...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Ryuji]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 0][f 4 6 65 10 0 3][f 3 1 1 0 0 6]The hell is this!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 0 0 1][f 3 1 1 0 0 7]Such redundant security...[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Ann]]
[f 0 5 65278][f 2 1][f 6 1 2 0 0 6][f 4 6 66 0 1 0][f 3 1 1 0 0 8]Wait, doesn't this mean we're trapped[n]in here!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 10 0 6][f 3 1 1 0 0 9][f 6 1 1 0 0 1][f 6 1 2 0 0 1]Abduction and confinement confirmed![n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 23 1 0 1][f 4 6 65 8 1 3][f 3 1 1 0 0 10][f 6 1 2 0 0 10]Hey, Morgana! Can't you pick them[n]open?[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 11]I gave it a shot, but it was useless.[n]The keyholes aren't shaped for[n]any ordinary keys.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011_5 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 18 1 0][f 3 1 1 0 0 12]If we did something about them, I bet[n]we could get out of here...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 64 1 0 3][f 4 6 66 12 0 1][f 3 1 1 0 0 13]Yeah... Hey, [f 6 1 30 0 0 0], isn't there[n]anything we can do?[n][f 1 3 65535][f 1 1][e]

[sel SEL_013 top]
[f 0 5 65278][f 2 1]Let's force it open.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]This is hopeless.[f 2 7 1 64 0 32][e]
[f 0 5 65278][f 2 1]Could we even find the keys?[f 2 7 1 64 6 32][e]

[msg MSG_014 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 6 0 1][f 3 1 1 0 0 14][f 6 1 2 0 0 3]*gasp* *pant* Dammit... this sucks![n]Won't budge... one bit![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 4][f 3 1 1 0 0 15]Hm, so brute force won't work. Could[n]we perhaps look for the keys?[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 10 0 0][f 3 1 1 0 0 16][f 6 1 2 0 0 6]You're giving up already!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 6 68 12 0 4][f 3 1 1 0 0 17]Accepting defeat with grace can be[n]admirable, but let's not do that just[n]yet. Shall we find the keys?[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Morgana]]
[f 0 5 65278][f 2 1][f 4 7 11 0 0][f 4 6 23 12 0 1][f 3 1 1 0 0 18]I already looked, but couldn't find[n]them, or anything else―not even[n]a mouse...[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Morgana]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 19][f 6 1 2 0 0 4][f 6 1 3 0 0 1]While we're at it, how'd it go on your[n]end? Any sign of Makoto or Haru?[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 2 1 0][f 3 1 1 0 0 20][f 6 1 2 0 0 10]Not at all. We looked everywhere, too...[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Ryuji]]
[f 0 5 65278][f 2 1][f 4 6 65 12 0 6][f 3 1 1 0 0 21]We didn't see a single clue.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 6 0 0][f 3 1 1 0 0 22][f 6 1 2 0 0 3]Since the exit's chained up, it's[n]doubtful they made it outside.[n]What to do...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Ann]]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 66 12 0 0][f 3 1 1 0 0 23][f 6 1 2 0 0 5]Hey, why don't we try heading back to[n]where we first woke up?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24]Maybe they've turned up there since we[n]started poking around out here.[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Morgana]]
[f 0 5 65278][f 2 1][f 4 6 23 12 0 0][f 3 1 1 0 0 25]Yeah, Lady Ann has a point―and there's[n]no use worrying about it out here...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 26]All right, let's head back![n][f 1 3 65535][f 1 1][e]

