[msg MSG_000 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 12 0 3][f 3 1 1 0 0 64006]Over here is the shop... After you,[n]please.[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 1][f 3 1 1 0 0 0]Ah, this is quite impressive. There is[n]an abundance of space...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I believe that I can prepare a number of[n]items here that will be useful to you.[n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Ann]]
[f 0 5 65278][f 2 1][f 4 6 66 12 0 0][f 3 1 1 0 0 22047][f 6 1 2 0 0 4]Ooh, like what? Maybe some new[n]sweets?[n][f 1 3 65535][f 1 1][e]

[msg MSG_003 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 6 0 0][f 3 1 1 0 0 0]Well... I'm afraid I don't know all the[n]details just yet. I do apologize for that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 4]I must first prepare for the grand[n]opening, so won't you allow me[n]some time to do so?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I vow to provide an assortment of goods[n]that will make your hearts dance[n]in rapture.[n][f 1 3 65535][f 1 1][e]

[sel SEL_004 top]
[f 0 5 65278][f 2 1][f 4 7 13 0 0][f 4 6 64 1 0 0]I can't wait to see that.[f 2 7 1 64 2 32][e]
[f 0 5 65278][f 2 1]Are you sure you can do that?[f 2 7 1 64 4 32][e]
[f 0 5 65278][f 2 1]Give us wholesale prices.[f 2 7 1 64 0 32][e]

[msg MSG_005 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 56097][f 6 1 2 0 0 6]Please leave it to me! I will make sure[n]to surpass your every expectation![n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 56059][f 6 1 2 0 0 6]Yes―I swear upon the Velvet Room[n]name that I will fully satisfy your needs![n][f 1 3 65535][f 1 1][e]

[msg MSG_007 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 0 0 0][f 3 1 1 0 0 56018][f 6 1 2 0 0 4]Wholesale... prices?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...Ah! I understand. There's no need[n]to worry about that.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 6]All the wares I shall sell you will be[n]entirely whole, with prices to match.[n]I have no interest in half-measures![n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Akechi]]
[f 0 5 65278][f 2 1][f 4 6 72 0 0 0][f 3 1 1 0 0 0]You seem to be having fun, Theodore.[n]It's as if you're a veteran shopkeeper.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 0][f 3 1 1 0 0 56041]Veteran... What a wonderful ring that[n]term has![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've merely come to realize that I don't[n]mind doing things of this nature.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 74 1 3 1][f 3 1 1 0 0 0]By the way―*munch munch*[n]My guests―*munch munch*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]They seem to be lost too... *munch*[n]My, this foodstuff called popcorn...[n]*munch* *munch* *munch*[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 9]Sister! It's ill-mannered to eat[n]and speak at the same time...[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Elizabeth]]
[f 0 5 65278][f 2 1][f 4 6 74 1 3 0][f 3 1 1 0 0 0]Theo, you should―*munch munch*[n]―try shoving this much in your mouth[n]at once as well... *munch munch*[n][f 1 3 65535][f 1 1][e]

[msg MSG_013 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 10 0 0][f 3 1 1 0 0 56050][f 6 1 2 0 0 0]Are you attempting to desiccate me!?[n]This is just like that confounded[n]soybean powder all over again![n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]U-Uhm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Futaba]]
[f 0 5 65278][f 2 1][f 4 6 70 12 1 6][f 3 1 1 0 0 0][f 6 1 2 0 0 6]I-It's okay![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I freaked out over the Blue Brigade at[n]first when I saw 'em too, but now I think[n]these guys are ultimately harmless.[n][f 1 3 65535][f 1 1][e]

[msg MSG_016 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 4 2 0][f 3 1 1 0 0 61066]...O-Okay.[n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Theodore]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 76 0 2 1][f 3 1 1 0 0 0]*munch munch* My, this is quite...[n]*munch munch*[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hmm... If I were to change the[n]seasonings―*munch* perhaps[n]I could create new flavors...[n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 12 0 0][f 3 1 1 0 0 61018][f 6 1 2 0 0 4]Huh? New flavors?[n][f 1 3 65535][f 1 1][e]

[msg MSG_019 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 12 0 0][f 3 1 1 0 0 0]Oh? Does that interest you?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Then, I shall fully devote myself[n]to the creation of new varieties[n]of popcorn.[n][f 1 3 65535][f 1 1][e]

[msg MSG_020 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 6 0 0][f 3 1 1 0 0 0][f 6 1 2 0 0 10]Um... Nagi-san?[n][f 1 3 65535][f 1 1][e]

[msg MSG_021 [Nagi]]
[f 0 5 65278][f 2 1][f 4 6 84 2 0 1][f 3 1 1 0 0 64032]*chuckle* It's fine by me―especially if[n]it would be of assistance to everyone.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Also, I could not say no after seeing[n]such a hopeful look on your face,[n]Hikari-san.[n][f 1 3 65535][f 1 1][e]

[msg MSG_022 [Hikari]]
[f 0 5 65278][f 2 1][f 4 6 81 0 0 0][f 3 1 1 0 0 0]Huh? Um, mmhm...[n][f 1 3 65535][f 1 1][e]

[msg MSG_023 [Yusuke]]
[f 0 5 65278][f 2 1][f 4 7 0 0 0][f 4 6 76 1 0 1][f 4 6 68 2 0 3][f 3 1 1 0 0 0]We'll leave it to you, then. I look[n]forward to the new varieties of[n]popcorn as well... *chuckle*[n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Theodore]]
[f 0 5 65278][f 2 1][f 4 6 76 2 0 0][f 3 1 1 0 0 56062]Of course! Now, please wait just a short[n]while longer until my preparations[n]here are completed.[n][f 1 3 65535][f 1 1][e]

